var Localization_commonAppDict_el_GR = {
	//"stringId" : "localString"
	"AppleCarPlay" : "Apple CarPlay",
	"ApplicationsMenu" : "Μενού εφαρμογών",
	"Auto" : "Αυτ.",
	"Back" : "Πίσω",
	"BrightnessTab" : "Φωτειν.",
	"Cancel" : "Ακύρωση",
	"ColorTab" : "Χρώμα",
	"Connect" : "Σύνδεση",
	"Contacts" : "Επαφές",
	"ContrastTab" : "Αντίθεση",
	"DateFormat" : "{day} {month}",
	"DevicesTab" : "Συσκευέ",
	"DisplayTab" : "Οθόνη",
	"Download" : "Λήψη",
	"FullMonthNameApr" : "Απρίλιος",
	"FullMonthNameAug" : "Αύγουστος",
	"FullMonthNameDec" : "Δεκέμβριος",
	"FullMonthNameFeb" : "Φεβρουάριος",
	"FullMonthNameJan" : "Ιανουάριος",
	"FullMonthNameJul" : "Ιούλιος",
	"FullMonthNameJun" : "Ιούνιος",
	"FullMonthNameMar" : "Μάρτιος",
	"FullMonthNameMay" : "Μάιος",
	"FullMonthNameNov" : "Νοέμβριος",
	"FullMonthNameOct" : "Οκτώβριος",
	"FullMonthNameSep" : "Σεπτέμβριος",
	"HUDTab" : "AD-Disp",
	"LanguageChangeNotice" : "Αλλαγή γλωσσών. Περιμένετε",
	"Loading" : "Γίνεται φόρτωση",
	"MemoryFull" : "Πλήρης μνήμη",
	"MirrorLink" : "MirrorLink",
	"MonthNameApr" : "Απρ",
	"MonthNameAug" : "Αύγ",
	"MonthNameDec" : "Δεκ",
	"MonthNameFeb" : "Φεβ",
	"MonthNameJan" : "Ιαν",
	"MonthNameJul" : "Ιούλ",
	"MonthNameJun" : "Ιούν",
	"MonthNameMar" : "Μάρ",
	"MonthNameMay" : "Μάι",
	"MonthNameNov" : "Νοέ",
	"MonthNameOct" : "Οκτ",
	"MonthNameSep" : "Σεπ",
	"No" : "Όχι",
	"Off" : "Ανενεργό",
	"Ok" : "OK",
	"On" : "Ενερ.",
	"Quit" : "Έξοδος",
	"Remove" : "Αφαίρεση",
	"ResetTab" : "Επαναφ.",
	"Retry" : "Πάλι",
	"SbnVoiceLoading" : "Φόρτωση Φωνητ. Αναγνώρ…",
	"SbnVoiceNotSupported" : "Μη υποστήρ.φωνητ. Λειτουργ.",
	"SbnVoiceRecognition" : "Φωνητική αναγνώριση",
	"SbnWaitForTone" : "Αναμονή για τόνο",
	"Setup" : "Ρύθμιση",
	"Siri" : "Siri",
	"SoundTab" : "Ήχος",
	"SpacebarText" : "διάστημα",
	"SystemTab" : "Σύστημα",
	"TimeLabelAm" : "ΠΜ",
	"TimeLabelPm" : "ΜΜ",
	"TintTab" : "Τόνος",
	"TooltipFavorites" : "Αγαπημένα",
	"Tooltip_IcnUmpAddCall" : "Προσθ. κλήσης",
	"Tooltip_IcnUmpAddContact" : "Προσθ. επαφής",
	"Tooltip_IcnUmpAddSong" : "Προσθήκη τραγουδιού",
	"Tooltip_IcnUmpAmPm" : "Εναλλαγή ΠΜ/ΜΜ",
	"Tooltip_IcnUmpApps" : "Εφαρμογές",
	"Tooltip_IcnUmpAutoMem" : "Αυτόματη μνήμη",
	"Tooltip_IcnUmpBack" : "Πίσω",
	"Tooltip_IcnUmpBack15s" : "Πίσω 15 δευτερόλεπτα",
	"Tooltip_IcnUmpBack30s" : "Πίσω 30 δευτερόλεπτα",
	"Tooltip_IcnUmpBargeIn" : "Μιλήστε τώρα",
	"Tooltip_IcnUmpBookmark" : "Σελιδοδείκτης",
	"Tooltip_IcnUmpBookmark_Sel" : "Σελιδοδείκτης",
	"Tooltip_IcnUmpBookmark_Unsel" : "Σελιδοδείκτης",
	"Tooltip_IcnUmpCall" : "Κλήση",
	"Tooltip_IcnUmpCamAngle" : "Γωνία κάμερας",
	"Tooltip_IcnUmpCloseUmp" : "Απόκρυψη κουμπιών",
	"Tooltip_IcnUmpCommMenu" : "Επικοινωνία",
	"Tooltip_IcnUmpConnectionManager" : "Διαχείριση συνδέσεων",
	"Tooltip_IcnUmpContinueListening" : "Συνέχιση ακρόασης",
	"Tooltip_IcnUmpCurrentList" : "Λίστα σταθμών",
	"Tooltip_IcnUmpDelete" : "Διαγραφή",
	"Tooltip_IcnUmpDialpad" : "Πληκτρολόγιο αρ. κλήσης",
	"Tooltip_IcnUmpEject" : "Εξαγωγή",
	"Tooltip_IcnUmpEntMenu" : "Ψυχαγωγία",
	"Tooltip_IcnUmpEqualizer" : "Ρυθμίσεις ήχου",
	"Tooltip_IcnUmpFavorite_Favorite" : "Αφαίρεση από Αγαπημένα",
	"Tooltip_IcnUmpFavorite_Unfavorite" : "Προσθήκη στα Αγαπημένα",
	"Tooltip_IcnUmpFolder_Up" : "Μενού πάνω",
	"Tooltip_IcnUmpFwd15s" : "Εμπρός 15 δευτερόλεπτα",
	"Tooltip_IcnUmpFwd30s" : "30 δευτερόλεπτα εμπρός",
	"Tooltip_IcnUmpGenre" : "Είδος",
	"Tooltip_IcnUmpHD_Sel" : "HD μη ενεργό",
	"Tooltip_IcnUmpHD_Unsel" : "HD ενεργό",
	"Tooltip_IcnUmpHangup" : "Τερμ. κλήσης",
	"Tooltip_IcnUmpItunesTag_Tagged" : "Αφαιρέστε ετικέτα για iTunes",
	"Tooltip_IcnUmpItunesTag_Untagged" : "Ετικέτα",
	"Tooltip_IcnUmpLock_Locked" : "Ξεκλείδωμα",
	"Tooltip_IcnUmpLock_Unlocked" : "Κλείδωμα",
	"Tooltip_IcnUmpMap" : "Χάρτης",
	"Tooltip_IcnUmpMergecall" : "Συγχώνευση κλήσεων",
	"Tooltip_IcnUmpMic" : "Ηχητικό μήνυμα",
	"Tooltip_IcnUmpMinus" : "Μείωση",
	"Tooltip_IcnUmpMore" : "Περισσότερα παρόμοια",
	"Tooltip_IcnUmpMuteUnmute_Mute" : "Σίγαση",
	"Tooltip_IcnUmpMuteUnmute_Unmute" : "Αναίρεση σίγασης",
	"Tooltip_IcnUmpNextAudio" : "Επόμενο",
	"Tooltip_IcnUmpNowPlaying" : "Αναπαραγωγή τώρα",
	"Tooltip_IcnUmpPhoneRoute_Handset" : "Μεταφορά σε συσκευή χειρός",
	"Tooltip_IcnUmpPhoneRoute_Vehicle" : "Μεταφορά σε όχημα",
	"Tooltip_IcnUmpPlayOrPause" : "Αναπαραγωγή/Παύση",
	"Tooltip_IcnUmpPlayPause_Pause" : "Παύση",
	"Tooltip_IcnUmpPlayPause_Play" : "Αναπαραγωγή",
	"Tooltip_IcnUmpPlayPause_Stop" : "Διακοπή",
	"Tooltip_IcnUmpPlus" : "Αύξηση",
	"Tooltip_IcnUmpPreviousAudio" : "Προηγούμενο",
	"Tooltip_IcnUmpRepeat_List" : "Επανάληψη",
	"Tooltip_IcnUmpRepeat_None" : "Επανάληψη",
	"Tooltip_IcnUmpRepeat_Song" : "Επανάληψη",
	"Tooltip_IcnUmpReply" : "Απάν.",
	"Tooltip_IcnUmpReplyToAll" : "Απάντηση σε όλους",
	"Tooltip_IcnUmpReset" : "Επαναφορά",
	"Tooltip_IcnUmpRestartAlert" : "Επανεκκίνηση ειδοποίησης",
	"Tooltip_IcnUmpScan_Sel" : "Διακοπή σάρωσης",
	"Tooltip_IcnUmpScan_Unsel" : "Σάρωση",
	"Tooltip_IcnUmpSettings" : "Ρυθμίσεις",
	"Tooltip_IcnUmpShuffle_Folder" : "Τυχαία σειρά",
	"Tooltip_IcnUmpShuffle_Off" : "Τυχαία σειρά",
	"Tooltip_IcnUmpShuffle_On" : "Τυχαία σειρά",
	"Tooltip_IcnUmpStation_Create" : "Δημιουργία Σταθμού",
	"Tooltip_IcnUmpSubtitles" : "Υπότιτλοι",
	"Tooltip_IcnUmpSwapCalls_01" : "Αλλαγή κλήσεων",
	"Tooltip_IcnUmpSwapCalls_02" : "Αλλαγή κλήσεων",
	"Tooltip_IcnUmpSwitchView" : "Εναλλαγή προβολής",
	"Tooltip_IcnUmpSwitchView_1" : "Εναλλαγή προβολής",
	"Tooltip_IcnUmpSwitchView_2" : "Εναλλαγή προβολής",
	"Tooltip_IcnUmpSwitchView_3" : "Εναλλαγή προβολής",
	"Tooltip_IcnUmpThumbsDown_Sel" : "Αποδοκιμασία",
	"Tooltip_IcnUmpThumbsDown_UnSel" : "Αποδοκιμασία",
	"Tooltip_IcnUmpThumbsUp_Sel" : "Επιδοκιμασία",
	"Tooltip_IcnUmpThumbsUp_UnSel" : "Επιδοκιμασία",
	"Tooltip_IcnUmpTopList" : "Βασικός Φάκελος",
	"Tooltip_IcnUmpTrafficAlert" : "Ειδοποίηση κίνησης (TA)",
	"Tooltip_IcnUmpTrafficAlert_Sel" : "Ειδοποίηση κίνησης (TA)",
	"Tooltip_IcnUmpTrafficAlert_Unsel" : "Ειδοποίηση κίνησης (TA)",
	"Tooltip_IcnUmpTune" : "Συντονισμός",
	"Tooltip_IcnUmpTuneScan" : "Σάρωση συχνοτήτων",
	"Tooltip_IcnUmpVideoSet" : "Ρυθμίσεις βίντεο",
	"VehicleTab" : "Όχημα",
	"VolumeTab" : "Ένταση",
	"VrExample_Address" : "Address  (Navigation route)",
	"VrExample_CallTo" : "Call <Contact Name> ",
	"VrExample_Callback" : "Callback  (return call)",
	"VrExample_ChannelNumber" : "Channel <number>",
	"VrExample_DialNumber" : "Dial <Phone Number>",
	"VrExample_FindNearestPOI" : "Find nearest <POI category / Brand>",
	"VrExample_GoToAudioSrc" : "Go to (FM,AM, Bluetooth, etc..)",
	"VrExample_Help" : "Help",
	"VrExample_PlayArtist" : "Play Artist <artist name>",
	"VrExample_Redial" : "Redial  (repeat last call)",
	"VrExample_TakeMeHome" : "Take Me Home",
	"VrExample_TextMsg" : "Text Message",
	"VrExample_Title" : "Example Commands",
	"VrExample_TuneTo" : "Tune to <FM/AM> <Frequency>",
	"VuiHelpDefaultTitle" : "Στις διαθ. εντολές περ. οι εξής",
	"Yes" : "Ναι",
	"delete" : "Διαγραφή",
	"distanceUnitsKms" : "km",
	"distanceUnitsMiles" : "mi",
	"muteOff" : "Σίγαση ΑΝΕΝΕΡΓΗ",
	"muteOn" : "Σίγαση ΕΝΕΡΓΗ",
	"shortRepnHours" : "ώ.",
	"shortRepnMins" : "λεπ.",
	"shortRepnSecs" : "δευτ.",
	"tempUnitsCelsius" : "C",
	"tempUnitsFahrenheit" : "F",
	"volUnitsGallons" : "γαλόνια",
	"volUnitsLiters" : "λίτρα",
};

framework.registerAppDictLoaded("common", "el_GR");