var Localization_pandoraAppDict_ar_SA = {
	//"stringId" : "localString"
	"AZ" : "أ-ي",
	"AddActiveStation" : " {activestation} إضافة",
	"AddBookmark_Alert" : "إضافة إشارة مرجعية",
	"AddGenreStation" : "إضافة محطة: {genreStation}",
	"AddStation" : "إضافة محطة",
	"AddStationOption" : "إنشاء محطة جديدة:",
	"AddStationOptionButton3" : "الفنان",
	"AddingFavorites" : "إضافة محطة إلى المفضلات",
	"AddingStation" : "إضافة محطة",
	"BluetoothAudioLost" : "تم فقدان اتصال Bluetooth",
	"Bookmark" : "خيارات الإشارات المرجعية لتطبيق Pandora",
	"BookmarkAlreadyAdded" : "تمت إضافة إشارة مرجعية مسبقًا",
	"BookmarkArtist" : "وضع علامة مرجعية للفنان",
	"BookmarkSong" : "وضع علامة مرجعية للأغنية",
	"Buffering" : "تخزين مؤقت",
	"ConnectionLost1" : "تم فقد الاتصال",
	"ConnectionLost2" : "تأكد من أن وحدة توصيل البيانات في هاتفك الجوال تعمل على النحو الصحيح.",
	"Date" : "التاريخ",
	"DeleteFavorites" : "إزالة محطة من المفضلات",
	"FavoritesLimitReached" : "الوصول إلى الحد الأقصى ",
	"FromCurrentArtist" : "من الفنان الحالي",
	"FromCurrentSong" : "من الأغنية الحالية",
	"InsufficientConnectivity" : "الاتصال غير كافٍ لفتح تطبيق Pandora.",
	"InsufficientConnectivity_Alert" : "إمكانية الاتصال غير كافية",
	"InvalidLogin1" : "تسجيل دخول غير سارٍ",
	"InvalidLogin2" : "فشلت المصادقة.",
	"LicensingRestriction1" : "موقع غير معتمد لتطبيق Pandora",
	"LicensingRestriction2" : "تطبيق Pandora غير متاح خارج الولايات المتحدة الأمريكية.",
	"LicensingRestrictions_Alert" : "تطبيق Pandora غير معتمد في موقعك الحالي",
	"Loading" : "الرجاء إضافة محطة.",
	"MobileDevice1" : "حدث خطأ في الهاتف الجوال",
	"MobileDevice2" : "عند القيام بذلك، تأكد من أن جهازك المحمول يعمل بشكل صحيح.",
	"NoBookmark_Alert" : "لا يمكن إضافة علامة",
	"NoCurrentStation" : "لا توجد محطة قيد التشغيل حاليًا",
	"NoDeviceConnected" : "لا يوجد جهاز متصل",
	"NoFavoritesStationsCreated" : "لم يتم إنشاء أي محطات مفضلة.",
	"NoPandora1" : "تطبيق Pandora غير موجود",
	"NoPandora2" : "تأكد من أن تطبيق Pandora مثبت على جهازك المحمول.",
	"NoRating_Alert" : "تعذر إضافة تصنيف إبهام لأعلى/لأسفل",
	"NoStationFound1" : "لم يتم العثور على محطة.",
	"NoStationFound2" : "يجب تعيين محطة Pandora واحدة على الأقل أولاً.",
	"Nostationsadded" : "لم تتم إضافة محطات.",
	"NotSupportedVersion1" : "عند القيام بذلك، يُرجى ترقية تطبيق Pandora على جهازك المحمول.",
	"OverLimit" : "ترخيص الموسيقى من Pandora يقلل عدد المسارات التي قد تتخطاها.",
	"Pandora" : "Pandora",
	"PandoraAddEditFavorites" : "إضافة/تعديل مفضلة Pandora ",
	"PandoraDeleteConfirmation" : "هل ترغب بالتأكيد في حذف المفضلة {name}؟",
	"PandoraFavorites" : "مفضلة Pandora",
	"PandoraFavoritesAvailable" : "تم إضافة مفضلة Pandora مسبقًا",
	"PandoraFavoritesConfirm" : "هل ترغب في استبدال مفضلة؟",
	"PandoraFavoritesDelete" : "حدد مفضلة Pandora للحذف",
	"PandoraFavoritesMax" : "لقد وصلت إلى أقصى عدد ممكن من مفضلات Pandora.",
	"PandoraFavoritesMove" : "حدد مفضلة Pandora للنقل",
	"PandoraFavoritesReplace" : "استبدل بـ {activestation}",
	"PandoraFavoritesSelect" : "حدد مفضلة Pandora للاستبدال",
	"PandoraMaintinence" : "عذرًا، خوادم Pandora غير متوفرة حاليًا.",
	"PandoraMoveFavorite" : "النقل",
	"PandoraReplaceButtonText" : "الاستبدال",
	"PandoraSelectPosition" : "حدد الموضع المطلوب",
	"Quit" : "خروج",
	"SBNStationCreationError" : "محطة خطأ الخلق",
	"SBNStationLimitReached" : "تم الوصول إلى الحد الأقصى للمحطات",
	"SelectStation" : "لقد تم حذف هذه المحطة من جهاز آخر على هذا الحساب.",
	"Setup" : "إعداد",
	"SetupBluetoothDeviceNow" : "هل ترغب في إعداد جهاز البلوتوث الآن؟",
	"Shuffle" : "تبديل",
	"ShuffleNotAddedFavorites" : "تعذر إضافة التشغيل العشوائي إلى مفضلات Pandora.",
	"SortBy" : "فرز حسب",
	"SortByAZ" : "فرز حسب: أ-ي",
	"SortByDate" : "فرز حسب: التاريخ",
	"StationCreationError" : "حدث خطأ أثناء إنشاء المحطة",
	"StationLimitReached" : "لقد تم الوصول إلى الحد الأقصى لعدد المحطات.",
	"StationList" : "قائمة المحطة",
	"StationListTab" : "المفضلات",
	"ThumbsDown" : "إبهام إلى لأسفل",
	"ThumbsUp" : "إبهام لأعلى",
	"VrHelp_BookmarkOptions_Help_Left1" : "ضع علامة مرجعية للفنان",
	"VrHelp_BookmarkOptions_Help_Left2" : "ضع علامة مرجعية للأغنية",
	"VrHelp_NowPlaying_Help_Left1" : "تشغيل",
	"VrHelp_NowPlaying_Help_Left2" : "إيقاف مؤقت",
	"VrHelp_NowPlaying_Help_Left3" : "تخطي",
	"VrHelp_NowPlaying_Help_Left4" : "إبهام لأعلى",
	"VrHelp_NowPlaying_Help_Left5" : "إبهام لأسفل",
	"VrHelp_NowPlaying_Help_Right1" : "ضع علامة مرجعية للفنان",
	"VrHelp_NowPlaying_Help_Right2" : "وبدء التشغيل/ والتوقف المؤقت",
	"VrHelp_NowPlaying_Help_Right3" : "تخطي",
	"VrHelp_NowPlaying_Help_Right4" : "تغيير المصدر",
	"VrHelp_SortBy_Help_Left1" : "التاريخ",
	"VrHelp_SortBy_Help_Left2" : "أ إلى ي",
	"entMenu" : "قائمة الترفيه",
	"sbNameId" : "Pandora",
	"sbnBookmarkFailed" : "لم يتمكن من إضافة علامة مرجعية",
	"sbnConnectionError" : "تم فقد الاتصال بالشبكة",
	"sbnConnectivityError" : "الاتصال غير كافٍ",
	"sbnMobileDeviceError" : "حدث خطأ في الهاتف الجوال",
	"sbnOverLimit" : "تخطى الحد الذي تم الوصول إليه",
	"sbnPandoraMaintErr" : "خطأ في خادم Pandora",
	"sbnRatingFailed" : "لم يتمكن من إضافة تصنيف",
	"sbnStationDeleted" : "لا توجد محطة حاليًا",
	"skip_Tooltip" : "تخطي",
};

framework.registerAppDictLoaded("pandora", "ar_SA");