var Localization_pandoraAppDict_ms_MY = {
	//"stringId" : "localString"
	"AZ" : "A-Z",
	"AddActiveStation" : "Tambah  {activestation}",
	"AddBookmark_Alert" : "Menambah Tanda Buku",
	"AddGenreStation" : "Tambah Stesen:{genreStation}",
	"AddStation" : "Tambah Stesen",
	"AddStationOption" : "Cipta Stesen Baharu:",
	"AddStationOptionButton3" : "Artis",
	"AddingFavorites" : "Tambah Stesen kepada Kegemaran",
	"AddingStation" : "Tambah Stesen",
	"BluetoothAudioLost" : "Komunikasi Bluetooth Terputus",
	"Bookmark" : "Pilihan Penanda Buku Pandora",
	"BookmarkAlreadyAdded" : "Penanda Buku Ditambah Sebelum Ini",
	"BookmarkArtist" : "Tandakan Artis",
	"BookmarkSong" : "Tandakan Lagu",
	"Buffering" : "Menimbal",
	"ConnectionLost1" : "Sambungan Terputus",
	"ConnectionLost2" : "Pastikan sambungan data pada peranti mudah alih anda berfungsi dengan betul.",
	"Date" : "Tarikh",
	"DeleteFavorites" : "Keluarkan Stesen dari Kegemaran",
	"FavoritesLimitReached" : "Had Kegemaran Dicapai",
	"FromCurrentArtist" : "Dari Artis Semasa",
	"FromCurrentSong" : "Dari Lagu Semasa",
	"InsufficientConnectivity" : "Sambungan tidak mencukupi untuk membuka Pandora.",
	"InsufficientConnectivity_Alert" : "Sambungan Tidak Mencukupi",
	"InvalidLogin1" : "Log Masuk Tidak Sah",
	"InvalidLogin2" : "Pengesahan gagal",
	"LicensingRestriction1" : "Lokasi Tidak Di sokong",
	"LicensingRestriction2" : "Pandora tidak tersedia di luar Amerika Syarikat.",
	"LicensingRestrictions_Alert" : "Pandora Tidak Disokong di Lokasi Semasa Anda",
	"Loading" : "Sila tambah Stesen.",
	"MobileDevice1" : "Ralat Peranti Mudah Alih",
	"MobileDevice2" : "Apabila selamat untuk berbuat demikian, pastikan peranti mudah alih anda berfungsi dengan baik.",
	"NoBookmark_Alert" : "Gagal tamb. tanda buku",
	"NoCurrentStation" : "Stesen Dikeluarkan",
	"NoDeviceConnected" : "Tiada Peranti Disambungkan",
	"NoFavoritesStationsCreated" : "Tiada stesen kegemaran dicipta.",
	"NoPandora1" : "Pandora Tidak Ditemui",
	"NoPandora2" : "Pastikan aplikasi Pandora dipasang pada peranti mudah alih anda.",
	"NoRating_Alert" : "Tidak dapat menambah Rating 'Thumbs Up/Down'",
	"NoStationFound1" : "Tiada Stesen Ditemui",
	"NoStationFound2" : "Anda mesti menyediakan sekurang-kurangnya satu stesen Pandora terlebih dahulu.",
	"Nostationsadded" : "Tiada stesen ditambah.",
	"NotSupportedVersion1" : "Apabila selamat untuk berbuat demikian, sila naik taraf aplikasi Pandora pada Peranti Mudah Alih anda.",
	"OverLimit" : "Pelesenan muzik Pandora mengehadkan bilangan runut yang boleh anda langkau.",
	"Pandora" : "Pandora",
	"PandoraAddEditFavorites" : "Tambah/Edit Kegemaran Pandora ",
	"PandoraDeleteConfirmation" : "Adakah anda pasti mahu memadamkan Kegemaran {name}?",
	"PandoraFavorites" : "Kegemaran Pandora",
	"PandoraFavoritesAvailable" : "Kegemaran Pandora Ditambah Sebelum Ini",
	"PandoraFavoritesConfirm" : "Adakah anda ingin menggantikan satu?",
	"PandoraFavoritesDelete" : "Pilih Kegemaran Pandora untuk Padamkan",
	"PandoraFavoritesMax" : "Anda telah mencapai bilangan maksimum Kegemaran Pandora.",
	"PandoraFavoritesMove" : "Pilih Kegemaran Pandora untuk Alihkan",
	"PandoraFavoritesReplace" : "Gantikan dengan {activestation}",
	"PandoraFavoritesSelect" : "Pilih Kegemaran Pandora untuk Gantikan",
	"PandoraMaintinence" : "Maaf, pelayan Pandora tidak tersedia buat masa ini.",
	"PandoraMoveFavorite" : "Alihkan",
	"PandoraReplaceButtonText" : "Gantikan",
	"PandoraSelectPosition" : "Pilih Kedudukan yang Diingini",
	"Quit" : "Berhenti",
	"SBNStationCreationError" : "Ralat Stesen Penciptaan",
	"SBNStationLimitReached" : "Had Stesen Dicapai",
	"SelectStation" : "Stesen ini telah dipadam daripada peranti lain dalam akaun ini.",
	"Setup" : "Persediaan",
	"SetupBluetoothDeviceNow" : "Sediakan Peranti Bluetooth Sekarang?",
	"Shuffle" : "Rombak",
	"ShuffleNotAddedFavorites" : "Susun Semula tidak boleh ditambah ke Kegemaran Pandora.",
	"SortBy" : "Isih Mengikut",
	"SortByAZ" : "Isih Mengikut: A-Z",
	"SortByDate" : "Isih Mengikut: Tarikh",
	"StationCreationError" : "Terdapat ralat semasa cipta Stesen.",
	"StationLimitReached" : "Bilangan maksimum stesen telah dicapai.",
	"StationList" : "Senarai Stesen",
	"StationListTab" : "Kegemaran",
	"ThumbsDown" : "Tidak Suka",
	"ThumbsUp" : "Tanda Suka",
	"VrHelp_BookmarkOptions_Help_Left1" : "Bookmark Artist",
	"VrHelp_BookmarkOptions_Help_Left2" : "Bookmark Song",
	"VrHelp_NowPlaying_Help_Left1" : "Entertainment",
	"VrHelp_NowPlaying_Help_Left2" : "Station List",
	"VrHelp_NowPlaying_Help_Left3" : "Thumbs Down",
	"VrHelp_NowPlaying_Help_Left4" : "Thumbs Up",
	"VrHelp_NowPlaying_Help_Left5" : "Bookmark Song",
	"VrHelp_NowPlaying_Help_Right1" : "Bookmark Artist",
	"VrHelp_NowPlaying_Help_Right2" : "Play / Pause",
	"VrHelp_NowPlaying_Help_Right3" : "Skip",
	"VrHelp_NowPlaying_Help_Right4" : "Sound Settings",
	"VrHelp_SortBy_Help_Left1" : "Date",
	"VrHelp_SortBy_Help_Left2" : "A to Z",
	"entMenu" : "Menu Hiburan",
	"sbNameId" : "Pandora",
	"sbnBookmarkFailed" : "Tdk dpt tambah penanda halaman",
	"sbnConnectionError" : "Sambungan Rangkaian Terputus",
	"sbnConnectivityError" : "Sambungan Tidak Mencukupi",
	"sbnMobileDeviceError" : "Ralat Peranti Mudah Alih",
	"sbnOverLimit" : "Had langkau dicapai",
	"sbnPandoraMaintErr" : "Ralat Pelayan Pandora",
	"sbnRatingFailed" : "Tidak dapat menambah penarafan",
	"sbnStationDeleted" : "Tiada Stesen Semasa",
	"skip_Tooltip" : "Langkau",
};

framework.registerAppDictLoaded("pandora", "ms_MY");