var Localization_pandoraAppDict_cn_HK = {
	//"stringId" : "localString"
	"AZ" : "A-Z",
	"AddActiveStation" : "新增 {activestation}",
	"AddBookmark_Alert" : "正在新增書簽",
	"AddGenreStation" : "新增電臺： {genreStation}",
	"AddStation" : "新增電臺",
	"AddStationOption" : "從現在播放的節目中建立一個新電臺：",
	"AddStationOptionButton3" : "演出者",
	"AddingFavorites" : "將電臺新增至我的最愛",
	"AddingStation" : "新增電臺",
	"BluetoothAudioLost" : "Bluetooth 通訊中斷",
	"Bookmark" : "Pandora 書簽選項",
	"BookmarkAlreadyAdded" : "以前新增的書簽",
	"BookmarkArtist" : "將演出者加入書簽",
	"BookmarkSong" : "將歌曲加入書簽",
	"Buffering" : "正在緩衝",
	"ConnectionLost1" : "失去連線",
	"ConnectionLost2" : "確保您的行動裝置上的資料連線可用。",
	"Date" : "日期",
	"DeleteFavorites" : "從我的最愛中移除電臺",
	"FavoritesLimitReached" : "已達到我的最愛限制",
	"FromCurrentArtist" : "從當前演出者",
	"FromCurrentSong" : "從當前曲目",
	"InsufficientConnectivity" : "連線不足，無法打開 Pandora。",
	"InsufficientConnectivity_Alert" : "連線不足",
	"InvalidLogin1" : "登錄無效",
	"InvalidLogin2" : "認證失敗 確保您已登錄您的行動裝置。",
	"LicensingRestriction1" : "未受支援的 Pandora 地點",
	"LicensingRestriction2" : "Pandora 在美國以外無法使用。",
	"LicensingRestrictions_Alert" : "當前地點不支援 Pandora。",
	"Loading" : "請新增一個電臺",
	"MobileDevice1" : "行動裝置錯誤",
	"MobileDevice2" : "在安全的狀況下，確保行動裝置運行正常。",
	"NoBookmark_Alert" : "無法新增書簽",
	"NoCurrentStation" : "當前沒有正在播放節目的電臺",
	"NoDeviceConnected" : "未連線裝置",
	"NoFavoritesStationsCreated" : "未能建立我的最愛電臺。",
	"NoPandora1" : "未找到 Pandora",
	"NoPandora2" : "確保 Pandora 應用程式已經安裝在行動裝置上。",
	"NoRating_Alert" : "無法新增反對/讚成評分",
	"NoStationFound1" : "未發現電臺",
	"NoStationFound2" : "請在您的行動裝置上建立至少一個 Pandora 電臺。",
	"Nostationsadded" : "未新增電臺。",
	"NotSupportedVersion1" : "在安全的狀況下，請升級行動裝置上的 Pandora 應用程式。",
	"OverLimit" : "Pandora 的音樂收聽設定限制您的曲目跳過次數。",
	"Pandora" : "Pandora",
	"PandoraAddEditFavorites" : "新增/編輯 Pandora 我的最愛",
	"PandoraDeleteConfirmation" : "確定要刪除我的最愛 {name}？",
	"PandoraFavorites" : "Pandora 我的最愛",
	"PandoraFavoritesAvailable" : "以前新增的 Pandora 我的最愛",
	"PandoraFavoritesConfirm" : "是否要取代？",
	"PandoraFavoritesDelete" : "選取要刪除的 Pandora 我的最愛",
	"PandoraFavoritesMax" : "Pandora 我的最愛的數量已達到最大限制。",
	"PandoraFavoritesMove" : "選取要移動的 Pandora 我的最愛",
	"PandoraFavoritesReplace" : "用 {activestation} 取代",
	"PandoraFavoritesSelect" : "選取要取代的 Pandora 我的最愛",
	"PandoraMaintinence" : "抱歉，Pandora 伺服器目前不可用。",
	"PandoraMoveFavorite" : "移動",
	"PandoraReplaceButtonText" : "取代",
	"PandoraSelectPosition" : "選取目標位置",
	"Quit" : "退出",
	"SBNStationCreationError" : "Station Creation Error",
	"SBNStationLimitReached" : "Station Limit Reached",
	"SelectStation" : "該電臺已從此賬號的另一裝置中刪除。",
	"Setup" : "設定",
	"SetupBluetoothDeviceNow" : "立即設定 Bluetooth 裝置？",
	"Shuffle" : "隨機播放",
	"ShuffleNotAddedFavorites" : "隨機播放無法新增至 Pandora 我的最愛。",
	"SortBy" : "排序依據",
	"SortByAZ" : "排序依據： A-Z",
	"SortByDate" : "排序依據： 日期",
	"StationCreationError" : "建立電臺時出錯。",
	"StationLimitReached" : "電臺數量已達到最大限制。",
	"StationList" : "電臺清單",
	"StationListTab" : "我的最愛",
	"ThumbsDown" : "不喜歡",
	"ThumbsUp" : "讚好",
	"VrHelp_BookmarkOptions_Help_Left1" : "藝術家",
	"VrHelp_BookmarkOptions_Help_Left2" : "歌曲",
	"VrHelp_NowPlaying_Help_Left1" : "更改來源",
	"VrHelp_NowPlaying_Help_Left2" : "電台列表",
	"VrHelp_NowPlaying_Help_Left3" : "拇指朝下",
	"VrHelp_NowPlaying_Help_Left4" : "拇指朝上",
	"VrHelp_NowPlaying_Help_Left5" : "對歌曲設置書籤",
	"VrHelp_NowPlaying_Help_Right1" : "對藝術家設置書籤",
	"VrHelp_NowPlaying_Help_Right2" : "播放 / 暫停",
	"VrHelp_NowPlaying_Help_Right3" : "跳過",
	"VrHelp_NowPlaying_Help_Right4" : "聲音設置",
	"VrHelp_SortBy_Help_Left1" : "日期",
	"VrHelp_SortBy_Help_Left2" : "A 到 Z",
	"entMenu" : "音訊源",
	"sbNameId" : "Pandora",
	"sbnBookmarkFailed" : "無法新增書簽",
	"sbnConnectionError" : "失去網路連線",
	"sbnConnectivityError" : "連線不足",
	"sbnMobileDeviceError" : "行動裝置錯誤",
	"sbnOverLimit" : "已達到跳過限制",
	"sbnPandoraMaintErr" : "Pandora 伺服器錯誤",
	"sbnRatingFailed" : "無法新增評分",
	"sbnStationDeleted" : "沒有當前電臺",
	"skip_Tooltip" : "跳過",
};

framework.registerAppDictLoaded("pandora", "cn_HK");