var Localization_pandoraAppDict_pt_BR = {
	//"stringId" : "localString"
	"AZ" : "De A a Z",
	"AddActiveStation" : "Add {activestation}",
	"AddBookmark_Alert" : "Adicionado aos favoritos",
	"AddGenreStation" : "Adicionar estação: {genreStation}",
	"AddStation" : "Adicionar estação",
	"AddStationOption" : "Criar uma nova estação:",
	"AddStationOptionButton3" : "Artista",
	"AddingFavorites" : "Adicionando estação aos favoritos",
	"AddingStation" : "Adicionando estação",
	"BluetoothAudioLost" : "Falha de comunicação Bluetooth",
	"Bookmark" : "Opções de marcad. Pandora",
	"BookmarkAlreadyAdded" : "Esse marcador já foi adicionado",
	"BookmarkArtist" : "Adicionar artista aos favoritos",
	"BookmarkSong" : "Adicionar música aos favoritos",
	"Buffering" : "Armazenando em buffer",
	"ConnectionLost1" : "Conexão perdida",
	"ConnectionLost2" : "Certifique-se de que a conexão de dados do seu dispositivo móvel está disponível.",
	"Date" : "Data",
	"DeleteFavorites" : "Removendo estação dos favoritos",
	"FavoritesLimitReached" : "Limite de fav. alcançado",
	"FromCurrentArtist" : "Do artista atual",
	"FromCurrentSong" : "Da música atual",
	"InsufficientConnectivity" : "Conectividade insuficiente para abrir o Pandora",
	"InsufficientConnectivity_Alert" : "Conectividade insuficiente",
	"InvalidLogin1" : "Login incorreto",
	"InvalidLogin2" : "Falha na autenticação. Certifique-se de que esteja conectado em seu dispositivo móvel.",
	"LicensingRestriction1" : "Esta localização Pandora não é suportada",
	"LicensingRestriction2" : "O Pandora não está disponível fora dos Estados Unidos.",
	"LicensingRestrictions_Alert" : "O serviço Pandora não é suportado nessa localização",
	"Loading" : "Por favor, adicione uma estação.",
	"MobileDevice1" : "Erro no dispositivo móvel",
	"MobileDevice2" : "Assim que for seguro fazê-lo, verifique se seu dispositivo móvel está funcionamente corretamente.",
	"NoBookmark_Alert" : "Não é possível adic. fav.",
	"NoCurrentStation" : "Nenhuma estação tocando no momento",
	"NoDeviceConnected" : "Nenhum dispositivo conectado",
	"NoFavoritesStationsCreated" : "Não há estações favoritas criadas.",
	"NoPandora1" : "Pandora não encontrado",
	"NoPandora2" : "Verifique se a app Pandora está instalada no dispositivo móvel.",
	"NoRating_Alert" : "Não é possível adic.a classificação Polegar para cima/Polegar para baixo",
	"NoStationFound1" : "Nenhuma estação encontrada",
	"NoStationFound2" : "Por favor, criar pelo menos uma estação Pandora em seu dispositivo móvel.",
	"Nostationsadded" : "Nenhuma estação adicionada.",
	"NotSupportedVersion1" : "Assim que for seguro fazê-lo, atualize a app Pandora no seu dispositivo móvel.",
	"OverLimit" : "O licenciamento da música Pandora limita o número de faixas que pode ignorar.",
	"Pandora" : "Pandora",
	"PandoraAddEditFavorites" : "Adic/Edi favoritos do Pandora",
	"PandoraDeleteConfirmation" : "Tem certeza que deseja excluir o favorito {name}?",
	"PandoraFavorites" : "Favoritos do Pandora",
	"PandoraFavoritesAvailable" : "Este favorito já foi adicionado",
	"PandoraFavoritesConfirm" : "Deseja substituir algum?",
	"PandoraFavoritesDelete" : "Selecione o favorito a ser excluído",
	"PandoraFavoritesMax" : "Atingiu o número máximo de Favoritos Pandora.",
	"PandoraFavoritesMove" : "Selecione o favorito a ser movido",
	"PandoraFavoritesReplace" : "Substituir por  {activestation}",
	"PandoraFavoritesSelect" : "Selecione o favorito a ser subst.",
	"PandoraMaintinence" : "Lamentamos, mas os serviços Pandora estão indisponíveis de momento.",
	"PandoraMoveFavorite" : "Mover",
	"PandoraReplaceButtonText" : "Substituir",
	"PandoraSelectPosition" : "Selecione a posição pretendida",
	"Quit" : "Sair",
	"SBNStationCreationError" : "Estação Erro de criação",
	"SBNStationLimitReached" : "Limite de estações alcançado",
	"SelectStation" : "Esta estação foi eliminada por outro dispositivo nesta conta.",
	"Setup" : "Configuração",
	"SetupBluetoothDeviceNow" : "Configurar dispositivo Bluetooth agora?",
	"Shuffle" : "Ordem aleatória",
	"ShuffleNotAddedFavorites" : "Não é possível adicionar a leitura aleatória aos Favoritos Pandora.",
	"SortBy" : "Ordenar por",
	"SortByAZ" : "Ordenar por: De A a Z",
	"SortByDate" : "Ordenar por: Data",
	"StationCreationError" : "Erro ao criar uma estação.",
	"StationLimitReached" : "Atingiu o número máximo de estações",
	"StationList" : "Lista de estações",
	"StationListTab" : "Favoritos",
	"ThumbsDown" : "Descurtir",
	"ThumbsUp" : "Curtir",
	"VrHelp_BookmarkOptions_Help_Left1" : "Adicionar artista aos favoritos",
	"VrHelp_BookmarkOptions_Help_Left2" : "Adicionar a canção aos favoritos",
	"VrHelp_NowPlaying_Help_Left1" : "Entretenimento",
	"VrHelp_NowPlaying_Help_Left2" : "Lista de estações",
	"VrHelp_NowPlaying_Help_Left3" : "Desaprovar",
	"VrHelp_NowPlaying_Help_Left4" : "Aprovar",
	"VrHelp_NowPlaying_Help_Left5" : "Adicionar a canção aos favoritos",
	"VrHelp_NowPlaying_Help_Right1" : "Adicionar artista aos favoritos",
	"VrHelp_NowPlaying_Help_Right2" : "Reproduzir / Pausar",
	"VrHelp_NowPlaying_Help_Right3" : "Ignorar",
	"VrHelp_NowPlaying_Help_Right4" : "Definições de som",
	"VrHelp_SortBy_Help_Left1" : "Data",
	"VrHelp_SortBy_Help_Left2" : "A a Z",
	"entMenu" : "Entretenimento",
	"sbNameId" : "Pandora",
	"sbnBookmarkFailed" : "Não é possível adicionar favoritos",
	"sbnConnectionError" : "Conexão de rede perdida",
	"sbnConnectivityError" : "Conectividade insuficiente",
	"sbnMobileDeviceError" : "Erro no dispositivo móvel",
	"sbnOverLimit" : "Limite de itens ignorados alcançado",
	"sbnPandoraMaintErr" : "Erro no servidor Pandora",
	"sbnRatingFailed" : "Não é possível adicionar classif.",
	"sbnStationDeleted" : "Nenhuma estação no momento",
	"skip_Tooltip" : "Ignorar",
};

framework.registerAppDictLoaded("pandora", "pt_BR");