var Localization_pandoraAppDict_en_US = {
	//"stringId" : "localString"
	"AZ" : "A-Z",
	"AddActiveStation" : "Add {activestation}",
	"AddBookmark_Alert" : "Adding Bookmark",
	"AddGenreStation" : "Add Station: {genreStation}",
	"AddStation" : "Add Station",
	"AddStationOption" : "Create a New Station:",
	"AddStationOptionButton3" : "Artist",
	"AddingFavorites" : "Adding Station to Pandora Favorites",
	"AddingStation" : "Adding Station",
	"BluetoothAudioLost" : "Bluetooth Communication Lost",
	"Bookmark" : "Pandora Bookmark Options",
	"BookmarkAlreadyAdded" : "Bookmark Previously Added",
	"BookmarkArtist" : "Bookmark Artist",
	"BookmarkSong" : "Bookmark Song",
	"Buffering" : "Buffering",
	"ConnectionLost1" : "Connection Lost",
	"ConnectionLost2" : "Make sure the data connection on your mobile device is available.",
	"Date" : "Date",
	"DeleteFavorites" : "Removing Station from Pandora Favorites",
	"FavoritesLimitReached" : "Pandora Favorites Limit Reached",
	"FromCurrentArtist" : "From Current Artist",
	"FromCurrentSong" : "From Current Song",
	"InsufficientConnectivity" : "Insufficient Connectivity to Open Pandora",
	"InsufficientConnectivity_Alert" : "Insufficient Connectivity",
	"InvalidLogin1" : "Invalid Login",
	"InvalidLogin2" : "Authentication failed. Make sure you are logged in on your mobile device.",
	"LicensingRestriction1" : "Unsupported Pandora Location",
	"LicensingRestriction2" : "Pandora is not available outside the United States.",
	"LicensingRestrictions_Alert" : "Pandora is Unsupported in Your Current Location",
	"Loading" : "Please add a Station.",
	"MobileDevice1" : "Mobile Device Error",
	"MobileDevice2" : "When safe to do so, make sure your mobile device is functioning properly.",
	"NoBookmark_Alert" : "Unable to Add Bookmark",
	"NoCurrentStation" : "Station Removed ",
	"NoDeviceConnected" : "No Device Connected",
	"NoFavoritesStationsCreated" : "No favorite stations created.",
	"NoPandora1" : "Pandora Not Found",
	"NoPandora2" : "Make sure the Pandora application is installed on your mobile device.",
	"NoRating_Alert" : "Unable to add Thumbs Up/Down Rating",
	"NoStationFound1" : "No Station Found",
	"NoStationFound2" : "Please create at least one Pandora station on your mobile device.",
	"Nostationsadded" : "No stations added.",
	"NotSupportedVersion1" : "When safe to do so, please upgrade the Pandora application on your Mobile Device.",
	"OverLimit" : "Pandora's music licensing limits the number of tracks you may skip.",
	"Pandora" : "Pandora",
	"PandoraAddEditFavorites" : "Add/Edit Pandora Favorites",
	"PandoraDeleteConfirmation" : "Are you sure you want to delete the Pandora Favorite {name}?",
	"PandoraFavorites" : "Pandora Favorites",
	"PandoraFavoritesAvailable" : "Pandora Favorite Previously Added",
	"PandoraFavoritesConfirm" : "Would you like to replace one?",
	"PandoraFavoritesDelete" : "Select Pandora Favorite to Delete",
	"PandoraFavoritesMax" : "You have reached the maximum number of Pandora Favorites.",
	"PandoraFavoritesMove" : "Select Pandora Favorite to Move",
	"PandoraFavoritesReplace" : "Replace with {activestation}",
	"PandoraFavoritesSelect" : "Select Pandora Favorite to Replace",
	"PandoraMaintinence" : "Sorry, Pandora servers are currently unavailable.",
	"PandoraMoveFavorite" : "Move",
	"PandoraReplaceButtonText" : "Replace",
	"PandoraSelectPosition" : "Select the Desired Position",
	"Quit" : "Quit",
	"SBNStationCreationError" : "Station Creation Error",
	"SBNStationLimitReached" : "Station Limit Reached",
	"SelectStation" : "This station has been deleted from another device on this account.",
	"Setup" : "Setup",
	"SetupBluetoothDeviceNow" : "Setup Bluetooth Device Now?",
	"Shuffle" : "Shuffle",
	"ShuffleNotAddedFavorites" : "Shuffle cannot be added to Pandora Favorites.",
	"SortBy" : "Sort By",
	"SortByAZ" : "Sort By: A-Z",
	"SortByDate" : "Sort By: Date",
	"StationCreationError" : "There was an error while creating a station.",
	"StationLimitReached" : "The maximum number of stations has been reached.",
	"StationList" : "Station List",
	"StationListTab" : "Favorites",
	"ThumbsDown" : "Thumbs Down",
	"ThumbsUp" : "Thumbs Up",
	"VrHelp_BookmarkOptions_Help_Left1" : "Bookmark Artist",
	"VrHelp_BookmarkOptions_Help_Left2" : "Bookmark Song",
	"VrHelp_NowPlaying_Help_Left1" : "Entertainment",
	"VrHelp_NowPlaying_Help_Left2" : "Station List",
	"VrHelp_NowPlaying_Help_Left3" : "Thumbs Down",
	"VrHelp_NowPlaying_Help_Left4" : "Thumbs Up",
	"VrHelp_NowPlaying_Help_Left5" : "Bookmark Song",
	"VrHelp_NowPlaying_Help_Right1" : "Bookmark Artist",
	"VrHelp_NowPlaying_Help_Right2" : "Play / Pause",
	"VrHelp_NowPlaying_Help_Right3" : "Skip",
	"VrHelp_NowPlaying_Help_Right4" : "Sound Settings",
	"VrHelp_SortBy_Help_Left1" : "Date",
	"VrHelp_SortBy_Help_Left2" : "A to Z",
	"entMenu" : "Audio Sources",
	"sbNameId" : "Pandora",
	"sbnBookmarkFailed" : "Unable to Add Bookmark",
	"sbnConnectionError" : "Network Connection Lost",
	"sbnConnectivityError" : "Insufficient Connectivity",
	"sbnMobileDeviceError" : "Mobile Device Error",
	"sbnOverLimit" : "Skip Limit Reached",
	"sbnPandoraMaintErr" : "Pandora Server Error",
	"sbnRatingFailed" : "Unable to Add Rating",
	"sbnStationDeleted" : "No Current Station",
	"skip_Tooltip" : "Skip",
};

framework.registerAppDictLoaded("pandora", "en_US");