var Localization_pandoraAppDict_fr_CN = {
	//"stringId" : "localString"
	"AZ" : "A-Z",
	"AddActiveStation" : "Ajouter {activestation}",
	"AddBookmark_Alert" : "Ajout d'un signet",
	"AddGenreStation" : "Ajout station : {genreStation}",
	"AddStation" : "Ajout station",
	"AddStationOption" : "Créer une nouvelle station :",
	"AddStationOptionButton3" : "Artiste",
	"AddingFavorites" : "Ajout de station aux favoris",
	"AddingStation" : "Ajout de station",
	"BluetoothAudioLost" : "Communication Bluetooth perdue",
	"Bookmark" : "Options sur les Sig. Pandora",
	"BookmarkAlreadyAdded" : "Signet déjà ajouté",
	"BookmarkArtist" : "Marquer l’artiste",
	"BookmarkSong" : "Marquer le morceau",
	"Buffering" : "Mise en mémoire",
	"ConnectionLost1" : "Pas de connexion",
	"ConnectionLost2" : "Assurez-vous que la connexion de données sur votre dispositif mobile fonctionne correctement.",
	"Date" : "Date",
	"DeleteFavorites" : "Retrait de la station des favoris",
	"FavoritesLimitReached" : "Max des favoris atteint",
	"FromCurrentArtist" : "D'artiste en cours",
	"FromCurrentSong" : "De morceau en cours",
	"InsufficientConnectivity" : "Connectivité insuffisante pour ouvrir Pandora.",
	"InsufficientConnectivity_Alert" : "Connectivité insuffisante",
	"InvalidLogin1" : "Connexion non valide",
	"InvalidLogin2" : "Échec d'authentification.",
	"LicensingRestriction1" : "Emplacement non appuyé.",
	"LicensingRestriction2" : "Pandora n'est pas disponible en dehors des États-Unis.",
	"LicensingRestrictions_Alert" : "Pandora n'est pas appuyé dans votre emplacement actuel.",
	"Loading" : "Veuillez ajouter une station.",
	"MobileDevice1" : "Erreur du dispositif mobile",
	"MobileDevice2" : "Lorsque c'est possible de le faire en toute sécurité, s'assurer que l'appareil mobile fonctionne correctement.",
	"NoBookmark_Alert" : "Impossible d’ajouter signet",
	"NoCurrentStation" : "Station enlevée",
	"NoDeviceConnected" : "Pas de dispositif connecté",
	"NoFavoritesStationsCreated" : "Aucune station favorite créée.",
	"NoPandora1" : "Pandora non trouvé",
	"NoPandora2" : "S'assurer que l'application Pandora est installée sur votre appareil mobile.",
	"NoRating_Alert" : "Impossible d'ajouter la classification pouce en l'air/pouce en bas",
	"NoStationFound1" : "Aucune station trouvée",
	"NoStationFound2" : "Vous devez d’abord avoir configuré au moins une station Pandora",
	"Nostationsadded" : "Aucune station ajoutée",
	"NotSupportedVersion1" : "Lorsque c'est possible de le faire en toute sécurité, mettre à jour l'application Pandora sur votre appareil mobile.",
	"OverLimit" : "La licence pour la musique Pandora limite le nombre de pistes que vous pouvez sauter.",
	"Pandora" : "Pandora",
	"PandoraAddEditFavorites" : "Ajout./Édit. Pandora fav.",
	"PandoraDeleteConfirmation" : "Êtes-vous sûr de vouloir supprimer le favori {name}?",
	"PandoraFavorites" : "Favoris Pandora",
	"PandoraFavoritesAvailable" : "Favori Pandora déjà ajouté",
	"PandoraFavoritesConfirm" : "Voulez-vous en rem. un maint?",
	"PandoraFavoritesDelete" : "Sélect. le fav. Pandora à supprimer",
	"PandoraFavoritesMax" : "Vous avez atteint le nombre maximum de favoris Pandora.",
	"PandoraFavoritesMove" : "Sélect. le fav. Pandora à déplacer",
	"PandoraFavoritesReplace" : "Remplacer par {activestation}",
	"PandoraFavoritesSelect" : "Sélectionner le favori Pandora à remplacer",
	"PandoraMaintinence" : "Désolé, les serveurs Pandora sont actuellement indisponibles.",
	"PandoraMoveFavorite" : "Déplacer",
	"PandoraReplaceButtonText" : "Remplacer",
	"PandoraSelectPosition" : "Sélectionner la position désirée",
	"Quit" : "Quitter",
	"SBNStationCreationError" : "Erreur création station",
	"SBNStationLimitReached" : "Max des stations atteint",
	"SelectStation" : "Ce poste a été supprimé depuis un autre appareil relié à ce compte.",
	"Setup" : "Configurer",
	"SetupBluetoothDeviceNow" : "Configurer le dispositif Bluetooth maintenant ?",
	"Shuffle" : "Lecture aléatoire",
	"ShuffleNotAddedFavorites" : "Il est impossible d'ajouter la lecture aléatoire aux favoris Pandora.",
	"SortBy" : "Trier par",
	"SortByAZ" : "Trier par : A-Z",
	"SortByDate" : "Trier par : Date",
	"StationCreationError" : "Une erreur s'est produite lors de la création d'un poste.",
	"StationLimitReached" : "Vous avez atteint le nombre maximum de postes.",
	"StationList" : "Liste des stations",
	"StationListTab" : "Favoris",
	"ThumbsDown" : "Défavorable",
	"ThumbsUp" : "Favorable",
	"VrHelp_BookmarkOptions_Help_Left1" : "Marquer l’artiste",
	"VrHelp_BookmarkOptions_Help_Left2" : "Marquer le morceau",
	"VrHelp_NowPlaying_Help_Left1" : "Divertissements",
	"VrHelp_NowPlaying_Help_Left2" : "Liste des stations",
	"VrHelp_NowPlaying_Help_Left3" : "Défavorable",
	"VrHelp_NowPlaying_Help_Left4" : "Favorable",
	"VrHelp_NowPlaying_Help_Left5" : " Marquer le morceau",
	"VrHelp_NowPlaying_Help_Right1" : "Marquer l’artiste",
	"VrHelp_NowPlaying_Help_Right2" : "Lire/Pause",
	"VrHelp_NowPlaying_Help_Right3" : "Sauter",
	"VrHelp_NowPlaying_Help_Right4" : " Paramètres audio",
	"VrHelp_SortBy_Help_Left1" : "Date",
	"VrHelp_SortBy_Help_Left2" : "Par ordre alphabétique",
	"entMenu" : "Menu des divertissements",
	"sbNameId" : "Pandora",
	"sbnBookmarkFailed" : "Impossible d’ajouter un signet",
	"sbnConnectionError" : "Perte de connexion au réseau",
	"sbnConnectivityError" : "Connectivité insuffisante",
	"sbnMobileDeviceError" : "Erreur du dispositif mobile",
	"sbnOverLimit" : "Limite passage au suivant atteinte",
	"sbnPandoraMaintErr" : "Erreur du serveur Pandora",
	"sbnRatingFailed" : "Impossible d’ajouter classification",
	"sbnStationDeleted" : "Pas de station en cours",
	"skip_Tooltip" : "Sauter",
};

framework.registerAppDictLoaded("pandora", "fr_CN");