var Localization_pandoraAppDict_pt_PT = {
	//"stringId" : "localString"
	"AZ" : "A-Z",
	"AddActiveStation" : "Adicionar {activestation}",
	"AddBookmark_Alert" : "A adicionar Marcador",
	"AddGenreStation" : "Adicionar Est.: {genreStation}",
	"AddStation" : "Adicionar Estação",
	"AddStationOption" : "Criar uma Estação Nova:",
	"AddStationOptionButton3" : "Artista",
	"AddingFavorites" : "A Adicionar Estação aos Favoritos",
	"AddingStation" : "A Adicionar Estação",
	"BluetoothAudioLost" : "Falha de comunicação Bluetooth",
	"Bookmark" : "Opções de marcadores Pandora",
	"BookmarkAlreadyAdded" : "Este marcador já foi adicionado",
	"BookmarkArtist" : "Adicionar artista aos favoritos",
	"BookmarkSong" : "Adicionar a Canção aos Favoritos",
	"Buffering" : "A Coloc. na Mem. Interm.",
	"ConnectionLost1" : "Ligação Perdida",
	"ConnectionLost2" : "Certifique-se de que a ligação de dados do dispositivo móvel está a funcionar correctamente.",
	"Date" : "Data",
	"DeleteFavorites" : "A Remover Estação dos Favoritos",
	"FavoritesLimitReached" : "Limite Favoritos Atingido",
	"FromCurrentArtist" : "A partir do Artista Actual",
	"FromCurrentSong" : "A partir da Canção Actual",
	"InsufficientConnectivity" : "Conectividade insuficiente para abrir a Pandora.",
	"InsufficientConnectivity_Alert" : "Conectividade insuficiente",
	"InvalidLogin1" : "Início de Sessão Inválido",
	"InvalidLogin2" : "A autenticação falhou.",
	"LicensingRestriction1" : "Esta localização Pandora não é suportada",
	"LicensingRestriction2" : "A Pandora não está disponível fora dos Estados Unidos.",
	"LicensingRestrictions_Alert" : "O serviço Pandora não é suportado na localização atual",
	"Loading" : "Por favor adicione uma Estação.",
	"MobileDevice1" : "Erro no Dispositivo Móvel",
	"MobileDevice2" : "Assim que for seguro fazê-lo, verifique se o dispositivo móvel está a funcionar corretamente.",
	"NoBookmark_Alert" : "Não foi pos. adic. marcad.",
	"NoCurrentStation" : "Nenhuma Estação em Reprodução",
	"NoDeviceConnected" : "Não Existe Dispositivo Ligado",
	"NoFavoritesStationsCreated" : "Não foram criadas estações favoritas.",
	"NoPandora1" : "Pandora Não Encontrada",
	"NoPandora2" : "Certifique-se de que a app Pandora está instalada no dispositivo móvel.",
	"NoRating_Alert" : "Não é possível adicionar a classificação Polegar para cima/Polegar para baixo",
	"NoStationFound1" : "Nenhuma Estação Encontrada",
	"NoStationFound2" : "Tem de configurar, pelo menos, uma estação Pandora em primeiro lugar.",
	"Nostationsadded" : "Nenhuma estação adicionada",
	"NotSupportedVersion1" : "Assim que for seguro fazê-lo, atualize a app Pandora no seu dispositivo móvel.",
	"OverLimit" : "O licenciamento da música Pandora limita o número de faixas que pode ignorar.",
	"Pandora" : "Pandora",
	"PandoraAddEditFavorites" : "Adicionar/Editar Favoritos Pandora ",
	"PandoraDeleteConfirmation" : "Tem a certeza de que pretende apagar o Favorito {name}?",
	"PandoraFavorites" : "Favoritos Pandora",
	"PandoraFavoritesAvailable" : "Este favorito já foi adicionado",
	"PandoraFavoritesConfirm" : "Pretende substituir algum?",
	"PandoraFavoritesDelete" : "Selecione Favorito Pandora para Apagar",
	"PandoraFavoritesMax" : "Atingiu o número máximo de Favoritos Pandora.",
	"PandoraFavoritesMove" : "Selecione Favorito Pandora para Mover",
	"PandoraFavoritesReplace" : "Substituir por {activestation}",
	"PandoraFavoritesSelect" : "Selecione Favorito Pandora para Substituir",
	"PandoraMaintinence" : "Lamentamos, mas as serviços Pandora estão indisponíveis neste momento.",
	"PandoraMoveFavorite" : "Mover",
	"PandoraReplaceButtonText" : "Substituir",
	"PandoraSelectPosition" : "Selecione a posição pretendida",
	"Quit" : "Sair",
	"SBNStationCreationError" : "Erro ao Criar Estação",
	"SBNStationLimitReached" : "Limite de estações atingido",
	"SelectStation" : "Esta estação foi eliminada por outro dispositivo nesta conta.",
	"Setup" : "Configurar",
	"SetupBluetoothDeviceNow" : "Configurar Dispositivo Bluetooth Agora?",
	"Shuffle" : "Aleatório",
	"ShuffleNotAddedFavorites" : "Não é possível adicionar a leitura aleatória aos Favoritos Pandora.",
	"SortBy" : "Ordenar Por",
	"SortByAZ" : "Ordenar Por: A-Z",
	"SortByDate" : "Ordenar Por: Data",
	"StationCreationError" : "Erro ao criar uma estação.",
	"StationLimitReached" : "Atingiu o número máximo de estações",
	"StationList" : "Lista de Estações",
	"StationListTab" : "Favoritos",
	"ThumbsDown" : "Desaprovar",
	"ThumbsUp" : "Aprovar",
	"VrHelp_BookmarkOptions_Help_Left1" : "Adicionar artista aos favoritos",
	"VrHelp_BookmarkOptions_Help_Left2" : "Adicionar a Canção aos Favoritos",
	"VrHelp_NowPlaying_Help_Left1" : "Entretenimento",
	"VrHelp_NowPlaying_Help_Left2" : "Lista de Estações",
	"VrHelp_NowPlaying_Help_Left3" : "Desaprovar",
	"VrHelp_NowPlaying_Help_Left4" : "Aprovar",
	"VrHelp_NowPlaying_Help_Left5" : " Adicionar a Canção aos Favoritos",
	"VrHelp_NowPlaying_Help_Right1" : "Adicionar artista aos favoritos",
	"VrHelp_NowPlaying_Help_Right2" : "Reproduzir / Pausar",
	"VrHelp_NowPlaying_Help_Right3" : "Ignorar",
	"VrHelp_NowPlaying_Help_Right4" : "Definições de Som",
	"VrHelp_SortBy_Help_Left1" : "Data",
	"VrHelp_SortBy_Help_Left2" : "A a Z",
	"entMenu" : "Menu Entretenimento",
	"sbNameId" : "Pandora",
	"sbnBookmarkFailed" : "Não é possível adicionar marcador",
	"sbnConnectionError" : "Ligação de Rede Perdida",
	"sbnConnectivityError" : "Conectividade Insuficiente",
	"sbnMobileDeviceError" : "Erro no Dispositivo Móvel",
	"sbnOverLimit" : "Limite para ignorar atingido",
	"sbnPandoraMaintErr" : "Erro no servidor Pandora",
	"sbnRatingFailed" : "Não é possível adicion. classificação",
	"sbnStationDeleted" : "Actualmente sem estação",
	"skip_Tooltip" : "Ignorar",
};

framework.registerAppDictLoaded("pandora", "pt_PT");