var Localization_pandoraAppDict_es_ES = {
	//"stringId" : "localString"
	"AZ" : "A-Z",
	"AddActiveStation" : "Añadir {activestation}",
	"AddBookmark_Alert" : "Añadiendo favorito",
	"AddGenreStation" : "Añadir emisora: {genreStation}",
	"AddStation" : "Añadir emisora",
	"AddStationOption" : "Crear una nueva estación:",
	"AddStationOptionButton3" : "Artista",
	"AddingFavorites" : "Añadiendo emisora a Favoritos",
	"AddingStation" : "Añadiendo emisora",
	"BluetoothAudioLost" : "Comunicación por Bluetooth perdida",
	"Bookmark" : "Opciones de marcador de Pandora",
	"BookmarkAlreadyAdded" : "Marcador ya añadido anteriormente",
	"BookmarkArtist" : "Artista favorito",
	"BookmarkSong" : "Canción favorita",
	"Buffering" : "Amortiguación",
	"ConnectionLost1" : "Conexión perdida",
	"ConnectionLost2" : "Asegúrese de que la conexión de datos en su dispositivo móvil está funcionando adecuadamente.",
	"Date" : "Fecha",
	"DeleteFavorites" : "Borrando la emisora de Favoritos",
	"FavoritesLimitReached" : "Ha llegado límite Favoritos",
	"FromCurrentArtist" : "Desde el artista actual",
	"FromCurrentSong" : "Desde la canción actual",
	"InsufficientConnectivity" : "Conectividad insuficiente para abrir Pandora.",
	"InsufficientConnectivity_Alert" : "Conectividad insuficiente",
	"InvalidLogin1" : "Acceso no Válido",
	"InvalidLogin2" : "Autenticación fallida",
	"LicensingRestriction1" : "Ubicación no admitida",
	"LicensingRestriction2" : "Pandora no está disponible fuera de los Estados Unidos",
	"LicensingRestrictions_Alert" : "Pandora no es admitida en su ubicación actual",
	"Loading" : "Por favor, añada una emisora.",
	"MobileDevice1" : "Error del dispositivo móvil",
	"MobileDevice2" : "Cuando sea seguro hacerlo, asegúrese de que su dispositivo móvil funciona correctamente.",
	"NoBookmark_Alert" : "No puede agregar a fav",
	"NoCurrentStation" : "Emisora eliminada",
	"NoDeviceConnected" : "No hay dispositivo conectado",
	"NoFavoritesStationsCreated" : "No se ha creado ninguna estación favorita.",
	"NoPandora1" : "No se encontró Pandora",
	"NoPandora2" : "Asegúrese de que la aplicación Pandora está instalada en su dispositivo móvil.",
	"NoRating_Alert" : "No se puede agregar clasificación Me gusta/No me gusta",
	"NoStationFound1" : "No se encontró Emisora",
	"NoStationFound2" : "Primero debe tener al menos una emisora Pandora configurada.",
	"Nostationsadded" : "No se ha añadido ninguna emisora.",
	"NotSupportedVersion1" : "Cuando sea seguro hacerlo, actualice la aplicación Pandora en su dispositivo móvil.",
	"OverLimit" : "La licencia de música de Pandora limita el número de canciones que puede saltar.",
	"Pandora" : "Pandora",
	"PandoraAddEditFavorites" : "Añadir/Editar Pandora Favorita",
	"PandoraDeleteConfirmation" : "¿Está seguro de que quiere eliminar el {name} favorito?",
	"PandoraFavorites" : "Favoritos de Pandora",
	"PandoraFavoritesAvailable" : "Favorito de Pandora ya añadido previamente",
	"PandoraFavoritesConfirm" : "¿Le gustaría sustituir alguno?",
	"PandoraFavoritesDelete" : "Seleccione el favorito de Pandora que desee eliminar",
	"PandoraFavoritesMax" : "Ha alcanzado el número máximo de favoritos de Pandora.",
	"PandoraFavoritesMove" : "Seleccione el favorito de Pandora que desee mover",
	"PandoraFavoritesReplace" : "Sustituir por {activestation}",
	"PandoraFavoritesSelect" : "Seleccione un favorito de Pandora para sustituirlo",
	"PandoraMaintinence" : "Lo sentimos, los servidores de Pandora no están disponibles en este momento.",
	"PandoraMoveFavorite" : "Mover",
	"PandoraReplaceButtonText" : "Sustituir",
	"PandoraSelectPosition" : "Seleccione la posición deseada",
	"Quit" : "Abandonar ",
	"SBNStationCreationError" : "Error al crear la emisora",
	"SBNStationLimitReached" : "Ha llegado al límite de emisoras",
	"SelectStation" : "Esta emisora ha sido eliminada desde otro dispositivo con esta cuenta.",
	"Setup" : "Configurar",
	"SetupBluetoothDeviceNow" : "¿Configurar el dispositivo Bluetooth ahora?",
	"Shuffle" : "Aleatorio ",
	"ShuffleNotAddedFavorites" : "Aleatorio no puede añadirse a favoritos de Pandora.",
	"SortBy" : "Ordenar por",
	"SortByAZ" : "Ordenar de: A-Z",
	"SortByDate" : "Ordenar por: Fecha ",
	"StationCreationError" : "Ha habido un error al crear una emisora.",
	"StationLimitReached" : "Se ha alcanzado el número máximo de emisoras.",
	"StationList" : "Lista de Emisoras",
	"StationListTab" : "Favoritos",
	"ThumbsDown" : "No me gusta",
	"ThumbsUp" : "Me gusta",
	"VrHelp_BookmarkOptions_Help_Left1" : "Artista Favorito ",
	"VrHelp_BookmarkOptions_Help_Left2" : "Canción Favorita",
	"VrHelp_NowPlaying_Help_Left1" : "Entretenimiento",
	"VrHelp_NowPlaying_Help_Left2" : "Lista de Emisoras",
	"VrHelp_NowPlaying_Help_Left3" : "No me gusta",
	"VrHelp_NowPlaying_Help_Left4" : "Me gusta",
	"VrHelp_NowPlaying_Help_Left5" : "Canción favorita",
	"VrHelp_NowPlaying_Help_Right1" : "Artista favorito",
	"VrHelp_NowPlaying_Help_Right2" : "Reproducir/Pausa",
	"VrHelp_NowPlaying_Help_Right3" : "Saltar",
	"VrHelp_NowPlaying_Help_Right4" : "Ajustes de sonido",
	"VrHelp_SortBy_Help_Left1" : "Fecha",
	"VrHelp_SortBy_Help_Left2" : "A a la Z",
	"entMenu" : "Menú entretenimiento",
	"sbNameId" : "Pandora",
	"sbnBookmarkFailed" : "No se pudo agregar a favoritos.",
	"sbnConnectionError" : "Conexión de red perdida",
	"sbnConnectivityError" : "Conectividad insuficiente",
	"sbnMobileDeviceError" : "Error del dispositivo móvil",
	"sbnOverLimit" : "Límite de saltos alcanzado",
	"sbnPandoraMaintErr" : "Error del servidor de Pandora",
	"sbnRatingFailed" : "No se pudo añadir clasificación",
	"sbnStationDeleted" : "No hay señal de emisora ",
	"skip_Tooltip" : "Saltar",
};

framework.registerAppDictLoaded("pandora", "es_ES");