var Localization_pandoraAppDict_fr_FR = {
	//"stringId" : "localString"
	"AZ" : "A-Z",
	"AddActiveStation" : "Ajouter  {activestation}",
	"AddBookmark_Alert" : "Ajout d'un signet",
	"AddGenreStation" : "Ajout station : {genreStation}",
	"AddStation" : "Ajout station",
	"AddStationOption" : "Créer une nouvelle station:",
	"AddStationOptionButton3" : "Artiste",
	"AddingFavorites" : "Ajout de station aux favoris",
	"AddingStation" : "Ajout de station",
	"BluetoothAudioLost" : "Communication Bluetooth perdue",
	"Bookmark" : "Options sur les Sig. Pandora",
	"BookmarkAlreadyAdded" : "Signet déjà ajouté",
	"BookmarkArtist" : "Marquer l’artiste",
	"BookmarkSong" : "Marquer le morceau",
	"Buffering" : "Mise en mémoire",
	"ConnectionLost1" : "Pas de connexion",
	"ConnectionLost2" : "Assurez-vous que la connexion de données sur votre dispositif mobile fonctionne correctement.",
	"Date" : "Date",
	"DeleteFavorites" : "Retrait de la station des favoris",
	"FavoritesLimitReached" : "Max des favoris atteint",
	"FromCurrentArtist" : "D'artiste en cours",
	"FromCurrentSong" : "De morceau en cours",
	"InsufficientConnectivity" : "Connectivité insuffisante pour ouvrir Pandora.",
	"InsufficientConnectivity_Alert" : "Connectivité insuffisante",
	"InvalidLogin1" : "Connexion non valide",
	"InvalidLogin2" : "Échec d'authentification.",
	"LicensingRestriction1" : "N'est pas disp. à cet endroit",
	"LicensingRestriction2" : "Pandora n'est pas disponible en dehors des États-Unis.",
	"LicensingRestrictions_Alert" : "Pandora n'est pas disponible pour votre emplacement actuel",
	"Loading" : "Veuillez ajouter une station.",
	"MobileDevice1" : "Erreur du dispositif mobile",
	"MobileDevice2" : "Lorsque cela ne présente pas de risque, assurez-vous que votre appareil mobile fonctionne correctement.",
	"NoBookmark_Alert" : "Impossible d’ajouter signet",
	"NoCurrentStation" : "Station enlevée",
	"NoDeviceConnected" : "Pas de dispositif connecté",
	"NoFavoritesStationsCreated" : "Aucune station favorite créée.",
	"NoPandora1" : "Pandora non trouvé",
	"NoPandora2" : "Assurez-vous que l'application Pandora est bien installée sur votre appareil mobile.",
	"NoRating_Alert" : "Impossible d'ajouter un classement Pouces levés/baissés",
	"NoStationFound1" : "Aucune station trouvée",
	"NoStationFound2" : "Vous devez d’abord avoir configuré au moins une station Pandora",
	"Nostationsadded" : "Aucune station ajoutée",
	"NotSupportedVersion1" : "Lorsque cela ne présente pas de risque, veuillez mettre à jour l'application Pandora sur votre appareil mobile.",
	"OverLimit" : "La licence de musique Pandora limite le nombre de morceaux que vous pouvez sauter.",
	"Pandora" : "Pandora",
	"PandoraAddEditFavorites" : "Ajouter/Éditer Pandora fav",
	"PandoraDeleteConfirmation" : "Voulez-vous vraiment supprimer le favori {name}?",
	"PandoraFavorites" : "Favoris Pandora",
	"PandoraFavoritesAvailable" : "Favoris Pandora déjà ajouté",
	"PandoraFavoritesConfirm" : "Voulez-vous en remplacer un?",
	"PandoraFavoritesDelete" : "Sélectionnez le favori Pandora à supprimer",
	"PandoraFavoritesMax" : "Vous avez atteint le nombre maximum de favoris sur Pandora.",
	"PandoraFavoritesMove" : "Sélectionnez le favori Pandora à déplacer",
	"PandoraFavoritesReplace" : "Remplacer par {activestation}",
	"PandoraFavoritesSelect" : "Sélectionnez un favori Pandora à remplacer",
	"PandoraMaintinence" : "Désolé, les serveurs Pandora sont momentanément indisponibles.",
	"PandoraMoveFavorite" : "Déplacer",
	"PandoraReplaceButtonText" : "Remplacer",
	"PandoraSelectPosition" : "Sélectionnez la position souhaitée",
	"Quit" : "Quitter",
	"SBNStationCreationError" : "Erreur station création",
	"SBNStationLimitReached" : "Max des stations atteint",
	"SelectStation" : "Cette station a été supprimée de ce compte depuis un autre appareil.",
	"Setup" : "Configurer",
	"SetupBluetoothDeviceNow" : "Configurer le dispositif Bluetooth maintenant ?",
	"Shuffle" : "Lecture aléatoire",
	"ShuffleNotAddedFavorites" : "La lecture aléatoire ne peut pas être ajoutée aux favoris Pandora.",
	"SortBy" : "Trier par",
	"SortByAZ" : "Trier par : A-Z",
	"SortByDate" : "Trier par : Date",
	"StationCreationError" : "Une erreur est survenue lors de la création de la station.",
	"StationLimitReached" : "Vous avez atteint le nombre de stations maximum.",
	"StationList" : "Liste des stations",
	"StationListTab" : "Favoris",
	"ThumbsDown" : "Défavorable",
	"ThumbsUp" : "Favorable",
	"VrHelp_BookmarkOptions_Help_Left1" : "Marquer l’artiste",
	"VrHelp_BookmarkOptions_Help_Left2" : "Marquer le morceau",
	"VrHelp_NowPlaying_Help_Left1" : "Divertissements",
	"VrHelp_NowPlaying_Help_Left2" : "Liste des stations",
	"VrHelp_NowPlaying_Help_Left3" : "Défavorable",
	"VrHelp_NowPlaying_Help_Left4" : "Favorable",
	"VrHelp_NowPlaying_Help_Left5" : " Marquer le morceau",
	"VrHelp_NowPlaying_Help_Right1" : "Marquer l’artiste",
	"VrHelp_NowPlaying_Help_Right2" : "Lire/Pause",
	"VrHelp_NowPlaying_Help_Right3" : "Passer au suivant",
	"VrHelp_NowPlaying_Help_Right4" : "Paramètres audio",
	"VrHelp_SortBy_Help_Left1" : "Date",
	"VrHelp_SortBy_Help_Left2" : "Par ordre alphabétique",
	"entMenu" : "Menu des divertissements",
	"sbNameId" : "Pandora",
	"sbnBookmarkFailed" : "Impossible d’ajouter un signet",
	"sbnConnectionError" : "Perte de connexion au réseau",
	"sbnConnectivityError" : "Connectivité insuffisante",
	"sbnMobileDeviceError" : "Erreur du dispositif mobile",
	"sbnOverLimit" : "Limite passage au suivant atteinte",
	"sbnPandoraMaintErr" : "Erreur de serveur Pandora",
	"sbnRatingFailed" : "Impossible d’ajouter classification",
	"sbnStationDeleted" : "Pas de station en cours",
	"skip_Tooltip" : "Passer au suivant",
};

framework.registerAppDictLoaded("pandora", "fr_FR");