var Localization_xmdataAppDict_mn_TW = {
	//"stringId" : "localString"
	"24hToolTip" : "Today's Weather",
	"5DayWeather" : "5-Day Weather",
	"5dToolTip" : "6 day Weather",
	"AF_A" : "Volcanic Ashfall Watch",
	"AF_W" : "Ashfall Warning",
	"AF_Y" : "Volcanic Ashfall Advisory\t",
	"AQA" : "Air Quality Warning\t",
	"ARCF" : "Arctic Outflow Warning\t",
	"AS_A" : "Air Stagnation Watch",
	"AS_W" : "Air Stagnation Warning",
	"AS_Y" : "Air Stagnation Advisory",
	"AVAL" : "Avalanche Warning\t",
	"AV_A" : "Avalanche Watch",
	"AV_W" : "Avalanche Warning",
	"AV_Y" : "Avalanche Advisory",
	"AWW" : "Aviation Weather\t",
	"AccountNo" : "Radio ID: {XMSerialNumber}",
	"AddStock" : "Add a Stock",
	"Alabama" : "Alabama",
	"Alaska" : "Alaska",
	"AlertNotifications" : "Alert Notifications",
	"Alerts" : "Alerts",
	"AllBrands" : "All Brands",
	"ApplicationsTooltip" : "Applications",
	"Arizona" : "Arizona",
	"Arkansas" : "Arkansas",
	"AwayTooltip" : "Away",
	"BS_A" : "Blowing/Drifting Snow Watch",
	"BS_W" : "Snow Warning",
	"BS_Y" : "Snow Advisory",
	"BW_A" : "Brisk Wind Watch",
	"BW_W" : "Wind Warning",
	"BW_Y" : "Brisk Wind Advisory",
	"BZ_A" : "Blizzard Watch",
	"BZ_W" : "Blizzard Warning",
	"BZ_Y" : "Blizzard Advisory",
	"Back" : "Back",
	"Blizzard" : "Blizzard",
	"BlowingDust" : "Blowing Dust",
	"BlowingSnow" : "Blowing Snow",
	"Blustery" : "Blustery",
	"BrandPreference" : "Brand Preferences",
	"CAE" : "Child Abduction Emergency \t",
	"CA_E" : "Child Abduction Emergency\t",
	"CDWV" : "Cold Wave Warning\t",
	"CFNL" : "Cold-Core Funnel Warning\t",
	"CF_A" : "Coastal Flood Watch",
	"CF_W" : "Flood Warning",
	"CF_Y" : "Coastal Flood Advisory",
	"CONV" : "Severe Convective Activity Warning\t",
	"California" : "California",
	"Call" : "Call",
	"Cancel" : "Cancel",
	"Celsius" : "°C",
	"ChangeCity" : "Change City ",
	"ChangeCurrentCity" : "Change Current City",
	"ChangeCurrentCityTooltip" : "Change Current City",
	"CityList" : "City List",
	"CityListisNotAvailable" : "City List not available",
	"CityName" : "{CityName}",
	"ClearNight" : "Clear Night",
	"Cloudy" : "Cloudy",
	"Cold" : "Cold",
	"Colorado" : "Colorado",
	"Connecticut" : "Connecticut",
	"CurrentDaily" : "Current Daily",
	"CurrentHourly" : "Current Hourly",
	"CurrentWeather" : "Current Weather",
	"DF_A" : "Debris Flow Watch",
	"DF_W" : "Debris Flow Warning",
	"DF_Y" : "Debris Flow Advisory",
	"DS_A" : "Dust Storm Watch",
	"DS_W" : "Dust Storm Warning",
	"DS_Y" : "Dust Storm Advisory",
	"DU_A" : "Blowing Dust Watch",
	"DU_W" : "Blowing Dust Warning",
	"DU_Y" : "Blowing Dust Advisory",
	"Daily" : "Daily",
	"DayAgo" : "{Days} Days Ago",
	"Delaware" : "Delaware",
	"Details" : "Details",
	"Diesel" : "Diesel",
	"Distance" : "Distance",
	"DistrictofColumbia" : "District of Columbia",
	"Drizzle" : "Drizzle",
	"Dust" : "Dust",
	"EC_A" : "Extreme Cold Watch\t",
	"EC_W" : "Cold Warning",
	"EC_Y" : "Extreme Cold Advisory\t",
	"EH_A" : "Excessive Heat Watch\t",
	"EH_W" : "Excessive Heat Warning\t",
	"EH_Y" : "Excessive Heat Advisory\t",
	"EQW" : "Earthquake Warning\t",
	"EVI" : "Immediate Evacuation Warning\t",
	"EditStocks" : "Edit Stocks",
	"ElectricDC" : "Electric DC",
	"ElectricL1120V" : "Electric L1 120V",
	"ElectricL2240V" : "Electric L2 240V",
	"EnterTicker" : "Enter Stock Identifier",
	"EventDaily" : "Event Daily",
	"EventHourly" : "Event Hourly",
	"EventListisTemporarilyUnavailable" : "Event List is temporarily unavailable. ",
	"FA_A" : "Areal Flood Watch\t",
	"FA_W" : "Areal Flood Warning\t",
	"FA_Y" : "Areal Flood Advisory\t",
	"FDRZ" : "Freezing Drizzle Warning\t",
	"FFRZ" : "Flash Freeze Warning\t",
	"FF_A" : "Flash Flood Watch\t",
	"FF_W" : "Flash Flood Warning\t",
	"FF_Y" : "Flash Flood Advisory\t",
	"FGSM" : "Fog-Smoke Warning\t",
	"FG_A" : "Dense Fog Watch\t",
	"FG_W" : "Dense Fog Warning\t",
	"FG_Y" : "Dense Fog Advisory\t",
	"FL_A" : "Flood Watch\t",
	"FL_W" : "Flood Warning\t",
	"FL_Y" : "Flood Advisory\t",
	"FNLC" : "Funnel Cloud Warning\t",
	"FRW" : "Fire Warning\t",
	"FR_A" : "Frost Watch\t",
	"FR_W" : "Frost Warning\t",
	"FR_Y" : "Frost Advisory\t",
	"FW_A" : "Fire Weather Watch\t",
	"FW_W" : "Fire Weather Warning\t",
	"FW_Y" : "Fire Weather Advisory\t",
	"FZ_A" : "Freeze Watch\t",
	"FZ_W" : "Freeze Warning\t",
	"FZ_Y" : "Freeze Advisory\t",
	"Farenheit" : "°F",
	"Florida" : "Florida",
	"Flurries" : "Flurries",
	"Foggy" : "Foggy",
	"ForSafetyReasonsNoDataWillBeDisplayedWhileDriving" : "For safety reasons, no data will be displayed while driving. ",
	"FreezingDrizzle" : "Freezing Drizzle",
	"FreezingRain" : "Freezing Rain",
	"FuelPrices" : "Fuel Prices",
	"FuelSettings" : "Fuel Settings",
	"FuelTypePreference" : "Fuel Type Preference",
	"FunnelCloud" : "Funnel Cloud",
	"GL_A" : "Gale Watch\t",
	"GL_W" : "Gale Warning\t",
	"GL_Y" : "Gale Advisory\t",
	"GNWX" : "General Weather Warning\t",
	"Georgia" : "Georgia",
	"HF_A" : "Hurricane Force Wind Watch\t",
	"HF_W" : "Hurricane Force Wind Warning\t",
	"HF_Y" : "Hurricane Force Wind Advisory\t",
	"HI_A" : "Inland Hurricane Watch\t",
	"HI_W" : "Inland Hurricane Warning\t",
	"HI_Y" : "Inland Hurricane Advisory\t",
	"HMDX" : "combined Heat and Humidity Warning\t",
	"HMW" : "Hazardous Materials Warning\t",
	"HP_A" : "Heavy Sleet Watch\t",
	"HP_W" : "Heavy Sleet Warning\t",
	"HP_Y" : "Heavy Sleet Advisory\t",
	"HS_A" : "Heavy Snow Watch\t",
	"HS_W" : "Heavy Snow Warning\t",
	"HS_Y" : "Heavy Snow Advisory\t",
	"HTHM" : "High Heat and Humidity Warning\t",
	"HT_A" : "Heat Watch\t",
	"HT_W" : "Heat Warning\t",
	"HT_Y" : "Heat Advisory\t",
	"HU_A" : "Hurricane Watch\t",
	"HU_W" : "Hurricane Warning\t",
	"HU_Y" : "Hurricane Advisory\t",
	"HVRN" : "Heavy Rain Warning\t",
	"HW_A" : "High Wind Watch\t",
	"HW_W" : "High Wind Warning\t",
	"HW_Y" : "High Wind Advisory\t",
	"HY_A" : "Hydrologic Watch\t",
	"HY_W" : "Hydrologic Warning\t",
	"HY_Y" : "Hydrologic Advisory\t",
	"HZ_A" : "Hard Freeze Watch\t",
	"HZ_W" : "Hard Freeze Warning\t",
	"HZ_Y" : "Hard Freeze Advisory\t",
	"Hail" : "Hail",
	"HailWarning" : "Hail Warning\t",
	"Hawaii" : "Hawaii",
	"Hazy" : "Hazy",
	"HeavyFog" : "Heavy Fog",
	"HeavyRain" : "Heavy Rain",
	"HeavySnow" : "Heavy Snow",
	"HomeTooltip" : "Home",
	"Hot" : "Hot",
	"Hourly" : "Hourly",
	"HourlyPrice" : "Hourly Price",
	"Humidity" : "Humidity",
	"Hurricane" : "Hurricane",
	"IP_A" : "Sleet Watch\t",
	"IP_W" : "Sleet Warning\t",
	"IP_Y" : "Sleet Advisory\t",
	"IS_A" : "Ice Storm Watch\t",
	"IS_W" : "Ice Storm Warning\t",
	"IS_Y" : "Ice Storm Advisory\t",
	"IcePellets" : "Ice Pellets",
	"Idaho" : "Idaho",
	"Illinois" : "Illinois",
	"Indiana" : "Indiana",
	"Iowa" : "Iowa",
	"IsolatedThunderstorms" : "Isolated Thunderstorms",
	"Kansas" : "Kansas",
	"Kentucky" : "Kentucky",
	"LB_A" : "Lake Effect Snow and Blowing Snow Watch\t",
	"LB_W" : "Lake Effect Snow and Blowing Snow Warning\t",
	"LB_Y" : "Lake Effect Snow and Blowing Snow Advisory\t",
	"LDSP" : "Landspout Warning\t",
	"LEW" : "Law Enforcement Warning\t",
	"LE_A" : "Lake Effect Snow Watch\t",
	"LE_W" : "Lake Effect Snow Warning\t",
	"LE_Y" : "Lake Effect Snow Advisory\t",
	"LO_A" : "Low Water Watch\t",
	"LO_W" : "Low Water Warning\t",
	"LO_Y" : "Low Water Advisory\t",
	"LSWI" : "Les Suetes Wind Warning\t",
	"LS_A" : "Lakeshore Flood Watch\t",
	"LS_W" : "Lakeshore Flood Warning\t",
	"LS_Y" : "Lakeshore Flood Advisory\t",
	"LW_A" : "Lake Wind Watch\t",
	"LW_W" : "Lake Wind Warning\t",
	"LW_Y" : "Lake Wind Advisory\t",
	"LeagueListisTemporarilyUnavailable" : "League List is temporarily unavailable.",
	"LightFog" : "Light Fog",
	"LightRain" : "Light Rain",
	"LightSnow" : "Light Snow",
	"ListenNow" : "Listen Now",
	"LotFull" : "Lot Full",
	"Louisiana" : "Louisiana",
	"MA_A" : "Marine Watch\t",
	"MA_W" : "Marine Warning\t",
	"MA_Y" : "Marine Advisory\t",
	"MF_A" : "Marine Dense Fog Watch\t",
	"MF_W" : "Marine Dense Fog Warning\t",
	"MF_Y" : "Marine Dense Fog Advisory\t",
	"MH_A" : "Marine Ashfall Watch\t",
	"MH_W" : "Marine Ashfall Warning\t",
	"MH_Y" : "Marine Ashfall Advisory\t",
	"MRWI" : "Marine Wind Warning\t",
	"MS_A" : "Marine Dense Smoke Watch\t",
	"MS_W" : "Marine Dense Smoke Warning\t",
	"MS_Y" : "Marine Dense Smoke Advisory\t",
	"Maine" : "Maine",
	"Maryland" : "Maryland",
	"Massachusetts" : "Massachusetts",
	"MatchInfo" : "Match Info",
	"Michigan" : "Michigan",
	"MidGrade" : "Mid-Grade",
	"Midrange" : "Midrange",
	"Minnesota" : "Minnesota",
	"Mississippi" : "Mississippi",
	"Missouri" : "Missouri",
	"Mist" : "Mist",
	"MixedRainAndHail" : "Mixed Rain And Hail",
	"MixedRainAndSleet" : "Mixed Rain And Sleet",
	"MixedRainAndSnow" : "Mixed Rain And Snow",
	"ModerateFog" : "Moderate Fog",
	"ModerateSnow" : "Moderate Snow",
	"Montana" : "Montana",
	"MostlyClearNight" : "Mostly Clear Night",
	"MostlyCloudy" : "Mostly Cloudy",
	"MostlyCloudyNight" : "Mostly Cloudy Night",
	"MostlySunny" : "Mostly Sunny",
	"Movies" : "Movies",
	"NUW" : "Nuclear Power Plant Warning\t",
	"NationalTooltip" : "National",
	"NearestCity" : "Nearest City",
	"Nebraska" : "Nebraska",
	"Nevada" : "Nevada",
	"NewHampshire" : "New Hampshire",
	"NewJersey" : "New Jersey",
	"NewMexico" : "New Mexico",
	"NewYork" : "New York",
	"NextDay" : "Next day",
	"NextGame" : "Next Game",
	"NextMovie" : "Next Movie",
	"NoAlertsFound" : "No alerts found",
	"NoEventsInProgress" : "No events in progress",
	"NoFinalEvents" : "No final events",
	"NoParkinglotsfoundinrange" : "No parking lots found in range",
	"NoScheduledEvents" : "No scheduled events",
	"Nofuelstationsfoundinrange" : "No fuel stations found in range",
	"NorthCarolina" : "North Carolina",
	"NorthDakota" : "North Dakota",
	"Notheaterfoundinrange" : "No theaters found in range",
	"NowIn" : "Now in {CityName}",
	"NowTooltip" : "Current Weather",
	"Now_3_6" : "Now 3/6",
	"Ohio" : "Ohio",
	"Oklahoma" : "Oklahoma",
	"OneDayAgo" : "One Day Ago",
	"Oregon" : "Oregon",
	"OutofFuel" : "Out of Fuel",
	"PUBS" : "Civil Emergency or Danger Statement\t",
	"Parking" : "Parking",
	"PartlyCloudy" : "Partly Cloudy",
	"PartlyCloudyNight" : "Partly Cloudy Night",
	"Pennsylvania" : "Pennsylvania",
	"Percent" : "%",
	"Premium" : "Premium",
	"PreviousDay" : "Previous day",
	"PreviousGame" : "Previous Game",
	"PreviousMovie" : "Previous Movie",
	"Price" : "Price",
	"PricingRate" : "Pricing Rate",
	"RB_A" : "Small Craft for Rough Bar Watch\t",
	"RB_W" : "Small Craft for Rough Bar Warning\t",
	"RB_Y" : "Small Craft for Rough Bar Advisory\t",
	"RHW" : "Radiological Hazard Warning\t",
	"RH_A" : "Radiological Hazard Watch\t",
	"RH_W" : "Radiological Hazard Warning\t",
	"RH_Y" : "Radiological Hazard Advisory\t",
	"RNFL" : "Rainfall Warning\t",
	"Rain" : "Rain",
	"Rate" : "Rate",
	"RecentCities" : "Recent Cities",
	"RecentCitiesnotavailble" : "Recent Cities not available",
	"Regular" : "Regular",
	"RelativeDaily" : "Relative Daily",
	"RelativeHourly" : "Relative Hourly",
	"Remaining" : "Remaining",
	"Remove" : "Remove",
	"RemoveStock" : "Remove Stock?",
	"RemoveStockDisplay" : "Remove stock ",
	"RenewSubscription" : "Renew your subscription by calling SXM at {XMPhoneNumber}. ",
	"RhodeIsland" : "Rhode Island",
	"RouteTo" : "Route to",
	"SB_A" : "Snow and Blowing Snow Watch\t",
	"SB_W" : "Snow and Blowing Snow Warning\t",
	"SB_Y" : "Snow and Blowing Snow Advisory\t",
	"SC_A" : "Small Craft Watch\t",
	"SC_W" : "Small Craft Warning\t",
	"SC_Y" : "Small Craft Advisory\t",
	"SE_A" : "Hazardous Seas Watch\t",
	"SE_W" : "Hazardous Seas Warning\t",
	"SE_Y" : "Hazardous Seas Advisory\t",
	"SI_A" : "Small Craft for Winds Watch\t",
	"SI_W" : "Small Craft for Winds Warning\t",
	"SI_Y" : "Small Craft for Winds Advisory\t",
	"SLWX" : "Severe Local Storm Warning\t",
	"SM_A" : "Dense Smoke Watch\t",
	"SM_W" : "Dense Smoke Warning\t",
	"SM_Y" : "Dense Smoke Advisory\t",
	"SNSQ" : "Snow Squall Warning\t",
	"SN_A" : "Snow Watch\t",
	"SN_W" : "Snow Warning\t",
	"SN_Y" : "Snow Advisory\t",
	"SPW" : "Shelter in-Place Warning\t",
	"SPWX" : "Special Weather Warning\t",
	"SR_A" : "Storm Watch\t",
	"SR_W" : "Storm Warning\t",
	"SR_Y" : "Storm Advisory\t",
	"SSRG" : "Storm Surge Warning\t",
	"SU_A" : "High Surf Watch\t",
	"SU_W" : "High Surf Warning\t",
	"SU_Y" : "High Surf Advisory\t",
	"SVCO" : "Significant Severe Convective Activity Warning\t",
	"SVHA" : "Significant Severe Hail Warning\t",
	"SVTO" : "Significant Severe Tornado Warning\t",
	"SVWI" : "Severe Wind Warning\t",
	"SVWX" : "Severe Weather Warning\t",
	"SV_A" : "Severe Thunderstorm Watch\t",
	"SV_W" : "Severe Thunderstorm Warning\t",
	"SV_Y" : "Severe Thunderstorm Advisory\t",
	"SW_A" : "Small Craft for Hazardous Seas Watch\t",
	"SW_W" : "Small Craft for Hazardous Seas Warning\t",
	"SW_Y" : "Small Craft for Hazardous Seas Advisory\t",
	"SXMNoStocksAdded" : "No Stocks Added",
	"SXMWeatherAndSecurityAlerts" : "SXM Weather and Security Alerts",
	"Sandstorm" : "Sandstorm",
	"ScatteredShowers" : "Scattered Showers",
	"ScatteredShowersNight" : "Scattered Showers Night",
	"ScatteredSnowShowers" : "Scattered Snow Showers",
	"ScatteredSnowShowersNight" : "Scattered Snow Showers Night",
	"ScatteredThunderstorms" : "Scattered Thunderstorms",
	"ScatteredThunderstormsNight" : "Scattered Thunderstorms Night",
	"SelectCity" : "Select City",
	"SelectEvent" : "Select Event",
	"SelectLeague" : "Select League",
	"SelectSport" : "Select Sport",
	"SelectSportIsTemporarilyUnavailable" : "Select Sport is temporarily unavailable. ",
	"SelectState" : "Select State or Province",
	"SelectStocktoRemove" : "Select stock to remove",
	"SelectTeam" : "Select Team",
	"Settings" : "Settings",
	"SevereThunderstorms" : "Severe Thunderstorms",
	"Showers" : "Showers",
	"Sleet" : "Sleet",
	"Smoky" : "Smoky",
	"Snow" : "Snow",
	"SnowShowers" : "Snow Showers",
	"SouthCarolina" : "South Carolina",
	"SouthDakota" : "South Dakota",
	"SpacesAvailable" : "Spaces Available ",
	"SpecialEvent" : "Special Event",
	"Sports" : "Sports",
	"StateListisnotavailable" : "State or Province List is not available",
	"StockAlreadyIncluded" : "Stock already included in List. ",
	"StockDeleted" : "Stock Deleted",
	"StockNotFound" : "Stock not found.",
	"StockRemoved" : "Stock Removed.",
	"StockRemovedDisplay" : "Remove stock",
	"Stocks" : "Stocks",
	"Sunny" : "Sunny",
	"Synopsis" : "Synopsis",
	"SynopsisTooltip" : "Synopsis",
	"TI_A" : "Inland Tropical Storm Watch\t",
	"TI_W" : "Inland Tropical Storm Warning\t",
	"TI_Y" : "Inland Tropical Storm Advisory\t",
	"TOE" : "Telephone Outage Emergency\t",
	"TO_A" : "Tornado Watch\t",
	"TO_W" : "Tornado Warning\t",
	"TO_Y" : "Tornado Advisory\t",
	"TR_A" : "Tropical Storm Watch\t",
	"TR_W" : "Tropical Storm Warning\t",
	"TR_Y" : "Tropical Storm Advisory\t",
	"TSTM" : "General Thunderstorm Warning\t",
	"TS_A" : "Tsunami Watch\t",
	"TS_W" : "Tsunami Warning\t",
	"TS_Y" : "Tsunami Advisory\t",
	"TWNowSetup" : "Traffic and Weather Alert",
	"TY_A" : "Typhoon Watch\t",
	"TY_W" : "Typhoon Warning\t",
	"TY_Y" : "Typhoon Advisory\t",
	"TeamListIsTemporarilyUnavailable" : "Team list is temporarily unavailable.",
	"Tennessee" : "Tennessee",
	"Texas" : "Texas",
	"Thunderstorms" : "Thunderstorms",
	"Today" : "Today",
	"TodayIn" : "Today in {CityName}",
	"TodaysWeather" : "Today's Weather",
	"Tornado" : "Tornado",
	"Traffic" : "Traffic",
	"TrafficPlus" : "Traffic Plus",
	"TropicalStorm" : "Tropical Storm",
	"TuneAwayBroadcast" : "Tune to Away Broadcast",
	"TuneHomeBroadcast" : "Tune to Home Broadcast",
	"TuneNationalBroadcast" : "Tune to National Broadcast",
	"UP_A" : "Heavy Freezing Spray Watch\t",
	"UP_W" : "Heavy Freezing Spray Warning\t",
	"UP_Y" : "Heavy Freezing Spray Advisory\t",
	"UVRD" : "Ultra-Violet Warning\t",
	"UnknownPrecipitation" : "Unknown Precipitation",
	"Updated:" : "Updated:  ",
	"Utah" : "Utah",
	"VOW" : "Volcano Warning\t",
	"VO_A" : "Volcano Watch\t",
	"VO_W" : "Volcano Warning\t",
	"VO_Y" : "Volcano Advisory\t",
	"Vermont" : "Vermont",
	"View" : "View",
	"Virginia" : "Virginia",
	"WC_A" : "Wind Chill Watch\t",
	"WC_W" : "Wind Chill Warning\t",
	"WC_Y" : "Wind Chill Advisory\t",
	"WI_A" : "Wind Watch\t",
	"WI_W" : "Wind Warning\t",
	"WI_Y" : "Wind Advisory\t",
	"WRWI" : "Wreckhouse Wind Warning\t",
	"WS_A" : "Winter Storm Watch\t",
	"WS_W" : "Winter Storm Warning\t",
	"WS_Y" : "Winter Storm Advisory\t",
	"WTSP" : "Waterspout Warning\t",
	"WW_A" : "Winter Weather Watch\t",
	"WW_W" : "Winter Weather Warning\t",
	"WW_Y" : "Winter Weather Advisory\t",
	"Washington" : "Washington",
	"Weather" : "Weather  ",
	"WeatherAndSecurityAlerts" : "Weather and Security Alerts",
	"WeatherForecast" : "Weather Forecast",
	"WeatherRadar" : "Weather Radar",
	"WeatherfortheselectedCityisnotAvailable" : "Weather for the selected city is not available",
	"WestVirginia" : "West Virginia",
	"Wind" : "Wind",
	"Windy" : "Windy",
	"WintryMix" : "Wintry Mix",
	"Wisconsin" : "Wisconsin",
	"Wyoming" : "Wyoming",
	"XMAlerts" : "SXM Alerts",
	"XMFuelPrices" : "SXM Fuel Prices",
	"XMLastTeam" : "Last Viewed Teams",
	"XMLeagueOffSeason" : "League currently in Off Season",
	"XMMovies" : "SXM Movies",
	"XMParking" : "SXM Parking",
	"XMServiceLoading" : "{Selected Service} Loading . . .",
	"XMServices" : "SiriusXM Services",
	"XMServicesTooltip" : "SiriusXM Services",
	"XMSportNext" : "Next Event",
	"XMSportNoSchedule" : "There are no Scheduled Games or Events for the Selected Sport.",
	"XMSportOffSeason" : "The Selected Sport or Event is in the Off Season",
	"XMSportPrevious" : "Previous Event",
	"XMSports" : "SXM Sports",
	"XMStockDelay" : "All Stock Data may be delayed up to 15 minutes.",
	"XMStockLimit" : "Limited to 20 stocks",
	"XMStocks" : "SXM Stocks",
	"XMSubscriptionExpired" : "Your <Service> Subscription has Expired. Calling SiriusXM at {XMPhoneNumber}.",
	"XMSubscriptionExpiring" : "Your SiriusXM Subscription Expires in {days} Days. ",
	"XMTeams" : "Scheduled Teams",
	"XMTraffic" : "SXM Traffic",
	"XMWeather" : "SXM Weather  ",
	"XMWeatherForecast" : "SXM Weather Forecast",
	"XMWeatherRadar" : "SXM Weather Radar",
	"ZF_A" : "Freezing Fog Watch\t",
	"ZF_W" : "Freezing Fog Warning\t",
	"ZF_Y" : "Freezing Fog Advisory\t",
	"ZR_A" : "Freezing Rain Snow Watch\t",
	"ZR_W" : "Freezing Rain Warning\t",
	"ZR_Y" : "Freezing Rain Advisory\t",
	"ZY_A" : "Freezing Spray Watch\t",
	"ZY_W" : "Freezing Spray Warning\t",
	"ZY_Y" : "Freezing Spray Advisory\t",
	"ZoomIn" : "Zoom In",
	"ZoomOut" : "Zoom Out",
	"for" : "for",
};

framework.registerAppDictLoaded("xmdata", "mn_TW");