var Localization_xmdataAppDict_fr_CN = {
	//"stringId" : "localString"
	"24hToolTip" : "Météo du jour",
	"5DayWeather" : "Prévisions météo 5 jours",
	"5dToolTip" : "Météo à 6 jours",
	"AF_A" : "Veille retombées volcaniques",
	"AF_W" : "Alerte retombées volcaniques",
	"AF_Y" : "Conseils retombées volcaniques\t",
	"AQA" : "Mise en garde qualité de l'air\t",
	"ARCF" : "Mise en garde écoulement arctique\t",
	"AS_A" : "Veille stagnation de l'air",
	"AS_W" : "Mise en garde ",
	"AS_Y" : "Conseils stagnation de l'air",
	"AVAL" : "Mise en garde avalanche\t",
	"AV_A" : "Veille avalanche",
	"AV_W" : "Mise en garde avalanche",
	"AV_Y" : "Conseils avalanche",
	"AWW" : "Météo aviation\t",
	"AccountNo" : "ID Radio: {XMSerialNumber}",
	"AddStock" : "Ajouter un titre boursier",
	"Alabama" : "Alabama",
	"Alaska" : "Alaska",
	"AlertNotifications" : "Notifications d'alerte",
	"Alerts" : "Alertes",
	"AllBrands" : "Toutes les marques ",
	"ApplicationsTooltip" : "Applications",
	"Arizona" : "Arizona",
	"Arkansas" : "Arkansas",
	"AwayTooltip" : "Absent",
	"BS_A" : "Veille poudrerie/poudrerie basse",
	"BS_W" : "Mise en garde neige",
	"BS_Y" : "Conseils neige",
	"BW_A" : "Veille coups de vent",
	"BW_W" : "Mise en garde vent",
	"BW_Y" : "Conseils coups de vent",
	"BZ_A" : "Veille blizzard",
	"BZ_W" : "Mise en garde blizzard",
	"BZ_Y" : "Conseils blizzard",
	"Back" : "Retour",
	"Blizzard" : "Blizzard",
	"BlowingDust" : "Chasse-poussière élevée",
	"BlowingSnow" : "poudrerie",
	"Blustery" : "Rafales",
	"BrandPreference" : "Préférence de marque",
	"CAE" : "Urgence enlèvement d'enfant \t",
	"CA_E" : "Urgence enlèvement d'enfant\t",
	"CDWV" : "Mise en garde vague de froid\t",
	"CFNL" : "Mise en garde entonnoir de trombe froid\t",
	"CF_A" : "Veille inondations côtières",
	"CF_W" : "Mise en garde inondations",
	"CF_Y" : "Conseils inondations côtières",
	"CONV" : "Mise en garde activité de convection importante\t",
	"California" : "Californie",
	"Call" : "Appeler",
	"Cancel" : "Annuler",
	"Celsius" : "° C",
	"ChangeCity" : "Changer de ville ",
	"ChangeCurrentCity" : "Changer de ville",
	"ChangeCurrentCityTooltip" : "Changer de ville",
	"CityList" : "Liste des villes",
	"CityListisNotAvailable" : "Liste des villes non disponible",
	"CityName" : "{CityName}",
	"ClearNight" : "Nuit claire",
	"Cloudy" : "Nuageux",
	"Cold" : "Froid",
	"Colorado" : "Colorado",
	"Connecticut" : "Connecticut",
	"CurrentDaily" : "Actuel, par jour",
	"CurrentHourly" : "Actuel, par heure",
	"CurrentWeather" : "Météo actuelle",
	"DF_A" : "Veille avalanche de débris",
	"DF_W" : "Mise en garde avalanche de débris",
	"DF_Y" : "Conseils avalanche de débris",
	"DS_A" : "Veille tempête de poussière",
	"DS_W" : "Mise en garde tempête de poussière",
	"DS_Y" : "Conseils tempête de poussière",
	"DU_A" : "Veille chasse-poussière élevée",
	"DU_W" : "Mise en garde chasse-poussière élevée",
	"DU_Y" : "Conseils chasse-poussière élevée",
	"Daily" : "Quotidien",
	"DayAgo" : "il y a {Days} jours",
	"Delaware" : "Delaware",
	"Details" : "Détails",
	"Diesel" : "Diesel",
	"Distance" : "Distance",
	"DistrictofColumbia" : "District de Columbia",
	"Drizzle" : "Bruine",
	"Dust" : "Poussière",
	"EC_A" : "Veille froid extrême\t",
	"EC_W" : "Mise en garde froid",
	"EC_Y" : "Conseils froid extrême\t",
	"EH_A" : "Veille chaleur anormale\t",
	"EH_W" : "Mise en garde chaleur anormale\t",
	"EH_Y" : "Conseils chaleur anormale\t",
	"EQW" : "Mise en garde séisme\t",
	"EVI" : "Mise en garde évacuation immédiate\t",
	"EditStocks" : "Éditer le boursiers",
	"ElectricDC" : "Électrique CC",
	"ElectricL1120V" : "Électrique L1 120 V",
	"ElectricL2240V" : "Électrique L2 240 V",
	"EnterTicker" : "Entrer le symbole du titre boursier",
	"EventDaily" : "Tarif journée Évènement ",
	"EventHourly" : "Tarif horaire Évènement",
	"EventListisTemporarilyUnavailable" : "Liste Évènement temporairement indisponible. ",
	"FA_A" : "Veille inondation aréale\t",
	"FA_W" : "Mise en garde inondation aréale\t",
	"FA_Y" : "Conseils inondation aréale\t",
	"FDRZ" : "Mise en garde bruine verglaçante\t",
	"FFRZ" : "Mise en garde verglas éclair\t",
	"FF_A" : "Veille inondation éclair\t",
	"FF_W" : "Mise en garde inondation éclair\t",
	"FF_Y" : "Conseils inondation éclair\t",
	"FGSM" : "Mise en garde brouillard-fumée\t",
	"FG_A" : "Veille brume épaisse\t",
	"FG_W" : "Mise en garde brume épaisse\t",
	"FG_Y" : "Conseils brume épaisse\t",
	"FL_A" : "Veille inondations\t",
	"FL_W" : "Mise en garde inondations\t",
	"FL_Y" : "Conseils inondations\t",
	"FNLC" : "Mise en garde trombe\t",
	"FRW" : "Mise en garde feu\t",
	"FR_A" : "Veille gelée\t",
	"FR_W" : "Mise en garde gel\t",
	"FR_Y" : "Conseils gel\t",
	"FW_A" : "Veille conditions d'alerte météo\t",
	"FW_W" : "Mise en garde conditions d'alerte météo\t",
	"FW_Y" : "Conseils conditions d'alerte météo\t",
	"FZ_A" : "Veille gel\t",
	"FZ_W" : "Mise en garde gel\t",
	"FZ_Y" : "Conseils gel\t",
	"Farenheit" : " °F",
	"Florida" : "Floride",
	"Flurries" : "Averses",
	"Foggy" : "Brumeux",
	"ForSafetyReasonsNoDataWillBeDisplayedWhileDriving" : "Pour des raisons de sécurité, aucune donnée ne sera affichée pendant la conduite. ",
	"FreezingDrizzle" : "précipitations verglaçantes",
	"FreezingRain" : "Pluie verglaçante",
	"FuelPrices" : "Prix du carb.",
	"FuelSettings" : "Paramètres carburant",
	"FuelTypePreference" : "Préférence Type de carburant ",
	"FunnelCloud" : "Trombe",
	"GL_A" : "Veille vent violent\t",
	"GL_W" : "Mise en garde vent violent\t",
	"GL_Y" : "Conseils vent violent\t",
	"GNWX" : "Mise en garde météo générale\t",
	"Georgia" : "Géorgie",
	"HF_A" : "Veille vent d'ouragan\t",
	"HF_W" : "Mise en garde vent d'ouragan\t",
	"HF_Y" : "Conseils vent d'ouragan\t",
	"HI_A" : "Veille tornade\t",
	"HI_W" : "Mise en garde tornade\t",
	"HI_Y" : "Conseils tornade\t",
	"HMDX" : "Mise en garde chaleur et humidité\t",
	"HMW" : "Mise en garde matières dangereuses\t",
	"HP_A" : "Veille fortes giboulées\t",
	"HP_W" : "Mise en garde fortes giboulées\t",
	"HP_Y" : "Conseils fortes giboulées\t",
	"HS_A" : "Veille fortes chutes de neige\t",
	"HS_W" : "Mise en garde fortes chutes de neige\t",
	"HS_Y" : "Conseils fortes chutes de neige\t",
	"HTHM" : "Mise en garde forte chaleur et humidité\t",
	"HT_A" : "Veille chaleur\t",
	"HT_W" : "Mise en garde chaleur\t",
	"HT_Y" : "Conseils chaleur\t",
	"HU_A" : "Veille ouragan\t",
	"HU_W" : "Mise en garde ouragan\t",
	"HU_Y" : "Conseils ouragan\t",
	"HVRN" : "Mise en garde fortes pluies\t",
	"HW_A" : "Veille vents forts\t",
	"HW_W" : "Mise en garde vents forts\t",
	"HW_Y" : "Conseils vents forts\t",
	"HY_A" : "Veille hydrologique\t",
	"HY_W" : "Mise en garde hydrologique\t",
	"HY_Y" : "Conseils hydrologie\t",
	"HZ_A" : "Veille gelées dures\t",
	"HZ_W" : "Mise en garde gelées dures\t",
	"HZ_Y" : "Conseils gelées dures\t",
	"Hail" : "Grêle",
	"HailWarning" : "Mise en garde grêle\t",
	"Hawaii" : "Hawaï",
	"Hazy" : "Brumeux",
	"HeavyFog" : "Brume épaisse",
	"HeavyRain" : "Fortes pluies",
	"HeavySnow" : "Fortes chutes de neige",
	"HomeTooltip" : "Maison",
	"Hot" : "Chaud",
	"Hourly" : "Heure par heure",
	"HourlyPrice" : "Cotations horaires",
	"Humidity" : "Humidité",
	"Hurricane" : "Ouragan",
	"IP_A" : "Veille giboulées\t",
	"IP_W" : "Mise en garde giboulées\t",
	"IP_Y" : "Conseils giboulées\t",
	"IS_A" : "Veille tempête de verglas\t",
	"IS_W" : "Mise en garde tempête de verglas\t",
	"IS_Y" : "Conseils tempête de verglas\t",
	"IcePellets" : "Grésil",
	"Idaho" : "Idaho",
	"Illinois" : "Illinois",
	"Indiana" : "Indiana",
	"Iowa" : "Iowa",
	"IsolatedThunderstorms" : "Orages isolés",
	"Kansas" : "Kansas",
	"Kentucky" : "Kentucky",
	"LB_A" : "Veille tempête de neige d'effet de lac et poudrerie\t",
	"LB_W" : "Mise en garde tempête de neige d'effet de lac et poudrerie\t",
	"LB_Y" : "Conseils tempête de neige d'effet de lac et poudrerie\t",
	"LDSP" : "Mise en garde tornade terrestre\t",
	"LEW" : "Mise en garde forces de l'ordre\t",
	"LE_A" : "Veille tempête de neige d'effet de lac\t",
	"LE_W" : "Mise en garde tempête de neige d'effet de lac\t",
	"LE_Y" : "Conseils tempête de neige d'effet de lac\t",
	"LO_A" : "Veille étiage\t",
	"LO_W" : "Mise en garde étiage\t",
	"LO_Y" : "Conseils étiage\t",
	"LSWI" : "Mise en garde vents de Suête\t",
	"LS_A" : "Veille inondations de lac\t",
	"LS_W" : "Mise en garde inondations de lac\t",
	"LS_Y" : "Conseils inondations de lac\t",
	"LW_A" : "Veille vent de lac\t",
	"LW_W" : "Mise en garde vent de lac\t",
	"LW_Y" : "Conseils vent de lac\t",
	"LeagueListisTemporarilyUnavailable" : "Liste Ligue temporairement indisponible.",
	"LightFog" : "Brume",
	"LightRain" : "Pluie fine",
	"LightSnow" : "Neige légère",
	"ListenNow" : "Écouter maintenant",
	"LotFull" : "Plein",
	"Louisiana" : "Louisiane",
	"MA_A" : "Veille marine\t",
	"MA_W" : "Mise en garde marine\t",
	"MA_Y" : "Conseils marine\t",
	"MF_A" : "Veille brume épaisse marine\t",
	"MF_W" : "Mise en garde brume épaisse marine\t",
	"MF_Y" : "Conseils brume épaisse marine\t",
	"MH_A" : "Veille chute de cendres marine\t",
	"MH_W" : "Mise en garde chute de cendres marine\t",
	"MH_Y" : "Conseils chute de cendres marine\t",
	"MRWI" : "Mise en garde vent marin\t",
	"MS_A" : "Veille fumée épaisse marine\t",
	"MS_W" : "Mise en garde fumée épaisse marine\t",
	"MS_Y" : "Conseils fumée épaisse marine\t",
	"Maine" : "Maine",
	"Maryland" : "Maryland",
	"Massachusetts" : "Massachusetts",
	"MatchInfo" : "Info reliée ",
	"Michigan" : "Michigan",
	"MidGrade" : "Intermédiaire",
	"Midrange" : "Moyenne distance",
	"Minnesota" : "Minnesota",
	"Mississippi" : "Mississippi",
	"Missouri" : "Missouri",
	"Mist" : "Brume",
	"MixedRainAndHail" : "Pluie et grêle mélangées",
	"MixedRainAndSleet" : "Pluie et giboulées mélangées",
	"MixedRainAndSnow" : "Pluie et neige mélangées",
	"ModerateFog" : "Brouillard modéré",
	"ModerateSnow" : "Neige modérée",
	"Montana" : "Montana",
	"MostlyClearNight" : "Nuit dégagée dans l'ensemble",
	"MostlyCloudy" : "Nuageux dans l'ensemble",
	"MostlyCloudyNight" : "Nuit nuageuse dans l'ensemble",
	"MostlySunny" : "Ensoleillé dans l'ensemble",
	"Movies" : "Films",
	"NUW" : "Mise en garde centrale nucléaire\t",
	"NationalTooltip" : "National",
	"NearestCity" : "Ville la plus proche",
	"Nebraska" : "Nebraska",
	"Nevada" : "Nevada",
	"NewHampshire" : "New Hampshire",
	"NewJersey" : "New Jersey",
	"NewMexico" : "Nouveau Mexique",
	"NewYork" : "New York",
	"NextDay" : "Jour suivant",
	"NextGame" : "Match suivant",
	"NextMovie" : "Film suivant",
	"NoAlertsFound" : "Aucune alerte trouvée",
	"NoEventsInProgress" : "Aucun événement en cours",
	"NoFinalEvents" : "Aucun résultat final",
	"NoParkinglotsfoundinrange" : "Aucun parc de stationnement localisé à proximité",
	"NoScheduledEvents" : "Aucun événement programmé",
	"Nofuelstationsfoundinrange" : "Aucune station-service localisée à proximité",
	"NorthCarolina" : "Caroline du Nord",
	"NorthDakota" : "Dakota du Nord",
	"Notheaterfoundinrange" : "Aucune salle de spectacle localisée à proximité",
	"NowIn" : "Maintenant à {CityName}",
	"NowTooltip" : "Météo actuelle",
	"Now_3_6" : "Météo actuellement/à 3h/à 6h",
	"Ohio" : "Ohio",
	"Oklahoma" : "Oklahoma",
	"OneDayAgo" : "Il y a un jour",
	"Oregon" : "Oregon",
	"OutofFuel" : "Plus de carb.",
	"PUBS" : "Urgence civile ou déclaration de danger\t",
	"Parking" : "Parking",
	"PartlyCloudy" : "Partiellement couvert",
	"PartlyCloudyNight" : "Nuit partiellement couverte",
	"Pennsylvania" : "Pennsylvanie",
	"Percent" : "%",
	"Premium" : "Premier choix",
	"PreviousDay" : "Jour précédent",
	"PreviousGame" : "Match précédent",
	"PreviousMovie" : "Film précédent",
	"Price" : "Prix",
	"PricingRate" : "Tarifs",
	"RB_A" : "Veille barre dangereuse pour petites embarcations\t",
	"RB_W" : "Mise en garde barre dangereuse pour petites embarcations\t",
	"RB_Y" : "Conseils barre dangereuse pour petites embarcations\t",
	"RHW" : "Mise en garde danger d'irradiation\t",
	"RH_A" : "Veille danger d'irradiation\t",
	"RH_W" : "Mise en garde danger d'irradiation\t",
	"RH_Y" : "Conseils danger d'irradiation\t",
	"RNFL" : "Mise en garde chute de pluie\t",
	"Rain" : "Pluie",
	"Rate" : "Taux",
	"RecentCities" : "Villes récentes",
	"RecentCitiesnotavailble" : "Villes récentes non disponibles",
	"Regular" : "Régulier",
	"RelativeDaily" : "Quotidien relatif",
	"RelativeHourly" : "Horaire relatif",
	"Remaining" : "Restant",
	"Remove" : "Supprimer",
	"RemoveStock" : "Supprimer le titre boursier?",
	"RemoveStockDisplay" : "Supprimer le titre boursier ",
	"RenewSubscription" : "Renouveller votre abonnement en appellant au SXM {XMPhoneNumber}. ",
	"RhodeIsland" : "Rhode Island",
	"RouteTo" : "Aller à",
	"SB_A" : "Veille neige et poudrerie\t",
	"SB_W" : "Mise en garde neige et poudrerie\t",
	"SB_Y" : "Conseils neige et poudrerie\t",
	"SC_A" : "Veille petites embarcations\t",
	"SC_W" : "Mise en garde petites embarcations\t",
	"SC_Y" : "Conseils petites embarcations\t",
	"SE_A" : "Veille mer dangereuse\t",
	"SE_W" : "Mise en garde mer dangereuse\t",
	"SE_Y" : "Conseils mer dangereuse\t",
	"SI_A" : "Veille vent petites embarcations\t",
	"SI_W" : "Mise en garde vent petites embarcations\t",
	"SI_Y" : "Conseils vent petites embarcations\t",
	"SLWX" : "Mise en garde forte tempête locale\t",
	"SM_A" : "Veille fumée épaisse\t",
	"SM_W" : "Mise en garde fumée épaisse\t",
	"SM_Y" : "Conseils fumée épaisse\t",
	"SNSQ" : "Mise en garde rafales de neige\t",
	"SN_A" : "Veille neige\t",
	"SN_W" : "Mise en garde neige\t",
	"SN_Y" : "Conseils neige\t",
	"SPW" : "Mise en garde abri sur place\t",
	"SPWX" : "Mise en garde spéciale météo\t",
	"SR_A" : "Veille tempête\t",
	"SR_W" : "Mise en garde tempête\t",
	"SR_Y" : "Conseils tempête\t",
	"SSRG" : "Mise en garde onde de tempête\t",
	"SU_A" : "Veille ressac élevé\t",
	"SU_W" : "Mise en garde ressac élevé\t",
	"SU_Y" : "Conseils ressac élevé\t",
	"SVCO" : "Mise en garde forte activité de convection\t",
	"SVHA" : "Mise en garde forte grêle\t",
	"SVTO" : "Mise en garde forte tornade\t",
	"SVWI" : "Mise en garde vent fort\t",
	"SVWX" : "Mise en garde météo agitée\t",
	"SV_A" : "Veille orage fort\t",
	"SV_W" : "Mise en garde orage fort\t",
	"SV_Y" : "Conseils orage fort\t",
	"SW_A" : "Veille mer dangereuse petites embarcations\t",
	"SW_W" : "Mise en garde mer dangereuse petites embarcations\t",
	"SW_Y" : "Conseils mer dangereuse petites embarcations\t",
	"SXMNoStocksAdded" : "Aucun titre boursier ajouté",
	"SXMWeatherAndSecurityAlerts" : "Alertes météo et sécurité SXM",
	"Sandstorm" : "Tempête de sable",
	"ScatteredShowers" : "Averses éparses",
	"ScatteredShowersNight" : "Nuit avec averses éparses",
	"ScatteredSnowShowers" : "Averses de neige éparses",
	"ScatteredSnowShowersNight" : "Nuit avec averses de neige éparses",
	"ScatteredThunderstorms" : "Orages épars",
	"ScatteredThunderstormsNight" : "Nuit avec orages épars",
	"SelectCity" : "Choisir une ville",
	"SelectEvent" : "Sélectionner l'événement",
	"SelectLeague" : "Sélectionner la ligue",
	"SelectSport" : "Sélectionner le sport",
	"SelectSportIsTemporarilyUnavailable" : "Sélectionner le sport temporairement indisponible. ",
	"SelectState" : "Choisir État ou Province",
	"SelectStocktoRemove" : "Sélectionner un élément standard pour le retirer",
	"SelectTeam" : "Sélectionner l'équipe",
	"Settings" : "Paramètres SXM",
	"SevereThunderstorms" : "Orages violents",
	"Showers" : "Averses",
	"Sleet" : "Grésil",
	"Smoky" : "Fumé",
	"Snow" : "Neige",
	"SnowShowers" : "Averses de neige",
	"SouthCarolina" : "Caroline du Sud",
	"SouthDakota" : "Dakota du Sud",
	"SpacesAvailable" : "Places disponibles ",
	"SpecialEvent" : "Événement spécial",
	"Sports" : "Sports",
	"StateListisnotavailable" : "Liste des états/provinces non disponible",
	"StockAlreadyIncluded" : "Titre déjà inclus dans liste. ",
	"StockDeleted" : "Élément standard supprimé",
	"StockNotFound" : "Titre boursier introuvable.",
	"StockRemoved" : "Titre boursier supprimé.",
	"StockRemovedDisplay" : "Supprimer le titre boursier",
	"Stocks" : "Titres boursiers",
	"Sunny" : "Ensoleillé",
	"Synopsis" : "Synopsis",
	"SynopsisTooltip" : "Synopsis",
	"TI_A" : "Veille tempête tropicale intérieure\t",
	"TI_W" : "Mise en garde tempête tropicale intérieure\t",
	"TI_Y" : "Conseils tempête tropicale intérieure\t",
	"TOE" : "Urgence coupure de téléphone\t",
	"TO_A" : "Veille tornade\t",
	"TO_W" : "Mise en garde tornade\t",
	"TO_Y" : "Conseils tornade\t",
	"TR_A" : "Veille tempête tropicale\t",
	"TR_W" : "Mise en garde tempête tropicale\t",
	"TR_Y" : "Conseils tempête tropicale\t",
	"TSTM" : "Mise en garde générale orage\t",
	"TS_A" : "Veille tsunami\t",
	"TS_W" : "Mise en garde tsunami\t",
	"TS_Y" : "Conseils tsunami\t",
	"TWNowSetup" : "Alerte circulation et météo",
	"TY_A" : "Veille ouragan\t",
	"TY_W" : "Mise en garde ouragan\t",
	"TY_Y" : "Conseils ouragan\t",
	"TeamListIsTemporarilyUnavailable" : "Liste Équipe temporairement indisponible.",
	"Tennessee" : "Tennessee",
	"Texas" : "Texas",
	"Thunderstorms" : "Orages",
	"Today" : "Aujourd'hui",
	"TodayIn" : "Aujourd'hui à {CityName}",
	"TodaysWeather" : "Météo du jour",
	"Tornado" : "Tornade",
	"Traffic" : "Navigation",
	"TrafficPlus" : "Trafic Plus",
	"TropicalStorm" : "Tempête tropicale",
	"TuneAwayBroadcast" : "Syntoniser la diffusion à l'extérieur",
	"TuneHomeBroadcast" : "Syntoniser la diffusion à domicile",
	"TuneNationalBroadcast" : "Syntoniser la diffusion nationale",
	"UP_A" : "Veille forts embruns givrants\t",
	"UP_W" : "Mise en garde forts embruns givrants\t",
	"UP_Y" : "Conseils forts embruns givrants\t",
	"UVRD" : "Mise en garde ultraviolets\t",
	"UnknownPrecipitation" : "Précipitations inconnues",
	"Updated:" : "Mise à jour :  ",
	"Utah" : "Utah",
	"VOW" : "Mise en garde volcan\t",
	"VO_A" : "Veille volcan\t",
	"VO_W" : "Mise en garde volcan\t",
	"VO_Y" : "Conseils volcan\t",
	"Vermont" : "Vermont",
	"View" : "Afficher",
	"Virginia" : "Virginie",
	"WC_A" : "Veille refroidissement éolien\t",
	"WC_W" : "Mise en garde refroidissement éolien\t",
	"WC_Y" : "Conseils refroidissement éolien\t",
	"WI_A" : "Veille vent\t",
	"WI_W" : "Mise en garde vent\t",
	"WI_Y" : "Conseils vent\t",
	"WRWI" : "Mise en garde vent de Wreckhouse\t",
	"WS_A" : "Veille tempête hivernale\t",
	"WS_W" : "Mise en garde tempête hivernale\t",
	"WS_Y" : "Conseils tempête hivernale\t",
	"WTSP" : "Mise en garde trombe\t",
	"WW_A" : "Veille météo hivernale\t",
	"WW_W" : "Mise en garde météo hivernale\t",
	"WW_Y" : "Conseils météo hivernale\t",
	"Washington" : "Washington",
	"Weather" : "Navigation  ",
	"WeatherAndSecurityAlerts" : "Alertes Météo et Sécurité",
	"WeatherForecast" : "Prévisions météo",
	"WeatherRadar" : "Radar météo",
	"WeatherfortheselectedCityisnotAvailable" : "La météo n'est pas disponible pour la ville sélectionnée",
	"WestVirginia" : "Virginie occidentale",
	"Wind" : "Vent",
	"Windy" : "Venté",
	"WintryMix" : "Frimas",
	"Wisconsin" : "Wisconsin",
	"Wyoming" : "Wyoming",
	"XMAlerts" : "Alertes SXM",
	"XMFuelDetails" : "Types de carburant disponibles",
	"XMFuelPrices" : "Prix du carb. SXM",
	"XMLastTeam" : "Dernières équipes visualisées",
	"XMLeagueOffSeason" : "Ligue actuellement hors saison",
	"XMMovies" : "Films SXM",
	"XMParking" : "Parking SXM",
	"XMServiceLoading" : "{Selected Service} en cours de chargement",
	"XMServices" : "Services SiriusXM",
	"XMServicesTooltip" : "Services SiriusXM",
	"XMSportNext" : "Événement suivant",
	"XMSportNoSchedule" : "Aucun match/événement n'est programmé pour le sport sélectionné.",
	"XMSportOffSeason" : "Le sport ou l'événement sélectionné est hors saison",
	"XMSportPrevious" : "Événement précédent",
	"XMSports" : "Sports SXM",
	"XMStockDelay" : "Toutes les données boursières peuvent être retardées jusqu'à 20 minutes.",
	"XMStockLimit" : "Limite de 20 titres boursiers",
	"XMStocks" : "Bourse SXM",
	"XMSubscriptionExpired" : "Votre <Service> abonnement est expiré. Appeler SiriusXM au {XMPhoneNumber}",
	"XMSubscriptionExpiring" : "Votre abonnement à SiriusXM vient à échéance dans{days}  jours.   ",
	"XMTeams" : "Equipes planifiées",
	"XMTraffic" : "Circulation SXM",
	"XMWeather" : "Météo SXM  ",
	"XMWeatherForecast" : "Prévisions météo SXM",
	"XMWeatherRadar" : "Radar météo SXM",
	"ZF_A" : "Veille brouillard givrant\t",
	"ZF_W" : "Mise en garde brouillard givrant\t",
	"ZF_Y" : "Conseils brouillard givrant\t",
	"ZR_A" : "Veille précipitations verglaçantes\t",
	"ZR_W" : "Mise en garde pluie verglaçante\t",
	"ZR_Y" : "Conseils pluie verglaçante\t",
	"ZY_A" : "Veille embruns givrants\t",
	"ZY_W" : "Mise en garde embruns givrants\t",
	"ZY_Y" : "Conseils embruns givrants\t",
	"ZoomIn" : "Zoom avant",
	"ZoomOut" : "Zoom arrière",
	"for" : "pour",
};

framework.registerAppDictLoaded("xmdata", "fr_CN");