var Localization_xmdataAppDict_es_MX = {
	//"stringId" : "localString"
	"24hToolTip" : "Clima de hoy",
	"5DayWeather" : "Clima de 5 días",
	"5dToolTip" : "Clima a 6 días",
	"AF_A" : "Alerta sobre caída de ceniza volcánica",
	"AF_W" : "Advertencia sobre caída de ceniza volcánica",
	"AF_Y" : "Aviso sobre caída de ceniza volcánica\t",
	"AQA" : "Advertencia sobre la calidad del aire\t",
	"ARCF" : "Advertencia de ola de frío ártico\t",
	"AS_A" : "Alerta sobre estancamiento del aire",
	"AS_W" : "Advertencia sobre estancamiento del aire",
	"AS_Y" : "Aviso sobre estancamiento del aire",
	"AVAL" : "Advertencia de alud\t",
	"AV_A" : "Alerta de alud",
	"AV_W" : "Advertencia de alud",
	"AV_Y" : "Aviso de alud",
	"AWW" : "Condiciones climáticas para la aviación\t",
	"AccountNo" : "Identificación del Radio: {XMSerialNumber}",
	"AddStock" : "Añadir existencias",
	"Alabama" : "Alabama",
	"Alaska" : "Alaska",
	"AlertNotifications" : "Notificaciones de alerta",
	"Alerts" : "Alertas",
	"AllBrands" : "Todas las marcas",
	"ApplicationsTooltip" : "Aplicaciones",
	"Arizona" : "Arizona",
	"Arkansas" : "Arkansas",
	"AwayTooltip" : "De visitante",
	"BS_A" : "Alerta sobre tormenta/acumulación de nieve",
	"BS_W" : "Advertencia de nieve",
	"BS_Y" : "Aviso de nieve",
	"BW_A" : "Alerta de vientos frescos",
	"BW_W" : "Advertencia de viento",
	"BW_Y" : "Aviso de vientos frescos",
	"BZ_A" : "Alerta de tormenta de nieve",
	"BZ_W" : "Advertencia de tormenta de nieve",
	"BZ_Y" : "Aviso de tormenta de nieve",
	"Back" : "Atrás",
	"Blizzard" : "Tormenta de nieve",
	"BlowingDust" : "Tormenta de polvo",
	"BlowingSnow" : "Tormenta de nieve",
	"Blustery" : "Ráfagas de viento",
	"BrandPreference" : "Preferencias Marca",
	"CAE" : "Emergencia de secuestro infantil \t",
	"CA_E" : "Emergencia de secuestro infantil\t",
	"CDWV" : "Advertencia de ola de frío\t",
	"CFNL" : "Advertencia de embudo de aire frío\t",
	"CF_A" : "Alerta de inundación costera",
	"CF_W" : "Advertencia de inundación",
	"CF_Y" : "Aviso de inundación costera",
	"CONV" : "Advertencia de actividad convectiva severa\t",
	"California" : "California",
	"Call" : "Llamada",
	"Cancel" : "Cancelar",
	"Celsius" : "°C",
	"ChangeCity" : "Cambiar ciudad ",
	"ChangeCurrentCity" : "Cambiar ciudad actual",
	"ChangeCurrentCityTooltip" : "Cambiar ciudad actual",
	"CityList" : "Lista de ciudades",
	"CityListisNotAvailable" : "Lista de ciudades no disponible",
	"CityName" : "{CityName}",
	"ClearNight" : "Noche despejada",
	"Cloudy" : "Nublado",
	"Cold" : "Frío",
	"Colorado" : "Colorado",
	"Connecticut" : "Connecticut",
	"CurrentDaily" : "Actual a cada día",
	"CurrentHourly" : "Actual a cada hora",
	"CurrentWeather" : "Clima actual",
	"DF_A" : "Alerta sobre flujo de detritos",
	"DF_W" : "Advertencia sobre flujo de detritos",
	"DF_Y" : "Aviso sobre flujo de detritos",
	"DS_A" : "Alerta de tormenta de polvo",
	"DS_W" : "Advertencia de tormenta de polvo",
	"DS_Y" : "Aviso de tormenta de polvo",
	"DU_A" : "Alerta de tormenta de polvo",
	"DU_W" : "Advertencia de tormenta de polvo",
	"DU_Y" : "Aviso de tormenta de polvo",
	"Daily" : "A diario",
	"DayAgo" : "{Days} días atrás",
	"Delaware" : "Delaware",
	"Details" : "Detalles",
	"Diesel" : "Diésel",
	"Distance" : "Distancia",
	"DistrictofColumbia" : "Distrito de Columbia",
	"Drizzle" : "Llovizna",
	"Dust" : "Polvo",
	"EC_A" : "Alerta de frío extremo\t",
	"EC_W" : "Advertencia de frío",
	"EC_Y" : "Aviso de frío extremo\t",
	"EH_A" : "Alerta de calor excesivo\t",
	"EH_W" : "Advertencia de calor excesivo\t",
	"EH_Y" : "Aviso de calor excesivo\t",
	"EQW" : "Advertencia de terremoto\t",
	"EVI" : "Advertencia de evacuación inmediata\t",
	"EditStocks" : "Editar existencias",
	"ElectricDC" : "Eléctrico de CC",
	"ElectricL1120V" : "Eléctrico L1 de 120 V",
	"ElectricL2240V" : "Eléctrico L2 de 140 V",
	"EnterTicker" : "Ingresar identificador de existencias",
	"EventDaily" : "Evento a cada día",
	"EventHourly" : "Evento a cada hora",
	"EventListisTemporarilyUnavailable" : "La Lista de eventos no está disponible temporalmente. ",
	"FA_A" : "Alerta de inundación en el área\t",
	"FA_W" : "Advertencia de inundación en el área\t",
	"FA_Y" : "Aviso de inundación en el área\t",
	"FDRZ" : "Advertencia de llovizna gélida\t",
	"FFRZ" : "Advertencia de helada repentina\t",
	"FF_A" : "Alerta de inundación repentina\t",
	"FF_W" : "Advertencia de inundación repentina\t",
	"FF_Y" : "Aviso de inundación repentina\t",
	"FGSM" : "Advertencia de niebla y humo\t",
	"FG_A" : "Alerta de niebla espesa\t",
	"FG_W" : "Advertencia de niebla espesa\t",
	"FG_Y" : "Aviso de niebla espesa\t",
	"FL_A" : "Alerta de inundación\t",
	"FL_W" : "Advertencia de inundación\t",
	"FL_Y" : "Aviso de inundación\t",
	"FNLC" : "Advertencia de nube embudo\t",
	"FRW" : "Advertencia de incendio\t",
	"FR_A" : "Alerta de escarcha\t",
	"FR_W" : "Advertencia de escarcha\t",
	"FR_Y" : "Aviso de escarcha\t",
	"FW_A" : "Alerta de condiciones meteorológicas favorables para incendios\t",
	"FW_W" : "Advertencia de condiciones meteorológicas favorables para incendios\t",
	"FW_Y" : "Aviso de condiciones meteorológicas favorables para incendios\t",
	"FZ_A" : "Alerta de helada\t",
	"FZ_W" : "Advertencia de helada\t",
	"FZ_Y" : "Aviso de helada\t",
	"Farenheit" : "°F",
	"Florida" : "Florida",
	"Flurries" : "Ráfagas",
	"Foggy" : "Neblinoso",
	"ForSafetyReasonsNoDataWillBeDisplayedWhileDriving" : "Por razones de seguridad, no se mostrarán datos mientras conduce. ",
	"FreezingDrizzle" : "Llovizna gélida",
	"FreezingRain" : "Lluvia gélida",
	"FuelPrices" : "Precios del comb.",
	"FuelSettings" : "Configuraciones de combustible",
	"FuelTypePreference" : "Preferencia sobre Tipo de combustible",
	"FunnelCloud" : "Nube embudo",
	"GL_A" : "Alerta de vendaval\t",
	"GL_W" : "Advertencia de vendaval\t",
	"GL_Y" : "Aviso de vendaval\t",
	"GNWX" : "Advertencia del tiempo general\t",
	"Georgia" : "Georgia",
	"HF_A" : "Alerta de vientos huracanados\t",
	"HF_W" : "Advertencia de vientos huracanados\t",
	"HF_Y" : "Aviso de vientos huracanados\t",
	"HI_A" : "Alerta de huracán tierra adentro\t",
	"HI_W" : "Advertencia de huracán tierra adentro\t",
	"HI_Y" : "Aviso de huracán tierra adentro\t",
	"HMDX" : "Advertencia de calor y humedad\t",
	"HMW" : "Advertencia de materiales peligrosos\t",
	"HP_A" : "Alerta de aguanieve intensa\t",
	"HP_W" : "Advertencia de aguanieve intensa\t",
	"HP_Y" : "Aviso de aguanieve intensa\t",
	"HS_A" : "Alerta de nieve intensa\t",
	"HS_W" : "Advertencia de nieve intensa\t",
	"HS_Y" : "Aviso de nieve intensa\t",
	"HTHM" : "Advertencia de calor intenso y humedad\t",
	"HT_A" : "Alerta de calor\t",
	"HT_W" : "Advertencia de calor\t",
	"HT_Y" : "Aviso de calor\t",
	"HU_A" : "Alerta de huracán\t",
	"HU_W" : "Advertencia de huracán\t",
	"HU_Y" : "Aviso de huracán\t",
	"HVRN" : "Advertencia de lluvias intensas\t",
	"HW_A" : "Alerta de vientos fuertes\t",
	"HW_W" : "Advertencia de vientos fuertes\t",
	"HW_Y" : "Aviso de vientos fuertes\t",
	"HY_A" : "Alerta hidrológica\t",
	"HY_W" : "Advertencia hidrológica\t",
	"HY_Y" : "Aviso hidrológico\t",
	"HZ_A" : "Alerta de helada intensa\t",
	"HZ_W" : "Advertencia de helada intensa\t",
	"HZ_Y" : "Aviso de helada intensa\t",
	"Hail" : "Granizo",
	"HailWarning" : "Advertencia de granizo\t",
	"Hawaii" : "Hawái",
	"Hazy" : "Brumoso",
	"HeavyFog" : "Niebla intensa",
	"HeavyRain" : "Lluvias intensas",
	"HeavySnow" : "Nieve intensa",
	"HomeTooltip" : "De local",
	"Hot" : "Caluroso",
	"Hourly" : "A cada hora",
	"HourlyPrice" : "Precios por hora",
	"Humidity" : "Humedad",
	"Hurricane" : "Huracán",
	"IP_A" : "Alerta de aguanieve\t",
	"IP_W" : "Advertencia de aguanieve\t",
	"IP_Y" : "Aviso de aguanieve\t",
	"IS_A" : "Alerta de tormenta de hielo\t",
	"IS_W" : "Advertencia de tormenta de hielo\t",
	"IS_Y" : "Aviso de tormenta de hielo\t",
	"IcePellets" : "Perdigones de hielo",
	"Idaho" : "Idaho",
	"Illinois" : "Illinois",
	"Indiana" : "Indiana",
	"Iowa" : "Iowa",
	"IsolatedThunderstorms" : "Tormentas aisladas",
	"Kansas" : "Kansas",
	"Kentucky" : "Kentucky",
	"LB_A" : "Alerta de tormenta de nieve y nevada por efecto lacustre\t",
	"LB_W" : "Advertencia de tormenta de nieve y nevada por efecto lacustre\t",
	"LB_Y" : "Aviso de tormenta de nieve y nevada por efecto lacustre\t",
	"LDSP" : "Advertencia de tornado\t",
	"LEW" : "Advertencia de fuerza pública\t",
	"LE_A" : "Alerta de nevada por efecto lacustre\t",
	"LE_W" : "Advertencia de nevada por efecto lacustre\t",
	"LE_Y" : "Aviso de nevada por efecto lacustre\t",
	"LO_A" : "Alerta de marea baja\t",
	"LO_W" : "Advertencia de marea baja\t",
	"LO_Y" : "Aviso de marea baja\t",
	"LSWI" : "Advertencia de vientos de Les Suêtes\t",
	"LS_A" : "Alerta de inundación por lagos\t",
	"LS_W" : "Advertencia de inundación por lagos\t",
	"LS_Y" : "Aviso de inundación por lagos\t",
	"LW_A" : "Alerta de vientos en áreas lacustres\t",
	"LW_W" : "Advertencia de vientos en áreas lacustres\t",
	"LW_Y" : "Aviso de vientos en áreas lacustres\t",
	"LeagueListisTemporarilyUnavailable" : "La Lista de la liga no está disponible temporalmente.",
	"LightFog" : "Niebla ligera",
	"LightRain" : "Lluvia ligera",
	"LightSnow" : "Nieve ligera",
	"ListenNow" : "Escuchar ahora",
	"LotFull" : "Aparcamiento lleno",
	"Louisiana" : "Luisiana",
	"MA_A" : "Alerta marina\t",
	"MA_W" : "Advertencia marina\t",
	"MA_Y" : "Aviso marino\t",
	"MF_A" : "Alerta marina de niebla espesa\t",
	"MF_W" : "Advertencia marina de niebla espesa\t",
	"MF_Y" : "Aviso marino de niebla espesa\t",
	"MH_A" : "Alerta marina de caída de ceniza\t",
	"MH_W" : "Advertencia marina de caída de ceniza\t",
	"MH_Y" : "Aviso marino de caída de ceniza\t",
	"MRWI" : "Advertencia marina de vientos\t",
	"MS_A" : "Alerta marina de humo espeso\t",
	"MS_W" : "Advertencia marina de humo espeso\t",
	"MS_Y" : "Aviso marino de humo espeso\t",
	"Maine" : "Maine",
	"Maryland" : "Maryland",
	"Massachusetts" : "Massachusetts",
	"MatchInfo" : "Información de coincidencia",
	"Michigan" : "Michigan",
	"MidGrade" : "Grado medio",
	"Midrange" : "Alcance medio",
	"Minnesota" : "Minnesota",
	"Mississippi" : "Misisipí",
	"Missouri" : "Misuri",
	"Mist" : "Neblina",
	"MixedRainAndHail" : "Mezcla de lluvia y granizo",
	"MixedRainAndSleet" : "Mezcla de lluvia y aguanieve",
	"MixedRainAndSnow" : "Mezcla de lluvia y nieve",
	"ModerateFog" : "Niebla moderada",
	"ModerateSnow" : "Nieve moderada",
	"Montana" : "Montana",
	"MostlyClearNight" : "Noche mayormente despejada",
	"MostlyCloudy" : "Mayormente nublado",
	"MostlyCloudyNight" : "Noche mayormente nublada",
	"MostlySunny" : "Mayormente soleado",
	"Movies" : "Películas",
	"NUW" : "Advertencia de planta de energía nuclear\t",
	"NationalTooltip" : "Nacional",
	"NearestCity" : "Ciudad más cercana",
	"Nebraska" : "Nebraska",
	"Nevada" : "Nevada",
	"NewHampshire" : "Nuevo Hampshire",
	"NewJersey" : "Nueva Jersey",
	"NewMexico" : "Nuevo México",
	"NewYork" : "Nueva York",
	"NextDay" : "Día siguiente",
	"NextGame" : "Siguiente juego",
	"NextMovie" : "Siguiente película",
	"NoAlertsFound" : "No se encontraron alertas",
	"NoEventsInProgress" : "No hay eventos en progreso",
	"NoFinalEvents" : "No hay eventos finales",
	"NoParkinglotsfoundinrange" : "No se encontraron garajes de aparcamiento en el área de alcance",
	"NoScheduledEvents" : "No hay eventos programados",
	"Nofuelstationsfoundinrange" : "No se encontraron estaciones de combustible en el área de alcance",
	"NorthCarolina" : "Carolina del Norte",
	"NorthDakota" : "Dakota del Norte",
	"Notheaterfoundinrange" : "No se encontraron teatros en el área de alcance",
	"NowIn" : "Ahora en {CityName}",
	"NowTooltip" : "Clima actual",
	"Now_3_6" : "Ahora 3/6",
	"Ohio" : "Ohio",
	"Oklahoma" : "Oklahoma",
	"OneDayAgo" : "Un día atrás",
	"Oregon" : "Oregón",
	"OutofFuel" : "Combustible agotado",
	"PUBS" : "Declaración de peligro o emergencia civil\t",
	"Parking" : "Aparcamiento",
	"PartlyCloudy" : "Parcialmente nublado",
	"PartlyCloudyNight" : "Noche parcialmente nublada",
	"Pennsylvania" : "Pensilvania",
	"Percent" : "%",
	"Premium" : "Premium",
	"PreviousDay" : "Día anterior",
	"PreviousGame" : "Juego anterior",
	"PreviousMovie" : "Película anterior",
	"Price" : "Precio",
	"PricingRate" : "Tarifa",
	"RB_A" : "Alerta de mal tiempo para embarcaciones pequeñas\t",
	"RB_W" : "Advertencia de mal tiempo para embarcaciones pequeñas\t",
	"RB_Y" : "Aviso de mal tiempo para embarcaciones pequeñas\t",
	"RHW" : "Advertencia de peligro radiológico\t",
	"RH_A" : "Alerta de peligro radiológico\t",
	"RH_W" : "Advertencia de peligro radiológico\t",
	"RH_Y" : "Aviso de peligro radiológico\t",
	"RNFL" : "Advertencia de precipitaciones\t",
	"Rain" : "Lluvia",
	"Rate" : "Tarifa",
	"RecentCities" : "Ciudades recientes",
	"RecentCitiesnotavailble" : "Ciudades recientes no disponibles",
	"Regular" : "Regular",
	"RelativeDaily" : "Relativo a diario",
	"RelativeHourly" : "Relativo a cada hora",
	"Remaining" : "Restante",
	"Remove" : "Eliminar",
	"RemoveStock" : "¿Eliminar existencias?",
	"RemoveStockDisplay" : "Eliminar existencias ",
	"RenewSubscription" : "Renueve su suscripción llamando a SiriusXM al {XMPhoneNumber}. ",
	"RhodeIsland" : "Rhode Island",
	"RouteTo" : "Ruta a",
	"SB_A" : "Alerta de nieve y tormenta de nieve\t",
	"SB_W" : "Advertencia de nieve y tormenta de nieve\t",
	"SB_Y" : "Aviso de nieve y tormenta de nieve\t",
	"SC_A" : "Alerta para embarcaciones pequeñas\t",
	"SC_W" : "Advertencia para embarcaciones pequeñas\t",
	"SC_Y" : "Aviso para embarcaciones pequeñas\t",
	"SE_A" : "Alerta de mareas peligrosas\t",
	"SE_W" : "Advertencia de mareas peligrosas\t",
	"SE_Y" : "Aviso de mareas peligrosas\t",
	"SI_A" : "Alerta de vientos para embarcaciones pequeñas\t",
	"SI_W" : "Advertencia de vientos para embarcaciones pequeñas\t",
	"SI_Y" : "Aviso de vientos para embarcaciones pequeñas\t",
	"SLWX" : "Advertencia de tormenta local severa\t",
	"SM_A" : "Alerta de humo espeso\t",
	"SM_W" : "Advertencia de humo espeso\t",
	"SM_Y" : "Aviso de humo espeso\t",
	"SNSQ" : "Advertencia de borrasca de nieve\t",
	"SN_A" : "Alerta de nieve\t",
	"SN_W" : "Advertencia de nieve\t",
	"SN_Y" : "Aviso de nieve\t",
	"SPW" : "Advertencia de refugio designado\t",
	"SPWX" : "Advertencia de condiciones climáticas especiales\t",
	"SR_A" : "Alerta de tormenta\t",
	"SR_W" : "Advertencia de tormenta\t",
	"SR_Y" : "Aviso de tormenta\t",
	"SSRG" : "Advertencia de marea tormentosa\t",
	"SU_A" : "Alerta de olas altas\t",
	"SU_W" : "Advertencia de olas altas\t",
	"SU_Y" : "Aviso de olas altas\t",
	"SVCO" : "Advertencia de actividad convectiva severa importante\t",
	"SVHA" : "Advertencia de granizo severo importante\t",
	"SVTO" : "Advertencia de tornado severo importante\t",
	"SVWI" : "Advertencia de vientos severos\t",
	"SVWX" : "Advertencia de condiciones climáticas severas\t",
	"SV_A" : "Alerta de tormenta severa\t",
	"SV_W" : "Advertencia de tormenta severa\t",
	"SV_Y" : "Aviso de tormenta severa\t",
	"SW_A" : "Alerta de mareas peligrosas para embarcaciones pequeñas\t",
	"SW_W" : "Advertencia de mareas peligrosas para embarcaciones pequeñas\t",
	"SW_Y" : "Aviso de mareas peligrosas para embarcaciones pequeñas\t",
	"SXMNoStocksAdded" : "No se añadieron existencias",
	"SXMWeatherAndSecurityAlerts" : "Alertas de seguridad y clima de SXM",
	"Sandstorm" : "Tormenta de arena",
	"ScatteredShowers" : "Lloviznas aisladas",
	"ScatteredShowersNight" : "Noche con lloviznas aisladas",
	"ScatteredSnowShowers" : "Leves nevadas aisladas",
	"ScatteredSnowShowersNight" : "Noche con leves nevadas aisladas",
	"ScatteredThunderstorms" : "Tormentas aisladas",
	"ScatteredThunderstormsNight" : "Noche con tormentas aisladas",
	"SelectCity" : "Seleccionar ciudad",
	"SelectEvent" : "Seleccionar evento",
	"SelectLeague" : "Seleccionar liga",
	"SelectSport" : "Seleccionar deporte",
	"SelectSportIsTemporarilyUnavailable" : "El deporte que seleccionó no está disponible temporalmente. ",
	"SelectState" : "Seleccione el Estado o Provincia",
	"SelectStocktoRemove" : "Seleccionar existencias para eliminar",
	"SelectTeam" : "Seleccionar equipo",
	"Settings" : "Configuración SXM",
	"SevereThunderstorms" : "Tormentas severas",
	"Showers" : "Lloviznas",
	"Sleet" : "Aguanieve",
	"Smoky" : "Nublado",
	"Snow" : "Nieve",
	"SnowShowers" : "Leves nevadas",
	"SouthCarolina" : "Carolina del Sur",
	"SouthDakota" : "Dakota del Sur",
	"SpacesAvailable" : "Espacios disponibles ",
	"SpecialEvent" : "Evento especial",
	"Sports" : "Deportes",
	"StateListisnotavailable" : "La lista de Estados o Provincias no está disponible",
	"StockAlreadyIncluded" : "Las existencias ya están incluidas en la Lista. ",
	"StockDeleted" : "Existencias eliminadas",
	"StockNotFound" : "Existencias no encontradas.",
	"StockRemoved" : "Existencias eliminadas.",
	"StockRemovedDisplay" : "Eliminar existencias",
	"Stocks" : "Existencias",
	"Sunny" : "Soleado",
	"Synopsis" : "Sinopsis",
	"SynopsisTooltip" : "Sinopsis",
	"TI_A" : "Alerta de tormenta tropical tierra adentro\t",
	"TI_W" : "Advertencia de tormenta tropical tierra adentro\t",
	"TI_Y" : "Aviso de tormenta tropical tierra adentro\t",
	"TOE" : "Emergencia de corte telefónico\t",
	"TO_A" : "Alerta de tornado\t",
	"TO_W" : "Advertencia de tornado\t",
	"TO_Y" : "Aviso de tornado\t",
	"TR_A" : "Alerta de tormenta tropical\t",
	"TR_W" : "Advertencia de tormenta tropical\t",
	"TR_Y" : "Aviso de tormenta tropical\t",
	"TSTM" : "Advertencia de tormenta general\t",
	"TS_A" : "Alerta de tsunami\t",
	"TS_W" : "Advertencia de tsunami\t",
	"TS_Y" : "Aviso de tsunami\t",
	"TWNowSetup" : "Alerta de tráfico y clima",
	"TY_A" : "Alerta de tifón\t",
	"TY_W" : "Advertencia de tifón\t",
	"TY_Y" : "Aviso de tifón\t",
	"TeamListIsTemporarilyUnavailable" : "La Lista del equipo no está disponible temporalmente.",
	"Tennessee" : "Tennessee",
	"Texas" : "Texas",
	"Thunderstorms" : "Tormentas",
	"Today" : "Hoy",
	"TodayIn" : "Hoy en {CityName}",
	"TodaysWeather" : "Clima de hoy",
	"Tornado" : "Tornado",
	"Traffic" : "Tráfico",
	"TrafficPlus" : "Tráfico Plus",
	"TropicalStorm" : "Tormenta tropical",
	"TuneAwayBroadcast" : "Sintonizar transmisión del equipo visitante",
	"TuneHomeBroadcast" : "Sintonizar transmisión del equipo local",
	"TuneNationalBroadcast" : "Sintonizar transmisión nacional",
	"UP_A" : "Alerta de rocío gélido intenso\t",
	"UP_W" : "Advertencia de rocío gélido intenso\t",
	"UP_Y" : "Aviso de rocío gélido intenso\t",
	"UVRD" : "Advertencia de rayos ultravioletas\t",
	"UnknownPrecipitation" : "Precipitación desconocida",
	"Updated:" : "Actualizado:  ",
	"Utah" : "Utah",
	"VOW" : "Advertencia de volcano\t",
	"VO_A" : "Alerta de volcano\t",
	"VO_W" : "Advertencia de volcano\t",
	"VO_Y" : "Aviso de volcano\t",
	"Vermont" : "Vermont",
	"View" : "Vista",
	"Virginia" : "Virginia",
	"WC_A" : "Alerta de temperatura percibida\t",
	"WC_W" : "Advertencia de temperatura percibida\t",
	"WC_Y" : "Aviso de temperatura percibida\t",
	"WI_A" : "Alerta de viento\t",
	"WI_W" : "Advertencia de viento\t",
	"WI_Y" : "Aviso de viento\t",
	"WRWI" : "Advertencia de vientos intensos\t",
	"WS_A" : "Alerta de tormenta de viento\t",
	"WS_W" : "Advertencia de tormenta de invierno\t",
	"WS_Y" : "Aviso de tormenta de invierno\t",
	"WTSP" : "Advertencia de tromba marina\t",
	"WW_A" : "Alerta de condiciones climáticas invernales\t",
	"WW_W" : "Advertencia de condiciones climáticas invernales\t",
	"WW_Y" : "Aviso de condiciones climáticas invernales\t",
	"Washington" : "Washington",
	"Weather" : "Clima  ",
	"WeatherAndSecurityAlerts" : "Alertas de clima y seguridad",
	"WeatherForecast" : "Pronóstico del tiempo",
	"WeatherRadar" : "Radar meteorológico",
	"WeatherfortheselectedCityisnotAvailable" : "El clima de la ciudad seleccionada no está disponible",
	"WestVirginia" : "Virginia Occidental",
	"Wind" : "Viento",
	"Windy" : "Ventoso",
	"WintryMix" : "Mezcla de condiciones invernales",
	"Wisconsin" : "Wisconsin",
	"Wyoming" : "Wyoming",
	"XMAlerts" : "Alertas SXM",
	"XMFuelDetails" : "Tipos de combustibles disponibles",
	"XMFuelPrices" : "Precios del comb. SXM",
	"XMLastTeam" : "Últimos equipos vistos",
	"XMLeagueOffSeason" : "Liga actualmente fuera de temporada",
	"XMMovies" : "Películas SXM",
	"XMParking" : "Aparcamiento SXM",
	"XMServiceLoading" : "{Selected Service} cargando . . .",
	"XMServices" : "Servicios SiriusXM ",
	"XMServicesTooltip" : "Servicios SiriusXM",
	"XMSportNext" : "Siguiente evento",
	"XMSportNoSchedule" : "Hay juegos o eventos programados para el deporte seleccionado.",
	"XMSportOffSeason" : "El deporte o evento seleccionado está fuera de temporada",
	"XMSportPrevious" : "Evento anterior",
	"XMSports" : "Deportes SXM",
	"XMStockDelay" : "Todos los datos de existencias se pueden demorar hasta 20 minutos.",
	"XMStockLimit" : "Limitado a 20 existencias",
	"XMStocks" : "Existencias SXM",
	"XMSubscriptionExpired" : "Su <Service> suscripción ha caducado. Llame a SiriusXM al {XMPhoneNumber}.",
	"XMSubscriptionExpiring" : "Su suscripción SiriusXM caduca en {days} días. ",
	"XMTeams" : "Agenda de los equipos",
	"XMTraffic" : "Tráfico SXM",
	"XMWeather" : "Clima SXM  ",
	"XMWeatherForecast" : "Pronóstico del tiempo SXM",
	"XMWeatherRadar" : "Radar meteorológico SXM",
	"ZF_A" : "Alerta de niebla gélida\t",
	"ZF_W" : "Advertencia de niebla gélida\t",
	"ZF_Y" : "Aviso de niebla gélida\t",
	"ZR_A" : "Alerta de nieve y lluvia gélida\t",
	"ZR_W" : "Advertencia de lluvia gélida\t",
	"ZR_Y" : "Aviso de lluvia gélida\t",
	"ZY_A" : "Alerta de rocío gélido\t",
	"ZY_W" : "Advertencia de rocío gélido\t",
	"ZY_Y" : "Aviso de rocío gélido\t",
	"ZoomIn" : "Acercar",
	"ZoomOut" : "Alejar",
	"for" : "para",
};

framework.registerAppDictLoaded("xmdata", "es_MX");