var __VrHelpPositionTable__fmradioAppDict_lv_LV = {
	"AutoMemory_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"AreaPresetJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"NowPlayingEU_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_FMSettings","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_TrafficAnnouncement","VrHelp_Scan"]
	},
	"AreaPresetJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"NowPlayingNA_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_iTunesTagging","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_HDMenu","VrHelp_Scan"]
	},
	"Settings_Help" : {
		"Left" : ["VrHelp_AlternativeFrequencyOn","VrHelp_AlternativeFrequencyOff","VrHelp_RegionLockOn","VrHelp_RegionLockOff"]
	},
	"Tune_NA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"StationListJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"StationListJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"GenreSeek_Help" : {
		"Left" : ["VrHelp_SeekUp","VrHelp_SeekDown","VrHelp_ChangeGenre"]
	},
	"NowPlayingJapan_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"Tune_nonNA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"NowPlayingOther_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"AutoMemory_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	}
};

var Localization_fmradioAppDict_lv_LV = {
	//"stringId" : "localString"
	"Affairs" : "Aktualitātes",
	"Alarm" : "Trauksme",
	"AlarmTest" : "Trauksmes pārbaude",
	"AllMemoryFull" : "Visa atmiņa ir pilna",
	"AllStations" : "Visas stacijas",
	"AllTagsTransferred" : "Visas atzīmes pārsūtītas",
	"AlternativeFrequency" : "Alternatīva frekvence",
	"AreaPresetTab" : "Area Preset",
	"AutoMemoryList" : "Autom. atmiņas saraksts",
	"CannotTransferTags" : "Nevar pārsūtīt atzīmes",
	"ChangeGenre" : "Mainīt žanru",
	"ChannelListJP" : "Channel List",
	"ChannelListTab" : "Channel List",
	"Childrens" : "Bērni",
	"Classics" : "Klasika",
	"Close" : "Aizv.",
	"ConnectIPod" : "Piev. iPod, lai pārs. atzīm.",
	"Country" : "Kantrī",
	"Culture" : "Kultūra",
	"Documentary" : "Dokumentāls",
	"Drama" : "Drāma",
	"Education" : "Izglītība",
	"ErrorConnection" : "Kļūda, pārs. atzīm. uz iPod",
	"FMRadio" : "FM radio",
	"FMSettings" : "FM iestatījumi",
	"Finance" : "Finanses",
	"Folk" : "Folkmūzika",
	"GenreAffairs" : "Žanrs: aktualitātes",
	"GenreAlarm" : "Žanrs: trauksme",
	"GenreAlarmTest" : "Žanrs: trauksmes pārbaude",
	"GenreAllStations" : "Žanrs: visas stacijas",
	"GenreChildrens" : "Žanrs: bērni",
	"GenreClassics" : "Žanrs: klasika",
	"GenreCountry" : "Žanrs: kantrī",
	"GenreCulture" : "Žanrs: kultūra",
	"GenreDocumentary" : "Žanrs: dokumentāls",
	"GenreDrama" : "Žanrs: drāma",
	"GenreEducation" : "Žanrs: izglītība",
	"GenreFinance" : "Žanrs: finanses",
	"GenreFolk" : "Žanrs: folkmūzika",
	"GenreInfo" : "Žanrs: informācija",
	"GenreJazz" : "Žanrs: džezs",
	"GenreLeisure" : "Žanrs: brīvais laiks",
	"GenreLight" : "Žanrs: vieglā mūzika",
	"GenreList" : "Žanru saraksts",
	"GenreMor" : "Žanrs: vieglā mūzika",
	"GenreName" : "Žanrs: {genreName}",
	"GenreNational" : "Žanrs: valsts",
	"GenreNews" : "Žanrs: ziņas",
	"GenreOldies" : "Žanrs: vecās dziesmas",
	"GenreOther" : "Žanrs: cits",
	"GenrePhoneIn" : "Žanrs: iezvana prog.",
	"GenrePop" : "Žanrs: popmūzika",
	"GenreReligion" : "Žanrs: reliģija",
	"GenreRock" : "Žanrs: rokmūzika",
	"GenreScience" : "Žanrs: zinātne",
	"GenreSeek" : "Žanra meklēšana",
	"GenreSocial" : "Žanrs: sociālie tīkli",
	"GenreSport" : "Žanrs: sports",
	"GenreTravel" : "Žanrs: ceļošana",
	"GenreVaried" : "Žanrs: dažādi",
	"GenreWeather" : "Žanrs: laikapstākļi",
	"HDRadio" : "HD Radio",
	"HDStations" : "HD stacijas",
	"Info" : "Informācija",
	"IpodError" : "iPod kļūda",
	"IpodFull" : "iPod pilna",
	"Jazz" : "Džezs",
	"Leisure" : "Brīvais laiks",
	"Light" : "Vieglā mūzika ",
	"ListUpdate" : "List Update",
	"MemoryFull" : "Atmiņa pilna",
	"Mor" : "Vieglā mūzika ",
	"National" : "Valsts",
	"News" : "Ziņas",
	"Noresultsfound" : "Nav atrasts neviens rezultāts",
	"Oldies" : "Vecās dziesmas",
	"Other" : "Cits",
	"PartialTransfer" : "Daļēja pārsūtīšana",
	"PhoneIn" : "Iezvana prog.",
	"Pop" : "Popmūzika",
	"RegionLock" : "Reģiona bloķēšana",
	"Religion" : "Reliģija",
	"Remaining" : "Atlik. {numberOfTags} atz.",
	"Remove" : "Noņemt",
	"Rock" : "Rokmūzika",
	"Science" : "Zinātne",
	"SignalLost" : "Signāls pazaudēts",
	"Social" : "Sociālie tīkli",
	"Sport" : "Sports",
	"StationList" : "Staciju saraksts",
	"TAOff" : "Sat. brīd. izsl.",
	"TagAlreadySaved" : "Atzīme jau saglabāta",
	"TagCaptured" : "Atzīme uztverta",
	"TagMemoryFull" : "Atzīmju atmiņa pilna",
	"TagNotYetProcessed" : "Atz. vēl nav apstrādāta",
	"TagSaved" : "Atzīme saglabāta",
	"TagSavedtoIpod" : "Atzīme saglabāta iPod ier.",
	"TagSavedtoSystem" : "Atzīme saglabāta sistēmā",
	"TagTransferredtoiPod" : "Atzīme pārsūtīta uz iPod",
	"TagsCannotBeSaved" : "Atzīmes nevar saglabāt",
	"Tooltip_IcnUmpFMSettings" : "FM iestatījumi",
	"TrafficAlert" : "Satiksmes paziņojums (TA)",
	"TrafficAlertOff" : "Satiksmes paziņojums (TA) izslēgts",
	"TrafficAlertOn" : "Satiksmes paziņojums (TA) ieslēgts",
	"Travel" : "Ceļošana",
	"UnplugAndReconnect" : "Atvienot un pievienot",
	"UpdateStationList" : "Atjaunināt staciju sarakstu",
	"UpdatingStationList" : "Atjaunina staciju sarakstu",
	"Varied" : "Dažādi",
	"VrHelp_AlternativeFrequencyOff" : "Alternative Frequency Off",
	"VrHelp_AlternativeFrequencyOn" : "Alternative Frequency On",
	"VrHelp_AutoMemory" : "Auto Memory",
	"VrHelp_ChangeGenre" : "Change Genre",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_FMSettings" : "FM Settings",
	"VrHelp_Favorites" : "Favorites",
	"VrHelp_Frequency" : "(frequency)",
	"VrHelp_HDMenu" : "HD Radio Channels",
	"VrHelp_RegionLockOff" : "Region Lock Off",
	"VrHelp_RegionLockOn" : "Region Lock On",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SeekDown" : "Seek Down",
	"VrHelp_SeekNext" : "Seek Next",
	"VrHelp_SeekPrevious" : "Seek Previous",
	"VrHelp_SeekUp" : "Seek Up",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement (TA)",
	"VrHelp_Tune" : "Tune",
	"VrHelp_TuneDown" : "Tune Down",
	"VrHelp_TuneUp" : "Tune Up",
	"VrHelp_UpdateList" : "Update List",
	"VrHelp_iTunesTagging" : "iTunes Tagging",
	"Weather" : "Laikapstākļi",
	"favorites_Tooltip" : "Izlase",
	"hdChannels_Tooltip" : "HD kanāli",
	"rbds_Adult" : "Pieaugušo hiti",
	"rbds_Class" : "Klasiskais roks",
	"rbds_Classical" : "Klasika",
	"rbds_College" : "Koledža",
	"rbds_Country" : "Kantrī",
	"rbds_Emergency" : "Brīdinājums! Brīdinājums!",
	"rbds_EmergencyTest" : "Avārijas tests",
	"rbds_Foreign" : "Svešvaloda",
	"rbds_Hablar" : "Runā spāņu valodā",
	"rbds_HipHop" : "Hiphops",
	"rbds_Info" : "Informācija",
	"rbds_Jazz" : "Džezs",
	"rbds_Musica" : "Spāņu mūzika",
	"rbds_News" : "Ziņas",
	"rbds_None" : "--",
	"rbds_Nostalgia" : "Nostalģija",
	"rbds_Oldies" : "Vecie gabali",
	"rbds_Personality" : "Personība",
	"rbds_Public" : "Sabiedrība",
	"rbds_ReligousM" : "Reliģiskā mūzikas",
	"rbds_ReligousT" : "Reliģiskā runa",
	"rbds_Rhythym" : "Ritmablūzs",
	"rbds_Rock" : "Rokmūzika",
	"rbds_Soft" : "Melodisks",
	"rbds_SoftRB" : "Melodisks ritmablūzs",
	"rbds_SoftRock" : "Melodisks roks",
	"rbds_Sports" : "Sports",
	"rbds_Talk" : "Runāt",
	"rbds_Top40" : "Top 40",
	"rbds_Weather" : "Laikapstākļi",
	"rbds_genre_Adult" : "Žanrs: pieaugušo hiti",
	"rbds_genre_Class" : "Žanrs: klasiskais roks",
	"rbds_genre_Classical" : "Žanrs: klasika",
	"rbds_genre_College" : "Žanrs: koledža",
	"rbds_genre_Country" : "Žanrs: kantrī",
	"rbds_genre_Emergency" : "Žanrs: Brīdinājums! Brīdinājums!",
	"rbds_genre_EmergencyTest" : "Žanrs: avārijas tests",
	"rbds_genre_Foreign" : "Žanrs: svešvaloda",
	"rbds_genre_Hablar" : "Žanrs: runā spāņu valodā",
	"rbds_genre_HipHop" : "Žanrs: Hiphops",
	"rbds_genre_Info" : "Žanrs: informācija",
	"rbds_genre_Jazz" : "Žanrs: džezs",
	"rbds_genre_Musica" : "Žanrs: Spāņu mūzika",
	"rbds_genre_News" : "Žanrs: ziņas",
	"rbds_genre_None" : "Žanrs: --",
	"rbds_genre_Nostalgia" : "Žanrs: nostalģija",
	"rbds_genre_Oldies" : "Žanrs: vecie gabali",
	"rbds_genre_Personality" : "Žanrs: personība",
	"rbds_genre_Public" : "Žanrs: sabiedrība",
	"rbds_genre_ReligousM" : "Žanrs: reliģiskā mūzika",
	"rbds_genre_ReligousT" : "Žanrs: reliģiskā runa",
	"rbds_genre_Rhythym" : "Žanrs: ritmblūzs",
	"rbds_genre_Rock" : "Žanrs: Avārijas tests",
	"rbds_genre_Soft" : "Žanrs: melodisks",
	"rbds_genre_SoftRB" : "Žanrs: melodisks ritmblūzs",
	"rbds_genre_SoftRock" : "Žanrs: melodisks roks",
	"rbds_genre_Sports" : "Žanrs: sports",
	"rbds_genre_Talk" : "Žanrs: runa",
	"rbds_genre_Top40" : "Žanrs: top 40",
	"rbds_genre_Weather" : "Žanrs: laikapstākļi",
};

framework.registerAppDictLoaded("fmradio", "lv_LV");