var __VrHelpPositionTable__fmradioAppDict_tr_TR = {
	"AutoMemory_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"AreaPresetJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"NowPlayingEU_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_FMSettings","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_TrafficAnnouncement","VrHelp_Scan"]
	},
	"AreaPresetJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"NowPlayingNA_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_iTunesTagging","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_HDMenu","VrHelp_Scan"]
	},
	"Settings_Help" : {
		"Left" : ["VrHelp_AlternativeFrequencyOn","VrHelp_AlternativeFrequencyOff","VrHelp_RegionLockOn","VrHelp_RegionLockOff"]
	},
	"Tune_NA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"StationListJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"StationListJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"GenreSeek_Help" : {
		"Left" : ["VrHelp_SeekUp","VrHelp_SeekDown","VrHelp_ChangeGenre"]
	},
	"NowPlayingJapan_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"Tune_nonNA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"NowPlayingOther_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"AutoMemory_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	}
};

var Localization_fmradioAppDict_tr_TR = {
	//"stringId" : "localString"
	"Affairs" : "İlişkiler",
	"Alarm" : "Alarm",
	"AlarmTest" : "Alarm Testi",
	"AllMemoryFull" : "Tüm Hafıza Dolu",
	"AllStations" : "Tüm İstasyonlar",
	"AllTagsTransferred" : "Tüm Etiketler Aktarıldı",
	"AlternativeFrequency" : "Alternatif Frekans",
	"AreaPresetTab" : "Area Preset",
	"AutoMemoryList" : "Otomatik Hafıza Listesi",
	"CannotTransferTags" : "Etiketler Aktarılamıyor",
	"ChangeGenre" : "Türü Değiştir",
	"ChannelListJP" : "Channel List",
	"ChannelListTab" : "Channel List",
	"Childrens" : "Çocuklar",
	"Classics" : "Klasik",
	"Close" : "Kapat",
	"ConnectIPod" : "Etiketler, iPod'u Bağla",
	"Country" : "Ülke",
	"Culture" : "Kültür",
	"Documentary" : "Belgesel",
	"Drama" : "Drama",
	"Education" : "Eğitim",
	"ErrorConnection" : "iPod'a Etiket Aktar Hata",
	"FMRadio" : "FM Radyo",
	"FMSettings" : "FM Ayarları",
	"Finance" : "Finans",
	"Folk" : "Halk Müziği",
	"GenreAffairs" : "Tür: İlişkiler",
	"GenreAlarm" : "Tür: Alarm",
	"GenreAlarmTest" : "Tür: Alarm Testi",
	"GenreAllStations" : "Tür: Tüm İstasyonlar",
	"GenreChildrens" : "Tür: Çocuklar",
	"GenreClassics" : "Tür: Klasik",
	"GenreCountry" : "Tür: Ülke",
	"GenreCulture" : "Tür: Kültür",
	"GenreDocumentary" : "Tür: Belgesel",
	"GenreDrama" : "Tür: Drama",
	"GenreEducation" : "Tür: Eğitim",
	"GenreFinance" : "Tür: Finans",
	"GenreFolk" : "Tür: Halk Müziği",
	"GenreInfo" : "Tür: Bilgilendirici",
	"GenreJazz" : "Tür: Caz",
	"GenreLeisure" : "Tür: Hobi",
	"GenreLight" : "Tür: Hafif",
	"GenreList" : "Tür Listesi",
	"GenreMor" : "Tür: Dinlendirici",
	"GenreName" : "Tür: {genreName}",
	"GenreNational" : "Tür: Ulusal",
	"GenreNews" : "Tür: Haberler",
	"GenreOldies" : "Tür: Eskiler",
	"GenreOther" : "Tür: Diğer",
	"GenrePhoneIn" : "Tür: Telefon Girişi",
	"GenrePop" : "Tür: Pop",
	"GenreReligion" : "Tür: Dini",
	"GenreRock" : "Tür: Rock",
	"GenreScience" : "Tür: Bilim",
	"GenreSeek" : "Tür Ara",
	"GenreSocial" : "Tür: Sosyal",
	"GenreSport" : "Tür: Spor",
	"GenreTravel" : "Tür: Seyahat",
	"GenreVaried" : "Tür: Muhtelif",
	"GenreWeather" : "Tür: Hava Durumu",
	"HDRadio" : "HD Radyo",
	"HDStations" : "HD İstasyonlar",
	"Info" : "Bilgilendirici",
	"IpodError" : "iPod Hatası",
	"IpodFull" : "iPod Dolu",
	"Jazz" : "Caz",
	"Leisure" : "Hobi",
	"Light" : "Hafif",
	"ListUpdate" : "List Update",
	"MemoryFull" : "Hafıza Dolu",
	"Mor" : "Dinlendirici",
	"National" : "Ulusal",
	"News" : "Haberler",
	"Noresultsfound" : "Sonuç bulunamadı",
	"Oldies" : "Eskiler",
	"Other" : "Diğer",
	"PartialTransfer" : "Kısmi Transfer",
	"PhoneIn" : "Telefon Girişi",
	"Pop" : "Pop",
	"RegionLock" : "Bölge Kilidi",
	"Religion" : "Dini",
	"Remaining" : "Kalan: {numberOfTags}",
	"Remove" : "Kaldır",
	"Rock" : "Rock",
	"Science" : "Bilim",
	"SignalLost" : "Sinyal Kesildi",
	"Social" : "Sosyal",
	"Sport" : "Spor",
	"StationList" : "İstasyon Listesi",
	"TAOff" : "TA Kapalı",
	"TagAlreadySaved" : "Etiket Zaten Kayıtlı",
	"TagCaptured" : "Etiket Alındı",
	"TagMemoryFull" : "Etiket Hafızası Dolu",
	"TagNotYetProcessed" : "Etiket Henüz İşlenmedi",
	"TagSaved" : "Etiket Kaydedildi",
	"TagSavedtoIpod" : "Etiket iPod'a Kaydedildi",
	"TagSavedtoSystem" : "Etiket Sisteme Kaydedildi",
	"TagTransferredtoiPod" : "Etiket iPod'a Aktarıldı",
	"TagsCannotBeSaved" : "Etiketler Kaydedilemiyor",
	"Tooltip_IcnUmpFMSettings" : "FM Ayarları",
	"TrafficAlert" : "Trafik Uyarısı (TA)",
	"TrafficAlertOff" : "Trafik Uyarısı (TA) Kapalı",
	"TrafficAlertOn" : "Trafik Uyarısı (TA) Açık",
	"Travel" : "Seyahat",
	"UnplugAndReconnect" : "Çıkar ve Yeniden Bağla",
	"UpdateStationList" : "İstasyon Listesini Güncelle",
	"UpdatingStationList" : "İstasyon Listesi Güncelleniyor",
	"Varied" : "Muhtelif",
	"VrHelp_AlternativeFrequencyOff" : "Alternative Frequency Off",
	"VrHelp_AlternativeFrequencyOn" : "Alternative Frequency On",
	"VrHelp_AutoMemory" : "Auto Memory",
	"VrHelp_ChangeGenre" : "Change Genre",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_FMSettings" : "FM Settings",
	"VrHelp_Favorites" : "Favorites",
	"VrHelp_Frequency" : "(frequency)",
	"VrHelp_HDMenu" : "HD Radio Channels",
	"VrHelp_RegionLockOff" : "Region Lock Off",
	"VrHelp_RegionLockOn" : "Region Lock On",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SeekDown" : "Seek Down",
	"VrHelp_SeekNext" : "Seek Next",
	"VrHelp_SeekPrevious" : "Seek Previous",
	"VrHelp_SeekUp" : "Seek Up",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement (TA)",
	"VrHelp_Tune" : "Tune",
	"VrHelp_TuneDown" : "Tune Down",
	"VrHelp_TuneUp" : "Tune Up",
	"VrHelp_UpdateList" : "Update List",
	"VrHelp_iTunesTagging" : "iTunes Tagging",
	"Weather" : "Hava Durumu",
	"favorites_Tooltip" : "Omiljeni",
	"hdChannels_Tooltip" : "HD stanice",
	"rbds_Adult" : "Yetişkin Sayısı",
	"rbds_Class" : "Klasik Rock",
	"rbds_Classical" : "Klasik",
	"rbds_College" : "Üniversite",
	"rbds_Country" : "Ülke",
	"rbds_Emergency" : "Uyarı! Uyarı!",
	"rbds_EmergencyTest" : "Acil Testi",
	"rbds_Foreign" : "Yabancı Dil",
	"rbds_Hablar" : "İspanyolca Konuşan",
	"rbds_HipHop" : "Hip Hop",
	"rbds_Info" : "Bilgi",
	"rbds_Jazz" : "Caz",
	"rbds_Musica" : "İspanyol Müzik",
	"rbds_News" : "Haberler",
	"rbds_None" : "--",
	"rbds_Nostalgia" : "Nostalji",
	"rbds_Oldies" : "Eskiler",
	"rbds_Personality" : "Kişilik",
	"rbds_Public" : "Kamu",
	"rbds_ReligousM" : "Dini Müzik",
	"rbds_ReligousT" : "Dini Konuşma",
	"rbds_Rhythym" : "Ritim ve Blues",
	"rbds_Rock" : "Rock",
	"rbds_Soft" : "Yumuşak",
	"rbds_SoftRB" : "Yumuşakp R&B",
	"rbds_SoftRock" : "Yumuşak Rock",
	"rbds_Sports" : "Spor",
	"rbds_Talk" : "Konuşmak",
	"rbds_Top40" : "üst 40",
	"rbds_Weather" : "Hava Durumu",
	"rbds_genre_Adult" : "Tür: Yetişkin Sayısı",
	"rbds_genre_Class" : "Tür: Klasik Rock",
	"rbds_genre_Classical" : "Tür: Klasik",
	"rbds_genre_College" : "Tür: Üniversite",
	"rbds_genre_Country" : "Tür: Ülke",
	"rbds_genre_Emergency" : "Tür: Uyarı! Uyarı!",
	"rbds_genre_EmergencyTest" : "Tür: Acil Testi",
	"rbds_genre_Foreign" : "Tür: Yabancı Dil",
	"rbds_genre_Hablar" : "Tür: İspanyolca Konuşan",
	"rbds_genre_HipHop" : "Tür: Hip Hop",
	"rbds_genre_Info" : "Tür: Bilgi",
	"rbds_genre_Jazz" : "Tür: Caz",
	"rbds_genre_Musica" : "Tür: İspanyol Müzik",
	"rbds_genre_News" : "Tür: Haberler",
	"rbds_genre_None" : "Tür: --",
	"rbds_genre_Nostalgia" : "Tür: Nostalji",
	"rbds_genre_Oldies" : "Tür: Eskiler",
	"rbds_genre_Personality" : "Tür: Kişilik",
	"rbds_genre_Public" : "Tür: Kamu",
	"rbds_genre_ReligousM" : "Tür: Dini Müzik",
	"rbds_genre_ReligousT" : "Tür: Dini Konuşma",
	"rbds_genre_Rhythym" : "Tür: Ritim ve Blues",
	"rbds_genre_Rock" : "Tür: Rock",
	"rbds_genre_Soft" : "Tür: Yumuşak",
	"rbds_genre_SoftRB" : "Tür: Yumuşakp R&B",
	"rbds_genre_SoftRock" : "Tür: Yumuşak Rock",
	"rbds_genre_Sports" : "Tür: Spor",
	"rbds_genre_Talk" : "Tür: Konuşmak",
	"rbds_genre_Top40" : "Tür: üst 40",
	"rbds_genre_Weather" : "Tür: Hava Durumu",
};

framework.registerAppDictLoaded("fmradio", "tr_TR");