var __VrHelpPositionTable__fmradioAppDict_fi_FI = {
	"AutoMemory_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"AreaPresetJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"NowPlayingEU_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_FMSettings","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_TrafficAnnouncement","VrHelp_Scan"]
	},
	"AreaPresetJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"NowPlayingNA_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_iTunesTagging","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_HDMenu","VrHelp_Scan"]
	},
	"Settings_Help" : {
		"Left" : ["VrHelp_AlternativeFrequencyOn","VrHelp_AlternativeFrequencyOff","VrHelp_RegionLockOn","VrHelp_RegionLockOff"]
	},
	"Tune_NA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"StationListJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"StationListJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"GenreSeek_Help" : {
		"Left" : ["VrHelp_SeekUp","VrHelp_SeekDown","VrHelp_ChangeGenre"]
	},
	"NowPlayingJapan_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"Tune_nonNA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"NowPlayingOther_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"AutoMemory_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	}
};

var Localization_fmradioAppDict_fi_FI = {
	//"stringId" : "localString"
	"Affairs" : "Asiaohjelmat",
	"Alarm" : "Hälytys",
	"AlarmTest" : "Hälytystesti",
	"AllMemoryFull" : "Kaikki muistit täynnä",
	"AllStations" : "Kaikki kanavat",
	"AllTagsTransferred" : "Kaikki tunnisteet siirretty",
	"AlternativeFrequency" : "Vaihtoehtoinen taajuus",
	"AreaPresetTab" : "Area Preset",
	"AutoMemoryList" : "Autom. tallenn. kanavien luettelo",
	"CannotTransferTags" : "Tunnisteita ei voi siirtää",
	"ChangeGenre" : "Vaihda tyylilajia",
	"ChannelListJP" : "Channel List",
	"ChannelListTab" : "Channel List",
	"Childrens" : "Lapset",
	"Classics" : "Klassikot",
	"Close" : "Sulje",
	"ConnectIPod" : "Liitä iPod siirtääksesi tunn.",
	"Country" : "Country",
	"Culture" : "Kulttuuri",
	"Documentary" : "Dokumentti",
	"Drama" : "Draama",
	"Education" : "Koulutus",
	"ErrorConnection" : "Virhe siirr. tunnist. iPodiin",
	"FMRadio" : "FM radio",
	"FMSettings" : "FM-asetukset",
	"Finance" : "Talous",
	"Folk" : "Folk",
	"GenreAffairs" : "Tyylilaji: Asiaohjelmat",
	"GenreAlarm" : "Tyylilaji: Hälytys",
	"GenreAlarmTest" : "Tyylilaji: Hälytystesti",
	"GenreAllStations" : "Tyylilaji: Kaikki kanavat",
	"GenreChildrens" : "Tyylilaji: Lapset",
	"GenreClassics" : "Tyylilaji: Klassikot",
	"GenreCountry" : "Tyylilaji: Country",
	"GenreCulture" : "Tyylilaji: Kulttuuri",
	"GenreDocumentary" : "Tyylilaji: Dokumentti",
	"GenreDrama" : "Tyylilaji: Draama",
	"GenreEducation" : "Tyylilaji: Koulutus",
	"GenreFinance" : "Tyylilaji: Talous",
	"GenreFolk" : "Tyylilaji: Folk",
	"GenreInfo" : "Tyylilaji: Tiedot",
	"GenreJazz" : "Tyylilaji: Jazz",
	"GenreLeisure" : "Tyylilaji: Vapaa-aika",
	"GenreLight" : "Tyylilaji: Kevyt",
	"GenreList" : "Tyylilajiluettelo",
	"GenreMor" : "Tyylilaji: Easy Listening",
	"GenreName" : "Tyylilaji: {genreName}",
	"GenreNational" : "Tyylilaji: Kansallinen",
	"GenreNews" : "Tyylilaji: Uutiset",
	"GenreOldies" : "Tyylilaji: Ikivihreät",
	"GenreOther" : "Tyylilaji: Muu",
	"GenrePhoneIn" : "Tyylilaji: Puhelintulo",
	"GenrePop" : "Tyylilaji: Pop",
	"GenreReligion" : "Tyylilaji: Uskonto",
	"GenreRock" : "Tyylilaji: Rock",
	"GenreScience" : "Tyylilaji: Tiede",
	"GenreSeek" : "Tyylilajihaku",
	"GenreSocial" : "Tyylilaji: Sosiaalinen",
	"GenreSport" : "Tyylilaji: Urheilu",
	"GenreTravel" : "Tyylilaji: Matkailu",
	"GenreVaried" : "Tyylilaji: Sekalainen",
	"GenreWeather" : "Tyylilaji: Sää",
	"HDRadio" : "HD Radio",
	"HDStations" : "HD-kanavat",
	"Info" : "Tiedot",
	"IpodError" : "iPod-virhe",
	"IpodFull" : "iPod täynnä",
	"Jazz" : "Jazz",
	"Leisure" : "Vapaa-aika",
	"Light" : "Kevyt",
	"ListUpdate" : "List Update",
	"MemoryFull" : "Muisti täynnä",
	"Mor" : "Easy Listening ",
	"National" : "Kansallinen",
	"News" : "Uutiset",
	"Noresultsfound" : "Ei tuloksia",
	"Oldies" : "Ikivihreät",
	"Other" : "Muu",
	"PartialTransfer" : "Osittainen siirto",
	"PhoneIn" : "Keskusteluohjelmat",
	"Pop" : "Pop",
	"RegionLock" : "Aluelukitus",
	"Religion" : "Uskonto",
	"Remaining" : "{numberOfTags} jäljellä",
	"Remove" : "Poista",
	"Rock" : "Rock",
	"Science" : "Tiede",
	"SignalLost" : "Signaali katkesi",
	"Social" : "Sosiaalinen",
	"Sport" : "Urheilu",
	"StationList" : "Kanavaluettelo",
	"TAOff" : "TA pois",
	"TagAlreadySaved" : "Tunniste on jo tallennettu",
	"TagCaptured" : "Tunniste poimittu",
	"TagMemoryFull" : "Tunnistemuisti täynnä",
	"TagNotYetProcessed" : "Tunnistetta ei ole käsitelty",
	"TagSaved" : "Tunniste tallennettu",
	"TagSavedtoIpod" : "Tunniste tallennettu iPodiin",
	"TagSavedtoSystem" : "Tunniste tallennettiin järj.",
	"TagTransferredtoiPod" : "Tunniste siirrettiin iPodiin",
	"TagsCannotBeSaved" : "Tunnisteita ei voi tallentaa",
	"Tooltip_IcnUmpFMSettings" : "FM-asetukset",
	"TrafficAlert" : "Liikennetiedote (TA)",
	"TrafficAlertOff" : "Liikennetiedote (TA) pois päältä",
	"TrafficAlertOn" : "Liikennetiedote (TA) päälle",
	"Travel" : "Matkailu",
	"UnplugAndReconnect" : "Irrota ja yhdistä uudelleen",
	"UpdateStationList" : "Päivitä kanavaluettelo",
	"UpdatingStationList" : "Päivitetään kanavaluetteloa",
	"Varied" : "Sekalainen",
	"VrHelp_AlternativeFrequencyOff" : "Vaihtoeht. taajuus pois",
	"VrHelp_AlternativeFrequencyOn" : "Vaihtoeht. taajuus päällä",
	"VrHelp_AutoMemory" : "Automaattinen Muisti",
	"VrHelp_ChangeGenre" : "Vaihda tyylilajia",
	"VrHelp_Entertainment" : "Viihde",
	"VrHelp_FMSettings" : "FM-asetukset",
	"VrHelp_Favorites" : "Suosikit",
	"VrHelp_Frequency" : "(taajuus)",
	"VrHelp_HDMenu" : "HD Radio kanavat ",
	"VrHelp_RegionLockOff" : "Aluelukitus pois päältä",
	"VrHelp_RegionLockOn" : "Aluelukitus päällä",
	"VrHelp_Scan" : "Haku",
	"VrHelp_SeekDown" : "Hae alaspäin",
	"VrHelp_SeekNext" : "Hae seuraava",
	"VrHelp_SeekPrevious" : "Hae edellinen",
	"VrHelp_SeekUp" : "Hae ylöspäin",
	"VrHelp_SoundSettings" : "Ääniasetukset",
	"VrHelp_StationList" : "Kanavaluettelo",
	"VrHelp_TrafficAnnouncement" : "Liikennetiedote (TA)",
	"VrHelp_Tune" : "Viritä",
	"VrHelp_TuneDown" : "Viritä alaspäin",
	"VrHelp_TuneUp" : "Viritä ylöspäin",
	"VrHelp_UpdateList" : "Päivitä luettelo",
	"VrHelp_iTunesTagging" : "iTunes-tunnisteet",
	"Weather" : "Sää",
	"favorites_Tooltip" : "Suosikit",
	"hdChannels_Tooltip" : "HD-kanavat",
	"rbds_Adult" : "Aikuisten iskelmät",
	"rbds_Class" : "Klassikko Rock",
	"rbds_Classical" : "Klassinen",
	"rbds_College" : "College",
	"rbds_Country" : "Country",
	"rbds_Emergency" : "Hälytys! Hälytys!",
	"rbds_EmergencyTest" : "Yleisen hälytyksen testi",
	"rbds_Foreign" : "Vieraskielinen",
	"rbds_Hablar" : "Puhe espanja",
	"rbds_HipHop" : "Hip Hop",
	"rbds_Info" : "Tiedot",
	"rbds_Jazz" : "Jazz",
	"rbds_Musica" : "Musiikki espanja",
	"rbds_News" : "Uutiset",
	"rbds_None" : "--",
	"rbds_Nostalgia" : "Nostalgia",
	"rbds_Oldies" : "Ikivihreät",
	"rbds_Personality" : "Julkisuuden henkilöt",
	"rbds_Public" : "Julkinen",
	"rbds_ReligousM" : "Hengellinen Musiikki",
	"rbds_ReligousT" : "Hengellinen puhe",
	"rbds_Rhythym" : "Rhythm and Blues",
	"rbds_Rock" : "Rock",
	"rbds_Soft" : "Pehmeä",
	"rbds_SoftRB" : "Pehmeä R&B",
	"rbds_SoftRock" : "Pehmeä Rock",
	"rbds_Sports" : "Urheilu",
	"rbds_Talk" : "Puhe",
	"rbds_Top40" : "Top 40",
	"rbds_Weather" : "Sää",
	"rbds_genre_Adult" : "Tyylilaji: Aikuisten iskelmät",
	"rbds_genre_Class" : "Tyylilaji: Klassikko Rock",
	"rbds_genre_Classical" : "Tyylilaji: Klassinen",
	"rbds_genre_College" : "Tyylilaji: College",
	"rbds_genre_Country" : "Tyylilaji: Country",
	"rbds_genre_Emergency" : "Tyylilaji: Hälytys! Hälytys!",
	"rbds_genre_EmergencyTest" : "Tyylilaji: Yleisen hälytyksen testi",
	"rbds_genre_Foreign" : "Tyylilaji: Vieraskielinen",
	"rbds_genre_Hablar" : "Tyylilaji: Puhe espanja",
	"rbds_genre_HipHop" : "Tyylilaji: Hip Hop",
	"rbds_genre_Info" : "Tyylilaji: Tiedot",
	"rbds_genre_Jazz" : "Tyylilaji: Jazz",
	"rbds_genre_Musica" : "Tyylilaji: Musiikki espanja",
	"rbds_genre_News" : "Tyylilaji: Uutiset",
	"rbds_genre_None" : "Tyylilaji: --",
	"rbds_genre_Nostalgia" : "Tyylilaji: Nostalgia",
	"rbds_genre_Oldies" : "Tyylilaji: Ikivihreät",
	"rbds_genre_Personality" : "Tyylilaji: Julkisuuden henkilöt",
	"rbds_genre_Public" : "Tyylilaji: Julkinen",
	"rbds_genre_ReligousM" : "Tyylilaji: Hengellinen Musiikki",
	"rbds_genre_ReligousT" : "Tyylilaji: Hengellinen puhe",
	"rbds_genre_Rhythym" : "Tyylilaji: Rhythm and Blues",
	"rbds_genre_Rock" : "Tyylilaji: Rock",
	"rbds_genre_Soft" : "Tyylilaji: Pehmeä",
	"rbds_genre_SoftRB" : "Tyylilaji: Pehmeä R&B",
	"rbds_genre_SoftRock" : "Tyylilaji: Pehmeä Rock",
	"rbds_genre_Sports" : "Tyylilaji: Urheilu",
	"rbds_genre_Talk" : "Tyylilaji: Puhe",
	"rbds_genre_Top40" : "Tyylilaji: Top 40",
	"rbds_genre_Weather" : "Tyylilaji: Sää",
};

framework.registerAppDictLoaded("fmradio", "fi_FI");