var __VrHelpPositionTable__fmradioAppDict_pt_PT = {
	"AutoMemory_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"AreaPresetJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"NowPlayingEU_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_FMSettings","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_TrafficAnnouncement","VrHelp_Scan"]
	},
	"AreaPresetJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"NowPlayingNA_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_iTunesTagging","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_HDMenu","VrHelp_Scan"]
	},
	"Settings_Help" : {
		"Left" : ["VrHelp_AlternativeFrequencyOn","VrHelp_AlternativeFrequencyOff","VrHelp_RegionLockOn","VrHelp_RegionLockOff"]
	},
	"Tune_NA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"StationListJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"StationListJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"GenreSeek_Help" : {
		"Left" : ["VrHelp_SeekUp","VrHelp_SeekDown","VrHelp_ChangeGenre"]
	},
	"NowPlayingJapan_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"Tune_nonNA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"NowPlayingOther_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"AutoMemory_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	}
};

var Localization_fmradioAppDict_pt_PT = {
	//"stringId" : "localString"
	"Affairs" : "Actualidades",
	"Alarm" : "Alarme",
	"AlarmTest" : "Teste de Alarme",
	"AllMemoryFull" : "Memória Esgotada",
	"AllStations" : "Todas as Estações",
	"AllTagsTransferred" : "Todas as Etiq. Transf.",
	"AlternativeFrequency" : "Frequência Alternativa",
	"AreaPresetTab" : "Area Preset",
	"AutoMemoryList" : "Lista de Memória Automática",
	"CannotTransferTags" : "Impossível Transf. Etiq.",
	"ChangeGenre" : "Alterar Género",
	"ChannelListJP" : "Channel List",
	"ChannelListTab" : "Channel List",
	"Childrens" : "Filhos",
	"Classics" : "Clássicos",
	"Close" : "Fechar",
	"ConnectIPod" : "Ligar iPod p/ Transf. Etiq.",
	"Country" : "Country",
	"Culture" : "Cultura",
	"Documentary" : "Documentário",
	"Drama" : "Drama",
	"Education" : "Educação",
	"ErrorConnection" : "Erro ao Transf Etiq p/ iPod",
	"FMRadio" : "Rádio FM",
	"FMSettings" : "Definições de FM",
	"Finance" : "Finanças",
	"Folk" : "Música Popular",
	"GenreAffairs" : "Género: Actualidades",
	"GenreAlarm" : "Género: Alarme",
	"GenreAlarmTest" : "Género: Teste de Alarme",
	"GenreAllStations" : "Género: Todas as Estações",
	"GenreChildrens" : "Género: Filhos",
	"GenreClassics" : "Género: Clássicos",
	"GenreCountry" : "Género: Country",
	"GenreCulture" : "Género: Cultura",
	"GenreDocumentary" : "Género: Documentário",
	"GenreDrama" : "Género: Drama",
	"GenreEducation" : "Género: Educação",
	"GenreFinance" : "Género: Finanças",
	"GenreFolk" : "Género: Música Popular",
	"GenreInfo" : "Género: Informação",
	"GenreJazz" : "Género: Jazz",
	"GenreLeisure" : "Género: Lazer",
	"GenreLight" : "Género: Soft",
	"GenreList" : "Lista de Géneros",
	"GenreMor" : "Género: Calma",
	"GenreName" : "Género: {genreName}",
	"GenreNational" : "Género: Nacional",
	"GenreNews" : "Género: Notícias",
	"GenreOldies" : "Género: Antigos Sucessos",
	"GenreOther" : "Género: Outros",
	"GenrePhoneIn" : "Género: Telefone em",
	"GenrePop" : "Género: Pop",
	"GenreReligion" : "Género: Religião",
	"GenreRock" : "Género: Rock",
	"GenreScience" : "Género: Ciência",
	"GenreSeek" : "Procura de Género",
	"GenreSocial" : "Género: Social",
	"GenreSport" : "Género: Desporto",
	"GenreTravel" : "Género: Viagem",
	"GenreVaried" : "Género: Diversos",
	"GenreWeather" : "Género: Meteorologia",
	"HDRadio" : "Rádio HD",
	"HDStations" : "Estações HD",
	"Info" : "Informação",
	"IpodError" : "Erro no iPod",
	"IpodFull" : "iPod Completo",
	"Jazz" : "Jazz",
	"Leisure" : "Lazer",
	"Light" : "Soft",
	"ListUpdate" : "List Update",
	"MemoryFull" : "Memória Esgotada",
	"Mor" : "Calma",
	"National" : "Nacional",
	"News" : "Notícias",
	"Noresultsfound" : "Nenhum resultado encontrado",
	"Oldies" : "Antigos Sucessos",
	"Other" : "Outros",
	"PartialTransfer" : "Transferência Parcial",
	"PhoneIn" : "Chamada",
	"Pop" : "Pop",
	"RegionLock" : "Bloqueio da Região",
	"Religion" : "Religião",
	"Remaining" : "{numberOfTags} Restant.",
	"Remove" : "Remover",
	"Rock" : "Rock",
	"Science" : "Ciência",
	"SignalLost" : "Sinal Perdido",
	"Social" : "Social",
	"Sport" : "Desporto",
	"StationList" : "Lista de Estações",
	"TAOff" : "TA Desligado",
	"TagAlreadySaved" : "A Etiq. Já Foi Guardada",
	"TagCaptured" : "Etiqueta Capturada",
	"TagMemoryFull" : "Mem. de Etiq. Esgotada",
	"TagNotYetProcessed" : "Etiq. Ainda Não Processada",
	"TagSaved" : "Etiqueta Guardada",
	"TagSavedtoIpod" : "Etiqueta Guardada no iPod",
	"TagSavedtoSystem" : "Etiq. Guardada no Sistema",
	"TagTransferredtoiPod" : "Etiqueta Transf. para iPod",
	"TagsCannotBeSaved" : "Etiq. Não Guardadas",
	"Tooltip_IcnUmpFMSettings" : "Definições de FM",
	"TrafficAlert" : "Anúncio de Tráfego (TA)",
	"TrafficAlertOff" : "Anúncio de Tráfego (TA) desactivado",
	"TrafficAlertOn" : "Anúncio de Tráfego (TA) activado",
	"Travel" : "Viagem",
	"UnplugAndReconnect" : "Desl. e Restabelec. Ligação",
	"UpdateStationList" : "Actualizar Lista de Estações",
	"UpdatingStationList" : "Actualizar Lista de Estações",
	"Varied" : "Diversos",
	"VrHelp_AlternativeFrequencyOff" : "Frequência Alternativa Desligada",
	"VrHelp_AlternativeFrequencyOn" : "Frequência Alternativa Ligada",
	"VrHelp_AutoMemory" : "Memória Automática",
	"VrHelp_ChangeGenre" : "Alterar Género",
	"VrHelp_Entertainment" : "Entretenimento",
	"VrHelp_FMSettings" : "Definições de FM",
	"VrHelp_Favorites" : "Favoritos",
	"VrHelp_Frequency" : "(frequência)",
	"VrHelp_HDMenu" : "Canal HD Radio",
	"VrHelp_RegionLockOff" : "Bloqueio da Região Desligado",
	"VrHelp_RegionLockOn" : "Bloqueio da Região Ligado",
	"VrHelp_Scan" : "Procurar",
	"VrHelp_SeekDown" : "Procurar para Baixo",
	"VrHelp_SeekNext" : "Procurar Seguinte",
	"VrHelp_SeekPrevious" : "Procurar Anterior",
	"VrHelp_SeekUp" : "Procurar para Cima",
	"VrHelp_SoundSettings" : "Definições de Som",
	"VrHelp_StationList" : "Lista de Estações",
	"VrHelp_TrafficAnnouncement" : "Anúncio de Tráfego (TA)",
	"VrHelp_Tune" : "Sintonizar",
	"VrHelp_TuneDown" : "Sintonizar para Baixo",
	"VrHelp_TuneUp" : "Sintonizar para Cima",
	"VrHelp_UpdateList" : "Actualizar Lista",
	"VrHelp_iTunesTagging" : "Marcação do iTunes",
	"Weather" : "Meteorologia",
	"favorites_Tooltip" : "Favoritos",
	"hdChannels_Tooltip" : "Canais HD",
	"rbds_Adult" : "Sucessos Adultos",
	"rbds_Class" : "Rock Clássico",
	"rbds_Classical" : "Clássico",
	"rbds_College" : "Faculdade",
	"rbds_Country" : "Country",
	"rbds_Emergency" : "Alertar! Alertar!",
	"rbds_EmergencyTest" : "Teste de Emergência",
	"rbds_Foreign" : "Língua Estrangeira",
	"rbds_Hablar" : "Falar Espanhol",
	"rbds_HipHop" : "Hip Hop",
	"rbds_Info" : "Informação",
	"rbds_Jazz" : "Jazz",
	"rbds_Musica" : "Música Espanhola",
	"rbds_News" : "Notícias",
	"rbds_None" : "--",
	"rbds_Nostalgia" : "Nostalgia",
	"rbds_Oldies" : "Antigos Sucessos",
	"rbds_Personality" : "Personalidade",
	"rbds_Public" : "Público",
	"rbds_ReligousM" : "Música Religiosa",
	"rbds_ReligousT" : "Discussão Religiosa",
	"rbds_Rhythym" : "Rhytm & Blues",
	"rbds_Rock" : "Rock",
	"rbds_Soft" : "Suave",
	"rbds_SoftRB" : "Suave R&B",
	"rbds_SoftRock" : "Rock Suave",
	"rbds_Sports" : "Desporto",
	"rbds_Talk" : "Falar",
	"rbds_Top40" : "Top 40",
	"rbds_Weather" : "Meteorologia",
	"rbds_genre_Adult" : "Género: Sucessos Adultos",
	"rbds_genre_Class" : "Género: Rock Clássico",
	"rbds_genre_Classical" : "Género: Clássico",
	"rbds_genre_College" : "Género: Faculdade",
	"rbds_genre_Country" : "Género: Country",
	"rbds_genre_Emergency" : "Género: Alertar! Alertar!",
	"rbds_genre_EmergencyTest" : "Género: Teste de Emergência",
	"rbds_genre_Foreign" : "Género: Língua Estrangeira",
	"rbds_genre_Hablar" : "Género: Falar Espanhol",
	"rbds_genre_HipHop" : "Género: Hip Hop",
	"rbds_genre_Info" : "Género: Informação",
	"rbds_genre_Jazz" : "Género: Jazz",
	"rbds_genre_Musica" : "Género: Música Espanhola",
	"rbds_genre_News" : "Género: Notícias",
	"rbds_genre_None" : "Género: --",
	"rbds_genre_Nostalgia" : "Género: Nostalgia",
	"rbds_genre_Oldies" : "Género: Antigos Sucessos",
	"rbds_genre_Personality" : "Género: Personalidade",
	"rbds_genre_Public" : "Género: Público",
	"rbds_genre_ReligousM" : "Género: Música Religiosa",
	"rbds_genre_ReligousT" : "Género: Discussão Religiosa",
	"rbds_genre_Rhythym" : "Género: Rhytm & Blues",
	"rbds_genre_Rock" : "Género: Rock",
	"rbds_genre_Soft" : "Género: Suave",
	"rbds_genre_SoftRB" : "Género: Suave R&B",
	"rbds_genre_SoftRock" : "Género: Rock Suave",
	"rbds_genre_Sports" : "Género: Desporto",
	"rbds_genre_Talk" : "Género: Falar",
	"rbds_genre_Top40" : "Género: Top 40",
	"rbds_genre_Weather" : "Género: Meteorologia",
};

framework.registerAppDictLoaded("fmradio", "pt_PT");