var __VrHelpPositionTable__fmradioAppDict_es_ES = {
	"AutoMemory_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"AreaPresetJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"NowPlayingEU_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_FMSettings","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_TrafficAnnouncement","VrHelp_Scan"]
	},
	"AreaPresetJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"NowPlayingNA_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_iTunesTagging","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_HDMenu","VrHelp_Scan"]
	},
	"Settings_Help" : {
		"Left" : ["VrHelp_AlternativeFrequencyOn","VrHelp_AlternativeFrequencyOff","VrHelp_RegionLockOn","VrHelp_RegionLockOff"]
	},
	"Tune_NA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"StationListJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"StationListJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"GenreSeek_Help" : {
		"Left" : ["VrHelp_SeekUp","VrHelp_SeekDown","VrHelp_ChangeGenre"]
	},
	"NowPlayingJapan_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"Tune_nonNA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"NowPlayingOther_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"AutoMemory_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	}
};

var Localization_fmradioAppDict_es_ES = {
	//"stringId" : "localString"
	"Affairs" : "Affairs",
	"Alarm" : "Alarma",
	"AlarmTest" : "Prueba de alarma",
	"AllMemoryFull" : "Toda la memoria llena",
	"AllStations" : "Todas las emisoras",
	"AllTagsTransferred" : "Todas Etiq. transf.",
	"AlternativeFrequency" : "Frecuencia Alternativa",
	"AreaPresetTab" : "Area Preset",
	"AutoMemoryList" : "Lista de emisoras auto memorizadas",
	"CannotTransferTags" : "No puede transf. Etiq.",
	"ChangeGenre" : "Cambiar Género",
	"ChannelListJP" : "Channel List",
	"ChannelListTab" : "Channel List",
	"Childrens" : "Niños",
	"Classics" : "Clásicos",
	"Close" : "Cerrar ",
	"ConnectIPod" : "Conec Ipod y Transf Etiq",
	"Country" : "Country",
	"Culture" : "Cultura",
	"Documentary" : "Documentales",
	"Drama" : "Drama",
	"Education" : "Educación",
	"ErrorConnection" : "Error al transf. Etiq. al iPod",
	"FMRadio" : "Radio FM",
	"FMSettings" : "Ajustes de FM",
	"Finance" : "Economía",
	"Folk" : "Folk",
	"GenreAffairs" : "Género: Affairs",
	"GenreAlarm" : "Género: Alarma ",
	"GenreAlarmTest" : "Género: Prueba de alarma",
	"GenreAllStations" : "Género: Todas las Emisoras",
	"GenreChildrens" : "Género: Niños",
	"GenreClassics" : "Género: Clásicos",
	"GenreCountry" : "Género: Country",
	"GenreCulture" : "Género: Cultura",
	"GenreDocumentary" : "Género: Documental ",
	"GenreDrama" : "Género: Drama",
	"GenreEducation" : "Género: Educación",
	"GenreFinance" : "Género: Economía",
	"GenreFolk" : "Género: Folk",
	"GenreInfo" : "Tipo: Información",
	"GenreJazz" : "Género: Jazz",
	"GenreLeisure" : "Género: Ocio",
	"GenreLight" : "Género: Ligera",
	"GenreList" : "Lista de géneros",
	"GenreMor" : "Género: Música ligera",
	"GenreName" : "Género: {genreName}",
	"GenreNational" : "Género: Información nacional",
	"GenreNews" : "Género: Noticias",
	"GenreOldies" : "Género: Oldies",
	"GenreOther" : "Género: Otros",
	"GenrePhoneIn" : "Género: Comentarios por teléfono",
	"GenrePop" : "Género: Pop",
	"GenreReligion" : "Género: Religión",
	"GenreRock" : "Género: Rock",
	"GenreScience" : "Género: Ciencia",
	"GenreSeek" : "Buscar Género",
	"GenreSocial" : "Género: Social ",
	"GenreSport" : "Género: Deportes",
	"GenreTravel" : "Género: Viajes",
	"GenreVaried" : "Género: Variado",
	"GenreWeather" : "Género: El tiempo",
	"HDRadio" : "Radio HD",
	"HDStations" : "Emisoras HD",
	"Info" : "Información",
	"IpodError" : "Error de iPod",
	"IpodFull" : "iPod lleno",
	"Jazz" : "Jazz",
	"Leisure" : "Ocio",
	"Light" : "Ligera",
	"ListUpdate" : "List Update",
	"MemoryFull" : "Memoria llena",
	"Mor" : "Música ligera",
	"National" : "Información nacional",
	"News" : "Noticias",
	"Noresultsfound" : "No se encontraron resultados",
	"Oldies" : "Oldies",
	"Other" : "Otro",
	"PartialTransfer" : "Transferencia parcial",
	"PhoneIn" : "Comentarios por teléfono",
	"Pop" : "Pop",
	"RegionLock" : "Bloqueo de región",
	"Religion" : "Religión",
	"Remaining" : "{numberOfTags} Restant",
	"Remove" : "Eliminar ",
	"Rock" : "Rock",
	"Science" : "Ciencia",
	"SignalLost" : "Señal Perdida",
	"Social" : "Social",
	"Sport" : "Deportes",
	"StationList" : "Lista de Emisoras",
	"TAOff" : "TA Off",
	"TagAlreadySaved" : "Etiqueta guardada",
	"TagCaptured" : "Etiqueta Capturada",
	"TagMemoryFull" : "Memoria de etiquetas llena",
	"TagNotYetProcessed" : "Etiqueta aún no procesada",
	"TagSaved" : "Etiqueta Guardada",
	"TagSavedtoIpod" : "Etiq Guardada en iPod",
	"TagSavedtoSystem" : "Etiqueta Guardada en Sist",
	"TagTransferredtoiPod" : "Etiq Transf a iPod",
	"TagsCannotBeSaved" : "No puede guardar Etiq.",
	"Tooltip_IcnUmpFMSettings" : "Ajustes FM",
	"TrafficAlert" : "Anuncio de tráfico (TA)",
	"TrafficAlertOff" : "Anuncio de tráfico (TA) apagado",
	"TrafficAlertOn" : "Anuncio de tráfico (TA) encendido",
	"Travel" : "Viajes",
	"UnplugAndReconnect" : "Desconectar y Reconectar",
	"UpdateStationList" : "Actualizar lista de emisoras",
	"UpdatingStationList" : "Actualizando Lista de Emisoras",
	"Varied" : "Variado",
	"VrHelp_AlternativeFrequencyOff" : "Frecuencia Alternativa Desactivada",
	"VrHelp_AlternativeFrequencyOn" : "Frecuencia Alternativa Activada",
	"VrHelp_AutoMemory" : "Memoria automática",
	"VrHelp_ChangeGenre" : "Cambiar Género",
	"VrHelp_Entertainment" : "Entretenimiento",
	"VrHelp_FMSettings" : "Ajustes FM",
	"VrHelp_Favorites" : "Favorito",
	"VrHelp_Frequency" : "(frecuencia)",
	"VrHelp_HDMenu" : "Canales HD Radio",
	"VrHelp_RegionLockOff" : "Bloqueo Región apagado",
	"VrHelp_RegionLockOn" : "Bloqueo Región encendido",
	"VrHelp_Scan" : "Explorar",
	"VrHelp_SeekDown" : "Buscar Abajo",
	"VrHelp_SeekNext" : "Buscar Siguiente",
	"VrHelp_SeekPrevious" : "Buscar Anterior",
	"VrHelp_SeekUp" : "Buscar Arriba",
	"VrHelp_SoundSettings" : "Ajustes de Sonido",
	"VrHelp_StationList" : "Lista de Emisoras",
	"VrHelp_TrafficAnnouncement" : "Anuncio de tráfico (TA)",
	"VrHelp_Tune" : "Explorar",
	"VrHelp_TuneDown" : "Sintonizar Abajo",
	"VrHelp_TuneUp" : "Sintonizar Arriba",
	"VrHelp_UpdateList" : "Actualizar Lista",
	"VrHelp_iTunesTagging" : "Etiquetado de iTunes",
	"Weather" : "El tiempo",
	"favorites_Tooltip" : "Favoritos",
	"hdChannels_Tooltip" : "Canales HD",
	"rbds_Adult" : "Tipo adultos",
	"rbds_Class" : "Rock clásico",
	"rbds_Classical" : "Clásico",
	"rbds_College" : "Colegio",
	"rbds_Country" : "Country",
	"rbds_Emergency" : "¡Alerta! ¡Alerta!",
	"rbds_EmergencyTest" : "Prueba de emergencia",
	"rbds_Foreign" : "Lengua extranjera",
	"rbds_Hablar" : "Hablar Español",
	"rbds_HipHop" : "Hip Hop",
	"rbds_Info" : "Información",
	"rbds_Jazz" : "Jazz",
	"rbds_Musica" : "Música española",
	"rbds_News" : "Noticias",
	"rbds_None" : "--",
	"rbds_Nostalgia" : "Nostalgia",
	"rbds_Oldies" : "Viejos éxitos",
	"rbds_Personality" : "Personalidad",
	"rbds_Public" : "Público",
	"rbds_ReligousM" : "Música religiosa",
	"rbds_ReligousT" : "Habla religiosa",
	"rbds_Rhythym" : "Rhythm and Blues",
	"rbds_Rock" : "Rock",
	"rbds_Soft" : "Suave",
	"rbds_SoftRB" : "Suave R&B",
	"rbds_SoftRock" : "Rock Suave",
	"rbds_Sports" : "Deportes",
	"rbds_Talk" : "Hablar",
	"rbds_Top40" : "Top 40",
	"rbds_Weather" : "El tiempo",
	"rbds_genre_Adult" : "Género: Tipo adultos",
	"rbds_genre_Class" : "Género: Rock clásico",
	"rbds_genre_Classical" : "Género: Clásico",
	"rbds_genre_College" : "Género: Colegio",
	"rbds_genre_Country" : "Género: Country",
	"rbds_genre_Emergency" : "Género: ¡Alerta! ¡Alerta!",
	"rbds_genre_EmergencyTest" : "Género: Prueba de Emergen.",
	"rbds_genre_Foreign" : "Género: Lengua Extranjera",
	"rbds_genre_Hablar" : "Género: Hablar Español",
	"rbds_genre_HipHop" : "Género: Hip Hop",
	"rbds_genre_Info" : "Género: Información",
	"rbds_genre_Jazz" : "Género: Jazz",
	"rbds_genre_Musica" : "Género: Música española",
	"rbds_genre_News" : "Género: Noticias",
	"rbds_genre_None" : "Género: --",
	"rbds_genre_Nostalgia" : "Género: Nostalgia",
	"rbds_genre_Oldies" : "Género: Viejos éxitos",
	"rbds_genre_Personality" : "Género: Personalidad",
	"rbds_genre_Public" : "Género: Público",
	"rbds_genre_ReligousM" : "Género: Música religiosa",
	"rbds_genre_ReligousT" : "Género: Habla religiosa",
	"rbds_genre_Rhythym" : "Género: Rhythm and Blues",
	"rbds_genre_Rock" : "Género: Rock",
	"rbds_genre_Soft" : "Género: Suave",
	"rbds_genre_SoftRB" : "Género: Suave R&B",
	"rbds_genre_SoftRock" : "Género: Rock Suave",
	"rbds_genre_Sports" : "Género: Deportes",
	"rbds_genre_Talk" : "Género: Tertúlia",
	"rbds_genre_Top40" : "Género: Top 40",
	"rbds_genre_Weather" : "Género: El tiempo",
};

framework.registerAppDictLoaded("fmradio", "es_ES");