var __VrHelpPositionTable__fmradioAppDict_bg_BG = {
	"AutoMemory_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"AreaPresetJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"NowPlayingEU_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_FMSettings","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_TrafficAnnouncement","VrHelp_Scan"]
	},
	"AreaPresetJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"NowPlayingNA_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_iTunesTagging","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_HDMenu","VrHelp_Scan"]
	},
	"Settings_Help" : {
		"Left" : ["VrHelp_AlternativeFrequencyOn","VrHelp_AlternativeFrequencyOff","VrHelp_RegionLockOn","VrHelp_RegionLockOff"]
	},
	"Tune_NA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"StationListJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"StationListJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"GenreSeek_Help" : {
		"Left" : ["VrHelp_SeekUp","VrHelp_SeekDown","VrHelp_ChangeGenre"]
	},
	"NowPlayingJapan_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"Tune_nonNA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"NowPlayingOther_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"AutoMemory_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	}
};

var Localization_fmradioAppDict_bg_BG = {
	//"stringId" : "localString"
	"Affairs" : "Актуално",
	"Alarm" : "Аларма",
	"AlarmTest" : "Тест на алармата",
	"AllMemoryFull" : "Цялата памет е пълна",
	"AllStations" : "Всички станции",
	"AllTagsTransferred" : "Вс. таг. са прехв.",
	"AlternativeFrequency" : "Алтернативна честота",
	"AreaPresetTab" : "Area Preset",
	"AutoMemoryList" : "Списък с авт. запаметени",
	"CannotTransferTags" : "Таг-те не се прехв.",
	"ChangeGenre" : "Промяна на жанра",
	"ChannelListJP" : "Channel List",
	"ChannelListTab" : "Channel List",
	"Childrens" : "Детски",
	"Classics" : "Класика",
	"Close" : "Затв.",
	"ConnectIPod" : "Свър. iPod за прехв. таг.",
	"Country" : "Страна",
	"Culture" : "Култура",
	"Documentary" : "Документален",
	"Drama" : "Драма",
	"Education" : "Образование",
	"ErrorConnection" : "Грешка прехв. таг. в iPod",
	"FMRadio" : "Радио FM",
	"FMSettings" : "Настройки за FM",
	"Finance" : "Финанси",
	"Folk" : "Фолк",
	"GenreAffairs" : "Жанр: актуално",
	"GenreAlarm" : "Жанр: аларма",
	"GenreAlarmTest" : "Жанр: тест на алармата",
	"GenreAllStations" : "Жанр: всички станции",
	"GenreChildrens" : "Жанр: детски",
	"GenreClassics" : "Жанр: класика",
	"GenreCountry" : "Жанр: страна",
	"GenreCulture" : "Жанр: култура",
	"GenreDocumentary" : "Жанр: документален",
	"GenreDrama" : "Жанр: драма",
	"GenreEducation" : "Жанр: образование",
	"GenreFinance" : "Жанр: финанси",
	"GenreFolk" : "Жанр: фолк",
	"GenreInfo" : "Жанр: информация",
	"GenreJazz" : "Жанр: джаз",
	"GenreLeisure" : "Жанр: отдих",
	"GenreLight" : "Жанр: лек",
	"GenreList" : "Списък с жанрове",
	"GenreMor" : "Жанр: лека музика",
	"GenreName" : "Жанр: {genreName}",
	"GenreNational" : "Жанр: национални",
	"GenreNews" : "Жанр: новини",
	"GenreOldies" : "Жанр: ретро",
	"GenreOther" : "Жанр: други",
	"GenrePhoneIn" : "Жанр: обаждания на слушатели",
	"GenrePop" : "Жанр: поп",
	"GenreReligion" : "Жанр: религия",
	"GenreRock" : "Жанр: рок",
	"GenreScience" : "Жанр: наука",
	"GenreSeek" : "Търсене на жанр",
	"GenreSocial" : "Жанр: социални",
	"GenreSport" : "Жанр: спорт",
	"GenreTravel" : "Жанр: туризъм",
	"GenreVaried" : "Жанр: разни",
	"GenreWeather" : "Жанр: времето",
	"HDRadio" : "Радио HD",
	"HDStations" : "Станции HD",
	"Info" : "Информация ",
	"IpodError" : "Грешка в iPod",
	"IpodFull" : "iPod е пълен",
	"Jazz" : "Джаз",
	"Leisure" : "Отдих",
	"Light" : "Светло",
	"ListUpdate" : "List Update",
	"MemoryFull" : "Паметта е пълна",
	"Mor" : "Лека музика ",
	"National" : "Национални",
	"News" : "Новини",
	"Noresultsfound" : "Няма намерени резултати",
	"Oldies" : "Ретро",
	"Other" : "Други",
	"PartialTransfer" : "Частичен трансфер",
	"PhoneIn" : "Обаждания на слушатели",
	"Pop" : "Поп",
	"RegionLock" : "Заключване по регион",
	"Religion" : "Религия",
	"Remaining" : "Остават {numberOfTags}",
	"Remove" : "Изтриване",
	"Rock" : "Рок",
	"Science" : "Наука",
	"SignalLost" : "Сигналът е изгубен",
	"Social" : "Социални",
	"Sport" : "Спорт",
	"StationList" : "Списък със станции",
	"TAOff" : "Изкл. пр. дв.",
	"TagAlreadySaved" : "Тагът е вече записан",
	"TagCaptured" : "Тагът е снет",
	"TagMemoryFull" : "Пълна памет за тагове",
	"TagNotYetProcessed" : "Тагът не е обработен",
	"TagSaved" : "Тагът е записан",
	"TagSavedtoIpod" : "Тагът е записан в iPod",
	"TagSavedtoSystem" : "Тагът е записан в сист.",
	"TagTransferredtoiPod" : "Тагът прехв. в iPod",
	"TagsCannotBeSaved" : "Таг-те не се записв.",
	"Tooltip_IcnUmpFMSettings" : "Настройки за FM",
	"TrafficAlert" : "Предупр. движение",
	"TrafficAlertOff" : "Изключено предупреждение за движението",
	"TrafficAlertOn" : "Включено предупреждение за движението",
	"Travel" : "Туризъм",
	"UnplugAndReconnect" : "Изв. и свър. пак",
	"UpdateStationList" : "Акт. спис. станции",
	"UpdatingStationList" : "Актуал. спис. станции",
	"Varied" : "Разни",
	"VrHelp_AlternativeFrequencyOff" : "Alternative Frequency Off",
	"VrHelp_AlternativeFrequencyOn" : "Alternative Frequency On",
	"VrHelp_AutoMemory" : "Auto Memory",
	"VrHelp_ChangeGenre" : "Change Genre",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_FMSettings" : "FM Settings",
	"VrHelp_Favorites" : "Favorites",
	"VrHelp_Frequency" : "(frequency)",
	"VrHelp_HDMenu" : "HD Radio Channels",
	"VrHelp_RegionLockOff" : "Region Lock Off",
	"VrHelp_RegionLockOn" : "Region Lock On",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SeekDown" : "Seek Down",
	"VrHelp_SeekNext" : "Seek Next",
	"VrHelp_SeekPrevious" : "Seek Previous",
	"VrHelp_SeekUp" : "Seek Up",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement (TA)",
	"VrHelp_Tune" : "Tune",
	"VrHelp_TuneDown" : "Tune Down",
	"VrHelp_TuneUp" : "Tune Up",
	"VrHelp_UpdateList" : "Update List",
	"VrHelp_iTunesTagging" : "iTunes Tagging",
	"Weather" : "Времето",
	"favorites_Tooltip" : "Предпочитани",
	"hdChannels_Tooltip" : "Канали HD",
	"rbds_Adult" : "Смесени хитове",
	"rbds_Class" : "Класически рок",
	"rbds_Classical" : "Класическа музика",
	"rbds_College" : "Kолеж",
	"rbds_Country" : "Страна",
	"rbds_Emergency" : "Предупреждение! Предупреждение!",
	"rbds_EmergencyTest" : "Авариeн тест",
	"rbds_Foreign" : "Чужд език",
	"rbds_Hablar" : "Говорейки испански",
	"rbds_HipHop" : "Хип хоп",
	"rbds_Info" : "Информация",
	"rbds_Jazz" : "Джаз",
	"rbds_Musica" : "Испански музика",
	"rbds_News" : "Новини",
	"rbds_None" : "--",
	"rbds_Nostalgia" : "Носталгия",
	"rbds_Oldies" : "Ретро",
	"rbds_Personality" : "Личност",
	"rbds_Public" : "Обществено",
	"rbds_ReligousM" : "Религиозна музика",
	"rbds_ReligousT" : "Религиозни разговори",
	"rbds_Rhythym" : "Ритъм и блус",
	"rbds_Rock" : "Рок",
	"rbds_Soft" : "Софт",
	"rbds_SoftRB" : "Софт ритъм и блус",
	"rbds_SoftRock" : "Софт рок",
	"rbds_Sports" : "Спорт",
	"rbds_Talk" : "Ток",
	"rbds_Top40" : "Топ 40",
	"rbds_Weather" : "Времето",
	"rbds_genre_Adult" : "Жанр: Смесени хитове",
	"rbds_genre_Class" : "Жанр: Класически рок",
	"rbds_genre_Classical" : "Жанр: Класическа музика",
	"rbds_genre_College" : "Жанр: Kолеж",
	"rbds_genre_Country" : "Жанр: Страна",
	"rbds_genre_Emergency" : "Жанр: Предупр.! Предупр.!",
	"rbds_genre_EmergencyTest" : "Жанр: Авариeн тест",
	"rbds_genre_Foreign" : "Жанр: Чужд език",
	"rbds_genre_Hablar" : "Жанр: Говорейки испански",
	"rbds_genre_HipHop" : "Жанр: Хип хоп",
	"rbds_genre_Info" : "Жанр: Информация",
	"rbds_genre_Jazz" : "Жанр: Джаз",
	"rbds_genre_Musica" : "Жанр: Испански музика",
	"rbds_genre_News" : "Жанр: Новини",
	"rbds_genre_None" : "Жанр: --",
	"rbds_genre_Nostalgia" : "Жанр: Носталгия",
	"rbds_genre_Oldies" : "Жанр: Ретро",
	"rbds_genre_Personality" : "Жанр: Личност",
	"rbds_genre_Public" : "Жанр: Обществено",
	"rbds_genre_ReligousM" : "Жанр: Религиозна музика",
	"rbds_genre_ReligousT" : "Жанр: Религиозни разговори",
	"rbds_genre_Rhythym" : "Жанр: Ритъм и блус",
	"rbds_genre_Rock" : "Жанр: Рок",
	"rbds_genre_Soft" : "Жанр: Софт",
	"rbds_genre_SoftRB" : "Жанр: Софт ритъм и блус",
	"rbds_genre_SoftRock" : "Жанр: Софт рок",
	"rbds_genre_Sports" : "Жанр: Спорт",
	"rbds_genre_Talk" : "Жанр: Ток",
	"rbds_genre_Top40" : "Жанр: Топ 40",
	"rbds_genre_Weather" : "Жанр: Времето",
};

framework.registerAppDictLoaded("fmradio", "bg_BG");