var __VrHelpPositionTable__fmradioAppDict_hr_HR = {
	"AutoMemory_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"AreaPresetJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"NowPlayingEU_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_FMSettings","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_TrafficAnnouncement","VrHelp_Scan"]
	},
	"AreaPresetJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"NowPlayingNA_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_iTunesTagging","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_HDMenu","VrHelp_Scan"]
	},
	"Settings_Help" : {
		"Left" : ["VrHelp_AlternativeFrequencyOn","VrHelp_AlternativeFrequencyOff","VrHelp_RegionLockOn","VrHelp_RegionLockOff"]
	},
	"Tune_NA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"StationListJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"StationListJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"GenreSeek_Help" : {
		"Left" : ["VrHelp_SeekUp","VrHelp_SeekDown","VrHelp_ChangeGenre"]
	},
	"NowPlayingJapan_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"Tune_nonNA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"NowPlayingOther_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"AutoMemory_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	}
};

var Localization_fmradioAppDict_hr_HR = {
	//"stringId" : "localString"
	"Affairs" : "Poslovi",
	"Alarm" : "Alarm",
	"AlarmTest" : "Test alarma",
	"AllMemoryFull" : "Memorija je puna",
	"AllStations" : "Sve stanice",
	"AllTagsTransferred" : "Sve oznake prenesene",
	"AlternativeFrequency" : "Alternativna frekvencija",
	"AreaPresetTab" : "Area Preset",
	"AutoMemoryList" : "Popis automatske memorije",
	"CannotTransferTags" : "Oznake nemoguće prenijeti",
	"ChangeGenre" : "Promijeni žanr",
	"ChannelListJP" : "Channel List",
	"ChannelListTab" : "Channel List",
	"Childrens" : "Djeca",
	"Classics" : "Klasika",
	"Close" : "Zatv.",
	"ConnectIPod" : "Poveži iPod na ozn. prijen.",
	"Country" : "Država",
	"Culture" : "Kultura",
	"Documentary" : "Dokumentarni",
	"Drama" : "Drama",
	"Education" : "Obrazovanje",
	"ErrorConnection" : "Pogr. pri prij. ozn. na iPod",
	"FMRadio" : "FM radio",
	"FMSettings" : "FM postavke",
	"Finance" : "Financije",
	"Folk" : "Narodna glazba",
	"GenreAffairs" : "Žanr: poslovi",
	"GenreAlarm" : "Žanr: alarm",
	"GenreAlarmTest" : "Žanr: test alarma",
	"GenreAllStations" : "Žanr: sve postaje",
	"GenreChildrens" : "Žanr: djeca",
	"GenreClassics" : "Žanr: klasika",
	"GenreCountry" : "Žanr: country",
	"GenreCulture" : "Žanr: kultura",
	"GenreDocumentary" : "Žanr: dokumentarni",
	"GenreDrama" : "Žanr: drama",
	"GenreEducation" : "Žanr: obrazovanje",
	"GenreFinance" : "Žanr: financije",
	"GenreFolk" : "Žanr: narodna glazba",
	"GenreInfo" : "Žanr: Informacije",
	"GenreJazz" : "Žanr: jazz",
	"GenreLeisure" : "Žanr: slobodno vrijeme",
	"GenreLight" : "Žanr: lagano",
	"GenreList" : "Popis žanrova",
	"GenreMor" : "Žanr: Ugodno slušanje",
	"GenreName" : "Žanr: {genreName}",
	"GenreNational" : "Žanr: nacionalno",
	"GenreNews" : "Žanr: vijesti",
	"GenreOldies" : "Žanr: stari hitovi",
	"GenreOther" : "Žanr: ostalo",
	"GenrePhoneIn" : "Žanr: ulaz telefona",
	"GenrePop" : "Žanr: pop",
	"GenreReligion" : "Žanr: religijski",
	"GenreRock" : "Žanr: rock",
	"GenreScience" : "Žanr: znanost",
	"GenreSeek" : "Traženje žanra",
	"GenreSocial" : "Žanr: društveni",
	"GenreSport" : "Žanr: sport",
	"GenreTravel" : "Žanr: putovanja",
	"GenreVaried" : "Žanr: raznoliko",
	"GenreWeather" : "Žanr: vrijeme",
	"HDRadio" : "HD radio",
	"HDStations" : "HD stanice",
	"Info" : "Informacije",
	"IpodError" : "Pogreška iPoda",
	"IpodFull" : "iPod pun",
	"Jazz" : "Jazz",
	"Leisure" : "Slobodno vrijeme",
	"Light" : "Lagano",
	"ListUpdate" : "List Update",
	"MemoryFull" : "Puna memorija",
	"Mor" : "Ugodno slušanje",
	"National" : "Nacionalno",
	"News" : "Vijesti",
	"Noresultsfound" : "Nisu pronađeni rezultati",
	"Oldies" : "Stari hitovi",
	"Other" : "Drugi",
	"PartialTransfer" : "Djelimični prijenos",
	"PhoneIn" : "Nazovite",
	"Pop" : "Pop",
	"RegionLock" : "Regionalna blokada",
	"Religion" : "Religijski",
	"Remaining" : "Preostalo {numberOfTags}",
	"Remove" : "Ukloni",
	"Rock" : "Rock",
	"Science" : "Znanost",
	"SignalLost" : "Signal izgubljen",
	"Social" : "Društveni",
	"Sport" : "Sport",
	"StationList" : "Popis postaja",
	"TAOff" : "TA isključen",
	"TagAlreadySaved" : " Oznaka je već spremljena ",
	"TagCaptured" : "Oznaka snimlj.",
	"TagMemoryFull" : "Memorija oznakaa puna",
	"TagNotYetProcessed" : "Oznaka još nije obrađena",
	"TagSaved" : "Oznaka spremljena",
	"TagSavedtoIpod" : "Oznaka spremljena u iPod",
	"TagSavedtoSystem" : "Oznaka spremljena u sust.",
	"TagTransferredtoiPod" : "Oznaka prenesena u iPod",
	"TagsCannotBeSaved" : "Ozn. nije moguće spremiti",
	"Tooltip_IcnUmpFMSettings" : "FM postavke",
	"TrafficAlert" : "Prometna objava (TA)",
	"TrafficAlertOff" : "Prometna objava (TA) isklj",
	"TrafficAlertOn" : "Prometna objava (TA) uklj",
	"Travel" : "Putovanje",
	"UnplugAndReconnect" : "Isključi i ponovno poveži",
	"UpdateStationList" : "Ažuriraj popis postaja ",
	"UpdatingStationList" : "Ažuriranje popisa postaja ",
	"Varied" : "Raznoliko",
	"VrHelp_AlternativeFrequencyOff" : "Alternative Frequency Off",
	"VrHelp_AlternativeFrequencyOn" : "Alternative Frequency On",
	"VrHelp_AutoMemory" : "Auto Memory",
	"VrHelp_ChangeGenre" : "Change Genre",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_FMSettings" : "FM Settings",
	"VrHelp_Favorites" : "Favorites",
	"VrHelp_Frequency" : "(frequency)",
	"VrHelp_HDMenu" : "HD Radio Channels",
	"VrHelp_RegionLockOff" : "Region Lock Off",
	"VrHelp_RegionLockOn" : "Region Lock On",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SeekDown" : "Seek Down",
	"VrHelp_SeekNext" : "Seek Next",
	"VrHelp_SeekPrevious" : "Seek Previous",
	"VrHelp_SeekUp" : "Seek Up",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement (TA)",
	"VrHelp_Tune" : "Tune",
	"VrHelp_TuneDown" : "Tune Down",
	"VrHelp_TuneUp" : "Tune Up",
	"VrHelp_UpdateList" : "Update List",
	"VrHelp_iTunesTagging" : "iTunes Tagging",
	"Weather" : "Vrijeme",
	"favorites_Tooltip" : "Favoriti",
	"hdChannels_Tooltip" : "HD kanali",
	"rbds_Adult" : "Odrasle Posjeta",
	"rbds_Class" : "Klasični Rock",
	"rbds_Classical" : "Klasika",
	"rbds_College" : "Koledž",
	"rbds_Country" : "Država",
	"rbds_Emergency" : "Uzbuna! Uzbuna!",
	"rbds_EmergencyTest" : "Hitna Test",
	"rbds_Foreign" : "Strani Jezik",
	"rbds_Hablar" : "Govoreći Španjolski",
	"rbds_HipHop" : "Hip Hop",
	"rbds_Info" : "Informacije",
	"rbds_Jazz" : "Jazz",
	"rbds_Musica" : "Španjolski Glazba",
	"rbds_News" : "Vijesti",
	"rbds_None" : "--",
	"rbds_Nostalgia" : "Nostalgija",
	"rbds_Oldies" : "Stari hitovi",
	"rbds_Personality" : "Ličnost",
	"rbds_Public" : "Javni",
	"rbds_ReligousM" : "Vjerska Glazba",
	"rbds_ReligousT" : "Vjerski Razgovor",
	"rbds_Rhythym" : "Ritam i Blues",
	"rbds_Rock" : "Rock",
	"rbds_Soft" : "Mekan",
	"rbds_SoftRB" : "Mekan R&B",
	"rbds_SoftRock" : "Soft Rock",
	"rbds_Sports" : "Sports",
	"rbds_Talk" : "Govoriti",
	"rbds_Top40" : "Top 40",
	"rbds_Weather" : "Vrijeme",
	"rbds_genre_Adult" : "Žanr: Odrasle Posjeta",
	"rbds_genre_Class" : "Žanr: Klasični Rock",
	"rbds_genre_Classical" : "Žanr: Klasika",
	"rbds_genre_College" : "Žanr: Koledž",
	"rbds_genre_Country" : "Žanr: Država",
	"rbds_genre_Emergency" : "Žanr: Uzbuna! Uzbuna!",
	"rbds_genre_EmergencyTest" : "Žanr: Hitna Test",
	"rbds_genre_Foreign" : "Žanr: Strani Jezik",
	"rbds_genre_Hablar" : "Žanr: Govoreći Španjolski",
	"rbds_genre_HipHop" : "Žanr: Hip Hop",
	"rbds_genre_Info" : "Žanr: Informacije",
	"rbds_genre_Jazz" : "Žanr: Country",
	"rbds_genre_Musica" : "Žanr: Španjolski Glazba",
	"rbds_genre_News" : "Žanr: Vijesti",
	"rbds_genre_None" : "Žanr: --",
	"rbds_genre_Nostalgia" : "Žanr: Nostalgija",
	"rbds_genre_Oldies" : "Žanr: Stari hitovi",
	"rbds_genre_Personality" : "Žanr: Ličnost",
	"rbds_genre_Public" : "Žanr: Javni",
	"rbds_genre_ReligousM" : "Žanr: Vjerska Glazba",
	"rbds_genre_ReligousT" : "Žanr: Vjerski Razgovor",
	"rbds_genre_Rhythym" : "Žanr: Ritam i Blues",
	"rbds_genre_Rock" : "Žanr: Rock",
	"rbds_genre_Soft" : "Žanr: Mekan",
	"rbds_genre_SoftRB" : "Žanr: Mekan R&B",
	"rbds_genre_SoftRock" : "Žanr: Soft Rock",
	"rbds_genre_Sports" : "Žanr: Sports",
	"rbds_genre_Talk" : "Žanr: Govoriti",
	"rbds_genre_Top40" : "Žanr: Top 40",
	"rbds_genre_Weather" : "Žanr: Vrijeme",
};

framework.registerAppDictLoaded("fmradio", "hr_HR");