var __VrHelpPositionTable__fmradioAppDict_he_IL = {
	"AutoMemory_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"AreaPresetJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"NowPlayingEU_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_FMSettings","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_TrafficAnnouncement","VrHelp_Scan"]
	},
	"AreaPresetJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"NowPlayingNA_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_iTunesTagging","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_HDMenu","VrHelp_Scan"]
	},
	"Settings_Help" : {
		"Left" : ["VrHelp_AlternativeFrequencyOn","VrHelp_AlternativeFrequencyOff","VrHelp_RegionLockOn","VrHelp_RegionLockOff"]
	},
	"Tune_NA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"StationListJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"StationListJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"GenreSeek_Help" : {
		"Left" : ["VrHelp_SeekUp","VrHelp_SeekDown","VrHelp_ChangeGenre"]
	},
	"NowPlayingJapan_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"Tune_nonNA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"NowPlayingOther_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"AutoMemory_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	}
};

var Localization_fmradioAppDict_he_IL = {
	//"stringId" : "localString"
	"Affairs" : "עניינים",
	"Alarm" : "אזעקה",
	"AlarmTest" : "ניסוי אזעקה",
	"AllMemoryFull" : "כל הזכרון מלא",
	"AllStations" : "כל התחנות",
	"AllTagsTransferred" : "כל התגיות הועברו",
	"AlternativeFrequency" : "תדר חלופי",
	"AreaPresetTab" : "Area Preset",
	"AutoMemoryList" : "רשימת זכרון אוטומטי",
	"CannotTransferTags" : "לא ניתן להעביר תגיות",
	"ChangeGenre" : "שינוי ז'אנר",
	"ChannelListJP" : "Channel List",
	"ChannelListTab" : "Channel List",
	"Childrens" : "ילדים",
	"Classics" : "קלאסיקות",
	"Close" : "סגור",
	"ConnectIPod" : "חבר אייפוד ",
	"Country" : "ארץ",
	"Culture" : "תרבות",
	"Documentary" : "תיעודי",
	"Drama" : "דרמה",
	"Education" : "חינוך",
	"ErrorConnection" : "שגיאה בהתקשרות",
	"FMRadio" : "רדיו FM",
	"FMSettings" : "הגדרות FM",
	"Finance" : "עסקים",
	"Folk" : "שירי עם",
	"GenreAffairs" : "ז'אנר: עסקים",
	"GenreAlarm" : "ז'אנר: אזעקה",
	"GenreAlarmTest" : "ז'אנר: ניסוי אזעקה",
	"GenreAllStations" : "ז'אנר: כל התחנות",
	"GenreChildrens" : "ז'אנר: ילדים",
	"GenreClassics" : "ז'אנר: קלסיקה",
	"GenreCountry" : "ז'אנר: ארץ",
	"GenreCulture" : "ז'אנר: תרבות",
	"GenreDocumentary" : "ז'אנר: תיעודי",
	"GenreDrama" : "ז'אנר: דרמה",
	"GenreEducation" : "ז'אנר: חינוך",
	"GenreFinance" : "ז'אנר: עסקים",
	"GenreFolk" : "ז'אנר: שירי עם",
	"GenreInfo" : "ז'אנר: מידע",
	"GenreJazz" : "ז'אנר: ג'אז",
	"GenreLeisure" : "ז'אנר: פנאי",
	"GenreLight" : "ז'אנר: קליל",
	"GenreList" : "רשימת ז'אנרים",
	"GenreMor" : "ז'אנר: האזנה קלה",
	"GenreName" : "סוג: {genreName}",
	"GenreNational" : "ז'אנר: לאומי",
	"GenreNews" : "ז'אנר: חדשות",
	"GenreOldies" : "ז'אנר: נוסטלגיה",
	"GenreOther" : "ז'אנר : אחר",
	"GenrePhoneIn" : "ז'אנר: התקשר",
	"GenrePop" : "ז'אנר: פופ",
	"GenreReligion" : "ז'אנר: דת",
	"GenreRock" : "ז'אנר: רוק",
	"GenreScience" : "ז'אנר: מדע",
	"GenreSeek" : "חיפוש ז'אנר",
	"GenreSocial" : "ז'אנר: חברתי",
	"GenreSport" : "ז'אנר: ספורט",
	"GenreTravel" : "ז'אנר: נסיעות",
	"GenreVaried" : "ז'אנר: משתנה",
	"GenreWeather" : "ז'אנר: מזג אויר",
	"HDRadio" : "רדיו HD",
	"HDStations" : "תחנות HD",
	"Info" : "מידע",
	"IpodError" : "שגיאת iPod",
	"IpodFull" : "iPod מלא",
	"Jazz" : "ג'אז",
	"Leisure" : "פנאי",
	"Light" : "קליל",
	"ListUpdate" : "List Update",
	"MemoryFull" : "זיכרון מלא",
	"Mor" : "האזנה קלה",
	"National" : "לאומי",
	"News" : "חדשות",
	"Noresultsfound" : "לא נמצאו תוצאות",
	"Oldies" : "נוסטלגיה",
	"Other" : "אחר",
	"PartialTransfer" : "העברה חלקית",
	"PhoneIn" : "התקשר",
	"Pop" : "פופ",
	"RegionLock" : "נעילת אזור",
	"Religion" : "דת",
	"Remaining" : "נותרו {numberOfTags}",
	"Remove" : "הסר",
	"Rock" : "רוק",
	"Science" : "מדע",
	"SignalLost" : "אות אבד",
	"Social" : "חברה",
	"Sport" : "ספורט",
	"StationList" : "רשימת תחנות",
	"TAOff" : "TA כבוי",
	"TagAlreadySaved" : "תגית כבר נשמרה",
	"TagCaptured" : "התג אותר",
	"TagMemoryFull" : "זיכרון התגיות מלא",
	"TagNotYetProcessed" : "תגית עוד לא עובדה",
	"TagSaved" : "התגית נשמרה",
	"TagSavedtoIpod" : "התגית נשמרה ב-iPod",
	"TagSavedtoSystem" : "התגית נשמרה במערכת",
	"TagTransferredtoiPod" : "תגית הועברה ל-iPod",
	"TagsCannotBeSaved" : "לא ניתן לשמור תגיות",
	"Tooltip_IcnUmpFMSettings" : "הגדרות FM",
	"TrafficAlert" : "הודעת תנועה",
	"TrafficAlertOff" : "הודעת תנועה כבוי",
	"TrafficAlertOn" : "הודעת תנועה מופעל",
	"Travel" : "נסיעות",
	"UnplugAndReconnect" : "נתק וחבר מחדש",
	"UpdateStationList" : "עדכן רשימת תחנות",
	"UpdatingStationList" : "מעדכן את רשימת התחנות",
	"Varied" : "משתנה",
	"VrHelp_AlternativeFrequencyOff" : "Alternative Frequency Off",
	"VrHelp_AlternativeFrequencyOn" : "Alternative Frequency On",
	"VrHelp_AutoMemory" : "Auto Memory",
	"VrHelp_ChangeGenre" : "Change Genre",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_FMSettings" : "FM Settings",
	"VrHelp_Favorites" : "Favorites",
	"VrHelp_Frequency" : "(frequency)",
	"VrHelp_HDMenu" : "HD Radio Channels",
	"VrHelp_RegionLockOff" : "Region Lock Off",
	"VrHelp_RegionLockOn" : "Region Lock On",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SeekDown" : "Seek Down",
	"VrHelp_SeekNext" : "Seek Next",
	"VrHelp_SeekPrevious" : "Seek Previous",
	"VrHelp_SeekUp" : "Seek Up",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement (TA)\u200e",
	"VrHelp_Tune" : "Tune",
	"VrHelp_TuneDown" : "Tune Down",
	"VrHelp_TuneUp" : "Tune Up",
	"VrHelp_UpdateList" : "Update List",
	"VrHelp_iTunesTagging" : "iTunes Tagging",
	"Weather" : "מזג אוויר",
	"favorites_Tooltip" : "מועדפים",
	"hdChannels_Tooltip" : "ערוצי HD",
	"rbds_Adult" : "כניסות למבוגרים",
	"rbds_Class" : "רוק קלאסי",
	"rbds_Classical" : "קלאסי",
	"rbds_College" : "מכללה",
	"rbds_Country" : "קאנטרי",
	"rbds_Emergency" : "התראה! התראה!",
	"rbds_EmergencyTest" : "מבחן חירום",
	"rbds_Foreign" : "לועזית",
	"rbds_Hablar" : "אם כבר מדברים ספרדית",
	"rbds_HipHop" : "היפ הופ",
	"rbds_Info" : "מידע",
	"rbds_Jazz" : "ג'אז",
	"rbds_Musica" : "מוסיקה ספרדית",
	"rbds_News" : "חדשות",
	"rbds_None" : "--",
	"rbds_Nostalgia" : "נוסטלגיה",
	"rbds_Oldies" : "שירים ישנים",
	"rbds_Personality" : "אישיות",
	"rbds_Public" : "ציבורי",
	"rbds_ReligousM" : "מוסיקה דתית",
	"rbds_ReligousT" : "שיחה דתית",
	"rbds_Rhythym" : "ריתם אנד בלוז",
	"rbds_Rock" : "רוק",
	"rbds_Soft" : "רך",
	"rbds_SoftRB" : "ריתם אנד בלוז רך",
	"rbds_SoftRock" : "רוק רך",
	"rbds_Sports" : "ספורט",
	"rbds_Talk" : "מֶלֶל",
	"rbds_Top40" : "40 נבחרים",
	"rbds_Weather" : "מזג אויר",
	"rbds_genre_Adult" : "ג'אנר: כניסות למבוגרים",
	"rbds_genre_Class" : "ג'אנר: רוק קלאסי",
	"rbds_genre_Classical" : "ג'אנר: קלאסי",
	"rbds_genre_College" : "ג'אנר: מכללה",
	"rbds_genre_Country" : "ג'אנר: קאנטרי",
	"rbds_genre_Emergency" : "ג'אנר: התראה! התראה!",
	"rbds_genre_EmergencyTest" : "ג'אנר: מבחן חירום",
	"rbds_genre_Foreign" : "ג'אנר: לועזית",
	"rbds_genre_Hablar" : "ג'אנר: אם כבר מדברים ספרדית",
	"rbds_genre_HipHop" : "ג'אנר: היפ הופ",
	"rbds_genre_Info" : "ג'אנר: מידע",
	"rbds_genre_Jazz" : "ג'אנר: ג'אז",
	"rbds_genre_Musica" : "ג'אנר: מוסיקה ספרדית",
	"rbds_genre_News" : "ג'אנר: חדשות",
	"rbds_genre_None" : "ג'אנר: אין",
	"rbds_genre_Nostalgia" : "ג'אנר: נוסטלגיה",
	"rbds_genre_Oldies" : "ג'אנר: שירים ישנים",
	"rbds_genre_Personality" : "ג'אנר: אישיות",
	"rbds_genre_Public" : "ג'אנר: ציבורי",
	"rbds_genre_ReligousM" : "ג'אנר: מוסיקה דתית",
	"rbds_genre_ReligousT" : "ג'אנר: שיחה דתית",
	"rbds_genre_Rhythym" : "ג'אנר: ריתם אנד בלוז",
	"rbds_genre_Rock" : "ג'אנר: רוק",
	"rbds_genre_Soft" : "ג'אנר: רך",
	"rbds_genre_SoftRB" : "ג'אנר: ריתם אנד בלוז רך",
	"rbds_genre_SoftRock" : "ג'אנר: רוק רך",
	"rbds_genre_Sports" : "ג'אנר: ספורט",
	"rbds_genre_Talk" : "ג'אנר: מֶלֶל",
	"rbds_genre_Top40" : "ג'אנר: 40 נבחרים",
	"rbds_genre_Weather" : "ג'אנר: מזג אויר",
};

framework.registerAppDictLoaded("fmradio", "he_IL");