var __VrHelpPositionTable__fmradioAppDict_cs_CS = {
	"AutoMemory_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"AreaPresetJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"NowPlayingEU_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_FMSettings","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_TrafficAnnouncement","VrHelp_Scan"]
	},
	"AreaPresetJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"NowPlayingNA_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_iTunesTagging","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_HDMenu","VrHelp_Scan"]
	},
	"Settings_Help" : {
		"Left" : ["VrHelp_AlternativeFrequencyOn","VrHelp_AlternativeFrequencyOff","VrHelp_RegionLockOn","VrHelp_RegionLockOff"]
	},
	"Tune_NA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"StationListJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"StationListJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"GenreSeek_Help" : {
		"Left" : ["VrHelp_SeekUp","VrHelp_SeekDown","VrHelp_ChangeGenre"]
	},
	"NowPlayingJapan_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"Tune_nonNA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"NowPlayingOther_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"AutoMemory_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	}
};

var Localization_fmradioAppDict_cs_CS = {
	//"stringId" : "localString"
	"Affairs" : "Události",
	"Alarm" : "Alarm",
	"AlarmTest" : "Zkouška alarmu",
	"AllMemoryFull" : "Paměť je plná",
	"AllStations" : "Všechny stanice",
	"AllTagsTransferred" : "Všechny zálož. přeneseny",
	"AlternativeFrequency" : "Náhradní frekvence",
	"AreaPresetTab" : "Area Preset",
	"AutoMemoryList" : "Seznam automatické paměti",
	"CannotTransferTags" : "Nelze přenést záložky",
	"ChangeGenre" : "Změnit žánr",
	"ChannelListJP" : "Channel List",
	"ChannelListTab" : "Channel List",
	"Childrens" : "Dětský",
	"Classics" : "Klasika",
	"Close" : "Zavřít",
	"ConnectIPod" : "Připojit iPod k záložkám",
	"Country" : "Venkovský",
	"Culture" : "Kultura",
	"Documentary" : "Dokumentární",
	"Drama" : "Drama",
	"Education" : "Vzdělávání",
	"ErrorConnection" : "Chyba přen.zálož.do iPodu",
	"FMRadio" : "Rádio FM",
	"FMSettings" : "Nastavení FM",
	"Finance" : "Ekonomika",
	"Folk" : "Folk",
	"GenreAffairs" : "Žánr: Události",
	"GenreAlarm" : "Žánr: Alarm",
	"GenreAlarmTest" : "Žánr: Test alarmu",
	"GenreAllStations" : "Žánr: Všechny stanice",
	"GenreChildrens" : "Žánr: Dětský",
	"GenreClassics" : "Žánr: Klasika",
	"GenreCountry" : "Žánr: Venkovský",
	"GenreCulture" : "Žánr: Kultura",
	"GenreDocumentary" : "Žánr: Dokument",
	"GenreDrama" : "Žánr: Drama",
	"GenreEducation" : "Žánr: Vzdělávání",
	"GenreFinance" : "Žánr: Ekonomika",
	"GenreFolk" : "Žánr: Folk",
	"GenreInfo" : "Žánr: Informace",
	"GenreJazz" : "Žánr: Jazz",
	"GenreLeisure" : "Žánr: Zábavný",
	"GenreLight" : "Žánr: Lehký",
	"GenreList" : "Seznam žánrů",
	"GenreMor" : "Žánr: Snadné poslouchání",
	"GenreName" : "Žánr : {genreName}",
	"GenreNational" : "Žánr: Národní",
	"GenreNews" : "Žánr: Zprávy",
	"GenreOldies" : "Žánr: Oldies",
	"GenreOther" : "Žánr: Další",
	"GenrePhoneIn" : "Žánr: PhoneIn",
	"GenrePop" : "Žánr: Pop",
	"GenreReligion" : "Žánr: Náboženský",
	"GenreRock" : "Žánr: Rock",
	"GenreScience" : "Žánr: Věda",
	"GenreSeek" : "Vyhledávání žánru",
	"GenreSocial" : "Žánr: Společenský",
	"GenreSport" : "Žánr: Sport",
	"GenreTravel" : "Žánr: Cestovatelský",
	"GenreVaried" : "Žánr: Smíšený",
	"GenreWeather" : "Žánr: Počasí",
	"HDRadio" : "Rádio HD",
	"HDStations" : "Stanice HD",
	"Info" : "Informace",
	"IpodError" : "Chyba iPodu",
	"IpodFull" : "iPod zaplněn",
	"Jazz" : "Jazz",
	"Leisure" : "Zábavný",
	"Light" : "Lehký",
	"ListUpdate" : "List Update",
	"MemoryFull" : "Paměť zaplněna",
	"Mor" : "Snadné poslouchání",
	"National" : "Národní",
	"News" : "Zprávy",
	"Noresultsfound" : "Nebyl nalezen žádný výsledek",
	"Oldies" : "Oldies",
	"Other" : "Další",
	"PartialTransfer" : "Částečný přenos",
	"PhoneIn" : "Telefonní kontakt",
	"Pop" : "Pop",
	"RegionLock" : "Regionální zámek",
	"Religion" : "Náboženský",
	"Remaining" : "Zůstává {numberOfTags}",
	"Remove" : "Odebrat",
	"Rock" : "Rock",
	"Science" : "Věda",
	"SignalLost" : "Ztráta signálu",
	"Social" : "Společenský",
	"Sport" : "Sport",
	"StationList" : "Seznam stanic",
	"TAOff" : "TA vyp.",
	"TagAlreadySaved" : "Záložka je již uložena.",
	"TagCaptured" : "Zaškrtnutí zaznamenáno",
	"TagMemoryFull" : "Paměť záložek je plná.",
	"TagNotYetProcessed" : "Zálož. zatím nezpracována",
	"TagSaved" : "Záložka uložena",
	"TagSavedtoIpod" : "Záložka uložena do iPodu",
	"TagSavedtoSystem" : "Zálož. uložena do systému",
	"TagTransferredtoiPod" : "Zálož. přenesena do iPodu",
	"TagsCannotBeSaved" : "Záložky nelze uložit",
	"Tooltip_IcnUmpFMSettings" : "Nastavení FM",
	"TrafficAlert" : "Dopravní oznámení (TA)",
	"TrafficAlertOff" : "Dopravní oznámení (TA) vypn.",
	"TrafficAlertOn" : "Dopravní oznámení (TA) zapn.",
	"Travel" : "Cestovatelský",
	"UnplugAndReconnect" : "Odpojit a znovu zapojit",
	"UpdateStationList" : "Aktualizovat seznam stanic",
	"UpdatingStationList" : "Aktualizovat seznam stanic",
	"Varied" : "Smíšený",
	"VrHelp_AlternativeFrequencyOff" : "Alternative Frequency Off",
	"VrHelp_AlternativeFrequencyOn" : "Alternative Frequency On",
	"VrHelp_AutoMemory" : "Auto Memory",
	"VrHelp_ChangeGenre" : "Change Genre",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_FMSettings" : "FM Settings",
	"VrHelp_Favorites" : "Favorites",
	"VrHelp_Frequency" : "(frequency)",
	"VrHelp_HDMenu" : "HD Radio Channels",
	"VrHelp_RegionLockOff" : "Region Lock Off",
	"VrHelp_RegionLockOn" : "Region Lock On",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SeekDown" : "Seek Down",
	"VrHelp_SeekNext" : "Seek Next",
	"VrHelp_SeekPrevious" : "Seek Previous",
	"VrHelp_SeekUp" : "Seek Up",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement (TA)",
	"VrHelp_Tune" : "Tune",
	"VrHelp_TuneDown" : "Tune Down",
	"VrHelp_TuneUp" : "Tune Up",
	"VrHelp_UpdateList" : "Update List",
	"VrHelp_iTunesTagging" : "iTunes Tagging",
	"Weather" : "Počasí",
	"favorites_Tooltip" : "Oblíbené",
	"hdChannels_Tooltip" : "HD Kanály",
	"rbds_Adult" : "Dospělí Hits",
	"rbds_Class" : "Klasický Rocková",
	"rbds_Classical" : "Klasický",
	"rbds_College" : "Kolej",
	"rbds_Country" : "Venkovský",
	"rbds_Emergency" : "Upozornění! Upozornění!",
	"rbds_EmergencyTest" : "Nouzové Testy",
	"rbds_Foreign" : "Cizí jazyk",
	"rbds_Hablar" : "Mluvit španělsky!",
	"rbds_HipHop" : "Hip Hop",
	"rbds_Info" : "Informace",
	"rbds_Jazz" : "Jazz",
	"rbds_Musica" : "Španělská Hudba",
	"rbds_News" : "Zprávy",
	"rbds_None" : "--",
	"rbds_Nostalgia" : "Nostalgie",
	"rbds_Oldies" : "Oldies",
	"rbds_Personality" : "Osobnost",
	"rbds_Public" : "Veřejnost",
	"rbds_ReligousM" : "Náboženská Hudba",
	"rbds_ReligousT" : "Náboženské Diskuse",
	"rbds_Rhythym" : "Rytmus a Blues",
	"rbds_Rock" : "Rock",
	"rbds_Soft" : "Měkké",
	"rbds_SoftRB" : "Měkké R&B",
	"rbds_SoftRock" : "Měkké Rocková",
	"rbds_Sports" : "Sports",
	"rbds_Talk" : "Rozhovory",
	"rbds_Top40" : "Top 40",
	"rbds_Weather" : "Počasí",
	"rbds_genre_Adult" : "Žánr: Dospělí Hits",
	"rbds_genre_Class" : "Žánr: Klasický Rocková",
	"rbds_genre_Classical" : "Žánr: Klasický",
	"rbds_genre_College" : "Žánr: Kolej",
	"rbds_genre_Country" : "Žánr: Venkovský",
	"rbds_genre_Emergency" : "Žánr: Upozornění! Upozornění!",
	"rbds_genre_EmergencyTest" : "Žánr: Nouzové Testy",
	"rbds_genre_Foreign" : "Žánr: Cizí jazyk",
	"rbds_genre_Hablar" : "Žánr: Mluvit španělsky!",
	"rbds_genre_HipHop" : "Žánr: Hip Hop",
	"rbds_genre_Info" : "Žánr: Informace",
	"rbds_genre_Jazz" : "Žánr: Jazz",
	"rbds_genre_Musica" : "Žánr: Španělská Hudba",
	"rbds_genre_News" : "Žánr: Zprávy",
	"rbds_genre_None" : "Žánr: --",
	"rbds_genre_Nostalgia" : "Žánr: Nostalgie",
	"rbds_genre_Oldies" : "Žánr: Oldies",
	"rbds_genre_Personality" : "Žánr: Osobnost",
	"rbds_genre_Public" : "Žánr: Veřejnost",
	"rbds_genre_ReligousM" : "Žánr: Náboženská Hudba",
	"rbds_genre_ReligousT" : "Žánr: Náboženské Diskuse",
	"rbds_genre_Rhythym" : "Žánr: Rytmus a Blues",
	"rbds_genre_Rock" : "Žánr: Rock",
	"rbds_genre_Soft" : "Žánr: Měkké",
	"rbds_genre_SoftRB" : "Žánr: Měkké R&B",
	"rbds_genre_SoftRock" : "Žánr: Měkké Rocková",
	"rbds_genre_Sports" : "Žánr: Sports",
	"rbds_genre_Talk" : "Žánr: Rozhovory",
	"rbds_genre_Top40" : "Žánr: Top 40",
	"rbds_genre_Weather" : "Žánr: Počasí",
};

framework.registerAppDictLoaded("fmradio", "cs_CS");