var __VrHelpPositionTable__fmradioAppDict_hu_HU = {
	"AutoMemory_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"AreaPresetJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"NowPlayingEU_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_FMSettings","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_TrafficAnnouncement","VrHelp_Scan"]
	},
	"AreaPresetJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"NowPlayingNA_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_iTunesTagging","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_HDMenu","VrHelp_Scan"]
	},
	"Settings_Help" : {
		"Left" : ["VrHelp_AlternativeFrequencyOn","VrHelp_AlternativeFrequencyOff","VrHelp_RegionLockOn","VrHelp_RegionLockOff"]
	},
	"Tune_NA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"StationListJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"StationListJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"GenreSeek_Help" : {
		"Left" : ["VrHelp_SeekUp","VrHelp_SeekDown","VrHelp_ChangeGenre"]
	},
	"NowPlayingJapan_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"Tune_nonNA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"NowPlayingOther_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"AutoMemory_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	}
};

var Localization_fmradioAppDict_hu_HU = {
	//"stringId" : "localString"
	"Affairs" : "Hírháttér",
	"Alarm" : "Riasztó",
	"AlarmTest" : "Riasztóteszt",
	"AllMemoryFull" : "Minden memória betelt",
	"AllStations" : "Az összes állomás",
	"AllTagsTransferred" : "Minden címke átadva",
	"AlternativeFrequency" : "Alternatív frekvencia",
	"AreaPresetTab" : "Area Preset",
	"AutoMemoryList" : "Automemória-lista",
	"CannotTransferTags" : "Címkék nem adhatók át",
	"ChangeGenre" : "Műfaj módosítása",
	"ChannelListJP" : "Channel List",
	"ChannelListTab" : "Channel List",
	"Childrens" : "Gyerekek",
	"Classics" : "Klasszikus",
	"Close" : "Bezár",
	"ConnectIPod" : "iPod-csatl címkeátadáshoz",
	"Country" : "Country",
	"Culture" : "Kultúra",
	"Documentary" : "Dokumentum",
	"Drama" : "Dráma",
	"Education" : "Oktatás",
	"ErrorConnection" : "Hiba címk.iPodra adásakor",
	"FMRadio" : "FM rádió",
	"FMSettings" : "FM beállítások",
	"Finance" : "Gazdaság",
	"Folk" : "Népzene",
	"GenreAffairs" : "Műfaj: Hírháttér",
	"GenreAlarm" : "Műfaj: Riasztás",
	"GenreAlarmTest" : "Műfaj: Próbariadó",
	"GenreAllStations" : "Műfaj: Az összes állomás",
	"GenreChildrens" : "Műfaj: Gyerekek",
	"GenreClassics" : "Műfaj: Klasszikus",
	"GenreCountry" : "Műfaj: Country",
	"GenreCulture" : "Műfaj: Kultúra",
	"GenreDocumentary" : "Műfaj: Ismeretterjesztő",
	"GenreDrama" : "Műfaj: Dráma",
	"GenreEducation" : "Műfaj: Oktatás",
	"GenreFinance" : "Műfaj: Gazdaság",
	"GenreFolk" : "Műfaj: Népzene",
	"GenreInfo" : "Műfaj: Tájékoztatás",
	"GenreJazz" : "Műfaj: Jazz",
	"GenreLeisure" : "Műfaj: Szabadidő",
	"GenreLight" : "Műfaj: Könnyűzene",
	"GenreList" : "Műfajlista",
	"GenreMor" : "Műfaj: Easy Listening",
	"GenreName" : "Műfaj: {genreName}",
	"GenreNational" : "Műfaj: Országos",
	"GenreNews" : "Műfaj: Hírek",
	"GenreOldies" : "Műfaj: Örökzöldek",
	"GenreOther" : "Műfaj: Egyéb",
	"GenrePhoneIn" : "Műfaj: Betelefonálás",
	"GenrePop" : "Műfaj: Pop",
	"GenreReligion" : "Műfaj: Vallás",
	"GenreRock" : "Műfaj: Rock",
	"GenreScience" : "Műfaj: Tudomány",
	"GenreSeek" : "Műfajkeresés",
	"GenreSocial" : "Műfaj: Közösségi hírek",
	"GenreSport" : "Műfaj: Sport",
	"GenreTravel" : "Műfaj: Utazás",
	"GenreVaried" : "Műfaj: Vegyes",
	"GenreWeather" : "Műfaj: Időjárás",
	"HDRadio" : "HD rádió",
	"HDStations" : "HD rádióadók",
	"Info" : "Tájékoztatás",
	"IpodError" : "iPod-hiba",
	"IpodFull" : "iPod megtelt",
	"Jazz" : "Jazz",
	"Leisure" : "Szabadidő",
	"Light" : "Könnyűzene",
	"ListUpdate" : "List Update",
	"MemoryFull" : "Betelt a memória",
	"Mor" : "Easy Listening",
	"National" : "Országos",
	"News" : "Hírek",
	"Noresultsfound" : "Nincs találat",
	"Oldies" : "Örökzöldek",
	"Other" : "Egyéb",
	"PartialTransfer" : "Részleges átvitel",
	"PhoneIn" : "Betelefonálás",
	"Pop" : "Pop",
	"RegionLock" : "Régiózár",
	"Religion" : "Vallás",
	"Remaining" : "{numberOfTags} fennmar.",
	"Remove" : "Eltávolítás",
	"Rock" : "Rock",
	"Science" : "Tudomány",
	"SignalLost" : "Megszakadt a jel",
	"Social" : "Közösségi",
	"Sport" : "Sport",
	"StationList" : "Rádióadások listája",
	"TAOff" : "Forg fi kikap.",
	"TagAlreadySaved" : "Címke már mentve",
	"TagCaptured" : "Címke rögzítve",
	"TagMemoryFull" : "Címkememória betelt",
	"TagNotYetProcessed" : "Még feldolgozatlan címke",
	"TagSaved" : "Címke mentve",
	"TagSavedtoIpod" : "Címke iPod-ra mentve",
	"TagSavedtoSystem" : "Címke rendszerre mentve",
	"TagTransferredtoiPod" : "Címke iPod-ra átadva",
	"TagsCannotBeSaved" : "Nem menthető címkék",
	"Tooltip_IcnUmpFMSettings" : "FM beállítások",
	"TrafficAlert" : "Útinform (TA)",
	"TrafficAlertOff" : "Útinform (TA) ki",
	"TrafficAlertOn" : "Útinform (TA) be",
	"Travel" : "Utazás",
	"UnplugAndReconnect" : "Kihúzás és újracsatl.",
	"UpdateStationList" : "Rádióadók listájának frissítése",
	"UpdatingStationList" : "Állomáslista frissítése",
	"Varied" : "Vegyes",
	"VrHelp_AlternativeFrequencyOff" : "Alternative Frequency Off",
	"VrHelp_AlternativeFrequencyOn" : "Alternative Frequency On",
	"VrHelp_AutoMemory" : "Auto Memory",
	"VrHelp_ChangeGenre" : "Change Genre",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_FMSettings" : "FM Settings",
	"VrHelp_Favorites" : "Favorites",
	"VrHelp_Frequency" : "(frequency)",
	"VrHelp_HDMenu" : "HD Radio Channels",
	"VrHelp_RegionLockOff" : "Region Lock Off",
	"VrHelp_RegionLockOn" : "Region Lock On",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SeekDown" : "Seek Down",
	"VrHelp_SeekNext" : "Seek Next",
	"VrHelp_SeekPrevious" : "Seek Previous",
	"VrHelp_SeekUp" : "Seek Up",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement (TA)",
	"VrHelp_Tune" : "Tune",
	"VrHelp_TuneDown" : "Tune Down",
	"VrHelp_TuneUp" : "Tune Up",
	"VrHelp_UpdateList" : "Update List",
	"VrHelp_iTunesTagging" : "iTunes Tagging",
	"Weather" : "Időjárás",
	"favorites_Tooltip" : "Kedvencek",
	"hdChannels_Tooltip" : "HD csatornák",
	"rbds_Adult" : "Felnőtt slágerek",
	"rbds_Class" : "Klasszikus rock",
	"rbds_Classical" : "Klasszikus",
	"rbds_College" : "Főiskola",
	"rbds_Country" : "Country",
	"rbds_Emergency" : "Figyelmeztetés! Figyelmeztetés!",
	"rbds_EmergencyTest" : "Vészhelyzetpróba",
	"rbds_Foreign" : "Idegen nyelv",
	"rbds_Hablar" : "Spanyol nyelvű",
	"rbds_HipHop" : "Hip Hop",
	"rbds_Info" : "Tájékoztatás",
	"rbds_Jazz" : "Jazz",
	"rbds_Musica" : "Spanyol zene",
	"rbds_News" : "Hírek",
	"rbds_None" : "--",
	"rbds_Nostalgia" : "Nosztalgia",
	"rbds_Oldies" : "Örökzöldek",
	"rbds_Personality" : "Személyiség",
	"rbds_Public" : "Nyilvános",
	"rbds_ReligousM" : "Vallási zene",
	"rbds_ReligousT" : "Vallási beszélgetős",
	"rbds_Rhythym" : "R'n'B",
	"rbds_Rock" : "Rock",
	"rbds_Soft" : "Lágy",
	"rbds_SoftRB" : "Lágy R'n'B",
	"rbds_SoftRock" : "Lágy rock",
	"rbds_Sports" : "Sport",
	"rbds_Talk" : "Beszélgetős",
	"rbds_Top40" : "Legjobb 40",
	"rbds_Weather" : "Időjárás",
	"rbds_genre_Adult" : "Műfaj: Felnőtt slágerek",
	"rbds_genre_Class" : "Műfaj: Klasszikus rock",
	"rbds_genre_Classical" : "Műfaj: Klasszikus",
	"rbds_genre_College" : "Műfaj: Főiskola",
	"rbds_genre_Country" : "Műfaj: Country",
	"rbds_genre_Emergency" : "Műfaj: Figyelmeztetés!",
	"rbds_genre_EmergencyTest" : "Műfaj: Vészhelyzetpróba",
	"rbds_genre_Foreign" : "Műfaj: Idegen nyelv",
	"rbds_genre_Hablar" : "Műfaj: Spanyol nyelvű",
	"rbds_genre_HipHop" : "Műfaj: Hip Hop",
	"rbds_genre_Info" : "Műfaj: Tájékoztatás",
	"rbds_genre_Jazz" : "Műfaj: Jazz",
	"rbds_genre_Musica" : "Műfaj: Spanyol zene",
	"rbds_genre_News" : "Műfaj: Hírek",
	"rbds_genre_None" : "Műfaj: --",
	"rbds_genre_Nostalgia" : "Műfaj: Nosztalgia",
	"rbds_genre_Oldies" : "Műfaj: Örökzöldek",
	"rbds_genre_Personality" : "Műfaj: Személyiség",
	"rbds_genre_Public" : "Műfaj: Nyilvános",
	"rbds_genre_ReligousM" : "Műfaj: Vallási zene",
	"rbds_genre_ReligousT" : "Műfaj: Vallási beszélgetős",
	"rbds_genre_Rhythym" : "Műfaj: R'n'B",
	"rbds_genre_Rock" : "Műfaj: Rock",
	"rbds_genre_Soft" : "Műfaj: Lágy",
	"rbds_genre_SoftRB" : "Műfaj: Lágy R'n'B",
	"rbds_genre_SoftRock" : "Műfaj: Lágy rock",
	"rbds_genre_Sports" : "Műfaj: Sport",
	"rbds_genre_Talk" : "Műfaj: Beszélgetős",
	"rbds_genre_Top40" : "Műfaj: Legjobb 40",
	"rbds_genre_Weather" : "Műfaj: Időjárás",
};

framework.registerAppDictLoaded("fmradio", "hu_HU");