var __VrHelpPositionTable__fmradioAppDict_ru_RU = {
	"AutoMemory_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"AreaPresetJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"NowPlayingEU_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_FMSettings","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_TrafficAnnouncement","VrHelp_Scan"]
	},
	"AreaPresetJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"NowPlayingNA_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_iTunesTagging","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_HDMenu","VrHelp_Scan"]
	},
	"Settings_Help" : {
		"Left" : ["VrHelp_AlternativeFrequencyOn","VrHelp_AlternativeFrequencyOff","VrHelp_RegionLockOn","VrHelp_RegionLockOff"]
	},
	"Tune_NA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"StationListJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"StationListJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"GenreSeek_Help" : {
		"Left" : ["VrHelp_SeekUp","VrHelp_SeekDown","VrHelp_ChangeGenre"]
	},
	"NowPlayingJapan_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"Tune_nonNA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"NowPlayingOther_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"AutoMemory_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	}
};

var Localization_fmradioAppDict_ru_RU = {
	//"stringId" : "localString"
	"Affairs" : "События",
	"Alarm" : "Аварийный сигнал",
	"AlarmTest" : "Тест аварийного сигнала",
	"AllMemoryFull" : "Вся память переполнена",
	"AllStations" : "Все станции",
	"AllTagsTransferred" : "Все теги переданы",
	"AlternativeFrequency" : "Альтернативн.частоты",
	"AreaPresetTab" : "Area Preset",
	"AutoMemoryList" : "Список авт.сохр.станций",
	"CannotTransferTags" : "Невозм.передать теги",
	"ChangeGenre" : "Изменить жанр",
	"ChannelListJP" : "Channel List",
	"ChannelListTab" : "Channel List",
	"Childrens" : "Дети",
	"Classics" : "Классика",
	"Close" : "Закр.",
	"ConnectIPod" : "подкл iPod, перед тег",
	"Country" : "Кантри",
	"Culture" : "Культура",
	"Documentary" : "Документальные передачи",
	"Drama" : "Драма",
	"Education" : "Образование",
	"ErrorConnection" : "Ошиб. перед. тегов в iPod",
	"FMRadio" : "Радио FM ",
	"FMSettings" : "Настройки FM",
	"Finance" : "Финансы",
	"Folk" : "Фолк",
	"GenreAffairs" : "Жанр: отношения",
	"GenreAlarm" : "Жанр: аварийный сигнал",
	"GenreAlarmTest" : "Жанр: тест аварийного сигнала",
	"GenreAllStations" : "Жанр: все станции",
	"GenreChildrens" : "Жанр: дети",
	"GenreClassics" : "Жанр: классика",
	"GenreCountry" : "Жанр: кантри",
	"GenreCulture" : "Жанр: культура",
	"GenreDocumentary" : "Жанр: документалистика",
	"GenreDrama" : "Жанр: драма",
	"GenreEducation" : "Жанр: образование",
	"GenreFinance" : "Жанр: финансы",
	"GenreFolk" : "Жанр: фолк",
	"GenreInfo" : "Жанр: информация",
	"GenreJazz" : "Жанр: джаз",
	"GenreLeisure" : "Жанр: досуг",
	"GenreLight" : "Жанр: легкая музыка",
	"GenreList" : "Список жанров",
	"GenreMor" : "Жанр: спокойная музыка ",
	"GenreName" : "Жанр: {genreName}",
	"GenreNational" : "Жанр: национальная музыка",
	"GenreNews" : "Жанр: новости",
	"GenreOldies" : "Жанр: ретро",
	"GenreOther" : "Жанр: прочее",
	"GenrePhoneIn" : "Жанр: прямая линия",
	"GenrePop" : "Жанр: поп",
	"GenreReligion" : "Жанр: религия",
	"GenreRock" : "Жанр: рок",
	"GenreScience" : "Жанр: наука",
	"GenreSeek" : "Поиск по жанру",
	"GenreSocial" : "Жанр: социальн. вопросы",
	"GenreSport" : "Жанр: спорт",
	"GenreTravel" : "Жанр: путешествия",
	"GenreVaried" : "Жанр: разное",
	"GenreWeather" : "Жанр: погода",
	"HDRadio" : "Радио HD",
	"HDStations" : "Станции HD",
	"Info" : "Информация",
	"IpodError" : "Ошибка iPod",
	"IpodFull" : "Память iPod переполнена",
	"Jazz" : "Джаз",
	"Leisure" : "Досуг",
	"Light" : "Легкая музыка",
	"ListUpdate" : "List Update",
	"MemoryFull" : "Память переполнена",
	"Mor" : "Спокойная музыка",
	"National" : "Национальная музыка",
	"News" : "Новости",
	"Noresultsfound" : "Результаты не найдены",
	"Oldies" : "Ретро",
	"Other" : "Прочее",
	"PartialTransfer" : "Частичная передача ",
	"PhoneIn" : "Прямая линия",
	"Pop" : "Поп",
	"RegionLock" : "Региональная блокировка",
	"Religion" : "Религия",
	"Remaining" : "Осталось {numberOfTags}",
	"Remove" : "Удалить",
	"Rock" : "Рок",
	"Science" : "Наука",
	"SignalLost" : "Сигнал потерян",
	"Social" : "Социальн. вопросы",
	"Sport" : "Спорт",
	"StationList" : "Список станций",
	"TAOff" : "TA Выкл.",
	"TagAlreadySaved" : "Тег уже сохранен",
	"TagCaptured" : "Тег получен",
	"TagMemoryFull" : "Память тегов переполн.",
	"TagNotYetProcessed" : "Тег еще не обработан",
	"TagSaved" : "Тег сохранен",
	"TagSavedtoIpod" : "Тег сохранен на iPod",
	"TagSavedtoSystem" : "Тег сохранен в системе",
	"TagTransferredtoiPod" : "Тег передан на iPod",
	"TagsCannotBeSaved" : "Невозможно сохр. теги",
	"Tooltip_IcnUmpFMSettings" : "Настройки FM",
	"TrafficAlert" : "Контроль трафика",
	"TrafficAlertOff" : "Выключить контроль трафика",
	"TrafficAlertOn" : "Включить контроль трафика",
	"Travel" : "Путешествия",
	"UnplugAndReconnect" : "Откл и подкл снова",
	"UpdateStationList" : "Обновить список станций",
	"UpdatingStationList" : "Обновление списка станций",
	"Varied" : "Разное",
	"VrHelp_AlternativeFrequencyOff" : "Альтернативная частота Выкл.",
	"VrHelp_AlternativeFrequencyOn" : "Альтернативная частота Вкл.",
	"VrHelp_AutoMemory" : "Авто-память",
	"VrHelp_ChangeGenre" : "Изменить жанр",
	"VrHelp_Entertainment" : "Развлечения",
	"VrHelp_FMSettings" : "Настройки FM",
	"VrHelp_Favorites" : "Избранное",
	"VrHelp_Frequency" : "(частота)",
	"VrHelp_HDMenu" : "HD Radio каналы",
	"VrHelp_RegionLockOff" : "Блокировка региона Выкл.",
	"VrHelp_RegionLockOn" : "Блокировка региона Вкл.",
	"VrHelp_Scan" : "Сканировать",
	"VrHelp_SeekDown" : "Поиск вниз",
	"VrHelp_SeekNext" : "Искать cледующий",
	"VrHelp_SeekPrevious" : "Искать пpeдыдущий",
	"VrHelp_SeekUp" : "Поиск вверх",
	"VrHelp_SoundSettings" : "Настройки звука",
	"VrHelp_StationList" : "Список станций",
	"VrHelp_TrafficAnnouncement" : "Контроль трафика",
	"VrHelp_Tune" : "Настройка частот",
	"VrHelp_TuneDown" : "Частота ниже",
	"VrHelp_TuneUp" : "Частота выше",
	"VrHelp_UpdateList" : "Обновить список",
	"VrHelp_iTunesTagging" : "Тегирование iTunes",
	"Weather" : "Погода",
	"favorites_Tooltip" : "Избранное",
	"hdChannels_Tooltip" : "HD каналы",
	"rbds_Adult" : "Хиты для взрослых",
	"rbds_Class" : "Kлассический рок",
	"rbds_Classical" : "Классика",
	"rbds_College" : "Колледж",
	"rbds_Country" : "Кантри",
	"rbds_Emergency" : "Тревога! Тревога!",
	"rbds_EmergencyTest" : "Аварийные испытания",
	"rbds_Foreign" : "Иностранный язык",
	"rbds_Hablar" : "Испанский язык",
	"rbds_HipHop" : "Хип-хоп",
	"rbds_Info" : "Информация",
	"rbds_Jazz" : "Джаз",
	"rbds_Musica" : "Испанская музыка",
	"rbds_News" : "Новости",
	"rbds_None" : "--",
	"rbds_Nostalgia" : "Hостальгия",
	"rbds_Oldies" : "Ретро",
	"rbds_Personality" : "Ведущий",
	"rbds_Public" : "Общественность",
	"rbds_ReligousM" : "Религиозная музыка",
	"rbds_ReligousT" : "Религиозные беседы",
	"rbds_Rhythym" : "Ритм-энд-блюз",
	"rbds_Rock" : "Рок",
	"rbds_Soft" : "Легкий",
	"rbds_SoftRB" : "Легкий R&B",
	"rbds_SoftRock" : "Легкий рок",
	"rbds_Sports" : "Спорт",
	"rbds_Talk" : "Разговорный",
	"rbds_Top40" : "Топ 40",
	"rbds_Weather" : "Погода",
	"rbds_genre_Adult" : "Жанр: хиты для взрослых",
	"rbds_genre_Class" : "Жанр: классический рок",
	"rbds_genre_Classical" : "Жанр: классика",
	"rbds_genre_College" : "Жанр: колледж",
	"rbds_genre_Country" : "Жанр: кантри",
	"rbds_genre_Emergency" : "Жанр: Тревога! Тревога!",
	"rbds_genre_EmergencyTest" : "Жанр: аварийные испытания",
	"rbds_genre_Foreign" : "Жанр: иностранный язык",
	"rbds_genre_Hablar" : "Жанр: испанский язык",
	"rbds_genre_HipHop" : "Жанр: хип-хоп",
	"rbds_genre_Info" : "Жанр: информация",
	"rbds_genre_Jazz" : "Жанр: джаз",
	"rbds_genre_Musica" : "Жанр: испанская музыка",
	"rbds_genre_News" : "Жанр: новости",
	"rbds_genre_None" : "Жанр: --",
	"rbds_genre_Nostalgia" : "Жанр: ностальгия",
	"rbds_genre_Oldies" : "Жанр: ретро",
	"rbds_genre_Personality" : "Жанр: ведущий",
	"rbds_genre_Public" : "Жанр: общественное радио",
	"rbds_genre_ReligousM" : "Жанр: религиозная музыка",
	"rbds_genre_ReligousT" : "Жанр: религиозные беседы",
	"rbds_genre_Rhythym" : "Жанр: ритм-энд-блюз",
	"rbds_genre_Rock" : "Жанр: рок",
	"rbds_genre_Soft" : "Жанр: легкий",
	"rbds_genre_SoftRB" : "Жанр: легкий R&B",
	"rbds_genre_SoftRock" : "Жанр: легкий рок",
	"rbds_genre_Sports" : "Жанр: спорт",
	"rbds_genre_Talk" : "Жанр: разговорный",
	"rbds_genre_Top40" : "Жанр: топ 40",
	"rbds_genre_Weather" : "Жанр: погода",
};

framework.registerAppDictLoaded("fmradio", "ru_RU");