var __VrHelpPositionTable__fmradioAppDict_th_TH = {
	"AutoMemory_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"AreaPresetJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"NowPlayingEU_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_FMSettings","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_TrafficAnnouncement","VrHelp_Scan"]
	},
	"AreaPresetJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"NowPlayingNA_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_iTunesTagging","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_HDMenu","VrHelp_Scan"]
	},
	"Settings_Help" : {
		"Left" : ["VrHelp_AlternativeFrequencyOn","VrHelp_AlternativeFrequencyOff","VrHelp_RegionLockOn","VrHelp_RegionLockOff"]
	},
	"Tune_NA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"StationListJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"StationListJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"GenreSeek_Help" : {
		"Left" : ["VrHelp_SeekUp","VrHelp_SeekDown","VrHelp_ChangeGenre"]
	},
	"NowPlayingJapan_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"Tune_nonNA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"NowPlayingOther_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"AutoMemory_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	}
};

var Localization_fmradioAppDict_th_TH = {
	//"stringId" : "localString"
	"Affairs" : "เหตุการณ์",
	"Alarm" : "เสียงเตือน",
	"AlarmTest" : "การทดสอบเสียงเตือน",
	"AllMemoryFull" : "หน่วยความจำทั้งหมดเต็ม",
	"AllStations" : "สถานีทั้งหมด",
	"AllTagsTransferred" : "ถ่ายโอนแท็กทั้งหมดแล้ว",
	"AlternativeFrequency" : "ระบบค้นหาคลื่นความถี่อัตโนมัติ",
	"AreaPresetTab" : "Area Preset",
	"AutoMemoryList" : "รายการหน่วยความจำอัตโนมัติ",
	"CannotTransferTags" : "ไม่สามารถถ่ายโอนแท็ก",
	"ChangeGenre" : "เปลี่ยนประเภท",
	"ChannelListJP" : "Channel List",
	"ChannelListTab" : "Channel List",
	"Childrens" : "เด็ก",
	"Classics" : "คลาสสิก",
	"Close" : "ปิด",
	"ConnectIPod" : "ต่อ iPod เพื่อโอนแท็ก",
	"Country" : "ลูกทุ่ง",
	"Culture" : "วัฒนธรรม",
	"Documentary" : "สารคดี",
	"Drama" : "การแสดง",
	"Education" : "การศึกษา",
	"ErrorConnection" : "ผิดพลาดขณะโอนแท็กไปiPod",
	"FMRadio" : "วิทยุ FM",
	"FMSettings" : "การตั้งค่า FM",
	"Finance" : "การเงิน",
	"Folk" : "โฟล์ค",
	"GenreAffairs" : "ประเภท: เหตุการณ์",
	"GenreAlarm" : "ประเภท: เสียงเตือน",
	"GenreAlarmTest" : "ประเภท: การทดสอบเสียงเตือน",
	"GenreAllStations" : "ประเภท: สถานีทั้งหมด",
	"GenreChildrens" : "ประเภท: เด็ก",
	"GenreClassics" : "ประเภท: คลาสสิก",
	"GenreCountry" : "ประเภท: คันทรี่",
	"GenreCulture" : "ประเภท: วัฒนธรรม",
	"GenreDocumentary" : "ประเภท: สารคดี",
	"GenreDrama" : "ประเภท: การแสดง",
	"GenreEducation" : "ประเภท: การศึกษา",
	"GenreFinance" : "ประเภท: การเงิน",
	"GenreFolk" : "ประเภท: โฟล์ค",
	"GenreInfo" : "ประเภท: ข้อมูล",
	"GenreJazz" : "ประเภท: แจ๊ส",
	"GenreLeisure" : "ประเภท: กิจกรรมยามว่าง",
	"GenreLight" : "ประเภท: คลายอารมณ์",
	"GenreList" : "ประเภทต่างๆ",
	"GenreMor" : "ประเภท: ฟังสบายๆ",
	"GenreName" : "ประเภท: {genreName}",
	"GenreNational" : "ประเภท: ลูกทุ่ง",
	"GenreNews" : "ประเภท: ข่าวสาร",
	"GenreOldies" : "ประเภท: ย้อนยุค",
	"GenreOther" : "ประเภท: อื่นๆ",
	"GenrePhoneIn" : "ประเภท: โฟนอิน",
	"GenrePop" : "ประเภท: ป๊อป",
	"GenreReligion" : "ประเภท: ศาสนา",
	"GenreRock" : "ประเภท: ร็อค",
	"GenreScience" : "ประเภท: วิทยาศาสตร์",
	"GenreSeek" : "การค้นหาประเภท",
	"GenreSocial" : "ประเภท: สังคม",
	"GenreSport" : "ประเภท: กีฬา",
	"GenreTravel" : "ประเภท: การท่องเที่ยว",
	"GenreVaried" : "ประเภท: หลากหลาย",
	"GenreWeather" : "ประเภท: สภาพอากาศ",
	"HDRadio" : "วิทยุ HD",
	"HDStations" : "สถานี HD",
	"Info" : "ข้อมูล ",
	"IpodError" : "ข้อผิดพลาดของ iPod",
	"IpodFull" : "iPod เต็ม",
	"Jazz" : "แจ๊ส",
	"Leisure" : "กิจกรรมยามว่าง",
	"Light" : "คลายอารมณ์",
	"ListUpdate" : "List Update",
	"MemoryFull" : "หน่วยความจำเต็ม",
	"Mor" : "ฟังสบายๆ",
	"National" : "ประจำชาติ",
	"News" : "ข่าวสาร",
	"Noresultsfound" : "ไม่พบผลลัพธ์",
	"Oldies" : "ย้อนยุค",
	"Other" : "อื่นๆ",
	"PartialTransfer" : "โอนย้ายข้อมูลบางส่วน",
	"PhoneIn" : "โฟนอิน",
	"Pop" : "ป๊อป",
	"RegionLock" : "การล็อกโซน",
	"Religion" : "ศาสนา",
	"Remaining" : "เหลืออยู่ {numberOfTags}",
	"Remove" : "ลบ",
	"Rock" : "ร็อค",
	"Science" : "วิทยาศาสตร์",
	"SignalLost" : "สัญญาณขาดหาย",
	"Social" : "สังคม",
	"Sport" : "กีฬา",
	"StationList" : "รายการสถานี",
	"TAOff" : "ปิด TA",
	"TagAlreadySaved" : "บันทึกแท็กไว้แล้ว",
	"TagCaptured" : "แท็กที่จับได้",
	"TagMemoryFull" : "หน่วยความจำแท็กเต็ม",
	"TagNotYetProcessed" : "แท็กยังไม่ได้ประมวลผล",
	"TagSaved" : "บันทึกแท็กแล้ว",
	"TagSavedtoIpod" : "บันทึกแท็กลงใน iPod แล้ว",
	"TagSavedtoSystem" : "บันทึกแท็กลงในระบบแล้ว",
	"TagTransferredtoiPod" : "ถ่ายโอนแท็กไปยัง iPod แล้ว",
	"TagsCannotBeSaved" : "ไม่สามารถบันทึกแท็ก",
	"Tooltip_IcnUmpFMSettings" : "การตั้งค่า FM",
	"TrafficAlert" : "ประกาศการจราจร (TA)",
	"TrafficAlertOff" : "ปิดการประกาศการจราจร (TA)",
	"TrafficAlertOn" : "เปิดการประกาศการจราจร (TA)",
	"Travel" : "การท่องเที่ยว",
	"UnplugAndReconnect" : "ถอดปลั๊กและเชื่อมต่อใหม่",
	"UpdateStationList" : "อัปเดตรายการสถานี",
	"UpdatingStationList" : "กำลังอัปเดตรายการสถานี",
	"Varied" : "หลากหลาย",
	"VrHelp_AlternativeFrequencyOff" : "Alternative Frequency Off",
	"VrHelp_AlternativeFrequencyOn" : "Alternative Frequency On",
	"VrHelp_AutoMemory" : "Auto Memory",
	"VrHelp_ChangeGenre" : "Change Genre",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_FMSettings" : "FM Settings",
	"VrHelp_Favorites" : "Favorites",
	"VrHelp_Frequency" : "(frequency)",
	"VrHelp_HDMenu" : "HD Radio Channels",
	"VrHelp_RegionLockOff" : "Region Lock Off",
	"VrHelp_RegionLockOn" : "Region Lock On",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SeekDown" : "Seek Down",
	"VrHelp_SeekNext" : "Seek Next",
	"VrHelp_SeekPrevious" : "Seek Previous",
	"VrHelp_SeekUp" : "Seek Up",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement (TA)",
	"VrHelp_Tune" : "Tune",
	"VrHelp_TuneDown" : "Tune Down",
	"VrHelp_TuneUp" : "Tune Up",
	"VrHelp_UpdateList" : "Update List",
	"VrHelp_iTunesTagging" : "iTunes Tagging",
	"Weather" : "สภาพอากาศ",
	"favorites_Tooltip" : "รายการโปรด",
	"hdChannels_Tooltip" : "ช่อง HD",
	"rbds_Adult" : "เพลงฮิตสำหรับผู้ใหญ่",
	"rbds_Class" : "คลาสสิคร็อค",
	"rbds_Classical" : "คลาสสิก",
	"rbds_College" : "วิทยาลัย",
	"rbds_Country" : "ลูกทุ่ง",
	"rbds_Emergency" : "แจ้งเตือน! แจ้งเตือน!",
	"rbds_EmergencyTest" : "ทดสอบฉุกเฉิน",
	"rbds_Foreign" : "ภาษาต่างประเทศ",
	"rbds_Hablar" : "การพูดภาษาสเปน",
	"rbds_HipHop" : "ฮิปฮอป",
	"rbds_Info" : "ข้อมูล",
	"rbds_Jazz" : "แจ๊ส",
	"rbds_Musica" : "เพลงภาษาสเปน",
	"rbds_News" : "ข่าวสาร",
	"rbds_None" : "ไม่มี",
	"rbds_Nostalgia" : "เพลงหวานวันวาน",
	"rbds_Oldies" : "ย้อนยุค",
	"rbds_Personality" : "บุคลิกภาพ",
	"rbds_Public" : "สาธารณะ",
	"rbds_ReligousM" : "เพลงศาสนา",
	"rbds_ReligousT" : "พูดคุยเรื่องศาสนา",
	"rbds_Rhythym" : "ริทึมแอนด์บลูส์",
	"rbds_Rock" : "ร็อค",
	"rbds_Soft" : "ซอฟต์",
	"rbds_SoftRB" : "ซอฟต์อาร์แอนด์บี",
	"rbds_SoftRock" : "ซอฟต์ร็อค",
	"rbds_Sports" : "กีฬา",
	"rbds_Talk" : "คุย",
	"rbds_Top40" : "เพลงฮิต 40 อันดับ",
	"rbds_Weather" : "สภาพอากาศ",
	"rbds_genre_Adult" : "ประเภท:เพลงฮิตสำหรับผู้ใหญ่",
	"rbds_genre_Class" : "ประเภท:คลาสสิคร็อค",
	"rbds_genre_Classical" : "ประเภท:คลาสสิก",
	"rbds_genre_College" : "ประเภท:วิทยาลัย",
	"rbds_genre_Country" : "ประเภท:ลูกทุ่ง",
	"rbds_genre_Emergency" : "แจ้งเตือน! แจ้งเตือน!",
	"rbds_genre_EmergencyTest" : "ประเภท:ทดสอบฉุกเฉิน",
	"rbds_genre_Foreign" : "ประเภท:ภาษาต่างประเทศ",
	"rbds_genre_Hablar" : "ประเภท:การพูดภาษาสเปน",
	"rbds_genre_HipHop" : "ประเภท:ฮิปฮอป",
	"rbds_genre_Info" : "ประเภท:ข้อมูล",
	"rbds_genre_Jazz" : "ประเภท:แจ๊ส",
	"rbds_genre_Musica" : "ประเภท:เพลงภาษาสเปน",
	"rbds_genre_News" : "ประเภท:ข่าวสาร",
	"rbds_genre_None" : "ประเภท: ไม่มี",
	"rbds_genre_Nostalgia" : "ประเภท:เพลงหวานวันวาน",
	"rbds_genre_Oldies" : "ประเภท:ย้อนยุค",
	"rbds_genre_Personality" : "ประเภท:บุคลิกภาพ",
	"rbds_genre_Public" : "ประเภท:สาธารณะ",
	"rbds_genre_ReligousM" : "ประเภท:เพลงศาสนา",
	"rbds_genre_ReligousT" : "ประเภท:พูดคุยทางศาสนา",
	"rbds_genre_Rhythym" : "ประเภท:ริทึมแอนด์บลูส์",
	"rbds_genre_Rock" : "ประเภท:ร็อก",
	"rbds_genre_Soft" : "ประเภท:ซอฟต์",
	"rbds_genre_SoftRB" : "ประเภท:ซอฟต์อาร์แอนด์บี",
	"rbds_genre_SoftRock" : "ประเภท:ซอฟต์ร็อค",
	"rbds_genre_Sports" : "ประเภท:กีฬา",
	"rbds_genre_Talk" : "ประเภท:พูดคุย",
	"rbds_genre_Top40" : "ประเภท:เพลงฮิต 40 อันดับ",
	"rbds_genre_Weather" : "ประเภท:สภาพอากาศ",
};

framework.registerAppDictLoaded("fmradio", "th_TH");