var __VrHelpPositionTable__fmradioAppDict_el_GR = {
	"AutoMemory_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"AreaPresetJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"NowPlayingEU_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_FMSettings","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_TrafficAnnouncement","VrHelp_Scan"]
	},
	"AreaPresetJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"NowPlayingNA_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_iTunesTagging","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_HDMenu","VrHelp_Scan"]
	},
	"Settings_Help" : {
		"Left" : ["VrHelp_AlternativeFrequencyOn","VrHelp_AlternativeFrequencyOff","VrHelp_RegionLockOn","VrHelp_RegionLockOff"]
	},
	"Tune_NA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"StationListJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"StationListJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"GenreSeek_Help" : {
		"Left" : ["VrHelp_SeekUp","VrHelp_SeekDown","VrHelp_ChangeGenre"]
	},
	"NowPlayingJapan_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"Tune_nonNA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"NowPlayingOther_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"AutoMemory_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	}
};

var Localization_fmradioAppDict_el_GR = {
	//"stringId" : "localString"
	"Affairs" : "Υποθέσεις",
	"Alarm" : "Συναγερμός",
	"AlarmTest" : "Δοκιμή συναγερμού",
	"AllMemoryFull" : "Μνήμη πλήρης",
	"AllStations" : "Όλοι οι σταθμοί",
	"AllTagsTransferred" : "Όλες οι ετικ. μεταφέρθ.",
	"AlternativeFrequency" : "Εναλλακτική συχνότητα",
	"AreaPresetTab" : "Area Preset",
	"AutoMemoryList" : "Λίστα αυτόματης μνήμης",
	"CannotTransferTags" : "Αδύνατη μεταφ. ετικετών",
	"ChangeGenre" : "Αλλαγή είδους",
	"ChannelListJP" : "Channel List",
	"ChannelListTab" : "Channel List",
	"Childrens" : "Παιδιών",
	"Classics" : "Κλασικά",
	"Close" : "Κλείσ.",
	"ConnectIPod" : "Σύνδ. iPod για μεταφ. ετικ.",
	"Country" : "Χώρα",
	"Culture" : "Πολιτισμός",
	"Documentary" : "Ντοκιμαντέρ",
	"Drama" : "Δράμα",
	"Education" : "Εκπαίδευση",
	"ErrorConnection" : "Σφάλμα μετ. ετικ. σε iPod",
	"FMRadio" : "Ραδιόφωνο FM",
	"FMSettings" : "Ρυθμίσεις FM",
	"Finance" : "Οικονομικά",
	"Folk" : "Φολκ",
	"GenreAffairs" : "Είδος: Υποθέσεις",
	"GenreAlarm" : "Είδος: Συναγερμός",
	"GenreAlarmTest" : "Είδος: Δοκιμή συναγερμού",
	"GenreAllStations" : "Είδος: Όλοι οι σταθμοί",
	"GenreChildrens" : "Είδος: Παιδιών",
	"GenreClassics" : "Είδος: Κλασικά",
	"GenreCountry" : "Είδος: Χώρα",
	"GenreCulture" : "Είδος: Πολιτισμός",
	"GenreDocumentary" : "Είδος: Ντοκιμαντέρ",
	"GenreDrama" : "Είδος: Δράμα",
	"GenreEducation" : "Είδος: Εκπαίδευση",
	"GenreFinance" : "Είδος: Οικονομικά",
	"GenreFolk" : "Είδος: Φολκ",
	"GenreInfo" : "Είδος: Πληροφορίες",
	"GenreJazz" : "Είδος: Τζαζ",
	"GenreLeisure" : "Είδος: Ψυχαγωγία",
	"GenreLight" : "Είδος: Ελαφρά",
	"GenreList" : "Λίστα ειδών",
	"GenreMor" : "Είδος: Χαλαρά",
	"GenreName" : "Είδος: {genreName}",
	"GenreNational" : "Είδος: Εθνική",
	"GenreNews" : "Είδος: Ειδήσεις",
	"GenreOldies" : "Είδος: Επιτυχίες του παρελθόντος",
	"GenreOther" : "Είδος: Άλλο",
	"GenrePhoneIn" : "Είδος: Δια τηλεφώνου",
	"GenrePop" : "Είδος: Ποπ",
	"GenreReligion" : "Είδος: Θρησκευτικό",
	"GenreRock" : "Είδος: Ροκ",
	"GenreScience" : "Είδος: Επιστήμη",
	"GenreSeek" : "Αναζήτηση ειδών",
	"GenreSocial" : "Είδος: Κοινωνικό",
	"GenreSport" : "Είδος: Αθλητικά",
	"GenreTravel" : "Είδος: Ταξίδια",
	"GenreVaried" : "Είδος: Διάφορα",
	"GenreWeather" : "Είδος: Καιρός",
	"HDRadio" : "Ραδιόφωνο HD",
	"HDStations" : "Σταθμοί HD",
	"Info" : "Πληροφορίες",
	"IpodError" : "Σφάλμα iPod",
	"IpodFull" : "Πλήρες iPod",
	"Jazz" : "Τζαζ",
	"Leisure" : "Ψυχαγωγία",
	"Light" : "Ελαφρά",
	"ListUpdate" : "List Update",
	"MemoryFull" : "Πλήρης μνήμη",
	"Mor" : "Χαλαρά",
	"National" : "Εθνική",
	"News" : "Ειδήσεις",
	"Noresultsfound" : "Δεν βρέθηκε κανένα αποτέλεσμα",
	"Oldies" : "Επιτυχίες του παρελθόντος",
	"Other" : "Άλλο",
	"PartialTransfer" : "Μερική Μεταφορά",
	"PhoneIn" : "Δια τηλεφώνου",
	"Pop" : "Ποπ",
	"RegionLock" : "Κλείδωμα περιοχής",
	"Religion" : "Θρησκευτικό",
	"Remaining" : "Ακόμη {numberOfTags}",
	"Remove" : "Αφαίρεση",
	"Rock" : "Ροκ",
	"Science" : "Επιστήμη",
	"SignalLost" : "Απώλεια σήματος",
	"Social" : "Κοινωνικό",
	"Sport" : "Αθλητικά",
	"StationList" : "Λίστα σταθμών",
	"TAOff" : "TA ανενεργό",
	"TagAlreadySaved" : "Ετικέτα ήδη αποθ.",
	"TagCaptured" : "Ετικέτα ελήφθη",
	"TagMemoryFull" : "Πλήρης μνήμη ετικέτας",
	"TagNotYetProcessed" : "Δεν έγινε επεξ. ετικέτας",
	"TagSaved" : "Ετικέτα αποθηκευμένη",
	"TagSavedtoIpod" : "Ετικέτα αποθηκ. σε iPod",
	"TagSavedtoSystem" : "Ετικ. αποθηκ. στο σύσ.",
	"TagTransferredtoiPod" : "Ετικέτα μεταφ. σε iPod",
	"TagsCannotBeSaved" : "Αδύνατη αποθ. ετικετών",
	"Tooltip_IcnUmpFMSettings" : "Ρυθμίσεις FM",
	"TrafficAlert" : "Ειδοποίηση κίνησης (TA) ",
	"TrafficAlertOff" : "Ειδοποίηση κίνησης (TA) - ανενεργή",
	"TrafficAlertOn" : "Ειδοποίηση κίνησης (TA) - ενεργή",
	"Travel" : "Ταξίδια",
	"UnplugAndReconnect" : "Αποσύνδ. και επανασ.",
	"UpdateStationList" : "Ενημέρωση λίστας σταθμών",
	"UpdatingStationList" : "Ενημέρωση λίστας σταθμών",
	"Varied" : "Διάφορα",
	"VrHelp_AlternativeFrequencyOff" : "Alternative Frequency Off",
	"VrHelp_AlternativeFrequencyOn" : "Alternative Frequency On",
	"VrHelp_AutoMemory" : "Auto Memory",
	"VrHelp_ChangeGenre" : "Change Genre",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_FMSettings" : "FM Settings",
	"VrHelp_Favorites" : "Favorites",
	"VrHelp_Frequency" : "(frequency)",
	"VrHelp_HDMenu" : "HD Radio Channels",
	"VrHelp_RegionLockOff" : "Region Lock Off",
	"VrHelp_RegionLockOn" : "Region Lock On",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SeekDown" : "Seek Down",
	"VrHelp_SeekNext" : "Seek Next",
	"VrHelp_SeekPrevious" : "Seek Previous",
	"VrHelp_SeekUp" : "Seek Up",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement (TA)",
	"VrHelp_Tune" : "Tune",
	"VrHelp_TuneDown" : "Tune Down",
	"VrHelp_TuneUp" : "Tune Up",
	"VrHelp_UpdateList" : "Update List",
	"VrHelp_iTunesTagging" : "iTunes Tagging",
	"Weather" : "Καιρός",
	"favorites_Tooltip" : "Αγαπημένα",
	"hdChannels_Tooltip" : "Κανάλια HD",
	"rbds_Adult" : "Διάφορες επιτυχίες",
	"rbds_Class" : "Κλασικό ροκ",
	"rbds_Classical" : "Κλασικά",
	"rbds_College" : "Κολέγιο",
	"rbds_Country" : "Χώρα",
	"rbds_Emergency" : "Προσοχή! Προσοχή!",
	"rbds_EmergencyTest" : "Επείγουσα δοκιμή",
	"rbds_Foreign" : "Ξενόγλωσσα",
	"rbds_Hablar" : "Μιλάτε ισπανικά",
	"rbds_HipHop" : "Hip Hop",
	"rbds_Info" : "Πληροφορίες",
	"rbds_Jazz" : "Τζαζ",
	"rbds_Musica" : "Ισπανική μουσική",
	"rbds_News" : "Ειδήσεις",
	"rbds_None" : "--",
	"rbds_Nostalgia" : "Νοσταλγία",
	"rbds_Oldies" : "Επιτυχίες του παρελθόντος",
	"rbds_Personality" : "Προσωπικότητα",
	"rbds_Public" : "Δημόσιο",
	"rbds_ReligousM" : "Θρησκευτική μουσική",
	"rbds_ReligousT" : "Θρησκευτικές συζητήσεις",
	"rbds_Rhythym" : "Ρυθμός και μπλουζ",
	"rbds_Rock" : "Ροκ",
	"rbds_Soft" : "Ελαφρά",
	"rbds_SoftRB" : "Ελαφρύ R&B",
	"rbds_SoftRock" : "Ελαφρύ ροκ",
	"rbds_Sports" : "Αθλητικά",
	"rbds_Talk" : "Συζητήσεις",
	"rbds_Top40" : "Κορυφαία 40",
	"rbds_Weather" : "Καιρός",
	"rbds_genre_Adult" : "Είδος: Διάφορες επιτυχίες",
	"rbds_genre_Class" : "Είδος: Κλασικό ροκ",
	"rbds_genre_Classical" : "Είδος: Κλασικά",
	"rbds_genre_College" : "Είδος: Κολέγιο",
	"rbds_genre_Country" : "Είδος: Χώρα",
	"rbds_genre_Emergency" : "Είδος: Προσοχή! Προσοχή!",
	"rbds_genre_EmergencyTest" : "Είδος: Επείγουσα δοκιμή",
	"rbds_genre_Foreign" : "Είδος: Ξενόγλωσσα",
	"rbds_genre_Hablar" : "Είδος: Μιλάτε ισπανικά",
	"rbds_genre_HipHop" : "Είδος: Hip Hop",
	"rbds_genre_Info" : "Είδος: Πληροφορίες",
	"rbds_genre_Jazz" : "Είδος: Τζαζ",
	"rbds_genre_Musica" : "Είδος: Ισπανική μουσική",
	"rbds_genre_News" : "Είδος: Ειδήσεις",
	"rbds_genre_None" : "Είδος: --",
	"rbds_genre_Nostalgia" : "Είδος: Νοσταλγία",
	"rbds_genre_Oldies" : "Είδος: Επιτυχίες του παρελθόντος",
	"rbds_genre_Personality" : "Είδος: Προσωπικότητα",
	"rbds_genre_Public" : "Είδος: Δημόσιο",
	"rbds_genre_ReligousM" : "Είδος: Θρησκευτική μουσική",
	"rbds_genre_ReligousT" : "Είδος: Θρησκευτικές συζητήσεις",
	"rbds_genre_Rhythym" : "Είδος: Ρυθμός και μπλουζ",
	"rbds_genre_Rock" : "Είδος: Ροκ",
	"rbds_genre_Soft" : "Είδος: Ελαφρά",
	"rbds_genre_SoftRB" : "Είδος: Ελαφρύ R&B",
	"rbds_genre_SoftRock" : "Είδος: Ελαφρύ ροκ",
	"rbds_genre_Sports" : "Είδος: Αθλητικά",
	"rbds_genre_Talk" : "Είδος: Συζητήσεις",
	"rbds_genre_Top40" : "Είδος: Κορυφαία 40",
	"rbds_genre_Weather" : "Είδος: Καιρός",
};

framework.registerAppDictLoaded("fmradio", "el_GR");