var __VrHelpPositionTable__fmradioAppDict_sr_RS = {
	"AutoMemory_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"AreaPresetJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"NowPlayingEU_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_FMSettings","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_TrafficAnnouncement","VrHelp_Scan"]
	},
	"AreaPresetJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"NowPlayingNA_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_iTunesTagging","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_HDMenu","VrHelp_Scan"]
	},
	"Settings_Help" : {
		"Left" : ["VrHelp_AlternativeFrequencyOn","VrHelp_AlternativeFrequencyOff","VrHelp_RegionLockOn","VrHelp_RegionLockOff"]
	},
	"Tune_NA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"StationListJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"StationListJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"GenreSeek_Help" : {
		"Left" : ["VrHelp_SeekUp","VrHelp_SeekDown","VrHelp_ChangeGenre"]
	},
	"NowPlayingJapan_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"Tune_nonNA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"NowPlayingOther_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"AutoMemory_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	}
};

var Localization_fmradioAppDict_sr_RS = {
	//"stringId" : "localString"
	"Affairs" : "Događaji",
	"Alarm" : "Alarm",
	"AlarmTest" : "Test alarma",
	"AllMemoryFull" : "Sva memorija je puna",
	"AllStations" : "Sve stanice",
	"AllTagsTransferred" : "Sve oznake su prebačene",
	"AlternativeFrequency" : "Alternativna frekvencija",
	"AreaPresetTab" : "Area Preset",
	"AutoMemoryList" : "Lista automatske memorije",
	"CannotTransferTags" : "Ozn.se ne mogu pren.",
	"ChangeGenre" : "Promeni žanr",
	"ChannelListJP" : "Channel List",
	"ChannelListTab" : "Channel List",
	"Childrens" : "Za decu",
	"Classics" : "Klasici",
	"Close" : "Zatv.",
	"ConnectIPod" : "Poveži iPod za prenos ozn",
	"Country" : "Kantri",
	"Culture" : "Kultura",
	"Documentary" : "Dokumentarci",
	"Drama" : "Drama",
	"Education" : "Obrazovanje",
	"ErrorConnection" : "Greška pren.ozn.na iPod",
	"FMRadio" : "FM radio",
	"FMSettings" : "FM postavke",
	"Finance" : "Finansije",
	"Folk" : "Folk",
	"GenreAffairs" : "Žanr: Događaji",
	"GenreAlarm" : "Žanr: Alarm",
	"GenreAlarmTest" : "Žanr: Test alarma",
	"GenreAllStations" : "Žanr: Sve stanice",
	"GenreChildrens" : "Žanr: Dečije",
	"GenreClassics" : "Žanr: Klasici",
	"GenreCountry" : "Žanr: Kantri",
	"GenreCulture" : "Žanr: Kultura",
	"GenreDocumentary" : "Žanr: Dokumentarci",
	"GenreDrama" : "Žanr: Drama",
	"GenreEducation" : "Žanr: Obrazovanje",
	"GenreFinance" : "Žanr: Finansije",
	"GenreFolk" : "Žanr: Folk",
	"GenreInfo" : "Žanr: Informacije",
	"GenreJazz" : "Žanr: Džez",
	"GenreLeisure" : "Žanr: Slobodno vreme",
	"GenreLight" : "Žanr: Za opuštanje",
	"GenreList" : "Lista žanrova",
	"GenreMor" : "Žanr: Lagana muzika",
	"GenreName" : "Žanr: {genreName}",
	"GenreNational" : "Žanr: Nacionalni hitovi",
	"GenreNews" : "Žanr: Vesti",
	"GenreOldies" : "Žanr: Stari hitovi",
	"GenreOther" : "Žanr: Drugo",
	"GenrePhoneIn" : "Žanr: Na telefonu",
	"GenrePop" : "Žanr: Pop",
	"GenreReligion" : "Žanr: Religija",
	"GenreRock" : "Žanr: Rok",
	"GenreScience" : "Žanr: Nauka",
	"GenreSeek" : "Traži žanr",
	"GenreSocial" : "Žanr: Društvo",
	"GenreSport" : "Žanr: Sport",
	"GenreTravel" : "Žanr: Putovanja",
	"GenreVaried" : "Žanr: Razno",
	"GenreWeather" : "Žanr: Vremenska prognoza",
	"HDRadio" : "HD radio",
	"HDStations" : "HD stanice",
	"Info" : "Informacije",
	"IpodError" : "Greška u iPod-u",
	"IpodFull" : "iPod je pun",
	"Jazz" : "Džez",
	"Leisure" : "Slobodno vreme",
	"Light" : "Za opuštanje",
	"ListUpdate" : "List Update",
	"MemoryFull" : "Puna memorija",
	"Mor" : "Lagana muzika",
	"National" : "Nacionalni hitovi",
	"News" : "Vesti",
	"Noresultsfound" : "Nema pronađenih rezultata",
	"Oldies" : "Stari hitovi",
	"Other" : "Drugo",
	"PartialTransfer" : "Delimični prenos",
	"PhoneIn" : "Telefon",
	"Pop" : "Pop",
	"RegionLock" : "Regionalno zaključavanje",
	"Religion" : "Religija",
	"Remaining" : "{numberOfTags} preostalo",
	"Remove" : "Ukloni",
	"Rock" : "Rok",
	"Science" : "Nauka",
	"SignalLost" : "Signal je izgubljen",
	"Social" : "Društvo",
	"Sport" : "Sport",
	"StationList" : "Lista stanica",
	"TAOff" : "TA isključeno",
	"TagAlreadySaved" : "Oznaka je već sačuvana",
	"TagCaptured" : "Oznaka sačuvana",
	"TagMemoryFull" : "Memorija oznaka je puna",
	"TagNotYetProcessed" : "Oznaka još nije obrađena",
	"TagSaved" : "Oznaka je sačuvana",
	"TagSavedtoIpod" : "Ozn.sačuvana na iPod-u",
	"TagSavedtoSystem" : "Ozn.sačuvana u sistemu",
	"TagTransferredtoiPod" : "Ozn.prebačena na iPod",
	"TagsCannotBeSaved" : "Nemoguće sačuvati ozn.",
	"Tooltip_IcnUmpFMSettings" : "FM postavke",
	"TrafficAlert" : "Obaveštenja o stanju saobraćaja",
	"TrafficAlertOff" : "Obaveštenja o stanju saobraćaja isključena",
	"TrafficAlertOn" : "Obaveštenja o stanju saobraćaja uključena",
	"Travel" : "Putovanja",
	"UnplugAndReconnect" : "Izvucite i ponovo povežite",
	"UpdateStationList" : "Ažuriraj listu stanica",
	"UpdatingStationList" : "Ažuriranje liste stanica",
	"Varied" : "Razno",
	"VrHelp_AlternativeFrequencyOff" : "Alternative Frequency Off",
	"VrHelp_AlternativeFrequencyOn" : "Alternative Frequency On",
	"VrHelp_AutoMemory" : "Auto Memory",
	"VrHelp_ChangeGenre" : "Change Genre",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_FMSettings" : "FM Settings",
	"VrHelp_Favorites" : "Favorites",
	"VrHelp_Frequency" : "(frequency)",
	"VrHelp_HDMenu" : "HD Radio Channels",
	"VrHelp_RegionLockOff" : "Region Lock Off",
	"VrHelp_RegionLockOn" : "Region Lock On",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SeekDown" : "Seek Down",
	"VrHelp_SeekNext" : "Seek Next",
	"VrHelp_SeekPrevious" : "Seek Previous",
	"VrHelp_SeekUp" : "Seek Up",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement (TA)",
	"VrHelp_Tune" : "Tune",
	"VrHelp_TuneDown" : "Tune Down",
	"VrHelp_TuneUp" : "Tune Up",
	"VrHelp_UpdateList" : "Update List",
	"VrHelp_iTunesTagging" : "iTunes Tagging",
	"Weather" : "Vremenska prognoza",
	"favorites_Tooltip" : "Omiljeni",
	"hdChannels_Tooltip" : "HD stanice",
	"rbds_Adult" : "Hitovi za odrasle",
	"rbds_Class" : "Klasični rok",
	"rbds_Classical" : "Klasična muzika",
	"rbds_College" : "Koledž",
	"rbds_Country" : "Kantri",
	"rbds_Emergency" : "Upozorenje! Upozorenje!",
	"rbds_EmergencyTest" : "Test bezbednosti",
	"rbds_Foreign" : "Strani jezik",
	"rbds_Hablar" : "Razgovor na španskom",
	"rbds_HipHop" : "Hip Hop",
	"rbds_Info" : "Informacije",
	"rbds_Jazz" : "Džez",
	"rbds_Musica" : "Španska muzika",
	"rbds_News" : "Vesti",
	"rbds_None" : "--",
	"rbds_Nostalgia" : "Nostalgija",
	"rbds_Oldies" : "Stari hitovi",
	"rbds_Personality" : "Javne ličnosti",
	"rbds_Public" : "Javno",
	"rbds_ReligousM" : "Crkvena muzika",
	"rbds_ReligousT" : "Religiozni razgovor",
	"rbds_Rhythym" : "Ritam i bluz",
	"rbds_Rock" : "Rok",
	"rbds_Soft" : "Lagana muzika",
	"rbds_SoftRB" : "Lagani R&B",
	"rbds_SoftRock" : "Lagani rok",
	"rbds_Sports" : "Sport",
	"rbds_Talk" : "Razgovor",
	"rbds_Top40" : "Top 40",
	"rbds_Weather" : "Vremenska prognoza",
	"rbds_genre_Adult" : "Žanr: Hitovi za odrasle",
	"rbds_genre_Class" : "Žanr: Klasični rok",
	"rbds_genre_Classical" : "Žanr: Klasična muzika",
	"rbds_genre_College" : "Žanr: Koledž",
	"rbds_genre_Country" : "Žanr: Kantri",
	"rbds_genre_Emergency" : "Žanr: Upozorenje! Upozorenje!",
	"rbds_genre_EmergencyTest" : "Žanr: Test bezbednosti",
	"rbds_genre_Foreign" : "Žanr: Strani jezik",
	"rbds_genre_Hablar" : "Žanr: Razgovor na španskom",
	"rbds_genre_HipHop" : "Žanr: Hip Hop",
	"rbds_genre_Info" : "Žanr: Informacije",
	"rbds_genre_Jazz" : "Žanr: Džez",
	"rbds_genre_Musica" : "Žanr: Španska muzika",
	"rbds_genre_News" : "Žanr: Vesti",
	"rbds_genre_None" : "Žanr: --",
	"rbds_genre_Nostalgia" : "Žanr: Nostalgija",
	"rbds_genre_Oldies" : "Žanr: Stari hitovi",
	"rbds_genre_Personality" : "Žanr: Javne ličnosti",
	"rbds_genre_Public" : "Žanr: Javno mjenje",
	"rbds_genre_ReligousM" : "Žanr: Crkvena muzika",
	"rbds_genre_ReligousT" : "Žanr: Religiozni razgovor",
	"rbds_genre_Rhythym" : "Žanr: Ritam i bluz",
	"rbds_genre_Rock" : "Žanr: Rok",
	"rbds_genre_Soft" : "Žanr: Lagana muzika",
	"rbds_genre_SoftRB" : "Žanr: Lagani R&B",
	"rbds_genre_SoftRock" : "Žanr: Lagani rok",
	"rbds_genre_Sports" : "Žanr: Sportovi",
	"rbds_genre_Talk" : "Žanr: Razgovor",
	"rbds_genre_Top40" : "Žanr: Top 40",
	"rbds_genre_Weather" : "Žanr: Vremenska prognoza",
};

framework.registerAppDictLoaded("fmradio", "sr_RS");