var __VrHelpPositionTable__fmradioAppDict_en_UK = {
	"AutoMemory_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"AreaPresetJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"NowPlayingEU_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_FMSettings","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_TrafficAnnouncement","VrHelp_Scan"]
	},
	"AreaPresetJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"NowPlayingNA_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_iTunesTagging","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_HDMenu","VrHelp_Scan"]
	},
	"Settings_Help" : {
		"Left" : ["VrHelp_AlternativeFrequencyOn","VrHelp_AlternativeFrequencyOff","VrHelp_RegionLockOn","VrHelp_RegionLockOff"]
	},
	"Tune_NA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"StationListJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"StationListJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"GenreSeek_Help" : {
		"Left" : ["VrHelp_SeekUp","VrHelp_SeekDown","VrHelp_ChangeGenre"]
	},
	"NowPlayingJapan_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"Tune_nonNA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"NowPlayingOther_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"AutoMemory_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	}
};

var Localization_fmradioAppDict_en_UK = {
	//"stringId" : "localString"
	"Affairs" : "Affairs",
	"Alarm" : "Alarm",
	"AlarmTest" : "Alarm Test",
	"AllMemoryFull" : "All Memory Full",
	"AllStations" : "All Stations",
	"AllTagsTransferred" : "All Tags Transferred",
	"AlternativeFrequency" : "Alternative Frequency",
	"AreaPresetTab" : "Area Preset",
	"AutoMemoryList" : "Auto Memory List",
	"CannotTransferTags" : "Cannot Transfer Tags",
	"ChangeGenre" : "Change Genre",
	"ChannelListJP" : "Channel List",
	"ChannelListTab" : "Channel List",
	"Childrens" : "Children",
	"Classics" : "Classics",
	"Close" : "Close",
	"ConnectIPod" : "Connect iPod to Transfer",
	"Country" : "Country",
	"Culture" : "Culture",
	"Documentary" : "Document",
	"Drama" : "Drama",
	"Education" : "Educate",
	"ErrorConnection" : "Error While Transferring",
	"FMRadio" : "FM Radio",
	"FMSettings" : "FM Settings",
	"Finance" : "Finance",
	"Folk" : "Folk M",
	"GenreAffairs" : "Genre: Affairs",
	"GenreAlarm" : "Genre: Alarm",
	"GenreAlarmTest" : "Genre: Alarm Test",
	"GenreAllStations" : "Genre: All Stations",
	"GenreChildrens" : "Genre: Children",
	"GenreClassics" : "Genre: Classics",
	"GenreCountry" : "Genre: Country",
	"GenreCulture" : "Genre: Culture",
	"GenreDocumentary" : "Genre: Document",
	"GenreDrama" : "Genre: Drama",
	"GenreEducation" : "Genre: Educate",
	"GenreFinance" : "Genre: Finance",
	"GenreFolk" : "Genre: Folk M",
	"GenreInfo" : "Genre: Info",
	"GenreJazz" : "Genre: Jazz",
	"GenreLeisure" : "Genre: Leisure",
	"GenreLight" : "Genre: Light M",
	"GenreList" : "Genre List",
	"GenreMor" : "Genre: Easy M",
	"GenreName" : "Genre: {genreName}",
	"GenreNational" : "Genre: Nation M",
	"GenreNews" : "Genre: News",
	"GenreOldies" : "Genre: Oldies",
	"GenreOther" : "Genre: Other M",
	"GenrePhoneIn" : "Genre: Phone In",
	"GenrePop" : "Genre: Pop M",
	"GenreReligion" : "Genre: Religion",
	"GenreRock" : "Genre: Rock M",
	"GenreScience" : "Genre: Science",
	"GenreSeek" : "Genre Seek",
	"GenreSocial" : "Genre: Social",
	"GenreSport" : "Genre: Sport",
	"GenreTravel" : "Genre: Travel",
	"GenreVaried" : "Genre: Varied",
	"GenreWeather" : "Genre: Weather",
	"HDRadio" : "HD Radio",
	"HDStations" : "HD Stations",
	"Info" : "Info",
	"IpodError" : "iPod Error",
	"IpodFull" : "iPod Full",
	"Jazz" : "Jazz",
	"Leisure" : "Leisure",
	"Light" : "Light M",
	"ListUpdate" : "List Update",
	"MemoryFull" : "Memory Full",
	"Mor" : "Easy M",
	"National" : "Nation M",
	"News" : "News",
	"Noresultsfound" : "No Results Found",
	"Oldies" : "Oldies",
	"Other" : "Other M",
	"PartialTransfer" : "Partial Transfer",
	"PhoneIn" : "Phone In",
	"Pop" : "Pop M",
	"RegionLock" : "Region Lock",
	"Religion" : "Religion",
	"Remaining" : "{numberOfTags} Remaining",
	"Remove" : "Remove",
	"Rock" : "Rock M",
	"Science" : "Science",
	"SignalLost" : "Signal Lost",
	"Social" : "Social",
	"Sport" : "Sport",
	"StationList" : "Station List",
	"TAOff" : "TA Off",
	"TagAlreadySaved" : "Tag Already Saved",
	"TagCaptured" : "Tag Captured",
	"TagMemoryFull" : "Tag Memory Full",
	"TagNotYetProcessed" : "Tag Not Yet Processed",
	"TagSaved" : "Tag Saved",
	"TagSavedtoIpod" : "Tag Saved to iPod",
	"TagSavedtoSystem" : "Tag Saved to System",
	"TagTransferredtoiPod" : "Tag Transferred to iPod",
	"TagsCannotBeSaved" : "Tags Cannot be Saved",
	"Tooltip_IcnUmpFMSettings" : "FM Settings",
	"TrafficAlert" : "Traffic Announcement  (TA)",
	"TrafficAlertOff" : "Traffic Announcement  (TA) Off",
	"TrafficAlertOn" : "Traffic Announcement  (TA) On",
	"Travel" : "Travel",
	"UnplugAndReconnect" : "Unplug and Reconnect",
	"UpdateStationList" : "Update Station List",
	"UpdatingStationList" : "Updating Station List",
	"Varied" : "Varied",
	"VrHelp_AlternativeFrequencyOff" : "Alternative Frequency Off",
	"VrHelp_AlternativeFrequencyOn" : "Alternative Frequency On",
	"VrHelp_AutoMemory" : "Auto Memory",
	"VrHelp_ChangeGenre" : "Change Genre",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_FMSettings" : "FM Settings",
	"VrHelp_Favorites" : "Favourites",
	"VrHelp_Frequency" : "(frequency)",
	"VrHelp_HDMenu" : "HD Radio Channels",
	"VrHelp_RegionLockOff" : "Region Lock Off",
	"VrHelp_RegionLockOn" : "Region Lock On",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SeekDown" : "Seek Down",
	"VrHelp_SeekNext" : "Seek Next",
	"VrHelp_SeekPrevious" : "Seek Previous",
	"VrHelp_SeekUp" : "Seek Up",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement  (TA)",
	"VrHelp_Tune" : "Tune",
	"VrHelp_TuneDown" : "Tune Down",
	"VrHelp_TuneUp" : "Tune Up",
	"VrHelp_UpdateList" : "Update List",
	"VrHelp_iTunesTagging" : "iTunes Tagging",
	"Weather" : "Weather",
	"favorites_Tooltip" : "Favourites",
	"hdChannels_Tooltip" : "HD Channels",
	"rbds_Adult" : "Adult Hits",
	"rbds_Class" : "Classic Rock",
	"rbds_Classical" : "Classical",
	"rbds_College" : "College",
	"rbds_Country" : "Country",
	"rbds_Emergency" : "Alert! Alert!",
	"rbds_EmergencyTest" : "Emergency Test",
	"rbds_Foreign" : "Foreign Language",
	"rbds_Hablar" : "Hablar Español",
	"rbds_HipHop" : "Hip Hop",
	"rbds_Info" : "Information",
	"rbds_Jazz" : "Jazz",
	"rbds_Musica" : "Música Español",
	"rbds_News" : "News",
	"rbds_None" : "None",
	"rbds_Nostalgia" : "Nostalgia",
	"rbds_Oldies" : "Oldies",
	"rbds_Personality" : "Personality",
	"rbds_Public" : "Public",
	"rbds_ReligousM" : "Religious Music",
	"rbds_ReligousT" : "Religious Talk",
	"rbds_Rhythym" : "Rhythm and Blues",
	"rbds_Rock" : "Rock",
	"rbds_Soft" : "Soft",
	"rbds_SoftRB" : "Soft R&B",
	"rbds_SoftRock" : "Soft Rock",
	"rbds_Sports" : "Sports",
	"rbds_Talk" : "Talk",
	"rbds_Top40" : "Top 40",
	"rbds_Weather" : "Weather",
	"rbds_genre_Adult" : "Genre: Adult Hits",
	"rbds_genre_Class" : "Genre: Classic Rock",
	"rbds_genre_Classical" : "Genre: Classical",
	"rbds_genre_College" : "Genre: Música Español",
	"rbds_genre_Country" : "Genre: Country",
	"rbds_genre_Emergency" : "Genre: Alert! Alert!",
	"rbds_genre_EmergencyTest" : "Genre: Emergency Test",
	"rbds_genre_Foreign" : "Genre: Foreign Language",
	"rbds_genre_Hablar" : "Genre: Hablar Español",
	"rbds_genre_HipHop" : "Genre: Hip Hop",
	"rbds_genre_Info" : "Genre: Information",
	"rbds_genre_Jazz" : "Genre: Jazz",
	"rbds_genre_Musica" : "Genre: Música Español",
	"rbds_genre_News" : "Genre: News",
	"rbds_genre_None" : "Genre: None",
	"rbds_genre_Nostalgia" : "Genre: Nostalgia",
	"rbds_genre_Oldies" : "Genre: Oldies",
	"rbds_genre_Personality" : "Genre: Personality",
	"rbds_genre_Public" : "Genre: Public",
	"rbds_genre_ReligousM" : "Genre: Religious Music",
	"rbds_genre_ReligousT" : "Genre: Religious Talk",
	"rbds_genre_Rhythym" : "Genre: Rhythm and Blues",
	"rbds_genre_Rock" : "Genre: Rock",
	"rbds_genre_Soft" : "Genre: Soft",
	"rbds_genre_SoftRB" : "Genre: Soft R&B",
	"rbds_genre_SoftRock" : "Genre: Soft Rock",
	"rbds_genre_Sports" : "Genre: Sports",
	"rbds_genre_Talk" : "Genre: Talk",
	"rbds_genre_Top40" : "Genre: Top 40",
	"rbds_genre_Weather" : "Genre: Weather",
};

framework.registerAppDictLoaded("fmradio", "en_UK");