var __VrHelpPositionTable__fmradioAppDict_sv_SE = {
	"AutoMemory_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"AreaPresetJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"NowPlayingEU_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_FMSettings","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_TrafficAnnouncement","VrHelp_Scan"]
	},
	"AreaPresetJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"NowPlayingNA_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_iTunesTagging","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_HDMenu","VrHelp_Scan"]
	},
	"Settings_Help" : {
		"Left" : ["VrHelp_AlternativeFrequencyOn","VrHelp_AlternativeFrequencyOff","VrHelp_RegionLockOn","VrHelp_RegionLockOff"]
	},
	"Tune_NA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"StationListJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"StationListJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"GenreSeek_Help" : {
		"Left" : ["VrHelp_SeekUp","VrHelp_SeekDown","VrHelp_ChangeGenre"]
	},
	"NowPlayingJapan_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"Tune_nonNA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"NowPlayingOther_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"AutoMemory_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	}
};

var Localization_fmradioAppDict_sv_SE = {
	//"stringId" : "localString"
	"Affairs" : "Affärer",
	"Alarm" : "Larm",
	"AlarmTest" : "Larmtest",
	"AllMemoryFull" : "Hela minnet fullt",
	"AllStations" : "Alla stationer",
	"AllTagsTransferred" : "Alla taggar överförda",
	"AlternativeFrequency" : "Alternativ frekvens",
	"AreaPresetTab" : "Area Preset",
	"AutoMemoryList" : "Autominneslista",
	"CannotTransferTags" : "Kan inte överföra taggar",
	"ChangeGenre" : "Ändra kategori",
	"ChannelListJP" : "Channel List",
	"ChannelListTab" : "Channel List",
	"Childrens" : "Barn",
	"Classics" : "Klassiskt",
	"Close" : "Stäng",
	"ConnectIPod" : "Anslut iPod, överför tagg",
	"Country" : "Country",
	"Culture" : "Kultur",
	"Documentary" : "Dokumentär",
	"Drama" : "Drama",
	"Education" : "Utbildning",
	"ErrorConnection" : "Fel då taggar överförs till",
	"FMRadio" : "FM radio",
	"FMSettings" : "FM-inställningar",
	"Finance" : "Ekonomi",
	"Folk" : "Folkmusik",
	"GenreAffairs" : "Kategori: Affärer",
	"GenreAlarm" : "Kategori: Larm",
	"GenreAlarmTest" : "Kategori: Larmtest",
	"GenreAllStations" : "Kategori: Alla stationer",
	"GenreChildrens" : "Kategori: Barn",
	"GenreClassics" : "Kategori: Klassiskt",
	"GenreCountry" : "Kategori: Country",
	"GenreCulture" : "Kategori: Kultur",
	"GenreDocumentary" : "Kategori: Dokumentär",
	"GenreDrama" : "Kategori: Drama",
	"GenreEducation" : "Kategori: Utbildning",
	"GenreFinance" : "Kategori: Ekonomi",
	"GenreFolk" : "Kategori: Folkmusik",
	"GenreInfo" : "Kategori: Information",
	"GenreJazz" : "Kategori: Jazz",
	"GenreLeisure" : "Kategori: Fritid",
	"GenreLight" : "Kategori: Lätt",
	"GenreList" : "Kategorilista",
	"GenreMor" : "Kategori: Lättlyssnat",
	"GenreName" : "Kategori: {genreName}",
	"GenreNational" : "Kategori: Nationellt",
	"GenreNews" : "Kategori: Nyheter",
	"GenreOldies" : "Kategori: Äldre",
	"GenreOther" : "Kategori: Annat",
	"GenrePhoneIn" : "Kategori: Telefon in",
	"GenrePop" : "Kategori: Pop",
	"GenreReligion" : "Kategori: Religion",
	"GenreRock" : "Kategori: Rock",
	"GenreScience" : "Kategori: Vetenskap",
	"GenreSeek" : "Sök i kategori",
	"GenreSocial" : "Kategori: Social",
	"GenreSport" : "Kategori: Sport",
	"GenreTravel" : "Kategori: Resa",
	"GenreVaried" : "Kategori: Varierat",
	"GenreWeather" : "Kategori: Väder",
	"HDRadio" : "HD-radio",
	"HDStations" : "HD-stationer",
	"Info" : "Information",
	"IpodError" : "Fel på iPod",
	"IpodFull" : "iPod full",
	"Jazz" : "Jazz",
	"Leisure" : "Fritid",
	"Light" : "Lätt",
	"ListUpdate" : "List Update",
	"MemoryFull" : "Minnet fullt",
	"Mor" : "Lättlyssnat",
	"National" : "Nationellt",
	"News" : "Nyheter",
	"Noresultsfound" : "Hittade inga resultat",
	"Oldies" : "Äldre",
	"Other" : "Annat",
	"PartialTransfer" : "Partiell överföring",
	"PhoneIn" : "Ring in",
	"Pop" : "Pop",
	"RegionLock" : "Regionslås",
	"Religion" : "Religion",
	"Remaining" : "{numberOfTags} kvar",
	"Remove" : "Ta bort",
	"Rock" : "Rock",
	"Science" : "Vetenskap",
	"SignalLost" : "Signalen har förlorats",
	"Social" : "Social",
	"Sport" : "Sport",
	"StationList" : "Stationslista",
	"TAOff" : "TA av",
	"TagAlreadySaved" : "Taggen redan sparad",
	"TagCaptured" : "Tagg tagen",
	"TagMemoryFull" : "Taggminnet fullt",
	"TagNotYetProcessed" : "Tagg har inte bearbetats",
	"TagSaved" : "Tagg har sparats",
	"TagSavedtoIpod" : "Tagg har sparats till iPod",
	"TagSavedtoSystem" : "Tagg sparad till system",
	"TagTransferredtoiPod" : "Tagg överförd till iPod",
	"TagsCannotBeSaved" : "Taggar kan inte sparas",
	"Tooltip_IcnUmpFMSettings" : "FM-inställningar",
	"TrafficAlert" : "Trafikvarning (TA)",
	"TrafficAlertOff" : "Trafikvarning (TA) av",
	"TrafficAlertOn" : "Trafikvarning (TA) på",
	"Travel" : "Resa",
	"UnplugAndReconnect" : "Koppla från och återanslut",
	"UpdateStationList" : "Uppdatera stationslista",
	"UpdatingStationList" : "Uppdaterar stationslista",
	"Varied" : "Blandat",
	"VrHelp_AlternativeFrequencyOff" : "Alternativ frekvens av",
	"VrHelp_AlternativeFrequencyOn" : "Alternativ frekvens på",
	"VrHelp_AutoMemory" : "Automatiskt minne",
	"VrHelp_ChangeGenre" : "Ändra kategori",
	"VrHelp_Entertainment" : "Underhållning",
	"VrHelp_FMSettings" : "FM-inställningar",
	"VrHelp_Favorites" : "Favoriter",
	"VrHelp_Frequency" : "(frekvens)",
	"VrHelp_HDMenu" : "HD Radio-kanal",
	"VrHelp_RegionLockOff" : "Regionlås av",
	"VrHelp_RegionLockOn" : "Regionlås på",
	"VrHelp_Scan" : "Sök",
	"VrHelp_SeekDown" : "Sök nedåt",
	"VrHelp_SeekNext" : "Sök nästa",
	"VrHelp_SeekPrevious" : "Sök föregående",
	"VrHelp_SeekUp" : "Sök uppåt",
	"VrHelp_SoundSettings" : "Ljudinställningar",
	"VrHelp_StationList" : "Stationslista",
	"VrHelp_TrafficAnnouncement" : "Trafikvarning (TA)",
	"VrHelp_Tune" : "Ställ in",
	"VrHelp_TuneDown" : "Ställ in nedåt",
	"VrHelp_TuneUp" : "Ställ in uppåt",
	"VrHelp_UpdateList" : "Uppdatera lista",
	"VrHelp_iTunesTagging" : "iTunes-taggning",
	"Weather" : "Väder",
	"favorites_Tooltip" : "Favoriter",
	"hdChannels_Tooltip" : "HD stanice",
	"rbds_Adult" : "Vuxenhits",
	"rbds_Class" : "Klassisk rock",
	"rbds_Classical" : "Klassiskt",
	"rbds_College" : "College",
	"rbds_Country" : "Country",
	"rbds_Emergency" : "SOS! SOS!",
	"rbds_EmergencyTest" : "Nödanropstest",
	"rbds_Foreign" : "Främmande språk",
	"rbds_Hablar" : "Spanska",
	"rbds_HipHop" : "Hip hop",
	"rbds_Info" : "Information",
	"rbds_Jazz" : "Jazz",
	"rbds_Musica" : "Spansk musik",
	"rbds_News" : "Nyheter",
	"rbds_None" : "--",
	"rbds_Nostalgia" : "Nostalgi",
	"rbds_Oldies" : "Äldre",
	"rbds_Personality" : "Personlighet",
	"rbds_Public" : "Allmänt",
	"rbds_ReligousM" : "Religiös musik",
	"rbds_ReligousT" : "Religiöst prat",
	"rbds_Rhythym" : "Rhytm'n Blues",
	"rbds_Rock" : "Rock",
	"rbds_Soft" : "Soft",
	"rbds_SoftRB" : "Soft R&B",
	"rbds_SoftRock" : "Mjukrock",
	"rbds_Sports" : "Sport",
	"rbds_Talk" : "Prata",
	"rbds_Top40" : "Topp 40",
	"rbds_Weather" : "Väder",
	"rbds_genre_Adult" : "Kategori: Vuxenhits",
	"rbds_genre_Class" : "Kategori: Klassisk rock",
	"rbds_genre_Classical" : "Kategori: Klassiskt",
	"rbds_genre_College" : "Kategori: College",
	"rbds_genre_Country" : "Kategori: Country",
	"rbds_genre_Emergency" : "Kategori: SOS! SOS!",
	"rbds_genre_EmergencyTest" : "Kategori: Nödanropstest",
	"rbds_genre_Foreign" : "Kategori: Främmande språk",
	"rbds_genre_Hablar" : "Kategori: Spanska",
	"rbds_genre_HipHop" : "Kategori: Hip hop",
	"rbds_genre_Info" : "Kategori: Info",
	"rbds_genre_Jazz" : "Kategori: Jazz",
	"rbds_genre_Musica" : "Kategori: Spansk musik",
	"rbds_genre_News" : "Kategori: Nyheter",
	"rbds_genre_None" : "Kategori: --",
	"rbds_genre_Nostalgia" : "Kategori: Nostalgi",
	"rbds_genre_Oldies" : "Kategori: Oldies",
	"rbds_genre_Personality" : "Kategori: Personlighet",
	"rbds_genre_Public" : "Kategori: Allmänt",
	"rbds_genre_ReligousM" : "Kategori: Religiös musik",
	"rbds_genre_ReligousT" : "Kategori: Religiöst prat",
	"rbds_genre_Rhythym" : "Kategori: Rhytm'n Blues",
	"rbds_genre_Rock" : "Kategori: Rock",
	"rbds_genre_Soft" : "Kategori: Soft",
	"rbds_genre_SoftRB" : "Kategori: Soft R&B",
	"rbds_genre_SoftRock" : "Kategori: Mjukrock",
	"rbds_genre_Sports" : "Kategori: Sports",
	"rbds_genre_Talk" : "Kategori: Prata",
	"rbds_genre_Top40" : "Kategori: Topp 40",
	"rbds_genre_Weather" : "Kategori: Väder",
};

framework.registerAppDictLoaded("fmradio", "sv_SE");