var __VrHelpPositionTable__fmradioAppDict_it_IT = {
	"AutoMemory_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"AreaPresetJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"NowPlayingEU_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_FMSettings","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_TrafficAnnouncement","VrHelp_Scan"]
	},
	"AreaPresetJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"NowPlayingNA_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_iTunesTagging","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_HDMenu","VrHelp_Scan"]
	},
	"Settings_Help" : {
		"Left" : ["VrHelp_AlternativeFrequencyOn","VrHelp_AlternativeFrequencyOff","VrHelp_RegionLockOn","VrHelp_RegionLockOff"]
	},
	"Tune_NA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"StationListJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"StationListJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"GenreSeek_Help" : {
		"Left" : ["VrHelp_SeekUp","VrHelp_SeekDown","VrHelp_ChangeGenre"]
	},
	"NowPlayingJapan_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"Tune_nonNA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"NowPlayingOther_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"AutoMemory_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	}
};

var Localization_fmradioAppDict_it_IT = {
	//"stringId" : "localString"
	"Affairs" : "Affari",
	"Alarm" : "Allarme",
	"AlarmTest" : "Allarme Test",
	"AllMemoryFull" : "Memoria piena.",
	"AllStations" : "Tutte le stazioni",
	"AllTagsTransferred" : "Tutte le tag trasferite.",
	"AlternativeFrequency" : "Frequenza alternativa",
	"AreaPresetTab" : "Area Preset",
	"AutoMemoryList" : "Elenco stazioni Auto Memory",
	"CannotTransferTags" : "Impossibile trasferire tag.",
	"ChangeGenre" : "Cambia genere",
	"ChannelListJP" : "Channel List",
	"ChannelListTab" : "Channel List",
	"Childrens" : "Bambini",
	"Classics" : "Classica",
	"Close" : "Chiudi",
	"ConnectIPod" : "Conn iPod per trasfer tag",
	"Country" : "Country",
	"Culture" : "Cultura",
	"Documentary" : "Documentari",
	"Drama" : "Teatro",
	"Education" : "Istruzione",
	"ErrorConnection" : "Errore invio Tag su iPod.",
	"FMRadio" : "Radio FM",
	"FMSettings" : "Impostazioni FM",
	"Finance" : "Finanza",
	"Folk" : "Folk",
	"GenreAffairs" : "Genere: Affari",
	"GenreAlarm" : "Genere: Allarme",
	"GenreAlarmTest" : "Genere: Test allarme",
	"GenreAllStations" : "Genere: tutte le stazioni",
	"GenreChildrens" : "Genere: Bambini",
	"GenreClassics" : "Genere: Classica",
	"GenreCountry" : "Genere: Country",
	"GenreCulture" : "Genere: Cultura",
	"GenreDocumentary" : "Genere: Documentari",
	"GenreDrama" : "Genere: Teatro",
	"GenreEducation" : "Genere: Istruzione",
	"GenreFinance" : "Genere: Finanza",
	"GenreFolk" : "Genere: Folk",
	"GenreInfo" : "Genere: Informazioni",
	"GenreJazz" : "Genere: Jazz",
	"GenreLeisure" : "Genere: Tempo libero",
	"GenreLight" : "Genere: Leggera",
	"GenreList" : "Elenco generi",
	"GenreMor" : "Genere: di facile ascolto",
	"GenreName" : "Genere: {genreName}",
	"GenreNational" : "Genere: Nazionale",
	"GenreNews" : "Genere: Notizie",
	"GenreOldies" : "Genere: Classici",
	"GenreOther" : "Genere: Altro",
	"GenrePhoneIn" : "Genere: Programma con telefonate",
	"GenrePop" : "Genere: Pop",
	"GenreReligion" : "Genere: Religione",
	"GenreRock" : "Genere: Rock",
	"GenreScience" : "Genere: Scienza",
	"GenreSeek" : "Ricerca genere",
	"GenreSocial" : "Genere: Sociale",
	"GenreSport" : "Genere: Sport",
	"GenreTravel" : "Genere: Viaggi",
	"GenreVaried" : "Genere: Vari",
	"GenreWeather" : "Genere: Clima",
	"HDRadio" : "Radio HD",
	"HDStations" : "Stazioni HD",
	"Info" : "Informazioni",
	"IpodError" : "Errore iPod ",
	"IpodFull" : "iPod pieno.",
	"Jazz" : "Jazz",
	"Leisure" : "Tempo libero",
	"Light" : "Leggera",
	"ListUpdate" : "List Update",
	"MemoryFull" : "Memoria piena.",
	"Mor" : "Di facile ascolto",
	"National" : "Nazionale",
	"News" : "Notizie",
	"Noresultsfound" : "Nessun risultato trovato.",
	"Oldies" : "Classici",
	"Other" : "Altro",
	"PartialTransfer" : "Trasferimento parziale",
	"PhoneIn" : "Con telefonate",
	"Pop" : "Pop",
	"RegionLock" : "Blocco territoriale",
	"Religion" : "Religione",
	"Remaining" : "{numberOfTags} Rimanenti",
	"Remove" : "Elimina",
	"Rock" : "Rock",
	"Science" : "Scienza",
	"SignalLost" : "Segnale perso",
	"Social" : "Sociale",
	"Sport" : "Sport",
	"StationList" : "Elenco stazioni",
	"TAOff" : "TA spento",
	"TagAlreadySaved" : "Etichetta già salvata",
	"TagCaptured" : "Tag preso",
	"TagMemoryFull" : "Memoria etichetta piena.",
	"TagNotYetProcessed" : "Etichetta non processata.",
	"TagSaved" : "Etichetta salvata",
	"TagSavedtoIpod" : "Etichetta salvata su iPod",
	"TagSavedtoSystem" : "Tag salvata su sistema.",
	"TagTransferredtoiPod" : "Tag trasferita su iPod.",
	"TagsCannotBeSaved" : "Impossibile salvare le tag.",
	"Tooltip_IcnUmpFMSettings" : "Impostazioni FM",
	"TrafficAlert" : "Annuncio sul traffico (TA)",
	"TrafficAlertOff" : "Annunci sul traffico (TA) spento",
	"TrafficAlertOn" : "Annunci sul traffico (TA) acceso",
	"Travel" : "Viaggi",
	"UnplugAndReconnect" : "Sconnetti e riconnetti",
	"UpdateStationList" : "Aggiorna elenco stazioni",
	"UpdatingStationList" : "Aggiornamento elenco stazioni",
	"Varied" : "Vari",
	"VrHelp_AlternativeFrequencyOff" : "Frequenza alternativa spenta",
	"VrHelp_AlternativeFrequencyOn" : "Frequenza alternativa accesa",
	"VrHelp_AutoMemory" : "Memoria automatica",
	"VrHelp_ChangeGenre" : "Cambia genere",
	"VrHelp_Entertainment" : "Intrattenimento",
	"VrHelp_FMSettings" : "Impostazioni FM",
	"VrHelp_Favorites" : "Preferito",
	"VrHelp_Frequency" : "(frequenza)",
	"VrHelp_HDMenu" : "Canale HD Radio",
	"VrHelp_RegionLockOff" : "Blocco territoriale spento",
	"VrHelp_RegionLockOn" : "Blocco territoriale acceso",
	"VrHelp_Scan" : "Scansione",
	"VrHelp_SeekDown" : "Cerca avanti",
	"VrHelp_SeekNext" : "Cerca successivo",
	"VrHelp_SeekPrevious" : "Cerca precedente",
	"VrHelp_SeekUp" : "Cerca indietro",
	"VrHelp_SoundSettings" : "Impostazioni audio",
	"VrHelp_StationList" : "Elenco stazioni",
	"VrHelp_TrafficAnnouncement" : "Annuncio sul traffico (TA)",
	"VrHelp_Tune" : "Sintonizza",
	"VrHelp_TuneDown" : "Sintonizza avanti",
	"VrHelp_TuneUp" : "Sintonizza indietro",
	"VrHelp_UpdateList" : "Aggiorna elenco",
	"VrHelp_iTunesTagging" : "Tag iTunes",
	"Weather" : "Clima",
	"favorites_Tooltip" : "Preferiti",
	"hdChannels_Tooltip" : "Canali HD",
	"rbds_Adult" : "Vecchie hit",
	"rbds_Class" : "Rock classico",
	"rbds_Classical" : "Classica",
	"rbds_College" : "Università",
	"rbds_Country" : "Country",
	"rbds_Emergency" : "Alert! Alert!",
	"rbds_EmergencyTest" : "Test di Emergenza",
	"rbds_Foreign" : "In lingua straniera",
	"rbds_Hablar" : "In Spagnolo",
	"rbds_HipHop" : "Hip Hop",
	"rbds_Info" : "Informazioni",
	"rbds_Jazz" : "Jazz",
	"rbds_Musica" : "Musica Spagnola",
	"rbds_News" : "Notizie",
	"rbds_None" : "--",
	"rbds_Nostalgia" : "Nostalgica",
	"rbds_Oldies" : "Classici",
	"rbds_Personality" : "Personalità",
	"rbds_Public" : "Pubblico",
	"rbds_ReligousM" : "Musica religiosa",
	"rbds_ReligousT" : "Discorsi Religiosi",
	"rbds_Rhythym" : "Rhythm and Blues",
	"rbds_Rock" : "Rock",
	"rbds_Soft" : "Soft",
	"rbds_SoftRB" : "Rhythm and Blues soft",
	"rbds_SoftRock" : "Rock leggero",
	"rbds_Sports" : "Sport",
	"rbds_Talk" : "Conversazioni",
	"rbds_Top40" : "Top 40",
	"rbds_Weather" : "Clima",
	"rbds_genre_Adult" : "Genere: Vecchie hit",
	"rbds_genre_Class" : "Genere: Rock classico",
	"rbds_genre_Classical" : "Genere: Classica",
	"rbds_genre_College" : "Genere: Università",
	"rbds_genre_Country" : "Genere: Country",
	"rbds_genre_Emergency" : "Genere: Alert! Alert!",
	"rbds_genre_EmergencyTest" : "Genere: Test di Emergenza",
	"rbds_genre_Foreign" : "Genere: In lingua straniera",
	"rbds_genre_Hablar" : "Genere: In Spagnolo",
	"rbds_genre_HipHop" : "Genere: Hip Hop",
	"rbds_genre_Info" : "Genere: Informazioni",
	"rbds_genre_Jazz" : "Genere: Jazz",
	"rbds_genre_Musica" : "Genere: Musica Spagnola",
	"rbds_genre_News" : "Genere: Notizie",
	"rbds_genre_None" : "Genere: --",
	"rbds_genre_Nostalgia" : "Genere: Nostalgica",
	"rbds_genre_Oldies" : "Genere: Classici",
	"rbds_genre_Personality" : "Genere: Personalità",
	"rbds_genre_Public" : "Genere: Pubblico",
	"rbds_genre_ReligousM" : "Genere: Musica religiosa",
	"rbds_genre_ReligousT" : "Genere: Discorsi Religiosi",
	"rbds_genre_Rhythym" : "Genere: Rhythm and Blues",
	"rbds_genre_Rock" : "Genere: Rock",
	"rbds_genre_Soft" : "Genere: Soft",
	"rbds_genre_SoftRB" : "Genere: Rhythm and Blues soft",
	"rbds_genre_SoftRock" : "Genere: Rock leggero",
	"rbds_genre_Sports" : "Genere: Sport",
	"rbds_genre_Talk" : "Genere: Conversazioni",
	"rbds_genre_Top40" : "Genere: Top 40",
	"rbds_genre_Weather" : "Genere: Clima",
};

framework.registerAppDictLoaded("fmradio", "it_IT");