var __VrHelpPositionTable__fmradioAppDict_id_ID = {
	"AutoMemory_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"AreaPresetJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"NowPlayingEU_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_FMSettings","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_TrafficAnnouncement","VrHelp_Scan"]
	},
	"AreaPresetJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"NowPlayingNA_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_iTunesTagging","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_HDMenu","VrHelp_Scan"]
	},
	"Settings_Help" : {
		"Left" : ["VrHelp_AlternativeFrequencyOn","VrHelp_AlternativeFrequencyOff","VrHelp_RegionLockOn","VrHelp_RegionLockOff"]
	},
	"Tune_NA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"StationListJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"StationListJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"GenreSeek_Help" : {
		"Left" : ["VrHelp_SeekUp","VrHelp_SeekDown","VrHelp_ChangeGenre"]
	},
	"NowPlayingJapan_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"Tune_nonNA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"NowPlayingOther_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"AutoMemory_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	}
};

var Localization_fmradioAppDict_id_ID = {
	//"stringId" : "localString"
	"Affairs" : "Peristiwa Terkini",
	"Alarm" : "Alarm",
	"AlarmTest" : "Tes Alarm",
	"AllMemoryFull" : "Semua Memori Penuh",
	"AllStations" : "Semua Stasiun",
	"AllTagsTransferred" : "Semua Tag Ditransfer",
	"AlternativeFrequency" : "Frekuensi Alternatif",
	"AreaPresetTab" : "Area Preset",
	"AutoMemoryList" : "Daftar Memori Otomatis",
	"CannotTransferTags" : "Tak Bisa Transfer Tag",
	"ChangeGenre" : "Rubah Aliran",
	"ChannelListJP" : "Channel List",
	"ChannelListTab" : "Channel List",
	"Childrens" : "Anak-anak",
	"Classics" : "Klasik",
	"Close" : "Tutup",
	"ConnectIPod" : "Smbng iPod utk Trnsfr Tag",
	"Country" : "Negara",
	"Culture" : "Budaya",
	"Documentary" : "Dokumenter",
	"Drama" : "Drama",
	"Education" : "Pendidikan",
	"ErrorConnection" : "Transfer ke iPod Gagal",
	"FMRadio" : "Radio FM",
	"FMSettings" : "Pengaturan FM",
	"Finance" : "Keuangan",
	"Folk" : "Kebangsaan",
	"GenreAffairs" : "Aliran: Peristiwa Terkini",
	"GenreAlarm" : "Aliran: Alarm",
	"GenreAlarmTest" : "Aliran: Tes Alarm",
	"GenreAllStations" : "Aliran: Semua stasiun",
	"GenreChildrens" : "Aliran: Anak-anak",
	"GenreClassics" : "Aliran: Klasik",
	"GenreCountry" : "Aliran: Country",
	"GenreCulture" : "Aliran: Budaya",
	"GenreDocumentary" : "Aliran: Dokumenter",
	"GenreDrama" : "Aliran: Drama",
	"GenreEducation" : "Aliran: Pendidikan",
	"GenreFinance" : "Aliran: Keuangan",
	"GenreFolk" : "Aliran: Folk",
	"GenreInfo" : "Aliran: Informasi",
	"GenreJazz" : "Aliran: Jazz",
	"GenreLeisure" : "Aliran: Santai",
	"GenreLight" : "Aliran: Ringan",
	"GenreList" : "Daftar Aliran",
	"GenreMor" : "Aliran: Mudah Didengarkan",
	"GenreName" : "Aliran: {genreName}",
	"GenreNational" : "Aliran: Nasional",
	"GenreNews" : "Aliran: Berita",
	"GenreOldies" : "Aliran: Lagu Lama",
	"GenreOther" : "Aliran: Lainnya",
	"GenrePhoneIn" : "Aliran: Telepon Masuk",
	"GenrePop" : "Aliran: Pop",
	"GenreReligion" : "Aliran: Religi",
	"GenreRock" : "Aliran: Rock",
	"GenreScience" : "Aliran: Pengetahuan",
	"GenreSeek" : "Pencarian Aliran",
	"GenreSocial" : "Aliran: Sosial",
	"GenreSport" : "Aliran: Olahraga",
	"GenreTravel" : "Aliran: Perjalanan",
	"GenreVaried" : "Aliran: Beragam",
	"GenreWeather" : "Aliran: Cuaca",
	"HDRadio" : "Radio HD",
	"HDStations" : "Stasiun HD",
	"Info" : "Informasi",
	"IpodError" : "iPod Eror",
	"IpodFull" : "iPod Penuh",
	"Jazz" : "Jazz",
	"Leisure" : "Santai",
	"Light" : "Redup",
	"ListUpdate" : "List Update",
	"MemoryFull" : "Memori Penuh",
	"Mor" : "Mudah Didengarkan",
	"National" : "Nasional",
	"News" : "Berita",
	"Noresultsfound" : "Hasil tidak ditemukan",
	"Oldies" : "Lagu Lama",
	"Other" : "Lainnya",
	"PartialTransfer" : "Transfer Parsial",
	"PhoneIn" : "Telepon Masuk",
	"Pop" : "Pop",
	"RegionLock" : "Penguncian Wilayah",
	"Religion" : "Religi",
	"Remaining" : "{numberOfTags} Tersisa",
	"Remove" : "Hapus",
	"Rock" : "Rock",
	"Science" : "Pengetahuan",
	"SignalLost" : "Sinyal Hilang",
	"Social" : "Sosial",
	"Sport" : "Olahraga",
	"StationList" : "Daftar Stasiun",
	"TAOff" : "TA Mati",
	"TagAlreadySaved" : "Tag Telah Tersimpan",
	"TagCaptured" : "Label Disimpan",
	"TagMemoryFull" : "Memori Tag Penuh",
	"TagNotYetProcessed" : "Tag Belum Diproses",
	"TagSaved" : "Transfer ke iPod Eror",
	"TagSavedtoIpod" : "Tag Disimpan ke iPod",
	"TagSavedtoSystem" : "Tag Disimpan ke Sistem",
	"TagTransferredtoiPod" : "Tag Ditransfer ke ipod",
	"TagsCannotBeSaved" : "Tag Tidak Dapat Disimpan",
	"Tooltip_IcnUmpFMSettings" : "Pengaturan FM",
	"TrafficAlert" : "Pemberitahuan Lalu-Lintas (TA)",
	"TrafficAlertOff" : "Pemberitahuan Lalu-Lintas (TA) non aktif",
	"TrafficAlertOn" : "Pemberitahuan Lalu-Lintas (TA) aktif",
	"Travel" : "Perjalanan",
	"UnplugAndReconnect" : "Cabut dan Sambung Lagi",
	"UpdateStationList" : "Perbarui Daftar Stasiun",
	"UpdatingStationList" : "Memperbarui Daftar Stasiun",
	"Varied" : "Beragam",
	"VrHelp_AlternativeFrequencyOff" : "Alternative Frequency Off",
	"VrHelp_AlternativeFrequencyOn" : "Alternative Frequency On",
	"VrHelp_AutoMemory" : "Auto Memory",
	"VrHelp_ChangeGenre" : "Change Genre",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_FMSettings" : "FM Settings",
	"VrHelp_Favorites" : "Favorites",
	"VrHelp_Frequency" : "(frequency)",
	"VrHelp_HDMenu" : "HD Radio Channels",
	"VrHelp_RegionLockOff" : "Region Lock Off",
	"VrHelp_RegionLockOn" : "Region Lock On",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SeekDown" : "Seek Down",
	"VrHelp_SeekNext" : "Seek Next",
	"VrHelp_SeekPrevious" : "Seek Previous",
	"VrHelp_SeekUp" : "Seek Up",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement (TA)",
	"VrHelp_Tune" : "Tune",
	"VrHelp_TuneDown" : "Tune Down",
	"VrHelp_TuneUp" : "Tune Up",
	"VrHelp_UpdateList" : "Update List",
	"VrHelp_iTunesTagging" : "iTunes Tagging",
	"Weather" : "Cuaca",
	"favorites_Tooltip" : "Favorit",
	"hdChannels_Tooltip" : "Saluran HD",
	"rbds_Adult" : "Hits Dewasa",
	"rbds_Class" : "Rock Klasik",
	"rbds_Classical" : "Klasik",
	"rbds_College" : "Kampus",
	"rbds_Country" : "Country",
	"rbds_Emergency" : "Waspada! Waspada!",
	"rbds_EmergencyTest" : "Uji Darurat",
	"rbds_Foreign" : "Bahasa Asing",
	"rbds_Hablar" : "Berbicara Spanyol",
	"rbds_HipHop" : "Hip Hop",
	"rbds_Info" : "Informasi",
	"rbds_Jazz" : "Jazz",
	"rbds_Musica" : "Musik Spanyol",
	"rbds_News" : "Berita",
	"rbds_None" : "Tak Satupun",
	"rbds_Nostalgia" : "Nostalgia",
	"rbds_Oldies" : "Lagu Lama",
	"rbds_Personality" : "Kepribadian",
	"rbds_Public" : "Publik",
	"rbds_ReligousM" : "Musik Keagamaan",
	"rbds_ReligousT" : "Bahasan Keagamaan",
	"rbds_Rhythym" : "Ritme dan Blues",
	"rbds_Rock" : "Rock",
	"rbds_Soft" : "Ringan",
	"rbds_SoftRB" : "R&B Ringan",
	"rbds_SoftRock" : "Rock Ringan",
	"rbds_Sports" : "Olahraga",
	"rbds_Talk" : "Berbicara",
	"rbds_Top40" : "Top 40",
	"rbds_Weather" : "Cuaca",
	"rbds_genre_Adult" : "Aliran: Rock Klasik",
	"rbds_genre_Class" : "Aliran: Berbicara",
	"rbds_genre_Classical" : "Country",
	"rbds_genre_College" : "Aliran: Publik",
	"rbds_genre_Country" : "Aliran: Jazz",
	"rbds_genre_Emergency" : "Aliran: Rock",
	"rbds_genre_EmergencyTest" : "Aliran: Hip Hop",
	"rbds_genre_Foreign" : "Aliran: R&B Ringan",
	"rbds_genre_Hablar" : "Aliran: Kampus",
	"rbds_genre_HipHop" : "Aliran: Musik Spanyol",
	"rbds_genre_Info" : "Aliran: Kepribadian",
	"rbds_genre_Jazz" : "Aliran: Nostalgia",
	"rbds_genre_Musica" : "Aliran: Berbicara Spanyol",
	"rbds_genre_News" : "Aliran: Bahasan Keagamaan",
	"rbds_genre_None" : "Aliran: Tak Satupun",
	"rbds_genre_Nostalgia" : "Aliran: Ringan",
	"rbds_genre_Oldies" : "Aliran: Klasik",
	"rbds_genre_Personality" : "Aliran: Berita",
	"rbds_genre_Public" : "Aliran: Olahraga",
	"rbds_genre_ReligousM" : "Aliran: Bahasa Asing",
	"rbds_genre_ReligousT" : "Aliran: Musik Keagamaan",
	"rbds_genre_Rhythym" : "Aliran: Lagu Lama",
	"rbds_genre_Rock" : "Aliran: Uji Darurat",
	"rbds_genre_Soft" : "Aliran: Top 40",
	"rbds_genre_SoftRB" : "Aliran: Ritme dan Blues",
	"rbds_genre_SoftRock" : "Aliran: Hits Dewasa",
	"rbds_genre_Sports" : "Aliran: Informasi",
	"rbds_genre_Talk" : "Aliran: Diskusi",
	"rbds_genre_Top40" : "Aliran: Rock Ringan",
	"rbds_genre_Weather" : "Aliran: Cuaca",
};

framework.registerAppDictLoaded("fmradio", "id_ID");