var __VrHelpPositionTable__fmradioAppDict_pt_BR = {
	"AutoMemory_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"AreaPresetJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"NowPlayingEU_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_FMSettings","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_TrafficAnnouncement","VrHelp_Scan"]
	},
	"AreaPresetJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"NowPlayingNA_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_iTunesTagging","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_HDMenu","VrHelp_Scan"]
	},
	"Settings_Help" : {
		"Left" : ["VrHelp_AlternativeFrequencyOn","VrHelp_AlternativeFrequencyOff","VrHelp_RegionLockOn","VrHelp_RegionLockOff"]
	},
	"Tune_NA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"StationListJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"StationListJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"GenreSeek_Help" : {
		"Left" : ["VrHelp_SeekUp","VrHelp_SeekDown","VrHelp_ChangeGenre"]
	},
	"NowPlayingJapan_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"Tune_nonNA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"NowPlayingOther_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"AutoMemory_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	}
};

var Localization_fmradioAppDict_pt_BR = {
	//"stringId" : "localString"
	"Affairs" : "Relacionamentos",
	"Alarm" : "Alarme",
	"AlarmTest" : "Teste do alarme",
	"AllMemoryFull" : "Todas as memória cheias",
	"AllStations" : "Todas as estações",
	"AllTagsTransferred" : "Todas as tags transferidas",
	"AlternativeFrequency" : "Frequência alternativa",
	"AreaPresetTab" : "Area Preset",
	"AutoMemoryList" : "Lista de memória automática",
	"CannotTransferTags" : "Não é possível transf. tags",
	"ChangeGenre" : "Alterar gênero",
	"ChannelListJP" : "Channel List",
	"ChannelListTab" : "Channel List",
	"Childrens" : "Infantis",
	"Classics" : "Clássicos",
	"Close" : "Fechar",
	"ConnectIPod" : "Conecte iPod p/ transf.",
	"Country" : "Sertanejas",
	"Culture" : "Cultura",
	"Documentary" : "Documentários",
	"Drama" : "Drama",
	"Education" : "Educação",
	"ErrorConnection" : "Erro durante transferência",
	"FMRadio" : "Rádio FM",
	"FMSettings" : "Configurações FM",
	"Finance" : "Finanças",
	"Folk" : "Folk",
	"GenreAffairs" : "Gênero: Relacionamentos",
	"GenreAlarm" : "Gênero: Alarme",
	"GenreAlarmTest" : "Gênero: Teste do alarme",
	"GenreAllStations" : "Gênero: Todas as estações",
	"GenreChildrens" : "Gênero: Infantis",
	"GenreClassics" : "Gênero: Clássicos",
	"GenreCountry" : "Gênero: Sertanejas",
	"GenreCulture" : "Gênero: Cultura",
	"GenreDocumentary" : "Gênero: Documentários",
	"GenreDrama" : "Gênero: Drama",
	"GenreEducation" : "Gênero: Educação",
	"GenreFinance" : "Gênero: Finanças",
	"GenreFolk" : "Gênero: Folk",
	"GenreInfo" : "Gênero: Informações",
	"GenreJazz" : "Gênero: Jazz",
	"GenreLeisure" : "Gênero: Lazer",
	"GenreLight" : "Gênero: Leves",
	"GenreList" : "Seleção de gênero",
	"GenreMor" : "Gênero: Suaves",
	"GenreName" : "Gênero: {genreName}",
	"GenreNational" : "Gênero: Nacionais",
	"GenreNews" : "Gênero: Notícias",
	"GenreOldies" : "Gênero: Antigas",
	"GenreOther" : "Gênero: Outros",
	"GenrePhoneIn" : "Gênero: Telefonemas",
	"GenrePop" : "Gênero: Pop",
	"GenreReligion" : "Gênero: Religião",
	"GenreRock" : "Gênero: Rock",
	"GenreScience" : "Gênero: Ciência",
	"GenreSeek" : "Procurar gênero",
	"GenreSocial" : "Gênero: Responsabilidade",
	"GenreSport" : "Gênero: Esporte",
	"GenreTravel" : "Gênero: Viagens",
	"GenreVaried" : "Gênero: Variedades",
	"GenreWeather" : "Gênero: Clima",
	"HDRadio" : "Rádio HD",
	"HDStations" : "Estações HD",
	"Info" : "Informações",
	"IpodError" : "Erro no iPod",
	"IpodFull" : "iPod cheio",
	"Jazz" : "Jazz",
	"Leisure" : "Lazer",
	"Light" : "Leves",
	"ListUpdate" : "List Update",
	"MemoryFull" : "Memória cheia",
	"Mor" : "Suaves ",
	"National" : "Nacionais",
	"News" : "Notícias",
	"Noresultsfound" : "Nenhum resultado encontrado",
	"Oldies" : "Antigas",
	"Other" : "Outros",
	"PartialTransfer" : "Transferência parcial",
	"PhoneIn" : "Telefonemas",
	"Pop" : "Pop",
	"RegionLock" : "Bloqueio de região",
	"Religion" : "Religião",
	"Remaining" : "{numberOfTags} restantes",
	"Remove" : "Remover",
	"Rock" : "Rock",
	"Science" : "Ciência",
	"SignalLost" : "Sinal perdido",
	"Social" : "Responsabilidade",
	"Sport" : "Esporte",
	"StationList" : "Lista de estações",
	"TAOff" : "TA desligado",
	"TagAlreadySaved" : "Tag salva",
	"TagCaptured" : "Tag capturada",
	"TagMemoryFull" : "Memória de tags cheia",
	"TagNotYetProcessed" : "Tag ainda não processada",
	"TagSaved" : "Tag salva",
	"TagSavedtoIpod" : "Tag salva no iPod",
	"TagSavedtoSystem" : "Tag salva no sistema",
	"TagTransferredtoiPod" : "Tag transferida para iPod",
	"TagsCannotBeSaved" : "Não é possível salvar tags",
	"Tooltip_IcnUmpFMSettings" : "Configurações FM",
	"TrafficAlert" : "Anúncio de Tráfego (TA)",
	"TrafficAlertOff" : "Anúncio de Tráfego (TA) desligado",
	"TrafficAlertOn" : "Anúncio de Tráfego (TA) ligado",
	"Travel" : "Viagens",
	"UnplugAndReconnect" : "Desconecte e conecte",
	"UpdateStationList" : "Atualizar lista de estações",
	"UpdatingStationList" : "Atualizando lista de estações",
	"Varied" : "Variedades",
	"VrHelp_AlternativeFrequencyOff" : "Frequência alternativa desligada",
	"VrHelp_AlternativeFrequencyOn" : "Frequência alternativa ligada",
	"VrHelp_AutoMemory" : "Memória automática",
	"VrHelp_ChangeGenre" : "Alterar gênero",
	"VrHelp_Entertainment" : "Entretenimento",
	"VrHelp_FMSettings" : "Configurações FM",
	"VrHelp_Favorites" : "Favoritos",
	"VrHelp_Frequency" : "(frequência)",
	"VrHelp_HDMenu" : "HD Radio Channels",
	"VrHelp_RegionLockOff" : "Bloqueio de região desligado",
	"VrHelp_RegionLockOn" : "Bloqueio de região ligado",
	"VrHelp_Scan" : "Procurar",
	"VrHelp_SeekDown" : "Procurar para baixo",
	"VrHelp_SeekNext" : "Procurar seguinte",
	"VrHelp_SeekPrevious" : "Procurar anterior",
	"VrHelp_SeekUp" : "Procurar para cima",
	"VrHelp_SoundSettings" : "Definições de som",
	"VrHelp_StationList" : "Lista de estações",
	"VrHelp_TrafficAnnouncement" : "Anúncio de Tráfego (TA)",
	"VrHelp_Tune" : "Sintonizar",
	"VrHelp_TuneDown" : "Sintonizar para baixo",
	"VrHelp_TuneUp" : "Sintonizar para cima",
	"VrHelp_UpdateList" : "Atualizar lista",
	"VrHelp_iTunesTagging" : "Marcação do iTunes",
	"Weather" : "Clima",
	"favorites_Tooltip" : "Favoritos",
	"hdChannels_Tooltip" : "Menu do HD",
	"rbds_Adult" : "Hits",
	"rbds_Class" : "Rock clássico",
	"rbds_Classical" : "Clássicas",
	"rbds_College" : "Faculdade",
	"rbds_Country" : "País",
	"rbds_Emergency" : "Alerta! Alerta!",
	"rbds_EmergencyTest" : "Teste de emergência",
	"rbds_Foreign" : "Idioma estrangeiro",
	"rbds_Hablar" : "Falar espanhol",
	"rbds_HipHop" : "Hip hop",
	"rbds_Info" : "Informações",
	"rbds_Jazz" : "Jazz",
	"rbds_Musica" : "Músicas em espanhol",
	"rbds_News" : "Notícias",
	"rbds_None" : "Nenhum",
	"rbds_Nostalgia" : "Nostalgia",
	"rbds_Oldies" : "Antigas",
	"rbds_Personality" : "Personalidades",
	"rbds_Public" : "Público",
	"rbds_ReligousM" : "Músicas religiosas",
	"rbds_ReligousT" : "Religião",
	"rbds_Rhythym" : "Ritmo e Blues",
	"rbds_Rock" : "Rock",
	"rbds_Soft" : "Calmas",
	"rbds_SoftRB" : "R&B Suave",
	"rbds_SoftRock" : "Rock Suave",
	"rbds_Sports" : "Esportes",
	"rbds_Talk" : "Programa de auditório",
	"rbds_Top40" : "40 Melhores",
	"rbds_Weather" : "Clima",
	"rbds_genre_Adult" : "Gênero: Hits",
	"rbds_genre_Class" : "Gênero: Rock Clássico",
	"rbds_genre_Classical" : "Gênero: Clássicas",
	"rbds_genre_College" : "Gênero: Faculdade",
	"rbds_genre_Country" : "Gênero: Nacionais",
	"rbds_genre_Emergency" : "Gênero: Alerta! Alerta!",
	"rbds_genre_EmergencyTest" : "Gênero: Teste de emergência",
	"rbds_genre_Foreign" : "Gênero: Idioma Estrangeiro",
	"rbds_genre_Hablar" : "Gênero: Falar Espanhol",
	"rbds_genre_HipHop" : "Gênero: Hip hop",
	"rbds_genre_Info" : "Gênero: Informações",
	"rbds_genre_Jazz" : "Gênero: Jazz",
	"rbds_genre_Musica" : "Gênero: Músicas em Espanhol",
	"rbds_genre_News" : "Gênero: Notícias",
	"rbds_genre_None" : "Gênero: Nenhum",
	"rbds_genre_Nostalgia" : "Gênero: Nostalgia",
	"rbds_genre_Oldies" : "Gênero: Antigas",
	"rbds_genre_Personality" : "Gênero: Personalidades",
	"rbds_genre_Public" : "Gênero: Público",
	"rbds_genre_ReligousM" : "Gênero: Músicas Religiosas",
	"rbds_genre_ReligousT" : "Gênero: Religião",
	"rbds_genre_Rhythym" : "Gênero: Ritmo e Blues",
	"rbds_genre_Rock" : "Gênero: Rock",
	"rbds_genre_Soft" : "Gênero: Normal",
	"rbds_genre_SoftRB" : "Gênero: R&B Suave",
	"rbds_genre_SoftRock" : "Gênero: Rock Suave",
	"rbds_genre_Sports" : "Gênero: Esportes",
	"rbds_genre_Talk" : "Gênero: Programa de auditório",
	"rbds_genre_Top40" : "Gênero: 40 Melhores",
	"rbds_genre_Weather" : "Gênero: Clima",
};

framework.registerAppDictLoaded("fmradio", "pt_BR");