var __VrHelpPositionTable__fmradioAppDict_sk_SK = {
	"AutoMemory_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"AreaPresetJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"NowPlayingEU_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_FMSettings","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_TrafficAnnouncement","VrHelp_Scan"]
	},
	"AreaPresetJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"NowPlayingNA_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_iTunesTagging","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_HDMenu","VrHelp_Scan"]
	},
	"Settings_Help" : {
		"Left" : ["VrHelp_AlternativeFrequencyOn","VrHelp_AlternativeFrequencyOff","VrHelp_RegionLockOn","VrHelp_RegionLockOff"]
	},
	"Tune_NA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"StationListJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"StationListJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"GenreSeek_Help" : {
		"Left" : ["VrHelp_SeekUp","VrHelp_SeekDown","VrHelp_ChangeGenre"]
	},
	"NowPlayingJapan_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"Tune_nonNA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"NowPlayingOther_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"AutoMemory_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	}
};

var Localization_fmradioAppDict_sk_SK = {
	//"stringId" : "localString"
	"Affairs" : "Udalosti",
	"Alarm" : "Alarm",
	"AlarmTest" : "Test alarmu",
	"AllMemoryFull" : "Celá pamäť plná",
	"AllStations" : "Všetky stanice",
	"AllTagsTransferred" : "Všetky značky prenesené",
	"AlternativeFrequency" : "Alternatívna frekvencia",
	"AreaPresetTab" : "Area Preset",
	"AutoMemoryList" : "Zoznam automatickej pamäte",
	"CannotTransferTags" : "Značky nemožno preniesť",
	"ChangeGenre" : "Zmeniť žáner",
	"ChannelListJP" : "Channel List",
	"ChannelListTab" : "Channel List",
	"Childrens" : "Deti",
	"Classics" : "Klasika",
	"Close" : "Zat.",
	"ConnectIPod" : "Na prenos zn. prip. iPod",
	"Country" : "Country",
	"Culture" : "Kultúra",
	"Documentary" : "Dokumentárne",
	"Drama" : "Dráma",
	"Education" : "Vzdelávanie",
	"ErrorConnection" : "Tag prenesený do iPodu",
	"FMRadio" : "FM rádio",
	"FMSettings" : "Nastavenia FM",
	"Finance" : "Financie",
	"Folk" : "Folk",
	"GenreAffairs" : "Žáner: Udalosti",
	"GenreAlarm" : "Žáner: Alarm",
	"GenreAlarmTest" : "Žáner: Test alarmu",
	"GenreAllStations" : "Žáner: Všetky stanice",
	"GenreChildrens" : "Žáner: Deti",
	"GenreClassics" : "Žáner: Klasika",
	"GenreCountry" : "Žáner: Country",
	"GenreCulture" : "Žáner: Kultúra",
	"GenreDocumentary" : "Žáner: Dokumentárne",
	"GenreDrama" : "Žáner: Dráma",
	"GenreEducation" : "Žáner: Vzdelávanie",
	"GenreFinance" : "Žáner: Financie",
	"GenreFolk" : "Žáner: Folk",
	"GenreInfo" : "Žáner: Informácie",
	"GenreJazz" : "Žáner: Džez",
	"GenreLeisure" : "Žáner: Voľný čas",
	"GenreLight" : "Žáner: Ľahké",
	"GenreList" : "Zoznam žánrov",
	"GenreMor" : "Žáner: Ľahké počúvanie",
	"GenreName" : "Žáner: {genreName}",
	"GenreNational" : "Žáner: Národné",
	"GenreNews" : "Žáner: Novinky",
	"GenreOldies" : "Žáner: Oldies",
	"GenreOther" : "Žáner: Iné",
	"GenrePhoneIn" : "Žáner: PhoneIn",
	"GenrePop" : "Žáner: Pop",
	"GenreReligion" : "Žáner: Náboženstvo",
	"GenreRock" : "Žáner: Rock",
	"GenreScience" : "Žáner: Veda",
	"GenreSeek" : "Vyhľadávanie žánru",
	"GenreSocial" : "Žáner: Spoločnosť",
	"GenreSport" : "Žáner: Šport",
	"GenreTravel" : "Žáner: Cestovanie",
	"GenreVaried" : "Žáner: Rôzne",
	"GenreWeather" : "Žáner: Počasie",
	"HDRadio" : "HD rádio",
	"HDStations" : "HD stanice",
	"Info" : "Informácie",
	"IpodError" : "Chyba iPod-u",
	"IpodFull" : "iPod je plný",
	"Jazz" : "Džez",
	"Leisure" : "Voľný čas",
	"Light" : "Light",
	"ListUpdate" : "List Update",
	"MemoryFull" : "Pamäť plná",
	"Mor" : "Ľahké počúvanie",
	"National" : "Národné",
	"News" : "Novinky",
	"Noresultsfound" : "Nenašli sa žiadne výsledky",
	"Oldies" : "Oldies",
	"Other" : "Iné",
	"PartialTransfer" : "Čiastočný prenos",
	"PhoneIn" : "Phone In",
	"Pop" : "Pop",
	"RegionLock" : "Zámok regiónu",
	"Religion" : "Náboženstvo",
	"Remaining" : "Zostáva {numberOfTags}",
	"Remove" : "Odstrániť",
	"Rock" : "Rock",
	"Science" : "Veda",
	"SignalLost" : "Signál sa stratil",
	"Social" : "Spoločenské",
	"Sport" : "Šport",
	"StationList" : "Zoznam staníc",
	"TAOff" : "TA vyp",
	"TagAlreadySaved" : "Značka už uložená",
	"TagCaptured" : "Značka zachytená",
	"TagMemoryFull" : "Pamäť značiek plná",
	"TagNotYetProcessed" : "Znač. nie je spracovaná",
	"TagSaved" : "Značka uložená",
	"TagSavedtoIpod" : "Značka uložená do iPodu",
	"TagSavedtoSystem" : "Značka uložená do sys.",
	"TagTransferredtoiPod" : "Tag prenesený do iPodu",
	"TagsCannotBeSaved" : "Značky nemožno uložiť",
	"Tooltip_IcnUmpFMSettings" : "Nastavenia FM",
	"TrafficAlert" : "Premávka (TA)",
	"TrafficAlertOff" : "Premávka (TA) vyp",
	"TrafficAlertOn" : "Premávka (TA) zap",
	"Travel" : "Cestovanie",
	"UnplugAndReconnect" : "Odpojiť a znovu pripojiť",
	"UpdateStationList" : "Aktualizovať zoznam staníc",
	"UpdatingStationList" : "Aktualizácia zoznamu staníc",
	"Varied" : "Rôzne",
	"VrHelp_AlternativeFrequencyOff" : "Alternative Frequency Off",
	"VrHelp_AlternativeFrequencyOn" : "Alternative Frequency On",
	"VrHelp_AutoMemory" : "Auto Memory",
	"VrHelp_ChangeGenre" : "Change Genre",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_FMSettings" : "FM Settings",
	"VrHelp_Favorites" : "Favorites",
	"VrHelp_Frequency" : "(frequency)",
	"VrHelp_HDMenu" : "HD Radio Channels",
	"VrHelp_RegionLockOff" : "Region Lock Off",
	"VrHelp_RegionLockOn" : "Region Lock On",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SeekDown" : "Seek Down",
	"VrHelp_SeekNext" : "Seek Next",
	"VrHelp_SeekPrevious" : "Seek Previous",
	"VrHelp_SeekUp" : "Seek Up",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement (TA)",
	"VrHelp_Tune" : "Tune",
	"VrHelp_TuneDown" : "Tune Down",
	"VrHelp_TuneUp" : "Tune Up",
	"VrHelp_UpdateList" : "Update List",
	"VrHelp_iTunesTagging" : "iTunes Tagging",
	"Weather" : "Počasie",
	"favorites_Tooltip" : "Obľúbené",
	"hdChannels_Tooltip" : "HD kanály",
	"rbds_Adult" : "Hity pre dospelých",
	"rbds_Class" : "Klasický Rock",
	"rbds_Classical" : "Klasický",
	"rbds_College" : "Koľaj",
	"rbds_Country" : "Country",
	"rbds_Emergency" : "Upozornenie! Upozornenie!",
	"rbds_EmergencyTest" : "Núdzové Testy",
	"rbds_Foreign" : "Cudzí Jazyk",
	"rbds_Hablar" : "Hovoriť španielsky",
	"rbds_HipHop" : "Hip Hop",
	"rbds_Info" : "Informácie",
	"rbds_Jazz" : "Džez",
	"rbds_Musica" : "Španielska hudba",
	"rbds_News" : "Novinky",
	"rbds_None" : "--",
	"rbds_Nostalgia" : "Nostalgie",
	"rbds_Oldies" : "Oldies",
	"rbds_Personality" : "Osobnosť",
	"rbds_Public" : "Verejnosť",
	"rbds_ReligousM" : "Náboženská Hudba",
	"rbds_ReligousT" : "Náboženské rozhovory",
	"rbds_Rhythym" : "Rytmus a Blues",
	"rbds_Rock" : "Rock",
	"rbds_Soft" : "Mäkký",
	"rbds_SoftRB" : "Jemný R&B",
	"rbds_SoftRock" : "Jemný Rock",
	"rbds_Sports" : "Šport",
	"rbds_Talk" : "Rozhovory",
	"rbds_Top40" : "Top 40",
	"rbds_Weather" : "Počasie",
	"rbds_genre_Adult" : "Žáner: Dospelých Hity",
	"rbds_genre_Class" : "Žáner: Klasický Rock",
	"rbds_genre_Classical" : "Žáner: Klasický",
	"rbds_genre_College" : "Žáner: Koľaj",
	"rbds_genre_Country" : "Žáner: Country",
	"rbds_genre_Emergency" : "Žáner: Upozornenie! Upozornenie!",
	"rbds_genre_EmergencyTest" : "Žáner: Núdzové Testy",
	"rbds_genre_Foreign" : "Žáner: Cudzí Jazyk",
	"rbds_genre_Hablar" : "Žáner: Hovoriť španielsky",
	"rbds_genre_HipHop" : "Žáner: Hip Hop",
	"rbds_genre_Info" : "Žáner: Informácie",
	"rbds_genre_Jazz" : "Žáner: Džez",
	"rbds_genre_Musica" : "Žáner: Španielska hudba",
	"rbds_genre_News" : "Žáner: Novinky",
	"rbds_genre_None" : "Žáner: --",
	"rbds_genre_Nostalgia" : "Žáner: Nostalgie",
	"rbds_genre_Oldies" : "Žáner: Oldies",
	"rbds_genre_Personality" : "Žáner: Osobnosť",
	"rbds_genre_Public" : "Žáner: Verejnosť",
	"rbds_genre_ReligousM" : "Žáner: Náboženská Hudba",
	"rbds_genre_ReligousT" : "Žáner: Náboženské rozhovory",
	"rbds_genre_Rhythym" : "Žáner: Rytmus a Blues",
	"rbds_genre_Rock" : "Žáner: Rock",
	"rbds_genre_Soft" : "Žáner: Mäkký",
	"rbds_genre_SoftRB" : "Žáner: Mäkký R&B",
	"rbds_genre_SoftRock" : "Žáner: Mäkký Rock",
	"rbds_genre_Sports" : "Žáner: Sports",
	"rbds_genre_Talk" : "Žáner: Rozhovory",
	"rbds_genre_Top40" : "Žáner: Top 40",
	"rbds_genre_Weather" : "Žáner: Počasie",
};

framework.registerAppDictLoaded("fmradio", "sk_SK");