var __VrHelpPositionTable__fmradioAppDict_de_DE = {
	"AutoMemory_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"AreaPresetJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"NowPlayingEU_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_FMSettings","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_TrafficAnnouncement","VrHelp_Scan"]
	},
	"AreaPresetJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"NowPlayingNA_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_iTunesTagging","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_HDMenu","VrHelp_Scan"]
	},
	"Settings_Help" : {
		"Left" : ["VrHelp_AlternativeFrequencyOn","VrHelp_AlternativeFrequencyOff","VrHelp_RegionLockOn","VrHelp_RegionLockOff"]
	},
	"Tune_NA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"StationListJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"StationListJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"GenreSeek_Help" : {
		"Left" : ["VrHelp_SeekUp","VrHelp_SeekDown","VrHelp_ChangeGenre"]
	},
	"NowPlayingJapan_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"Tune_nonNA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"NowPlayingOther_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"AutoMemory_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	}
};

var Localization_fmradioAppDict_de_DE = {
	//"stringId" : "localString"
	"Affairs" : "Aktuelles Geschehen",
	"Alarm" : "Alarm",
	"AlarmTest" : "Alarm Test",
	"AllMemoryFull" : "Gesamter Speicher voll",
	"AllStations" : "Alle Sender",
	"AllTagsTransferred" : "Alle Tags übertragen",
	"AlternativeFrequency" : "Alternative Frequenz",
	"AreaPresetTab" : "Area Preset",
	"AutoMemoryList" : "Automatische Speicherliste",
	"CannotTransferTags" : "Kann Tags nicht übertr.",
	"ChangeGenre" : "Genre ändern",
	"ChannelListJP" : "Channel List",
	"ChannelListTab" : "Channel List",
	"Childrens" : "Kinder",
	"Classics" : "Klassisch",
	"Close" : "Schließen",
	"ConnectIPod" : "iPod anschl. f. Tagübertr.",
	"Country" : "Country",
	"Culture" : "Kultur",
	"Documentary" : "Dokumentation",
	"Drama" : "Schauspiel",
	"Education" : "Ausbildung",
	"ErrorConnection" : "Tag-Übertra.-Fehler z. iPod",
	"FMRadio" : "FM Radio",
	"FMSettings" : "FM Einstellungen",
	"Finance" : "Finanzen",
	"Folk" : "Folk",
	"GenreAffairs" : "Genre: Aktuelles Geschehen",
	"GenreAlarm" : "Genre: Alarm",
	"GenreAlarmTest" : "Genre: Alarm Test",
	"GenreAllStations" : "Genre: Alle Sender",
	"GenreChildrens" : "Genre: Kinder",
	"GenreClassics" : "Genre: Klassisch",
	"GenreCountry" : "Genre: Country",
	"GenreCulture" : "Genre: Kultur",
	"GenreDocumentary" : "Genre: Dokumentation",
	"GenreDrama" : "Genre: Schauspiel",
	"GenreEducation" : "Genre: Ausbildung",
	"GenreFinance" : "Genre: Finanzen",
	"GenreFolk" : "Genre: Folk",
	"GenreInfo" : "Genre: Information",
	"GenreJazz" : "Genre: Jazz",
	"GenreLeisure" : "Genre: Freizeit",
	"GenreLight" : "Genre: Leicht",
	"GenreList" : "Genreliste",
	"GenreMor" : "Genre: Unterhaltung",
	"GenreName" : "Genre : {genreName}",
	"GenreNational" : "Genre: National",
	"GenreNews" : "Genre: Neuigkeiten",
	"GenreOldies" : "Genre: Oldies",
	"GenreOther" : "Genre: Andere",
	"GenrePhoneIn" : "Genre: Phone-In",
	"GenrePop" : "Genre: Pop",
	"GenreReligion" : "Genre: Religion",
	"GenreRock" : "Genre: Rock",
	"GenreScience" : "Genre: Wissenschaft",
	"GenreSeek" : "Genre-Suche",
	"GenreSocial" : "Genre: Soziales",
	"GenreSport" : "Genre: Sport",
	"GenreTravel" : "Genre: Reise",
	"GenreVaried" : "Genre: Verschiedenes",
	"GenreWeather" : "Genre: Wetter",
	"HDRadio" : "HD Radio",
	"HDStations" : "HD Sender",
	"Info" : "Information ",
	"IpodError" : "iPod Fehler",
	"IpodFull" : "iPod voll",
	"Jazz" : "Jazz",
	"Leisure" : "Freizeit",
	"Light" : "Leicht",
	"ListUpdate" : "List Update",
	"MemoryFull" : "Speicher voll",
	"Mor" : "Unterhaltung ",
	"National" : "National",
	"News" : "Neuigkeiten",
	"Noresultsfound" : "Nicht gefunden",
	"Oldies" : "Oldies",
	"Other" : "Andere",
	"PartialTransfer" : "Übertragung teilweise",
	"PhoneIn" : "Anrufsendung",
	"Pop" : "Pop",
	"RegionLock" : "Regionalprogramm",
	"Religion" : "Religion",
	"Remaining" : "{numberOfTags} übrig",
	"Remove" : "Entfernen",
	"Rock" : "Rock",
	"Science" : "Wissenschaft",
	"SignalLost" : "Signal verloren",
	"Social" : "Soziales",
	"Sport" : "Sport",
	"StationList" : "Senderliste",
	"TAOff" : "TA aus",
	"TagAlreadySaved" : "Tag bereits gespeichert",
	"TagCaptured" : "Ermitteltes Tag",
	"TagMemoryFull" : "Tag-Speicher voll",
	"TagNotYetProcessed" : "Tag noch nicht bearbeitet",
	"TagSaved" : "Tag gespeichert",
	"TagSavedtoIpod" : "Tag auf iPod gespeichert",
	"TagSavedtoSystem" : "Tag auf System gespeich.",
	"TagTransferredtoiPod" : "Tag auf iPod übertragen",
	"TagsCannotBeSaved" : "Tags nicht speicherbar",
	"Tooltip_IcnUmpFMSettings" : "FM-Einstellungen",
	"TrafficAlert" : "Verkehrsmeldung (TA)",
	"TrafficAlertOff" : "Verkehrsmeldung (TA) aus",
	"TrafficAlertOn" : "Verkehrsmeldung (TA) an",
	"Travel" : "Reise",
	"UnplugAndReconnect" : "Trennen u. wiederverbind.",
	"UpdateStationList" : "Senderliste aktualisieren",
	"UpdatingStationList" : "Senderliste aktualisieren",
	"Varied" : "Verschiedenes",
	"VrHelp_AlternativeFrequencyOff" : "Alternative Frequenz aus",
	"VrHelp_AlternativeFrequencyOn" : "Alternative Frequenz an",
	"VrHelp_AutoMemory" : "Automatischer Speicher",
	"VrHelp_ChangeGenre" : "Genre ändern",
	"VrHelp_Entertainment" : "Unterhaltung",
	"VrHelp_FMSettings" : "FM-Einstellungen",
	"VrHelp_Favorites" : "Favoriten",
	"VrHelp_Frequency" : "(Frequenz)",
	"VrHelp_HDMenu" : "HD Radio-Kanäle",
	"VrHelp_RegionLockOff" : "Regionale Sicherung ausschalten",
	"VrHelp_RegionLockOn" : "Regionale Sicherung einschalten",
	"VrHelp_Scan" : "Abstimmen",
	"VrHelp_SeekDown" : "Suche nach unten",
	"VrHelp_SeekNext" : "Suche nächsten",
	"VrHelp_SeekPrevious" : "Suche vorherigen",
	"VrHelp_SeekUp" : "Suche nach oben",
	"VrHelp_SoundSettings" : "Toneinstellungen.",
	"VrHelp_StationList" : "Senderliste",
	"VrHelp_TrafficAnnouncement" : "Verkehrsmeldung (TA)",
	"VrHelp_Tune" : "Einstellen",
	"VrHelp_TuneDown" : "Einstellen nach unten",
	"VrHelp_TuneUp" : "Einstellen nach oben",
	"VrHelp_UpdateList" : "Liste aktualisieren",
	"VrHelp_iTunesTagging" : "iTunes-Tagging",
	"Weather" : "Wetter",
	"favorites_Tooltip" : "Favoriten",
	"hdChannels_Tooltip" : "HD-Kanäle",
	"rbds_Adult" : "Hits für Erwachsene",
	"rbds_Class" : "Rock-Klassiker",
	"rbds_Classical" : "Klassik",
	"rbds_College" : "Uni",
	"rbds_Country" : "Country",
	"rbds_Emergency" : "Warnung! Warnung!",
	"rbds_EmergencyTest" : "Notfalltest",
	"rbds_Foreign" : "Fremdsprachen",
	"rbds_Hablar" : "Spanischer Talk",
	"rbds_HipHop" : "Hip-Hop",
	"rbds_Info" : "Information",
	"rbds_Jazz" : "Jazz",
	"rbds_Musica" : "Spanische Musik",
	"rbds_News" : "Neuigkeiten",
	"rbds_None" : "--",
	"rbds_Nostalgia" : "Nostalgie",
	"rbds_Oldies" : "Oldies",
	"rbds_Personality" : "Personality",
	"rbds_Public" : "Öfffentlich",
	"rbds_ReligousM" : "Kirchenmusik",
	"rbds_ReligousT" : "Kirchentalk",
	"rbds_Rhythym" : "Rhythm & Blues",
	"rbds_Rock" : "Rock",
	"rbds_Soft" : "Leichte Musik",
	"rbds_SoftRB" : "Leichter R&B",
	"rbds_SoftRock" : "Soft-Rock",
	"rbds_Sports" : "Sports",
	"rbds_Talk" : "Talk",
	"rbds_Top40" : "Top 40",
	"rbds_Weather" : "Wetter",
	"rbds_genre_Adult" : "Genre: Hits für Erwachsene",
	"rbds_genre_Class" : "Genre: Rock-Klassiker",
	"rbds_genre_Classical" : "Genre: Klassik",
	"rbds_genre_College" : "Genre: Uni",
	"rbds_genre_Country" : "Genre: Country",
	"rbds_genre_Emergency" : "Genre: Warnung! Warnung!",
	"rbds_genre_EmergencyTest" : "Genre: Notfalltest",
	"rbds_genre_Foreign" : "Genre: Fremdsprachen",
	"rbds_genre_Hablar" : "Genre: Spanischer Talk",
	"rbds_genre_HipHop" : "Genre: Hip-Hop",
	"rbds_genre_Info" : "Genre: Information",
	"rbds_genre_Jazz" : "Genre: Jazz",
	"rbds_genre_Musica" : "Genre: Spanische Musik",
	"rbds_genre_News" : "Genre: Nachrichten",
	"rbds_genre_None" : "Genre: --",
	"rbds_genre_Nostalgia" : "Genre: Nostalgie",
	"rbds_genre_Oldies" : "Genre: Oldies",
	"rbds_genre_Personality" : "Genre: Personality",
	"rbds_genre_Public" : "Genre: Öffentlich",
	"rbds_genre_ReligousM" : "Genre: Kirchenmusik",
	"rbds_genre_ReligousT" : "Genre: Kirchentalk",
	"rbds_genre_Rhythym" : "Genre: Rhythm & Blues",
	"rbds_genre_Rock" : "Genre: Rock",
	"rbds_genre_Soft" : "Genre: Leichte Musik",
	"rbds_genre_SoftRB" : "Genre: Leichter R&B",
	"rbds_genre_SoftRock" : "Genre: Soft-Rock",
	"rbds_genre_Sports" : "Genre: Sport",
	"rbds_genre_Talk" : "Genre: Talk",
	"rbds_genre_Top40" : "Genre: Top 40",
	"rbds_genre_Weather" : "Genre: Wetter",
};

framework.registerAppDictLoaded("fmradio", "de_DE");