var __VrHelpPositionTable__fmradioAppDict_da_DK = {
	"AutoMemory_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"AreaPresetJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"NowPlayingEU_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_FMSettings","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_TrafficAnnouncement","VrHelp_Scan"]
	},
	"AreaPresetJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"NowPlayingNA_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_iTunesTagging","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_HDMenu","VrHelp_Scan"]
	},
	"Settings_Help" : {
		"Left" : ["VrHelp_AlternativeFrequencyOn","VrHelp_AlternativeFrequencyOff","VrHelp_RegionLockOn","VrHelp_RegionLockOff"]
	},
	"Tune_NA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"StationListJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"StationListJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"GenreSeek_Help" : {
		"Left" : ["VrHelp_SeekUp","VrHelp_SeekDown","VrHelp_ChangeGenre"]
	},
	"NowPlayingJapan_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"Tune_nonNA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"NowPlayingOther_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"AutoMemory_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	}
};

var Localization_fmradioAppDict_da_DK = {
	//"stringId" : "localString"
	"Affairs" : "Politik",
	"Alarm" : "Alarm",
	"AlarmTest" : "Alarmtest",
	"AllMemoryFull" : "Hele hukommelsen er fuld",
	"AllStations" : "Alle stationer",
	"AllTagsTransferred" : "Alle tags er overført",
	"AlternativeFrequency" : "Alternativ frekvens",
	"AreaPresetTab" : "Area Preset",
	"AutoMemoryList" : "Liste med automatisk hukommelse",
	"CannotTransferTags" : "Kan ikke overføre tags",
	"ChangeGenre" : "Skift genre",
	"ChannelListJP" : "Channel List",
	"ChannelListTab" : "Channel List",
	"Childrens" : "For børn",
	"Classics" : "Klassikere",
	"Close" : "Luk",
	"ConnectIPod" : "Tilslut iPod for tagoverfør",
	"Country" : "Country",
	"Culture" : "Kultur",
	"Documentary" : "Dokumentar",
	"Drama" : "Dramatik",
	"Education" : "Uddannelse",
	"ErrorConnection" : "Fejl: tag-overfør. til iPod",
	"FMRadio" : "FM radio",
	"FMSettings" : "FM-indstillinger",
	"Finance" : "Finans",
	"Folk" : "Folkemusik",
	"GenreAffairs" : "Genre: Politik",
	"GenreAlarm" : "Genre: Alarm",
	"GenreAlarmTest" : "Genre: Alarmtest",
	"GenreAllStations" : "Genre: alle stationer",
	"GenreChildrens" : "Genre: For børn",
	"GenreClassics" : "Genre: Klassisk",
	"GenreCountry" : "Genre: Countrymusik",
	"GenreCulture" : "Genre: Kultur",
	"GenreDocumentary" : "Genre: Dokumentar",
	"GenreDrama" : "Genre: Drama",
	"GenreEducation" : "Genre: Undervisning",
	"GenreFinance" : "Genre: Finans",
	"GenreFolk" : "Genre: Folkemusik",
	"GenreInfo" : "Genre: Information",
	"GenreJazz" : "Genre: Jazz",
	"GenreLeisure" : "Genre: Fritid",
	"GenreLight" : "Genre: Let",
	"GenreList" : "Genreliste",
	"GenreMor" : "Genre: Easy Listening",
	"GenreName" : "Genre: {genreName}",
	"GenreNational" : "Genre: National",
	"GenreNews" : "Genre: Nyheder",
	"GenreOldies" : "Genre: Oldies",
	"GenreOther" : "Genre: Andet",
	"GenrePhoneIn" : "Genre: Ring ind",
	"GenrePop" : "Genre: Pop",
	"GenreReligion" : "Genre: Religion",
	"GenreRock" : "Genre: Rock",
	"GenreScience" : "Genre: Videnskab",
	"GenreSeek" : "Genre søgning",
	"GenreSocial" : "Genre: Social",
	"GenreSport" : "Genre: Sport",
	"GenreTravel" : "Genre: Rejser",
	"GenreVaried" : "Genre: Diverse",
	"GenreWeather" : "Genre: Vejret",
	"HDRadio" : "HD radio",
	"HDStations" : "HD-stationer",
	"Info" : "Information",
	"IpodError" : "Fejl i iPod",
	"IpodFull" : " iPod fuld",
	"Jazz" : "Jazz",
	"Leisure" : "Fritid",
	"Light" : "Let",
	"ListUpdate" : "List Update",
	"MemoryFull" : "Hukommelsen er fuld",
	"Mor" : "Easy Listening ",
	"National" : "National",
	"News" : "Nyheder",
	"Noresultsfound" : "Der blev ikke fundet resultater",
	"Oldies" : "Oldies",
	"Other" : "Andet",
	"PartialTransfer" : "Delvis overførsel",
	"PhoneIn" : "Ring ind",
	"Pop" : "Pop",
	"RegionLock" : "Regionslås",
	"Religion" : "Religion",
	"Remaining" : "{numberOfTags} tilbage",
	"Remove" : "Fjern ",
	"Rock" : "Rock",
	"Science" : "Videnskab",
	"SignalLost" : "Signal mistet",
	"Social" : "Social",
	"Sport" : "Sport",
	"StationList" : "Stationsliste",
	"TAOff" : "Trafikvar. Fra",
	"TagAlreadySaved" : "Tag allerede gemt",
	"TagCaptured" : "Tag fundet",
	"TagMemoryFull" : "Tag-hukommelsen er fuld",
	"TagNotYetProcessed" : "Tag endnu ikke bearbejdet",
	"TagSaved" : "Tag gemt",
	"TagSavedtoIpod" : "Tag gemt på iPod",
	"TagSavedtoSystem" : "Tag gemt på Systemet",
	"TagTransferredtoiPod" : "Tag overført til iPod",
	"TagsCannotBeSaved" : "Tags kan ikke gemmes",
	"Tooltip_IcnUmpFMSettings" : "FM-indstillinger",
	"TrafficAlert" : "Trafikvarsel (TA)",
	"TrafficAlertOff" : "Trafikvarsel (TA) fra",
	"TrafficAlertOn" : "Trafikvarsel (TA) til",
	"Travel" : "Rejser",
	"UnplugAndReconnect" : "Tag stik ud og genforbind",
	"UpdateStationList" : "Opdatér stationsliste",
	"UpdatingStationList" : "Opdaterer stationsliste",
	"Varied" : "Blandet",
	"VrHelp_AlternativeFrequencyOff" : "Alternativ frekvens fra",
	"VrHelp_AlternativeFrequencyOn" : "Alternativ frekvens til",
	"VrHelp_AutoMemory" : "Automatisk hukommelse",
	"VrHelp_ChangeGenre" : "Skift genre",
	"VrHelp_Entertainment" : "Underholdning",
	"VrHelp_FMSettings" : "FM-indstillinger",
	"VrHelp_Favorites" : "Favoritter",
	"VrHelp_Frequency" : "(frekvens)",
	"VrHelp_HDMenu" : "HD Radio-kanaler",
	"VrHelp_RegionLockOff" : "Regional fra",
	"VrHelp_RegionLockOn" : "Regional til",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SeekDown" : "Søg ned",
	"VrHelp_SeekNext" : "Søg næste",
	"VrHelp_SeekPrevious" : "Søg forrige",
	"VrHelp_SeekUp" : "Søg op",
	"VrHelp_SoundSettings" : "LydIndstillinger",
	"VrHelp_StationList" : "Stationsliste",
	"VrHelp_TrafficAnnouncement" : "Trafikvarsel (TA)",
	"VrHelp_Tune" : "Indstil",
	"VrHelp_TuneDown" : "Frekvens ned",
	"VrHelp_TuneUp" : "Frekvens op",
	"VrHelp_UpdateList" : "Opdatér liste",
	"VrHelp_iTunesTagging" : "iTunes Tagging",
	"Weather" : "Vejr",
	"favorites_Tooltip" : "Favoritter",
	"hdChannels_Tooltip" : "HD-kanaler",
	"rbds_Adult" : "Voksen Hits",
	"rbds_Class" : "Classic Rock",
	"rbds_Classical" : "Klassisk",
	"rbds_College" : "College",
	"rbds_Country" : "Country",
	"rbds_Emergency" : "Advarsel! Advarsel!",
	"rbds_EmergencyTest" : "Emergency Test",
	"rbds_Foreign" : "Udenlandske Sprog",
	"rbds_Hablar" : "Spansk",
	"rbds_HipHop" : "Hip Hop",
	"rbds_Info" : "Information",
	"rbds_Jazz" : "Jazz",
	"rbds_Musica" : "Spansk Musik",
	"rbds_News" : "Nyheder",
	"rbds_None" : "--",
	"rbds_Nostalgia" : "Nostalgi",
	"rbds_Oldies" : "Oldies",
	"rbds_Personality" : "Personlighed",
	"rbds_Public" : "Public",
	"rbds_ReligousM" : "Religiøs Musik",
	"rbds_ReligousT" : "Religiøs",
	"rbds_Rhythym" : "Rhythm og Blues",
	"rbds_Rock" : "Rock",
	"rbds_Soft" : "Soft",
	"rbds_SoftRB" : "Soft R&B",
	"rbds_SoftRock" : "Soft Rock",
	"rbds_Sports" : "Sports",
	"rbds_Talk" : "Tale",
	"rbds_Top40" : "Top 40",
	"rbds_Weather" : "Vejr",
	"rbds_genre_Adult" : "Genre: Voksen",
	"rbds_genre_Class" : "Genre: Klassisk rock",
	"rbds_genre_Classical" : "Genre: Klassisk",
	"rbds_genre_College" : "Genre: College",
	"rbds_genre_Country" : "Genre: Country",
	"rbds_genre_Emergency" : "Genre: Advarsel! Advarsel!",
	"rbds_genre_EmergencyTest" : "Genre: Nødtest",
	"rbds_genre_Foreign" : "Genre: Udenlandske sprog",
	"rbds_genre_Hablar" : "Genre: Spansk tale",
	"rbds_genre_HipHop" : "Genre: Hip Hop",
	"rbds_genre_Info" : "Genre: Information",
	"rbds_genre_Jazz" : "Genre: Jazz",
	"rbds_genre_Musica" : "Genre: Spansk Musik",
	"rbds_genre_News" : "Genre: Nyheder",
	"rbds_genre_None" : "Genre: --",
	"rbds_genre_Nostalgia" : "Genre: Nostalgi",
	"rbds_genre_Oldies" : "Genre: Oldies",
	"rbds_genre_Personality" : "Genre: Personlighed",
	"rbds_genre_Public" : "Genre: Offentlig",
	"rbds_genre_ReligousM" : "Genre: Religiøs musik",
	"rbds_genre_ReligousT" : "Genre: Religiøs snak",
	"rbds_genre_Rhythym" : "Genre: Rytme og Blues",
	"rbds_genre_Rock" : "Genre: Rock",
	"rbds_genre_Soft" : "Genre: Rolig",
	"rbds_genre_SoftRB" : "Genre: Soft R&B",
	"rbds_genre_SoftRock" : "Genre: Blød rock",
	"rbds_genre_Sports" : "Genre: Sport",
	"rbds_genre_Talk" : "Genre: Tal",
	"rbds_genre_Top40" : "Genre: Top 40",
	"rbds_genre_Weather" : "Genre: Vejr",
};

framework.registerAppDictLoaded("fmradio", "da_DK");