var __VrHelpPositionTable__fmradioAppDict_ro_RO = {
	"AutoMemory_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"AreaPresetJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"NowPlayingEU_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_FMSettings","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_TrafficAnnouncement","VrHelp_Scan"]
	},
	"AreaPresetJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"NowPlayingNA_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_iTunesTagging","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_HDMenu","VrHelp_Scan"]
	},
	"Settings_Help" : {
		"Left" : ["VrHelp_AlternativeFrequencyOn","VrHelp_AlternativeFrequencyOff","VrHelp_RegionLockOn","VrHelp_RegionLockOff"]
	},
	"Tune_NA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"StationListJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"StationListJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"GenreSeek_Help" : {
		"Left" : ["VrHelp_SeekUp","VrHelp_SeekDown","VrHelp_ChangeGenre"]
	},
	"NowPlayingJapan_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"Tune_nonNA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"NowPlayingOther_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"AutoMemory_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	}
};

var Localization_fmradioAppDict_ro_RO = {
	//"stringId" : "localString"
	"Affairs" : "Afaceri",
	"Alarm" : "Alarmă",
	"AlarmTest" : "Test alarmă",
	"AllMemoryFull" : "Toate memoriile sunt pline",
	"AllStations" : "Toate posturile",
	"AllTagsTransferred" : "Toate etichetele transf.",
	"AlternativeFrequency" : "Frecvenţă alternativă",
	"AreaPresetTab" : "Area Preset",
	"AutoMemoryList" : "Listă automată memorie",
	"CannotTransferTags" : "Nu se pot transf. etich.",
	"ChangeGenre" : "Modificare gen",
	"ChannelListJP" : "Channel List",
	"ChannelListTab" : "Channel List",
	"Childrens" : "Copii",
	"Classics" : "Clasic",
	"Close" : "Închis",
	"ConnectIPod" : "Con. iPod pt transf. tags",
	"Country" : "Country",
	"Culture" : "Cultură",
	"Documentary" : "Documentar",
	"Drama" : "Dramă",
	"Education" : "Educaţie",
	"ErrorConnection" : "Eroare transf. tags pe iPod",
	"FMRadio" : "Radio FM",
	"FMSettings" : "Setări FM",
	"Finance" : "Finanţe",
	"Folk" : "Folk",
	"GenreAffairs" : "Gen: Afaceri",
	"GenreAlarm" : "Gen: Alarmă",
	"GenreAlarmTest" : "Gen: Test alarmă",
	"GenreAllStations" : "Gen: Toate posturile",
	"GenreChildrens" : "Gen: Copii",
	"GenreClassics" : "Gen: Clasic",
	"GenreCountry" : "Gen: Country",
	"GenreCulture" : "Gen: Cultură",
	"GenreDocumentary" : "Gen: Documentar",
	"GenreDrama" : "Gen: Dramă",
	"GenreEducation" : "Gen: Educaţie",
	"GenreFinance" : "Gen: Finanţe",
	"GenreFolk" : "Gen: Folk",
	"GenreInfo" : "Gen: Informaţie",
	"GenreJazz" : "Gen: Jazz",
	"GenreLeisure" : "Gen: Timp liber",
	"GenreLight" : "Gen: Uşor",
	"GenreList" : "Listă genuri",
	"GenreMor" : "Gen: Ascultare uşoară",
	"GenreName" : "Gen: {genreName}",
	"GenreNational" : "Gen: Naţional",
	"GenreNews" : "Gen: Ştiri",
	"GenreOldies" : "Gen: Oldies",
	"GenreOther" : "Gen: Altele",
	"GenrePhoneIn" : "Gen: Dialog cu ascultătorii",
	"GenrePop" : "Gen: Pop",
	"GenreReligion" : "Gen: Religie",
	"GenreRock" : "Gen: Rock",
	"GenreScience" : "Gen: Ştiinţific",
	"GenreSeek" : "Căutare gen",
	"GenreSocial" : "Gen: Social",
	"GenreSport" : "Gen: Sport",
	"GenreTravel" : "Gen: Călătorii",
	"GenreVaried" : "Gen: Varietăţi",
	"GenreWeather" : "Gen: Meteo",
	"HDRadio" : "HD Radio",
	"HDStations" : "Posturi HD",
	"Info" : "Informaţie",
	"IpodError" : "Eroare iPod",
	"IpodFull" : "iPod plin",
	"Jazz" : "Jazz",
	"Leisure" : "Timp liber",
	"Light" : "Lumină",
	"ListUpdate" : "List Update",
	"MemoryFull" : "Memorie plină",
	"Mor" : "Ascultare uşoară",
	"National" : "Naţional",
	"News" : "Ştiri",
	"Noresultsfound" : "Nu s-au găsit rezultate",
	"Oldies" : "Muzică veche",
	"Other" : "Altele",
	"PartialTransfer" : "Transfer Parţial",
	"PhoneIn" : "Discuţii cu ascultătorii",
	"Pop" : "Pop",
	"RegionLock" : "Blocare regiune",
	"Religion" : "Religie",
	"Remaining" : "{numberOfTags} rămase",
	"Remove" : "Eliminare",
	"Rock" : "Rock",
	"Science" : "Ştiinţific",
	"SignalLost" : "Semnal întrerupt",
	"Social" : "Social",
	"Sport" : "Sport",
	"StationList" : "Listă de posturi",
	"TAOff" : "TA oprit",
	"TagAlreadySaved" : "Etichetă deja salvată",
	"TagCaptured" : "Marcare captată",
	"TagMemoryFull" : "Memorie etichete plină",
	"TagNotYetProcessed" : "Etichetă încă neprocesată",
	"TagSaved" : "Etichetă salvată",
	"TagSavedtoIpod" : "Etichetă salvată pe iPod",
	"TagSavedtoSystem" : "Etichetă salvată în sistem",
	"TagTransferredtoiPod" : "Etichetă transf. pe iPod",
	"TagsCannotBeSaved" : "Etich. nu se pot salva",
	"Tooltip_IcnUmpFMSettings" : "Setări FM",
	"TrafficAlert" : "Informaţii trafic",
	"TrafficAlertOff" : "Informaţii trafic oprite",
	"TrafficAlertOn" : "Informaţii trafic pornite",
	"Travel" : "Călătorii",
	"UnplugAndReconnect" : "Decuplaţi şi reconectaţi",
	"UpdateStationList" : "Actualizare listă de posturi",
	"UpdatingStationList" : "Se actualizează lista de posturi",
	"Varied" : "Varietăţi",
	"VrHelp_AlternativeFrequencyOff" : "Alternative Frequency Off",
	"VrHelp_AlternativeFrequencyOn" : "Alternative Frequency On",
	"VrHelp_AutoMemory" : "Auto Memory",
	"VrHelp_ChangeGenre" : "Change Genre",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_FMSettings" : "FM Settings",
	"VrHelp_Favorites" : "Favorites",
	"VrHelp_Frequency" : "(frequency)",
	"VrHelp_HDMenu" : "HD Radio Channels",
	"VrHelp_RegionLockOff" : "Region Lock Off",
	"VrHelp_RegionLockOn" : "Region Lock On",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SeekDown" : "Seek Down",
	"VrHelp_SeekNext" : "Seek Next",
	"VrHelp_SeekPrevious" : "Seek Previous",
	"VrHelp_SeekUp" : "Seek Up",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement (TA)",
	"VrHelp_Tune" : "Tune",
	"VrHelp_TuneDown" : "Tune Down",
	"VrHelp_TuneUp" : "Tune Up",
	"VrHelp_UpdateList" : "Update List",
	"VrHelp_iTunesTagging" : "iTunes Tagging",
	"Weather" : "Meteo",
	"favorites_Tooltip" : "Favorite",
	"hdChannels_Tooltip" : "Canale HD",
	"rbds_Adult" : "Hit-uri pentru adulţi",
	"rbds_Class" : "Rock clasic",
	"rbds_Classical" : "Clasică",
	"rbds_College" : "Colegiu",
	"rbds_Country" : "Country",
	"rbds_Emergency" : "Alertă! Alertă!",
	"rbds_EmergencyTest" : "Test de urgenţă",
	"rbds_Foreign" : "Limbă Străină",
	"rbds_Hablar" : "Vorbitoare de limba Spaniolă",
	"rbds_HipHop" : "Hip Hop",
	"rbds_Info" : "Informaţii",
	"rbds_Jazz" : "Jazz",
	"rbds_Musica" : "Muzica Spaniolă",
	"rbds_News" : "Ştiri",
	"rbds_None" : "--",
	"rbds_Nostalgia" : "Nostalgie",
	"rbds_Oldies" : "Muzică veche",
	"rbds_Personality" : "Personalitate",
	"rbds_Public" : "Public",
	"rbds_ReligousM" : "Muzică Religioasă",
	"rbds_ReligousT" : "Discuţie religioasă",
	"rbds_Rhythym" : "Rhythm and Blues",
	"rbds_Rock" : "Rock",
	"rbds_Soft" : "Soft",
	"rbds_SoftRB" : "Soft R&B",
	"rbds_SoftRock" : "Rock Soft",
	"rbds_Sports" : "Sports",
	"rbds_Talk" : "Conversaţie",
	"rbds_Top40" : "Top 40",
	"rbds_Weather" : "Meteo",
	"rbds_genre_Adult" : "Gen: Hit-uri pentru adulţi",
	"rbds_genre_Class" : "Gen: Rock clasic",
	"rbds_genre_Classical" : "Gen: Clasică",
	"rbds_genre_College" : "Gen: Colegiu",
	"rbds_genre_Country" : "Gen: Country",
	"rbds_genre_Emergency" : "Gen: Alertă! Alertă!",
	"rbds_genre_EmergencyTest" : "Gen: Test de urgenţă",
	"rbds_genre_Foreign" : "Gen: Limbă Străină",
	"rbds_genre_Hablar" : "Gen: Vorbitoare de limba Spaniolă",
	"rbds_genre_HipHop" : "Gen: Hip Hop",
	"rbds_genre_Info" : "Gen: Informaţii",
	"rbds_genre_Jazz" : "Gen: Jazz",
	"rbds_genre_Musica" : "Gen: Muzica Spaniolă",
	"rbds_genre_News" : "Gen: Ştiri",
	"rbds_genre_None" : "Gen: --",
	"rbds_genre_Nostalgia" : "Gen: Nostalgie",
	"rbds_genre_Oldies" : "Gen: Muzică veche",
	"rbds_genre_Personality" : "Gen: Personalitate",
	"rbds_genre_Public" : "Gen: Public",
	"rbds_genre_ReligousM" : "Gen: Muzică Religioasă",
	"rbds_genre_ReligousT" : "Gen: Discuţie religioasă",
	"rbds_genre_Rhythym" : "Gen: Rhythm and Blues",
	"rbds_genre_Rock" : "Gen: Rock",
	"rbds_genre_Soft" : "Gen: Soft",
	"rbds_genre_SoftRB" : "Gen: Soft R&B",
	"rbds_genre_SoftRock" : "Gen: Rock Soft",
	"rbds_genre_Sports" : "Gen: Sports",
	"rbds_genre_Talk" : "Gen: Conversaţie",
	"rbds_genre_Top40" : "Gen: Top 40",
	"rbds_genre_Weather" : "Gen: Meteo",
};

framework.registerAppDictLoaded("fmradio", "ro_RO");