var __VrHelpPositionTable__fmradioAppDict_fr_CN = {
	"AutoMemory_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"AreaPresetJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"NowPlayingEU_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_FMSettings","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_TrafficAnnouncement","VrHelp_Scan"]
	},
	"AreaPresetJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"NowPlayingNA_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_iTunesTagging","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_HDMenu","VrHelp_Scan"]
	},
	"Settings_Help" : {
		"Left" : ["VrHelp_AlternativeFrequencyOn","VrHelp_AlternativeFrequencyOff","VrHelp_RegionLockOn","VrHelp_RegionLockOff"]
	},
	"Tune_NA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"StationListJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"StationListJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"GenreSeek_Help" : {
		"Left" : ["VrHelp_SeekUp","VrHelp_SeekDown","VrHelp_ChangeGenre"]
	},
	"NowPlayingJapan_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"Tune_nonNA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"NowPlayingOther_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"AutoMemory_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	}
};

var Localization_fmradioAppDict_fr_CN = {
	//"stringId" : "localString"
	"Affairs" : "Affaires",
	"Alarm" : "Alarme",
	"AlarmTest" : "Test alarme",
	"AllMemoryFull" : "Toutes mémoires pleines",
	"AllStations" : "Toutes les stations",
	"AllTagsTransferred" : "Toutes balises transférées",
	"AlternativeFrequency" : "Autre fréquence",
	"AreaPresetTab" : "",
	"AutoMemoryList" : "Liste de la Mémoire Automatique",
	"CannotTransferTags" : "Transf balises impossible",
	"ChangeGenre" : "Modifier genre",
	"ChannelListJP" : "",
	"ChannelListTab" : "",
	"Childrens" : "Enfants",
	"Classics" : "Classiques",
	"Close" : "Fermer",
	"ConnectIPod" : "Conct iPod pr transf balis",
	"Country" : "Country",
	"Culture" : "Culture",
	"Documentary" : "Documentaire",
	"Drama" : "Fiction",
	"Education" : "Education",
	"ErrorConnection" : "Err transf balise vers iPod",
	"FMRadio" : "Radio FM",
	"FMSettings" : "Réglages FM",
	"Finance" : "Finance",
	"Folk" : "Folk",
	"GenreAffairs" : "Genre:  Affaires",
	"GenreAlarm" : "Genre:  Alarme",
	"GenreAlarmTest" : "Genre: Test alarme",
	"GenreAllStations" : "Genre: Toutes les stations",
	"GenreChildrens" : "Genre:  Enfants",
	"GenreClassics" : "Genre:  Classiques",
	"GenreCountry" : "Genre:  Country",
	"GenreCulture" : "Genre:  Culture",
	"GenreDocumentary" : "Genre:  Documentaire",
	"GenreDrama" : "Genre:  Fiction",
	"GenreEducation" : "Genre:  Education",
	"GenreFinance" : "Genre:  Finance",
	"GenreFolk" : "Genre:  Folk",
	"GenreInfo" : "Genre : Information",
	"GenreJazz" : "Genre:  Jazz",
	"GenreLeisure" : "Genre:  Loisirs",
	"GenreLight" : "Genre:  Musique Légère",
	"GenreList" : "Liste de genre",
	"GenreMor" : "Genre : Musique de détente",
	"GenreName" : "Genre:  {genreName}",
	"GenreNational" : "Genre:  National",
	"GenreNews" : "Genre:  Informations",
	"GenreOldies" : "Genre:  Vieux classiques",
	"GenreOther" : "Genre:  Autre",
	"GenrePhoneIn" : "Genre:  Emission à ligne ouverte",
	"GenrePop" : "Genre:  Pop",
	"GenreReligion" : "Genre:  Religion",
	"GenreRock" : "Genre:  Rock",
	"GenreScience" : "Genre:  Sciences",
	"GenreSeek" : "Recherche de Genre",
	"GenreSocial" : "Genre:  Sociale",
	"GenreSport" : "Genre:  Sport",
	"GenreTravel" : "Genre:  Voyage",
	"GenreVaried" : "Genre:  Varié",
	"GenreWeather" : "Genre:  Météo",
	"HDRadio" : "HD Radio ",
	"HDStations" : "Stations HD Radio",
	"Info" : "Information",
	"IpodError" : "Erreur de l’iPod",
	"IpodFull" : "Mémoire iPod pleine",
	"Jazz" : "Jazz",
	"Leisure" : "Loisirs",
	"Light" : "Musique Légère",
	"ListUpdate" : "",
	"MemoryFull" : "Mémoire pleine",
	"Mor" : "Musique de détente ",
	"National" : "National",
	"News" : "Actualités",
	"Noresultsfound" : "Aucun résultat trouvé",
	"Oldies" : "Vieux classiques",
	"Other" : "Autre",
	"PartialTransfer" : "Transfert partiel",
	"PhoneIn" : "Émission à ligne ouverte",
	"Pop" : "Pop",
	"RegionLock" : "Verrouillage de la région",
	"Religion" : "Religion",
	"Remaining" : "{numberOfTags} restants",
	"Remove" : "Supprimer",
	"Rock" : "Rock",
	"Science" : "Sciences",
	"SignalLost" : "Signal perdu",
	"Social" : "Social",
	"Sport" : "Sport",
	"StationList" : "Liste des stations",
	"TAOff" : "Info circ off",
	"TagAlreadySaved" : "Balise déjà enregistrée",
	"TagCaptured" : "Balise enregistrée",
	"TagMemoryFull" : "Mémoires balises pleines",
	"TagNotYetProcessed" : "Balise non encore traitée",
	"TagSaved" : "Balise enregistrée",
	"TagSavedtoIpod" : "Balise enregistrée sur l’iPod",
	"TagSavedtoSystem" : "Balise enregistrée sur syst",
	"TagTransferredtoiPod" : "Balise transférée sur l’iPod",
	"TagsCannotBeSaved" : "Balises non enregistrables",
	"Tooltip_IcnUmpFMSettings" : "Paramètres FM",
	"TrafficAlert" : "Annonce de circulation",
	"TrafficAlertOff" : "Annonce de circulation désactivée",
	"TrafficAlertOn" : "Annonce de circulation activée",
	"Travel" : "Voyage",
	"UnplugAndReconnect" : "Débrancher et reconnecter",
	"UpdateStationList" : "Mettre à jour la liste des stations",
	"UpdatingStationList" : "Mise à jour de liste des stations",
	"Varied" : "Varié",
	"VrHelp_AlternativeFrequencyOff" : "Autre fréquence désactivé",
	"VrHelp_AlternativeFrequencyOn" : "Autre fréquence activé",
	"VrHelp_AutoMemory" : "Mémoire automatique",
	"VrHelp_ChangeGenre" : "Modifier genre",
	"VrHelp_Entertainment" : "Divertissements",
	"VrHelp_FMSettings" : "Paramètres FM",
	"VrHelp_Favorites" : "Favori",
	"VrHelp_Frequency" : "(fréquence)",
	"VrHelp_HDMenu" : "Canaux HD Radio",
	"VrHelp_RegionLockOff" : "Verrouillage régional désactivé",
	"VrHelp_RegionLockOn" : "Verrouillage régional activé",
	"VrHelp_Scan" : "Balayage",
	"VrHelp_SeekDown" : "Recherche radio suivante",
	"VrHelp_SeekNext" : "Rechercher suivant",
	"VrHelp_SeekPrevious" : "Rechercher précédent",
	"VrHelp_SeekUp" : "Recherche radio précédente",
	"VrHelp_SoundSettings" : "Paramètres audio",
	"VrHelp_StationList" : "Liste des stations",
	"VrHelp_TrafficAnnouncement" : "Annonce de circulation",
	"VrHelp_Tune" : "Syntoniser",
	"VrHelp_TuneDown" : "Syntoniser vers le bas",
	"VrHelp_TuneUp" : "Syntoniser vers le haut",
	"VrHelp_UpdateList" : "Mettre liste à jour",
	"VrHelp_iTunesTagging" : "Balisage iTunes",
	"Weather" : "Météo",
	"favorites_Tooltip" : "Favoris",
	"hdChannels_Tooltip" : "Canaux HD Radio",
	"rbds_Adult" : "Hits Adultes",
	"rbds_Class" : "Rock Classique",
	"rbds_Classical" : "Classique",
	"rbds_College" : "Collège",
	"rbds_Country" : "Country",
	"rbds_Emergency" : "Alerte! Alerte!",
	"rbds_EmergencyTest" : "Test d'Urgence",
	"rbds_Foreign" : "Langue Étrangère",
	"rbds_Hablar" : "Hablar Español",
	"rbds_HipHop" : "Hip Hop",
	"rbds_Info" : "Information",
	"rbds_Jazz" : "Jazz",
	"rbds_Musica" : "Música Español",
	"rbds_News" : "Actualités",
	"rbds_None" : "--",
	"rbds_Nostalgia" : "Nostalgie",
	"rbds_Oldies" : "Oldies",
	"rbds_Personality" : "Personnalité",
	"rbds_Public" : "Publique",
	"rbds_ReligousM" : "Musique Religieuse",
	"rbds_ReligousT" : "Discussion Religieuse",
	"rbds_Rhythym" : "Rythme et Blues",
	"rbds_Rock" : "Rock",
	"rbds_Soft" : "Musique douce",
	"rbds_SoftRB" : "R&B Doux",
	"rbds_SoftRock" : "Soft Rock",
	"rbds_Sports" : "Sports",
	"rbds_Talk" : "Parler",
	"rbds_Top40" : "Top 40",
	"rbds_Weather" : "Météo",
	"rbds_genre_Adult" : "Genre: Hits Adultes",
	"rbds_genre_Class" : "Genre: Rock Classique",
	"rbds_genre_Classical" : "Genre: Classique",
	"rbds_genre_College" : "Genre: Collège",
	"rbds_genre_Country" : "Genre: Country",
	"rbds_genre_Emergency" : "Genre: Alerte! Alerte!",
	"rbds_genre_EmergencyTest" : "Genre: Test d'Urgence",
	"rbds_genre_Foreign" : "Genre: Langue Étrangère",
	"rbds_genre_Hablar" : "Genre: Hablar Español",
	"rbds_genre_HipHop" : "Genre: Hip Hop",
	"rbds_genre_Info" : "Genre: Information",
	"rbds_genre_Jazz" : "Genre: Jazz",
	"rbds_genre_Musica" : "Genre: Música Español",
	"rbds_genre_News" : "Genre: Actualités",
	"rbds_genre_None" : "Genre: --",
	"rbds_genre_Nostalgia" : "Genre: Nostalgie",
	"rbds_genre_Oldies" : "Genre: Oldies",
	"rbds_genre_Personality" : "Genre: Personnalité",
	"rbds_genre_Public" : "Genre: Publique",
	"rbds_genre_ReligousM" : "Genre: Musique Religieuse",
	"rbds_genre_ReligousT" : "Genre: Discussion religieuse",
	"rbds_genre_Rhythym" : "Genre: Rythme and Blues",
	"rbds_genre_Rock" : "Genre: Rock",
	"rbds_genre_Soft" : "Genre: Doux",
	"rbds_genre_SoftRB" : "Genre: R&B doux",
	"rbds_genre_SoftRock" : "Genre: Soft Rock",
	"rbds_genre_Sports" : "Genre: Sports",
	"rbds_genre_Talk" : "Genre: Parler",
	"rbds_genre_Top40" : "Genre: Top 40",
	"rbds_genre_Weather" : "Genre: Météo",
};

framework.registerAppDictLoaded("fmradio", "fr_CN");