var __VrHelpPositionTable__fmradioAppDict_no_NO = {
	"AutoMemory_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"AreaPresetJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"NowPlayingEU_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_FMSettings","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_TrafficAnnouncement","VrHelp_Scan"]
	},
	"AreaPresetJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"NowPlayingNA_Help" : {
		"Right" : ["VrHelp_Tune","VrHelp_iTunesTagging","VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_HDMenu","VrHelp_Scan"]
	},
	"Settings_Help" : {
		"Left" : ["VrHelp_AlternativeFrequencyOn","VrHelp_AlternativeFrequencyOff","VrHelp_RegionLockOn","VrHelp_RegionLockOff"]
	},
	"Tune_NA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"StationListJP_Help2" : {
		"Left" : ["VrHelp_UpdateList"]
	},
	"StationListJP_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	},
	"GenreSeek_Help" : {
		"Left" : ["VrHelp_SeekUp","VrHelp_SeekDown","VrHelp_ChangeGenre"]
	},
	"NowPlayingJapan_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_StationList","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"Tune_nonNA_Help" : {
		"Left" : ["VrHelp_Frequency","VrHelp_TuneUp","VrHelp_TuneDown"]
	},
	"NowPlayingOther_Help" : {
		"Right" : ["VrHelp_SeekPrevious","VrHelp_SeekNext","VrHelp_SoundSettings"],
		"Left" : ["VrHelp_Entertainment","VrHelp_AutoMemory","VrHelp_Favorites","VrHelp_Scan","VrHelp_Tune"]
	},
	"AutoMemory_Help1" : {
		"Left" : ["VrHelp_Frequency","VrHelp_UpdateList"]
	}
};

var Localization_fmradioAppDict_no_NO = {
	//"stringId" : "localString"
	"Affairs" : "Aktuelt",
	"Alarm" : "Alarm",
	"AlarmTest" : "Alarmtest",
	"AllMemoryFull" : "Alt minne er fullt",
	"AllStations" : "Alle stasjoner",
	"AllTagsTransferred" : "Alle taggene er overført",
	"AlternativeFrequency" : "Alternativ frekvens",
	"AreaPresetTab" : "Area Preset",
	"AutoMemoryList" : "Autominneliste",
	"CannotTransferTags" : "Kan ikke overføre tagger",
	"ChangeGenre" : "Endre sjanger",
	"ChannelListJP" : "Channel List",
	"ChannelListTab" : "Channel List",
	"Childrens" : "For barn",
	"Classics" : "Klassisk",
	"Close" : "Lukk",
	"ConnectIPod" : "Kobl. til iPod for tag-overf",
	"Country" : "Country",
	"Culture" : "Kultur",
	"Documentary" : "Dokumentar",
	"Drama" : "Drama",
	"Education" : "Utdanning",
	"ErrorConnection" : "F. ved overf. av tag iPod",
	"FMRadio" : "FM radio",
	"FMSettings" : "FM-innstillinger",
	"Finance" : "Finans",
	"Folk" : "Folkemusikk",
	"GenreAffairs" : "Sjanger: Aktuelt",
	"GenreAlarm" : "Sjanger: Alarm",
	"GenreAlarmTest" : "Sjanger: Alarmtest",
	"GenreAllStations" : "Sjanger: Alle stasjoner",
	"GenreChildrens" : "Sjanger: For barn",
	"GenreClassics" : "Sjanger: Klassisk",
	"GenreCountry" : "Sjanger: Country",
	"GenreCulture" : "Sjanger: Kultur",
	"GenreDocumentary" : "Sjanger: Dokumentar",
	"GenreDrama" : "Sjanger: Drama",
	"GenreEducation" : "Sjanger: Utdanning",
	"GenreFinance" : "Sjanger: Finans",
	"GenreFolk" : "Sjanger: Folkemusikk",
	"GenreInfo" : "Sjanger: Informasjon",
	"GenreJazz" : "Sjanger: Jazz",
	"GenreLeisure" : "Sjanger: Fritid",
	"GenreLight" : "Sjanger: Lett",
	"GenreList" : "Sjangerliste",
	"GenreMor" : "Sjanger: Easy Listening",
	"GenreName" : "Sjanger: {genreName}",
	"GenreNational" : "Sjanger: Nasjonal",
	"GenreNews" : "Sjanger: Nyheter",
	"GenreOldies" : "Sjanger: Oldies",
	"GenreOther" : "Sjanger: Annet",
	"GenrePhoneIn" : "Sjanger: Telefon inn",
	"GenrePop" : "Sjanger: Pop",
	"GenreReligion" : "Sjanger: Religion",
	"GenreRock" : "Sjanger: Rock",
	"GenreScience" : "Sjanger: Vitenskap",
	"GenreSeek" : "Sjangersøk",
	"GenreSocial" : "Sjanger: Sosialt",
	"GenreSport" : "Sjanger: Sport",
	"GenreTravel" : "Sjanger: Reise",
	"GenreVaried" : "Sjanger: Diverse",
	"GenreWeather" : "Sjanger: Vær",
	"HDRadio" : "HD Radio",
	"HDStations" : "HD-stasjoner",
	"Info" : "Informasjon ",
	"IpodError" : "iPod-feil",
	"IpodFull" : "iPod er full",
	"Jazz" : "Jazz",
	"Leisure" : "Fritid",
	"Light" : "Lett",
	"ListUpdate" : "List Update",
	"MemoryFull" : "Minnet er fullt",
	"Mor" : "Easy Listening ",
	"National" : "Nasjonal",
	"News" : "Nyheter",
	"Noresultsfound" : "Fant ingen resultater",
	"Oldies" : "Oldies",
	"Other" : "Annet",
	"PartialTransfer" : "Delvis overføring",
	"PhoneIn" : "Telefon inn",
	"Pop" : "Pop",
	"RegionLock" : "Regionlås",
	"Religion" : "Religion",
	"Remaining" : "{numberOfTags} gjenstår",
	"Remove" : "Fjern",
	"Rock" : "Rock",
	"Science" : "Vitenskap",
	"SignalLost" : "Tapt signal",
	"Social" : "Sosialt",
	"Sport" : "Sport",
	"StationList" : "Stasjonsliste",
	"TAOff" : "TA av",
	"TagAlreadySaved" : "Taggen er allerede lagret",
	"TagCaptured" : "Tagg opptak",
	"TagMemoryFull" : "Tagg-minnet er fullt",
	"TagNotYetProcessed" : "Tag. er ikke behan. Ennå",
	"TagSaved" : "Taggen er lagret",
	"TagSavedtoIpod" : "Taggen er lagret på iPod",
	"TagSavedtoSystem" : "Taggen er lagret på syst.",
	"TagTransferredtoiPod" : "Taggen overført til iPod",
	"TagsCannotBeSaved" : "Taggene kan ikke lagres",
	"Tooltip_IcnUmpFMSettings" : "FM-innstillinger",
	"TrafficAlert" : "Trafikkmelding (TA)",
	"TrafficAlertOff" : "Trafikkmelding (TA) av",
	"TrafficAlertOn" : "Trafikkmelding (TA) på",
	"Travel" : "Fjæringslengde",
	"UnplugAndReconnect" : "Koble fra og til på nytt",
	"UpdateStationList" : "Oppdater stasjonsliste",
	"UpdatingStationList" : "Oppdaterer stasjonsliste",
	"Varied" : "Diverse",
	"VrHelp_AlternativeFrequencyOff" : "Alternative Frequency Off",
	"VrHelp_AlternativeFrequencyOn" : "Alternative Frequency On",
	"VrHelp_AutoMemory" : "Auto Memory",
	"VrHelp_ChangeGenre" : "Change Genre",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_FMSettings" : "FM Settings",
	"VrHelp_Favorites" : "Favorites",
	"VrHelp_Frequency" : "(frequency)",
	"VrHelp_HDMenu" : "HD Radio Channels",
	"VrHelp_RegionLockOff" : "Region Lock Off",
	"VrHelp_RegionLockOn" : "Region Lock On",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SeekDown" : "Seek Down",
	"VrHelp_SeekNext" : "Seek Next",
	"VrHelp_SeekPrevious" : "Seek Previous",
	"VrHelp_SeekUp" : "Seek Up",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement (TA)",
	"VrHelp_Tune" : "Tune",
	"VrHelp_TuneDown" : "Tune Down",
	"VrHelp_TuneUp" : "Tune Up",
	"VrHelp_UpdateList" : "Update List",
	"VrHelp_iTunesTagging" : "iTunes Tagging",
	"Weather" : "Vær",
	"favorites_Tooltip" : "Favoritter",
	"hdChannels_Tooltip" : "HD-kanaler",
	"rbds_Adult" : "Adult hits",
	"rbds_Class" : "Klassisk Rock",
	"rbds_Classical" : "Klassisk",
	"rbds_College" : "Høyskole",
	"rbds_Country" : "Country",
	"rbds_Emergency" : "Varsle! Varsle!",
	"rbds_EmergencyTest" : "Test, nødsituasjon",
	"rbds_Foreign" : "Fremmedspråk",
	"rbds_Hablar" : "Snakker Spansk",
	"rbds_HipHop" : "Hip Hop",
	"rbds_Info" : "Informasjon",
	"rbds_Jazz" : "Jazz",
	"rbds_Musica" : "Spansk Musikk",
	"rbds_News" : "Nyheter",
	"rbds_None" : "--",
	"rbds_Nostalgia" : "Nostalgi",
	"rbds_Oldies" : "Oldies",
	"rbds_Personality" : "Personlighet",
	"rbds_Public" : "Public",
	"rbds_ReligousM" : "Religiøs Musikk",
	"rbds_ReligousT" : "Religiøs Diskusjon",
	"rbds_Rhythym" : "Rhythm and Blues",
	"rbds_Rock" : "Rock",
	"rbds_Soft" : "Soft",
	"rbds_SoftRB" : "Soft R&B",
	"rbds_SoftRock" : "Soft rock",
	"rbds_Sports" : "Sports",
	"rbds_Talk" : "Diskusjon",
	"rbds_Top40" : "Top 40",
	"rbds_Weather" : "Vær",
	"rbds_genre_Adult" : "Sjanger: Adult hits",
	"rbds_genre_Class" : "Sjanger: Klassisk Rock",
	"rbds_genre_Classical" : "Sjanger: Klassisk",
	"rbds_genre_College" : "Sjanger: Høyskole",
	"rbds_genre_Country" : "Sjanger: Country",
	"rbds_genre_Emergency" : "Sjanger: Varsle! Varsle!",
	"rbds_genre_EmergencyTest" : "Sjanger: Test, nødsituasjon",
	"rbds_genre_Foreign" : "Sjanger: Fremmedspråk",
	"rbds_genre_Hablar" : "Sjanger: Snakker Spansk",
	"rbds_genre_HipHop" : "Sjanger: Hip Hop",
	"rbds_genre_Info" : "Sjanger: Informasjon",
	"rbds_genre_Jazz" : "Sjanger: Jazz",
	"rbds_genre_Musica" : "Sjanger: Spansk Musikk",
	"rbds_genre_News" : "Sjanger: Nyheter",
	"rbds_genre_None" : "Sjanger: --",
	"rbds_genre_Nostalgia" : "Sjanger: Nostalgi",
	"rbds_genre_Oldies" : "Sjanger: Oldies",
	"rbds_genre_Personality" : "Sjanger: Personlighet",
	"rbds_genre_Public" : "Sjanger: Public",
	"rbds_genre_ReligousM" : "Sjanger: Religiøs Musikk",
	"rbds_genre_ReligousT" : "Sjanger: Religiøs Diskusjon",
	"rbds_genre_Rhythym" : "Sjanger: Rhythm and Blues",
	"rbds_genre_Rock" : "Sjanger: Rock",
	"rbds_genre_Soft" : "Sjanger: Soft",
	"rbds_genre_SoftRB" : "Sjanger: Soft R&B",
	"rbds_genre_SoftRock" : "Sjanger: Soft rock",
	"rbds_genre_Sports" : "Sjanger: Sports",
	"rbds_genre_Talk" : "Sjanger: Diskusjon",
	"rbds_genre_Top40" : "Sjanger: Top 40",
	"rbds_genre_Weather" : "Sjanger: Vær",
};

framework.registerAppDictLoaded("fmradio", "no_NO");