var Localization_xmaudioAppDict_en_US = {
	//"stringId" : "localString"
	"AboutSmartFavorties" : "SXM Favorites 1-10 are SXM Smart Favorites.  If saved as a Smart Favorite, content will be buffered for 30 minutes and you may add the Smart Favorite to a TuneMix Channel. ",
	"AboutSportsFlash" : "SportsFlash allows you to keep up with your selected team's key plays even while you are listening to other audio.  Access SportsFlash through SXM settings. ",
	"AboutTWNow" : "Traffic and Weather Now provides audio alerts of the most recently broadcast traffic and weather reports for a selected city. Traffic and Weather Now setup is accessible through SXM Settings.",
	"AboutTuneMix" : "In TuneMix, buffered content from each Smart Favorite saved in a TuneMix Channel will be played. Access TuneMix Channels through a tab in Channel List. ",
	"AboutTuneScan" : "When user initiates Tune scan, a sample is played from the buffered content in each Smart Favorite. Tune Scan acts in place of Channel Scan and can be turned On and Off through SXM Settings.",
	"Add" : "Add",
	"AddAsSmartFavorite" : "Add {ChannelName} as a Smart Favorite or Normal Favorite",
	"AddRemoveTeams" : "Add/Remove Teams",
	"AddSmartFavoriteCnfm" : "Are you sure you want to add {FavoriteChannelName} to Smart Favorites?",
	"AddToTuneMix" : "Add to TuneMix Channel.",
	"AllChannels" : "All Channels",
	"AtLeastTwoFavorites" : "At least two SXM Favorites are required to create a TuneMix channel.",
	"AtLeastTwoFavoritestoCreate" : "Select at least two SXM Favorites to create a TuneMix Channel.",
	"AtLeastTwoFavoritestoSave" : "Select at least two SXM Favorites to save to this TuneMix Channel.",
	"BufferContent" : "This will remove buffered content from {Favorite1}. ",
	"CallXM" : "Call SiriusXM",
	"ChangeCategory" : "Change Category",
	"ChannelDescriptionService" : "Channel Description Service",
	"ChannelList" : "Channel List",
	"ChannelLocked" : "Channel Locked",
	"ChannelScanToolTip" : "Channel Scan",
	"ChannelsUnlocked" : "Channels unlocked for session.",
	"CheckXMAntenna" : "Check SXM Antenna",
	"CheckXMTuner" : "Check SXM Tuner",
	"CitySelection" : "City Selection",
	"ContinueListening" : "Continue Listening",
	"CreateNewTuneMixChannel" : "Create New TuneMix Channel",
	"DeleteSmartFavoriteCnfm" : "Are you sure you want to delete {SmartFavoriteChannelName} from Favorites?",
	"DeleteSmartFavoriteCnfm_2" : "Are you sure you want to delete {SmartFavoriteChannelName} from Smart Favorites? It will be retained as a normal favorite.",
	"DeleteTuneMixChannelCnfm" : "Are you sure you want to delete {TuneMixChannelName}?",
	"DisableAlerts" : "Disable Alerts",
	"Dismiss" : "Dismiss",
	"EditPINCode" : "Edit PIN Code",
	"EditSmartFavorite" : "Edit Smart Favorite",
	"EditTuneMixChannel" : "Edit TuneMix Channel",
	"EnterDefaultPIN" : "Enter Default PIN",
	"EnterPIN" : "Enter PIN",
	"EntertainmentMenu" : "Entertainment Menu",
	"EveryOtherReport" : "Every Other Report",
	"EveryReport" : "Every Report",
	"ExitTuneMix" : "Exit TuneMix",
	"Favorite" : "Favorite",
	"FeaturedFavoriteSelectionUpdated" : "Featured favorite selection updated",
	"FeaturedFavorites" : "Featured Favorites",
	"FlashFrequency" : "Flash Frequency",
	"LastAlert" : "Last Alert",
	"Listen" : "Listen  ",
	"ListenNow" : "Listen Now",
	"ListenNowToolTip" : "Listen Now",
	"LoadingSXM" : "Loading SXM",
	"LoadingXM" : "Loading SXM",
	"LockCurrentChannel" : "Lock Current Channel",
	"MLB" : "MLB",
	"Max50TeamsAllowed" : "Maximum of 50 Teams Allowed",
	"Move" : "Move  ",
	"MoveConfirmationAffected" : "This will remove buffered content from {Favorite 1} and impact TuneMix Channels.",
	"MoveFavorite" : "Move favorite",
	"NCAA(Football)" : "NCAA (Football)",
	"NFL" : "NFL",
	"NHL" : "NHL",
	"NearestCity" : "Nearest City",
	"NextAlert" : "Next Alert",
	"NextChannelToolTip" : "Next Channel",
	"NextToolTip" : "Next  ",
	"NextTrackToolTip" : "Next Track",
	"NoSaveTuneMixChannels" : "No Saved TuneMix Channels",
	"NoXMSignal" : "No SXM Signal",
	"None" : "None",
	"Only10TuneMixAllowed" : "Only 10 TuneMix Channels are allowed.",
	"OnlyFirstReport" : "Only First Report After Vehicle Start",
	"OnlyFirstReportInGame" : "Only First Report in Game",
	"OnlyTenAvailable" : "Only 10 TuneMix Channels are available. ",
	"PINCorrectCnfm" : "Is this correct?",
	"PINReset" : "PIN Reset",
	"PINSet" : "PIN Set",
	"ParentalLock" : "Parental Lock  ",
	"ParentalLockPinSettings" : "Parental Lock Pin Settings",
	"PlayingAlert" : "CH. {ChannelNumber} Playing Alert",
	"PreviousChannelToolTip" : "Previous Channel",
	"PreviousToolTip" : "Previous",
	"PreviousTrackToolTip" : "Previous Track",
	"RadioID" : "Radio ID: {Radio Serial Number}",
	"RemoveSmartFavorite" : "Remove Smart Favorite",
	"RemoveTuneMixChannel" : "Remove TuneMix Channel",
	"RenameTuneMixChannel" : "Rename TuneMix Channel",
	"RenewSubscription" : "Renew your subscription by calling SXM at {XMPhoneNumber}. ",
	"ReplaceFavorite" : "Are you sure you want to replace {Favorite1} with {Favorite2} ?",
	"ReplayAlert" : "Replay Alert",
	"ReplayMemoryAlmostFull" : "Replay Memory Almost Full.  Oldest buffered content will be lost. ",
	"ReplayMemoryFull" : "Replay Memory Full.  Oldest buffered content will be lost. ",
	"ReportFrequency" : "Report Frequency",
	"ResetPINCode" : "Reset PIN Code",
	"ReturnToPrevious" : "Return to Previous",
	"SXMSettingsToolTip" : "SXM Settings",
	"SXMTMChannels" : "SXM TuneMix Channels",
	"SelectAFavoriteTeam" : "Select a Favorite Team",
	"SelectASport" : "Select a Sport",
	"SelectCHannelsToAdd" : "Select Channels to add to TuneMix.",
	"SelectCity" : "Select a City",
	"SelectOptionsIcon" : "Select options icon below to unlock channel/session. ",
	"SelectPosition" : "Select Position",
	"SelectPriorityPosition" : "Select Priority Position",
	"SelectSettings" : "Select Settings icon below to unlock channel/session.",
	"SelectStationToEdit" : "Select Channel to Edit",
	"SelectStationToRemove" : "Select Channel to Remove",
	"SelectStationsForTuneMix" : "Select Channels for TuneMix",
	"SelectStationsToAdd" : "Select Channel to Add",
	"SelectTuneMixChannelToDelete" : "Select TuneMix Channel to Delete",
	"SelectTuneMixChannelToEdit" : "Select TuneMix Channel to Edit",
	"SelectTuneMixToRemove" : "Select TuneMix Channel to Remove",
	"SelectTuneMixToRename" : "Select TuneMix Channel to Rename",
	"SelectTwoSXMFavoritesToAdd" : "Select at least two SXM Favorites to add to this TuneMix Channel.  Would you like to add SXM Favorites to {TuneMixChannelName}?",
	"Serial" : "Serial No: {XMSerialNumber} ",
	"SessionLock" : "Session Lock",
	"SetNewPIN" : "Set New PIN",
	"SmartFavorite" : "Smart Favorite ",
	"SmartFavoriteOptions" : "Smart Favorite Options",
	"SmartFavorites" : "Smart Favorites",
	"SportSelection" : "Sport Selection",
	"SportsFlash" : "SportsFlash  ",
	"SportsFlashAvailable" : "SportsFlash {Alert Team} Available",
	"SportsFlashPriority" : "SportsFlash Priority",
	"SportsFlashSetup" : "SportsFlash Setup",
	"StopChannelScanToolTip" : "Stop Channel Scan",
	"StopTuneScanToolTip" : "Stop Tune Scan",
	"SubscriptionExpired" : "Your SiriusXM subscription has expired.  Renew your subscription by calling SXM at {XMPhoneNumber}.",
	"SubscriptionExpires" : "Your SiriusXM subscription expires in {Days} days.",
	"TWNowSetup" : "Traffic and Weather Alert",
	"TeamPriority" : "Sports Team Priority",
	"Traffic&WeatherNow" : "Traffic and Weather Now",
	"Traffic&WeatherNowSetup" : "Traffic and Weather Now Setup",
	"TrafficAndWeatherAvailable" : "Traffic and Weather for {alert city} available. ",
	"TryAgain" : "Please try again.",
	"TuneMixChannelCreated" : "{TuneMixChannelName} created",
	"TuneMixChannelOptions" : "TuneMix Channel Options",
	"TuneMixChannels" : "TuneMix",
	"TuneMixChannelsList" : "TuneMix Channels List",
	"TuneMixDeleted" : "TuneMix {TuneMixName} deleted",
	"TuneMixEditOptions" : "TuneMix Edit Options",
	"TuneScan" : "Tune Scan",
	"TuneScanToolTip" : "Tune Scan",
	"TuneStart" : "Tune Start",
	"TurnAlertsOff" : "Turn Alerts Off",
	"UnableToSave" : "Unable to Save.  Smart Favorites Full.",
	"WrongPIN" : "Wrong PIN.    ",
	"XM" : "SXM",
	"XMChannelNotAuthorized" : "SXM Channel Not Authorized",
	"XMChannelNotAvailable" : "SXM Channel Not Available",
	"XMChannelOffAir" : "SXM Channel Off Air",
	"XMError" : "Unable to Reconnect to SXM Radio",
	"XMLoading" : "Reconnecting to SXM Radio",
	"XMSettings" : "Settings",
	"iTunesTagging" : "iTunes Tagging",
};

framework.registerAppDictLoaded("xmaudio", "en_US");