var Localization_xmaudioAppDict_fr_CN = {
	//"stringId" : "localString"
	"AboutSmartFavorties" : "Les favoris SXM 1 à 10 sont des favoris SXM Smart.  En cas de sauvegarde en tant que favori Smart, le contenu sera mis en mémoire tampon pendant 30 minutes et vous pouvez ajouter le favori Smart à la chaîne TuneMix. ",
	"AboutSportsFlash" : "SportsFlash vous permet d’être au courant des jeux importants de votre équipe sélectionnée, même lorsque vous écoutez d’autre contenu.  Accéder à SportsFlash depuis les paramètres SXM. ",
	"AboutTWNow" : "Les options Trafic et Météo actuelle fournissent des alertes audio pour les plus récentes émissions concernant la circulation routière et la météo pour la ville sélectionnée. La configuration de Trafic et Météo actuelle est accessible dans les paramètres SXM.",
	"AboutTuneMix" : "Dans TuneMix, le contenu en mémoire tampon de chaque favori Smart sauvegardé dans une chaîne TuneMix sera joué.  Accéder aux TuneMix depuis un onglet dans la liste des chaînes. ",
	"AboutTuneScan" : "Lorsque l'utilisateur lance un balayage du réglage, un échantillon de la mémoire tampon est lu dans chaque Favori intelligent. Le balayage du réglage remplace le balayage des canaux et peut être allumé ou éteint à travers les paramètres SXM.",
	"Add" : "Ajouter",
	"AddAsSmartFavorite" : "Ajouter {ChannelName} en tant que favori intelligent ou favori ordinaire",
	"AddRemoveTeams" : " Ajouter/Enlever des équipes",
	"AddSmartFavoriteCnfm" : "Êtes-vous sûr de vouloir ajouter {FavoriteChannelName} aux favoris intelligents?",
	"AddToTuneMix" : "Ajouter à la chaîne TuneMix.",
	"AllChannels" : "Tous les canaux",
	"AtLeastTwoFavorites" : "Au moins deux favoris SXM sont nécessaires pour créer une chaîne TuneMix.",
	"AtLeastTwoFavoritestoCreate" : "Sélectionner au moins deux favoris SXM pour créer une chaîne TuneMix.",
	"AtLeastTwoFavoritestoSave" : "Sélectionner au moins deux favoris SXM à sauvegarder dans cette chaîne TuneMix.",
	"BufferContent" : "Ceci enlèvera le contenu tamponné de {Favorite1}. ",
	"CallXM" : "Téléphoner à  SXM",
	"ChangeCategory" : "Changer la catégorie",
	"ChannelDescriptionService" : "Service de description de la chaîne",
	"ChannelList" : "Liste des chaînes",
	"ChannelLocked" : "Chaîne verrouillée",
	"ChannelScanToolTip" : "Balayage des chaînes ",
	"ChannelsUnlocked" : "Canaux déverrouillés pour la session",
	"CheckXMAntenna" : "Vérifier l’antenne SXM",
	"CheckXMTuner" : "Vérifier le tuner SXM",
	"CitySelection" : "Sélection de la ville",
	"ContinueListening" : "Continuer à écouter",
	"CreateNewTuneMixChannel" : "Créer une nouvelle chaîne TuneMix",
	"DeleteSmartFavoriteCnfm" : "Êtes-vous sûr de vouloir supprimer {SmartFavoriteChannelName}?",
	"DeleteSmartFavoriteCnfm_2" : "Êtes-vous sûr de vouloir supprimer {SmartFavoriteChannelName} des favoris intelligents? Il sera conservé en tant que favori intelligent.",
	"DeleteTuneMixChannelCnfm" : "Êtes-vous sûr de vouloir supprimer {TuneMixChannelName}?",
	"DisableAlerts" : "Désactiver ",
	"Dismiss" : "Exclure",
	"EditPINCode" : "Modifier le code PIN",
	"EditSmartFavorite" : "Éditer le favori intelligent",
	"EditTuneMixChannel" : "Éditer la chaîne TuneMix",
	"EnterDefaultPIN" : "Entrer le NIP par défaut",
	"EnterPIN" : "Modifier le code PIN",
	"EntertainmentMenu" : "Menu des divertissements",
	"EveryOtherReport" : "Sauter un reportage",
	"EveryReport" : "Tous les reportages",
	"ExitTuneMix" : "Sortir de TuneMix",
	"Favorite" : "Favori",
	"FeaturedFavoriteSelectionUpdated" : "Sélection des favoris mise à jour",
	"FeaturedFavorites" : "Favoris",
	"FlashFrequency" : "Fréquence des nouvelles ",
	"LastAlert" : "Dernière alerte",
	"Listen" : "Écouter  ",
	"ListenNow" : "Écouter maintenant",
	"ListenNowToolTip" : "Écouter maintenant",
	"LoadingSXM" : "En cours de chargement d’SXM",
	"LoadingXM" : "En cours de chargement d’SXM",
	"LockCurrentChannel" : "Verrouiller la chaîne actuelle",
	"MLB" : "LMB",
	"Max50TeamsAllowed" : "Maximum autorisé de 50 équipes",
	"Move" : "Déplacer  ",
	"MoveConfirmationAffected" : "Cette commande efface le contenu en mémoire tampon de {Favorite 1} et aura un impact sur les canaux TuneMix. ",
	"MoveFavorite" : "Déplacer le favori",
	"NCAA(Football)" : "NCAA (football)",
	"NFL" : "LNF",
	"NHL" : "LNH",
	"NearestCity" : "Ville la plus proche",
	"NextAlert" : "Alerte suivante",
	"NextChannelToolTip" : "Canal suivant ",
	"NextToolTip" : "Suivant  ",
	"NextTrackToolTip" : "Piste suivante ",
	"NoSaveTuneMixChannels" : "Aucune chaîne TuneMix sauvegardée",
	"NoXMSignal" : "Pas de signal SXM",
	"None" : "--",
	"Only10TuneMixAllowed" : "Possibilité de 10 chaînes TuneMix seulement.",
	"OnlyFirstReport" : "Seulement le premier reportage après le démarrage du véhicule",
	"OnlyFirstReportInGame" : "Seulement le premier reportage du match",
	"OnlyTenAvailable" : "Seulement 10 chaînes TuneMix sont offertes. ",
	"PINCorrectCnfm" : "Est-ce exact ?",
	"PINReset" : "Réinitialisation du NIP",
	"PINSet" : "PIN configuré",
	"ParentalLock" : "Entrer le NIP par défaut  ",
	"ParentalLockPinSettings" : "Configuration du NIP du contrôle parental",
	"PlayingAlert" : "CH. {ChannelNumber} jouer l'alerte",
	"PreviousChannelToolTip" : "Canal précédent ",
	"PreviousToolTip" : "Précédent",
	"PreviousTrackToolTip" : "Piste précédente ",
	"RadioID" : "ID Radio: {Radio Serial Number}",
	"RemoveSmartFavorite" : "Supprimer le favori intelligent",
	"RemoveTuneMixChannel" : "Supprimer la chaîne TuneMix",
	"RenameTuneMixChannel" : "Renommer la chaîne TuneMix",
	"RenewSubscription" : "Renouveller votre abonnement en appellant au {XMPhoneNumber}. ",
	"ReplaceFavorite" : "Are you sure you want to replace {Favorite1} with {Favorite2} ?",
	"ReplayAlert" : "Lire l'alerte de nouveau ",
	"ReplayMemoryAlmostFull" : "Mémoire de reprise de la lecture presque pleine.  Les contenus les plus anciens du tampon seront perdus. ",
	"ReplayMemoryFull" : "Mémoire de reprise de la lecture pleine.  Les contenus les plus anciens mis en tampon seront perdus. ",
	"ReportFrequency" : "Fréquence de reportage",
	"ResetPINCode" : "Configurer le nouveau NIP",
	"ReturnToPrevious" : "Revenir au précédent",
	"SXMSettingsToolTip" : "Paramètres SXM ",
	"SXMTMChannels" : "Chaînes TuneMix SXM",
	"SelectAFavoriteTeam" : "Sélectionner une équipe favorite",
	"SelectASport" : "Sélectionner un sport",
	"SelectCHannelsToAdd" : "Sélectionner les chaînes à ajouter à TuneMix",
	"SelectCity" : "Sélectionner une ville",
	"SelectOptionsIcon" : "Sélectionner l'icône options ci-dessous pour déverrouiller le poste/la session. ",
	"SelectPosition" : "Sélectionner position",
	"SelectPriorityPosition" : "Sélectionner la position prioritaire",
	"SelectSettings" : "Sélectionnez l'icône Paramètres ci-dessous pour déverrouiller la chaîne ou la session.",
	"SelectStationToEdit" : "Sélectionner la chaîne à éditer",
	"SelectStationToRemove" : "Sélectionner la chaîne à supprimer ",
	"SelectStationsForTuneMix" : "Sélectionner la chaîne pour TuneMix ",
	"SelectStationsToAdd" : " Sélectionner les chaînes à ajouter.",
	"SelectTuneMixChannelToDelete" : "Sélectionner la chaîne TuneMix à supprimer",
	"SelectTuneMixChannelToEdit" : "Sélectionner la chaîne TuneMix à éditer",
	"SelectTuneMixToRemove" : "Sélectionner la chaîne TuneMix à supprimer ",
	"SelectTuneMixToRename" : "Sélectionner la chaîne TuneMix à renommer ",
	"SelectTwoSXMFavoritesToAdd" : "Sélectionner au moins deux favoris SXM à ajouter à cette chaîne TuneMix.  Souhaitez-vous ajouter des favoris SXM à {TuneMixChannelName}?",
	"Serial" : "No de série : {XMSerialNumber} ",
	"SessionLock" : "Verrouillage de session",
	"SetNewPIN" : "Config. le nouv. NIP",
	"SmartFavorite" : "Favori intelligent ",
	"SmartFavoriteOptions" : "Options des favoris intelligents",
	"SmartFavorites" : "Favoris intelligents",
	"SportSelection" : "Sélection du sport",
	"SportsFlash" : "SportsFlash  ",
	"SportsFlashAvailable" : "SportsFlash {Alert Team} disponible",
	"SportsFlashPriority" : "Priorité aux SportsFlash",
	"SportsFlashSetup" : "Configuration des SportsFlash",
	"StopChannelScanToolTip" : "Arrêter le balayage des chaînes ",
	"StopTuneScanToolTip" : "Arrêter le balayage du réglage ",
	"SubscriptionExpired" : "Votre abonnement SiriusXM a expiré.  Renouveller votre abonnement en appellant au {XMPhoneNumber}.",
	"SubscriptionExpires" : "Votre abonnement SiriusXM expirera dans {Days} jours.",
	"TWNowSetup" : " Alertes Trafic et Météo ",
	"TeamPriority" : "Priorité des équipes ",
	"Traffic&WeatherNow" : "Circulation et météo maintenant",
	"Traffic&WeatherNowSetup" : "Configuration de Circulation et météo maintenant",
	"TrafficAndWeatherAvailable" : "Circulation et météo pour {alert city} disponible. ",
	"TryAgain" : "Veuillez réessayer.",
	"TuneMixChannelCreated" : "{TuneMixChannelName} créé",
	"TuneMixChannelOptions" : "Options de chaînes TuneMix",
	"TuneMixChannels" : "TuneMix",
	"TuneMixChannelsList" : "Liste des chaînes TuneMix",
	"TuneMixDeleted" : " TuneMix {TuneMixName} effacé ",
	"TuneMixEditOptions" : "Options d’édition de TuneMix",
	"TuneScan" : "Balayage du réglage ",
	"TuneScanToolTip" : "Balayage du réglage ",
	"TuneStart" : "Fonction TuneStart",
	"TurnAlertsOff" : "Désactiver les alertes",
	"UnableToSave" : "Sauvegarde impossible.  Favoris intelligents au maximum de la capacité.",
	"WrongPIN" : "NIP incorrect.    ",
	"XM" : "SiriusXM",
	"XMChannelNotAuthorized" : "Canal SXM non autorisé",
	"XMChannelNotAvailable" : "Canal SXM non disponible",
	"XMChannelOffAir" : "Le canal SXM a cessé d’émettre",
	"XMError" : "Impossible de se reconnecter à la radio SXM",
	"XMLoading" : "Reconnexion à la radio SXM",
	"XMSettings" : "Paramètres SXM",
	"iTunesTagging" : "Balisage iTunes",
};

framework.registerAppDictLoaded("xmaudio", "fr_CN");