var Localization_xmaudioAppDict_es_MX = {
	//"stringId" : "localString"
	"AboutSmartFavorties" : "Los Favoritos 1-10 SXM son Favoritos SXM automáticos.  Si lo guardó como Favorito automático, el contenido se almacenará durante 30 minutos y podrá agregar el Favorito automático a un canal de TuneMix. ",
	"AboutSportsFlash" : "SportsFlash le permite mantenerse actualizado con las jugadas clave de su equipo seleccionado, incluso cuando está escuchando otro audio.  Acceda a SportsFlash a través de la configuración de SXM. ",
	"AboutTWNow" : "Traffic and Weather Now genera alertas de audio de los informes de más reciente emisión sobre el tránsito y el clima de la ciudad seleccionada. Puede acceder a los ajustes de Traffic and Weather Now a través de las configuraciones de SXM.",
	"AboutTuneMix" : "En TuneMix, el contenido almacenado de cada Favorito automático guardado en un canal de TuneMix será reproducido. Acceda a los canales de la TuneMix a través de la pestaña en la Lista de canales. ",
	"AboutTuneScan" : "Cuando el usuario inicia una exploración de sintonización, se reproduce una muestra del contenido almacenado en cada favorito del dispositivo inteligente. La exploración de sintonización actúa en lugar de la exploración de canales y puede activarse y desactivarse a través de las configuraciones de SXM.",
	"Add" : "Añadir",
	"AddAsSmartFavorite" : "Añadir {ChannelName} como un Favorito inteligente o un Favorito normal",
	"AddRemoveTeams" : "Agregar/Eliminar equipos ",
	"AddSmartFavoriteCnfm" : "¿Está seguro que desea añadir {FavoriteChannelName} a Favoritos inteligentes?",
	"AddToTuneMix" : "Agregar al canal de TuneMix.",
	"AllChannels" : "Todos los canales",
	"AtLeastTwoFavorites" : "Se requieren al menos dos Favoritos SXM para crear un canal de TuneMix.",
	"AtLeastTwoFavoritestoCreate" : "Seleccione al menos dos Favoritos SXM para crear un canal de TuneMix.",
	"AtLeastTwoFavoritestoSave" : "Seleccione al menos dos Favoritos SXM para guardarlos en este canal de TuneMix.",
	"BufferContent" : "Esto eliminará el contenido en búfer de {Favorite1}. ",
	"CallXM" : "Llamar a SXM",
	"ChangeCategory" : "Cambiar categoría",
	"ChannelDescriptionService" : "Servicio de descripción de canales",
	"ChannelList" : "Lista de canales",
	"ChannelLocked" : "Canal bloqueado",
	"ChannelScanToolTip" : "Exploración de canales ",
	"ChannelsUnlocked" : "Canales desbloqueados para la sesión",
	"CheckXMAntenna" : "Verificar Antena SXM",
	"CheckXMTuner" : "Verificar Sintonizador SXM",
	"CitySelection" : "Selección de ciudad",
	"ContinueListening" : "Continuar escuchando",
	"CreateNewTuneMixChannel" : "Crear nuevo canal de TuneMix",
	"DeleteSmartFavoriteCnfm" : "¿Está seguro que desea eliminar {SmartFavoriteChannelName} de Favoritos?",
	"DeleteSmartFavoriteCnfm_2" : "¿Está seguro que dese eliminar {SmartFavoriteChannelName} de Favoritos inteligentes? Se mantendrá como un favorito normal.",
	"DeleteTuneMixChannelCnfm" : "¿Está seguro que desea eliminar {TuneMixChannelName}?",
	"DisableAlerts" : "Deshabilitar alertas",
	"Dismiss" : "Ignorar",
	"EditPINCode" : "Canales desbloqueados para la sesión",
	"EditSmartFavorite" : "Editar Favorito inteligente",
	"EditTuneMixChannel" : "Editar canal de TuneMix",
	"EnterDefaultPIN" : "PIN incorrecto.  Intente de nuevo.",
	"EnterPIN" : "Ingrese el PIN predeterminado",
	"EntertainmentMenu" : "Menú Entretenimiento",
	"EveryOtherReport" : "Cada dos informes",
	"EveryReport" : "Cada informe",
	"ExitTuneMix" : "Salir de la TuneMix",
	"Favorite" : "Favorito",
	"FeaturedFavoriteSelectionUpdated" : "Selección de favoritos destacados actualizada ",
	"FeaturedFavorites" : "Favoritos destacados ",
	"FlashFrequency" : "Frecuencia del flash informativo ",
	"LastAlert" : "Última alerta",
	"Listen" : "Escuchar  ",
	"ListenNow" : "Escuchar ahora",
	"ListenNowToolTip" : "Escuchar ahora",
	"LoadingSXM" : "Cargando SXM",
	"LoadingXM" : "Cargando SXM",
	"LockCurrentChannel" : "Bloquear canal actual",
	"MLB" : "MLB",
	"Max50TeamsAllowed" : "Solo se permite un máximo de 50 equipos.",
	"Move" : "Mover  ",
	"MoveConfirmationAffected" : "Esto eliminará el contenido almacenado en {Favorite 1} y repercutirá en los canales de la TuneMix. ",
	"MoveFavorite" : "Mover favorito",
	"NCAA(Football)" : "NCAA (fútbol americano)",
	"NFL" : "NFL",
	"NHL" : "NHL",
	"NearestCity" : "Ciudad más cercana",
	"NextAlert" : "Siguiente alerta",
	"NextChannelToolTip" : "Canal siguiente ",
	"NextToolTip" : "Siguiente  ",
	"NextTrackToolTip" : "Pista siguiente ",
	"NoSaveTuneMixChannels" : "No hay canales de TuneMix guardados",
	"NoXMSignal" : "No hay señal SXM",
	"None" : "Ninguno",
	"Only10TuneMixAllowed" : "Solo se permiten 10 canales de TuneMix.",
	"OnlyFirstReport" : "Solo primer informe después del inicio del vehículo",
	"OnlyFirstReportInGame" : "Solo primer informe del juego",
	"OnlyTenAvailable" : "Solo hay disponibles 10 canales de TuneMix. ",
	"PINCorrectCnfm" : "¿Es correcto?",
	"PINReset" : "Reinicio de PIN",
	"PINSet" : "Reinicio de PIN",
	"ParentalLock" : "Establezca un nuevo PIN  ",
	"ParentalLockPinSettings" : "Configuración de PIN de bloqueo parental",
	"PlayingAlert" : "CH. {ChannelNumber} Alerta de reproducción",
	"PreviousChannelToolTip" : "Canal anterior ",
	"PreviousToolTip" : "Anterior",
	"PreviousTrackToolTip" : " Pista anterior ",
	"RadioID" : "Identificación de radio: {Radio Serial Number}",
	"RemoveSmartFavorite" : "Eliminar Favorito inteligente",
	"RemoveTuneMixChannel" : "Eliminar canal de TuneMix",
	"RenameTuneMixChannel" : "Renombrar canal de TuneMix",
	"RenewSubscription" : "Renueve su suscripción llamando a SiriusXM al {XMPhoneNumber}. ",
	"ReplaceFavorite" : "¿Está seguro de que desea sustituir a {Favorite1} con {Favorite2}?",
	"ReplayAlert" : " Volver a reproducir alerta",
	"ReplayMemoryAlmostFull" : "Memoria de reproducción casi llena.Se perderá el contenido más antiguo en búfer. ",
	"ReplayMemoryFull" : "Memoria de reproducción llena.Se perderá el contenido más antiguo en búfer. ",
	"ReportFrequency" : "Frecuencia de informes",
	"ResetPINCode" : "¿Es correcto?",
	"ReturnToPrevious" : "Volver a anterior",
	"SXMSettingsToolTip" : "Configuración SXM ",
	"SXMTMChannels" : "Canal de TuneMix SMX",
	"SelectAFavoriteTeam" : "Seleccionar un equipo favorito",
	"SelectASport" : "Seleccionar un deporte",
	"SelectCHannelsToAdd" : "Seleccione los canales para añadir a la TuneMix.",
	"SelectCity" : "Seleccionar una ciudad",
	"SelectOptionsIcon" : "Seleccione el icono de Opciones a continuación para desbloquear el canal/la sesión. ",
	"SelectPosition" : "Seleccione posición",
	"SelectPriorityPosition" : "Seleccionar posición de prioridad",
	"SelectSettings" : "Seleccione el icono de Configuración a continuación para desbloquear el canal/la sesión.",
	"SelectStationToEdit" : "Seleccionar canal para editar ",
	"SelectStationToRemove" : "Seleccionar canal para eliminar ",
	"SelectStationsForTuneMix" : "Seleccionar canal para TuneMix ",
	"SelectStationsToAdd" : "Seleccionar canal para añadir",
	"SelectTuneMixChannelToDelete" : "Seleccionar canal de TuneMix para eliminar",
	"SelectTuneMixChannelToEdit" : "Seleccionar canal de TuneMix para editar",
	"SelectTuneMixToRemove" : "Seleccionar canal de TuneMix para eliminar",
	"SelectTuneMixToRename" : "Seleccionar canal de TuneMix para renombrar",
	"SelectTwoSXMFavoritesToAdd" : "Seleccione al menos dos Favoritos SXM para agregar a este canal de TuneMix.  ¿Le gustaría agregar Favoritos SXM a {TuneMixChannelName}?",
	"Serial" : "N. º de serie: {XMSerialNumber} ",
	"SessionLock" : "Bloqueo de sesión",
	"SetNewPIN" : "Estab. un nuevo PIN",
	"SmartFavorite" : "Favorito inteligente ",
	"SmartFavoriteOptions" : "Opciones de Favoritos inteligentes",
	"SmartFavorites" : "Favoritos inteligentes",
	"SportSelection" : "Selección de deporte",
	"SportsFlash" : "SportsFlash  ",
	"SportsFlashAvailable" : "SportsFlash {Alert Team} disponible",
	"SportsFlashPriority" : "Prioridad del SportsFlash",
	"SportsFlashSetup" : "Configuración de SportsFlash",
	"StopChannelScanToolTip" : "Detener Exploración de Canales",
	"StopTuneScanToolTip" : "Detener Exploración de Sintonización",
	"SubscriptionExpired" : "Su suscripción SiriusXM ha caducado.  Renueve su suscripción llamando a SiriusXM al {XMPhoneNumber}.",
	"SubscriptionExpires" : "Su suscripción SiriusXM caduca en {Days} días.  ",
	"TWNowSetup" : "Alerta de tráfico y clima",
	"TeamPriority" : "Prioridad del equipo deportivo ",
	"Traffic&WeatherNow" : "Tráfico y Clima ahora",
	"Traffic&WeatherNowSetup" : "Configuración de Tráfico y Clima ahora",
	"TrafficAndWeatherAvailable" : "Tráfico y Clima para {alert city} disponibles. ",
	"TryAgain" : "Por favor, Reinténtelo",
	"TuneMixChannelCreated" : "{TuneMixChannelName} se creó",
	"TuneMixChannelOptions" : "Opciones del canal de TuneMix",
	"TuneMixChannels" : "TuneMix",
	"TuneMixChannelsList" : "Lista de canales de TuneMix",
	"TuneMixDeleted" : "TuneMix {TuneMixName} eliminada ",
	"TuneMixEditOptions" : "Opciones para editar la TuneMix",
	"TuneScan" : "Exploración de sintonización",
	"TuneScanToolTip" : "Exploración de sintonización",
	"TuneStart" : "Inicio de sintonización",
	"TurnAlertsOff" : "Desactivar alertas",
	"UnableToSave" : "No se puede guardar.  Favoritos inteligentes llenos.",
	"WrongPIN" : "PIN incorrecto.    ",
	"XM" : "SiriusXM",
	"XMChannelNotAuthorized" : "Canal SXM no autorizado",
	"XMChannelNotAvailable" : "Canal SXM no disponible",
	"XMChannelOffAir" : "Canal SXM fuera del aire",
	"XMError" : "No se puede reconectar a SXM Radio",
	"XMLoading" : "Reconectando a SXM Radio",
	"XMSettings" : "Configuración SXM",
	"iTunesTagging" : "Etiquetado de iTunes",
};

framework.registerAppDictLoaded("xmaudio", "es_MX");