var Localization_xmaudioAppDict_th_TH = {
	//"stringId" : "localString"
	"AboutSmartFavorties" : "SXM Favorites 1-10 are SXM Smart Favorites.  If saved as a Smart Favorite, content will be buffered for 30 minutes and you may add the Smart Favorite to a TuneMix Channel. ",
	"AboutSportsFlash" : "SportsFlash allows you to keep up with your selected team's key plays even while you are listening to other audio.  Access SportsFlash through SXM settings. ",
	"AboutTWNow" : "Traffic and Weather Now provides audio alerts of the most recently broadcast traffic and weather reports for a selected city. Traffic and Weather Now setup is accessible through SXM Settings.",
	"AboutTuneMix" : "In TuneMix, buffered content from each Smart Favorite saved in a TuneMix Channel will be played according to your preferences.   Access TuneMix Channels through a tab in Channel List. ",
	"AboutTuneScan" : "When user initiates Tune scan, a sample is played from the buffered content in each Smart Favorite. Tune Scan acts in place of Channel Scan and can be turned On and Off through SXM Settings.",
	"Add" : " ",
	"AddAsSmartFavorite" : " ",
	"AddRemoveTeams" : "Add/Remove Teams",
	"AddSmartFavoriteCnfm" : " ",
	"AddToTuneMix" : "Add to TuneMix Channel.",
	"AllChannels" : "All Channels",
	"AtLeastTwoFavorites" : "At least two SXM Favorites are required to create a TuneMix channel.",
	"AtLeastTwoFavoritestoCreate" : "Select at least two SXM Favorites to create a TuneMix Channel.",
	"AtLeastTwoFavoritestoSave" : "Select at least two SXM Favorites to save to this TuneMix Channel.",
	"BufferContent" : "This will remove buffered content from {Favorite1}. ",
	"CallXM" : " ",
	"ChangeCategory" : " ",
	"ChannelDescriptionService" : " ",
	"ChannelList" : " ",
	"ChannelScanToolTip" : "Channel Scan",
	"ChannelsUnlocked" : " ",
	"CheckXMAntenna" : " ",
	"CheckXMTuner" : " ",
	"CitySelection" : " ",
	"ContinueListening" : "Continue Listening",
	"CreateNewTuneMixChannel" : " ",
	"DeleteSmartFavoriteCnfm" : " ",
	"DeleteSmartFavoriteCnfm_2" : " ",
	"DeleteTuneMixChannelCnfm" : " ",
	"DisableAlerts" : " ",
	"Dismiss" : " ",
	"EditPINCode" : " ",
	"EditSmartFavorite" : " ",
	"EditTuneMixChannel" : " ",
	"EnterDefaultPIN" : " ",
	"EnterPIN" : " ",
	"EveryOtherReport" : " ",
	"EveryReport" : " ",
	"ExitTuneMix" : "Exit TuneMix",
	"Favorite" : " ",
	"FeaturedFavoriteSelectionUpdated" : "Featured favorite selection updated",
	"FeaturedFavorites" : "Featured Favorites",
	"FlashFrequency" : "Flash Frequency",
	"LastAlert" : " ",
	"Listen" : " ",
	"ListenNow" : " ",
	"ListenNowToolTip" : "Listen Now",
	"Live" : "Live",
	"LoadingSXM" : "Loading SXM",
	"LoadingXM" : " ",
	"LockCurrentChannel" : " ",
	"MLB" : " ",
	"Max50TeamsAllowed" : "Maximum of 50 Teams Allowed",
	"Move" : " ",
	"MoveConfirmationAffected" : "This will remove buffered content from {Favorite 1} and impact TuneMix Channels.",
	"MoveFavorite" : "Move favorite",
	"NCAA(Football)" : " ",
	"NFL" : " ",
	"NHL" : " ",
	"NearestCity" : "Nearest City",
	"NextAlert" : " ",
	"NextChannelToolTip" : "Next Channel",
	"NextToolTip" : "Next  ",
	"NextTrackToolTip" : "Next Track",
	"NoSaveTuneMixChannels" : "No Saved TuneMix Channels",
	"NoXMSignal" : " ",
	"None" : " ",
	"Only10TuneMixAllowed" : " ",
	"OnlyFirstReport" : " ",
	"OnlyFirstReportInGame" : " ",
	"OnlyTenAvailable" : "Only 10 TuneMix Channels are available. ",
	"PINCorrectCnfm" : " ",
	"PINReset" : " ",
	"PINSet" : " ",
	"ParentalLock" : " ",
	"ParentalLockPinSettings" : " ",
	"PlayingAlert" : " ",
	"PreviousChannelToolTip" : "Previous Channel",
	"PreviousToolTip" : "Previous",
	"PreviousTrackToolTip" : "Previous Track",
	"RadioID" : " ",
	"RemoveSmartFavorite" : " ",
	"RemoveTuneMixChannel" : " ",
	"RenameTuneMixChannel" : "Rename TuneMix Channel",
	"RenewSubscription" : "Renew your subscription by calling SXM at {XMPhoneNumber}. ",
	"ReplaceFavorite" : "Are you sure you want to replace {Favorite1} with {Favorite2} ?",
	"ReplayAlert" : "Replay alert",
	"ReplayMemoryAlmostFull" : "Replay Memory Almost Full.  Oldest buffered content will be lost. ",
	"ReplayMemoryFull" : "Replay Memory Full.  Oldest buffered content will be lost. ",
	"ReportFrequency" : " ",
	"ResetPINCode" : " ",
	"ReturnToPrevious" : " ",
	"SXMSettingsToolTip" : "SXM Settings",
	"SelectAFavoriteTeam" : " ",
	"SelectASport" : " ",
	"SelectCHannelsToAdd" : "Select Channels to add to TuneMix.",
	"SelectCity" : " ",
	"SelectOptionsIcon" : "Select options icon below to unlock channel/session. ",
	"SelectPosition" : "Select Position",
	"SelectPriorityPosition" : " ",
	"SelectSettings" : " ",
	"SelectStationToEdit" : " ",
	"SelectStationToRemove" : " ",
	"SelectStationsForTuneMix" : " ",
	"SelectStationsToAdd" : " ",
	"SelectTuneMixChannelToDelete" : " ",
	"SelectTuneMixChannelToEdit" : " ",
	"SelectTuneMixToRemove" : "Select TuneMix Channel to Remove.",
	"SelectTuneMixToRename" : "Select TuneMix Channel to Rename.",
	"SelectTwoSXMFavoritesToAdd" : "Select at least two SXM Favorites to add to this TuneMix Channel.  Would you like to add SXM Favorites to {TuneMixChannelName}?",
	"Serial" : "Serial No: {XMSerialNumber} ",
	"SessionLock" : " ",
	"SetNewPIN" : " ",
	"SmartFavorite" : " ",
	"SmartFavoriteOptions" : " ",
	"SmartFavorites" : " ",
	"SportSelection" : " ",
	"SportsFlash" : " ",
	"SportsFlashAvailable" : " ",
	"SportsFlashPriority" : " ",
	"SportsFlashSetup" : " ",
	"SubscriptionExpired" : "Your XM subscription has expired.  Renew your subscription by calling XM at {number}.",
	"SubscriptionExpires" : "Your XM subscription expires in {Days} days. Renew your subscription by calling XM at {XMPhoneNumber}. ",
	"TWNowSetup" : "Traffic and Weather Alert",
	"TeamPriority" : "Sports Team Priority",
	"Traffic&WeatherNow" : " ",
	"Traffic&WeatherNowSetup" : " ",
	"TrafficAndWeatherAvailable" : " ",
	"TryAgain" : "Please try again.",
	"TuneMixChannelCreated" : " ",
	"TuneMixChannelOptions" : "TuneMix Channel Options",
	"TuneMixChannels" : " ",
	"TuneMixChannelsList" : " ",
	"TuneMixDeleted" : "TuneMix {TuneMixName} deleted",
	"TuneMixEditOptions" : "TuneMix Edit Options",
	"TuneScan" : "Tune Scan",
	"TuneScanToolTip" : "Tune Scan",
	"TuneStart" : " ",
	"TurnAlertsOff" : " ",
	"UnableToSave" : " ",
	"WrongPIN" : " ",
	"XM" : " ",
	"XMChannelNotAuthorized" : " ",
	"XMChannelNotAvailable" : " ",
	"XMChannelOffAir" : " ",
	"XMSettings" : " ",
	"iTunesTagging" : " ",
};

framework.registerAppDictLoaded("xmaudio", "th_TH");