var Localization_warnguideAppDict_lv_LV = {
	//"stringId" : "localString"
	"AbsSysErrorLong" : "Bremžu pretbloķēšanas sistēmas (ABS) disfunkcija.\nAutomobilis nekavējoties jāpārbauda pie izplatītāja.",
	"AbsSysErrorShrt" : "ABS disfunkcija",
	"AbsSystemErrorLong" : "Bremžu pretbloķēšanas sistēmas (ABS) disfunkcija. Transportlīdzeklis nekavējoties jāpārbauda pie izplatītāja.",
	"AbsSystemErrorShrt" : "ABS disfunkcija",
	"AccumulationDpfLong" : "Cietās daļiņas, kas savāktas dīzeļdegvielas cieto daļiņu filtrā, pārsniedz noteikto vērtību. Brauciet aptuveni 10–15 minūtes ar pilnīgi uzsilušu motoru (zilā\n temperatūras lampiņa ir izslēgta) ar ātrumu 15 km/h (10 jūdzes stundā) vai vairāk, lai likvidētu cietās daļiņas\nJa šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
	"AccumulationDpfShrt" : "Cieto daļ. uzkrāš. dīzeļd. cieto daļ. filtrā",
	"ActiveBonnetSystemMalfunctionLong" : "Active Bonnet sistēmas disfunkcija.\nJa šis indikators paliek nemainīgs vai turpina mirgot, nodrošiniet, lai dīleris pārbaudītu transportlīdzekli.",
	"ActiveBonnetSystemMalfunctionShrt" : "Active Bonnet sistēmas disfunkcija",
	"AfsSystemErrorLong" : "Adaptīvās priekšējo lukturu sistēmas (AFS) disfunkcija.  Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
	"AfsSystemErrorShrt" : "AFS disfunkcija",
	"AfterRunCoolingPumpLong" : "Ja jūsu „Mazda” pārkarst, sazinieties ar izplatītāju vai dodieties pie tā. ",
	"AfterRunCoolingPumpShrt" : "Izslēgta dzinēja dzesēšanas sūknis ",
	"AirbagSysPretensionerSysErrorLong" : "Drošības spilvena/drošības jostas disfunkcija. Transportlīdzeklis nekavējoties jāpārbauda pie izplatītāja.",
	"AirbagSysPretensionerSysErrorShrt" : "Droš. spilv. sist./spriegotāju sist. disfunkc.",
	"AutoLevelSystemErrorLong" : "Priekšējo lukturu automātiskās līmeņošanas sistēmas disfunkcija. Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
	"AutoLevelSystemErrorShrt" : "Autom. pārnesumk. disfunkc.",
	"AutoLevelSystemErrorShrtJ03" : "Priekšējo lukturu sistēmas disfunkcija",
	"AutoTransSysErrorLong" : "Autom. transmis. disf. Ja turpināsiet braukt, var rasties transportl. bojājumi.  Transportl. nekav. jāpārbauda pie izplatītāja.  ",
	"AutoTransSysErrorShrt" : "Autom. transmis. disfunkc.",
	"AuxBattLowLong" : "Zems 12V akumulatora uzlādes līmenis. \n・Ja signāllampiņa bieži deg braukšanas laikā, iespējams, akumulators ir bojāts. Transportlīdzeklis jāpārbauda pie izplatītāja.\n・Ja šis rādītājs deg pastāvīgi un neizslēdzas, 12V akumulators nedarbojas. Pirms hibrīdsistēmas startēšanas skatiet īpašnieka rokasgrāmatu un pārbaudiet transportlīdzekli pie izplatītāja.",
	"AuxBattLowShrt" : "Zems 12V akumulatora uzl. līm.",
	"BattManagSysErrorLong" : "Akumul. pārvald. sist. disfunkc. Transportl. jāpārbauda pie izplatītāja.",
	"BattManagSysErrorShrt" : "Akumul. pārvald. sist. disfunkc.",
	"BrakOverrideSysErrorLong" : "Bremžu slēdža disfunkcija. Transportlīdzeklis nekavējoties jāpārbauda pie izplatītāja.",
	"BrakOverrideSysErrorShrt" : "Bremžu ped. priorit. sist. disfunkc.",
	"BrakeSysErrorLong" : "Zems bremžu šķidruma līmenis vai bremžu sistēmas disfunkcija.  Nekavējoties apturiet transportlīdzekli drošā vietā un lūdziet izplatītāju to pārbaudīt.",
	"BrakeSysErrorShrt" : "Bremžu sistēmas disfunkcija",
	"BrakeSystemErrorLong" : "Elektroniski kontrolētās bremžu sistēmas disfunkcija. Nekavējoties apturiet transportlīdzekli drošā vietā un lūdziet izplatītāju to pārbaudīt.",
	"BrakeSystemErrorShrt" : "Bremžu sistēmas disfunkcija",
	"BsmSystemErrorLong" : "Blind Spot Monitoring (BSM)/Rear Cross Traffic Alert (RCTA) disfunkcija. Pārbaudiet, vai uz aizmugurējā bufera virsmas nav defektu, un, ja tas ir netīrs vai pārklāts ar sniegu, notīriet to.  Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
	"BsmSystemErrorShrt" : "BSM disfunkcija",
	"ChargSysMalHighPrt" : "Uzlādes sistēmas disfunkcija. Nekavējoties apturiet transportlīdzekli drošā vietā.",
	"ChargingSysErrorLong" : "Uzlādes sistēmas disfunkcija. Ja turpināsiet braukt, var rasties transportlīdzekļa bojājumi.  Nekavējoties apturiet transportlīdzekli drošā vietā un lūdziet izplatītāju to pārbaudīt.",
	"ChargingSysErrorShrt" : "Uzlādes sistēmas disfunkcija",
	"ChrgSysErrorLong" : "Uzlādes sistēmas disfunkcija. Ja turpināsiet braukt, var rasties transportlīdzekļa bojājumi.  Nekavējoties apturiet transportlīdzekli drošā vietā un lūdziet izplatītāju to pārbaudīt.",
	"ChrgSysErrorShrt" : "Uzlādes sistēmas disfunkcija",
	"ColdStartDisableLong" : "Kamēr apkārtējā temperatūra ir pārāk zema, dzinēju nav iespējams griezt, lai pasargātu to no bojājumiem. Skatiet lietotāja rokasgrāmatu. Kad iedarbināt „Mazda” automobili, no aizkaves iespējams izvairīties, pieslēdzot dzinēja bloka sildītāju.",
	"ColdStartDisableShrt" : "Auksta dzinēja iedarbināšana atspējota",
	"ControlSystemErrorLong" : "Parkošanās sistēmas disfunkcija. Ja netiek veikta pārbaude, var notikt jebkura no tālāk minētajām situācijām. \n・Pārnesumkārbas bloķēšanas mehānisms var nedarboties. Novietojiet transportlīdzekli uz līdzenas virsmas un drošā veidā aktivizējiet stāvbremzi. \n・Barošanas slēdzis var neizslēgties. Spiediet barošanas slēdzi atkārtoti, lai izslēgtu. \n・Braukšanas un apstāšanās laikā tiks izslēgts displejs “Aktivizējiet stāvbremzi parkošanās laikā”. \nTransportlīdzeklis nekavējoties jāpārbauda pie izplatītāja.",
	"ControlSystemErrorShrt" : "Parkošanās sistēmas disfunkcija",
	"DPFErrorLong" : "Dīzeļdegvielas cieto daļiņu filtra (DPF) disfunkcija. Transportlīdzeklis jāpārbauda pie izplatītāja.",
	"DPFErrorShrt" : "Dīzeļd. cieto daļ. filtra kļūda",
	"DRSSSysErrorLong" : "DRSS sistēmā ir kļūda. Transportlīdzeklis jāpārbauda pie Mazda izplatītāja.",
	"DRSSSysErrorShrt" : "DRSS disfunkcija",
	"DefEmpty" : "Nav DEF",
	"DefLow" : "DEF līmenis zems",
	"DefVeryLow" : "DEF līmenis ļoti zems",
	"DriveBattDropLong" : "Augstsprieguma akumulatora atlikusī jauda ir zema, jo pārnesums ir bijis neitrālā stāvoklī ilgu laiku. Neitrālā stāvoklī uzlāde nav iespējama. Pārslēdziet stāvēšanas pārnesumā, kad stāvat ilgāku laiku. Ja nepieciešams, restartējiet hibrīdsistēmu, nospiežot barošanas slēdzi.",
	"DriveBattDropShrt" : "Zems augstspr. akumul. uzl. līm.",
	"DropKeyBattChrgLong" : "Atslēgas baterijas uzlādes līmenis ir zems. Nekavējoties nomainiet atslēgas bateriju.",
	"DropKeyBattChrgShrt" : "Zems atslēgas bater. uzlād. līm.",
	"DscSysErrorLong" : "Dynamic Stability Control sistēmas (DSC), Traction Control System (TCS) vai Hill Launch Assist (HLA) disfunkcija. Transportlīdzeklis nekavējoties jāpārbauda pie izplatītāja.",
	"DscSysErrorShrt" : "DSC disfunkcija",
	"DscSystemErrorLong" : "Dinamiskas stabilitātes kontroles sistēmas (DSC) vai saķeres kontroles sistēmas (TCS) disfunkcija. Transportlīdzeklis nekavējoties jāpārbauda pie izplatītāja.",
	"DscSystemErrorShrt" : "DSC disfunkcija",
	"EcbSysErrorLong" : "Reģeneratīvo bremžu vai elektroniski kontrolēto bremžu sistēmas disfunkcija. Nekavējoties apturiet transportlīdzekli drošā vietā un lūdziet izplatītāju to pārbaudīt.",
	"EcbSysErrorShrt" : "Bremžu sistēmas disfunkcija",
	"ElectricParkingBrakeHighLong" : "Stāvbremzes sistēmā radās disfunkcija. Konsultējieties ar Mazda pārstāvi par pārbaudi.",
	"ElectricParkingBrakeLong" : "Stāvbremzes sistēmā radās disfunkcija. Konsultējieties ar Mazda pārstāvi par pārbaudi.",
	"ElectricParkingBrakeShrt" : "Stāvbremzes sistēmas disfunkcija",
	"ElectricVacuumPumpSystemMalfunctionLong" : "Elektriskā vakuumsūkņa sistēmā radās disfunkcija. Ja šī kļūme netiek novērsta, tā var izraisīt sistēmas atteici, kas savukārt izraisa negaidītu risku vai disfunkciju. Nekavējoties konsultējieties ar Mazda pārstāvi par kļūdas pārbaudi.",
	"ElectricVacuumPumpSystemMalfunctionShrt" : "Elektriskā vakuumsūkņa sistēmas disfunkcija",
	"ElectronicThrottleControlLong" : "Ja brīdinājuma indikators neizdziest, elektroniskajā vadības blokā radusies kļūda.  Izslēdziet un ieslēdziet sava „Mazda” dzinēju, lai pārstartētu elektroniskās vadības bloku, vai pārbaudiet dzinēju pie izplatītāja.  \n\nJa brīdinājuma indikators mirgo, ir konstatēta nopietna disfunkcija, un droseles darbība būs ierobežota.  Automobilis pēc iespējas ātrāk jāpārbauda pie izplatītāja.  Mēģiniet pārstartēt elektronisko vadības bloku, izslēdzot un ieslēdzot dzinēju. \n",
	"ElectronicThrottleControlShrt" : "Elektroniskā droseļregulēšana",
	"EloopChargingLong" : "Notiek i‑ELOOP uzlāde. Motoram darbojoties, pārbaudiet, vai uzlāde ir pabeigta un brīdinājuma signāllampiņa ir nodzisusi. Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
	"EloopChargingShrt" : "Notiek i‑ELOOP uzlāde",
	"EloopSysErrorLong" : "i‑ELOOP sistēmas disfunkcija. Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
	"EloopSysErrorShrt" : "i‑ELOOP sistēmas disfunkcija",
	"EngCoolntTempHighOnLong" : "Motors ir pārkarsis. Nekavējoties apturiet transportlīdzekli drošā vietā, izslēdziet motoru un veiciet atbilstošās darbības.  Skatiet īpašnieka rokasgrāmatu.",
	"EngCoolntTempHighOnShrt" : "Augsta motora dzesētāja temp.",
	"EngOilPressureErrorLong" : "Zems motoreļļas spiediens. Nekavējoties apturiet transportlīdzekli drošā vietā, izslēdziet motoru un pārbaudiet motoreļļas līmeni. Ja nepieciešams, pielejiet eļļu. Ja pēc eļļas pieliešanas iedegas šī signāllampiņa vai motoreļļas līmenis ir atbilstošs, nekavējoties nogādājiet automašīnu pie izplatītāja, lai veiktu pārbaudi.",
	"EngOilPressureErrorShrt" : "Zems motoreļļas spiediens",
	"EngSystemErrorLong" : "Motora sistēmas disfunkcija.  Transportlīdzeklis nekavējoties jāpārbauda pie izplatītāja.",
	"EngSystemErrorShrt" : "Motora sistēmas disfunkcija",
	"EngineOilPressureErrorLong" : "Zems motoreļļas spiediens. Nekavējoties apturiet transportlīdzekli drošā vietā, izslēdziet motoru un pārbaudiet motoreļļas līmeni. Ja nepieciešams, pielejiet eļļu. Ja pēc eļļas pieliešanas iedegas šī signāllampiņa vai motoreļļas līmenis ir atbilstošs, nekavējoties nogādājiet automašīnu pie izplatītāja, lai veiktu pārbaudi.",
	"EngineOilPressureErrorShrt" : "Zems motoreļļas spiediens",
	"EngineWaterTempDropLong" : "Motora dzesēšanas šķidrums ir auksts, un sildīšanas sistēmai/atkausētājam nav pieejams silts gaiss. Transportlīdzekli drīkst vadīt ar iedegtu vai neiedegtu signāllampiņu.  Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
	"EngineWaterTempDropShrt" : "Zema motora dzes. šķidr. temp.",
	"EngineWaterTempRiseLong" : "Motors tiek iedarbināts uzsilšanai. Brauciet lēnām vai apstājieties un uzgaidiet, kamēr signāllampiņa pārstāj mirgot. Ja tā turpina mirgot pat pēc apstāšanās, veiciet atbilstošās darbības. Skatiet īpašnieka rokasgrāmatu.",
	"EngineWaterTempRiseShrt" : "Augsta motora dzesētāja temp.",
	"EngnCoolTempHighHighPrt" : "Motora dzesēšanas šķidruma temperatūra ir augsta. Nekavējoties apturiet transportlīdzekli drošā vietā.",
	"FOWMRCCDRSSRadarSoilingLong" : "FOW/MRCC/DRSS radars (sensors) ir netīrs. Notīriet radara (sensora) virsmu.",
	"FOWMRCCDRSSRadarSoilingShrt" : "FOW/MRCC/DRSS radara disfunkcija",
	"FOWMRCCRadarSoilingLong" : "FOW/MRCC radara (sensora) disfunkcija.  Ja priekšējā režģa emblēma ir netīra vai klāta ar sniegu, notīriet visu virsmu.  \nJa šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.\n",
	"FOWMRCCRadarSoilingShrt" : "FOW/MRCC radara disfunkcija",
	"FOWSysError" : "FOW disfunkcija",
	"FOWSysErrorLong" : "Forward Obstruction Warning (FOW) sistēmas disfunkcija. Transportlīdzeklis jāpārbauda pie izplatītāja.",
	"FWDSysErrorLong" : "4WD sistēmas disfunkcija vai atšķiras priekšējo un aizmugurējo riepu izmēri. Transportlīdzeklis jāpārbauda pie izplatītāja.",
	"FWDSysErrorShrt" : "4WD sistēmas disfunkcija",
	"FuelAirFilterCartReplacePeriodLong" : "Jānomaina degvielas filtra patrona.",
	"FuelAirFilterCartReplacePeriodShrt" : "Jānomaina degvielas filtrs.",
	"FuelCapInspectionLong" : "Iespējams, degvielas tvertnes vāciņš nav ievietots pareizi. Pārbaudiet, vai degvielas tvertnes vāciņš ir ievietots un pareizi pievilkts. Pēc degvielas tvertnes vāciņa atbilstošas ievietošanas un pievilkšanas signāllampiņa nenodzisīs dažu braukšanas ciklu laikā, kamēr tā nepārliecināsies, ka sistēma darbojas pareizi. Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
	"FuelCapInspectionShrt" : "Degvielas tvertnes vāciņa pārbaude",
	"HBCALHUnavailableLong_1" : "Salona pārmērīgi augstās temperatūras dēļ sistēma High Beam Control ir īslaicīgi atspējota. Sistēma High Beam Control tiks iespējota, kad salona temperatūra būs pietiekami zema.",
	"HBCALHUnavailableLong_2" : "Salona pārmērīgi augstās temperatūras dēļ sistēma Adaptive LED Headlights ir īslaicīgi atspējota. Sistēma Adaptive LED Headlights tiks iespējota, kad salona temperatūra būs pietiekami zema.",
	"HBCALHUnavailableShrt_1" : "HBC nav pieejama",
	"HBCALHUnavailableShrt_2" : "ALH nav pieejama",
	"HBCLDWSSysErrorLong" : "Sistēmas High Beam Control (HBC)* un/vai Lane Departure Warning System (LDWS)* darbības traucējums. Ja šī signāllampiņa nenodziest, lūdziet izplatītājam pārbaudīt transportlīdzekli.\n*Šo sistēmu pieejamība atkarīga no automašīnas modeļa/aprīkojuma klases.",
	"HBCLDWSSysErrorLong_2" : "High Beam Control (HBC)/Lane-keep Assist System (LAS) disfunkcija. Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
	"HBCLDWSSysErrorLong_3" : "Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS) disfunkcija.  Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
	"HBCLDWSSysErrorLong_4" : "Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS) disfunkcija.  Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
	"HBCLDWSSysErrorShrt" : "HBC/LDWS sistēmas disfunkcija",
	"HBCLDWSSysErrorShrt_2" : "HBC/LAS sistēmas disfunkcija",
	"HBCLDWSSysErrorShrt_3" : "ALH/LDWS sistēmas disfunkcija",
	"HBCLDWSSysErrorShrt_4" : "ALH/LAS sistēmas disfunkcija",
	"HBCLDWSWindshieldFogLong" : "Sistēmas High Beam Control (HBC)* un/vai Lane Departure Warning System (LDWS)* darbības traucējums. Atkausējiet vējstiklu.  Ja šī signāllampiņa nenodziest, lūdziet izplatītājam pārbaudīt transportlīdzekli.\n*Šo sistēmu pieejamība atkarīga no automašīnas modeļa/aprīkojuma klases.",
	"HBCLDWSWindshieldFogLong_2" : "High Beam Control (HBC)/Lane-keep Assist System (LAS) disfunkcija. Atkausējiet vējstiklu. Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
	"HBCLDWSWindshieldFogLong_3" : "Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS) disfunkcija. Atkausējiet vējstiklu. Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
	"HBCLDWSWindshieldFogLong_4" : "Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS) disfunkcija. Atkausējiet vējstiklu. Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
	"HBCLDWSWindshieldFogShrt" : "HBC/LDWS sistēmas disfunkcija",
	"HBCLDWSWindshieldFogShrt_2" : "HBC/LAS sistēmas disfunkcija",
	"HBCLDWSWindshieldFogShrt_3" : "ALH/LDWS sistēmas disfunkcija",
	"HBCLDWSWindshieldFogShrt_4" : "ALH/LAS sistēmas disfunkcija",
	"HBCLLDWSCamDisconnectLong" : "Sistēmas High Beam Control (HBC)* un/vai Lane Departure Warning System (LDWS)* darbības traucējums. Notīriet vējstiklu.  Ja šī signāllampiņa nenodziest, lūdziet izplatītājam pārbaudīt transportlīdzekli.\n*Šo sistēmu pieejamība atkarīga no automašīnas modeļa/aprīkojuma klases.",
	"HBCLLDWSCamDisconnectLong_2" : "High Beam Control (HBC)/Lane-keep Assist System (LAS) disfunkcija. Notīriet vējstiklu. Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
	"HBCLLDWSCamDisconnectLong_3" : "Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS) disfunkcija. Notīriet vējstiklu.   Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
	"HBCLLDWSCamDisconnectLong_4" : "Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS) disfunkcija.  Notīriet vējstiklu.  Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
	"HBCLLDWSCamDisconnectShrt" : "HBC/LDWS kameras disfunkcija",
	"HBCLLDWSCamDisconnectShrt_2" : "HBC/LAS kameras disfunkcija",
	"HBCLLDWSCamDisconnectShrt_3" : "ALH/LDWS kameras disfunkcija",
	"HBCLLDWSCamDisconnectShrt_4" : "ALH/LAS kameras disfunkcija",
	"HBCSysErrorLong" : "High Beam Control (HBC)  disfunkcija. Transportlīdzeklis jāpārbauda pie izplatītāja.\n",
	"HBCSysErrorLong_2" : "Adaptive LED Headlights (ALH) disfunkcija. Transportlīdzeklis jāpārbauda pie izplatītāja.",
	"HBCSysErrorShrt" : "HBC disfunkcija",
	"HBCSysErrorShrt_2" : "ALH disfunkcija",
	"HbcOrAlhUnavailable" : "HBC vai ALH funkcija nav pieejama",
	"HeadlightSystemErrorLongJ03" : "Priekšējo lukturu sistēmā radās disfunkcija. Ja brīdinājuma gaisma mirgo nepārtraukti, konsultējieties ar Mazda pārstāvi.",
	"HighEngineOillevel" : "Augsts motoreļļas līmenis",
	"HighEngineOillevelDetail" : "Motoreļļas līmenis ir pārāk augsts. Lūdzu, nomainiet eļļu.",
	"HybrdSysMalHighPrt" : "Hibrīdsistēmas disfunkcija. Nekavējoties apturiet transportlīdzekli drošā vietā.",
	"HybridSysErrorLong" : "Hibrīdsistēmas disfunkcija. Ja turpināsiet braukt, var rasties transportlīdzekļa bojājumi. Nekavējoties apturiet transportlīdzekli drošā vietā un lūdziet izplatītāju to pārbaudīt.",
	"HybridSysErrorShrt" : "Hibrīdsistēmas disfunkcija",
	"HybridSysOverheatLong" : "Hibrīdsistēmas disfunkcija. Ja turpināsiet braukt, var rasties transportlīdzekļa bojājumi. Nekavējoties apturiet transportlīdzekli drošā vietā un lūdziet izplatītāju to pārbaudīt.",
	"HybridSysOverheatShrt" : "Hibrīdsistēma ir pārkarsusi",
	"IeloopChrgHighPrt" : "Uzlādē i‑ELOOP. Dzinēj. darbojoties, pārb., vai uzlāde ir pabeigta un brīdin. lamp. ir nodzisusi.",
	"IstopSysErrorLong" : "i‑stop darbība nav iespējama. Transportlīdzeklis jāpārbauda pie Mazda izplatītāja.",
	"IstopSysErrorShrt" : "i‑stop sistēmas disfunkcija",
	"KeylesSysErrorLong" : "Bezatslēgas ievades sistēmas disfunkcija. Transportlīdzeklis jāpārbauda pie izplatītāja.",
	"KeylesSysErrorShrt" : "Bezatslēgas ievades kļūme",
	"LDWSLASUnavailableLong_1" : "Salona pārmērīgi augstās temperatūras dēļ sistēma Lane Departure Warning System ir īslaicīgi atspējota. Sistēma Lane Departure Warning System tiks iespējota, kad salona temperatūra būs pietiekami zema.",
	"LDWSLASUnavailableLong_2" : "Salona pārmērīgi augstās temperatūras dēļ sistēma Lane-Keep Assist System ir īslaicīgi atspējota. Sistēma Lane-Keep Assist System tiks iespējota, kad salona temperatūra būs pietiekami zema. ",
	"LDWSLASUnavailableShrt_1" : "LDWS nav pieejama",
	"LDWSLASUnavailableShrt_2" : "LAS nav pieejama",
	"LDWSSysErrorLong" : "Lane Departure Warning System (LDWS) disfunkcija. Transportlīdzeklis jāpārbauda pie izplatītāja.\n",
	"LDWSSysErrorLong_2" : "Lane-keep Assist System (LAS) disfunkcija. Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
	"LDWSSysErrorShrt" : "LDWS disfunkcija",
	"LDWSSysErrorShrt_2" : "LAS disfunkcija",
	"LdwsOrLasUnavailable" : "LDWS vai LAS funkcija nav pieejama",
	"LowBrakeFluidLong" : "Zems bremžu šķidruma līmenis. Nekavējoties apturiet transportlīdzekli drošā vietā un lūdziet izplatītāju to pārbaudīt.",
	"LowBrakeFluidShrt" : "Zems bremžu šķidruma līmenis",
	"LowEngineOillevel" : "Zems motoreļļas līmenis",
	"LowEngineOillevelDetail" : "Motoreļļas līmenis ir pārāk zems. Lūdzu, pielejiet eļļu.",
	"LowFuelLong" : "Degvielas tvertnes līmenis ir zems. Pēc iespējas drīzāk uzpildiet degvielu.",
	"LowFuelShrt" : "Zems degvielas līmenis",
	"LowTireAirPressureFlatLong" : "Ja spiediens ārkārtīgi samazinās pēc TPMS, iedegas brīdinājuma gaisma, vai ja riepā ir caurums, iedegas arī tukšas riepas brīdinājuma gaisma. Ja tiek pārdurta nulles spiediena riepa, uzmanīgi brauciet ar transportlīdzekli līdz tuvākajam Mazda pārstāvim un lūdziet nomainīt riepu.",
	"LowTireAirPressureLong" : "Zems riepu gaisa spiediens vienā vai vairākās riepās. \nPārbaudiet riepu gaisa spiedienu un piepūtiet līdz pareizajam gaisa spiedienam. Pēc riepu spiediena noregulēšanas spiediet slēdzi TPMS SET, līdz atskan signāls.",
	"LowTireAirPressureShrt" : "Zems gaisa spiediens riepās",
	"LowWasheFluidLong" : "Zems logu mazgāšanas sistēmas šķidruma līmenis. Uzpildiet logu mazgāšanas šķidrumu.",
	"LowWasheFluidShrt" : "Zems logu mazg. šķ. līm.",
	"MRCCSysErrorLong" : "Mazda Radar Cruise Control (MRCC) disfunkcija. Transportlīdzeklis jāpārbauda pie izplatītāja.",
	"MRCCSysErrorShrt" : "MRCC disfunkcija",
	"MRCCUnavailableLong" : "Mazda Radar Cruise Control (MRCC) šobrīd nav pieejams.",
	"MRCCUnavailableShrt" : "MRCC nav pieejams",
	"NoWarnings" : "Brīdinājumi nav atrasti",
	"OilLevelSystemMalfunctioning" : "Motoreļļas līmeņa sensora darbības kļūda",
	"OilLevelSystemMalfunctioningDetail" : "Mašīneļļas līmeņa sensorā ir nepareiza darbība. Lūdzu, nogādājiet transportlīdzekli pārbaudei pie Mazda tirgotāja. ",
	"PowerSteeringSysErrorLong" : "Elektriskā stūres pastiprinātāja disfunkcija. Apturiet transportlīdzekli drošā vietā un izslēdziet motoru.  Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
	"PowerSteeringSysErrorShrt" : "Stūres pastiprin. sist. disfunkc.",
	"PpositionRequestLong" : "Pārslēdziet pārnesumkārbu stāvēšanas pārnesumā. To izraisa kāds no tālāk norādītajiem iemesliem:\n・Akumulatora sistēma tika palaista vai apturēta pārnesumā, kas nav stāvēšanas pārnesums \n・Vadītāja puses durvis tika atvērtas ar pārnesumu stāvoklī N, D vai B \n・Augstsprieguma akumulatora atlikusī jauda ir zema, jo pārnesums ir bijis neitrālā stāvoklī ilgu laiku. \nJa nepieciešams, restartējiet hibrīdsistēmu, nospiežot barošanas slēdzi.\n",
	"PpositionRequestShrt" : "Jāaktivizē parkošanās stāvoklis",
	"PreheatingDispLampLong" : "Kvēlsveces ir uzsildītas. Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
	"PreheatingDispLampShrt" : "Kvēlsveces uzsildītas",
	"RoadSurfaceIcingCautionLong" : "Āra temperatūra ir līdz 4 °C. Braukšanas laikā uzmanieties no apledojušām ceļa virsmām.",
	"RoadSurfaceIcingCautionShrt" : "Brīdin. par ceļa virsm. apled.",
	"RvmSysErrorLong" : "RVM sistēmā ir kļūda. Pārbaudiet, vai uz aizmugurējā bufera virsmas nav defektu, un, ja tas ir netīrs vai pārklāts ar sniegu, notīriet to. Ja šī brīdinājuma lampiņa joprojām deg, pārbaudiet transportlīdzekli pie Mazda izplatītāja.",
	"RvmSysErrorShrt" : "RVM disfunkcija",
	"SBSBrakeMRCCUnavailableLong" : "SBS bremzes/MRCC šobrīd nav pieejams.",
	"SBSBrakeMRCCUnavailableShrt" : "SBS bremzes/MRCC nav pieejams",
	"SBSBrakeUnavailableLong" : "SBS bremzes šobrīd nav pieejamas.",
	"SBSBrakeUnavailableShrt" : "SBS bremzes nav pieejamas",
	"SBSMRCCDRSSRadarSoilingLong" : "SBS/MRCC/DRSS radars (sensors) ir netīrs. Notīriet radara (sensora) virsmu.",
	"SBSMRCCDRSSRadarSoilingShrt" : "SBS/MRCC/DRSS radara disfunkcija",
	"SBSMRCCRadarSoilingLong" : "SBS/MRCC radars (sensors) ir netīrs. Notīriet radara (sensora) virsmu.",
	"SBSMRCCRadarSoilingShrt" : "SBS/MRCC radara disfunkcija",
	"SBSSysErrorLong" : "SBS sistēmā ir kļūda. Transportlīdzeklis jāpārbauda pie Mazda izplatītāja.",
	"SBSSysErrorShrt" : "SBS disfunkcija",
	"SCBSSysErrorLong" : "Smart City Brake Support (SCBS) disfunkcija. Transportlīdzeklis nekavējoties jāpārbauda pie izplatītāja.",
	"SCBSSysErrorLong_105" : "Smart City Brake Support (SCBS) disfunkcija. Atkausējiet vējstiklu. Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
	"SCBSSysErrorShort_105" : "SCBS disfunkcija",
	"SCBSSysErrorShrt" : "SCBS disfunkcija",
	"SCBSUnavailableLong" : "Smart City Brake Support (SCBS) šobrīd nav pieejama.",
	"SCBSUnavailableLong1" : "Salona pārmērīgi augstās temperatūras dēļ sistēma Smart City Brake Support ir īslaicīgi atspējota. Sistēma Smart City Brake Support tiks iespējota, kad salona temperatūra būs pietiekami zema.",
	"SCBSUnavailableShrt" : "SCBS nav pieejama",
	"SCBSUnavailableShrt1" : "SCBS nav pieejama",
	"SCBSWindshieldSoilingLong" : "Smart City Brake Support (SCBS) disfunkcija. Notīriet priekšējo vējstiklu. Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
	"SCBSWindshieldSoilingShrt" : "SCBS disfunkcija",
	"SCRMalfunction100Long" : "Dīzeļdegvielas izmešu sistēmas (SCR) disfunkcija.\nJa problēma netiks atrisināta, transportlīdzekļa ātrums tiks ierobežots.",
	"SCRMalfunction101Long" : "Dīzeļdegvielas izmešu sistēmas (SCR) disfunkcija.\nJa problēma netiks atrisināta, dzinējs tiks pārslēgts obligātajā brīvgaitas režīmā.",
	"SCRMalfunction102Long" : "Dīzeļdegvielas izmešu sistēmas (SCR) disfunkcija. Dzinējs šobrīd pārslēgts obligātajā brīvgaitas režīmā.\nVērsieties pie pilnvarota “Mazda” izplatītāja, lai veiktu apkopi.",
	"ScrMalfunction" : "SCR disfunkcija",
	"SedimenterWarningLong" : "Ūdens separatorā uzkrātais daudzums pārsniedz nominālo daudzumu. Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
	"SedimenterWarningShrt" : "Ūdens separatora pārbaude",
	"SystemInspectionLong" : "Diferenciāļa eļļas temperatūra ir neadekvāti augsta vai radusies liela griešanās atšķirība starp priekšējām un aizmugurējām riepām (piemēram, kad mēģina tikt ārā no dubļiem). Apturiet transportlīdzekli drošā vietā un turpiniet braukt tikai pēc tam, kad signāllampiņa ir nodzisusi. Ja šī signāllampiņa turpina mirgot, transportlīdzeklis jāpārbauda pie izplatītāja.",
	"SystemInspectionShrt" : "4WD sistēmas pārbaude",
	"TpmsSysErrorLong" : "Riepu gaisa spiediena uzraudzības sistēmas (TPMS) disfunkcija. Transportlīdzeklis jāpārbauda pie izplatītāja.",
	"TpmsSysErrorShrt" : "TPMS sistēmas disfunkcija",
	"VehicleSysErrorLong" : "Transportlīdzekļa sistēmas disfunkcija. Transportlīdzeklis jāpārbauda pie izplatītāja.",
	"VehicleSysErrorShrt" : "Transportl. sist. Disfunkcija",
	"WarningGuidance" : "Brīdinājuma norāde",
	"WarningSafetyMessage" : "Drošības nolūkos brīdinājuma norāde netiek rādīta.",
	"Warnings" : "Brīdinājumi",
	"brakeFluid" : "Zems bremžu šķidruma līmenis",
	"engineOilPressure" : "Motoreļļas spiediens",
	"highVoltage" : "Zems augstsprieguma akumulatora uzlādes līmenis",
	"lowBattStartEngine" : "Tukša baterija! Iedarbiniet dzinēju!",
};

framework.registerAppDictLoaded("warnguide", "lv_LV");