var Localization_warnguideAppDict_es_ES = {
	//"stringId" : "localString"
	"AbsSysErrorLong" : "Fallo en el sistema de frenos antibloqueo (ABS).\nRevise el vehículo en un Servicio Autorizado Mazda inmediatamente.",
	"AbsSysErrorShrt" : "Fallo de ABS",
	"AbsSystemErrorLong" : "Fallo en el sistema de frenos antibloqueo (ABS).\nHaga revisar el vehículo por un Servicio Autorizado inmediatamente.",
	"AbsSystemErrorShrt" : "Fallo de ABS",
	"AccumulationDpfLong" : "Las particulas (PM) atrapadas en el filtro de particulas diesel (DPF) han excedido el valor de regulación. Conduzca el vehículo durante unos 10 o 15 minutos con el motor caliente (testigo de temperatura azul apagado) a una velocidad de 15 km/h (10mph) o más para eliminar las PM. Haga revisar el vehículo por un Servicio Autorizado Mazda si el indicador permanece activado",
	"AccumulationDpfShrt" : "Acumulación de PM en DPF",
	"ActiveBonnetSystemMalfunctionLong" : "Fallo del sistema del Active Bonnet.\nHaga revisar el vehículo por un servicio autorizado si este indicador permanece activado o sigue parpadeando.",
	"ActiveBonnetSystemMalfunctionShrt" : "Fallo del sistema del Active Bonnet",
	"AfsSystemErrorLong" : "Fallo en el sistema de luces adaptativas (AFS).  Haga revisar el vehículo por un concesionario si este indicador permanece parpadeando.",
	"AfsSystemErrorShrt" : "Fallo de AFS",
	"AfterRunCoolingPumpLong" : "Si su Mazda se sobrecalienta, llame o acuda a su concesionario para una revisión. ",
	"AfterRunCoolingPumpShrt" : "Bomba de enfriamiento de retardo",
	"AirbagSysPretensionerSysErrorLong" : "Fallo en el Airbag / cinturón de seguridad.\nHaga revisar el vehículo por un Servicio Autorizado inmediatamente.",
	"AirbagSysPretensionerSysErrorShrt" : "Fallo Sist.  Pretensores/Airbag",
	"AutoLevelSystemErrorLong" : "Fallo en el sistema de autonivelado de luces.\nHaga revisar el vehículo por un Sevicio Autorizado si este indicador permanece activado.",
	"AutoLevelSystemErrorShrt" : "Fallo Sist Autonivelado",
	"AutoLevelSystemErrorShrtJ03" : "Fallo del sistema de faros",
	"AutoTransSysErrorLong" : "Fallo en la caja de cambios automática.\nSi continúa conduciendo puede causar  un daño al vehículo.  Haga revisar el vehículo por un Servicio Autorizado inmediatamente.  ",
	"AutoTransSysErrorShrt" : "Fallo Transmisión Auto",
	"AuxBattLowLong" : "La carga de la batería de 12V es baja.\nSi este indicador se enciende frecuentemente mientras conduce, la batería puede estar dañada. Revise su vehículo en un Servicio Autorizado Mazda.\nSi este indicador queda fijo y no se apaga, la batería de 12V estará agotada. Consulte el Manual del Propietario antes de iniciar el sistema híbrido y revise el vehículo en un Servicio Autorizado Mazda.",
	"AuxBattLowShrt" : "Batería de 12 V Baja",
	"BattManagSysErrorLong" : "Fallo en el Sistema de Gestión de Batería.\nHaga revisar el vehículo por un Servicio Autorizado.",
	"BattManagSysErrorShrt" : "Fallo Sist. Gestión Batería",
	"BrakOverrideSysErrorLong" : "Fallo en el interruptor de frenos.\nHaga revisar el vehículo por un Servicio Autorizado inmediatamente.",
	"BrakOverrideSysErrorShrt" : "Fallo Sist Mando Frenos",
	"BrakeSysErrorLong" : "El nivel del líquido de frenos está bajo o hay un fallo en el sistema de frenos.  Detenga el vehículo inmediatamente en una zona segura y  revise el vehículo en un Servicio Autorizado Mazda.",
	"BrakeSysErrorShrt" : "Fallo en el Sistema de Frenos",
	"BrakeSystemErrorLong" : "Fallo en el sistema de frenos controlado electrónicamente. Detenga el vehículo inmediatamente en un lugar seguro y haga revisar el vehículo por un Servicio Autorizado Mazda.",
	"BrakeSystemErrorShrt" : "Fallo en el Sistema de Frenos",
	"BsmSystemErrorLong" : "Fallo en Blind Spot Monitoring (BSM)/Rear Cross Traffic Alert (RCTA),\nVerifique si hay anomalías en la superficie del paragolpes trasero y límpielo si está sucio o cubierto con nieve. Haga revisar el vehículo por un Servicio Autorizado si este indicador permanece activado.",
	"BsmSystemErrorShrt" : "Fallo de BSM",
	"ChargSysMalHighPrt" : "Fallo del Sistema de Carga. Detenga el vehículo inmediatamente en un lugar seguro.",
	"ChargingSysErrorLong" : "Fallo en el Sistema de Carga. El vehículo podría dañarse si continua circulando. Detenga el vehículo inmediatamente en una zona segura y haga revisar el vehículo por un Servicio Autorizado Mazda.",
	"ChargingSysErrorShrt" : "Fallo en el Sistema de Carga",
	"ChrgSysErrorLong" : "Fallo en el Sistema de Carga. Detenga el vehículo inmediatamente en una zona segura y haga revisar el vehículo por un Servicio Autorizado Mazda.",
	"ChrgSysErrorShrt" : "Fallo en el Sistema de Carga",
	"ColdStartDisableLong" : "Cuando la temperatura ambiente es muy baja, se impide el arranque del motor para evitar que sufra daños. Consulte el manual del propietario. Puede evitar posibles retrasos al arrancar su Mazda conectando el calentador del bloque motor.",
	"ColdStartDisableShrt" : "Arranque en frío desactivado",
	"ControlSystemErrorLong" : "Fallo en el Sistema de  control de posición de aparcamiento\nSi permaneció sin revisar, puede llevar a cabo cualquiera de las siguientes acciones:\nEl mecanismo de bloqueo de aparcamiento puede no funcionar correctamente. Estacione en un lugar plano y active el freno de estacionamiento.\nEl interruptor dearranque no se puede apagar. Pulse repetidamente el interruptor de arranque para apagarlo.\nLa pantalla “Establezca el Freno de Aparcamiento Cuando Estacione” se apagará cuando circule o cuando se detenga.\nHaga revisar el vehículo por un Servicio Autorizado Mazda inmediatamente.",
	"ControlSystemErrorShrt" : "Fallo del Sistema de Control de la Posición de Parking",
	"DPFErrorLong" : "Fallo en el filtro de partículas diesel (DPF)\nHaga revisar el vehículo por un Servicio Autorizado.",
	"DPFErrorShrt" : "Error de DPF",
	"DRSSSysErrorLong" : "Hay un error en el sistema DRSS.\nHaga revisar su vehículo por un Servicio Autorizado Mazda.",
	"DRSSSysErrorShrt" : "Fallo en el DRSS",
	"DefEmpty" : "DEF agotado",
	"DefLow" : "Nivel bajo de DEF",
	"DefVeryLow" : "Nivel muy bajo de DEF",
	"DriveBattDropLong" : "La energía residual en la batería de alto voltaje es baja debido a que la transmisión ha estado por un largo período de tiempo en posición Neutra. No es posible cargar en posición Neutra. Cambie a posición Parking cuando detenga el vehículo durante un largo período de tiempo. Reinicie el sistema híbrido presionando el botón de arranque si es necesario.",
	"DriveBattDropShrt" : "Batería de Alto voltaje de baja",
	"DropKeyBattChrgLong" : "La batería de la llave es baja. Sustituya la batería de la llave en el menor tiempo posible",
	"DropKeyBattChrgShrt" : "Batería de la llave baja",
	"DscSysErrorLong" : "Fallo en el sistema de Hill Launch Assist (HLA), en el Traction Control System (TCS), o en el Dynamic Stability Control (DSC).Haga revisar el vehículo por un Servicio Autorizado Mazda inmediatamente.",
	"DscSysErrorShrt" : "Fallo de DSC",
	"DscSystemErrorLong" : "Fallo en el sistema de control de tracción (TCS) o en el control de estabilidad dinámico (DSC).\nHaga revisar el vehículo por un Servcicio Autorizado inmediatamente.",
	"DscSystemErrorShrt" : "Fallo de DSC",
	"EcbSysErrorLong" : "Fallo en el sistema de frenada regenerativa o en el sistema de frenada electrónica. Detenga el vehículo inmediatamente en una zona segura y revise su vehículo en un Servicio Autorizado Mazda.",
	"EcbSysErrorShrt" : "Fallo en el Sistema de Frenos",
	"ElectricParkingBrakeHighLong" : "Ha ocurrido un fallo en el sistema del freno de estacionamiento. Acuda a su concesionario Mazda para una inspección.",
	"ElectricParkingBrakeLong" : "Ha ocurrido un fallo en el sistema del freno de estacionamiento. Acuda a su concesionario Mazda para una inspección.",
	"ElectricParkingBrakeShrt" : "Fallo del sistema del freno de estacionamiento",
	"ElectricVacuumPumpSystemMalfunctionLong" : "Ha ocurrido un fallo en el sistema de la bomba de vacio eléctrica Si no repara este error, podría causar el fallo del sistema, lo que podría suponer un peligro inesperado o su mal funcionamiento. Acuda a su concesionario Mazda enseguida y haga que revisen el error.",
	"ElectricVacuumPumpSystemMalfunctionShrt" : "Fallo del sistema de la bomba de vacio eléctrica",
	"ElectronicThrottleControlLong" : "Si la luz de advertencia permanece encendida, hay un fallo en la unidad de control electrónico.  Apague y encienda el motor de su Mazda para reiniciar la unidad de control electrónico o acuda a un concesionario para su revisión. \n\nSi la luz de advertencia parpadea, indica que se ha producido un fallo grave y la acción del acelerador estará limitada.  Lleve su vehículo a revisión a un concesionario lo antes posible.  Intente reiniciar la unidad de control electrónico apagando y encendiendo el motor.  \n",
	"ElectronicThrottleControlShrt" : "Control electrónico del acelerador",
	"EloopChargingLong" : "Cargando i‑ELOOP.\nCon el motor en marcha, verifique que la carga esté completa y que el indicador de advertencia esté apagado. Revise el vehículo por un Servicio Autorizado Mazda  si este indicador permanece activado.",
	"EloopChargingShrt" : "Cargando i‑ELOOP",
	"EloopSysErrorLong" : "Fallo en el sistema i‑ELOOP, haga revisar el vehículo por un Servicio Autorizado Mazda si el indicador permanece activado.",
	"EloopSysErrorShrt" : "Fallo en el Sistema i‑ELOOP",
	"EngCoolntTempHighOnLong" : "El motor se está sobrecalentado.\nDetenga el vehículo inmediatamente en un lugar seguro, apague el motor, y tome las acciones adecuadas.  Consulte el Manual del Usuario.\n",
	"EngCoolntTempHighOnShrt" : "Temperatura del refrigerador del motor alta",
	"EngOilPressureErrorLong" : "Presión de Aceite de Motor Baja.\nDetenga el vehículo inmediatamente en un lugar seguro, apague el motor, e inspeccione el nivel de aceite del motor. Añada aceite si es necesario.\nHaga revisar el vehículo por un Servicio Autorizado Mazda inmediatamente si este indicador se enciende después de haber añadido aceite o  el nivel de aceite del motor está bien.",
	"EngOilPressureErrorShrt" : "Presión de Aceite de Motor Baja",
	"EngSystemErrorLong" : "Fallo en el Sistema del Motor.  Haga revisar el vehículo por un Servicio Autorizado inmediatamente.",
	"EngSystemErrorShrt" : "Fallo en el Sistema de Motor",
	"EngineOilPressureErrorLong" : "Presión de Aceite de Motor Baja.\nDetenga el vehículo inmediatamente en un lugar seguro, apague el motor, e inspeccione el nivel de aceite del motor. Añada aceite si es necesario.\nHaga revisar el vehículo por un Servicio Autorizado Mazda inmediatamente si este indicador se enciende después de haber añadido aceite o  el nivel de aceite del motor está bien.",
	"EngineOilPressureErrorShrt" : "Presión de Aceite de Motor Baja.",
	"EngineWaterTempDropLong" : "El refrigerante del motor está frío y no hay aire caliente disponible para el calentador / desempañador. El vehículo puede conducirse con el indicador activado o apagado.  Haga revisar el vehículo por un Servicio Autorizado si este indicador permanece activado.",
	"EngineWaterTempDropShrt" : "Temp. Refrig. de Motor Baja",
	"EngineWaterTempRiseLong" : "El motor está empezando a calentarse.\nConduzca lentamente o detenga el vehículo hasta que el indicador deje de parpadear. Si continua intermitente, incluso después de haber detenido el vehículo, tome las acciones adecuadas. Consulte el Manual del Usuario.\n",
	"EngineWaterTempRiseShrt" : "Temperatura del refrigerador del motor alta",
	"EngnCoolTempHighHighPrt" : "Temperatura de Refrigerante de Motor Alta. Detenga el vehículo inmediatamente en un lugar seguro.",
	"FOWMRCCDRSSRadarSoilingLong" : "El sensor FOW/MRCC/DRSS está sucio. Limpie toda la superficie del sensor.",
	"FOWMRCCDRSSRadarSoilingShrt" : "Fallo Radar FOW/MRCC/DRSS",
	"FOWMRCCRadarSoilingLong" : "Fallo en el sensor FOW/MRCC.\nLimpie toda la superficie del logotipo de la rejilla frontal si está sucia o cubierta de nieve.  \nHaga revisar el vehículo por un Servicio Autorizado si este indicador permanece Activado.",
	"FOWMRCCRadarSoilingShrt" : "Fallo en el Radar FOW/MRCC",
	"FOWSysError" : "Fallo en el FOW",
	"FOWSysErrorLong" : "Fallo en el Forward Obstruction Warning (FOW).\nHaga revisar el vehículo por un Servicio Autorizado.",
	"FWDSysErrorLong" : "Fallo en el sistema de tracción en las cuatro ruedas (4WD) o el tamaño de neumáticos delanteros y traseros es diferente.\nHaga revisar el vehículo por un Servicio Autorizado.",
	"FWDSysErrorShrt" : "Fallo en el Sistema 4WD",
	"FuelAirFilterCartReplacePeriodLong" : "Es necesario cambiar el cartucho del filtro de combustible.",
	"FuelAirFilterCartReplacePeriodShrt" : "Se requiere cambiar el filtro del combustible.",
	"FuelCapInspectionLong" : "El tapón del deposito podría no estar cerrado correctamente. Compruebe que el  tapón del deposito esta correctamente colocado y apretado. Tras cerrar y apretar correctamente el tapón de combustible, el indicador no se apagará hasta confirmar que el sistema funciona correctamente. Haga revisar el vehículo por un Servicio Autorizado Mazda si este indicador permanece activado.",
	"FuelCapInspectionShrt" : "Inspecc Tapa Comb",
	"HBCALHUnavailableLong_1" : "El High Beam Control se ha desactivado temporalmente debido a un exceso de temperatura en el habitáculo. El High Beam Control se activará una vez que la temperatura del habitáculo se haya reducido lo suficiente.",
	"HBCALHUnavailableLong_2" : "Las Adaptive LED Headlights se han desactivado temporalmente debido a un exceso de temperatura en el habitáculo. Las Adaptive LED Headlights se activarán una vez que la temperatura del habitáculo se haya reducido lo suficiente.",
	"HBCALHUnavailableShrt_1" : "HBC no disponible",
	"HBCALHUnavailableShrt_2" : "ALH no disponible",
	"HBCLDWSSysErrorLong" : "Fallo en High Beam Control (HBC)* y/o Lane Departure Warning System (LDWS)*. Lleve el vehículo a un proveedor autorizado para su revisión si el indicador permanece encendido.\n*La existencia de estas funciones depende del modelo o niveles de accesorios.",
	"HBCLDWSSysErrorLong_2" : "Fallo en el sistema de High Beam Control (HBC)/Lane-keep Assist System (LAS). Haga revisar el vehículo por un Servicio Autorizado si este indicador permanece activado.",
	"HBCLDWSSysErrorLong_3" : "Fallo en el sistema de Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS). Haga revisar el vehículo por un Servicio Autorizado si este indicador permanece activado.",
	"HBCLDWSSysErrorLong_4" : "Fallo en el sistema de Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS). Haga revisar el vehículo por un Servicio Autorizado si este indicador permanece activado.",
	"HBCLDWSSysErrorShrt" : "Fallo en el Sistema HBC/LDWS",
	"HBCLDWSSysErrorShrt_2" : "Fallo en el Sistema HBC/LAS",
	"HBCLDWSSysErrorShrt_3" : "Fallo en el Sistema ALH/LDWS",
	"HBCLDWSSysErrorShrt_4" : "Fallo en el Sistema ALH/LAS",
	"HBCLDWSWindshieldFogLong" : "Fallo en High Beam Control (HBC)* y/o Lane Departure Warning System (LDWS)*. Desempañe el parabrisas.  Lleve el vehículo a un proveedor autorizado para su revisión si el indicador permanece encendido.\n*La existencia de estas funciones depende del modelo o niveles de accesorios.",
	"HBCLDWSWindshieldFogLong_2" : "Fallo en el sistema de High Beam Control (HBC)/Lane-keep Assist System (LAS). Desempañe el parabrisas. Haga revisar el vehículo por un Servicio Autorizado si este indicador permanece activado.",
	"HBCLDWSWindshieldFogLong_3" : "Fallo en el sistema de Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS). Desempañe el parabrisas. Haga revisar el vehículo por un Servicio Autorizado si este indicador permanece activado.",
	"HBCLDWSWindshieldFogLong_4" : "Fallo en el sistema de Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS). Desempañe el parabrisas. Haga revisar el vehículo por un Servicio Autorizado si este indicador permanece activado.",
	"HBCLDWSWindshieldFogShrt" : "Fallo en el Sistema HBC/LDWS",
	"HBCLDWSWindshieldFogShrt_2" : "Fallo en el Sistema HBC/LAS",
	"HBCLDWSWindshieldFogShrt_3" : "Fallo en el Sistema ALH/LDWS",
	"HBCLDWSWindshieldFogShrt_4" : "Fallo en el Sistema ALH/LAS",
	"HBCLLDWSCamDisconnectLong" : "Fallo en High Beam Control (HBC)* y/o Lane Departure Warning System (LDWS)*. Limpie el parabrisas.  Lleve el vehículo a un proveedor autorizado para su revisión si el indicador permanece encendido.\n*La existencia de estas funciones depende del modelo o niveles de accesorios.",
	"HBCLLDWSCamDisconnectLong_2" : "Fallo en el sistema de High Beam Control (HBC)/Lane-keep Assist System (LAS). Limpie el parabrisas. Haga revisar el vehículo por un Servicio Autorizado si este indicador permanece activado.",
	"HBCLLDWSCamDisconnectLong_3" : "Fallo en el sistema de Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS). Limpie el parabrisas.  Haga revisar el vehículo por un Servicio Autorizado si este indicador permanece activado",
	"HBCLLDWSCamDisconnectLong_4" : "Fallo en el sistema de Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS). Limpie el parabrisas. Haga revisar el vehículo por un Servicio Autorizado si este indicador permanece activado.",
	"HBCLLDWSCamDisconnectShrt" : "Fallo en la Cámara HBC/LDWS",
	"HBCLLDWSCamDisconnectShrt_2" : "Fallo en la Cámara HBC/LAS",
	"HBCLLDWSCamDisconnectShrt_3" : "Fallo en la Cámara ALH/LDWS",
	"HBCLLDWSCamDisconnectShrt_4" : "Fallo en la Cámara ALH/LAS",
	"HBCSysErrorLong" : "Fallo en el High Beam Control (HBC).\nHaga revisar el vehículo por un Servicio Autorizado.\n",
	"HBCSysErrorLong_2" : "Fallo en el Adaptive LED Headlights (ALH). Haga revisar el vehículo por un Servicio Autorizado.",
	"HBCSysErrorShrt" : "Fallo en el HBC",
	"HBCSysErrorShrt_2" : "Fallo en el ALH",
	"HbcOrAlhUnavailable" : "HBC o ALH no disponible",
	"HeadlightSystemErrorLongJ03" : "Ha ocurrido un fallo en el sistema de faros Si la luz de aviso parpadea continuamente, acuda a su concesionario Mazda.",
	"HighEngineOillevel" : "Nivel de aceite del motor alto",
	"HighEngineOillevelDetail" : "El nivel de aceite del motor es demasiado alto. Es necesario cambiar el aceite.",
	"HybrdSysMalHighPrt" : "Fallo del Sistema Híbrido. Detenga el vehículo inmediatamente en un lugar seguro.",
	"HybridSysErrorLong" : "Fallo en el Sistema Híbrido. El vehículo podría dañarse si continua circulando. Detenga el vehículo inmediatamente en una zona segura y haga revisar el vehículo por un Servicio Autorizado Mazda.",
	"HybridSysErrorShrt" : "Fallo del Sistema Híbrido",
	"HybridSysOverheatLong" : "Fallo en el Sistema Híbrido. El vehículo podría dañarse si continua circulando. Detenga el vehículo inmediatamente en una zona segura y haga revisar el vehículo por un Servicio Autorizado Mazda.",
	"HybridSysOverheatShrt" : "Sobrecalentamiento Sist. Híbrido",
	"IeloopChrgHighPrt" : "Cargando i‑ELOOP. Con motor en marcha, revise que la carga esté completa y el indicador de advertencia esté apagado.",
	"IstopSysErrorLong" : "No es posible el funcionamiento del sistema i‑stop.\nHaga revisar su vehículo por un Servicio Autorizado Mazda.",
	"IstopSysErrorShrt" : "Fallo en el Sistema i‑stop",
	"KeylesSysErrorLong" : "Fallo en el cierre centralizado. Haga revisar el vehículo por un Servicio Autorizado.",
	"KeylesSysErrorShrt" : "Fallo en el Acceso sin Llave",
	"LDWSLASUnavailableLong_1" : "El Lane Departure Warning System se ha desactivado temporalmente debido a un exceso de temperatura en el habitáculo. El Lane Departure Warning System se activará una vez que la temperatura del habitáculo se haya reducido lo suficiente.",
	"LDWSLASUnavailableLong_2" : "El Lane-Keep Assist System se ha desactivado temporalmente debido a un exceso de temperatura en el habitáculo. El Lane-Keep Assist System se activará una vez que la temperatura del habitáculo se haya reducido lo suficiente.",
	"LDWSLASUnavailableShrt_1" : "LDWS no disponible",
	"LDWSLASUnavailableShrt_2" : "LAS no disponible",
	"LDWSSysErrorLong" : "Fallo en el sistema de Lane Departure Warning System (LDWS).\nHaga revisar el vehículo por un Servicio Autorizado.\n",
	"LDWSSysErrorLong_2" : "Fallo en el sistema de Lane-keep Assist System (LAS). Haga revisar el vehículo por un Servicio Autorizado.",
	"LDWSSysErrorShrt" : "Fallo en el LDWS",
	"LDWSSysErrorShrt_2" : "Fallo en el sistema de LAS",
	"LdwsOrLasUnavailable" : "LDWS o LAS no disponible",
	"LowBrakeFluidLong" : "El nivel de líquido de frenos está bajo.\nDetenga el vehículo inmediatamente en un lugar seguro y haga revisar el vehículo por un Servicio Autorizado Mazda.",
	"LowBrakeFluidShrt" : "Líquido de Frenos Bajo",
	"LowEngineOillevel" : "Nivel de aceite del motor bajo",
	"LowEngineOillevelDetail" : "El nivel de aceite del motor es demasiado bajo.  Es necesario añadir aceite.",
	"LowFuelLong" : "El nivel de combustible es bajo. Reposte el vehículo lo más pronto posible.",
	"LowFuelShrt" : "Combustible bajo",
	"LowTireAirPressureFlatLong" : "Si la presión de los neumáticos disminuye en exceso después de que la luz de aviso TPMS se encienda, o si se pincha un neumático, la luz de aviso de neumático desinchado también se enciende. Si se pincha un neumático Runflat, conduzca con cuidado su vehículo hasta el concesionario Mazda más cercano y haga que cambien el neumático.",
	"LowTireAirPressureLong" : "Presión de aire de neumáticos baja en una o más ruedas.\nRevise la presión de aire de los neumáticos y ajústela a la presión de aire correcta.  Oprima el interruptor TPMS SET después de ajustar la presión del neumático hasta que escuche un pitido.",
	"LowTireAirPressureShrt" : "Baja presión de aire en los neumáticos",
	"LowWasheFluidLong" : "El nivel de líquido limpiador está bajo.\nVuelva a llenar el líquido limpiador.\n",
	"LowWasheFluidShrt" : "Líquido de Limpiaparabrisas Bajo",
	"MRCCSysErrorLong" : "Fallo en el Mazda Radar Cruise Control (MRCC).\nHaga revisar el vehículo por un Servicio Autorizado.",
	"MRCCSysErrorShrt" : "Fallo en el MRCC",
	"MRCCUnavailableLong" : "El Mazda Radar Cruise Control (MRCC)  no está disponible en estos momentos.",
	"MRCCUnavailableShrt" : "MRCC No disponible",
	"NoWarnings" : "No hay Advertencias",
	"OilLevelSystemMalfunctioning" : "Error en el sensor de nivel de aceite del motor",
	"OilLevelSystemMalfunctioningDetail" : "Hay un fallo en el sensor de nivel de aceite del motor.  Por favor, revise el vehículo en un concesionario Mazda. ",
	"PowerSteeringSysErrorLong" : "Fallo en la dirección asistida eléctrica.\nDetenga el vehículo en un lugar seguro y apague el motor.  Haga revisar el vehículo por un Servicio Autorizado si este indicador permanece Activado.",
	"PowerSteeringSysErrorShrt" : "Fallo Sist. Direc. Asistida",
	"PpositionRequestLong" : "Cambie la transmisión a Parking.\nEsto es causado por una de los siguientes motivos:\n· El sistema de batería se inicio o se detuvo con la transmsión en una posición distinta de Parking\n· La puerta del conductor se abrió con la transmisión en posición N, D, o B\n· La carga restante de la batería de alto voltaje es baja debido a que la transmisión se ha mantenido en posición Neutra por un largo período de tiempo\nReinicie el sistema híbrido pulsando el interruptor de arranque en caso necesario.",
	"PpositionRequestShrt" : "Solicitud Posic Aparcamiento",
	"PreheatingDispLampLong" : "Precalentamiento de Bujías Incandescentes.\nHaga revisar el vehículo por un Servicio Autorizado si este indicador permanece activado.\n",
	"PreheatingDispLampShrt" : "Precalent. Bujías Incandesc.",
	"RoadSurfaceIcingCautionLong" : "La temperatura exterior es de 4ºC o menos. Tenga cuidado. Posible formación de hielo en la carretera.",
	"RoadSurfaceIcingCautionShrt" : "Caución Carretera con Hielo",
	"RvmSysErrorLong" : "Hay un error en el sistema RVM.\nVerifique si hay anomalías en la superficie del  paragolpes trasero, y limpielo si está sucio o cubierto con nieve.\nHaga revisar el vehículo por un Servicio Autorizado Mazda si este testigo de aviso permanece activado.",
	"RvmSysErrorShrt" : "Fallo de RVM",
	"SBSBrakeMRCCUnavailableLong" : "El sistema de frenos SBS/MRCC no está disponible en estos momentos.",
	"SBSBrakeMRCCUnavailableShrt" : "Frenos SBS/MRCC No Dispon.",
	"SBSBrakeUnavailableLong" : "El sistema de frenos SBS no está disponible en estos momentos.",
	"SBSBrakeUnavailableShrt" : "Frenos SBS No Disponibles",
	"SBSMRCCDRSSRadarSoilingLong" : "El sensor SBS/MRCC/DRSS está sucio.\nLimpie toda la superficie del sensor.",
	"SBSMRCCDRSSRadarSoilingShrt" : "Fallo Radar SBS/MRCC/DRSS",
	"SBSMRCCRadarSoilingLong" : "El sensor SBS/MRCC está sucio.\nLimpie toda la superficie del sensor.",
	"SBSMRCCRadarSoilingShrt" : "Fallo en el Radar SBS/MRCC",
	"SBSSysErrorLong" : "Hay un error en el sistema SBS.\nHaga revisar su vehículo con un Servicio Autorizado Mazda.",
	"SBSSysErrorShrt" : "Fallo en el SBS",
	"SCBSSysErrorLong" : "Fallo en el sistema de Smart City Brake Support (SCBS).\nHaga revisar el vehículo por un Servicio Autorizado inmediatamente.",
	"SCBSSysErrorLong_105" : "Fallo en el sistema de Smart City Brake Support(SCBS). Desempañe el parabrisas. Haga revisar el vehículo por un Servicio Autorizado si este indicador permanece activado.",
	"SCBSSysErrorShort_105" : "Fallo en el SCBS",
	"SCBSSysErrorShrt" : "Fallo en el SCBS",
	"SCBSUnavailableLong" : "El sistema de Smart City Brake Support (SCBS) no está disponible en estos momentos.",
	"SCBSUnavailableLong1" : "El sistema Smart City Brake Support se ha desactivado temporalmente debido a un exceso de temperatura en el habitáculo. El sistema Smart City Brake Support se activará una vez que la temperatura del habitáculo se haya reducido lo suficiente.",
	"SCBSUnavailableShrt" : "SCBS no disponible",
	"SCBSUnavailableShrt1" : "SCBS no disponible",
	"SCBSWindshieldSoilingLong" : "Fallo en el sistema de Smart City Brake Support (SCBS).\nLimpie el parabrisas delantero.  Haga revisar el vehículo por un Servicio Autorizado si este indicador permanece activado.",
	"SCBSWindshieldSoilingShrt" : "Fallo en el SCBS",
	"SCRMalfunction100Long" : "Fallo de SCR de emisiones diésel.\nSi no se aborda el problema, se limitará la velocidad del vehículo.",
	"SCRMalfunction101Long" : "Fallo de SCR de emisiones diésel.\nSi no se aborda el problema, se pasará el motor al modo de ralentí forzado.",
	"SCRMalfunction102Long" : "Fallo de SCR de emisiones diésel. El motor se encuentra ahora en el modo de ralentí forzado.\nPóngase en contacto con el concesionario de Mazda para recibir asistencia.",
	"ScrMalfunction" : "Fallo del SCR",
	"SedimenterWarningLong" : "La cantidad de agua acumulada en el sedimentador excede la cantidad nominal.\nHaga revisar el vehículo por un Servicio Autorizado si este indicador permanece activado.\n",
	"SedimenterWarningShrt" : "Inspección del Sedimentador",
	"SystemInspectionLong" : "La temperatura del aceite del diferencial es excesivamente alta o la diferencia de giro entre las ruedas delanteras y traseras es excesiva (como cuando intenta salir del barro). Detenga el vehículo en un lugar seguro y vuelva a conducir después de que el indicador de alarma se apague. Haga revisar el vehículo por un Servicio Autorizado Mazda si este indicador permanece activado.",
	"SystemInspectionShrt" : "Inspección del Sistema 4WD",
	"TpmsSysErrorLong" : "Fallo en el sistema de control de presión de neumáticos (TPMS).\nHaga revisar el vehículo por un Sercvicio Autorizado.",
	"TpmsSysErrorShrt" : "Fallo Sist. TPMS",
	"VehicleSysErrorLong" : "Fallo de  sistema en el vehículo.\nHaga revisar el vehículo por un Servicio Autorizado.\n",
	"VehicleSysErrorShrt" : "Fallo en el Sistema del Vehículo",
	"WarningGuidance" : "Guía de advertencia",
	"WarningSafetyMessage" : "Por motivos de seguridad, la Guía de Advertencia no se muestra en la pantalla.",
	"Warnings" : "Advertencias",
	"brakeFluid" : "Nivel de líquido de frenos bajo",
	"engineOilPressure" : "Presión del aceite del motor",
	"highVoltage" : "Batería de alto voltaje baja",
	"lowBattStartEngine" : "¡Batería baja! ¡Arranque el motor!",
};

framework.registerAppDictLoaded("warnguide", "es_ES");