var Localization_warnguideAppDict_ar_SA = {
	//"stringId" : "localString"
	"AbsSysErrorLong" : "يوجد خلل في نظام منع إنغلاق المكابح (ABS).\nاحرص على قيام الموزع بفحص المركبة على الفور.\n",
	"AbsSysErrorShrt" : "خلل بنظام ABS",
	"AbsSystemErrorLong" : "يوجد خلل في نظام منع إنغلاق المكابح (ABS).\nاحرص على قيام الموزع بفحص المركبة على الفور.\n",
	"AbsSystemErrorShrt" : "خلل بنظام ABS",
	"AccumulationDpfLong" : "الجسيمات المتجمعة (PM) في مرشح الجسيمات الذي يعمل بالديزل (DPF) تجاوزت قيمة النظم.\nاحرص على القيادة لمدة تتراوح ما بين 10 إلى 15 دقيقة مع تسخين المحرك بالكامل (على أن يكون ضوء درجة الحرارة الأزرق مطفئًا) على سرعة 10 متر في الساعة (15 كم/ساعة) أو أكثر لإزالة الجسيمات.  احرص على قيام الموزع بفحص المركبة في حالة استمرار هذا المؤشر قيد التشغيل.\n",
	"AccumulationDpfShrt" : "تراكم PM في DPF",
	"ActiveBonnetSystemMalfunctionLong" : "خلل في نظام Active Bonnet.\nافحص المحرك بواسطة الوكيل في حالة بقاء أو استمرار وميض هذا المؤشر.",
	"ActiveBonnetSystemMalfunctionShrt" : "خلل في نظام Active Bonnet",
	"AfsSystemErrorLong" : "يوجد خلل في نظام الإضاءة الأمامية المهايئ (AFS). احرص على قيام الموزع بفحص المركبة في حالة استمرار هذا المؤشر في الوميض.",
	"AfsSystemErrorShrt" : "خلل بنظام AFS",
	"AfterRunCoolingPumpLong" : "اتصل بالموزع أو قم بزيارته للحصول على خدمات الصيانة في حالة ارتفاع حرارة سيارة Mazda. ",
	"AfterRunCoolingPumpShrt" : "بعد تشغيل مضخة التبريد",
	"AirbagSysPretensionerSysErrorLong" : "يوجد خلل في الوسادة الهوائية/حزام الأمان.\nاحرص على قيام الموزع بفحص المركبة على الفور.\n",
	"AirbagSysPretensionerSysErrorShrt" : "خلل بنظام وسادة الهواء/آلية الشد",
	"AutoLevelSystemErrorLong" : "خلل في نظام ضبط المستوى التلقائي للمصابيح الأمامية.\nاحرص على قيام الموزع بفحص المركبة في حالة استمرار هذا المؤشر قيد التشغيل.",
	"AutoLevelSystemErrorShrt" : "خلل بنظام التسوية الآلية",
	"AutoLevelSystemErrorShrtJ03" : "تعطل نظام الأضواء الأمامية",
	"AutoTransSysErrorLong" : "خلل في النقل التلقائي.\nقد تحدث تلفيات في المركبة حال مواصلتك القيادة.  احرص على قيام الموزع بفحص المركبة على الفور.\n  ",
	"AutoTransSysErrorShrt" : "خلل في ناقل الحركة التلقائي",
	"AuxBattLowLong" : "شحن بطارية 12V منخفض.\n· إذا كان هذا المؤشر قيد التشغيل باستمرار أثناء القيادة، فقد تفسد البطارية. احرص على قيام الموزع بفحص المركبة.\n· إذا كان هذا المؤشر قيد التشغيل باستمرار دون توقف، فإن بطارية 12V قد تلفت. يرجى الرجوع إلى دليل المالك قبل تشغيل نظام الهجين واحرص على قيام الموزع بفحص المركبة.",
	"AuxBattLowShrt" : "شحن البطارية 12V منخفض",
	"BattManagSysErrorLong" : "يوجد خلل في نظام إدارة البطارية.\nاحرص على قيام الموزع بفحص المركبة.\n",
	"BattManagSysErrorShrt" : "خلل في نظام إدارة البطارية",
	"BrakOverrideSysErrorLong" : "خلل في المفتاح الكهربائي للمكابح.\nاحرص على قيام الموزع بفحص المركبة على الفور.\n",
	"BrakOverrideSysErrorShrt" : "خلل في نظام الفرملة المهيمنة",
	"BrakeSysErrorLong" : "مستوى سائل المكابح منخفض أو يوجد خلل في نظام المكابح.  أوقف المركبة على الفور في مكان آمن واحرص على قيام الموزع بفحص المركبة.",
	"BrakeSysErrorShrt" : "خلل في نظام المكابح",
	"BrakeSystemErrorLong" : "يوجد خلل في نظام المكابح إلكتروني التحكم.\nأوقف المركبة على الفور في مكان آمن واحرص على قيام الموزع بفحص المركبة.\n",
	"BrakeSystemErrorShrt" : "خلل في نظام المكابح",
	"BsmSystemErrorLong" : "خلل في Blind Spot Monitoring (BSM)/Rear Cross Traffic Alert (RCTA)\u200e . تحقق من عدم وجود خلل في سطح المصد الخلفي ونظفه إذا كان متسخًا أو مغطى بالثلج. احرص على قيام الموزع بفحص المركبة في حالة استمرار هذا المؤشر قيد التشغيل.\n",
	"BsmSystemErrorShrt" : "خلل في BSM",
	"ChargSysMalHighPrt" : "خلل في نظام الشحن.  أوقف المركبة على الفور في مكان آمن.",
	"ChargingSysErrorLong" : "يوجد خلل في نظام الشحن. \nقد تحدث تلفيات في المركبة حال مواصلتك القيادة.  أوقف المركبة على الفور في مكان آمن واحرص على قيام الموزع بفحص المركبة.\n",
	"ChargingSysErrorShrt" : "خلل في نظام الشحن",
	"ChrgSysErrorLong" : "يوجد خلل في نظام الشحن.\nأوقف المركبة على الفور في مكان آمن واحرص على قيام الموزع بفحص المركبة.\n",
	"ChrgSysErrorShrt" : "خلل في نظام الشحن",
	"ColdStartDisableLong" : "أثناء البرودة الشديدة، يتم توقف تدوير المحرك لمنع تلفه. يُرجى مراجعة دليل المالك. يمكنك تجنب التأخير المحتمل عند بدء تشغيل سيارة Mazda عن طريق توصيل سخان كتلة المحرك.",
	"ColdStartDisableShrt" : "تم تعطيل البدء على البارد",
	"ControlSystemErrorLong" : "خلل في نظام التحكم في وضع الوقوف التام.\nفي حالة تركه دون فحص، فمن الممكن أن يؤدي إلى أي من التالي:\n• قد لا تعمل آلية قفل الوقوف التام. احرص على صف السيارة في مكانٍ مستوٍ واضبط فرملة اليد بإحكام.\n• قد يتعذر إيقاف تشغيل مفتاح الطاقة. اضغط على مفتاح الطاقة بشكل متكرر لإيقاف التشغيل.\n• ستختفي شاشة \"اضبط فرامل اليد عند صف السيارة\" عند القيادة وستظهر عند التوقف.\nاحرص على قيام الموزع بفحص المركبة على الفور.",
	"ControlSystemErrorShrt" : "خلل بنظام التحكم بوضع الوقوف التام",
	"DPFErrorLong" : "حدث خلل في مرشح الجسيمات الذي يعمل بالديزل (DPF).\nاحرص على قيام الموزع بفحص المركبة.\n",
	"DPFErrorShrt" : "خطأ في DPF",
	"DRSSSysErrorLong" : "يوجد خطأ في نظام DRSS.\nاحرص على أن يتم فحص سيارتك لدى أحد موزعي Mazda.\n",
	"DRSSSysErrorShrt" : "خلل بنظام DRSS",
	"DefEmpty" : "DEF فارغ",
	"DefLow" : "DEF منخفض",
	"DefVeryLow" : "DEF منخفض للغاية",
	"DriveBattDropLong" : "الطاقة المتبقية في البطارية ذات الجهد العالي منخفضة وذلك لضبط ناقل الحركة على وضع محايد لفترة طويلة. الشحن غير ممكن في الوضع المحايد. اضبط ناقل الحركة على وضع الوقوف التام عند التوقف لفترة طويلة. أعد تشغيل نظام الهجين عن طريق الضغط على مفتاح الطاقة إذا لزم الأمر.",
	"DriveBattDropShrt" : "انخفض شحن بطارية ج.ع",
	"DropKeyBattChrgLong" : "شحن البطارية الأساسية منخفض.\nاستبدل البطارية الأساسية على الفور.\n",
	"DropKeyBattChrgShrt" : "شحن البطارية الرئيسية منخفض",
	"DscSysErrorLong" : "يوجد خلل في (Dynamic Stability Control  (DSC  أو(Traction Control System (TCS  أو نظام المساعدة Hill Launch Assist   (HLA).\r\nاحرص على قيام الموزع بفحص المركبة على الفور.\n",
	"DscSysErrorShrt" : "خلل بنظام DSC",
	"DscSystemErrorLong" : "يوجد خلل في نظام التحكم الديناميكي في الثبات (DSC) أو نظام مانع الانزلاق (TCS).\nاحرص على قيام الموزع بفحص المركبة على الفور.\n",
	"DscSystemErrorShrt" : "خلل بنظام DSC",
	"EcbSysErrorLong" : "يوجد خلل في نظام كبح الاسترجاع أو نظام المكابح إلكتروني التحكم.\nأوقف المركبة على الفور في مكان آمن واحرص على قيام الموزع بفحص المركبة.\n",
	"EcbSysErrorShrt" : "خلل في نظام المكابح",
	"ElectricParkingBrakeHighLong" : "حدث عطل في نظام فرامل الوقوف.\nاستشر وكيل Mazda للفحص.",
	"ElectricParkingBrakeLong" : "حدث عطل في نظام فرامل الوقوف.\nاستشر وكيل Mazda للفحص.",
	"ElectricParkingBrakeShrt" : "تعطل نظام فرامل الوقوف",
	"ElectricVacuumPumpSystemMalfunctionLong" : "حدث عطل في نظام مضخة التفريغ الكهربائية.\nرك هذا الخلل بدون تصليح قد يسبب عدم تشغيل النظام، مما سيتسبب في خطر أو عطل غير متوقعين. \nاستشر وكيل Mazda على الفور لفحص الخلل.",
	"ElectricVacuumPumpSystemMalfunctionShrt" : "تعطل نظام مضخة التفريغ الكهربائية",
	"ElectronicThrottleControlLong" : "إذا ظل مصباح التحذير مضيئًا، فإن هناك عطل في وحدة التحكم الإلكتروني.قم بإعادة تشغيل محرك Mazda لإعادة ضبط وحدة التحكم الإلكتروني، أو خذ السيارة إلى الموزع للصيانة.\n\n  في حالة وميض مصباح التحذير، هذا يعني حدوث عطل كبير، وسوف يكون خرج الخانق محدودًا.  اصطحب السيارة إلى الموزع للصيانة بأسرع ما يمكن.  حاول إعادة ضبط وحدة التحكم الإلكتروني عن طريق إعادة تشغيل المحرك. \n",
	"ElectronicThrottleControlShrt" : "التحكم في الخانق الإلكتروني",
	"EloopChargingLong" : "جارٍ شحن i‑ELOOP.\nتأكد أثناء تشغيل المحرك من أن الشحن مكتمل وكذلك من ضبط مؤشر التحذير على وضع إيقاف التشغيل. احرص على قيام الموزع بفحص المركبة في حالة استمرار هذا المؤشر قيد التشغيل.\n",
	"EloopChargingShrt" : "يتم شحن i‑ELOOP",
	"EloopSysErrorLong" : "يوجد خلل في نظام i‑ELOOP.\nاحرص على قيام الموزع بفحص المركبة في حالة استمرار هذا المؤشر قيد التشغيل.\n",
	"EloopSysErrorShrt" : "خلل في نظام i‑ELOOP",
	"EngCoolntTempHighOnLong" : "سخونة المحرك مفرطة.\nأوقف المركبة على الفور في مكان آمن وأوقف المحرك واتخذ الإجراءات الملائمة.  يرجى الرجوع إلى كتيب المالك.\n",
	"EngCoolntTempHighOnShrt" : "حرارة مبرد المحرك مرتفعة",
	"EngOilPressureErrorLong" : "ضغط زيت المحرك منخفض.\nأوقف المركبة على الفور في مكان آمن وأوقف المحرك وتفحص مستوى الزيت في المحرك. أضف الزيت عند الحاجة.\nاحرص على قيام الموزع بفحص المركبة على الفور في حالة انتقال المؤشر إلى وضع التشغيل بعد إضافة الزيت أو إذا كان مستوى زيت المحرك جيد.\n",
	"EngOilPressureErrorShrt" : "ضغط زيت المحرك منخفض",
	"EngSystemErrorLong" : "خلل في نظام المحرك.  احرص على قيام الموزع بفحص المركبة على الفور.",
	"EngSystemErrorShrt" : "خلل في نظام المحرك",
	"EngineOilPressureErrorLong" : "ضغط زيت المحرك منخفض.\nأوقف المركبة على الفور في مكان آمن وأوقف المحرك وتفحص مستوى الزيت في المحرك. أضف الزيت عند الحاجة.\nاحرص على قيام الموزع بفحص المركبة على الفور في حالة انتقال المؤشر إلى وضع التشغيل بعد إضافة الزيت أو إذا كان مستوى زيت المحرك جيد.\n",
	"EngineOilPressureErrorShrt" : "ضغط زيت المحرك منخفض.",
	"EngineWaterTempDropLong" : "سائل تبريد المحرك بارد ولا يوجد هواء دافئ في السخان/جهاز إذابة الصقيع. يمكن قيادة المركبة مع ضبط المؤشر على تشغيل أو إيقاف.  احرص على قيام الموزع بفحص المركبة إذا ظل هذا المؤشر قيد التشغيل.",
	"EngineWaterTempDropShrt" : "حرارة مبرد المحرك منخفضة",
	"EngineWaterTempRiseLong" : "بدأت حرارة المحرك في الارتفاع.\nاحرص على القيادة ببطء أو إيقاف المركبة حتى يتوقف المؤشر عن الوميض. فإذا استمر في الوميض، حتى بعد إيقاف المركبة، عليك باتخاذ الإجراءات الملائمة. يرجى الرجوع إلى كتيب المالك.\n",
	"EngineWaterTempRiseShrt" : "حرارة مبرد المحرك مرتفعة",
	"EngnCoolTempHighHighPrt" : "درجة حرارة سائل تبريد المحرك مرتفعة. أوقف المركبة على الفور في مكان آمن.",
	"FOWMRCCDRSSRadarSoilingLong" : "رادار (مستشعر) FOW/MRCC/DRSS متسخ.\nنظف سطح الرادار (المستشعر) بالكامل.\n",
	"FOWMRCCDRSSRadarSoilingShrt" : "خلل برادار FOW/MRCC/DRSS",
	"FOWMRCCRadarSoilingLong" : "يوجد خلل في نظام رادار (مستشعر) FOW/MRCC.\nنظف سطح شبكة شعار السيارة الأمامي بالكامل إذا كان متسخًا أو مغطى بالثلج.  \nاحرص على قيام الموزع بفحص المركبة في حالة بقاء هذا المؤشر قيد التشغيل.\n",
	"FOWMRCCRadarSoilingShrt" : "خلل برادار MRCC/FOW",
	"FOWSysError" : "خلل بنظام FOW",
	"FOWSysErrorLong" : "خلل في نظام Forward Obstruction Warning (FOW)\u200e.\nاحرص على قيام الموزع بفحص المركبة.\n",
	"FWDSysErrorLong" : "الخلل في نظام 4WD أو حجم الإطار يختلف فيما بين الإطارات الأمامية والخلفية.\nاحرص على قيام الموزع بفحص المركبة.\n",
	"FWDSysErrorShrt" : "خلل في نظام 4WD",
	"FuelAirFilterCartReplacePeriodLong" : "يلزم استبدال خرطوشة فلتر الوقود.",
	"FuelAirFilterCartReplacePeriodShrt" : "يلزم استبدال فلتر الوقود",
	"FuelCapInspectionLong" : "قد يكون غطاء الوقود غير مثبت على النحو الصحيح.\nتأكد من تثبيت غطاء الوقود وإحكامه على النحو الصحيح.\nبعد تثبيت غطاء الوقود وإحكامه على النحو الصحيح، لن يتوقف هذا المؤشر على مدى عدة دورات للمحرك حتى يتم التأكيد على أن النظام قد أصبح جيدًا.  احرص على قيام الموزع بفحص المركبة في حالة استمرار هذا المؤشر قيد التشغيل.\n",
	"FuelCapInspectionShrt" : "فحص غطاء الوقود",
	"HBCALHUnavailableLong_1" : "تم تعطيل High Beam Control مؤقتًا نتيجة الحرارة الزائدة في مقصورة الركاب. سيتم تعطيل High Beam Control بمجرد تبريد مقصورة الركاب بشكل كافٍ.",
	"HBCALHUnavailableLong_2" : "تم تعطيل Adaptive LED Headlights مؤقتًا نتيجة الحرارة الزائدة في مقصورة الركاب. سيتم تعطيل Adaptive LED Headlights بمجرد تبريد مقصورة الركاب بشكل كافٍ.",
	"HBCALHUnavailableShrt_1" : "HBC غير متوفر",
	"HBCALHUnavailableShrt_2" : "ALH غير متوفر",
	"HBCLDWSSysErrorLong" : "خلل في نظام High Beam Control (HBC)*\u200e و / أوLane Departure Warning System (LDWS)*\u200e. اطلب من تاجر فحص المركبة إذا استمر هذا المؤشر قيد التشغيل.\n*يعتمد تواجد هذه السمات على الطرازات / مستويات الحواف.",
	"HBCLDWSSysErrorLong_2" : "عطل في High Beam Control (HBC)/Lane-keep Assist System (LAS)\u200e. يجب فحص المركبة من قبل الوكيل في حالة إضاءة المؤشر بشكلٍ مستمر.",
	"HBCLDWSSysErrorLong_3" : "عطل في نظام Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS)\u200e. يجب فحص المركبة من قبل الوكيل في حالة إضاءة المؤشر بشكلٍ مستمر.",
	"HBCLDWSSysErrorLong_4" : "عطل في Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS)\u200e. يجب فحص المركبة من قبل الوكيل في حالة إضاءة المؤشر بشكلٍ مستمر.",
	"HBCLDWSSysErrorShrt" : "خلل في نظام HBC/ LDWS",
	"HBCLDWSSysErrorShrt_2" : "خلل في نظام HBC/LAS",
	"HBCLDWSSysErrorShrt_3" : "خلل في نظام ALH/LDWS",
	"HBCLDWSSysErrorShrt_4" : "خلل في نظام ALH/LAS",
	"HBCLDWSWindshieldFogLong" : "خلل في نظام High Beam Control (HBC)*\u200e و / أو Lane Departure Warning System (LDWS)*\u200e. أزل الجليد عن الزجاج الأمامي.  اطلب من تاجر فحص المركبة إذا استمر هذا المؤشر قيد التشغيل.\n*يعتمد تواجد هذه السمات على الطرازات / مستويات الحواف.",
	"HBCLDWSWindshieldFogLong_2" : "عطل في High Beam Control (HBC)/Lane-keep Assist System (LAS)\u200e. أزل الجليد عن الزجاج الأمامي. يجب فحص المركبة من قبل الوكيل في حالة إضاءة المؤشر بشكلٍ مستمر.",
	"HBCLDWSWindshieldFogLong_3" : "عطل في Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS)\u200e. أزل الجليد عن الزجاج الأمامي. يجب فحص المركبة من قبل الوكيل في حالة إضاءة المؤشر بشكلٍ مستمر.",
	"HBCLDWSWindshieldFogLong_4" : "عطل في Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS)\u200e. أزل الجليد الزجاج الأمامي. يجب فحص المركبة من قبل الوكيل في حالة إضاءة المؤشر بشكلٍ مستمر.",
	"HBCLDWSWindshieldFogShrt" : "خلل في نظام HBC/ LDWS",
	"HBCLDWSWindshieldFogShrt_2" : "خلل في نظام HBC/LAS",
	"HBCLDWSWindshieldFogShrt_3" : "خلل في نظام ALH/LDWS",
	"HBCLDWSWindshieldFogShrt_4" : "خلل في نظام ALH/LAS",
	"HBCLLDWSCamDisconnectLong" : "خلل في نظام High Beam Control (HBC)*\u200e و / أو Lane Departure Warning System (LDWS)*\u200e.\n نظّف الزجاج الأمامي.  احرص على قيام الموزع بفحص المركبة في حالة استمرار هذا المؤشر قيد التشغيل.\n*يعتمد تواجد هذه السمات على الطرازات / مستويات الحواف.",
	"HBCLLDWSCamDisconnectLong_2" : "عطل في نظام High Beam Control (HBC)/Lane-keep Assist System (LAS)\u200e . قم بتنظيف الزجاج الأمامي. يجب فحص المركبة من قبل الوكيل في حالة إضاءة المؤشر بشكلٍ مستمر.",
	"HBCLLDWSCamDisconnectLong_3" : "عطل في نظام Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS)\u200e. قم بتنظيف الزجاج الأمامي. يجب فحص المركبة من قبل الوكيل في حالة إضاءة المؤشر بشكلٍ مستمر.",
	"HBCLLDWSCamDisconnectLong_4" : "عطل في Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS)\u200e. تنظيف الزجاج الأمامي. يجب فحص المركبة من قبل الوكيل في حالة إضاءة المؤشر بشكلٍ مستمر.",
	"HBCLLDWSCamDisconnectShrt" : "خلل في كاميرا HBC/LDWS",
	"HBCLLDWSCamDisconnectShrt_2" : "خلل في كاميرا HBC/LAS",
	"HBCLLDWSCamDisconnectShrt_3" : "خلل في كاميرا ALH/LDWS",
	"HBCLLDWSCamDisconnectShrt_4" : "خلل في كاميرا ALH/LAS",
	"HBCSysErrorLong" : "خلل في نظام High Beam Control (HBC)\u200e.\nاحرص على قيام الموزع بفحص المركبة.\n\n",
	"HBCSysErrorLong_2" : "عطل في نظام Adaptive LED Headlights (ALH)\u200e. يجب فحص المركبة من قبل الوكيل.",
	"HBCSysErrorShrt" : "خلل بنظام HBC",
	"HBCSysErrorShrt_2" : "عطل ALH",
	"HbcOrAlhUnavailable" : "HBC أو ALH غير متاح",
	"HeadlightSystemErrorLongJ03" : "حدث عطل في نظام الأضواء الأمامية.\nإذا كان ضوء التحذير يومض بشكل مستمر، استشر وكيل Mazda.",
	"HighEngineOillevel" : "مستوى زيت المحرك مرتفع",
	"HighEngineOillevelDetail" : "مستوى زيت المحرك مرتفع جدًا. يرجى تغيير الزيت.",
	"HybrdSysMalHighPrt" : "خلل في نظام الهجين. أوقف المركبة على الفور في مكان آمن.",
	"HybridSysErrorLong" : "يوجد خلل في نظام الهجين.\nقد تحدث تلفيات في المركبة حال مواصلتك القيادة. أوقف المركبة على الفور في مكان آمن واحرص على قيام الموزع بفحص المركبة.\n",
	"HybridSysErrorShrt" : "خلل في نظام الهجين",
	"HybridSysOverheatLong" : "يوجد خلل في نظام الهجين.\nقد تحدث تلفيات في المركبة حال مواصلتك القيادة. أوقف المركبة على الفور في مكان آمن واحرص على قيام الموزع بفحص المركبة.\n",
	"HybridSysOverheatShrt" : "سخونة مفرطة بنظام الهجين",
	"IeloopChrgHighPrt" : "جارٍ شحن i‑ELOOP. تأكد عند تشغيل المحرك أن الشحن مكتمل ومن ضبط مؤشر التحذير على إيقاف.",
	"IstopSysErrorLong" : "تشغيل i‑stop غير ممكن.\nاحرص على أن يتم فحص سيارتك لدى أحد موزعي Mazda.\n",
	"IstopSysErrorShrt" : "خلل في نظام i‑stop",
	"KeylesSysErrorLong" : "يوجد خلل في نظام الدخول بدون مفتاح.\nاحرص على قيام الموزع بفحص المركبة.\n",
	"KeylesSysErrorShrt" : "خلل بنظام الدخول بدون مفتاح",
	"LDWSLASUnavailableLong_1" : "تم تعطيل Lane Departure Warning System مؤقتًا نتيجة الحرارة الزائدة في مقصورة الركاب. سيتم تعطيل Lane Departure Warning System بمجرد تبريد مقصورة الركاب بشكل كافٍ.",
	"LDWSLASUnavailableLong_2" : "تم تعطيل Lane-Keep Assist System مؤقتًا نتيجة الحرارة الزائدة في مقصورة الركاب. سيتم تعطيل Lane-Keep Assist System بمجرد تبريد مقصورة الركاب بشكل كافٍ.",
	"LDWSLASUnavailableShrt_1" : "LDWS غير متوفر",
	"LDWSLASUnavailableShrt_2" : "LAS غير متوفر",
	"LDWSSysErrorLong" : "خلل في Lane Departure Warning System (LDWS)\u200e احرص على قيام الموزع بفحص المركبة.\n\n",
	"LDWSSysErrorLong_2" : "عطل في Lane-keep Assist System (LAS)\u200e. يجب فحص المركبة من قبل الوكيل.",
	"LDWSSysErrorShrt" : "خلل بنظام LDWS",
	"LDWSSysErrorShrt_2" : "عطل في LAS",
	"LdwsOrLasUnavailable" : "LDWS أو LAS غير متاح",
	"LowBrakeFluidLong" : "مستوى سائل المكابح منخفض.\nأوقف المركبة على الفور في مكان آمن واحرص على قيام الموزع بفحص المركبة.\n",
	"LowBrakeFluidShrt" : "مستوى سائل المكابح منخفض",
	"LowEngineOillevel" : "مستوى زيت المحرك منخفض",
	"LowEngineOillevelDetail" : "مستوى زيت المحرك منخفض جدًا.  يرجى إضافة زيت.",
	"LowFuelLong" : "مستوى خزان الوقود منخفض.\nاحرص على تزويد المركبة بالوقود سريعًا.\n",
	"LowFuelShrt" : "انخفاض الوقود",
	"LowTireAirPressureFlatLong" : "إذا كان ضغط الإطار ينخفض بشكل كبير بعد إضاءة ضوء التحذير الخاص بنظام مراقبة ضغط الإطار TPMS، أو إذا انثقب إطار، سوف يضيء أيضا ضوء التحذير الخاص بالإطار المفرغ من الهواء.\nإذا انثقب الإطار الخوائي (Run-flat tire)، قم بقيادة السيارة بحذر إلى أقرب وكيل Mazda لتغييره.",
	"LowTireAirPressureLong" : "انخفاض ضغط هواء الإطار في واحد أو أكثر من الإطارات.\nتفقد ضغط هواء الإطارات واضبطه على ضغط الهواء الملائم.  اضغط على مفتاح ضبط TPMS بعد ضبط ضغط الإطار وذلك حتى سماع صوت الصفارة.\n",
	"LowTireAirPressureShrt" : "ضغط هواء الإطار منخفض",
	"LowWasheFluidLong" : "مستوى سائل الغاسل منخفض.\nأعد ملء سائل الغاسل.\n",
	"LowWasheFluidShrt" : "مستوى سائل الغاسل منخفض",
	"MRCCSysErrorLong" : "خلل في Mazda Radar Cruise Control (MRCC)\u200e.\nاحرص على قيام الموزع بفحص المركبة.\n",
	"MRCCSysErrorShrt" : "خلل برادار MRCC",
	"MRCCUnavailableLong" : "رادار Mazda Radar Cruise Control (MRCC)\u200e غير متوفر حاليًا.",
	"MRCCUnavailableShrt" : "MRCC غير متوفر",
	"NoWarnings" : "لا توجد تحذيرات",
	"OilLevelSystemMalfunctioning" : "عطل في مستشعر مستوى زيت المحرك",
	"OilLevelSystemMalfunctioningDetail" : "هناك خلل وظيفي في جهاز مستوى الزيت. يرجى فحص السيارة عند أحد وكلاء Mazda. ",
	"PowerSteeringSysErrorLong" : "يوجد خلل في عجلة القيادة الكهربائية.\nأوقف المركبة في مكان آمن وأوقف تشغيل المحرك.  احرص على قيام الموزع بفحص المركبة في حالة استمرار هذا المؤشر قيد التشغيل.\n",
	"PowerSteeringSysErrorShrt" : "خلل في نظام عجلة القيادة",
	"PpositionRequestLong" : "تبديل ناقل الحركة إلى وضع الوقوف التام.\nويرجع السبب إلى أحد العوامل التالية:\n· تشغيل نظام البطارية أو إيقافه مع ضبط ناقل الحركة على وضع آخر بخلاف وضع الوقوف التام\n· فتح الباب من جانب السائق مع ضبط ناقل الحركة على وضع محايد أو قيادة أو فرامل\n· انخفاض شحن البطارية ذات الجهد العالي المتبقي لضبط ناقل الحركة على وضع محايد لفترة طويلة\nأعد تشغيل نظام الهجين بالضغط على مفتاح الطاقة إذا لزم الأمر.",
	"PpositionRequestShrt" : "طلب وضع الوقوف التام",
	"PreheatingDispLampLong" : "مقابس الحرارة قيد التسخين.\nاحرص على قيام الموزع بفحص المركبة في حالة استمرار هذا المؤشر قيد التشغيل.\n",
	"PreheatingDispLampShrt" : "تسخين مسبق لمقابس الحرارة",
	"RoadSurfaceIcingCautionLong" : "تبلغ درجة الحرارة بالخارج 4 درجة مئوية أو أقل.\nاحذر من أسطح الطرق الجليدية أثناء القيادة.\n",
	"RoadSurfaceIcingCautionShrt" : "تحذير الطريق مكسو بالجليد",
	"RvmSysErrorLong" : "يوجد خطأ في نظام RVM.\nتحقق من عدم وجود خلل في سطح المصد الخلفي ونظفه إذا كان متسخًا أو مغطى بالثلج.\nاحرص على قيام أحد موزعي Mazda بفحص السيارة إذا ظل مصباح التحذير مضاءًا.",
	"RvmSysErrorShrt" : "خلل في RVM",
	"SBSBrakeMRCCUnavailableLong" : "مكابح SBS/MRCC غير متوفرة حاليًا.",
	"SBSBrakeMRCCUnavailableShrt" : "مكابح SBS/MRCC غير متوفرة",
	"SBSBrakeUnavailableLong" : "مكابح SBS غير متوافرة حاليًا.",
	"SBSBrakeUnavailableShrt" : "مكابح SBS غير متوفرة",
	"SBSMRCCDRSSRadarSoilingLong" : "رادار (مستشعر) SBS/MRCC/DRSS متسخ.\nنظف سطح الرادار (المستشعر) بالكامل.\n",
	"SBSMRCCDRSSRadarSoilingShrt" : "خلل برادار SBS/MRCC/DRSS",
	"SBSMRCCRadarSoilingLong" : "رادار (مستشعر) SBS/MRCC متسخ.\nنظف سطح الرادار (المستشعر) بالكامل.\n",
	"SBSMRCCRadarSoilingShrt" : "خلل بنظام SBS/MRCC رادار",
	"SBSSysErrorLong" : "يوجد خطأ في نظام SBS.\nاحرص على أن يتم فحص سيارتك لدى أحد موزعي Mazda.\n",
	"SBSSysErrorShrt" : "خلل بنظام SBS",
	"SCBSSysErrorLong" : "خلل في Smart City Brake Support (SCBS)\u200e.\nاحرص على قيام الموزع بفحص المركبة على الفور.\n",
	"SCBSSysErrorLong_105" : "عطل في Smart City Brake Support(SCBS). أزل الجليد الزجاج الأمامي. يجب فحص المركبة من قبل الوكيل في حالة إضاءة المؤشر بشكلٍ مستمر.",
	"SCBSSysErrorShort_105" : "خلل بنظام SCBS",
	"SCBSSysErrorShrt" : "خلل بنظام SCBS",
	"SCBSUnavailableLong" : "نظام Smart City Brake Support (SCBS)\u200e غير متوفر حاليًا.",
	"SCBSUnavailableLong1" : "تم تعطيل Smart City Brake Support system مؤقتًا نتيجة الحرارة الزائدة في مقصورة الركاب. سيتم تعطيل Smart City Brake Support system بمجرد تبريد مقصورة الركاب بشكل كافٍ.",
	"SCBSUnavailableShrt" : "نظام SCBS غير متوفر",
	"SCBSUnavailableShrt1" : "نظام SCBS غير متوفر",
	"SCBSWindshieldSoilingLong" : "خلل في Smart City Brake Support (SCBS)\u200e.\nنظّف الزجاج الأمامي.  احرص على قيام الموزع بفحص المركبة في حالة استمرار هذا المؤشر قيد التشغيل.\n",
	"SCBSWindshieldSoilingShrt" : "خلل بنظام SCBS",
	"SCRMalfunction100Long" : "عطل في نظام الانبعاثات (SCR) لانبعاثات الديزل.\n إذا لم يتم التعامل مع هذه المشكلة، فستصبح سرعة المركبة محدودة.",
	"SCRMalfunction101Long" : "عطل في نظام الانبعاثات (SCR) لانبعاثات الديزل.\n إذا لم يتم التعامل مع هذه المشكلة، فسيدخل المحرك في وضع التباطؤ الإجباري.",
	"SCRMalfunction102Long" : "عطل في نظام الانبعاثات (SCR) لانبعاثات الديزل.  المحرك الآن في وضع التباطؤ الإجباري.\n الرجاء الاتصال بموزع Mazda الذي تتعامل معه للصيانة.",
	"ScrMalfunction" : "خلل بنظام SCR",
	"SedimenterWarningLong" : "كمية المياه المتراكمة في الرواسب تتجاوز الكمية المقدرة.\nاحرص على قيام الموزع بفحص المركبة في حالة استمرار هذا المؤشر قيد التشغيل.\n",
	"SedimenterWarningShrt" : "فحص الرواسب",
	"SystemInspectionLong" : "درجة حرارة الزيت التباينية مرتفعة بصورة غير طبيعية أو أنه قد حدث اختلافًا دورانيًا كبيرًا في الإطارات الأمامية والخلفية (وهو ما يشبه محاولة الخروج من الوحل).\nأوقف المركبة في مكان آمن وواصل القيادة بعد توقف مؤشر الإنذار. احرص على قيام الموزع بفحص المركبة في حالة استمرار هذا المؤشر قيد التشغيل.\n",
	"SystemInspectionShrt" : "فحص نظام 4WD",
	"TpmsSysErrorLong" : "يوجد خلل في نظام مراقبة ضغط الإطار (TPMS).\nاحرص على قيام الموزع بفحص المركبة.\n",
	"TpmsSysErrorShrt" : "خلل في نظام TPMS",
	"VehicleSysErrorLong" : "يوجد خلل في نظام المركبة.\nاحرص على قيام الموزع بفحص المركبة.\n",
	"VehicleSysErrorShrt" : "خلل في نظام المركبة",
	"WarningGuidance" : "توجيه تحذيري",
	"WarningSafetyMessage" : "لأسباب تتعلق بالأمان، لن يتم عرض دليل التحذير.",
	"Warnings" : "تحذيرات",
	"brakeFluid" : "مستوى سائل المكابح منخفض",
	"engineOilPressure" : "ضغط زيت المحرك",
	"highVoltage" : "شحن بطارية الجهد العالي منخفض",
	"lowBattStartEngine" : "انخفض شحن البطارية! أدر المحرك!",
};

framework.registerAppDictLoaded("warnguide", "ar_SA");