var Localization_warnguideAppDict_cn_HK = {
	//"stringId" : "localString"
	"AbsSysErrorLong" : "防鎖死制動系統 (ABS) 故障。\n請立即聯絡 Mazda 經銷商檢查車輛。",
	"AbsSysErrorShrt" : "ABS 故障",
	"AbsSystemErrorLong" : "防鎖死制動系統 (ABS) 故障。\n請立即聯絡 Mazda 經銷商檢查車輛。",
	"AbsSystemErrorShrt" : "ABS 故障",
	"AccumulationDpfLong" : "柴油顆粒篩選器 (DPF) 所收集的顆粒物 (PM) 超出規定值。 在引擎完全預熱的狀態 (藍色溫度燈熄滅) 下以每小時 10 英里 (15公里/小時) 或更高的速度行駛 10-15 分鐘，以排空顆粒物。  如果該指示燈一直亮起，請聯絡 Mazda 經銷商檢查車輛。",
	"AccumulationDpfShrt" : "DPF 內的 PM 蓄積",
	"ActiveBonnetSystemMalfunctionLong" : "Active Bonnet 系統故障。如果該指示燈一直亮起或持續閃爍，請聯絡 Mazda 經銷商檢查車輛。",
	"ActiveBonnetSystemMalfunctionShrt" : "Active Bonnet 系統故障",
	"AfsSystemErrorLong" : "自動轉向頭燈系統 (AFS) 故障。如果該指示燈持續閃爍，請聯絡 Mazda 經銷商檢查車輛。",
	"AfsSystemErrorShrt" : "AFS 故障",
	"AfterRunCoolingPumpLong" : "如果Mazda 過熱，請致電或造訪經銷商進行維修。 ",
	"AfterRunCoolingPumpShrt" : "冷卻液泵 (熄火後運轉)",
	"AirbagSysPretensionerSysErrorLong" : "安全帶/氣袋故障。 請立即聯絡 Mazda 經銷商檢查車輛。",
	"AirbagSysPretensionerSysErrorShrt" : "安全帶及氣袋系統錯誤",
	"AutoLevelSystemErrorLong" : "自動調校頭燈糸統故障。如果該指示燈一直亮起，請聯絡 Mazda 經銷商檢查車輛。",
	"AutoLevelSystemErrorShrt" : "自動調校頭燈糸統故障",
	"AutoLevelSystemErrorShrtJ03" : "大燈系統故障",
	"AutoTransSysErrorLong" : "自動變速器故障。 如果繼續行駛可能會造成車輛損壞。  請立即聯絡 Mazda 經銷商檢查車輛。  ",
	"AutoTransSysErrorShrt" : "自動。 變速器故障",
	"AuxBattLowLong" : "12V 電池充電電量低。\n・如果行駛過程中該指示燈頻繁亮起，可能表示電池電量等級正在降低。 連絡經銷商檢查車輛。\n・如果該指示燈常亮不滅，表示 12V 電池電量耗盡。 在起動混合系統之前請閱讀車主手冊，並連絡經銷商檢查車輛。",
	"AuxBattLowShrt" : "12V 電池電量低",
	"BattManagSysErrorLong" : "電池管理系統故障。\n請聯絡 Mazda 經銷商檢查車輛。",
	"BattManagSysErrorShrt" : "電池管理系統故障",
	"BrakOverrideSysErrorLong" : "制動優先系統故障。請聯絡 Mazda 經銷商檢查車輛。",
	"BrakOverrideSysErrorShrt" : "制動優先系統故障",
	"BrakeSysErrorLong" : "制動液不足或制動系統故障。 請立即在安全情況下停車並聯絡 Mazda 經銷商檢查車輛。",
	"BrakeSysErrorShrt" : "制動系統故障",
	"BrakeSystemErrorLong" : "電控制動系統故障。立即在安全情況下停車並聯絡 Mazda 經銷商檢查車輛。",
	"BrakeSystemErrorShrt" : "制動系統故障",
	"BsmSystemErrorLong" : "Blind Spot Monitoring (BSM)/Rear Cross Traffic Alert  (RCTA)故障。檢查後保險杠表面是否有異常，如有髒物或灰塵則清除乾淨。如果該指示燈一直亮起，請聯絡 Mazda 經銷商檢查車輛。",
	"BsmSystemErrorShrt" : "BSM 故障",
	"ChargSysMalHighPrt" : "充電系統故障。 請立即在安全情況下停車。",
	"ChargingSysErrorLong" : "充電系統故障。 如果繼續行駛可能會造成車輛損壞。  請立即在安全情況下停車並聯絡 Mazda 經銷商檢查車輛。",
	"ChargingSysErrorShrt" : "充電系統故障",
	"ChrgSysErrorLong" : "充電系統故障。 請立即在安全情況下停車並聯絡 Mazda 經銷商檢查車輛。",
	"ChrgSysErrorShrt" : "充電系統故障",
	"ColdStartDisableLong" : "環境溫度極低，引擎起動被抑制，以防引擎損壞。詳情參見車主手冊。 透過插入引擎預加熱器，您可以在啟動 Mazda 時避免可能發生的延遲。 ",
	"ColdStartDisableShrt" : "冷起動已停用",
	"ControlSystemErrorLong" : "停車位置控制系統故障。\n如不檢查，可能導致以下任一狀況：\n・停車鎖定裝置可能失效。 在平坦地面停車並將停車制動器固定到位。\n・電源開關可能未關閉。 重複按電源開關以將其關閉。\n・「停車時固定停車制動器」在行駛時將關閉，而在停車時開啟。\n請立即聯絡 Mazda 經銷商檢查車輛。",
	"ControlSystemErrorShrt" : "停車位置控制系統錯誤",
	"DPFErrorLong" : "柴油微粒篩選器 (DPF) 故障。\n請聯絡 Mazda 經銷商檢查車輛。",
	"DPFErrorShrt" : "DPF 錯誤",
	"DRSSSysErrorLong" : "DRSS 系統出現錯誤。請聯絡 Mazda 經銷商檢查車輛。",
	"DRSSSysErrorShrt" : "DRSS 故障",
	"DefEmpty" : "DEF 為空",
	"DefLow" : "DEF 低",
	"DefVeryLow" : "DEF 非常低",
	"DriveBattDropLong" : "高壓電池的剩餘電量低，因為變速器已長時間處於空檔位置。 空檔狀態無法充電。 長時間停車時切換到停車狀態。 如有必要，按下電源開關以重新啟動混合系統。",
	"DriveBattDropShrt" : "高壓電池電量低",
	"DropKeyBattChrgLong" : "鑰匙電池電量低。請立即更換鑰匙電池。",
	"DropKeyBattChrgShrt" : "鑰匙電池電量低",
	"DscSysErrorLong" : "Dynamic Stability Control (DSC)、Traction Control System (TCS)、或Hill Launch Assist (HLA) 故障。 請立即聯絡 Mazda 經銷商檢查車輛。",
	"DscSysErrorShrt" : "DSC 故障",
	"DscSystemErrorLong" : "動態穩定性控制 (DSC) 或跟蹤控制系統 (TCS)故障。 請立即聯絡 Mazda 經銷商檢查車輛。",
	"DscSystemErrorShrt" : "DSC 故障",
	"EcbSysErrorLong" : "回饋制動或電控制動系統故障。 請立即在安全情況下停車並聯絡 Mazda 經銷商檢查車輛。",
	"EcbSysErrorShrt" : "制動系統故障",
	"ElectricParkingBrakeHighLong" : "電子停車制動故障。\n如果在操作電子停車開關時此指示燈繼續閃爍甚至亮起，應立即在平坦且安全的地點停車並聯絡 Mazda 經銷商檢查車輛。",
	"ElectricParkingBrakeLong" : "電子停車制動故障。\n如果在操作電子停車制動開關時此指示燈仍舊亮起，請聯絡 Mazda 經銷商檢查車輛。",
	"ElectricParkingBrakeShrt" : "電子停車制動故障",
	"ElectricVacuumPumpSystemMalfunctionLong" : "電動真空泵系統故障。\n不解決此問題可能導致系統故障並造成危險或損壞。\n請立即諮詢 Mazda 經銷商檢查此故障。",
	"ElectricVacuumPumpSystemMalfunctionShrt" : "電動真空泵系統故障",
	"ElectronicThrottleControlLong" : "如果警告燈一直亮起，則表示電子控制單元出現故障。重啟 Mazda 的引擎，以重置電子控制單元，或者造訪經銷商進行維修。\n\n如果警告燈閃爍，則表示出現嚴重故障，節氣門輸出將受到限制。 盡快造訪經銷商維修車輛。嘗試透過重新啟動引擎來重置電子控制單元。  \n",
	"ElectronicThrottleControlShrt" : "電子節氣門控制",
	"EloopChargingLong" : "i‑ELOOP 充電中。 引擎運轉時檢查充電是否完成以及警告指示燈是否熄滅。 如果該指示燈一直亮起，請聯絡 Mazda 經銷商檢查車輛。",
	"EloopChargingShrt" : "i‑ELOOP 充電中",
	"EloopSysErrorLong" : "i‑ELOOP 系統故障。 如果該指示燈一直亮起，請聯絡 Mazda 經銷商檢查車輛。",
	"EloopSysErrorShrt" : "i‑ELOOP 系統故障",
	"EngCoolntTempHighOnLong" : "引擎過熱。 立即在安全情況下停車，關閉引擎並採取適當措施。詳情參見車主手冊。",
	"EngCoolntTempHighOnShrt" : "引擎冷卻液溫度過高",
	"EngOilPressureErrorLong" : "引擎油壓過低。\n立即在安全情況下停車，關閉引擎並檢查引擎油位。必要時加油。加油完畢或引擎油位回覆正常時，如果此指示燈亮起，應聯絡 Mazda 經銷商檢查車輛。",
	"EngOilPressureErrorShrt" : "引擎油壓過低",
	"EngSystemErrorLong" : "引擎系統故障。請立即聯絡 Mazda 經銷商檢查車輛。",
	"EngSystemErrorShrt" : "引擎系統故障",
	"EngineOilPressureErrorLong" : "引擎油壓過低。立即在安全情況下停車，關閉引擎並檢查引擎油位。必要時加油。加油完成後或引擎油位回復正常時，如果此指示燈亮起，請聯絡 Mazda 經銷商檢查車輛。",
	"EngineOilPressureErrorShrt" : "引擎油壓過低",
	"EngineWaterTempDropLong" : "引擎冷卻液較冷，加熱器/除霜器沒有暖空氣可用。 指示燈開或關時均可行駛。  如果該指示燈一直亮起，請聯絡 Mazda 經銷商檢查車輛。",
	"EngineWaterTempDropShrt" : "引擎冷卻液溫度低",
	"EngineWaterTempRiseLong" : "引擎開始發熱。 慢速行駛或停車，直至指示燈停止閃爍。 如果停車後指示燈繼續閃爍，則應採取適當措施。詳情參見車主手冊。",
	"EngineWaterTempRiseShrt" : "引擎冷卻液溫度過高",
	"EngnCoolTempHighHighPrt" : "引擎冷卻液溫度過高。請立即在安全情況下停車。",
	"FOWMRCCDRSSRadarSoilingLong" : "FOW/MRCC/DRSS 雷達 (感應器) 骯髒。請清潔整個雷達 (感應器) 表面。",
	"FOWMRCCDRSSRadarSoilingShrt" : "FOW/MRCC/DRSS 雷達錯誤",
	"FOWMRCCRadarSoilingLong" : "FOW/MRCC 雷達 (感應器) 故障。如果前中網標有髒物或積雪，請清潔整個表面。如果指示燈一直亮起，請聯絡 Mazda 經銷商檢查車輛。",
	"FOWMRCCRadarSoilingShrt" : "FOW/MRCC 雷達故障",
	"FOWSysError" : "FOW 故障",
	"FOWSysErrorLong" : "前方障礙警告 (FOW) 系統故障。請聯絡 Mazda 經銷商檢查車輛。",
	"FWDSysErrorLong" : "4WD 系統故障或前後輪胎尺寸不一致。\n請聯絡 Mazda 經銷商檢查車輛。",
	"FWDSysErrorShrt" : "4WD 系統故障",
	"FuelAirFilterCartReplacePeriodLong" : "需要更換燃油濾清器濾芯。 ",
	"FuelAirFilterCartReplacePeriodShrt" : "需要更換燃油濾清器。",
	"FuelCapInspectionLong" : "油箱蓋可能沒有蓋好。\n檢查油箱蓋是否穩妥蓋好。穩妥蓋好油箱蓋之後，此指示燈將繼續亮起幾個駕駛週期，直至確認系統正常運行。如果該指示燈一直亮起，請聯絡 Mazda 經銷商檢查車輛。",
	"FuelCapInspectionShrt" : "檢查油箱蓋",
	"HBCALHUnavailableLong_1" : "由於車廂過熱，High Beam Control 暫時停用。 車廂充分冷卻後，High Beam Control 將啟用。 ",
	"HBCALHUnavailableLong_2" : "由於車廂過熱，Adaptive LED Headlights 暫時停用。 車廂充分冷卻後，Adaptive LED Headlights 將啟用。 ",
	"HBCALHUnavailableShrt_1" : "HBC 不可用",
	"HBCALHUnavailableShrt_2" : "ALH 不可用",
	"HBCLDWSSysErrorLong" : "High Beam Control (HBC)* 與/或 Lane Departure Warning System (LDWS)* 故障。如果該指示燈一直亮起，請聯絡經銷商檢查車輛。 \n*是否具備這些功能視型號/裝飾水準而定。",
	"HBCLDWSSysErrorLong_2" : "High Beam Control (HBC)/Lane-keep Assist System (LAS) 故障。 如果該指示燈一直亮起，請聯絡 Mazda 經銷商檢查車輛。",
	"HBCLDWSSysErrorLong_3" : "Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS)故障。 如果該指示燈一直亮起，請聯絡 Mazda 經銷商檢查車輛。",
	"HBCLDWSSysErrorLong_4" : "Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS) 故障。 如果該指示燈一直亮起，請聯絡 Mazda 經銷商檢查車輛。",
	"HBCLDWSSysErrorShrt" : "HBC/LDWS 系統故障",
	"HBCLDWSSysErrorShrt_2" : "HBC/LAS 系統故障",
	"HBCLDWSSysErrorShrt_3" : "ALH/LDWS 系統故障",
	"HBCLDWSSysErrorShrt_4" : "ALH/LAS 系統故障",
	"HBCLDWSWindshieldFogLong" : "High Beam Control (HBC)* 與/或 Lane Departure Warning System (LDWS)* 故障。擋風玻璃除霜。如果該指示燈一直亮起，請聯絡經銷商檢查車輛。\n*是否具備這些功能視型號/裝飾水準而定。 ",
	"HBCLDWSWindshieldFogLong_2" : "High Beam Control (HBC)/Lane-keep Assist System (LAS) 故障。 擋風玻璃除霜。  如果該指示燈一直亮起，請聯絡 Mazda 經銷商檢查車輛。",
	"HBCLDWSWindshieldFogLong_3" : "Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS) 故障。 擋風玻璃除霜。  如果該指示燈一直亮起，請聯絡 Mazda 經銷商檢查車輛。",
	"HBCLDWSWindshieldFogLong_4" : "Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS) 故障。 擋風玻璃除霜。  如果該指示燈一直亮起，請聯絡 Mazda 經銷商檢查車輛。",
	"HBCLDWSWindshieldFogShrt" : "HBC/LDWS 系統故障",
	"HBCLDWSWindshieldFogShrt_2" : "HBC/LAS 系統故障",
	"HBCLDWSWindshieldFogShrt_3" : "ALH/LDWS 系統故障",
	"HBCLDWSWindshieldFogShrt_4" : "ALH/LAS 系統故障",
	"HBCLLDWSCamDisconnectLong" : "High Beam Control (HBC)* 與/或 Lane Departure Warning System (LDWS)* 故障。清潔擋風玻璃。如果該指示燈一直亮起，請聯絡經銷商檢查車輛。\n*是否具備這些功能視型號/裝飾水準而定。",
	"HBCLLDWSCamDisconnectLong_2" : "High Beam Control (HBC)/Lane-keep Assist System (LAS) 故障。 清潔擋風玻璃。  如果該指示燈一直亮起，請聯絡 Mazda 經銷商檢查車輛。",
	"HBCLLDWSCamDisconnectLong_3" : "Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS) 故障。 清潔擋風玻璃。  如果該指示燈一直亮起，請聯絡 Mazda 經銷商檢查車輛。",
	"HBCLLDWSCamDisconnectLong_4" : "Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS) 故障。 清潔擋風玻璃。  如果該指示燈一直亮起，請聯絡 Mazda 經銷商檢查車輛。",
	"HBCLLDWSCamDisconnectShrt" : "HBC/LDWS 攝像頭故障",
	"HBCLLDWSCamDisconnectShrt_2" : "HBC/LAS 攝像頭故障",
	"HBCLLDWSCamDisconnectShrt_3" : "ALH/LDWS 攝像頭故障",
	"HBCLLDWSCamDisconnectShrt_4" : "ALH/LAS 攝像頭故障",
	"HBCSysErrorLong" : "High Beam Control (HBC) 故障。請聯絡 Mazda 經銷商檢查車輛。\n\n",
	"HBCSysErrorLong_2" : "Adaptive LED Headlights (ALH)故障。 連絡經銷商檢查車輛。",
	"HBCSysErrorShrt" : "HBC 故障",
	"HBCSysErrorShrt_2" : "ALH故障",
	"HbcOrAlhUnavailable" : "HBC 或 ALH 不可用 ",
	"HeadlightSystemErrorLongJ03" : "頭燈系統故障。請聯絡 Mazda 經銷商檢查車輛。",
	"HighEngineOillevel" : "引擎油位高",
	"HighEngineOillevelDetail" : "引擎機油量太多。 請更換機油。",
	"HybrdSysMalHighPrt" : "混合系統故障。 請立即在安全情況下停車。",
	"HybridSysErrorLong" : "混合系統故障。 如果繼續行駛可能會造成車輛損壞。 請立即在安全情況下停車並聯絡 Mazda 經銷商檢查車輛。",
	"HybridSysErrorShrt" : "混合系統故障",
	"HybridSysOverheatLong" : "混合系統故障。 如果繼續行駛可能會造成車輛損壞。 請立即在安全情況下停車並聯絡 Mazda 經銷商檢查車輛。",
	"HybridSysOverheatShrt" : "混合系統過熱",
	"IeloopChrgHighPrt" : "i‑ELOOP 充電中。 引擎運轉時檢查充電是否完成以及警告指示燈是否熄滅。",
	"IstopSysErrorLong" : "無法執行 i‑stop 操作。\n請聯絡 Mazda 經銷商檢查車輛。",
	"IstopSysErrorShrt" : "i‑stop 系統故障",
	"KeylesSysErrorLong" : "無匙系統故障。請聯絡 Mazda 經銷商檢查車輛。",
	"KeylesSysErrorShrt" : "無匙系統故障",
	"LDWSLASUnavailableLong_1" : "由於車廂過熱，Lane Departure Warning System 暫時停用。 車廂充分冷卻後，Lane Departure Warning System 將啟用。 ",
	"LDWSLASUnavailableLong_2" : "由於車廂過熱，Lane-Keep Assist System 暫時停用。 車廂充分冷卻後，Lane-Keep Assist System 將啟用。 ",
	"LDWSLASUnavailableShrt_1" : "LDWS 不可用",
	"LDWSLASUnavailableShrt_2" : "LAS 不可用",
	"LDWSSysErrorLong" : "Lane Departure Warning System (LDWS) 故障。請聯絡 Mazda 經銷商檢查車輛。\n\n",
	"LDWSSysErrorLong_2" : "Lane-keep Assist System (LAS) 故障。 連絡經銷商檢查車輛。",
	"LDWSSysErrorShrt" : "LDWS 故障",
	"LDWSSysErrorShrt_2" : "LAS 故障",
	"LdwsOrLasUnavailable" : "LDWS 或 LAS 不可用",
	"LowBrakeFluidLong" : "制動液不足。 請立即在安全情況下停車並聯絡 Mazda 經銷商檢查車輛。",
	"LowBrakeFluidShrt" : "制動液不足",
	"LowEngineOillevel" : "引擎油位低",
	"LowEngineOillevelDetail" : "引擎機油量太少。  請添加機油。",
	"LowFuelLong" : "油箱液位低。\n儘快為車輛加油。",
	"LowFuelShrt" : "油量低",
	"LowTireAirPressureFlatLong" : "若 TPMS 警告燈亮起後胎壓顯著降低，抑或輪胎被戳破，爆胎警告燈亦會亮起。若安全輪胎被戳破，請將車輪謹慎駕至最近的 Mazda 經銷商進行換胎。",
	"LowTireAirPressureLong" : "有一個或多於一個輪胎氣壓過低。請檢查輪胎氣壓並調整至正常氣壓。輪胎壓力調整完成並聽見提示音後，請按下 TPMS 設定開關。",
	"LowTireAirPressureShrt" : "輪胎氣壓過低",
	"LowWasheFluidLong" : "水撥水量低。請補充水撥水。",
	"LowWasheFluidShrt" : "水撥水量低",
	"MRCCSysErrorLong" : "Mazda Radar Cruise Control (MRCC) 發生故障。請聯絡 Mazda  經銷商檢查車輛。",
	"MRCCSysErrorShrt" : "MRCC 故障",
	"MRCCUnavailableLong" : "Mazda Radar Cruise Control (MRCC) 目前不可用。",
	"MRCCUnavailableShrt" : "MRCC 不可用",
	"NoWarnings" : "未發現警告",
	"OilLevelSystemMalfunctioning" : "引擎油位感測器故障",
	"OilLevelSystemMalfunctioningDetail" : "引擎油位感測器有故障。 連絡 Mazda 經銷商檢查車輛。 ",
	"PowerSteeringSysErrorLong" : "電動輔助轉向系統故障。立即在安全情況下停車並關閉引擎。如果該指示燈一直亮起，請聯絡 Mazda 經銷商檢查車輛。",
	"PowerSteeringSysErrorShrt" : "電動輔助轉向系統錯誤",
	"PpositionRequestLong" : "將變速器切換至停車檔。\n此情況由以下原因之一導致：\n・起動或停止電池系統時，變速器不在停車位置\n・打開駕駛側車門時，變速器在 N、D 或B 位置\n・由於變速器長時間處於空檔位置，高壓電池剩餘充電量低。\n如有必要，按下電源開關以重新啟動混合系統。",
	"PpositionRequestShrt" : "停車位置請求",
	"PreheatingDispLampLong" : "電熱塞正在預熱中。如果該指示燈一直亮起，請聯絡 Mazda 經銷商檢查車輛。",
	"PreheatingDispLampShrt" : "電熱塞預熱",
	"RoadSurfaceIcingCautionLong" : "外界溫度為 4°C 或更低。 在結冰路面行駛時應小心謹慎。",
	"RoadSurfaceIcingCautionShrt" : "小心，路面結冰",
	"RvmSysErrorLong" : "RVM 系統出現錯誤。\n請檢查後保險杠表面是否有異常，如有髒物或灰塵則清除乾淨。如果該警告燈一直亮起，請聯絡 Mazda 經銷商檢查車輛。",
	"RvmSysErrorShrt" : "RVM 故障",
	"SBSBrakeMRCCUnavailableLong" : "SBS Brake/MRCC 目前不可用。",
	"SBSBrakeMRCCUnavailableShrt" : "SBS Brake/MRCC 不可用",
	"SBSBrakeUnavailableLong" : "SBS Brake 目前不可用。",
	"SBSBrakeUnavailableShrt" : "SBS Brake 不可用",
	"SBSMRCCDRSSRadarSoilingLong" : "SBS/MRCC/DRSS 雷達 (感應器) 骯髒。請清潔整個雷達 (感應器) 表面。",
	"SBSMRCCDRSSRadarSoilingShrt" : "SBS/MRCC/DRSS 雷達錯誤",
	"SBSMRCCRadarSoilingLong" : "SBS/MRCC 雷達 (感應器) 骯髒。請清潔整個雷達 (感應器) 表面。",
	"SBSMRCCRadarSoilingShrt" : "SBS/MRCC 雷達故障",
	"SBSSysErrorLong" : "SBS 系統出現錯誤。請聯絡 Mazda 經銷商檢查車輛。",
	"SBSSysErrorShrt" : "SBS 故障",
	"SCBSSysErrorLong" : "Smart City Brake Support (SCBS) 故障。\n請立即聯絡 Mazda 經銷商檢查車輛。",
	"SCBSSysErrorLong_105" : "Smart City Brake Support(SCBS) 故障。 擋風玻璃除霜。 如果該指示燈一直亮起，請聯絡 Mazda 經銷商檢查車輛。",
	"SCBSSysErrorShort_105" : "SCBS 故障",
	"SCBSSysErrorShrt" : "SCBS 故障",
	"SCBSUnavailableLong" : "Smart City Brake Support (SCBS) 目前不可用。",
	"SCBSUnavailableLong1" : "由於車廂過熱，Smart City Brake Support 系統暫時停用。 車廂充分冷卻後，Smart City Brake Support 系統將啟用。 ",
	"SCBSUnavailableShrt" : "SCBS 不可用",
	"SCBSUnavailableShrt1" : "SCBS 不可用",
	"SCBSWindshieldSoilingLong" : "Smart City Brake Support (SCBS) 故障。\n清潔前擋風玻璃。  如果該指示燈一直亮起，請聯絡 Mazda 經銷商檢查車輛。",
	"SCBSWindshieldSoilingShrt" : "SCBS 故障",
	"SCRMalfunction100Long" : "柴油排放 SCR 故障。\n若該問題未得到解決，車速將受限。",
	"SCRMalfunction101Long" : "柴油排放 SCR 故障。\n若該問題未得到解決，引擎將進入強制怠速模式。",
	"SCRMalfunction102Long" : "柴油排放 SCR 故障。引擎現已進入強制怠速模式。\n請聯絡 Mazda 經銷商進行維修。",
	"ScrMalfunction" : "SCR 故障",
	"SedimenterWarningLong" : "沉澱分離器中的積水量超過額定標準。如果該指示燈一直亮起，請聯絡 Mazda 經銷商檢查車輛。",
	"SedimenterWarningShrt" : "沉澱分離器檢查",
	"SystemInspectionLong" : "差速油溫度異常升高或者前後輪胎出現大幅度轉動偏差 (例如在嘗試駛出泥濘路面時)。在安全情況下停車，當警告指示燈熄滅後繼續行駛。如果該指示燈一直亮起，請聯絡 Mazda 經銷商檢查車輛。",
	"SystemInspectionShrt" : "4WD 系統檢查",
	"TpmsSysErrorLong" : "胎壓監控系統 (TPMS) 故障。 連絡經銷商檢查車輛。",
	"TpmsSysErrorShrt" : "TPMS 系統故障",
	"VehicleSysErrorLong" : "車輛系統故障。請聯絡 Mazda 經銷商檢查車輛。",
	"VehicleSysErrorShrt" : "車輛系統故障",
	"WarningGuidance" : "警告指引",
	"WarningSafetyMessage" : "出於安全起見，不顯示警告指引。",
	"Warnings" : "警告",
	"brakeFluid" : "制動液不足",
	"engineOilPressure" : "引擎油壓",
	"highVoltage" : "高壓電池電量低",
	"lowBattStartEngine" : "電池電量低！ 起動引擎！",
};

framework.registerAppDictLoaded("warnguide", "cn_HK");