var Localization_warnguideAppDict_hu_HU = {
	//"stringId" : "localString"
	"AbsSysErrorLong" : "Blokkolásgátló (ABS) hibája. Azonnal kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"AbsSysErrorShrt" : "ABS-hiba",
	"AbsSystemErrorLong" : "Blokkolásgátló (ABS) hibája. Azonnal kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"AbsSystemErrorShrt" : "ABS-hiba",
	"AccumulationDpfLong" : "A dízelmotor részecskeszűrője (DPF) által begyűjtött korom (PM) mennyisége meghaladta a szabályos értéket.\nA korom kitisztítása érdekében vezessen teljesen felmelegedett motorral (miután a kék hőmérséklet-visszajelző kialudt) 10-15 percet legalább 15 km/h sebességgel.  Ha a jelzés nem szűnik meg, kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"AccumulationDpfShrt" : "Korom tárolódás a DPF-ben",
	"ActiveBonnetSystemMalfunctionLong" : "Active Bonnet rendszer hiba.\nEllenőriztesse a gépjárművét egy értékesítésben, ha ez a jelző égve marad vagy folyamatosan villog.",
	"ActiveBonnetSystemMalfunctionShrt" : "Active Bonnet rendszer hiba",
	"AfsSystemErrorLong" : "Alkalmazkodó fényszóró (AFS) hiba.  Ha a jelzés továbbra is villog, kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"AfsSystemErrorShrt" : "AFS-hiba",
	"AfterRunCoolingPumpLong" : "A Mazda túlmelegedése esetén hívjon fel egy márkakereskedést, vagy látogasson el egyhez. ",
	"AfterRunCoolingPumpShrt" : "Hűtőfolyadék-utókeringető szivattyú",
	"AirbagSysPretensionerSysErrorLong" : "A légzsák, ill. biztonsági öv hibája. Azonnal kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"AirbagSysPretensionerSysErrorShrt" : "Légzsák / Övfeszítő rendszer hiba",
	"AutoLevelSystemErrorLong" : "Automata fényszórómagasság-állítás hibája Ha a jelzés nem szűnik meg, kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"AutoLevelSystemErrorShrt" : "Auto- fényszórómag.-állítás hibája",
	"AutoLevelSystemErrorShrtJ03" : "A fényszórórendszer meghibásodása",
	"AutoTransSysErrorLong" : "Automata sebességváltó hibája.\nA továbbhaladás a jármű károsodásához vezethet.  Azonnal kérje egy márkakereskedőtől a jármű felülvizsgálatát.\n  ",
	"AutoTransSysErrorShrt" : "Automata sebességváltó hibája",
	"AuxBattLowLong" : "Lemerülőben a 12V-os akkumulátor.\n・Ha ez a jelzés vezetés közben gyakran bekapcsol, akkor az akkumulátor esetleg elöregedett. Kérje egy márkakereskedőtől a jármű felülvizsgálatát.\n・Ha ez a jelzés állandóan világít, és nem kapcsol ki, a 12V-os akkumulátor tönkrement. A hibrid rendszer indítása előtt olvassa el a Felhasználói útmutatót, és kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"AuxBattLowShrt" : "Lemerülőben a 12 V-os akkumulátor",
	"BattManagSysErrorLong" : "Akkumulátorkezelő rendszer hibája. Kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"BattManagSysErrorShrt" : "Akkumulátorkezelő rendszerhiba",
	"BrakOverrideSysErrorLong" : "Fékkapcsoló hibája\nAzonnal kérje egy márkakereskedőtől a jármű felülvizsgálatát.\n",
	"BrakOverrideSysErrorShrt" : "Felülbíráló fékrendszer (BOS) hiba",
	"BrakeSysErrorLong" : "Alacsony fékfolyadékszint vagy fékrendszerhiba.  Azonnal álljon le egy biztonságos helyen, és kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"BrakeSysErrorShrt" : "A fékrendszer hibás",
	"BrakeSystemErrorLong" : "Elektromos vezérlésű fékrendszer hibája.\nAzonnal álljon le egy biztonságos helyen, és kérje egy márkakereskedőtől a jármű felülvizsgálatát.\n",
	"BrakeSystemErrorShrt" : "A fékrendszer hibás",
	"BsmSystemErrorLong" : "Blind Spot Monitoring (BSM)/Rear Cross Traffic Alert (RCTA)  hibája. Ellenőrizze a hátsó lökhárító felületét, és az esetleges szennyeződéstől vagy hótól tisztítsa meg. Ha a jelzés nem szűnik meg, kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"BsmSystemErrorShrt" : "BSM hibája",
	"ChargSysMalHighPrt" : "Töltőrendszerhiba. Parkoljon azonnal egy biztonságos helyre.",
	"ChargingSysErrorLong" : "Töltőrendszerhiba. \nA továbbhaladás a jármű károsodásához vezethet.  Azonnal álljon le egy biztonságos helyen, és kérje egy márkakereskedőtől a jármű felülvizsgálatát.\n",
	"ChargingSysErrorShrt" : "A tölőrendszer hibás",
	"ChrgSysErrorLong" : "Töltőrendszerhiba.\nAzonnal álljon le egy biztonságos helyen, és kérje egy márkakereskedőtől a jármű felülvizsgálatát.\n",
	"ChrgSysErrorShrt" : "Töltőrendszerhiba",
	"ColdStartDisableLong" : "A külső hőmérséklet rendkívüli lehűlése esetén a motor beindítása gátolva van, hogy az ne károsodjon. Kérjük, olvassa el a használati útmutatót. Mazda típusú járműve elindításakor motorblokkfűtő használatával kerülheti el a késlekedést.",
	"ColdStartDisableShrt" : "Hidegindítás kikapcsolva",
	"ControlSystemErrorLong" : "Parkoló fokozati vezérlőrendszer hibája.\nA hiba kivizsgálásának hiányában az alábbi problémák jelentkezhetnek:\n・A parkolózár esetleg nem fog működni. Parkoljon sík területen, és gondosan húzza be a kéziféket.\n・Az elektromos táplálás kapcsolója esetleg nem kapcsol ki. A kikapcsoláshoz ismételten meg kell nyomni az elektromos táplálás kapcsolóját.\n・ A \"Parkoláskor húzza be a kéziféket\" felirat vezetéskor eltűnik, megálláskor megjelenik.\nAzonnal kérje a márkakereskedőtől a jármű felülvizsgálatát.\n",
	"ControlSystemErrorShrt" : "A parkolási helyzet vezérlő rendszer hibás",
	"DPFErrorLong" : "Dízelmotor részecskeszűrőjének (DPF) hibája.\nKérje egy márkakereskedőtől a jármű felülvizsgálatát.\n",
	"DPFErrorShrt" : "Részecskeszűrő hibája",
	"DRSSSysErrorLong" : "Hiba a DRSS rendszerben.\nKérje egy Mazda márkakereskedőtől a jármű felülvizsgálatát.",
	"DRSSSysErrorShrt" : "DRSS hiba",
	"DefEmpty" : "A DEF kiürült",
	"DefLow" : "A DEF szint alacsony",
	"DefVeryLow" : "A DEF szintje rendkívül alacsony",
	"DriveBattDropLong" : "Alacsony a nagyfeszültségű akkumulátor maradék teljesítménye, mert a sebességváltó semleges (N) helyzetben volt hosszú ideig. Semleges fokozatban nem történik töltés. Ha hosszabb időre megáll, mindig váltson parkoló (P) fokozatba. Szükség esetén indítsa újra a hibrid rendszert az elektromos táplálás kapcsolójának megnyomásával.",
	"DriveBattDropShrt" : "Lemerülőben a nagyfeszültségű akkumulátor",
	"DropKeyBattChrgLong" : "Gyenge a távirányítóban az elem. Haladéktalanul cserélje ki az elemet.",
	"DropKeyBattChrgShrt" : "A távirányító elem merül",
	"DscSysErrorLong" : "Dynamic Stability Control (DSC), Traction Control System (TCS) vagy Hill Launch Assist (HLA) hibája.  Azonnal kérje egy márkakereskedőtől a jármű felülvizsgálatát.\n",
	"DscSysErrorShrt" : "Dinamikus menetstab.(DSC) hibája",
	"DscSystemErrorLong" : "Dinamikus menetstabilizáló (DSC) vagy kipörgésgátló (TCS) hibája.\nAzonnal kérje egy márkakereskedőtől a jármű felülvizsgálatát.\n",
	"DscSystemErrorShrt" : "Dinamikus menetstab.(DSC) hibája",
	"EcbSysErrorLong" : "Visszatápláló, illetve elektromos vezérlésű fékrendszer hibája. Azonnal álljon le egy biztonságos helyen, és kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"EcbSysErrorShrt" : "A fékrendszer hibás",
	"ElectricParkingBrakeHighLong" : "A rögzítőfékrendszer meghibásodott. Keresse fel Mazda kereskedőjét, és vizsgáltassa ki.",
	"ElectricParkingBrakeLong" : "A rögzítőfékrendszer meghibásodott. Keresse fel Mazda kereskedőjét, és vizsgáltassa ki.",
	"ElectricParkingBrakeShrt" : "A rögzítőfékrendszer meghibásodása",
	"ElectricVacuumPumpSystemMalfunctionLong" : "Az elektromos vákuumszivattyú-rendszer meghibásodott. Ha nem oldja meg a problémát, az rendszerhibához vezethet, így pedig váratlan veszély vagy meghibásodás léphet fel. Azonnal forduljon Mazda kereskedőjéhez, és vizsgáltassa ki a hibát.",
	"ElectricVacuumPumpSystemMalfunctionShrt" : "Az elektromos vákuumszivattyú-rendszer meghibásodása",
	"ElectronicThrottleControlLong" : "Ha a figyelmeztető lámpa égve marad, az az elektronikus vezérlőegység (ECU) hibájára utal.  Állítsa le, majd indítsa újra a Mazda motorját az elektronikus vezérlőegység visszaállításához, vagy vigye a járművet egy márkakereskedésbe. \n\nHa a figyelmeztető lámpa villog, az súlyos hibát jelez, a rendszer pedig korlátozza a motorteljesítményt.  A lehető leghamarabb vizsgáltassa meg járművét egy márkakereskedésben.  Próbálja meg visszaállítani az ECU-t a motor leállításával, majd ismételt elindításával. \n",
	"ElectronicThrottleControlShrt" : "Elektronikus fojtószelep-vezérlés",
	"EloopChargingLong" : "Az i‑ELOOP töltődik.\nJáró motor mellett ellenőrizze, hogy a töltés befejeződött-e, és a figyelmeztető jelzés megszűnt-e. Ha a jelzés nem szűnik meg, kérje egy márkakereskedőtől a jármű felülvizsgálatát.\n",
	"EloopChargingShrt" : "Az i‑ELOOP töltődik",
	"EloopSysErrorLong" : "i‑ELOOP rendszer hibája. Ha a jelzés nem szűnik meg, kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"EloopSysErrorShrt" : "i‑ELOOP rendszer hibája",
	"EngCoolntTempHighOnLong" : "Túlmelegszik a motor.\nAzonnal álljon le egy biztonságos helyen, és állítsa le a motort.  Olvassa el a Felhasználói útmutatót.\n",
	"EngCoolntTempHighOnShrt" : "Motor hűtőfolyadék hőm. magas",
	"EngOilPressureErrorLong" : "Alacsony motorolajnyomás.\nAzonnal álljon le egy biztonságos helyen, állítsa le a motort, majd ellenőrizze a motorolajszintet. Szükség esetét végezzen olajutántöltést.\nHa a jelzés olajutántöltést követően, illetve megfelelő motorolajszint ellenére sem szűnik meg, akkor azonnal kérje egy márkakereskedőtől a jármű felülvizsgálatát.\n",
	"EngOilPressureErrorShrt" : "Alacsony motorolajnyomás",
	"EngSystemErrorLong" : "Motorhiba.  Azonnal kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"EngSystemErrorShrt" : "Motorhiba",
	"EngineOilPressureErrorLong" : "Alacsony motorolajnyomás.\nAzonnal álljon le egy biztonságos helyen, állítsa le a motort, majd ellenőrizze a motorolajszintet. Szükség esetét végezzen olajutántöltést.\nHa a jelzés olajutántöltést követően, illetve megfelelő motorolajszint ellenére sem szűnik meg, akkor azonnal kérje egy márkakereskedőtől a jármű felülvizsgálatát.\n",
	"EngineOilPressureErrorShrt" : "Alacsony motorolajnyomás",
	"EngineWaterTempDropLong" : "Hideg a hűtőfolyadék, így a fűtés, ill. jégtelenítés/páramentesítés számára nincs meleg levegő. A jelzéstől függetlenül a jármű tovább vezethető.  Ha a jelzés nem szűnik meg, kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"EngineWaterTempDropShrt" : "Alacsony hűtőfoly.-hőmérséklet",
	"EngineWaterTempRiseLong" : "A motor kezd túlmelegedni.\nHajtson lassan vagy állítsa meg a járművet, amíg a villogó jelzés meg nem szűnik. Ha a villogó jelzés a jármű leállítása után is folytatódik, akkor tegye meg a szükséges intézkedéseket. Olvassa el a Felhasználói útmutatót.\n",
	"EngineWaterTempRiseShrt" : "Motor hűtőfolyadék hőm. magas",
	"EngnCoolTempHighHighPrt" : "Magas hűtőfolyadék-hőmérséklet. Parkoljon azonnal egy biztonságos helyre.",
	"FOWMRCCDRSSRadarSoilingLong" : "FOW/MRCC/DRSS érzékelő szennyezett.\nTisztítsa meg a radar (érzékelő) teljes felületét.",
	"FOWMRCCDRSSRadarSoilingShrt" : "FOW/MRCC/DRSS radar. Hiba",
	"FOWMRCCRadarSoilingLong" : "FOW/MRCC radarérzékelő hibája.\nAz esetleges szennyeződéstől vagy hótól tisztítsa meg az első díszrácson a Mazda embléma teljes felületét.  \nHa a jelzés nem szűnik meg, kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"FOWMRCCRadarSoilingShrt" : "FOW/MRCC radar. Hiba",
	"FOWSysError" : "FOW Hibája",
	"FOWSysErrorLong" : "Forward Obstruction Warning (FOW) hibája. Kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"FWDSysErrorLong" : "Összkerékhajtás rendszerhiba, vagy az első és hátsó abroncsméret eltérő. Kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"FWDSysErrorShrt" : "Összkerékhajtás rendszerhiba",
	"FuelAirFilterCartReplacePeriodLong" : "Az üzemanyagszűrő betétet ki kell cserélni.",
	"FuelAirFilterCartReplacePeriodShrt" : "Üzemanyagszűrő betét – csere szükséges",
	"FuelCapInspectionLong" : "A tanksapka esetleg nem került pontosan a helyére.\nEllenőrizze, hogy a tanksapka a helyén van-e és meg van-e szorítva.\nMiután a tanksapka a helyére került és meg lett szorítva, ez a jelzés még egy bizonyos ideig látható marad, amíg a rendszer vissza nem igazolja, hogy minden rendben van.  Ha a jelzés nem szűnik meg, kérje egy márkakereskedőtől a jármű felülvizsgálatát.\n",
	"FuelCapInspectionShrt" : "Tanksapka vizsgálat",
	"HBCALHUnavailableLong_1" : "A High Beam Control (Távolságifényszóró-vezérlés) funkció az utastérben fennálló magas hőmérséklet következtében átmenetileg nem üzemel. A High Beam Control (Távolságifényszóró-vezérlés) funkció az utastér megfelelő hőfokra történő lehűlését követően újra bekapcsol.",
	"HBCALHUnavailableLong_2" : "Az Adaptive LED Headlights (Adaptív LED-fényszórók) funkció az utastérben fennálló magas hőmérséklet következtében átmenetileg nem üzemel. Az Adaptive LED Headlights (Adaptív LED-fényszórók) funkció az utastér megfelelő hőfokra történő lehűlését követően újra bekapcsol.",
	"HBCALHUnavailableShrt_1" : "HBC nem áll rend.",
	"HBCALHUnavailableShrt_2" : "ALH nem áll rend.",
	"HBCLDWSSysErrorLong" : "High Beam Control (HBC)* és/vagy Lane Departure Warning System (LDWS)* meghibásodása. Amennyiben a jelzés nem szűnik meg, ellenőriztesse járművet egy márkakereskedésben.\n*A funkciók megléte függ a jármű típusától/felszereltségétől.",
	"HBCLDWSSysErrorLong_2" : "High Beam Control (HBC)/Lane-keep Assist System (LAS)  hibája. Ha a jelzés nem szűnik meg, kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"HBCLDWSSysErrorLong_3" : "Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS)  hibája. Ha a jelzés nem szűnik meg, kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"HBCLDWSSysErrorLong_4" : "Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS) hibája.  Ha a jelzés nem szűnik meg, kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"HBCLDWSSysErrorShrt" : "HBC/LDWS rend. hiba",
	"HBCLDWSSysErrorShrt_2" : "HBC/LAS rendszer hibája",
	"HBCLDWSSysErrorShrt_3" : "ALH/LDWS rendszer hibája",
	"HBCLDWSSysErrorShrt_4" : "ALH/LAS rendszer hibája",
	"HBCLDWSWindshieldFogLong" : "High Beam Control (HBC)* és/vagy Lane Departure Warning System (LDWS)* meghibásodása. Jégtelenítse/páramentesítse a szélvédőt.   Amennyiben a jelzés nem szűnik meg, ellenőriztesse járművét egy márkakereskedésben.\n*A funkciók megléte a függ a jármű típusától/felszereltségétől.",
	"HBCLDWSWindshieldFogLong_2" : "High Beam Control (HBC)/Lane-keep Assist System (LAS)  hibája. Jégtelenítse/páramentesítse a szélvédőt. Ha a jelzés nem szűnik meg, kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"HBCLDWSWindshieldFogLong_3" : "Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS)  hibája. Jégtelenítse/páramentesítse a szélvédőt. Ha a jelzés nem szűnik meg, kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"HBCLDWSWindshieldFogLong_4" : "Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS)  hibája. Jégtelenítse/páramentesítse a szélvédőt. Ha a jelzés nem szűnik meg, kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"HBCLDWSWindshieldFogShrt" : "HBC/LDWS rend. Hiba",
	"HBCLDWSWindshieldFogShrt_2" : "HBC/LAS rendszer hibája",
	"HBCLDWSWindshieldFogShrt_3" : "ALH/LDWS rendszer hibája",
	"HBCLDWSWindshieldFogShrt_4" : "ALH/LAS rendszer hibája",
	"HBCLLDWSCamDisconnectLong" : "High Beam Control (HBC)* és/vagy Lane Departure Warning System (LDWS)* meghibásodása. Tisztítsa meg a szélvédőt.  Amennyiben a jelzés nem szűnik meg, ellenőriztesse járművét egy márkakereskedésben.\n*A funkciók megléte függ a jármű típusától/felszereltségétől.",
	"HBCLLDWSCamDisconnectLong_2" : "High Beam Control (HBC)/Lane-keep Assist System (LAS) hibája. Tisztítsa meg a szélvédőt.  Ha a jelzés nem szűnik meg, kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"HBCLLDWSCamDisconnectLong_3" : "Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS) hibája. Tisztítsa meg a szélvédőt.  Ha a jelzés nem szűnik meg, kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"HBCLLDWSCamDisconnectLong_4" : "Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS) hiba. Tisztítsa meg a szélvédőt.  Ha a jelzés nem szűnik meg, kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"HBCLLDWSCamDisconnectShrt" : "HBC/LDWS kamera hiba",
	"HBCLLDWSCamDisconnectShrt_2" : "HBC/LAS kamera hiba",
	"HBCLLDWSCamDisconnectShrt_3" : "ALH/LDWS kamera hiba",
	"HBCLLDWSCamDisconnectShrt_4" : "ALH/LAS kamera hiba",
	"HBCSysErrorLong" : "High Beam Control (HBC) hibája.\nKérje egy márkakereskedőtől a jármű felülvizsgálatát.\n\n",
	"HBCSysErrorLong_2" : "Adaptive LED Headlights (ALH) hibája. Kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"HBCSysErrorShrt" : "HBC hiba",
	"HBCSysErrorShrt_2" : "ALH hibája",
	"HbcOrAlhUnavailable" : "HBC vagy ALH nem áll rendelkezésre",
	"HeadlightSystemErrorLongJ03" : "A fényszórórendszer meghibásodott. Ha a figyelmeztető fény folyamatosan villog, forduljon Mazda kereskedőjéhez.",
	"HighEngineOillevel" : "A motorolajszint magas.",
	"HighEngineOillevelDetail" : "A motor olajszintje túl magas. Cseréljen olajat.",
	"HybrdSysMalHighPrt" : "Hibridrendszerhiba. Parkoljon azonnal egy biztonságos helyre.",
	"HybridSysErrorLong" : "Hibridrendszerhiba.\nA továbbhaladás a jármű károsodásához vezethet. Azonnal álljon le egy biztonságos helyen, és kérje egy márkakereskedőtől a jármű felülvizsgálatát.\n",
	"HybridSysErrorShrt" : "A hibrid-rendszer hibás",
	"HybridSysOverheatLong" : "Hibridrendszerhiba.\nA továbbhaladás a jármű károsodásához vezethet. Azonnal álljon le egy biztonságos helyen, és kérje egy márkakereskedőtől a jármű felülvizsgálatát.\n",
	"HybridSysOverheatShrt" : "A hibrid-rendszer túlmelegedett",
	"IeloopChrgHighPrt" : "Az i‑ELOOP töltődik. Ellenőrizze járó motor mellett, hogy kész-e a töltés, és a figyelmeztető jelzés megszűnt-e.",
	"IstopSysErrorLong" : "Az i‑stop nem működtethető.\nKérje egy Mazda márkakereskedőtől a jármű felülvizsgálatát.\n",
	"IstopSysErrorShrt" : "i‑stop rendszerhiba",
	"KeylesSysErrorLong" : "Kulcs nélküli ajtónyitó rendszer hibája\nKérje egy márkakereskedőtől a jármű felülvizsgálatát.\n",
	"KeylesSysErrorShrt" : "Kulcs nélküli ajtónyitó hibája",
	"LDWSLASUnavailableLong_1" : "A Lane Departure Warning System (Sávelhagyásra figyelmeztető rendszer) az utastérben fennálló magas hőmérséklet következtében átmenetileg nem üzemel. A Lane Departure Warning System (Sávelhagyásra figyelmeztető rendszer) az utastér megfelelő hőfokra történő lehűlését követően újra bekapcsol.",
	"LDWSLASUnavailableLong_2" : "A Lane-Keep Assist System (Sávtartó asszisztens) funkció az utastérben fennálló magas hőmérséklet következtében átmenetileg nem üzemel. A Lane-Keep Assist System (Sávtartó asszisztens) funkció az utastér megfelelő hőfokra történő lehűlését követően újra bekapcsol.",
	"LDWSLASUnavailableShrt_1" : "LDWS nem áll rend.",
	"LDWSLASUnavailableShrt_2" : "LAS nem áll rend.",
	"LDWSSysErrorLong" : "Lane Departure Warning System (LDWS) hibája.\nKérje egy márkakereskedőtől a jármű felülvizsgálatát.\n",
	"LDWSSysErrorLong_2" : "Lane-keep Assist System (LAS)  hibája. Kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"LDWSSysErrorShrt" : "LDWS hiba",
	"LDWSSysErrorShrt_2" : "LAS  hibája",
	"LdwsOrLasUnavailable" : "Az LDWS vagy az LAS nem áll rendelkezésre.",
	"LowBrakeFluidLong" : "Alacsony fékfolyadékszint. Azonnal álljon le egy biztonságos helyen, és kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"LowBrakeFluidShrt" : "Alacsony fékfolyadékszint",
	"LowEngineOillevel" : "A motorolajszint alacsony.",
	"LowEngineOillevelDetail" : "A motor olajszintje túl alacsony.  Töltsön be olajat.",
	"LowFuelLong" : "Alacsony az üzemanyagszint.\nTankoljon hamarosan.\n",
	"LowFuelShrt" : "Alacsony üzemanyagszint",
	"LowTireAirPressureFlatLong" : "Ha a TPMS figyelmeztető fény kigyulladása után az  abroncsnyomás erősen lecsökken, vagy ha kilyukadt az abroncs, a lapos gumira figyelmeztető fény is kigyullad. Ha egy defekttűrő abroncs kilyukad, óvatosan vezessen el a legközelebbi Mazda kereskedőhöz, és cseréltesse ki az abroncsot.",
	"LowTireAirPressureLong" : "Alacsony abroncsnyomás egy vagy több keréken.\nEllenőrizze, majd állítsa be a kerekek helyes abroncsnyomását.  A nyomásbeállítás után addig nyomja a gumiabroncsnyomás-figyelő TPMS SET kapcsolót, amíg egy hangjelzést nem hall.",
	"LowTireAirPressureShrt" : "Alacsony abroncsnyomás",
	"LowWasheFluidLong" : "Alacsony szélvédőmosó folyadék szint. Végezze el a szélvédőmosó folyadék utántöltését.",
	"LowWasheFluidShrt" : "Alacsony szélvédőmosó f. szint",
	"MRCCSysErrorLong" : "Mazda Radar Cruise Control (MRCC) hibája. Kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"MRCCSysErrorShrt" : "MRCC hibája",
	"MRCCUnavailableLong" : "Mazda Radar Cruise Control (MRCC) jelenleg nem áll rendelkezésre.",
	"MRCCUnavailableShrt" : "MRCC nem áll rend.",
	"NoWarnings" : "Nem található figyelmeztetés.",
	"OilLevelSystemMalfunctioning" : "A motorolajszint-érzékelő meghibásodott.",
	"OilLevelSystemMalfunctioningDetail" : "A motorolajszint-érzékelő meghibásodott. Ellenőriztesse a járművet egy Mazda márkakereskedésben. ",
	"PowerSteeringSysErrorLong" : "Elektromos szervokormány hibája.\nÁlljon le egy biztonságos helyen, és állítsa le a motort.  Ha a jelzés nem szűnik meg, kérje egy márkakereskedőtől a jármű felülvizsgálatát.\n",
	"PowerSteeringSysErrorShrt" : "Szervokormány hibája",
	"PpositionRequestLong" : "A sebességváltó parkoló fokozatra vált.\nEnnek az alábbi okai lehetnek:\n・ Az akkumulátor-rendszer indítása, illetve leállítása a sebességváltónak a parkoló fokozattól eltérő fokozatában történt\n・ Kinyitották a vezető oldali ajtót, miközben a sebességváltó N, D vagy B fokozatban volt\n・ A maradék nagyfeszültségű akkumulátor töltöttsége alacsony, mert az átvitel semleges sokáig\nSzükség esetén indítsa újra a hibrid rendszert az elektromos táplálás kapcsolójának megnyomásával.",
	"PpositionRequestShrt" : "Parkoló fokozat kérés",
	"PreheatingDispLampLong" : "Izzógyertya előfűtése. Ha a jelzés nem szűnik meg, kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"PreheatingDispLampShrt" : "Izzógyertya előfűtése",
	"RoadSurfaceIcingCautionLong" : "4 °C vagy hidegebb külső hőmérséklet.\nVezetéskor figyeljen az út jegesedésére.\n",
	"RoadSurfaceIcingCautionShrt" : "Útjegesedési figyelmeztetés",
	"RvmSysErrorLong" : "Hiba a RVM rendszerben.\nEllenőrizze a hátsó lökhárító felületét, és az esetleges szennyeződéstől vagy hótól tisztítsa meg.\nHa a jelzés nem szűnik meg, kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"RvmSysErrorShrt" : "RVM hibája",
	"SBSBrakeMRCCUnavailableLong" : "SBS/MRCC jelenleg nem áll rendelkezésre.",
	"SBSBrakeMRCCUnavailableShrt" : "SBS/MRCC nem áll rend.",
	"SBSBrakeUnavailableLong" : "SBS jelenleg nem áll rendelkezésre.",
	"SBSBrakeUnavailableShrt" : "SBS nem áll rend.",
	"SBSMRCCDRSSRadarSoilingLong" : "SBS/MRCC/DRSS érzékelő szennyezett.\nTisztítsa meg a radar (érzékelő) teljes felületét.\n",
	"SBSMRCCDRSSRadarSoilingShrt" : "SBS/MRCC/DRSS radar. Hiba",
	"SBSMRCCRadarSoilingLong" : "SBS/MRCC érzékelő szennyezett.\nTisztítsa meg a radar (érzékelő) teljes felületét.",
	"SBSMRCCRadarSoilingShrt" : "SBS/MRCC radar. Hiba",
	"SBSSysErrorLong" : "Hiba a SBS rendszerben.\nKérje egy Mazda márkakereskedőtől a jármű felülvizsgálatát.\n",
	"SBSSysErrorShrt" : "SBS hibája",
	"SCBSSysErrorLong" : "Smart City Brake Support (SCBS) hibája.\nAzonnal kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"SCBSSysErrorLong_105" : "Smart City Brake Support (SCBS) hibája. Jégtelenítse/páramentesítse a szélvédőt. Ha a jelzés nem szűnik meg, kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"SCBSSysErrorShort_105" : "SCBS hibája",
	"SCBSSysErrorShrt" : "SCBS hibája",
	"SCBSUnavailableLong" : "Smart City Brake Support (SCBS) jelenleg nem áll rendelkezésre.",
	"SCBSUnavailableLong1" : "A Smart City Brake Support (Intelligens városi fékasszisztens) funkció az utastérben fennálló magas hőmérséklet következtében átmenetileg nem üzemel. A Smart City Brake Support (Intelligens városi fékasszisztens) funkció az utastér megfelelő hőfokra történő lehűlését követően újra bekapcsol.",
	"SCBSUnavailableShrt" : "SCBS nem áll rend.",
	"SCBSUnavailableShrt1" : "SCBS nem áll rend.",
	"SCBSWindshieldSoilingLong" : "Smart City Brake Support (SCBS) hibája.\nTisztítsa meg a szélvédőt.  Ha a jelzés nem szűnik meg, kérje egy márkakereskedőtől a jármű felülvizsgálatát.\n",
	"SCBSWindshieldSoilingShrt" : "SCBS hibája",
	"SCRMalfunction100Long" : "Károsanyag-kibocsátási SCR-hiba dízelmotornál.\nHa ezt a hibát nem orvosolják, a jármű sebessége korlátozva lesz.",
	"SCRMalfunction101Long" : "Károsanyag-kibocsátási SCR-hiba dízelmotornál.\nHa ezt a hibát nem orvosolják, a motor üresjáratba kényszerül.",
	"SCRMalfunction102Long" : "Károsanyag-kibocsátási SCR-hiba dízelmotornál. A motor üresjáratba kényszerült.\nA szervizhez lépjen kapcsolatba Mazda-kereskedőjével.",
	"ScrMalfunction" : "Az SCR hibája",
	"SedimenterWarningLong" : "Az ülepítőben összegyűlt vízmennyiség meghaladja a névleges értéket.\nHa a jelzés nem szűnik meg, kérje egy márkakereskedőtől a jármű felülvizsgálatát.\n",
	"SedimenterWarningShrt" : "Ülepítő vizsgálata",
	"SystemInspectionLong" : "A differenciálmű olajhőmérséklete rendellenesen magas, illetve nagy fordulatszám-különbség volt az első és hátsó kerekek között (mert például sáros területről próbált kijutni).\nÁlljon le egy biztonságos helyen, és csak akkor haladjon tovább, ha a figyelmeztető jelzés megszűnt. Ha a jelzés nem szűnik meg, kérje egy márkakereskedőtől a jármű felülvizsgálatát.\n",
	"SystemInspectionShrt" : "Összkerékhajtás rendszervizsgálat",
	"TpmsSysErrorLong" : "Gumiabroncsnyomás-figyelő (TPMS) hibája.\nKérje egy márkakereskedőtől a jármű felülvizsgálatát.\n",
	"TpmsSysErrorShrt" : "TPMS-rendszer hibás működése",
	"VehicleSysErrorLong" : "Járműrendszerhiba. Kérje egy márkakereskedőtől a jármű felülvizsgálatát.",
	"VehicleSysErrorShrt" : "Járműrendszerhiba",
	"WarningGuidance" : "Figyelmeztetés",
	"WarningSafetyMessage" : "A figyelmeztetéseket a rendszer biztonsági okokból nem jeleníti meg.",
	"Warnings" : "Figyelmeztetések",
	"brakeFluid" : "Fékfolyadék szint alacsony.",
	"engineOilPressure" : "Motorolaj nyomás",
	"highVoltage" : "Nagy feszültségű akk. lemerült.",
	"lowBattStartEngine" : "Akk. Lemerül! Indítsa be a motort!",
};

framework.registerAppDictLoaded("warnguide", "hu_HU");