var Localization_warnguideAppDict_pt_BR = {
	//"stringId" : "localString"
	"AbsSysErrorLong" : "Anti-lock Brake System (ABS) Malfunction. \nHave the vehicle checked by a dealer immediately.",
	"AbsSysErrorShrt" : "Anomalia no ABS",
	"AbsSystemErrorLong" : "Anti-lock Brake System (ABS) Malfunction. \nHave the vehicle checked by a dealer immediately.",
	"AbsSystemErrorShrt" : "Anomalia no ABS",
	"AccumulationDpfLong" : "O Material Particulado (PM), coletado no Filtro de Partículas do Diesel (DPF), ultrapassou o Valor Regulamentar admitido. Dirija por cerca de 10 a 15 minutos com o motor totalmente aquecido (luz azul da temperatura apagada) a uma velocidade de 10 mph (15 km/h) ou mais para eliminar o PM.  Se este indicador permanecer aceso, leve o veículo para inspeção em uma concessionária autorizada.",
	"AccumulationDpfShrt" : "Acúmulo de PM em DPF",
	"ActiveBonnetSystemMalfunctionLong" : "Active Bonnet System Malfunction. \nHave the vehicle checked by a dealer if this indicator stays on or continues to flash.",
	"ActiveBonnetSystemMalfunctionShrt" : "Anomalia no sistema Active Bonnet",
	"AfsSystemErrorLong" : "Anomalia no sistema de faróis dianteiros adaptativos (AFS). Se este indicador continuar piscando, leve o veículo para inspeção em uma concessionária autorizada.",
	"AfsSystemErrorShrt" : "Anomalia no AFS",
	"AfterRunCoolingPumpLong" : "Call or visit a dealer for service if your Mazda overheats. ",
	"AfterRunCoolingPumpShrt" : "After Run Cooling Pump",
	"AirbagSysPretensionerSysErrorLong" : "Anomalia no airbag/cinto de segurança. Leve o veículo imediatamente para inspeção em uma concessionária autorizada.",
	"AirbagSysPretensionerSysErrorShrt" : "Erro no sistema de airbags",
	"AutoLevelSystemErrorLong" : "Anomalia no sistema de auto-nivelamento de faróis dianteiros.\nSe este indicador permanecer aceso, leve o veículo para inspeção em uma concessionária autorizada.",
	"AutoLevelSystemErrorShrt" : "Anomalia no sistema de auto-nivelamento",
	"AutoLevelSystemErrorShrtJ03" : "Anomalia no sistema de faróis",
	"AutoTransSysErrorLong" : "Anomalia na transmissão automática. Continuar a dirigir pode causar ocorrer danos ao veículo.  Leve o veículo imediatamente para inspeção em uma concessionária autorizada.  ",
	"AutoTransSysErrorShrt" : "Anomalia no na transmissão automática",
	"AuxBattLowLong" : "A carga da bateria de 12 V está baixa.\n・Se este indicador ascender com frequência durante a condução, a bateria pode estar desgastada. Leve seu veículo para inspeção em uma concessionária autorizada.\n・Se este indicador permanecer constantemente aceso e não desligar, isso significa que a bateria de 12 V está completamente descarregada. Consulte o manual do proprietário antes de iniciar o Sistema Híbrido e leve o veículo para inspeção em uma concessionária autorizada.",
	"AuxBattLowShrt" : "Bateria de 12 V baixa",
	"BattManagSysErrorLong" : "Battery Management System Malfunction. \nHave the vehicle checked by a dealer.",
	"BattManagSysErrorShrt" : "Anomalia no sistema de gerenciamento da bateria",
	"BrakOverrideSysErrorLong" : "Anomalia no pedal do freio. Leve o veículo imediatamente para inspeção em uma concessionária autorizada.",
	"BrakOverrideSysErrorShrt" : "Anomalia no interruptor do pedal de freio",
	"BrakeSysErrorLong" : "Baixo nível de fluído dos freios ou sistema de freios com defeito. Pare o veículo imediatamente em um lugar seguro e solicite uma inspeção de uma concessionária autorizada.",
	"BrakeSysErrorShrt" : "Anomalia no sistema de freios",
	"BrakeSystemErrorLong" : "Sistema de freios controlados eletronicamente com defeito. Pare o veículo imediatamente em um lugar seguro e solicite uma inspeção de uma concessionária autorizada.",
	"BrakeSystemErrorShrt" : "Anomalia no sistema de freios",
	"BsmSystemErrorLong" : "Anomalia no Blind Spot Monitoring (BSM)/Rear Cross Traffic Alert (RCTA). Verifique se há alguma anormalidade na superfície do para-choque traseiro e limpe se estiver suja ou coberta de neve. Se este indicador permanecer aceso, leve o veículo para inspeção em uma concessionária autorizada.",
	"BsmSystemErrorShrt" : "Anomalia no BSM",
	"ChargSysMalHighPrt" : "Anomalia no sistema de carga. Pare o veículo imediatamente em um local seguro.",
	"ChargingSysErrorLong" : "Anomalia no sistema de carga. Se continuar a conduzir podem ocorrer danos ao veículo.  Pare o veículo imediatamente em um lugar seguro e solicite uma inspeção de uma concessionária autorizada.",
	"ChargingSysErrorShrt" : "Sistema de carregamento com defeito",
	"ChrgSysErrorLong" : "Anomalia no sistema de carregamento. Pare o veículo imediatamente em um lugar seguro e solicite uma inspeção de uma concessionária autorizada.",
	"ChrgSysErrorShrt" : "Anomalia no sistema de carga",
	"ColdStartDisableLong" : "While ambient temperature is extremely cold, engine cranking is inhibited to prevent engine damage. Please refer to owner’s manual. You can avoid possible delay when you start your Mazda by plugging in the engine block heater.",
	"ColdStartDisableShrt" : "Cold Start Disable",
	"ControlSystemErrorLong" : "Anomalia no sistema de controle da posição de estacionamento.\nSe não inspecionado, pode evoluir para uma das seguintes situações:\n・O mecanismo de bloqueio de estacionamento pode não funcionar corretamente. Estacione em um local plano e acione corretamente o freio de estacionamento (freio de mão).\n・A chave de alimentação pode não desligar. Pressione repetidamente a chave de alimentação para desligar.\n・ A mensagem \"Aplique o freio de estacionamento ao estacionar\" irá apagar quando estiver dirigindo e acender quando estiver parado.\nLeve o veículo imediatamente para inspeção em uma concessionária autorizada.",
	"ControlSystemErrorShrt" : "Erro no sistema de controle da posição de estacionamento",
	"DPFErrorLong" : "Diesel Particulate Filter (DPF) Malfunction. \nHave the vehicle checked by a dealer.",
	"DPFErrorShrt" : "Erro de DPF",
	"DRSSSysErrorLong" : "There is an error in the DRSS System. \nHave your vehicle checked at a Mazda dealer.",
	"DRSSSysErrorShrt" : "Anomalia no DRSS",
	"DefEmpty" : "DEF empty",
	"DefLow" : "DEF  low",
	"DefVeryLow" : "DEF very low",
	"DriveBattDropLong" : "A potência residual na bateria de alta voltagem está baixa, pois a transmissão permaneceu em ponto morto por um longo período de tempo. Não é possível efetuar o carregamento em ponto morto. Coloque na posição de estacionamento quanto ficar parado um longo período de tempo. Reinicialize o sistema híbrido pressionando a chave de alimentação, se necessário.",
	"DriveBattDropShrt" : "Bateria de alta voltagem baixa",
	"DropKeyBattChrgLong" : "Nível da bateria da chave eletrônica baixa. Substitua a bateria imediatamente.",
	"DropKeyBattChrgShrt" : "Bateria da chave baixa",
	"DscSysErrorLong" : "Anomalia no Dynamic Stability Control (DSC), Traction Control System (TCS) ou Hill Launch Assist (HLA). Leve o veículo imediatamente para inspeção em uma concessionária autorizada.",
	"DscSysErrorShrt" : "Anomalia no DSC",
	"DscSystemErrorLong" : "Anomalia no Controle dinâmico de estabilidade (DSC) ou Sistema de controle de tração (TCS). Leve o veículo imediatamente para inspeção em uma concessionária autorizada.",
	"DscSystemErrorShrt" : "Anomalia no DSC",
	"EcbSysErrorLong" : "Anomalia na frenagem regenerativa ou sistema de freios controlados eletronicamente. Pare o veículo imediatamente em um lugar seguro e solicite uma inspeção de uma concessionária autorizada.",
	"EcbSysErrorShrt" : "Anomalia no sistema de freios",
	"ElectricParkingBrakeHighLong" : "Ocorreu uma falha no sistema de freio de estacionamento.\nLeve seu veículo para inspeção em uma concessionária autorizada Mazda.",
	"ElectricParkingBrakeLong" : "Ocorreu uma falha no sistema de freio de estacionamento.\nLeve seu veículo para inspeção em uma concessionária autorizada Mazda.",
	"ElectricParkingBrakeShrt" : "Anomalia no sistema de freio de estacionamento",
	"ElectricVacuumPumpSystemMalfunctionLong" : "A malfunction has occurred in the electric vacuum pump system. Leaving this issue unresolved may cause the system to fail, which will pose unexpected danger or damage. Consult your Mazda Dealer immediately and have the malfunction inspected.",
	"ElectricVacuumPumpSystemMalfunctionShrt" : "Anomalia no sistema de bomba elétrica à vácuo do freio",
	"ElectronicThrottleControlLong" : "If the warning lamp stays on, there is a malfunction in the Electronic Control Unit.  Restart the engine on your Mazda to reset the Electronic Control Unit, or take it to a dealer for service. \n\nIf the warning lamp blinks, a severe malfunction has occurred, and the throttle output will be limited.  Have the vehicle serviced at your dealer as soon as possible.  Attempt to reset the Electronic Control Unit by restarting the engine. \n",
	"ElectronicThrottleControlShrt" : "Electronic Throttle Control",
	"EloopChargingLong" : "O i‑ELOOP está carregando. Com o motor em funcionamento, verifique se a carga está completa e o indicador de alerta está apagado. Se este indicador permanecer aceso, leve o veículo para inspeção em uma concessionária autorizada.",
	"EloopChargingShrt" : "i‑ELOOP carregando",
	"EloopSysErrorLong" : "Anomalia no sistema i‑ELOOP. Se este indicador permanecer aceso, leve o veículo para inspeção em uma concessionária autorizada.",
	"EloopSysErrorShrt" : "Anomalia no sistema i‑ELOOP",
	"EngCoolntTempHighOnLong" : "O motor está superaquecendo. Pare o veículo imediatamente em um lugar seguro, desligue o motor e tome as medidas adequadas.  Consulte o manual do proprietário.",
	"EngCoolntTempHighOnShrt" : "Alta temperatura do líquido de arrefecimento do motor",
	"EngOilPressureErrorLong" : "Baixa pressão do óleo do motor. Pare o veículo imediatamente em um lugar seguro, desligue o motor e verifique o nível de óleo do motor. Adicione óleo, se necessário. Leve o veículo imediatamente para inspeção em uma concessionária autorizada se este indicador permanecer aceso após a adição de óleo ou se o nível de óleo do motor estiver bom.",
	"EngOilPressureErrorShrt" : "Baixa pressão do óleo do motor",
	"EngSystemErrorLong" : "Anomalia no sistema do motor.  Leve o veículo imediatamente para inspeção em uma concessionária autorizada.",
	"EngSystemErrorShrt" : "Anomalia no sistema do motor",
	"EngineOilPressureErrorLong" : "Baixa pressão do óleo do motor. Pare o veículo imediatamente em um lugar seguro, desligue o motor e verifique o nível de óleo do motor. Adicione óleo, se necessário. Leve o veículo imediatamente para inspeção em uma concessionária autorizada se este indicador permanecer aceso após a adição de óleo ou se o nível de óleo do motor estiver bom.",
	"EngineOilPressureErrorShrt" : "Baixa pressão do óleo do motor",
	"EngineWaterTempDropLong" : "O líquido de arrefecimento do motor está frio e não há ar quente disponível para o aquecedor/descongelador. O veículo pode ser dirigido com o indicador aceso ou apagado.  Se este indicador permanecer aceso, leve o veículo para inspeção em uma concessionária autorizada.",
	"EngineWaterTempDropShrt" : "Temperatura do líquido de arrefecimento do motor baixa",
	"EngineWaterTempRiseLong" : "O motor está começando a ficar quente. Dirija devagar ou pare o veículo até que o indicador pare de piscar. Se ele continuar piscando, mesmo após parar o veículo, tome as medidas adequadas. Consulte o manual do proprietário.",
	"EngineWaterTempRiseShrt" : "Alta temperatura do líquido de arrefecimento do motor",
	"EngnCoolTempHighHighPrt" : "Temperatura do líquido de arrefecimento do motor alta. Pare o veículo imediatamente em um local seguro.",
	"FOWMRCCDRSSRadarSoilingLong" : "O radar FOW/MRCC/DRSS (sensor) está sujo. Limpe toda a superfície do radar (sensor).",
	"FOWMRCCDRSSRadarSoilingShrt" : "Erro de radar FOW/MRCC/DRSS",
	"FOWMRCCRadarSoilingLong" : "Anomalia no radar FOW/MRCC (sensor). Limpe toda a superfície da grade do emblema frontal se estiver suja ou coberta de neve. Se este indicador permanecer aceso, leve o veículo para inspeção em uma concessionária autorizada.",
	"FOWMRCCRadarSoilingShrt" : "Anomalia no radar FOW/MRCC",
	"FOWSysError" : "Anomalia no FOW",
	"FOWSysErrorLong" : "Anomalia no sistema Forward Obstruction Warning (FOW). Leve seu veículo para inspeção em uma concessionária autorizada.",
	"FWDSysErrorLong" : "Anomalia no sistema 4WD ou tamanho diferente dos pneus dianteiros e traseiros.\nLeve o veículo para inspeção em uma concessionária autorizada.",
	"FWDSysErrorShrt" : "Anomalia no sistema 4WD",
	"FuelAirFilterCartReplacePeriodLong" : "The Fuel Filter Cartridge needs to be replaced.",
	"FuelAirFilterCartReplacePeriodShrt" : "Fuel Filter Replacement Rqd.",
	"FuelCapInspectionLong" : "A tampa do tanque de combustível pode não ter sido colocada adequadamente.\nVerifique se a tampa do tanque de combustível foi colocada e apertada corretamente. Após colocar e apertar corretamente a tampa do tanque de combustível, este indicador não irá desligar antes da alguns percursos, até que seja possível confirmar que o sistema está ok.  Se este indicador permanecer aceso, leve o veículo para inspeção em uma concessionária autorizada.",
	"FuelCapInspectionShrt" : "Inspecione a tampa do tanque de combustível",
	"HBCALHUnavailableLong_1" : "High Beam Control is temporarily disabled due to excessive heat in the passenger compartment. The High Beam Control will be enabled once the passenger compartment has cooled sufficiently.",
	"HBCALHUnavailableLong_2" : "Adaptive LED Headlights are temporarily disabled due to excessive heat in the passenger compartment. The Adaptive LED Headlights will be enabled once the passenger compartment has cooled sufficiently.",
	"HBCALHUnavailableShrt_1" : "HBC Unavailable",
	"HBCALHUnavailableShrt_2" : "ALH Unavailable",
	"HBCLDWSSysErrorLong" : "Anomalia no High Beam Control (HBC)/Lane Departure Warning System (LDWS). Se este indicador permanecer aceso, leve o veículo para inspeção em uma concessionária autorizada.",
	"HBCLDWSSysErrorLong_2" : "Anomalia no High Beam Control (HBC)/Lane-keep Assist System (LAS). Se este indicador permanecer aceso, leve o veículo para inspeção em uma concessionária autorizada.",
	"HBCLDWSSysErrorLong_3" : "Anomalia no Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS). Se este indicador permanecer aceso, leve o veículo para inspeção em uma concessionária autorizada.",
	"HBCLDWSSysErrorLong_4" : "Anomalia no Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS). Se este indicador permanecer aceso, leve o veículo para inspeção em uma concessionária autorizada.",
	"HBCLDWSSysErrorShrt" : "Anomalia no sistema HBC/LDWS",
	"HBCLDWSSysErrorShrt_2" : "Anomalia no Sistema HBC/LAS",
	"HBCLDWSSysErrorShrt_3" : "Anomalia no Sistema ALH/LDWS",
	"HBCLDWSSysErrorShrt_4" : "Anomalia no Sistema ALH/LAS",
	"HBCLDWSWindshieldFogLong" : "Anomalia no High Beam Control (HBC)/Lane Departure Warning System (LDWS). Descongele o para-brisa.  Se este indicador permanecer aceso, leve o veículo para inspeção em uma concessionária autorizada.",
	"HBCLDWSWindshieldFogLong_2" : "Anomalia no High Beam Control (HBC)/Lane-keep Assist System (LAS). Descongele o para-brisa.  Se este indicador permanecer aceso, leve o veículo para inspeção em uma concessionária autorizada.",
	"HBCLDWSWindshieldFogLong_3" : "Anomalia no Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS). Descongele o para-brisa.  Se este indicador permanecer aceso, leve o veículo para inspeção em uma concessionária autorizada.",
	"HBCLDWSWindshieldFogLong_4" : "Anomalia no Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS). Descongele o para-brisa.  Se este indicador permanecer aceso, leve o veículo para inspeção em uma concessionária autorizada.",
	"HBCLDWSWindshieldFogShrt" : "Anomalia no sistema HBC/LDWS",
	"HBCLDWSWindshieldFogShrt_2" : "Anomalia no Sistema HBC/LAS",
	"HBCLDWSWindshieldFogShrt_3" : "Anomalia no Sistema ALH/LDWS",
	"HBCLDWSWindshieldFogShrt_4" : "Anomalia no Sistema ALH/LAS",
	"HBCLLDWSCamDisconnectLong" : "Anomalia no High Beam Control (HBC)/Lane Departure Warning System (LDWS). Limpe o para-brisa.  Se este indicador permanecer aceso, leve o veículo para inspeção em uma concessionária autorizada.",
	"HBCLLDWSCamDisconnectLong_2" : "Anomalia no High Beam Control (HBC)/Lane-keep Assist System (LAS). Limpe o para-brisa.  Se este indicador permanecer aceso, leve o veículo para inspeção em uma concessionária autorizada.",
	"HBCLLDWSCamDisconnectLong_3" : "Anomalia no Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS). Limpe o para-brisa.  Se este indicador permanecer aceso, leve o veículo para inspeção em uma concessionária autorizada.",
	"HBCLLDWSCamDisconnectLong_4" : "Anomalia no Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS). Limpe o para-brisa.  Se este indicador permanecer aceso, leve o veículo para inspeção em uma concessionária autorizada.",
	"HBCLLDWSCamDisconnectShrt" : "Anomalia na câmera HBC/LDWS",
	"HBCLLDWSCamDisconnectShrt_2" : "Anomalia na Câmera HBC/LAS",
	"HBCLLDWSCamDisconnectShrt_3" : "Anomalia na Câmera ALH/LDWS",
	"HBCLLDWSCamDisconnectShrt_4" : "Anomalia na Câmera ALH/LAS",
	"HBCSysErrorLong" : "Anomalia no High Beam Control (HBC). Leve seu veículo para inspeção em uma concessionária autorizada.\n\n",
	"HBCSysErrorLong_2" : "Anomalia no Adaptive LED Headlights (ALH). Leve o veículo para inspeção em uma concessionária autorizada.",
	"HBCSysErrorShrt" : "Anomalia no HBC",
	"HBCSysErrorShrt_2" : "Anomalia no ALH",
	"HbcOrAlhUnavailable" : "HBC or ALH Unavailable",
	"HeadlightSystemErrorLongJ03" : "Anomalia no sistema de faróis.\nCompareça a uma inspeção em uma concessionária autorizada Mazda.",
	"HighEngineOillevel" : "Nível de óleo do motor alto",
	"HighEngineOillevelDetail" : "O nível do óleo do motor está muito alto. Substitua o óleo. ",
	"HybrdSysMalHighPrt" : "Anomalia no sistema híbrido. Pare o veículo imediatamente em um local seguro.",
	"HybridSysErrorLong" : "Anomalia no sistema híbrido. Continuar dirigindo pode causar danos ao veículo. Pare o veículo imediatamente em um lugar seguro e solicite uma inspeção de uma concessionária autorizada.",
	"HybridSysErrorShrt" : "Sistema híbrido com defeito",
	"HybridSysOverheatLong" : "Anomalia no sistema híbrido. Continuar dirigindo pode causar danos ao veículo. Pare o veículo imediatamente em um lugar seguro e solicite uma inspeção de uma concessionária autorizada.",
	"HybridSysOverheatShrt" : "Superaquecimento do sistema híbrido",
	"IeloopChrgHighPrt" : "i‑ELOOP carregando. Com o motor em funcionamento, verifique se a carga está completa e o indicador de alerta está apagado.",
	"IstopSysErrorLong" : "Não é possível operar o i‑stop.\nLeve seu veículo para inspeção em uma concessionária autorizada Mazda.",
	"IstopSysErrorShrt" : "Anomalia no sistema i‑stop",
	"KeylesSysErrorLong" : "Anomalia no sistema da chave eletrônica. Leve o veículo para inspeção em uma concessionária autorizada.",
	"KeylesSysErrorShrt" : "Chave Eletronica não detectada",
	"LDWSLASUnavailableLong_1" : "Lane Departure Warning System is temporarily disabled due to excessive heat in the passenger compartment. The Lane Departure Warning System will be enabled once the passenger compartment has cooled sufficiently.",
	"LDWSLASUnavailableLong_2" : "Lane-Keep Assist System is temporarily disabled due to excessive heat in the passenger compartment. The Lane-Keep Assist System will be enabled once the passenger compartment has cooled sufficiently.",
	"LDWSLASUnavailableShrt_1" : "LDWS Unavailable",
	"LDWSLASUnavailableShrt_2" : "LAS Unavailable",
	"LDWSSysErrorLong" : "Lane Departure Warning System (LDWS) Malfunction. \nHave the vehicle checked by a dealer.\n",
	"LDWSSysErrorLong_2" : "Lane-keep Assist System (LAS) Malfunction. \nHave the vehicle checked by a dealer.",
	"LDWSSysErrorShrt" : "Anomalia no LDWS",
	"LDWSSysErrorShrt_2" : "Anomalia no LAS",
	"LdwsOrLasUnavailable" : "LDWS or LAS Unavailable",
	"LowBrakeFluidLong" : "O nível do fluído de freios está baixo. Pare o veículo imediatamente em um lugar seguro e solicite uma inspeção de uma concessionária autorizada.",
	"LowBrakeFluidShrt" : "Nível baixo de fluido de freio",
	"LowEngineOillevel" : "Nível de óleo do motor baixo",
	"LowEngineOillevelDetail" : "O nível do óleo do motor está muito baixo.  Adicione óleo.",
	"LowFuelLong" : "O nível de combustível do tanque está baixo.\nReabasteça o veículo assim que possível.",
	"LowFuelShrt" : "Baixo nível de combustível",
	"LowTireAirPressureFlatLong" : "Baixa pressão de ar do pneu\nSe a pressão de ar cair de forma significativa depois de a luz TPMS acender, ou se o pneu furar, a luz de alerta de pneu furado também acenderá. Se um pneu de esvaziamento limitado for perfurado, dirija o veículo cuidadosamente até a concessionária Mazda mais próxima e troque o pneu.",
	"LowTireAirPressureLong" : "Baixa pressão de ar em um ou mais pneus. \nVerifique a pressão de ar nos pneus e ajuste para o nível adequado.  Pressione a chave DEFINIR TPMS após ajustar a pressão de ar nos pneus até ouvir um bip.",
	"LowTireAirPressureShrt" : "Baixa pressão de ar no pneu",
	"LowWasheFluidLong" : "O nível do fluido do lavador do para-brisa está baixo. Adicione fluido do lavador.",
	"LowWasheFluidShrt" : "Baixo nível do fluido do lavador",
	"MRCCSysErrorLong" : "Mazda Radar Cruise Control (MRCC) Malfunction. \nHave the vehicle checked by a dealer.",
	"MRCCSysErrorShrt" : "Anomalia no MRCC",
	"MRCCUnavailableLong" : "Mazda Radar Cruise Control (MRCC) indisponível no momento.",
	"MRCCUnavailableShrt" : "MRCC indisponível",
	"NoWarnings" : "Nenhum alerta encontrado",
	"OilLevelSystemMalfunctioning" : "Mau funcionamento do sensor de nível do óleo do motor",
	"OilLevelSystemMalfunctioningDetail" : "Avaria no sensor do nível de óleo do motor. Leve o veículo a um concessionário Mazda. ",
	"PowerSteeringSysErrorLong" : "Anomalia na direção hidráulica. Pare o veículo em um local seguro e desligue o motor.  Se este indicador permanecer aceso, leve o veículo para inspeção em uma concessionária autorizada.",
	"PowerSteeringSysErrorShrt" : "Anomalia no sistema de direção hidráulica",
	"PpositionRequestLong" : "Coloque a transmissão na posição de Estacionamento (P).\nIsto pode ser causado por um dos seguintes fatores:\n・ O sistema de bateria foi iniciado ou interrompido com a transmissão em uma posição diferente da posição de estacionamento\n・ A porta do motorista foi aberta com a transmissão nas posições N, D ou B\n・ A carga residual da bateria de alta voltagem está baixa, pois a transmissão ficou em ponto morto por um período de tempo muito longo.\nReinicialize o sistema híbrido pressionando a chave de alimentação, se necessário.",
	"PpositionRequestShrt" : "Solicitação da posição de estacionamento",
	"PreheatingDispLampLong" : "As velas incandescentes estão pré-aquecendo. Se este indicador permanecer aceso, leve o veículo para inspeção em uma concessionária autorizada.",
	"PreheatingDispLampShrt" : "Velas incandescentes pré-aquecendo",
	"RoadSurfaceIcingCautionLong" : "Temperatura externa é de 4 °C ou inferior. Fique atento a possíveis superfícies de estrada congeladas ao dirigir.",
	"RoadSurfaceIcingCautionShrt" : "Atenção com congelamento da superfície da estrada",
	"RvmSysErrorLong" : "Anomalia no Sistema RVM.\nVerifique se há alguma anormalidade na superfície do para-choque traseiro e limpe se estiver suja ou coberta de neve. Se esta luz indicadora permanecer acesa, leve o veículo para inspeção em uma concessionária autorizada da Mazda.",
	"RvmSysErrorShrt" : "Anomalia no RVM",
	"SBSBrakeMRCCUnavailableLong" : "Freio SBS/MRCC indisponível no momento.",
	"SBSBrakeMRCCUnavailableShrt" : "Freio SBS/MRCC indisponível",
	"SBSBrakeUnavailableLong" : "Freio SBS indisponível no momento.",
	"SBSBrakeUnavailableShrt" : "Freio SBS indisponível",
	"SBSMRCCDRSSRadarSoilingLong" : "O radar SBS/MRCC/DRSS (sensor) está sujo. Limpe toda a superfície do radar (sensor).",
	"SBSMRCCDRSSRadarSoilingShrt" : "Erro de radar SBS/MRCC/DRSS",
	"SBSMRCCRadarSoilingLong" : "O radar SBS/MRCC (sensor) está sujo. Limpe toda a superfície do radar (sensor).",
	"SBSMRCCRadarSoilingShrt" : "Anomalia no Radar SBS/MRCC",
	"SBSSysErrorLong" : "There is an error in the SBS System. \nHave your vehicle checked at a Mazda dealer.",
	"SBSSysErrorShrt" : "Anomalia no SBS",
	"SCBSSysErrorLong" : "Smart City Brake Support (SCBS) Malfunction. \nHave the vehicle checked by a dealer immediately.",
	"SCBSSysErrorLong_105" : "Smart City Brake Support (SCBS) Malfunction. Defrost the Windshield.  Have the vehicle checked by a dealer if this Indicator stays On.",
	"SCBSSysErrorShort_105" : "SCBS Malfunction.",
	"SCBSSysErrorShrt" : "Anomalia no SCBS",
	"SCBSUnavailableLong" : "Smart City Brake Support (SCBS) indisponível no momento.",
	"SCBSUnavailableLong1" : "Smart City Brake Support system is temporarily disabled due to excessive heat in the passenger compartment. The Smart City Brake Support system will be enabled once the passenger compartment has cooled sufficiently.",
	"SCBSUnavailableShrt" : "SCBS indisponível",
	"SCBSUnavailableShrt1" : "SCBS Unavailable",
	"SCBSWindshieldSoilingLong" : "Smart City Brake Support (SCBS) Malfunction. \nClean the Front Windshield.  Have the vehicle checked by a dealer if this Indicator stays On.",
	"SCBSWindshieldSoilingShrt" : "Anomalia no SCBS",
	"SCRMalfunction100Long" : "Diesel Emissions SCR Malfunction.\nIf this issue is not addressed, vehicle speed will be limited.",
	"SCRMalfunction101Long" : "Diesel Emissions SCR Malfunction.\nIf this issue is not addressed, engine will go into forced idle mode.",
	"SCRMalfunction102Long" : "Diesel Emissions SCR Malfunction. Engine is now in forced idle mode.\nPlease contact your Mazda Dealer for service.",
	"ScrMalfunction" : "SCR Malfunction",
	"SedimenterWarningLong" : "A quantidade de água acumulada no sedimentador excede o valor nominal. Se este indicador permanecer aceso, leve o veículo para inspeção em uma concessionária autorizada.",
	"SedimenterWarningShrt" : "Inspeção do sedimentador",
	"SystemInspectionLong" : "A temperatura do óleo do diferencial está anormalmente elevada ou ocorreu uma diferença de rotação significativa entre os pneus dianteiros e traseiros (como quando se tenta sair da lama, por exemplo). Pare o veículo em um local seguro e continue a dirigir depois que o indicador de alerta se apagar. Se este indicador permanecer aceso, leve o veículo para inspeção em uma concessionária autorizada.",
	"SystemInspectionShrt" : "Inspeção do sistema 4WD",
	"TpmsSysErrorLong" : "Anomalia no sistema de monitoramento da pressão de ar nos pneus (TPMS). Leve o veículo para inspeção em uma concessionária autorizada.",
	"TpmsSysErrorShrt" : "Anomalia no sistema TPMS",
	"VehicleSysErrorLong" : "Anomalia no sistema do veículo. Leve o veículo para inspeção em uma concessionária autorizada.",
	"VehicleSysErrorShrt" : "Anomalia no sistema do veículo",
	"WarningGuidance" : "Alertas de orientação",
	"WarningSafetyMessage" : "Por motivos de segurança, os alertas de orientação não são exibidos.",
	"Warnings" : "Alertas",
	"brakeFluid" : "Nível baixo do fluido de freio",
	"engineOilPressure" : "Pressão de óleo do motor",
	"highVoltage" : "Bateria de alta voltagem baixa",
	"lowBattStartEngine" : "Bateria fraca. Dê partida no motor!",
};

framework.registerAppDictLoaded("warnguide", "pt_BR");