var Localization_warnguideAppDict_de_DE = {
	//"stringId" : "localString"
	"AbsSysErrorLong" : "Fehlfunktion des Anti-Blockier-Bremssystems (ABS). \nLassen Sie Ihr Fahrzeug sofort bei einem Mazda-Händler überprüfen.\n",
	"AbsSysErrorShrt" : "ABS-Fehlfunktion",
	"AbsSystemErrorLong" : "Fehlfunktion des Anti-Blockier-Bremssystems (ABS). \nLassen Sie Ihr Fahrzeug sofort bei einem Mazda-Händler überprüfen.\n",
	"AbsSystemErrorShrt" : "ABS-Fehlfunktion",
	"AccumulationDpfLong" : "Die im Diesel-Partikelfilter (DPF) gesammelten Partikel (PM), haben den Grenzwert überschritten. \nFahren Sie für etwa 10 bis 15 Minuten bei voll aufgewärmten Motor (blaues Temperatur-Licht aus) bei einer Geschwindigkeit von 10 mph (15km/h) oder mehr, um die PM zu beseitigen.  Lassen Sie Ihr Fahrzeug von einem Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet",
	"AccumulationDpfShrt" : "Rußpartikelansammlung im DPF",
	"ActiveBonnetSystemMalfunctionLong" : "Fehlfunktion im Active Bonnet system.\nLassen Sie das Fahrzeug von einem Händler überprüfen, falls diese Anzeige anbleibt oder weiterhin blinkt.",
	"ActiveBonnetSystemMalfunctionShrt" : "Fehlfunktion im Active Bonnet System",
	"AfsSystemErrorLong" : "Adaptives Frontbeleuchtungssystem (AFS) Fehlfunktion. Lassen Sie Ihr Fahrzeug von einem Händler überprüfen, wenn die Warnleuchte weiterhin blinkt.",
	"AfsSystemErrorShrt" : "AFS-Fehlfunktion",
	"AfterRunCoolingPumpLong" : "Bei Überhitzung Ihres Mazda rufen Sie bei einem Händler an oder fahren Sie dort zur Überprüfung vorbei. ",
	"AfterRunCoolingPumpShrt" : "Nachlauf Kühlmittelpumpe",
	"AirbagSysPretensionerSysErrorLong" : "Airbag/Sicherheitsgurt-Fehlfunktion. Lassen Sie Ihr Fahrzeug sofort bei einem Händler überprüfen.",
	"AirbagSysPretensionerSysErrorShrt" : "Sicherheits-Rückhaltesystem Systemfehler",
	"AutoLevelSystemErrorLong" : "Fehlfunktion der automatischen Scheinwerferhöhenverstellung. \nLassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn dieses Warnlicht weiterhin leuchtet.",
	"AutoLevelSystemErrorShrt" : "Auto-Regulierungs-Systems-Fehlfunktion",
	"AutoLevelSystemErrorShrtJ03" : "Scheinwerfersystem-Fehlfunktion",
	"AutoTransSysErrorLong" : "Automatikgetriebe-Fehlfunktion. Wenn Sie weiterfahren, kann das Fahrzeug beschädigt werden. Lassen Sie Ihr Fahrzeug sofort bei einem Händler überprüfen.  ",
	"AutoTransSysErrorShrt" : "Fehlfunktion Automatikgetriebe",
	"AuxBattLowLong" : "Niedrige Ladung der 12V-Starterbatterie.\n· Wenn diese Anzeige häufig während der Fahrt leuchtet, kann die Batterie beeinträchtigt werden. Lassen Sie das Fahrzeug von einem Händler überprüfen.\n· Wenn diese Anzeige ständig leuchtet und nicht mehr ausgeht, ist die 12V-Statrerbatterie leer. Sehen Sie vor dem Start des Hybridsystems in der Bedienungsanleitung nach und lassen das Fahrzeug von einem Händler überprüfen.",
	"AuxBattLowShrt" : "12V-Batterie fast leer",
	"BattManagSysErrorLong" : "Batteriemanagement-Systemfehlfunktion \nLassen Sie Ihr Fahrzeug bei einem Händler überprüfen.",
	"BattManagSysErrorShrt" : "Fehlfunktion Batteriesteuerungssyst.",
	"BrakOverrideSysErrorLong" : "Bremsschalterfehlfunktion. \nLassen Sie Ihr Fahrzeug sofort bei einem Händler überprüfen.",
	"BrakOverrideSysErrorShrt" : "Bremsüberbrückung-Systemfehler",
	"BrakeSysErrorLong" : "Niedriger Bremsflüssigkeitsstand oder Bremssystemfehlfunktion. Das Fahrzeug sofort an einer sicheren Stelle anhalten und von einem Händler überprüfen lassen.",
	"BrakeSysErrorShrt" : "Bremssystemfehlfunktion",
	"BrakeSystemErrorLong" : "Fehlfunktion im elektronisch überwachten Bremssystem. Das Fahrzeug sofort an einer sicheren Stelle anhalten und von einem Händler überprüfen lassen.",
	"BrakeSystemErrorShrt" : "Bremsen-Systemfehlfunktion",
	"BsmSystemErrorLong" : "Blind Spot Monitoring (BSM)-/Rear Cross Traffic Alert (RCTA)-Fehlfunktion. Überprüfen Sie die Oberfläche der hinteren Stoßstange auf Auffälligkeiten und reinigen Sie sie bei Verschmutzung oder sie falls mit Schnee bedeckt ist. Lassen Sie Ihr Fahrzeug bei einem Mazda-Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.",
	"BsmSystemErrorShrt" : "BSM-Fehlfunktion",
	"ChargSysMalHighPrt" : "Ladevorgangs-Systemfehlfunktion. Halten Sie das Fahrzeug sofort an einer sicheren Stelle an.",
	"ChargingSysErrorLong" : "Ladevorgang Systemfehlfunktion. Wenn Sie weiterfahren, kann das Fahrzeug beschädigt werden. Das Fahrzeug sofort an einer sicheren Stelle anhalten und von einem Händler überprüfen lassen.",
	"ChargingSysErrorShrt" : "Ladesystemfehlfunktion",
	"ChrgSysErrorLong" : "Ladesystemfehlfunktion \nDas Fahrzeug sofort an einer sicheren Stelle anhalten und von einem Händler überprüfen lassen.",
	"ChrgSysErrorShrt" : "Ladesystemfehlfunktion",
	"ColdStartDisableLong" : "Bei extrem niedrigen Außentemperaturen wird die Drehung des Motors unterdrückt, um Motorschäden zu vermeiden. Weitere Informationen hierzu entnehmen Sie bitte dem Benutzerhandbuch. Sie können mögliche Verzögerungen beim Starten des Mazda vermeiden, indem Sie die Motorblockheizung anschließen.",
	"ColdStartDisableShrt" : "Kaltstart deaktiviert",
	"ControlSystemErrorLong" : "Fehler Einparkhilfe. Wenn dies nicht überprüft wird, kann das zu den folgenden Situationen führen: \n・Der Park-Schließechanismus funktioniert ggf. nicht. Parken Sie auf einer flachen Stelle und verwenden Sie die Feststellbremse. \n・Der Netzschalter läßt sich ggf. nicht ausschalten. Drücken Sie zum Ausschalten wiederholt den Netzschalter. \n・ Die Anzeige\"Feststellbremse beim Parken verwenden\" geht beim Fahren und bei Anhalten aus. \nLassen Sie Ihr Fahrzeug  bei einem Händler überprüfen.\n",
	"ControlSystemErrorShrt" : "Sytemfehler Einparkhilfe",
	"DPFErrorLong" : "Diesel-Partikelfilter (DPF) Fehlfunktion \nLassen Sie Ihr Fahrzeug  bei einem Händler überprüfen.",
	"DPFErrorShrt" : "DPF-Fehler",
	"DRSSSysErrorLong" : "Im DRSS-System ist ein Fehler aufgetreten.\nLassen Sie Ihr Fahrzeug  bei einem Mazda-Händler überprüfen.\n",
	"DRSSSysErrorShrt" : "DRSS-Fehlfunktion",
	"DefEmpty" : "DEF leer",
	"DefLow" : "DEF niedrig",
	"DefVeryLow" : "DEF sehr niedrig",
	"DriveBattDropLong" : "Die verbleibende Ladung der Hochvoltbatterie ist gering, weil das Getriebe lange in der Neutral Position verblieben ist. \nIn der Position Neutral ist ein Aufladen nicht möglich. Stellen Sie bei langen Stillstandszeiten auf die Position Parken. \nStarten Sie das Hybridsystem ggf. durch Drücken des Netzschalters neu.",
	"DriveBattDropShrt" : "Hochspannungsbatterie fast leer",
	"DropKeyBattChrgLong" : "Schlüsselbatterie schwach. Ersetzen Sie sofort die Schlüsselbatterie.",
	"DropKeyBattChrgShrt" : "Schlüsselbatterie schwach",
	"DscSysErrorLong" : "Fehlfunktion der Dynamic Stability Control (DSC), des Traction Control System (TCS) oder des Hill Launch Assist (HLA). Lassen Sie Ihr Fahrzeug sofort bei einem Händler überprüfen.",
	"DscSysErrorShrt" : "DSC-Fehlfunktion",
	"DscSystemErrorLong" : "Fehlfunktion der dynamischen Stabilitätskontrolle (DSC) oder des Traktionskontrollsystems (TCS). \nLassen Sie Ihr Fahrzeug sofort bei einem Händler überprüfen.",
	"DscSystemErrorShrt" : "DSC-Fehlfunktion",
	"EcbSysErrorLong" : "Fehlfunktion bei der Bremsrückgewinnung oder des elektronisch gesteuerten Bremssystems. Das Fahrzeug sofort an einer sicheren Stelle anhalten und von einem Händler überprüfen lassen.",
	"EcbSysErrorShrt" : "Bremsen-Systemfehlfunktion",
	"ElectricParkingBrakeHighLong" : "Eine Fehlfunkion ist bei der Parkbremse aufgetreten. Zur Inspektion konsultieren Sie Ihren Mazda-Händler.",
	"ElectricParkingBrakeLong" : "Eine Fehlfunkion ist bei der Parkbremse aufgetreten. Zur Inspektion konsultieren Sie Ihren Mazda-Händler.",
	"ElectricParkingBrakeShrt" : "Parkbremsen-Fehlfunktion",
	"ElectricVacuumPumpSystemMalfunctionLong" : "Eine Fehlfunktion ist in der  elektrischen Unterdruckpumpe der Bremse aufgetreten. Ohne Korrektur kann das System ausfallen, wodurch Gefahr oder Fehlfunktion droht. Konsultieren Sie sofort Ihren Mazda-Händler und lassen Sie diesen Fehler inspizieren.",
	"ElectricVacuumPumpSystemMalfunctionShrt" : "Bremssystem-Unterdruckpumpe - Fehlfunktion",
	"ElectronicThrottleControlLong" : "Sollte die Warnleuchte weiterhin aufleuchten, liegt eine Fehlfunktion im elektronischen Steuergerät vor.  Starten Sie den Motor Ihres Mazda neu, um das elektronische Steuergerät zurückzusetzen, oder bringen Sie das Fahrzeug zur Überprüfung bei einem Händler vorbei.  \n\nWenn die Warnleuchte blinkt, ist eine schwere Fehlfunktion aufgetreten und die Leistungsausgabe wird begrenzt.  Bringen Sie das Fahrzeug so schnell wie möglich zur Wartung bei Ihrem Händler vorbei.  Versuchen Sie, das elektronische Steuergerät zurückzusetzen, indem Sie den Motor neu starten. \n",
	"ElectronicThrottleControlShrt" : "Elektronische Motorleistungssteuerung",
	"EloopChargingLong" : "i‑ELOOP wird geladen. Überprüfen Sie bei laufendem Motor, dass der Ladevorgang abgeschlossen und die Warnanzeige aus ist. Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.",
	"EloopChargingShrt" : "i‑ELOOP-Ladevorgang",
	"EloopSysErrorLong" : "i‑ELOOP-Systemfehlfunktion \nLassen Sie Ihr Fahrzeug bei einem Mazda-Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.\n",
	"EloopSysErrorShrt" : "i‑ELOOP-Systemfehlfunktion",
	"EngCoolntTempHighOnLong" : "Motor überhitzt sich. Halten Sie das Auto sofort an einer sicheren Stelle an, stellen Sie den Motor ab und ergreifen Sie entsprechende Maßnahmen. Schauen Sie in der Bedienungsanleitung nach.",
	"EngCoolntTempHighOnShrt" : "Temperatur Motorkühlmittel hoch",
	"EngOilPressureErrorLong" : "Niedriger Motoröldruck. Halten Sie das Auto sofort an einer sicheren Stelle an, stellen Sie den Motor ab und prüfen Sie den Ölstand. Falls erforderlich, Öl hinzufügen. Lassen Sie das Fahrzeug sofort von einem Händler überprüfen, wenn diese Anzeige nach dem Hinzufügen von Öl leuchtet oder wenn der Motorölstand OK ist.",
	"EngOilPressureErrorShrt" : "Niedriger Motoröldruck",
	"EngSystemErrorLong" : "Motorsystemfehlfunktion  Lassen Sie Ihr Fahrzeug sofort bei einem Händler überprüfen.",
	"EngSystemErrorShrt" : "Motorsystemfehlfunktion",
	"EngineOilPressureErrorLong" : "Niedriger Motoröldruck. Halten Sie das Auto sofort an einer sicheren Stelle an, stellen Sie den Motor ab und prüfen Sie den Motorölstand. Falls erforderlich, Öl hinzufügen. Lassen Sie das Fahrzeug sofort von einem Händler überprüfen, wenn diese Anzeige nach dem Hinzufügen von Öl leuchtet oder wenn der Motorölstand OK ist.",
	"EngineOilPressureErrorShrt" : "Niedriger Motoröldruck",
	"EngineWaterTempDropLong" : "Motorkühlmittel ist kalt und es ist keine warme Luft für Heizung/Defroster verfügbar. Das Fahrzeug darf mit ein-oder ausgeschalteter Anzeige gefahren werden.  Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.",
	"EngineWaterTempDropShrt" : "Temperatur Motorkühlmittel niedrig",
	"EngineWaterTempRiseLong" : "Der Motor fängt an, heiß zu laufen. Fahren Sie langsam oder halten Sie das Fahrzeug an, bis die Anzeige aufhört zu blinken. Wenn die Anzeige auch nach dem Anhalten des Fahrzeugs weiter blinkt, ergreifen Sie entsprechende Maßnahmen. Schauen Sie in der Bedienungsanleitung nach.",
	"EngineWaterTempRiseShrt" : "Temperatur Motorkühlmittel hoch",
	"EngnCoolTempHighHighPrt" : "Fahrzeug-Kühlmitteltemperatur hoch. Halten Sie das Fahrzeug sofort an einer sicheren Stelle an.",
	"FOWMRCCDRSSRadarSoilingLong" : "Das FOW/MRCC/DRSS-Radar (Sensor) ist verschmutzt.\nReinigen Sie die gesamte Oberfläche des Radars (Sensors).",
	"FOWMRCCDRSSRadarSoilingShrt" : "FOW/MRCC/DRSS-Radarfehlfunktion",
	"FOWMRCCRadarSoilingLong" : "FOW/MRCC/Radar (Sensor)-Fehlfunktion. Reinigen Sie die gesamte Oberfläche des vorderen Kühlergrill-Emblems, falls dieses verschmutzt oder mit Schnee bedeckt ist. Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn diese Anzeige weiterhin leuchtet.",
	"FOWMRCCRadarSoilingShrt" : "FOW/MRCC-Radar-Fehlfunktion",
	"FOWSysError" : "FOW-Fehlfunktion",
	"FOWSysErrorLong" : "Im Forward Obstruction Warning (FOW) System ist ein Fehler aufgetreten.\nLassen Sie Ihr Fahrzeug  bei einem Händler überprüfen.",
	"FWDSysErrorLong" : "Fehlfunktion des 4WD-Systems oder Größenunterschied zwischen Vorder-und Hinterreifen. \nLassen Sie Ihr Fahrzeug sofort bei einem Händler überprüfen.",
	"FWDSysErrorShrt" : "4WD-Systemfehlfunktion",
	"FuelAirFilterCartReplacePeriodLong" : "Die Kraftstofffilterpatrone muss ausgetauscht werden",
	"FuelAirFilterCartReplacePeriodShrt" : "Austausch des Kraftstofffilters erforderlich",
	"FuelCapInspectionLong" : "Der Tankdeckel ist möglicherweise nicht richtig verschlossen. \nÜberprüfen Sie, ob der Tankdeckel richtig geschlossen ist. \nNach Aufsetzen und Festziehen des Tankdeckels bleibt diese Anzeige zunächst für ein paar Fahrzyklen an bis bestätigt werden kann, dass das System in Ordnung ist.  Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.\n",
	"FuelCapInspectionShrt" : "Tankdeckel Verschlusskontrolle",
	"HBCALHUnavailableLong_1" : "Die Fernlichtsteuerung wird aufgrund übermäßiger Wärme im Innenraum vorübergehend deaktiviert. Die Fernlichtsteuerung wird wieder aktiviert, sobald sich der Innenraum hinreichend abgekühlt hat.",
	"HBCALHUnavailableLong_2" : "Die adaptiven LED-Scheinwerfer werden aufgrund übermäßiger Wärme im Innenraum vorübergehend deaktiviert. Die adaptiven LED-Scheinwerfer werden wieder aktiviert, sobald sich der Innenraum hinreichend abgekühlt hat.",
	"HBCALHUnavailableShrt_1" : "HBC nicht verfügbar",
	"HBCALHUnavailableShrt_2" : "ALH nicht verfügbar",
	"HBCLDWSSysErrorLong" : "High Beam Control (HBC)*- und/oder Lane Departure Warning System (LDWS)*-Fehlfunktion. Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn diese Anzeige weiterhin leuchtet.\n*Die Verfügbarkeit dieser Funktionen richtet sich nach dem Modell und der Ausstattungsvariante.",
	"HBCLDWSSysErrorLong_2" : "High Beam Control (HBC)-/Lane-keep Assist System (LAS)-Fehlfunktion. Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn diese Anzeige weiterhin leuchtet.",
	"HBCLDWSSysErrorLong_3" : "Adaptive LED Headlights (ALH)-/Lane Departure Warning System (LDWS)-Fehlfunktion. Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn diese Anzeige weiterhin leuchtet.",
	"HBCLDWSSysErrorLong_4" : "Adaptive LED Headlights (ALH)-/Lane-keep Assist System (LAS)-Fehlfunktion. Enteisen Sie die Windschutzscheibe. Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.",
	"HBCLDWSSysErrorShrt" : "HBC/LDWS-Systemfehlfunktion",
	"HBCLDWSSysErrorShrt_2" : "HBC/LAS Systemfehlfunktion",
	"HBCLDWSSysErrorShrt_3" : "ALH/LDWS Systemfehlfunktion",
	"HBCLDWSSysErrorShrt_4" : "ALH/LAS Systemfehlfunktion",
	"HBCLDWSWindshieldFogLong" : "High Beam Control (HBC)*- und/oder Lane Departure Warning System (LDWS)*-Fehlfunktion. Enteisen Sie die Windschutzscheibe.   Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn diese Anzeige weiterhin leuchtet.\n*Die Verfügbarkeit dieser Funktionen richtet sich nach dem Modell und der Ausstattungsvariante.",
	"HBCLDWSWindshieldFogLong_2" : "High Beam Control (HBC)-/Lane-keep Assist System (LAS)-Fehlfunktion. Enteisen Sie die Windschutzscheibe. Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn diese Anzeige weiterhin leuchtet.",
	"HBCLDWSWindshieldFogLong_3" : "Adaptive LED Headlights (ALH)-/Lane Departure Warning System (LDWS)-Fehlfunktion. Enteisen Sie die Windschutzscheibe. Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.",
	"HBCLDWSWindshieldFogLong_4" : "Adaptive LED Headlights (ALH)-/Lane-keep Assist System (LAS)-Fehlfunktion. Enteisen Sie die Windschutzscheibe. Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.",
	"HBCLDWSWindshieldFogShrt" : "HBC/LDWS-Systemfehlfunktion",
	"HBCLDWSWindshieldFogShrt_2" : "HBC/LAS Systemfehlfunktion",
	"HBCLDWSWindshieldFogShrt_3" : "ALH/LDWS Systemfehlfunktion",
	"HBCLDWSWindshieldFogShrt_4" : "ALH/LAS Systemfehlfunktion",
	"HBCLLDWSCamDisconnectLong" : "High Beam Control (HBC)*- und/oder Lane Departure Warning System (LDWS)*-Fehlfunktion. Reinigen Sie die Windschutzscheibe.  Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn diese Anzeige weiterhin leuchtet.\n*Die Verfügbarkeit dieser Funktionen richtet sich nach dem Modell und der Ausstattungsvariante.",
	"HBCLLDWSCamDisconnectLong_2" : "High Beam Control (HBC)/Lane-keep Assist System (LAS) Fehlfunktion. Reinigen Sie die  Windschutzscheibe. Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn diese Anzeige weiterhin leuchtet.",
	"HBCLLDWSCamDisconnectLong_3" : "Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS) Fehlfunktion. Reinigen Sie die  Windschutzscheibe. Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn diese Anzeige weiterhin leuchtet.",
	"HBCLLDWSCamDisconnectLong_4" : "Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS) Fehlfunktion. Reinigen Sie die  Windschutzscheibe. Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn diese Anzeige weiterhin leuchtet.",
	"HBCLLDWSCamDisconnectShrt" : "HBC/LDWS Kamerafehlfunktion",
	"HBCLLDWSCamDisconnectShrt_2" : "HBC/LAS Kamerafehlfunktion",
	"HBCLLDWSCamDisconnectShrt_3" : "ALH/LDWS Kamerafehlfunktion",
	"HBCLLDWSCamDisconnectShrt_4" : "ALH/LAS Kamerafehlfunktion",
	"HBCSysErrorLong" : "High Beam Control (HBC)-Fehlfunktion. Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen.\n",
	"HBCSysErrorLong_2" : "Adaptive LED Headlights (ALH)-Fehlfunktion. Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen.",
	"HBCSysErrorShrt" : "HBC-Fehlfunktion",
	"HBCSysErrorShrt_2" : "ALH Fehlfunktion",
	"HbcOrAlhUnavailable" : "HBC oder ALH nicht verfügbar",
	"HeadlightSystemErrorLongJ03" : "Eine Fehlfunktion ist im Scheinwerfersystem aufgetreten. Falls die Warnleuchte kontinuierlich blinkt, konsultieren Sie Ihren Mazda-Händler.",
	"HighEngineOillevel" : "Hoher Motorölstand",
	"HighEngineOillevelDetail" : "Der Motorölstand ist zu hoch. Bitte Öl wechseln.",
	"HybrdSysMalHighPrt" : "Hybridsystem-Fehlfunktion. Halten Sie das Fahrzeug sofort an einer sicheren Stelle an.",
	"HybridSysErrorLong" : "Hybridsystemfehlfunktion \nWenn Sie weiterfahren, kann das Fahrzeug beschädigt werden. Das Fahrzeug sofort an einer sicheren Stelle anhalten und von einem Händler überprüfen lassen.",
	"HybridSysErrorShrt" : "Hybridsystem-Fehlfunktion",
	"HybridSysOverheatLong" : "Hybridsystem-Fehlfunktion. Wenn Sie weiterfahren, kann das Fahrzeug Schaden nehmen. Das Fahrzeug sofort an einer sicheren Stelle anhalten und von einem Händler überprüfen lassen.",
	"HybridSysOverheatShrt" : "Hybridsystem-Überhitzung",
	"IeloopChrgHighPrt" : "i‑ELOOP-Ladevorgang. Bitte bei laufendem Motor prüfen, ob Ladevorgang abgeschlossen und Warnanzeige aus ist.",
	"IstopSysErrorLong" : "i‑stop-Betrieb ist nicht möglich.\nLassen Sie Ihr Fahrzeug  bei einem Mazda-Händler überprüfen.\n",
	"IstopSysErrorShrt" : "i‑stop-Systemfehlfunktion",
	"KeylesSysErrorLong" : "Schlüsselloser Zugang Systemfehlfunktion. Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen.",
	"KeylesSysErrorShrt" : "Fehlfunktion schlüsselloser Zugang",
	"LDWSLASUnavailableLong_1" : "Das Spurhaltewarnsystem wird aufgrund übermäßiger Wärme im Innenraum vorübergehend deaktiviert. Das Spurhaltewarnsystem wird wieder aktiviert, sobald sich der Innenraum hinreichend abgekühlt hat.",
	"LDWSLASUnavailableLong_2" : "Der Spurhalteassistent wird aufgrund übermäßiger Wärme im Innenraum vorübergehend deaktiviert. Der Spurhalteassistent wird wieder aktiviert, sobald sich der Innenraum hinreichend abgekühlt hat.",
	"LDWSLASUnavailableShrt_1" : "LDWS nicht verfügbar",
	"LDWSLASUnavailableShrt_2" : "LAS nicht verfügbar",
	"LDWSSysErrorLong" : "Lane Departure Warning System (LDWS) Fehlfunktion \nLassen Sie Ihr Fahrzeug bei einem Händler überprüfen.\n",
	"LDWSSysErrorLong_2" : "Lane-keep Assist System (LAS) Fehlfunktion. Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen",
	"LDWSSysErrorShrt" : "LDWS-Fehlfunktion",
	"LDWSSysErrorShrt_2" : "LAS Fehlfunktion",
	"LdwsOrLasUnavailable" : "LDWS oder LAS nicht verfügbar",
	"LowBrakeFluidLong" : "Der Bremsflüssigkeitsstand ist niedrig. Das Fahrzeug sofort an einer sicheren Stelle anhalten und von einem Händler überprüfen lassen.",
	"LowBrakeFluidShrt" : "Niedriger Bremsflüssigkeitsstand",
	"LowEngineOillevel" : "Niedriger Motorölstand",
	"LowEngineOillevelDetail" : "Der Motorölstand ist zu niedrig.  Füllen Sie bitte Öl nach.",
	"LowFuelLong" : "Die Kraftstoffanzeige ist niedrig. \nDas Fahrzeug bald tanken.",
	"LowFuelShrt" : "Niedriger Kraftstoffstand",
	"LowTireAirPressureFlatLong" : "Falls sich der Reifendruck extrem verringert, nachdem die TPMS-Warnleuchte aufleuchtete oder falls ein Reifen beschädigt ist, leuchtet auch die Reifenpannen-Warnleuchte  auf. Falls ein Runflat-Reifen beschädigt ist, fahren Sie das Fahrzeug vorsichtig zum nächstliegenden Mazda-Händler und lassen Sie den Reifen wechseln.",
	"LowTireAirPressureLong" : "Geringer Reifenluftdruck in einem oder mehreren Reifen. \nDen Luftdruck der Reifen prüfen und auf den richtigen Luftdruck einstellen. Drücken Sie nach dem Einstellen des Reifendrucks den TPMS SET Schalter, bis Sie einen Piepston hören.",
	"LowTireAirPressureShrt" : "Geringer Reifendruck",
	"LowWasheFluidLong" : "Der Waschflüssigkeitsstand ist gering. \nFüllen Sie die Waschflüssigkeit auf.\n",
	"LowWasheFluidShrt" : "Niedr. Scheibenrein.-Flüssigkeit",
	"MRCCSysErrorLong" : "Fehlfunktion Mazda Radar Cruise Control (MRCC). Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen.",
	"MRCCSysErrorShrt" : "MRCC-Fehlfunktion",
	"MRCCUnavailableLong" : "Mazda Radar Cruise Control (MRCC) momentan nicht verfügbar.",
	"MRCCUnavailableShrt" : "MRCC nicht verfügbar",
	"NoWarnings" : "Keine Warnmeldungen gefunden",
	"OilLevelSystemMalfunctioning" : "Defekt des Motorölstandsensors",
	"OilLevelSystemMalfunctioningDetail" : "Es liegt ein Defekt des Motorölstandssensors vor. Lassen Sie das Fahrzeug bei einem Mazda-Händler überprüfen. ",
	"PowerSteeringSysErrorLong" : "Servolenkung-Fehlfunktion. Halten Sie das Auto sofort an einer sicheren Stelle an, stellen Sie den Motor ab. Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.",
	"PowerSteeringSysErrorShrt" : "Servolenkung Systemfehler",
	"PpositionRequestLong" : "Stellen Sie den Schalthebel auf Parken. \nDies hat eine der folgenden Ursachen: \n・ Das Batteriesystem wurde mit einer anderen Schalthebel-Position als P gestartet oder gestoppt\n・ Die Fahrerseitentür wurde mit der Schalthebel-Position N, D oder B geöffnet.\n ・ Die verbleibende Ladung der Hochspannungsbatterie ist abgefallen, weil die Schalthebel-Position lange Zeit auf Neutral stand.\nStarten Sie das Hybridsystem ggf. durch Drücken des Netzschalters neu.",
	"PpositionRequestShrt" : "Parkpositionsanfrage",
	"PreheatingDispLampLong" : "Glühkerzen glühen vor. Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.",
	"PreheatingDispLampShrt" : "Glühkerzen glühen vor",
	"RoadSurfaceIcingCautionLong" : "Die Außentemperatur beträgt 4° C oder weniger. Achten Sie beim Fahren auf vereiste Straßen.",
	"RoadSurfaceIcingCautionShrt" : "Vorsicht: Vereisung d. Straßenbel.",
	"RvmSysErrorLong" : "Im RVM-System ist ein Fehler aufgetreten.\nÜberprüfen Sie die Oberfläche der hinteren Stoßstange auf Auffälligkeiten und reinigen Sie sie bei Verschmutzung oder falls sie mit Schnee bedeckt ist. Lassen Sie Ihr Fahrzeug von einem Mazda-Händler überprüfen, wenn dieses Warnlicht nicht ausgeht.",
	"RvmSysErrorShrt" : "RVM-Fehlfunktion",
	"SBSBrakeMRCCUnavailableLong" : "SBS-Bremsen/MRCC momentan nicht verfügbar.",
	"SBSBrakeMRCCUnavailableShrt" : "SBS/MRCC nicht verfügbar",
	"SBSBrakeUnavailableLong" : "SBS-Bremsen momentan nicht verfügbar.",
	"SBSBrakeUnavailableShrt" : "SBS Bremse nicht verfügbar",
	"SBSMRCCDRSSRadarSoilingLong" : "Das SBS/MRCC/DRSS-Radar (Sensor) ist verschmutzt. Reinigen Sie die gesamte Oberfläche des Radars (Sensors).",
	"SBSMRCCDRSSRadarSoilingShrt" : "SBS/MRCC/DRSS-Radarfehler",
	"SBSMRCCRadarSoilingLong" : "Das SBS/MRCC Radar (Sensor) ist verschmutzt.\nReinigen Sie die gesamte Oberfläche des Radars (Sensors).",
	"SBSMRCCRadarSoilingShrt" : "SBS/MRCC-Radar-Fehlfunktion",
	"SBSSysErrorLong" : "Im SBS-System ist ein Fehler aufgetreten.\nLassen Sie Ihr Fahrzeug  bei einem Mazda-Händler überprüfen.\n",
	"SBSSysErrorShrt" : "SBS-Fehlfunktion",
	"SCBSSysErrorLong" : "Smart City Brake Support (SCBS) Fehlfunktion. \nLassen Sie Ihr Fahrzeug bei einem Händler überprüfen.",
	"SCBSSysErrorLong_105" : "Smart City Brake Support (SCBS) Fehlfunktion. Enteisen Sie die Windschutzscheibe. Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.",
	"SCBSSysErrorShort_105" : "SCBS-Fehlfunktion",
	"SCBSSysErrorShrt" : "SCBS-Fehlfunktion",
	"SCBSUnavailableLong" : "Smart City Brake Support (SCBS) momentan nicht verfügbar.",
	"SCBSUnavailableLong1" : "Das Smart City-Bremssystem wird aufgrund übermäßiger Wärme im Innenraum vorübergehend deaktiviert. Das Smart City-Bremssystem wird wieder aktiviert, sobald sich der Innenraum hinreichend abgekühlt hat.",
	"SCBSUnavailableShrt" : "SCBS nicht verfügbar",
	"SCBSUnavailableShrt1" : "SCBS nicht verfügbar",
	"SCBSWindshieldSoilingLong" : "Smart City Brake Support (SCBS) Fehlfunktion. \nReinigen Sie die  Windschutzscheibe.  Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.",
	"SCBSWindshieldSoilingShrt" : "SCBS-Fehlfunktion",
	"SCRMalfunction100Long" : "Diesel-Emissionen-SCR-Fehlfunktion.\nWenn dieses Problem nicht behoben wird, wird die Fahrzeuggeschwindigkeit begrenzt.",
	"SCRMalfunction101Long" : "Diesel-Emissionen-SCR-Fehlfunktion.\nWenn dieses Problem nicht behoben wird, wird der Motor in den Leerlaufmodus geschaltet.",
	"SCRMalfunction102Long" : "Diesel-Emissionen-SCR-Fehlfunktion. Der Motor befindet sich nun im Leerlaufmodus.\nWenden Sie sich für Hilfe an Ihren Mazda-Händler.",
	"ScrMalfunction" : "SCR-Fehlfunktion",
	"SedimenterWarningLong" : "Die Menge des im Sedimenter angesammelten Wassers übersteigt den kalkulierten Wert. Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.",
	"SedimenterWarningShrt" : "Sediment. Inspektion",
	"SystemInspectionLong" : "Die Differentialöl-Temperatur ist ungewöhnlich hoch oder ein großer Rotations-Unterschied ist in den Vorder- und Hinterreifen aufgetreten (z. B. beim Versuch aus Schlamm herauszufahren). \nDas Fahrzeug an einer sicheren Stelle anhalten und erst weiterfahren, nachdem die Warnanzeige ausgegangen ist. Lassen Sie Ihr Fahrzeug von einem Händler überprüfen, wenn dieses Anzeige weiterhin leuchtet.",
	"SystemInspectionShrt" : "4WD-System Inspektion",
	"TpmsSysErrorLong" : "Fehlfunktion des Tire Pressure Monitoring Systems (TPMS). Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen.",
	"TpmsSysErrorShrt" : "Fehlfunktion TPMS-System",
	"VehicleSysErrorLong" : "Fahrzeug Systemfehlfunktion. Lassen Sie Ihr Fahrzeug bei einem Händler überprüfen.",
	"VehicleSysErrorShrt" : "Fahrzeug Systemfehlfunktion",
	"WarningGuidance" : "Warnmeldung",
	"WarningSafetyMessage" : "Aus Sicherheitsgründen wird die Warnmeldung nicht agezeigt",
	"Warnings" : "Warnmeldungen",
	"brakeFluid" : "Bremsflüssigkeitsstand niedrig",
	"engineOilPressure" : "Motoröldruck",
	"highVoltage" : "Hochspannungsbatterie schwach",
	"lowBattStartEngine" : "Batterie fast leer! Motor anlassen!",
};

framework.registerAppDictLoaded("warnguide", "de_DE");