var Localization_warnguideAppDict_fi_FI = {
	//"stringId" : "localString"
	"AbsSysErrorLong" : "Lukkiutumattomien jarrujen (ABS) toimintahäiriö. \nTarkistuta auto välittömästi myyjäliikkeessä.",
	"AbsSysErrorShrt" : "ABS-jarrujen toimintahäiriö",
	"AbsSystemErrorLong" : "Lukkiutumattomien jarrujen (ABS) toimintahäiriö. \nTarkistuta auto välittömästi myyjäliikkeessä.",
	"AbsSystemErrorShrt" : "ABS-jarrujen toimintahäiriö",
	"AccumulationDpfLong" : "Diesel-järjestelmän hiukkassuodattimeen (DPF) kerääntynyt hiukkasmassa ylittää sallitun arvon. Aja noin 10–15 minuuttia vähintään 15 km/h:n (10 mph) nopeudella niin, että moottori on lämmennyt kokonaan (sininen lämpötilavalo on sammunut), jotta hiukkasmassa poistuu suodattimesta. Tarkistuta auto myyjäliikkeessä, jos merkkivalo ei sammu.",
	"AccumulationDpfShrt" : "Hiukkaskeräänt. DPF-suotimessa",
	"ActiveBonnetSystemMalfunctionLong" : "Active Bonnet järjestelmän toimintahäiriö. Tarkistuta ajoneuvo jälleenmyyjällä, jos tämä merkkivalo pysyy päällä tai jatkaa vilkkumista.",
	"ActiveBonnetSystemMalfunctionShrt" : "Active Bonnet järjestelmän toimintahäiriö",
	"AfsSystemErrorLong" : "Mukautuvien etuvalojen (AFS) toimintahäiriö. Tarkistuta auto myyjäliikkeessä, jos merkkivalo ei lakkaa vilkkumasta.",
	"AfsSystemErrorShrt" : "AFS-valojen toimintahäiriö",
	"AfterRunCoolingPumpLong" : "Ota yhteyttä tai käy huoltoliikkeessä jos Mazda ylikuumenee. ",
	"AfterRunCoolingPumpShrt" : "Ajonjälkeinen jäähdytinpumppu",
	"AirbagSysPretensionerSysErrorLong" : "Turvatyynyn/turvavyön toimintahäiriö.",
	"AirbagSysPretensionerSysErrorShrt" : "Turvatyynyn/vyönkiristimen häiriö",
	"AutoLevelSystemErrorLong" : "Ajovalojen korkeudensäädön toimintahäiriö.\nTarkistuta auto myyjäliikkeessä, jos merkkivalo ei sammu.",
	"AutoLevelSystemErrorShrt" : "Autom. tasonsäädön häiriö",
	"AutoLevelSystemErrorShrtJ03" : "Ajovalojärjestelmän vika",
	"AutoTransSysErrorLong" : "Automaattivaihteiston toimintahäiriö. Auto saattaa rikkoutua, jos jatkat ajamista. Tarkistuta auto välittömästi myyjäliikkeessä.  ",
	"AutoTransSysErrorShrt" : "Automaattivaihteiston häiriö",
	"AuxBattLowLong" : "12 V akun varaus on vähissä.\n・Jos tämä merkkivalo palaa useasti ajon aikana, akun kunto on voinut heikentyä. Tarkistuta auto myyjäliikkeessä.\n・Jos tämä merkkivalo palaa jatkuvasti ajon aikana, 12 V akku on täysin tyhjä / ei toimi. Katso lisätietoja Omistajan käsikirjasta ennen hybridijärjestelmän käynnistämistä ja tarkistuta auto myyjäliikkeessä.",
	"AuxBattLowShrt" : "12 V akku lähes tyhjä",
	"BattManagSysErrorLong" : "Akunhallintajärjestelmän toimintahäiriö. \nTarkistuta auto myyjäliikkeessä.",
	"BattManagSysErrorShrt" : "Akunhallintajärjestelmän häiriö",
	"BrakOverrideSysErrorLong" : "Jarrukytkimen toimintahäiriö. Tarkistuta auto välittömästi myyjäliikkeessä.",
	"BrakOverrideSysErrorShrt" : "Jarrujen ohitusjärjestelmän häiriö",
	"BrakeSysErrorLong" : "Jarruneste vähissä tai jarrujärjestelmässä toimintahäiriö. Pysäytä auto välittömästi turvalliseen paikkaan ja tarkistuta auto myyjäliikkeessä.",
	"BrakeSysErrorShrt" : "Jarrujärjestelmän toimintahäiriö",
	"BrakeSystemErrorLong" : "Sähköisen jarrujärjestelmän toimintahäiriö. Pysäytä auto välittömästi turvalliseen paikkaan ja tarkistuta auto myyjäliikkeessä.",
	"BrakeSystemErrorShrt" : "Jarrujärjestelmän toimintahäiriö",
	"BsmSystemErrorLong" : "Blind Spot Monitoring (BSM)/ Rear Cross Traffic Alert (RCTA) toimintahäiriö. Tarkista, ettei takapuskurin pinnassa näy mitään epätavallista ja puhdista puskuri, jos se on lian tai lumen peitossa. Tarkistuta auto myyjäliikkeessä, jos merkkivalo ei sammu.",
	"BsmSystemErrorShrt" : "BSM-järjestelmän toimintahäiriö",
	"ChargSysMalHighPrt" : "Latausjärjestelmän toimintahäiriö. Pysäytä auto välittömästi turvalliseen paikkaan.",
	"ChargingSysErrorLong" : "Latausjärjestelmän toimintahäiriö. Auto saattaa rikkoutua, jos jatkat ajamista. Pysäytä auto välittömästi turvalliseen paikkaan ja tarkistuta auto myyjäliikkeessä.",
	"ChargingSysErrorShrt" : "Latausjärjestelmän toimintahäiriö",
	"ChrgSysErrorLong" : "Latausjärjestelmän toimintahäiriö. Pysäytä auto välittömästi turvalliseen paikkaan ja tarkistuta auto myyjäliikkeessä.",
	"ChrgSysErrorShrt" : "Latausjärjestelmän toimintahäiriö",
	"ColdStartDisableLong" : "Kun ympäröivä lämpötila on erittäin alhainen, moottorin käynnistäminen on estetty moottorivaurion välttämiseksi. Katso lisätietoja Omistajan oppaasta. Lohkolämmittimen käyttö nopeuttaa Mazdan käynnistämistä.",
	"ColdStartDisableShrt" : "Kylmäkäynnistys poistettu käytöstä",
	"ControlSystemErrorLong" : "Pysäköintiasennon valvontajärjestelmän toimintahäiriö.\nJos tätä ei valita, seurauksena voi olla jokin seuraavista tilanteista:\n・Pysäköintijarrun mekanismi ei toimi välttämättä. Pysäköi tasaiseen paikkaan ja kytke pysäköintijarru huolellisesti.\n・Virtakytkin ei mene Off-asentoon. Sammuta virta painamalla virtakytkintä toistuvasti.\n・ \"Kytke pysäköintijarru pysäköitäessä\" -näyttö sammuu ajettaessa ja syttyy pysähdyttäessä.\nTarkistuta auto välittömästi myyjäliikkeessä.",
	"ControlSystemErrorShrt" : "P-asennon valvontajärj. häiriö",
	"DPFErrorLong" : "Dieselin hiukkassuodattimen (DPF) toimintahäiriö. \nTarkistuta auto myyjäliikkeessä.",
	"DPFErrorShrt" : "Hiukkassuodattimen häiriö",
	"DRSSSysErrorLong" : "DRSS-järjestelmässä on virhe.\nTarkistuta auto Mazda-liikkeessä.\n",
	"DRSSSysErrorShrt" : "DRSS-järjestelmän toimintahäiriö",
	"DefEmpty" : "DEF on tyhjä.",
	"DefLow" : "DEF-taso on matala.",
	"DefVeryLow" : "DEF-taso on erittäin matala.",
	"DriveBattDropLong" : "Korkeajänniteakun varaus on alhainen, koska vaihde oli pitkään vapaalla (Neutral-asennossa). Lataus ei toimi, kun vaihde on vapaalla (Neutral). Aseta vaihde P-asentoon, kun olet pysähdyksissä pitkään. Käynnistä hybridijärjestelmä tarvittaessa uudelleen virtapainikkeesta.",
	"DriveBattDropShrt" : "Korkeajänniteakku lähes tyhjä",
	"DropKeyBattChrgLong" : "Avaimen pariston varaus on vähissä.\nVaihda avaimen paristo välittömästi.\n",
	"DropKeyBattChrgShrt" : "Avaimen pariston virta vähissä",
	"DscSysErrorLong" : "Dynamic Stability Control (DSC), Traction Control System (TCS) tai Hill Launch Assist (HLA) toimintahäiriö. Tarkistuta auto välittömästi myyjäliikkeessä.",
	"DscSysErrorShrt" : "DSC-järjestelmän toimintahäiriö",
	"DscSystemErrorLong" : "Ajonvakautusjärjestelmän (DSC) tai luistonestojärjestelmän (TCS) toimintahäiriö. Tarkistuta auto välittömästi huoltoliikkeessä.",
	"DscSystemErrorShrt" : "DSC-järjestelmän toimintahäiriö",
	"EcbSysErrorLong" : "Jarrutehon talteenoton tai sähköisesti ohjatun jarrujärjestelmän toimintahäiriö. Pysäytä auto välittömästi turvalliseen paikkaan ja tarkistuta auto myyjäliikkeessä.",
	"EcbSysErrorShrt" : "Jarrujärjestelmän toimintahäiriö",
	"ElectricParkingBrakeHighLong" : "Seisontajarrujärjestelmässä ilmeni häiriö. Käänny Mazda-jälleenmyyjän puoleen tarkastusta varten.",
	"ElectricParkingBrakeLong" : "Seisontajarrujärjestelmässä ilmeni häiriö. Käänny Mazda-jälleenmyyjän puoleen tarkastusta varten.",
	"ElectricParkingBrakeShrt" : "Seisontajarrujärjestelmän häiriö",
	"ElectricVacuumPumpSystemMalfunctionLong" : "Sähköpumppujärjestelmässä ilmeni vika. Vian huomioimatta jättäminen voi johtaa järjestelmän virheeseen, joka voi aiheuttaa odottamattoman vaaratilanteen tai vian. Ota välittömästi yhteys Mazda-jälleenmyyjään vian tarkastamiseksi.",
	"ElectricVacuumPumpSystemMalfunctionShrt" : "Sähköpumppujärjestelmän vika",
	"ElectronicThrottleControlLong" : "Jos varoitusvalo ei sammu, sähköisessä hallintajärjestelmässä on vika.  Uudelleenkäynnistä Mazdain moottori tyhjentääksesi sähköisen hallintajärjestelmän, tai vie se huoltoliikkeeseen.  \n\nJos varoitusvalo vilkkuu, vika on vakava, ja kaasua rajoitetaan.  Vie ajoneuvosi huoltoon mahdollisimman pian.  Yritä tyhjentää sähköinen hallintajärjestelmä uudelleenkäynnistämällä moottori. \n",
	"ElectronicThrottleControlShrt" : "Sähköinen kaasunhallinta",
	"EloopChargingLong" : "i‑ELOOP latautuu. Kun moottori on käynnissä, tarkista että lataus on suoritettu loppuun ja että varoitusvalo on sammunut. Tarkistuta auto myyjäliikkeessä, jos merkkivalo ei sammu.",
	"EloopChargingShrt" : "i‑ELOOP latautuu",
	"EloopSysErrorLong" : "i‑ELOOP-järjestelmän toimintahäiriö. Tarkistuta auto myyjäliikkeessä, jos merkkivalo ei sammu.",
	"EloopSysErrorShrt" : "i‑ELOOP-järjestelmän toim.häiriö",
	"EngCoolntTempHighOnLong" : "Moottori ylikuumenee.\nPysäytä ajoneuvo välittömästi turvalliseen paikkaan, sammuta moottori ja ryhdy tarvittaviin toimenpiteisiin.  Katso lisätietoja omistajan käsikirjasta.\n",
	"EngCoolntTempHighOnShrt" : "Jäähd.nesteen korkea lämpötila",
	"EngOilPressureErrorLong" : "Alhainen moottorin öljynpaine.\nPysäytä auto välittömästi turvalliseen paikkaan, sammuta moottori ja tarkista moottoriöljyn määrä. Lisää öljyä tarvittaessa.\nTarkistuta auto välittömästi myyjäliikkeessä jos tämä merkkivalo syttyy öljyn lisäämisen jälkeen tai jos moottorissa on riittävästi öljyä.\n",
	"EngOilPressureErrorShrt" : "Alhainen moottorin öljynpaine",
	"EngSystemErrorLong" : "Moottorijärjestelmän toimintahäiriö. Tarkistuta auto välittömästi myyjäliikkeessä.",
	"EngSystemErrorShrt" : "Moottorijärjestelmän häiriö",
	"EngineOilPressureErrorLong" : "Alhainen moottorin öljynpaine.\nPysäytä auto välittömästi turvalliseen paikkaan, sammuta moottori ja tarkista moottoriöljyn määrä. Lisää öljyä tarvittaessa.\nTarkistuta auto välittömästi myyjäliikkeessä, jos tämä merkkivalo syttyy öljyn lisäämisen jälkeen tai jos moottorissa on riittävästi öljyä.\n",
	"EngineOilPressureErrorShrt" : "Alhainen moottorin öljynpaine",
	"EngineWaterTempDropLong" : "Jäähdytysneste on kylmää eikä lämmityslaite/lasinlämmitin saa mistään lämmintä ilmaa. Autoa voi ajaa vaikka tämä merkkivalo palaa. Tarkistuta auto merkin omassa liikkeessä jos merkkivalo ei sammu.",
	"EngineWaterTempDropShrt" : "Jäähd.nesteen alhainen lämpötila",
	"EngineWaterTempRiseLong" : "Moottori alkaa kuumentua.\nAja hitaasti tai pysäytä auto ja odota, että merkkivalo lakkaa vilkkumasta. Jos merkkivalo ei lakkaa vilkkumasta auton pysäyttämisen jälkeen, ryhdy tarvittaviin toimenpiteisiin. Katso lisätietoja omistajan käsikirjasta.\n",
	"EngineWaterTempRiseShrt" : "Jäähd.nesteen korkea lämpötila",
	"EngnCoolTempHighHighPrt" : "Jäähdytysnesteen korkea lämpötila. Pysäytä auto välittömästi turvalliseen paikkaan.",
	"FOWMRCCDRSSRadarSoilingLong" : "FOW/MRCC/DRSS-tutka (anturi) on likaantunut.\nPuhdista tutkan (anturin) koko pinta.\n",
	"FOWMRCCDRSSRadarSoilingShrt" : "FOW/MRCC/DRSS-tutkan häiriö",
	"FOWMRCCRadarSoilingLong" : "FOW/MRCC-tutkan (anturin) toimintahäiriö. Puhdista etupuskuri kauttaaltaan, jos se on lian tai lumen peitossa. Tarkistuta auto myyjäliikkeessä, jos merkkivalo ei sammu.",
	"FOWMRCCRadarSoilingShrt" : "FOW/MRCC-tutkan toimintahäiriö",
	"FOWSysError" : "FOW-järjestelmän toimintahäiriö",
	"FOWSysErrorLong" : "Forward Obstruction Warning (FOW) toimintahäiriö. Tarkistuta auto myyjäliikkeessä.",
	"FWDSysErrorLong" : "Nelivetojärjestelmän toimintahäiriö tai edessä ja takana on erikokoiset renkaat. Tarkistuta auto myyjäliikkeessä.",
	"FWDSysErrorShrt" : "Nelivetojärjestelmän häiriö",
	"FuelAirFilterCartReplacePeriodLong" : "Polttoaineensuodattimen hylsy pitää vaihtaa.",
	"FuelAirFilterCartReplacePeriodShrt" : "Polttoaineensuodattimen hylsy täytyy vaihtaa",
	"FuelCapInspectionLong" : "Polttoainesäiliön korkki ei ole välttämättä kunnolla paikoillaan.\nTarkista, että polttoainesäiliön korkki on paikoillaan ja riittävän tiukasti kiinni. Kun polttoainesäiliön korkki on asetettu paikoilleen ja kiristetty huolellisesti, merkkivalo sammuu vasta muutaman ajokerran jälkeen, kun kaikki on varmasti kunnossa. Tarkistuta auto merkin omassa liikkeessä jos merkkivalo ei sammu.",
	"FuelCapInspectionShrt" : "Polttoainekorkin tarkistus",
	"HBCALHUnavailableLong_1" : "Kaukovalojen hallinta on väliaikaisesti poistettu käytöstä, koska auton sisälämpötila on liian korkea. Kaukovalojen hallinta otetaan takaisin käyttöön, kun auton sisälämpötila laskee riittävästi.",
	"HBCALHUnavailableLong_2" : "Mukautuvat LED-ajovalot on väliaikaisesti poistettu käytöstä, koska auton sisälämpötila on liian korkea. Mukautuvat LED-ajovalot otetaan takaisin käyttöön, kun auton sisälämpötila laskee riittävästi.",
	"HBCALHUnavailableShrt_1" : "HBC ei ole käytössä",
	"HBCALHUnavailableShrt_2" : "ALH ei ole käytössä",
	"HBCLDWSSysErrorLong" : "High Beam Control (HBC)* ja/tai Lane Departure Warning System (LDWS)* -toimintahäiriö. Vie ajoneuvo tarkistettavaksi merkkiliikkeeseen, jos valo palaa edelleen.\n*Nämä ominaisuudet riippuvat ajoneuvon mallista ja varustetasosta.",
	"HBCLDWSSysErrorLong_2" : "High Beam Control (HBC)/Lane-keep Assist System (LAS) Toimintahäiriö. Tarkastuta ajoneuvo myyntiliikkeessä jos tämä indikaattori pysyy päällä.",
	"HBCLDWSSysErrorLong_3" : "Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS) Toimintahäiriö. Tarkistuta ajoneuvo jälleenmyyjällä jos tämä indikaattori pysyy päällä.",
	"HBCLDWSSysErrorLong_4" : "Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS) toimintahäiriö. Tarkistuta ajoneuvo jälleenmyyjällä jos tämä indikaattori pysyy päällä.",
	"HBCLDWSSysErrorShrt" : "HBC/LDWS-järjestelmän toimintahäiriö",
	"HBCLDWSSysErrorShrt_2" : "HBC/LAS järjestelmän toimintahäiriö",
	"HBCLDWSSysErrorShrt_3" : "ALH/LDWS järjestelmän toimintahäiriö",
	"HBCLDWSSysErrorShrt_4" : "ALH/LAS järjestelmän toimintahäiriö",
	"HBCLDWSWindshieldFogLong" : "High Beam Control (HBC)* ja/tai Lane Departure Warning System (LDWS)* -toimintahäiriö. Poista huurre tuulilasista.  Vie ajoneuvo tarkistettavaksi merkkiliikkeeseen, jos valo palaa edelleen.\n*Nämä ominaisuudet riippuvat ajoneuvon mallista ja varustetasosta.",
	"HBCLDWSWindshieldFogLong_2" : "High Beam Control (HBC)/Lane-keep Assist System (LAS) Toimintahäiriö. Poista jää tuulilasista. Tarkistuta ajoneuvo jälleenmyyjällä jos tämä indikaattori pysyy päällä.",
	"HBCLDWSWindshieldFogLong_3" : "Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS) toimintahäiriö. Poista jää tuulilasista. Ota yhteys myyjään tarkistusta varten jos tämä indikaattori pysyy päällä.",
	"HBCLDWSWindshieldFogLong_4" : "Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS) toimintahäiriö. Poista jää tuulilasista.  Anna myyjän tarkistaa ajoneuvo jos indikaattori pysyy päällä.",
	"HBCLDWSWindshieldFogShrt" : "HBC/LDWS-järjestelmän toimintahäiriö",
	"HBCLDWSWindshieldFogShrt_2" : "HBC/LAS järjestelmän toimintahäiriö",
	"HBCLDWSWindshieldFogShrt_3" : "ALH/LDWS järjestelmän toimintahäiriö",
	"HBCLDWSWindshieldFogShrt_4" : "ALH/LAS järjestelmän toimintahäiriö",
	"HBCLLDWSCamDisconnectLong" : "High Beam Control (HBC)* ja/tai Lane Departure Warning System (LDWS)* -toimintahäiriö. Puhdista tuulilasi.  Vie ajoneuvo tarkistettavaksi merkkiliikkeeseen, jos valo palaa edelleen.\n*Nämä ominaisuudet riippuvat ajoneuvon mallista ja varustetasosta.",
	"HBCLLDWSCamDisconnectLong_2" : "High Beam Control (HBC)/Lane-keep Assist System (LAS) Toimintahäiriö. Puhdista tuulilasi. Tarkastuta ajoneuvo myyjällä jos tämä indikaattori pysyy päällä.",
	"HBCLLDWSCamDisconnectLong_3" : "Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS) Toimintahäiriö. Puhdista tuulilasi. Tarkistuta ajoneuvo jälleenmyyjällä jos tämä indikaattori pysyy päällä.",
	"HBCLLDWSCamDisconnectLong_4" : "Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS) Toimintahäiriö. Puhdista tuulilasi.  Tarkistuta ajoneuvo jälleenmyyjällä jos tämä indikaattori pysyy päällä.",
	"HBCLLDWSCamDisconnectShrt" : "HBC/LDWS kameran toimintahäiriö",
	"HBCLLDWSCamDisconnectShrt_2" : "HBC/LAS Kameran Toimintahäiriö",
	"HBCLLDWSCamDisconnectShrt_3" : "ALH/LDWS Kameran Toimintahäiriö",
	"HBCLLDWSCamDisconnectShrt_4" : "ALH/LAS kameran toimintahäiriö",
	"HBCSysErrorLong" : "High Beam Control (HBC) toimintahäiriö. Tarkistuta auto myyjäliikkeessä.\n",
	"HBCSysErrorLong_2" : "Adaptive LED Headlights (ALH) Toimintahäiriö. Tarkastuta auto myyjäliikkeessä.",
	"HBCSysErrorShrt" : "Kaukovalojärj. (HBC) häiriö",
	"HBCSysErrorShrt_2" : "ALH Toimintahäiriö",
	"HbcOrAlhUnavailable" : "HBC tai ALH ei ole käytössä",
	"HeadlightSystemErrorLongJ03" : "Ajovalojärjestelmässä ilmeni vika. Jos varoitusvalo vilkkuu jatkuvasti, ota yhteys Mazda-jälleenmyyjään.",
	"HighEngineOillevel" : "Moottoriöljyn taso on korkea",
	"HighEngineOillevelDetail" : "Moottoriöljyn taso on liian korkea. Vaihda öljy.",
	"HybrdSysMalHighPrt" : "Hybridijärjestelmän toimintahäiriö. Pysäytä auto välittömästi turvalliseen paikkaan.",
	"HybridSysErrorLong" : "Hybridijärjestelmän toimintahäiriö. Auto saattaa rikkoutua, jos jatkat ajamista. Pysäytä auto välittömästi turvalliseen paikkaan ja tarkistuta auto myyjäliikkeessä.",
	"HybridSysErrorShrt" : "Hybridijärjestelmän toimintahäiriö",
	"HybridSysOverheatLong" : "Hybridijärjestelmän toimintahäiriö. Auto saattaa rikkoutua, jos jatkat ajamista. Pysäytä auto välittömästi turvalliseen paikkaan ja tarkistuta auto myyjäliikkeessä.",
	"HybridSysOverheatShrt" : "Hybridijärjestelmä ylikuumenee",
	"IeloopChrgHighPrt" : "i‑ELOOP latautuu. Kun moottori on käynnissä, tarkista että lataus on valmis ja varoitusvalo sammunut.",
	"IstopSysErrorLong" : "i‑stop ei voi käyttää.\nTarkistuta auto Mazda-liikkeessä.\n",
	"IstopSysErrorShrt" : "i‑stop-järjestelmän toimintahäiriö",
	"KeylesSysErrorLong" : "Avaimeton käyttö -järjestelmän toimintahäiriö. Tarkistuta auto myyjäliikkeessä.",
	"KeylesSysErrorShrt" : "Avaimettoman käytön häiriö",
	"LDWSLASUnavailableLong_1" : "Kaistanvaihtovaroitin on väliaikaisesti poistettu käytöstä, koska auton sisälämpötila on liian korkea. Kaistanvaihtovaroitin otetaan takaisin käyttöön, kun auton sisälämpötila laskee riittävästi.",
	"LDWSLASUnavailableLong_2" : "Kaistanpitoavustin on väliaikaisesti poistettu käytöstä, koska auton sisälämpötila on liian korkea. Kaistanpitoavustin otetaan takaisin käyttöön, kun auton sisätlämpötila laskee riittävästi.",
	"LDWSLASUnavailableShrt_1" : "LDWS ei ole käytössä",
	"LDWSLASUnavailableShrt_2" : "LAS ei ole käytössä",
	"LDWSSysErrorLong" : "Lane Departure Warning System (LDWS) toimintahäiriö.\nTarkistuta auto myyjäliikkeessä.\n",
	"LDWSSysErrorLong_2" : "Lane-keep Assist System (LAS) Toimintahäiriö. Tarkastuta auto myyjäliikkeessä.",
	"LDWSSysErrorShrt" : "LDWS toimintahäiriö",
	"LDWSSysErrorShrt_2" : "LAS Toimintahäiriö",
	"LdwsOrLasUnavailable" : "LDWS tai LAS ei ole käytössä",
	"LowBrakeFluidLong" : "Jarruneste on vähissä. Pysäytä auto välittömästi turvalliseen paikkaan ja tarkistuta auto myyjäliikkeessä.",
	"LowBrakeFluidShrt" : "Alhainen jarrunesteen määrä",
	"LowEngineOillevel" : "Moottoriöljyn taso on alhainen",
	"LowEngineOillevelDetail" : "Moottoriöljyn taso on liian alhainen.  Lisää öljyä.",
	"LowFuelLong" : "Polttoaine on vähissä.\nTankkaa auto pian.\n",
	"LowFuelShrt" : "Polttoaine vähissä",
	"LowTireAirPressureFlatLong" : "Jos renkaan ilmanpaine laskee rajusti TPMS-varoitusvalon sytyttyä. Mikäli rengas on puhjennut, myös rengasrikon varoitusvalo syttyy. Jos puhkeamaton rengas on puhjennut, aja auto varovasti lähimpään Mazda-liikkeeseen ja vaihdata rengas.",
	"LowTireAirPressureLong" : "Alhainen rengaspaine vähintään yhdessä renkaassa.\nTarkista renkaiden ilmanpaineet ja säädä tarvittaessa oikeaan arvoon.  Kun renkaiden ilmanpaineet on säädetty, paina TPMS SET -kytkintä niin kauan että kuulet äänimerkin.",
	"LowTireAirPressureShrt" : "Matala renkaan ilmanpaine",
	"LowWasheFluidLong" : "Lasinpesuneste on vähissä. Lisää lasinpesunestettä.",
	"LowWasheFluidShrt" : "Lasinpesuneste vähissä",
	"MRCCSysErrorLong" : "Mazda Radar Cruise Control (MRCC) toimintahäiriö.\nTarkistuta auto Mazda-liikkeessä.",
	"MRCCSysErrorShrt" : "MRCC-järjestelmän toimintahäiriö",
	"MRCCUnavailableLong" : "MRCC-vakionopeussäädin ei ole tällä hetkellä käytettävissä.",
	"MRCCUnavailableShrt" : "MRCC-järj. ei ole käytettävissä",
	"NoWarnings" : "Ei varoituksia",
	"OilLevelSystemMalfunctioning" : "Moottoriöljyn tason anturin toimintahäiriö",
	"OilLevelSystemMalfunctioningDetail" : "Moottoriöljyn mitta-anturissa on toimintahäiriö. Tarkistuta ajoneuvo Mazda-jälleenmyyjällä. ",
	"PowerSteeringSysErrorLong" : "Sähköisen ohjaustehostimen toimintahäiriö. Pysäytä auto turvalliseen paikkaan ja sammuta moottori. Tarkistuta auto myyjäliikkeessä, jos merkkivalo ei sammu.",
	"PowerSteeringSysErrorShrt" : "Ohjaustehostimen toimintahäiriö",
	"PpositionRequestLong" : "Vaihda P- eli pysäköintivaihteelle.\nSyynä on jokin seuraavista:\n・ Akkujärjestelmä käynnistettiin tai sammutettiin, kun jokin muu kuin P-vaihde oli päällä\n・ Kuljettajan ovi avattiin, kun N-, D- tai B-vaihde oli päällä\n・ Vara-akun varaus on alhainen, koska vaihde oli pitkään vapaalla (Neutral-asennossa)\nKäynnistä hybridijärjestelmä tarvittaessa uudelleen virtapainikkeesta.",
	"PpositionRequestShrt" : "Pysäköintiasentopyyntö",
	"PreheatingDispLampLong" : "Hehkutus käynnissä. Tarkistuta auto myyjäliikkeessä, jos merkkivalo ei sammu.",
	"PreheatingDispLampShrt" : "Hehkutus käynnissä",
	"RoadSurfaceIcingCautionLong" : "Ulkolämpötila on enintään 4 °C.\nVaro jäisiä tienpintoja.\n",
	"RoadSurfaceIcingCautionShrt" : "Jäätyneen tienpinnan varoitus",
	"RvmSysErrorLong" : "RVM-järjestelmässä on virhe.\nTarkista, ettei takapuskurin pinnassa näy mitään epätavallista ja puhdista puskuri, jos se on lian tai lumen peitossa.\nTarkistuta auto Mazda-liikkeessä jos tämä varoitusvalo ei sammu.",
	"RvmSysErrorShrt" : "RVM-järjestelmän toimintahäiriö",
	"SBSBrakeMRCCUnavailableLong" : "SBS-jarrutustoiminto/MRCC-vakionopeussäädin ei ole tällä hetkellä käytettävissä.",
	"SBSBrakeMRCCUnavailableShrt" : "SBS/MRCC ei ole käytettävissä",
	"SBSBrakeUnavailableLong" : "SBS-jarrutustoiminto ei ole tällä hetkellä käytettävissä.",
	"SBSBrakeUnavailableShrt" : "SBS-jarrutus ei ole käytettävissä",
	"SBSMRCCDRSSRadarSoilingLong" : "SBS/MRCC/DRSS-tutka (anturi) on likaantunut.\nPuhdista tutkan (anturin) koko pinta.\n",
	"SBSMRCCDRSSRadarSoilingShrt" : "SBS-/MRCC-/DRSS-tutkan häiriö",
	"SBSMRCCRadarSoilingLong" : "SBS/MRCC-tutka (anturi) on likaantunut.\nPuhdista tutkan (anturin) koko pinta.\n",
	"SBSMRCCRadarSoilingShrt" : "SBS-/MRCC-tutkan toimintahäiriö",
	"SBSSysErrorLong" : "SBS-järjestelmässä on virhe.\nTarkistuta auto Mazda-liikkeessä.\n",
	"SBSSysErrorShrt" : "SBS-järjestelmän toimintahäiriö",
	"SCBSSysErrorLong" : "Smart City Brake Support (SCBS) toimintahäiriö. \nTarkistuta auto välittömästi myyjäliikkeessä.",
	"SCBSSysErrorLong_105" : "Smart City Brake Support (SCBS) toimintahäiriö. Poista jää tuulilasista. Anna myyjän tarkistaa ajoneuvo jos indikaattori pysyy päällä.",
	"SCBSSysErrorShort_105" : "SCBS-järjestelmän toimintahäiriö",
	"SCBSSysErrorShrt" : "SCBS-järjestelmän toimintahäiriö",
	"SCBSUnavailableLong" : "Smart City Brake Support  (SCBS) ei ole tällä hetkellä käytettävissä.",
	"SCBSUnavailableLong1" : "Jarrutusavustinjärjestelmä on väliaikaisesti poistettu käytöstä, koska auton sisälämpötila on liian korkea. Jarrutusavustinjärjestelmä otetaan takaisin käyttöön, kun auton sisälämpötila laskee riittävästi.",
	"SCBSUnavailableShrt" : "SCBS ei ole käytössä",
	"SCBSUnavailableShrt1" : "SCBS ei ole käytössä",
	"SCBSWindshieldSoilingLong" : "Smart City Brake Support (SCBS) toimintahäiriö. \nPuhdista tuulilasi. Tarkistuta auto myyjäliikkeessä, jos merkkivalo ei sammu.",
	"SCBSWindshieldSoilingShrt" : "SCBS-järjestelmän toimintahäiriö",
	"SCRMalfunction100Long" : "Dieselpäästöjärjestelmän (SCR) toimintahäiriö.\nAjoneuvon nopeutta rajoitetaan, jos ongelmaa ei korjata.",
	"SCRMalfunction101Long" : "Dieselpäästöjärjestelmän (SCR) toimintahäiriö.\nMoottori siirtyy pakotetulle tyhjäkäynnille, jos ongelmaa ei korjata.",
	"SCRMalfunction102Long" : "Dieselpäästöjärjestelmän (SCR) toimintahäiriö. Moottori on pakotetulla joutokäynnillä.\nOta yhteyttä Mazda-jälleenmyyjään huoltoa varten.",
	"ScrMalfunction" : "SCR häiriö",
	"SedimenterWarningLong" : "Vedenerottimeen kertynyt vesi ylittää suunnitellun määrän. Tarkistuta auto myyjäliikkeessä, jos merkkivalo ei sammu.",
	"SedimenterWarningShrt" : "Vedenerottimen tarkastus",
	"SystemInspectionLong" : "Tasauspyörästön öljyn lämpötila on epätavallisen korkea tai etu- ja takarenkaiden pyörimisnopeuksissa on ollut merkittäviä eroja (esimerkiksi mudasta lähdettäessä). Pysäytä auto turvalliseen paikkaan ja jatka vasta kun varoitusvalo on sammunut. Tarkistuta auto myyjäliikkeessä, jos merkkivalo ei sammu.",
	"SystemInspectionShrt" : "Nelivetojärjestelmän tarkistus",
	"TpmsSysErrorLong" : "Rengaspaineen valvontajärjestelmän (TPMS) toimintahäiriö.Tarkistuta auto myyjäliikkeessä.",
	"TpmsSysErrorShrt" : "TPMS-järjestelmän toimintahäiriö",
	"VehicleSysErrorLong" : "Auton järjestelmän toimintahäiriö. Tarkistuta auto myyjäliikkeessä.",
	"VehicleSysErrorShrt" : "Auton järjestelmän toimintahäiriö",
	"WarningGuidance" : "Varoitukset",
	"WarningSafetyMessage" : "Varoituksia ei näytetä turvallisuussyistä.",
	"Warnings" : "Varoituksia",
	"brakeFluid" : "Jarruneste on vähissä",
	"engineOilPressure" : "Moottorin öljynpaine",
	"highVoltage" : "Korkeajänniteakku lähes tyhjä",
	"lowBattStartEngine" : "Akku lähes tyhjä. Käynnistä auto!",
};

framework.registerAppDictLoaded("warnguide", "fi_FI");