var Localization_warnguideAppDict_nl_NL = {
	//"stringId" : "localString"
	"AbsSysErrorLong" : "Storing antiblokkeersysteem (ABS).\nLaat het voertuig onmiddellijk nakijken door een dealer.\n",
	"AbsSysErrorShrt" : "Storing ABS",
	"AbsSystemErrorLong" : "Storing antiblokkeersysteem (ABS).\nLaat het voertuig onmiddellijk nakijken door een dealer.\n",
	"AbsSystemErrorShrt" : "Storing ABS",
	"AccumulationDpfLong" : "De ophoping van roetdeeltjes (PM) in het roetfilter (DPF) heeft de voorgeschreven limiet overschreden.\nRijd gedurende 10 tot 15 minuten met een volledig opgewarmde motor (blauw temperatuurlicht uit) met een snelheid van 15 km/u of meer om de roetdeeltjes te elimineren.  Laat het voertuig nakijken door een dealer als deze indicator niet uitgaat.\n",
	"AccumulationDpfShrt" : "Roetdeeltjes ophoping in DPF",
	"ActiveBonnetSystemMalfunctionLong" : "Active Bonnet Systeem Storing.\nLaat het voertuig controleren door een dealer als deze waarschuwing aan blijft of blijft knipperen.",
	"ActiveBonnetSystemMalfunctionShrt" : "Active Bonnet Systeem Storing",
	"AfsSystemErrorLong" : "Storing adaptief bochtenverlichtingssysteem (AFS).  Laat het voertuig nakijken door een dealer als deze indicator blijft knipperen.",
	"AfsSystemErrorShrt" : "Storing AFS",
	"AfterRunCoolingPumpLong" : "Bel of bezoek uw dealership voor onderhoud als uw Mazda overhit raakt. ",
	"AfterRunCoolingPumpShrt" : "After Run Koelpomp",
	"AirbagSysPretensionerSysErrorLong" : "Storing airbag/gordel.\nLaat het voertuig onmiddellijk nakijken door een dealer\n",
	"AirbagSysPretensionerSysErrorShrt" : "Stor. airbag/gordelspanning",
	"AutoLevelSystemErrorLong" : "Storing automatische koplamphoogteregelaar.\nLaat het voertuig nakijken door een dealer als deze indicator niet uitgaat.",
	"AutoLevelSystemErrorShrt" : "Stor. autom. Koplampinstelling",
	"AutoLevelSystemErrorShrtJ03" : "Storing in koplampsysteem",
	"AutoTransSysErrorLong" : "Storing automatische versnellingsbak.\nHet voertuig kan schade oplopen als u blijft rijden.  Laat het voertuig onmiddellijk nakijken door een dealer.\n  ",
	"AutoTransSysErrorShrt" : "Storing automatische versnellingsbak",
	"AuxBattLowLong" : "De 12V-accu is bijna leeg.\n・Als dit lampje vaak brandt tijdens het rijden, kan het zijn dat de accu capaciteit verloren heeft. Laat het voertuig nakijken door uw dealer.\n・Als dit lampje permanent brandt en niet uitgaat, is de 12V-accu leeg. Raadpleeg de gebruikershandleiding voordat u het hybride systeem start en laat het voertuig nakijken door uw dealer.",
	"AuxBattLowShrt" : "12V Battery Low",
	"BattManagSysErrorLong" : "Storing accubeheersysteem.\nLaat het voertuig nakijken door een dealer.\n",
	"BattManagSysErrorShrt" : "Storing accubeheersysteem",
	"BrakOverrideSysErrorLong" : "Storing remlichtschakelaar.\nLaat het voertuig onmiddellijk nakijken door een dealer.\n",
	"BrakOverrideSysErrorShrt" : "Storing Brake Overridesysteem",
	"BrakeSysErrorLong" : "Remvloeistofpeil laag of storing remsysteem.  Zet het voertuig onmiddellijk op een veilige plek stil en laat het nakijken door een dealer.",
	"BrakeSysErrorShrt" : "Storing remsysteem",
	"BrakeSystemErrorLong" : "Storing elektronisch bestuurd remsysteem.\nZet het voertuig onmiddellijk op een veilige plek stil en laat hem nakijken door een dealer.\n",
	"BrakeSystemErrorShrt" : "Storing remsysteem",
	"BsmSystemErrorLong" : "Storing Blind Spot Monitoring (BSM)/Rear Cross Traffic Alert (RCTA).\nControleer op afwijkingen in het oppervlak van de achterbumper en maak schoon als er vuil of sneeuw opzit. Laat het voertuig nakijken door een dealer als deze indicator niet uitgaat.\n",
	"BsmSystemErrorShrt" : "Storing BSM",
	"ChargSysMalHighPrt" : "Oplading Systeem Defect. Voertuig onmiddellijk stoppen op een veilige plaats.",
	"ChargingSysErrorLong" : "Storing oplaadsysteem. \nHet voertuig kan schade oplopen als u blijft rijden.  Zet het voertuig onmiddellijk op een veilige plek stil en laat het nakijken door een dealer.\n",
	"ChargingSysErrorShrt" : "Storing oplaadsysteem",
	"ChrgSysErrorLong" : "Storing oplaadsysteem.\nZet het voertuig onmiddellijk op een veilige plek stil en laat het nakijken door een dealer.\n",
	"ChrgSysErrorShrt" : "Storing oplaadsysteem",
	"ColdStartDisableLong" : "Het starten van de motor wordt verhinderd wanneer er sprake is van een extreem koude omgevingstemperatuur om motorschade te voorkomen. Raadpleeg de gebruikershandleiding. U kunt mogelijke vertraging bij het starten van uw Mazda voorkomen door de motorblokverwarmer in te schakelen.",
	"ColdStartDisableShrt" : "Koude start uitgeschakeld",
	"ControlSystemErrorLong" : "Storing controlesysteem parkeerstand.\nIndien dit niet wordt nagekeken, kan dit leiden tot de volgende situaties:\n・Het parkeerblokkeringsmechanisme werkt niet. Parkeer op een vlakke locatie en trek de handrem stevig aan.\n・De start-/stopknop kan niet uitgeschakeld worden. Druk herhaaldelijk op de start-/stopknop om uit te schakelen.\n・De melding \"Handrem aantrekken bij het parkeren\" verdwijnt tijdens het rijden en verschijnt na het stoppen.\nLaat het voertuig onmiddellijk nakijken door de dealer.\n",
	"ControlSystemErrorShrt" : "Fout parkeerstandcontrolesysteem",
	"DPFErrorLong" : "Storing roetfilter (DPF).\nLaat het voertuig nakijken door een dealer.\n",
	"DPFErrorShrt" : "DPF-fout",
	"DRSSSysErrorLong" : "Er is een fout in het DRSS-systeem.\nLaat uw voertuig nakijken door een Mazda-dealer.\n",
	"DRSSSysErrorShrt" : "Storing DRSS",
	"DefEmpty" : "DEF leeg",
	"DefLow" : "DEF raakt op",
	"DefVeryLow" : "DEF bijna op",
	"DriveBattDropLong" : "Het resterende vermogen in de hoogspanningsaccu is laag omdat de versnelling langdurig in de vrijstand heeft gestaan.\nOpladen is niet mogelijk in de vrijstand. Schakel naar de parkeerstand wanneer het voertuig langdurig stilstaat.\nStart het hybride systeem indien nodig opnieuw op door op de start-/stopknop te drukken.\n",
	"DriveBattDropShrt" : "High Voltage Battery Low",
	"DropKeyBattChrgLong" : "Sleutelbatterij laag.\nVervang de sleutelbatterij onmiddellijk.\n",
	"DropKeyBattChrgShrt" : "Batterij sleutel bijna leeg",
	"DscSysErrorLong" : "Storing Dynamic Stability Control (DSC), Traction Control System (TCS) of Hill Launch Assist (HLA).\nLaat het voertuig onmiddellijk nakijken door een dealer.\n",
	"DscSysErrorShrt" : "Storing DSC",
	"DscSystemErrorLong" : "Storing dynamische stabiliteitscontrole (DCS) of tractiecontrolesysteem (TCS).\nLaat het voertuig onmiddellijk nakijken door een dealer.\n",
	"DscSystemErrorShrt" : "Storing DSC",
	"EcbSysErrorLong" : "Storing regeneratief remmen of elektronisch bestuurd remsysteem.\nZet het voertuig onmiddellijk op een veilige plek stil en laat het nakijken door een dealer.\n",
	"EcbSysErrorShrt" : "Storing remsysteem",
	"ElectricParkingBrakeHighLong" : "Er heeft zich een storing voorgedaan in het parkeerremsysteem. Raadpleeg uw Mazda-dealer voor een controle.",
	"ElectricParkingBrakeLong" : "Er heeft zich een storing voorgedaan in het parkeerremsysteem. Raadpleeg uw Mazda-dealer voor een controle.",
	"ElectricParkingBrakeShrt" : "Storing in systeem parkeerrem",
	"ElectricVacuumPumpSystemMalfunctionLong" : "Er heeft zich een storing voorgedaan in het systeem van de elektrische vacuümpomp. Als u deze storing niet verhelpt, kan het systeem defect raken, wat kan leiden tot onverwachte gevaren of problemen. Raadpleeg onmiddellijk uw Mazda-dealer en laat deze storing controleren.",
	"ElectricVacuumPumpSystemMalfunctionShrt" : "Storing in systeem elektrische vacuümpomp",
	"ElectronicThrottleControlLong" : "Als het waarschuwingslampje blijft branden, is er een storing in de Elektronische Controle Unit.  Start de motor van uw Mazda opnieuw voor het resetten van de Elektronische Controle Unit, of breng het voertuig naar een dealership voor onderhoud.  \n\nAls het waarschuwingslampje knippert, is een ernstige storing opgetreden en de gaspedaal output zal beperkt zijn.  Laat het voertuig zo spoedig mogelijk onderhouden door uw dealership.  Probeer de Elektronische Controle Unit te resetten door uw motor opnieuw te starten. \n",
	"ElectronicThrottleControlShrt" : "Elektronische smoorregeling",
	"EloopChargingLong" : "i‑ELOOP wordt opgeladen.\nControleer terwijl de motor draait of het opladen voltooid is en de waarschuwingsindicator uit is. Laat het voertuig nakijken door een dealer als deze indicator niet uitgaat.\n",
	"EloopChargingShrt" : "i‑ELOOP laadt op",
	"EloopSysErrorLong" : "Storing i‑ELOOP-systeem.\nLaat het voertuig nakijken door een dealer als deze indicator niet uitgaat.\n",
	"EloopSysErrorShrt" : "Storing i‑ELOOP-systeem",
	"EngCoolntTempHighOnLong" : "Motor raakt oververhit.\nZet het voertuig onmiddellijk op een veilige plek stil, zet de motor af, en neem gepaste maatregelen.  Raadpleeg de gebruikershandleiding.\n",
	"EngCoolntTempHighOnShrt" : "Hoge temperatuur motorkoelvloeistof",
	"EngOilPressureErrorLong" : "Motoroliedruk laag.\nZet het voertuig onmiddellijk op een veilige plek stil, zet de motor af, en controleer het motoroliepeil. Vul de olie indien nodig bij.\nLaat het voertuig onmiddellijk nakijken door een dealer als deze indicator aangaat nadat u de olie hebt bijgevuld of wanneer het oliepeil goed is.\n",
	"EngOilPressureErrorShrt" : "Oliedruk motor laag",
	"EngSystemErrorLong" : "Storing motorsysteem.  Laat het voertuig onmiddellijk nakijken door een dealer.",
	"EngSystemErrorShrt" : "Storing motorsysteem",
	"EngineOilPressureErrorLong" : "Motoroliedruk laag.\nZet het voertuig onmiddellijk op een veilige plek stil, zet de motor af, en controleer het motoroliepeil. Vul de olie indien nodig bij.\nLaat het voertuig onmiddellijk nakijken door een dealer als deze indicator aangaat nadat u de olie hebt bijgevuld of wanneer het oliepeil goed is.\n",
	"EngineOilPressureErrorShrt" : "Oliedruk motor laag",
	"EngineWaterTempDropLong" : "Motorkoelvloeistof is koud en er is geen warme lucht beschikbaar voor verwarmen/ontdooien. Er kan met het voertuig gereden worden met de indicator aan of uit.  Laat het voertuig nakijken door een dealer als deze indicator niet uitgaat.",
	"EngineWaterTempDropShrt" : "Temp. motorkoelvloeistof laag",
	"EngineWaterTempRiseLong" : "Motor wordt heet.\nRij langzaam of zet het voertuig stil totdat de indicator niet meer knippert. Neem gepaste maatregelen als de indicator ook na het stoppen blijft knipperen. Raadpleeg de gebruikershandleiding.",
	"EngineWaterTempRiseShrt" : "Hoge temperatuur motorkoelvloeistof",
	"EngnCoolTempHighHighPrt" : "Motorkoelvloeistoftemperatuur Hoog. Voertuig onmiddellijk stoppen op een veilige plaats.",
	"FOWMRCCDRSSRadarSoilingLong" : "De FOW/MRCC/DRSS-radar (sensor) is vuil.\nMaak het hele oppervlak van de radar (sensor) schoon.\n",
	"FOWMRCCDRSSRadarSoilingShrt" : "Radarstoring FOW/MRCC/DRSS",
	"FOWMRCCRadarSoilingLong" : "Radarstoring (sensor) FOW/MRCC.\nMaak het hele oppervlak van het grille-embleem aan de voorkant schoon als dit vies of met sneeuw bedekt is.  \nLaat het voertuig nakijken door een dealer als deze indicator niet uitgaat.",
	"FOWMRCCRadarSoilingShrt" : "Radarstoring FOW/MRCC",
	"FOWSysError" : "Storing FOW",
	"FOWSysErrorLong" : "Storing Forward Obstruction Warning (FOW)-systeem.\nLaat het voertuig nakijken door een dealer.",
	"FWDSysErrorLong" : "Storing 4WD-systeem of de maat van de banden is voor en achter verschillend.\nLaat het voertuig nakijken door een dealer.",
	"FWDSysErrorShrt" : "Storing 4WD-systeem",
	"FuelAirFilterCartReplacePeriodLong" : "Brandstoffilterpatroon moet worden vervangen.",
	"FuelAirFilterCartReplacePeriodShrt" : "Vervanging brandstoffilterpatroon vereist.",
	"FuelCapInspectionLong" : "De tankdop is mogelijk niet goed geplaatst.\nControleer of de tankdop goed geplaatst en vastgedraaid is.\nNadat de tankdop goed geplaatst en vastgedraaid is, zal deze indicator nog een aantal rijcycli aanblijven totdat geverifieerd kan worden dat het systeem in orde is.  Laat het voertuig nakijken door een dealer als deze indicator niet uitgaat.\n",
	"FuelCapInspectionShrt" : "Inspectie tankdop",
	"HBCALHUnavailableLong_1" : "High Beam Control is tijdelijk uitgeschakeld vanwege een te hoge temperatuur in de passagiersruimte. High Beam Control wordt ingeschakeld zodra de passagiersruimte voldoende is afgekoeld.",
	"HBCALHUnavailableLong_2" : "Adaptive LED Headlights zijn tijdelijk uitgeschakeld vanwege een te hoge temperatuur in de passagiersruimte. De Adaptive LED Headlights worden ingeschakeld zodra de passagiersruimte voldoende is afgekoeld.",
	"HBCALHUnavailableShrt_1" : "HBC niet beschikbaar",
	"HBCALHUnavailableShrt_2" : "ALH niet beschikbaar",
	"HBCLDWSSysErrorLong" : "Storing High Beam Control (HBC)* en/of Lane Departure Warning System (LDWS)*. Laat het voertuig nakijken door een dealer als deze indicator niet uitgaat.\n*De aanwezigheid van deze functies is afhankelijk van het model/uitrustingsniveau.",
	"HBCLDWSSysErrorLong_2" : "Storing High Beam Control (HBC)/Lane-keep Assist System (LAS). Laat het voertuig nakijken door een dealer als deze indicator niet uitgaat.",
	"HBCLDWSSysErrorLong_3" : "Storing Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS). Maak de ruit schoon.  Laat het voertuig nakijken door een dealer als deze indicator niet uitgaat.",
	"HBCLDWSSysErrorLong_4" : "Storing Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS). Laat het voertuig nakijken door een dealer als deze indicator niet uitgaat.",
	"HBCLDWSSysErrorShrt" : "Systeemstoring HBC/LDWS",
	"HBCLDWSSysErrorShrt_2" : "Storing HBC/LAS systeem",
	"HBCLDWSSysErrorShrt_3" : "Storing ALH/LDWS systeem",
	"HBCLDWSSysErrorShrt_4" : "Storing ALH/LAS systeem",
	"HBCLDWSWindshieldFogLong" : "Storing High Beam Control (HBC)* en/of Lane Departure Warning System (LDWS)*. Ontdooi de voorruit.  Laat het voertuig nakijken door een dealer als deze indicator niet uitgaat.\n*De aanwezigheid van deze functies is afhankelijk van het model/uitrustingsniveau.",
	"HBCLDWSWindshieldFogLong_2" : "Storing High Beam Control (HBC)/Lane-keep Assist System (LAS). Ontdooi de voorruit. Laat het voertuig door een dealer nakijken als deze indicator blijft branden.",
	"HBCLDWSWindshieldFogLong_3" : "Storing Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS). Ontdooi de voorruit. Laat het voertuig nakijken door een dealer als deze indicator niet uitgaat.",
	"HBCLDWSWindshieldFogLong_4" : "Storing Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS). Ontdooi de voorruit.\nLaat het voertuig nakijken door een dealer als deze indicator niet uitgaat.",
	"HBCLDWSWindshieldFogShrt" : "Systeemstoring HBC/LDWS",
	"HBCLDWSWindshieldFogShrt_2" : "Storing HBC/LAS systeem",
	"HBCLDWSWindshieldFogShrt_3" : "Storing ALH/LDWS systeem",
	"HBCLDWSWindshieldFogShrt_4" : "Storing ALH/LAS systeem",
	"HBCLLDWSCamDisconnectLong" : "Storing High Beam Control (HBC)* en/of Lane Departure Warning System (LDWS)*. Maak de voorruit schoon.   Laat het voertuig nakijken door een dealer als deze indicator niet uitgaat.\n*De aanwezigheid van deze functies is afhankelijk van het model/uitrustingsniveau.",
	"HBCLLDWSCamDisconnectLong_2" : "Storing High Beam Control (HBC)/Lane-keep Assist System (LAS). Maak de ruit schoon.  Laat het voertuig nakijken door een dealer als deze indicator niet uitgaat.",
	"HBCLLDWSCamDisconnectLong_3" : "Storing Adaptive LED Headlights (ALH)/Lane Departure Warning System (LDWS). Maak de ruit schoon.  Laat het voertuig nakijken door een dealer als deze indicator niet uitgaat.",
	"HBCLLDWSCamDisconnectLong_4" : "Storing Adaptive LED Headlights (ALH)/Lane-keep Assist System (LAS). Reinig de voorruit. Laat het voertuig door een dealer nakijken als deze indicator blijft branden.",
	"HBCLLDWSCamDisconnectShrt" : "Camerastoring HBC/LDWS",
	"HBCLLDWSCamDisconnectShrt_2" : "Camerastoring HBC/LAS",
	"HBCLLDWSCamDisconnectShrt_3" : "Camerastoring ALH/LDWS",
	"HBCLLDWSCamDisconnectShrt_4" : "Camerastoring ALH/LAS",
	"HBCSysErrorLong" : "Storing High Beam Control (HBC).\nLaat het voertuig nakijken door een dealer.\n",
	"HBCSysErrorLong_2" : "Storing Adaptive LED Headlights (ALH). Laat het voertuig nakijken door een dealer.",
	"HBCSysErrorShrt" : "Storing HBC",
	"HBCSysErrorShrt_2" : "Storing ALH",
	"HbcOrAlhUnavailable" : "HBC of ALH niet beschikbaar",
	"HeadlightSystemErrorLongJ03" : "Er heeft zich een storing voorgedaan in het koplampsysteem. Raadpleeg uw Mazda-dealer als het waarschuwingslampje blijft knipperen.",
	"HighEngineOillevel" : "Hoog motoroliepeil",
	"HighEngineOillevelDetail" : "Het oliepeil van de motor is te hoog. Vervang de olie.",
	"HybrdSysMalHighPrt" : "Hybride Systeem Defect. Voertuig onmiddellijk stoppen op een veilige plaats.",
	"HybridSysErrorLong" : "Storing hybride systeem.\nHet voertuig kan schade oplopen als u blijft rijden. Zet het voertuig onmiddellijk op een veilige plek stil en laat het nakijken door een dealer.\n",
	"HybridSysErrorShrt" : "Defect Hybride Systeem",
	"HybridSysOverheatLong" : "Storing hybride systeem.\nHet voertuig kan schade oplopen als u blijft rijden. Zet het voertuig onmiddellijk op een veilige plek stil en laat het nakijken door een dealer.\n",
	"HybridSysOverheatShrt" : "Oververhitting hybride systeem",
	"IeloopChrgHighPrt" : "i‑ELOOP opladen. Terwijl de motor draait, controleer dan of het opladen voltooid is en het waarschuwingslampje uit is.",
	"IstopSysErrorLong" : "i‑stop-besturing is niet mogelijk.\nLaat uw voertuig nakijken door een Mazda-dealer.\n",
	"IstopSysErrorShrt" : "Storing i‑stop systeem",
	"KeylesSysErrorLong" : "Storing keyless entry systeem.\nLaat het voertuig nakijken door een dealer.",
	"KeylesSysErrorShrt" : "Storing keyless entry",
	"LDWSLASUnavailableLong_1" : "Lane Departure Warning System is tijdelijk uitgeschakeld vanwege een te hoge temperatuur in de passagiersruimte. Lane Departure Warning System wordt ingeschakeld zodra de passagiersruimte voldoende is afgekoeld.",
	"LDWSLASUnavailableLong_2" : "Lane-Keep Assist System is tijdelijk uitgeschakeld vanwege een te hoge temperatuur in de passagiersruimte. Lane-Keep Assist System wordt ingeschakeld zodra de passagiersruimte voldoende is afgekoeld. ",
	"LDWSLASUnavailableShrt_1" : "LDWS niet beschikbaar",
	"LDWSLASUnavailableShrt_2" : "LAS niet beschikbaar",
	"LDWSSysErrorLong" : "Storing Lane Departure Warning System (LDWS).\nLaat het voertuig nakijken door een dealer.\n",
	"LDWSSysErrorLong_2" : "Storing Lane-keep Assist System (LAS). Laat het voertuig nakijken door een dealer.",
	"LDWSSysErrorShrt" : "Storing LDWS",
	"LDWSSysErrorShrt_2" : "Storing LAS",
	"LdwsOrLasUnavailable" : "LDWS of LAS niet beschikbaar",
	"LowBrakeFluidLong" : "Remvloeistofpeil is laag.\nZet het voertuig onmiddellijk op een veilige plek stil en laat hem nakijken door een dealer.",
	"LowBrakeFluidShrt" : "Remvloeistofpeil laag",
	"LowEngineOillevel" : "Laag motoroliepeil",
	"LowEngineOillevelDetail" : "Het oliepeil van de motor is te laag.  Voeg olie toe.",
	"LowFuelLong" : "Brandstofpeil is laag.\nU moet binnenkort tanken.\n",
	"LowFuelShrt" : "Brandstofpeil laag",
	"LowTireAirPressureFlatLong" : "Als de bandendruk beduidend zakt na het oplichten van het TPMS-waarschuwingslampje, of als een band lek is, licht het waarschuwingslampje voor een lekke band ook op.  Als een run-flatband lek is, rijdt u voorzichtig met het voertuig naar de dichtstbijzijnde Mazda-dealer om de band te laten vervangen.",
	"LowTireAirPressureLong" : "Lage bandenspanning in één of meer banden.\nControleer de luchtdruk van de banden en vul aan tot de juiste luchtdruk.  Druk na het aanpassen van de bandenspanning op de TPMS SET-schakelaar totdat u een piep hoort.",
	"LowTireAirPressureShrt" : "Lage bandendruk",
	"LowWasheFluidLong" : "Ruitenwisservloeistofpeil is laag.\nVul de ruitenwisservloeistof bij.\n",
	"LowWasheFluidShrt" : "Ruitenwisservloeistofpeil laag",
	"MRCCSysErrorLong" : "Storing Mazda Radar Cruise Control (MRCC).\nLaat het voertuig nakijken door een dealer.\n",
	"MRCCSysErrorShrt" : "Storing MRCC",
	"MRCCUnavailableLong" : "Mazda Radar Cruise Control (MRCC) is op dit moment niet beschikbaar.",
	"MRCCUnavailableShrt" : "MRCC niet beschikbaar",
	"NoWarnings" : "Geen waarschuwingen gevonden",
	"OilLevelSystemMalfunctioning" : "Defect aan de sensor van het motoroliepeil",
	"OilLevelSystemMalfunctioningDetail" : "De sensor voor het motoroliepeil functioneert niet goed. Laat het voertuig nazien bij een Mazda-distributeur. ",
	"PowerSteeringSysErrorLong" : "Storing elektrische stuurbekrachtiging.\nZet het voertuig op een veilige plaatst stil en zet de motor af.  Laat het voertuig nakijken door een dealer als deze indicator niet uitgaat.\n",
	"PowerSteeringSysErrorShrt" : "Storing stuurbekrachtiging",
	"PpositionRequestLong" : "Schakel de versnelling naar de parkeerstand.\nDit heeft een van de volgende oorzaken:\n・ Het accusysteem is gestart of gestopt terwijl de versnelling in een andere stand dan de parkeerstand stond\n・ De deur aan de bestuurderskant werd geopend terwijl de versnelling in de N-, D- of B-stand stond\n・De resterende lading in de hoogspanningsaccu is laag omdat de transmissie langdurig in de vrijstand heeft gestaan\nStart het hybride systeem indien nodig opnieuw op door op de start-/stopknop te drukken.",
	"PpositionRequestShrt" : "Aanvraag parkeerstand",
	"PreheatingDispLampLong" : "Gloeibougies gloeien voor.\nLaat het voertuig nakijken door een dealer als deze indicator niet uitgaat.\n",
	"PreheatingDispLampShrt" : "Voorgloeien gloeibougies",
	"RoadSurfaceIcingCautionLong" : "Buitentemperatuur is 4 °C of lager.\nLet tijdens het rijden op glad wegdek.\n",
	"RoadSurfaceIcingCautionShrt" : "Waarschuwing glad wegdek",
	"RvmSysErrorLong" : "Er is een fout in het RVM-systeem.\nControleer op afwijkingen in het oppervlak van de achterbumper en maak schoon als er vuil of sneeuw opzit.\nLaat uw voertuig nakijken door een Mazda-dealer als dit waarschuwingslampje niet uitgaat.",
	"RvmSysErrorShrt" : "Storing RVM",
	"SBSBrakeMRCCUnavailableLong" : "SBS-rem/MRCC op dit moment niet beschikbaar.",
	"SBSBrakeMRCCUnavailableShrt" : "SBS-rem/MRCC niet beschikbaar",
	"SBSBrakeUnavailableLong" : "SBS-rem op dit moment niet beschikbaar.",
	"SBSBrakeUnavailableShrt" : "SBS-rem niet beschikbaar",
	"SBSMRCCDRSSRadarSoilingLong" : "De SBS/MRCC/DRSS-radar (sensor) is vuil.\nMaak het hele oppervlak van de radar (sensor) schoon.\n",
	"SBSMRCCDRSSRadarSoilingShrt" : "Radarstoring SBS/MRCC/DRSS",
	"SBSMRCCRadarSoilingLong" : "De SBS/MRCC -radar (sensor) is vuil.\nMaak het hele oppervlak van de radar (sensor) schoon.\n",
	"SBSMRCCRadarSoilingShrt" : "Radarstoring SBS/MRCC",
	"SBSSysErrorLong" : "Er is een fout in het SBS-systeem.\nLaat uw voertuig nakijken door een Mazda-dealer.\n",
	"SBSSysErrorShrt" : "Storing SBS",
	"SCBSSysErrorLong" : "Storing Smart City Brake Support (SCBS).\nLaat het voertuig onmiddellijk nakijken door een dealer.\n",
	"SCBSSysErrorLong_105" : "Storing Smart City Brake Support(SCBS). Ontdooi de voorruit. Laat het voertuig nakijken door een dealer als deze indicator niet uitgaat.",
	"SCBSSysErrorShort_105" : "Storing SCBS",
	"SCBSSysErrorShrt" : "Storing SCBS",
	"SCBSUnavailableLong" : "Smart City Brake Support (SCBS) op dit moment niet beschikbaar.",
	"SCBSUnavailableLong1" : "Het Smart City Brake Support-systeem is tijdelijk uitgeschakeld vanwege een te hoge temperatuur in de passagiersruimte. Het Smart City Brake Support-systeem wordt ingeschakeld zodra de passagiersruimte voldoende is afgekoeld.",
	"SCBSUnavailableShrt" : "SCBS niet beschikbaar",
	"SCBSUnavailableShrt1" : "SCBS niet beschikbaar",
	"SCBSWindshieldSoilingLong" : "Storing Smart City Brake Support (SCBS).\nMaak de voorruit schoon.  Laat het voertuig nakijken door een dealer als deze indicator niet uitgaat.\n",
	"SCBSWindshieldSoilingShrt" : "Storing SCBS",
	"SCRMalfunction100Long" : "Storing in SCR-systeem voor dieselemissie.\nDe voertuigsnelheid wordt beperkt als het probleem niet wordt behandeld.",
	"SCRMalfunction101Long" : "Storing in SCR-systeem voor dieselemissie.\nDe motor gaat geforceerd over op de stationaire modus als het probleem niet wordt behandeld.",
	"SCRMalfunction102Long" : "Storing in SCR-systeem voor dieselemissie. Motor staat nu geforceerd in de stationaire modus.\nNeem contact op met uw Mazda-dealer voor service.",
	"ScrMalfunction" : "Storing SCR",
	"SedimenterWarningLong" : "De hoeveelheid water die zich in de waterafscheider heeft opgehoopt, overschrijdt de gespecificeerde hoeveelheid.\nLaat het voertuig nakijken door een dealer als deze indicator niet uitgaat.\n",
	"SedimenterWarningShrt" : "Inspectie waterafscheider ",
	"SystemInspectionLong" : "De differentieelolietemperatuur is abnormaal hoog of er heeft zich een groot rotatieverschil voorgedaan tussen de voor- en achterbanden (bijvoorbeeld wanneer er geprobeerd wordt om los te komen uit de modder).\nZet het voertuig op een veilige plaats stil en rijd weer verder nadat de waarschuwingsindicator uit is gegaan. Laat het voertuig nakijken door een dealer als deze indicator niet uitgaat.\n",
	"SystemInspectionShrt" : "Inspectie 4WD-systeem",
	"TpmsSysErrorLong" : "Storing controlesysteem bandenspanning (TPMS).\nLaat het voertuig nakijken door een dealer.\n",
	"TpmsSysErrorShrt" : "Storing TPMS-systeem",
	"VehicleSysErrorLong" : "Systeemstoring voertuig.\nLaat het voertuig nakijken door een dealer.\n",
	"VehicleSysErrorShrt" : "Systeemstoring voertuig",
	"WarningGuidance" : "Waarschuwing",
	"WarningSafetyMessage" : "De waarschuwingsinformatie wordt om veiligheidsredenen niet weergegeven.",
	"Warnings" : "Waarschuwingen",
	"brakeFluid" : "Laag niveau remvloeistof",
	"engineOilPressure" : "Oliedrukmeter",
	"highVoltage" : "Hoge spanning Accu laag",
	"lowBattStartEngine" : "Accu bijna leeg! Start motor!",
};

framework.registerAppDictLoaded("warnguide", "nl_NL");