var Localization_ecoenergyAppDict_sr_RS = {
	//"stringId" : "localString"
	"ActuationTimeTitle" : "Aktivno vreme",
	"ApplicationsMenu" : "Aplikacije",
	"Average" : "Prosek",
	"AverageFuelEconomy" : "Prosek (ovaj put)",
	"Back" : "Nazad",
	"CancelBtn" : "Otkaži",
	"CelebrationMessage" : "Čestitamo!",
	"ConfirmBtn" : "Resetuj",
	"CummulativeFuelEconomy" : "Prosek",
	"CummulativeFuelEconomyReset" : "Istorija pros.potr. goriva",
	"CurrentDriveFuelTitle" : "Ekon. goriva (ova vožnja)",
	"CurrentStatus" : "Sadaš.",
	"DPFissue" : "i-stop unavailable.",
	"DPFissue2" : "DPF problem.",
	"EVDistn" : "tren. elek. vožnju",
	"EcoDriveStatus" : "Status eko vožnje",
	"ElapsedTimeInMin" : "m",
	"ErrorActivated" : "Ne može se aktivirati",
	"ErrorBrake" : "Pritisnite jače kočnicu",
	"ErrorEngineRestart" : "Motor treba ponovo startovati",
	"ErrorReady" : "Spreman",
	"ErrorShift" : "Prebacite menjač u neutralni položaj",
	"ErrorSteering" : "Pozicionirajte volan na sredinu",
	"ErrorUnknown" : "i‑stop sistem nije dostupan",
	"HEVAverage" : "Prosečno",
	"HEVThisDrive" : "ova vožnja",
	"HidePanel" : "Sakri dugmiće",
	"IgnitionOff" : "Prikaži ekran pri Isključivanju",
	"Km" : "km",
	"KmDriveMonitorJP" : "km",
	"LoadEEM" : "Ekonomične Potrošnje Učitavanje",
	"LoadEEMHEV" : "Nadzor drajva Učitavanje",
	"Miles" : "mi",
	"NotReady" : "NIJE SPREMNO",
	"OneDrv" : "Dist. za",
	"Ready" : "SPREMNO",
	"Reset" : "Resetuj pros.potroš.goriva",
	"ResetConfirm" : "Da li ste sigurni da želite resetovati prosečnu potrošnju goriva?",
	"ResetUnsuccessful" : "Resetovanje je bilo neuspešno. Da li želite da pokušate ponovo?",
	"RetryBtn" : "Pokušaj ponovo",
	"SbnTitleId" : "Ekonomične Potrošnje",
	"SelectSettings" : "Postavke",
	"Settings" : "Postavke",
	"SettingsRetryMsg" : "Postavka za sinhr. proseka i put A ne može se promeniti",
	"SinceReset" : "(od reset.)",
	"StopTimeTitle" : "Zaustavljen",
	"SwitchView" : "Sledeći ekran",
	"SyncTripA" : "Sinhr. prosek i put A",
	"ThisDrive" : "(ova vožnja)",
	"TotalActive" : "Akt. vreme",
	"TotalTimeTitle" : "Tot.vreme",
	"Wh" : "Wh",
	"batteryId" : "BATTERY",
	"cumulativeEV" : "Ukupna dist. električne vožnje",
	"driveMonitor" : "Nadzor drajva",
	"energyFlow" : "Tok energije",
	"engineId" : "ENGINE",
	"iStopBoost" : "i‑stop Opseg pojačanja",
	"iStopOn" : "i‑stop ON",
	"iStopOnTitle" : "% i‑stop UKLJUČEN",
	"kml" : "km/L",
	"lkm" : "L/100km",
	"motorId" : "MOTOR",
	"mpg" : "mpg",
	"oneDriveEV" : "Dist. za tr. elek. vožnju",
};

framework.registerAppDictLoaded("ecoenergy", "sr_RS");