var Localization_ecoenergyAppDict_it_IT = {
	//"stringId" : "localString"
	"ActuationTimeTitle" : "Tempo attivo",
	"ApplicationsMenu" : "Applicazioni",
	"Average" : "Media",
	"AverageFuelEconomy" : "Media (corrente)",
	"Back" : "Indietro",
	"CancelBtn" : "Annulla",
	"CelebrationMessage" : "Congratulazioni!",
	"ConfirmBtn" : "Resetta",
	"CummulativeFuelEconomy" : "Media (stor.)",
	"CummulativeFuelEconomyReset" : "Media consumi (storico)",
	"CurrentDriveFuelTitle" : "Hypermiling (Stavolta)",
	"CurrentStatus" : "Attuale",
	"DPFissue" : "i-stop unavailable.",
	"DPFissue2" : "DPF problem.",
	"EVDistn" : "Distanza EV",
	"EcoDriveStatus" : "Stato eco drive",
	"ElapsedTimeInMin" : "min",
	"ErrorActivated" : "Attivazione impossibile.",
	"ErrorBrake" : "Fare più pressione sul pedale del freno",
	"ErrorEngineRestart" : "Bisogna riavviare il motore.",
	"ErrorReady" : "Pronto",
	"ErrorShift" : "Mettere il cambio in folle.",
	"ErrorSteering" : "Riportare lo sterzo in posizione centrale.",
	"ErrorUnknown" : "i‑stop non disponibile.",
	"HEVAverage" : "Media",
	"HEVThisDrive" : "Stavolta",
	"HidePanel" : "Nascondi pulsanti",
	"IgnitionOff" : "Mostra schermo a veicolo spento",
	"Km" : "km",
	"KmDriveMonitorJP" : "km",
	"LoadEEM" : "Controllo consumo carburante in corso",
	"LoadEEMHEV" : "Monitor di guida Caricamento in corso",
	"Miles" : "mi",
	"NotReady" : "NON PRONTO",
	"OneDrv" : "Solo cond.",
	"Ready" : "PRONTO",
	"Reset" : "Resetta media",
	"ResetConfirm" : "Resettare la media di consumo carburante?",
	"ResetUnsuccessful" : "Reset impossibile. Riprovare?",
	"RetryBtn" : "Riprova",
	"SbnTitleId" : "Consumo carburante",
	"SelectSettings" : "Impostazioni",
	"Settings" : "Impostazioni",
	"SettingsRetryMsg" : "Impossibile cambiare le impostazioni di Media Sync e Trip A.",
	"SinceReset" : "Reset",
	"StopTimeTitle" : "Fermato",
	"SwitchView" : "Schermata successiva",
	"SyncTripA" : "Media SYnc e Trip A",
	"ThisDrive" : "Stavolta",
	"TotalActive" : "Tempo att.",
	"TotalTimeTitle" : "Tempo tot.",
	"Wh" : "Wh",
	"batteryId" : "BATTERY",
	"cumulativeEV" : "Distanza EV cumulativa",
	"driveMonitor" : "Monitor di guida",
	"energyFlow" : "Flusso di energia",
	"engineId" : "ENGINE",
	"iStopBoost" : "Totale Km in più grazie a i‑stop",
	"iStopOn" : "i‑stop ON",
	"iStopOnTitle" : "% i‑stop ON",
	"kml" : "km/L",
	"lkm" : "l/100Km",
	"motorId" : "MOTOR",
	"mpg" : "mpg",
	"oneDriveEV" : "Dist. EV singola guida",
};

framework.registerAppDictLoaded("ecoenergy", "it_IT");