var Localization_ecoenergyAppDict_no_NO = {
	//"stringId" : "localString"
	"ActuationTimeTitle" : "Tid aktiv",
	"ApplicationsMenu" : "Applikasjoner",
	"Average" : "Snitt",
	"AverageFuelEconomy" : "Snitt",
	"Back" : "Tilbake",
	"CancelBtn" : "Avbryt",
	"CelebrationMessage" : "Gratulerer!",
	"ConfirmBtn" : "Tilbakestill",
	"CummulativeFuelEconomy" : "Snitt (e. st.)",
	"CummulativeFuelEconomyReset" : "Snittforbruk (tidligere)",
	"CurrentDriveFuelTitle" : "Drivstofføkonomi (Den. Tur.)",
	"CurrentStatus" : "Nå",
	"DPFissue" : "i-stop unavailable.",
	"DPFissue2" : "DPF problem.",
	"EVDistn" : "EV-avstand",
	"EcoDriveStatus" : "Eco Drive-status",
	"ElapsedTimeInMin" : "min",
	"ErrorActivated" : "Kan ikke aktiveres.",
	"ErrorBrake" : "Trykk hardere på bremsen.",
	"ErrorEngineRestart" : "Motoren må startes på nytt",
	"ErrorReady" : "Klar.",
	"ErrorShift" : "Gir over til nøytral.",
	"ErrorSteering" : "Drei rattet til midtstilling.",
	"ErrorUnknown" : "i‑stop er ikke tilgjengelig.",
	"HEVAverage" : "Gjennom.",
	"HEVThisDrive" : "Den. Tur.",
	"HidePanel" : "Skjul knapper",
	"IgnitionOff" : "Vis skjermen når tenningen er av",
	"Km" : "km",
	"KmDriveMonitorJP" : "km",
	"LoadEEM" : "Forbruksovervåkning Laster",
	"LoadEEMHEV" : "Kjøremonitor Laster",
	"Miles" : "mi",
	"NotReady" : "IKKE KLAR",
	"OneDrv" : "One-Drive",
	"Ready" : "KLAR",
	"Reset" : "Tilbakestill Snitt",
	"ResetConfirm" : "Er du sikker på at du vil tilbakestille gjennomsnittlig drivstofforbruk?",
	"ResetUnsuccessful" : "Tilbakestilling mislyktes. Vil du prøve på nytt?",
	"RetryBtn" : "Prøv på nytt",
	"SbnTitleId" : "Forbruksovervåkning",
	"SelectSettings" : "Innstillinger",
	"Settings" : "Innstillinger",
	"SettingsRetryMsg" : "Innstillingene for Sync Average og Trip A kunne ikke endres",
	"SinceReset" : "e. st.",
	"StopTimeTitle" : "Stoppet",
	"SwitchView" : "Neste skjermbilde",
	"SyncTripA" : "Sync Average og Trip A",
	"ThisDrive" : "Den. Tur.",
	"TotalActive" : "Tid aktiv",
	"TotalTimeTitle" : "Total tid",
	"Wh" : "Wh",
	"batteryId" : "BATTERY",
	"cumulativeEV" : "Kumulativ EV-kjøreavstand",
	"driveMonitor" : "Kjøremonitor",
	"energyFlow" : "Energistrøm",
	"engineId" : "ENGINE",
	"iStopBoost" : "i‑stop, Forbedret Rekkevidde",
	"iStopOn" : "i‑stop ON",
	"iStopOnTitle" : "% i‑stop ON (Den. Tur.)",
	"kml" : "km/L",
	"lkm" : "L/100km",
	"motorId" : "MOTOR",
	"mpg" : "mpg",
	"oneDriveEV" : "One-Drive EV-avstand",
};

framework.registerAppDictLoaded("ecoenergy", "no_NO");