var __VrHelpPositionTable__emnaviAppDict_en_AU = {
	"Cockpit_Help2" : {
		"Right" : ["VrHelp_WhereAmI","VrHelp_RouteSummary","VrHelp_RepeatInstruction","VrHelp_AddCurrentLocationToFavorites","VrHelp_AddWaypointCategory"],
		"Left" : ["VrHelp_NewDestination","VrHelp_TakeMeHome","VrHelp_NavigateToAnAddress","VrHelp_NavigateToRecentDestination","VrHelp_ClearRoute"]
	}
};

var Localization_emnaviAppDict_en_AU = {
	//"stringId" : "localString"
	"AddressNotFound" : "Address Not Found",
	"AtSpeedCautionText" : " ",
	"Compass" : "Compass",
	"E" : "{value} E",
	"Elevation" : "Elevation",
	"FT" : "{value}{spacing} ft",
	"Latitude" : "Latitude",
	"Loading" : "Loading Navigation",
	"Longitude" : "Longitude",
	"M" : "{value}{spacing} m",
	"N" : "{value} N",
	"NAVAddressSearch" : "Navigation",
	"NAVAvoidances" : "Navigation",
	"NAVCitySearch" : "Navigation",
	"NAVCoordinate" : "Navigation",
	"NAVDragMode" : "Navigation",
	"NAVGasPrice" : "Navigation",
	"NAVHistory" : "Navigation",
	"NAVItemList" : "Navigation",
	"NAVMap" : "Navigation",
	"NAVMecca" : "Navigation",
	"NAVModifyPoint" : "Navigation",
	"NAVNavigationInfo" : "Navigation",
	"NAVNewDestination" : "Navigation",
	"NAVPOI" : "Navigation",
	"NAVPhoneZipSearch" : "Navigation",
	"NAVPointOnMap" : "Navigation",
	"NAVQuickSearch" : "Navigation",
	"NAVResults" : "Navigation",
	"NAVRoute" : "Navigation",
	"NAVSettings" : "Navigation",
	"NAVSimulation" : "Navigation",
	"NAVSortingOptions" : "Navigation",
	"NAVTraffic" : "Navigation",
	"NAVTurnByTurn" : "Navigation",
	"NAVVoicePrompts" : "Navigation",
	"NAVWeather" : "Navigation",
	"NoNavigation" : "Your Mazda is not equipped with a Navigation system. However, an integrated Navigation system is available through your Mazda dealer as a Genuine Mazda  Accessory.",
	"S" : "{value} S",
	"SDCardInvalid" : "Invalid SD Card",
	"SDCradInserted" : "SD Card Inserted",
	"SDCradRemoved" : "SD Card Removed",
	"VrHelp_AddCurrentLocationToFavorites" : "Add Current Location to Favourites",
	"VrHelp_AddWaypointCategory" : "Add Waypoint (category)",
	"VrHelp_ClearRoute" : "Clear Route",
	"VrHelp_NavigateToAnAddress" : "Navigate to an Address",
	"VrHelp_NavigateToRecentDestination" : "Navigate to Recent Destination",
	"VrHelp_NewDestination" : "New Destination",
	"VrHelp_RepeatInstruction" : "Repeat Instruction",
	"VrHelp_RouteSummary" : "Route Summary",
	"VrHelp_TakeMeHome" : "Take Me Home",
	"VrHelp_WhereAmI" : "Where Am I",
	"W" : "{value} W",
	"Y" : "{value}{spacing} yd",
	"YourLocation" : "Your Location",
	"emnavi" : "Navigation",
	"km" : "{value}{spacing} km",
	"mi" : "{value}{spacing}mi",
};

framework.registerAppDictLoaded("emnavi", "en_AU");