var __VrHelpPositionTable__emnaviAppDict_nl_NL = {
	"Cockpit_Help2" : {
		"Right" : ["VrHelp_WhereAmI","VrHelp_RouteSummary","VrHelp_RepeatInstruction","VrHelp_AddCurrentLocationToFavorites","VrHelp_AddWaypointCategory"],
		"Left" : ["VrHelp_NewDestination","VrHelp_TakeMeHome","VrHelp_NavigateToAnAddress","VrHelp_NavigateToRecentDestination","VrHelp_ClearRoute"]
	}
};

var Localization_emnaviAppDict_nl_NL = {
	//"stringId" : "localString"
	"AddressNotFound" : "Adres niet gevonden",
	"AtSpeedCautionText" : " ",
	"Compass" : "Kompas",
	"E" : "{value} O",
	"Elevation" : "Hoogte",
	"FT" : "{value}{spacing}ft",
	"Latitude" : "Geo. Bree.",
	"Loading" : "Navigatie wordt geladen",
	"Longitude" : "Geo. Len.",
	"M" : "{value}{spacing}m",
	"N" : "{value} N",
	"NAVAddressSearch" : "Navigatie",
	"NAVAvoidances" : "Navigatie",
	"NAVCitySearch" : "Navigatie",
	"NAVCoordinate" : "Navigatie",
	"NAVDragMode" : "Navigatie",
	"NAVGasPrice" : "Navigatie",
	"NAVHistory" : "Navigatie",
	"NAVItemList" : "Navigatie",
	"NAVMap" : "Navigatie",
	"NAVMecca" : "Navigatie",
	"NAVModifyPoint" : "Navigatie",
	"NAVNavigationInfo" : "Navigatie",
	"NAVNewDestination" : "Navigatie",
	"NAVPOI" : "Navigatie",
	"NAVPhoneZipSearch" : "Navigatie",
	"NAVPointOnMap" : "Navigatie",
	"NAVQuickSearch" : "Navigatie",
	"NAVResults" : "Navigatie",
	"NAVRoute" : "Navigatie",
	"NAVSettings" : "Navigatie",
	"NAVSimulation" : "Navigatie",
	"NAVSortingOptions" : "Navigatie",
	"NAVTraffic" : "Navigatie",
	"NAVTurnByTurn" : "Navigatie",
	"NAVVoicePrompts" : "Navigatie",
	"NAVWeather" : "Navigatie",
	"NoNavigation" : "Uw Mazda is niet uitgerust met een navigatiesysteem. Een geïntegreerd systeem is verkrijgbaar bij uw Mazda-dealer als originele Mazda Accessoire.",
	"S" : "{value} Z",
	"SDCardInvalid" : "Ongeldige SD-kaart",
	"SDCradInserted" : "SD-kaart ingevoerd",
	"SDCradRemoved" : "SD-kaart verwijderd",
	"VrHelp_AddCurrentLocationToFavorites" : "Huidige locatie toevoegen aan favorieten",
	"VrHelp_AddWaypointCategory" : "Waypoint toevoegen (categorie)",
	"VrHelp_ClearRoute" : "Route verwijderen",
	"VrHelp_NavigateToAnAddress" : "Navigeer naar een adres",
	"VrHelp_NavigateToRecentDestination" : "Navigeer naar recente bestemming",
	"VrHelp_NewDestination" : "Nieuwe bestemming",
	"VrHelp_RepeatInstruction" : "Instructie herhalen",
	"VrHelp_RouteSummary" : "Routesamenvatting",
	"VrHelp_TakeMeHome" : "Breng me naar huis",
	"VrHelp_WhereAmI" : "Waar ben ik",
	"W" : "{value} W",
	"Y" : "{value}{spacing}yd",
	"YourLocation" : "Uw locatie",
	"emnavi" : "Navigatie",
	"km" : "{value}{spacing}km",
	"mi" : "{value}{spacing}mi",
};

framework.registerAppDictLoaded("emnavi", "nl_NL");