var __VrHelpPositionTable__emnaviAppDict_sv_SE = {
	"Cockpit_Help2" : {
		"Right" : ["VrHelp_WhereAmI","VrHelp_RouteSummary","VrHelp_RepeatInstruction","VrHelp_AddCurrentLocationToFavorites","VrHelp_AddWaypointCategory"],
		"Left" : ["VrHelp_NewDestination","VrHelp_TakeMeHome","VrHelp_NavigateToAnAddress","VrHelp_NavigateToRecentDestination","VrHelp_ClearRoute"]
	}
};

var Localization_emnaviAppDict_sv_SE = {
	//"stringId" : "localString"
	"AddressNotFound" : "Hittade inte adressen",
	"AtSpeedCautionText" : " ",
	"Compass" : "Navigering",
	"E" : "{value} Ö",
	"Elevation" : "Höjd ö.h.",
	"FT" : "{value}{spacing}fot",
	"Latitude" : "Latitud",
	"Loading" : "Läser in navigation",
	"Longitude" : "Longitud",
	"M" : "{value}{spacing}m",
	"N" : "{value} N",
	"NAVAddressSearch" : "Navigation",
	"NAVAvoidances" : "Navigation",
	"NAVCitySearch" : "Navigation",
	"NAVCoordinate" : "Navigation",
	"NAVDragMode" : "Navigation",
	"NAVGasPrice" : "Navigation",
	"NAVHistory" : "Navigation",
	"NAVItemList" : "Navigation",
	"NAVMap" : "Navigation",
	"NAVMecca" : "Navigation",
	"NAVModifyPoint" : "Navigation",
	"NAVNavigationInfo" : "Navigation",
	"NAVNewDestination" : "Navigation",
	"NAVPOI" : "Navigation",
	"NAVPhoneZipSearch" : "Navigation",
	"NAVPointOnMap" : "Navigation",
	"NAVQuickSearch" : "Navigation",
	"NAVResults" : "Navigation",
	"NAVRoute" : "Navigation",
	"NAVSettings" : "Navigation",
	"NAVSimulation" : "Navigation",
	"NAVSortingOptions" : "Navigation",
	"NAVTraffic" : "Navigation",
	"NAVTurnByTurn" : "Navigation",
	"NAVVoicePrompts" : "Navigation",
	"NAVWeather" : "Navigation",
	"NoNavigation" : "Din Mazda är inte utrustad med navigeringssystem. Dock finns ett integrerat navigeringssystem tillgängligt via din Mazda-återförsäljare som ett äkta Mazda tillbehör.",
	"S" : "{value} S",
	"SDCardInvalid" : "Ogiltigt SD-kort",
	"SDCradInserted" : "SD-kort isatt",
	"SDCradRemoved" : "SD-kort urtaget",
	"VrHelp_AddCurrentLocationToFavorites" : "Lägg till aktuell plats bland favoriter",
	"VrHelp_AddWaypointCategory" : "Lägg till vägmärke (kategori)",
	"VrHelp_ClearRoute" : "Rensa rutt",
	"VrHelp_NavigateToAnAddress" : "Navigera till adress",
	"VrHelp_NavigateToRecentDestination" : "Navigera till senaste destination",
	"VrHelp_NewDestination" : "Ny destination",
	"VrHelp_RepeatInstruction" : "Upprepa instruktion",
	"VrHelp_RouteSummary" : "Sammanfattning av rutt",
	"VrHelp_TakeMeHome" : "Ta mig hem",
	"VrHelp_WhereAmI" : "Var är jag",
	"W" : "{value} V",
	"Y" : "{value}{spacing}yards",
	"YourLocation" : "Din plats",
	"emnavi" : "Navigation",
	"km" : "{value}{spacing}km",
	"mi" : "{value}{spacing}mi",
};

framework.registerAppDictLoaded("emnavi", "sv_SE");