var __VrHelpPositionTable__emnaviAppDict_bg_BG = {
	"Cockpit_Help2" : {
		"Right" : ["VrHelp_WhereAmI","VrHelp_RouteSummary","VrHelp_RepeatInstruction","VrHelp_AddCurrentLocationToFavorites","VrHelp_AddWaypointCategory"],
		"Left" : ["VrHelp_NewDestination","VrHelp_TakeMeHome","VrHelp_NavigateToAnAddress","VrHelp_NavigateToRecentDestination","VrHelp_ClearRoute"]
	}
};

var Localization_emnaviAppDict_bg_BG = {
	//"stringId" : "localString"
	"AddressNotFound" : "Адресът не е намерен",
	"AtSpeedCautionText" : " ",
	"Compass" : "Компас",
	"E" : "{value} И",
	"Elevation" : "Височина",
	"FT" : "{value}{spacing}фута",
	"Latitude" : "Ширина",
	"Loading" : "Зареждане на навигация",
	"Longitude" : "Дължина",
	"M" : "{value}{spacing}м",
	"N" : "{value} С",
	"NAVAddressSearch" : "Навигация",
	"NAVAvoidances" : "Навигация",
	"NAVCitySearch" : "Навигация",
	"NAVCoordinate" : "Навигация",
	"NAVDragMode" : "Навигация",
	"NAVGasPrice" : "Навигация",
	"NAVHistory" : "Навигация",
	"NAVItemList" : "Навигация",
	"NAVMap" : "Навигация",
	"NAVMecca" : "Навигация",
	"NAVModifyPoint" : "Навигация",
	"NAVNavigationInfo" : "Навигация",
	"NAVNewDestination" : "Навигация",
	"NAVPOI" : "Навигация",
	"NAVPhoneZipSearch" : "Навигация",
	"NAVPointOnMap" : "Навигация",
	"NAVQuickSearch" : "Навигация",
	"NAVResults" : "Навигация",
	"NAVRoute" : "Навигация",
	"NAVSettings" : "Навигация",
	"NAVSimulation" : "Навигация",
	"NAVSortingOptions" : "Навигация",
	"NAVTraffic" : "Навигация",
	"NAVTurnByTurn" : "Навигация",
	"NAVVoicePrompts" : "Навигация",
	"NAVWeather" : "Навигация",
	"NoNavigation" : "Вашият автомобил Mazda няма навигационна система. Вземете интегр. навиг. с-ма от дилър на Mazda.",
	"S" : "{value} Ю",
	"SDCardInvalid" : "Невалидна SD карта",
	"SDCradInserted" : "SD картата е поставена",
	"SDCradRemoved" : "SD картата е извадена",
	"VrHelp_AddCurrentLocationToFavorites" : "Add Current Location to Favorites",
	"VrHelp_AddWaypointCategory" : "Add Waypoint (category)",
	"VrHelp_ClearRoute" : "Clear Route",
	"VrHelp_NavigateToAnAddress" : "Navigate to an Address",
	"VrHelp_NavigateToRecentDestination" : "Navigate to Recent Destination",
	"VrHelp_NewDestination" : "New Destination",
	"VrHelp_RepeatInstruction" : "Repeat Instruction",
	"VrHelp_RouteSummary" : "Route Summary",
	"VrHelp_TakeMeHome" : "Take Me Home",
	"VrHelp_WhereAmI" : "Where Am I",
	"W" : "{value} З",
	"Y" : "{value}{spacing}ярда",
	"YourLocation" : "Вашето местопл.",
	"emnavi" : "Навигация",
	"km" : "{value}{spacing}км",
	"mi" : "{value}{spacing}mi",
};

framework.registerAppDictLoaded("emnavi", "bg_BG");