var __VrHelpPositionTable__emnaviAppDict_de_DE = {
	"Cockpit_Help2" : {
		"Right" : ["VrHelp_WhereAmI","VrHelp_RouteSummary","VrHelp_RepeatInstruction","VrHelp_AddCurrentLocationToFavorites","VrHelp_AddWaypointCategory"],
		"Left" : ["VrHelp_NewDestination","VrHelp_TakeMeHome","VrHelp_NavigateToAnAddress","VrHelp_NavigateToRecentDestination","VrHelp_ClearRoute"]
	}
};

var Localization_emnaviAppDict_de_DE = {
	//"stringId" : "localString"
	"AddressNotFound" : "Adresse nicht gefunden",
	"AtSpeedCautionText" : " ",
	"Compass" : "Kompass",
	"E" : "{value} O",
	"Elevation" : "Erhebung",
	"FT" : "{value}{spacing}ft",
	"Latitude" : "Breitengrad",
	"Loading" : "Navigation wird geladen",
	"Longitude" : "Längengrad",
	"M" : "{value}{spacing}m",
	"N" : "{value} N",
	"NAVAddressSearch" : "Navigation",
	"NAVAvoidances" : "Navigation",
	"NAVCitySearch" : "Navigation",
	"NAVCoordinate" : "Navigation",
	"NAVDragMode" : "Navigation",
	"NAVGasPrice" : "Navigation",
	"NAVHistory" : "Navigation",
	"NAVItemList" : "Navigation",
	"NAVMap" : "Navigation",
	"NAVMecca" : "Navigation",
	"NAVModifyPoint" : "Navigation",
	"NAVNavigationInfo" : "Navigation",
	"NAVNewDestination" : "Navigation",
	"NAVPOI" : "Navigation",
	"NAVPhoneZipSearch" : "Navigation",
	"NAVPointOnMap" : "Navigation",
	"NAVQuickSearch" : "Navigation",
	"NAVResults" : "Navigation",
	"NAVRoute" : "Navigation",
	"NAVSettings" : "Navigation",
	"NAVSimulation" : "Navigation",
	"NAVSortingOptions" : "Navigation",
	"NAVTraffic" : "Navigation",
	"NAVTurnByTurn" : "Navigation",
	"NAVVoicePrompts" : "Navigation",
	"NAVWeather" : "Navigation",
	"NoNavigation" : "Ihr Mazda verfügt über kein Navigationssyst. Bei Ihrem Mazda Händler ist ein integr. Navigationssyst. als Orig.-Zubehör erhältlich.",
	"S" : "{value} S",
	"SDCardInvalid" : "Ungültige SD-Karte",
	"SDCradInserted" : "SD-Karte eingefügt",
	"SDCradRemoved" : "SD-Karte entfernt",
	"VrHelp_AddCurrentLocationToFavorites" : "Aktueller Standort zu Favoriten hinzufügen",
	"VrHelp_AddWaypointCategory" : "(Kategorie) als Wegpunkt hinzufügen",
	"VrHelp_ClearRoute" : "Route löschen",
	"VrHelp_NavigateToAnAddress" : "Leite mich zu dieser Adresse",
	"VrHelp_NavigateToRecentDestination" : "Leite mich zu einem vorherigen Ziel",
	"VrHelp_NewDestination" : "Neues Ziel",
	"VrHelp_RepeatInstruction" : "Anweisung wiederholen",
	"VrHelp_RouteSummary" : "Routen-Zusammenf.",
	"VrHelp_TakeMeHome" : "Bring mich nach hause",
	"VrHelp_WhereAmI" : "Wo bin ich",
	"W" : "{value} W",
	"Y" : "{value}{spacing}yd",
	"YourLocation" : "Ihr Standort",
	"emnavi" : "Navigation",
	"km" : "{value}{spacing}km",
	"mi" : "{value}{spacing}mi",
};

framework.registerAppDictLoaded("emnavi", "de_DE");