var __VrHelpPositionTable__emnaviAppDict_ru_RU = {
	"Cockpit_Help2" : {
		"Right" : ["VrHelp_WhereAmI","VrHelp_RouteSummary","VrHelp_RepeatInstruction","VrHelp_AddCurrentLocationToFavorites","VrHelp_AddWaypointCategory"],
		"Left" : ["VrHelp_NewDestination","VrHelp_TakeMeHome","VrHelp_NavigateToAnAddress","VrHelp_NavigateToRecentDestination","VrHelp_ClearRoute"]
	}
};

var Localization_emnaviAppDict_ru_RU = {
	//"stringId" : "localString"
	"AddressNotFound" : "Адрес не найден",
	"AtSpeedCautionText" : " ",
	"Compass" : "Компас",
	"E" : "{value} В",
	"Elevation" : "Высота",
	"FT" : "{value}{spacing}фт",
	"Latitude" : "Широта",
	"Loading" : "Загрузка навигации",
	"Longitude" : "Долгота",
	"M" : "{value}{spacing}м",
	"N" : "{value} С",
	"NAVAddressSearch" : "Навигация",
	"NAVAvoidances" : "Навигация",
	"NAVCitySearch" : "Навигация",
	"NAVCoordinate" : "Навигация",
	"NAVDragMode" : "Навигация",
	"NAVGasPrice" : "Цена бензина",
	"NAVHistory" : "Навигация",
	"NAVItemList" : "Навигация",
	"NAVMap" : "Навигация",
	"NAVMecca" : "Навигация",
	"NAVModifyPoint" : "Навигация",
	"NAVNavigationInfo" : "Навигация",
	"NAVNewDestination" : "Навигация",
	"NAVPOI" : "Навигация",
	"NAVPhoneZipSearch" : "Навигация",
	"NAVPointOnMap" : "Навигация",
	"NAVQuickSearch" : "Навигация",
	"NAVResults" : "Навигация",
	"NAVRoute" : "Навигация",
	"NAVSettings" : "Навигация",
	"NAVSimulation" : "Навигация",
	"NAVSortingOptions" : "Навигация",
	"NAVTraffic" : "Навигация",
	"NAVTurnByTurn" : "Навигация",
	"NAVVoicePrompts" : "Навигация",
	"NAVWeather" : "Навигация",
	"NoNavigation" : "Ваш а/м Mazda не оснащен навигац. системой. Вы можете приобрести данную систему в качестве оригинального аксессуара Mazda у Вашего дилера Mazda.",
	"S" : "{value} Ю",
	"SDCardInvalid" : "Неверная SD-карта",
	"SDCradInserted" : "SD-карта вставлена",
	"SDCradRemoved" : "SD-карта извлечена",
	"VrHelp_AddCurrentLocationToFavorites" : "Добавить текущее местоположение в избранное",
	"VrHelp_AddWaypointCategory" : "Добавить точку маршрута (категорию)",
	"VrHelp_ClearRoute" : "Очистить маршрут",
	"VrHelp_NavigateToAnAddress" : "Ехать по адресу",
	"VrHelp_NavigateToRecentDestination" : "Ехать к последнему пункту назначения",
	"VrHelp_NewDestination" : "Новый пункт назначения",
	"VrHelp_RepeatInstruction" : "Повторить инструкцию",
	"VrHelp_RouteSummary" : "Краткая информация по маршруту",
	"VrHelp_TakeMeHome" : "Ехать домой",
	"VrHelp_WhereAmI" : "Где я",
	"W" : "{value} З",
	"Y" : "{value}{spacing}ярд",
	"YourLocation" : "Ваше мест-ние",
	"emnavi" : "Навигация",
	"km" : "{value}{spacing}км",
	"mi" : "{value}{spacing}ми",
};

framework.registerAppDictLoaded("emnavi", "ru_RU");