var __VrHelpPositionTable__emnaviAppDict_cs_CS = {
	"Cockpit_Help2" : {
		"Right" : ["VrHelp_WhereAmI","VrHelp_RouteSummary","VrHelp_RepeatInstruction","VrHelp_AddCurrentLocationToFavorites","VrHelp_AddWaypointCategory"],
		"Left" : ["VrHelp_NewDestination","VrHelp_TakeMeHome","VrHelp_NavigateToAnAddress","VrHelp_NavigateToRecentDestination","VrHelp_ClearRoute"]
	}
};

var Localization_emnaviAppDict_cs_CS = {
	//"stringId" : "localString"
	"AddressNotFound" : "Adresa nenalezena",
	"AtSpeedCautionText" : "JAPAN ONLY",
	"Compass" : "Kompas",
	"E" : "{value} V",
	"Elevation" : "Nadmoř. Výška",
	"FT" : "{value}{spacing}ft",
	"Latitude" : "Zem. šířka",
	"Loading" : "Nahrávání navigace",
	"Longitude" : "Zeměp. délka",
	"M" : "{value}{spacing}m",
	"N" : "{value} S",
	"NAVAddressSearch" : "Navigace",
	"NAVAvoidances" : "Navigace",
	"NAVCitySearch" : "Navigace",
	"NAVCoordinate" : "Navigace",
	"NAVDragMode" : "Navigace",
	"NAVGasPrice" : "Navigace",
	"NAVHistory" : "Navigace",
	"NAVItemList" : "Navigace",
	"NAVMap" : "Navigace",
	"NAVMecca" : "Navigace",
	"NAVModifyPoint" : "Navigace",
	"NAVNavigationInfo" : "Navigace",
	"NAVNewDestination" : "Navigace",
	"NAVPOI" : "Navigace",
	"NAVPhoneZipSearch" : "Navigace",
	"NAVPointOnMap" : "Navigace",
	"NAVQuickSearch" : "Navigace",
	"NAVResults" : "Navigace",
	"NAVRoute" : "Navigace",
	"NAVSettings" : "Navigace",
	"NAVSimulation" : "Navigace",
	"NAVSortingOptions" : "Navigace",
	"NAVTraffic" : "Navigace",
	"NAVTurnByTurn" : "Navigace",
	"NAVVoicePrompts" : "Navigace",
	"NAVWeather" : "Navigace",
	"NoNavigation" : "Tato Mazda není vybavena navigaci. Navigační systém lze dokoupit u kteréhokoli  dealera Mazda jako dodatečné příslušenství.",
	"S" : "{value} J",
	"SDCardInvalid" : "Chybná karta SD",
	"SDCradInserted" : "Karta SD vložena",
	"SDCradRemoved" : "Karta SD odebrána",
	"VrHelp_AddCurrentLocationToFavorites" : "Add Current Location to Favorites",
	"VrHelp_AddWaypointCategory" : "Add Waypoint (category)",
	"VrHelp_ClearRoute" : "Clear Route",
	"VrHelp_NavigateToAnAddress" : "Navigate to an Address",
	"VrHelp_NavigateToRecentDestination" : "Navigate to Recent Destination",
	"VrHelp_NewDestination" : "New Destination",
	"VrHelp_RepeatInstruction" : "Repeat Instruction",
	"VrHelp_RouteSummary" : "Route Summary",
	"VrHelp_TakeMeHome" : "Take Me Home",
	"VrHelp_WhereAmI" : "Where Am I",
	"W" : "{value} Z",
	"Y" : "{value}{spacing}yd",
	"YourLocation" : "Vaše poloha",
	"emnavi" : "Navigace",
	"km" : "{value}{spacing}km",
	"mi" : "{value}{spacing}mi",
};

framework.registerAppDictLoaded("emnavi", "cs_CS");