var __VrHelpPositionTable__emnaviAppDict_no_NO = {
	"Cockpit_Help2" : {
		"Right" : ["VrHelp_WhereAmI","VrHelp_RouteSummary","VrHelp_RepeatInstruction","VrHelp_AddCurrentLocationToFavorites","VrHelp_AddWaypointCategory"],
		"Left" : ["VrHelp_NewDestination","VrHelp_TakeMeHome","VrHelp_NavigateToAnAddress","VrHelp_NavigateToRecentDestination","VrHelp_ClearRoute"]
	}
};

var Localization_emnaviAppDict_no_NO = {
	//"stringId" : "localString"
	"AddressNotFound" : "Adressen finnes ikke",
	"AtSpeedCautionText" : " ",
	"Compass" : "Kompass",
	"E" : "{value} Ø",
	"Elevation" : "Høyde",
	"FT" : "{value}{spacing}fot",
	"Latitude" : "Breddegrad",
	"Loading" : "Laster navigering",
	"Longitude" : "Lengdegrad",
	"M" : "{value}{spacing}m",
	"N" : "{value} N",
	"NAVAddressSearch" : "Navigering",
	"NAVAvoidances" : "Navigering",
	"NAVCitySearch" : "Navigering",
	"NAVCoordinate" : "Navigering",
	"NAVDragMode" : "Navigering",
	"NAVGasPrice" : "Navigering",
	"NAVHistory" : "Navigering",
	"NAVItemList" : "Navigering",
	"NAVMap" : "Navigering",
	"NAVMecca" : "Navigering",
	"NAVModifyPoint" : "Navigering",
	"NAVNavigationInfo" : "Navigering",
	"NAVNewDestination" : "Navigering",
	"NAVPOI" : "Navigering",
	"NAVPhoneZipSearch" : "Navigering",
	"NAVPointOnMap" : "Navigering",
	"NAVQuickSearch" : "Navigering",
	"NAVResults" : "Navigering",
	"NAVRoute" : "Navigering",
	"NAVSettings" : "Navigering",
	"NAVSimulation" : "Navigering",
	"NAVSortingOptions" : "Navigering",
	"NAVTraffic" : "Navigering",
	"NAVTurnByTurn" : "Navigering",
	"NAVVoicePrompts" : "Navigering",
	"NAVWeather" : "Navigering",
	"NoNavigation" : "Din Mazda er ikke utstyrt med et navigasjon. Navigasjonssystem kan ettermonteres av en Mazda-forhandler.",
	"S" : "{value} S",
	"SDCardInvalid" : "Ugyldig SD-kort",
	"SDCradInserted" : "SD-kort er satt inn",
	"SDCradRemoved" : "SD-kort er fjernet",
	"VrHelp_AddCurrentLocationToFavorites" : "Add Current Location to Favorites",
	"VrHelp_AddWaypointCategory" : "Add Waypoint (category)",
	"VrHelp_ClearRoute" : "Clear Route",
	"VrHelp_NavigateToAnAddress" : "Navigate to an Address",
	"VrHelp_NavigateToRecentDestination" : "Navigate to Recent Destination",
	"VrHelp_NewDestination" : "New Destination",
	"VrHelp_RepeatInstruction" : "Repeat Instruction",
	"VrHelp_RouteSummary" : "Route Summary",
	"VrHelp_TakeMeHome" : "Take Me Home",
	"VrHelp_WhereAmI" : "Where Am I",
	"W" : "{value} V",
	"Y" : "{value}{spacing}yd",
	"YourLocation" : "Din plassering",
	"emnavi" : "Navigering",
	"km" : "{value}{spacing}km",
	"mi" : "{value}{spacing}mi",
};

framework.registerAppDictLoaded("emnavi", "no_NO");