var __VrHelpPositionTable__emnaviAppDict_et_EE = {
	"Cockpit_Help2" : {
		"Right" : ["VrHelp_WhereAmI","VrHelp_RouteSummary","VrHelp_RepeatInstruction","VrHelp_AddCurrentLocationToFavorites","VrHelp_AddWaypointCategory"],
		"Left" : ["VrHelp_NewDestination","VrHelp_TakeMeHome","VrHelp_NavigateToAnAddress","VrHelp_NavigateToRecentDestination","VrHelp_ClearRoute"]
	}
};

var Localization_emnaviAppDict_et_EE = {
	//"stringId" : "localString"
	"AddressNotFound" : "Aadressi ei leitud",
	"AtSpeedCautionText" : " ",
	"Compass" : "Kompass",
	"E" : "{value} E",
	"Elevation" : "Kõrgus",
	"FT" : "{value}{spacing}jalga",
	"Latitude" : "Laiuskraad",
	"Loading" : "Navigatsiooni laadimine",
	"Longitude" : "Pikkuskraad",
	"M" : "{value}{spacing}m",
	"N" : "{value} N",
	"NAVAddressSearch" : "Navigatsioon",
	"NAVAvoidances" : "Navigatsioon",
	"NAVCitySearch" : "Navigatsioon",
	"NAVCoordinate" : "Navigatsioon",
	"NAVDragMode" : "Navigatsioon",
	"NAVGasPrice" : "Navigatsioon",
	"NAVHistory" : "Navigatsioon",
	"NAVItemList" : "Navigatsioon",
	"NAVMap" : "Navigatsioon",
	"NAVMecca" : "Navigatsioon",
	"NAVModifyPoint" : "Navigatsioon",
	"NAVNavigationInfo" : "Navigatsioon",
	"NAVNewDestination" : "Navigatsioon",
	"NAVPOI" : "Navigatsioon",
	"NAVPhoneZipSearch" : "Navigatsioon",
	"NAVPointOnMap" : "Navigatsioon",
	"NAVQuickSearch" : "Navigatsioon",
	"NAVResults" : "Navigatsioon",
	"NAVRoute" : "Navigatsioon",
	"NAVSettings" : "Navigatsioon",
	"NAVSimulation" : "Navigatsioon",
	"NAVSortingOptions" : "Navigatsioon",
	"NAVTraffic" : "Navigatsioon",
	"NAVTurnByTurn" : "Navigatsioon",
	"NAVVoicePrompts" : "Navigatsioon",
	"NAVWeather" : "Navigatsioon",
	"NoNavigation" : "Teie Mazda pole navigatsioonisüsteemi. Navigatsioonisüsteem on saadaval Mazda originaalvarustusena kohalikust Mazda esindusest.",
	"S" : "{value} S",
	"SDCardInvalid" : "Vale SD-kaart",
	"SDCradInserted" : "Sisestati SD-kaart",
	"SDCradRemoved" : "Eemaldati SD-kaart",
	"VrHelp_AddCurrentLocationToFavorites" : "Add Current Location to Favorites",
	"VrHelp_AddWaypointCategory" : "Add Waypoint (category)",
	"VrHelp_ClearRoute" : "Clear Route",
	"VrHelp_NavigateToAnAddress" : "Navigate to an Address",
	"VrHelp_NavigateToRecentDestination" : "Navigate to Recent Destination",
	"VrHelp_NewDestination" : "New Destination",
	"VrHelp_RepeatInstruction" : "Repeat Instruction",
	"VrHelp_RouteSummary" : "Route Summary",
	"VrHelp_TakeMeHome" : "Take Me Home",
	"VrHelp_WhereAmI" : "Where Am I",
	"W" : "{value} W",
	"Y" : "{value}{spacing}jardi",
	"YourLocation" : "Teie asukoht",
	"emnavi" : "Navigatsioon",
	"km" : "{value}{spacing}km",
	"mi" : "{value}{spacing}mi",
};

framework.registerAppDictLoaded("emnavi", "et_EE");