var __VrHelpPositionTable__emnaviAppDict_es_MX = {
	"Cockpit_Help2" : {
		"Right" : ["VrHelp_WhereAmI","VrHelp_RouteSummary","VrHelp_RepeatInstruction","VrHelp_AddCurrentLocationToFavorites","VrHelp_AddWaypointCategory"],
		"Left" : ["VrHelp_NewDestination","VrHelp_TakeMeHome","VrHelp_NavigateToAnAddress","VrHelp_NavigateToRecentDestination","VrHelp_ClearRoute"]
	}
};

var Localization_emnaviAppDict_es_MX = {
	//"stringId" : "localString"
	"AddressNotFound" : "Dirección No Encontrada",
	"AtSpeedCautionText" : " ",
	"Compass" : "Brújula",
	"E" : "{value} E",
	"Elevation" : "Altitud",
	"FT" : "{value}{spacing}piés",
	"Latitude" : "Latitud ",
	"Loading" : "Cargando Navegación",
	"Longitude" : "Longitud ",
	"M" : "{value}{spacing}m",
	"N" : "{value} N",
	"NAVAddressSearch" : "Navegación",
	"NAVAvoidances" : "Navegación",
	"NAVCitySearch" : "Navegación",
	"NAVCoordinate" : "Navegación",
	"NAVDragMode" : "Navegación",
	"NAVGasPrice" : "Navegación",
	"NAVHistory" : "Navegación",
	"NAVItemList" : "Navegación",
	"NAVMap" : "Navegación",
	"NAVMecca" : "Navegación",
	"NAVModifyPoint" : "Navegación",
	"NAVNavigationInfo" : "Navegación",
	"NAVNewDestination" : "Navegación",
	"NAVPOI" : "Navegación",
	"NAVPhoneZipSearch" : "Navegación",
	"NAVPointOnMap" : "Navegación",
	"NAVQuickSearch" : "Navegación",
	"NAVResults" : "Navegación",
	"NAVRoute" : "Navegación",
	"NAVSettings" : "Navegación",
	"NAVSimulation" : "Navegación",
	"NAVSortingOptions" : "Navegación",
	"NAVTraffic" : "Navegación",
	"NAVTurnByTurn" : "Navegación",
	"NAVVoicePrompts" : "Navegación",
	"NAVWeather" : "Navegación",
	"NoNavigation" : "Su Mazda no está equipado con sistema de navegación. Hay disponible un sistema de navegación integrado como Accesorio Genuino Mazda. Consulte distribuidor oficial Mazda.",
	"S" : "{value} S",
	"SDCardInvalid" : "Tarjeta SD no Válida",
	"SDCradInserted" : "Tarjeta SD Insertada",
	"SDCradRemoved" : "Tarjeta SD Extraida",
	"VrHelp_AddCurrentLocationToFavorites" : "Añadir ubicación actual a favoritos",
	"VrHelp_AddWaypointCategory" : "Añadir waypoint (categoría)",
	"VrHelp_ClearRoute" : "Despejar ruta",
	"VrHelp_NavigateToAnAddress" : "Navegar a una dirección",
	"VrHelp_NavigateToRecentDestination" : "Navegar a un destino reciente",
	"VrHelp_NewDestination" : "Nuevo destino",
	"VrHelp_RepeatInstruction" : "Repetir instrucción",
	"VrHelp_RouteSummary" : "Resumen de ruta",
	"VrHelp_TakeMeHome" : "Llévame a casa",
	"VrHelp_WhereAmI" : "Dónde estoy",
	"W" : "{value} O",
	"Y" : "{value}{spacing}yardas",
	"YourLocation" : "Su Ubicación",
	"emnavi" : "Navegación",
	"km" : "{value}{spacing}km",
	"mi" : "{value}{spacing}mi",
};

framework.registerAppDictLoaded("emnavi", "es_MX");