var __VrHelpPositionTable__emnaviAppDict_zh_CN = {
	"Cockpit_Help2" : {
		"Right" : ["VrHelp_WhereAmI","VrHelp_RouteSummary","VrHelp_RepeatInstruction","VrHelp_AddCurrentLocationToFavorites","VrHelp_AddWaypointCategory"],
		"Left" : ["VrHelp_NewDestination","VrHelp_TakeMeHome","VrHelp_NavigateToAnAddress","VrHelp_NavigateToRecentDestination","VrHelp_ClearRoute"]
	}
};

var Localization_emnaviAppDict_zh_CN = {
	//"stringId" : "localString"
	"AddressNotFound" : "未找到地址",
	"AtSpeedCautionText" : "",
	"Compass" : "指南针",
	"E" : "{value} 东",
	"Elevation" : "海拔",
	"FT" : "{value}{spacing}英尺",
	"Latitude" : "纬度",
	"Loading" : "正在加载导航",
	"Longitude" : "经度",
	"M" : "{value}{spacing}米",
	"N" : "{value} 北",
	"NAVAddressSearch" : "导航",
	"NAVAvoidances" : "导航",
	"NAVCitySearch" : "导航",
	"NAVCoordinate" : "导航",
	"NAVDragMode" : "导航",
	"NAVGasPrice" : "导航",
	"NAVHistory" : "导航",
	"NAVItemList" : "导航",
	"NAVMap" : "导航",
	"NAVMecca" : "导航",
	"NAVModifyPoint" : "导航",
	"NAVNavigationInfo" : "导航",
	"NAVNewDestination" : "导航",
	"NAVPOI" : "导航",
	"NAVPhoneZipSearch" : "导航",
	"NAVPointOnMap" : "导航",
	"NAVQuickSearch" : "导航",
	"NAVResults" : "导航",
	"NAVRoute" : "导航",
	"NAVSettings" : "导航",
	"NAVSimulation" : "导航",
	"NAVSortingOptions" : "导航",
	"NAVTraffic" : "导航",
	"NAVTurnByTurn" : "导航",
	"NAVVoicePrompts" : "导航",
	"NAVWeather" : "导航",
	"NoNavigation" : "您的Mazda未配备导航系统。但通过您的Mazda经销商可获得作为真品Mazda附件提供的集成导航系统。",
	"S" : "{value} 南",
	"SDCardInvalid" : "SD卡无效",
	"SDCradInserted" : "SD卡已插入",
	"SDCradRemoved" : "SD卡已取出",
	"VrHelp_AddCurrentLocationToFavorites" : "将当前位置添加到收藏夹",
	"VrHelp_AddWaypointCategory" : "添加路标（类别）",
	"VrHelp_ClearRoute" : "清除路线",
	"VrHelp_NavigateToAnAddress" : "导航到地址",
	"VrHelp_NavigateToRecentDestination" : "导航到最近目的地",
	"VrHelp_NewDestination" : "新目的地",
	"VrHelp_RepeatInstruction" : "重复指令",
	"VrHelp_RouteSummary" : "路线概览",
	"VrHelp_TakeMeHome" : "将我带到家",
	"VrHelp_WhereAmI" : "我在哪儿",
	"W" : "{value} 西",
	"Y" : "{value}{spacing}码",
	"YourLocation" : "您的位置",
	"emnavi" : "导航",
	"km" : "{value}{spacing}公里",
	"mi" : "{value}{spacing}英里",
};

framework.registerAppDictLoaded("emnavi", "zh_CN");