var __VrHelpPositionTable__emnaviAppDict_ja_JP = {
	"Cockpit_Help2" : {
		"Right" : ["VrHelp_WhereAmI","VrHelp_RouteSummary","VrHelp_RepeatInstruction","VrHelp_AddCurrentLocationToFavorites","VrHelp_AddWaypointCategory"],
		"Left" : ["VrHelp_NewDestination","VrHelp_TakeMeHome","VrHelp_NavigateToAnAddress","VrHelp_NavigateToRecentDestination","VrHelp_ClearRoute"]
	}
};

var Localization_emnaviAppDict_ja_JP = {
	//"stringId" : "localString"
	"AddressNotFound" : "住所が見つかりません。",
	"AtSpeedCautionText" : "走行中は音声のみでお楽しみ下さい\n",
	"Compass" : "Navigation",
	"E" : "{value} E",
	"Elevation" : "高度",
	"FT" : "{value}{spacing}ft",
	"Latitude" : "緯度",
	"Loading" : "ナビゲーション起動中",
	"Longitude" : "経度",
	"M" : "{value}{spacing}m",
	"N" : "{value} N",
	"NAVAddressSearch" : "Navigation",
	"NAVAvoidances" : "Navigation",
	"NAVCitySearch" : "Navigation",
	"NAVCoordinate" : "Navigation",
	"NAVDragMode" : "Navigation",
	"NAVGasPrice" : "Navigation",
	"NAVHistory" : "Navigation",
	"NAVItemList" : "Navigation",
	"NAVMap" : "Navigation",
	"NAVMecca" : "Navigation",
	"NAVModifyPoint" : "Navigation",
	"NAVNavigationInfo" : "Navigation",
	"NAVNewDestination" : "Navigation",
	"NAVPOI" : "Navigation",
	"NAVPhoneZipSearch" : "Navigation",
	"NAVPointOnMap" : "Navigation",
	"NAVQuickSearch" : "Navigation",
	"NAVResults" : "Navigation",
	"NAVRoute" : "Navigation",
	"NAVSettings" : "Navigation",
	"NAVSimulation" : "Navigation",
	"NAVSortingOptions" : "Navigation",
	"NAVTraffic" : "Navigation",
	"NAVTurnByTurn" : "Navigation",
	"NAVVoicePrompts" : "Navigation",
	"NAVWeather" : "Navigation",
	"NoNavigation" : "ナビゲーションシステムを利用できません。\n純正ナビゲーションシステム専用の\nSDカードを装着してください。",
	"S" : "{value} S",
	"SDCardInvalid" : "Invalid SD Card",
	"SDCradInserted" : "SD Card Inserted",
	"SDCradRemoved" : "SD Card Removed",
	"VrHelp_AddCurrentLocationToFavorites" : "現在の位置をお気に入りに追加",
	"VrHelp_AddWaypointCategory" : "経由地に追加",
	"VrHelp_ClearRoute" : "ルートの削除",
	"VrHelp_NavigateToAnAddress" : "指定する住所までナビゲート",
	"VrHelp_NavigateToRecentDestination" : "最近の目的地までナビゲート",
	"VrHelp_NewDestination" : "新しい目的地",
	"VrHelp_RepeatInstruction" : "道順をリピート",
	"VrHelp_RouteSummary" : "ルート情報",
	"VrHelp_TakeMeHome" : "自宅に帰る",
	"VrHelp_WhereAmI" : "現在地",
	"W" : "{value} W",
	"Y" : "{value}{spacing}yd",
	"YourLocation" : "現在地",
	"emnavi" : "Navigation",
	"km" : "{value}{spacing}km",
	"mi" : "{value}{spacing}mi",
};

framework.registerAppDictLoaded("emnavi", "ja_JP");