var __VrHelpPositionTable__emnaviAppDict_lt_LT = {
	"Cockpit_Help2" : {
		"Right" : ["VrHelp_WhereAmI","VrHelp_RouteSummary","VrHelp_RepeatInstruction","VrHelp_AddCurrentLocationToFavorites","VrHelp_AddWaypointCategory"],
		"Left" : ["VrHelp_NewDestination","VrHelp_TakeMeHome","VrHelp_NavigateToAnAddress","VrHelp_NavigateToRecentDestination","VrHelp_ClearRoute"]
	}
};

var Localization_emnaviAppDict_lt_LT = {
	//"stringId" : "localString"
	"AddressNotFound" : "Adresas nerastas",
	"AtSpeedCautionText" : " ",
	"Compass" : "Kompasas",
	"E" : "{value} R",
	"Elevation" : "Aukštis",
	"FT" : "{value}{spacing}pėdos",
	"Latitude" : "Platuma",
	"Loading" : "Įkeliama navigacija",
	"Longitude" : "Ilguma",
	"M" : "{value}{spacing}m",
	"N" : "{value} Š",
	"NAVAddressSearch" : "Navigacija",
	"NAVAvoidances" : "Navigacija",
	"NAVCitySearch" : "Navigacija",
	"NAVCoordinate" : "Navigacija",
	"NAVDragMode" : "Navigacija",
	"NAVGasPrice" : "Navigacija",
	"NAVHistory" : "Navigacija",
	"NAVItemList" : "Navigacija",
	"NAVMap" : "Navigacija",
	"NAVMecca" : "Navigacija",
	"NAVModifyPoint" : "Navigacija",
	"NAVNavigationInfo" : "Navigacija",
	"NAVNewDestination" : "Navigacija",
	"NAVPOI" : "Navigacija",
	"NAVPhoneZipSearch" : "Navigacija",
	"NAVPointOnMap" : "Navigacija",
	"NAVQuickSearch" : "Navigacija",
	"NAVResults" : "Navigacija",
	"NAVRoute" : "Navigacija",
	"NAVSettings" : "Navigacija",
	"NAVSimulation" : "Navigacija",
	"NAVSortingOptions" : "Navigacija",
	"NAVTraffic" : "Navigacija",
	"NAVTurnByTurn" : "Navigacija",
	"NAVVoicePrompts" : "Navigacija",
	"NAVWeather" : "Navigacija",
	"NoNavigation" : "Jūsų Mazda nėra navigavimo sistemos. Tačiau integruojamą navigavimo sistemą (originalų Mazda priedą) galite įsigyti iš savo Mazda prekybos atstovo.",
	"S" : "{value} P",
	"SDCardInvalid" : "Netinkama SD kortelė",
	"SDCradInserted" : "Įdėta SD kortelė",
	"SDCradRemoved" : "Išimta SD kortelė",
	"VrHelp_AddCurrentLocationToFavorites" : "Add Current Location to Favorites",
	"VrHelp_AddWaypointCategory" : "Add Waypoint (category)",
	"VrHelp_ClearRoute" : "Clear Route",
	"VrHelp_NavigateToAnAddress" : "Navigate to an Address",
	"VrHelp_NavigateToRecentDestination" : "Navigate to Recent Destination",
	"VrHelp_NewDestination" : "New Destination",
	"VrHelp_RepeatInstruction" : "Repeat Instruction",
	"VrHelp_RouteSummary" : "Route Summary",
	"VrHelp_TakeMeHome" : "Take Me Home",
	"VrHelp_WhereAmI" : "Where Am I",
	"W" : "{value} V",
	"Y" : "{value}{spacing}jard",
	"YourLocation" : "Jūsų buvimo vieta",
	"emnavi" : "Navigacija",
	"km" : "{value}{spacing}km",
	"mi" : "{value}{spacing}mi",
};

framework.registerAppDictLoaded("emnavi", "lt_LT");