var __VrHelpPositionTable__emnaviAppDict_hr_HR = {
	"Cockpit_Help2" : {
		"Right" : ["VrHelp_WhereAmI","VrHelp_RouteSummary","VrHelp_RepeatInstruction","VrHelp_AddCurrentLocationToFavorites","VrHelp_AddWaypointCategory"],
		"Left" : ["VrHelp_NewDestination","VrHelp_TakeMeHome","VrHelp_NavigateToAnAddress","VrHelp_NavigateToRecentDestination","VrHelp_ClearRoute"]
	}
};

var Localization_emnaviAppDict_hr_HR = {
	//"stringId" : "localString"
	"AddressNotFound" : "Adresa nije pronađena",
	"AtSpeedCautionText" : " ",
	"Compass" : "Kompas",
	"E" : "{value} I",
	"Elevation" : "Visina",
	"FT" : "{value}{spacing}st.",
	"Latitude" : "Zem. širina",
	"Loading" : "Učitavanje navigacije",
	"Longitude" : "Zem. dužina",
	"M" : "{value}{spacing}m",
	"N" : "{value}S",
	"NAVAddressSearch" : "Navigacija",
	"NAVAvoidances" : "Navigacija",
	"NAVCitySearch" : "Navigacija",
	"NAVCoordinate" : "Navigacija",
	"NAVDragMode" : "Navigacija",
	"NAVGasPrice" : "Navigacija",
	"NAVHistory" : "Navigacija",
	"NAVItemList" : "Navigacija",
	"NAVMap" : "Navigacija",
	"NAVMecca" : "Navigacija",
	"NAVModifyPoint" : "Navigacija",
	"NAVNavigationInfo" : "Navigacija",
	"NAVNewDestination" : "Navigacija",
	"NAVPOI" : "Navigacija",
	"NAVPhoneZipSearch" : "Navigacija",
	"NAVPointOnMap" : "Navigacija",
	"NAVQuickSearch" : "Navigacija",
	"NAVResults" : "Navigacija",
	"NAVRoute" : "Navigacija",
	"NAVSettings" : "Navigacija",
	"NAVSimulation" : "Navigacija",
	"NAVSortingOptions" : "Navigacija",
	"NAVTraffic" : "Navigacija",
	"NAVTurnByTurn" : "Navigacija",
	"NAVVoicePrompts" : "Navigacija",
	"NAVWeather" : "Navigacija",
	"NoNavigation" : "Vaša Mazda nije opremljena navigacijskim sustavom. Kod vašeg Mazda partnera možete nabaviti originalni Mazda navigacijski sustav.",
	"S" : "{value} J",
	"SDCardInvalid" : "Neispravna SD kartica",
	"SDCradInserted" : "SD kartica umetnuta",
	"SDCradRemoved" : "SD kartica izvađena",
	"VrHelp_AddCurrentLocationToFavorites" : "Add Current Location to Favorites",
	"VrHelp_AddWaypointCategory" : "Add Waypoint (category)",
	"VrHelp_ClearRoute" : "Clear Route",
	"VrHelp_NavigateToAnAddress" : "Navigate to an Address",
	"VrHelp_NavigateToRecentDestination" : "Navigate to Recent Destination",
	"VrHelp_NewDestination" : "New Destination",
	"VrHelp_RepeatInstruction" : "Repeat Instruction",
	"VrHelp_RouteSummary" : "Route Summary",
	"VrHelp_TakeMeHome" : "Take Me Home",
	"VrHelp_WhereAmI" : "Where Am I",
	"W" : "{value} Z",
	"Y" : "{value}{spacing}yd",
	"YourLocation" : "Vaša lokacija",
	"emnavi" : "Navigacija",
	"km" : "{value}{spacing}km",
	"mi" : "{value}{spacing}mi",
};

framework.registerAppDictLoaded("emnavi", "hr_HR");