var __VrHelpPositionTable__emnaviAppDict_pt_PT = {
	"Cockpit_Help2" : {
		"Right" : ["VrHelp_WhereAmI","VrHelp_RouteSummary","VrHelp_RepeatInstruction","VrHelp_AddCurrentLocationToFavorites","VrHelp_AddWaypointCategory"],
		"Left" : ["VrHelp_NewDestination","VrHelp_TakeMeHome","VrHelp_NavigateToAnAddress","VrHelp_NavigateToRecentDestination","VrHelp_ClearRoute"]
	}
};

var Localization_emnaviAppDict_pt_PT = {
	//"stringId" : "localString"
	"AddressNotFound" : "Endereço Não Encontrado",
	"AtSpeedCautionText" : " ",
	"Compass" : "Bússola",
	"E" : "{value} E",
	"Elevation" : "Elevação",
	"FT" : "{value}{spacing}pé",
	"Latitude" : "Latitude",
	"Loading" : "A Carregar Navegação",
	"Longitude" : "Longitude",
	"M" : "{value}{spacing}m",
	"N" : "{value} N",
	"NAVAddressSearch" : "Navegação",
	"NAVAvoidances" : "Navegação",
	"NAVCitySearch" : "Navegação",
	"NAVCoordinate" : "Navegação",
	"NAVDragMode" : "Navegação",
	"NAVGasPrice" : "Navegação",
	"NAVHistory" : "Navegação",
	"NAVItemList" : "Navegação",
	"NAVMap" : "Navegação",
	"NAVMecca" : "Navegação",
	"NAVModifyPoint" : "Navegação",
	"NAVNavigationInfo" : "Navegação",
	"NAVNewDestination" : "Navegação",
	"NAVPOI" : "Navegação",
	"NAVPhoneZipSearch" : "Navegação",
	"NAVPointOnMap" : "Navegação",
	"NAVQuickSearch" : "Navegação",
	"NAVResults" : "Navegação",
	"NAVRoute" : "Navegação",
	"NAVSettings" : "Navegação",
	"NAVSimulation" : "Navegação",
	"NAVSortingOptions" : "Navegação",
	"NAVTraffic" : "Navegação",
	"NAVTurnByTurn" : "Navegação",
	"NAVVoicePrompts" : "Navegação",
	"NAVWeather" : "Navegação",
	"NoNavigation" : "O Mazda não tem sistema de navegação, mas há um integrado oficial pelo concessionário local.",
	"S" : "{value} S",
	"SDCardInvalid" : "Cartão SD Inválido",
	"SDCradInserted" : "Cartão SD Inserido",
	"SDCradRemoved" : "Cartão SD Retirado",
	"VrHelp_AddCurrentLocationToFavorites" : "Adicionar localização actual aos favoritos",
	"VrHelp_AddWaypointCategory" : "Adicionar ponto de referência (categoria)",
	"VrHelp_ClearRoute" : "Limpar percurso",
	"VrHelp_NavigateToAnAddress" : "Navegar para um endereço",
	"VrHelp_NavigateToRecentDestination" : "Navegar para destino recente",
	"VrHelp_NewDestination" : "Novo destino",
	"VrHelp_RepeatInstruction" : "Repetir instrução",
	"VrHelp_RouteSummary" : "Resumo do percurso",
	"VrHelp_TakeMeHome" : "Ir para casa",
	"VrHelp_WhereAmI" : "Onde estou",
	"W" : "{value} O",
	"Y" : "{value}{spacing}jd",
	"YourLocation" : "A Sua Localização",
	"emnavi" : "Navegação",
	"km" : "{value}{spacing}km",
	"mi" : "{value}{spacing}mi",
};

framework.registerAppDictLoaded("emnavi", "pt_PT");