var __VrHelpPositionTable__emnaviAppDict_hu_HU = {
	"Cockpit_Help2" : {
		"Right" : ["VrHelp_WhereAmI","VrHelp_RouteSummary","VrHelp_RepeatInstruction","VrHelp_AddCurrentLocationToFavorites","VrHelp_AddWaypointCategory"],
		"Left" : ["VrHelp_NewDestination","VrHelp_TakeMeHome","VrHelp_NavigateToAnAddress","VrHelp_NavigateToRecentDestination","VrHelp_ClearRoute"]
	}
};

var Localization_emnaviAppDict_hu_HU = {
	//"stringId" : "localString"
	"AddressNotFound" : "Cím nem található",
	"AtSpeedCautionText" : " ",
	"Compass" : "Iránytű",
	"E" : "{value} K",
	"Elevation" : "Magasság",
	"FT" : "{value}{spacing}láb",
	"Latitude" : "Földr. Széles.",
	"Loading" : "Navigáció kártya betétele",
	"Longitude" : "Földr. Hossz.",
	"M" : "{value}{spacing}m",
	"N" : "{value} É",
	"NAVAddressSearch" : "Navigáció",
	"NAVAvoidances" : "Navigáció",
	"NAVCitySearch" : "Navigáció",
	"NAVCoordinate" : "Navigáció",
	"NAVDragMode" : "Navigáció",
	"NAVGasPrice" : "Navigáció",
	"NAVHistory" : "Navigáció",
	"NAVItemList" : "Navigáció",
	"NAVMap" : "Navigáció",
	"NAVMecca" : "Navigáció",
	"NAVModifyPoint" : "Navigáció",
	"NAVNavigationInfo" : "Navigáció",
	"NAVNewDestination" : "Navigáció",
	"NAVPOI" : "Navigáció",
	"NAVPhoneZipSearch" : "Navigáció",
	"NAVPointOnMap" : "Navigáció",
	"NAVQuickSearch" : "Navigáció",
	"NAVResults" : "Navigáció",
	"NAVRoute" : "Navigáció",
	"NAVSettings" : "Navigáció",
	"NAVSimulation" : "Navigáció",
	"NAVSortingOptions" : "Navigáció",
	"NAVTraffic" : "Navigáció",
	"NAVTurnByTurn" : "Navigáció",
	"NAVVoicePrompts" : "Navigáció",
	"NAVWeather" : "Navigáció",
	"NoNavigation" : "A Mazda nem rendelkezik navigációs rendszerrel. Ugyanakkor az integrált navigációs rendszer elérhető a Mazda kereskedőknél, mint eredeti Mazda tartozék. ",
	"S" : "{value} D",
	"SDCardInvalid" : "Érvénytelen SD-kártya",
	"SDCradInserted" : "SD-kártya behelyezve",
	"SDCradRemoved" : "SD-kártya eltávolítva",
	"VrHelp_AddCurrentLocationToFavorites" : "Add Current Location to Favorites",
	"VrHelp_AddWaypointCategory" : "Add Waypoint (category)",
	"VrHelp_ClearRoute" : "Clear Route",
	"VrHelp_NavigateToAnAddress" : "Navigate to an Address",
	"VrHelp_NavigateToRecentDestination" : "Navigate to Recent Destination",
	"VrHelp_NewDestination" : "New Destination",
	"VrHelp_RepeatInstruction" : "Repeat Instruction",
	"VrHelp_RouteSummary" : "Route Summary",
	"VrHelp_TakeMeHome" : "Take Me Home",
	"VrHelp_WhereAmI" : "Where Am I",
	"W" : "{value} Ny",
	"Y" : "{value}{spacing}yard",
	"YourLocation" : "Jelenlegi helyszín",
	"emnavi" : "Navigáció",
	"km" : "{value}{spacing}km",
	"mi" : "{value}{spacing}mi",
};

framework.registerAppDictLoaded("emnavi", "hu_HU");