var __VrHelpPositionTable__emnaviAppDict_fr_FR = {
	"Cockpit_Help2" : {
		"Right" : ["VrHelp_WhereAmI","VrHelp_RouteSummary","VrHelp_RepeatInstruction","VrHelp_AddCurrentLocationToFavorites","VrHelp_AddWaypointCategory"],
		"Left" : ["VrHelp_NewDestination","VrHelp_TakeMeHome","VrHelp_NavigateToAnAddress","VrHelp_NavigateToRecentDestination","VrHelp_ClearRoute"]
	}
};

var Localization_emnaviAppDict_fr_FR = {
	//"stringId" : "localString"
	"AddressNotFound" : "Adresse inconnue",
	"AtSpeedCautionText" : " ",
	"Compass" : "Boussole",
	"E" : "{value} E",
	"Elevation" : "Altitude",
	"FT" : "{value}{spacing}pi",
	"Latitude" : "Latitude",
	"Loading" : "Chargement de la navigation",
	"Longitude" : "Longitude",
	"M" : "{value}{spacing}m",
	"N" : "{value} N",
	"NAVAddressSearch" : "Navigation",
	"NAVAvoidances" : "Navigation",
	"NAVCitySearch" : "Navigation",
	"NAVCoordinate" : "Navigation",
	"NAVDragMode" : "Navigation",
	"NAVGasPrice" : "Navigation",
	"NAVHistory" : "Navigation",
	"NAVItemList" : "Navigation",
	"NAVMap" : "Navigation",
	"NAVMecca" : "Navigation",
	"NAVModifyPoint" : "Navigation",
	"NAVNavigationInfo" : "Navigation",
	"NAVNewDestination" : "Navigation",
	"NAVPOI" : "Navigation",
	"NAVPhoneZipSearch" : "Navigation",
	"NAVPointOnMap" : "Navigation",
	"NAVQuickSearch" : "Navigation",
	"NAVResults" : "Navigation",
	"NAVRoute" : "Navigation",
	"NAVSettings" : "Navigation",
	"NAVSimulation" : "Navigation",
	"NAVSortingOptions" : "Navigation",
	"NAVTraffic" : "Navigation",
	"NAVTurnByTurn" : "Navigation",
	"NAVVoicePrompts" : "Navigation",
	"NAVWeather" : "Navigation",
	"NoNavigation" : "Votre Mazda n'est pas équipée d'un système de navigation. Toutefois, un système de navigation intégré Mazda est disponible chez votre concessionnaire Mazda",
	"S" : "{value} S",
	"SDCardInvalid" : "Carte SD non valide",
	"SDCradInserted" : "Carte SD insérée",
	"SDCradRemoved" : "Carte SD retirée",
	"VrHelp_AddCurrentLocationToFavorites" : "Ajouter la Position Actuelle aux Favoris",
	"VrHelp_AddWaypointCategory" : "Ajouter un Point de Cheminement (catégorie)",
	"VrHelp_ClearRoute" : "Effacer l’itinéraire",
	"VrHelp_NavigateToAnAddress" : "Me Rendre à une Adresse",
	"VrHelp_NavigateToRecentDestination" : "Me Rendre à une Destination Récente",
	"VrHelp_NewDestination" : "Nouvelle Destination",
	"VrHelp_RepeatInstruction" : "Répéter l’instruction",
	"VrHelp_RouteSummary" : "Résumé de l'itinéraire",
	"VrHelp_TakeMeHome" : "Me Ramener à la Maison",
	"VrHelp_WhereAmI" : "Où Suis-je",
	"W" : "{value} O",
	"Y" : "{value}{spacing}yd",
	"YourLocation" : "Votre position",
	"emnavi" : "Navigation",
	"km" : "{value}{spacing}km",
	"mi" : "{value}{spacing}mi",
};

framework.registerAppDictLoaded("emnavi", "fr_FR");