var __VrHelpPositionTable__emnaviAppDict_sk_SK = {
	"Cockpit_Help2" : {
		"Right" : ["VrHelp_WhereAmI","VrHelp_RouteSummary","VrHelp_RepeatInstruction","VrHelp_AddCurrentLocationToFavorites","VrHelp_AddWaypointCategory"],
		"Left" : ["VrHelp_NewDestination","VrHelp_TakeMeHome","VrHelp_NavigateToAnAddress","VrHelp_NavigateToRecentDestination","VrHelp_ClearRoute"]
	}
};

var Localization_emnaviAppDict_sk_SK = {
	//"stringId" : "localString"
	"AddressNotFound" : "Adresa sa nenašla",
	"AtSpeedCautionText" : " ",
	"Compass" : "Kompas",
	"E" : "{value} V",
	"Elevation" : "n/výška",
	"FT" : "{value}{spacing}stopy",
	"Latitude" : "Zem. šírka",
	"Loading" : "Načítava sa navigácia",
	"Longitude" : "Zemep. dĺžka",
	"M" : "{value}{spacing}m",
	"N" : "{value} S",
	"NAVAddressSearch" : "Navigácia",
	"NAVAvoidances" : "Navigácia",
	"NAVCitySearch" : "Navigácia",
	"NAVCoordinate" : "Navigácia",
	"NAVDragMode" : "Navigácia",
	"NAVGasPrice" : "Navigácia",
	"NAVHistory" : "Navigácia",
	"NAVItemList" : "Navigácia",
	"NAVMap" : "Navigácia",
	"NAVMecca" : "Navigácia",
	"NAVModifyPoint" : "Navigácia",
	"NAVNavigationInfo" : "Navigácia",
	"NAVNewDestination" : "Navigácia",
	"NAVPOI" : "Navigácia",
	"NAVPhoneZipSearch" : "Navigácia",
	"NAVPointOnMap" : "Navigácia",
	"NAVQuickSearch" : "Navigácia",
	"NAVResults" : "Navigácia",
	"NAVRoute" : "Navigácia",
	"NAVSettings" : "Navigácia",
	"NAVSimulation" : "Navigácia",
	"NAVSortingOptions" : "Navigácia",
	"NAVTraffic" : "Navigácia",
	"NAVTurnByTurn" : "Navigácia",
	"NAVVoicePrompts" : "Navigácia",
	"NAVWeather" : "Navigácia",
	"NoNavigation" : "Vaša Mazda nie je vybavená navigačným systémom. Avšak, integrovaný navigačný systém si možno zadovážiť od svojho predajcu Mazda ako originálne príslušenstvo značky Mazda.",
	"S" : "{value} J",
	"SDCardInvalid" : "Neplatná SD karta",
	"SDCradInserted" : "SD karta zasunutá",
	"SDCradRemoved" : "SD karta vybratá",
	"VrHelp_AddCurrentLocationToFavorites" : "Add Current Location to Favorites",
	"VrHelp_AddWaypointCategory" : "Add Waypoint (category)",
	"VrHelp_ClearRoute" : "Clear Route",
	"VrHelp_NavigateToAnAddress" : "Navigate to an Address",
	"VrHelp_NavigateToRecentDestination" : "Navigate to Recent Destination",
	"VrHelp_NewDestination" : "New Destination",
	"VrHelp_RepeatInstruction" : "Repeat Instruction",
	"VrHelp_RouteSummary" : "Route Summary",
	"VrHelp_TakeMeHome" : "Take Me Home",
	"VrHelp_WhereAmI" : "Where Am I",
	"W" : "{value} Z",
	"Y" : "{value}{spacing}yardov",
	"YourLocation" : "Vaša poloha",
	"emnavi" : "Navigácia",
	"km" : "{value}{spacing}km",
	"mi" : "{value}{spacing}mi",
};

framework.registerAppDictLoaded("emnavi", "sk_SK");