var __VrHelpPositionTable__emnaviAppDict_lv_LV = {
	"Cockpit_Help2" : {
		"Right" : ["VrHelp_WhereAmI","VrHelp_RouteSummary","VrHelp_RepeatInstruction","VrHelp_AddCurrentLocationToFavorites","VrHelp_AddWaypointCategory"],
		"Left" : ["VrHelp_NewDestination","VrHelp_TakeMeHome","VrHelp_NavigateToAnAddress","VrHelp_NavigateToRecentDestination","VrHelp_ClearRoute"]
	}
};

var Localization_emnaviAppDict_lv_LV = {
	//"stringId" : "localString"
	"AddressNotFound" : "Adrese nav atrasta",
	"AtSpeedCautionText" : " ",
	"Compass" : "Kompass",
	"E" : "{value} A",
	"Elevation" : "Augstums",
	"FT" : "{value}{spacing}ft",
	"Latitude" : "Platums",
	"Loading" : "Ielādē navigāciju",
	"Longitude" : "Garums",
	"M" : "{value}{spacing}m",
	"N" : "{value} Z",
	"NAVAddressSearch" : "Navigācija",
	"NAVAvoidances" : "Navigācija",
	"NAVCitySearch" : "Navigācija",
	"NAVCoordinate" : "Navigācija",
	"NAVDragMode" : "Navigācija",
	"NAVGasPrice" : "Navigācija",
	"NAVHistory" : "Navigācija",
	"NAVItemList" : "Navigācija",
	"NAVMap" : "Navigācija",
	"NAVMecca" : "Navigācija",
	"NAVModifyPoint" : "Navigācija",
	"NAVNavigationInfo" : "Navigācija",
	"NAVNewDestination" : "Navigācija",
	"NAVPOI" : "Navigācija",
	"NAVPhoneZipSearch" : "Navigācija",
	"NAVPointOnMap" : "Navigācija",
	"NAVQuickSearch" : "Navigācija",
	"NAVResults" : "Navigācija",
	"NAVRoute" : "Navigācija",
	"NAVSettings" : "Navigācija",
	"NAVSimulation" : "Navigācija",
	"NAVSortingOptions" : "Navigācija",
	"NAVTraffic" : "Navigācija",
	"NAVTurnByTurn" : "Navigācija",
	"NAVVoicePrompts" : "Navigācija",
	"NAVWeather" : "Navigācija",
	"NoNavigation" : "Šī autom. Mazda nav aprīkota ar navigāc. sist. Taču Mazda oriģinālo piederumu klāstā ir pieejama integrēta navigācijas sist., ko var pasūtīt pie Mazda izplatītāja.",
	"S" : "{value} D",
	"SDCardInvalid" : "Nederīga SD karte",
	"SDCradInserted" : "SD karte ievietota",
	"SDCradRemoved" : "SD karte izņemta",
	"VrHelp_AddCurrentLocationToFavorites" : "Add Current Location to Favorites",
	"VrHelp_AddWaypointCategory" : "Add Waypoint (category)",
	"VrHelp_ClearRoute" : "Clear Route",
	"VrHelp_NavigateToAnAddress" : "Navigate to an Address",
	"VrHelp_NavigateToRecentDestination" : "Navigate to Recent Destination",
	"VrHelp_NewDestination" : "New Destination",
	"VrHelp_RepeatInstruction" : "Repeat Instruction",
	"VrHelp_RouteSummary" : "Route Summary",
	"VrHelp_TakeMeHome" : "Take Me Home",
	"VrHelp_WhereAmI" : "Where Am I",
	"W" : "{value} R",
	"Y" : "{value}{spacing}yd",
	"YourLocation" : "Jūsu atrašanās vieta",
	"emnavi" : "Navigācija",
	"km" : "{value}{spacing}km",
	"mi" : "{value}{spacing}mi",
};

framework.registerAppDictLoaded("emnavi", "lv_LV");