var __VrHelpPositionTable__emnaviAppDict_fi_FI = {
	"Cockpit_Help2" : {
		"Right" : ["VrHelp_WhereAmI","VrHelp_RouteSummary","VrHelp_RepeatInstruction","VrHelp_AddCurrentLocationToFavorites","VrHelp_AddWaypointCategory"],
		"Left" : ["VrHelp_NewDestination","VrHelp_TakeMeHome","VrHelp_NavigateToAnAddress","VrHelp_NavigateToRecentDestination","VrHelp_ClearRoute"]
	}
};

var Localization_emnaviAppDict_fi_FI = {
	//"stringId" : "localString"
	"AddressNotFound" : "Osoitetta ei löydy",
	"AtSpeedCautionText" : " ",
	"Compass" : "Kompassi",
	"E" : "{value} E",
	"Elevation" : "Korkeus",
	"FT" : "{value}{spacing}jalkaa",
	"Latitude" : "Leveysaste",
	"Loading" : "Ladataan navigointia",
	"Longitude" : "Pituusaste",
	"M" : "{value}{spacing}m",
	"N" : "{value} N",
	"NAVAddressSearch" : "Navigointi",
	"NAVAvoidances" : "Navigointi",
	"NAVCitySearch" : "Navigointi",
	"NAVCoordinate" : "Navigointi",
	"NAVDragMode" : "Navigointi",
	"NAVGasPrice" : "Navigointi",
	"NAVHistory" : "Navigointi",
	"NAVItemList" : "Navigointi",
	"NAVMap" : "Navigointi",
	"NAVMecca" : "Navigointi",
	"NAVModifyPoint" : "Navigointi",
	"NAVNavigationInfo" : "Navigointi",
	"NAVNewDestination" : "Navigointi",
	"NAVPOI" : "Navigointi",
	"NAVPhoneZipSearch" : "Navigointi",
	"NAVPointOnMap" : "Navigointi",
	"NAVQuickSearch" : "Navigointi",
	"NAVResults" : "Navigointi",
	"NAVRoute" : "Navigointi",
	"NAVSettings" : "Navigointi",
	"NAVSimulation" : "Navigointi",
	"NAVSortingOptions" : "Navigointi",
	"NAVTraffic" : "Navigointi",
	"NAVTurnByTurn" : "Navigointi",
	"NAVVoicePrompts" : "Navigointi",
	"NAVWeather" : "Navigointi",
	"NoNavigation" : "Mazda-autossasi ei ole navigointijärjestelmää. Voit hankkia alkuperäisenä Mazda-lisävarusteena saatavan integroidun navigointijärjestelmän Mazda-jälleenmyyjältäsi.",
	"S" : "{value} S",
	"SDCardInvalid" : "Virheellinen SD-kortti",
	"SDCradInserted" : "SD-kortti laitettu asemaan",
	"SDCradRemoved" : "SD-kortti otettiin pois asemasta",
	"VrHelp_AddCurrentLocationToFavorites" : "Lisää nykyinen sijainti suosikkeihin",
	"VrHelp_AddWaypointCategory" : "Lisää välietappi (luokka)",
	"VrHelp_ClearRoute" : "Tyhjennä reitti",
	"VrHelp_NavigateToAnAddress" : "Navigoi osoitteeseen",
	"VrHelp_NavigateToRecentDestination" : "Navigoi äskettäin käytettyyn määränpäähän",
	"VrHelp_NewDestination" : "Uusi määränpää",
	"VrHelp_RepeatInstruction" : "Toista ohjeet",
	"VrHelp_RouteSummary" : "Reitin yhteenveto",
	"VrHelp_TakeMeHome" : "Vie minut kotiin",
	"VrHelp_WhereAmI" : "Missä minä olen",
	"W" : "{value} W",
	"Y" : "{value}{spacing}jaardia",
	"YourLocation" : "Oma sijaintisi",
	"emnavi" : "Navigointi",
	"km" : "{value}{spacing}km",
	"mi" : "{value}{spacing}mi",
};

framework.registerAppDictLoaded("emnavi", "fi_FI");