var __VrHelpPositionTable__emnaviAppDict_ro_RO = {
	"Cockpit_Help2" : {
		"Right" : ["VrHelp_WhereAmI","VrHelp_RouteSummary","VrHelp_RepeatInstruction","VrHelp_AddCurrentLocationToFavorites","VrHelp_AddWaypointCategory"],
		"Left" : ["VrHelp_NewDestination","VrHelp_TakeMeHome","VrHelp_NavigateToAnAddress","VrHelp_NavigateToRecentDestination","VrHelp_ClearRoute"]
	}
};

var Localization_emnaviAppDict_ro_RO = {
	//"stringId" : "localString"
	"AddressNotFound" : "Adresă negăsită",
	"AtSpeedCautionText" : " ",
	"Compass" : "Cuprins",
	"E" : "{value} E",
	"Elevation" : "Altitudine",
	"FT" : "{value}{spacing}ft",
	"Latitude" : "Latitudine",
	"Loading" : "Încărcare navigaţie",
	"Longitude" : "Longitudine",
	"M" : "{value}{spacing}m",
	"N" : "{value} N",
	"NAVAddressSearch" : "Navigaţie",
	"NAVAvoidances" : "Navigaţie",
	"NAVCitySearch" : "Navigaţie",
	"NAVCoordinate" : "Navigaţie",
	"NAVDragMode" : "Navigaţie",
	"NAVGasPrice" : "Navigaţie",
	"NAVHistory" : "Navigaţie",
	"NAVItemList" : "Navigaţie",
	"NAVMap" : "Navigaţie",
	"NAVMecca" : "Navigaţie",
	"NAVModifyPoint" : "Navigaţie",
	"NAVNavigationInfo" : "Navigaţie",
	"NAVNewDestination" : "Navigaţie",
	"NAVPOI" : "Navigaţie",
	"NAVPhoneZipSearch" : "Navigaţie",
	"NAVPointOnMap" : "Navigaţie",
	"NAVQuickSearch" : "Navigaţie",
	"NAVResults" : "Navigaţie",
	"NAVRoute" : "Navigaţie",
	"NAVSettings" : "Navigaţie",
	"NAVSimulation" : "Navigaţie",
	"NAVSortingOptions" : "Navigaţie",
	"NAVTraffic" : "Navigaţie",
	"NAVTurnByTurn" : "Navigaţie",
	"NAVVoicePrompts" : "Navigaţie",
	"NAVWeather" : "Navigaţie",
	"NoNavigation" : "Vehiculul dvs. Mazda nu este dotat cu sistem de navigaţie. Un sistem de navigaţie integrat este disponibil la dealerul Mazda ca Accesoriu original Mazda.",
	"S" : "{value} S",
	"SDCardInvalid" : "Card SD nevalid",
	"SDCradInserted" : "Card SD introdus",
	"SDCradRemoved" : "Card SD scos",
	"VrHelp_AddCurrentLocationToFavorites" : "Add Current Location to Favorites",
	"VrHelp_AddWaypointCategory" : "Add Waypoint (category)",
	"VrHelp_ClearRoute" : "Clear Route",
	"VrHelp_NavigateToAnAddress" : "Navigate to an Address",
	"VrHelp_NavigateToRecentDestination" : "Navigate to Recent Destination",
	"VrHelp_NewDestination" : "New Destination",
	"VrHelp_RepeatInstruction" : "Repeat Instruction",
	"VrHelp_RouteSummary" : "Route Summary",
	"VrHelp_TakeMeHome" : "Take Me Home",
	"VrHelp_WhereAmI" : "Where Am I",
	"W" : "{value} V",
	"Y" : "{value}{spacing}yd",
	"YourLocation" : "Locaţia dvoastră",
	"emnavi" : "Navigaţie",
	"km" : "{value}{spacing}km",
	"mi" : "{value}{spacing}mi",
};

framework.registerAppDictLoaded("emnavi", "ro_RO");