var __VrHelpPositionTable__emnaviAppDict_pl_PL = {
	"Cockpit_Help2" : {
		"Right" : ["VrHelp_WhereAmI","VrHelp_RouteSummary","VrHelp_RepeatInstruction","VrHelp_AddCurrentLocationToFavorites","VrHelp_AddWaypointCategory"],
		"Left" : ["VrHelp_NewDestination","VrHelp_TakeMeHome","VrHelp_NavigateToAnAddress","VrHelp_NavigateToRecentDestination","VrHelp_ClearRoute"]
	}
};

var Localization_emnaviAppDict_pl_PL = {
	//"stringId" : "localString"
	"AddressNotFound" : "Nie znaleziono adresu.",
	"AtSpeedCautionText" : " ",
	"Compass" : "Kompas",
	"E" : "{value} E",
	"Elevation" : "W. npm.",
	"FT" : "{value}{spacing}stóp",
	"Latitude" : "Szer. geog.",
	"Loading" : "Ładowanie nawigacji",
	"Longitude" : "Długość geog.",
	"M" : "{value}{spacing}m",
	"N" : "{value} N",
	"NAVAddressSearch" : "Nawigacja",
	"NAVAvoidances" : "Nawigacja",
	"NAVCitySearch" : "Nawigacja",
	"NAVCoordinate" : "Nawigacja",
	"NAVDragMode" : "Nawigacja",
	"NAVGasPrice" : "Nawigacja",
	"NAVHistory" : "Nawigacja",
	"NAVItemList" : "Nawigacja",
	"NAVMap" : "Nawigacja",
	"NAVMecca" : "Nawigacja",
	"NAVModifyPoint" : "Nawigacja",
	"NAVNavigationInfo" : "Nawigacja",
	"NAVNewDestination" : "Nawigacja",
	"NAVPOI" : "Nawigacja",
	"NAVPhoneZipSearch" : "Nawigacja",
	"NAVPointOnMap" : "Nawigacja",
	"NAVQuickSearch" : "Nawigacja",
	"NAVResults" : "Nawigacja",
	"NAVRoute" : "Nawigacja",
	"NAVSettings" : "Nawigacja",
	"NAVSimulation" : "Nawigacja",
	"NAVSortingOptions" : "Nawigacja",
	"NAVTraffic" : "Nawigacja",
	"NAVTurnByTurn" : "Nawigacja",
	"NAVVoicePrompts" : "Nawigacja",
	"NAVWeather" : "Nawigacja",
	"NoNavigation" : "Ten model Mazda nie ma nawigacji. U dealera można kupić autentyczny system nawigacyjny Mazda.",
	"S" : "{value} S",
	"SDCardInvalid" : "Nieprawidłowa karta SD",
	"SDCradInserted" : "Karta SD włożona",
	"SDCradRemoved" : "Karta SD wyjęta",
	"VrHelp_AddCurrentLocationToFavorites" : "Add Current Location to Favorites",
	"VrHelp_AddWaypointCategory" : "Add Waypoint (category)",
	"VrHelp_ClearRoute" : "Clear Route",
	"VrHelp_NavigateToAnAddress" : "Navigate to an Address",
	"VrHelp_NavigateToRecentDestination" : "Navigate to Recent Destination",
	"VrHelp_NewDestination" : "New Destination",
	"VrHelp_RepeatInstruction" : "Repeat Instruction",
	"VrHelp_RouteSummary" : "Route Summary",
	"VrHelp_TakeMeHome" : "Take Me Home",
	"VrHelp_WhereAmI" : "Where Am I",
	"W" : "{value} W",
	"Y" : "{value}{spacing}jardów",
	"YourLocation" : "Lokalizacja użytk.",
	"emnavi" : "Nawigacja",
	"km" : "{value}{spacing}km",
	"mi" : "{value}{spacing}mi",
};

framework.registerAppDictLoaded("emnavi", "pl_PL");