var __VrHelpPositionTable__emnaviAppDict_tr_TR = {
	"Cockpit_Help2" : {
		"Right" : ["VrHelp_WhereAmI","VrHelp_RouteSummary","VrHelp_RepeatInstruction","VrHelp_AddCurrentLocationToFavorites","VrHelp_AddWaypointCategory"],
		"Left" : ["VrHelp_NewDestination","VrHelp_TakeMeHome","VrHelp_NavigateToAnAddress","VrHelp_NavigateToRecentDestination","VrHelp_ClearRoute"]
	}
};

var Localization_emnaviAppDict_tr_TR = {
	//"stringId" : "localString"
	"AddressNotFound" : "Adres Bulunamadı",
	"AtSpeedCautionText" : " ",
	"Compass" : "Pusula",
	"E" : "{value} D",
	"Elevation" : "Yükseklik",
	"FT" : "{value}{spacing}ft",
	"Latitude" : "Enlem",
	"Loading" : "Navigasyon Yükleniyor",
	"Longitude" : "Boylam",
	"M" : "{value}{spacing}m",
	"N" : "{value} K",
	"NAVAddressSearch" : "Navigasyon",
	"NAVAvoidances" : "Navigasyon",
	"NAVCitySearch" : "Navigasyon",
	"NAVCoordinate" : "Navigasyon",
	"NAVDragMode" : "Navigasyon",
	"NAVGasPrice" : "Navigasyon",
	"NAVHistory" : "Navigasyon",
	"NAVItemList" : "Navigasyon",
	"NAVMap" : "Navigasyon",
	"NAVMecca" : "Navigasyon",
	"NAVModifyPoint" : "Navigasyon",
	"NAVNavigationInfo" : "Navigasyon",
	"NAVNewDestination" : "Navigasyon",
	"NAVPOI" : "Navigasyon",
	"NAVPhoneZipSearch" : "Navigasyon",
	"NAVPointOnMap" : "Navigasyon",
	"NAVQuickSearch" : "Navigasyon",
	"NAVResults" : "Navigasyon",
	"NAVRoute" : "Navigasyon",
	"NAVSettings" : "Navigasyon",
	"NAVSimulation" : "Navigasyon",
	"NAVSortingOptions" : "Navigasyon",
	"NAVTraffic" : "Navigasyon",
	"NAVTurnByTurn" : "Navigasyon",
	"NAVVoicePrompts" : "Navigasyon",
	"NAVWeather" : "Navigasyon",
	"NoNavigation" : "Mazda'nızda navigasyon sistemi mevcut değildir. Entegre navigasyon sistemini aksesuar olarak Mazda Bayisinden  temin edebilirsiniz.",
	"S" : "{value} G",
	"SDCardInvalid" : "Geçersiz SD Kart",
	"SDCradInserted" : "SD Kartı Takıldı",
	"SDCradRemoved" : "SD Kartı Çıkartıldı",
	"VrHelp_AddCurrentLocationToFavorites" : "Add Current Location to Favorites",
	"VrHelp_AddWaypointCategory" : "Add Waypoint (category)",
	"VrHelp_ClearRoute" : "Clear Route",
	"VrHelp_NavigateToAnAddress" : "Navigate to an Address",
	"VrHelp_NavigateToRecentDestination" : "Navigate to Recent Destination",
	"VrHelp_NewDestination" : "New Destination",
	"VrHelp_RepeatInstruction" : "Repeat Instruction",
	"VrHelp_RouteSummary" : "Route Summary",
	"VrHelp_TakeMeHome" : "Take Me Home",
	"VrHelp_WhereAmI" : "Where Am I",
	"W" : "{value} B",
	"Y" : "{value}{spacing}yd",
	"YourLocation" : "Konumunuz",
	"emnavi" : "Navigasyon",
	"km" : "{value}{spacing}km",
	"mi" : "{value}{spacing}mi",
};

framework.registerAppDictLoaded("emnavi", "tr_TR");