var __VrHelpPositionTable__emnaviAppDict_th_TH = {
	"Cockpit_Help2" : {
		"Right" : ["VrHelp_WhereAmI","VrHelp_RouteSummary","VrHelp_RepeatInstruction","VrHelp_AddCurrentLocationToFavorites","VrHelp_AddWaypointCategory"],
		"Left" : ["VrHelp_NewDestination","VrHelp_TakeMeHome","VrHelp_NavigateToAnAddress","VrHelp_NavigateToRecentDestination","VrHelp_ClearRoute"]
	}
};

var Localization_emnaviAppDict_th_TH = {
	//"stringId" : "localString"
	"AddressNotFound" : "ไม่พบที่อยู่",
	"AtSpeedCautionText" : " ",
	"Compass" : "เข็มทิศ",
	"E" : "{value} ต.อ.",
	"Elevation" : "ค่าระดับความสูง",
	"FT" : "{value}{spacing}ฟ.",
	"Latitude" : "ละติจูด",
	"Loading" : "กำลังโหลดระบบนำทาง",
	"Longitude" : "ลองจิจูด",
	"M" : "{value}{spacing}ม.",
	"N" : "{value} น.",
	"NAVAddressSearch" : "ระบบนำทาง",
	"NAVAvoidances" : "ระบบนำทาง",
	"NAVCitySearch" : "ระบบนำทาง",
	"NAVCoordinate" : "ระบบนำทาง",
	"NAVDragMode" : "ระบบนำทาง",
	"NAVGasPrice" : "ระบบนำทาง",
	"NAVHistory" : "ระบบนำทาง",
	"NAVItemList" : "ระบบนำทาง",
	"NAVMap" : "ระบบนำทาง",
	"NAVMecca" : "ระบบนำทาง",
	"NAVModifyPoint" : "ระบบนำทาง",
	"NAVNavigationInfo" : "ระบบนำทาง",
	"NAVNewDestination" : "ระบบนำทาง",
	"NAVPOI" : "ระบบนำทาง",
	"NAVPhoneZipSearch" : "ระบบนำทาง",
	"NAVPointOnMap" : "ระบบนำทาง",
	"NAVQuickSearch" : "ระบบนำทาง",
	"NAVResults" : "ระบบนำทาง",
	"NAVRoute" : "ระบบนำทาง",
	"NAVSettings" : "ระบบนำทาง",
	"NAVSimulation" : "ระบบนำทาง",
	"NAVSortingOptions" : "ระบบนำทาง",
	"NAVTraffic" : "ระบบนำทาง",
	"NAVTurnByTurn" : "ระบบนำทาง",
	"NAVVoicePrompts" : "ระบบนำทาง",
	"NAVWeather" : "ระบบนำทาง",
	"NoNavigation" : "Mazda ของคุณไม่มีระบบนำทาง อย่างไรก็ตาม สามารถจัดหาระบบนำทางมาเป็นส่วนเสริมของแท้ของ Mazda (Genuine Mazda Accessory) ได้จากตัวแทนจำหน่าย Mazda ของคุณ",
	"S" : "{value} ต",
	"SDCardInvalid" : "การ์ด SD ไม่ถูกต้อง",
	"SDCradInserted" : "ใส่การ์ด SD",
	"SDCradRemoved" : "ถอดการ์ด SD ออก",
	"VrHelp_AddCurrentLocationToFavorites" : "Add Current Location to Favorites",
	"VrHelp_AddWaypointCategory" : "Add Waypoint (category)",
	"VrHelp_ClearRoute" : "Clear Route",
	"VrHelp_NavigateToAnAddress" : "Navigate to an Address",
	"VrHelp_NavigateToRecentDestination" : "Navigate to Recent Destination",
	"VrHelp_NewDestination" : "New Destination",
	"VrHelp_RepeatInstruction" : "Repeat Instruction",
	"VrHelp_RouteSummary" : "Route Summary",
	"VrHelp_TakeMeHome" : "Take Me Home",
	"VrHelp_WhereAmI" : "Where Am I",
	"W" : "{value} ต.ต.",
	"Y" : "{value}{spacing}หลา",
	"YourLocation" : "ตำแหน่งของคุณ",
	"emnavi" : "ระบบนำทาง",
	"km" : "{value}{spacing}กม.",
	"mi" : "{value}{spacing}ไมล์",
};

framework.registerAppDictLoaded("emnavi", "th_TH");