var __VrHelpPositionTable__emnaviAppDict_it_IT = {
	"Cockpit_Help2" : {
		"Right" : ["VrHelp_WhereAmI","VrHelp_RouteSummary","VrHelp_RepeatInstruction","VrHelp_AddCurrentLocationToFavorites","VrHelp_AddWaypointCategory"],
		"Left" : ["VrHelp_NewDestination","VrHelp_TakeMeHome","VrHelp_NavigateToAnAddress","VrHelp_NavigateToRecentDestination","VrHelp_ClearRoute"]
	}
};

var Localization_emnaviAppDict_it_IT = {
	//"stringId" : "localString"
	"AddressNotFound" : "Indirizzo non trovato",
	"AtSpeedCautionText" : " ",
	"Compass" : "Bussola",
	"E" : "{value} E",
	"Elevation" : "Altezza",
	"FT" : "{value}{spacing}ft",
	"Latitude" : "Latitudine",
	"Loading" : "Caricamento navigazione",
	"Longitude" : "Longitudine",
	"M" : "{value}{spacing}m",
	"N" : "{value}N",
	"NAVAddressSearch" : "Navigazione",
	"NAVAvoidances" : "Navigazione",
	"NAVCitySearch" : "Navigazione",
	"NAVCoordinate" : "Navigazione",
	"NAVDragMode" : "Navigazione",
	"NAVGasPrice" : "Navigazione",
	"NAVHistory" : "Navigazione",
	"NAVItemList" : "Navigazione",
	"NAVMap" : "Navigazione",
	"NAVMecca" : "Navigazione",
	"NAVModifyPoint" : "Navigazione",
	"NAVNavigationInfo" : "Navigazione",
	"NAVNewDestination" : "Navigazione",
	"NAVPOI" : "Navigazione",
	"NAVPhoneZipSearch" : "Navigazione",
	"NAVPointOnMap" : "Navigazione",
	"NAVQuickSearch" : "Navigazione",
	"NAVResults" : "Navigazione",
	"NAVRoute" : "Navigazione",
	"NAVSettings" : "Navigazione",
	"NAVSimulation" : "Navigazione",
	"NAVSortingOptions" : "Navigazione",
	"NAVTraffic" : "Navigazione",
	"NAVTurnByTurn" : "Navigazione",
	"NAVVoicePrompts" : "Navigazione",
	"NAVWeather" : "Navigazione",
	"NoNavigation" : "Questa Mazda non ha un sistema di navigazione. È possibile trovarne uno integrato presso un concessionario Mazda come Accessorio Originale Mazda.",
	"S" : "{value} S",
	"SDCardInvalid" : "SD Card non valida",
	"SDCradInserted" : "SD Card inserita",
	"SDCradRemoved" : "SD Card rimossa",
	"VrHelp_AddCurrentLocationToFavorites" : "Aggiungi località attuale a preferiti",
	"VrHelp_AddWaypointCategory" : "Aggiungi punto intermedio",
	"VrHelp_ClearRoute" : "Annulla percorso",
	"VrHelp_NavigateToAnAddress" : "Naviga verso un indirizzo",
	"VrHelp_NavigateToRecentDestination" : "Naviga verso una destinazione recente",
	"VrHelp_NewDestination" : "Nuova destinazione",
	"VrHelp_RepeatInstruction" : "Ripeti istruzione",
	"VrHelp_RouteSummary" : "Riassunto percorso",
	"VrHelp_TakeMeHome" : "Portami a casa",
	"VrHelp_WhereAmI" : "Dove sono",
	"W" : "{value}O",
	"Y" : "{value}{spacing}yd",
	"YourLocation" : "La tua posizione",
	"emnavi" : "Navigazione",
	"km" : "{value}{spacing}km",
	"mi" : "{value}{spacing}miglia",
};

framework.registerAppDictLoaded("emnavi", "it_IT");