var __VrHelpPositionTable__emnaviAppDict_zh_TW = {
	"Cockpit_Help2" : {
		"Right" : ["VrHelp_WhereAmI","VrHelp_RouteSummary","VrHelp_RepeatInstruction","VrHelp_AddCurrentLocationToFavorites","VrHelp_AddWaypointCategory"],
		"Left" : ["VrHelp_NewDestination","VrHelp_TakeMeHome","VrHelp_NavigateToAnAddress","VrHelp_NavigateToRecentDestination","VrHelp_ClearRoute"]
	}
};

var Localization_emnaviAppDict_zh_TW = {
	//"stringId" : "localString"
	"AddressNotFound" : "未找到地址",
	"AtSpeedCautionText" : " ",
	"Compass" : "指南針",
	"E" : "{value} 東",
	"Elevation" : "海拔",
	"FT" : "{value}{spacing}英呎",
	"Latitude" : "緯度",
	"Loading" : "正在載入導航",
	"Longitude" : "經度",
	"M" : "{value}{spacing}米",
	"N" : "{value} 北",
	"NAVAddressSearch" : "導航",
	"NAVAvoidances" : "導航",
	"NAVCitySearch" : "導航",
	"NAVCoordinate" : "導航",
	"NAVDragMode" : "導航",
	"NAVGasPrice" : "導航",
	"NAVHistory" : "導航",
	"NAVItemList" : "導航",
	"NAVMap" : "導航",
	"NAVMecca" : "導航",
	"NAVModifyPoint" : "導航",
	"NAVNavigationInfo" : "導航",
	"NAVNewDestination" : "導航",
	"NAVPOI" : "導航",
	"NAVPhoneZipSearch" : "導航",
	"NAVPointOnMap" : "導航",
	"NAVQuickSearch" : "導航",
	"NAVResults" : "導航",
	"NAVRoute" : "導航",
	"NAVSettings" : "導航",
	"NAVSimulation" : "導航",
	"NAVSortingOptions" : "導航",
	"NAVTraffic" : "導航",
	"NAVTurnByTurn" : "導航",
	"NAVVoicePrompts" : "導航",
	"NAVWeather" : "導航",
	"NoNavigation" : "您的Mazda未配備導航系統。但通過您的Mazda經銷商可獲得作為真品Mazda附件提供的整合導航系統。",
	"S" : "{value} 南",
	"SDCardInvalid" : "SD卡無效",
	"SDCradInserted" : "SD卡已插入",
	"SDCradRemoved" : "SD卡已取出",
	"VrHelp_AddCurrentLocationToFavorites" : "將當前位置添加到收藏夾",
	"VrHelp_AddWaypointCategory" : "添加路標 (類別)",
	"VrHelp_ClearRoute" : "清除路線",
	"VrHelp_NavigateToAnAddress" : "導航到地址",
	"VrHelp_NavigateToRecentDestination" : "導航到最近目的地",
	"VrHelp_NewDestination" : "新目的地",
	"VrHelp_RepeatInstruction" : "重復指令",
	"VrHelp_RouteSummary" : "路線概覽",
	"VrHelp_TakeMeHome" : "將我帶到家",
	"VrHelp_WhereAmI" : "我在哪兒",
	"W" : "{value} 西",
	"Y" : "{value}{spacing}碼",
	"YourLocation" : "您的位置",
	"emnavi" : "導航",
	"km" : "{value}{spacing}公里",
	"mi" : "{value}{spacing}英裏",
};

framework.registerAppDictLoaded("emnavi", "zh_TW");