var __VrHelpPositionTable__emnaviAppDict_ms_MY = {
	"Cockpit_Help2" : {
		"Right" : ["VrHelp_WhereAmI","VrHelp_RouteSummary","VrHelp_RepeatInstruction","VrHelp_AddCurrentLocationToFavorites","VrHelp_AddWaypointCategory"],
		"Left" : ["VrHelp_NewDestination","VrHelp_TakeMeHome","VrHelp_NavigateToAnAddress","VrHelp_NavigateToRecentDestination","VrHelp_ClearRoute"]
	}
};

var Localization_emnaviAppDict_ms_MY = {
	//"stringId" : "localString"
	"AddressNotFound" : "Alamat Tidak Ditemui",
	"AtSpeedCautionText" : " ",
	"Compass" : "Kompas",
	"E" : "{value} T",
	"Elevation" : "Ketinggian",
	"FT" : "{value}{spacing}ka",
	"Latitude" : "Latitud",
	"Loading" : "Memuatkan Navigasi",
	"Longitude" : "Longitud",
	"M" : "{value}{spacing}m",
	"N" : "{value} U",
	"NAVAddressSearch" : "Navigasi",
	"NAVAvoidances" : "Navigasi",
	"NAVCitySearch" : "Navigasi",
	"NAVCoordinate" : "Navigasi",
	"NAVDragMode" : "Navigasi",
	"NAVGasPrice" : "Navigasi",
	"NAVHistory" : "Navigasi",
	"NAVItemList" : "Navigasi",
	"NAVMap" : "Navigasi",
	"NAVMecca" : "Navigasi",
	"NAVModifyPoint" : "Navigasi",
	"NAVNavigationInfo" : "Navigasi",
	"NAVNewDestination" : "Navigasi",
	"NAVPOI" : "Navigasi",
	"NAVPhoneZipSearch" : "Navigasi",
	"NAVPointOnMap" : "Navigasi",
	"NAVQuickSearch" : "Navigasi",
	"NAVResults" : "Navigasi",
	"NAVRoute" : "Navigasi",
	"NAVSettings" : "Navigasi",
	"NAVSimulation" : "Navigasi",
	"NAVSortingOptions" : "Navigasi",
	"NAVTraffic" : "Navigasi",
	"NAVTurnByTurn" : "Navigasi",
	"NAVVoicePrompts" : "Navigasi",
	"NAVWeather" : "Navigasi",
	"NoNavigation" : "Tidak dilengkapi sistem navigasi. Walau bagaimanapun, sistem navigasi bersepadu boleh didapati melalui wakil penjual Mazda anda sebagai Aksesori Tulen Mazda.",
	"S" : "{value} S",
	"SDCardInvalid" : "Kad SD Tidak Sah",
	"SDCradInserted" : "Kad SD Dimasukkan",
	"SDCradRemoved" : "Kad SD Dikeluarkan",
	"VrHelp_AddCurrentLocationToFavorites" : "Add Current Location to Favorites",
	"VrHelp_AddWaypointCategory" : "Add Waypoint (category)",
	"VrHelp_ClearRoute" : "Clear Route",
	"VrHelp_NavigateToAnAddress" : "Navigate to an Address",
	"VrHelp_NavigateToRecentDestination" : "Navigate to Recent Destination",
	"VrHelp_NewDestination" : "New Destination",
	"VrHelp_RepeatInstruction" : "Repeat Instruction",
	"VrHelp_RouteSummary" : "Route Summary",
	"VrHelp_TakeMeHome" : "Take Me Home",
	"VrHelp_WhereAmI" : "Where Am I",
	"W" : "{value} B",
	"Y" : "{value}{spacing}el",
	"YourLocation" : "Lokasi Anda",
	"emnavi" : "Navigasi",
	"km" : "{value}{spacing}km",
	"mi" : "{value}{spacing}bt",
};

framework.registerAppDictLoaded("emnavi", "ms_MY");