var __VrHelpPositionTable__emnaviAppDict_he_IL = {
	"Cockpit_Help2" : {
		"Right" : ["VrHelp_WhereAmI","VrHelp_RouteSummary","VrHelp_RepeatInstruction","VrHelp_AddCurrentLocationToFavorites","VrHelp_AddWaypointCategory"],
		"Left" : ["VrHelp_NewDestination","VrHelp_TakeMeHome","VrHelp_NavigateToAnAddress","VrHelp_NavigateToRecentDestination","VrHelp_ClearRoute"]
	}
};

var Localization_emnaviAppDict_he_IL = {
	//"stringId" : "localString"
	"AddressNotFound" : "כתובת לא נמצאה",
	"AtSpeedCautionText" : " ",
	"Compass" : "מצפן",
	"E" : "{value} מזרח",
	"Elevation" : "רום",
	"FT" : "{value}{spacing}רגל",
	"Latitude" : "קו רוחב",
	"Loading" : "טוען ניווט",
	"Longitude" : "קו אורך",
	"M" : "{value}{spacing}מטר",
	"N" : "{value} צפון",
	"NAVAddressSearch" : "ניווט",
	"NAVAvoidances" : "ניווט",
	"NAVCitySearch" : "ניווט",
	"NAVCoordinate" : "ניווט",
	"NAVDragMode" : "ניווט",
	"NAVGasPrice" : "ניווט",
	"NAVHistory" : "ניווט",
	"NAVItemList" : "ניווט",
	"NAVMap" : "ניווט",
	"NAVMecca" : "ניווט",
	"NAVModifyPoint" : "ניווט",
	"NAVNavigationInfo" : "ניווט",
	"NAVNewDestination" : "ניווט",
	"NAVPOI" : "ניווט",
	"NAVPhoneZipSearch" : "ניווט",
	"NAVPointOnMap" : "ניווט",
	"NAVQuickSearch" : "ניווט",
	"NAVResults" : "ניווט",
	"NAVRoute" : "ניווט",
	"NAVSettings" : "ניווט",
	"NAVSimulation" : "ניווט",
	"NAVSortingOptions" : "ניווט",
	"NAVTraffic" : "ניווט",
	"NAVTurnByTurn" : "ניווט",
	"NAVVoicePrompts" : "ניווט",
	"NAVWeather" : "ניווט",
	"NoNavigation" : "Mazda שלך לא מצויידת במערכת ניווט. למרות זאת, מערכת ניווט משולבת זמינה דרך סוכן Mazda שלך כאביזר Mazda מקורי.",
	"S" : "{value} דרום",
	"SDCardInvalid" : "כרטיס SD אינו תקף",
	"SDCradInserted" : "הוכנס כרטיס SD",
	"SDCradRemoved" : "הוסר כרטיס SD",
	"VrHelp_AddCurrentLocationToFavorites" : "Add Current Location to Favorites",
	"VrHelp_AddWaypointCategory" : "Add Waypoint (category)",
	"VrHelp_ClearRoute" : "Clear Route",
	"VrHelp_NavigateToAnAddress" : "Navigate to an Address",
	"VrHelp_NavigateToRecentDestination" : "Navigate to Recent Destination",
	"VrHelp_NewDestination" : "New Destination",
	"VrHelp_RepeatInstruction" : "Repeat Instruction",
	"VrHelp_RouteSummary" : "Route Summary",
	"VrHelp_TakeMeHome" : "Take Me Home",
	"VrHelp_WhereAmI" : "Where Am I",
	"W" : "{value} מערב",
	"Y" : "{value}{spacing}יארד",
	"YourLocation" : "מיקומך",
	"emnavi" : "ניווט",
	"km" : "{value}{spacing}ק\"מ",
	"mi" : "{value}{spacing}מייל",
};

framework.registerAppDictLoaded("emnavi", "he_IL");