var __VrHelpPositionTable__emnaviAppDict_ar_SA = {
	"Cockpit_Help2" : {
		"Right" : ["VrHelp_WhereAmI","VrHelp_RouteSummary","VrHelp_RepeatInstruction","VrHelp_AddCurrentLocationToFavorites","VrHelp_AddWaypointCategory"],
		"Left" : ["VrHelp_NewDestination","VrHelp_TakeMeHome","VrHelp_NavigateToAnAddress","VrHelp_NavigateToRecentDestination","VrHelp_ClearRoute"]
	}
};

var Localization_emnaviAppDict_ar_SA = {
	//"stringId" : "localString"
	"AddressNotFound" : "لم يتم العثور على العنوان",
	"AtSpeedCautionText" : "",
	"Compass" : "بوصلة",
	"E" : "{value} شرق",
	"Elevation" : "إرتفاع",
	"FT" : "{value}{spacing}قدم",
	"Latitude" : "خط العرض",
	"Loading" : " تحميل  الملاحة جارٍ",
	"Longitude" : "خط الطول",
	"M" : "{value}{spacing}م",
	"N" : "{value} شمال",
	"NAVAddressSearch" : "التنقل",
	"NAVAvoidances" : "التنقل",
	"NAVCitySearch" : "التنقل",
	"NAVCoordinate" : "التنقل",
	"NAVDragMode" : "التنقل",
	"NAVGasPrice" : "التنقل",
	"NAVHistory" : "التنقل",
	"NAVItemList" : "التنقل",
	"NAVMap" : "التنقل",
	"NAVMecca" : "التنقل",
	"NAVModifyPoint" : "التنقل",
	"NAVNavigationInfo" : "التنقل",
	"NAVNewDestination" : "التنقل",
	"NAVPOI" : "التنقل",
	"NAVPhoneZipSearch" : "التنقل",
	"NAVPointOnMap" : "التنقل",
	"NAVQuickSearch" : "التنقل",
	"NAVResults" : "التنقل",
	"NAVRoute" : "التنقل",
	"NAVSettings" : "التنقل",
	"NAVSimulation" : "التنقل",
	"NAVSortingOptions" : "التنقل",
	"NAVTraffic" : "التنقل",
	"NAVTurnByTurn" : "التنقل",
	"NAVVoicePrompts" : "التنقل",
	"NAVWeather" : "التنقل",
	"NoNavigation" : "Mazda غير مجهزة بنظام ملاحة . يتوفر نظام  ملاحة مدمج لدى موزع Mazda",
	"S" : "{value} جنوب",
	"SDCardInvalid" : "بطاقة رقمية آمنة غير سارية",
	"SDCradInserted" : "تم إدخال البطاقة الرقمية الآمنة",
	"SDCradRemoved" : "تمت إزالة البطاقة الرقمية الآمنة",
	"VrHelp_AddCurrentLocationToFavorites" : "إضافة الموقع الحالي إلى المفضلات",
	"VrHelp_AddWaypointCategory" : "إضافة إحداثية (بفئة)",
	"VrHelp_ClearRoute" : "مسح مسار",
	"VrHelp_NavigateToAnAddress" : "انتقال إلى أحد العناوين",
	"VrHelp_NavigateToRecentDestination" : "انتقال إلى وجهة حديثة",
	"VrHelp_NewDestination" : "وجهة جديدة،",
	"VrHelp_RepeatInstruction" : "تكرار التعليمات",
	"VrHelp_RouteSummary" : "ملخص المسار",
	"VrHelp_TakeMeHome" : "اصطحبني للمنزل",
	"VrHelp_WhereAmI" : "أين أنا",
	"W" : "{value} غرب",
	"Y" : "{value}{spacing}ياردة",
	"YourLocation" : "موقعك",
	"emnavi" : "التنقل",
	"km" : "{value}{spacing}كم",
	"mi" : "{value}{spacing}ميل",
};

framework.registerAppDictLoaded("emnavi", "ar_SA");