var __VrHelpPositionTable__emnaviAppDict_da_DK = {
	"Cockpit_Help2" : {
		"Right" : ["VrHelp_WhereAmI","VrHelp_RouteSummary","VrHelp_RepeatInstruction","VrHelp_AddCurrentLocationToFavorites","VrHelp_AddWaypointCategory"],
		"Left" : ["VrHelp_NewDestination","VrHelp_TakeMeHome","VrHelp_NavigateToAnAddress","VrHelp_NavigateToRecentDestination","VrHelp_ClearRoute"]
	}
};

var Localization_emnaviAppDict_da_DK = {
	//"stringId" : "localString"
	"AddressNotFound" : "Adressen blev ikke fundet",
	"AtSpeedCautionText" : "JAPAN ONLY",
	"Compass" : "Kompas",
	"E" : "{value} Ø",
	"Elevation" : "Højde",
	"FT" : "{value}{spacing}ft",
	"Latitude" : "Breddegrad",
	"Loading" : "Indlæser navigation",
	"Longitude" : "Længdegrad",
	"M" : "{value}{spacing}m",
	"N" : "{value} N",
	"NAVAddressSearch" : "Navigering",
	"NAVAvoidances" : "Navigering",
	"NAVCitySearch" : "Navigering",
	"NAVCoordinate" : "Navigering",
	"NAVDragMode" : "Navigering",
	"NAVGasPrice" : "Navigering",
	"NAVHistory" : "Navigering",
	"NAVItemList" : "Navigering",
	"NAVMap" : "Navigering",
	"NAVMecca" : "Navigering",
	"NAVModifyPoint" : "Navigering",
	"NAVNavigationInfo" : "Navigering",
	"NAVNewDestination" : "Navigering",
	"NAVPOI" : "Navigering",
	"NAVPhoneZipSearch" : "Navigering",
	"NAVPointOnMap" : "Navigering",
	"NAVQuickSearch" : "Navigering",
	"NAVResults" : "Navigering",
	"NAVRoute" : "Navigering",
	"NAVSettings" : "Navigering",
	"NAVSimulation" : "Navigering",
	"NAVSortingOptions" : "Navigering",
	"NAVTraffic" : "Navigering",
	"NAVTurnByTurn" : "Navigering",
	"NAVVoicePrompts" : "Navigering",
	"NAVWeather" : "Navigering",
	"NoNavigation" : "Din Mazda er ikke udstyret med navigationssystem. Et integreret navigationssystem kan købes som originalt tilbehør hos din Mazda-forhandler.",
	"S" : "{value} S",
	"SDCardInvalid" : "Ugyldigt SD-kort",
	"SDCradInserted" : "SD-kort indsat",
	"SDCradRemoved" : "SD-kort fjernet",
	"VrHelp_AddCurrentLocationToFavorites" : "Føj nuværende placering til favoritter",
	"VrHelp_AddWaypointCategory" : "Tilføj rutepunkt (kategori)",
	"VrHelp_ClearRoute" : "Ryd rute",
	"VrHelp_NavigateToAnAddress" : "Navigér til en adresse",
	"VrHelp_NavigateToRecentDestination" : "Navigér til seneste destination",
	"VrHelp_NewDestination" : "Ny destination",
	"VrHelp_RepeatInstruction" : "Gentag instruktion",
	"VrHelp_RouteSummary" : "Rute-resumé",
	"VrHelp_TakeMeHome" : "Før mig hjem",
	"VrHelp_WhereAmI" : "Hvor er jeg",
	"W" : "{value} V",
	"Y" : "{value}{spacing}yd",
	"YourLocation" : "Din placering",
	"emnavi" : "Navigering",
	"km" : "{value}{spacing}km",
	"mi" : "{value}{spacing}mi",
};

framework.registerAppDictLoaded("emnavi", "da_DK");