var __VrHelpPositionTable__emnaviAppDict_el_GR = {
	"Cockpit_Help2" : {
		"Right" : ["VrHelp_WhereAmI","VrHelp_RouteSummary","VrHelp_RepeatInstruction","VrHelp_AddCurrentLocationToFavorites","VrHelp_AddWaypointCategory"],
		"Left" : ["VrHelp_NewDestination","VrHelp_TakeMeHome","VrHelp_NavigateToAnAddress","VrHelp_NavigateToRecentDestination","VrHelp_ClearRoute"]
	}
};

var Localization_emnaviAppDict_el_GR = {
	//"stringId" : "localString"
	"AddressNotFound" : "Δεν βρέθηκε η διεύθυνση",
	"AtSpeedCautionText" : " ",
	"Compass" : "Πυξίδα",
	"E" : "{value} Α",
	"Elevation" : "Υψόμετρο",
	"FT" : "{value}{spacing}π.",
	"Latitude" : " πλάτος",
	"Loading" : "Φόρτωση πλοήγησης",
	"Longitude" : "Γεω. μήκος",
	"M" : "{value}{spacing}μ",
	"N" : "{value} Β",
	"NAVAddressSearch" : "Πλοήγηση",
	"NAVAvoidances" : "Πλοήγηση",
	"NAVCitySearch" : "Πλοήγηση",
	"NAVCoordinate" : "Πλοήγηση",
	"NAVDragMode" : "Πλοήγηση",
	"NAVGasPrice" : "Πλοήγηση",
	"NAVHistory" : "Πλοήγηση",
	"NAVItemList" : "Πλοήγηση",
	"NAVMap" : "Πλοήγηση",
	"NAVMecca" : "Πλοήγηση",
	"NAVModifyPoint" : "Πλοήγηση",
	"NAVNavigationInfo" : "Πλοήγηση",
	"NAVNewDestination" : "Πλοήγηση",
	"NAVPOI" : "Πλοήγηση",
	"NAVPhoneZipSearch" : "Πλοήγηση",
	"NAVPointOnMap" : "Πλοήγηση",
	"NAVQuickSearch" : "Πλοήγηση",
	"NAVResults" : "Πλοήγηση",
	"NAVRoute" : "Πλοήγηση",
	"NAVSettings" : "Πλοήγηση",
	"NAVSimulation" : "Πλοήγηση",
	"NAVSortingOptions" : "Πλοήγηση",
	"NAVTraffic" : "Πλοήγηση",
	"NAVTurnByTurn" : "Πλοήγηση",
	"NAVVoicePrompts" : "Πλοήγηση",
	"NAVWeather" : "Πλοήγηση",
	"NoNavigation" : "Το Mazda σας δεν έχει σύστημα πλοήγησης. Ωστόσο, διατίθεται ενοποιημένο σύστημα πλοήγησης μέσω της αντιπροσωπείας Mazda της περιοχής σας ως αυθεντικό αξεσουάρ Mazda.",
	"S" : "{value} Ν",
	"SDCardInvalid" : "Άκυρη κάρτα SD",
	"SDCradInserted" : "Κάρτα SD εισηγμένη",
	"SDCradRemoved" : "Κάρτα SD αφαιρέθηκε",
	"VrHelp_AddCurrentLocationToFavorites" : "Add Current Location to Favorites",
	"VrHelp_AddWaypointCategory" : "Add Waypoint (category)",
	"VrHelp_ClearRoute" : "Clear Route",
	"VrHelp_NavigateToAnAddress" : "Navigate to an Address",
	"VrHelp_NavigateToRecentDestination" : "Navigate to Recent Destination",
	"VrHelp_NewDestination" : "New Destination",
	"VrHelp_RepeatInstruction" : "Repeat Instruction",
	"VrHelp_RouteSummary" : "Route Summary",
	"VrHelp_TakeMeHome" : "Take Me Home",
	"VrHelp_WhereAmI" : "Where Am I",
	"W" : "{value} Δ",
	"Y" : "{value}{spacing}γιαρ.",
	"YourLocation" : "Η τοποθεσία σας",
	"emnavi" : "Πλοήγηση",
	"km" : "{value}{spacing}km",
	"mi" : "{value}{spacing}mi",
};

framework.registerAppDictLoaded("emnavi", "el_GR");