var __VrHelpPositionTable__systemAppDict_zh_CN = {
	"HomeScreen_Help" : {
		"Right" : ["VrHelp_Favorites"],
		"Left" : ["VrHelp_Entertainment","VrHelp_Communication","VrHelp_Navigation","VrHelp_Settings","VrHelp_Applications"]
	}
};

var Localization_systemAppDict_zh_CN = {
	//"stringId" : "localString"
	"ActiveCallItem" : "正在通话",
	"AhaMaintError" : "aha 维护错误",
	"AhaRadio" : "aha",
	"AmRadio" : "AM",
	"AndroidAuto" : "Android Auto",
	"Applications" : "应用程序",
	"AudioSourceNotAvailableBTAudio" : "Bluetooth音频不可用",
	"AudioSourceNotAvailableCD" : "CD已取出",
	"AudioSourceNotAvailableDVD" : "DVD已取出",
	"AudioSourceNotAvailableTV" : "电视不可用",
	"AudioSourceNotAvailableUSB" : "USB设备已更改",
	"AuxIn" : "AUX",
	"BT" : "BT",
	"Bluetooth" : "Bluetooth",
	"BluetoothWithDevice" : "Bluetooth - {deviceName}",
	"CallHistory" : "通话记录",
	"CarPlay" : "Apple CarPlay",
	"CdPlayer" : "CD",
	"ChannelOffAir" : "频道停止广播",
	"ChannelUnauth" : "频道未授权",
	"CheckAntenna" : "检查天线",
	"CheckTuner" : "检查调谐器",
	"Communication" : "通讯",
	"Connect" : "连接",
	"Contacts" : "联系人",
	"DVDItem" : "DVD",
	"DabRadio" : "DAB",
	"DialPhone" : "拨打电话",
	"DidYouSay" : "请选择：",
	"DisclaimerText" : "注意力分散可能导致事故。不要在驾驶时操作。始终专心驾驶并遵守交通法规。参阅所有者手册。",
	"DisconnectThenReconnect" : "启动 Siri 时出错。 断开并重新连接 Apple 设备。",
	"DriveRecord" : "驾驶记录",
	"DriverIDItem" : "驾驶员识别",
	"EcoenergyApp" : "燃油经济性 [监测器]",
	"EcoenergyAppHEV" : "驾驶显示器",
	"Email" : "电子邮件",
	"EngineOilLevel" : "发动机油位",
	"Entertainment" : "娱乐",
	"ErrorWhileStartingSiri" : "启动Siri时出现错误。",
	"FailedNotificationRetrieval" : "无法检索通知列表。",
	"FavoritesItem" : "收藏夹",
	"FmRadio" : "FM",
	"HDTrafficItem" : "HD Radio™交通图",
	"InitiateSiri" : "长按讲话按钮以便启动Siri会话",
	"IntelligentDriveMasterItem" : "i-DM",
	"NavigationTitle" : "导航",
	"NoConnectionNotifyText" : "现在是否要连接电话？",
	"NoConnectionNotifyTitle" : "未连接电话",
	"NoDeviceText" : "现在是否要连接设备？",
	"NoDeviceTitle" : "未连接设备",
	"Notifications" : "通知",
	"NotifyIgnore" : "忽略",
	"NotifyIncomingMsg" : "收信来自：",
	"NotifyOff" : "通知关闭",
	"NotifyRead" : "阅读",
	"NotifyReadNow" : "是否要现在阅读它？",
	"Pandora" : "Pandora",
	"ReconnectAhaRadio" : "正在重新连接 aha 收音机的BT音频",
	"ReconnectBTAudio" : "正在重新连接BT音频，以继续播放",
	"ReconnectCD" : "正在验证 CD，以便继续播放",
	"ReconnectCarPlay" : "正在恢复 Apple CarPlay。",
	"ReconnectDVD" : "正在验证 DVD，以便继续播放",
	"ReconnectEntMenuButton" : "娱乐菜单",
	"ReconnectFailedBTAudio" : "无法重新连接Bluetooth音频",
	"ReconnectFailedCD" : "CD已取出。无法继续播放。",
	"ReconnectFailedCarPlay" : "无法重新连接 Apple CarPlay",
	"ReconnectFailedDVD" : "DVD已取出。无法继续播放。",
	"ReconnectFailedTV" : "电视不可用。无法继续播放。",
	"ReconnectFailedUSB" : "USB设备已更改。无法继续播放。",
	"ReconnectPandora" : "正在重新连接Pandora的Bluetooth音频",
	"ReconnectStitcher" : "正在重新连接Stitcher的Bluetooth音频",
	"ReconnectTV" : "检验电视以便继续播放",
	"ReconnectUSB" : "正在重新连接 USB 设备，以继续播放",
	"RetryLabel" : "重试",
	"SchedMaintenanceApp" : "维护",
	"ScreenReplication" : "屏幕复制",
	"SdarsRadio" : "XM",
	"Settings" : "设置",
	"SettingsCommunication" : "设置",
	"Siri" : "Siri",
	"SiriDisabled" : "Siri is Disabled on Apple Device.",
	"Sms" : "短信",
	"StitcherItem" : "Stitcher",
	"TVItem" : "TV",
	"TempWarning" : "温度警告",
	"TempWarningText" : "显示屏太热。在冷却前，屏幕性能可能降低。",
	"TextDownloaded" : "已下载文本",
	"TextSent" : "已发送文本",
	"TrafficAlertsItem" : "交通信息",
	"USB" : "USB",
	"USB1AndroidAuto" : "USB 1 - Android Auto",
	"USB1CarPlay" : "USB 1 - Apple CarPlay",
	"USB2AndroidAuto" : "USB 2 - Android Auto",
	"UsbAudioA" : "USB 1",
	"UsbAudioAWithDevice" : "USB 1 - {deviceName}",
	"UsbAudioB" : "USB 2",
	"UsbAudioBWithDevice" : "USB 2 - {deviceName}",
	"UseCommander" : "开车时请使用命令程序。",
	"VehicleDataTransferItem" : "车辆数据传输 ",
	"VehicleStatusMonitor" : "车辆状态监视器",
	"VehicleTelemetryTransfer" : "车辆遥测传输",
	"VideoSignalLost" : "视频信号丢失",
	"VoiceNotSupported" : "不支持语音 ",
	"VoiceRecognition" : "语音识别",
	"VrHelp_Applications" : "应用程序",
	"VrHelp_Communication" : "通讯",
	"VrHelp_Entertainment" : "娱乐",
	"VrHelp_Favorites" : "收藏夹",
	"VrHelp_Navigation" : "导航",
	"VrHelp_Settings" : "设置",
	"WarnGuidanceApp" : "警告指导",
	"WarningTitle" : "警告！",
	"XMAudio" : "SiriusXM",
	"XMData" : "SXM Services",
	"agree" : "我同意",
	"VRD_aharadioSelectCall" : "呼叫",
	"VRD_aharadioSelectDiscard" : "放弃",
	"VRD_aharadioSelectEpisodes" : "剧集列表",
	"VRD_aharadioSelectLBSTab" : "附近",
	"VRD_aharadioSelectMainList" : "Aha 主列表",
	"VRD_aharadioSelectMap" : "地图",
	"VRD_aharadioSelectPresetsTab" : "预设",
	"VRD_aharadioSelectSave" : "保存",
	"VRD_aharadioSelectSettings" : "声音设置",
	"VRD_aharadioSelectShout" : "大声说",
	"VRD_aharadioSelectSource" : "娱乐/更改来源",
	"VRD_aharadioSelectThumbsDown" : "不喜欢",
	"VRD_aharadioSelectThumbsUp" : "喜欢",
	"VRD_amradioPlayStationFrequency" : "调到 {frequency} AM",
	"VRD_amradioSelectAutoMemory" : "自动记忆",
	"VRD_amradioSelectFavorites" : "收藏夹",
	"VRD_amradioSelectHD" : "HD电台",
	"VRD_amradioSelectHDOff" : "关闭 HD Radio",
	"VRD_amradioSelectHDOn" : "打开 HD Radio",
	"VRD_amradioSelectScanOff" : "扫描关闭",
	"VRD_amradioSelectScanOn" : "扫描开启",
	"VRD_amradioSelectSeekNext" : "搜索下一个",
	"VRD_amradioSelectSeekPrevious" : "搜索上一个",
	"VRD_amradioSelectSettings" : "声音设置",
	"VRD_amradioSelectSource" : "转到娱乐菜单",
	"VRD_amradioSelectStationFrequency" : "{AMFrequency}",
	"VRD_amradioSelectTrafficAlert" : "流量警告",
	"VRD_amradioSelectTrafficAlertOff" : "关闭流量警告",
	"VRD_amradioSelectTrafficAlertOn" : "开启流量警告",
	"VRD_amradioSelectTune" : "调台",
	"VRD_amradioSelectUpdateAutoMemory" : "自动记忆搜索",
	"VRD_amradioSelectiTunesTagging" : "iTunes 标记",
	"VRD_amradioTuneDown" : "向下调台",
	"VRD_amradioTuneUp" : "向上调台",
	"VRD_amradioUpdateAutoMemory" : "更新电台列表",
	"VRD_auxinSelectSettings" : "声音设置",
	"VRD_auxinSelectSource" : "娱乐/更改来源",
	"VRD_btaudioScanPlay" : "扫描播放",
	"VRD_btaudioSelectConnect" : "连接",
	"VRD_btaudioSelectRootMenu" : "根菜单",
	"VRD_btaudioSelectSettings" : "声音设置",
	"VRD_btaudioSelectSource" : "转到娱乐菜单",
	"VRD_btaudioToggleRepeat" : "重复",
	"VRD_btaudioToggleShuffle" : "随机播放",
	"VRD_carplaySelectApplications" : "应用程序",
	"VRD_cdGoSettings" : "声音设置",
	"VRD_cdHandleStartScan" : "开始扫描",
	"VRD_cdPlayBeginning" : "重新开始",
	"VRD_cdRepeatFolder" : "重复文件夹",
	"VRD_cdRepeatOff" : "关闭重复",
	"VRD_cdRepeatOn" : "开启重复",
	"VRD_cdRepeatTrack" : "重复曲目",
	"VRD_cdSelectCurrentFolder" : "当前文件夹",
	"VRD_cdSelectRepeat" : "重复",
	"VRD_cdSelectRootFolder" : "根菜单",
	"VRD_cdSelectShuffle" : "随机播放",
	"VRD_cdSelectSource" : "转到娱乐菜单",
	"VRD_cdSelectTrackList" : "曲目列表",
	"VRD_cdSelectTrackNumber" : "播放曲目 {Number}",
	"VRD_cdShuffleDisk" : "随机播放磁盘",
	"VRD_cdShuffleFolder" : "随机播放文件夹",
	"VRD_cdShuffleOff" : "关闭随机播放",
	"VRD_cdShuffleOn" : "开启随机播放",
	"VRD_commonAddToFavorites" : "添加到收藏夹",
	"VRD_commonCancel" : "取消",
	"VRD_commonFastForward" : "快进",
	"VRD_commonGoBack" : "返回",
	"VRD_commonIntentParent" : "父级",
	"VRD_commonIntentParentUSBAudio" : "父级",
	"VRD_commonIntentUSBAudio" : "住宅电话",
	"VRD_commonIntentUSBAudioBG" : "住宅电话",
	"VRD_commonMenuUp" : "菜单向上",
	"VRD_commonNext" : "下一个",
	"VRD_commonNo" : "否",
	"VRD_commonPageDown" : "向下翻页/向下滚动",
	"VRD_commonPageUp" : "向上翻页/向上滚动",
	"VRD_commonPause" : "暂停",
	"VRD_commonPrevious" : "上一个",
	"VRD_commonResume" : "播放 / 继续",
	"VRD_commonRewind" : "倒带",
	"VRD_commonSelectLineNumber" : "线{lineNumber}",
	"VRD_commonYes" : "是/确定",
	"VRD_contactsChooseContactName" : "{ContactName}",
	"VRD_contactsDisambiguateContactName" : "显示 {ContactName}",
	"VRD_contactsImportAll" : "导入所有联系人",
	"VRD_contactsImportCancel" : "取消导入",
	"VRD_contactsImportContacts" : "编辑联系人",
	"VRD_contactsImportSingle" : "导入选定的联系人",
	"VRD_contactsRemoveContact" : "移除联系人",
	"VRD_contactsSelectCall" : "呼叫",
	"VRD_contactsSelectContactName" : "{ContactName}",
	"VRD_contactsSelectDownload" : "下载",
	"VRD_contactsSelectFavorites" : "收藏夹",
	"VRD_contactsSelectNone" : "这些都不是",
	"VRD_contactsSelectReadContactName" : "读取联系人姓名",
	"VRD_contactsSelectRemove" : "移除",
	"VRD_contactsSelectRetry" : "重试",
	"VRD_contactsSendPhoneType" : "{phoneType}",
	"VRD_contactsShowAddress" : "地址",
	"VRD_dabDisplayDABSettings" : "DAB 设置",
	"VRD_dabDisplayEnsembleList" : "选择电台合集",
	"VRD_dabDisplayStationList" : "电台列表",
	"VRD_dabSelectFavorites" : "收藏夹",
	"VRD_dabSelectScan" : "扫描",
	"VRD_dabSelectSeekNext" : "下一个",
	"VRD_dabSelectSeekPrevious" : "上一个",
	"VRD_dabSelectSettings" : "声音设置",
	"VRD_dabSelectSource" : "娱乐",
	"VRD_dabTAToggleOFF" : "流量关闭",
	"VRD_dabTAToggleON" : "流量开启",
	"VRD_dabTAToggleVois" : "交通警告 (TA)",
	"VRD_dabUpdateStationList" : "更新列表",
	"VRD_dvdClearPin" : "删除数字",
	"VRD_dvdSayGRating" : "G",
	"VRD_dvdSayPG12" : "P G 十二",
	"VRD_dvdSayR15" : "R 十五加",
	"VRD_dvdSayR18" : "无",
	"VRD_dvdSelectAspectRatio" : "高宽比",
	"VRD_dvdSelectAudioSettings" : "显示调整 ",
	"VRD_dvdSelectCameraAngle" : "摄像头角度",
	"VRD_dvdSelectEditPin" : "编辑 PIN 码",
	"VRD_dvdSelectParentLock" : "家长锁",
	"VRD_dvdSelectParentLockOff" : "关闭家长锁",
	"VRD_dvdSelectParentLockOn" : "打开家长锁",
	"VRD_dvdSelectParentLockRating" : "家长所等级",
	"VRD_dvdSelectResetPin" : "重设验证密码",
	"VRD_dvdSelectRootMenu" : "根菜单",
	"VRD_dvdSelectSettings" : "声音设置",
	"VRD_dvdSelectSource" : "娱乐",
	"VRD_dvdSelectSubtitleOff" : "字幕关闭",
	"VRD_dvdSelectSubtitleOn" : "字幕开启",
	"VRD_dvdSlowForward" : "快进",
	"VRD_dvdSlowRewind" : "倒带",
	"VRD_dvdVUISendPin" : "{FourDigitPin}",
	"VRD_emailSelectAllAccounts" : "所有帐户",
	"VRD_emailSelectCall" : "呼叫",
	"VRD_emailSelectContactName" : "{ContactName}",
	"VRD_emailSelectContinueEmail" : "继续电子邮件",
	"VRD_emailSelectDelete" : "删除",
	"VRD_emailSelectDiscard" : "放弃",
	"VRD_emailSelectImportEmail" : "更新收件箱",
	"VRD_emailSelectInbox" : "电子邮件收件箱",
	"VRD_emailSelectInboxSelector" : "收件箱",
	"VRD_emailSelectMessage" : "添加消息",
	"VRD_emailSelectNone" : "这些都不是",
	"VRD_emailSelectReply" : "回复",
	"VRD_emailSelectReplyAll" : "全部回复",
	"VRD_emailSelectRetry" : "重试",
	"VRD_emailSelectReturn" : "返回",
	"VRD_emailSelectSend" : "发送",
	"VRD_emailSelectSenderName" : "{senderName}",
	"VRD_emnaviAcceptAvoidance" : "确认",
	"VRD_emnaviAddCurrentPosToFavourites" : "将当前位置添加到收藏夹",
	"VRD_emnaviAddWaypointCityCenter" : "添加路标城市中心",
	"VRD_emnaviAddWaypointDistrictCenter" : "添加路标区中心",
	"VRD_emnaviAddWaypointFavorite" : "添加路标收藏夹",
	"VRD_emnaviAddWaypointPOI" : "添加路标 {poiHypList}",
	"VRD_emnaviAvoidRouteAhead" : "避开前方路线",
	"VRD_emnaviCancelRoute" : "取消路线",
	"VRD_emnaviDecreaseAvoidanceLength" : "更短",
	"VRD_emnaviGoToCockpit" : "开始",
	"VRD_emnaviIncreaseAvoidanceLength" : "更长",
	"VRD_emnaviJPJ_VDEHypothesisList" : "城市名称",
	"VRD_emnaviNavigateHere" : "导航到这里",
	"VRD_emnaviNavigateHome" : "导航到家",
	"VRD_emnaviNavigateToARecentDestination" : "导航到最近目的地",
	"VRD_emnaviNavigateToAddress" : "导航到地址",
	"VRD_emnaviNavigateToCityCenter" : "导航到城市中心",
	"VRD_emnaviNavigateToDistrictCenter" : "导航到区中心",
	"VRD_emnaviNavigateToFavorite" : "导航到收藏夹",
	"VRD_emnaviNavigateToPOI" : "导航到 {poiHypList}",
	"VRD_emnaviNewDestination" : "新目的地",
	"VRD_emnaviRepeatInstruction" : "重复指令",
	"VRD_emnaviRouteSummary" : "路线概览",
	"VRD_emnaviSelectCancelRoute" : "清除路线",
	"VRD_emnaviSelectNavigateToAddress" : "导航到地址",
	"VRD_emnaviSimpleHypothesisList" : "州的名称",
	"VRD_emnaviStepByStep" : "逐步输入",
	"VRD_emnaviTravelViaARecentDestination" : "添加路标最近目的地",
	"VRD_emnaviTravelViaAddress" : "途径地址",
	"VRD_emnaviTravelViaHome" : "途径家",
	"VRD_emnaviTryAgain" : "重试",
	"VRD_emnaviUniSimpleHypothesisList" : "地址",
	"VRD_emnaviUniVDEHypothesisList" : "地址",
	"VRD_emnaviVDEHypothesisList" : "地址",
	"VRD_emnaviWhereAmI" : "我在哪儿",
	"VRD_emnaviZoomIn" : "放大",
	"VRD_emnaviZoomOut" : "缩小",
	"VRD_fmradioPlayStationFrequency" : "调到 {frequency} FM",
	"VRD_fmradioSelectAutoMemory" : "自动记忆",
	"VRD_fmradioSelectChangeGenre" : "更改类型",
	"VRD_fmradioSelectFMSettings" : "FM 设置",
	"VRD_fmradioSelectFavorites" : "收藏夹",
	"VRD_fmradioSelectGenreSeek" : "类型搜索",
	"VRD_fmradioSelectHDChannel" : "{HD Channel}",
	"VRD_fmradioSelectHDChannels" : "HD电台",
	"VRD_fmradioSelectHDRadio" : "HD 广播",
	"VRD_fmradioSelectHDRadioOff" : "关闭 HD Radio",
	"VRD_fmradioSelectHDRadioOn" : "打开 HD Radio",
	"VRD_fmradioSelectScanOff" : "扫描关闭",
	"VRD_fmradioSelectScanOn" : "扫描开启",
	"VRD_fmradioSelectSeekNext" : "搜索下一个",
	"VRD_fmradioSelectSeekPrevious" : "搜索上一个",
	"VRD_fmradioSelectSettings" : "声音设置",
	"VRD_fmradioSelectSource" : "娱乐 / 更改来源",
	"VRD_fmradioSelectStationAll" : "所有电台",
	"VRD_fmradioSelectStationFrequency" : "{frequency}",
	"VRD_fmradioSelectStationGenre" : "{genreName}",
	"VRD_fmradioSelectStationList" : "电台列表",
	"VRD_fmradioSelectStationName" : "{stationName}",
	"VRD_fmradioSelectTrafficAlert" : "交通警告 (TA)",
	"VRD_fmradioSelectTrafficAlertOff" : "流量关闭",
	"VRD_fmradioSelectTrafficAlertOn" : "流量开启",
	"VRD_fmradioSelectTune" : "调台",
	"VRD_fmradioSelectUpdateAutoMemory" : "更新自动记忆",
	"VRD_fmradioSelectiTunesTagging" : "iTunes 标记",
	"VRD_fmradioTuneDown" : "向下调台",
	"VRD_fmradioTuneUp" : "向上调台",
	"VRD_fmradioTurnOffAF" : "关闭替代频率",
	"VRD_fmradioTurnOffREG" : "关闭地区锁",
	"VRD_fmradioTurnOnAF" : "打开替代频率",
	"VRD_fmradioTurnOnREG" : "打开地区锁",
	"VRD_fmradioUpdateAutoMemory" : "更新电台列表",
	"VRD_pandoraAddStation" : "添加电台",
	"VRD_pandoraAddStationFromArtist" : "创建艺术家站",
	"VRD_pandoraAddStationFromSong" : "创建歌站",
	"VRD_pandoraAddToFavorites" : "添加到收藏夹",
	"VRD_pandoraBookmarkArtist" : "对艺术家设置书签",
	"VRD_pandoraBookmarkSong" : "对歌曲设置书签",
	"VRD_pandoraCreateStation" : "创建电台",
	"VRD_pandoraSelectAddCurrentStation" : "添加到收藏夹",
	"VRD_pandoraSelectDelete" : "删除",
	"VRD_pandoraSelectEditDelete" : "删除",
	"VRD_pandoraSelectEditMove" : "移动",
	"VRD_pandoraSelectEditReplace" : "更换",
	"VRD_pandoraSelectFavorites" : "收藏夹",
	"VRD_pandoraSelectMove" : "移动",
	"VRD_pandoraSelectQuickMix" : "随机播放",
	"VRD_pandoraSelectSettings" : "声音设置",
	"VRD_pandoraSelectSortBy" : "排序",
	"VRD_pandoraSelectSource" : "娱乐",
	"VRD_pandoraSelectStationList" : "电台列表",
	"VRD_pandoraShowBookmarkOptions" : "书签",
	"VRD_pandoraShowByAZ" : "按字母顺序排序",
	"VRD_pandoraShowByDate" : "按日期排序",
	"VRD_pandoraSkip" : "跳过",
	"VRD_pandoraThumbsDown" : "不喜欢",
	"VRD_pandoraThumbsUp" : "喜欢",
	"VRD_phoneCall" : "呼叫",
	"VRD_phoneCallBack" : "回拨",
	"VRD_phoneCallByName" : "按姓名呼叫",
	"VRD_phoneCallByNumber" : "按号码呼叫",
	"VRD_phoneCallContactType" : "呼叫{contactName}{contactType}",
	"VRD_phoneCallLast" : "呼叫上次来电",
	"VRD_phoneChooseContactType" : "{contactType}{contactName}日",
	"VRD_phoneDialAnyNumber" : "呼叫{number}",
	"VRD_phoneDialpadClearAllDigits" : "清除所有数字",
	"VRD_phoneDialpadDeleteDigit" : "删除",
	"VRD_phoneDialpadPhoneNumber" : "{phoneNumber}",
	"VRD_phoneReDial" : "重拨",
	"VRD_phoneSelectByName" : "名称",
	"VRD_phoneSelectByNumber" : "号码",
	"VRD_phoneSelectContactType" : "{contactType}",
	"VRD_phoneSelectDialPad" : "拨号盘",
	"VRD_phoneSelectFavorites" : "收藏夹",
	"VRD_phoneSelectRecentCalls" : "最近呼叫",
	"VRD_phoneSelectRecentCallsAll" : "所有通话",
	"VRD_phoneSelectRecentCallsMissed" : "未接来电",
	"VRD_satradioBackSpaceDelete" : "删除数字",
	"VRD_satradioChangeLockCode" : "更改 PIN 码",
	"VRD_satradioEnterPIN" : "{4digitPin}",
	"VRD_satradioInitializeLockCode" : "PIN 码初始化",
	"VRD_satradioPlayChannelName" : "播放 {channelName}",
	"VRD_satradioPlayStationNumber" : "调到 {channelNumber}",
	"VRD_satradioResetLockCode" : "重设验证密码",
	"VRD_satradioSeekNext" : "搜索下一个",
	"VRD_satradioSeekPrevious" : "搜索上一个",
	"VRD_satradioSelectChangeCategory" : "类别",
	"VRD_satradioSelectFavorites" : "收藏夹",
	"VRD_satradioSelectParentalLock" : "家长锁",
	"VRD_satradioSelectScanOff" : "扫描关闭",
	"VRD_satradioSelectScanOn" : "扫描开启",
	"VRD_satradioSelectSettings" : "声音设置",
	"VRD_satradioSelectSource" : "娱乐",
	"VRD_satradioSelectStation" : "电台 {Station number}",
	"VRD_satradioSelectStationAll" : "所有频道",
	"VRD_satradioSelectStationCategory" : "{categoryName}",
	"VRD_satradioSelectStationList" : "频道列表",
	"VRD_satradioTurnChannelLockOFF" : "解锁当前频道",
	"VRD_satradioTurnChannelLockON" : "锁定当前频道",
	"VRD_satradioTurnParentalLockOFF" : "关闭会话锁",
	"VRD_satradioTurnParentalLockON" : "打开会话锁",
	"VRD_smsCallPhoneNumber" : "呼叫",
	"VRD_smsDelete" : "删除",
	"VRD_smsImportMessages" : "更新文本收件箱",
	"VRD_smsReply" : "回复",
	"VRD_smsSayAnyConversation" : "{senderName}",
	"VRD_smsSelectBody" : "添加消息",
	"VRD_smsSelectContactName" : "{ContactName}",
	"VRD_smsSelectContinueTextMessage" : "继续消息",
	"VRD_smsSelectDiscard" : "放弃",
	"VRD_smsSelectInbox" : "短信收件箱列表",
	"VRD_smsSelectNone" : "这些都不是",
	"VRD_smsSelectRetry" : "重试",
	"VRD_smsSelectReturn" : "返回",
	"VRD_smsSelectSend" : "发送",
	"VRD_stitcherAddToFavorites" : "添加到收藏夹",
	"VRD_stitcherRemoveFromFavorites" : "从收藏夹中移除",
	"VRD_stitcherSaveFavorites" : "保存更改",
	"VRD_stitcherSelectSettings" : "声音设置",
	"VRD_stitcherSelectSource" : "娱乐",
	"VRD_stitcherSelectStationList" : "电台列表",
	"VRD_stitcherThumbsDown" : "不喜欢",
	"VRD_stitcherThumbsUp" : "喜欢",
	"VRD_systemSelectAhaRadio" : "Aha Radio",
	"VRD_systemSelectAndroidAuto" : "Android Auto",
	"VRD_systemSelectApplications" : "应用程序",
	"VRD_systemSelectAuxIn" : "线路输入/辅助接口",
	"VRD_systemSelectBTAudio" : "Bluetooth",
	"VRD_systemSelectCD" : "CD",
	"VRD_systemSelectCallHistory" : "通话记录",
	"VRD_systemSelectCarPlay" : "Apple CarPlay",
	"VRD_systemSelectCommunication" : "通讯",
	"VRD_systemSelectConnect" : "连接",
	"VRD_systemSelectContacts" : "联系人",
	"VRD_systemSelectDAB" : "DAB",
	"VRD_systemSelectDVD" : "DVD",
	"VRD_systemSelectDisplayClock" : "时钟显示",
	"VRD_systemSelectDisplayOff" : "显示关闭",
	"VRD_systemSelectEmail" : "电子邮件",
	"VRD_systemSelectEntertainment" : "娱乐",
	"VRD_systemSelectEntertainmentMenu" : "娱乐菜单",
	"VRD_systemSelectFavorites" : "收藏夹",
	"VRD_systemSelectNavigation" : "导航",
	"VRD_systemSelectNotifications" : "短信",
	"VRD_systemSelectNotifyOff" : "通知关闭",
	"VRD_systemSelectPandora" : "Pandora",
	"VRD_systemSelectPhone" : "电话",
	"VRD_systemSelectRadioAM" : "AM 收音机",
	"VRD_systemSelectRadioFM" : "FM 收音机",
	"VRD_systemSelectRetry" : "重试",
	"VRD_systemSelectSatRadio" : "卫星无线电",
	"VRD_systemSelectSettings" : "设置",
	"VRD_systemSelectSiri" : "Siri",
	"VRD_systemSelectSms" : "文本/短信",
	"VRD_systemSelectStitcher" : "Stitcher",
	"VRD_systemSelectTV" : "TV",
	"VRD_systemSelectTrafficAlert" : "交通警告 (TA)",
	"VRD_systemSelectTutorial" : "教程",
	"VRD_systemSelectUSB" : "USB",
	"VRD_systemSelectUSBA" : "USB 1",
	"VRD_systemSelectUSBB" : "USB 2",
	"VRD_systemSelectXmAudio" : "SXM Radio",
	"VRD_tvSelectView" : "查看",
	"VRD_usbaudioBrowse" : "浏览",
	"VRD_usbaudioBrowseAlbum" : "浏览 {albumName}",
	"VRD_usbaudioBrowseAlbums" : "浏览专辑",
	"VRD_usbaudioBrowseAll" : "浏览所有歌曲、唱片集或艺术家",
	"VRD_usbaudioBrowseAnyAlbum" : "浏览 [唱片集] {albumName}",
	"VRD_usbaudioBrowseAnyArtist" : "浏览 [艺术家] {artistName}",
	"VRD_usbaudioBrowseAnyFolder" : "浏览文件夹 {folderName}",
	"VRD_usbaudioBrowseArtist" : "浏览 {artistName}",
	"VRD_usbaudioBrowseArtists" : "浏览艺术家",
	"VRD_usbaudioBrowseAudiobooks" : "浏览有声读物",
	"VRD_usbaudioBrowseFolder" : "浏览 {folderName}",
	"VRD_usbaudioBrowseFolders" : "浏览文件夹",
	"VRD_usbaudioBrowseGenre" : "浏览 [流派] {genreName}",
	"VRD_usbaudioBrowseGenres" : "浏览流派",
	"VRD_usbaudioBrowseLineNumber" : "浏览线路 {lineNumber}",
	"VRD_usbaudioBrowsePlaylist" : "浏览播放列表 {playlistName}",
	"VRD_usbaudioBrowsePlaylists" : "浏览播放列表",
	"VRD_usbaudioBrowsePodcast" : "浏览播客 {podcastName}",
	"VRD_usbaudioBrowsePodcasts" : "浏览播客",
	"VRD_usbaudioBrowseSongs" : "浏览歌曲",
	"VRD_usbaudioChooseAlbumArtist" : "{artistName}",
	"VRD_usbaudioGenerateMoreLikeThis" : "更喜欢这首",
	"VRD_usbaudioPlayAlbums" : "播放唱片集",
	"VRD_usbaudioPlayAll" : "播放所有",
	"VRD_usbaudioPlayAnyAlbum" : "播放 [唱片集] {albumName}",
	"VRD_usbaudioPlayAnyArtist" : "播放[艺术家] {artistName}",
	"VRD_usbaudioPlayAnyFolder" : "播放文件夹 {folderName}",
	"VRD_usbaudioPlayArtistAlbum" : "播放 {artistName} {albumName}",
	"VRD_usbaudioPlayArtists" : "播放艺术家",
	"VRD_usbaudioPlayAudiobook" : "播放有声读物 {AudiobookName}",
	"VRD_usbaudioPlayAudiobooks" : "播放有声读物",
	"VRD_usbaudioPlayChapter" : "{chapterName}",
	"VRD_usbaudioPlayChapterIndex" : "播放章节 {index} {chapter}",
	"VRD_usbaudioPlayEpisode" : "{episodeName}",
	"VRD_usbaudioPlayFolder" : "播放 {folderName}",
	"VRD_usbaudioPlayFolders" : "播放文件夹",
	"VRD_usbaudioPlayGenre" : "播放 [流派] {genreName}",
	"VRD_usbaudioPlayGenres" : "播放流派",
	"VRD_usbaudioPlayLineNumber" : "播放 [线路] {lineNumber}",
	"VRD_usbaudioPlayPlaylist" : "播放播放列表 {playlistName}",
	"VRD_usbaudioPlayPlaylists" : "播放播放列表",
	"VRD_usbaudioPlayPodcast" : "播放播客 {PodcastName}",
	"VRD_usbaudioPlayPodcasts" : "播放播客",
	"VRD_usbaudioPlaySongs" : "播放歌曲",
	"VRD_usbaudioRepeat" : "重复",
	"VRD_usbaudioRepeatAll" : "重复全部",
	"VRD_usbaudioRepeatOff" : "关闭重复",
	"VRD_usbaudioRepeatSong" : "重复播放歌曲",
	"VRD_usbaudioRewind" : "倒带",
	"VRD_usbaudioSelectAlbum" : "唱片机 {albumName}",
	"VRD_usbaudioSelectAlbums" : "唱片集",
	"VRD_usbaudioSelectAll" : "所有剧集、章节、歌曲、唱片集或艺术家",
	"VRD_usbaudioSelectArtist" : "艺术家 {artistName}",
	"VRD_usbaudioSelectArtists" : "艺术家",
	"VRD_usbaudioSelectAudiobook" : "{audiobookName}",
	"VRD_usbaudioSelectAudiobooks" : "有声读物",
	"VRD_usbaudioSelectFolder" : "文件夹 {folderName}",
	"VRD_usbaudioSelectFolders" : "文件夹",
	"VRD_usbaudioSelectGenre" : "流派 {genreName}",
	"VRD_usbaudioSelectGenres" : "流派",
	"VRD_usbaudioSelectPlaylist" : "播放列表 {playlistName}",
	"VRD_usbaudioSelectPlaylists" : "播放列表",
	"VRD_usbaudioSelectPodcast" : "{podcastName}",
	"VRD_usbaudioSelectPodcasts" : "播客",
	"VRD_usbaudioSelectRootFolder" : "根菜单",
	"VRD_usbaudioSelectSettings" : "声音设置",
	"VRD_usbaudioSelectSongs" : "歌曲",
	"VRD_usbaudioSelectSourceMenu" : "娱乐",
	"VRD_usbaudioShuffle" : "随机播放",
	"VRD_usbaudioShuffleOff" : "关闭随机播放",
	"VRD_usbaudioShuffleOn" : "开启随机播放",
	"VRD_usbaudioSongList" : "歌曲列表",
	"VRD_xmaudioBackSpaceDelete" : "删除数字",
	"VRD_xmaudioChangeLockCode" : "编辑 PIN 码",
	"VRD_xmaudioConfirmDelete" : "删除",
	"VRD_xmaudioEnterPIN" : "{fourDigitPIN}",
	"VRD_xmaudioPlayChannelName" : "播放 XM 频道 {channelName}",
	"VRD_xmaudioPlayStationNumber" : "调到 {channelNumber}",
	"VRD_xmaudioResetLockCode" : "重设验证密码",
	"VRD_xmaudioSelectCallXM" : "呼叫 XM",
	"VRD_xmaudioSelectChangeCategory" : "更改类别",
	"VRD_xmaudioSelectContinueListening" : "继续收听",
	"VRD_xmaudioSelectDismiss" : "取消",
	"VRD_xmaudioSelectEveryOccurance" : "每个事件",
	"VRD_xmaudioSelectEveryOtherReport" : "每份其他报告",
	"VRD_xmaudioSelectEveryReport" : "每份报告",
	"VRD_xmaudioSelectExitTuneMix" : "退出 TuneMix",
	"VRD_xmaudioSelectFavorites" : "收藏夹",
	"VRD_xmaudioSelectListenNow" : "现在收听",
	"VRD_xmaudioSelectMove" : "移动",
	"VRD_xmaudioSelectNearestCity" : "最近的城市",
	"VRD_xmaudioSelectOnlyFirstAfterVehicleStart" : "车辆启动",
	"VRD_xmaudioSelectOnlyFirstOccuranceInGame" : "首个事件",
	"VRD_xmaudioSelectReplayAlert" : "重新启动警报",
	"VRD_xmaudioSelectReturnToPrevious" : "返回上一个",
	"VRD_xmaudioSelectSFSportBaseball" : "棒球",
	"VRD_xmaudioSelectSFSportNCAA" : "高校橄榄球",
	"VRD_xmaudioSelectSFSportNFL" : "职业橄榄球",
	"VRD_xmaudioSelectSFSportNHL" : "冰球",
	"VRD_xmaudioSelectScanOff" : "扫描关闭",
	"VRD_xmaudioSelectScanOn" : "扫描开启",
	"VRD_xmaudioSelectSettings" : "设置",
	"VRD_xmaudioSelectSoundSettings" : "声音设置",
	"VRD_xmaudioSelectSource" : "娱乐",
	"VRD_xmaudioSelectStation" : "电台 {channelNumber}",
	"VRD_xmaudioSelectStationAll" : "所有频道",
	"VRD_xmaudioSelectStationCategory" : "{categoryName}",
	"VRD_xmaudioSelectStationFeaturedFavorites" : "推荐收藏夹",
	"VRD_xmaudioSelectStationList" : "频道",
	"VRD_xmaudioSelectTuneMix" : "TuneMix",
	"VRD_xmaudioSelectTuneMixChannel" : "TuneMix 频道选项",
	"VRD_xmaudioSelectTuneMixChannelsOptions" : "频道选项",
	"VRD_xmaudioSelectTuneMixCreation" : "创建新 TuneMix 频道",
	"VRD_xmaudioSelectTuneMixEdit" : "编辑 TuneMix 频道",
	"VRD_xmaudioSelectTuneMixEditOps" : "TuneMix 编辑选项",
	"VRD_xmaudioSelectTuneMixRemove" : "移除 TuneMix 频道",
	"VRD_xmaudioSelectTuneMixRename" : "重命名 TuneMix",
	"VRD_xmaudioSelectTurnAlertsOff" : "关闭警告",
	"VRD_xmaudioSelectiTunesTagging" : "iTunes 标记",
	"VRD_xmaudioSetChannelLock" : "锁定频道",
	"VRD_xmaudioSetParentalLock" : "会话锁定",
	"VRD_xmdataSelectFuelPrices" : "燃油价格",
	"VRD_xmdataSelectMovies" : "电影",
	"VRD_xmdataSelectParking" : "停车",
	"VRD_xmdataSelectSports" : "体育",
	"VRD_xmdataSelectStock" : "股票",
	"VRD_xmdataSelectTrafficPlus" : "交通加",
	"VRD_xmdataSelectWeatherForecast" : "天气预报",
	"VRD_xmdataSelectWeatherRadar" : "气象雷达",
	"VRD_xmdataSelectWeatherSecurityAlerts" : "天气安全预警",
};

framework.registerAppDictLoaded("system", "zh_CN");