var __VrHelpPositionTable__systemAppDict_pt_PT = {
	"HomeScreen_Help" : {
		"Right" : ["VrHelp_Favorites"],
		"Left" : ["VrHelp_Entertainment","VrHelp_Communication","VrHelp_Navigation","VrHelp_Settings","VrHelp_Applications"]
	}
};

var Localization_systemAppDict_pt_PT = {
	//"stringId" : "localString"
	"ActiveCallItem" : "Chamada Activa",
	"AhaMaintError" : "Erro de Manutenção da aha",
	"AhaRadio" : "aha",
	"AmRadio" : "AM",
	"AndroidAuto" : "Android Auto",
	"Applications" : "Aplicações",
	"AudioSourceNotAvailableBTAudio" : "Áudio Bluetooth Não Disponível",
	"AudioSourceNotAvailableCD" : "O CD foi retirado",
	"AudioSourceNotAvailableDVD" : "O DVD foi retirado",
	"AudioSourceNotAvailableTV" : "TV Não Disponível",
	"AudioSourceNotAvailableUSB" : "O dispositivo USB foi alterado",
	"AuxIn" : "AUX",
	"BT" : "BT",
	"Bluetooth" : "Bluetooth",
	"BluetoothWithDevice" : "Bluetooth - {deviceName}",
	"CallHistory" : "Histórico de Chamadas",
	"CarPlay" : "Apple CarPlay",
	"CdPlayer" : "CD",
	"ChannelOffAir" : "Canal Fora de Emissão",
	"ChannelUnauth" : "Canal Não Autorizado",
	"CheckAntenna" : "Verificar Antena",
	"CheckTuner" : "Verificar Sintonizador",
	"Communication" : "Comunicação",
	"Connect" : "Ligar",
	"Contacts" : "Contactos",
	"DVDItem" : "DVD",
	"DabRadio" : "DAB",
	"DialPhone" : "Marcar",
	"DidYouSay" : "Quis dizer:",
	"DisclaimerText" : "A distracção pode originar acidentes. Não utilize durante a condução. Concentre-se sempre na condução e respeite as regras de trânsito. Consulte o Manual de Utilizador.",
	"DisconnectThenReconnect" : "Erro ao iniciar Siri. Desligar e Lig. Novam. Apple Device.",
	"DriveRecord" : "Registo de condução",
	"DriverIDItem" : "Identificação do Condutor",
	"EcoenergyApp" : "Poupança Combustível",
	"EcoenergyAppHEV" : "Monitor de Condução",
	"Email" : "Correio Electrónico",
	"EngineOilLevel" : "Nível óleo do motor",
	"Entertainment" : "Entretenimento",
	"ErrorWhileStartingSiri" : "Erro ao iniciar o Siri.",
	"FailedNotificationRetrieval" : "Não é possível obter a Lista de Notificações",
	"FavoritesItem" : "Favoritos",
	"FmRadio" : "FM",
	"HDTrafficItem" : "Mapa de Trânsito HD Radio™",
	"InitiateSiri" : "Prima continuamente o Botão Falar para iniciar a sessão do Siri",
	"IntelligentDriveMasterItem" : "i-DM",
	"NavigationTitle" : "Navegação",
	"NoConnectionNotifyText" : "Pretende ligar um telefone agora?",
	"NoConnectionNotifyTitle" : "Nenhum Telefone Ligado",
	"NoDeviceText" : "Pretende ligar um dispositivo agora?",
	"NoDeviceTitle" : "Nenhum Dispositivo Ligado",
	"Notifications" : "Notificações",
	"NotifyIgnore" : "Ignorar",
	"NotifyIncomingMsg" : "Mensagem Recebida de:",
	"NotifyOff" : "Notif. Deslig.",
	"NotifyRead" : "Ler",
	"NotifyReadNow" : "Pretende ler agora?",
	"Pandora" : "Pandora",
	"ReconnectAhaRadio" : "A rest. lig. áudio Bluetooth p/ Rádio aha",
	"ReconnectBTAudio" : "A rest. áudio Bluetooth p/retomar repr",
	"ReconnectCD" : "A verificar CD p/ retomar reprodução",
	"ReconnectCarPlay" : "A retomar Apple CarPlay.",
	"ReconnectDVD" : "A verif. DVD p/ retomar a reprodução",
	"ReconnectEntMenuButton" : "Menu Entretenimento",
	"ReconnectFailedBTAudio" : "Não é Possível Voltar a Ligar Áudio Bluetooth",
	"ReconnectFailedCD" : "O CD foi retirado. Não é possível retomar a reprodução.",
	"ReconnectFailedCarPlay" : "Impossível voltar a ligar Apple CarPlay",
	"ReconnectFailedDVD" : "O DVD foi retirado. Não é possível retomar a reprodução.",
	"ReconnectFailedTV" : "TV Não disponível. Impossível retomar reprodução.",
	"ReconnectFailedUSB" : "O dispositivo USB foi alterado. Não é possível retomar a reprodução.",
	"ReconnectPandora" : "A restab. lig. áudio Bluetooth p/ Pandora",
	"ReconnectStitcher" : "A restab. lig. áudio Bluetooth p/ Stitcher",
	"ReconnectTV" : "A verificar TV para retomar a reprodução",
	"ReconnectUSB" : "A rest lig dispos USB p/ retomar reprod",
	"RetryLabel" : "Tentar Novamente",
	"SchedMaintenanceApp" : "Manutenção",
	"ScreenReplication" : "Replicação de Ecrã",
	"SdarsRadio" : "XM",
	"Settings" : "Definições",
	"SettingsCommunication" : "Definições",
	"Siri" : "Siri",
	"SiriDisabled" : "Siri desativada no dispositivo Apple.",
	"Sms" : "SMS",
	"StitcherItem" : "Stitcher",
	"TVItem" : "TV",
	"TempWarning" : "Aviso de Temperatura",
	"TempWarningText" : "O ecrã está demasiado quente. O ecrã tem um desempenho reduzido até arrefecer.",
	"TextDownloaded" : "SMS Transferido",
	"TextSent" : "SMS Enviado",
	"TrafficAlertsItem" : "Informações de Trânsito",
	"USB" : "USB",
	"USB1AndroidAuto" : "USB 1 - Android Auto",
	"USB1CarPlay" : "USB 1 - Apple CarPlay",
	"USB2AndroidAuto" : "USB 2 - Android Auto",
	"UsbAudioA" : "USB 1",
	"UsbAudioAWithDevice" : "USB 1 - {deviceName}",
	"UsbAudioB" : "USB 2",
	"UsbAudioBWithDevice" : "USB 2 - {deviceName}",
	"UseCommander" : "Use o comando durante a condução.",
	"VehicleDataTransferItem" : "Transferência Dados ",
	"VehicleStatusMonitor" : "Monitor estado",
	"VehicleTelemetryTransfer" : "Transferência Dados",
	"VideoSignalLost" : "Sinal de Vídeo Perdido",
	"VoiceNotSupported" : "Sem suporte a voz. ",
	"VoiceRecognition" : "Reconhecimento de Voz",
	"VrHelp_Applications" : "Aplicações",
	"VrHelp_Communication" : "Comunicação",
	"VrHelp_Entertainment" : "Entretenimento",
	"VrHelp_Favorites" : "Favoritos",
	"VrHelp_Navigation" : "Navegação",
	"VrHelp_Settings" : "Definições",
	"WarnGuidanceApp" : "Ajuda de Avisos",
	"WarningTitle" : "AVISO!",
	"XMAudio" : "SXM",
	"XMData" : "SXM Services",
	"agree" : "Aceito",
	"VRD_aharadioSelectCall" : "Chamar",
	"VRD_aharadioSelectDiscard" : "Rejeitar",
	"VRD_aharadioSelectEpisodes" : "Lista de Episódios",
	"VRD_aharadioSelectLBSTab" : "Próximo",
	"VRD_aharadioSelectMainList" : "Lista Principal Aha",
	"VRD_aharadioSelectMap" : "Mapa",
	"VRD_aharadioSelectPresetsTab" : "Predefinir",
	"VRD_aharadioSelectSave" : "Guardar",
	"VRD_aharadioSelectSettings" : "Definições de Som",
	"VRD_aharadioSelectShout" : "Gritar",
	"VRD_aharadioSelectSource" : "Entretenimento / Alterar Origem",
	"VRD_aharadioSelectThumbsDown" : "Desaprovar",
	"VRD_aharadioSelectThumbsUp" : "Aprovar",
	"VRD_amradioPlayStationFrequency" : "Sintonizar {frequency} AM",
	"VRD_amradioSelectAutoMemory" : "Memória Automática",
	"VRD_amradioSelectFavorites" : "Favoritos",
	"VRD_amradioSelectHD" : "Estações HD",
	"VRD_amradioSelectHDOff" : "Rádio HD Desactivado",
	"VRD_amradioSelectHDOn" : "Rádio HD Activado",
	"VRD_amradioSelectScanOff" : "Análise Desactivada",
	"VRD_amradioSelectScanOn" : "Análise Activada",
	"VRD_amradioSelectSeekNext" : "Procurar Seguinte",
	"VRD_amradioSelectSeekPrevious" : "Procurar Anterior",
	"VRD_amradioSelectSettings" : "Definições de Som",
	"VRD_amradioSelectSource" : "Ir para Menu de Entretenimento",
	"VRD_amradioSelectStationFrequency" : "{AMFrequency}",
	"VRD_amradioSelectTrafficAlert" : "Alerta de Trânsito",
	"VRD_amradioSelectTrafficAlertOff" : "Alerta de Trânsito Desactivado",
	"VRD_amradioSelectTrafficAlertOn" : "Alerta de Trânsito Activado",
	"VRD_amradioSelectTune" : "Sintonizar",
	"VRD_amradioSelectUpdateAutoMemory" : "Procura de Memória Automática",
	"VRD_amradioSelectiTunesTagging" : "Marcação do iTunes",
	"VRD_amradioTuneDown" : "Sintonizar para Baixo",
	"VRD_amradioTuneUp" : "Sintonizar para Cima",
	"VRD_amradioUpdateAutoMemory" : "Actualizar Lista de Estações",
	"VRD_auxinSelectSettings" : "Definições de Som",
	"VRD_auxinSelectSource" : "Entretenimento / Alterar Origem",
	"VRD_btaudioScanPlay" : "Procurar Reproduzir",
	"VRD_btaudioSelectConnect" : "Ligar",
	"VRD_btaudioSelectRootMenu" : "Menu de Raiz",
	"VRD_btaudioSelectSettings" : "Definições de Som",
	"VRD_btaudioSelectSource" : "Ir para Menu de Entretenimento",
	"VRD_btaudioToggleRepeat" : "Repetir",
	"VRD_btaudioToggleShuffle" : "Aleatório",
	"VRD_carplaySelectApplications" : "Aplicações",
	"VRD_cdGoSettings" : "Definições de Som",
	"VRD_cdHandleStartScan" : "Iniciar Procurar",
	"VRD_cdPlayBeginning" : "Recomeçar",
	"VRD_cdRepeatFolder" : "Repetir Pasta",
	"VRD_cdRepeatOff" : "Repetir Desactivado",
	"VRD_cdRepeatOn" : "Repetir Activado",
	"VRD_cdRepeatTrack" : "Repetir Faixa",
	"VRD_cdSelectCurrentFolder" : "Pasta Actual",
	"VRD_cdSelectRepeat" : "Repetir",
	"VRD_cdSelectRootFolder" : "Menu de Raiz",
	"VRD_cdSelectShuffle" : "Aleatório",
	"VRD_cdSelectSource" : "Ir para Menu de Entretenimento",
	"VRD_cdSelectTrackList" : "Lista de Faixas",
	"VRD_cdSelectTrackNumber" : "Reproduzir Faixa {Number}",
	"VRD_cdShuffleDisk" : "Reprodução Aleatória do Disco ",
	"VRD_cdShuffleFolder" : "Reprodução Aleatória da Pasta",
	"VRD_cdShuffleOff" : "Reprodução Aleatória Desactivada",
	"VRD_cdShuffleOn" : "Aleatório Activado",
	"VRD_commonAddToFavorites" : "Adicionar aos Favoritos",
	"VRD_commonCancel" : "Cancelar",
	"VRD_commonFastForward" : "Avançar",
	"VRD_commonGoBack" : "Retroceder",
	"VRD_commonIntentParent" : "Principal",
	"VRD_commonIntentParentUSBAudio" : "Principal",
	"VRD_commonIntentUSBAudio" : "Casa",
	"VRD_commonIntentUSBAudioBG" : "Casa",
	"VRD_commonMenuUp" : "Para Cima no Menu",
	"VRD_commonNext" : "Seguinte",
	"VRD_commonNo" : "Não",
	"VRD_commonPageDown" : "Página Abaixo / Deslocar para Baixo",
	"VRD_commonPageUp" : "Página Acima / Deslocar para Cima",
	"VRD_commonPause" : "Pausa",
	"VRD_commonPrevious" : "Anterior",
	"VRD_commonResume" : "Reproduzir / Retomar",
	"VRD_commonRewind" : "Recuar",
	"VRD_commonSelectLineNumber" : "Linha {lineNumber}",
	"VRD_commonYes" : "Sim / OK",
	"VRD_contactsChooseContactName" : "{ContactName}",
	"VRD_contactsDisambiguateContactName" : "Mostrar {ContactName}",
	"VRD_contactsImportAll" : "Importar Todos os Contactos",
	"VRD_contactsImportCancel" : "Canc. Import.",
	"VRD_contactsImportContacts" : "Editar Contactos",
	"VRD_contactsImportSingle" : "Importar Contacto Seleccionado",
	"VRD_contactsRemoveContact" : "Remover Contacto",
	"VRD_contactsSelectCall" : "Chamar",
	"VRD_contactsSelectContactName" : "{ContactName}",
	"VRD_contactsSelectDownload" : "Transferir",
	"VRD_contactsSelectFavorites" : "Favoritos",
	"VRD_contactsSelectNone" : "Nenhum destes",
	"VRD_contactsSelectReadContactName" : "Ler Nome de Contacto",
	"VRD_contactsSelectRemove" : "Remover",
	"VRD_contactsSelectRetry" : "Tentar Novamente",
	"VRD_contactsSendPhoneType" : "{phoneType}",
	"VRD_contactsShowAddress" : "Endereço",
	"VRD_dabDisplayDABSettings" : "Definições DAB",
	"VRD_dabDisplayEnsembleList" : "Seleccionar conjunto de estações",
	"VRD_dabDisplayStationList" : "Lista de Estações",
	"VRD_dabSelectFavorites" : "Favoritos",
	"VRD_dabSelectScan" : "Procurar",
	"VRD_dabSelectSeekNext" : "Seguinte",
	"VRD_dabSelectSeekPrevious" : "Anterior",
	"VRD_dabSelectSettings" : "Definições de Som",
	"VRD_dabSelectSource" : "Entretenimento",
	"VRD_dabTAToggleOFF" : "Trânsito Desactivado",
	"VRD_dabTAToggleON" : "Trânsito Activado",
	"VRD_dabTAToggleVois" : "Anúncio de Tráfego (TA)",
	"VRD_dabUpdateStationList" : "Actualizar Lista",
	"VRD_dvdClearPin" : "Eliminar Dígitos",
	"VRD_dvdSayGRating" : "G",
	"VRD_dvdSayPG12" : "Maiores de 12",
	"VRD_dvdSayR15" : "Maiores de 15",
	"VRD_dvdSayR18" : "--",
	"VRD_dvdSelectAspectRatio" : "Proporção",
	"VRD_dvdSelectAudioSettings" : "Definições de Vídeo",
	"VRD_dvdSelectCameraAngle" : "Ângulo da Câmara",
	"VRD_dvdSelectEditPin" : "Editar Código PIN",
	"VRD_dvdSelectParentLock" : "Limitação de Acesso",
	"VRD_dvdSelectParentLockOff" : "Limitação de Acesso Desactivada",
	"VRD_dvdSelectParentLockOn" : "Limitação de Acesso Activada",
	"VRD_dvdSelectParentLockRating" : "Classif. da Limitação de Acesso",
	"VRD_dvdSelectResetPin" : "Repor Código PIN",
	"VRD_dvdSelectRootMenu" : "Menu de Raiz",
	"VRD_dvdSelectSettings" : "Definições de Som",
	"VRD_dvdSelectSource" : "Entretenimento",
	"VRD_dvdSelectSubtitleOff" : "Legendas Desactivadas",
	"VRD_dvdSelectSubtitleOn" : "Legendas Activadas",
	"VRD_dvdSlowForward" : "Avançar",
	"VRD_dvdSlowRewind" : "Recuar",
	"VRD_dvdVUISendPin" : "{FourDigitPin}",
	"VRD_emailSelectAllAccounts" : "Todas as Contas",
	"VRD_emailSelectCall" : "Chamar",
	"VRD_emailSelectContactName" : "{ContactName}",
	"VRD_emailSelectContinueEmail" : "Continuar Msg. Correio Electrónico",
	"VRD_emailSelectDelete" : "Eliminar",
	"VRD_emailSelectDiscard" : "Rejeitar",
	"VRD_emailSelectImportEmail" : "Actualizar pasta A Receber",
	"VRD_emailSelectInbox" : "A Receber do Correio Electrónico",
	"VRD_emailSelectInboxSelector" : "A Receber",
	"VRD_emailSelectMessage" : "Adicionar Mensagem",
	"VRD_emailSelectNone" : "Nenhum destes",
	"VRD_emailSelectReply" : "Responder",
	"VRD_emailSelectReplyAll" : "Responder a Todos",
	"VRD_emailSelectRetry" : "Tentar Novamente",
	"VRD_emailSelectReturn" : "Voltar",
	"VRD_emailSelectSend" : "Enviar",
	"VRD_emailSelectSenderName" : "{senderName}",
	"VRD_emnaviAcceptAvoidance" : "Confirmar",
	"VRD_emnaviAddCurrentPosToFavourites" : "Adicionar posição atual aos Favoritos",
	"VRD_emnaviAddWaypointCityCenter" : "Adicionar Ponto de Referência do Centro da Cidade",
	"VRD_emnaviAddWaypointDistrictCenter" : "Adicionar Ponto de Referência do Centro do Distrito",
	"VRD_emnaviAddWaypointFavorite" : "Adicionar Ponto de Referência Favorito",
	"VRD_emnaviAddWaypointPOI" : "Adicionar Ponto de Referência {poiHypList}",
	"VRD_emnaviAvoidRouteAhead" : "Evitar o percurso à frente",
	"VRD_emnaviCancelRoute" : "Cancelar percurso",
	"VRD_emnaviDecreaseAvoidanceLength" : "Menos",
	"VRD_emnaviGoToCockpit" : "Iniciar",
	"VRD_emnaviIncreaseAvoidanceLength" : "Mais",
	"VRD_emnaviJPJ_VDEHypothesisList" : "O nome de uma cidade",
	"VRD_emnaviNavigateHere" : "Navegar para aqui",
	"VRD_emnaviNavigateHome" : "Navegar para Casa",
	"VRD_emnaviNavigateToARecentDestination" : "Navegar para um destino recente",
	"VRD_emnaviNavigateToAddress" : "Navegar para endereço",
	"VRD_emnaviNavigateToCityCenter" : "Navegar para o Centro da Cidade",
	"VRD_emnaviNavigateToDistrictCenter" : "Navegar para o Centro do Distrito",
	"VRD_emnaviNavigateToFavorite" : "Navegar para Favorito",
	"VRD_emnaviNavigateToPOI" : "Navegar para {poiHypList}",
	"VRD_emnaviNewDestination" : "Novo destino",
	"VRD_emnaviRepeatInstruction" : "Repetir instrução",
	"VRD_emnaviRouteSummary" : "Resumo do percurso",
	"VRD_emnaviSelectCancelRoute" : "Limpar percurso",
	"VRD_emnaviSelectNavigateToAddress" : "Navegar para Endereço",
	"VRD_emnaviSimpleHypothesisList" : "O nome de um distrito",
	"VRD_emnaviStepByStep" : "Entrada passo a passo",
	"VRD_emnaviTravelViaARecentDestination" : "Adicionar Ponto de Referência de destino recente",
	"VRD_emnaviTravelViaAddress" : "Viajar via endereço",
	"VRD_emnaviTravelViaHome" : "Viajar via Casa",
	"VRD_emnaviTryAgain" : "Tentar novamente",
	"VRD_emnaviUniSimpleHypothesisList" : "Um endereço",
	"VRD_emnaviUniVDEHypothesisList" : "Um endereço",
	"VRD_emnaviVDEHypothesisList" : "Um endereço",
	"VRD_emnaviWhereAmI" : "Onde Estou",
	"VRD_emnaviZoomIn" : "Ampliar",
	"VRD_emnaviZoomOut" : "Reduzir",
	"VRD_fmradioPlayStationFrequency" : "Sintonizar {frequency} FM",
	"VRD_fmradioSelectAutoMemory" : "Memória Automática",
	"VRD_fmradioSelectChangeGenre" : "Alterar Género",
	"VRD_fmradioSelectFMSettings" : "Definições de FM",
	"VRD_fmradioSelectFavorites" : "Favoritos",
	"VRD_fmradioSelectGenreSeek" : "Procura de Género",
	"VRD_fmradioSelectHDChannel" : "{HD Channel}",
	"VRD_fmradioSelectHDChannels" : "Estações HD",
	"VRD_fmradioSelectHDRadio" : "Rádio HD",
	"VRD_fmradioSelectHDRadioOff" : "Rádio HD Desligado",
	"VRD_fmradioSelectHDRadioOn" : "Rádio HD Ligado",
	"VRD_fmradioSelectScanOff" : "Análise Desactivada",
	"VRD_fmradioSelectScanOn" : "Análise Activada",
	"VRD_fmradioSelectSeekNext" : "Procurar Seguinte",
	"VRD_fmradioSelectSeekPrevious" : "Procurar Anterior",
	"VRD_fmradioSelectSettings" : "Definições de Som",
	"VRD_fmradioSelectSource" : "Entretenimento / Alterar Origem",
	"VRD_fmradioSelectStationAll" : "Todas as Estações",
	"VRD_fmradioSelectStationFrequency" : "{frequency}",
	"VRD_fmradioSelectStationGenre" : "{genreName}",
	"VRD_fmradioSelectStationList" : "Lista de Estações",
	"VRD_fmradioSelectStationName" : "{stationName}",
	"VRD_fmradioSelectTrafficAlert" : "Anúncio de Tráfego (TA)",
	"VRD_fmradioSelectTrafficAlertOff" : "Trânsito Desactivado",
	"VRD_fmradioSelectTrafficAlertOn" : "Trânsito Activado",
	"VRD_fmradioSelectTune" : "Sintonizar",
	"VRD_fmradioSelectUpdateAutoMemory" : "Actualizar Memória Automática",
	"VRD_fmradioSelectiTunesTagging" : "Marcação do iTunes",
	"VRD_fmradioTuneDown" : "Sintonizar para Baixo",
	"VRD_fmradioTuneUp" : "Sintonizar para Cima",
	"VRD_fmradioTurnOffAF" : "Frequência Alternativa Desligada",
	"VRD_fmradioTurnOffREG" : "Bloqueio da Região Desligado",
	"VRD_fmradioTurnOnAF" : "Frequência Alternativa Ligada",
	"VRD_fmradioTurnOnREG" : "Bloqueio da Região Ligado",
	"VRD_fmradioUpdateAutoMemory" : "Actualizar Lista de Estações",
	"VRD_pandoraAddStation" : "Adicionar Estação",
	"VRD_pandoraAddStationFromArtist" : "Criar Estação do Artista",
	"VRD_pandoraAddStationFromSong" : "Criar Estação a partir da Música ",
	"VRD_pandoraAddToFavorites" : "Adicionar aos Favoritos",
	"VRD_pandoraBookmarkArtist" : "Adicionar o Intérprete aos Favoritos",
	"VRD_pandoraBookmarkSong" : "Adicionar a Música aos Favoritos",
	"VRD_pandoraCreateStation" : "Criar Estação",
	"VRD_pandoraSelectAddCurrentStation" : "Adicionar",
	"VRD_pandoraSelectDelete" : "Eliminar",
	"VRD_pandoraSelectEditDelete" : "Eliminar",
	"VRD_pandoraSelectEditMove" : "Mover",
	"VRD_pandoraSelectEditReplace" : "Substituir",
	"VRD_pandoraSelectFavorites" : "Favoritos",
	"VRD_pandoraSelectMove" : "Mover",
	"VRD_pandoraSelectQuickMix" : "Reprodução Aleatória",
	"VRD_pandoraSelectSettings" : "Definições de Som",
	"VRD_pandoraSelectSortBy" : "Ordenar",
	"VRD_pandoraSelectSource" : "Entretenimento",
	"VRD_pandoraSelectStationList" : "Lista de Estações",
	"VRD_pandoraShowBookmarkOptions" : "Marcador",
	"VRD_pandoraShowByAZ" : "Ordenar por ordem alfabética",
	"VRD_pandoraShowByDate" : "Ordenar por data",
	"VRD_pandoraSkip" : "Ignorar",
	"VRD_pandoraThumbsDown" : "Desaprovar",
	"VRD_pandoraThumbsUp" : "Aprovar",
	"VRD_phoneCall" : "Chamar",
	"VRD_phoneCallBack" : "Chamada de Retorno",
	"VRD_phoneCallByName" : "Chamar por Nome",
	"VRD_phoneCallByNumber" : "Chamar por Número",
	"VRD_phoneCallContactType" : "Chamar {contactName} {contactType}",
	"VRD_phoneCallLast" : "Chamar Último Número",
	"VRD_phoneChooseContactType" : "{contactName} {contactType}",
	"VRD_phoneDialAnyNumber" : "Chamar {number}",
	"VRD_phoneDialpadClearAllDigits" : "Limpar Todos os Dígitos",
	"VRD_phoneDialpadDeleteDigit" : "Eliminar",
	"VRD_phoneDialpadPhoneNumber" : "{phoneNumber}",
	"VRD_phoneReDial" : "Remarcar",
	"VRD_phoneSelectByName" : "Nome",
	"VRD_phoneSelectByNumber" : "Número",
	"VRD_phoneSelectContactType" : "{contactType}",
	"VRD_phoneSelectDialPad" : "Teclado de Telefone",
	"VRD_phoneSelectFavorites" : "Favoritos",
	"VRD_phoneSelectRecentCalls" : "Chamadas Recentes",
	"VRD_phoneSelectRecentCallsAll" : "Todas as Chamadas",
	"VRD_phoneSelectRecentCallsMissed" : "Chamad. Não Atendidas",
	"VRD_satradioBackSpaceDelete" : "Eliminar Dígitos",
	"VRD_satradioChangeLockCode" : "Alterar Código PIN",
	"VRD_satradioEnterPIN" : "{4digitPin}",
	"VRD_satradioInitializeLockCode" : "Inicializar Código PIN",
	"VRD_satradioPlayChannelName" : "Reproduzir {channelName}",
	"VRD_satradioPlayStationNumber" : "Sintonizar {channelNumber}",
	"VRD_satradioResetLockCode" : "Repor Código PIN",
	"VRD_satradioSeekNext" : "Procurar Seguinte",
	"VRD_satradioSeekPrevious" : "Procurar Anterior",
	"VRD_satradioSelectChangeCategory" : "Categoria",
	"VRD_satradioSelectFavorites" : "Favoritos",
	"VRD_satradioSelectParentalLock" : "Limitação de Acesso",
	"VRD_satradioSelectScanOff" : "Análise Desactivada",
	"VRD_satradioSelectScanOn" : "Análise Activada",
	"VRD_satradioSelectSettings" : "Definições de Som",
	"VRD_satradioSelectSource" : "Entretenimento",
	"VRD_satradioSelectStation" : "Estação {Station number}",
	"VRD_satradioSelectStationAll" : "Todos os Canais",
	"VRD_satradioSelectStationCategory" : "{categoryName}",
	"VRD_satradioSelectStationList" : "Lista de Canais",
	"VRD_satradioTurnChannelLockOFF" : "Desbloquear Canal Actual",
	"VRD_satradioTurnChannelLockON" : "Bloquear Canal Actual",
	"VRD_satradioTurnParentalLockOFF" : "Bloqueio da Sessão Desactivado",
	"VRD_satradioTurnParentalLockON" : "Bloqueio da Sessão Activado",
	"VRD_smsCallPhoneNumber" : "Chamada",
	"VRD_smsDelete" : "Eliminar",
	"VRD_smsImportMessages" : "Actualizar Texto de A Receber",
	"VRD_smsReply" : "Responder",
	"VRD_smsSayAnyConversation" : "{senderName}",
	"VRD_smsSelectBody" : "Adicionar Mensagem",
	"VRD_smsSelectContactName" : "{ContactName}",
	"VRD_smsSelectContinueTextMessage" : "Continuar Mensagem",
	"VRD_smsSelectDiscard" : "Rejeitar",
	"VRD_smsSelectInbox" : "Lista A Receber de SMS",
	"VRD_smsSelectNone" : "Nenhum destes",
	"VRD_smsSelectRetry" : "Tentar Novamente",
	"VRD_smsSelectReturn" : "Voltar",
	"VRD_smsSelectSend" : "Enviar",
	"VRD_stitcherAddToFavorites" : "Adicionar aos Favoritos",
	"VRD_stitcherRemoveFromFavorites" : "Remover dos Favoritos",
	"VRD_stitcherSaveFavorites" : "Guardar Alterações",
	"VRD_stitcherSelectSettings" : "Definições de Som",
	"VRD_stitcherSelectSource" : "Entretenimento",
	"VRD_stitcherSelectStationList" : "Lista de Estações",
	"VRD_stitcherThumbsDown" : "Desaprovar",
	"VRD_stitcherThumbsUp" : "Aprovar",
	"VRD_systemSelectAhaRadio" : "Rádio Aha",
	"VRD_systemSelectAndroidAuto" : "Android Auto",
	"VRD_systemSelectApplications" : "Aplicações",
	"VRD_systemSelectAuxIn" : "Entrada / AUX",
	"VRD_systemSelectBTAudio" : "Bluetooth",
	"VRD_systemSelectCD" : "CD",
	"VRD_systemSelectCallHistory" : "Histórico de Chamadas",
	"VRD_systemSelectCarPlay" : "CarPlay",
	"VRD_systemSelectCommunication" : "Comunicação",
	"VRD_systemSelectConnect" : "Ligar",
	"VRD_systemSelectContacts" : "Contactos",
	"VRD_systemSelectDAB" : "DAB",
	"VRD_systemSelectDVD" : "DVD",
	"VRD_systemSelectDisplayClock" : "Ecrã do relógio",
	"VRD_systemSelectDisplayOff" : "Desligar Ecrã",
	"VRD_systemSelectEmail" : "Correio Electrónico",
	"VRD_systemSelectEntertainment" : "Entretenimento",
	"VRD_systemSelectEntertainmentMenu" : "Menu de Entretenimento",
	"VRD_systemSelectFavorites" : "Favoritos",
	"VRD_systemSelectNavigation" : "Navegação",
	"VRD_systemSelectNotifications" : "Mensagens",
	"VRD_systemSelectNotifyOff" : "Notif. Deslig.",
	"VRD_systemSelectPandora" : "Pandora",
	"VRD_systemSelectPhone" : "Telefone",
	"VRD_systemSelectRadioAM" : "Rádio AM",
	"VRD_systemSelectRadioFM" : "Rádio FM",
	"VRD_systemSelectRetry" : "Tentar Novamente",
	"VRD_systemSelectSatRadio" : "Rádio por Satélite",
	"VRD_systemSelectSettings" : "Definições",
	"VRD_systemSelectSiri" : "Siri",
	"VRD_systemSelectSms" : "Mensagem / SMS",
	"VRD_systemSelectStitcher" : "Stitcher",
	"VRD_systemSelectTV" : "TV",
	"VRD_systemSelectTrafficAlert" : "Anúncio de Tráfego (TA)",
	"VRD_systemSelectTutorial" : "Tutorial",
	"VRD_systemSelectUSB" : "USB",
	"VRD_systemSelectUSBA" : "USB 1",
	"VRD_systemSelectUSBB" : "USB 2",
	"VRD_systemSelectXmAudio" : "Rádio SXM",
	"VRD_tvSelectView" : "Ver",
	"VRD_usbaudioBrowse" : "Procurar",
	"VRD_usbaudioBrowseAlbum" : "Procurar {albumName}",
	"VRD_usbaudioBrowseAlbums" : "Procurar Álbum",
	"VRD_usbaudioBrowseAll" : "Procurar Todas as Músicas ou Álbuns ou Artistas",
	"VRD_usbaudioBrowseAnyAlbum" : "Procurar [Album] {albumName}",
	"VRD_usbaudioBrowseAnyArtist" : "Procurar [Artist] {artistName}",
	"VRD_usbaudioBrowseAnyFolder" : "Procurar Pasta {folderName}",
	"VRD_usbaudioBrowseArtist" : "Procurar {artistName}",
	"VRD_usbaudioBrowseArtists" : "Procurar Artista",
	"VRD_usbaudioBrowseAudiobooks" : "Procurar Audiolivros",
	"VRD_usbaudioBrowseFolder" : "Procurar {folderName}",
	"VRD_usbaudioBrowseFolders" : "Procurar Pasta",
	"VRD_usbaudioBrowseGenre" : "Procurar [Genre] {genreName}",
	"VRD_usbaudioBrowseGenres" : "Procurar Género",
	"VRD_usbaudioBrowseLineNumber" : "Procurar Linha {lineNumber}",
	"VRD_usbaudioBrowsePlaylist" : "Procura Lista Pessoal {playlistName}",
	"VRD_usbaudioBrowsePlaylists" : "Procurar Lista Pessoal",
	"VRD_usbaudioBrowsePodcast" : "Procurar Podcast {podcastName}",
	"VRD_usbaudioBrowsePodcasts" : "Procurar Podcasts",
	"VRD_usbaudioBrowseSongs" : "Procurar Música",
	"VRD_usbaudioChooseAlbumArtist" : "{artistName}",
	"VRD_usbaudioGenerateMoreLikeThis" : "Mais deste género",
	"VRD_usbaudioPlayAlbums" : "Reproduzir Álbum",
	"VRD_usbaudioPlayAll" : "Reproduzir Tudo",
	"VRD_usbaudioPlayAnyAlbum" : "Reproduzir [Album] {albumName}",
	"VRD_usbaudioPlayAnyArtist" : "Reproduzir [Artist] {artistName}",
	"VRD_usbaudioPlayAnyFolder" : "Reproduzir Pasta {folderName}",
	"VRD_usbaudioPlayArtistAlbum" : "Reproduzir {artistName} {albumName}",
	"VRD_usbaudioPlayArtists" : "Reproduzir Artista",
	"VRD_usbaudioPlayAudiobook" : "Reproduzir Audiolivro {AudiobookName}",
	"VRD_usbaudioPlayAudiobooks" : "Reproduzir Audiolivros",
	"VRD_usbaudioPlayChapter" : "{chapterName}",
	"VRD_usbaudioPlayChapterIndex" : "Reproduzir Capítulo {index} {chapter}",
	"VRD_usbaudioPlayEpisode" : "{episodeName}",
	"VRD_usbaudioPlayFolder" : "Reproduzir {folderName}",
	"VRD_usbaudioPlayFolders" : "Reproduzir Pasta",
	"VRD_usbaudioPlayGenre" : "Reproduzir [Genre] {genreName}",
	"VRD_usbaudioPlayGenres" : "Reproduzir Género",
	"VRD_usbaudioPlayLineNumber" : "Reproduzir [Line] {lineNumber}",
	"VRD_usbaudioPlayPlaylist" : "Reproduzir Lista Pessoal {playlistName}",
	"VRD_usbaudioPlayPlaylists" : "Reproduzir Lista Pessoal",
	"VRD_usbaudioPlayPodcast" : "Reproduzir Podcast {PodcastName}",
	"VRD_usbaudioPlayPodcasts" : "Reproduzir Podcasts",
	"VRD_usbaudioPlaySongs" : "Reproduzir Música",
	"VRD_usbaudioRepeat" : "Repetir",
	"VRD_usbaudioRepeatAll" : "Repetir Tudo",
	"VRD_usbaudioRepeatOff" : "Repetir Desactivado",
	"VRD_usbaudioRepeatSong" : "Repetir Música",
	"VRD_usbaudioRewind" : "Recuar",
	"VRD_usbaudioSelectAlbum" : "Álbum {albumName}",
	"VRD_usbaudioSelectAlbums" : "Álbum",
	"VRD_usbaudioSelectAll" : "Todos os Episódios ou Capítulos ou Músicas ou Álbuns ou Artistas",
	"VRD_usbaudioSelectArtist" : "Artista {artistName}",
	"VRD_usbaudioSelectArtists" : "Artista",
	"VRD_usbaudioSelectAudiobook" : "{audiobookName}",
	"VRD_usbaudioSelectAudiobooks" : "Audiolivros",
	"VRD_usbaudioSelectFolder" : "Pasta {folderName}",
	"VRD_usbaudioSelectFolders" : "Pastas",
	"VRD_usbaudioSelectGenre" : "Género {genreName}",
	"VRD_usbaudioSelectGenres" : "Género",
	"VRD_usbaudioSelectPlaylist" : "Lista Pessoal {playlistName}",
	"VRD_usbaudioSelectPlaylists" : "Lista Pessoal",
	"VRD_usbaudioSelectPodcast" : "{podcastName}",
	"VRD_usbaudioSelectPodcasts" : "Podcast",
	"VRD_usbaudioSelectRootFolder" : "Menu de Raiz",
	"VRD_usbaudioSelectSettings" : "Definições de Som",
	"VRD_usbaudioSelectSongs" : "Música",
	"VRD_usbaudioSelectSourceMenu" : "Entretenimento",
	"VRD_usbaudioShuffle" : "Aleatório",
	"VRD_usbaudioShuffleOff" : "Reprodução Aleatória Desactivada",
	"VRD_usbaudioShuffleOn" : "Aleatório Activado",
	"VRD_usbaudioSongList" : "Lista de Músicas",
	"VRD_xmaudioBackSpaceDelete" : "Eliminar Dígitos",
	"VRD_xmaudioChangeLockCode" : "Editar Código PIN",
	"VRD_xmaudioConfirmDelete" : "Eliminar",
	"VRD_xmaudioEnterPIN" : "{fourDigitPIN}",
	"VRD_xmaudioPlayChannelName" : "Reproduzir Canal XM {channelName}",
	"VRD_xmaudioPlayStationNumber" : "Sintonizar {channelNumber}",
	"VRD_xmaudioResetLockCode" : "Repor Código PIN",
	"VRD_xmaudioSelectCallXM" : "Chamar XM",
	"VRD_xmaudioSelectChangeCategory" : "Alterar Categoria",
	"VRD_xmaudioSelectContinueListening" : "Continuar a ouvir",
	"VRD_xmaudioSelectDismiss" : "Dispensar",
	"VRD_xmaudioSelectEveryOccurance" : "Todas as Ocorrências",
	"VRD_xmaudioSelectEveryOtherReport" : "Todos os Outros Relatórios",
	"VRD_xmaudioSelectEveryReport" : "Todos os Relatórios",
	"VRD_xmaudioSelectExitTuneMix" : "Sair do TuneMix",
	"VRD_xmaudioSelectFavorites" : "Favoritos",
	"VRD_xmaudioSelectListenNow" : "Ouvir Agora",
	"VRD_xmaudioSelectMove" : "Mover",
	"VRD_xmaudioSelectNearestCity" : "Cidade Mais Próxima",
	"VRD_xmaudioSelectOnlyFirstAfterVehicleStart" : "Arrancar Veículo",
	"VRD_xmaudioSelectOnlyFirstOccuranceInGame" : "Primeira Ocorrência",
	"VRD_xmaudioSelectReplayAlert" : "Repetir Alerta",
	"VRD_xmaudioSelectReturnToPrevious" : "Voltar a Anterior",
	"VRD_xmaudioSelectSFSportBaseball" : "Basebol",
	"VRD_xmaudioSelectSFSportNCAA" : "Futebol Americano Universitário",
	"VRD_xmaudioSelectSFSportNFL" : "Futebol Americano",
	"VRD_xmaudioSelectSFSportNHL" : "Hóquei",
	"VRD_xmaudioSelectScanOff" : "Análise Desactivada",
	"VRD_xmaudioSelectScanOn" : "Análise Activada",
	"VRD_xmaudioSelectSettings" : "Definições",
	"VRD_xmaudioSelectSoundSettings" : "Definições de Som",
	"VRD_xmaudioSelectSource" : "Entretenimento",
	"VRD_xmaudioSelectStation" : "Estação {channelNumber}",
	"VRD_xmaudioSelectStationAll" : "Todos os Canais",
	"VRD_xmaudioSelectStationCategory" : "{categoryName}",
	"VRD_xmaudioSelectStationFeaturedFavorites" : "Favoritos em Destaque",
	"VRD_xmaudioSelectStationList" : "Canais",
	"VRD_xmaudioSelectTuneMix" : "TuneMix",
	"VRD_xmaudioSelectTuneMixChannel" : "Opções de Canal TuneMix",
	"VRD_xmaudioSelectTuneMixChannelsOptions" : "Opções de Canais",
	"VRD_xmaudioSelectTuneMixCreation" : "Criar Novo Canal TuneMix",
	"VRD_xmaudioSelectTuneMixEdit" : "Editar Canal TuneMix",
	"VRD_xmaudioSelectTuneMixEditOps" : "Opções de Edição do TuneMix",
	"VRD_xmaudioSelectTuneMixRemove" : "Remover Canal TuneMix",
	"VRD_xmaudioSelectTuneMixRename" : "Mudar o Nome do TuneMix",
	"VRD_xmaudioSelectTurnAlertsOff" : "Desactivar Alertas",
	"VRD_xmaudioSelectiTunesTagging" : "Marcação do iTunes",
	"VRD_xmaudioSetChannelLock" : "Bloquear Canal",
	"VRD_xmaudioSetParentalLock" : "Bloqueio da Sessão",
	"VRD_xmdataSelectFuelPrices" : "Preços de Combustível",
	"VRD_xmdataSelectMovies" : "Filmes",
	"VRD_xmdataSelectParking" : "Estacionamento",
	"VRD_xmdataSelectSports" : "Desporto",
	"VRD_xmdataSelectStock" : "Acções",
	"VRD_xmdataSelectTrafficPlus" : "Trânsito Plus",
	"VRD_xmdataSelectWeatherForecast" : "Previsão Meteorológica",
	"VRD_xmdataSelectWeatherRadar" : "Radar Meteorológico",
	"VRD_xmdataSelectWeatherSecurityAlerts" : "Alertas de Segurança Relacionados com Meteorologia",
};

framework.registerAppDictLoaded("system", "pt_PT");