var __VrHelpPositionTable__systemAppDict_no_NO = {
	"HomeScreen_Help" : {
		"Right" : ["VrHelp_Favorites"],
		"Left" : ["VrHelp_Entertainment","VrHelp_Communication","VrHelp_Navigation","VrHelp_Settings","VrHelp_Applications"]
	}
};

var Localization_systemAppDict_no_NO = {
	//"stringId" : "localString"
	"ActiveCallItem" : "Aktiv samtale",
	"AhaMaintError" : "Vedlikeholdsfeil, aha",
	"AhaRadio" : "aha",
	"AmRadio" : "AM",
	"AndroidAuto" : "Android Auto",
	"Applications" : "Applikasjoner",
	"AudioSourceNotAvailableBTAudio" : "Bluetooth er ikke tilgjengelig",
	"AudioSourceNotAvailableCD" : "CD-en ble tatt ut",
	"AudioSourceNotAvailableDVD" : "DVD-en ble tatt ut",
	"AudioSourceNotAvailableTV" : "TV ikke tilgjengelig",
	"AudioSourceNotAvailableUSB" : "USB-enheten er endret",
	"AuxIn" : "AUX",
	"BT" : "BT",
	"Bluetooth" : "Bluetooth",
	"BluetoothWithDevice" : "Bluetooth - {deviceName}",
	"CallHistory" : "Anropshistorikk",
	"CarPlay" : "Apple CarPlay",
	"CdPlayer" : "CD",
	"ChannelOffAir" : "Kanalen er ikke på lufta",
	"ChannelUnauth" : "Kanalen er ikke autorisert",
	"CheckAntenna" : "Sjekk antennen",
	"CheckTuner" : "Sjekk mottakeren",
	"Communication" : "Kommunikasjon",
	"Connect" : "Koble til",
	"Contacts" : "Kontakter",
	"DVDItem" : "DVD",
	"DabRadio" : "DAB",
	"DialPhone" : "Ring telefon",
	"DidYouSay" : "Sa du …",
	"DisclaimerText" : "Distraksjoner kan forårsake ulykker. Må ikke brukes mens du kjører. Konsentrer deg alltid om å kjøre og overhold trafikkreglene. Se bruksanvisningen.",
	"DisconnectThenReconnect" : "Koble fra og koble til Apple Device på nytt",
	"DriveRecord" : "Kjørepost",
	"DriverIDItem" : "Føreridentifisering",
	"EcoenergyApp" : "Forbruksovervåkning",
	"EcoenergyAppHEV" : "Kjøremonitor",
	"Email" : "Email",
	"EngineOilLevel" : "Motoroljenivå",
	"Entertainment" : "Underholdning",
	"ErrorWhileStartingSiri" : "Feil ved oppstart av Siri.",
	"FailedNotificationRetrieval" : "Kan ikke hente meldingslisten",
	"FavoritesItem" : "Favoritter",
	"FmRadio" : "FM",
	"HDTrafficItem" : "HD Radio™ trafikkart",
	"InitiateSiri" : "Hold knappen for å snakke  for å starte Siri-økt",
	"IntelligentDriveMasterItem" : "i-DM",
	"NavigationTitle" : "Navigering",
	"NoConnectionNotifyText" : "Vil du koble til en telefon nå?",
	"NoConnectionNotifyTitle" : "Ingen telefon tilkoblet",
	"NoDeviceText" : "Vil du koble til en enhet nå?",
	"NoDeviceTitle" : "Ingen enheter koblet til",
	"Notifications" : "Meldinger",
	"NotifyIgnore" : "Ignorer",
	"NotifyIncomingMsg" : "Innkommende melding fra:",
	"NotifyOff" : "Meldinger av",
	"NotifyRead" : "Leselig",
	"NotifyReadNow" : "Vil du lese den nå?",
	"Pandora" : "Pandora",
	"ReconnectAhaRadio" : "Gjenoppretter Bluetooth for radio",
	"ReconnectBTAudio" : "Gjenoppretter Bluetooth for avspilling",
	"ReconnectCD" : "Verifiserer CD for å gjenoppta avspilling",
	"ReconnectCarPlay" : "Gjenopptar Apple CarPlay.",
	"ReconnectDVD" : "Verifiserer DVD for å gjenoppta avsp.",
	"ReconnectEntMenuButton" : "Underholdningsmeny",
	"ReconnectFailedBTAudio" : "Kan ikke koble til Bluetooth audio på nytt",
	"ReconnectFailedCD" : "CD-en ble tatt ut. Kan ikke gjenoppta avspillingen.",
	"ReconnectFailedCarPlay" : "Kunne ikke koble til Apple CarPlay på nytt",
	"ReconnectFailedDVD" : "DVD-en ble tatt ut. Kan ikke gjenoppta avspillingen.",
	"ReconnectFailedTV" : "TV ikke tilgjengelig. Ikke mulig å gjenoppta avspilling.",
	"ReconnectFailedUSB" : "USB-enheten er endret. Kan ikke gjenoppta avspillingen.",
	"ReconnectPandora" : "Gjenoppretter Bluetooth for Pandora",
	"ReconnectStitcher" : "Gjenoppretter Bluetooth for Stitcher",
	"ReconnectTV" : "Verifiserer tv for å gjenoppta avspilling",
	"ReconnectUSB" : "Gjenoppretter USB for avspilling",
	"RetryLabel" : "Prøv på nytt",
	"SchedMaintenanceApp" : "Vedlikehold",
	"ScreenReplication" : "Skjermreplikasjon",
	"SdarsRadio" : "XM",
	"Settings" : "Innstillinger",
	"SettingsCommunication" : "Innstillinger",
	"Siri" : "Siri",
	"SiriDisabled" : "Siri er deaktivert på Apple-enhet.",
	"Sms" : "SMS",
	"StitcherItem" : "Stitcher",
	"TVItem" : "TV",
	"TempWarning" : "Temperaturadvarsel",
	"TempWarningText" : "Skjermen er for varm. Skjermens ytelse vil muligens være nedsatt til den kjølner.",
	"TextDownloaded" : "SMS lastet ned",
	"TextSent" : "SMS sendt",
	"TrafficAlertsItem" : "Trafikkinformasjon",
	"USB" : "USB",
	"USB1AndroidAuto" : "USB 1 - Android Auto",
	"USB1CarPlay" : "USB 1 - Apple CarPlay",
	"USB2AndroidAuto" : "USB 2 - Android Auto",
	"UsbAudioA" : "USB 1",
	"UsbAudioAWithDevice" : "USB 1 - {deviceName}",
	"UsbAudioB" : "USB 2",
	"UsbAudioBWithDevice" : "USB 2 - {deviceName}",
	"UseCommander" : "Bruk commander når du kjører.",
	"VehicleDataTransferItem" : "Overføring, kjøretøydata ",
	"VehicleStatusMonitor" : "Bilstatus",
	"VehicleTelemetryTransfer" : "Overføring av kjøretøy telemetri",
	"VideoSignalLost" : "Tapt videosignal",
	"VoiceNotSupported" : "Voice støttes ikke. ",
	"VoiceRecognition" : "Stemmegjenkjenning",
	"VrHelp_Applications" : "Applications",
	"VrHelp_Communication" : "Communication",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_Favorites" : "Favorites",
	"VrHelp_Navigation" : "Navigation",
	"VrHelp_Settings" : "Settings",
	"WarnGuidanceApp" : "Advarselsveiledning",
	"WarningTitle" : "ADVARSEL!",
	"XMAudio" : "SXM",
	"XMData" : "SXM Services",
	"agree" : "Jeg Godtar",
	"VRD_aharadioSelectCall" : "Call",
	"VRD_aharadioSelectDiscard" : "Discard",
	"VRD_aharadioSelectEpisodes" : "Episode List",
	"VRD_aharadioSelectLBSTab" : "Nearby",
	"VRD_aharadioSelectMainList" : "Aha Main List",
	"VRD_aharadioSelectMap" : "Map",
	"VRD_aharadioSelectPresetsTab" : "Preset",
	"VRD_aharadioSelectSave" : "Save",
	"VRD_aharadioSelectSettings" : "Sound Settings",
	"VRD_aharadioSelectShout" : "Shout",
	"VRD_aharadioSelectSource" : "Entertainment / Change Source",
	"VRD_aharadioSelectThumbsDown" : "Thumbs Down",
	"VRD_aharadioSelectThumbsUp" : "Thumbs Up",
	"VRD_amradioPlayStationFrequency" : "Tune to {frequency} AM",
	"VRD_amradioSelectAutoMemory" : "Auto Memory",
	"VRD_amradioSelectFavorites" : "Favorites",
	"VRD_amradioSelectHD" : "HD Radio Stations",
	"VRD_amradioSelectHDOff" : "HD Radio Off",
	"VRD_amradioSelectHDOn" : "HD Radio On",
	"VRD_amradioSelectScanOff" : "Scan Off",
	"VRD_amradioSelectScanOn" : "Scan On",
	"VRD_amradioSelectSeekNext" : "Seek Next",
	"VRD_amradioSelectSeekPrevious" : "Seek Previous",
	"VRD_amradioSelectSettings" : "Sound Settings",
	"VRD_amradioSelectSource" : "Go to Entertainment Menu",
	"VRD_amradioSelectStationFrequency" : "{AMFrequency}",
	"VRD_amradioSelectTrafficAlert" : "Traffic Alert",
	"VRD_amradioSelectTrafficAlertOff" : "Traffic Alert Off",
	"VRD_amradioSelectTrafficAlertOn" : "Traffic Alert On",
	"VRD_amradioSelectTune" : "Tune",
	"VRD_amradioSelectUpdateAutoMemory" : "Auto Memory Seek",
	"VRD_amradioSelectiTunesTagging" : "iTunes Tagging",
	"VRD_amradioTuneDown" : "Tune Down",
	"VRD_amradioTuneUp" : "Tune Up",
	"VRD_amradioUpdateAutoMemory" : "Update Station List",
	"VRD_auxinSelectSettings" : "Sound Settings",
	"VRD_auxinSelectSource" : "Entertainment / Change Source",
	"VRD_btaudioScanPlay" : "Scan Play",
	"VRD_btaudioSelectConnect" : "Connect",
	"VRD_btaudioSelectRootMenu" : "Root Menu",
	"VRD_btaudioSelectSettings" : "Sound Settings",
	"VRD_btaudioSelectSource" : "Go to Entertainment Menu",
	"VRD_btaudioToggleRepeat" : "Repeat",
	"VRD_btaudioToggleShuffle" : "Shuffle",
	"VRD_carplaySelectApplications" : "Applications",
	"VRD_cdGoSettings" : "Sound Settings",
	"VRD_cdHandleStartScan" : "Start Scan",
	"VRD_cdPlayBeginning" : "Start over",
	"VRD_cdRepeatFolder" : "Repeat Folder",
	"VRD_cdRepeatOff" : "Repeat Off",
	"VRD_cdRepeatOn" : "Repeat On",
	"VRD_cdRepeatTrack" : "Repeat Track",
	"VRD_cdSelectCurrentFolder" : "Current Folder",
	"VRD_cdSelectRepeat" : "Repeat",
	"VRD_cdSelectRootFolder" : "Root Menu",
	"VRD_cdSelectShuffle" : "Shuffle",
	"VRD_cdSelectSource" : "Go to Entertainment Menu",
	"VRD_cdSelectTrackList" : "Track List",
	"VRD_cdSelectTrackNumber" : "Play Track {Number}",
	"VRD_cdShuffleDisk" : "Shuffle Disc",
	"VRD_cdShuffleFolder" : "Shuffle Folder",
	"VRD_cdShuffleOff" : "Shuffle Off",
	"VRD_cdShuffleOn" : "Shuffle On",
	"VRD_commonAddToFavorites" : "Add to Favorites",
	"VRD_commonCancel" : "Cancel",
	"VRD_commonFastForward" : "Fast Forward",
	"VRD_commonGoBack" : "Go Back",
	"VRD_commonIntentParent" : "Parent",
	"VRD_commonIntentParentUSBAudio" : "Parent",
	"VRD_commonIntentUSBAudio" : "Home",
	"VRD_commonIntentUSBAudioBG" : "Home",
	"VRD_commonMenuUp" : "Nenu Up",
	"VRD_commonNext" : "Next",
	"VRD_commonNo" : "No",
	"VRD_commonPageDown" : "Page Down / Scroll Down",
	"VRD_commonPageUp" : "Page Up / Scroll Up",
	"VRD_commonPause" : "Pause",
	"VRD_commonPrevious" : "Previous",
	"VRD_commonResume" : "Play / Resume",
	"VRD_commonRewind" : "Rewind",
	"VRD_commonSelectLineNumber" : "Line {lineNumber}",
	"VRD_commonYes" : "Yes / OK",
	"VRD_contactsChooseContactName" : "{ContactName}",
	"VRD_contactsDisambiguateContactName" : "Show {ContactName}",
	"VRD_contactsImportAll" : "Import All Contacts",
	"VRD_contactsImportCancel" : "Cancel Import",
	"VRD_contactsImportContacts" : "Edit Contacts",
	"VRD_contactsImportSingle" : "Import Selected Contact",
	"VRD_contactsRemoveContact" : "Remove Contact",
	"VRD_contactsSelectCall" : "Call",
	"VRD_contactsSelectContactName" : "{ContactName}",
	"VRD_contactsSelectDownload" : "Download",
	"VRD_contactsSelectFavorites" : "Favorites",
	"VRD_contactsSelectNone" : "None of these",
	"VRD_contactsSelectReadContactName" : "Read Contact Name",
	"VRD_contactsSelectRemove" : "Remove",
	"VRD_contactsSelectRetry" : "Retry",
	"VRD_contactsSendPhoneType" : "{phoneType}",
	"VRD_contactsShowAddress" : "Address",
	"VRD_dabDisplayDABSettings" : "DAB Settings",
	"VRD_dabDisplayEnsembleList" : "Select Ensemble",
	"VRD_dabDisplayStationList" : "Station List",
	"VRD_dabSelectFavorites" : "Favorites",
	"VRD_dabSelectScan" : "Scan",
	"VRD_dabSelectSeekNext" : "Next",
	"VRD_dabSelectSeekPrevious" : "Previous",
	"VRD_dabSelectSettings" : "Sound Settings",
	"VRD_dabSelectSource" : "Entertainment",
	"VRD_dabTAToggleOFF" : "Traffic Off",
	"VRD_dabTAToggleON" : "Traffic On",
	"VRD_dabTAToggleVois" : "Traffic Announcement",
	"VRD_dabUpdateStationList" : "Update List",
	"VRD_dvdClearPin" : "Delete Digits",
	"VRD_dvdSayGRating" : "G",
	"VRD_dvdSayPG12" : "P G Twelve",
	"VRD_dvdSayR15" : "R Fifteen Plus",
	"VRD_dvdSayR18" : "None",
	"VRD_dvdSelectAspectRatio" : "Aspect Ratio",
	"VRD_dvdSelectAudioSettings" : "Video Settings",
	"VRD_dvdSelectCameraAngle" : "Camera Angle",
	"VRD_dvdSelectEditPin" : "Edit PIN Code",
	"VRD_dvdSelectParentLock" : "Parental Lock",
	"VRD_dvdSelectParentLockOff" : "Parental Lock Off",
	"VRD_dvdSelectParentLockOn" : "Parental Lock On",
	"VRD_dvdSelectParentLockRating" : "Parental Lock Rating",
	"VRD_dvdSelectResetPin" : "Reset PIN Code",
	"VRD_dvdSelectRootMenu" : "Root Menu",
	"VRD_dvdSelectSettings" : "Sound Settings",
	"VRD_dvdSelectSource" : "Entertainment",
	"VRD_dvdSelectSubtitleOff" : "Subtitle Off",
	"VRD_dvdSelectSubtitleOn" : "Subtitle On",
	"VRD_dvdSlowForward" : "Fast Forward",
	"VRD_dvdSlowRewind" : "Rewind",
	"VRD_dvdVUISendPin" : "{FourDigitPin}",
	"VRD_emailSelectAllAccounts" : "All Accounts",
	"VRD_emailSelectCall" : "Call",
	"VRD_emailSelectContactName" : "{ContactName}",
	"VRD_emailSelectContinueEmail" : "Continue Email",
	"VRD_emailSelectDelete" : "Delete",
	"VRD_emailSelectDiscard" : "Discard",
	"VRD_emailSelectImportEmail" : "Update Inbox",
	"VRD_emailSelectInbox" : "Email Inbox",
	"VRD_emailSelectInboxSelector" : "Inbox",
	"VRD_emailSelectMessage" : "Add Message",
	"VRD_emailSelectNone" : "None of these",
	"VRD_emailSelectReply" : "Reply",
	"VRD_emailSelectReplyAll" : "Reply All",
	"VRD_emailSelectRetry" : "Retry",
	"VRD_emailSelectReturn" : "Return",
	"VRD_emailSelectSend" : "Send",
	"VRD_emailSelectSenderName" : "{senderName}",
	"VRD_emnaviAcceptAvoidance" : "Confirm",
	"VRD_emnaviAddCurrentPosToFavourites" : "Add current position to Favorites",
	"VRD_emnaviAddWaypointCityCenter" : "Add Waypoint City Center",
	"VRD_emnaviAddWaypointDistrictCenter" : "Add Waypoint District Center",
	"VRD_emnaviAddWaypointFavorite" : "Add Waypoint Favorite",
	"VRD_emnaviAddWaypointPOI" : "Add Waypoint {poiHypList}",
	"VRD_emnaviAvoidRouteAhead" : "Avoid route ahead",
	"VRD_emnaviCancelRoute" : "Cancel route",
	"VRD_emnaviDecreaseAvoidanceLength" : "Less",
	"VRD_emnaviGoToCockpit" : "Start",
	"VRD_emnaviIncreaseAvoidanceLength" : "More",
	"VRD_emnaviJPJ_VDEHypothesisList" : "A city name",
	"VRD_emnaviNavigateHere" : "Navigate Here",
	"VRD_emnaviNavigateHome" : "Navigate Home",
	"VRD_emnaviNavigateToARecentDestination" : "Navigate to a recent destination",
	"VRD_emnaviNavigateToAddress" : "Navigate to address",
	"VRD_emnaviNavigateToCityCenter" : "Navigate to City Center",
	"VRD_emnaviNavigateToDistrictCenter" : "Navigate to District Center",
	"VRD_emnaviNavigateToFavorite" : "Navigate to Favorite",
	"VRD_emnaviNavigateToPOI" : "Navigate to {poiHypList}",
	"VRD_emnaviNewDestination" : "New destination",
	"VRD_emnaviRepeatInstruction" : "Repeat instruction",
	"VRD_emnaviRouteSummary" : "Route summary",
	"VRD_emnaviSelectCancelRoute" : "Clear route",
	"VRD_emnaviSelectNavigateToAddress" : "Navigate to an address",
	"VRD_emnaviSimpleHypothesisList" : "A state name",
	"VRD_emnaviStepByStep" : "Step by step entry",
	"VRD_emnaviTravelViaARecentDestination" : "Add Waypoint recent destination",
	"VRD_emnaviTravelViaAddress" : "Travel via address",
	"VRD_emnaviTravelViaHome" : "Travel via Home",
	"VRD_emnaviTryAgain" : "Try again",
	"VRD_emnaviUniSimpleHypothesisList" : "An address",
	"VRD_emnaviUniVDEHypothesisList" : "An address",
	"VRD_emnaviVDEHypothesisList" : "An address",
	"VRD_emnaviWhereAmI" : "Where am I",
	"VRD_emnaviZoomIn" : "Zoom In",
	"VRD_emnaviZoomOut" : "Zoom Out",
	"VRD_fmradioPlayStationFrequency" : "Tune to {frequency} FM",
	"VRD_fmradioSelectAutoMemory" : "Auto Memory",
	"VRD_fmradioSelectChangeGenre" : "Change Genre",
	"VRD_fmradioSelectFMSettings" : "FM Settings",
	"VRD_fmradioSelectFavorites" : "Favorites",
	"VRD_fmradioSelectGenreSeek" : "Genre Seek",
	"VRD_fmradioSelectHDChannel" : "{HD Channel}",
	"VRD_fmradioSelectHDChannels" : "HD Radio Stations",
	"VRD_fmradioSelectHDRadio" : "HD Radio",
	"VRD_fmradioSelectHDRadioOff" : "HD Radio Off",
	"VRD_fmradioSelectHDRadioOn" : "HD Radio On",
	"VRD_fmradioSelectScanOff" : "Scan Off",
	"VRD_fmradioSelectScanOn" : "Scan On",
	"VRD_fmradioSelectSeekNext" : "Seek Next",
	"VRD_fmradioSelectSeekPrevious" : "Seek Previous",
	"VRD_fmradioSelectSettings" : "Sound Settings",
	"VRD_fmradioSelectSource" : "Entertainment / Change Source",
	"VRD_fmradioSelectStationAll" : "All Stations",
	"VRD_fmradioSelectStationFrequency" : "{frequency}",
	"VRD_fmradioSelectStationGenre" : "{genreName}",
	"VRD_fmradioSelectStationList" : "Station List",
	"VRD_fmradioSelectStationName" : "{stationName}",
	"VRD_fmradioSelectTrafficAlert" : "Traffic Announcement",
	"VRD_fmradioSelectTrafficAlertOff" : "Traffic Off",
	"VRD_fmradioSelectTrafficAlertOn" : "Traffic On",
	"VRD_fmradioSelectTune" : "Tune",
	"VRD_fmradioSelectUpdateAutoMemory" : "Update Auto Memory",
	"VRD_fmradioSelectiTunesTagging" : "iTunes Tagging",
	"VRD_fmradioTuneDown" : "Tune Down",
	"VRD_fmradioTuneUp" : "Tune Up",
	"VRD_fmradioTurnOffAF" : "Alternate Frequency Off",
	"VRD_fmradioTurnOffREG" : "Region Lock Off",
	"VRD_fmradioTurnOnAF" : "Alternate Frequency On",
	"VRD_fmradioTurnOnREG" : "Region Lock On",
	"VRD_fmradioUpdateAutoMemory" : "Update Station List",
	"VRD_pandoraAddStation" : "Add Station",
	"VRD_pandoraAddStationFromArtist" : "Create Station from Artist",
	"VRD_pandoraAddStationFromSong" : "Create Station from Song",
	"VRD_pandoraAddToFavorites" : "Add to Favorites",
	"VRD_pandoraBookmarkArtist" : "Bookmark Artist",
	"VRD_pandoraBookmarkSong" : "Bookmark Song",
	"VRD_pandoraCreateStation" : "Create Station",
	"VRD_pandoraSelectAddCurrentStation" : "Add",
	"VRD_pandoraSelectDelete" : "Delete",
	"VRD_pandoraSelectEditDelete" : "Delete",
	"VRD_pandoraSelectEditMove" : "Move",
	"VRD_pandoraSelectEditReplace" : "Replace",
	"VRD_pandoraSelectFavorites" : "Favorites",
	"VRD_pandoraSelectMove" : "Move",
	"VRD_pandoraSelectQuickMix" : "Shuffle",
	"VRD_pandoraSelectSettings" : "Sound Settings",
	"VRD_pandoraSelectSortBy" : "Sort",
	"VRD_pandoraSelectSource" : "Entertainment",
	"VRD_pandoraSelectStationList" : "Station List",
	"VRD_pandoraShowBookmarkOptions" : "Bookmark",
	"VRD_pandoraShowByAZ" : "Sort alphabetically",
	"VRD_pandoraShowByDate" : "Sort by date",
	"VRD_pandoraSkip" : "Skip",
	"VRD_pandoraThumbsDown" : "Thumbs Down",
	"VRD_pandoraThumbsUp" : "Thumbs Up",
	"VRD_phoneCall" : "Call",
	"VRD_phoneCallBack" : "Call Back",
	"VRD_phoneCallByName" : "Call by Name",
	"VRD_phoneCallByNumber" : "Call by Number",
	"VRD_phoneCallContactType" : "Call {contactName} {contactType}",
	"VRD_phoneCallLast" : "Call Last Number",
	"VRD_phoneChooseContactType" : "{contactName} {contactType}",
	"VRD_phoneDialAnyNumber" : "Call {number}",
	"VRD_phoneDialpadClearAllDigits" : "Clear All Digits",
	"VRD_phoneDialpadDeleteDigit" : "Delete",
	"VRD_phoneDialpadPhoneNumber" : "{phoneNumber}",
	"VRD_phoneReDial" : "Redial",
	"VRD_phoneSelectByName" : "Name",
	"VRD_phoneSelectByNumber" : "Number",
	"VRD_phoneSelectContactType" : "{contactType}",
	"VRD_phoneSelectDialPad" : "Dial Pad",
	"VRD_phoneSelectFavorites" : "Favorites",
	"VRD_phoneSelectRecentCalls" : "Recent Calls",
	"VRD_phoneSelectRecentCallsAll" : "All Calls",
	"VRD_phoneSelectRecentCallsMissed" : "Missed Calls",
	"VRD_satradioBackSpaceDelete" : "Delete Digits",
	"VRD_satradioChangeLockCode" : "Change PIN Code",
	"VRD_satradioEnterPIN" : "{4digitPin}",
	"VRD_satradioInitializeLockCode" : "Initialize PIN Code",
	"VRD_satradioPlayChannelName" : "Play {channelName}",
	"VRD_satradioPlayStationNumber" : "Tune to {channelNumber}",
	"VRD_satradioResetLockCode" : "Reset PIN Code",
	"VRD_satradioSeekNext" : "Seek Next",
	"VRD_satradioSeekPrevious" : "Seek Previous",
	"VRD_satradioSelectChangeCategory" : "Category",
	"VRD_satradioSelectFavorites" : "Favorites",
	"VRD_satradioSelectParentalLock" : "Parental Lock",
	"VRD_satradioSelectScanOff" : "Scan Off",
	"VRD_satradioSelectScanOn" : "Scan On",
	"VRD_satradioSelectSettings" : "Sound Settings",
	"VRD_satradioSelectSource" : "Entertainment",
	"VRD_satradioSelectStation" : "Station {Station number}",
	"VRD_satradioSelectStationAll" : "All Channels",
	"VRD_satradioSelectStationCategory" : "{categoryName}",
	"VRD_satradioSelectStationList" : "Channel List",
	"VRD_satradioTurnChannelLockOFF" : "Unlock Current Channel",
	"VRD_satradioTurnChannelLockON" : "Lock Current Channel",
	"VRD_satradioTurnParentalLockOFF" : "Session Lock Off",
	"VRD_satradioTurnParentalLockON" : "Session Lock On",
	"VRD_smsCallPhoneNumber" : "Call",
	"VRD_smsDelete" : "Delete",
	"VRD_smsImportMessages" : "Update Text Inbox",
	"VRD_smsReply" : "Reply",
	"VRD_smsSayAnyConversation" : "{senderName}",
	"VRD_smsSelectBody" : "Add Message",
	"VRD_smsSelectContactName" : "{ContactName}",
	"VRD_smsSelectContinueTextMessage" : "Continue Message",
	"VRD_smsSelectDiscard" : "Discard",
	"VRD_smsSelectInbox" : "SMS Inbox List",
	"VRD_smsSelectNone" : "None of these",
	"VRD_smsSelectRetry" : "Retry",
	"VRD_smsSelectReturn" : "Return",
	"VRD_smsSelectSend" : "Send",
	"VRD_stitcherAddToFavorites" : "Add to Favorites",
	"VRD_stitcherRemoveFromFavorites" : "Remove from Favorites",
	"VRD_stitcherSaveFavorites" : "Save Changes",
	"VRD_stitcherSelectSettings" : "Sound Settings",
	"VRD_stitcherSelectSource" : "Entertainment",
	"VRD_stitcherSelectStationList" : "Station List",
	"VRD_stitcherThumbsDown" : "Thumbs Down",
	"VRD_stitcherThumbsUp" : "Thumbs Up",
	"VRD_systemSelectAhaRadio" : "Aha Radio",
	"VRD_systemSelectAndroidAuto" : "Android Auto",
	"VRD_systemSelectApplications" : "Applications",
	"VRD_systemSelectAuxIn" : "Line In / AUX",
	"VRD_systemSelectBTAudio" : "Bluetooth",
	"VRD_systemSelectCD" : "CD",
	"VRD_systemSelectCallHistory" : "Call History",
	"VRD_systemSelectCarPlay" : "Car Play",
	"VRD_systemSelectCommunication" : "Communication",
	"VRD_systemSelectConnect" : "Connect",
	"VRD_systemSelectContacts" : "Contacts",
	"VRD_systemSelectDAB" : "DAB",
	"VRD_systemSelectDVD" : "DVD",
	"VRD_systemSelectDisplayClock" : "Clock Display",
	"VRD_systemSelectDisplayOff" : "Display Off",
	"VRD_systemSelectEmail" : "Email",
	"VRD_systemSelectEntertainment" : "Entertainment",
	"VRD_systemSelectEntertainmentMenu" : "Entertainment Menu",
	"VRD_systemSelectFavorites" : "Favorites",
	"VRD_systemSelectNavigation" : "Navigation",
	"VRD_systemSelectNotifications" : "Messages",
	"VRD_systemSelectNotifyOff" : "Notify Off",
	"VRD_systemSelectPandora" : "Pandora",
	"VRD_systemSelectPhone" : "Phone",
	"VRD_systemSelectRadioAM" : "AM Radio",
	"VRD_systemSelectRadioFM" : "FM Radio",
	"VRD_systemSelectRetry" : "Retry",
	"VRD_systemSelectSatRadio" : "Satellite Radio",
	"VRD_systemSelectSettings" : "Settings",
	"VRD_systemSelectSiri" : "Siri",
	"VRD_systemSelectSms" : "Text / SMS",
	"VRD_systemSelectStitcher" : "Stitcher",
	"VRD_systemSelectTV" : "TV",
	"VRD_systemSelectTrafficAlert" : "Traffic Announcement",
	"VRD_systemSelectTutorial" : "Tutorial",
	"VRD_systemSelectUSB" : "USB",
	"VRD_systemSelectUSBA" : "USB 1",
	"VRD_systemSelectUSBB" : "USB 2",
	"VRD_systemSelectXmAudio" : "SXM Radio",
	"VRD_tvSelectView" : "View",
	"VRD_usbaudioBrowse" : "Browse",
	"VRD_usbaudioBrowseAlbum" : "Browse {albumName}",
	"VRD_usbaudioBrowseAlbums" : "Browse Album",
	"VRD_usbaudioBrowseAll" : "Browse All Songs or Albums or Artists",
	"VRD_usbaudioBrowseAnyAlbum" : "Browse [Album] {albumName}",
	"VRD_usbaudioBrowseAnyArtist" : "Browse [Artist] {artistName}",
	"VRD_usbaudioBrowseAnyFolder" : "Browse Folder {folderName}",
	"VRD_usbaudioBrowseArtist" : "Browse {artistName}",
	"VRD_usbaudioBrowseArtists" : "Browse Artist",
	"VRD_usbaudioBrowseAudiobooks" : "Browse Audiobooks",
	"VRD_usbaudioBrowseFolder" : "Browse {folderName}",
	"VRD_usbaudioBrowseFolders" : "Browse Folder",
	"VRD_usbaudioBrowseGenre" : "Browse [Genre] {genreName}",
	"VRD_usbaudioBrowseGenres" : "Browse Genre",
	"VRD_usbaudioBrowseLineNumber" : "Browse Line {lineNumber}",
	"VRD_usbaudioBrowsePlaylist" : "Browse Playlist {playlistName}",
	"VRD_usbaudioBrowsePlaylists" : "Browse Playlist",
	"VRD_usbaudioBrowsePodcast" : "Browse Podcast {podcastName}",
	"VRD_usbaudioBrowsePodcasts" : "Browse Podcasts",
	"VRD_usbaudioBrowseSongs" : "Browse Song",
	"VRD_usbaudioChooseAlbumArtist" : "{artistName}",
	"VRD_usbaudioGenerateMoreLikeThis" : "More Like This",
	"VRD_usbaudioPlayAlbums" : "Play Album",
	"VRD_usbaudioPlayAll" : "Play All",
	"VRD_usbaudioPlayAnyAlbum" : "Play [Album] {albumName}",
	"VRD_usbaudioPlayAnyArtist" : "Play [Artist] {artistName}",
	"VRD_usbaudioPlayAnyFolder" : "Play Folder {folderName}",
	"VRD_usbaudioPlayArtistAlbum" : "Play {artistName} {albumName}",
	"VRD_usbaudioPlayArtists" : "Play Artist",
	"VRD_usbaudioPlayAudiobook" : "Play Audiobook {AudiobookName}",
	"VRD_usbaudioPlayAudiobooks" : "Play Audiobooks",
	"VRD_usbaudioPlayChapter" : "{chapterName}",
	"VRD_usbaudioPlayChapterIndex" : "Play Chapter {index} {chapter}",
	"VRD_usbaudioPlayEpisode" : "{episodeName}",
	"VRD_usbaudioPlayFolder" : "Play {folderName}",
	"VRD_usbaudioPlayFolders" : "Play Folder",
	"VRD_usbaudioPlayGenre" : "Play [Genre] {genreName}",
	"VRD_usbaudioPlayGenres" : "Play Genre",
	"VRD_usbaudioPlayLineNumber" : "Play [Line] {lineNumber}",
	"VRD_usbaudioPlayPlaylist" : "Play Playlist {playlistName}",
	"VRD_usbaudioPlayPlaylists" : "Play Playlist",
	"VRD_usbaudioPlayPodcast" : "Play Podcast {PodcastName}",
	"VRD_usbaudioPlayPodcasts" : "Play Podcasts",
	"VRD_usbaudioPlaySongs" : "Play Song",
	"VRD_usbaudioRepeat" : "Repeat",
	"VRD_usbaudioRepeatAll" : "Repeat All",
	"VRD_usbaudioRepeatOff" : "Repeat Off",
	"VRD_usbaudioRepeatSong" : "Repeat Song",
	"VRD_usbaudioRewind" : "Rewind",
	"VRD_usbaudioSelectAlbum" : "Album {albumName}",
	"VRD_usbaudioSelectAlbums" : "Album",
	"VRD_usbaudioSelectAll" : "All Episodes or Chapters or Songs or Albums or Artists",
	"VRD_usbaudioSelectArtist" : "Artist {artistName}",
	"VRD_usbaudioSelectArtists" : "Artist",
	"VRD_usbaudioSelectAudiobook" : "{audiobookName}",
	"VRD_usbaudioSelectAudiobooks" : "Audiobooks",
	"VRD_usbaudioSelectFolder" : "Folder {folderName}",
	"VRD_usbaudioSelectFolders" : "Folders",
	"VRD_usbaudioSelectGenre" : "Genre {genreName}",
	"VRD_usbaudioSelectGenres" : "Genre",
	"VRD_usbaudioSelectPlaylist" : "Playlist {playlistName}",
	"VRD_usbaudioSelectPlaylists" : "Playlist",
	"VRD_usbaudioSelectPodcast" : "{podcastName}",
	"VRD_usbaudioSelectPodcasts" : "Podcast",
	"VRD_usbaudioSelectRootFolder" : "Root Menu",
	"VRD_usbaudioSelectSettings" : "Sound Settings",
	"VRD_usbaudioSelectSongs" : "Song",
	"VRD_usbaudioSelectSourceMenu" : "Entertainment",
	"VRD_usbaudioShuffle" : "Shuffle",
	"VRD_usbaudioShuffleOff" : "Shuffle Off",
	"VRD_usbaudioShuffleOn" : "Shuffle On",
	"VRD_usbaudioSongList" : "Song List",
	"VRD_xmaudioBackSpaceDelete" : "Delete Digits",
	"VRD_xmaudioChangeLockCode" : "Edit PIN Code",
	"VRD_xmaudioConfirmDelete" : "Delete",
	"VRD_xmaudioEnterPIN" : "{fourDigitPIN}",
	"VRD_xmaudioPlayChannelName" : "Play XM Channel {channelName}",
	"VRD_xmaudioPlayStationNumber" : "Tune to {channelNumber}",
	"VRD_xmaudioResetLockCode" : "Reset PIN Code",
	"VRD_xmaudioSelectCallXM" : "Call XM",
	"VRD_xmaudioSelectChangeCategory" : "Change Category",
	"VRD_xmaudioSelectContinueListening" : "Continue Listening",
	"VRD_xmaudioSelectDismiss" : "Dismiss",
	"VRD_xmaudioSelectEveryOccurance" : "Every Occurrence",
	"VRD_xmaudioSelectEveryOtherReport" : "Every Other Report",
	"VRD_xmaudioSelectEveryReport" : "Every Report",
	"VRD_xmaudioSelectExitTuneMix" : "Exit TuneMix",
	"VRD_xmaudioSelectFavorites" : "Favorites",
	"VRD_xmaudioSelectListenNow" : "Listen Now",
	"VRD_xmaudioSelectMove" : "Move",
	"VRD_xmaudioSelectNearestCity" : "Nearest City",
	"VRD_xmaudioSelectOnlyFirstAfterVehicleStart" : "Vehicle Start",
	"VRD_xmaudioSelectOnlyFirstOccuranceInGame" : "First Occurrence",
	"VRD_xmaudioSelectReplayAlert" : "Replay Alert",
	"VRD_xmaudioSelectReturnToPrevious" : "Return to Previous",
	"VRD_xmaudioSelectSFSportBaseball" : "Baseball",
	"VRD_xmaudioSelectSFSportNCAA" : "College Football",
	"VRD_xmaudioSelectSFSportNFL" : "Professional Football",
	"VRD_xmaudioSelectSFSportNHL" : "Hockey",
	"VRD_xmaudioSelectScanOff" : "Scan Off",
	"VRD_xmaudioSelectScanOn" : "Scan On",
	"VRD_xmaudioSelectSettings" : "Settings",
	"VRD_xmaudioSelectSoundSettings" : "Sound Settings",
	"VRD_xmaudioSelectSource" : "Entertainment",
	"VRD_xmaudioSelectStation" : "Station {channelNumber}",
	"VRD_xmaudioSelectStationAll" : "All Channels",
	"VRD_xmaudioSelectStationCategory" : "{categoryName}",
	"VRD_xmaudioSelectStationFeaturedFavorites" : "Featured Favorites",
	"VRD_xmaudioSelectStationList" : "Channels",
	"VRD_xmaudioSelectTuneMix" : "TuneMix",
	"VRD_xmaudioSelectTuneMixChannel" : "TuneMix Channel Options",
	"VRD_xmaudioSelectTuneMixChannelsOptions" : "Channel Options",
	"VRD_xmaudioSelectTuneMixCreation" : "Create New TuneMix Channel",
	"VRD_xmaudioSelectTuneMixEdit" : "Edit TuneMix Channel",
	"VRD_xmaudioSelectTuneMixEditOps" : "TuneMix Edit Options",
	"VRD_xmaudioSelectTuneMixRemove" : "Remove TuneMix Channel",
	"VRD_xmaudioSelectTuneMixRename" : "Rename TuneMix",
	"VRD_xmaudioSelectTurnAlertsOff" : "Turn Alerts Off",
	"VRD_xmaudioSelectiTunesTagging" : "iTunes Tagging",
	"VRD_xmaudioSetChannelLock" : "Lock Channel",
	"VRD_xmaudioSetParentalLock" : "Session Lock",
	"VRD_xmdataSelectFuelPrices" : "Fuel Prices",
	"VRD_xmdataSelectMovies" : "Movies",
	"VRD_xmdataSelectParking" : "Parking",
	"VRD_xmdataSelectSports" : "Sports",
	"VRD_xmdataSelectStock" : "Stocks",
	"VRD_xmdataSelectTrafficPlus" : "Traffic Plus",
	"VRD_xmdataSelectWeatherForecast" : "Weather Forecast",
	"VRD_xmdataSelectWeatherRadar" : "Weather Radar",
	"VRD_xmdataSelectWeatherSecurityAlerts" : "Weather Security Alerts",
};

framework.registerAppDictLoaded("system", "no_NO");