var __VrHelpPositionTable__systemAppDict_sv_SE = {
	"HomeScreen_Help" : {
		"Right" : ["VrHelp_Favorites"],
		"Left" : ["VrHelp_Entertainment","VrHelp_Communication","VrHelp_Navigation","VrHelp_Settings","VrHelp_Applications"]
	}
};

var Localization_systemAppDict_sv_SE = {
	//"stringId" : "localString"
	"ActiveCallItem" : "Aktivt samtal",
	"AhaMaintError" : "Greška pri održ. aha",
	"AhaRadio" : "aha",
	"AmRadio" : "AM",
	"AndroidAuto" : "Android Auto",
	"Applications" : "Program",
	"AudioSourceNotAvailableBTAudio" : "Bluetooth-ljud inte tillgängligt",
	"AudioSourceNotAvailableCD" : "CD har tagits bort",
	"AudioSourceNotAvailableDVD" : "DVD har tagits bort",
	"AudioSourceNotAvailableTV" : "TV är inte tillgängligt",
	"AudioSourceNotAvailableUSB" : "USB-enhet har ändrats",
	"AuxIn" : "AUX",
	"BT" : "BT",
	"Bluetooth" : "Bluetooth",
	"BluetoothWithDevice" : "Bluetooth – {deviceName}",
	"CallHistory" : "Samtalshistorik",
	"CarPlay" : "Apple CarPlay",
	"CdPlayer" : "CD",
	"ChannelOffAir" : "Stanica se ne emituje",
	"ChannelUnauth" : "Stanica nije autorizovana",
	"CheckAntenna" : "Proverite antenu",
	"CheckTuner" : "Proverite radio",
	"Communication" : "Kommunikation",
	"Connect" : "Anslut",
	"Contacts" : "Kontakter",
	"DVDItem" : "DVD",
	"DabRadio" : "DAB",
	"DialPhone" : "Knappsats",
	"DidYouSay" : "Sa du...",
	"DisclaimerText" : "Delad uppmärksamhet kan orsaka olyckor. Använd inte under körning. Var alltid koncentrerad på körningen och följ trafikreglerna. Se ägarmanualen.",
	"DisconnectThenReconnect" : "Fel vid start av Siri. Koppla först ur och sedan in Apple Device igen.",
	"DriveRecord" : "Körhistorik",
	"DriverIDItem" : "Föraridentifiering",
	"EcoenergyApp" : "Bränsleförbrukning",
	"EcoenergyAppHEV" : "Körkontroll",
	"Email" : "E-post",
	"EngineOilLevel" : "Oljenivå i motor",
	"Entertainment" : "Underhållning",
	"ErrorWhileStartingSiri" : "Fel uppstod vid start av Siri.",
	"FailedNotificationRetrieval" : "Kan inte hämta aviseringslista",
	"FavoritesItem" : "Favoriter",
	"FmRadio" : "FM",
	"HDTrafficItem" : "HD Radio™ trafikkarta",
	"InitiateSiri" : "Håll talknappen intryckt för att starta en Siri session",
	"IntelligentDriveMasterItem" : "i-DM",
	"NavigationTitle" : "Navigation",
	"NoConnectionNotifyText" : "Vill du ansluta en telefon nu?",
	"NoConnectionNotifyTitle" : "Ingen telefon ansluten",
	"NoDeviceText" : "Vill du ansluta en enhet nu?",
	"NoDeviceTitle" : "Ingen enhet ansluten",
	"Notifications" : "Aviseringar",
	"NotifyIgnore" : "Ignorera",
	"NotifyIncomingMsg" : "Inkommande meddelande från:",
	"NotifyOff" : "Avisering av",
	"NotifyRead" : "Läs",
	"NotifyReadNow" : "Vill du läsa det nu?",
	"Pandora" : "Pandora",
	"ReconnectAhaRadio" : "Återansluter Bluetooth, aha Radio",
	"ReconnectBTAudio" : "Återansluter Bluetooth, spelar upp",
	"ReconnectCD" : "Verifierar CD, spelar upp",
	"ReconnectCarPlay" : "Återupptar Apple CarPlay",
	"ReconnectDVD" : "Verifierar DVD, spelar upp",
	"ReconnectEntMenuButton" : "Underhållningsmeny",
	"ReconnectFailedBTAudio" : "Kan inte återansluta Bluetooth-ljud",
	"ReconnectFailedCD" : "CD har tagits bort. Kan inte återuppta uppspelning.",
	"ReconnectFailedCarPlay" : "Kan inte återansluta Apple CarPlay",
	"ReconnectFailedDVD" : "DVD har tagits bort. Kan inte återuppta uppspelning.",
	"ReconnectFailedTV" : "TV är inte tillgängligt. Uppspelning kan inte återupptas.",
	"ReconnectFailedUSB" : "USB-enhet har ändrats. Kan inte återuppta uppspelning.",
	"ReconnectPandora" : "Återansluter Bluetooth-ljud för Pandora",
	"ReconnectStitcher" : "Återansluter Bluetooth-ljud för Stitcher",
	"ReconnectTV" : "Verifierar TV för att återuppta uppspelning",
	"ReconnectUSB" : "Återansluter USB-enhet, spelar upp",
	"RetryLabel" : "Prova igen",
	"SchedMaintenanceApp" : "Underhåll",
	"ScreenReplication" : "Kopiera displayen",
	"SdarsRadio" : "XM",
	"Settings" : "Inställningar",
	"SettingsCommunication" : "Inställningar",
	"Siri" : "Siri",
	"SiriDisabled" : "Siri är inte aktiverad på Apple-enhet.",
	"Sms" : "SMS",
	"StitcherItem" : "Stitcher",
	"TVItem" : "TV",
	"TempWarning" : "Temperaturvarning",
	"TempWarningText" : "Displayen är för varm. Bildskärmens kvalitet kan vara sämre tills den svalnat.",
	"TextDownloaded" : "SMS hämtad",
	"TextSent" : "SMS skickad",
	"TrafficAlertsItem" : "Trafikinformation",
	"USB" : "USB",
	"USB1AndroidAuto" : "USB 1 - Android Auto",
	"USB1CarPlay" : "USB 1 - Apple CarPlay",
	"USB2AndroidAuto" : "USB 2 - Android Auto",
	"UsbAudioA" : "USB 1",
	"UsbAudioAWithDevice" : "USB 1 - {deviceName}",
	"UsbAudioB" : "USB 2",
	"UsbAudioBWithDevice" : "USB 2 - {deviceName}",
	"UseCommander" : "Använd kommandofunktionen vid körning.",
	"VehicleDataTransferItem" : "Överföring av fordonsdata ",
	"VehicleStatusMonitor" : "Monitor fordonsstatus",
	"VehicleTelemetryTransfer" : "VTT",
	"VideoSignalLost" : "Izgubljen video signal",
	"VoiceNotSupported" : "Röst stöds inte ",
	"VoiceRecognition" : "Röstigenkänning",
	"VrHelp_Applications" : "Program",
	"VrHelp_Communication" : "Kommunikation",
	"VrHelp_Entertainment" : "Underhållning",
	"VrHelp_Favorites" : "Favoriter",
	"VrHelp_Navigation" : "Navigation",
	"VrHelp_Settings" : "Inställningar",
	"WarnGuidanceApp" : "Varningar",
	"WarningTitle" : "VARNING!",
	"XMAudio" : "SXM",
	"XMData" : "SXM Services",
	"agree" : "Jag godkänner",
	"VRD_aharadioSelectCall" : "Ring upp",
	"VRD_aharadioSelectDiscard" : "Släng",
	"VRD_aharadioSelectEpisodes" : "Lista över avsnitt",
	"VRD_aharadioSelectLBSTab" : "I närheten",
	"VRD_aharadioSelectMainList" : "Aha-huvudlista",
	"VRD_aharadioSelectMap" : "Karta",
	"VRD_aharadioSelectPresetsTab" : "Förval",
	"VRD_aharadioSelectSave" : "Spara",
	"VRD_aharadioSelectSettings" : "Ljudinställningar",
	"VRD_aharadioSelectShout" : "Rop",
	"VRD_aharadioSelectSource" : "Underhållning/ändra källa",
	"VRD_aharadioSelectThumbsDown" : "Tummen ner",
	"VRD_aharadioSelectThumbsUp" : "Tummen upp",
	"VRD_amradioPlayStationFrequency" : "Ställ in på {frequency} AM",
	"VRD_amradioSelectAutoMemory" : "Autominne",
	"VRD_amradioSelectFavorites" : "Favoriter",
	"VRD_amradioSelectHD" : "HD-stationer",
	"VRD_amradioSelectHDOff" : "HD-radio av",
	"VRD_amradioSelectHDOn" : "HD-radio på",
	"VRD_amradioSelectScanOff" : "Sökning av",
	"VRD_amradioSelectScanOn" : "Sökning på",
	"VRD_amradioSelectSeekNext" : "Sök nästa",
	"VRD_amradioSelectSeekPrevious" : "Sök föregående",
	"VRD_amradioSelectSettings" : "Ljudinställningar",
	"VRD_amradioSelectSource" : "Gå till underhållningsmenyn",
	"VRD_amradioSelectStationFrequency" : "{AMFrequency}",
	"VRD_amradioSelectTrafficAlert" : "Trafikvarning",
	"VRD_amradioSelectTrafficAlertOff" : "Trafikvarning av",
	"VRD_amradioSelectTrafficAlertOn" : "Trafikvarning på",
	"VRD_amradioSelectTune" : "Ställ in",
	"VRD_amradioSelectUpdateAutoMemory" : "Autominnessökning",
	"VRD_amradioSelectiTunesTagging" : "iTunes-taggning",
	"VRD_amradioTuneDown" : "Ställ in nedåt",
	"VRD_amradioTuneUp" : "Ställ in uppåt",
	"VRD_amradioUpdateAutoMemory" : "Uppdatera stationslista",
	"VRD_auxinSelectSettings" : "Ljudinställningar",
	"VRD_auxinSelectSource" : "Underhållning/ändra källa",
	"VRD_btaudioScanPlay" : "Skanna spelning",
	"VRD_btaudioSelectConnect" : "Anslut",
	"VRD_btaudioSelectRootMenu" : "Rotmeny",
	"VRD_btaudioSelectSettings" : "Ljudinställningar",
	"VRD_btaudioSelectSource" : "Gå till underhållningsmenyn",
	"VRD_btaudioToggleRepeat" : "Upprepa",
	"VRD_btaudioToggleShuffle" : "Blanda",
	"VRD_carplaySelectApplications" : "Program",
	"VRD_cdGoSettings" : "Ljudinställningar",
	"VRD_cdHandleStartScan" : "Starta sökning",
	"VRD_cdPlayBeginning" : "Börja om",
	"VRD_cdRepeatFolder" : "Upprepa mapp",
	"VRD_cdRepeatOff" : "Upprepning av",
	"VRD_cdRepeatOn" : "Upprepning: på",
	"VRD_cdRepeatTrack" : "Upprepa spår",
	"VRD_cdSelectCurrentFolder" : "Aktuell mapp",
	"VRD_cdSelectRepeat" : "Upprepa",
	"VRD_cdSelectRootFolder" : "Rotmeny",
	"VRD_cdSelectShuffle" : "Blanda",
	"VRD_cdSelectSource" : "Gå till underhållningsmenyn",
	"VRD_cdSelectTrackList" : "Spårlista",
	"VRD_cdSelectTrackNumber" : "Spela upp spår {Number}",
	"VRD_cdShuffleDisk" : "Blanda skiva",
	"VRD_cdShuffleFolder" : "Blanda mapp",
	"VRD_cdShuffleOff" : "Blandning av",
	"VRD_cdShuffleOn" : "Blandning: på",
	"VRD_commonAddToFavorites" : "Lägg till i favoriter",
	"VRD_commonCancel" : "Avbryt",
	"VRD_commonFastForward" : "Snabbspola framåt",
	"VRD_commonGoBack" : "Gå tillbaka",
	"VRD_commonIntentParent" : "Överordnad",
	"VRD_commonIntentParentUSBAudio" : "Överordnad",
	"VRD_commonIntentUSBAudio" : "Hem",
	"VRD_commonIntentUSBAudioBG" : "Hem",
	"VRD_commonMenuUp" : "Upp i meny",
	"VRD_commonNext" : "Nästa",
	"VRD_commonNo" : "Nej",
	"VRD_commonPageDown" : "Sida ned/rulla nedåt",
	"VRD_commonPageUp" : "Sida upp/rulla uppåt",
	"VRD_commonPause" : "Paus",
	"VRD_commonPrevious" : "Föregående",
	"VRD_commonResume" : "Spela upp/återuppta",
	"VRD_commonRewind" : "Spola tillbaka",
	"VRD_commonSelectLineNumber" : "Rad {lineNumber}",
	"VRD_commonYes" : "Ja/OK",
	"VRD_contactsChooseContactName" : "{ContactName}",
	"VRD_contactsDisambiguateContactName" : "Visa {ContactName}",
	"VRD_contactsImportAll" : "Importera alla kontakter",
	"VRD_contactsImportCancel" : "Avbryt imp.",
	"VRD_contactsImportContacts" : "Redigera kontakter",
	"VRD_contactsImportSingle" : "Importera vald kontakt",
	"VRD_contactsRemoveContact" : "Ta bort kontakt",
	"VRD_contactsSelectCall" : "Ring upp",
	"VRD_contactsSelectContactName" : "{ContactName}",
	"VRD_contactsSelectDownload" : "Ladda ned",
	"VRD_contactsSelectFavorites" : "Favoriter",
	"VRD_contactsSelectNone" : "Inget av dessa",
	"VRD_contactsSelectReadContactName" : "Läs kontaktnamn",
	"VRD_contactsSelectRemove" : "Ta bort",
	"VRD_contactsSelectRetry" : "Försök igen",
	"VRD_contactsSendPhoneType" : "{phoneType}",
	"VRD_contactsShowAddress" : "Adress",
	"VRD_dabDisplayDABSettings" : "DAB Inställningar",
	"VRD_dabDisplayEnsembleList" : "Välj Ensemble",
	"VRD_dabDisplayStationList" : "Stationslista",
	"VRD_dabSelectFavorites" : "Favoriter",
	"VRD_dabSelectScan" : "Sök",
	"VRD_dabSelectSeekNext" : "Nästa",
	"VRD_dabSelectSeekPrevious" : "Föregående",
	"VRD_dabSelectSettings" : "Ljudinställningar",
	"VRD_dabSelectSource" : "Underhållning",
	"VRD_dabTAToggleOFF" : "Trafik av",
	"VRD_dabTAToggleON" : "Trafik på",
	"VRD_dabTAToggleVois" : "Trafikvarning (TA)",
	"VRD_dabUpdateStationList" : "Uppdatera lista",
	"VRD_dvdClearPin" : "Radera siffror",
	"VRD_dvdSayGRating" : "G",
	"VRD_dvdSayPG12" : "PG tolv",
	"VRD_dvdSayR15" : "R femton plus",
	"VRD_dvdSayR18" : "--",
	"VRD_dvdSelectAspectRatio" : "Bildformat",
	"VRD_dvdSelectAudioSettings" : "Videoinställningar",
	"VRD_dvdSelectCameraAngle" : "Kameravinkel",
	"VRD_dvdSelectEditPin" : "Ange PIN-kod",
	"VRD_dvdSelectParentLock" : "Föräldralås",
	"VRD_dvdSelectParentLockOff" : "Föräldralås av",
	"VRD_dvdSelectParentLockOn" : "Föräldralås på",
	"VRD_dvdSelectParentLockRating" : "Föräldralåsklassning",
	"VRD_dvdSelectResetPin" : "Återställ PIN-kod",
	"VRD_dvdSelectRootMenu" : "Rotmeny",
	"VRD_dvdSelectSettings" : "Ljudinställningar",
	"VRD_dvdSelectSource" : "Underhållning",
	"VRD_dvdSelectSubtitleOff" : "Textning av",
	"VRD_dvdSelectSubtitleOn" : "Textning på",
	"VRD_dvdSlowForward" : "Snabbspola framåt",
	"VRD_dvdSlowRewind" : "Spola tillbaka",
	"VRD_dvdVUISendPin" : "{FourDigitPin}",
	"VRD_emailSelectAllAccounts" : "Alla konton",
	"VRD_emailSelectCall" : "Ring upp",
	"VRD_emailSelectContactName" : "{ContactName}",
	"VRD_emailSelectContinueEmail" : "Fortsätt e-post",
	"VRD_emailSelectDelete" : "Radera",
	"VRD_emailSelectDiscard" : "Släng",
	"VRD_emailSelectImportEmail" : "Uppdatera inkorgen",
	"VRD_emailSelectInbox" : "E-postinkorg",
	"VRD_emailSelectInboxSelector" : "Inkorg",
	"VRD_emailSelectMessage" : "Lägg till meddelande",
	"VRD_emailSelectNone" : "Inget av dessa",
	"VRD_emailSelectReply" : "Svara",
	"VRD_emailSelectReplyAll" : "Svara alla",
	"VRD_emailSelectRetry" : "Prova igen",
	"VRD_emailSelectReturn" : "Tillbaka",
	"VRD_emailSelectSend" : "Skicka",
	"VRD_emailSelectSenderName" : "{senderName}",
	"VRD_emnaviAcceptAvoidance" : "Bekräfta",
	"VRD_emnaviAddCurrentPosToFavourites" : "Lägg till aktuell position i favoriter",
	"VRD_emnaviAddWaypointCityCenter" : "Lägg till vägmärke stadscentrum",
	"VRD_emnaviAddWaypointDistrictCenter" : "Lägg till vägmärke regioncentrum",
	"VRD_emnaviAddWaypointFavorite" : "Lägg till favoritvägmärke",
	"VRD_emnaviAddWaypointPOI" : "Lägg till vägmärke {poiHypList}",
	"VRD_emnaviAvoidRouteAhead" : "Undvik rutten framåt",
	"VRD_emnaviCancelRoute" : "Avbryt rutt",
	"VRD_emnaviDecreaseAvoidanceLength" : "Mindre",
	"VRD_emnaviGoToCockpit" : "Börja",
	"VRD_emnaviIncreaseAvoidanceLength" : "Mer",
	"VRD_emnaviJPJ_VDEHypothesisList" : "Namn på en stad",
	"VRD_emnaviNavigateHere" : "Navigera hit",
	"VRD_emnaviNavigateHome" : "Navigera hem",
	"VRD_emnaviNavigateToARecentDestination" : "Navigera till en av de senaste destinationerna",
	"VRD_emnaviNavigateToAddress" : "Navigera till adress",
	"VRD_emnaviNavigateToCityCenter" : "Naivgera till stadscentrum",
	"VRD_emnaviNavigateToDistrictCenter" : "Navigera till regioncentrum",
	"VRD_emnaviNavigateToFavorite" : "Navigera till favorit",
	"VRD_emnaviNavigateToPOI" : "Navigera till {poiHypList}",
	"VRD_emnaviNewDestination" : "Ny destination",
	"VRD_emnaviRepeatInstruction" : "Upprepa instruktion",
	"VRD_emnaviRouteSummary" : "Sammanfattning av rutt",
	"VRD_emnaviSelectCancelRoute" : "Rensa rutt",
	"VRD_emnaviSelectNavigateToAddress" : "Navigera till en adress",
	"VRD_emnaviSimpleHypothesisList" : "Ett ortnamn",
	"VRD_emnaviStepByStep" : "Steg för steg-post",
	"VRD_emnaviTravelViaARecentDestination" : "Lägg till vägmärke senaste destination",
	"VRD_emnaviTravelViaAddress" : "Res via adress",
	"VRD_emnaviTravelViaHome" : "Res via hem",
	"VRD_emnaviTryAgain" : "Försök igen",
	"VRD_emnaviUniSimpleHypothesisList" : "En adress",
	"VRD_emnaviUniVDEHypothesisList" : "En adress",
	"VRD_emnaviVDEHypothesisList" : "En adress",
	"VRD_emnaviWhereAmI" : "Var är jag",
	"VRD_emnaviZoomIn" : "Zooma in",
	"VRD_emnaviZoomOut" : "Zooma ut",
	"VRD_fmradioPlayStationFrequency" : "Ställ in på {frequency} FM",
	"VRD_fmradioSelectAutoMemory" : "Autominne",
	"VRD_fmradioSelectChangeGenre" : "Ändra genre",
	"VRD_fmradioSelectFMSettings" : "FM-inställningar",
	"VRD_fmradioSelectFavorites" : "Favoriter",
	"VRD_fmradioSelectGenreSeek" : "Sök i kategori",
	"VRD_fmradioSelectHDChannel" : "{HD Channel}",
	"VRD_fmradioSelectHDChannels" : "HD-stationer",
	"VRD_fmradioSelectHDRadio" : "HD-radio",
	"VRD_fmradioSelectHDRadioOff" : "HD-radio av",
	"VRD_fmradioSelectHDRadioOn" : "HD-radio på",
	"VRD_fmradioSelectScanOff" : "Sökning av",
	"VRD_fmradioSelectScanOn" : "Sökning på",
	"VRD_fmradioSelectSeekNext" : "Sök nästa",
	"VRD_fmradioSelectSeekPrevious" : "Sök föregående",
	"VRD_fmradioSelectSettings" : "Ljudinställningar",
	"VRD_fmradioSelectSource" : "Underhållning/ändra källa",
	"VRD_fmradioSelectStationAll" : "Alla stationer",
	"VRD_fmradioSelectStationFrequency" : "{frequency}",
	"VRD_fmradioSelectStationGenre" : "{genreName}",
	"VRD_fmradioSelectStationList" : "Stationslista",
	"VRD_fmradioSelectStationName" : "{stationName}",
	"VRD_fmradioSelectTrafficAlert" : "Trafikvarning (TA)",
	"VRD_fmradioSelectTrafficAlertOff" : "Trafik av",
	"VRD_fmradioSelectTrafficAlertOn" : "Trafik på",
	"VRD_fmradioSelectTune" : "Ställ in",
	"VRD_fmradioSelectUpdateAutoMemory" : "Uppdatera autominne",
	"VRD_fmradioSelectiTunesTagging" : "iTunes-taggning",
	"VRD_fmradioTuneDown" : "Ställ in nedåt",
	"VRD_fmradioTuneUp" : "Ställ in uppåt",
	"VRD_fmradioTurnOffAF" : "Alternativ frekvens av",
	"VRD_fmradioTurnOffREG" : "Regionlås av",
	"VRD_fmradioTurnOnAF" : "Alternativ frekvens på",
	"VRD_fmradioTurnOnREG" : "Regionlås på",
	"VRD_fmradioUpdateAutoMemory" : "Uppdatera stationslista",
	"VRD_pandoraAddStation" : "Lägg till station",
	"VRD_pandoraAddStationFromArtist" : "Skapa station från artist",
	"VRD_pandoraAddStationFromSong" : "Skapa station från låt",
	"VRD_pandoraAddToFavorites" : "Lägg till i favoriter",
	"VRD_pandoraBookmarkArtist" : "Bokmärk artist",
	"VRD_pandoraBookmarkSong" : "Bokmärk låt",
	"VRD_pandoraCreateStation" : "Skapa station",
	"VRD_pandoraSelectAddCurrentStation" : "Lägg till",
	"VRD_pandoraSelectDelete" : "Ta bort",
	"VRD_pandoraSelectEditDelete" : "Radera",
	"VRD_pandoraSelectEditMove" : "Flytta",
	"VRD_pandoraSelectEditReplace" : "Ersätt",
	"VRD_pandoraSelectFavorites" : "Favoriter",
	"VRD_pandoraSelectMove" : "Flytta",
	"VRD_pandoraSelectQuickMix" : "Blanda",
	"VRD_pandoraSelectSettings" : "Ljudinställningar",
	"VRD_pandoraSelectSortBy" : "Sortera",
	"VRD_pandoraSelectSource" : "Underhållning",
	"VRD_pandoraSelectStationList" : "Stationslista",
	"VRD_pandoraShowBookmarkOptions" : "Bokmärke",
	"VRD_pandoraShowByAZ" : "Sortera alfabetiskt",
	"VRD_pandoraShowByDate" : "Sortera efter datum",
	"VRD_pandoraSkip" : "Hoppa över",
	"VRD_pandoraThumbsDown" : "Tummen ner",
	"VRD_pandoraThumbsUp" : "Tummen upp",
	"VRD_phoneCall" : "Samtal",
	"VRD_phoneCallBack" : "Ring tillbaka",
	"VRD_phoneCallByName" : "Ring upp namn",
	"VRD_phoneCallByNumber" : "Ring upp nummer",
	"VRD_phoneCallContactType" : "Ring upp {contactName}{contactType}",
	"VRD_phoneCallLast" : "Ring upp senaste nummer",
	"VRD_phoneChooseContactType" : "{contactName} {contactType}",
	"VRD_phoneDialAnyNumber" : "Ring upp {number}",
	"VRD_phoneDialpadClearAllDigits" : "Rensa alla siffror",
	"VRD_phoneDialpadDeleteDigit" : "Radera",
	"VRD_phoneDialpadPhoneNumber" : "{phoneNumber}",
	"VRD_phoneReDial" : "Ring upp igen",
	"VRD_phoneSelectByName" : "Namn",
	"VRD_phoneSelectByNumber" : "Nummer",
	"VRD_phoneSelectContactType" : "{contactType}",
	"VRD_phoneSelectDialPad" : "Knappsats",
	"VRD_phoneSelectFavorites" : "Favoriter",
	"VRD_phoneSelectRecentCalls" : "Senaste samtal",
	"VRD_phoneSelectRecentCallsAll" : "Alla samtal",
	"VRD_phoneSelectRecentCallsMissed" : "Missade samtal",
	"VRD_satradioBackSpaceDelete" : "Radera siffror",
	"VRD_satradioChangeLockCode" : "Ändra PIN-kod",
	"VRD_satradioEnterPIN" : "{4digitPin}",
	"VRD_satradioInitializeLockCode" : "Initiera PIN-kod",
	"VRD_satradioPlayChannelName" : "Spela upp {channelName}",
	"VRD_satradioPlayStationNumber" : "Ställ in på {channelNumber}",
	"VRD_satradioResetLockCode" : "Återställ PIN-kod",
	"VRD_satradioSeekNext" : "Sök nästa",
	"VRD_satradioSeekPrevious" : "Sök föregående",
	"VRD_satradioSelectChangeCategory" : "Kategori",
	"VRD_satradioSelectFavorites" : "Favoriter",
	"VRD_satradioSelectParentalLock" : "Föräldralås",
	"VRD_satradioSelectScanOff" : "Sökning av",
	"VRD_satradioSelectScanOn" : "Sökning på",
	"VRD_satradioSelectSettings" : "Ljudinställningar",
	"VRD_satradioSelectSource" : "Underhållning",
	"VRD_satradioSelectStation" : "Station {Station number}",
	"VRD_satradioSelectStationAll" : "Alla kanaler",
	"VRD_satradioSelectStationCategory" : "{categoryName}",
	"VRD_satradioSelectStationList" : "Kanallista",
	"VRD_satradioTurnChannelLockOFF" : "Lås upp aktuell kanal",
	"VRD_satradioTurnChannelLockON" : "Lås aktuell kanal",
	"VRD_satradioTurnParentalLockOFF" : "Sessionslås av",
	"VRD_satradioTurnParentalLockON" : "Sessionslås på",
	"VRD_smsCallPhoneNumber" : "Ring upp",
	"VRD_smsDelete" : "Radera",
	"VRD_smsImportMessages" : "Uppdatera textinkorg",
	"VRD_smsReply" : "Svara",
	"VRD_smsSayAnyConversation" : "{senderName}",
	"VRD_smsSelectBody" : "Lägg till meddelande",
	"VRD_smsSelectContactName" : "{ContactName}",
	"VRD_smsSelectContinueTextMessage" : "Fortsätt meddelande",
	"VRD_smsSelectDiscard" : "Släng",
	"VRD_smsSelectInbox" : "SMS-inkorgslista",
	"VRD_smsSelectNone" : "Inget av dessa",
	"VRD_smsSelectRetry" : "Prova igen",
	"VRD_smsSelectReturn" : "Återgå",
	"VRD_smsSelectSend" : "Skicka",
	"VRD_stitcherAddToFavorites" : "Lägg till i favoriter",
	"VRD_stitcherRemoveFromFavorites" : "Ta bort från favoriter",
	"VRD_stitcherSaveFavorites" : "Spara ändringar",
	"VRD_stitcherSelectSettings" : "Ljudinställningar",
	"VRD_stitcherSelectSource" : "Underhållning",
	"VRD_stitcherSelectStationList" : "Stationslista",
	"VRD_stitcherThumbsDown" : "Tummen ner",
	"VRD_stitcherThumbsUp" : "Tummen upp",
	"VRD_systemSelectAhaRadio" : "Aha Radio",
	"VRD_systemSelectAndroidAuto" : "Android Auto",
	"VRD_systemSelectApplications" : "Program",
	"VRD_systemSelectAuxIn" : "Linje in/AUX",
	"VRD_systemSelectBTAudio" : "Bluetooth",
	"VRD_systemSelectCD" : "CD",
	"VRD_systemSelectCallHistory" : "Samtalshistorik",
	"VRD_systemSelectCarPlay" : "CarPlay",
	"VRD_systemSelectCommunication" : "Kommunikation",
	"VRD_systemSelectConnect" : "Anslut",
	"VRD_systemSelectContacts" : "Kontakter",
	"VRD_systemSelectDAB" : "DAB",
	"VRD_systemSelectDVD" : "DVD",
	"VRD_systemSelectDisplayClock" : "Klocka",
	"VRD_systemSelectDisplayOff" : "Släck skärm",
	"VRD_systemSelectEmail" : "E-post",
	"VRD_systemSelectEntertainment" : "Underhållning",
	"VRD_systemSelectEntertainmentMenu" : "Underhållningsmeny",
	"VRD_systemSelectFavorites" : "Favoriter",
	"VRD_systemSelectNavigation" : "Navigation",
	"VRD_systemSelectNotifications" : "Meddelanden",
	"VRD_systemSelectNotifyOff" : "Avisering av",
	"VRD_systemSelectPandora" : "Pandora",
	"VRD_systemSelectPhone" : "Telefon",
	"VRD_systemSelectRadioAM" : "AM-radio",
	"VRD_systemSelectRadioFM" : "FM-radio",
	"VRD_systemSelectRetry" : "Prova igen",
	"VRD_systemSelectSatRadio" : "Satellitradio",
	"VRD_systemSelectSettings" : "Inställningar",
	"VRD_systemSelectSiri" : "Siri",
	"VRD_systemSelectSms" : "Text/SMS",
	"VRD_systemSelectStitcher" : "Stitcher",
	"VRD_systemSelectTV" : "TV",
	"VRD_systemSelectTrafficAlert" : "Trafikvarning (TA)",
	"VRD_systemSelectTutorial" : "Handledning",
	"VRD_systemSelectUSB" : "USB",
	"VRD_systemSelectUSBA" : "USB 1",
	"VRD_systemSelectUSBB" : "USB 2",
	"VRD_systemSelectXmAudio" : "SXM-radio",
	"VRD_tvSelectView" : "Vy",
	"VRD_usbaudioBrowse" : "Bläddra",
	"VRD_usbaudioBrowseAlbum" : "Bläddra {albumName}",
	"VRD_usbaudioBrowseAlbums" : "Bläddra album",
	"VRD_usbaudioBrowseAll" : "Bläddra alla låtar eller album eller artister",
	"VRD_usbaudioBrowseAnyAlbum" : "Bläddra [Album] {albumName}",
	"VRD_usbaudioBrowseAnyArtist" : "Bläddra [Artist] {artistName}",
	"VRD_usbaudioBrowseAnyFolder" : "Bläddra mapp {folderName}",
	"VRD_usbaudioBrowseArtist" : "Bläddra {artistName}",
	"VRD_usbaudioBrowseArtists" : "Bläddra artist",
	"VRD_usbaudioBrowseAudiobooks" : "Bläddra ljudböcker",
	"VRD_usbaudioBrowseFolder" : "Bläddra {folderName}",
	"VRD_usbaudioBrowseFolders" : "Bläddra mapp",
	"VRD_usbaudioBrowseGenre" : "Bläddra [Genre] {genreName}",
	"VRD_usbaudioBrowseGenres" : "Bläddra genre",
	"VRD_usbaudioBrowseLineNumber" : "Bläddra rad {lineNumber}",
	"VRD_usbaudioBrowsePlaylist" : "Bläddra spellista {playlistName}",
	"VRD_usbaudioBrowsePlaylists" : "Bläddra spellista",
	"VRD_usbaudioBrowsePodcast" : "Bläddra podcast {podcastName}",
	"VRD_usbaudioBrowsePodcasts" : "Bläddra podcaster",
	"VRD_usbaudioBrowseSongs" : "Bläddra låt",
	"VRD_usbaudioChooseAlbumArtist" : "{artistName}",
	"VRD_usbaudioGenerateMoreLikeThis" : "Mer sånt här",
	"VRD_usbaudioPlayAlbums" : "Spela upp album",
	"VRD_usbaudioPlayAll" : "Spela upp alla",
	"VRD_usbaudioPlayAnyAlbum" : "Spela upp {Album] {albumName}",
	"VRD_usbaudioPlayAnyArtist" : "Spela upp [Artist] {artistName}",
	"VRD_usbaudioPlayAnyFolder" : "Spela upp mapp {folderName}",
	"VRD_usbaudioPlayArtistAlbum" : "Spela upp {artistName} {albumName}",
	"VRD_usbaudioPlayArtists" : "Spela upp artist",
	"VRD_usbaudioPlayAudiobook" : "Spela upp ljudbok {AudiobookName}",
	"VRD_usbaudioPlayAudiobooks" : "Spela upp ljudböcker",
	"VRD_usbaudioPlayChapter" : "{chapterName}",
	"VRD_usbaudioPlayChapterIndex" : "Spela upp kapitel {index} {chapter}",
	"VRD_usbaudioPlayEpisode" : "{episodeName}",
	"VRD_usbaudioPlayFolder" : "Spela upp {folderName}",
	"VRD_usbaudioPlayFolders" : "Spela upp mapp",
	"VRD_usbaudioPlayGenre" : "Spela upp [Genre] {genreName}",
	"VRD_usbaudioPlayGenres" : "Spela upp genre",
	"VRD_usbaudioPlayLineNumber" : "Spela upp [Rad] {lineNumber}",
	"VRD_usbaudioPlayPlaylist" : "Spela upp spellista {playlistName}",
	"VRD_usbaudioPlayPlaylists" : "Spela upp spellista",
	"VRD_usbaudioPlayPodcast" : "Spela upp podcast {PodcastName}",
	"VRD_usbaudioPlayPodcasts" : "Spela upp podcaster",
	"VRD_usbaudioPlaySongs" : "Spela upp låt",
	"VRD_usbaudioRepeat" : "Upprepa",
	"VRD_usbaudioRepeatAll" : "Upprepa alla",
	"VRD_usbaudioRepeatOff" : "Upprepning av",
	"VRD_usbaudioRepeatSong" : "Upprepa låt",
	"VRD_usbaudioRewind" : "Spola tillbaka",
	"VRD_usbaudioSelectAlbum" : "Album {albumName}",
	"VRD_usbaudioSelectAlbums" : "Album",
	"VRD_usbaudioSelectAll" : "Alla avsnitt eller kapitel eller låtar eller album eller artister",
	"VRD_usbaudioSelectArtist" : "Artist {artistName}",
	"VRD_usbaudioSelectArtists" : "Artist",
	"VRD_usbaudioSelectAudiobook" : "{audiobookName}",
	"VRD_usbaudioSelectAudiobooks" : "Ljudböcker",
	"VRD_usbaudioSelectFolder" : "Mapp {folderName}",
	"VRD_usbaudioSelectFolders" : "Mappar",
	"VRD_usbaudioSelectGenre" : "Genre {genreName}",
	"VRD_usbaudioSelectGenres" : "Kategori",
	"VRD_usbaudioSelectPlaylist" : "Spellista {playlistName}",
	"VRD_usbaudioSelectPlaylists" : "Spellista",
	"VRD_usbaudioSelectPodcast" : "{podcastName}",
	"VRD_usbaudioSelectPodcasts" : "Podcast",
	"VRD_usbaudioSelectRootFolder" : "Rotmeny",
	"VRD_usbaudioSelectSettings" : "Ljudinställningar",
	"VRD_usbaudioSelectSongs" : "Låt",
	"VRD_usbaudioSelectSourceMenu" : "Underhållning",
	"VRD_usbaudioShuffle" : "Blanda",
	"VRD_usbaudioShuffleOff" : "Blandning av",
	"VRD_usbaudioShuffleOn" : "Blandning på",
	"VRD_usbaudioSongList" : "Låtlista",
	"VRD_xmaudioBackSpaceDelete" : "Radera siffror",
	"VRD_xmaudioChangeLockCode" : "Ange PIN-kod",
	"VRD_xmaudioConfirmDelete" : "Radera",
	"VRD_xmaudioEnterPIN" : "{fourDigitPIN}",
	"VRD_xmaudioPlayChannelName" : "Spela upp XM-kanal {channelName}",
	"VRD_xmaudioPlayStationNumber" : "Ställ in på {channelNumber}",
	"VRD_xmaudioResetLockCode" : "Återställ PIN-kod",
	"VRD_xmaudioSelectCallXM" : "Ring upp XM",
	"VRD_xmaudioSelectChangeCategory" : "Ändra kategori",
	"VRD_xmaudioSelectContinueListening" : "Fortsätt lyssna",
	"VRD_xmaudioSelectDismiss" : "Stäng",
	"VRD_xmaudioSelectEveryOccurance" : "Varje förekomst",
	"VRD_xmaudioSelectEveryOtherReport" : "Alla andra rapporter",
	"VRD_xmaudioSelectEveryReport" : "Alla rapporter",
	"VRD_xmaudioSelectExitTuneMix" : "Stäng TuneMix",
	"VRD_xmaudioSelectFavorites" : "Favoriter",
	"VRD_xmaudioSelectListenNow" : "Lyssna nu",
	"VRD_xmaudioSelectMove" : "Flytta",
	"VRD_xmaudioSelectNearestCity" : "Närmaste stad",
	"VRD_xmaudioSelectOnlyFirstAfterVehicleStart" : "Fordonsstart",
	"VRD_xmaudioSelectOnlyFirstOccuranceInGame" : "Första förekomst",
	"VRD_xmaudioSelectReplayAlert" : "Spela upp varning igen",
	"VRD_xmaudioSelectReturnToPrevious" : "Gå tillbaka till föregående",
	"VRD_xmaudioSelectSFSportBaseball" : "Baseball",
	"VRD_xmaudioSelectSFSportNCAA" : "Collegefotboll",
	"VRD_xmaudioSelectSFSportNFL" : "Professionell fotboll",
	"VRD_xmaudioSelectSFSportNHL" : "Ishockey",
	"VRD_xmaudioSelectScanOff" : "Sökning av",
	"VRD_xmaudioSelectScanOn" : "Sökning på",
	"VRD_xmaudioSelectSettings" : "Inställningar",
	"VRD_xmaudioSelectSoundSettings" : "Ljudinställningar",
	"VRD_xmaudioSelectSource" : "Underhållning",
	"VRD_xmaudioSelectStation" : "Station {channelNumber}",
	"VRD_xmaudioSelectStationAll" : "Alla kanaler",
	"VRD_xmaudioSelectStationCategory" : "{categoryName}",
	"VRD_xmaudioSelectStationFeaturedFavorites" : "Aktuella favoriter",
	"VRD_xmaudioSelectStationList" : "Stationer",
	"VRD_xmaudioSelectTuneMix" : "TuneMix",
	"VRD_xmaudioSelectTuneMixChannel" : "Kanalalternativ för TuneMix",
	"VRD_xmaudioSelectTuneMixChannelsOptions" : "Stationsalternativ",
	"VRD_xmaudioSelectTuneMixCreation" : "Skapa ny TuneMix-kanal",
	"VRD_xmaudioSelectTuneMixEdit" : "Redigera TuneMix-kanal",
	"VRD_xmaudioSelectTuneMixEditOps" : "Redigeringsalternativ för TuneMix",
	"VRD_xmaudioSelectTuneMixRemove" : "Ta bort TuneMix-kanal",
	"VRD_xmaudioSelectTuneMixRename" : "Byt namn på TuneMix",
	"VRD_xmaudioSelectTurnAlertsOff" : "Stäng av varningar",
	"VRD_xmaudioSelectiTunesTagging" : "iTunes-taggning",
	"VRD_xmaudioSetChannelLock" : "Lås kanal",
	"VRD_xmaudioSetParentalLock" : "Sessionslås",
	"VRD_xmdataSelectFuelPrices" : "Bränslepriser",
	"VRD_xmdataSelectMovies" : "Filmer",
	"VRD_xmdataSelectParking" : "Parkering",
	"VRD_xmdataSelectSports" : "Sport",
	"VRD_xmdataSelectStock" : "Aktier",
	"VRD_xmdataSelectTrafficPlus" : "Trafik plus",
	"VRD_xmdataSelectWeatherForecast" : "Väderleksrapport",
	"VRD_xmdataSelectWeatherRadar" : "Väderradar",
	"VRD_xmdataSelectWeatherSecurityAlerts" : "Säkerhetsvarningar för väder",
};

framework.registerAppDictLoaded("system", "sv_SE");