var __VrHelpPositionTable__systemAppDict_nl_NL = {
	"HomeScreen_Help" : {
		"Right" : ["VrHelp_Favorites"],
		"Left" : ["VrHelp_Entertainment","VrHelp_Communication","VrHelp_Navigation","VrHelp_Settings","VrHelp_Applications"]
	}
};

var Localization_systemAppDict_nl_NL = {
	//"stringId" : "localString"
	"ActiveCallItem" : "Actieve oproep",
	"AhaMaintError" : "aha onderhoudsfout",
	"AhaRadio" : "aha",
	"AmRadio" : "AM",
	"AndroidAuto" : "Android Auto",
	"Applications" : "Applicaties",
	"AudioSourceNotAvailableBTAudio" : "Bluetooth Audio Niet Beschikbaar",
	"AudioSourceNotAvailableCD" : "CD werd verwijderd",
	"AudioSourceNotAvailableDVD" : "DVD werd verwijderd",
	"AudioSourceNotAvailableTV" : "TV niet beschikbaar",
	"AudioSourceNotAvailableUSB" : "USB-apparaat is gewijzigd",
	"AuxIn" : "AUX",
	"BT" : "BT",
	"Bluetooth" : "Bluetooth",
	"BluetoothWithDevice" : "Bluetooth - {deviceName}",
	"CallHistory" : "Belgeschiedenis",
	"CarPlay" : "Apple CarPlay",
	"CdPlayer" : "CD",
	"ChannelOffAir" : "Kanaal uit de lucht",
	"ChannelUnauth" : "Ongeautoriseerd kanaal",
	"CheckAntenna" : "Controleer antenne",
	"CheckTuner" : "Controleer audio",
	"Communication" : "Communicatie",
	"Connect" : "Verbinden",
	"Contacts" : "Contactpersonen",
	"DVDItem" : "DVD",
	"DabRadio" : "DAB",
	"DialPhone" : "Bellen",
	"DidYouSay" : "Zei u...",
	"DisclaimerText" : "Afleiding kan leiden tot ongelukken. Bedien het apparaat niet tijdens het rijden. Concentreer u altijd op de weg en houd u aan de verkeersregels. Zie handleiding.",
	"DisconnectThenReconnect" : "Fout bij starten Siri. Ontkoppel Apple Device en koppel opnieuw.",
	"DriveRecord" : "Rijbestand",
	"DriverIDItem" : "Identificatie bestuurder",
	"EcoenergyApp" : "Brandstofverbruik",
	"EcoenergyAppHEV" : "Schijfmonitor",
	"Email" : "Email",
	"EngineOilLevel" : "Oliepeil motor",
	"Entertainment" : "Entertainment",
	"ErrorWhileStartingSiri" : "Fout tijdens starten Siri.",
	"FailedNotificationRetrieval" : "Mededelingslijst terughalen mislukt",
	"FavoritesItem" : "Favorieten",
	"FmRadio" : "FM",
	"HDTrafficItem" : "HD Radio™ wegenkaart",
	"InitiateSiri" : "Houd de spreekknop lang ingedrukt om Siri sessie te beginnen",
	"IntelligentDriveMasterItem" : "i-DM",
	"NavigationTitle" : "Navigatie",
	"NoConnectionNotifyText" : "Wilt u nu een telefoon koppelen?",
	"NoConnectionNotifyTitle" : "Geen Telefoon verbonden",
	"NoDeviceText" : "Wilt u nu een apparaat aansluiten?",
	"NoDeviceTitle" : "Geen apparaat aangesloten",
	"Notifications" : "Mededelingen",
	"NotifyIgnore" : "Negeren",
	"NotifyIncomingMsg" : "Binnenkomend Bericht van:",
	"NotifyOff" : "Mededel. UIT",
	"NotifyRead" : "Lezen",
	"NotifyReadNow" : "Wilt u het nu lezen?",
	"Pandora" : "Pandora",
	"ReconnectAhaRadio" : "Bluetooth audio vr aha Radio opn. Verb.",
	"ReconnectBTAudio" : "Bluet. audio opn. verb. om afsp. te herv.",
	"ReconnectCD" : "CD verifiëren om afspelen te hervatten",
	"ReconnectCarPlay" : "Bezig met hervatten Apple CarPlay.",
	"ReconnectDVD" : "DVD verifiëren om afspelen te herv.",
	"ReconnectEntMenuButton" : "Entertainment Menu",
	"ReconnectFailedBTAudio" : "Bluetooth audio kan niet opnieuw worden verbonden",
	"ReconnectFailedCD" : "CD werd verwijderd. Opnieuw afspelen mislukt.",
	"ReconnectFailedCarPlay" : "Herstellen verbinding Apple CarPlay mislukt",
	"ReconnectFailedDVD" : "DVD werd verwijderd. Opnieuw afspelen mislukt.",
	"ReconnectFailedTV" : "TV niet beschikbaar. Afspelen kan niet worden hervat.",
	"ReconnectFailedUSB" : "USB-apparaat is gewijzigd. Opnieuw afspelen mislukt.",
	"ReconnectPandora" : "Bluetooth audio voor Pandora opn. Verb.",
	"ReconnectStitcher" : "Bluetooth audio voor Stitcher opn. Verb.",
	"ReconnectTV" : "TV wordt gecontroleerd om afspelen te hervatten",
	"ReconnectUSB" : "USB app. opn. Verb. om afsp. te herv.",
	"RetryLabel" : "Opnieuw proberen",
	"SchedMaintenanceApp" : "Onderhoud",
	"ScreenReplication" : "Schermreplicatie",
	"SdarsRadio" : "XM",
	"Settings" : "Instellingen",
	"SettingsCommunication" : "Instellingen",
	"Siri" : "Siri",
	"SiriDisabled" : "Siri werkt niet op Apple-apparaat.",
	"Sms" : "SMS",
	"StitcherItem" : "Stitcher",
	"TVItem" : "TV",
	"TempWarning" : "Temperatuurwaarschuwing",
	"TempWarningText" : "Display is te heet. Schermprestatie kan afnemen totdat de display is afgekoeld.",
	"TextDownloaded" : "SMS gedownload",
	"TextSent" : "SMS verzonden",
	"TrafficAlertsItem" : "Verkeersinformatie",
	"USB" : "USB",
	"USB1AndroidAuto" : "USB 1 - Android Auto",
	"USB1CarPlay" : "USB 1 - Apple CarPlay",
	"USB2AndroidAuto" : "USB 2 - Android Auto",
	"UsbAudioA" : "USB 1",
	"UsbAudioAWithDevice" : "USB 1 - {deviceName}",
	"UsbAudioB" : "USB 2",
	"UsbAudioBWithDevice" : "USB 2 - {deviceName}",
	"UseCommander" : "Gebruik de spraakbesturing tijdens het rijden.",
	"VehicleDataTransferItem" : "Gegevensoverdracht voertuig ",
	"VehicleStatusMonitor" : "Monitor voert.status",
	"VehicleTelemetryTransfer" : "Overdracht voertuigtelemetrie",
	"VideoSignalLost" : "Videosignaal verbroken",
	"VoiceNotSupported" : "Stem niet ondersteund. ",
	"VoiceRecognition" : "Spraakherkenning",
	"VrHelp_Applications" : "Applicaties",
	"VrHelp_Communication" : "Communicatie",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_Favorites" : "Favorieten",
	"VrHelp_Navigation" : "Navigatie",
	"VrHelp_Settings" : "Instellingen",
	"WarnGuidanceApp" : "Waarschuwing",
	"WarningTitle" : "WAARSCHUWING!",
	"XMAudio" : "SiriusXM",
	"XMData" : "SXM Services",
	"agree" : "OK",
	"VRD_aharadioSelectCall" : "Bellen",
	"VRD_aharadioSelectDiscard" : "Verwijderen",
	"VRD_aharadioSelectEpisodes" : "Episodelijst",
	"VRD_aharadioSelectLBSTab" : "Vlakbij",
	"VRD_aharadioSelectMainList" : "Aha hoofdlijst",
	"VRD_aharadioSelectMap" : "Kaart",
	"VRD_aharadioSelectPresetsTab" : "Voorinstelling",
	"VRD_aharadioSelectSave" : "Opslaan",
	"VRD_aharadioSelectSettings" : "Geluidsinstellingen",
	"VRD_aharadioSelectShout" : "Schreeuwen",
	"VRD_aharadioSelectSource" : "Entertainment / Bron wijzigen",
	"VRD_aharadioSelectThumbsDown" : "Duim omlaag",
	"VRD_aharadioSelectThumbsUp" : "Duim omhoog",
	"VRD_amradioPlayStationFrequency" : "Op {frequency} AM afstemmen",
	"VRD_amradioSelectAutoMemory" : "Automatisch geheugen",
	"VRD_amradioSelectFavorites" : "Favorieten",
	"VRD_amradioSelectHD" : "HD-zenders",
	"VRD_amradioSelectHDOff" : "HD Radio Uit ",
	"VRD_amradioSelectHDOn" : "HD Radio Aan ",
	"VRD_amradioSelectScanOff" : "Scannen uit",
	"VRD_amradioSelectScanOn" : "Scannen aan",
	"VRD_amradioSelectSeekNext" : "Volgende zoeken",
	"VRD_amradioSelectSeekPrevious" : "Vorige zoeken",
	"VRD_amradioSelectSettings" : "Geluidsinstellingen",
	"VRD_amradioSelectSource" : "Naar entertainmentmenu gaan",
	"VRD_amradioSelectStationFrequency" : "{AMFrequency}",
	"VRD_amradioSelectTrafficAlert" : "Verkeerswaarschuwing",
	"VRD_amradioSelectTrafficAlertOff" : "Verkeerswaarschuwing uit",
	"VRD_amradioSelectTrafficAlertOn" : "Verkeerswaarschuwing aan",
	"VRD_amradioSelectTune" : "Afstemmen",
	"VRD_amradioSelectUpdateAutoMemory" : "Automatisch geheugen-zoekopdracht",
	"VRD_amradioSelectiTunesTagging" : "iTunes tagging",
	"VRD_amradioTuneDown" : "Deoptimalisatie",
	"VRD_amradioTuneUp" : "Optimalisatie",
	"VRD_amradioUpdateAutoMemory" : "Zenderlijst bijwerken",
	"VRD_auxinSelectSettings" : "Geluidsinstellingen",
	"VRD_auxinSelectSource" : "Entertainment / Bron wijzigen",
	"VRD_btaudioScanPlay" : "Scannend afspelen",
	"VRD_btaudioSelectConnect" : "Verbinden",
	"VRD_btaudioSelectRootMenu" : "Rootmenu",
	"VRD_btaudioSelectSettings" : "Geluidsinstellingen",
	"VRD_btaudioSelectSource" : "Naar entertainmentmenu gaan",
	"VRD_btaudioToggleRepeat" : "Herhalen",
	"VRD_btaudioToggleShuffle" : "Shuffle",
	"VRD_carplaySelectApplications" : "Applicaties",
	"VRD_cdGoSettings" : "Geluidsinstellingen",
	"VRD_cdHandleStartScan" : "Scan starten",
	"VRD_cdPlayBeginning" : "Opnieuw starten",
	"VRD_cdRepeatFolder" : "Map herhalen",
	"VRD_cdRepeatOff" : "Herhalen uit",
	"VRD_cdRepeatOn" : "Herhalen aan",
	"VRD_cdRepeatTrack" : "Track herhalen",
	"VRD_cdSelectCurrentFolder" : "Huidige map",
	"VRD_cdSelectRepeat" : "Herhalen",
	"VRD_cdSelectRootFolder" : "Rootmenu",
	"VRD_cdSelectShuffle" : "Shuffle",
	"VRD_cdSelectSource" : "Naar entertainmentmenu gaan",
	"VRD_cdSelectTrackList" : "Tracklijst",
	"VRD_cdSelectTrackNumber" : "Track {Number} afspelen",
	"VRD_cdShuffleDisk" : "Disc shufflen",
	"VRD_cdShuffleFolder" : "Map shufflen",
	"VRD_cdShuffleOff" : "Shuffle uit",
	"VRD_cdShuffleOn" : "Shuffle aan",
	"VRD_commonAddToFavorites" : "Toevoegen aan \"Favorieten\"",
	"VRD_commonCancel" : "Annuleren",
	"VRD_commonFastForward" : "Snel doorspoelen",
	"VRD_commonGoBack" : "Teruggaan",
	"VRD_commonIntentParent" : "Ouder",
	"VRD_commonIntentParentUSBAudio" : "Ouder",
	"VRD_commonIntentUSBAudio" : "Startpagina",
	"VRD_commonIntentUSBAudioBG" : "Startpagina",
	"VRD_commonMenuUp" : "Menu omhoog",
	"VRD_commonNext" : "Volgende",
	"VRD_commonNo" : "Nee",
	"VRD_commonPageDown" : "Pagina omlaag / naar beneden scrollen",
	"VRD_commonPageUp" : "Pagina omhoog / Naar boven scrollen",
	"VRD_commonPause" : "Pauze",
	"VRD_commonPrevious" : "Vorige",
	"VRD_commonResume" : "Afspelen / Hervatten",
	"VRD_commonRewind" : "Terugspoelen",
	"VRD_commonSelectLineNumber" : "Regel {lineNumber}",
	"VRD_commonYes" : "Ja / Oké",
	"VRD_contactsChooseContactName" : "{ContactName}",
	"VRD_contactsDisambiguateContactName" : "{ContactName} tonen",
	"VRD_contactsImportAll" : "Alle contactpersonen importeren",
	"VRD_contactsImportCancel" : "Import annuleren",
	"VRD_contactsImportContacts" : "Contactpersonen bewerken",
	"VRD_contactsImportSingle" : "Geselecteerde contactpers. import.",
	"VRD_contactsRemoveContact" : "Contactpersoon verwijderen",
	"VRD_contactsSelectCall" : "Bellen",
	"VRD_contactsSelectContactName" : "{ContactName}",
	"VRD_contactsSelectDownload" : "Downloaden",
	"VRD_contactsSelectFavorites" : "Favorieten",
	"VRD_contactsSelectNone" : "Geen van deze",
	"VRD_contactsSelectReadContactName" : "Naam contactpersoon lezen",
	"VRD_contactsSelectRemove" : "Verwijderen",
	"VRD_contactsSelectRetry" : "Opnieuw proberen",
	"VRD_contactsSendPhoneType" : "{phoneType}",
	"VRD_contactsShowAddress" : "Adres",
	"VRD_dabDisplayDABSettings" : "DAB-instellingen",
	"VRD_dabDisplayEnsembleList" : "Ensemble selecteren",
	"VRD_dabDisplayStationList" : "Zenderlijst",
	"VRD_dabSelectFavorites" : "Favorieten",
	"VRD_dabSelectScan" : "Scannen",
	"VRD_dabSelectSeekNext" : "Volgende",
	"VRD_dabSelectSeekPrevious" : "Vorige",
	"VRD_dabSelectSettings" : "Geluidsinstellingen",
	"VRD_dabSelectSource" : "Entertainment",
	"VRD_dabTAToggleOFF" : "Verkeer uit",
	"VRD_dabTAToggleON" : "Verkeer aan",
	"VRD_dabTAToggleVois" : "Verkeerswaarschuwing (TA)",
	"VRD_dabUpdateStationList" : "Lijst bijwerken",
	"VRD_dvdClearPin" : "Cijfers verwijderen",
	"VRD_dvdSayGRating" : "G",
	"VRD_dvdSayPG12" : "PG-12",
	"VRD_dvdSayR15" : "R-15 plus",
	"VRD_dvdSayR18" : "Geen",
	"VRD_dvdSelectAspectRatio" : "Beeldverhouding",
	"VRD_dvdSelectAudioSettings" : "Video-instellingen",
	"VRD_dvdSelectCameraAngle" : "Camerahoek",
	"VRD_dvdSelectEditPin" : "Pincode bewerken",
	"VRD_dvdSelectParentLock" : "Kinderslot",
	"VRD_dvdSelectParentLockOff" : "Kinderslot uit",
	"VRD_dvdSelectParentLockOn" : "Kinderslot aan",
	"VRD_dvdSelectParentLockRating" : "Niveau kinderslot",
	"VRD_dvdSelectResetPin" : "Reset PIN",
	"VRD_dvdSelectRootMenu" : "Rootmenu",
	"VRD_dvdSelectSettings" : "Geluidsinstellingen",
	"VRD_dvdSelectSource" : "Entertainment",
	"VRD_dvdSelectSubtitleOff" : "Ondertiteling uit",
	"VRD_dvdSelectSubtitleOn" : "Ondertiteling aan",
	"VRD_dvdSlowForward" : "Snel doorspoelen",
	"VRD_dvdSlowRewind" : "Terugspoelen",
	"VRD_dvdVUISendPin" : "{FourDigitPin}",
	"VRD_emailSelectAllAccounts" : "Alle accounts",
	"VRD_emailSelectCall" : "Bellen",
	"VRD_emailSelectContactName" : "{ContactName}",
	"VRD_emailSelectContinueEmail" : "Meer e-mail",
	"VRD_emailSelectDelete" : "Verwijderen",
	"VRD_emailSelectDiscard" : "Verwijderen",
	"VRD_emailSelectImportEmail" : "Inbox bijwerken",
	"VRD_emailSelectInbox" : "E-mail inbox",
	"VRD_emailSelectInboxSelector" : "Inbox",
	"VRD_emailSelectMessage" : "Bericht toevoegen",
	"VRD_emailSelectNone" : "Geen van deze",
	"VRD_emailSelectReply" : "Beantwoorden",
	"VRD_emailSelectReplyAll" : "Alles beantwoorden",
	"VRD_emailSelectRetry" : "Opnieuw proberen",
	"VRD_emailSelectReturn" : "Terug",
	"VRD_emailSelectSend" : "Verzenden",
	"VRD_emailSelectSenderName" : "{senderName}",
	"VRD_emnaviAcceptAvoidance" : "Bevestigen",
	"VRD_emnaviAddCurrentPosToFavourites" : "Huidige positie aan favorieten toevoegen",
	"VRD_emnaviAddWaypointCityCenter" : "Waypoint in het stadscentrum toevoegen",
	"VRD_emnaviAddWaypointDistrictCenter" : "Waypoint in buurtcentrum toevoegen",
	"VRD_emnaviAddWaypointFavorite" : "Waypoint-favoriet toevoegen",
	"VRD_emnaviAddWaypointPOI" : "Waypoint {poiHypList} toevoegen",
	"VRD_emnaviAvoidRouteAhead" : "Deel van de route vermijden",
	"VRD_emnaviCancelRoute" : "Route annuleren",
	"VRD_emnaviDecreaseAvoidanceLength" : "Minder",
	"VRD_emnaviGoToCockpit" : "Starten",
	"VRD_emnaviIncreaseAvoidanceLength" : "Meer",
	"VRD_emnaviJPJ_VDEHypothesisList" : "Een stadsnaam",
	"VRD_emnaviNavigateHere" : "Hier naartoe navigeren",
	"VRD_emnaviNavigateHome" : "Naar huis navigeren",
	"VRD_emnaviNavigateToARecentDestination" : "Naar een recente bestemming navigeren",
	"VRD_emnaviNavigateToAddress" : "Naar een adres navigeren",
	"VRD_emnaviNavigateToCityCenter" : "Naar het stadscentrum navigeren",
	"VRD_emnaviNavigateToDistrictCenter" : "Naar een buurtcentrum navigeren",
	"VRD_emnaviNavigateToFavorite" : "Naar favorieten navigeren",
	"VRD_emnaviNavigateToPOI" : "Naar {poiHypList} navigeren",
	"VRD_emnaviNewDestination" : "Nieuwe bestemming",
	"VRD_emnaviRepeatInstruction" : "Instructie herhalen",
	"VRD_emnaviRouteSummary" : "Samenvatting van de route",
	"VRD_emnaviSelectCancelRoute" : "Route wissen",
	"VRD_emnaviSelectNavigateToAddress" : "Naar een adres navigeren",
	"VRD_emnaviSimpleHypothesisList" : "Een staatnaam",
	"VRD_emnaviStepByStep" : "Stapsgewijze invoer",
	"VRD_emnaviTravelViaARecentDestination" : "Waypoint van een recente bestemming toevoegen",
	"VRD_emnaviTravelViaAddress" : "Via een adres reizen",
	"VRD_emnaviTravelViaHome" : "Via huis reizen",
	"VRD_emnaviTryAgain" : "Opnieuw proberen",
	"VRD_emnaviUniSimpleHypothesisList" : "Een adres",
	"VRD_emnaviUniVDEHypothesisList" : "Een adres",
	"VRD_emnaviVDEHypothesisList" : "Een adres",
	"VRD_emnaviWhereAmI" : "Waar ben ik",
	"VRD_emnaviZoomIn" : "Inzoomen",
	"VRD_emnaviZoomOut" : "Uitzoomen",
	"VRD_fmradioPlayStationFrequency" : "Afstemmen op {frequency} FM",
	"VRD_fmradioSelectAutoMemory" : "Automatisch geheugen",
	"VRD_fmradioSelectChangeGenre" : "Genre wijzigen",
	"VRD_fmradioSelectFMSettings" : "FM-instellingen",
	"VRD_fmradioSelectFavorites" : "Favorieten",
	"VRD_fmradioSelectGenreSeek" : "Genre opzoeken",
	"VRD_fmradioSelectHDChannel" : "{HD Channel}",
	"VRD_fmradioSelectHDChannels" : "HD-zenders",
	"VRD_fmradioSelectHDRadio" : "HD radio",
	"VRD_fmradioSelectHDRadioOff" : "HD Radio uit",
	"VRD_fmradioSelectHDRadioOn" : "HD Radio aan",
	"VRD_fmradioSelectScanOff" : "Scannen uit",
	"VRD_fmradioSelectScanOn" : "Scannen aan",
	"VRD_fmradioSelectSeekNext" : "Volgende zoeken",
	"VRD_fmradioSelectSeekPrevious" : "Vorige zoeken",
	"VRD_fmradioSelectSettings" : "Geluidsinstellingen",
	"VRD_fmradioSelectSource" : "Entertainment / Bron wijzigen",
	"VRD_fmradioSelectStationAll" : "Alle zenders",
	"VRD_fmradioSelectStationFrequency" : "{frequency}",
	"VRD_fmradioSelectStationGenre" : "{genreName}",
	"VRD_fmradioSelectStationList" : "Zenderlijst",
	"VRD_fmradioSelectStationName" : "{stationName}",
	"VRD_fmradioSelectTrafficAlert" : "Verkeerswaarschuwing (TA)",
	"VRD_fmradioSelectTrafficAlertOff" : "Verkeer uit",
	"VRD_fmradioSelectTrafficAlertOn" : "Verkeer aan",
	"VRD_fmradioSelectTune" : "Afstemmen",
	"VRD_fmradioSelectUpdateAutoMemory" : "Automatisch geheugen bijwerken",
	"VRD_fmradioSelectiTunesTagging" : "iTunes tagging",
	"VRD_fmradioTuneDown" : "Deoptimalisatie",
	"VRD_fmradioTuneUp" : "Optimalisatie",
	"VRD_fmradioTurnOffAF" : "Alternatieve frequentie uit",
	"VRD_fmradioTurnOffREG" : "Regiovergrendeling uit",
	"VRD_fmradioTurnOnAF" : "Alternatieve frequentie aan",
	"VRD_fmradioTurnOnREG" : "Regiovergrendeling aan",
	"VRD_fmradioUpdateAutoMemory" : "Zenderlijst bijwerken",
	"VRD_pandoraAddStation" : "Zender toevoegen",
	"VRD_pandoraAddStationFromArtist" : "Zender creëren van artiest",
	"VRD_pandoraAddStationFromSong" : "Zender creëren van nummer",
	"VRD_pandoraAddToFavorites" : "Aan favorieten toevoegen",
	"VRD_pandoraBookmarkArtist" : "Bladwijzer toevoegen voor artiest",
	"VRD_pandoraBookmarkSong" : "Bladwijzer toevoegen voor nummer",
	"VRD_pandoraCreateStation" : "Zender creëren",
	"VRD_pandoraSelectAddCurrentStation" : "Toevoegen",
	"VRD_pandoraSelectDelete" : "Verwijderen",
	"VRD_pandoraSelectEditDelete" : "Verwijderen",
	"VRD_pandoraSelectEditMove" : "Verplaatsen",
	"VRD_pandoraSelectEditReplace" : "Vervangen",
	"VRD_pandoraSelectFavorites" : "Favorieten",
	"VRD_pandoraSelectMove" : "Verplaatsen",
	"VRD_pandoraSelectQuickMix" : "Shuffle",
	"VRD_pandoraSelectSettings" : "Geluidsinstellingen",
	"VRD_pandoraSelectSortBy" : "Sorteren",
	"VRD_pandoraSelectSource" : "Entertainment",
	"VRD_pandoraSelectStationList" : "Zenderlijst",
	"VRD_pandoraShowBookmarkOptions" : "Bladwijzer",
	"VRD_pandoraShowByAZ" : "Alfabetisch sorteren",
	"VRD_pandoraShowByDate" : "Op datum sorteren",
	"VRD_pandoraSkip" : "Overslaan",
	"VRD_pandoraThumbsDown" : "Duim omlaag",
	"VRD_pandoraThumbsUp" : "Duim omhoog",
	"VRD_phoneCall" : "Bellen",
	"VRD_phoneCallBack" : "Terugbellen",
	"VRD_phoneCallByName" : "Op naam bellen",
	"VRD_phoneCallByNumber" : "Op nummer bellen",
	"VRD_phoneCallContactType" : "{contactName} {contactType} bellen",
	"VRD_phoneCallLast" : "Laatste nummer bellen",
	"VRD_phoneChooseContactType" : "{contactName} {contactType}",
	"VRD_phoneDialAnyNumber" : "{number} bellen",
	"VRD_phoneDialpadClearAllDigits" : "Alle cijfers verwijderen",
	"VRD_phoneDialpadDeleteDigit" : "Verwijderen",
	"VRD_phoneDialpadPhoneNumber" : "{phoneNumber}",
	"VRD_phoneReDial" : "Opnieuw kiezen",
	"VRD_phoneSelectByName" : "Naam",
	"VRD_phoneSelectByNumber" : "Nummer",
	"VRD_phoneSelectContactType" : "{contactType}",
	"VRD_phoneSelectDialPad" : "Nummerscherm",
	"VRD_phoneSelectFavorites" : "Favorieten",
	"VRD_phoneSelectRecentCalls" : "Recente gesprekken",
	"VRD_phoneSelectRecentCallsAll" : "Alle gesprekken",
	"VRD_phoneSelectRecentCallsMissed" : "Gemiste oproepen",
	"VRD_satradioBackSpaceDelete" : "Cijfers verwijderen",
	"VRD_satradioChangeLockCode" : "Pincode wijzigen",
	"VRD_satradioEnterPIN" : "{4digitPin}",
	"VRD_satradioInitializeLockCode" : "Pincode initialiseren",
	"VRD_satradioPlayChannelName" : "{channelName} afspelen",
	"VRD_satradioPlayStationNumber" : "Op {channelNumber} afstemmen",
	"VRD_satradioResetLockCode" : "Reset PIN",
	"VRD_satradioSeekNext" : "Volgende zoeken",
	"VRD_satradioSeekPrevious" : "Vorige zoeken",
	"VRD_satradioSelectChangeCategory" : "Categorie",
	"VRD_satradioSelectFavorites" : "Favorieten",
	"VRD_satradioSelectParentalLock" : "Kinderslot",
	"VRD_satradioSelectScanOff" : "Scannen uit",
	"VRD_satradioSelectScanOn" : "Scannen aan",
	"VRD_satradioSelectSettings" : "Geluidsinstellingen",
	"VRD_satradioSelectSource" : "Entertainment",
	"VRD_satradioSelectStation" : "Zender {Station number}",
	"VRD_satradioSelectStationAll" : "Alle kanalen",
	"VRD_satradioSelectStationCategory" : "{categoryName}",
	"VRD_satradioSelectStationList" : "Lijst met kanalen",
	"VRD_satradioTurnChannelLockOFF" : "Huidig kanaal ontgrendelen",
	"VRD_satradioTurnChannelLockON" : "Huidig kanaal vergrendelen",
	"VRD_satradioTurnParentalLockOFF" : "Sessievergrendeling uit",
	"VRD_satradioTurnParentalLockON" : "Sessievergrendeling aan",
	"VRD_smsCallPhoneNumber" : "Bellen",
	"VRD_smsDelete" : "Verwijderen",
	"VRD_smsImportMessages" : "Tekstinbox bijwerken",
	"VRD_smsReply" : "Beantwoorden",
	"VRD_smsSayAnyConversation" : "{senderName}",
	"VRD_smsSelectBody" : "Bericht toevoegen",
	"VRD_smsSelectContactName" : "{ContactName}",
	"VRD_smsSelectContinueTextMessage" : "Bericht vervolgen",
	"VRD_smsSelectDiscard" : "Verwijderen",
	"VRD_smsSelectInbox" : "SMS-inboxlijst",
	"VRD_smsSelectNone" : "Geen van deze",
	"VRD_smsSelectRetry" : "Opnieuw proberen",
	"VRD_smsSelectReturn" : "Terug",
	"VRD_smsSelectSend" : "Verzenden",
	"VRD_stitcherAddToFavorites" : "Aan favorieten toevoegen",
	"VRD_stitcherRemoveFromFavorites" : "Verwijderen uit “Favorieten”",
	"VRD_stitcherSaveFavorites" : "Wijzigingen opslaan",
	"VRD_stitcherSelectSettings" : "Geluidsinstellingen",
	"VRD_stitcherSelectSource" : "Entertainment",
	"VRD_stitcherSelectStationList" : "Zenderlijst",
	"VRD_stitcherThumbsDown" : "Duim omlaag",
	"VRD_stitcherThumbsUp" : "Duim omhoog",
	"VRD_systemSelectAhaRadio" : "Aha Radio",
	"VRD_systemSelectAndroidAuto" : "Android Auto",
	"VRD_systemSelectApplications" : "Applicaties",
	"VRD_systemSelectAuxIn" : "Line in / AUX",
	"VRD_systemSelectBTAudio" : "Bluetooth",
	"VRD_systemSelectCD" : "CD",
	"VRD_systemSelectCallHistory" : "Belgeschiedenis",
	"VRD_systemSelectCarPlay" : "Car Play",
	"VRD_systemSelectCommunication" : "Communicatie",
	"VRD_systemSelectConnect" : "Verbinden",
	"VRD_systemSelectContacts" : "Contactpersonen",
	"VRD_systemSelectDAB" : "DAB",
	"VRD_systemSelectDVD" : "DVD",
	"VRD_systemSelectDisplayClock" : "Klokweergave",
	"VRD_systemSelectDisplayOff" : "Scherm uit",
	"VRD_systemSelectEmail" : "E-mail",
	"VRD_systemSelectEntertainment" : "Entertainment",
	"VRD_systemSelectEntertainmentMenu" : "Entertainmentmenu",
	"VRD_systemSelectFavorites" : "Favorieten",
	"VRD_systemSelectNavigation" : "Navigatie",
	"VRD_systemSelectNotifications" : "Berichten",
	"VRD_systemSelectNotifyOff" : "Melding uit",
	"VRD_systemSelectPandora" : "Pandora",
	"VRD_systemSelectPhone" : "Telefoon",
	"VRD_systemSelectRadioAM" : "AM Radio",
	"VRD_systemSelectRadioFM" : "FM Radio",
	"VRD_systemSelectRetry" : "Opnieuw proberen",
	"VRD_systemSelectSatRadio" : "Satellietradio",
	"VRD_systemSelectSettings" : "Instellingen",
	"VRD_systemSelectSiri" : "Siri",
	"VRD_systemSelectSms" : "Tekst / SMS",
	"VRD_systemSelectStitcher" : "Stitcher",
	"VRD_systemSelectTV" : "TV",
	"VRD_systemSelectTrafficAlert" : "Verkeerswaarschuwing (TA)",
	"VRD_systemSelectTutorial" : "Handleiding",
	"VRD_systemSelectUSB" : "USB",
	"VRD_systemSelectUSBA" : "USB 1",
	"VRD_systemSelectUSBB" : "USB 2",
	"VRD_systemSelectXmAudio" : "SXM Radio",
	"VRD_tvSelectView" : "Weergave",
	"VRD_usbaudioBrowse" : "Bladeren",
	"VRD_usbaudioBrowseAlbum" : "Door {albumName} bladeren",
	"VRD_usbaudioBrowseAlbums" : "Door album bladeren",
	"VRD_usbaudioBrowseAll" : "Door alle nummers of albums of artiesten bladeren",
	"VRD_usbaudioBrowseAnyAlbum" : "Door [Album] {albumName} bladeren",
	"VRD_usbaudioBrowseAnyArtist" : "Door [Artist] {artistName} bladeren",
	"VRD_usbaudioBrowseAnyFolder" : "Door map {folderName} bladeren",
	"VRD_usbaudioBrowseArtist" : "Door {artistName} bladeren",
	"VRD_usbaudioBrowseArtists" : "Door artiest bladeren",
	"VRD_usbaudioBrowseAudiobooks" : "Door audioboeken bladeren",
	"VRD_usbaudioBrowseFolder" : "Door {folderName} bladeren",
	"VRD_usbaudioBrowseFolders" : "Door map bladeren",
	"VRD_usbaudioBrowseGenre" : "Door [Genre] {genreName} bladeren",
	"VRD_usbaudioBrowseGenres" : "Door genre bladeren",
	"VRD_usbaudioBrowseLineNumber" : "Door regel {lineNumber} bladeren",
	"VRD_usbaudioBrowsePlaylist" : "Door afspeellijst {playlistName} bladeren",
	"VRD_usbaudioBrowsePlaylists" : "Door afspeellijst bladeren",
	"VRD_usbaudioBrowsePodcast" : "Door Podcast {podcastName} bladeren",
	"VRD_usbaudioBrowsePodcasts" : "Door Podcasts bladeren",
	"VRD_usbaudioBrowseSongs" : "Door nummers bladeren",
	"VRD_usbaudioChooseAlbumArtist" : "{artistName}",
	"VRD_usbaudioGenerateMoreLikeThis" : "Meer hiervan",
	"VRD_usbaudioPlayAlbums" : "Album afspelen",
	"VRD_usbaudioPlayAll" : "Alles afspelen ",
	"VRD_usbaudioPlayAnyAlbum" : "[Album] {albumName} afspelen",
	"VRD_usbaudioPlayAnyArtist" : "[Artist] {artistName} afspelen",
	"VRD_usbaudioPlayAnyFolder" : "Map {folderName} afspelen",
	"VRD_usbaudioPlayArtistAlbum" : "{artistName} {albumName} afspelen",
	"VRD_usbaudioPlayArtists" : "Artiest afspelen",
	"VRD_usbaudioPlayAudiobook" : "Audioboek {AudiobookName} afspelen",
	"VRD_usbaudioPlayAudiobooks" : "Audioboeken afspelen",
	"VRD_usbaudioPlayChapter" : "{chapterName}",
	"VRD_usbaudioPlayChapterIndex" : "Hoofdstuk {index} {chapter} afspelen",
	"VRD_usbaudioPlayEpisode" : "{episodeName}",
	"VRD_usbaudioPlayFolder" : "{folderName} afspelen",
	"VRD_usbaudioPlayFolders" : "Map afspelen",
	"VRD_usbaudioPlayGenre" : "[Genre] {genreName} afspelen",
	"VRD_usbaudioPlayGenres" : "Genre afspelen",
	"VRD_usbaudioPlayLineNumber" : "[Line] {lineNumber} afspelen",
	"VRD_usbaudioPlayPlaylist" : "Afspeellijst {playlistName} afspelen",
	"VRD_usbaudioPlayPlaylists" : "Afspeellijst afspelen",
	"VRD_usbaudioPlayPodcast" : "Podcast {PodcastName} afspelen",
	"VRD_usbaudioPlayPodcasts" : "Podcasts afspelen",
	"VRD_usbaudioPlaySongs" : "Nummer afspelen",
	"VRD_usbaudioRepeat" : "Herhalen",
	"VRD_usbaudioRepeatAll" : "Alles herhalen",
	"VRD_usbaudioRepeatOff" : "Herhalen uit",
	"VRD_usbaudioRepeatSong" : "Nummer herhalen",
	"VRD_usbaudioRewind" : "Terugspoelen",
	"VRD_usbaudioSelectAlbum" : "Album {albumName}",
	"VRD_usbaudioSelectAlbums" : "Album",
	"VRD_usbaudioSelectAll" : "Alle episodes of hoofdstukken of nummers of albums of artiesten",
	"VRD_usbaudioSelectArtist" : "Artiest {artistName}",
	"VRD_usbaudioSelectArtists" : "Artiest",
	"VRD_usbaudioSelectAudiobook" : "{audiobookName}",
	"VRD_usbaudioSelectAudiobooks" : "Audioboeken",
	"VRD_usbaudioSelectFolder" : "Map {folderName}",
	"VRD_usbaudioSelectFolders" : "Mappen",
	"VRD_usbaudioSelectGenre" : "Genre {genreName}",
	"VRD_usbaudioSelectGenres" : "Genre",
	"VRD_usbaudioSelectPlaylist" : "Afspeellijst {playlistName}",
	"VRD_usbaudioSelectPlaylists" : "Afspeellijst",
	"VRD_usbaudioSelectPodcast" : "{podcastName}",
	"VRD_usbaudioSelectPodcasts" : "Podcast",
	"VRD_usbaudioSelectRootFolder" : "Rootmenu",
	"VRD_usbaudioSelectSettings" : "Geluidsinstellingen",
	"VRD_usbaudioSelectSongs" : "Nummer",
	"VRD_usbaudioSelectSourceMenu" : "Entertainment",
	"VRD_usbaudioShuffle" : "Shuffle",
	"VRD_usbaudioShuffleOff" : "Shuffle uit",
	"VRD_usbaudioShuffleOn" : "Shuffle aan",
	"VRD_usbaudioSongList" : "Nummerlijst",
	"VRD_xmaudioBackSpaceDelete" : "Cijfers verwijderen",
	"VRD_xmaudioChangeLockCode" : "Pincode bewerken",
	"VRD_xmaudioConfirmDelete" : "Verwijderen",
	"VRD_xmaudioEnterPIN" : "{fourDigitPIN}",
	"VRD_xmaudioPlayChannelName" : "XM Kanaal {channelName} afspelen",
	"VRD_xmaudioPlayStationNumber" : "Op {channelNumber} afstemmen",
	"VRD_xmaudioResetLockCode" : "Reset PIN",
	"VRD_xmaudioSelectCallXM" : "XM bellen",
	"VRD_xmaudioSelectChangeCategory" : "Categorie wijzigen",
	"VRD_xmaudioSelectContinueListening" : "Blijven luisteren",
	"VRD_xmaudioSelectDismiss" : "Verwijderen",
	"VRD_xmaudioSelectEveryOccurance" : "Iedere gebeurtenis",
	"VRD_xmaudioSelectEveryOtherReport" : "Elk ander rapport",
	"VRD_xmaudioSelectEveryReport" : "Elk rapport",
	"VRD_xmaudioSelectExitTuneMix" : "TuneMix verlaten",
	"VRD_xmaudioSelectFavorites" : "Favorieten",
	"VRD_xmaudioSelectListenNow" : "Nu luisteren",
	"VRD_xmaudioSelectMove" : "Verplaatsen",
	"VRD_xmaudioSelectNearestCity" : "Dichtstbijzijnde stad",
	"VRD_xmaudioSelectOnlyFirstAfterVehicleStart" : "Voertuig starten",
	"VRD_xmaudioSelectOnlyFirstOccuranceInGame" : "Eerste gebeurtenis",
	"VRD_xmaudioSelectReplayAlert" : "Waarschuwing herhalen",
	"VRD_xmaudioSelectReturnToPrevious" : "Naar vorige terugkeren",
	"VRD_xmaudioSelectSFSportBaseball" : "Baseball",
	"VRD_xmaudioSelectSFSportNCAA" : "Schoolvoetbal",
	"VRD_xmaudioSelectSFSportNFL" : "Profvoetbal",
	"VRD_xmaudioSelectSFSportNHL" : "Hockey",
	"VRD_xmaudioSelectScanOff" : "Scannen uit",
	"VRD_xmaudioSelectScanOn" : "Scannen aan",
	"VRD_xmaudioSelectSettings" : "Instellingen",
	"VRD_xmaudioSelectSoundSettings" : "Geluidsinstellingen",
	"VRD_xmaudioSelectSource" : "Entertainment",
	"VRD_xmaudioSelectStation" : "Zender {channelNumber}",
	"VRD_xmaudioSelectStationAll" : "Alle kanalen",
	"VRD_xmaudioSelectStationCategory" : "{categoryName}",
	"VRD_xmaudioSelectStationFeaturedFavorites" : "Aanbevolen favorieten",
	"VRD_xmaudioSelectStationList" : "Kanalen",
	"VRD_xmaudioSelectTuneMix" : "TuneMix",
	"VRD_xmaudioSelectTuneMixChannel" : "TuneMix kanaalopties",
	"VRD_xmaudioSelectTuneMixChannelsOptions" : "Kanaalopties",
	"VRD_xmaudioSelectTuneMixCreation" : "Een nieuw TuneMix-kanaal creëren",
	"VRD_xmaudioSelectTuneMixEdit" : "TuneMix-kanaal bewerken",
	"VRD_xmaudioSelectTuneMixEditOps" : "TuneMix bewerkopties",
	"VRD_xmaudioSelectTuneMixRemove" : "TuneMix-kanaal verwijderen",
	"VRD_xmaudioSelectTuneMixRename" : "TuneMix hernoemen",
	"VRD_xmaudioSelectTurnAlertsOff" : "Waarschuwingen uitschakelen",
	"VRD_xmaudioSelectiTunesTagging" : "iTunes tagging",
	"VRD_xmaudioSetChannelLock" : "Kanaal vergrendelen",
	"VRD_xmaudioSetParentalLock" : "Sessie-lock",
	"VRD_xmdataSelectFuelPrices" : "Brandstofprijzen",
	"VRD_xmdataSelectMovies" : "Films",
	"VRD_xmdataSelectParking" : "Parkeerplaats",
	"VRD_xmdataSelectSports" : "Sporten",
	"VRD_xmdataSelectStock" : "Aandelen",
	"VRD_xmdataSelectTrafficPlus" : "Verkeer plus",
	"VRD_xmdataSelectWeatherForecast" : "Weersvoorspelling",
	"VRD_xmdataSelectWeatherRadar" : "Weerradar",
	"VRD_xmdataSelectWeatherSecurityAlerts" : "Weerswaarschuwingen",
};

framework.registerAppDictLoaded("system", "nl_NL");