var __VrHelpPositionTable__systemAppDict_fi_FI = {
	"HomeScreen_Help" : {
		"Right" : ["VrHelp_Favorites"],
		"Left" : ["VrHelp_Entertainment","VrHelp_Communication","VrHelp_Navigation","VrHelp_Settings","VrHelp_Applications"]
	}
};

var Localization_systemAppDict_fi_FI = {
	//"stringId" : "localString"
	"ActiveCallItem" : "Käynnissä oleva puhelu",
	"AhaMaintError" : "aha ylläpitovirhe",
	"AhaRadio" : "aha",
	"AmRadio" : "AM",
	"AndroidAuto" : "Android Auto",
	"Applications" : "Sovellukset",
	"AudioSourceNotAvailableBTAudio" : "BT-audioon ei ole käytettävissä",
	"AudioSourceNotAvailableCD" : "CD otettiin pois asemasta",
	"AudioSourceNotAvailableDVD" : "DVD otettiin pois asemasta",
	"AudioSourceNotAvailableTV" : "TV ei saatavilla",
	"AudioSourceNotAvailableUSB" : "USB-laite on vaihtunut",
	"AuxIn" : "AUX",
	"BT" : "BT",
	"Bluetooth" : "Bluetooth",
	"BluetoothWithDevice" : "Bluetooth - {deviceName}",
	"CallHistory" : "Puheluhistoria",
	"CarPlay" : "Apple CarPlay",
	"CdPlayer" : "CD",
	"ChannelOffAir" : "Kanavalla ei ole lähetystä",
	"ChannelUnauth" : "Kanavaan ei ole oikeuksia",
	"CheckAntenna" : "Tarkista antenni",
	"CheckTuner" : "Tarkista viritin",
	"Communication" : "Viestintä",
	"Connect" : "Yhdistä",
	"Contacts" : "Yhteystiedot",
	"DVDItem" : "DVD",
	"DabRadio" : "DAB",
	"DialPhone" : "Soita puhelimeen",
	"DidYouSay" : "Sanoitko...",
	"DisclaimerText" : "Häiriötekijät voivat aiheuttaa onnettomuuksia. Älä käytä laitetta ajon aikana. Keskity aina liikenteeseen ja noudata liikennesäätöjä. Katso omistajan käsikirja.",
	"DisconnectThenReconnect" : "Katkaise yhteys ja yhdistä Apple-laite uudelleen",
	"DriveRecord" : "Ajorekisteri",
	"DriverIDItem" : "Kuljettajan tunnistus",
	"EcoenergyApp" : "Kulutuksen valvonta",
	"EcoenergyAppHEV" : "Ajomonitori",
	"Email" : "Email",
	"EngineOilLevel" : "Moottoriöljyn taso",
	"Entertainment" : "Viihde",
	"ErrorWhileStartingSiri" : "Siri -sovelluksen käynnistyksessä tapahtui virhe.",
	"FailedNotificationRetrieval" : "Ilmoitusluettelon noutaminen ei onnistu",
	"FavoritesItem" : "Suosikit",
	"FmRadio" : "FM",
	"HDTrafficItem" : "HD Radio™ -liikennekartta",
	"InitiateSiri" : "Paina Puhe-nappulaa pohjassa ja aloita Siri-sovelluksen käyttö.",
	"IntelligentDriveMasterItem" : "i-DM",
	"NavigationTitle" : "Navigointi",
	"NoConnectionNotifyText" : "Haluatko liittää puhelimen nyt?",
	"NoConnectionNotifyTitle" : "Ei kytkettyä puhelinta",
	"NoDeviceText" : "Haluatko liittää laitteen nyt?",
	"NoDeviceTitle" : "Ei kytkettyä laitetta",
	"Notifications" : "Ilmoitukset",
	"NotifyIgnore" : "Ohita",
	"NotifyIncomingMsg" : "Saapuva viesti lähettäjältä:",
	"NotifyOff" : "Ilmoitus pois",
	"NotifyRead" : "Lue",
	"NotifyReadNow" : "Haluatko lukea sen nyt?",
	"Pandora" : "Pandora",
	"ReconnectAhaRadio" : "Yhdistää BT-audioon aha-radiota varten",
	"ReconnectBTAudio" : "Yhdistää BT-audioon toistoa varten",
	"ReconnectCD" : "Tarkistaa CD-levyä toistamista varten",
	"ReconnectCarPlay" : "Apple CarPlayn yhdistämistä jatketaan.",
	"ReconnectDVD" : "Tarkistaa DVD-levyä toistamista varten",
	"ReconnectEntMenuButton" : "Viihdevalikko",
	"ReconnectFailedBTAudio" : "Bluetooth-äänilaitteen yhteyden uudelleenmuodostaminen ei onnistunut",
	"ReconnectFailedCD" : "CD otettiin pois asemasta. Toistoa ei voi jatkaa.",
	"ReconnectFailedCarPlay" : "Apple CarPlayn uudelleen yhdistäminen epäonnistui",
	"ReconnectFailedDVD" : "DVD otettiin pois asemasta. Toistoa ei voi jatkaa.",
	"ReconnectFailedTV" : "TV ei saatavilla. Toiston jatkaminen ei onnistunut.",
	"ReconnectFailedUSB" : "USB-laite on vaihtunut. Toistoa ei voi jatkaa.",
	"ReconnectPandora" : "Yhdistää BT-audioon Pandoraa varten",
	"ReconnectStitcher" : "Yhdistää BT-audioon Stitcheriä varten",
	"ReconnectTV" : "TV:tä vahvistetaan toiston jatkamiseksi",
	"ReconnectUSB" : "Yhdistää USB-laitteeseen toistoa varten",
	"RetryLabel" : "Yritä uudelleen",
	"SchedMaintenanceApp" : "Huolto",
	"ScreenReplication" : "Näytönreplikaatio",
	"SdarsRadio" : "XM",
	"Settings" : "Asetukset",
	"SettingsCommunication" : "Asetukset",
	"Siri" : "Siri",
	"SiriDisabled" : "Siri ei ole käytössä Applen laitteilla.",
	"Sms" : "SMS",
	"StitcherItem" : "Stitcher",
	"TVItem" : "TV",
	"TempWarning" : "Lämpötilavaroitus",
	"TempWarningText" : "Näyttö on ylikuumentunut. Näyttö voi toimia hitaasti, kunnes se ehtii jäähtyä.",
	"TextDownloaded" : "SMS ladattu",
	"TextSent" : "SMS lähetetty",
	"TrafficAlertsItem" : "Liikennetiedot",
	"USB" : "USB",
	"USB1AndroidAuto" : "USB 1 - Android Auto",
	"USB1CarPlay" : "USB 1 - Apple CarPlay",
	"USB2AndroidAuto" : "USB 2 - Android Auto",
	"UsbAudioA" : "USB 1",
	"UsbAudioAWithDevice" : "USB 1 - {deviceName}",
	"UsbAudioB" : "USB 2",
	"UsbAudioBWithDevice" : "USB 2 - {deviceName}",
	"UseCommander" : "Käytä komentoa ajon aikana.",
	"VehicleDataTransferItem" : "Auton tiedonsiirto ",
	"VehicleStatusMonitor" : "Ajoneuvon tilanäyttö",
	"VehicleTelemetryTransfer" : "Ajoneuvon telemetrian siirto",
	"VideoSignalLost" : "Kuvasignaali katkesi",
	"VoiceNotSupported" : "Ääntä ei tueta ",
	"VoiceRecognition" : "Äänentunnistus",
	"VrHelp_Applications" : "Sovellukset",
	"VrHelp_Communication" : "Viestintä",
	"VrHelp_Entertainment" : "Viihde",
	"VrHelp_Favorites" : "Suosikit",
	"VrHelp_Navigation" : "Navigointi",
	"VrHelp_Settings" : "Asetukset",
	"WarnGuidanceApp" : "Varoitukset",
	"WarningTitle" : "VAROITUS!",
	"XMAudio" : "SXM",
	"XMData" : "SXM Services",
	"agree" : "Hyväksyn",
	"VRD_aharadioSelectCall" : "Soita",
	"VRD_aharadioSelectDiscard" : "Hylkää",
	"VRD_aharadioSelectEpisodes" : "Jaksolista",
	"VRD_aharadioSelectLBSTab" : "Lähellä",
	"VRD_aharadioSelectMainList" : "Aha Pääluettelo",
	"VRD_aharadioSelectMap" : "Kartta",
	"VRD_aharadioSelectPresetsTab" : "Radiokanava",
	"VRD_aharadioSelectSave" : "Tallenna",
	"VRD_aharadioSelectSettings" : "Ääniasetukset",
	"VRD_aharadioSelectShout" : "Shout-viesti",
	"VRD_aharadioSelectSource" : "Viihde / Vaihda lähdettä",
	"VRD_aharadioSelectThumbsDown" : "En tykkää",
	"VRD_aharadioSelectThumbsUp" : "Tykkään",
	"VRD_amradioPlayStationFrequency" : "Viritä {frequency} AM",
	"VRD_amradioSelectAutoMemory" : "Autom. muisti",
	"VRD_amradioSelectFavorites" : "Suosikit",
	"VRD_amradioSelectHD" : "HD Radio-kanavat",
	"VRD_amradioSelectHDOff" : "HD Radio pois ",
	"VRD_amradioSelectHDOn" : "HD Radio päällä ",
	"VRD_amradioSelectScanOff" : "Haku pois päältä",
	"VRD_amradioSelectScanOn" : "Haku päällä",
	"VRD_amradioSelectSeekNext" : "Hae seuraava",
	"VRD_amradioSelectSeekPrevious" : "Hae edellinen",
	"VRD_amradioSelectSettings" : "Ääniasetukset",
	"VRD_amradioSelectSource" : "Mene Viihdevalikkoon",
	"VRD_amradioSelectStationFrequency" : "{AMFrequency}",
	"VRD_amradioSelectTrafficAlert" : "Liikennehälytys",
	"VRD_amradioSelectTrafficAlertOff" : "Liikennehälytys pois päältä",
	"VRD_amradioSelectTrafficAlertOn" : "Liikennehälytys päälle",
	"VRD_amradioSelectTune" : "Viritä",
	"VRD_amradioSelectUpdateAutoMemory" : "Automaattinen haku muistista",
	"VRD_amradioSelectiTunesTagging" : "iTunes-tunnisteet",
	"VRD_amradioTuneDown" : "Viritä alaspäin",
	"VRD_amradioTuneUp" : "Viritä ylöspäin",
	"VRD_amradioUpdateAutoMemory" : "Päivitä kanavaluettelo",
	"VRD_auxinSelectSettings" : "Ääniasetukset",
	"VRD_auxinSelectSource" : "Viihde / Vaihda lähde",
	"VRD_btaudioScanPlay" : "Haku ja toisto",
	"VRD_btaudioSelectConnect" : "Yhdistä",
	"VRD_btaudioSelectRootMenu" : "Päävalikko",
	"VRD_btaudioSelectSettings" : "Ääniasetukset",
	"VRD_btaudioSelectSource" : "Mene Viihdevalikkoon",
	"VRD_btaudioToggleRepeat" : "Toisto",
	"VRD_btaudioToggleShuffle" : "Satunnaistoisto",
	"VRD_carplaySelectApplications" : "Sovellukset",
	"VRD_cdGoSettings" : "Ääniasetukset",
	"VRD_cdHandleStartScan" : "Aloita haku",
	"VRD_cdPlayBeginning" : "Aloita alusta",
	"VRD_cdRepeatFolder" : "Toista kansio uudelleen",
	"VRD_cdRepeatOff" : "Uudelleentoisto pois päältä",
	"VRD_cdRepeatOn" : "Uudelleentoisto päällä",
	"VRD_cdRepeatTrack" : "Toista kappale uudelleen",
	"VRD_cdSelectCurrentFolder" : "Nykyinen kansio",
	"VRD_cdSelectRepeat" : "Toisto",
	"VRD_cdSelectRootFolder" : "Päävalikko",
	"VRD_cdSelectShuffle" : "Satunnaistoisto",
	"VRD_cdSelectSource" : "Mene Viihdevalikkoon",
	"VRD_cdSelectTrackList" : "Kappaleluettelo",
	"VRD_cdSelectTrackNumber" : "Toista kappale{Number}",
	"VRD_cdShuffleDisk" : "Levyn satunnaistoisto",
	"VRD_cdShuffleFolder" : "Kansion satunnaistoisto",
	"VRD_cdShuffleOff" : "Satunnaistoisto pois päältä",
	"VRD_cdShuffleOn" : "Satunnaistoisto päällä",
	"VRD_commonAddToFavorites" : "Lisää suosikkeihin",
	"VRD_commonCancel" : "Peruuta",
	"VRD_commonFastForward" : "Siirry eteenpäin",
	"VRD_commonGoBack" : "Palaa takaisin",
	"VRD_commonIntentParent" : "Vanhempi",
	"VRD_commonIntentParentUSBAudio" : "Vanhempi",
	"VRD_commonIntentUSBAudio" : "Koti",
	"VRD_commonIntentUSBAudioBG" : "Koti",
	"VRD_commonMenuUp" : "Valikko ylös",
	"VRD_commonNext" : "Seuraava",
	"VRD_commonNo" : "Ei",
	"VRD_commonPageDown" : "Sivu alas / Selaa alas",
	"VRD_commonPageUp" : "Sivu ylös / Selaa ylös",
	"VRD_commonPause" : "Tauko",
	"VRD_commonPrevious" : "Edellinen",
	"VRD_commonResume" : "Toista / Pysäytä",
	"VRD_commonRewind" : "Siirry taaksepäin",
	"VRD_commonSelectLineNumber" : "Linja {lineNumber}",
	"VRD_commonYes" : "Kyllä / OK",
	"VRD_contactsChooseContactName" : "{ContactName}",
	"VRD_contactsDisambiguateContactName" : "Näytä {ContactName}",
	"VRD_contactsImportAll" : "Tuo kaikki yhteystiedot",
	"VRD_contactsImportCancel" : "Per. tuonti",
	"VRD_contactsImportContacts" : "Muokkaa yhteystietoja",
	"VRD_contactsImportSingle" : "Tuo valittu yhteystieto",
	"VRD_contactsRemoveContact" : "Poista yhteystieto",
	"VRD_contactsSelectCall" : "Soita",
	"VRD_contactsSelectContactName" : "{ContactName}",
	"VRD_contactsSelectDownload" : "Lataa",
	"VRD_contactsSelectFavorites" : "Suosikit",
	"VRD_contactsSelectNone" : "Ei mikään näistä | Ei mitään näistä",
	"VRD_contactsSelectReadContactName" : "Lue yhteystiedon nimi",
	"VRD_contactsSelectRemove" : "Poista",
	"VRD_contactsSelectRetry" : "Yritä uudelleen",
	"VRD_contactsSendPhoneType" : "{phoneType}",
	"VRD_contactsShowAddress" : "Osoite",
	"VRD_dabDisplayDABSettings" : "DAB-asetukset",
	"VRD_dabDisplayEnsembleList" : "Valitse yhdistelmä",
	"VRD_dabDisplayStationList" : "Kanavaluettelo",
	"VRD_dabSelectFavorites" : "Suosikit",
	"VRD_dabSelectScan" : "Haku",
	"VRD_dabSelectSeekNext" : "Seuraava",
	"VRD_dabSelectSeekPrevious" : "Edellinen",
	"VRD_dabSelectSettings" : "Ääniasetukset",
	"VRD_dabSelectSource" : "Viihde",
	"VRD_dabTAToggleOFF" : "Liikenne pois päältä",
	"VRD_dabTAToggleON" : "Liikenne päällä",
	"VRD_dabTAToggleVois" : "Liikennetiedote (TA)",
	"VRD_dabUpdateStationList" : "Päivitä luettelo",
	"VRD_dvdClearPin" : "Poista merkit",
	"VRD_dvdSayGRating" : "G",
	"VRD_dvdSayPG12" : "P G Twelve",
	"VRD_dvdSayR15" : "R Fifteen Plus",
	"VRD_dvdSayR18" : "--",
	"VRD_dvdSelectAspectRatio" : "Kuvasuhde",
	"VRD_dvdSelectAudioSettings" : "Videoasetukset",
	"VRD_dvdSelectCameraAngle" : "Kamerakulma",
	"VRD_dvdSelectEditPin" : "Muokkaa PIN-koodia",
	"VRD_dvdSelectParentLock" : "Lapsilukko",
	"VRD_dvdSelectParentLockOff" : "Lapsilukko pois",
	"VRD_dvdSelectParentLockOn" : "Lapsilukko päälle ",
	"VRD_dvdSelectParentLockRating" : "Lapsilukkoluokitus",
	"VRD_dvdSelectResetPin" : "Nollaa PIN-koodi",
	"VRD_dvdSelectRootMenu" : "Päävalikko",
	"VRD_dvdSelectSettings" : "Ääniasetukset",
	"VRD_dvdSelectSource" : "Viihde",
	"VRD_dvdSelectSubtitleOff" : "Tekstitys pois päältä",
	"VRD_dvdSelectSubtitleOn" : "Tekstitys päällä",
	"VRD_dvdSlowForward" : "Siirry eteenpäin",
	"VRD_dvdSlowRewind" : "Siirry taaksepäin",
	"VRD_dvdVUISendPin" : "{FourDigitPin}",
	"VRD_emailSelectAllAccounts" : "Kaikki tilit",
	"VRD_emailSelectCall" : "Soita",
	"VRD_emailSelectContactName" : "{ContactName}",
	"VRD_emailSelectContinueEmail" : "Jatka sähköpostia",
	"VRD_emailSelectDelete" : "Poista",
	"VRD_emailSelectDiscard" : "Hylkää",
	"VRD_emailSelectImportEmail" : "Päivitä Saapuneet-kansio",
	"VRD_emailSelectInbox" : "Saapuneet viestit",
	"VRD_emailSelectInboxSelector" : "Saapuneet",
	"VRD_emailSelectMessage" : "Lisää viesti",
	"VRD_emailSelectNone" : "Ei mikään näistä",
	"VRD_emailSelectReply" : "Vastaa",
	"VRD_emailSelectReplyAll" : "Vastaa kaikille",
	"VRD_emailSelectRetry" : "Yritä uudelleen",
	"VRD_emailSelectReturn" : "Palaa",
	"VRD_emailSelectSend" : "Lähetä",
	"VRD_emailSelectSenderName" : "{senderName}",
	"VRD_emnaviAcceptAvoidance" : "Vahvista",
	"VRD_emnaviAddCurrentPosToFavourites" : "Lisää tämänhetkinen sijainti Suosikkeihin",
	"VRD_emnaviAddWaypointCityCenter" : "Lisää Waypoint kaupungin keskusta",
	"VRD_emnaviAddWaypointDistrictCenter" : "Lisää Waypoint alueen keskusta",
	"VRD_emnaviAddWaypointFavorite" : "Lisää Waypoint suosikki",
	"VRD_emnaviAddWaypointPOI" : "Lisää Waypoint {poiHypList}",
	"VRD_emnaviAvoidRouteAhead" : "Vältä edessä olevaa reittiä",
	"VRD_emnaviCancelRoute" : "Peruuta reitti",
	"VRD_emnaviDecreaseAvoidanceLength" : "Vähemmän",
	"VRD_emnaviGoToCockpit" : "Aloita",
	"VRD_emnaviIncreaseAvoidanceLength" : "Enemmän",
	"VRD_emnaviJPJ_VDEHypothesisList" : "Kaupungin nimi",
	"VRD_emnaviNavigateHere" : "Navigoi tänne",
	"VRD_emnaviNavigateHome" : "Navigoi Kotiin",
	"VRD_emnaviNavigateToARecentDestination" : "Navigoi viimeaikaiseen kohteeseen",
	"VRD_emnaviNavigateToAddress" : "Navigoi osoitteeseen",
	"VRD_emnaviNavigateToCityCenter" : "Navigoi kaupungin keskustaan",
	"VRD_emnaviNavigateToDistrictCenter" : "Navigoi alueen keskustaan",
	"VRD_emnaviNavigateToFavorite" : "Navigoi Suosikkiin",
	"VRD_emnaviNavigateToPOI" : "Navigoi {poiHypList}",
	"VRD_emnaviNewDestination" : "Uusi kohde",
	"VRD_emnaviRepeatInstruction" : "Toista ohje",
	"VRD_emnaviRouteSummary" : "Reittiyhteenveto",
	"VRD_emnaviSelectCancelRoute" : "Tyhjennä reitti",
	"VRD_emnaviSelectNavigateToAddress" : "Navigoi osoitteeseen",
	"VRD_emnaviSimpleHypothesisList" : "Osavaltion nimi",
	"VRD_emnaviStepByStep" : "Vaihe vaiheelta saapuminen",
	"VRD_emnaviTravelViaARecentDestination" : "Lisää Waypoint viimeaikainen kohde",
	"VRD_emnaviTravelViaAddress" : "Matkusta osoitteen kautta",
	"VRD_emnaviTravelViaHome" : "Matkusta Kodin kautta",
	"VRD_emnaviTryAgain" : "Yritä uudelleen",
	"VRD_emnaviUniSimpleHypothesisList" : "Osoite",
	"VRD_emnaviUniVDEHypothesisList" : "Osoite",
	"VRD_emnaviVDEHypothesisList" : "Osoite",
	"VRD_emnaviWhereAmI" : "Missä olen",
	"VRD_emnaviZoomIn" : "Zoomaa lähemmäs",
	"VRD_emnaviZoomOut" : "Zoomaa kauemmas",
	"VRD_fmradioPlayStationFrequency" : "Viritä {frequency} FM",
	"VRD_fmradioSelectAutoMemory" : "Autom. muisti",
	"VRD_fmradioSelectChangeGenre" : "Vaihda tyylilajia",
	"VRD_fmradioSelectFMSettings" : "FM-asetukset",
	"VRD_fmradioSelectFavorites" : "Suosikit",
	"VRD_fmradioSelectGenreSeek" : "Tyylilajihaku",
	"VRD_fmradioSelectHDChannel" : "{HD Channel}",
	"VRD_fmradioSelectHDChannels" : "HD Radio-kanavat",
	"VRD_fmradioSelectHDRadio" : "HD Radio",
	"VRD_fmradioSelectHDRadioOff" : "HD Radio Pois päältä",
	"VRD_fmradioSelectHDRadioOn" : "HD Radio päälle",
	"VRD_fmradioSelectScanOff" : "Haku pois päältä",
	"VRD_fmradioSelectScanOn" : "Haku päällä",
	"VRD_fmradioSelectSeekNext" : "Hae seuraava",
	"VRD_fmradioSelectSeekPrevious" : "Hae edellinen",
	"VRD_fmradioSelectSettings" : "Ääniasetukset",
	"VRD_fmradioSelectSource" : "Viihde / Vaihda lähde",
	"VRD_fmradioSelectStationAll" : "Kaikki kanavat",
	"VRD_fmradioSelectStationFrequency" : "{frequency}",
	"VRD_fmradioSelectStationGenre" : "{genreName}",
	"VRD_fmradioSelectStationList" : "Kanavaluettelo",
	"VRD_fmradioSelectStationName" : "{stationName}",
	"VRD_fmradioSelectTrafficAlert" : "Liikennetiedote (TA)",
	"VRD_fmradioSelectTrafficAlertOff" : "Liikenne pois päältä",
	"VRD_fmradioSelectTrafficAlertOn" : "Liikenne päällä",
	"VRD_fmradioSelectTune" : "Viritä",
	"VRD_fmradioSelectUpdateAutoMemory" : "Päivitä automaattinen muisti",
	"VRD_fmradioSelectiTunesTagging" : "iTunes-tunnisteet",
	"VRD_fmradioTuneDown" : "Viritä alaspäin",
	"VRD_fmradioTuneUp" : "Viritä ylöspäin",
	"VRD_fmradioTurnOffAF" : "Vaihtoeht. taajuus pois",
	"VRD_fmradioTurnOffREG" : "Aluelukitus pois päältä",
	"VRD_fmradioTurnOnAF" : "Vaihtoeht. taajuus päällä",
	"VRD_fmradioTurnOnREG" : "Aluelukitus päällä",
	"VRD_fmradioUpdateAutoMemory" : "Päivitä kanavaluettelo",
	"VRD_pandoraAddStation" : "Lisää asema",
	"VRD_pandoraAddStationFromArtist" : "Luo asema esittäjältä",
	"VRD_pandoraAddStationFromSong" : "Luo asema kappaleesta",
	"VRD_pandoraAddToFavorites" : "Lisää suosikkeihin",
	"VRD_pandoraBookmarkArtist" : "Lisää esittäjä kirjanmerkkeihin",
	"VRD_pandoraBookmarkSong" : "Lisää kappale kirjanmerkkeihin",
	"VRD_pandoraCreateStation" : "Luo asema",
	"VRD_pandoraSelectAddCurrentStation" : "Lisää",
	"VRD_pandoraSelectDelete" : "Poista",
	"VRD_pandoraSelectEditDelete" : "Poista",
	"VRD_pandoraSelectEditMove" : "Siirrä",
	"VRD_pandoraSelectEditReplace" : "Korvaa",
	"VRD_pandoraSelectFavorites" : "Suosikit",
	"VRD_pandoraSelectMove" : "Siirrä",
	"VRD_pandoraSelectQuickMix" : "Satunnaistoisto",
	"VRD_pandoraSelectSettings" : "Ääniasetukset",
	"VRD_pandoraSelectSortBy" : "Lajittele",
	"VRD_pandoraSelectSource" : "Viihde",
	"VRD_pandoraSelectStationList" : "Kanavaluettelo",
	"VRD_pandoraShowBookmarkOptions" : "Lisää kirjanmerkkeihin",
	"VRD_pandoraShowByAZ" : "Lajittele aakkosjärjestyksen mukaan",
	"VRD_pandoraShowByDate" : "Lajittele päivämäärän mukaan",
	"VRD_pandoraSkip" : "Ohita",
	"VRD_pandoraThumbsDown" : "En tykkää",
	"VRD_pandoraThumbsUp" : "Tykkään",
	"VRD_phoneCall" : "Soita",
	"VRD_phoneCallBack" : "Soita takaisin",
	"VRD_phoneCallByName" : "Soita nimen perusteella",
	"VRD_phoneCallByNumber" : "Soita numeron perusteella",
	"VRD_phoneCallContactType" : "Soita{contactName}{contactType}",
	"VRD_phoneCallLast" : "Soita viimeisimpään numeroon",
	"VRD_phoneChooseContactType" : "{contactName} {contactType}",
	"VRD_phoneDialAnyNumber" : "Soita {number}",
	"VRD_phoneDialpadClearAllDigits" : "Poista kaikki merkit",
	"VRD_phoneDialpadDeleteDigit" : "Poista",
	"VRD_phoneDialpadPhoneNumber" : "{phoneNumber}",
	"VRD_phoneReDial" : "Soita uudelleen",
	"VRD_phoneSelectByName" : "Nimi",
	"VRD_phoneSelectByNumber" : "Numero",
	"VRD_phoneSelectContactType" : "{contactType}",
	"VRD_phoneSelectDialPad" : "Numeronäppäimet",
	"VRD_phoneSelectFavorites" : "Suosikit",
	"VRD_phoneSelectRecentCalls" : "Viimeisimmät puhelut",
	"VRD_phoneSelectRecentCallsAll" : "Kaikki puhelut",
	"VRD_phoneSelectRecentCallsMissed" : "Vastaamatt. puhelut",
	"VRD_satradioBackSpaceDelete" : "Poista merkit",
	"VRD_satradioChangeLockCode" : "Vaihda PIN-koodi",
	"VRD_satradioEnterPIN" : "{4digitPin}",
	"VRD_satradioInitializeLockCode" : "Alusta PIN-koodi",
	"VRD_satradioPlayChannelName" : "Soita {channelName}",
	"VRD_satradioPlayStationNumber" : "Viritä asema {channelNumber}",
	"VRD_satradioResetLockCode" : "Nollaa PIN-koodi",
	"VRD_satradioSeekNext" : "Hae seuraava",
	"VRD_satradioSeekPrevious" : "Hae edellinen",
	"VRD_satradioSelectChangeCategory" : "Kategoria",
	"VRD_satradioSelectFavorites" : "Suosikit",
	"VRD_satradioSelectParentalLock" : "Lapsilukko",
	"VRD_satradioSelectScanOff" : "Haku pois päältä",
	"VRD_satradioSelectScanOn" : "Haku päällä",
	"VRD_satradioSelectSettings" : "Ääniasetukset",
	"VRD_satradioSelectSource" : "Viihde",
	"VRD_satradioSelectStation" : "Asema {Station number}",
	"VRD_satradioSelectStationAll" : "Kaikki kanavat",
	"VRD_satradioSelectStationCategory" : "{categoryName}",
	"VRD_satradioSelectStationList" : "Kanavaluettelo",
	"VRD_satradioTurnChannelLockOFF" : "Poista nyk. kanavan lukitus",
	"VRD_satradioTurnChannelLockON" : "Lukitse tämä kanava",
	"VRD_satradioTurnParentalLockOFF" : "Istunnon lukitus pois päältä",
	"VRD_satradioTurnParentalLockON" : "Istunnon lukitus päälle",
	"VRD_smsCallPhoneNumber" : "Soita",
	"VRD_smsDelete" : "Poista",
	"VRD_smsImportMessages" : "Päivitä saapuneet tekstiviestit",
	"VRD_smsReply" : "Vastaa",
	"VRD_smsSayAnyConversation" : "{senderName}",
	"VRD_smsSelectBody" : "Lisää viesti",
	"VRD_smsSelectContactName" : "{ContactName}",
	"VRD_smsSelectContinueTextMessage" : "Jatka viestiä",
	"VRD_smsSelectDiscard" : "Hylkää",
	"VRD_smsSelectInbox" : "SMS Saapuneet lista",
	"VRD_smsSelectNone" : "Ei mikään näistä",
	"VRD_smsSelectRetry" : "Yritä uudelleen",
	"VRD_smsSelectReturn" : "Palaa",
	"VRD_smsSelectSend" : "Lähetä",
	"VRD_stitcherAddToFavorites" : "Lisää suosikkeihin",
	"VRD_stitcherRemoveFromFavorites" : "Poista suosikeista",
	"VRD_stitcherSaveFavorites" : "Tallenna muutokset",
	"VRD_stitcherSelectSettings" : "Ääniasetukset",
	"VRD_stitcherSelectSource" : "Viihde",
	"VRD_stitcherSelectStationList" : "Kanavaluettelo",
	"VRD_stitcherThumbsDown" : "En tykkää",
	"VRD_stitcherThumbsUp" : "Tykkään",
	"VRD_systemSelectAhaRadio" : "Aha Radio",
	"VRD_systemSelectAndroidAuto" : "Android Auto",
	"VRD_systemSelectApplications" : "Sovellukset",
	"VRD_systemSelectAuxIn" : "Sisääntulo / AUX",
	"VRD_systemSelectBTAudio" : "Bluetooth",
	"VRD_systemSelectCD" : "CD",
	"VRD_systemSelectCallHistory" : "Puheluhistoria",
	"VRD_systemSelectCarPlay" : "Car Play",
	"VRD_systemSelectCommunication" : "Viestintä",
	"VRD_systemSelectConnect" : "Yhdistä",
	"VRD_systemSelectContacts" : "Yhteystiedot",
	"VRD_systemSelectDAB" : "DAB",
	"VRD_systemSelectDVD" : "DVD",
	"VRD_systemSelectDisplayClock" : "Kellon näyttö",
	"VRD_systemSelectDisplayOff" : "Kytke näyttö päältä",
	"VRD_systemSelectEmail" : "Email",
	"VRD_systemSelectEntertainment" : "Viihde",
	"VRD_systemSelectEntertainmentMenu" : "Viihde valikko",
	"VRD_systemSelectFavorites" : "Suosikit",
	"VRD_systemSelectNavigation" : "Navigointi",
	"VRD_systemSelectNotifications" : "Viestit",
	"VRD_systemSelectNotifyOff" : "Ilmoitus pois",
	"VRD_systemSelectPandora" : "Pandora",
	"VRD_systemSelectPhone" : "Puhelin",
	"VRD_systemSelectRadioAM" : "AM Radio",
	"VRD_systemSelectRadioFM" : "FM radio",
	"VRD_systemSelectRetry" : "Yritä uudelleen",
	"VRD_systemSelectSatRadio" : "Satelliittiradio",
	"VRD_systemSelectSettings" : "Asetukset",
	"VRD_systemSelectSiri" : "Siri",
	"VRD_systemSelectSms" : "Teksti / SMS",
	"VRD_systemSelectStitcher" : "Stitcher",
	"VRD_systemSelectTV" : "TV",
	"VRD_systemSelectTrafficAlert" : "Liikennetiedote (TA)",
	"VRD_systemSelectTutorial" : "Opastus",
	"VRD_systemSelectUSB" : "USB",
	"VRD_systemSelectUSBA" : "USB 1",
	"VRD_systemSelectUSBB" : "USB 2",
	"VRD_systemSelectXmAudio" : "SXM Radio",
	"VRD_tvSelectView" : "Näytä",
	"VRD_usbaudioBrowse" : "Selaa",
	"VRD_usbaudioBrowseAlbum" : "Selaa {albumName}",
	"VRD_usbaudioBrowseAlbums" : "Selaa albumia",
	"VRD_usbaudioBrowseAll" : "Selaa kaikkia kappaleita tai albumeita tai esittäjiä",
	"VRD_usbaudioBrowseAnyAlbum" : "Selaa [Albumi] {albumName}",
	"VRD_usbaudioBrowseAnyArtist" : "Selaa [Esittäjä] {artistName}",
	"VRD_usbaudioBrowseAnyFolder" : "Selaa kansiota {folderName}",
	"VRD_usbaudioBrowseArtist" : "Selaa {artistName}",
	"VRD_usbaudioBrowseArtists" : "Selaa esittäjä",
	"VRD_usbaudioBrowseAudiobooks" : "Selaa äänikirjoja",
	"VRD_usbaudioBrowseFolder" : "Selaa {folderName}",
	"VRD_usbaudioBrowseFolders" : "Selaa kansiota",
	"VRD_usbaudioBrowseGenre" : "Selaa [Tyyli] {genreName}",
	"VRD_usbaudioBrowseGenres" : "Selaa tyylilajeja",
	"VRD_usbaudioBrowseLineNumber" : "Selaa linjaa {lineNumber}",
	"VRD_usbaudioBrowsePlaylist" : "Selaa soittolistaa {playlistName}",
	"VRD_usbaudioBrowsePlaylists" : "Selaa soittolistaa",
	"VRD_usbaudioBrowsePodcast" : "Selaa Podcastia {podcastName}",
	"VRD_usbaudioBrowsePodcasts" : "Selaa Podcasteja",
	"VRD_usbaudioBrowseSongs" : "Selaa laulua",
	"VRD_usbaudioChooseAlbumArtist" : "{artistName}",
	"VRD_usbaudioGenerateMoreLikeThis" : "Lisää tällaisia",
	"VRD_usbaudioPlayAlbums" : "Toista albumi",
	"VRD_usbaudioPlayAll" : "Toista kaikki",
	"VRD_usbaudioPlayAnyAlbum" : "Toista [Albumi] {albumName}",
	"VRD_usbaudioPlayAnyArtist" : "Toista [Esittäjä] {artistName}",
	"VRD_usbaudioPlayAnyFolder" : "Toista kansio {folderName}",
	"VRD_usbaudioPlayArtistAlbum" : "Toista {artistName}{albumName}",
	"VRD_usbaudioPlayArtists" : "Toista esittäjä",
	"VRD_usbaudioPlayAudiobook" : "Toista äänikirja {AudiobookName}",
	"VRD_usbaudioPlayAudiobooks" : "Toista äänikirjat",
	"VRD_usbaudioPlayChapter" : "{chapterName}",
	"VRD_usbaudioPlayChapterIndex" : "Toista jakso {index}{chapter}",
	"VRD_usbaudioPlayEpisode" : "{episodeName}",
	"VRD_usbaudioPlayFolder" : "Toista {folderName}",
	"VRD_usbaudioPlayFolders" : "Toista kansio",
	"VRD_usbaudioPlayGenre" : "Toista [Tyylilaji] {genreName}",
	"VRD_usbaudioPlayGenres" : "Toista tyylilaji",
	"VRD_usbaudioPlayLineNumber" : "Toista [Linja] {lineNumber}",
	"VRD_usbaudioPlayPlaylist" : "Toista soittolista {playlistName}",
	"VRD_usbaudioPlayPlaylists" : "Toista soittolista",
	"VRD_usbaudioPlayPodcast" : "Toista podcast {PodcastName}",
	"VRD_usbaudioPlayPodcasts" : "Toista podcastit",
	"VRD_usbaudioPlaySongs" : "Toista kappale",
	"VRD_usbaudioRepeat" : "Toisto",
	"VRD_usbaudioRepeatAll" : "Toista kaikki uudelleen",
	"VRD_usbaudioRepeatOff" : "Uudelleentoisto pois päältä",
	"VRD_usbaudioRepeatSong" : "Kappaleen toisto",
	"VRD_usbaudioRewind" : "Siirry taaksepäin",
	"VRD_usbaudioSelectAlbum" : "Albumi {albumName}",
	"VRD_usbaudioSelectAlbums" : "Albumi",
	"VRD_usbaudioSelectAll" : "Kaikki Jaksot tai Luvut tai Kappaleet tai Esiintyjät ",
	"VRD_usbaudioSelectArtist" : "Esittäjä {artistName}",
	"VRD_usbaudioSelectArtists" : "Esittäjä",
	"VRD_usbaudioSelectAudiobook" : "{audiobookName}",
	"VRD_usbaudioSelectAudiobooks" : "Äänikirjat",
	"VRD_usbaudioSelectFolder" : "Kansio {folderName}",
	"VRD_usbaudioSelectFolders" : "Kansiot",
	"VRD_usbaudioSelectGenre" : "Tyylilaji {genreName}",
	"VRD_usbaudioSelectGenres" : "Tyylilaji",
	"VRD_usbaudioSelectPlaylist" : "Soittolista {playlistName}",
	"VRD_usbaudioSelectPlaylists" : "Soittolista",
	"VRD_usbaudioSelectPodcast" : "{podcastName}",
	"VRD_usbaudioSelectPodcasts" : "Podcast",
	"VRD_usbaudioSelectRootFolder" : "Päävalikko",
	"VRD_usbaudioSelectSettings" : "Ääniasetukset",
	"VRD_usbaudioSelectSongs" : "Kappale",
	"VRD_usbaudioSelectSourceMenu" : "Viihde",
	"VRD_usbaudioShuffle" : "Satunnaistoisto",
	"VRD_usbaudioShuffleOff" : "Satunnaistoisto pois päältä",
	"VRD_usbaudioShuffleOn" : "Satunnaistoisto päällä",
	"VRD_usbaudioSongList" : "Kappaleluettelo",
	"VRD_xmaudioBackSpaceDelete" : "Poista merkit",
	"VRD_xmaudioChangeLockCode" : "Muokkaa PIN-koodia",
	"VRD_xmaudioConfirmDelete" : "Poista",
	"VRD_xmaudioEnterPIN" : "{fourDigitPIN}",
	"VRD_xmaudioPlayChannelName" : "Toista XM kanava {channelName}",
	"VRD_xmaudioPlayStationNumber" : "Viritä kanavalle {channelNumber}",
	"VRD_xmaudioResetLockCode" : "Nollaa PIN-koodi",
	"VRD_xmaudioSelectCallXM" : "Soita XM",
	"VRD_xmaudioSelectChangeCategory" : "Vaihda Kategoriaa",
	"VRD_xmaudioSelectContinueListening" : "Jatka kuuntelua",
	"VRD_xmaudioSelectDismiss" : "Hylkää",
	"VRD_xmaudioSelectEveryOccurance" : "Jokainen esiintymä",
	"VRD_xmaudioSelectEveryOtherReport" : "Joka toinen raportti",
	"VRD_xmaudioSelectEveryReport" : "Kaikki raportit",
	"VRD_xmaudioSelectExitTuneMix" : "Poistu TuneMix-kanavalta",
	"VRD_xmaudioSelectFavorites" : "Suosikit",
	"VRD_xmaudioSelectListenNow" : "Kuuntele nyt",
	"VRD_xmaudioSelectMove" : "Siirrä",
	"VRD_xmaudioSelectNearestCity" : "Lähin kaupunki",
	"VRD_xmaudioSelectOnlyFirstAfterVehicleStart" : "Ajoneuvon käynnistys",
	"VRD_xmaudioSelectOnlyFirstOccuranceInGame" : "Ensimmäinen esiintymä",
	"VRD_xmaudioSelectReplayAlert" : "Uudelleensoiton hälytys",
	"VRD_xmaudioSelectReturnToPrevious" : "Palaa edelliseen",
	"VRD_xmaudioSelectSFSportBaseball" : "Baseball",
	"VRD_xmaudioSelectSFSportNCAA" : "College jalkapallo",
	"VRD_xmaudioSelectSFSportNFL" : "Ammattilaisjalkapallo",
	"VRD_xmaudioSelectSFSportNHL" : "Hockey",
	"VRD_xmaudioSelectScanOff" : "Haku pois päältä",
	"VRD_xmaudioSelectScanOn" : "Haku päällä",
	"VRD_xmaudioSelectSettings" : "Asetukset",
	"VRD_xmaudioSelectSoundSettings" : "Ääniasetukset",
	"VRD_xmaudioSelectSource" : "Viihde",
	"VRD_xmaudioSelectStation" : "Asema {channelNumber}",
	"VRD_xmaudioSelectStationAll" : "Kaikki kanavat",
	"VRD_xmaudioSelectStationCategory" : "{categoryName}",
	"VRD_xmaudioSelectStationFeaturedFavorites" : "Tärkeimmät Suosikit",
	"VRD_xmaudioSelectStationList" : "Kanavat",
	"VRD_xmaudioSelectTuneMix" : "TuneMix",
	"VRD_xmaudioSelectTuneMixChannel" : "TuneMix-kanavavalinnat",
	"VRD_xmaudioSelectTuneMixChannelsOptions" : "Kanavavaihtoehdot",
	"VRD_xmaudioSelectTuneMixCreation" : "Luo uusi TuneMix-kanava",
	"VRD_xmaudioSelectTuneMixEdit" : "Muokkaa TuneMix-kanavaa",
	"VRD_xmaudioSelectTuneMixEditOps" : "TuneMix muokkausvalikko",
	"VRD_xmaudioSelectTuneMixRemove" : "Poista TuneMix-kanava",
	"VRD_xmaudioSelectTuneMixRename" : "Uudelleennimeä TuneMix",
	"VRD_xmaudioSelectTurnAlertsOff" : "Hälytykset pois päältä",
	"VRD_xmaudioSelectiTunesTagging" : "iTunes-tunnisteet",
	"VRD_xmaudioSetChannelLock" : "Lukitse kanava",
	"VRD_xmaudioSetParentalLock" : "Istunnon lukitus",
	"VRD_xmdataSelectFuelPrices" : "Polttoaineen hinnat",
	"VRD_xmdataSelectMovies" : "Elokuvat",
	"VRD_xmdataSelectParking" : "Pysäköinti",
	"VRD_xmdataSelectSports" : "Urheilu",
	"VRD_xmdataSelectStock" : "Osakkeet",
	"VRD_xmdataSelectTrafficPlus" : "Liikenne Plus",
	"VRD_xmdataSelectWeatherForecast" : "Säätiedot",
	"VRD_xmdataSelectWeatherRadar" : "Säätutka",
	"VRD_xmdataSelectWeatherSecurityAlerts" : "Säähälytykset",
};

framework.registerAppDictLoaded("system", "fi_FI");