var __VrHelpPositionTable__systemAppDict_ru_RU = {
	"HomeScreen_Help" : {
		"Right" : ["VrHelp_Favorites"],
		"Left" : ["VrHelp_Entertainment","VrHelp_Communication","VrHelp_Navigation","VrHelp_Settings","VrHelp_Applications"]
	}
};

var Localization_systemAppDict_ru_RU = {
	//"stringId" : "localString"
	"ActiveCallItem" : "Активный вызов",
	"AhaMaintError" : "Ошибка обсл-ния прилож. aha",
	"AhaRadio" : "aha",
	"AmRadio" : "AM",
	"AndroidAuto" : "Android Auto",
	"Applications" : "Приложения",
	"AudioSourceNotAvailableBTAudio" : "Аудио Bluetooth недоступно",
	"AudioSourceNotAvailableCD" : "CD был удален",
	"AudioSourceNotAvailableDVD" : "DVD был удален",
	"AudioSourceNotAvailableTV" : "ТВ недоступно",
	"AudioSourceNotAvailableUSB" : "USB-устройство изменено",
	"AuxIn" : "AUX",
	"BT" : "BT",
	"Bluetooth" : "Bluetooth",
	"BluetoothWithDevice" : "Bluetooth - {deviceName}",
	"CallHistory" : "История вызовов",
	"CarPlay" : "Apple CarPlay",
	"CdPlayer" : "CD",
	"ChannelOffAir" : "Неэфирный канал",
	"ChannelUnauth" : "Канал не авторизован",
	"CheckAntenna" : "Проверьте антенну",
	"CheckTuner" : "Проверьте тюнер",
	"Communication" : "Связь",
	"Connect" : "Подключение",
	"Contacts" : "Контакты",
	"DVDItem" : "DVD",
	"DabRadio" : "DAB",
	"DialPhone" : "Набор на телефоне",
	"DidYouSay" : "Ты сказал. , ,",
	"DisclaimerText" : "Отвлечение внимания водителя от управления а/м может привести к ДТП. Будьте внимательны во время движения и соблюдайте ПДД. См. \"Руководство по эксплуатации а/м\".",
	"DisconnectThenReconnect" : "Ошибка при запуске Siri. Отключите и заново подключите Apple Device",
	"DriveRecord" : "Запись поездок",
	"DriverIDItem" : "Выбор водителя",
	"EcoenergyApp" : "Экономия топлива",
	"EcoenergyAppHEV" : "Контроль поездки",
	"Email" : "Эл. почта",
	"EngineOilLevel" : "Уровень масла двигат.",
	"Entertainment" : "Развлечения",
	"ErrorWhileStartingSiri" : "Ошибка при попытке начать сеанс Siri.",
	"FailedNotificationRetrieval" : "Невозможно получить список уведомлений",
	"FavoritesItem" : "Избранное",
	"FmRadio" : "FM",
	"HDTrafficItem" : "Дорожная карта HD Radio™",
	"InitiateSiri" : "Чтобы начать сеанс Siri, нажмите и удерживайте кнопку «Говорить».",
	"IntelligentDriveMasterItem" : "i-DM",
	"NavigationTitle" : "Навигация",
	"NoConnectionNotifyText" : "Хотите подключить телефон сейчас?",
	"NoConnectionNotifyTitle" : "Нет подключенного телефона",
	"NoDeviceText" : "Хотите подключить устройство сейчас?",
	"NoDeviceTitle" : "Устройства не подключены",
	"Notifications" : "Уведомления",
	"NotifyIgnore" : "Игнор-вать",
	"NotifyIncomingMsg" : "Входящее сообщение от:",
	"NotifyOff" : "Увед. выкл.",
	"NotifyRead" : "Чтение",
	"NotifyReadNow" : "Хотите подключить прочитать сейчас?",
	"Pandora" : "Pandora",
	"ReconnectAhaRadio" : "Переподкл. Bluetooth для радио aha",
	"ReconnectBTAudio" : "Переподкл. Bluetooth д/проигрыв-я",
	"ReconnectCD" : "Проверка CD для продолжения воспр.",
	"ReconnectCarPlay" : "Возобновление работы системы Apple CarPlay.",
	"ReconnectDVD" : "Проверка DVD для продолж. воспр.",
	"ReconnectEntMenuButton" : "Меню «Развлечения»",
	"ReconnectFailedBTAudio" : "Невозможно переподкл. аудио Bluetooth",
	"ReconnectFailedCD" : "CD был удален. Невозможно возобновить воспроизведение.",
	"ReconnectFailedCarPlay" : "Не удалось повторно подключить систему Apple CarPlay",
	"ReconnectFailedDVD" : "DVD был удален. Невозможно возобновить воспроизведение.",
	"ReconnectFailedTV" : "TV недоступно. Невозможно возобновить воспроизведение.",
	"ReconnectFailedUSB" : "USB-устройство изменено. Невозможно возобновить воспроизведение.",
	"ReconnectPandora" : "Переподкл. Bluetooth для Pandora",
	"ReconnectStitcher" : "Переподкл. Bluetooth для Stitcher",
	"ReconnectTV" : "Проверка ТВ для возобновление воспроизведения",
	"ReconnectUSB" : "Переподкл. USB для продолж. воспр.",
	"RetryLabel" : "Повтор",
	"SchedMaintenanceApp" : "Обслуживание",
	"ScreenReplication" : "Дублирование экрана",
	"SdarsRadio" : "XM",
	"Settings" : "Настройки",
	"SettingsCommunication" : "Настройки",
	"Siri" : "Siri",
	"SiriDisabled" : "Система Siri отключена на устройстве Apple.",
	"Sms" : "SMS",
	"StitcherItem" : "Stitcher",
	"TVItem" : "ТВ",
	"TempWarning" : "Предупреждение о перегреве",
	"TempWarningText" : "Дисплей перегрелся. Качество изображения может снизиться. Необходимо охлаждение.",
	"TextDownloaded" : "SMS загружено",
	"TextSent" : "SMS отправлено",
	"TrafficAlertsItem" : "Информация о ситуации на дороге",
	"USB" : "USB",
	"USB1AndroidAuto" : "USB 1 - Android Auto",
	"USB1CarPlay" : "USB 1 - Apple CarPlay",
	"USB2AndroidAuto" : "USB 2 - Android Auto",
	"UsbAudioA" : "USB 1",
	"UsbAudioAWithDevice" : "USB 1 - {deviceName}",
	"UsbAudioB" : "USB 2",
	"UsbAudioBWithDevice" : "USB 2 - {deviceName}",
	"UseCommander" : "Используйте ручку управления во время движения.",
	"VehicleDataTransferItem" : "Передача данных автомобиля ",
	"VehicleStatusMonitor" : "Монитор сост. а/м",
	"VehicleTelemetryTransfer" : "VTT",
	"VideoSignalLost" : "Видеосигнал потерян",
	"VoiceNotSupported" : "Голос не поддерживается ",
	"VoiceRecognition" : "Распознавание голоса",
	"VrHelp_Applications" : "Приложения",
	"VrHelp_Communication" : "Связь",
	"VrHelp_Entertainment" : "Развлечения",
	"VrHelp_Favorites" : "Избранное",
	"VrHelp_Navigation" : "Навигация",
	"VrHelp_Settings" : "Настройки",
	"WarnGuidanceApp" : "Предупреждения",
	"WarningTitle" : "ПРЕДУПРЕЖДЕНИЕ!",
	"XMAudio" : "SXM",
	"XMData" : "SXM Services",
	"agree" : "Я согласен",
	"VRD_aharadioSelectCall" : "Вызов",
	"VRD_aharadioSelectDiscard" : "Удалить",
	"VRD_aharadioSelectEpisodes" : "Список эпизодов",
	"VRD_aharadioSelectLBSTab" : "Близлежащий",
	"VRD_aharadioSelectMainList" : "Главный список Aha",
	"VRD_aharadioSelectMap" : "Карта",
	"VRD_aharadioSelectPresetsTab" : "Настроенная станция",
	"VRD_aharadioSelectSave" : "Сохранить",
	"VRD_aharadioSelectSettings" : "Настройки звука",
	"VRD_aharadioSelectShout" : "Восклицание",
	"VRD_aharadioSelectSource" : "Развлечения/Изменить источник",
	"VRD_aharadioSelectThumbsDown" : "Не нравится",
	"VRD_aharadioSelectThumbsUp" : "Нравится",
	"VRD_amradioPlayStationFrequency" : "Настроить на {frequency} AM",
	"VRD_amradioSelectAutoMemory" : "Авто-память ",
	"VRD_amradioSelectFavorites" : "Избранное",
	"VRD_amradioSelectHD" : "Станции HD",
	"VRD_amradioSelectHDOff" : "карта HD Radio выкл",
	"VRD_amradioSelectHDOn" : "Kарта HD Radio выкл.",
	"VRD_amradioSelectScanOff" : "Сканировать Выкл.",
	"VRD_amradioSelectScanOn" : "Сканировать Вкл.",
	"VRD_amradioSelectSeekNext" : "Искать cледующий",
	"VRD_amradioSelectSeekPrevious" : "Искать пpeдыдущий",
	"VRD_amradioSelectSettings" : "Настройки звука",
	"VRD_amradioSelectSource" : "Перейти в меню развлечений",
	"VRD_amradioSelectStationFrequency" : "{AMFrequency}",
	"VRD_amradioSelectTrafficAlert" : "Контроль трафика",
	"VRD_amradioSelectTrafficAlertOff" : "Выключить контроль трафика",
	"VRD_amradioSelectTrafficAlertOn" : "Включить контроль трафика",
	"VRD_amradioSelectTune" : "Настройка частот",
	"VRD_amradioSelectUpdateAutoMemory" : "Автопоиск по памяти",
	"VRD_amradioSelectiTunesTagging" : "Тегирование iTunes",
	"VRD_amradioTuneDown" : "Частота ниже",
	"VRD_amradioTuneUp" : "Частота выше",
	"VRD_amradioUpdateAutoMemory" : "Обновить список станций",
	"VRD_auxinSelectSettings" : "Настройки звука",
	"VRD_auxinSelectSource" : "Развлечения/Изменить источник",
	"VRD_btaudioScanPlay" : "воспроизвести в режиме ознакомления",
	"VRD_btaudioSelectConnect" : "Подключение",
	"VRD_btaudioSelectRootMenu" : "Корневое меню",
	"VRD_btaudioSelectSettings" : "Настройки звука",
	"VRD_btaudioSelectSource" : "Перейти в меню развлечений",
	"VRD_btaudioToggleRepeat" : "Повторить",
	"VRD_btaudioToggleShuffle" : "В случайном порядке",
	"VRD_carplaySelectApplications" : "Приложения",
	"VRD_cdGoSettings" : "Настройки звука",
	"VRD_cdHandleStartScan" : "Начать сканирование",
	"VRD_cdPlayBeginning" : "С начала",
	"VRD_cdRepeatFolder" : "Повторно воспроизвести папку",
	"VRD_cdRepeatOff" : "повторить выключить",
	"VRD_cdRepeatOn" : "Включить повторение",
	"VRD_cdRepeatTrack" : "Повторно воспроизвести трек",
	"VRD_cdSelectCurrentFolder" : "Текущая папка",
	"VRD_cdSelectRepeat" : "Повторить",
	"VRD_cdSelectRootFolder" : "Корневое меню",
	"VRD_cdSelectShuffle" : "В случайном порядке",
	"VRD_cdSelectSource" : "Перейти в меню развлечений",
	"VRD_cdSelectTrackList" : "Список треков",
	"VRD_cdSelectTrackNumber" : "Воспроизвести дорожку {Number}",
	"VRD_cdShuffleDisk" : "Диск в случайном порядке",
	"VRD_cdShuffleFolder" : "Папка в случайном порядке",
	"VRD_cdShuffleOff" : "Отключить случайный выбор",
	"VRD_cdShuffleOn" : "Включить случайный выбор",
	"VRD_commonAddToFavorites" : "Добавить в избранное",
	"VRD_commonCancel" : "Отмена",
	"VRD_commonFastForward" : "Быстро вперед",
	"VRD_commonGoBack" : "Назад",
	"VRD_commonIntentParent" : "Родительская",
	"VRD_commonIntentParentUSBAudio" : "Родительская",
	"VRD_commonIntentUSBAudio" : "Дом.:",
	"VRD_commonIntentUSBAudioBG" : "Дом.:",
	"VRD_commonMenuUp" : "Меню вверх",
	"VRD_commonNext" : "Следующий",
	"VRD_commonNo" : "Нет",
	"VRD_commonPageDown" : "На страницу ниже/прокрутка вниз",
	"VRD_commonPageUp" : "На страницу выше/прокрутка вверх",
	"VRD_commonPause" : "Пауза",
	"VRD_commonPrevious" : "Предыдущий ",
	"VRD_commonResume" : "Воспроизведение/продолжить",
	"VRD_commonRewind" : "Перемотка",
	"VRD_commonSelectLineNumber" : "Линия {lineNumber}",
	"VRD_commonYes" : "Да/ОК",
	"VRD_contactsChooseContactName" : "{ContactName}",
	"VRD_contactsDisambiguateContactName" : "Показать {ContactName}",
	"VRD_contactsImportAll" : "Импорт контактов",
	"VRD_contactsImportCancel" : "Отм. имп.",
	"VRD_contactsImportContacts" : "Редактировать контакты",
	"VRD_contactsImportSingle" : "Импортировать выбранный контакт",
	"VRD_contactsRemoveContact" : "Удалить контакт",
	"VRD_contactsSelectCall" : "Вызов",
	"VRD_contactsSelectContactName" : "{ContactName}",
	"VRD_contactsSelectDownload" : "Загрузка",
	"VRD_contactsSelectFavorites" : "Избранное",
	"VRD_contactsSelectNone" : "Ни один из перечисленных",
	"VRD_contactsSelectReadContactName" : "Прочитать имя контакта",
	"VRD_contactsSelectRemove" : "Удалить",
	"VRD_contactsSelectRetry" : "Повтор",
	"VRD_contactsSendPhoneType" : "{phoneType}",
	"VRD_contactsShowAddress" : "Адрес",
	"VRD_dabDisplayDABSettings" : "Настройки DAB",
	"VRD_dabDisplayEnsembleList" : "Выбрать ансамбль",
	"VRD_dabDisplayStationList" : "Список станций ",
	"VRD_dabSelectFavorites" : "Избранное",
	"VRD_dabSelectScan" : "Сканировать",
	"VRD_dabSelectSeekNext" : "Следующий",
	"VRD_dabSelectSeekPrevious" : "Предыдущий ",
	"VRD_dabSelectSettings" : "Настройки звука",
	"VRD_dabSelectSource" : "Развлечения",
	"VRD_dabTAToggleOFF" : "Выключить трафика",
	"VRD_dabTAToggleON" : "Вкл. трафика",
	"VRD_dabTAToggleVois" : "Контроль трафика",
	"VRD_dabUpdateStationList" : "Обновить список",
	"VRD_dvdClearPin" : "Удалить цифры",
	"VRD_dvdSayGRating" : "G",
	"VRD_dvdSayPG12" : "P G 12",
	"VRD_dvdSayR15" : "R 15 плюс",
	"VRD_dvdSayR18" : "--",
	"VRD_dvdSelectAspectRatio" : "Формат изображения",
	"VRD_dvdSelectAudioSettings" : "Настройки видео",
	"VRD_dvdSelectCameraAngle" : "Угол камеры",
	"VRD_dvdSelectEditPin" : "Редактировать ПИН-код",
	"VRD_dvdSelectParentLock" : "Родительская блокировка",
	"VRD_dvdSelectParentLockOff" : "Выключить родительскую блокировку",
	"VRD_dvdSelectParentLockOn" : "родительская блокировка вкл.",
	"VRD_dvdSelectParentLockRating" : "Уровень родительской блокировки",
	"VRD_dvdSelectResetPin" : "Сбросить пин-код",
	"VRD_dvdSelectRootMenu" : "Корневое меню",
	"VRD_dvdSelectSettings" : "Настройки звука",
	"VRD_dvdSelectSource" : "Развлечения",
	"VRD_dvdSelectSubtitleOff" : "Выкл. субтитры",
	"VRD_dvdSelectSubtitleOn" : "Вкл. субтитры",
	"VRD_dvdSlowForward" : "Быстро вперед",
	"VRD_dvdSlowRewind" : "Перемотка",
	"VRD_dvdVUISendPin" : "{FourDigitPin}",
	"VRD_emailSelectAllAccounts" : "Все аккаунты",
	"VRD_emailSelectCall" : "Вызов",
	"VRD_emailSelectContactName" : "{ContactName}",
	"VRD_emailSelectContinueEmail" : "Продолжайте эл. сообщение",
	"VRD_emailSelectDelete" : "Удалить",
	"VRD_emailSelectDiscard" : "Удалить",
	"VRD_emailSelectImportEmail" : "Обновить входящие",
	"VRD_emailSelectInbox" : "Входящая электронная почта",
	"VRD_emailSelectInboxSelector" : "Входящ.",
	"VRD_emailSelectMessage" : "Добавить сообщение",
	"VRD_emailSelectNone" : "Ни один из перечисленных",
	"VRD_emailSelectReply" : "Ответить",
	"VRD_emailSelectReplyAll" : "Ответить всем",
	"VRD_emailSelectRetry" : "Повтор",
	"VRD_emailSelectReturn" : "Возврат",
	"VRD_emailSelectSend" : "Отправить",
	"VRD_emailSelectSenderName" : "{senderName}",
	"VRD_emnaviAcceptAvoidance" : "Подтвердить",
	"VRD_emnaviAddCurrentPosToFavourites" : "Добавить текущую позицию в избранное",
	"VRD_emnaviAddWaypointCityCenter" : "Добавить точку маршрута: центр города",
	"VRD_emnaviAddWaypointDistrictCenter" : "Добавить точку маршрута: районный центр",
	"VRD_emnaviAddWaypointFavorite" : "Добавить избранную точку маршрута",
	"VRD_emnaviAddWaypointPOI" : "Добавить точку маршрута {poiHypList}",
	"VRD_emnaviAvoidRouteAhead" : "Сократить маршрут",
	"VRD_emnaviCancelRoute" : "Отменить маршрут",
	"VRD_emnaviDecreaseAvoidanceLength" : "Меньше",
	"VRD_emnaviGoToCockpit" : "Начать",
	"VRD_emnaviIncreaseAvoidanceLength" : "Еще",
	"VRD_emnaviJPJ_VDEHypothesisList" : "Название города",
	"VRD_emnaviNavigateHere" : "Ехать сюда",
	"VRD_emnaviNavigateHome" : "Ехать домой",
	"VRD_emnaviNavigateToARecentDestination" : "Ехать к последнему пункту назначения",
	"VRD_emnaviNavigateToAddress" : "Ехать по адресу",
	"VRD_emnaviNavigateToCityCenter" : "Ехать в центр города",
	"VRD_emnaviNavigateToDistrictCenter" : "Ехать в районный центр",
	"VRD_emnaviNavigateToFavorite" : "Ехать к избранному",
	"VRD_emnaviNavigateToPOI" : "Ехать к {poiHypList}",
	"VRD_emnaviNewDestination" : "Новый пункт назначения",
	"VRD_emnaviRepeatInstruction" : "Повторить инструкцию",
	"VRD_emnaviRouteSummary" : "Сведения о маршруте",
	"VRD_emnaviSelectCancelRoute" : "Очистить маршрут",
	"VRD_emnaviSelectNavigateToAddress" : "Ехать по адресу",
	"VRD_emnaviSimpleHypothesisList" : "Название штата",
	"VRD_emnaviStepByStep" : "Поэтапный ввод",
	"VRD_emnaviTravelViaARecentDestination" : "Добавить точку маршрута: последний пункт назначения",
	"VRD_emnaviTravelViaAddress" : "Ехать через адрес",
	"VRD_emnaviTravelViaHome" : "Ехать через домашний адрес",
	"VRD_emnaviTryAgain" : "Повторите попытку",
	"VRD_emnaviUniSimpleHypothesisList" : "Адрес",
	"VRD_emnaviUniVDEHypothesisList" : "Адрес",
	"VRD_emnaviVDEHypothesisList" : "Адрес",
	"VRD_emnaviWhereAmI" : "Где я",
	"VRD_emnaviZoomIn" : "Увеличить",
	"VRD_emnaviZoomOut" : "Уменьшить",
	"VRD_fmradioPlayStationFrequency" : " Настроить на {frequency} FM",
	"VRD_fmradioSelectAutoMemory" : "Авто-память ",
	"VRD_fmradioSelectChangeGenre" : "Изменить жанр",
	"VRD_fmradioSelectFMSettings" : "Настройки FM",
	"VRD_fmradioSelectFavorites" : "Избранное",
	"VRD_fmradioSelectGenreSeek" : "Поиск по жанру",
	"VRD_fmradioSelectHDChannel" : "{HD Channel}",
	"VRD_fmradioSelectHDChannels" : "Станции HD",
	"VRD_fmradioSelectHDRadio" : "HD Radio",
	"VRD_fmradioSelectHDRadioOff" : "карта HD Radio выкл",
	"VRD_fmradioSelectHDRadioOn" : "Kарта HD Radio выкл.",
	"VRD_fmradioSelectScanOff" : "Сканировать Выкл.",
	"VRD_fmradioSelectScanOn" : "Сканировать Вкл.",
	"VRD_fmradioSelectSeekNext" : "Искать cледующий",
	"VRD_fmradioSelectSeekPrevious" : "Искать пpeдыдущий",
	"VRD_fmradioSelectSettings" : "Настройки звука",
	"VRD_fmradioSelectSource" : "Развлечения/Изменить источник",
	"VRD_fmradioSelectStationAll" : "Все станции",
	"VRD_fmradioSelectStationFrequency" : "{frequency}",
	"VRD_fmradioSelectStationGenre" : "{genreName}",
	"VRD_fmradioSelectStationList" : "Список станций ",
	"VRD_fmradioSelectStationName" : "{stationName}",
	"VRD_fmradioSelectTrafficAlert" : "Контроль трафика",
	"VRD_fmradioSelectTrafficAlertOff" : "Выключить трафик",
	"VRD_fmradioSelectTrafficAlertOn" : "Вкл. трафика",
	"VRD_fmradioSelectTune" : "Настройка частот",
	"VRD_fmradioSelectUpdateAutoMemory" : "Обновить Авто-память ",
	"VRD_fmradioSelectiTunesTagging" : "Тегирование iTunes",
	"VRD_fmradioTuneDown" : "Частота ниже",
	"VRD_fmradioTuneUp" : "Частота выше",
	"VRD_fmradioTurnOffAF" : "Альтернативная частота Выкл.",
	"VRD_fmradioTurnOffREG" : "Блокировка региона Выкл.",
	"VRD_fmradioTurnOnAF" : " Альтернативная частота Вкл. ",
	"VRD_fmradioTurnOnREG" : "Блокировка региона Вкл.",
	"VRD_fmradioUpdateAutoMemory" : "Обновить список станций",
	"VRD_pandoraAddStation" : "Добавить станцию",
	"VRD_pandoraAddStationFromArtist" : "Создать станцию из исполнителя",
	"VRD_pandoraAddStationFromSong" : "Создать станцию из песни",
	"VRD_pandoraAddToFavorites" : "Добавить в избранное",
	"VRD_pandoraBookmarkArtist" : "Добавить закладку д/исполнителя",
	"VRD_pandoraBookmarkSong" : "Добавить закладку для песни",
	"VRD_pandoraCreateStation" : "Создать станцию",
	"VRD_pandoraSelectAddCurrentStation" : "Добавить в избранное",
	"VRD_pandoraSelectDelete" : "Удалить",
	"VRD_pandoraSelectEditDelete" : "Удалить",
	"VRD_pandoraSelectEditMove" : "Переместить",
	"VRD_pandoraSelectEditReplace" : "Заменить",
	"VRD_pandoraSelectFavorites" : "Избранное",
	"VRD_pandoraSelectMove" : "Переместить",
	"VRD_pandoraSelectQuickMix" : "В случайном порядке",
	"VRD_pandoraSelectSettings" : "Настройки звука",
	"VRD_pandoraSelectSortBy" : "Сортировать",
	"VRD_pandoraSelectSource" : "Развлечения",
	"VRD_pandoraSelectStationList" : "Список станций ",
	"VRD_pandoraShowBookmarkOptions" : "Закладка",
	"VRD_pandoraShowByAZ" : "Сортировать по алфавиту",
	"VRD_pandoraShowByDate" : "Сортировать по дате",
	"VRD_pandoraSkip" : "Пропуск",
	"VRD_pandoraThumbsDown" : "Не нравится",
	"VRD_pandoraThumbsUp" : "Нравится",
	"VRD_phoneCall" : "Вызов",
	"VRD_phoneCallBack" : "Перезвонить",
	"VRD_phoneCallByName" : "Вызов по имени",
	"VRD_phoneCallByNumber" : "Вызов по номеру",
	"VRD_phoneCallContactType" : "Позвонить {contactName} {contactType}",
	"VRD_phoneCallLast" : "Позвонить по последнему номеру",
	"VRD_phoneChooseContactType" : "{contactName} {contactType}",
	"VRD_phoneDialAnyNumber" : "Вызов {number}",
	"VRD_phoneDialpadClearAllDigits" : "Очистить все цифры",
	"VRD_phoneDialpadDeleteDigit" : "Удалить",
	"VRD_phoneDialpadPhoneNumber" : "{phoneNumber}",
	"VRD_phoneReDial" : "Повторный набор",
	"VRD_phoneSelectByName" : "Имя",
	"VRD_phoneSelectByNumber" : "Номер",
	"VRD_phoneSelectContactType" : "{contactType}",
	"VRD_phoneSelectDialPad" : "Клавиатура набора",
	"VRD_phoneSelectFavorites" : "Избранное",
	"VRD_phoneSelectRecentCalls" : "Недавние вызовы",
	"VRD_phoneSelectRecentCallsAll" : "Все вызовы",
	"VRD_phoneSelectRecentCallsMissed" : "Пропущенные вызовы",
	"VRD_satradioBackSpaceDelete" : "Удалить цифры",
	"VRD_satradioChangeLockCode" : "Изменить ПИН-код",
	"VRD_satradioEnterPIN" : "{4digitPin}",
	"VRD_satradioInitializeLockCode" : "Инициализировать ПИН-код",
	"VRD_satradioPlayChannelName" : "Воспроизвести {channelName}",
	"VRD_satradioPlayStationNumber" : "Настроить на {channelNumber}",
	"VRD_satradioResetLockCode" : "Сбросить пин-код",
	"VRD_satradioSeekNext" : "Искать cледующий",
	"VRD_satradioSeekPrevious" : "Искать пpeдыдущий",
	"VRD_satradioSelectChangeCategory" : "Категория",
	"VRD_satradioSelectFavorites" : "Избранное",
	"VRD_satradioSelectParentalLock" : "Родительская блокировка",
	"VRD_satradioSelectScanOff" : "Сканировать Выкл.",
	"VRD_satradioSelectScanOn" : "Сканировать Вкл.",
	"VRD_satradioSelectSettings" : "Настройки звука",
	"VRD_satradioSelectSource" : "Развлечения",
	"VRD_satradioSelectStation" : "Станция {Station number}",
	"VRD_satradioSelectStationAll" : "Все каналы",
	"VRD_satradioSelectStationCategory" : "{categoryName}",
	"VRD_satradioSelectStationList" : "Список каналов",
	"VRD_satradioTurnChannelLockOFF" : "Разблокировать текущий канал",
	"VRD_satradioTurnChannelLockON" : "Закр. тек. канал",
	"VRD_satradioTurnParentalLockOFF" : "Выключить блокировку сеанса",
	"VRD_satradioTurnParentalLockON" : "Включить блокировку сеанса",
	"VRD_smsCallPhoneNumber" : "Вызов",
	"VRD_smsDelete" : "Удалить",
	"VRD_smsImportMessages" : "Обновить папку входящих текстовых сообщений",
	"VRD_smsReply" : "Ответить",
	"VRD_smsSayAnyConversation" : "{senderName}",
	"VRD_smsSelectBody" : "Добавить сообщение",
	"VRD_smsSelectContactName" : "{ContactName}",
	"VRD_smsSelectContinueTextMessage" : "Продолжить сообщение",
	"VRD_smsSelectDiscard" : "Удалить",
	"VRD_smsSelectInbox" : "Список входящих SMS-сообщений",
	"VRD_smsSelectNone" : "Ни один из перечисленных",
	"VRD_smsSelectRetry" : "Повтор",
	"VRD_smsSelectReturn" : "Возврат",
	"VRD_smsSelectSend" : "Отправить",
	"VRD_stitcherAddToFavorites" : "Добавить в избранное",
	"VRD_stitcherRemoveFromFavorites" : "Удалить из избранного",
	"VRD_stitcherSaveFavorites" : "Сохранить изменения",
	"VRD_stitcherSelectSettings" : "Настройки звука",
	"VRD_stitcherSelectSource" : "Развлечения",
	"VRD_stitcherSelectStationList" : "Список станций ",
	"VRD_stitcherThumbsDown" : "Не нравится",
	"VRD_stitcherThumbsUp" : "Нравится",
	"VRD_systemSelectAhaRadio" : "Радио Aha",
	"VRD_systemSelectAndroidAuto" : "Android Auto",
	"VRD_systemSelectApplications" : "Приложения",
	"VRD_systemSelectAuxIn" : "Линейный вход/AUX",
	"VRD_systemSelectBTAudio" : "Bluetooth",
	"VRD_systemSelectCD" : "CD",
	"VRD_systemSelectCallHistory" : "История вызовов",
	"VRD_systemSelectCarPlay" : "CarPlay",
	"VRD_systemSelectCommunication" : "Связь",
	"VRD_systemSelectConnect" : "Подключение",
	"VRD_systemSelectContacts" : "Контакты",
	"VRD_systemSelectDAB" : "DAB",
	"VRD_systemSelectDVD" : "DVD",
	"VRD_systemSelectDisplayClock" : "дисплей часов",
	"VRD_systemSelectDisplayOff" : "Выключить дисплей",
	"VRD_systemSelectEmail" : "Эл. почта",
	"VRD_systemSelectEntertainment" : "Развлечения",
	"VRD_systemSelectEntertainmentMenu" : "Меню развлечений",
	"VRD_systemSelectFavorites" : "Избранное",
	"VRD_systemSelectNavigation" : "Навигация",
	"VRD_systemSelectNotifications" : "Сообщения",
	"VRD_systemSelectNotifyOff" : "Увед. выкл.",
	"VRD_systemSelectPandora" : "Pandora",
	"VRD_systemSelectPhone" : "Встр.",
	"VRD_systemSelectRadioAM" : "Радио AM",
	"VRD_systemSelectRadioFM" : "Радио FM",
	"VRD_systemSelectRetry" : "Повтор",
	"VRD_systemSelectSatRadio" : "Спутниковое радио",
	"VRD_systemSelectSettings" : "Настройки",
	"VRD_systemSelectSiri" : "Siri",
	"VRD_systemSelectSms" : "Текстовые сообщения/SMS",
	"VRD_systemSelectStitcher" : "Stitcher",
	"VRD_systemSelectTV" : "ТВ",
	"VRD_systemSelectTrafficAlert" : "Контроль трафика",
	"VRD_systemSelectTutorial" : "Руководство",
	"VRD_systemSelectUSB" : "USB",
	"VRD_systemSelectUSBA" : "USB 1",
	"VRD_systemSelectUSBB" : "USB 2",
	"VRD_systemSelectXmAudio" : "Радио SXM",
	"VRD_tvSelectView" : "Просмотр",
	"VRD_usbaudioBrowse" : "Найти",
	"VRD_usbaudioBrowseAlbum" : "Найти {albumName}",
	"VRD_usbaudioBrowseAlbums" : "Найти альбом",
	"VRD_usbaudioBrowseAll" : "Найти все песни, альбомы или исполнителей",
	"VRD_usbaudioBrowseAnyAlbum" : "Найти [альбом] {albumName}",
	"VRD_usbaudioBrowseAnyArtist" : "Найти [исполнителя] {artistName}",
	"VRD_usbaudioBrowseAnyFolder" : "Найти папку {folderName}",
	"VRD_usbaudioBrowseArtist" : "Найти {artistName}",
	"VRD_usbaudioBrowseArtists" : "Найти исполнителя",
	"VRD_usbaudioBrowseAudiobooks" : "Найти аудиокниги",
	"VRD_usbaudioBrowseFolder" : "Найти {folderName}",
	"VRD_usbaudioBrowseFolders" : "Найти папку",
	"VRD_usbaudioBrowseGenre" : "Найти [жанр] {genreName}",
	"VRD_usbaudioBrowseGenres" : "Найти жанр",
	"VRD_usbaudioBrowseLineNumber" : "Найти строку {lineNumber}",
	"VRD_usbaudioBrowsePlaylist" : "Найти список воспроизведения {playlistName}",
	"VRD_usbaudioBrowsePlaylists" : "Найти список воспроизведения",
	"VRD_usbaudioBrowsePodcast" : "Найти подкаст {podcastName}",
	"VRD_usbaudioBrowsePodcasts" : "Найти подкасты",
	"VRD_usbaudioBrowseSongs" : "Найти песню",
	"VRD_usbaudioChooseAlbumArtist" : "{artistName}",
	"VRD_usbaudioGenerateMoreLikeThis" : "More Like This",
	"VRD_usbaudioPlayAlbums" : "Воспроизвести альбом",
	"VRD_usbaudioPlayAll" : "Воспроизвести все",
	"VRD_usbaudioPlayAnyAlbum" : "Воспроизвести [альбом] {albumName}",
	"VRD_usbaudioPlayAnyArtist" : "Воспроизвести [исполнителя] {artistName}",
	"VRD_usbaudioPlayAnyFolder" : "Воспроизвести папку {folderName}",
	"VRD_usbaudioPlayArtistAlbum" : "Воспроизвести {artistName} {albumName}",
	"VRD_usbaudioPlayArtists" : "Воспроизвести исполнителя",
	"VRD_usbaudioPlayAudiobook" : "Воспроизвести аудиокнигу {AudiobookName}",
	"VRD_usbaudioPlayAudiobooks" : "Воспроизвести аудиокниги",
	"VRD_usbaudioPlayChapter" : "{chapterName}",
	"VRD_usbaudioPlayChapterIndex" : "Воспроизвести главу {index} {chapter}",
	"VRD_usbaudioPlayEpisode" : "{episodeName}",
	"VRD_usbaudioPlayFolder" : "Воспроизвести {folderName}",
	"VRD_usbaudioPlayFolders" : "Воспроизвести папку",
	"VRD_usbaudioPlayGenre" : "Воспроизвести [жанр] {genreName}",
	"VRD_usbaudioPlayGenres" : "Воспроизвести жанр",
	"VRD_usbaudioPlayLineNumber" : "Воспроизвести [строку] {lineNumber}",
	"VRD_usbaudioPlayPlaylist" : "Воспроизвести список воспроизведения {playlistName}",
	"VRD_usbaudioPlayPlaylists" : "Воспроизвести список воспроизведения",
	"VRD_usbaudioPlayPodcast" : "Воспроизвести подкаст {PodcastName}",
	"VRD_usbaudioPlayPodcasts" : "Воспроизвести подкасты",
	"VRD_usbaudioPlaySongs" : "Воспроизвести песню",
	"VRD_usbaudioRepeat" : "Повторить",
	"VRD_usbaudioRepeatAll" : "Повторить все",
	"VRD_usbaudioRepeatOff" : "повторить выключить",
	"VRD_usbaudioRepeatSong" : "Повторить песню",
	"VRD_usbaudioRewind" : "Перемотка",
	"VRD_usbaudioSelectAlbum" : "Альбом {albumName}",
	"VRD_usbaudioSelectAlbums" : "Альбом",
	"VRD_usbaudioSelectAll" : "Все эпизоды, главы, песни, альбомы или исполнители",
	"VRD_usbaudioSelectArtist" : "Исполнитель {artistName}",
	"VRD_usbaudioSelectArtists" : "Исполнитель",
	"VRD_usbaudioSelectAudiobook" : "{audiobookName}",
	"VRD_usbaudioSelectAudiobooks" : "Аудиокниги",
	"VRD_usbaudioSelectFolder" : "Папка {folderName}",
	"VRD_usbaudioSelectFolders" : "Папки",
	"VRD_usbaudioSelectGenre" : "Жанр {genreName}",
	"VRD_usbaudioSelectGenres" : "Жанр",
	"VRD_usbaudioSelectPlaylist" : "Список воспроизведения {playlistName}",
	"VRD_usbaudioSelectPlaylists" : "Список воспроизвведения",
	"VRD_usbaudioSelectPodcast" : "{podcastName}",
	"VRD_usbaudioSelectPodcasts" : "Подкаст",
	"VRD_usbaudioSelectRootFolder" : "Корневое меню",
	"VRD_usbaudioSelectSettings" : "Настройки звука",
	"VRD_usbaudioSelectSongs" : "Песня",
	"VRD_usbaudioSelectSourceMenu" : "Развлечения",
	"VRD_usbaudioShuffle" : "В случайном порядке",
	"VRD_usbaudioShuffleOff" : "Отключить случайный выбор",
	"VRD_usbaudioShuffleOn" : "Включить случайный выбор",
	"VRD_usbaudioSongList" : "Список песен",
	"VRD_xmaudioBackSpaceDelete" : "Удалить цифры",
	"VRD_xmaudioChangeLockCode" : "Редактировать ПИН-код",
	"VRD_xmaudioConfirmDelete" : "Удалить",
	"VRD_xmaudioEnterPIN" : "{fourDigitPIN}",
	"VRD_xmaudioPlayChannelName" : "Воспроизвести канал XM {channelName}",
	"VRD_xmaudioPlayStationNumber" : "Настроить на {channelNumber}",
	"VRD_xmaudioResetLockCode" : "Сбросить пин-код",
	"VRD_xmaudioSelectCallXM" : "Вызов ХМ",
	"VRD_xmaudioSelectChangeCategory" : "Изменить категорию",
	"VRD_xmaudioSelectContinueListening" : "Продолжить прослушивание",
	"VRD_xmaudioSelectDismiss" : "Отменить",
	"VRD_xmaudioSelectEveryOccurance" : "Каждое повторение",
	"VRD_xmaudioSelectEveryOtherReport" : "Каждый второй отчет",
	"VRD_xmaudioSelectEveryReport" : "Каждый отчет",
	"VRD_xmaudioSelectExitTuneMix" : "Выйти из TuneMix",
	"VRD_xmaudioSelectFavorites" : "Избранное",
	"VRD_xmaudioSelectListenNow" : "Слушать сейчас",
	"VRD_xmaudioSelectMove" : "Переместить",
	"VRD_xmaudioSelectNearestCity" : "Ближайший город",
	"VRD_xmaudioSelectOnlyFirstAfterVehicleStart" : "Запуск автомобиля",
	"VRD_xmaudioSelectOnlyFirstOccuranceInGame" : "Первый раз",
	"VRD_xmaudioSelectReplayAlert" : "Повторить предупреждение",
	"VRD_xmaudioSelectReturnToPrevious" : "Вернуться к предыдущему",
	"VRD_xmaudioSelectSFSportBaseball" : "Бейсбол",
	"VRD_xmaudioSelectSFSportNCAA" : "Университетский американский футбол",
	"VRD_xmaudioSelectSFSportNFL" : "Профессиональный американский футбол",
	"VRD_xmaudioSelectSFSportNHL" : "Хоккей",
	"VRD_xmaudioSelectScanOff" : "Сканировать Выкл.",
	"VRD_xmaudioSelectScanOn" : "Сканировать Вкл.",
	"VRD_xmaudioSelectSettings" : "Настройки",
	"VRD_xmaudioSelectSoundSettings" : "Настройки звука",
	"VRD_xmaudioSelectSource" : "Развлечения",
	"VRD_xmaudioSelectStation" : "Станция {channelNumber}",
	"VRD_xmaudioSelectStationAll" : "Все каналы",
	"VRD_xmaudioSelectStationCategory" : "{categoryName}",
	"VRD_xmaudioSelectStationFeaturedFavorites" : "Популярное избранное",
	"VRD_xmaudioSelectStationList" : "Каналы",
	"VRD_xmaudioSelectTuneMix" : "TuneMix",
	"VRD_xmaudioSelectTuneMixChannel" : "Параметры канала TuneMix",
	"VRD_xmaudioSelectTuneMixChannelsOptions" : "Параметры канала",
	"VRD_xmaudioSelectTuneMixCreation" : "Создать новый канал TuneMix",
	"VRD_xmaudioSelectTuneMixEdit" : "Редактировать канал TuneMix",
	"VRD_xmaudioSelectTuneMixEditOps" : "Параметры редактирования TuneMix",
	"VRD_xmaudioSelectTuneMixRemove" : "Удалить канал TuneMix",
	"VRD_xmaudioSelectTuneMixRename" : "Переименовать TuneMix",
	"VRD_xmaudioSelectTurnAlertsOff" : "Выключить предупреждения",
	"VRD_xmaudioSelectiTunesTagging" : "Тегирование iTunes",
	"VRD_xmaudioSetChannelLock" : "Заблокировать канал",
	"VRD_xmaudioSetParentalLock" : "Блокировка сеанса",
	"VRD_xmdataSelectFuelPrices" : "Цены на топливо",
	"VRD_xmdataSelectMovies" : "Фильмы",
	"VRD_xmdataSelectParking" : "Парковка",
	"VRD_xmdataSelectSports" : "Спорт",
	"VRD_xmdataSelectStock" : "Акции",
	"VRD_xmdataSelectTrafficPlus" : "Трафик плюс",
	"VRD_xmdataSelectWeatherForecast" : "Прогноз погоды",
	"VRD_xmdataSelectWeatherRadar" : "Погодный радар",
	"VRD_xmdataSelectWeatherSecurityAlerts" : "Предупреждения о погоде",
};

framework.registerAppDictLoaded("system", "ru_RU");