var __VrHelpPositionTable__systemAppDict_it_IT = {
	"HomeScreen_Help" : {
		"Right" : ["VrHelp_Favorites"],
		"Left" : ["VrHelp_Entertainment","VrHelp_Communication","VrHelp_Navigation","VrHelp_Settings","VrHelp_Applications"]
	}
};

var Localization_systemAppDict_it_IT = {
	//"stringId" : "localString"
	"ActiveCallItem" : "Chiamata attiva",
	"AhaMaintError" : "Errore manutenzione aha.",
	"AhaRadio" : "aha",
	"AmRadio" : "AM",
	"AndroidAuto" : "Android Auto",
	"Applications" : "Applicazioni",
	"AudioSourceNotAvailableBTAudio" : "Audio Bluetooth non disponibile.",
	"AudioSourceNotAvailableCD" : "Il CD è stato estratto.",
	"AudioSourceNotAvailableDVD" : "Il DVD è stato estratto.",
	"AudioSourceNotAvailableTV" : "TV Non Disponibile",
	"AudioSourceNotAvailableUSB" : "Il dispositivo USB è cambiato",
	"AuxIn" : "AUX",
	"BT" : "BT",
	"Bluetooth" : "Bluetooth",
	"BluetoothWithDevice" : "Bluetooth - {deviceName}",
	"CallHistory" : "Registro chiamate",
	"CarPlay" : "Apple CarPlay",
	"CdPlayer" : "CD",
	"ChannelOffAir" : "Canale chiuso",
	"ChannelUnauth" : "Canale non autorizzato",
	"CheckAntenna" : "Controlla antenna",
	"CheckTuner" : "Controlla Tuner",
	"Communication" : "Comunicazione",
	"Connect" : "Connetti",
	"Contacts" : "Contatti",
	"DVDItem" : "DVD",
	"DabRadio" : "DAB",
	"DialPhone" : "Telefono con tastiera",
	"DidYouSay" : "Ha detto. . .",
	"DisclaimerText" : "La distrazione può causare incidenti. Non fare niente mentre si guida. Rimanere concentrati sulla guida e rispettare le norme stradali. Leggere il manuale di istruzioni.",
	"DisconnectThenReconnect" : "Disconnettere quindi riconnettere Apple Device",
	"DriveRecord" : "Archivio di guida",
	"DriverIDItem" : "Selezione conducente",
	"EcoenergyApp" : "Consumo carburante",
	"EcoenergyAppHEV" : "Monitor di guida",
	"Email" : "Email",
	"EngineOilLevel" : "Livello dell’olio motore",
	"Entertainment" : "Intrattenimento",
	"ErrorWhileStartingSiri" : "Errore durante l'avvio di Siri.",
	"FailedNotificationRetrieval" : "Impossibile recuperare l'elenco notifiche.",
	"FavoritesItem" : "Preferiti",
	"FmRadio" : "FM",
	"HDTrafficItem" : "Informazioni sul traffico Radio HD",
	"InitiateSiri" : "Premere a lungo il pulsante conversazione per avviare la sessione di Siri",
	"IntelligentDriveMasterItem" : "i-DM",
	"NavigationTitle" : "Navigazione",
	"NoConnectionNotifyText" : "Connettere un telefono ora?",
	"NoConnectionNotifyTitle" : "Nessun telefono connesso.",
	"NoDeviceText" : "Connettere il dispositivo ora?",
	"NoDeviceTitle" : "Nessun dispositivo connesso.",
	"Notifications" : "Notifiche",
	"NotifyIgnore" : "Ignora",
	"NotifyIncomingMsg" : "Messaggio in arrivo da:",
	"NotifyOff" : "Notifiche off",
	"NotifyRead" : "Leggi",
	"NotifyReadNow" : "Leggere ora?",
	"Pandora" : "Pandora",
	"ReconnectAhaRadio" : "Riconnes audio Bluetooth per Radio aha",
	"ReconnectBTAudio" : "Riconnes audio Bluetooth per riprod",
	"ReconnectCD" : "Verifica Cd per ripristino riproduzione",
	"ReconnectCarPlay" : "Riavvio di Apple CarPlay.",
	"ReconnectDVD" : "Verifica DVD per ripristino riproduzione",
	"ReconnectEntMenuButton" : "Menu intrattenimento",
	"ReconnectFailedBTAudio" : "Impossibile connettere di nuovo l'audio Bluetooth.",
	"ReconnectFailedCD" : "Il cd è stato estratto. Impossibile ripristinare la riproduzione.",
	"ReconnectFailedCarPlay" : "Impossibile ricollegare Apple CarPlay",
	"ReconnectFailedDVD" : "Il DVD è stato estratto. Impossibile ripristinare la riproduzione.",
	"ReconnectFailedTV" : "TV Non Disponibile. Non in grado di riprendere la riproduzione.",
	"ReconnectFailedUSB" : "Il dispositivo USB è cambiato. Impossibile ripristinare la riproduzione.",
	"ReconnectPandora" : "Riconnes audio Bluetooth per Pandora",
	"ReconnectStitcher" : "Riconnes audio Bluetooth per Stitcher",
	"ReconnectTV" : "Verifica TV per riprendere la riproduzione",
	"ReconnectUSB" : "Riconnes dispositivo USB per riproduzione",
	"RetryLabel" : "Riprova",
	"SchedMaintenanceApp" : "Manutenzione",
	"ScreenReplication" : "Replica schermata",
	"SdarsRadio" : "XM",
	"Settings" : "Impostazioni",
	"SettingsCommunication" : "Impostazioni",
	"Siri" : "Siri",
	"SiriDisabled" : "Siri è disabilitato sul disp. Apple.",
	"Sms" : "SMS",
	"StitcherItem" : "Stitcher",
	"TVItem" : "TV",
	"TempWarning" : "Avviso temperatura",
	"TempWarningText" : "Surriscaldamento display. La prestazione dello schermo potrebbe diminuire fin quando non si raffredda.",
	"TextDownloaded" : "SMS scaricato",
	"TextSent" : "SMS inviato",
	"TrafficAlertsItem" : "Informazioni sul traffico",
	"USB" : "USB",
	"USB1AndroidAuto" : "USB 1 - Android Auto",
	"USB1CarPlay" : "USB 1 - Apple CarPlay",
	"USB2AndroidAuto" : "USB 2 - Android Auto",
	"UsbAudioA" : "USB 1",
	"UsbAudioAWithDevice" : "USB 1 - {deviceName}",
	"UsbAudioB" : "USB 2",
	"UsbAudioBWithDevice" : "USB 2 - {deviceName}",
	"UseCommander" : "Utilizza il commander durante la guida.",
	"VehicleDataTransferItem" : "Trasferimento dati veicolo ",
	"VehicleStatusMonitor" : "Monitor stato veicolo",
	"VehicleTelemetryTransfer" : "Trasferimento telemetria del veicolo",
	"VideoSignalLost" : "Segnale video perso",
	"VoiceNotSupported" : "Voce non supportata. ",
	"VoiceRecognition" : "Riconoscimento vocale",
	"VrHelp_Applications" : "Applicazioni",
	"VrHelp_Communication" : "Comunicazione",
	"VrHelp_Entertainment" : "Intrattenimento",
	"VrHelp_Favorites" : "Preferiti",
	"VrHelp_Navigation" : "Navigazione",
	"VrHelp_Settings" : "Impostazioni",
	"WarnGuidanceApp" : "Avvisi di guida",
	"WarningTitle" : "ATTENZIONE!",
	"XMAudio" : "SXM",
	"XMData" : "SXM Services",
	"agree" : "Accetto",
	"VRD_aharadioSelectCall" : "Chiama",
	"VRD_aharadioSelectDiscard" : "Elimina",
	"VRD_aharadioSelectEpisodes" : "Elenco episodi",
	"VRD_aharadioSelectLBSTab" : "Nelle vicinanze",
	"VRD_aharadioSelectMainList" : "Elenco principale Aha",
	"VRD_aharadioSelectMap" : "Mappa",
	"VRD_aharadioSelectPresetsTab" : "Predefinito",
	"VRD_aharadioSelectSave" : "Salva",
	"VRD_aharadioSelectSettings" : "Impostazioni audio",
	"VRD_aharadioSelectShout" : "Post vocale",
	"VRD_aharadioSelectSource" : "Intrattenimento/Cambia sorgente",
	"VRD_aharadioSelectThumbsDown" : "Non mi piace",
	"VRD_aharadioSelectThumbsUp" : "Mi piace",
	"VRD_amradioPlayStationFrequency" : "Sintonizza su {frequency} AM",
	"VRD_amradioSelectAutoMemory" : "Memoria automatica",
	"VRD_amradioSelectFavorites" : "Preferiti",
	"VRD_amradioSelectHD" : "Stazioni HD",
	"VRD_amradioSelectHDOff" : "HD Radio spento ",
	"VRD_amradioSelectHDOn" : "HD Radio acceso ",
	"VRD_amradioSelectScanOff" : "Spegni scansione",
	"VRD_amradioSelectScanOn" : "Accendi scansione",
	"VRD_amradioSelectSeekNext" : "Cerca successivo",
	"VRD_amradioSelectSeekPrevious" : "Cerca precedente",
	"VRD_amradioSelectSettings" : "Impostazioni audio",
	"VRD_amradioSelectSource" : "Vai su Menu intrattenimento",
	"VRD_amradioSelectStationFrequency" : "{AMFrequency}",
	"VRD_amradioSelectTrafficAlert" : "Avviso traffico",
	"VRD_amradioSelectTrafficAlertOff" : "Avviso traffico disattivato",
	"VRD_amradioSelectTrafficAlertOn" : "Avviso traffico attivato",
	"VRD_amradioSelectTune" : "Sintonizza",
	"VRD_amradioSelectUpdateAutoMemory" : "Ricerca memoria automatica",
	"VRD_amradioSelectiTunesTagging" : "Tag iTunes",
	"VRD_amradioTuneDown" : "Sintonizza avanti",
	"VRD_amradioTuneUp" : "Sintonizza indietro",
	"VRD_amradioUpdateAutoMemory" : "Aggiorna elenco stazioni",
	"VRD_auxinSelectSettings" : "Impostazioni audio",
	"VRD_auxinSelectSource" : "Intrattenimento/Cambia sorgente",
	"VRD_btaudioScanPlay" : "Esecuzione scan",
	"VRD_btaudioSelectConnect" : "Connetti",
	"VRD_btaudioSelectRootMenu" : "Menu principale",
	"VRD_btaudioSelectSettings" : "Impostazioni audio",
	"VRD_btaudioSelectSource" : "Vai su Menu intrattenimento",
	"VRD_btaudioToggleRepeat" : "Ripeti",
	"VRD_btaudioToggleShuffle" : "Riproduzione casuale",
	"VRD_carplaySelectApplications" : "Applicazioni",
	"VRD_cdGoSettings" : "Impostazioni audio",
	"VRD_cdHandleStartScan" : "Avvia scansione",
	"VRD_cdPlayBeginning" : "Riprendi dall'inizio",
	"VRD_cdRepeatFolder" : "Ripeti cartella",
	"VRD_cdRepeatOff" : "Ripetizione disattivata",
	"VRD_cdRepeatOn" : "Ripetizione attivata",
	"VRD_cdRepeatTrack" : "Ripeti traccia",
	"VRD_cdSelectCurrentFolder" : "Cartella attuale",
	"VRD_cdSelectRepeat" : "Ripeti",
	"VRD_cdSelectRootFolder" : "Menu principale",
	"VRD_cdSelectShuffle" : "Riproduzione casuale",
	"VRD_cdSelectSource" : "Vai su Menu intrattenimento",
	"VRD_cdSelectTrackList" : "Elenco tracce",
	"VRD_cdSelectTrackNumber" : "Traccia in riproduzione {Number}",
	"VRD_cdShuffleDisk" : "Attiva riproduzione casuale disco",
	"VRD_cdShuffleFolder" : "Riproduzione casuale cartella",
	"VRD_cdShuffleOff" : "Riproduzione casuale disattivata",
	"VRD_cdShuffleOn" : "Riproduzione casuale attivata",
	"VRD_commonAddToFavorites" : "Aggiungi a preferiti",
	"VRD_commonCancel" : "Annulla",
	"VRD_commonFastForward" : "Avanti",
	"VRD_commonGoBack" : "Torna indietro",
	"VRD_commonIntentParent" : "Principale",
	"VRD_commonIntentParentUSBAudio" : "Principale",
	"VRD_commonIntentUSBAudio" : "Casa",
	"VRD_commonIntentUSBAudioBG" : "Casa",
	"VRD_commonMenuUp" : "Menu avanti",
	"VRD_commonNext" : "Successivo",
	"VRD_commonNo" : "No",
	"VRD_commonPageDown" : "Pagina giù/Scorri verso il basso",
	"VRD_commonPageUp" : "Pagina su/Scorri verso l'alto",
	"VRD_commonPause" : "Pausa",
	"VRD_commonPrevious" : "Precedente",
	"VRD_commonResume" : "Riproduci/Continua",
	"VRD_commonRewind" : "Rewind",
	"VRD_commonSelectLineNumber" : "Linea {lineNumber}",
	"VRD_commonYes" : "Sì/OK",
	"VRD_contactsChooseContactName" : "{ContactName}",
	"VRD_contactsDisambiguateContactName" : "Mostra {ContactName}",
	"VRD_contactsImportAll" : "Importa tutti i contatti",
	"VRD_contactsImportCancel" : "Annulla imp.",
	"VRD_contactsImportContacts" : "Modifica contatti",
	"VRD_contactsImportSingle" : "Importa contatto selezionato",
	"VRD_contactsRemoveContact" : "Elimina contatto",
	"VRD_contactsSelectCall" : "Chiama",
	"VRD_contactsSelectContactName" : "{ContactName}",
	"VRD_contactsSelectDownload" : "Scarica",
	"VRD_contactsSelectFavorites" : "Preferiti",
	"VRD_contactsSelectNone" : "Nessuno di questi",
	"VRD_contactsSelectReadContactName" : "Leggi nome contatto",
	"VRD_contactsSelectRemove" : "Elimina",
	"VRD_contactsSelectRetry" : "Riprova",
	"VRD_contactsSendPhoneType" : "{phoneType}",
	"VRD_contactsShowAddress" : "Indirizzo",
	"VRD_dabDisplayDABSettings" : "Impostazioni DAB",
	"VRD_dabDisplayEnsembleList" : "Seleziona esecuzione",
	"VRD_dabDisplayStationList" : "Elenco stazioni",
	"VRD_dabSelectFavorites" : "Preferiti",
	"VRD_dabSelectScan" : "Scansione",
	"VRD_dabSelectSeekNext" : "Successivo",
	"VRD_dabSelectSeekPrevious" : "Precedente",
	"VRD_dabSelectSettings" : "Impostazioni audio",
	"VRD_dabSelectSource" : "Intrattenimento",
	"VRD_dabTAToggleOFF" : "Traffico disattivato",
	"VRD_dabTAToggleON" : "Traffico attivato",
	"VRD_dabTAToggleVois" : "Annuncio sul traffico (TA)",
	"VRD_dabUpdateStationList" : "Aggiorna elenco",
	"VRD_dvdClearPin" : "Elimina cifre",
	"VRD_dvdSayGRating" : "G",
	"VRD_dvdSayPG12" : "Minori di 12 anni",
	"VRD_dvdSayR15" : "R 15 plus",
	"VRD_dvdSayR18" : "--",
	"VRD_dvdSelectAspectRatio" : "Proporzioni schermo",
	"VRD_dvdSelectAudioSettings" : "Impostazioni video",
	"VRD_dvdSelectCameraAngle" : "Angolazione telecamera",
	"VRD_dvdSelectEditPin" : "Modifica codice PIN",
	"VRD_dvdSelectParentLock" : "Controllo genitori",
	"VRD_dvdSelectParentLockOff" : "Spegni controllo genitori",
	"VRD_dvdSelectParentLockOn" : "Accendi controllo genitori",
	"VRD_dvdSelectParentLockRating" : "Categoria controllo genitori",
	"VRD_dvdSelectResetPin" : "Resetta Codice PIN",
	"VRD_dvdSelectRootMenu" : "Menu principale",
	"VRD_dvdSelectSettings" : "Impostazioni audio",
	"VRD_dvdSelectSource" : "Intrattenimento",
	"VRD_dvdSelectSubtitleOff" : "Sottotitoli disattivati",
	"VRD_dvdSelectSubtitleOn" : "Sottotitoli attivati",
	"VRD_dvdSlowForward" : "Avanti",
	"VRD_dvdSlowRewind" : "Rewind",
	"VRD_dvdVUISendPin" : "{FourDigitPin}",
	"VRD_emailSelectAllAccounts" : "Tutti gli account",
	"VRD_emailSelectCall" : "Chiama",
	"VRD_emailSelectContactName" : "{ContactName}",
	"VRD_emailSelectContinueEmail" : "Continua e-mail",
	"VRD_emailSelectDelete" : "Elimina",
	"VRD_emailSelectDiscard" : "Elimina",
	"VRD_emailSelectImportEmail" : "Aggiorna messaggi in arrivo",
	"VRD_emailSelectInbox" : "E-mail in arrivo",
	"VRD_emailSelectInboxSelector" : "Messaggi in arrivo",
	"VRD_emailSelectMessage" : "Aggiungi messaggio",
	"VRD_emailSelectNone" : "Nessuno di questi",
	"VRD_emailSelectReply" : "Rispondi",
	"VRD_emailSelectReplyAll" : "Rispondi a tutti",
	"VRD_emailSelectRetry" : "Riprova",
	"VRD_emailSelectReturn" : "Ritorna",
	"VRD_emailSelectSend" : "Invia",
	"VRD_emailSelectSenderName" : "{senderName}",
	"VRD_emnaviAcceptAvoidance" : "Conferma",
	"VRD_emnaviAddCurrentPosToFavourites" : "Aggiungi posizione attuale a Preferiti",
	"VRD_emnaviAddWaypointCityCenter" : "Aggiungi Waypoint centro città",
	"VRD_emnaviAddWaypointDistrictCenter" : "Aggiungi waypoint centro quartiere",
	"VRD_emnaviAddWaypointFavorite" : "Aggiungi waypoint preferiti",
	"VRD_emnaviAddWaypointPOI" : "Aggiungi waypoint {poiHypList}",
	"VRD_emnaviAvoidRouteAhead" : "Evita percorso davanti",
	"VRD_emnaviCancelRoute" : "Annulla percorso",
	"VRD_emnaviDecreaseAvoidanceLength" : "Meno",
	"VRD_emnaviGoToCockpit" : "Inizia",
	"VRD_emnaviIncreaseAvoidanceLength" : "Più",
	"VRD_emnaviJPJ_VDEHypothesisList" : "Un nome città",
	"VRD_emnaviNavigateHere" : "Naviga qui",
	"VRD_emnaviNavigateHome" : "Naviga verso casa",
	"VRD_emnaviNavigateToARecentDestination" : "Naviga verso una destinazione recente",
	"VRD_emnaviNavigateToAddress" : "Naviga verso un indirizzo",
	"VRD_emnaviNavigateToCityCenter" : "Naviga verso il centro città",
	"VRD_emnaviNavigateToDistrictCenter" : "Naviga verso il centro del quartiere",
	"VRD_emnaviNavigateToFavorite" : "Naviga verso preferito",
	"VRD_emnaviNavigateToPOI" : "Naviga verso {poiHypList}",
	"VRD_emnaviNewDestination" : "Nuova destinazione",
	"VRD_emnaviRepeatInstruction" : "Ripeti istruzione",
	"VRD_emnaviRouteSummary" : "Riassunto percorso",
	"VRD_emnaviSelectCancelRoute" : "Annulla percorso",
	"VRD_emnaviSelectNavigateToAddress" : "Naviga verso un indirizzo",
	"VRD_emnaviSimpleHypothesisList" : "Un nome stato",
	"VRD_emnaviStepByStep" : "Inserimento passo dopo passo",
	"VRD_emnaviTravelViaARecentDestination" : "Aggiungi waypoint destinazione recente",
	"VRD_emnaviTravelViaAddress" : "Viaggia seguendo l'indirizzo",
	"VRD_emnaviTravelViaHome" : "Viaggia seguendo casa",
	"VRD_emnaviTryAgain" : "Riprova",
	"VRD_emnaviUniSimpleHypothesisList" : "Un indirizzo",
	"VRD_emnaviUniVDEHypothesisList" : "Un indirizzo",
	"VRD_emnaviVDEHypothesisList" : "Un indirizzo",
	"VRD_emnaviWhereAmI" : "Dove sono",
	"VRD_emnaviZoomIn" : "Ingrandisci",
	"VRD_emnaviZoomOut" : "Rimpicciolisci",
	"VRD_fmradioPlayStationFrequency" : "Sintonizza su {frequency} FM",
	"VRD_fmradioSelectAutoMemory" : "Memoria automatica",
	"VRD_fmradioSelectChangeGenre" : "Cambia genere",
	"VRD_fmradioSelectFMSettings" : "Impostazioni FM",
	"VRD_fmradioSelectFavorites" : "Preferiti",
	"VRD_fmradioSelectGenreSeek" : "Ricerca genere",
	"VRD_fmradioSelectHDChannel" : "{HD Channel}",
	"VRD_fmradioSelectHDChannels" : "Stazioni HD",
	"VRD_fmradioSelectHDRadio" : "Radio HD",
	"VRD_fmradioSelectHDRadioOff" : "Radio HD spenta ",
	"VRD_fmradioSelectHDRadioOn" : "Radio HD accesa ",
	"VRD_fmradioSelectScanOff" : "Spegni scansione",
	"VRD_fmradioSelectScanOn" : "Accendi scansione",
	"VRD_fmradioSelectSeekNext" : "Cerca successivo",
	"VRD_fmradioSelectSeekPrevious" : "Cerca precedente",
	"VRD_fmradioSelectSettings" : "Impostazioni audio",
	"VRD_fmradioSelectSource" : "Intrattenimento/Cambia sorgente",
	"VRD_fmradioSelectStationAll" : "Tutte le stazioni",
	"VRD_fmradioSelectStationFrequency" : "{frequency}",
	"VRD_fmradioSelectStationGenre" : "{genreName}",
	"VRD_fmradioSelectStationList" : "Elenco stazioni",
	"VRD_fmradioSelectStationName" : "{stationName}",
	"VRD_fmradioSelectTrafficAlert" : "Annuncio sul traffico (TA)",
	"VRD_fmradioSelectTrafficAlertOff" : "Traffico disattivato",
	"VRD_fmradioSelectTrafficAlertOn" : "Traffico attivato",
	"VRD_fmradioSelectTune" : "Sintonizza",
	"VRD_fmradioSelectUpdateAutoMemory" : "Aggiorna memoria automatica",
	"VRD_fmradioSelectiTunesTagging" : "Tag iTunes",
	"VRD_fmradioTuneDown" : "Sintonizza avanti",
	"VRD_fmradioTuneUp" : "Sintonizza indietro",
	"VRD_fmradioTurnOffAF" : "Frequenza alternativa spenta",
	"VRD_fmradioTurnOffREG" : "Blocco territoriale spento",
	"VRD_fmradioTurnOnAF" : "Frequenza alternativa accesa",
	"VRD_fmradioTurnOnREG" : "Blocco territoriale acceso",
	"VRD_fmradioUpdateAutoMemory" : "Aggiorna elenco stazioni",
	"VRD_pandoraAddStation" : "Aggiungi stazione",
	"VRD_pandoraAddStationFromArtist" : "Crea stazione da artista",
	"VRD_pandoraAddStationFromSong" : "Crea stazione da canzone",
	"VRD_pandoraAddToFavorites" : "Aggiungi a preferiti",
	"VRD_pandoraBookmarkArtist" : "Metti segnalibro ad artista",
	"VRD_pandoraBookmarkSong" : "Metti segnalibro alla canzone",
	"VRD_pandoraCreateStation" : "Crea stazione",
	"VRD_pandoraSelectAddCurrentStation" : "Aggiungi",
	"VRD_pandoraSelectDelete" : "Elimina",
	"VRD_pandoraSelectEditDelete" : "Elimina",
	"VRD_pandoraSelectEditMove" : "Sposta",
	"VRD_pandoraSelectEditReplace" : "Sostituisci",
	"VRD_pandoraSelectFavorites" : "Preferiti",
	"VRD_pandoraSelectMove" : "Sposta",
	"VRD_pandoraSelectQuickMix" : "Riproduzione casuale",
	"VRD_pandoraSelectSettings" : "Impostazioni audio",
	"VRD_pandoraSelectSortBy" : "Ordina",
	"VRD_pandoraSelectSource" : "Intrattenimento",
	"VRD_pandoraSelectStationList" : "Elenco stazioni",
	"VRD_pandoraShowBookmarkOptions" : "Segnalibro",
	"VRD_pandoraShowByAZ" : "Ordina alfabeticamente",
	"VRD_pandoraShowByDate" : "Ordina per data",
	"VRD_pandoraSkip" : "Salta",
	"VRD_pandoraThumbsDown" : "Non mi piace",
	"VRD_pandoraThumbsUp" : "Mi piace",
	"VRD_phoneCall" : "Chiama",
	"VRD_phoneCallBack" : "Richiama",
	"VRD_phoneCallByName" : "Chiama per nome",
	"VRD_phoneCallByNumber" : "Chiama per numero",
	"VRD_phoneCallContactType" : "Chiama {contactName} {contactType}",
	"VRD_phoneCallLast" : "Chiama ultimo numero",
	"VRD_phoneChooseContactType" : "{contactName} {contactType}",
	"VRD_phoneDialAnyNumber" : "Chiama {number}",
	"VRD_phoneDialpadClearAllDigits" : "Cancella tutte le cifre",
	"VRD_phoneDialpadDeleteDigit" : "Elimina",
	"VRD_phoneDialpadPhoneNumber" : "{phoneNumber}",
	"VRD_phoneReDial" : "Ricomponi",
	"VRD_phoneSelectByName" : "Nome",
	"VRD_phoneSelectByNumber" : "Numero",
	"VRD_phoneSelectContactType" : "{contactType}",
	"VRD_phoneSelectDialPad" : "Tastiera",
	"VRD_phoneSelectFavorites" : "Preferiti",
	"VRD_phoneSelectRecentCalls" : "Chiamate recenti",
	"VRD_phoneSelectRecentCallsAll" : "Tutte le chiamate",
	"VRD_phoneSelectRecentCallsMissed" : "Chiamate perse",
	"VRD_satradioBackSpaceDelete" : "Elimina cifre",
	"VRD_satradioChangeLockCode" : "Modifica codice PIN",
	"VRD_satradioEnterPIN" : "{4digitPin}",
	"VRD_satradioInitializeLockCode" : "Inizializza codice PIN",
	"VRD_satradioPlayChannelName" : "Riproduci {channelName}",
	"VRD_satradioPlayStationNumber" : "Sintonizza su {channelNumber}",
	"VRD_satradioResetLockCode" : "Resetta Codice PIN",
	"VRD_satradioSeekNext" : "Cerca successivo",
	"VRD_satradioSeekPrevious" : "Cerca precedente",
	"VRD_satradioSelectChangeCategory" : "Categoria",
	"VRD_satradioSelectFavorites" : "Preferiti",
	"VRD_satradioSelectParentalLock" : "Controllo genitori",
	"VRD_satradioSelectScanOff" : "Spegni scansione",
	"VRD_satradioSelectScanOn" : "Accendi scansione",
	"VRD_satradioSelectSettings" : "Impostazioni audio",
	"VRD_satradioSelectSource" : "Intrattenimento",
	"VRD_satradioSelectStation" : "Stazione {Station number}",
	"VRD_satradioSelectStationAll" : "Tutti i canali",
	"VRD_satradioSelectStationCategory" : "{categoryName}",
	"VRD_satradioSelectStationList" : "Elenco canali",
	"VRD_satradioTurnChannelLockOFF" : "Sblocca canale attuale",
	"VRD_satradioTurnChannelLockON" : "Blocca canale attuale",
	"VRD_satradioTurnParentalLockOFF" : "Spegni blocco sessione",
	"VRD_satradioTurnParentalLockON" : "Accendi blocco sessione",
	"VRD_smsCallPhoneNumber" : "Chiama",
	"VRD_smsDelete" : "Elimina",
	"VRD_smsImportMessages" : "Aggiorna messaggi di testo in arrivo",
	"VRD_smsReply" : "Rispondi",
	"VRD_smsSayAnyConversation" : "{senderName}",
	"VRD_smsSelectBody" : "Aggiungi messaggio",
	"VRD_smsSelectContactName" : "{ContactName}",
	"VRD_smsSelectContinueTextMessage" : "Continua messaggio",
	"VRD_smsSelectDiscard" : "Elimina",
	"VRD_smsSelectInbox" : "Elenco SMS in arrivo",
	"VRD_smsSelectNone" : "Nessuno di questi",
	"VRD_smsSelectRetry" : "Riprova",
	"VRD_smsSelectReturn" : "Ritorna",
	"VRD_smsSelectSend" : "Invia",
	"VRD_stitcherAddToFavorites" : "Aggiungi a preferiti",
	"VRD_stitcherRemoveFromFavorites" : "Elimina da preferiti",
	"VRD_stitcherSaveFavorites" : "Salva modifiche",
	"VRD_stitcherSelectSettings" : "Impostazioni audio",
	"VRD_stitcherSelectSource" : "Intrattenimento",
	"VRD_stitcherSelectStationList" : "Elenco stazioni",
	"VRD_stitcherThumbsDown" : "Non mi piace",
	"VRD_stitcherThumbsUp" : "Mi piace",
	"VRD_systemSelectAhaRadio" : "Radio Aha",
	"VRD_systemSelectAndroidAuto" : "Android Auto",
	"VRD_systemSelectApplications" : "Applicazioni",
	"VRD_systemSelectAuxIn" : "Line In / AUX",
	"VRD_systemSelectBTAudio" : "Bluetooth",
	"VRD_systemSelectCD" : "CD",
	"VRD_systemSelectCallHistory" : "Registro chiamate",
	"VRD_systemSelectCarPlay" : "Car Play",
	"VRD_systemSelectCommunication" : "Comunicazione",
	"VRD_systemSelectConnect" : "Connetti",
	"VRD_systemSelectContacts" : "Contatti",
	"VRD_systemSelectDAB" : "DAB",
	"VRD_systemSelectDVD" : "DVD",
	"VRD_systemSelectDisplayClock" : "Display orologio",
	"VRD_systemSelectDisplayOff" : "Spegni display",
	"VRD_systemSelectEmail" : "E-mail",
	"VRD_systemSelectEntertainment" : "Intrattenimento",
	"VRD_systemSelectEntertainmentMenu" : "Menu intrattenimento",
	"VRD_systemSelectFavorites" : "Preferiti",
	"VRD_systemSelectNavigation" : "Navigazione",
	"VRD_systemSelectNotifications" : "Messaggi",
	"VRD_systemSelectNotifyOff" : "Notifiche off",
	"VRD_systemSelectPandora" : "Pandora",
	"VRD_systemSelectPhone" : "Telefono",
	"VRD_systemSelectRadioAM" : "Radio AM",
	"VRD_systemSelectRadioFM" : "Radio FM",
	"VRD_systemSelectRetry" : "Riprova",
	"VRD_systemSelectSatRadio" : "Radio satellitare",
	"VRD_systemSelectSettings" : "Impostazioni",
	"VRD_systemSelectSiri" : "Siri",
	"VRD_systemSelectSms" : "Testo / SMS",
	"VRD_systemSelectStitcher" : "Stitcher",
	"VRD_systemSelectTV" : "TV",
	"VRD_systemSelectTrafficAlert" : "Annuncio sul traffico (TA)",
	"VRD_systemSelectTutorial" : "Tutorial",
	"VRD_systemSelectUSB" : "USB",
	"VRD_systemSelectUSBA" : "USB 1",
	"VRD_systemSelectUSBB" : "USB 2",
	"VRD_systemSelectXmAudio" : "Radio SXM",
	"VRD_tvSelectView" : "Visualizza",
	"VRD_usbaudioBrowse" : "Sfoglia ",
	"VRD_usbaudioBrowseAlbum" : "Sfoglia {albumName}",
	"VRD_usbaudioBrowseAlbums" : "Sfoglia album",
	"VRD_usbaudioBrowseAll" : "Sfoglia tutte le canzoni, gli album o gli artisti",
	"VRD_usbaudioBrowseAnyAlbum" : "Sfoglia [Album] {albumName}",
	"VRD_usbaudioBrowseAnyArtist" : "Sfoglia l'[artista] {artistName}",
	"VRD_usbaudioBrowseAnyFolder" : "Sfoglia cartella {folderName}",
	"VRD_usbaudioBrowseArtist" : "Sfoglia {artistName}",
	"VRD_usbaudioBrowseArtists" : "Sfoglia artista",
	"VRD_usbaudioBrowseAudiobooks" : "Sfoglia audiolibri",
	"VRD_usbaudioBrowseFolder" : "Sfoglia {folderName}",
	"VRD_usbaudioBrowseFolders" : "Sfoglia cartella",
	"VRD_usbaudioBrowseGenre" : "Sfoglia [genere] {genreName}",
	"VRD_usbaudioBrowseGenres" : "Sfoglia genere",
	"VRD_usbaudioBrowseLineNumber" : "Cerca linea {lineNumber}",
	"VRD_usbaudioBrowsePlaylist" : "Sfoglia playlist {playlistName}",
	"VRD_usbaudioBrowsePlaylists" : "Sfoglia playlist",
	"VRD_usbaudioBrowsePodcast" : "Sfoglia podcast {podcastName}",
	"VRD_usbaudioBrowsePodcasts" : "Sfoglia podcast",
	"VRD_usbaudioBrowseSongs" : "Sfoglia canzoni",
	"VRD_usbaudioChooseAlbumArtist" : "{artistName}",
	"VRD_usbaudioGenerateMoreLikeThis" : "Altri come questo",
	"VRD_usbaudioPlayAlbums" : "Riproduci album",
	"VRD_usbaudioPlayAll" : "Riproduci tutti",
	"VRD_usbaudioPlayAnyAlbum" : "Riproduci l'[album] {albumName}",
	"VRD_usbaudioPlayAnyArtist" : "Riproduci l'[artista] {artistName}",
	"VRD_usbaudioPlayAnyFolder" : "Riproduci la cartella {folderName}",
	"VRD_usbaudioPlayArtistAlbum" : "Riproduci {artistName} {albumName}",
	"VRD_usbaudioPlayArtists" : "Riproduci artista",
	"VRD_usbaudioPlayAudiobook" : "Riproduci l'audiolibro {AudiobookName}",
	"VRD_usbaudioPlayAudiobooks" : "Riproduci audiolibri",
	"VRD_usbaudioPlayChapter" : "{chapterName}",
	"VRD_usbaudioPlayChapterIndex" : "Riproduci capitolo {index} {chapter}",
	"VRD_usbaudioPlayEpisode" : "{episodeName}",
	"VRD_usbaudioPlayFolder" : "Riproduci {folderName}",
	"VRD_usbaudioPlayFolders" : "Riproduci cartella",
	"VRD_usbaudioPlayGenre" : "Riproduci il [genere] {genreName}",
	"VRD_usbaudioPlayGenres" : "Riproduci genere",
	"VRD_usbaudioPlayLineNumber" : "Riproduci la [linea] {lineNumber}",
	"VRD_usbaudioPlayPlaylist" : "Riproduci playlist {playlistName}",
	"VRD_usbaudioPlayPlaylists" : "Riproduci playlist",
	"VRD_usbaudioPlayPodcast" : "Riproduci podcast {PodcastName}",
	"VRD_usbaudioPlayPodcasts" : "Riproduci podcast",
	"VRD_usbaudioPlaySongs" : "Riproduci canzone",
	"VRD_usbaudioRepeat" : "Ripeti",
	"VRD_usbaudioRepeatAll" : "Ripeti tutti",
	"VRD_usbaudioRepeatOff" : "Ripetizione disattivata",
	"VRD_usbaudioRepeatSong" : "Ripeti canzone",
	"VRD_usbaudioRewind" : "Rewind",
	"VRD_usbaudioSelectAlbum" : "Album {albumName}",
	"VRD_usbaudioSelectAlbums" : "Album",
	"VRD_usbaudioSelectAll" : "Tutti gli episodi, i capitoli, le canzoni, gli album o gli artisti",
	"VRD_usbaudioSelectArtist" : "Artista {artistName}",
	"VRD_usbaudioSelectArtists" : "Artista",
	"VRD_usbaudioSelectAudiobook" : "{audiobookName}",
	"VRD_usbaudioSelectAudiobooks" : "Audiolibri",
	"VRD_usbaudioSelectFolder" : "Cartella {folderName}",
	"VRD_usbaudioSelectFolders" : "Cartelle",
	"VRD_usbaudioSelectGenre" : "Genere {genreName}",
	"VRD_usbaudioSelectGenres" : "Genere",
	"VRD_usbaudioSelectPlaylist" : "Playlist {playlistName}",
	"VRD_usbaudioSelectPlaylists" : "Playlist",
	"VRD_usbaudioSelectPodcast" : "{podcastName}",
	"VRD_usbaudioSelectPodcasts" : "Podcast",
	"VRD_usbaudioSelectRootFolder" : "Menu principale",
	"VRD_usbaudioSelectSettings" : "Impostazioni audio",
	"VRD_usbaudioSelectSongs" : "Canzone",
	"VRD_usbaudioSelectSourceMenu" : "Intrattenimento",
	"VRD_usbaudioShuffle" : "Riproduzione casuale",
	"VRD_usbaudioShuffleOff" : "Riproduzione casuale disattivata",
	"VRD_usbaudioShuffleOn" : "Riproduzione casuale attivata",
	"VRD_usbaudioSongList" : "Elenco canzoni",
	"VRD_xmaudioBackSpaceDelete" : "Elimina cifre",
	"VRD_xmaudioChangeLockCode" : "Modifica codice PIN",
	"VRD_xmaudioConfirmDelete" : "Elimina",
	"VRD_xmaudioEnterPIN" : "{fourDigitPIN}",
	"VRD_xmaudioPlayChannelName" : "Riproduci canale XM {channelName}",
	"VRD_xmaudioPlayStationNumber" : "Sintonizza su {channelNumber}",
	"VRD_xmaudioResetLockCode" : "Resetta Codice PIN",
	"VRD_xmaudioSelectCallXM" : "Chiama XM",
	"VRD_xmaudioSelectChangeCategory" : "Cambia categoria",
	"VRD_xmaudioSelectContinueListening" : "Continua l'ascolto",
	"VRD_xmaudioSelectDismiss" : "Ignora",
	"VRD_xmaudioSelectEveryOccurance" : "Ogni occorrenza",
	"VRD_xmaudioSelectEveryOtherReport" : "Qualsiasi altro report",
	"VRD_xmaudioSelectEveryReport" : "Ogni report",
	"VRD_xmaudioSelectExitTuneMix" : "Esci da TuneMix",
	"VRD_xmaudioSelectFavorites" : "Preferiti",
	"VRD_xmaudioSelectListenNow" : "Ascoltato ora",
	"VRD_xmaudioSelectMove" : "Sposta",
	"VRD_xmaudioSelectNearestCity" : "Città più vicina",
	"VRD_xmaudioSelectOnlyFirstAfterVehicleStart" : "Avvio veicolo",
	"VRD_xmaudioSelectOnlyFirstOccuranceInGame" : "Prima occorrenza",
	"VRD_xmaudioSelectReplayAlert" : "Riproduci avviso",
	"VRD_xmaudioSelectReturnToPrevious" : "Torna a precedente",
	"VRD_xmaudioSelectSFSportBaseball" : "Baseball",
	"VRD_xmaudioSelectSFSportNCAA" : "Calcio giovanile",
	"VRD_xmaudioSelectSFSportNFL" : "Calcio professionale",
	"VRD_xmaudioSelectSFSportNHL" : "Hockey",
	"VRD_xmaudioSelectScanOff" : "Spegni scansione",
	"VRD_xmaudioSelectScanOn" : "Accendi scansione",
	"VRD_xmaudioSelectSettings" : "Impostazioni",
	"VRD_xmaudioSelectSoundSettings" : "Impostazioni audio",
	"VRD_xmaudioSelectSource" : "Intrattenimento",
	"VRD_xmaudioSelectStation" : "Stazione {channelNumber}",
	"VRD_xmaudioSelectStationAll" : "Tutti i canali",
	"VRD_xmaudioSelectStationCategory" : "{categoryName}",
	"VRD_xmaudioSelectStationFeaturedFavorites" : "Preferiti in primo piano",
	"VRD_xmaudioSelectStationList" : "Canali",
	"VRD_xmaudioSelectTuneMix" : "TuneMix",
	"VRD_xmaudioSelectTuneMixChannel" : "Opzioni canali TuneMix",
	"VRD_xmaudioSelectTuneMixChannelsOptions" : "Opzioni canale",
	"VRD_xmaudioSelectTuneMixCreation" : "Crea nuovo canale TuneMix",
	"VRD_xmaudioSelectTuneMixEdit" : "Modifica canale TuneMix",
	"VRD_xmaudioSelectTuneMixEditOps" : "Opzioni di modifica TuneMix",
	"VRD_xmaudioSelectTuneMixRemove" : "Elimina canale TuneMix",
	"VRD_xmaudioSelectTuneMixRename" : "Rinomina TuneMix",
	"VRD_xmaudioSelectTurnAlertsOff" : "Disattiva avvisi",
	"VRD_xmaudioSelectiTunesTagging" : "Tag iTunes",
	"VRD_xmaudioSetChannelLock" : "Blocca canale",
	"VRD_xmaudioSetParentalLock" : "Blocco sessione",
	"VRD_xmdataSelectFuelPrices" : "Prezzi benzina",
	"VRD_xmdataSelectMovies" : "Film",
	"VRD_xmdataSelectParking" : "Parcheggio",
	"VRD_xmdataSelectSports" : "Sport",
	"VRD_xmdataSelectStock" : "Rifornimenti",
	"VRD_xmdataSelectTrafficPlus" : "Traffico più",
	"VRD_xmdataSelectWeatherForecast" : "Previsioni del tempo",
	"VRD_xmdataSelectWeatherRadar" : "Radar meteorologico",
	"VRD_xmdataSelectWeatherSecurityAlerts" : "Allerte sicurezza meteo",
};

framework.registerAppDictLoaded("system", "it_IT");