var __VrHelpPositionTable__systemAppDict_fr_CN = {
	"HomeScreen_Help" : {
		"Right" : ["VrHelp_Favorites"],
		"Left" : ["VrHelp_Entertainment","VrHelp_Communication","VrHelp_Navigation","VrHelp_Settings","VrHelp_Applications"]
	}
};

var Localization_systemAppDict_fr_CN = {
	//"stringId" : "localString"
	"ActiveCallItem" : "Appel actif",
	"AhaMaintError" : "Erreur de maintenance d’aha",
	"AhaRadio" : "aha",
	"AmRadio" : "AM",
	"AndroidAuto" : "Android Auto",
	"Applications" : "Applications",
	"AudioSourceNotAvailableBTAudio" : "Bluetooth audio non disponible.",
	"AudioSourceNotAvailableCD" : "Le CD a été retiré",
	"AudioSourceNotAvailableDVD" : "Le DVD a été retiré",
	"AudioSourceNotAvailableTV" : "TV non disponible",
	"AudioSourceNotAvailableUSB" : "Le dispositif USB a été modifié",
	"AuxIn" : "AUX",
	"BT" : "BT",
	"Bluetooth" : "Bluetooth",
	"BluetoothWithDevice" : "Bluetooth - {deviceName}",
	"CallHistory" : "Historique des appels",
	"CarPlay" : "Apple CarPlay",
	"CdPlayer" : "CD",
	"ChannelOffAir" : "Le canal a cessé d’émettre",
	"ChannelUnauth" : "Canal non autorisé",
	"CheckAntenna" : "Vérifier l’antenne",
	"CheckTuner" : "Vérifier le tuner",
	"Communication" : "Communication",
	"Connect" : "Connecter",
	"Contacts" : "Contacts",
	"DVDItem" : "DVD",
	"DabRadio" : "DAB",
	"DialPhone" : "Clavier du téléphone",
	"DidYouSay" : "Avez-vous dit...",
	"DisclaimerText" : "Le manque de concentration peut causer accidents. Ne pas utiliser pendant la conduite. Toujours se concentrer sur la conduite et respecter le code de la route. Consulter le guide d'utilisation.",
	"DisconnectThenReconnect" : "Erreur au démarrage de Siri. Décon. puis reconnectez l'appareil Apple.",
	"DriveRecord" : "Dossier de conduite",
	"DriverIDItem" : "Identification du conducteur",
	"EcoenergyApp" : "Consommation",
	"EcoenergyAppHEV" : "Assistant de conduite",
	"Email" : "Email",
	"EngineOilLevel" : "Niveau de l'huile mot.",
	"Entertainment" : "Divertissements",
	"ErrorWhileStartingSiri" : "Erreur au démarrage de Siri.",
	"FailedNotificationRetrieval" : "Impossible de récupérer la liste de notifications",
	"FavoritesItem" : "Favoris",
	"FmRadio" : "FM",
	"HDTrafficItem" : "Carte de circulation de HD Radio™",
	"InitiateSiri" : "Appuyez longuement sur le bouton Talk pour démarrer la session Siri",
	"IntelligentDriveMasterItem" : "i-DM",
	"NavigationTitle" : "Navigation",
	"NoConnectionNotifyText" : "Voulez-vous connecter un téléphone maintenant ?",
	"NoConnectionNotifyTitle" : "Aucun téléphone connecté",
	"NoDeviceText" : "Voulez-vous connecter un dispositif maintenant ?",
	"NoDeviceTitle" : "Aucun dispositif connecté",
	"Notifications" : "Notifications",
	"NotifyIgnore" : "Ignorer",
	"NotifyIncomingMsg" : "Message entrant de :",
	"NotifyOff" : "Notif OFF",
	"NotifyRead" : "Lire",
	"NotifyReadNow" : "Voulez-vous le lire maintenant ?",
	"Pandora" : "Pandora",
	"ReconnectAhaRadio" : "Reconnexion Bluetooth audio pour aha",
	"ReconnectBTAudio" : "Reconnex Bluetooth audio pr repris lect",
	"ReconnectCD" : "Vérification du CD pour reprise lecture",
	"ReconnectCarPlay" : "Relancement d'Apple Carplay.",
	"ReconnectDVD" : "Vérification DVD pour reprise lecture",
	"ReconnectEntMenuButton" : "Menu des divertissements",
	"ReconnectFailedBTAudio" : "Impossible de reconnecter l’audio Bluetooth",
	"ReconnectFailedCD" : "Le CD a été retiré. Impossible de reprendre la lecture.",
	"ReconnectFailedCarPlay" : "Impossible de reconnecter Apple CarPlay",
	"ReconnectFailedDVD" : "Le DVD a été retiré. Impossible de reprendre la lecture.",
	"ReconnectFailedTV" : "TV non disponible. Impossible de reprendre la lecture.",
	"ReconnectFailedUSB" : "Le dispositif USB a été modifié. Impossible de reprendre la lecture.",
	"ReconnectPandora" : "Reconnexion Bluetooth audio pr Pandora",
	"ReconnectStitcher" : "Reconnexion Bluetooth audio pr Stitcher",
	"ReconnectTV" : "Vérification de la TV pour reprendre la lecture",
	"ReconnectUSB" : "Reconnex° dispositif USB pr reprise lect",
	"RetryLabel" : "Réessayer",
	"SchedMaintenanceApp" : "Entretien",
	"ScreenReplication" : "Screen Replication",
	"SdarsRadio" : "XM",
	"Settings" : "Paramètres",
	"SettingsCommunication" : "Paramètres",
	"Siri" : "Siri",
	"SiriDisabled" : "Siri est désactivé sur Apple Device.",
	"Sms" : "SMS",
	"StitcherItem" : "Stitcher",
	"TVItem" : "TV",
	"TempWarning" : "Avertissement de température",
	"TempWarningText" : "LA température de l’affichage est trop élevée. Les performances de l'écran peuvent être réduites jusqu'à son refroidissement.",
	"TextDownloaded" : "SMS téléchargé",
	"TextSent" : "SMS envoyé",
	"TrafficAlertsItem" : "Info sur la circulation",
	"USB" : "USB",
	"USB1AndroidAuto" : "USB 1 - Android Auto",
	"USB1CarPlay" : "USB 1 - Apple CarPlay",
	"USB2AndroidAuto" : "USB 2 - Android Auto",
	"UsbAudioA" : "USB 1",
	"UsbAudioAWithDevice" : "USB 1 - {deviceName}",
	"UsbAudioB" : "USB 2",
	"UsbAudioBWithDevice" : "USB 2 - {deviceName}",
	"UseCommander" : "Veuillez utiliser le contrôleur de commandes pendant que vous conduisez.",
	"VehicleDataTransferItem" : "Transfert données du véhicule ",
	"VehicleStatusMonitor" : "Écran stat véhicule",
	"VehicleTelemetryTransfer" : "Transfert de télémétrie véhiculaire",
	"VideoSignalLost" : "Signal vidéo perdu",
	"VoiceNotSupported" : "Voix pas pris en charge ",
	"VoiceRecognition" : "Reconnaissance vocale",
	"VrHelp_Applications" : "Applications",
	"VrHelp_Communication" : "Communication",
	"VrHelp_Entertainment" : "Divertissements",
	"VrHelp_Favorites" : "Favoris",
	"VrHelp_Navigation" : "Navigation",
	"VrHelp_Settings" : "Paramètres",
	"WarnGuidanceApp" : "Mise en garde",
	"WarningTitle" : "ATTENTION !",
	"XMAudio" : "SXM",
	"XMData" : "Services SXM",
	"agree" : "Je suis d'accord",
	"VRD_aharadioSelectCall" : "Appeler",
	"VRD_aharadioSelectDiscard" : "Ne pas enregistrer",
	"VRD_aharadioSelectEpisodes" : "Liste d'épisodes",
	"VRD_aharadioSelectLBSTab" : "A proximité",
	"VRD_aharadioSelectMainList" : "Liste principale Aha",
	"VRD_aharadioSelectMap" : "Carte",
	"VRD_aharadioSelectPresetsTab" : "Préréglage",
	"VRD_aharadioSelectSave" : "Enregistrer",
	"VRD_aharadioSelectSettings" : "Paramètres audio",
	"VRD_aharadioSelectShout" : "Shout",
	"VRD_aharadioSelectSource" : "Divertissements / Modifier la source",
	"VRD_aharadioSelectThumbsDown" : "Défavorable",
	"VRD_aharadioSelectThumbsUp" : "Favorable",
	"VRD_amradioPlayStationFrequency" : "Régler sur AM {frequency}",
	"VRD_amradioSelectAutoMemory" : "Mémoire automatique",
	"VRD_amradioSelectFavorites" : "Favoris",
	"VRD_amradioSelectHD" : "Stations HD Radio",
	"VRD_amradioSelectHDOff" : "HD Radio désactivée ",
	"VRD_amradioSelectHDOn" : "HD Radio activée ",
	"VRD_amradioSelectScanOff" : "Balayage désactivé",
	"VRD_amradioSelectScanOn" : "Balayage activé",
	"VRD_amradioSelectSeekNext" : "Rechercher suivant",
	"VRD_amradioSelectSeekPrevious" : "Rechercher précédent",
	"VRD_amradioSelectSettings" : "Paramètres audio",
	"VRD_amradioSelectSource" : "Aller à Menu des divertissements",
	"VRD_amradioSelectStationFrequency" : "{AMFrequency}",
	"VRD_amradioSelectTrafficAlert" : "Alerte circulation",
	"VRD_amradioSelectTrafficAlertOff" : "Alerte circulation désactivée",
	"VRD_amradioSelectTrafficAlertOn" : "Alerte circulation activée",
	"VRD_amradioSelectTune" : "Régler",
	"VRD_amradioSelectUpdateAutoMemory" : "Recherche dans mémoire automatique",
	"VRD_amradioSelectiTunesTagging" : "Balisage iTunes",
	"VRD_amradioTuneDown" : "Régler sur la radio suivante",
	"VRD_amradioTuneUp" : "Régler sur la radio précédente",
	"VRD_amradioUpdateAutoMemory" : "Mettre à jour la liste des stations",
	"VRD_auxinSelectSettings" : "Paramètres audio",
	"VRD_auxinSelectSource" : "Divertissements / Modifier la source",
	"VRD_btaudioScanPlay" : "Lecture par balayage",
	"VRD_btaudioSelectConnect" : "Connecter",
	"VRD_btaudioSelectRootMenu" : "Menu racine",
	"VRD_btaudioSelectSettings" : "Paramètres audio",
	"VRD_btaudioSelectSource" : "Aller à Menu des divertissements",
	"VRD_btaudioToggleRepeat" : "Lecture en boucle",
	"VRD_btaudioToggleShuffle" : "Lecture aléatoire",
	"VRD_carplaySelectApplications" : "Applications",
	"VRD_cdGoSettings" : "Paramètres audio",
	"VRD_cdHandleStartScan" : "Lancer le balayage",
	"VRD_cdPlayBeginning" : "Recommencer",
	"VRD_cdRepeatFolder" : "Lire Dossier en boucle",
	"VRD_cdRepeatOff" : "Lecture en boucle désactivée",
	"VRD_cdRepeatOn" : "Lecture en boucle activée",
	"VRD_cdRepeatTrack" : "Lire Piste en boucle ",
	"VRD_cdSelectCurrentFolder" : "Dossier actuel",
	"VRD_cdSelectRepeat" : "Lecture en boucle",
	"VRD_cdSelectRootFolder" : "Menu racine",
	"VRD_cdSelectShuffle" : "Lecture aléatoire",
	"VRD_cdSelectSource" : "Aller à Menu des divertissements",
	"VRD_cdSelectTrackList" : "Liste de pistes",
	"VRD_cdSelectTrackNumber" : "Lire piste {Number}",
	"VRD_cdShuffleDisk" : "Lire Disque en aléatoire",
	"VRD_cdShuffleFolder" : "Lire Dossier en aléatoire",
	"VRD_cdShuffleOff" : "Lecture aléatoire désactivée",
	"VRD_cdShuffleOn" : "Lecture aléatoire activée",
	"VRD_commonAddToFavorites" : "Ajouter aux favoris",
	"VRD_commonCancel" : "Annuler",
	"VRD_commonFastForward" : "Avance rapide",
	"VRD_commonGoBack" : "Retour",
	"VRD_commonIntentParent" : "Parent",
	"VRD_commonIntentParentUSBAudio" : "Parent",
	"VRD_commonIntentUSBAudio" : "Maison",
	"VRD_commonIntentUSBAudioBG" : "Maison",
	"VRD_commonMenuUp" : "Menu précédent",
	"VRD_commonNext" : "Suivant",
	"VRD_commonNo" : "Non",
	"VRD_commonPageDown" : "En bas de page / Faire défiler vers le bas",
	"VRD_commonPageUp" : "En haut de page / Faire défiler vers le bas",
	"VRD_commonPause" : "Pause",
	"VRD_commonPrevious" : "Précédent",
	"VRD_commonResume" : "Lire / Reprendre",
	"VRD_commonRewind" : "Retour rapide",
	"VRD_commonSelectLineNumber" : "Ligne {lineNumber}",
	"VRD_commonYes" : "Oui / OK",
	"VRD_contactsChooseContactName" : "{ContactName}",
	"VRD_contactsDisambiguateContactName" : "Afficher {ContactName}",
	"VRD_contactsImportAll" : "Importer tous les contacts",
	"VRD_contactsImportCancel" : "Annuler importation",
	"VRD_contactsImportContacts" : "Modifier les contacts",
	"VRD_contactsImportSingle" : "Importer le contact sélectionné",
	"VRD_contactsRemoveContact" : "Supprimer le contact",
	"VRD_contactsSelectCall" : "Appeler",
	"VRD_contactsSelectContactName" : "{ContactName}",
	"VRD_contactsSelectDownload" : "Télécharger",
	"VRD_contactsSelectFavorites" : "Favoris",
	"VRD_contactsSelectNone" : "aucune de ces options",
	"VRD_contactsSelectReadContactName" : "Lire le nom du contact",
	"VRD_contactsSelectRemove" : "Supprimer",
	"VRD_contactsSelectRetry" : "Réessayer",
	"VRD_contactsSendPhoneType" : "{phoneType}",
	"VRD_contactsShowAddress" : "Adresse",
	"VRD_dabDisplayDABSettings" : "Paramètres DAB",
	"VRD_dabDisplayEnsembleList" : "Sélectionner Ensemble",
	"VRD_dabDisplayStationList" : "Liste des stations",
	"VRD_dabSelectFavorites" : "Favoris",
	"VRD_dabSelectScan" : "Balayage",
	"VRD_dabSelectSeekNext" : "Suivant",
	"VRD_dabSelectSeekPrevious" : "Précédent",
	"VRD_dabSelectSettings" : "Paramètres audio",
	"VRD_dabSelectSource" : "Divertissements",
	"VRD_dabTAToggleOFF" : "Circulation désactivée",
	"VRD_dabTAToggleON" : "Circulation activée",
	"VRD_dabTAToggleVois" : "Annonce de circulation",
	"VRD_dabUpdateStationList" : "Mettre à jour Liste",
	"VRD_dvdClearPin" : "Supprimer les chiffres",
	"VRD_dvdSayGRating" : "G",
	"VRD_dvdSayPG12" : "Interdit au moins de douze ans",
	"VRD_dvdSayR15" : "Interdit au moins de quinze ans et plus",
	"VRD_dvdSayR18" : "--",
	"VRD_dvdSelectAspectRatio" : "Rapport d’image",
	"VRD_dvdSelectAudioSettings" : "Paramètres vidéo",
	"VRD_dvdSelectCameraAngle" : "Angle de caméra",
	"VRD_dvdSelectEditPin" : "Modifier le code PIN",
	"VRD_dvdSelectParentLock" : "Contrôle parental",
	"VRD_dvdSelectParentLockOff" : "Contrôle parental désactivé",
	"VRD_dvdSelectParentLockOn" : "Contrôle parental activé",
	"VRD_dvdSelectParentLockRating" : "Classification du contenu autorisé par le contrôle parental",
	"VRD_dvdSelectResetPin" : "Configurer le nouveau NIP",
	"VRD_dvdSelectRootMenu" : "Menu racine",
	"VRD_dvdSelectSettings" : "Paramètres audio",
	"VRD_dvdSelectSource" : "Divertissements",
	"VRD_dvdSelectSubtitleOff" : "Sous-titres désactivés",
	"VRD_dvdSelectSubtitleOn" : "Sous-titres activés",
	"VRD_dvdSlowForward" : "Avance rapide",
	"VRD_dvdSlowRewind" : "Retour rapide",
	"VRD_dvdVUISendPin" : "{FourDigitPin}",
	"VRD_emailSelectAllAccounts" : "Tous les comptes",
	"VRD_emailSelectCall" : "Appeler",
	"VRD_emailSelectContactName" : "{ContactName}",
	"VRD_emailSelectContinueEmail" : "Continuer le Courriel",
	"VRD_emailSelectDelete" : "Supprimer",
	"VRD_emailSelectDiscard" : "Ne pas enregistrer",
	"VRD_emailSelectImportEmail" : "Mettre à jour la boîte de réception",
	"VRD_emailSelectInbox" : "Boîte de réception de courriels",
	"VRD_emailSelectInboxSelector" : "Boîte de réception",
	"VRD_emailSelectMessage" : "Ajouter un message",
	"VRD_emailSelectNone" : "Aucune de ces options",
	"VRD_emailSelectReply" : "Répondre",
	"VRD_emailSelectReplyAll" : "Répondre à tous",
	"VRD_emailSelectRetry" : "Réessayer",
	"VRD_emailSelectReturn" : "Retour",
	"VRD_emailSelectSend" : "Envoyer",
	"VRD_emailSelectSenderName" : "{senderName}",
	"VRD_emnaviAcceptAvoidance" : "Confirmer",
	"VRD_emnaviAddCurrentPosToFavourites" : "Ajouter la position actuelle aux favoris",
	"VRD_emnaviAddWaypointCityCenter" : "Ajouter point de cheminement centre-ville",
	"VRD_emnaviAddWaypointDistrictCenter" : "Ajouter point de cheminement centre du quartier",
	"VRD_emnaviAddWaypointFavorite" : "Ajouter point de cheminement favori",
	"VRD_emnaviAddWaypointPOI" : "Ajouter point de cheminement {poiHypList}",
	"VRD_emnaviAvoidRouteAhead" : "Éviter le parcours en vue",
	"VRD_emnaviCancelRoute" : "Supprimer l'itinéraire",
	"VRD_emnaviDecreaseAvoidanceLength" : "Moins",
	"VRD_emnaviGoToCockpit" : "Lancer",
	"VRD_emnaviIncreaseAvoidanceLength" : "Plus",
	"VRD_emnaviJPJ_VDEHypothesisList" : "Nom de ville",
	"VRD_emnaviNavigateHere" : "Me rendre ici",
	"VRD_emnaviNavigateHome" : "Rentrer chez moi",
	"VRD_emnaviNavigateToARecentDestination" : "Me rendre à une destination récente",
	"VRD_emnaviNavigateToAddress" : "Me rendre à cette adresse",
	"VRD_emnaviNavigateToCityCenter" : "Me rendre dans le centre-ville",
	"VRD_emnaviNavigateToDistrictCenter" : "Me rendre dans le centre du quartier",
	"VRD_emnaviNavigateToFavorite" : "Me rendre à une destination favorite",
	"VRD_emnaviNavigateToPOI" : "Me rendre à {poiHypList}",
	"VRD_emnaviNewDestination" : "Nouvelle destination",
	"VRD_emnaviRepeatInstruction" : "Répéter l’instruction",
	"VRD_emnaviRouteSummary" : "Résumé de l'itinéraire",
	"VRD_emnaviSelectCancelRoute" : "Effacer l’itinéraire",
	"VRD_emnaviSelectNavigateToAddress" : "Me rendre à une adresse",
	"VRD_emnaviSimpleHypothesisList" : "Nom de région",
	"VRD_emnaviStepByStep" : "Entrée étape par étape",
	"VRD_emnaviTravelViaARecentDestination" : "Ajouter point de cheminement destination récente",
	"VRD_emnaviTravelViaAddress" : "Passer par cette adresse",
	"VRD_emnaviTravelViaHome" : "Passer par Maison",
	"VRD_emnaviTryAgain" : "Réessayer",
	"VRD_emnaviUniSimpleHypothesisList" : "Adresse",
	"VRD_emnaviUniVDEHypothesisList" : "Adresse",
	"VRD_emnaviVDEHypothesisList" : "Adresse",
	"VRD_emnaviWhereAmI" : "Où suis-je?",
	"VRD_emnaviZoomIn" : "Zoom avant",
	"VRD_emnaviZoomOut" : "Zoom arrière",
	"VRD_fmradioPlayStationFrequency" : "Régler sur FM {frequency}",
	"VRD_fmradioSelectAutoMemory" : "Mémoire automatique",
	"VRD_fmradioSelectChangeGenre" : "Modifier Genre",
	"VRD_fmradioSelectFMSettings" : "Paramètres FM",
	"VRD_fmradioSelectFavorites" : "Favoris",
	"VRD_fmradioSelectGenreSeek" : "Recherche de Genre",
	"VRD_fmradioSelectHDChannel" : "{HD Channel}",
	"VRD_fmradioSelectHDChannels" : "Stations HD Radio",
	"VRD_fmradioSelectHDRadio" : "HD Radio",
	"VRD_fmradioSelectHDRadioOff" : "HD Radio désactivée ",
	"VRD_fmradioSelectHDRadioOn" : "HD Radio activée ",
	"VRD_fmradioSelectScanOff" : "Balayage désactivé",
	"VRD_fmradioSelectScanOn" : "Balayage activé",
	"VRD_fmradioSelectSeekNext" : "Rechercher suivant",
	"VRD_fmradioSelectSeekPrevious" : "Rechercher précédent",
	"VRD_fmradioSelectSettings" : "Paramètres audio",
	"VRD_fmradioSelectSource" : "Divertissements / Modifier la source",
	"VRD_fmradioSelectStationAll" : "Toutes les stations",
	"VRD_fmradioSelectStationFrequency" : "{frequency}",
	"VRD_fmradioSelectStationGenre" : "{genreName}",
	"VRD_fmradioSelectStationList" : "Liste des stations",
	"VRD_fmradioSelectStationName" : "{stationName}",
	"VRD_fmradioSelectTrafficAlert" : "Annonce de circulation",
	"VRD_fmradioSelectTrafficAlertOff" : "Circulation désactivée",
	"VRD_fmradioSelectTrafficAlertOn" : "Circulation activée",
	"VRD_fmradioSelectTune" : "Régler",
	"VRD_fmradioSelectUpdateAutoMemory" : "Mettre à jour la mémoire automatique",
	"VRD_fmradioSelectiTunesTagging" : "Balisage iTunes",
	"VRD_fmradioTuneDown" : "Régler sur la radio précédente",
	"VRD_fmradioTuneUp" : "Régler sur la radio suivante",
	"VRD_fmradioTurnOffAF" : "Fréquence alternative désactivée",
	"VRD_fmradioTurnOffREG" : "Verrouillage régional désactivé",
	"VRD_fmradioTurnOnAF" : "Fréquence alternative activée",
	"VRD_fmradioTurnOnREG" : "Verrouillage régional activé",
	"VRD_fmradioUpdateAutoMemory" : "Mettre à jour la liste des stations",
	"VRD_pandoraAddStation" : "Ajouter station",
	"VRD_pandoraAddStationFromArtist" : "Créer une station depuis Artiste",
	"VRD_pandoraAddStationFromSong" : "Créer une station depuis Morceau",
	"VRD_pandoraAddToFavorites" : "Ajouter aux favoris",
	"VRD_pandoraBookmarkArtist" : "Marquer l’artiste",
	"VRD_pandoraBookmarkSong" : "Marquer le morceau",
	"VRD_pandoraCreateStation" : "Créer une station",
	"VRD_pandoraSelectAddCurrentStation" : "Ajouter",
	"VRD_pandoraSelectDelete" : "Supprimer",
	"VRD_pandoraSelectEditDelete" : "Supprimer",
	"VRD_pandoraSelectEditMove" : "Déplacer",
	"VRD_pandoraSelectEditReplace" : "Remplacer",
	"VRD_pandoraSelectFavorites" : "Favoris",
	"VRD_pandoraSelectMove" : "Déplacer",
	"VRD_pandoraSelectQuickMix" : "Lecture aléatoire",
	"VRD_pandoraSelectSettings" : "Paramètres audio",
	"VRD_pandoraSelectSortBy" : "Trier",
	"VRD_pandoraSelectSource" : "Divertissements",
	"VRD_pandoraSelectStationList" : "Liste des stations",
	"VRD_pandoraShowBookmarkOptions" : "Marquer",
	"VRD_pandoraShowByAZ" : "Trier par ordre alphabétique",
	"VRD_pandoraShowByDate" : "Filtrer par date",
	"VRD_pandoraSkip" : "Sauter",
	"VRD_pandoraThumbsDown" : "Défavorable",
	"VRD_pandoraThumbsUp" : "Favorable",
	"VRD_phoneCall" : "Appeler",
	"VRD_phoneCallBack" : "Rappeler",
	"VRD_phoneCallByName" : "Appeler par nom",
	"VRD_phoneCallByNumber" : "Appeler par numéro",
	"VRD_phoneCallContactType" : "Appeler {contactName}{contactType}",
	"VRD_phoneCallLast" : "Appeler le dernier numéro",
	"VRD_phoneChooseContactType" : "{contactName} {contactType}",
	"VRD_phoneDialAnyNumber" : "Appeler {number}",
	"VRD_phoneDialpadClearAllDigits" : "Effacer tous les chiffres",
	"VRD_phoneDialpadDeleteDigit" : "Supprimer",
	"VRD_phoneDialpadPhoneNumber" : "{phoneNumber}",
	"VRD_phoneReDial" : "Recomposer",
	"VRD_phoneSelectByName" : "Nom",
	"VRD_phoneSelectByNumber" : "Numéro",
	"VRD_phoneSelectContactType" : "{contactType}",
	"VRD_phoneSelectDialPad" : "Clavier",
	"VRD_phoneSelectFavorites" : "Favoris",
	"VRD_phoneSelectRecentCalls" : "Appels récents",
	"VRD_phoneSelectRecentCallsAll" : "Tous les appels",
	"VRD_phoneSelectRecentCallsMissed" : "Appels manqués",
	"VRD_satradioBackSpaceDelete" : "Supprimer les chiffres",
	"VRD_satradioChangeLockCode" : "Modifier code NIP",
	"VRD_satradioEnterPIN" : "{4digitPin}",
	"VRD_satradioInitializeLockCode" : "Initialiser le code PIN",
	"VRD_satradioPlayChannelName" : "Lire {channelName}",
	"VRD_satradioPlayStationNumber" : "Régler sur {channelNumber}",
	"VRD_satradioResetLockCode" : "Configurer le nouveau NIP",
	"VRD_satradioSeekNext" : "Rechercher suivant",
	"VRD_satradioSeekPrevious" : "Rechercher précédent",
	"VRD_satradioSelectChangeCategory" : "Catégorie",
	"VRD_satradioSelectFavorites" : "Favoris",
	"VRD_satradioSelectParentalLock" : "Contrôle parental",
	"VRD_satradioSelectScanOff" : "Balayage désactivé",
	"VRD_satradioSelectScanOn" : "Balayage activé",
	"VRD_satradioSelectSettings" : "Paramètres audio",
	"VRD_satradioSelectSource" : "Divertissements",
	"VRD_satradioSelectStation" : "Station {Station number}",
	"VRD_satradioSelectStationAll" : "Tous les canaux",
	"VRD_satradioSelectStationCategory" : "{categoryName}",
	"VRD_satradioSelectStationList" : "Liste des chaînes",
	"VRD_satradioTurnChannelLockOFF" : "Déverrouiller le canal actuel",
	"VRD_satradioTurnChannelLockON" : "Verrouiller le canal actuel",
	"VRD_satradioTurnParentalLockOFF" : "Verrouillage de session désactivé",
	"VRD_satradioTurnParentalLockON" : "Verrouillage de session activé",
	"VRD_smsCallPhoneNumber" : "Appeler",
	"VRD_smsDelete" : "Supprimer",
	"VRD_smsImportMessages" : "Mettre à jour le dossier SMS",
	"VRD_smsReply" : "Répondre",
	"VRD_smsSayAnyConversation" : "{senderName}",
	"VRD_smsSelectBody" : "Ajouter un message",
	"VRD_smsSelectContactName" : "{ContactName}",
	"VRD_smsSelectContinueTextMessage" : "Continuer message",
	"VRD_smsSelectDiscard" : "Ne pas enregistrer",
	"VRD_smsSelectInbox" : "Liste du dossier SMS",
	"VRD_smsSelectNone" : "Aucune de ces options",
	"VRD_smsSelectRetry" : "Réessayer",
	"VRD_smsSelectReturn" : "Retour",
	"VRD_smsSelectSend" : "Envoyer",
	"VRD_stitcherAddToFavorites" : "Ajouter aux favoris",
	"VRD_stitcherRemoveFromFavorites" : "Supprimer des Favoris",
	"VRD_stitcherSaveFavorites" : "Enregistrer les modifications",
	"VRD_stitcherSelectSettings" : "Paramètres audio",
	"VRD_stitcherSelectSource" : "Divertissements",
	"VRD_stitcherSelectStationList" : "Liste des stations",
	"VRD_stitcherThumbsDown" : "Défavorable",
	"VRD_stitcherThumbsUp" : "Favorable",
	"VRD_systemSelectAhaRadio" : "Aha Radio",
	"VRD_systemSelectAndroidAuto" : "Android Auto",
	"VRD_systemSelectApplications" : "Applications",
	"VRD_systemSelectAuxIn" : "Entrées Line In / AUX",
	"VRD_systemSelectBTAudio" : "Bluetooth",
	"VRD_systemSelectCD" : "CD",
	"VRD_systemSelectCallHistory" : "Historique des appels",
	"VRD_systemSelectCarPlay" : "CarPlay",
	"VRD_systemSelectCommunication" : "Communication",
	"VRD_systemSelectConnect" : "Connecter",
	"VRD_systemSelectContacts" : "Contacts",
	"VRD_systemSelectDAB" : "DAB",
	"VRD_systemSelectDVD" : "DVD",
	"VRD_systemSelectDisplayClock" : "Affichage de l'horloge",
	"VRD_systemSelectDisplayOff" : "Éteindre l’affichage",
	"VRD_systemSelectEmail" : "Adresse électronique",
	"VRD_systemSelectEntertainment" : "Divertissements",
	"VRD_systemSelectEntertainmentMenu" : "Menu des divertissements",
	"VRD_systemSelectFavorites" : "Favoris",
	"VRD_systemSelectNavigation" : "Navigation",
	"VRD_systemSelectNotifications" : "Messages",
	"VRD_systemSelectNotifyOff" : "Notifications désactivées",
	"VRD_systemSelectPandora" : "Pandora",
	"VRD_systemSelectPhone" : "Téléphone",
	"VRD_systemSelectRadioAM" : "Radio AM",
	"VRD_systemSelectRadioFM" : "Radio FM",
	"VRD_systemSelectRetry" : "Réessayer",
	"VRD_systemSelectSatRadio" : "Radio Satellite",
	"VRD_systemSelectSettings" : "Paramètres",
	"VRD_systemSelectSiri" : "Siri",
	"VRD_systemSelectSms" : "Message / SMS",
	"VRD_systemSelectStitcher" : "Stitcher",
	"VRD_systemSelectTV" : "TV",
	"VRD_systemSelectTrafficAlert" : "Annonce de circulation",
	"VRD_systemSelectTutorial" : "Tutoriel",
	"VRD_systemSelectUSB" : "USB",
	"VRD_systemSelectUSBA" : "USB 1",
	"VRD_systemSelectUSBB" : "USB 2",
	"VRD_systemSelectXmAudio" : "SXM Radio",
	"VRD_tvSelectView" : "Afficher",
	"VRD_usbaudioBrowse" : "Parcourir",
	"VRD_usbaudioBrowseAlbum" : "Parcourir {albumName}",
	"VRD_usbaudioBrowseAlbums" : "Parcourir Album",
	"VRD_usbaudioBrowseAll" : "Parcourir tous les Morceaux, Albums ou Artistes",
	"VRD_usbaudioBrowseAnyAlbum" : "Parcourir [Album] {albumName}",
	"VRD_usbaudioBrowseAnyArtist" : "Parcourir [Artiste] {artistName}",
	"VRD_usbaudioBrowseAnyFolder" : "Parcourir Dossier {folderName}",
	"VRD_usbaudioBrowseArtist" : "Parcourir {artistName}",
	"VRD_usbaudioBrowseArtists" : "Parcourir Artiste",
	"VRD_usbaudioBrowseAudiobooks" : "Parcourir Livres audio",
	"VRD_usbaudioBrowseFolder" : "Parcourir {folderName}",
	"VRD_usbaudioBrowseFolders" : "Parcourir Dossier",
	"VRD_usbaudioBrowseGenre" : "Parcourir [Genre] {genreName}",
	"VRD_usbaudioBrowseGenres" : "Parcourir Genre",
	"VRD_usbaudioBrowseLineNumber" : "Parcourir Ligne {lineNumber}",
	"VRD_usbaudioBrowsePlaylist" : "Parcourir Liste de titres {playlistName}",
	"VRD_usbaudioBrowsePlaylists" : "Parcourir Liste de titres",
	"VRD_usbaudioBrowsePodcast" : "Parcourir Balado {podcastName}",
	"VRD_usbaudioBrowsePodcasts" : "Parcourir Balados",
	"VRD_usbaudioBrowseSongs" : "Parcourir Morceau",
	"VRD_usbaudioChooseAlbumArtist" : "{artistName}",
	"VRD_usbaudioGenerateMoreLikeThis" : "Autres similaires",
	"VRD_usbaudioPlayAlbums" : "Lire Album",
	"VRD_usbaudioPlayAll" : "Tout lire",
	"VRD_usbaudioPlayAnyAlbum" : "Lire [Album] {albumName}",
	"VRD_usbaudioPlayAnyArtist" : "Lire [Artiste] {artistName}",
	"VRD_usbaudioPlayAnyFolder" : "Lire Dossier {folderName}",
	"VRD_usbaudioPlayArtistAlbum" : "Lire {artistName} {albumName}",
	"VRD_usbaudioPlayArtists" : "Lire Artiste",
	"VRD_usbaudioPlayAudiobook" : "Lire Livre audio {AudiobookName}",
	"VRD_usbaudioPlayAudiobooks" : "Lire Livres audio",
	"VRD_usbaudioPlayChapter" : "{chapterName}",
	"VRD_usbaudioPlayChapterIndex" : "Lire Chapitre {index} {chapter}",
	"VRD_usbaudioPlayEpisode" : "{episodeName}",
	"VRD_usbaudioPlayFolder" : "Lire {folderName}",
	"VRD_usbaudioPlayFolders" : "Lire Dossier",
	"VRD_usbaudioPlayGenre" : "Lire [Genre] {genreName}",
	"VRD_usbaudioPlayGenres" : "Lire Genre",
	"VRD_usbaudioPlayLineNumber" : "Lire [Ligne] {lineNumber}",
	"VRD_usbaudioPlayPlaylist" : "Lire Liste de titres {playlistName}",
	"VRD_usbaudioPlayPlaylists" : "Lire Liste de titres",
	"VRD_usbaudioPlayPodcast" : "Lire Balado {PodcastName}",
	"VRD_usbaudioPlayPodcasts" : "Lire Balados",
	"VRD_usbaudioPlaySongs" : "Lire Morceau",
	"VRD_usbaudioRepeat" : "Lecture en boucle",
	"VRD_usbaudioRepeatAll" : "Tout lire en boucle",
	"VRD_usbaudioRepeatOff" : "Lecture en boucle désactivée",
	"VRD_usbaudioRepeatSong" : "Lire Morceau en boucle",
	"VRD_usbaudioRewind" : "Retour rapide",
	"VRD_usbaudioSelectAlbum" : "Album {albumName}",
	"VRD_usbaudioSelectAlbums" : "Album",
	"VRD_usbaudioSelectAll" : "Tous les Épisodes, Chapitres, Morceaux, Albums ou Artistes",
	"VRD_usbaudioSelectArtist" : "Artiste {artistName}",
	"VRD_usbaudioSelectArtists" : "Artiste",
	"VRD_usbaudioSelectAudiobook" : "{audiobookName}",
	"VRD_usbaudioSelectAudiobooks" : "Livres audio",
	"VRD_usbaudioSelectFolder" : "Dossier {folderName}",
	"VRD_usbaudioSelectFolders" : "Dossiers",
	"VRD_usbaudioSelectGenre" : "Genre {genreName}",
	"VRD_usbaudioSelectGenres" : "Genre",
	"VRD_usbaudioSelectPlaylist" : "Liste de titres {playlistName}",
	"VRD_usbaudioSelectPlaylists" : "Liste de titres",
	"VRD_usbaudioSelectPodcast" : "{podcastName}",
	"VRD_usbaudioSelectPodcasts" : "Balado",
	"VRD_usbaudioSelectRootFolder" : "Menu racine",
	"VRD_usbaudioSelectSettings" : "Paramètres audio",
	"VRD_usbaudioSelectSongs" : "Morceau",
	"VRD_usbaudioSelectSourceMenu" : "Divertissements",
	"VRD_usbaudioShuffle" : "Lecture aléatoire",
	"VRD_usbaudioShuffleOff" : "Lecture aléatoire désactivée",
	"VRD_usbaudioShuffleOn" : "Lecture aléatoire activée",
	"VRD_usbaudioSongList" : "Liste des morceaux",
	"VRD_xmaudioBackSpaceDelete" : "Supprimer les chiffres",
	"VRD_xmaudioChangeLockCode" : "Modifier le code PIN",
	"VRD_xmaudioConfirmDelete" : "Supprimer",
	"VRD_xmaudioEnterPIN" : "{fourDigitPIN}",
	"VRD_xmaudioPlayChannelName" : "Lire canal XM {channelName}",
	"VRD_xmaudioPlayStationNumber" : "Régler sur {channelNumber}",
	"VRD_xmaudioResetLockCode" : "Configurer le nouveau NIP",
	"VRD_xmaudioSelectCallXM" : "Téléphoner à XM",
	"VRD_xmaudioSelectChangeCategory" : "Changer la catégorie",
	"VRD_xmaudioSelectContinueListening" : "Continuer à écouter",
	"VRD_xmaudioSelectDismiss" : "Exclure",
	"VRD_xmaudioSelectEveryOccurance" : "Chaque occurrence",
	"VRD_xmaudioSelectEveryOtherReport" : "Sauter un rapport",
	"VRD_xmaudioSelectEveryReport" : "Tous les rapports",
	"VRD_xmaudioSelectExitTuneMix" : "Sortir de TuneMix",
	"VRD_xmaudioSelectFavorites" : "Favoris",
	"VRD_xmaudioSelectListenNow" : "Écouter maintenant",
	"VRD_xmaudioSelectMove" : "Déplacer",
	"VRD_xmaudioSelectNearestCity" : "Ville la plus proche",
	"VRD_xmaudioSelectOnlyFirstAfterVehicleStart" : "Démarrer le véhicule",
	"VRD_xmaudioSelectOnlyFirstOccuranceInGame" : "Première occurrence",
	"VRD_xmaudioSelectReplayAlert" : "Lire l'alerte de nouveau ",
	"VRD_xmaudioSelectReturnToPrevious" : "Revenir au précédent",
	"VRD_xmaudioSelectSFSportBaseball" : "Baseball",
	"VRD_xmaudioSelectSFSportNCAA" : "Football américain universitaire",
	"VRD_xmaudioSelectSFSportNFL" : "Football américain professionnel",
	"VRD_xmaudioSelectSFSportNHL" : "Hockey",
	"VRD_xmaudioSelectScanOff" : "Balayage désactivé",
	"VRD_xmaudioSelectScanOn" : "Balayage activé",
	"VRD_xmaudioSelectSettings" : "Paramètres",
	"VRD_xmaudioSelectSoundSettings" : "Paramètres audio",
	"VRD_xmaudioSelectSource" : "Divertissements",
	"VRD_xmaudioSelectStation" : "Station {channelNumber}",
	"VRD_xmaudioSelectStationAll" : "Tous les canaux",
	"VRD_xmaudioSelectStationCategory" : "{categoryName}",
	"VRD_xmaudioSelectStationFeaturedFavorites" : "Favoris",
	"VRD_xmaudioSelectStationList" : "Canaux",
	"VRD_xmaudioSelectTuneMix" : "TuneMix",
	"VRD_xmaudioSelectTuneMixChannel" : "Options de chaînes TuneMix",
	"VRD_xmaudioSelectTuneMixChannelsOptions" : "Options de canal",
	"VRD_xmaudioSelectTuneMixCreation" : "Créer une nouvelle chaîne TuneMix",
	"VRD_xmaudioSelectTuneMixEdit" : "Éditer la chaîne TuneMix",
	"VRD_xmaudioSelectTuneMixEditOps" : "Options d’édition de TuneMix",
	"VRD_xmaudioSelectTuneMixRemove" : "Supprimer le canal TuneMix",
	"VRD_xmaudioSelectTuneMixRename" : "Renommer TuneMix",
	"VRD_xmaudioSelectTurnAlertsOff" : "Désactiver les alertes",
	"VRD_xmaudioSelectiTunesTagging" : "Balisage iTunes",
	"VRD_xmaudioSetChannelLock" : "Verrouiller le canal",
	"VRD_xmaudioSetParentalLock" : "Verrouillage de session",
	"VRD_xmdataSelectFuelPrices" : "Prix du carburant",
	"VRD_xmdataSelectMovies" : "Films",
	"VRD_xmdataSelectParking" : "Parking",
	"VRD_xmdataSelectSports" : "Sports",
	"VRD_xmdataSelectStock" : "Titres boursiers",
	"VRD_xmdataSelectTrafficPlus" : "Circulation Plus",
	"VRD_xmdataSelectWeatherForecast" : "Prévisions météo",
	"VRD_xmdataSelectWeatherRadar" : "Radar météo",
	"VRD_xmdataSelectWeatherSecurityAlerts" : "Alertes sécurité météo ",
};

framework.registerAppDictLoaded("system", "fr_CN");