var __VrHelpPositionTable__systemAppDict_ar_SA = {
	"HomeScreen_Help" : {
		"Right" : ["VrHelp_Favorites"],
		"Left" : ["VrHelp_Entertainment","VrHelp_Communication","VrHelp_Navigation","VrHelp_Settings","VrHelp_Applications"]
	}
};

var Localization_systemAppDict_ar_SA = {
	//"stringId" : "localString"
	"ActiveCallItem" : "مكالمة نشطة",
	"AhaMaintError" : "خطأ في صيانة aha",
	"AhaRadio" : "aha",
	"AmRadio" : "AM",
	"AndroidAuto" : "Android Auto",
	"Applications" : "التطبيقات",
	"AudioSourceNotAvailableBTAudio" : "صوت Bluetooth غير متاح",
	"AudioSourceNotAvailableCD" : "تمت إزالة CD",
	"AudioSourceNotAvailableDVD" : "تمت إزالة DVD",
	"AudioSourceNotAvailableTV" : "التلفاز غير متاح",
	"AudioSourceNotAvailableUSB" : "تم تغيير منفذ USB",
	"AuxIn" : "AUX",
	"BT" : "BT",
	"Bluetooth" : "Bluetooth",
	"BluetoothWithDevice" : "Bluetooth - {deviceName}",
	"CallHistory" : "سجل المكالمة",
	"CarPlay" : "Apple CarPlay",
	"CdPlayer" : "CD",
	"ChannelOffAir" : "القناة غير مذاعة",
	"ChannelUnauth" : "القناة غير معتمدة",
	"CheckAntenna" : "تفقد الهوائي",
	"CheckTuner" : "تفقد الموالف",
	"Communication" : "الاتصالات",
	"Connect" : "اتصال",
	"Contacts" : "جهات الاتصال",
	"DVDItem" : "DVD",
	"DabRadio" : "DAB",
	"DialPhone" : "هاتف الاتصال",
	"DidYouSay" : "هل قلت...",
	"DisclaimerText" : "قد يتسبب تشتت الانتباه في وقوع حوادث. تجنب التشغيل أثناء القيادة. احرص دائمًا على التركيز واتباع لوائح المرور. انظر كتيب المالك.",
	"DisconnectThenReconnect" : "افصل Apple Device ثم أعد توصيله",
	"DriveRecord" : "سجلّ القيادة",
	"DriverIDItem" : "تحديد السائق",
	"EcoenergyApp" : "إقتصاد وقود",
	"EcoenergyAppHEV" : "شاشة القيادة",
	"Email" : "بريد إلكتروني",
	"EngineOilLevel" : "مستوى زيت المحرك",
	"Entertainment" : "الترفيه",
	"ErrorWhileStartingSiri" : "حدث خطأ أثناء بدء Siri.",
	"FailedNotificationRetrieval" : "تعذر استرجاع قائمة الإخطارات",
	"FavoritesItem" : "المفضلات",
	"FmRadio" : "FM",
	"HDTrafficItem" : "HD Radio™ خريطة التنقل في",
	"InitiateSiri" : "اضغط بشكلٍ مطول على زر التحدث لبدء جلسة عمل Siri",
	"IntelligentDriveMasterItem" : "i-DM",
	"NavigationTitle" : "التنقل",
	"NoConnectionNotifyText" : "هل ترغب في توصيل هاتف الآن؟",
	"NoConnectionNotifyTitle" : "لا يوجد هاتف متصل",
	"NoDeviceText" : "هل ترغب في توصيل جهاز الآن؟",
	"NoDeviceTitle" : "لا يوجد جهاز متصل",
	"Notifications" : "الإخطارات",
	"NotifyIgnore" : "تجاهل",
	"NotifyIncomingMsg" : "رسالة واردة من:",
	"NotifyOff" : "إبطال الإخطار",
	"NotifyRead" : "قراءة",
	"NotifyReadNow" : "هل ترغب في قرائتها الآن؟",
	"Pandora" : "Pandora",
	"ReconnectAhaRadio" : "إعادة اتصال Bluetooth لراديو aha",
	"ReconnectBTAudio" : "إعادة اتصال BT لاستئناف التشغيل",
	"ReconnectCD" : "يتحقق من CD لاستئناف التشغيل",
	"ReconnectCarPlay" : "استئناف Apple CarPlay.",
	"ReconnectDVD" : "يتحقق من DVD لاستئناف التشغيل",
	"ReconnectEntMenuButton" : "قائمة الترفيه",
	"ReconnectFailedBTAudio" : "لم يتمكن من إعادة الاتصال بصوت Bluetooth.",
	"ReconnectFailedCD" : "تمت إزالة CD. تعذر استئناف التشغيل.",
	"ReconnectFailedCarPlay" : "يتعذر إعادة توصيل Apple CarPlay",
	"ReconnectFailedDVD" : "تمت إزالة DVD. تعذر استئناف التشغيل.",
	"ReconnectFailedTV" : "التلفاز غير متاح. لا يمكن متابعة التشغيل.",
	"ReconnectFailedUSB" : "تم تغيير منفذ USB. لم يتمكن من استئناف التشغيل.",
	"ReconnectPandora" : "إعادة اتصال صوت Bluetooth لـPandora",
	"ReconnectStitcher" : "إعادة اتصال صوت Bluetooth لـStitcher",
	"ReconnectTV" : "جاري التحقق من التلفاز لمتابعة التشغيل",
	"ReconnectUSB" : "إعادة اتصال USB لاستئناف التشغيل",
	"RetryLabel" : "أعد المحاولة",
	"SchedMaintenanceApp" : "الصيانة",
	"ScreenReplication" : "تكرار الشاشة",
	"SdarsRadio" : "XM",
	"Settings" : "الإعدادات",
	"SettingsCommunication" : "الإعدادات",
	"Siri" : "Siri",
	"SiriDisabled" : "تم تعطيل Siri في جهاز Apple.",
	"Sms" : "رسائل قصيرة",
	"StitcherItem" : "Stitcher",
	"TVItem" : "TV",
	"TempWarning" : "تحذير درجة الحرارة",
	"TempWarningText" : "جهاز العرض ساخن للغاية. قد ينراجع أداء الشاشة حتى تبرد.",
	"TextDownloaded" : "تم تنزيل النص",
	"TextSent" : "تم إرسال النص",
	"TrafficAlertsItem" : "المعلومات المتعلقة بالتنقل",
	"USB" : "USB",
	"USB1AndroidAuto" : "USB 1 - Android Auto\u200e",
	"USB1CarPlay" : "USB 1 - Apple CarPlay\u200e",
	"USB2AndroidAuto" : "USB 2 - Android Auto\u200e",
	"UsbAudioA" : "USB 1",
	"UsbAudioAWithDevice" : "USB 1 - {deviceName}",
	"UsbAudioB" : "USB 2",
	"UsbAudioBWithDevice" : "USB 2 - {deviceName}",
	"UseCommander" : "يرجى استخدام القائد أثناء القيادة.",
	"VehicleDataTransferItem" : "نقل معلومات ",
	"VehicleStatusMonitor" : "شاشة حالة المركبة",
	"VehicleTelemetryTransfer" : "نقل المعلومات",
	"VideoSignalLost" : "تم فقد إشارة الفيديو",
	"VoiceNotSupported" : "الصوت غير مدعوم. ",
	"VoiceRecognition" : "تمييز الصوت",
	"VrHelp_Applications" : "التطبيقات",
	"VrHelp_Communication" : "الاتصالات",
	"VrHelp_Entertainment" : "الترفيه",
	"VrHelp_Favorites" : "المفضلات",
	"VrHelp_Navigation" : "التنقل",
	"VrHelp_Settings" : "الإعدادات",
	"WarnGuidanceApp" : "التوجيه التحذيري",
	"WarningTitle" : "تحذير!",
	"XMAudio" : "SXM",
	"XMData" : "SXM Services",
	"agree" : "أوافق",
	"VRD_aharadioSelectCall" : "اتصال",
	"VRD_aharadioSelectDiscard" : "تجاهل",
	"VRD_aharadioSelectEpisodes" : "قائمة الحلقات",
	"VRD_aharadioSelectLBSTab" : "الأماكن القريبة",
	"VRD_aharadioSelectMainList" : "Aha القائمة الرئيسة",
	"VRD_aharadioSelectMap" : "خريطة",
	"VRD_aharadioSelectPresetsTab" : "الإعدادات المسبقة",
	"VRD_aharadioSelectSave" : "حفظ",
	"VRD_aharadioSelectSettings" : "إعدادات الصوت",
	"VRD_aharadioSelectShout" : "رسالة صوتية",
	"VRD_aharadioSelectSource" : "الترفيه / تغيير المصدر",
	"VRD_aharadioSelectThumbsDown" : "إبهام إلى الأسفل",
	"VRD_aharadioSelectThumbsUp" : "إبهام إلى الأعلى",
	"VRD_amradioPlayStationFrequency" : "موالفة على {frequency} AM",
	"VRD_amradioSelectAutoMemory" : "ذاكرة تلقائية",
	"VRD_amradioSelectFavorites" : "المفضلات",
	"VRD_amradioSelectHD" : "محطات HD",
	"VRD_amradioSelectHDOff" : "إيقاف تشغيل راديو HD",
	"VRD_amradioSelectHDOn" : "تشغيل راديو HD",
	"VRD_amradioSelectScanOff" : "إيقاف المسح",
	"VRD_amradioSelectScanOn" : "تشغيل المسح",
	"VRD_amradioSelectSeekNext" : "بحث عن التالي",
	"VRD_amradioSelectSeekPrevious" : "بحث عن السابق",
	"VRD_amradioSelectSettings" : "إعدادات الصوت",
	"VRD_amradioSelectSource" : "الانتقال إلى قائمة الترفيه",
	"VRD_amradioSelectStationFrequency" : "{AMFrequency}",
	"VRD_amradioSelectTrafficAlert" : "تنبيه التنقل",
	"VRD_amradioSelectTrafficAlertOff" : "إيقاف تنبيه التنقل",
	"VRD_amradioSelectTrafficAlertOn" : "تشغيل تنبيه التنقل",
	"VRD_amradioSelectTune" : "موالفة",
	"VRD_amradioSelectUpdateAutoMemory" : "بحث الذاكرة التلقائية",
	"VRD_amradioSelectiTunesTagging" : "علامات iTunes",
	"VRD_amradioTuneDown" : "توليف لأسفل",
	"VRD_amradioTuneUp" : "توليف لأعلى",
	"VRD_amradioUpdateAutoMemory" : "تحديث قائمة المحطات",
	"VRD_auxinSelectSettings" : "إعدادات الصوت",
	"VRD_auxinSelectSource" : "الترفيه / تغيير المصدر",
	"VRD_btaudioScanPlay" : "فحص وتشغيل",
	"VRD_btaudioSelectConnect" : "اتصال",
	"VRD_btaudioSelectRootMenu" : "القائمة الجذر",
	"VRD_btaudioSelectSettings" : "تغيير مستوى  الصوت",
	"VRD_btaudioSelectSource" : "الانتقال إلى قائمة الترفيه",
	"VRD_btaudioToggleRepeat" : "تكرار",
	"VRD_btaudioToggleShuffle" : "تبديل",
	"VRD_carplaySelectApplications" : "التطبيقات",
	"VRD_cdGoSettings" : "إعدادات الصوت",
	"VRD_cdHandleStartScan" : "بدء الفحص",
	"VRD_cdPlayBeginning" : "البدء من جديد",
	"VRD_cdRepeatFolder" : "تكرار مجلد",
	"VRD_cdRepeatOff" : "إيقاف التكرار",
	"VRD_cdRepeatOn" : "تشغيل التكرار",
	"VRD_cdRepeatTrack" : "تكرار مسار",
	"VRD_cdSelectCurrentFolder" : "المجلد الحالي",
	"VRD_cdSelectRepeat" : "تكرار",
	"VRD_cdSelectRootFolder" : "القائمة الجذر",
	"VRD_cdSelectShuffle" : "تبديل",
	"VRD_cdSelectSource" : "الانتقال إلى قائمة الترفيه",
	"VRD_cdSelectTrackList" : "قائمة المسار",
	"VRD_cdSelectTrackNumber" : "تشغيل المسار {Number}",
	"VRD_cdShuffleDisk" : "تبديل القرص",
	"VRD_cdShuffleFolder" : "تبديل المجلد",
	"VRD_cdShuffleOff" : "إيقاف التبديل",
	"VRD_cdShuffleOn" : "تشغيل التبديل",
	"VRD_commonAddToFavorites" : "اضف إلى المفضلات",
	"VRD_commonCancel" : "إلغاء",
	"VRD_commonFastForward" : "تقديم سريع",
	"VRD_commonGoBack" : "رجوع",
	"VRD_commonIntentParent" : "ولي أمر",
	"VRD_commonIntentParentUSBAudio" : "ولي أمر",
	"VRD_commonIntentUSBAudio" : "منزل",
	"VRD_commonIntentUSBAudioBG" : "منزل",
	"VRD_commonMenuUp" : "قائمة الاختيار إلى الأعلى",
	"VRD_commonNext" : "التالي",
	"VRD_commonNo" : "لا",
	"VRD_commonPageDown" : "صفحة لأسفل / تمرير لأسفل",
	"VRD_commonPageUp" : "صفحة لأعلى / تمرير لأعلى",
	"VRD_commonPause" : "توقف مؤقت",
	"VRD_commonPrevious" : "سابق",
	"VRD_commonResume" : "تشغيل/ استئناف",
	"VRD_commonRewind" : "إرجاع",
	"VRD_commonSelectLineNumber" : "خط {lineNumber}",
	"VRD_commonYes" : "نعم| موافق",
	"VRD_contactsChooseContactName" : "{ContactName}",
	"VRD_contactsDisambiguateContactName" : "إظهار {ContactName}",
	"VRD_contactsImportAll" : "استيراد جميع جهات الاتصال",
	"VRD_contactsImportCancel" : "ألغ استيراد",
	"VRD_contactsImportContacts" : "تحرير جهات الاتصال",
	"VRD_contactsImportSingle" : "استيراد جهة الاتصال المحددة",
	"VRD_contactsRemoveContact" : "حذف جهة اتصال",
	"VRD_contactsSelectCall" : "اتصال",
	"VRD_contactsSelectContactName" : "{ContactName}",
	"VRD_contactsSelectDownload" : "تنزيل",
	"VRD_contactsSelectFavorites" : "المفضلات",
	"VRD_contactsSelectNone" : "لا شيء من ذلك",
	"VRD_contactsSelectReadContactName" : "قراءة اسم جهة اتصال",
	"VRD_contactsSelectRemove" : "إزالة",
	"VRD_contactsSelectRetry" : "أعد المحاولة",
	"VRD_contactsSendPhoneType" : "{phoneType}",
	"VRD_contactsShowAddress" : "العنوان",
	"VRD_dabDisplayDABSettings" : "إعدادات DAB",
	"VRD_dabDisplayEnsembleList" : "اختر مجموعة",
	"VRD_dabDisplayStationList" : "قائمة المحطة",
	"VRD_dabSelectFavorites" : "المفضلات",
	"VRD_dabSelectScan" : "مسح",
	"VRD_dabSelectSeekNext" : "التالي",
	"VRD_dabSelectSeekPrevious" : "السابق",
	"VRD_dabSelectSettings" : "تغيير مستوى  الصوت",
	"VRD_dabSelectSource" : "الترفيه",
	"VRD_dabTAToggleOFF" : "إيقاف التنقل",
	"VRD_dabTAToggleON" : "تشغيل التنقل",
	"VRD_dabTAToggleVois" : "تنبيه التنقل",
	"VRD_dabUpdateStationList" : "تحديث القائمة",
	"VRD_dvdClearPin" : "حذف أرقام",
	"VRD_dvdSayGRating" : "G",
	"VRD_dvdSayPG12" : "بإرشاد عائلي لمن هم دون 12 سنة",
	"VRD_dvdSayR15" : "توجد مشاهد عنف أو مشاهد جنسية لا تناسب من هم دون سن الخامسة عشر [فأكثر]",
	"VRD_dvdSayR18" : "لا يوجد",
	"VRD_dvdSelectAspectRatio" : "العرض إلى الارتفاع",
	"VRD_dvdSelectAudioSettings" : "إعدادات الفيديو",
	"VRD_dvdSelectCameraAngle" : "زاوية الكاميرا",
	"VRD_dvdSelectEditPin" : "تحرير كود PIN",
	"VRD_dvdSelectParentLock" : "التأمين الأبوي",
	"VRD_dvdSelectParentLockOff" : "إيقاف تشغيل التأمين الأبوي",
	"VRD_dvdSelectParentLockOn" : "تشغيل التأمين الأبوي",
	"VRD_dvdSelectParentLockRating" : "تصنيف التأمين الأبوي",
	"VRD_dvdSelectResetPin" : "إعادة ضبط كود Pin",
	"VRD_dvdSelectRootMenu" : "القائمة الجذر",
	"VRD_dvdSelectSettings" : "إعدادات الصوت",
	"VRD_dvdSelectSource" : "الترفيه",
	"VRD_dvdSelectSubtitleOff" : "إيقاف الترجمة",
	"VRD_dvdSelectSubtitleOn" : "تشغيل الترجمة",
	"VRD_dvdSlowForward" : "تقديم سريع",
	"VRD_dvdSlowRewind" : "إرجاع",
	"VRD_dvdVUISendPin" : "{FourDigitPin}",
	"VRD_emailSelectAllAccounts" : "جميع الحسابات",
	"VRD_emailSelectCall" : "اتصال",
	"VRD_emailSelectContactName" : "{ContactName}",
	"VRD_emailSelectContinueEmail" : "تابع البريد الإلكتروني",
	"VRD_emailSelectDelete" : "حذف",
	"VRD_emailSelectDiscard" : "تجاهل",
	"VRD_emailSelectImportEmail" : "تحديث صندوق الوارد",
	"VRD_emailSelectInbox" : " صندوق الوارد للبريد الإلكتروني",
	"VRD_emailSelectInboxSelector" : "صندوق الوارد",
	"VRD_emailSelectMessage" : "إضافة رسالة",
	"VRD_emailSelectNone" : "لا شيء من ذلك",
	"VRD_emailSelectReply" : "رد",
	"VRD_emailSelectReplyAll" : "رد على الكل",
	"VRD_emailSelectRetry" : "أعد المحاولة",
	"VRD_emailSelectReturn" : "عودة",
	"VRD_emailSelectSend" : "إرسال",
	"VRD_emailSelectSenderName" : "{senderName}",
	"VRD_emnaviAcceptAvoidance" : "تأكيد",
	"VRD_emnaviAddCurrentPosToFavourites" : "إضافة الموقع الحالي إلى المفضلات",
	"VRD_emnaviAddWaypointCityCenter" : "إضافة إحداثية وسط المدينة",
	"VRD_emnaviAddWaypointDistrictCenter" : "إضافة إحداثية وسط المقاطعة",
	"VRD_emnaviAddWaypointFavorite" : "إضافة الإحداثية المفضلة",
	"VRD_emnaviAddWaypointPOI" : "إضافة الإحداثية {poiHypList}",
	"VRD_emnaviAvoidRouteAhead" : "تجنب المسار الأمامي",
	"VRD_emnaviCancelRoute" : "إلغاء المسار",
	"VRD_emnaviDecreaseAvoidanceLength" : "أقل",
	"VRD_emnaviGoToCockpit" : "بدء",
	"VRD_emnaviIncreaseAvoidanceLength" : "أكثر",
	"VRD_emnaviJPJ_VDEHypothesisList" : "اسم مدينة",
	"VRD_emnaviNavigateHere" : "تنقل إلى هنا",
	"VRD_emnaviNavigateHome" : "تنقل إلى الصفحة الرئيسية",
	"VRD_emnaviNavigateToARecentDestination" : "تنقل إلى وجهة حديثة",
	"VRD_emnaviNavigateToAddress" : "تنقل إلى عنوان",
	"VRD_emnaviNavigateToCityCenter" : "تنقل إلى وسط المدينة",
	"VRD_emnaviNavigateToDistrictCenter" : "تنقل إلى وسط المقاطعة",
	"VRD_emnaviNavigateToFavorite" : "تنقل إلى المفضلة",
	"VRD_emnaviNavigateToPOI" : "تنقل إلى {poiHypList}",
	"VRD_emnaviNewDestination" : "وجهة جديدة",
	"VRD_emnaviRepeatInstruction" : "تكرار التعليمات",
	"VRD_emnaviRouteSummary" : "ملخص المسار",
	"VRD_emnaviSelectCancelRoute" : "مسح المسار",
	"VRD_emnaviSelectNavigateToAddress" : "انتقال إلى أحد العناوين",
	"VRD_emnaviSimpleHypothesisList" : "اسم ولاية",
	"VRD_emnaviStepByStep" : "إدخال خطوة بخطوة",
	"VRD_emnaviTravelViaARecentDestination" : "إضافة إحداثية وجهة حديثة",
	"VRD_emnaviTravelViaAddress" : "السفر عبر عنوان",
	"VRD_emnaviTravelViaHome" : "السفر عبر المنزل",
	"VRD_emnaviTryAgain" : "محاولة مرة أخرى",
	"VRD_emnaviUniSimpleHypothesisList" : "عنوان",
	"VRD_emnaviUniVDEHypothesisList" : "عنوان",
	"VRD_emnaviVDEHypothesisList" : "عنوان",
	"VRD_emnaviWhereAmI" : "أين أنا",
	"VRD_emnaviZoomIn" : "تكبير",
	"VRD_emnaviZoomOut" : "تصغير",
	"VRD_fmradioPlayStationFrequency" : "موالفة على {frequency} FM",
	"VRD_fmradioSelectAutoMemory" : "ذاكرة تلقائية",
	"VRD_fmradioSelectChangeGenre" : "نوع التغيير",
	"VRD_fmradioSelectFMSettings" : "إعدادات FM",
	"VRD_fmradioSelectFavorites" : "المفضلات",
	"VRD_fmradioSelectGenreSeek" : "البحث عن النوع",
	"VRD_fmradioSelectHDChannel" : "{HD Channel}",
	"VRD_fmradioSelectHDChannels" : "محطات HD",
	"VRD_fmradioSelectHDRadio" : "راديو HD",
	"VRD_fmradioSelectHDRadioOff" : "إيقاف تشغيل راديو HD",
	"VRD_fmradioSelectHDRadioOn" : "تشغيل راديو HD",
	"VRD_fmradioSelectScanOff" : "إيقاف المسح",
	"VRD_fmradioSelectScanOn" : "تشغيل المسح",
	"VRD_fmradioSelectSeekNext" : "بحث عن التالي",
	"VRD_fmradioSelectSeekPrevious" : "بحث عن السابق",
	"VRD_fmradioSelectSettings" : "تغيير مستوى  الصوت",
	"VRD_fmradioSelectSource" : "الترفيه / تغيير المصدر",
	"VRD_fmradioSelectStationAll" : "جميع المحطات",
	"VRD_fmradioSelectStationFrequency" : "{frequency}",
	"VRD_fmradioSelectStationGenre" : "{genreName}",
	"VRD_fmradioSelectStationList" : "قائمة المحطة",
	"VRD_fmradioSelectStationName" : "{stationName}",
	"VRD_fmradioSelectTrafficAlert" : "تنبيه التنقل",
	"VRD_fmradioSelectTrafficAlertOff" : "إيقاف المرور",
	"VRD_fmradioSelectTrafficAlertOn" : "تشغيل المرور",
	"VRD_fmradioSelectTune" : "تغيير الموجات",
	"VRD_fmradioSelectUpdateAutoMemory" : "تحديث الذاكرة التلقائية",
	"VRD_fmradioSelectiTunesTagging" : "علامات iTunes",
	"VRD_fmradioTuneDown" : "توليف لأسفل",
	"VRD_fmradioTuneUp" : "توليف لأعلى",
	"VRD_fmradioTurnOffAF" : " إيقاف التردد البديل ",
	"VRD_fmradioTurnOffREG" : "إيقاف قفل المنطقة",
	"VRD_fmradioTurnOnAF" : " تشغيل التردد البديل ",
	"VRD_fmradioTurnOnREG" : "تشغيل قفل المنطقة",
	"VRD_fmradioUpdateAutoMemory" : "تحديث قائمة المحطات",
	"VRD_pandoraAddStation" : "إضافة محطة",
	"VRD_pandoraAddStationFromArtist" : "إنشاء محطة من الفنان",
	"VRD_pandoraAddStationFromSong" : "إنشاء محطة من أغنية",
	"VRD_pandoraAddToFavorites" : "إضافة إلى المفضلات",
	"VRD_pandoraBookmarkArtist" : "وضع علامة مرجعية للفنان",
	"VRD_pandoraBookmarkSong" : "وضع علامة مرجعية للأغنية",
	"VRD_pandoraCreateStation" : "إنشاء محطة",
	"VRD_pandoraSelectAddCurrentStation" : "إضافة إلى التفضيلات",
	"VRD_pandoraSelectDelete" : "حذف",
	"VRD_pandoraSelectEditDelete" : "حذف",
	"VRD_pandoraSelectEditMove" : "النقل",
	"VRD_pandoraSelectEditReplace" : "الاستبدال",
	"VRD_pandoraSelectFavorites" : "المفضلات",
	"VRD_pandoraSelectMove" : "النقل",
	"VRD_pandoraSelectQuickMix" : "تبديل",
	"VRD_pandoraSelectSettings" : "تغيير مستوى  الصوت",
	"VRD_pandoraSelectSortBy" : "فرز",
	"VRD_pandoraSelectSource" : "الترفيه",
	"VRD_pandoraSelectStationList" : "قائمة المحطة",
	"VRD_pandoraShowBookmarkOptions" : "علامة مرجعية",
	"VRD_pandoraShowByAZ" : "فرز أبجديًا",
	"VRD_pandoraShowByDate" : "فرز حسب التاريخ",
	"VRD_pandoraSkip" : "تخطي",
	"VRD_pandoraThumbsDown" : "إبهام إلى لأسفل",
	"VRD_pandoraThumbsUp" : "إبهام إلى لأعلى",
	"VRD_phoneCall" : "اتصال",
	"VRD_phoneCallBack" : "معاودة الاتصال",
	"VRD_phoneCallByName" : "الاتصال حسب الاسم",
	"VRD_phoneCallByNumber" : "اتصال حسب الرقم",
	"VRD_phoneCallContactType" : "مكالمة {contactName}{contactType}",
	"VRD_phoneCallLast" : "الاتصال بالرقم الأخير",
	"VRD_phoneChooseContactType" : "{contactName} {contactType}",
	"VRD_phoneDialAnyNumber" : "اتصال{number}",
	"VRD_phoneDialpadClearAllDigits" : "مسح جميع الأرقام",
	"VRD_phoneDialpadDeleteDigit" : "حذف",
	"VRD_phoneDialpadPhoneNumber" : "{phoneNumber}",
	"VRD_phoneReDial" : "إعادة الاتصال",
	"VRD_phoneSelectByName" : "الاسم",
	"VRD_phoneSelectByNumber" : "الرقم",
	"VRD_phoneSelectContactType" : "{contactType}",
	"VRD_phoneSelectDialPad" : "لوحة الاتصال",
	"VRD_phoneSelectFavorites" : "المفضلات",
	"VRD_phoneSelectRecentCalls" : "المكالمات الحديثة",
	"VRD_phoneSelectRecentCallsAll" : "جميع المكالمات",
	"VRD_phoneSelectRecentCallsMissed" : "المكالمات الفائتة",
	"VRD_satradioBackSpaceDelete" : "حذف أرقام",
	"VRD_satradioChangeLockCode" : "تغيير رمز PIN",
	"VRD_satradioEnterPIN" : "{4digitPin}",
	"VRD_satradioInitializeLockCode" : "تهيئة كود PIN",
	"VRD_satradioPlayChannelName" : "تشغيل {channelName}",
	"VRD_satradioPlayStationNumber" : "توليف على {channelNumber}",
	"VRD_satradioResetLockCode" : "إعادة ضبط كود Pin",
	"VRD_satradioSeekNext" : "بحث عن التالي",
	"VRD_satradioSeekPrevious" : "بحث عن السابق",
	"VRD_satradioSelectChangeCategory" : "الفئة",
	"VRD_satradioSelectFavorites" : "المفضلات",
	"VRD_satradioSelectParentalLock" : "التأمين الأبوي",
	"VRD_satradioSelectScanOff" : "إيقاف المسح",
	"VRD_satradioSelectScanOn" : "تشغيل المسح",
	"VRD_satradioSelectSettings" : "إعدادات الصوت",
	"VRD_satradioSelectSource" : "الترفيه",
	"VRD_satradioSelectStation" : "المحطة {Station number}",
	"VRD_satradioSelectStationAll" : "جميع القنوات",
	"VRD_satradioSelectStationCategory" : "{categoryName}",
	"VRD_satradioSelectStationList" : "قائمة القنوات",
	"VRD_satradioTurnChannelLockOFF" : "إلغاء تأمين القناة الحالية",
	"VRD_satradioTurnChannelLockON" : "تأمين القناة الحالية",
	"VRD_satradioTurnParentalLockOFF" : "إيقاف تأمين الجلسة",
	"VRD_satradioTurnParentalLockON" : "تشغيل تأمين الجلسة",
	"VRD_smsCallPhoneNumber" : "اتصال",
	"VRD_smsDelete" : "حذف",
	"VRD_smsImportMessages" : "تحديث صندوق النص الوارد",
	"VRD_smsReply" : "رد",
	"VRD_smsSayAnyConversation" : "{senderName}",
	"VRD_smsSelectBody" : "إضافة رسالة",
	"VRD_smsSelectContactName" : "{ContactName}",
	"VRD_smsSelectContinueTextMessage" : "تابع الرسالة",
	"VRD_smsSelectDiscard" : "تجاهل",
	"VRD_smsSelectInbox" : "قائمة علبة وارد الرسائل القصيرة",
	"VRD_smsSelectNone" : "لا شيء من ذلك",
	"VRD_smsSelectRetry" : "أعد المحاولة",
	"VRD_smsSelectReturn" : "عودة",
	"VRD_smsSelectSend" : "إرسال",
	"VRD_stitcherAddToFavorites" : "إضافة إلى المفضلات",
	"VRD_stitcherRemoveFromFavorites" : "احذف من المفضلات",
	"VRD_stitcherSaveFavorites" : "حفظ التغييرات",
	"VRD_stitcherSelectSettings" : "إعدادات الصوت",
	"VRD_stitcherSelectSource" : "الترفيه",
	"VRD_stitcherSelectStationList" : "قائمة المحطة",
	"VRD_stitcherThumbsDown" : "إبهام إلى الأسفل",
	"VRD_stitcherThumbsUp" : "إبهام إلى الأعلى",
	"VRD_systemSelectAhaRadio" : "Aha Radio",
	"VRD_systemSelectAndroidAuto" : "Android Auto",
	"VRD_systemSelectApplications" : "التطبيقات",
	"VRD_systemSelectAuxIn" : "دخل الخط / AUX",
	"VRD_systemSelectBTAudio" : "Bluetooth",
	"VRD_systemSelectCD" : "CD",
	"VRD_systemSelectCallHistory" : "سجل المكالمة",
	"VRD_systemSelectCarPlay" : "Apple CarPlay",
	"VRD_systemSelectCommunication" : "الاتصالات",
	"VRD_systemSelectConnect" : "اتصال",
	"VRD_systemSelectContacts" : "جهات الاتصال",
	"VRD_systemSelectDAB" : "DAB",
	"VRD_systemSelectDVD" : "DVD",
	"VRD_systemSelectDisplayClock" : "عرض الساعة",
	"VRD_systemSelectDisplayOff" : "إيقاف العرض",
	"VRD_systemSelectEmail" : "بريد إلكتروني",
	"VRD_systemSelectEntertainment" : "الترفيه",
	"VRD_systemSelectEntertainmentMenu" : "قائمة الترفيه",
	"VRD_systemSelectFavorites" : "المفضلات",
	"VRD_systemSelectNavigation" : "التنقل",
	"VRD_systemSelectNotifications" : "رسائل",
	"VRD_systemSelectNotifyOff" : "إبطال الإخطار",
	"VRD_systemSelectPandora" : "Pandora",
	"VRD_systemSelectPhone" : "إطـلاق",
	"VRD_systemSelectRadioAM" : "راديو AM",
	"VRD_systemSelectRadioFM" : "راديو FM",
	"VRD_systemSelectRetry" : "أعد المحاولة",
	"VRD_systemSelectSatRadio" : "راديو أقمار صناعية",
	"VRD_systemSelectSettings" : "الإعدادات",
	"VRD_systemSelectSiri" : "Siri",
	"VRD_systemSelectSms" : "نص / رسائل قصيرة",
	"VRD_systemSelectStitcher" : "Stitcher",
	"VRD_systemSelectTV" : "TV",
	"VRD_systemSelectTrafficAlert" : "تنبيه التنقل",
	"VRD_systemSelectTutorial" : "برامج تعليمية",
	"VRD_systemSelectUSB" : "USB",
	"VRD_systemSelectUSBA" : "USB 1",
	"VRD_systemSelectUSBB" : "USB 2",
	"VRD_systemSelectXmAudio" : "SXM Radio",
	"VRD_tvSelectView" : "عرض",
	"VRD_usbaudioBrowse" : "استعراض",
	"VRD_usbaudioBrowseAlbum" : "استعرض {albumName}",
	"VRD_usbaudioBrowseAlbums" : "استعراض ألبوم",
	"VRD_usbaudioBrowseAll" : "استعراض كل الأغاني أو الألبومات أو الفنانين",
	"VRD_usbaudioBrowseAnyAlbum" : "استعراض ألبوم {albumName}",
	"VRD_usbaudioBrowseAnyArtist" : "استعراض [الفنان] {artistName}",
	"VRD_usbaudioBrowseAnyFolder" : "استعراض مجلد{folderName}",
	"VRD_usbaudioBrowseArtist" : "استعرض {artistName}",
	"VRD_usbaudioBrowseArtists" : "استعراض الفنان",
	"VRD_usbaudioBrowseAudiobooks" : "استعراض الكتب الصوتية",
	"VRD_usbaudioBrowseFolder" : "استعرض {folderName}",
	"VRD_usbaudioBrowseFolders" : "استعراض مجلد",
	"VRD_usbaudioBrowseGenre" : "استعراض النوع {genreName}",
	"VRD_usbaudioBrowseGenres" : "استعراض نوع",
	"VRD_usbaudioBrowseLineNumber" : "استعرض {lineNumber}",
	"VRD_usbaudioBrowsePlaylist" : "استعراض قائمة التشغيل {playlistName}",
	"VRD_usbaudioBrowsePlaylists" : "استعراض قائمة التشغيل",
	"VRD_usbaudioBrowsePodcast" : "استعراض البودكاست{podcastName}",
	"VRD_usbaudioBrowsePodcasts" : "استعراض البودكاست",
	"VRD_usbaudioBrowseSongs" : "استعرض الأغاني",
	"VRD_usbaudioChooseAlbumArtist" : "{artistName}",
	"VRD_usbaudioGenerateMoreLikeThis" : "المزيد مما يشابه ذلك",
	"VRD_usbaudioPlayAlbums" : "تشغيل ألبوم",
	"VRD_usbaudioPlayAll" : "تشغيل الكل",
	"VRD_usbaudioPlayAnyAlbum" : "تشغيل [ألبوم] {albumName}",
	"VRD_usbaudioPlayAnyArtist" : "تشغيل فنان{artistName}",
	"VRD_usbaudioPlayAnyFolder" : "تشغيل المجلد{folderName}",
	"VRD_usbaudioPlayArtistAlbum" : "تشغيل {artistName}{albumName}",
	"VRD_usbaudioPlayArtists" : "تشغيل فنان",
	"VRD_usbaudioPlayAudiobook" : "تشغيل الكتب الصوتية {AudiobookName}",
	"VRD_usbaudioPlayAudiobooks" : "تشغيل الكتب الصوتية",
	"VRD_usbaudioPlayChapter" : "{chapterName}",
	"VRD_usbaudioPlayChapterIndex" : "تشغيل الفصل {chapter}{index}",
	"VRD_usbaudioPlayEpisode" : "{episodeName}",
	"VRD_usbaudioPlayFolder" : "بدء الاستماع{folderName}",
	"VRD_usbaudioPlayFolders" : "تشغيل المجلد",
	"VRD_usbaudioPlayGenre" : "تشغيل [النوع] {genreName}",
	"VRD_usbaudioPlayGenres" : "تشغيل النوع",
	"VRD_usbaudioPlayLineNumber" : "تشغيل [الخط] {lineNumber}",
	"VRD_usbaudioPlayPlaylist" : "تشغيل قائمة التشغيل{playlistName}",
	"VRD_usbaudioPlayPlaylists" : "تشغيل قائمة التشغيل",
	"VRD_usbaudioPlayPodcast" : "تشغيل البودكاست {PodcastName}",
	"VRD_usbaudioPlayPodcasts" : "تشغيل البودكاست",
	"VRD_usbaudioPlaySongs" : "تشغيل أغنية",
	"VRD_usbaudioRepeat" : "تكرار",
	"VRD_usbaudioRepeatAll" : "تكرار الكل",
	"VRD_usbaudioRepeatOff" : "تكرار متوقف",
	"VRD_usbaudioRepeatSong" : "تكرار الأغنية",
	"VRD_usbaudioRewind" : "إرجاع",
	"VRD_usbaudioSelectAlbum" : "ألبوم{albumName}",
	"VRD_usbaudioSelectAlbums" : "ألبوم",
	"VRD_usbaudioSelectAll" : "استعراض كل الحلقات أو الفصول أو الأغاني أو الألبومات أو الفنانين",
	"VRD_usbaudioSelectArtist" : "فنان{artistName}",
	"VRD_usbaudioSelectArtists" : "فنان",
	"VRD_usbaudioSelectAudiobook" : "{audiobookName}",
	"VRD_usbaudioSelectAudiobooks" : "الكتب الصوتية",
	"VRD_usbaudioSelectFolder" : "المجلد{folderName}",
	"VRD_usbaudioSelectFolders" : "المجلدات",
	"VRD_usbaudioSelectGenre" : "النوع {genreName}",
	"VRD_usbaudioSelectGenres" : "النوع",
	"VRD_usbaudioSelectPlaylist" : "قائمة التشغيل {playlistName}",
	"VRD_usbaudioSelectPlaylists" : "قائمة التشغيل",
	"VRD_usbaudioSelectPodcast" : "{podcastName}",
	"VRD_usbaudioSelectPodcasts" : "بودكاست",
	"VRD_usbaudioSelectRootFolder" : "القائمة الجذر",
	"VRD_usbaudioSelectSettings" : "إعدادات الصوت",
	"VRD_usbaudioSelectSongs" : "أغنية",
	"VRD_usbaudioSelectSourceMenu" : "الترفيه",
	"VRD_usbaudioShuffle" : "تبديل",
	"VRD_usbaudioShuffleOff" : "إيقاف التبديل",
	"VRD_usbaudioShuffleOn" : "تشغيل التبديل",
	"VRD_usbaudioSongList" : "قائمة الأغاني",
	"VRD_xmaudioBackSpaceDelete" : "حذف أرقام",
	"VRD_xmaudioChangeLockCode" : "تحرير كود PIN",
	"VRD_xmaudioConfirmDelete" : "حذف",
	"VRD_xmaudioEnterPIN" : "{fourDigitPIN}",
	"VRD_xmaudioPlayChannelName" : "تشغيل قناة XM{channelName}",
	"VRD_xmaudioPlayStationNumber" : "توليف على {channelNumber}",
	"VRD_xmaudioResetLockCode" : "إعادة ضبط كود Pin",
	"VRD_xmaudioSelectCallXM" : "الاتصال بـ XM",
	"VRD_xmaudioSelectChangeCategory" : "تغيير الفئة",
	"VRD_xmaudioSelectContinueListening" : "مواصلة الاستماع",
	"VRD_xmaudioSelectDismiss" : "صرف",
	"VRD_xmaudioSelectEveryOccurance" : "كل حدوث",
	"VRD_xmaudioSelectEveryOtherReport" : "كل التقارير الأخرى",
	"VRD_xmaudioSelectEveryReport" : "كل التقارير",
	"VRD_xmaudioSelectExitTuneMix" : "تحرير TuneMix",
	"VRD_xmaudioSelectFavorites" : "المفضلات",
	"VRD_xmaudioSelectListenNow" : "الاستماع الآن",
	"VRD_xmaudioSelectMove" : "النقل",
	"VRD_xmaudioSelectNearestCity" : "أقرب مدينة",
	"VRD_xmaudioSelectOnlyFirstAfterVehicleStart" : "بدء تشغيل المركبة",
	"VRD_xmaudioSelectOnlyFirstOccuranceInGame" : "أول حدوث",
	"VRD_xmaudioSelectReplayAlert" : "تنبيه إعادة التشغيل",
	"VRD_xmaudioSelectReturnToPrevious" : "عودة إلى السابق",
	"VRD_xmaudioSelectSFSportBaseball" : "بيسبول",
	"VRD_xmaudioSelectSFSportNCAA" : "كرة القدم الجامعية",
	"VRD_xmaudioSelectSFSportNFL" : "كرة القدم الاحترافية",
	"VRD_xmaudioSelectSFSportNHL" : "هوكي",
	"VRD_xmaudioSelectScanOff" : "إيقاف المسح",
	"VRD_xmaudioSelectScanOn" : "تشغيل المسح",
	"VRD_xmaudioSelectSettings" : "الإعدادات",
	"VRD_xmaudioSelectSoundSettings" : "إعدادات الصوت",
	"VRD_xmaudioSelectSource" : "ترفيه",
	"VRD_xmaudioSelectStation" : "محطة {channelNumber}",
	"VRD_xmaudioSelectStationAll" : "جميع القنوات",
	"VRD_xmaudioSelectStationCategory" : "{categoryName}",
	"VRD_xmaudioSelectStationFeaturedFavorites" : "المفضلات المميزة",
	"VRD_xmaudioSelectStationList" : "القنوات",
	"VRD_xmaudioSelectTuneMix" : "TuneMix",
	"VRD_xmaudioSelectTuneMixChannel" : "خيارات قناة TuneMix",
	"VRD_xmaudioSelectTuneMixChannelsOptions" : "خيارات القناة",
	"VRD_xmaudioSelectTuneMixCreation" : "إنشاء قناة TuneMix جديدة",
	"VRD_xmaudioSelectTuneMixEdit" : "تحرير قناة TuneMix",
	"VRD_xmaudioSelectTuneMixEditOps" : "خيارات تحرير TuneMix",
	"VRD_xmaudioSelectTuneMixRemove" : "إزالة قناة TuneMix",
	"VRD_xmaudioSelectTuneMixRename" : "إعادة تسمية TuneMix",
	"VRD_xmaudioSelectTurnAlertsOff" : "إيقاف التنبيهات",
	"VRD_xmaudioSelectiTunesTagging" : "علامات iTunes",
	"VRD_xmaudioSetChannelLock" : "تأمين القناة",
	"VRD_xmaudioSetParentalLock" : "تأمين الجلسة",
	"VRD_xmdataSelectFuelPrices" : "أسعار الوقود",
	"VRD_xmdataSelectMovies" : "أفلام",
	"VRD_xmdataSelectParking" : "موقف سيارات",
	"VRD_xmdataSelectSports" : "رياضة",
	"VRD_xmdataSelectStock" : "الأسهم",
	"VRD_xmdataSelectTrafficPlus" : "التنقل الإضافي",
	"VRD_xmdataSelectWeatherForecast" : "توقعات الطقس",
	"VRD_xmdataSelectWeatherRadar" : "رادار الطقس",
	"VRD_xmdataSelectWeatherSecurityAlerts" : "تنبيهات أمان الطقس",
};

framework.registerAppDictLoaded("system", "ar_SA");