var __VrHelpPositionTable__systemAppDict_es_MX = {
	"HomeScreen_Help" : {
		"Right" : ["VrHelp_Favorites"],
		"Left" : ["VrHelp_Entertainment","VrHelp_Communication","VrHelp_Navigation","VrHelp_Settings","VrHelp_Applications"]
	}
};

var Localization_systemAppDict_es_MX = {
	//"stringId" : "localString"
	"ActiveCallItem" : "Llamada Activa",
	"AhaMaintError" : "Error de mantenimiento aha",
	"AhaRadio" : "aha",
	"AmRadio" : "AM",
	"AndroidAuto" : "Android Auto",
	"Applications" : "Aplicaciones",
	"AudioSourceNotAvailableBTAudio" : "Audio de Bluetooth No Disponible",
	"AudioSourceNotAvailableCD" : "CD ha sido eliminado",
	"AudioSourceNotAvailableDVD" : "DVD ha sido eliminado",
	"AudioSourceNotAvailableTV" : "No hay TV disponible",
	"AudioSourceNotAvailableUSB" : "El dispositivo USB ha cambiado",
	"AuxIn" : "AUX",
	"BT" : "BT",
	"Bluetooth" : "Bluetooth",
	"BluetoothWithDevice" : "Bluetooth - {deviceName}",
	"CallHistory" : "Historial de Llamadas",
	"CarPlay" : "Apple CarPlay",
	"CdPlayer" : "CD",
	"ChannelOffAir" : "Canal fuera del área",
	"ChannelUnauth" : "Canal no autorizado",
	"CheckAntenna" : "Revisar antena",
	"CheckTuner" : "Revisar sintonizador",
	"Communication" : "Comunicación",
	"Connect" : "Conectar",
	"Contacts" : "Contactos",
	"DVDItem" : "DVD",
	"DabRadio" : "DAB",
	"DialPhone" : "Marcar Teléfono",
	"DidYouSay" : "Quiso decir. . .",
	"DisclaimerText" : "Las distracciones pueden causar accidentes. No maneje sus dispositivos mientras conduzca. Concéntrese en conducir y cumpla las reglas de tráfico. Vea manual de usuario",
	"DisconnectThenReconnect" : "Error al iniciar Siri. Desconecte y vuelva a conectar el dispositivo Apple.",
	"DriveRecord" : "Registro de conducción",
	"DriverIDItem" : "Selección Conductor",
	"EcoenergyApp" : "Ahorro de Combustible",
	"EcoenergyAppHEV" : "Monitor conducción",
	"Email" : "Email",
	"EngineOilLevel" : "Niv. de aceite del mot.",
	"Entertainment" : "Entretenimiento",
	"ErrorWhileStartingSiri" : "Error al iniciar Siri.",
	"FailedNotificationRetrieval" : "No se puede recuperar la Lista de Notificaciones",
	"FavoritesItem" : "Favoritos",
	"FmRadio" : "FM",
	"HDTrafficItem" : "Mapa de Tráfico HD Radio™",
	"InitiateSiri" : "Presione de forma prolongada el botón Hablar para iniciar una sesión de Siri",
	"IntelligentDriveMasterItem" : "i-DM",
	"NavigationTitle" : "Navegación",
	"NoConnectionNotifyText" : "¿Desea conectar un teléfono ahora?",
	"NoConnectionNotifyTitle" : "No hay Teléfono Conectado",
	"NoDeviceText" : "¿Desea conectar un dispositivo ahora?",
	"NoDeviceTitle" : "No hay ningún Dispositivo Conectado",
	"Notifications" : "Notificaciones",
	"NotifyIgnore" : "Ignorar",
	"NotifyIncomingMsg" : "Mensaje Entrante de:",
	"NotifyOff" : "Notif. Off",
	"NotifyRead" : "Lectura",
	"NotifyReadNow" : "¿Desea leerlo ahora?",
	"Pandora" : "Pandora",
	"ReconnectAhaRadio" : "Reconect.audio Bluetooth Radio aha",
	"ReconnectBTAudio" : "Recn.audio Bluetooth reanudar reprod.",
	"ReconnectCD" : "Verificando CD reanudar reproduc.",
	"ReconnectCarPlay" : "Reanudación de Apple Carplay.",
	"ReconnectDVD" : "Verificando DVD reanudar reproduc.",
	"ReconnectEntMenuButton" : "Menú entretenimiento",
	"ReconnectFailedBTAudio" : "No se puede Volver a Conectar el Audio de Bluetooth.",
	"ReconnectFailedCD" : "CD ha sido eliminado. No se puede reanudar la reproducción.",
	"ReconnectFailedCarPlay" : "No se puede volver a conectar Apple CarPlay",
	"ReconnectFailedDVD" : "DVD ha sido eliminado. No se puede reanudar la reproducción.",
	"ReconnectFailedTV" : "No hay TV disponible. No se puede resumir la reproducción.",
	"ReconnectFailedUSB" : "El dispositivo USB ha cambiado No se puede reanudar la reproducción.",
	"ReconnectPandora" : "Reconect.audio Bluetooth Pandora",
	"ReconnectStitcher" : "Reconect.audio Bluetooth Stitcher",
	"ReconnectTV" : "Verificando la TV para continuar la reproducción",
	"ReconnectUSB" : "Reconect.USB reanudar reproducc.",
	"RetryLabel" : "Reintentar",
	"SchedMaintenanceApp" : "Mantenimiento",
	"ScreenReplication" : "Reproducción de la pantalla",
	"SdarsRadio" : "XM",
	"Settings" : "Configuraciones",
	"SettingsCommunication" : "Configuraciones",
	"Siri" : "Siri",
	"SiriDisabled" : "Siri está desactivado en el dispositivo Apple.",
	"Sms" : "SMS",
	"StitcherItem" : "Stitcher",
	"TVItem" : "TV",
	"TempWarning" : "Advertencia de Temperatura",
	"TempWarningText" : "La pantalla está muy caliente.  El rendimiento de la pantalla puede disminuir hasta que enfríe.",
	"TextDownloaded" : "SMS descargado",
	"TextSent" : "SMS enviado",
	"TrafficAlertsItem" : "Información de Tráfico",
	"USB" : "USB",
	"USB1AndroidAuto" : "USB 1: Android Auto",
	"USB1CarPlay" : "USB 1: Apple CarPlay",
	"USB2AndroidAuto" : "USB 2: Android Auto",
	"UsbAudioA" : "USB 1",
	"UsbAudioAWithDevice" : "USB 1 - {deviceName}",
	"UsbAudioB" : "USB 2",
	"UsbAudioBWithDevice" : "USB 2 - {deviceName}",
	"UseCommander" : "Usar el botón comandante mientras conduce.",
	"VehicleDataTransferItem" : "Transf Datos de Vehículo ",
	"VehicleStatusMonitor" : "Monitor est.vehículo",
	"VehicleTelemetryTransfer" : "Transf. de información",
	"VideoSignalLost" : "Señal de vídeo perdida",
	"VoiceNotSupported" : "Voz no soportado ",
	"VoiceRecognition" : "Reconocimiento de voz",
	"VrHelp_Applications" : "Aplicaciones",
	"VrHelp_Communication" : "Comunicación",
	"VrHelp_Entertainment" : "Entretenimiento",
	"VrHelp_Favorites" : "Favoritos",
	"VrHelp_Navigation" : "Navegación",
	"VrHelp_Settings" : "Configuraciones",
	"WarnGuidanceApp" : "Guía de advertencia",
	"WarningTitle" : "¡ADVERTENCIA!",
	"XMAudio" : "SXM",
	"XMData" : "Servicios XM",
	"agree" : "Estoy de Acuerdo",
	"VRD_aharadioSelectCall" : "Llamar",
	"VRD_aharadioSelectDiscard" : "Descartar",
	"VRD_aharadioSelectEpisodes" : "Lista de episodios",
	"VRD_aharadioSelectLBSTab" : "Cerca",
	"VRD_aharadioSelectMainList" : "Lista principal de Aha",
	"VRD_aharadioSelectMap" : "Mapa",
	"VRD_aharadioSelectPresetsTab" : "Preajuste",
	"VRD_aharadioSelectSave" : "Guardar",
	"VRD_aharadioSelectSettings" : "Ajustes de sonido",
	"VRD_aharadioSelectShout" : "Comando de voz",
	"VRD_aharadioSelectSource" : "Entretenimiento / Cambiar fuente",
	"VRD_aharadioSelectThumbsDown" : "No me gusta",
	"VRD_aharadioSelectThumbsUp" : "Me gusta",
	"VRD_amradioPlayStationFrequency" : "Sintonizar AM {frequency}",
	"VRD_amradioSelectAutoMemory" : "Memoria automática",
	"VRD_amradioSelectFavorites" : "Favoritos",
	"VRD_amradioSelectHD" : "Emisoras HD Radio",
	"VRD_amradioSelectHDOff" : "HD Radio apagada",
	"VRD_amradioSelectHDOn" : "HD Radio encendida",
	"VRD_amradioSelectScanOff" : "Exploración desactivada",
	"VRD_amradioSelectScanOn" : "Exploración activada",
	"VRD_amradioSelectSeekNext" : "Buscar siguiente",
	"VRD_amradioSelectSeekPrevious" : "Buscar anterior",
	"VRD_amradioSelectSettings" : "Ajustes de sonido",
	"VRD_amradioSelectSource" : "Ir a Menú de entretenimiento",
	"VRD_amradioSelectStationFrequency" : "{AMFrequency}",
	"VRD_amradioSelectTrafficAlert" : "Alerta de tráfico",
	"VRD_amradioSelectTrafficAlertOff" : "Alerta de tráfico desactivada",
	"VRD_amradioSelectTrafficAlertOn" : "Alerta de tráfico activada",
	"VRD_amradioSelectTune" : "Sintonizar",
	"VRD_amradioSelectUpdateAutoMemory" : "Buscar en memoria automática",
	"VRD_amradioSelectiTunesTagging" : "Etiquetado de iTunes",
	"VRD_amradioTuneDown" : "Sintonizar Abajo",
	"VRD_amradioTuneUp" : "Sintonizar Arriba",
	"VRD_amradioUpdateAutoMemory" : "Actualizar lista de emisoras",
	"VRD_auxinSelectSettings" : "Ajustes de sonido",
	"VRD_auxinSelectSource" : "Entretenimiento / Cambiar fuente",
	"VRD_btaudioScanPlay" : "Explorar reproducción",
	"VRD_btaudioSelectConnect" : "Conectar",
	"VRD_btaudioSelectRootMenu" : "Menú raíz",
	"VRD_btaudioSelectSettings" : "Ajustes de sonido",
	"VRD_btaudioSelectSource" : "Ir a Menú Entretenimiento",
	"VRD_btaudioToggleRepeat" : "Repetir",
	"VRD_btaudioToggleShuffle" : "Aleatorio",
	"VRD_carplaySelectApplications" : "Aplicaciones",
	"VRD_cdGoSettings" : "Ajustes de sonido",
	"VRD_cdHandleStartScan" : "Comenzar exploración",
	"VRD_cdPlayBeginning" : "Iniciar de nuevo",
	"VRD_cdRepeatFolder" : "Repetir carpeta",
	"VRD_cdRepeatOff" : "Repetición apagada",
	"VRD_cdRepeatOn" : "Repetir encendido",
	"VRD_cdRepeatTrack" : "Repetir pista",
	"VRD_cdSelectCurrentFolder" : "Carpeta actual",
	"VRD_cdSelectRepeat" : "Repetir",
	"VRD_cdSelectRootFolder" : "Menú raíz",
	"VRD_cdSelectShuffle" : "Aleatorio",
	"VRD_cdSelectSource" : "Ir a Menú de entretenimiento",
	"VRD_cdSelectTrackList" : "Lista de pistas",
	"VRD_cdSelectTrackNumber" : "Reproducir pista {Number}",
	"VRD_cdShuffleDisk" : "Disco aleatorio",
	"VRD_cdShuffleFolder" : "Carpeta aleatoria",
	"VRD_cdShuffleOff" : "Aleatorio apagado",
	"VRD_cdShuffleOn" : "Aleatorio Encendido",
	"VRD_commonAddToFavorites" : "Añadir a Favoritos",
	"VRD_commonCancel" : "Cancelar",
	"VRD_commonFastForward" : "Avance rápido",
	"VRD_commonGoBack" : "Volver atrás",
	"VRD_commonIntentParent" : "Parental",
	"VRD_commonIntentParentUSBAudio" : "Parental",
	"VRD_commonIntentUSBAudio" : "De local",
	"VRD_commonIntentUSBAudioBG" : "De local",
	"VRD_commonMenuUp" : "Menú arriba",
	"VRD_commonNext" : "Siguiente",
	"VRD_commonNo" : "No",
	"VRD_commonPageDown" : "Página hacia abajo / Desplazar hacia abajo",
	"VRD_commonPageUp" : "Página hacia arriba / Desplazar hacia arriba",
	"VRD_commonPause" : "Pausa",
	"VRD_commonPrevious" : "Anterior",
	"VRD_commonResume" : "Reproducir / Reanudar",
	"VRD_commonRewind" : "Rebobinar",
	"VRD_commonSelectLineNumber" : "Línea {lineNumber}",
	"VRD_commonYes" : "Sí / OK",
	"VRD_contactsChooseContactName" : "{ContactName}",
	"VRD_contactsDisambiguateContactName" : "Mostrar {ContactName}",
	"VRD_contactsImportAll" : "Importar todos los contactos",
	"VRD_contactsImportCancel" : "Cancelar importación",
	"VRD_contactsImportContacts" : "Editar contactos",
	"VRD_contactsImportSingle" : "Importar contacto seleccionado",
	"VRD_contactsRemoveContact" : "Eliminar contacto",
	"VRD_contactsSelectCall" : "Llamar",
	"VRD_contactsSelectContactName" : "{ContactName}",
	"VRD_contactsSelectDownload" : "Descargar",
	"VRD_contactsSelectFavorites" : "Favoritos",
	"VRD_contactsSelectNone" : "Ninguno de los anteriores",
	"VRD_contactsSelectReadContactName" : "Leer el nombre del contacto",
	"VRD_contactsSelectRemove" : "Eliminar",
	"VRD_contactsSelectRetry" : "Reintentar",
	"VRD_contactsSendPhoneType" : "{phoneType}",
	"VRD_contactsShowAddress" : "Dirección",
	"VRD_dabDisplayDABSettings" : "Configuración de DAB",
	"VRD_dabDisplayEnsembleList" : "Seleccione un grupo",
	"VRD_dabDisplayStationList" : "Lista de emisoras",
	"VRD_dabSelectFavorites" : "Favoritos",
	"VRD_dabSelectScan" : "Explorar",
	"VRD_dabSelectSeekNext" : "Siguiente",
	"VRD_dabSelectSeekPrevious" : "Anterior",
	"VRD_dabSelectSettings" : "Ajustes de sonido",
	"VRD_dabSelectSource" : "Entretenimiento",
	"VRD_dabTAToggleOFF" : "Tráfico apagado",
	"VRD_dabTAToggleON" : "Tráfico encendido",
	"VRD_dabTAToggleVois" : "Anuncio de tráfico (TA)",
	"VRD_dabUpdateStationList" : "Actualizar lista",
	"VRD_dvdClearPin" : "Eliminar dígitos",
	"VRD_dvdSayGRating" : "APT",
	"VRD_dvdSayPG12" : "ATP C/R",
	"VRD_dvdSayR15" : "+15",
	"VRD_dvdSayR18" : "Ninguno",
	"VRD_dvdSelectAspectRatio" : "Relación de aspecto",
	"VRD_dvdSelectAudioSettings" : "Ajustes de vídeo",
	"VRD_dvdSelectCameraAngle" : "Ángulo de cámara",
	"VRD_dvdSelectEditPin" : "Editar Código PIN",
	"VRD_dvdSelectParentLock" : "Bloqueo parental",
	"VRD_dvdSelectParentLockOff" : "Bloqueo parental apagado",
	"VRD_dvdSelectParentLockOn" : "Bloqueo parental encendido",
	"VRD_dvdSelectParentLockRating" : "Clasificación de bloqueo parental",
	"VRD_dvdSelectResetPin" : "Restablecer código pin",
	"VRD_dvdSelectRootMenu" : "Menú raíz",
	"VRD_dvdSelectSettings" : "Ajustes de sonido",
	"VRD_dvdSelectSource" : "Entretenimiento",
	"VRD_dvdSelectSubtitleOff" : "Subtítulos desactivados",
	"VRD_dvdSelectSubtitleOn" : "Subtítulos activados",
	"VRD_dvdSlowForward" : "Avance rápido",
	"VRD_dvdSlowRewind" : "Rebobinar",
	"VRD_dvdVUISendPin" : "{FourDigitPin}",
	"VRD_emailSelectAllAccounts" : "Todas las cuentas",
	"VRD_emailSelectCall" : "Llamar",
	"VRD_emailSelectContactName" : "{ContactName}",
	"VRD_emailSelectContinueEmail" : "Continuar Email",
	"VRD_emailSelectDelete" : "Eliminar",
	"VRD_emailSelectDiscard" : "Descartar",
	"VRD_emailSelectImportEmail" : "Actualizar buzón de entrada",
	"VRD_emailSelectInbox" : "Buzón de entrada",
	"VRD_emailSelectInboxSelector" : "Buzón de entrada",
	"VRD_emailSelectMessage" : "Añadir mensaje",
	"VRD_emailSelectNone" : "Ninguno de los anteriores",
	"VRD_emailSelectReply" : "Responder",
	"VRD_emailSelectReplyAll" : "Responder Todos",
	"VRD_emailSelectRetry" : "Reintentar",
	"VRD_emailSelectReturn" : "Volver",
	"VRD_emailSelectSend" : "Enviar",
	"VRD_emailSelectSenderName" : "{senderName}",
	"VRD_emnaviAcceptAvoidance" : "Confirmar",
	"VRD_emnaviAddCurrentPosToFavourites" : "Añadir ubicación actual a Favoritos",
	"VRD_emnaviAddWaypointCityCenter" : "Añadir el centro de la ciudad como punto de referencia",
	"VRD_emnaviAddWaypointDistrictCenter" : "Añadir el centro del distrito como punto de referencia",
	"VRD_emnaviAddWaypointFavorite" : "Añadir Favorito como punto de referencia",
	"VRD_emnaviAddWaypointPOI" : "Añadir punto de referencia {poiHypList}",
	"VRD_emnaviAvoidRouteAhead" : "Evitar ruta adelante",
	"VRD_emnaviCancelRoute" : "Cancelar ruta",
	"VRD_emnaviDecreaseAvoidanceLength" : "Menos",
	"VRD_emnaviGoToCockpit" : "Iniciar",
	"VRD_emnaviIncreaseAvoidanceLength" : "Más",
	"VRD_emnaviJPJ_VDEHypothesisList" : "Nombre de una ciudad",
	"VRD_emnaviNavigateHere" : "Navegar aquí",
	"VRD_emnaviNavigateHome" : "Navegar a casa",
	"VRD_emnaviNavigateToARecentDestination" : "Navegar a un destino reciente",
	"VRD_emnaviNavigateToAddress" : "Navegar a dirección",
	"VRD_emnaviNavigateToCityCenter" : "Navegar al centro de la ciudad",
	"VRD_emnaviNavigateToDistrictCenter" : "Navegar al centro del distrito",
	"VRD_emnaviNavigateToFavorite" : "Navegar a Favorito",
	"VRD_emnaviNavigateToPOI" : "Navegar a {poiHypList}",
	"VRD_emnaviNewDestination" : "Nuevo destino",
	"VRD_emnaviRepeatInstruction" : "Repetir instrucción",
	"VRD_emnaviRouteSummary" : "Resumen de ruta",
	"VRD_emnaviSelectCancelRoute" : "Despejar ruta",
	"VRD_emnaviSelectNavigateToAddress" : "Navegar a una dirección",
	"VRD_emnaviSimpleHypothesisList" : "Nombre de un Estado",
	"VRD_emnaviStepByStep" : "Entrada paso a paso",
	"VRD_emnaviTravelViaARecentDestination" : "Añadir destino reciente como punto de referencia",
	"VRD_emnaviTravelViaAddress" : "Viajar por dirección",
	"VRD_emnaviTravelViaHome" : "Viajar por casa",
	"VRD_emnaviTryAgain" : "Volver a intentarlo",
	"VRD_emnaviUniSimpleHypothesisList" : "Una dirección",
	"VRD_emnaviUniVDEHypothesisList" : "Una dirección",
	"VRD_emnaviVDEHypothesisList" : "Una dirección",
	"VRD_emnaviWhereAmI" : "Dónde estoy",
	"VRD_emnaviZoomIn" : "Acercar",
	"VRD_emnaviZoomOut" : "Alejar",
	"VRD_fmradioPlayStationFrequency" : "Sintonizar FM {frequency}",
	"VRD_fmradioSelectAutoMemory" : "Memoria automática",
	"VRD_fmradioSelectChangeGenre" : "Cambiar género",
	"VRD_fmradioSelectFMSettings" : "Ajustes FM",
	"VRD_fmradioSelectFavorites" : "Favoritos",
	"VRD_fmradioSelectGenreSeek" : "Buscar género",
	"VRD_fmradioSelectHDChannel" : "{HD Channel}",
	"VRD_fmradioSelectHDChannels" : "Emisoras HD Radio",
	"VRD_fmradioSelectHDRadio" : "HD Radio",
	"VRD_fmradioSelectHDRadioOff" : "HD Radio apagada",
	"VRD_fmradioSelectHDRadioOn" : "HD Radio encendida",
	"VRD_fmradioSelectScanOff" : "Exploración desactivada",
	"VRD_fmradioSelectScanOn" : "Exploración activada",
	"VRD_fmradioSelectSeekNext" : "Buscar siguiente",
	"VRD_fmradioSelectSeekPrevious" : "Buscar anterior",
	"VRD_fmradioSelectSettings" : "Ajustes de sonido",
	"VRD_fmradioSelectSource" : "Entretenimiento / Cambiar fuente",
	"VRD_fmradioSelectStationAll" : "Todas las emisoras",
	"VRD_fmradioSelectStationFrequency" : "{frequency}",
	"VRD_fmradioSelectStationGenre" : "{genreName}",
	"VRD_fmradioSelectStationList" : "Lista de emisoras",
	"VRD_fmradioSelectStationName" : "{stationName}",
	"VRD_fmradioSelectTrafficAlert" : "Anuncio de tráfico (TA)",
	"VRD_fmradioSelectTrafficAlertOff" : "Tráfico apagado",
	"VRD_fmradioSelectTrafficAlertOn" : "Tráfico encendido",
	"VRD_fmradioSelectTune" : "Sintonizar",
	"VRD_fmradioSelectUpdateAutoMemory" : "Actualizar memoria automática",
	"VRD_fmradioSelectiTunesTagging" : "Etiquetado de iTunes",
	"VRD_fmradioTuneDown" : "Sintonizar hacia abajo",
	"VRD_fmradioTuneUp" : "Sintonizar hacia arriba",
	"VRD_fmradioTurnOffAF" : "Frecuencia alternativa desactivada",
	"VRD_fmradioTurnOffREG" : "Bloqueo de región desactivado",
	"VRD_fmradioTurnOnAF" : "Frecuencia alternativa activada",
	"VRD_fmradioTurnOnREG" : "Bloqueo de región activado",
	"VRD_fmradioUpdateAutoMemory" : "Actualizar lista de emisoras",
	"VRD_pandoraAddStation" : "Añadir emisora",
	"VRD_pandoraAddStationFromArtist" : "Crear emisora del artista",
	"VRD_pandoraAddStationFromSong" : "Crear emisora de la canción",
	"VRD_pandoraAddToFavorites" : "Añadir a Favoritos",
	"VRD_pandoraBookmarkArtist" : "Artista favorito",
	"VRD_pandoraBookmarkSong" : "Canción favorita",
	"VRD_pandoraCreateStation" : "Crear emisora",
	"VRD_pandoraSelectAddCurrentStation" : "Añadir",
	"VRD_pandoraSelectDelete" : "Eliminar",
	"VRD_pandoraSelectEditDelete" : "Eliminar",
	"VRD_pandoraSelectEditMove" : "Mover",
	"VRD_pandoraSelectEditReplace" : "Sustituir",
	"VRD_pandoraSelectFavorites" : "Favoritos",
	"VRD_pandoraSelectMove" : "Mover",
	"VRD_pandoraSelectQuickMix" : "Aleatorio",
	"VRD_pandoraSelectSettings" : "Ajustes de sonido",
	"VRD_pandoraSelectSortBy" : "Ordenar",
	"VRD_pandoraSelectSource" : "Entretenimiento",
	"VRD_pandoraSelectStationList" : "Lista de emisoras",
	"VRD_pandoraShowBookmarkOptions" : "Favoritos",
	"VRD_pandoraShowByAZ" : "Ordenar alfabéticamente",
	"VRD_pandoraShowByDate" : "Ordenar por fecha",
	"VRD_pandoraSkip" : "Saltar",
	"VRD_pandoraThumbsDown" : "No me gusta",
	"VRD_pandoraThumbsUp" : "Me gusta",
	"VRD_phoneCall" : "Llamar",
	"VRD_phoneCallBack" : "Devolver llamada",
	"VRD_phoneCallByName" : "Llamar por nombre",
	"VRD_phoneCallByNumber" : "Llamar por número",
	"VRD_phoneCallContactType" : "Llamar {contactName} {contactType}",
	"VRD_phoneCallLast" : "Llamar al último número",
	"VRD_phoneChooseContactType" : "{contactName} {contactType}",
	"VRD_phoneDialAnyNumber" : "Llamar {number}",
	"VRD_phoneDialpadClearAllDigits" : "Borrar todos los dígitos",
	"VRD_phoneDialpadDeleteDigit" : "Eliminar",
	"VRD_phoneDialpadPhoneNumber" : "{phoneNumber}",
	"VRD_phoneReDial" : "Volver a marcar",
	"VRD_phoneSelectByName" : "Nombre",
	"VRD_phoneSelectByNumber" : "Número",
	"VRD_phoneSelectContactType" : "{contactType}",
	"VRD_phoneSelectDialPad" : "Teclado de marcación",
	"VRD_phoneSelectFavorites" : "Favoritos",
	"VRD_phoneSelectRecentCalls" : "Llamadas recientes",
	"VRD_phoneSelectRecentCallsAll" : "Todas las llamadas",
	"VRD_phoneSelectRecentCallsMissed" : "Llamadas perdidas",
	"VRD_satradioBackSpaceDelete" : "Eliminar dígitos",
	"VRD_satradioChangeLockCode" : "Cambiar código PIN",
	"VRD_satradioEnterPIN" : "{4digitPin}",
	"VRD_satradioInitializeLockCode" : "Inicializar código PIN",
	"VRD_satradioPlayChannelName" : "Reproducir {channelName}",
	"VRD_satradioPlayStationNumber" : "Sintonizar {channelNumber}",
	"VRD_satradioResetLockCode" : "Restablecer código pin",
	"VRD_satradioSeekNext" : "Buscar siguiente",
	"VRD_satradioSeekPrevious" : "Buscar anterior",
	"VRD_satradioSelectChangeCategory" : "Categoría",
	"VRD_satradioSelectFavorites" : "Favoritos",
	"VRD_satradioSelectParentalLock" : "Bloqueo parental",
	"VRD_satradioSelectScanOff" : "Exploración desactivada",
	"VRD_satradioSelectScanOn" : "Exploración activada",
	"VRD_satradioSelectSettings" : "Ajustes de sonido",
	"VRD_satradioSelectSource" : "Entretenimiento",
	"VRD_satradioSelectStation" : "Emisora {Station number}",
	"VRD_satradioSelectStationAll" : "Todos los canales",
	"VRD_satradioSelectStationCategory" : "{categoryName}",
	"VRD_satradioSelectStationList" : "Lista de canales",
	"VRD_satradioTurnChannelLockOFF" : "Desbloquear canal actual",
	"VRD_satradioTurnChannelLockON" : "Bloquear canal actual",
	"VRD_satradioTurnParentalLockOFF" : "Bloqueo de sesión apagado",
	"VRD_satradioTurnParentalLockON" : "Bloqueo de sesión encendido",
	"VRD_smsCallPhoneNumber" : "Llamar",
	"VRD_smsDelete" : "Eliminar",
	"VRD_smsImportMessages" : "Actualizar buzón de entrada de SMS",
	"VRD_smsReply" : "Responder",
	"VRD_smsSayAnyConversation" : "{senderName}",
	"VRD_smsSelectBody" : "Añadir mensaje",
	"VRD_smsSelectContactName" : "{ContactName}",
	"VRD_smsSelectContinueTextMessage" : "Continuar mensaje",
	"VRD_smsSelectDiscard" : "Descartar",
	"VRD_smsSelectInbox" : "Lista de buzón de entrada de SMS",
	"VRD_smsSelectNone" : "Ninguno de los anteriores",
	"VRD_smsSelectRetry" : "Reintentar",
	"VRD_smsSelectReturn" : "Volver",
	"VRD_smsSelectSend" : "Enviar",
	"VRD_stitcherAddToFavorites" : "Añadir a Favoritos",
	"VRD_stitcherRemoveFromFavorites" : "Eliminar de Favoritos",
	"VRD_stitcherSaveFavorites" : "Guardar cambios",
	"VRD_stitcherSelectSettings" : "Ajustes de sonido",
	"VRD_stitcherSelectSource" : "Entretenimiento",
	"VRD_stitcherSelectStationList" : "Lista de emisoras",
	"VRD_stitcherThumbsDown" : "No me gusta",
	"VRD_stitcherThumbsUp" : "Me gusta",
	"VRD_systemSelectAhaRadio" : "Aha Radio",
	"VRD_systemSelectAndroidAuto" : "Android Auto",
	"VRD_systemSelectApplications" : "Aplicaciones",
	"VRD_systemSelectAuxIn" : "Entrada de línea / AUX.",
	"VRD_systemSelectBTAudio" : "Bluetooth",
	"VRD_systemSelectCD" : "CD",
	"VRD_systemSelectCallHistory" : "Historial de llamadas",
	"VRD_systemSelectCarPlay" : "Apple CarPlay",
	"VRD_systemSelectCommunication" : "Comunicación",
	"VRD_systemSelectConnect" : "Conectar",
	"VRD_systemSelectContacts" : "Contactos",
	"VRD_systemSelectDAB" : "DAB",
	"VRD_systemSelectDVD" : "DVD",
	"VRD_systemSelectDisplayClock" : "Pantalla de reloj",
	"VRD_systemSelectDisplayOff" : "Apagar pantalla",
	"VRD_systemSelectEmail" : "Email",
	"VRD_systemSelectEntertainment" : "Entretenimiento",
	"VRD_systemSelectEntertainmentMenu" : "Menú de entretenimiento",
	"VRD_systemSelectFavorites" : "Favoritos",
	"VRD_systemSelectNavigation" : "Navegación",
	"VRD_systemSelectNotifications" : "SMS",
	"VRD_systemSelectNotifyOff" : "Desactivar notificaciones",
	"VRD_systemSelectPandora" : "Pandora",
	"VRD_systemSelectPhone" : "Teléfono",
	"VRD_systemSelectRadioAM" : "Radio AM",
	"VRD_systemSelectRadioFM" : "Radio FM",
	"VRD_systemSelectRetry" : "Reintentar",
	"VRD_systemSelectSatRadio" : "Radio satelital",
	"VRD_systemSelectSettings" : "Configuraciones",
	"VRD_systemSelectSiri" : "Siri",
	"VRD_systemSelectSms" : "Texto / SMS",
	"VRD_systemSelectStitcher" : "Stitcher",
	"VRD_systemSelectTV" : "TV",
	"VRD_systemSelectTrafficAlert" : "Anuncio de Tráfico (TA)",
	"VRD_systemSelectTutorial" : "Tutorial",
	"VRD_systemSelectUSB" : "USB",
	"VRD_systemSelectUSBA" : "USB 1",
	"VRD_systemSelectUSBB" : "USB 2",
	"VRD_systemSelectXmAudio" : "SiriusXM Radio",
	"VRD_tvSelectView" : "Ver",
	"VRD_usbaudioBrowse" : "Buscar",
	"VRD_usbaudioBrowseAlbum" : "Buscar {albumName}",
	"VRD_usbaudioBrowseAlbums" : "Buscar álbum",
	"VRD_usbaudioBrowseAll" : "Buscar todas las canciones o álbumes o artistas",
	"VRD_usbaudioBrowseAnyAlbum" : "Buscar [Album] {albumName}",
	"VRD_usbaudioBrowseAnyArtist" : "Buscar [Artist] {artistName}",
	"VRD_usbaudioBrowseAnyFolder" : "Buscar carpeta {folderName}",
	"VRD_usbaudioBrowseArtist" : "Buscar {artistName}",
	"VRD_usbaudioBrowseArtists" : "Buscar artista",
	"VRD_usbaudioBrowseAudiobooks" : "Buscar audiolibros",
	"VRD_usbaudioBrowseFolder" : "Buscar {folderName}",
	"VRD_usbaudioBrowseFolders" : "Buscar carpeta",
	"VRD_usbaudioBrowseGenre" : "Buscar [Genre] {genreName}",
	"VRD_usbaudioBrowseGenres" : "Buscar género",
	"VRD_usbaudioBrowseLineNumber" : "Buscar línea {lineNumber}",
	"VRD_usbaudioBrowsePlaylist" : "Buscar lista de reproducción {playlistName}",
	"VRD_usbaudioBrowsePlaylists" : "Buscar lista de reproducción",
	"VRD_usbaudioBrowsePodcast" : "Buscar podcast {podcastName}",
	"VRD_usbaudioBrowsePodcasts" : "Buscar podcasts",
	"VRD_usbaudioBrowseSongs" : "Buscar canción",
	"VRD_usbaudioChooseAlbumArtist" : "{artistName}",
	"VRD_usbaudioGenerateMoreLikeThis" : "Más de este tipo",
	"VRD_usbaudioPlayAlbums" : "Reproducir álbum",
	"VRD_usbaudioPlayAll" : "Reproducir todo",
	"VRD_usbaudioPlayAnyAlbum" : "Reproducir [Album] {albumName}",
	"VRD_usbaudioPlayAnyArtist" : "Reproducir [Artist] {artistName}",
	"VRD_usbaudioPlayAnyFolder" : "Reproducir carpeta {folderName}",
	"VRD_usbaudioPlayArtistAlbum" : "Reproducir {artistName} {albumName}",
	"VRD_usbaudioPlayArtists" : "Reproducir artista",
	"VRD_usbaudioPlayAudiobook" : "Reproducir audiolibro {AudiobookName}",
	"VRD_usbaudioPlayAudiobooks" : "Reproducir audiolibros",
	"VRD_usbaudioPlayChapter" : "{chapterName}",
	"VRD_usbaudioPlayChapterIndex" : "Reproducir capítulo {index} {chapter}",
	"VRD_usbaudioPlayEpisode" : "{episodeName}",
	"VRD_usbaudioPlayFolder" : "Reproducir {folderName}",
	"VRD_usbaudioPlayFolders" : "Reproducir carpeta",
	"VRD_usbaudioPlayGenre" : "Reproducir [Genre] {genreName}",
	"VRD_usbaudioPlayGenres" : "Reproducir género",
	"VRD_usbaudioPlayLineNumber" : "Reproducir [Line] {lineNumber}",
	"VRD_usbaudioPlayPlaylist" : "Reproducir lista de reproducción {playlistName}",
	"VRD_usbaudioPlayPlaylists" : "Reproducir lista de reproducción",
	"VRD_usbaudioPlayPodcast" : "Reproducir podcast {PodcastName}",
	"VRD_usbaudioPlayPodcasts" : "Reproducir podcasts",
	"VRD_usbaudioPlaySongs" : "Reproducir canción",
	"VRD_usbaudioRepeat" : "Repetir",
	"VRD_usbaudioRepeatAll" : "Repetir todo",
	"VRD_usbaudioRepeatOff" : "Repetición apagada",
	"VRD_usbaudioRepeatSong" : "Repetir canción",
	"VRD_usbaudioRewind" : "Rebobinar",
	"VRD_usbaudioSelectAlbum" : "Álbum {albumName}",
	"VRD_usbaudioSelectAlbums" : "Álbum",
	"VRD_usbaudioSelectAll" : "Todos los episodios o capítulos o canciones o álbumes o artistas",
	"VRD_usbaudioSelectArtist" : "Artista {artistName}",
	"VRD_usbaudioSelectArtists" : "Artista",
	"VRD_usbaudioSelectAudiobook" : "{audiobookName}",
	"VRD_usbaudioSelectAudiobooks" : "Audiolibros",
	"VRD_usbaudioSelectFolder" : "Carpeta {folderName}",
	"VRD_usbaudioSelectFolders" : "Carpetas",
	"VRD_usbaudioSelectGenre" : "Género {genreName}",
	"VRD_usbaudioSelectGenres" : "Género",
	"VRD_usbaudioSelectPlaylist" : "Lista de reproducción {playlistName}",
	"VRD_usbaudioSelectPlaylists" : "Lista de reproducción",
	"VRD_usbaudioSelectPodcast" : "{podcastName}",
	"VRD_usbaudioSelectPodcasts" : "Podcast",
	"VRD_usbaudioSelectRootFolder" : "Menú raíz",
	"VRD_usbaudioSelectSettings" : "Ajustes de sonido",
	"VRD_usbaudioSelectSongs" : "Canción",
	"VRD_usbaudioSelectSourceMenu" : "Entretenimiento",
	"VRD_usbaudioShuffle" : "Aleatorio",
	"VRD_usbaudioShuffleOff" : "Aleatorio Apagado",
	"VRD_usbaudioShuffleOn" : "Aleatorio encendido",
	"VRD_usbaudioSongList" : "Lista de canciones",
	"VRD_xmaudioBackSpaceDelete" : "Eliminar dígitos",
	"VRD_xmaudioChangeLockCode" : "Editar Código PIN",
	"VRD_xmaudioConfirmDelete" : "Eliminar",
	"VRD_xmaudioEnterPIN" : "{fourDigitPIN}",
	"VRD_xmaudioPlayChannelName" : "Reproducir canal XM {channelName}",
	"VRD_xmaudioPlayStationNumber" : "Sintonizar {channelNumber}",
	"VRD_xmaudioResetLockCode" : "Restablecer código pin",
	"VRD_xmaudioSelectCallXM" : "Llamar a XM",
	"VRD_xmaudioSelectChangeCategory" : "Cambiar categoría",
	"VRD_xmaudioSelectContinueListening" : "Continuar escuchando",
	"VRD_xmaudioSelectDismiss" : "Ignorar",
	"VRD_xmaudioSelectEveryOccurance" : "Cada repetición",
	"VRD_xmaudioSelectEveryOtherReport" : "Cada dos informes",
	"VRD_xmaudioSelectEveryReport" : "Cada informe",
	"VRD_xmaudioSelectExitTuneMix" : "Salir de la TuneMix",
	"VRD_xmaudioSelectFavorites" : "Favoritos",
	"VRD_xmaudioSelectListenNow" : "Escuchar ahora",
	"VRD_xmaudioSelectMove" : "Mover",
	"VRD_xmaudioSelectNearestCity" : "Ciudad más cercana",
	"VRD_xmaudioSelectOnlyFirstAfterVehicleStart" : "Iniciar vehículo",
	"VRD_xmaudioSelectOnlyFirstOccuranceInGame" : "Primera repetición",
	"VRD_xmaudioSelectReplayAlert" : "Volver a reproducir alerta",
	"VRD_xmaudioSelectReturnToPrevious" : "Volver a anterior",
	"VRD_xmaudioSelectSFSportBaseball" : "Béisbol",
	"VRD_xmaudioSelectSFSportNCAA" : "Fútbol universitario",
	"VRD_xmaudioSelectSFSportNFL" : "Fútbol profesional",
	"VRD_xmaudioSelectSFSportNHL" : "Hockey",
	"VRD_xmaudioSelectScanOff" : "Exploración desactivada",
	"VRD_xmaudioSelectScanOn" : "Exploración activada",
	"VRD_xmaudioSelectSettings" : "Ajustes",
	"VRD_xmaudioSelectSoundSettings" : "Ajustes de sonido",
	"VRD_xmaudioSelectSource" : "Entretenimiento",
	"VRD_xmaudioSelectStation" : "Emisora {channelNumber}",
	"VRD_xmaudioSelectStationAll" : "Todos los canales",
	"VRD_xmaudioSelectStationCategory" : "{categoryName}",
	"VRD_xmaudioSelectStationFeaturedFavorites" : "Favoritos destacados ",
	"VRD_xmaudioSelectStationList" : "Canales",
	"VRD_xmaudioSelectTuneMix" : "TuneMix",
	"VRD_xmaudioSelectTuneMixChannel" : "Opciones del canal de TuneMix",
	"VRD_xmaudioSelectTuneMixChannelsOptions" : "Opciones de canal",
	"VRD_xmaudioSelectTuneMixCreation" : "Crear nuevo canal de TuneMix",
	"VRD_xmaudioSelectTuneMixEdit" : "Editar canal de TuneMix",
	"VRD_xmaudioSelectTuneMixEditOps" : "Opciones para editar la TuneMix",
	"VRD_xmaudioSelectTuneMixRemove" : "Eliminar canal de TuneMix",
	"VRD_xmaudioSelectTuneMixRename" : "Renombrar TuneMix",
	"VRD_xmaudioSelectTurnAlertsOff" : "Desactivar alertas",
	"VRD_xmaudioSelectiTunesTagging" : "Etiquetado de iTunes",
	"VRD_xmaudioSetChannelLock" : "Bloquear canal",
	"VRD_xmaudioSetParentalLock" : "Bloqueo de Sesión",
	"VRD_xmdataSelectFuelPrices" : "Precios del combustible",
	"VRD_xmdataSelectMovies" : "Películas",
	"VRD_xmdataSelectParking" : "Aparcamiento",
	"VRD_xmdataSelectSports" : "Deportes",
	"VRD_xmdataSelectStock" : "Existencias",
	"VRD_xmdataSelectTrafficPlus" : "Tráfico Plus",
	"VRD_xmdataSelectWeatherForecast" : "Pronóstico del tiempo",
	"VRD_xmdataSelectWeatherRadar" : "Radar meteorológico",
	"VRD_xmdataSelectWeatherSecurityAlerts" : "Alertas de clima y seguridad",
};

framework.registerAppDictLoaded("system", "es_MX");