var __VrHelpPositionTable__systemAppDict_mn_TW = {
	"HomeScreen_Help" : {
		"Right" : ["VrHelp_Favorites"],
		"Left" : ["VrHelp_Entertainment","VrHelp_Communication","VrHelp_Navigation","VrHelp_Settings","VrHelp_Applications"]
	}
};

var Localization_systemAppDict_mn_TW = {
	//"stringId" : "localString"
	"ActiveCallItem" : "主動呼叫",
	"AhaMaintError" : "aha 維修錯誤",
	"AhaRadio" : "aha",
	"AmRadio" : "AM",
	"AndroidAuto" : "Android Auto",
	"Applications" : "應用程式",
	"AudioSourceNotAvailableBTAudio" : "藍牙音訊無法使用",
	"AudioSourceNotAvailableCD" : "CD已退片",
	"AudioSourceNotAvailableDVD" : "DVD已退片",
	"AudioSourceNotAvailableTV" : "TV 無法使用",
	"AudioSourceNotAvailableUSB" : "已變更 USB 裝置",
	"AuxIn" : "AUX",
	"BT" : "BT",
	"Bluetooth" : "藍牙",
	"BluetoothWithDevice" : "藍牙 - {deviceName}",
	"CallHistory" : "通話歷史記錄",
	"CarPlay" : "Apple CarPlay",
	"CdPlayer" : "CD",
	"ChannelOffAir" : "頻道已停播",
	"ChannelUnauth" : "頻道未獲授權",
	"CheckAntenna" : "請檢查天線",
	"CheckTuner" : "請檢查調諧器",
	"Communication" : "通訊",
	"Connect" : "連接",
	"Contacts" : "通訊錄",
	"DVDItem" : "DVD",
	"DabRadio" : "DAB",
	"DialPhone" : "撥打電話",
	"DidYouSay" : "您是否說過. . .",
	"DisclaimerText" : "注意力分散可能導致事故。駕駛時請勿進行操作。請務必專心駕駛並遵守交通規則。 請參閱《車主手冊》。",
	"DisconnectThenReconnect" : "開啟 Siri 時發生錯誤。 已中斷連接並重新連接 Apple Device。",
	"DriveRecord" : "駕駛記錄",
	"DriverIDItem" : "選擇駕駛人",
	"EcoenergyApp" : "油耗顯示",
	"EcoenergyAppHEV" : "駕駛狀況",
	"Email" : "電子郵件",
	"EngineOilLevel" : "引擎機油量",
	"Entertainment" : "娛樂",
	"ErrorWhileStartingSiri" : "開啟 Siri 時發生錯誤",
	"FailedNotificationRetrieval" : "無法擷取通知清單",
	"FavoritesItem" : "我的最愛",
	"FmRadio" : "FM",
	"HDTrafficItem" : "HD Radio™ 路況顯示",
	"InitiateSiri" : "長按通話按鍵以開啟 Siri 工作階段",
	"IntelligentDriveMasterItem" : "i-DM",
	"NavigationTitle" : "導航",
	"NoConnectionNotifyText" : "要現在連接電話嗎?",
	"NoConnectionNotifyTitle" : "未連接電話",
	"NoDeviceText" : "要現在連接裝置嗎?",
	"NoDeviceTitle" : "未連接裝置",
	"Notifications" : "通知",
	"NotifyIgnore" : "忽略",
	"NotifyIncomingMsg" : "來自      的訊息",
	"NotifyOff" : "關閉通知",
	"NotifyRead" : "讀取",
	"NotifyReadNow" : "要現在閱讀嗎?",
	"Pandora" : "Pandora",
	"ReconnectAhaRadio" : "正在連接藍牙音訊以用於 aha 廣播",
	"ReconnectBTAudio" : "正在重新連接藍牙音訊以恢復",
	"ReconnectCD" : "正在驗證 CD 以恢復播放",
	"ReconnectCarPlay" : "繼續使用 Apple CarPlay。",
	"ReconnectDVD" : "正在驗證 DVD 以恢復播放",
	"ReconnectEntMenuButton" : "娛樂清単",
	"ReconnectFailedBTAudio" : "無法重新連接藍牙音訊",
	"ReconnectFailedCD" : "CD已退片，無法繼續播放",
	"ReconnectFailedCarPlay" : "無法與 Apple CarPlay 重新連線",
	"ReconnectFailedDVD" : "DVD已退片，無法繼續播放",
	"ReconnectFailedTV" : "TV 無法使用。 無法繼續播放。",
	"ReconnectFailedUSB" : "已變更 USB 裝置。 無法繼續播放。",
	"ReconnectPandora" : "正在連接藍牙音訊以用於 Pandora",
	"ReconnectStitcher" : "正在連接藍牙音訊以用於 Stitcher",
	"ReconnectTV" : "正在驗證 TV 以恢復播放",
	"ReconnectUSB" : "正在重新連接 USB 裝置以恢復",
	"RetryLabel" : "重試",
	"SchedMaintenanceApp" : "維修保養",
	"ScreenReplication" : "畫面複製",
	"SdarsRadio" : "XM",
	"Settings" : "設定",
	"SettingsCommunication" : "設定",
	"Siri" : "Siri",
	"SiriDisabled" : "無法在 Apple Device 使用 Siri。",
	"Sms" : "簡訊",
	"StitcherItem" : "Stitcher",
	"TVItem" : "TV",
	"TempWarning" : "溫度提示",
	"TempWarningText" : "螢幕過熱\n若不關閉冷卻，螢幕顯示效能可能下降",
	"TextDownloaded" : "已下載簡訊",
	"TextSent" : "簡訊已傳送",
	"TrafficAlertsItem" : "即時路況",
	"USB" : "USB",
	"USB1AndroidAuto" : "USB 1 - Android Auto",
	"USB1CarPlay" : "USB 1 - Apple CarPlay",
	"USB2AndroidAuto" : "USB 2 - Android Auto",
	"UsbAudioA" : "USB 1",
	"UsbAudioAWithDevice" : "USB 1 - {deviceName}",
	"UsbAudioB" : "USB 2",
	"UsbAudioBWithDevice" : "USB 2 - {deviceName}",
	"UseCommander" : "開車時請使用指揮台。",
	"VehicleDataTransferItem" : "車輛資訊傳輸 ",
	"VehicleStatusMonitor" : "車子狀態監視器",
	"VehicleTelemetryTransfer" : "車子遙感傳輸",
	"VideoSignalLost" : "視訊信號中斷",
	"VoiceNotSupported" : "系統不支援此語音 ",
	"VoiceRecognition" : "語音辨識",
	"VrHelp_Applications" : "應用程序 ",
	"VrHelp_Communication" : "通訊",
	"VrHelp_Entertainment" : "娛樂",
	"VrHelp_Favorites" : "我的最愛 ",
	"VrHelp_Navigation" : "導航",
	"VrHelp_Settings" : "設置 ",
	"WarnGuidanceApp" : "警告提示",
	"WarningTitle" : "警告!",
	"XMAudio" : "SXM",
	"XMData" : "SXM Services",
	"agree" : "我同意",
	"VRD_aharadioSelectCall" : "撥打電話",
	"VRD_aharadioSelectDiscard" : "捨棄",
	"VRD_aharadioSelectEpisodes" : "劇集清單",
	"VRD_aharadioSelectLBSTab" : "Nearby",
	"VRD_aharadioSelectMainList" : "Aha 主清單",
	"VRD_aharadioSelectMap" : "地圖",
	"VRD_aharadioSelectPresetsTab" : "預設",
	"VRD_aharadioSelectSave" : "儲存",
	"VRD_aharadioSelectSettings" : "音效設定",
	"VRD_aharadioSelectShout" : "大聲說",
	"VRD_aharadioSelectSource" : "Entertainment / Change Source",
	"VRD_aharadioSelectThumbsDown" : "遜斃了",
	"VRD_aharadioSelectThumbsUp" : "讚",
	"VRD_amradioPlayStationFrequency" : "Tune to {frequency} AM",
	"VRD_amradioSelectAutoMemory" : "Auto Memory",
	"VRD_amradioSelectFavorites" : "Favorites",
	"VRD_amradioSelectHD" : "HD Radio Stations",
	"VRD_amradioSelectHDOff" : "HD Radio Off",
	"VRD_amradioSelectHDOn" : "HD Radio On",
	"VRD_amradioSelectScanOff" : "Scan Off",
	"VRD_amradioSelectScanOn" : "Scan On",
	"VRD_amradioSelectSeekNext" : "Seek Next",
	"VRD_amradioSelectSeekPrevious" : "Seek Previous",
	"VRD_amradioSelectSettings" : "Sound Settings",
	"VRD_amradioSelectSource" : "Go to Entertainment Menu",
	"VRD_amradioSelectStationFrequency" : "{AMFrequency}",
	"VRD_amradioSelectTrafficAlert" : "Traffic Alert",
	"VRD_amradioSelectTrafficAlertOff" : "Traffic Alert Off",
	"VRD_amradioSelectTrafficAlertOn" : "Traffic Alert On",
	"VRD_amradioSelectTune" : "Tune",
	"VRD_amradioSelectUpdateAutoMemory" : "Auto Memory Seek",
	"VRD_amradioSelectiTunesTagging" : "iTunes Tagging",
	"VRD_amradioTuneDown" : "Tune Down",
	"VRD_amradioTuneUp" : "Tune Up",
	"VRD_amradioUpdateAutoMemory" : "Update Station List",
	"VRD_auxinSelectSettings" : "Sound Settings",
	"VRD_auxinSelectSource" : "Entertainment / Change Source",
	"VRD_btaudioScanPlay" : "掃描播放",
	"VRD_btaudioSelectConnect" : "連線",
	"VRD_btaudioSelectRootMenu" : "根選單",
	"VRD_btaudioSelectSettings" : "音效設定",
	"VRD_btaudioSelectSource" : "進入娛樂選單",
	"VRD_btaudioToggleRepeat" : "重複",
	"VRD_btaudioToggleShuffle" : "隨機播放",
	"VRD_carplaySelectApplications" : "Applications",
	"VRD_cdGoSettings" : "音效設定",
	"VRD_cdHandleStartScan" : "開始掃描",
	"VRD_cdPlayBeginning" : "重新開始",
	"VRD_cdRepeatFolder" : "重複資料夾",
	"VRD_cdRepeatOff" : "重複關閉",
	"VRD_cdRepeatOn" : "Repeat On",
	"VRD_cdRepeatTrack" : "重複曲目",
	"VRD_cdSelectCurrentFolder" : "當前資料夾",
	"VRD_cdSelectRepeat" : "重複",
	"VRD_cdSelectRootFolder" : "根選單",
	"VRD_cdSelectShuffle" : "隨機播放",
	"VRD_cdSelectSource" : "進入娛樂選單",
	"VRD_cdSelectTrackList" : "曲目清單",
	"VRD_cdSelectTrackNumber" : "播放曲目 {Number}",
	"VRD_cdShuffleDisk" : "隨機播放光碟",
	"VRD_cdShuffleFolder" : "隨機播放資料夾",
	"VRD_cdShuffleOff" : "隨機播放關閉",
	"VRD_cdShuffleOn" : "Shuffle On",
	"VRD_commonAddToFavorites" : "Add to Favorites",
	"VRD_commonCancel" : "Cancel",
	"VRD_commonFastForward" : "Fast Forward",
	"VRD_commonGoBack" : "Go Back",
	"VRD_commonIntentParent" : "Parent",
	"VRD_commonIntentParentUSBAudio" : "Parent",
	"VRD_commonIntentUSBAudio" : "Home",
	"VRD_commonIntentUSBAudioBG" : "Home",
	"VRD_commonMenuUp" : "Nenu Up",
	"VRD_commonNext" : "Next",
	"VRD_commonNo" : "No",
	"VRD_commonPageDown" : "Page Down / Scroll Down",
	"VRD_commonPageUp" : "Page Up / Scroll Up",
	"VRD_commonPause" : "Pause",
	"VRD_commonPrevious" : "Previous",
	"VRD_commonResume" : "Play / Resume",
	"VRD_commonRewind" : "Rewind",
	"VRD_commonSelectLineNumber" : "Line {lineNumber}",
	"VRD_commonYes" : "Yes / OK",
	"VRD_contactsChooseContactName" : "{ContactName}",
	"VRD_contactsDisambiguateContactName" : "Show {ContactName}",
	"VRD_contactsImportAll" : "匯入全部聯繫人",
	"VRD_contactsImportCancel" : "取消匯入",
	"VRD_contactsImportContacts" : "編輯聯繫人",
	"VRD_contactsImportSingle" : "匯入選定聯繫人",
	"VRD_contactsRemoveContact" : "移除聯繫人",
	"VRD_contactsSelectCall" : "撥打電話",
	"VRD_contactsSelectContactName" : "{ContactName}",
	"VRD_contactsSelectDownload" : "下載",
	"VRD_contactsSelectFavorites" : "我的最愛",
	"VRD_contactsSelectNone" : "None of these",
	"VRD_contactsSelectReadContactName" : "讀取聯繫人姓名",
	"VRD_contactsSelectRemove" : "移除",
	"VRD_contactsSelectRetry" : "重試",
	"VRD_contactsSendPhoneType" : "{phoneType}",
	"VRD_contactsShowAddress" : "地址",
	"VRD_dabDisplayDABSettings" : "DAB 設定",
	"VRD_dabDisplayEnsembleList" : "選取合奏",
	"VRD_dabDisplayStationList" : "電臺清單",
	"VRD_dabSelectFavorites" : "Favorites",
	"VRD_dabSelectScan" : "掃描",
	"VRD_dabSelectSeekNext" : "下一個",
	"VRD_dabSelectSeekPrevious" : "上一個",
	"VRD_dabSelectSettings" : "音效設定",
	"VRD_dabSelectSource" : "娛樂",
	"VRD_dabTAToggleOFF" : "路況關閉",
	"VRD_dabTAToggleON" : "路況開啟",
	"VRD_dabTAToggleVois" : "交通警告(TA)",
	"VRD_dabUpdateStationList" : "更新清單",
	"VRD_dvdClearPin" : "刪除數字",
	"VRD_dvdSayGRating" : "G",
	"VRD_dvdSayPG12" : "P G 十二",
	"VRD_dvdSayR15" : "R 十五加",
	"VRD_dvdSayR18" : "無",
	"VRD_dvdSelectAspectRatio" : "外觀比例",
	"VRD_dvdSelectAudioSettings" : "Video Settings",
	"VRD_dvdSelectCameraAngle" : "攝影機角度",
	"VRD_dvdSelectEditPin" : "Edit PIN Code",
	"VRD_dvdSelectParentLock" : "家長鎖",
	"VRD_dvdSelectParentLockOff" : "家長鎖關閉",
	"VRD_dvdSelectParentLockOn" : "家長鎖開啟",
	"VRD_dvdSelectParentLockRating" : "家長鎖評級",
	"VRD_dvdSelectResetPin" : "Reset PIN Code",
	"VRD_dvdSelectRootMenu" : "根選單",
	"VRD_dvdSelectSettings" : "音效設定",
	"VRD_dvdSelectSource" : "娛樂",
	"VRD_dvdSelectSubtitleOff" : "字幕關閉",
	"VRD_dvdSelectSubtitleOn" : "字幕開啟",
	"VRD_dvdSlowForward" : "快進 ",
	"VRD_dvdSlowRewind" : "倒帶",
	"VRD_dvdVUISendPin" : "{FourDigitPin}",
	"VRD_emailSelectAllAccounts" : "所有帳戶",
	"VRD_emailSelectCall" : "撥打電話",
	"VRD_emailSelectContactName" : "{ContactName}",
	"VRD_emailSelectContinueEmail" : "繼續傳送電子郵件",
	"VRD_emailSelectDelete" : "刪除",
	"VRD_emailSelectDiscard" : "捨棄",
	"VRD_emailSelectImportEmail" : "更新收件匣",
	"VRD_emailSelectInbox" : "電子郵件收件匣",
	"VRD_emailSelectInboxSelector" : "收件匣",
	"VRD_emailSelectMessage" : "新增訊息",
	"VRD_emailSelectNone" : "這些都不是",
	"VRD_emailSelectReply" : "回覆",
	"VRD_emailSelectReplyAll" : "全部回覆",
	"VRD_emailSelectRetry" : "重試",
	"VRD_emailSelectReturn" : "返回",
	"VRD_emailSelectSend" : "傳送",
	"VRD_emailSelectSenderName" : "{senderName}",
	"VRD_emnaviAcceptAvoidance" : "Confirm",
	"VRD_emnaviAddCurrentPosToFavourites" : "Add current position to Favorites",
	"VRD_emnaviAddWaypointCityCenter" : "Add Waypoint City Center",
	"VRD_emnaviAddWaypointDistrictCenter" : "Add Waypoint District Center",
	"VRD_emnaviAddWaypointFavorite" : "Add Waypoint Favorite",
	"VRD_emnaviAddWaypointPOI" : "Add Waypoint {poiHypList}",
	"VRD_emnaviAvoidRouteAhead" : "Avoid route ahead",
	"VRD_emnaviCancelRoute" : "Cancel route",
	"VRD_emnaviDecreaseAvoidanceLength" : "Less",
	"VRD_emnaviGoToCockpit" : "Start",
	"VRD_emnaviIncreaseAvoidanceLength" : "More",
	"VRD_emnaviJPJ_VDEHypothesisList" : "A city name",
	"VRD_emnaviNavigateHere" : "Navigate Here",
	"VRD_emnaviNavigateHome" : "Navigate Home",
	"VRD_emnaviNavigateToARecentDestination" : "Navigate to a recent destination",
	"VRD_emnaviNavigateToAddress" : "Navigate to address",
	"VRD_emnaviNavigateToCityCenter" : "Navigate to City Center",
	"VRD_emnaviNavigateToDistrictCenter" : "Navigate to District Center",
	"VRD_emnaviNavigateToFavorite" : "Navigate to Favorite",
	"VRD_emnaviNavigateToPOI" : "Navigate to {poiHypList}",
	"VRD_emnaviNewDestination" : "New destination",
	"VRD_emnaviRepeatInstruction" : "Repeat instruction",
	"VRD_emnaviRouteSummary" : "Route summary",
	"VRD_emnaviSelectCancelRoute" : "Clear route",
	"VRD_emnaviSelectNavigateToAddress" : "Navigate to an address",
	"VRD_emnaviSimpleHypothesisList" : "A state name",
	"VRD_emnaviStepByStep" : "Step by step entry",
	"VRD_emnaviTravelViaARecentDestination" : "Add Waypoint recent destination",
	"VRD_emnaviTravelViaAddress" : "Travel via address",
	"VRD_emnaviTravelViaHome" : "Travel via Home",
	"VRD_emnaviTryAgain" : "Try again",
	"VRD_emnaviUniSimpleHypothesisList" : "An address",
	"VRD_emnaviUniVDEHypothesisList" : "An address",
	"VRD_emnaviVDEHypothesisList" : "An address",
	"VRD_emnaviWhereAmI" : "Where am I",
	"VRD_emnaviZoomIn" : "Zoom In",
	"VRD_emnaviZoomOut" : "Zoom Out",
	"VRD_fmradioPlayStationFrequency" : "Tune to {frequency} FM",
	"VRD_fmradioSelectAutoMemory" : "Auto Memory",
	"VRD_fmradioSelectChangeGenre" : "Change Genre",
	"VRD_fmradioSelectFMSettings" : "FM Settings",
	"VRD_fmradioSelectFavorites" : "Favorites",
	"VRD_fmradioSelectGenreSeek" : "Genre Seek",
	"VRD_fmradioSelectHDChannel" : "{HD Channel}",
	"VRD_fmradioSelectHDChannels" : "HD Radio Stations",
	"VRD_fmradioSelectHDRadio" : "HD Radio",
	"VRD_fmradioSelectHDRadioOff" : "HD Radio Off",
	"VRD_fmradioSelectHDRadioOn" : "HD Radio On",
	"VRD_fmradioSelectScanOff" : "Scan Off",
	"VRD_fmradioSelectScanOn" : "Scan On",
	"VRD_fmradioSelectSeekNext" : "Seek Next",
	"VRD_fmradioSelectSeekPrevious" : "Seek Previous",
	"VRD_fmradioSelectSettings" : "Sound Settings",
	"VRD_fmradioSelectSource" : "Entertainment / Change Source",
	"VRD_fmradioSelectStationAll" : "All Stations",
	"VRD_fmradioSelectStationFrequency" : "{frequency}",
	"VRD_fmradioSelectStationGenre" : "{genreName}",
	"VRD_fmradioSelectStationList" : "Station List",
	"VRD_fmradioSelectStationName" : "{stationName}",
	"VRD_fmradioSelectTrafficAlert" : "Traffic Announcement",
	"VRD_fmradioSelectTrafficAlertOff" : "Traffic Off",
	"VRD_fmradioSelectTrafficAlertOn" : "Traffic On",
	"VRD_fmradioSelectTune" : "Tune",
	"VRD_fmradioSelectUpdateAutoMemory" : "Update Auto Memory",
	"VRD_fmradioSelectiTunesTagging" : "iTunes Tagging",
	"VRD_fmradioTuneDown" : "Tune Down",
	"VRD_fmradioTuneUp" : "Tune Up",
	"VRD_fmradioTurnOffAF" : "Alternate Frequency Off",
	"VRD_fmradioTurnOffREG" : "Region Lock Off",
	"VRD_fmradioTurnOnAF" : "Alternate Frequency On",
	"VRD_fmradioTurnOnREG" : "Region Lock On",
	"VRD_fmradioUpdateAutoMemory" : "Update Station List",
	"VRD_pandoraAddStation" : "新增電臺",
	"VRD_pandoraAddStationFromArtist" : "從演出者建立電臺",
	"VRD_pandoraAddStationFromSong" : "從歌曲建立電臺",
	"VRD_pandoraAddToFavorites" : "Add to Favorites",
	"VRD_pandoraBookmarkArtist" : "給演出者加書籤",
	"VRD_pandoraBookmarkSong" : "給歌曲加書籤",
	"VRD_pandoraCreateStation" : "建立電臺",
	"VRD_pandoraSelectAddCurrentStation" : "新增",
	"VRD_pandoraSelectDelete" : "刪除",
	"VRD_pandoraSelectEditDelete" : "刪除",
	"VRD_pandoraSelectEditMove" : "移動",
	"VRD_pandoraSelectEditReplace" : "取代",
	"VRD_pandoraSelectFavorites" : "Favorites",
	"VRD_pandoraSelectMove" : "移動",
	"VRD_pandoraSelectQuickMix" : "隨機播放",
	"VRD_pandoraSelectSettings" : "音效設定",
	"VRD_pandoraSelectSortBy" : "排序",
	"VRD_pandoraSelectSource" : "娛樂",
	"VRD_pandoraSelectStationList" : "電臺清單",
	"VRD_pandoraShowBookmarkOptions" : "書籤",
	"VRD_pandoraShowByAZ" : "依字母順序排序",
	"VRD_pandoraShowByDate" : "Sort by date",
	"VRD_pandoraSkip" : "跳過",
	"VRD_pandoraThumbsDown" : "Thumbs Down",
	"VRD_pandoraThumbsUp" : "Thumbs Up",
	"VRD_phoneCall" : "撥打電話",
	"VRD_phoneCallBack" : "回撥",
	"VRD_phoneCallByName" : "依姓名撥打電話",
	"VRD_phoneCallByNumber" : "依號碼撥打電話",
	"VRD_phoneCallContactType" : "撥打電話 {contactName} {contactType}",
	"VRD_phoneCallLast" : "Call Last Number",
	"VRD_phoneChooseContactType" : "{contactName} {contactType}",
	"VRD_phoneDialAnyNumber" : "撥打電話 {number}",
	"VRD_phoneDialpadClearAllDigits" : "清除全部數字",
	"VRD_phoneDialpadDeleteDigit" : "刪除",
	"VRD_phoneDialpadPhoneNumber" : "{phoneNumber}",
	"VRD_phoneReDial" : "重撥",
	"VRD_phoneSelectByName" : "Name",
	"VRD_phoneSelectByNumber" : "Number",
	"VRD_phoneSelectContactType" : "{contactType}",
	"VRD_phoneSelectDialPad" : "撥號鍵盤",
	"VRD_phoneSelectFavorites" : "我的最愛",
	"VRD_phoneSelectRecentCalls" : "最近通話",
	"VRD_phoneSelectRecentCallsAll" : "所有通話",
	"VRD_phoneSelectRecentCallsMissed" : "Missed Calls",
	"VRD_satradioBackSpaceDelete" : "刪除數字",
	"VRD_satradioChangeLockCode" : "Change PIN Code",
	"VRD_satradioEnterPIN" : "{4digitPin}",
	"VRD_satradioInitializeLockCode" : "Initialize PIN Code",
	"VRD_satradioPlayChannelName" : "播放 {channelName}",
	"VRD_satradioPlayStationNumber" : "調至 {channelNumber}",
	"VRD_satradioResetLockCode" : "Reset PIN Code",
	"VRD_satradioSeekNext" : "搜尋下一個 ",
	"VRD_satradioSeekPrevious" : "搜尋上一個 ",
	"VRD_satradioSelectChangeCategory" : "類別",
	"VRD_satradioSelectFavorites" : "Favorites",
	"VRD_satradioSelectParentalLock" : "Parental Lock",
	"VRD_satradioSelectScanOff" : "掃描關閉",
	"VRD_satradioSelectScanOn" : "掃描開啟",
	"VRD_satradioSelectSettings" : "音效設定",
	"VRD_satradioSelectSource" : "娛樂",
	"VRD_satradioSelectStation" : "電臺 {Station number}",
	"VRD_satradioSelectStationAll" : "所有頻道",
	"VRD_satradioSelectStationCategory" : "{categoryName}",
	"VRD_satradioSelectStationList" : "Channel List",
	"VRD_satradioTurnChannelLockOFF" : "解鎖當前頻道",
	"VRD_satradioTurnChannelLockON" : "鎖定當前頻道",
	"VRD_satradioTurnParentalLockOFF" : "工作階段鎖關閉",
	"VRD_satradioTurnParentalLockON" : "工作階段鎖開啟",
	"VRD_smsCallPhoneNumber" : "Call",
	"VRD_smsDelete" : "Delete",
	"VRD_smsImportMessages" : "Update Text Inbox",
	"VRD_smsReply" : "Reply",
	"VRD_smsSayAnyConversation" : "{senderName}",
	"VRD_smsSelectBody" : "Add Message",
	"VRD_smsSelectContactName" : "{ContactName}",
	"VRD_smsSelectContinueTextMessage" : "Continue Message",
	"VRD_smsSelectDiscard" : "Discard",
	"VRD_smsSelectInbox" : "SMS Inbox List",
	"VRD_smsSelectNone" : "None of these",
	"VRD_smsSelectRetry" : "Retry",
	"VRD_smsSelectReturn" : "Return",
	"VRD_smsSelectSend" : "Send",
	"VRD_stitcherAddToFavorites" : "Add to Favorites",
	"VRD_stitcherRemoveFromFavorites" : "Remove from Favorites",
	"VRD_stitcherSaveFavorites" : "儲存變更",
	"VRD_stitcherSelectSettings" : "音效設定",
	"VRD_stitcherSelectSource" : "娛樂",
	"VRD_stitcherSelectStationList" : "電臺清單",
	"VRD_stitcherThumbsDown" : "遜斃了",
	"VRD_stitcherThumbsUp" : "讚",
	"VRD_systemSelectAhaRadio" : "Aha 廣播電臺",
	"VRD_systemSelectAndroidAuto" : "Android Auto",
	"VRD_systemSelectApplications" : "應用程式",
	"VRD_systemSelectAuxIn" : "線路輸入/AUX",
	"VRD_systemSelectBTAudio" : "Bluetooth",
	"VRD_systemSelectCD" : "CD",
	"VRD_systemSelectCallHistory" : "通話歷史記錄",
	"VRD_systemSelectCarPlay" : "Car Play",
	"VRD_systemSelectCommunication" : "通訊",
	"VRD_systemSelectConnect" : "連線",
	"VRD_systemSelectContacts" : "聯繫人",
	"VRD_systemSelectDAB" : "DAB",
	"VRD_systemSelectDVD" : "DVD",
	"VRD_systemSelectDisplayClock" : "時鐘顯示",
	"VRD_systemSelectDisplayOff" : "顯示關閉",
	"VRD_systemSelectEmail" : "電子郵件",
	"VRD_systemSelectEntertainment" : "娛樂",
	"VRD_systemSelectEntertainmentMenu" : "娛樂選單",
	"VRD_systemSelectFavorites" : "我的最愛",
	"VRD_systemSelectNavigation" : "導航",
	"VRD_systemSelectNotifications" : "訊息",
	"VRD_systemSelectNotifyOff" : "關閉通知",
	"VRD_systemSelectPandora" : "Pandora",
	"VRD_systemSelectPhone" : "電話",
	"VRD_systemSelectRadioAM" : "AM 廣播電臺",
	"VRD_systemSelectRadioFM" : "FM 廣播電臺",
	"VRD_systemSelectRetry" : "重試",
	"VRD_systemSelectSatRadio" : "Satellite Radio",
	"VRD_systemSelectSettings" : "設定",
	"VRD_systemSelectSiri" : "Siri",
	"VRD_systemSelectSms" : "文字/SMS",
	"VRD_systemSelectStitcher" : "Stitcher",
	"VRD_systemSelectTV" : "TV",
	"VRD_systemSelectTrafficAlert" : "Traffic Announcement",
	"VRD_systemSelectTutorial" : "教程",
	"VRD_systemSelectUSB" : "USB",
	"VRD_systemSelectUSBA" : "USB 1",
	"VRD_systemSelectUSBB" : "USB 2",
	"VRD_systemSelectXmAudio" : "SXM 廣播電臺",
	"VRD_tvSelectView" : "View",
	"VRD_usbaudioBrowse" : "瀏覽",
	"VRD_usbaudioBrowseAlbum" : "瀏覽 {albumName}",
	"VRD_usbaudioBrowseAlbums" : "瀏覽專輯",
	"VRD_usbaudioBrowseAll" : "瀏覽全部歌曲或專輯或演出者",
	"VRD_usbaudioBrowseAnyAlbum" : "瀏覽[專輯] {albumName}",
	"VRD_usbaudioBrowseAnyArtist" : "瀏覽[演出者] {artistName}",
	"VRD_usbaudioBrowseAnyFolder" : "瀏覽資料夾 {folderName}",
	"VRD_usbaudioBrowseArtist" : "瀏覽 {artistName}",
	"VRD_usbaudioBrowseArtists" : "瀏覽演出者",
	"VRD_usbaudioBrowseAudiobooks" : "瀏覽有聲書",
	"VRD_usbaudioBrowseFolder" : "瀏覽 {folderName}",
	"VRD_usbaudioBrowseFolders" : "瀏覽資料夾",
	"VRD_usbaudioBrowseGenre" : "瀏覽[流派] {genreName}",
	"VRD_usbaudioBrowseGenres" : "瀏覽流派",
	"VRD_usbaudioBrowseLineNumber" : "瀏覽樂譜線 {lineNumber}",
	"VRD_usbaudioBrowsePlaylist" : "瀏覽播放清單 {playlistName}",
	"VRD_usbaudioBrowsePlaylists" : "瀏覽播放清單",
	"VRD_usbaudioBrowsePodcast" : "瀏覽播客 {podcastName}",
	"VRD_usbaudioBrowsePodcasts" : "瀏覽播客",
	"VRD_usbaudioBrowseSongs" : "瀏覽歌曲",
	"VRD_usbaudioChooseAlbumArtist" : "{artistName}",
	"VRD_usbaudioGenerateMoreLikeThis" : "更喜歡這個",
	"VRD_usbaudioPlayAlbums" : "播放專輯",
	"VRD_usbaudioPlayAll" : "播放全部",
	"VRD_usbaudioPlayAnyAlbum" : "播放[專輯] {albumName}",
	"VRD_usbaudioPlayAnyArtist" : "播放[演出者] {artistName}",
	"VRD_usbaudioPlayAnyFolder" : "播放資料夾 {folderName}",
	"VRD_usbaudioPlayArtistAlbum" : "播放 {artistName} {albumName}",
	"VRD_usbaudioPlayArtists" : "依演出者播放",
	"VRD_usbaudioPlayAudiobook" : "播放有聲書 {AudiobookName}",
	"VRD_usbaudioPlayAudiobooks" : "播放有聲書",
	"VRD_usbaudioPlayChapter" : "{chapterName}",
	"VRD_usbaudioPlayChapterIndex" : "播放章節 {index} {chapter}",
	"VRD_usbaudioPlayEpisode" : "{episodeName}",
	"VRD_usbaudioPlayFolder" : "播放 {folderName}",
	"VRD_usbaudioPlayFolders" : "播放資料夾",
	"VRD_usbaudioPlayGenre" : "播放[流派] {genreName}",
	"VRD_usbaudioPlayGenres" : "播放流派",
	"VRD_usbaudioPlayLineNumber" : "瀏覽[樂譜線] {lineNumber}",
	"VRD_usbaudioPlayPlaylist" : "依播放清單播放 {playlistName}",
	"VRD_usbaudioPlayPlaylists" : "依播放清單播放",
	"VRD_usbaudioPlayPodcast" : "播放播客 {PodcastName}",
	"VRD_usbaudioPlayPodcasts" : "播放播客",
	"VRD_usbaudioPlaySongs" : "播放歌曲",
	"VRD_usbaudioRepeat" : "重複 ",
	"VRD_usbaudioRepeatAll" : "重複全部",
	"VRD_usbaudioRepeatOff" : "重複關閉",
	"VRD_usbaudioRepeatSong" : "重複歌曲",
	"VRD_usbaudioRewind" : "倒帶",
	"VRD_usbaudioSelectAlbum" : "專輯 {albumName}",
	"VRD_usbaudioSelectAlbums" : "專輯",
	"VRD_usbaudioSelectAll" : "全部劇集或章節或歌曲或專輯或演出者",
	"VRD_usbaudioSelectArtist" : "演出者 {artistName}",
	"VRD_usbaudioSelectArtists" : "演出者",
	"VRD_usbaudioSelectAudiobook" : "{audiobookName}",
	"VRD_usbaudioSelectAudiobooks" : "有聲書",
	"VRD_usbaudioSelectFolder" : "資料夾 {folderName}",
	"VRD_usbaudioSelectFolders" : "資料夾",
	"VRD_usbaudioSelectGenre" : "流派 {genreName}",
	"VRD_usbaudioSelectGenres" : "流派",
	"VRD_usbaudioSelectPlaylist" : "播放清單 {playlistName}",
	"VRD_usbaudioSelectPlaylists" : "播放清單",
	"VRD_usbaudioSelectPodcast" : "{podcastName}",
	"VRD_usbaudioSelectPodcasts" : "播客",
	"VRD_usbaudioSelectRootFolder" : "根選單",
	"VRD_usbaudioSelectSettings" : "音效設定",
	"VRD_usbaudioSelectSongs" : "歌曲",
	"VRD_usbaudioSelectSourceMenu" : "娛樂",
	"VRD_usbaudioShuffle" : "隨機播放",
	"VRD_usbaudioShuffleOff" : "隨機播放關閉",
	"VRD_usbaudioShuffleOn" : "隨機播放開啟",
	"VRD_usbaudioSongList" : "歌曲清單",
	"VRD_xmaudioBackSpaceDelete" : "Delete Digits",
	"VRD_xmaudioChangeLockCode" : "Edit PIN Code",
	"VRD_xmaudioConfirmDelete" : "Delete",
	"VRD_xmaudioEnterPIN" : "{fourDigitPIN}",
	"VRD_xmaudioPlayChannelName" : "Play XM Channel {channelName}",
	"VRD_xmaudioPlayStationNumber" : "Tune to {channelNumber}",
	"VRD_xmaudioResetLockCode" : "Reset PIN Code",
	"VRD_xmaudioSelectCallXM" : "Call XM",
	"VRD_xmaudioSelectChangeCategory" : "Change Category",
	"VRD_xmaudioSelectContinueListening" : "Continue Listening",
	"VRD_xmaudioSelectDismiss" : "Dismiss",
	"VRD_xmaudioSelectEveryOccurance" : "Every Occurrence",
	"VRD_xmaudioSelectEveryOtherReport" : "Every Other Report",
	"VRD_xmaudioSelectEveryReport" : "Every Report",
	"VRD_xmaudioSelectExitTuneMix" : "Exit TuneMix",
	"VRD_xmaudioSelectFavorites" : "Favorites",
	"VRD_xmaudioSelectListenNow" : "Listen Now",
	"VRD_xmaudioSelectMove" : "Move",
	"VRD_xmaudioSelectNearestCity" : "Nearest City",
	"VRD_xmaudioSelectOnlyFirstAfterVehicleStart" : "Vehicle Start",
	"VRD_xmaudioSelectOnlyFirstOccuranceInGame" : "First Occurrence",
	"VRD_xmaudioSelectReplayAlert" : "Replay Alert",
	"VRD_xmaudioSelectReturnToPrevious" : "Return to Previous",
	"VRD_xmaudioSelectSFSportBaseball" : "Baseball",
	"VRD_xmaudioSelectSFSportNCAA" : "College Football",
	"VRD_xmaudioSelectSFSportNFL" : "Professional Football",
	"VRD_xmaudioSelectSFSportNHL" : "Hockey",
	"VRD_xmaudioSelectScanOff" : "Scan Off",
	"VRD_xmaudioSelectScanOn" : "Scan On",
	"VRD_xmaudioSelectSettings" : "Settings",
	"VRD_xmaudioSelectSoundSettings" : "Sound Settings",
	"VRD_xmaudioSelectSource" : "Entertainment",
	"VRD_xmaudioSelectStation" : "Station {channelNumber}",
	"VRD_xmaudioSelectStationAll" : "All Channels",
	"VRD_xmaudioSelectStationCategory" : "{categoryName}",
	"VRD_xmaudioSelectStationFeaturedFavorites" : "Featured Favorites",
	"VRD_xmaudioSelectStationList" : "Channels",
	"VRD_xmaudioSelectTuneMix" : "TuneMix",
	"VRD_xmaudioSelectTuneMixChannel" : "TuneMix Channel Options",
	"VRD_xmaudioSelectTuneMixChannelsOptions" : "Channel Options",
	"VRD_xmaudioSelectTuneMixCreation" : "Create New TuneMix Channel",
	"VRD_xmaudioSelectTuneMixEdit" : "Edit TuneMix Channel",
	"VRD_xmaudioSelectTuneMixEditOps" : "TuneMix Edit Options",
	"VRD_xmaudioSelectTuneMixRemove" : "Remove TuneMix Channel",
	"VRD_xmaudioSelectTuneMixRename" : "Rename TuneMix",
	"VRD_xmaudioSelectTurnAlertsOff" : "Turn Alerts Off",
	"VRD_xmaudioSelectiTunesTagging" : "iTunes Tagging",
	"VRD_xmaudioSetChannelLock" : "Lock Channel",
	"VRD_xmaudioSetParentalLock" : "Session Lock",
	"VRD_xmdataSelectFuelPrices" : "油價",
	"VRD_xmdataSelectMovies" : "電影",
	"VRD_xmdataSelectParking" : "泊車",
	"VRD_xmdataSelectSports" : "體育",
	"VRD_xmdataSelectStock" : "股票",
	"VRD_xmdataSelectTrafficPlus" : "交通加",
	"VRD_xmdataSelectWeatherForecast" : "天氣預報",
	"VRD_xmdataSelectWeatherRadar" : "氣候雷達",
	"VRD_xmdataSelectWeatherSecurityAlerts" : "天氣安全警示",
};

framework.registerAppDictLoaded("system", "mn_TW");