var __VrHelpPositionTable__systemAppDict_de_DE = {
	"HomeScreen_Help" : {
		"Right" : ["VrHelp_Favorites"],
		"Left" : ["VrHelp_Entertainment","VrHelp_Communication","VrHelp_Navigation","VrHelp_Settings","VrHelp_Applications"]
	}
};

var Localization_systemAppDict_de_DE = {
	//"stringId" : "localString"
	"ActiveCallItem" : "Aktiver Anruf",
	"AhaMaintError" : "aha-Wartungsfehler",
	"AhaRadio" : "aha",
	"AmRadio" : "AM",
	"AndroidAuto" : "Android Auto",
	"Applications" : "Anwendungen",
	"AudioSourceNotAvailableBTAudio" : "Bluetooth-Audio nicht verfügbar",
	"AudioSourceNotAvailableCD" : "CD wurde entfernt",
	"AudioSourceNotAvailableDVD" : "DVD wurde entfernt",
	"AudioSourceNotAvailableTV" : "TV nicht verfügbar",
	"AudioSourceNotAvailableUSB" : "USB-Gerät wurde gewechselt.",
	"AuxIn" : "AUX",
	"BT" : "BT",
	"Bluetooth" : "Bluetooth",
	"BluetoothWithDevice" : "Bluetooth - {deviceName}",
	"CallHistory" : "Anrufhistorie",
	"CarPlay" : "Apple CarPlay",
	"CdPlayer" : "CD",
	"ChannelOffAir" : "Sender sendet nicht",
	"ChannelUnauth" : "Unerlaubter Sender",
	"CheckAntenna" : "Antenne überprüfen",
	"CheckTuner" : "Tuner überprüfen",
	"Communication" : "Kommunikation",
	"Connect" : "Verbinden",
	"Contacts" : "Kontakte",
	"DVDItem" : "DVD",
	"DabRadio" : "DAB",
	"DialPhone" : "Wählen",
	"DidYouSay" : "Bitte wählen Sie...",
	"DisclaimerText" : "Ablenkung kann Unfälle verursachen. Nicht während der Fahrt benutzen. Immer auf das Fahren konzentrieren und die Verkehrsregeln beachten. Siehe Bedienungsanleitung.",
	"DisconnectThenReconnect" : "Fehler während Siri Start. Apple Device trennen und erneut verbinden.",
	"DriveRecord" : "Fahreintrag",
	"DriverIDItem" : "Auswahl Fahrer",
	"EcoenergyApp" : "Verbrauchsanzeige",
	"EcoenergyAppHEV" : "Fahranzeige",
	"Email" : "Email",
	"EngineOilLevel" : "Motorölstand",
	"Entertainment" : "Unterhaltung",
	"ErrorWhileStartingSiri" : "Fehler während Siri Start.",
	"FailedNotificationRetrieval" : "Meldungsliste kann nicht geladen werden",
	"FavoritesItem" : "Favoriten",
	"FmRadio" : "FM",
	"HDTrafficItem" : "HD Radio™ Verkehrskarte",
	"InitiateSiri" : "Sprechtaste länger drücken, um  die Siri Sitzung zu starten",
	"IntelligentDriveMasterItem" : "i-DM",
	"NavigationTitle" : "Navigation",
	"NoConnectionNotifyText" : "Möchten Sie jetzt ein Telefon verbinden?",
	"NoConnectionNotifyTitle" : "Kein Telefon angeschlossen",
	"NoDeviceText" : "Möchten Sie jetzt ein Gerät verbinden?",
	"NoDeviceTitle" : "Kein Gerät verbunden",
	"Notifications" : "Benachrichtigungen",
	"NotifyIgnore" : "Ignorieren",
	"NotifyIncomingMsg" : "Eingehende Nachricht von:",
	"NotifyOff" : "Benachr. aus",
	"NotifyRead" : "Lesen",
	"NotifyReadNow" : "Möchten Sie es nun lesen?",
	"Pandora" : "Pandora",
	"ReconnectAhaRadio" : "Ern. Bluetooth Audioverb. für aha Radio",
	"ReconnectBTAudio" : "Ern. Bluetooth Audioverb. z. WdgForts.",
	"ReconnectCD" : "Überprüfe CD, um Wiedergabe fortzus.",
	"ReconnectCarPlay" : "Apple CarPlay wird fortgesetzt.",
	"ReconnectDVD" : "Überprüfe DVD, um Wiedergabe fortzus.",
	"ReconnectEntMenuButton" : "Unterhaltungsmenü",
	"ReconnectFailedBTAudio" : "Kann Bluetooth-Audio Verbindung nicht wiederherstellen",
	"ReconnectFailedCD" : "CD wurde entfernt. Wiedergabe kann nicht fortgesetzt werden",
	"ReconnectFailedCarPlay" : "Erneute Verbindung von Apple CarPlay nicht möglich",
	"ReconnectFailedDVD" : "DVD wurde entfernt. Wiedergabe kann nicht fortgesetzt werden",
	"ReconnectFailedTV" : "TV nicht verfügbar. Wiedergabe kann nicht fortgesetzt werden.",
	"ReconnectFailedUSB" : "USB-Gerät wurde gewechselt. Wiedergabe kann nicht fortgesetzt werden",
	"ReconnectPandora" : "Ern. Bluetooth Audioverb. für Pandora",
	"ReconnectStitcher" : "Ern. Bluetooth Audioverb. für Stitcher",
	"ReconnectTV" : "Prüfe TV zum Fortsetzen der Wiedergabe",
	"ReconnectUSB" : "Ern. USB-Geräteverb. für Wiedergabe",
	"RetryLabel" : "Erneut versuchen",
	"SchedMaintenanceApp" : "Wartung",
	"ScreenReplication" : "Überprüfe Wiederholung",
	"SdarsRadio" : "XM",
	"Settings" : "Einstellungen",
	"SettingsCommunication" : "Einstellungen",
	"Siri" : "Siri",
	"SiriDisabled" : "Siri ist deaktiviert auf Apple Device",
	"Sms" : "SMS",
	"StitcherItem" : "Stitcher",
	"TVItem" : "TV",
	"TempWarning" : "Temperaturwarnung",
	"TempWarningText" : "Anzeige ist zu heiss. Bildschirmdarstellung kann verringert sein, bis er abkühlt",
	"TextDownloaded" : "SMS heruntergeladen",
	"TextSent" : "SMS gesendet",
	"TrafficAlertsItem" : "Verkehrsinformation",
	"USB" : "USB",
	"USB1AndroidAuto" : "USB 1 – Android Auto",
	"USB1CarPlay" : "USB 1 – Apple CarPlay",
	"USB2AndroidAuto" : "USB 2 – Android Auto",
	"UsbAudioA" : "USB 1",
	"UsbAudioAWithDevice" : "USB 1 - {deviceName}",
	"UsbAudioB" : "USB 2",
	"UsbAudioBWithDevice" : "USB 2 - {deviceName}",
	"UseCommander" : "Bitte verwenden Sie beim Fahren den Commander.",
	"VehicleDataTransferItem" : "Fahrzeugdaten-Übermittlung ",
	"VehicleStatusMonitor" : "Fahrzeugstatusanzeige",
	"VehicleTelemetryTransfer" : "Fahrzeugtelemetrie-Übertragung",
	"VideoSignalLost" : "Videosignal verloren",
	"VoiceNotSupported" : "Stimme nicht unterstützt ",
	"VoiceRecognition" : "Spracherkennung",
	"VrHelp_Applications" : "Anwendungen",
	"VrHelp_Communication" : "Kommunikation",
	"VrHelp_Entertainment" : "Unterhaltung",
	"VrHelp_Favorites" : "Favoriten",
	"VrHelp_Navigation" : "Navigation",
	"VrHelp_Settings" : "Einstellungen",
	"WarnGuidanceApp" : "Warnmeldungen",
	"WarningTitle" : "Achtung!",
	"XMAudio" : "SXM",
	"XMData" : "SXM Services",
	"agree" : "Ich stimme zu",
	"VRD_aharadioSelectCall" : "Anrufen",
	"VRD_aharadioSelectDiscard" : "Verwerfen",
	"VRD_aharadioSelectEpisodes" : "Episodenliste",
	"VRD_aharadioSelectLBSTab" : "In der Nähe",
	"VRD_aharadioSelectMainList" : "Aha-Hauptliste",
	"VRD_aharadioSelectMap" : "Karte",
	"VRD_aharadioSelectPresetsTab" : "Voreinstellung",
	"VRD_aharadioSelectSave" : "Speichern",
	"VRD_aharadioSelectSettings" : "Toneinstellungen",
	"VRD_aharadioSelectShout" : "Schrei",
	"VRD_aharadioSelectSource" : "Unterhaltung/Quelle ändern",
	"VRD_aharadioSelectThumbsDown" : "Ablehnen",
	"VRD_aharadioSelectThumbsUp" : "Akzeptieren",
	"VRD_amradioPlayStationFrequency" : "Einstellen auf {frequency} AM",
	"VRD_amradioSelectAutoMemory" : "Automatischer Speicher",
	"VRD_amradioSelectFavorites" : "Favoriten",
	"VRD_amradioSelectHD" : "HD Sender",
	"VRD_amradioSelectHDOff" : "HD Radio aus",
	"VRD_amradioSelectHDOn" : "HD Radio ein",
	"VRD_amradioSelectScanOff" : "Scannen aus",
	"VRD_amradioSelectScanOn" : "Scannen an",
	"VRD_amradioSelectSeekNext" : "Suche nächsten",
	"VRD_amradioSelectSeekPrevious" : "Suche vorherigen",
	"VRD_amradioSelectSettings" : "Toneinstellungen",
	"VRD_amradioSelectSource" : "Zum Unterhaltungsmenü gehen",
	"VRD_amradioSelectStationFrequency" : "{AMFrequency}",
	"VRD_amradioSelectTrafficAlert" : "Verkehrsmeldung",
	"VRD_amradioSelectTrafficAlertOff" : "Verkehrsmeldung aus",
	"VRD_amradioSelectTrafficAlertOn" : "Verkehrsmeldung ein",
	"VRD_amradioSelectTune" : "Einstellen",
	"VRD_amradioSelectUpdateAutoMemory" : "Automatische Speichersuche",
	"VRD_amradioSelectiTunesTagging" : "iTunes-Tagging",
	"VRD_amradioTuneDown" : "Einstellen nach unten",
	"VRD_amradioTuneUp" : "Einstellen nach oben",
	"VRD_amradioUpdateAutoMemory" : "Senderliste aktualisieren",
	"VRD_auxinSelectSettings" : "Toneinstellungen",
	"VRD_auxinSelectSource" : "Unterhaltung/Quelle ändern",
	"VRD_btaudioScanPlay" : "Scan-Wiedergabe",
	"VRD_btaudioSelectConnect" : "Verbinden",
	"VRD_btaudioSelectRootMenu" : "Stammmenü",
	"VRD_btaudioSelectSettings" : "Toneinstellungen",
	"VRD_btaudioSelectSource" : "Zum Unterhaltungsmenü gehen",
	"VRD_btaudioToggleRepeat" : "Wiederholen",
	"VRD_btaudioToggleShuffle" : "Mischen",
	"VRD_carplaySelectApplications" : "Anwendungen",
	"VRD_cdGoSettings" : "Toneinstellungen",
	"VRD_cdHandleStartScan" : "Scan starten",
	"VRD_cdPlayBeginning" : "Neu starten",
	"VRD_cdRepeatFolder" : "Ordner wiederholen",
	"VRD_cdRepeatOff" : "Wiederholen aus",
	"VRD_cdRepeatOn" : "Wiederholen an",
	"VRD_cdRepeatTrack" : "Titel wiederholen",
	"VRD_cdSelectCurrentFolder" : "Aktueller Ordner",
	"VRD_cdSelectRepeat" : "Wiederholen",
	"VRD_cdSelectRootFolder" : "Stammmenü",
	"VRD_cdSelectShuffle" : "Mischen",
	"VRD_cdSelectSource" : "Zum Unterhaltungsmenü gehen",
	"VRD_cdSelectTrackList" : "Titelliste",
	"VRD_cdSelectTrackNumber" : "Titel {Number} abspielen",
	"VRD_cdShuffleDisk" : "Disc mischen",
	"VRD_cdShuffleFolder" : "Ordner mischen",
	"VRD_cdShuffleOff" : "Mischen aus",
	"VRD_cdShuffleOn" : "Mischen an",
	"VRD_commonAddToFavorites" : "Zu Favoriten hinzufügen",
	"VRD_commonCancel" : "Abbrechen",
	"VRD_commonFastForward" : "Vorlauf",
	"VRD_commonGoBack" : "Zurück",
	"VRD_commonIntentParent" : "Übergeordnet",
	"VRD_commonIntentParentUSBAudio" : "Übergeordnet",
	"VRD_commonIntentUSBAudio" : "Zuhause",
	"VRD_commonIntentUSBAudioBG" : "Zuhause",
	"VRD_commonMenuUp" : "Menü nach oben",
	"VRD_commonNext" : "Nächster",
	"VRD_commonNo" : "Nein",
	"VRD_commonPageDown" : "Bild ab / Nach unten",
	"VRD_commonPageUp" : "Bild auf / Nach oben",
	"VRD_commonPause" : "Pause",
	"VRD_commonPrevious" : "Vorheriger",
	"VRD_commonResume" : "Wiedergeben/Fortsetzen",
	"VRD_commonRewind" : "Rücklauf",
	"VRD_commonSelectLineNumber" : "Linie {lineNumber}",
	"VRD_commonYes" : "Ja / OK",
	"VRD_contactsChooseContactName" : "{ContactName}",
	"VRD_contactsDisambiguateContactName" : "{ContactName} anzeigen",
	"VRD_contactsImportAll" : "Alle Kontakte importieren",
	"VRD_contactsImportCancel" : "Import abbr.",
	"VRD_contactsImportContacts" : "Kontakte bearbeiten",
	"VRD_contactsImportSingle" : "Ausgewählte Kontakte importieren",
	"VRD_contactsRemoveContact" : "Kontakt entfernen",
	"VRD_contactsSelectCall" : "Anrufen",
	"VRD_contactsSelectContactName" : "{ContactName}",
	"VRD_contactsSelectDownload" : "Herunterl.",
	"VRD_contactsSelectFavorites" : "Favoriten",
	"VRD_contactsSelectNone" : "keine davon",
	"VRD_contactsSelectReadContactName" : "Kontaktnamen lesen",
	"VRD_contactsSelectRemove" : "Entfernen",
	"VRD_contactsSelectRetry" : "Erneut versuchen",
	"VRD_contactsSendPhoneType" : "{phoneType}",
	"VRD_contactsShowAddress" : "Adresse",
	"VRD_dabDisplayDABSettings" : "DAB-Einstellungen",
	"VRD_dabDisplayEnsembleList" : "Ensemble wählen",
	"VRD_dabDisplayStationList" : "Senderliste",
	"VRD_dabSelectFavorites" : "Favoriten",
	"VRD_dabSelectScan" : "Abstimmen",
	"VRD_dabSelectSeekNext" : "Nächster",
	"VRD_dabSelectSeekPrevious" : "Vorheriger",
	"VRD_dabSelectSettings" : "Toneinstellungen",
	"VRD_dabSelectSource" : "Unterhaltung",
	"VRD_dabTAToggleOFF" : "Verkehr aus",
	"VRD_dabTAToggleON" : "Verkehr an",
	"VRD_dabTAToggleVois" : "Verkehrsmeldung (TA)",
	"VRD_dabUpdateStationList" : "Liste aktualisieren",
	"VRD_dvdClearPin" : "Ziffern löschen",
	"VRD_dvdSayGRating" : "G",
	"VRD_dvdSayPG12" : "P G Zwölf",
	"VRD_dvdSayR15" : "R Fünfzehn Plus",
	"VRD_dvdSayR18" : "--",
	"VRD_dvdSelectAspectRatio" : "Bildseitenverhältnis",
	"VRD_dvdSelectAudioSettings" : "Video-Einstellungen",
	"VRD_dvdSelectCameraAngle" : "Kamerawinkel",
	"VRD_dvdSelectEditPin" : "PIN-Code bearbeiten",
	"VRD_dvdSelectParentLock" : "Kindersicherung",
	"VRD_dvdSelectParentLockOff" : "Kindersicherung aus",
	"VRD_dvdSelectParentLockOn" : "Kindersicherung ein",
	"VRD_dvdSelectParentLockRating" : "Sicherheitsstufe Kindersicherung",
	"VRD_dvdSelectResetPin" : "PIN-Code zurücksetzen",
	"VRD_dvdSelectRootMenu" : "Stammmenü",
	"VRD_dvdSelectSettings" : "Toneinstellungen",
	"VRD_dvdSelectSource" : "Unterhaltung",
	"VRD_dvdSelectSubtitleOff" : "Untertitel Aus",
	"VRD_dvdSelectSubtitleOn" : "Untertitel Ein",
	"VRD_dvdSlowForward" : "Vorlauf",
	"VRD_dvdSlowRewind" : "Rücklauf",
	"VRD_dvdVUISendPin" : "{FourDigitPin}",
	"VRD_emailSelectAllAccounts" : "Alle Konten",
	"VRD_emailSelectCall" : "Anrufen",
	"VRD_emailSelectContactName" : "{ContactName}",
	"VRD_emailSelectContinueEmail" : "Email fortsetzen",
	"VRD_emailSelectDelete" : "Löschen",
	"VRD_emailSelectDiscard" : "Verwerfen",
	"VRD_emailSelectImportEmail" : "Posteingang aktualisieren",
	"VRD_emailSelectInbox" : "E-Mail-Postfach",
	"VRD_emailSelectInboxSelector" : "Eingang",
	"VRD_emailSelectMessage" : "Nachricht hinzufügen",
	"VRD_emailSelectNone" : "keine davon",
	"VRD_emailSelectReply" : "Antworten",
	"VRD_emailSelectReplyAll" : "Allen antworten",
	"VRD_emailSelectRetry" : "Erneut versuchen",
	"VRD_emailSelectReturn" : "Zurückgehen",
	"VRD_emailSelectSend" : "Senden",
	"VRD_emailSelectSenderName" : "{senderName}",
	"VRD_emnaviAcceptAvoidance" : "Bestätigen",
	"VRD_emnaviAddCurrentPosToFavourites" : "Aktuelle Position zu Favoriten hinzufügen",
	"VRD_emnaviAddWaypointCityCenter" : "Stadtzentrum als Wegpunkt hinzufügen",
	"VRD_emnaviAddWaypointDistrictCenter" : "Stadtteilzentrum als Wegpunkt hinzufügen",
	"VRD_emnaviAddWaypointFavorite" : "Favoriten als Wegpunkt hinzufügen",
	"VRD_emnaviAddWaypointPOI" : "Wegpunkt hinzufügen {poiHypList}",
	"VRD_emnaviAvoidRouteAhead" : "Vorausliegende Strecke vermeiden",
	"VRD_emnaviCancelRoute" : "Route abbrechen",
	"VRD_emnaviDecreaseAvoidanceLength" : "Weniger",
	"VRD_emnaviGoToCockpit" : "Start",
	"VRD_emnaviIncreaseAvoidanceLength" : "Mehr",
	"VRD_emnaviJPJ_VDEHypothesisList" : "Ein Stadtname",
	"VRD_emnaviNavigateHere" : "Leite mich hierhin",
	"VRD_emnaviNavigateHome" : "Leite mich nach Hause",
	"VRD_emnaviNavigateToARecentDestination" : "Leite mich zu einem vorherigen Ziel",
	"VRD_emnaviNavigateToAddress" : "Leite mich zur Adresse",
	"VRD_emnaviNavigateToCityCenter" : "Leite mich zum Stadtzentrum",
	"VRD_emnaviNavigateToDistrictCenter" : "Leite mich zum Stadtteilzentrum",
	"VRD_emnaviNavigateToFavorite" : "Leite mich zu Favoriten",
	"VRD_emnaviNavigateToPOI" : "Leite mich zu {poiHypList}",
	"VRD_emnaviNewDestination" : "Neues Ziel",
	"VRD_emnaviRepeatInstruction" : "Anweisung wiederholen",
	"VRD_emnaviRouteSummary" : "Routen-Zusammenfassung",
	"VRD_emnaviSelectCancelRoute" : "Route löschen",
	"VRD_emnaviSelectNavigateToAddress" : "Leite mich zu dieser Adresse",
	"VRD_emnaviSimpleHypothesisList" : "Ein Bundesstaatenname",
	"VRD_emnaviStepByStep" : "Schritt-für-Schritt-Eingabe",
	"VRD_emnaviTravelViaARecentDestination" : "Vorheriges Ziel als Wegpunkt hinzufügen",
	"VRD_emnaviTravelViaAddress" : "Über Adresse fahren",
	"VRD_emnaviTravelViaHome" : "Über zuhause fahren",
	"VRD_emnaviTryAgain" : "Erneut versuchen",
	"VRD_emnaviUniSimpleHypothesisList" : "Eine Adresse",
	"VRD_emnaviUniVDEHypothesisList" : "Eine Adresse",
	"VRD_emnaviVDEHypothesisList" : "Eine Adresse",
	"VRD_emnaviWhereAmI" : "Wo bin ich",
	"VRD_emnaviZoomIn" : "Vergrößern",
	"VRD_emnaviZoomOut" : "Verkleinern",
	"VRD_fmradioPlayStationFrequency" : "Einstellen auf {frequency}FM",
	"VRD_fmradioSelectAutoMemory" : "Automatischer Speicher",
	"VRD_fmradioSelectChangeGenre" : "Genre ändern",
	"VRD_fmradioSelectFMSettings" : "FM-Einstellungen",
	"VRD_fmradioSelectFavorites" : "Favoriten",
	"VRD_fmradioSelectGenreSeek" : "Genre-Suche",
	"VRD_fmradioSelectHDChannel" : "{HD Channel}",
	"VRD_fmradioSelectHDChannels" : "HD Sender",
	"VRD_fmradioSelectHDRadio" : "HD Radio",
	"VRD_fmradioSelectHDRadioOff" : "HD Radio aus",
	"VRD_fmradioSelectHDRadioOn" : "HD Radio ein",
	"VRD_fmradioSelectScanOff" : "Scannen aus",
	"VRD_fmradioSelectScanOn" : "Scannen an",
	"VRD_fmradioSelectSeekNext" : "Suche nächsten",
	"VRD_fmradioSelectSeekPrevious" : "Suche vorherigen",
	"VRD_fmradioSelectSettings" : "Toneinstellungen",
	"VRD_fmradioSelectSource" : "Unterhaltung/Quelle ändern",
	"VRD_fmradioSelectStationAll" : "Alle Sender",
	"VRD_fmradioSelectStationFrequency" : "{frequency}",
	"VRD_fmradioSelectStationGenre" : "{genreName}",
	"VRD_fmradioSelectStationList" : "Senderliste",
	"VRD_fmradioSelectStationName" : "{stationName}",
	"VRD_fmradioSelectTrafficAlert" : "Verkehrsmeldung (TA)",
	"VRD_fmradioSelectTrafficAlertOff" : "Verkehr aus",
	"VRD_fmradioSelectTrafficAlertOn" : "Verkehr an",
	"VRD_fmradioSelectTune" : "Einstellen",
	"VRD_fmradioSelectUpdateAutoMemory" : "Auto speicher aktualisieren",
	"VRD_fmradioSelectiTunesTagging" : "iTunes-Tagging",
	"VRD_fmradioTuneDown" : "Einstellen nach unten",
	"VRD_fmradioTuneUp" : "Einstellen nach oben",
	"VRD_fmradioTurnOffAF" : "Alternative Frequenz aus",
	"VRD_fmradioTurnOffREG" : "Regionale Sicherung ausschalten",
	"VRD_fmradioTurnOnAF" : "Alternative Frequenz an",
	"VRD_fmradioTurnOnREG" : "Regionale Sicherung einschalten",
	"VRD_fmradioUpdateAutoMemory" : "Senderliste aktualisieren",
	"VRD_pandoraAddStation" : "Sender hinzufügen",
	"VRD_pandoraAddStationFromArtist" : "Sender aus Künstler erstellen",
	"VRD_pandoraAddStationFromSong" : "Sender aus Lied erstellen",
	"VRD_pandoraAddToFavorites" : "Zu Favoriten hinzufügen",
	"VRD_pandoraBookmarkArtist" : "Lesezeichen für Interpreten setzen",
	"VRD_pandoraBookmarkSong" : "Lesezeichen für Titel setzen",
	"VRD_pandoraCreateStation" : "Sender erstellen",
	"VRD_pandoraSelectAddCurrentStation" : "Zu Favoriten hinzufügen",
	"VRD_pandoraSelectDelete" : "Löschen",
	"VRD_pandoraSelectEditDelete" : "Löschen",
	"VRD_pandoraSelectEditMove" : "Verschieben",
	"VRD_pandoraSelectEditReplace" : "Ersetzen",
	"VRD_pandoraSelectFavorites" : "Favoriten",
	"VRD_pandoraSelectMove" : "Verschieben",
	"VRD_pandoraSelectQuickMix" : "Mischen",
	"VRD_pandoraSelectSettings" : "Toneinstellungen",
	"VRD_pandoraSelectSortBy" : "Sortieren",
	"VRD_pandoraSelectSource" : "Unterhaltung",
	"VRD_pandoraSelectStationList" : "Senderliste",
	"VRD_pandoraShowBookmarkOptions" : "Lesezeichen",
	"VRD_pandoraShowByAZ" : "Alphabetisch sortieren",
	"VRD_pandoraShowByDate" : "Nach Datum sortieren",
	"VRD_pandoraSkip" : "Überspringen",
	"VRD_pandoraThumbsDown" : "Ablehnen",
	"VRD_pandoraThumbsUp" : "Akzeptieren",
	"VRD_phoneCall" : "Anrufen",
	"VRD_phoneCallBack" : "Zurückrufen",
	"VRD_phoneCallByName" : "Nach Namen anrufen",
	"VRD_phoneCallByNumber" : "Nach Nummer anrufen",
	"VRD_phoneCallContactType" : "{contactName} {contactType} anrufen",
	"VRD_phoneCallLast" : "Letzte Nummer anrufen",
	"VRD_phoneChooseContactType" : "{contactName} {contactType}",
	"VRD_phoneDialAnyNumber" : "{number} anrufen",
	"VRD_phoneDialpadClearAllDigits" : "Alle Ziffern löschen",
	"VRD_phoneDialpadDeleteDigit" : "Löschen",
	"VRD_phoneDialpadPhoneNumber" : "{phoneNumber}",
	"VRD_phoneReDial" : "Wahlwiederholung",
	"VRD_phoneSelectByName" : "Name",
	"VRD_phoneSelectByNumber" : "Nummer",
	"VRD_phoneSelectContactType" : "{contactType}",
	"VRD_phoneSelectDialPad" : "Wähltastatur",
	"VRD_phoneSelectFavorites" : "Favoriten",
	"VRD_phoneSelectRecentCalls" : "Vorherige Anrufe",
	"VRD_phoneSelectRecentCallsAll" : "Alle Anrufe",
	"VRD_phoneSelectRecentCallsMissed" : "Verpasste Anrufe",
	"VRD_satradioBackSpaceDelete" : "Ziffern löschen",
	"VRD_satradioChangeLockCode" : "PIN-Code",
	"VRD_satradioEnterPIN" : "{4digitPin}",
	"VRD_satradioInitializeLockCode" : "PIN-Code initialisieren",
	"VRD_satradioPlayChannelName" : "{channelName} wiedergeben",
	"VRD_satradioPlayStationNumber" : "Einstellen auf {channelNumber}",
	"VRD_satradioResetLockCode" : "PIN-Code zurücksetzen",
	"VRD_satradioSeekNext" : "Suche nächsten",
	"VRD_satradioSeekPrevious" : "Suche vorherigen",
	"VRD_satradioSelectChangeCategory" : "Kategorie",
	"VRD_satradioSelectFavorites" : "Favoriten",
	"VRD_satradioSelectParentalLock" : "Kindersicherung",
	"VRD_satradioSelectScanOff" : "Scannen aus",
	"VRD_satradioSelectScanOn" : "Scannen an",
	"VRD_satradioSelectSettings" : "Toneinstellungen",
	"VRD_satradioSelectSource" : "Unterhaltung",
	"VRD_satradioSelectStation" : "Sender {Station number}",
	"VRD_satradioSelectStationAll" : "Alle Sender",
	"VRD_satradioSelectStationCategory" : "{categoryName}",
	"VRD_satradioSelectStationList" : "Senderliste",
	"VRD_satradioTurnChannelLockOFF" : "Aktuelle Sender entsperren",
	"VRD_satradioTurnChannelLockON" : "Akt. Sender sperren",
	"VRD_satradioTurnParentalLockOFF" : "Session entsperren",
	"VRD_satradioTurnParentalLockON" : "Session sperren",
	"VRD_smsCallPhoneNumber" : "Anrufen",
	"VRD_smsDelete" : "Löschen",
	"VRD_smsImportMessages" : "SMS-Posteingang aktualisieren",
	"VRD_smsReply" : "Antworten",
	"VRD_smsSayAnyConversation" : "{senderName}",
	"VRD_smsSelectBody" : "Nachricht hinzufügen",
	"VRD_smsSelectContactName" : "{ContactName}",
	"VRD_smsSelectContinueTextMessage" : "Nachricht fortsetzen",
	"VRD_smsSelectDiscard" : "Verwerfen",
	"VRD_smsSelectInbox" : "SMS-Posteingangsliste",
	"VRD_smsSelectNone" : "keine davon",
	"VRD_smsSelectRetry" : "Erneut versuchen",
	"VRD_smsSelectReturn" : "Zurückgehen",
	"VRD_smsSelectSend" : "Senden",
	"VRD_stitcherAddToFavorites" : "Zu Favoriten hinzufügen",
	"VRD_stitcherRemoveFromFavorites" : "Aus Favoriten entfernen",
	"VRD_stitcherSaveFavorites" : "Änderungen speichern",
	"VRD_stitcherSelectSettings" : "Toneinstellungen",
	"VRD_stitcherSelectSource" : "Unterhaltung",
	"VRD_stitcherSelectStationList" : "Senderliste",
	"VRD_stitcherThumbsDown" : "Ablehnen",
	"VRD_stitcherThumbsUp" : "Akzeptieren",
	"VRD_systemSelectAhaRadio" : "Aha Radio",
	"VRD_systemSelectAndroidAuto" : "Android Auto",
	"VRD_systemSelectApplications" : "Anwendungen",
	"VRD_systemSelectAuxIn" : "Line-In/AUX",
	"VRD_systemSelectBTAudio" : "Bluetooth",
	"VRD_systemSelectCD" : "CD",
	"VRD_systemSelectCallHistory" : "Anrufhistorie",
	"VRD_systemSelectCarPlay" : "CarPlay",
	"VRD_systemSelectCommunication" : "Kommunikation",
	"VRD_systemSelectConnect" : "Verbinden",
	"VRD_systemSelectContacts" : "Kontakte",
	"VRD_systemSelectDAB" : "DAB",
	"VRD_systemSelectDVD" : "DVD",
	"VRD_systemSelectDisplayClock" : "Zeitanzeige",
	"VRD_systemSelectDisplayOff" : "Anzeige ausschalten",
	"VRD_systemSelectEmail" : "Email",
	"VRD_systemSelectEntertainment" : "Unterhaltung",
	"VRD_systemSelectEntertainmentMenu" : "Unterhaltungsmenü",
	"VRD_systemSelectFavorites" : "Favoriten",
	"VRD_systemSelectNavigation" : "Navigation",
	"VRD_systemSelectNotifications" : "Nachrichten",
	"VRD_systemSelectNotifyOff" : "Benachr. aus",
	"VRD_systemSelectPandora" : "Pandora",
	"VRD_systemSelectPhone" : "Phone",
	"VRD_systemSelectRadioAM" : "Radio AM",
	"VRD_systemSelectRadioFM" : "Radio FM",
	"VRD_systemSelectRetry" : "Erneut versuchen",
	"VRD_systemSelectSatRadio" : "Satellitenradio",
	"VRD_systemSelectSettings" : "Einstellungen",
	"VRD_systemSelectSiri" : "Siri",
	"VRD_systemSelectSms" : "Text / SMS",
	"VRD_systemSelectStitcher" : "Stitcher",
	"VRD_systemSelectTV" : "TV",
	"VRD_systemSelectTrafficAlert" : "Verkehrsmeldung (TA)",
	"VRD_systemSelectTutorial" : "Anleitung",
	"VRD_systemSelectUSB" : "USB",
	"VRD_systemSelectUSBA" : "USB 1",
	"VRD_systemSelectUSBB" : "USB 2",
	"VRD_systemSelectXmAudio" : "SXM Radio",
	"VRD_tvSelectView" : "Ansicht",
	"VRD_usbaudioBrowse" : "Durchsuchen",
	"VRD_usbaudioBrowseAlbum" : "{albumName} durchsuchen",
	"VRD_usbaudioBrowseAlbums" : "Album durchsuchen",
	"VRD_usbaudioBrowseAll" : "Alle Lieder oder Alben oder Interpreten durchsuchen",
	"VRD_usbaudioBrowseAnyAlbum" : "[Album] {albumName} durchsuchen",
	"VRD_usbaudioBrowseAnyArtist" : "[Interpret] {artistName} durchsuchen",
	"VRD_usbaudioBrowseAnyFolder" : "Ordner {folderName} durchsuchen",
	"VRD_usbaudioBrowseArtist" : "{artistName} durchsuchen",
	"VRD_usbaudioBrowseArtists" : "Interpret durchsuchen",
	"VRD_usbaudioBrowseAudiobooks" : "Hörbücher durchsuchen",
	"VRD_usbaudioBrowseFolder" : "{folderName} durchsuchen",
	"VRD_usbaudioBrowseFolders" : "Ordner durchsuchen",
	"VRD_usbaudioBrowseGenre" : "[Genre] {genreName} durchsuchen",
	"VRD_usbaudioBrowseGenres" : "Genre durchsuchen",
	"VRD_usbaudioBrowseLineNumber" : "Leitung {lineNumber} durchsuchen",
	"VRD_usbaudioBrowsePlaylist" : "Wiedergabeliste {playlistName} durchsuchen",
	"VRD_usbaudioBrowsePlaylists" : "Wiedergabeliste durchsuchen",
	"VRD_usbaudioBrowsePodcast" : "Podcast {podcastName} durchsuchen",
	"VRD_usbaudioBrowsePodcasts" : "Podcasts durchsuchen",
	"VRD_usbaudioBrowseSongs" : "Lied durchsuchen",
	"VRD_usbaudioChooseAlbumArtist" : "{artistName}",
	"VRD_usbaudioGenerateMoreLikeThis" : "Ähnliche Musik",
	"VRD_usbaudioPlayAlbums" : "Album wiedergeben",
	"VRD_usbaudioPlayAll" : "Alle wiedergeben",
	"VRD_usbaudioPlayAnyAlbum" : "[Album] {albumName} wiedergeben",
	"VRD_usbaudioPlayAnyArtist" : "[Interpret] {artistName} wiedergeben",
	"VRD_usbaudioPlayAnyFolder" : "Ordner {folderName} wiedergeben",
	"VRD_usbaudioPlayArtistAlbum" : "{artistName} {albumName} wiedergeben",
	"VRD_usbaudioPlayArtists" : "Interpret wiedergeben",
	"VRD_usbaudioPlayAudiobook" : "Hörbuch {AudiobookName} wiedergeben",
	"VRD_usbaudioPlayAudiobooks" : "Hörbücher wiedergeben",
	"VRD_usbaudioPlayChapter" : "{chapterName}",
	"VRD_usbaudioPlayChapterIndex" : "Kapitel {index} {chapter} wiedergeben",
	"VRD_usbaudioPlayEpisode" : "{episodeName}",
	"VRD_usbaudioPlayFolder" : "{folderName} wiedergeben",
	"VRD_usbaudioPlayFolders" : "Ordner wiedergeben",
	"VRD_usbaudioPlayGenre" : "[Genre] {genreName} wiedergeben",
	"VRD_usbaudioPlayGenres" : "Genre wiedergeben",
	"VRD_usbaudioPlayLineNumber" : "[Leitung] {lineNumber} wiedergeben",
	"VRD_usbaudioPlayPlaylist" : "Wiedergabeliste {playlistName} wiedergeben",
	"VRD_usbaudioPlayPlaylists" : "Wiedergabeliste wiedergeben",
	"VRD_usbaudioPlayPodcast" : "Podcast {PodcastName} wiedergeben",
	"VRD_usbaudioPlayPodcasts" : "Podcasts wiedergeben",
	"VRD_usbaudioPlaySongs" : "Lied wiedergeben",
	"VRD_usbaudioRepeat" : "Wiederholen",
	"VRD_usbaudioRepeatAll" : "Alles wiederholen",
	"VRD_usbaudioRepeatOff" : "Wiederholen aus",
	"VRD_usbaudioRepeatSong" : "Lied wiederholen",
	"VRD_usbaudioRewind" : "Rücklauf",
	"VRD_usbaudioSelectAlbum" : "Album {albumName}",
	"VRD_usbaudioSelectAlbums" : "Album",
	"VRD_usbaudioSelectAll" : "Alle Episoden oder Kapitel oder Lieder oder Alben oder Interpreten",
	"VRD_usbaudioSelectArtist" : "Interpret {artistName}",
	"VRD_usbaudioSelectArtists" : "Interpreten",
	"VRD_usbaudioSelectAudiobook" : "{audiobookName}",
	"VRD_usbaudioSelectAudiobooks" : "Audiobücher",
	"VRD_usbaudioSelectFolder" : "Ordner {folderName}",
	"VRD_usbaudioSelectFolders" : "Ordner",
	"VRD_usbaudioSelectGenre" : "Genre {genreName}",
	"VRD_usbaudioSelectGenres" : "Genre",
	"VRD_usbaudioSelectPlaylist" : "Wiedergabeliste {playlistName}",
	"VRD_usbaudioSelectPlaylists" : "Wiedergabeliste",
	"VRD_usbaudioSelectPodcast" : "{podcastName}",
	"VRD_usbaudioSelectPodcasts" : "Podcast",
	"VRD_usbaudioSelectRootFolder" : "Stammmenü",
	"VRD_usbaudioSelectSettings" : "Toneinstellungen",
	"VRD_usbaudioSelectSongs" : "Lied",
	"VRD_usbaudioSelectSourceMenu" : "Unterhaltung",
	"VRD_usbaudioShuffle" : "Mischen",
	"VRD_usbaudioShuffleOff" : "Mischen aus",
	"VRD_usbaudioShuffleOn" : "Mischen an",
	"VRD_usbaudioSongList" : "Lied-Liste",
	"VRD_xmaudioBackSpaceDelete" : "Ziffern löschen",
	"VRD_xmaudioChangeLockCode" : "PIN-Code bearbeiten",
	"VRD_xmaudioConfirmDelete" : "Löschen",
	"VRD_xmaudioEnterPIN" : "{fourDigitPIN}",
	"VRD_xmaudioPlayChannelName" : "XM-Kanal {channelName} wiedergeben",
	"VRD_xmaudioPlayStationNumber" : "Einstellen auf {channelNumber}",
	"VRD_xmaudioResetLockCode" : "PIN-Code zurücksetzen",
	"VRD_xmaudioSelectCallXM" : "XM anrufen",
	"VRD_xmaudioSelectChangeCategory" : "Kategorie wechseln",
	"VRD_xmaudioSelectContinueListening" : "Weiterhin zuhören",
	"VRD_xmaudioSelectDismiss" : "Verwerfen",
	"VRD_xmaudioSelectEveryOccurance" : "Jedes Vorkommnis",
	"VRD_xmaudioSelectEveryOtherReport" : "Jeder zweite Bericht",
	"VRD_xmaudioSelectEveryReport" : "Jeder Bericht",
	"VRD_xmaudioSelectExitTuneMix" : "TuneMix verlassen",
	"VRD_xmaudioSelectFavorites" : "Favoriten",
	"VRD_xmaudioSelectListenNow" : "Jetzt anhören",
	"VRD_xmaudioSelectMove" : "Verschieben",
	"VRD_xmaudioSelectNearestCity" : "Nächste Stadt",
	"VRD_xmaudioSelectOnlyFirstAfterVehicleStart" : "Fahrzeugstart",
	"VRD_xmaudioSelectOnlyFirstOccuranceInGame" : "Erstes Vorkommnis",
	"VRD_xmaudioSelectReplayAlert" : "Erneute Wiedergabemeldung",
	"VRD_xmaudioSelectReturnToPrevious" : "Zu vorherigem zurückkehren",
	"VRD_xmaudioSelectSFSportBaseball" : "Baseball",
	"VRD_xmaudioSelectSFSportNCAA" : "College Football",
	"VRD_xmaudioSelectSFSportNFL" : "Professionelles Football",
	"VRD_xmaudioSelectSFSportNHL" : "Hockey",
	"VRD_xmaudioSelectScanOff" : "Scannen aus",
	"VRD_xmaudioSelectScanOn" : "Scannen an",
	"VRD_xmaudioSelectSettings" : "Einstellungen",
	"VRD_xmaudioSelectSoundSettings" : "Toneinstellungen",
	"VRD_xmaudioSelectSource" : "Unterhaltung",
	"VRD_xmaudioSelectStation" : "Sender {channelNumber}",
	"VRD_xmaudioSelectStationAll" : "Alle Sender",
	"VRD_xmaudioSelectStationCategory" : "{categoryName}",
	"VRD_xmaudioSelectStationFeaturedFavorites" : "Vorgestellte Favoriten",
	"VRD_xmaudioSelectStationList" : "Kanäle",
	"VRD_xmaudioSelectTuneMix" : "TuneMix",
	"VRD_xmaudioSelectTuneMixChannel" : "TuneMix-Kanaloptionen",
	"VRD_xmaudioSelectTuneMixChannelsOptions" : "Kanaloptionen",
	"VRD_xmaudioSelectTuneMixCreation" : "Neuen TuneMix-Kanal erstellen",
	"VRD_xmaudioSelectTuneMixEdit" : "TuneMix-Kanal bearbeiten",
	"VRD_xmaudioSelectTuneMixEditOps" : "TuneMix-Bearbeitungsoptionen",
	"VRD_xmaudioSelectTuneMixRemove" : "TuneMix-Kanal entfernen",
	"VRD_xmaudioSelectTuneMixRename" : "TuneMix umbenennen",
	"VRD_xmaudioSelectTurnAlertsOff" : "Meldungen ausschalten",
	"VRD_xmaudioSelectiTunesTagging" : "iTunes-Tagging",
	"VRD_xmaudioSetChannelLock" : "Kanal sperren",
	"VRD_xmaudioSetParentalLock" : "Session Verriegelung",
	"VRD_xmdataSelectFuelPrices" : "Treibstoffpreise",
	"VRD_xmdataSelectMovies" : "Filme",
	"VRD_xmdataSelectParking" : "Parken",
	"VRD_xmdataSelectSports" : "Sport",
	"VRD_xmdataSelectStock" : "Aktien",
	"VRD_xmdataSelectTrafficPlus" : "Traffic Plus",
	"VRD_xmdataSelectWeatherForecast" : "Wetterbericht",
	"VRD_xmdataSelectWeatherRadar" : "Wetterradar",
	"VRD_xmdataSelectWeatherSecurityAlerts" : "Wetterwarnungen",
};

framework.registerAppDictLoaded("system", "de_DE");