var __VrHelpPositionTable__systemAppDict_pt_BR = {
	"HomeScreen_Help" : {
		"Right" : ["VrHelp_Favorites"],
		"Left" : ["VrHelp_Entertainment","VrHelp_Communication","VrHelp_Navigation","VrHelp_Settings","VrHelp_Applications"]
	}
};

var Localization_systemAppDict_pt_BR = {
	//"stringId" : "localString"
	"ActiveCallItem" : "Chamada ativa",
	"AhaMaintError" : "Erro de manutenção do aha",
	"AhaRadio" : "aha",
	"AmRadio" : "AM",
	"AndroidAuto" : "Android Auto",
	"Applications" : "Aplicativos",
	"AudioSourceNotAvailableBTAudio" : "Áudio Bluetooth indisponível",
	"AudioSourceNotAvailableCD" : "O CD foi removido",
	"AudioSourceNotAvailableDVD" : "DVD removido",
	"AudioSourceNotAvailableTV" : "TV não disponível",
	"AudioSourceNotAvailableUSB" : "Dispositivo USB alterado",
	"AuxIn" : "AUX",
	"BT" : "BT",
	"Bluetooth" : "Bluetooth",
	"BluetoothWithDevice" : "Bluetooth - {deviceName}",
	"CallHistory" : "Histórico de chamadas",
	"CarPlay" : "Apple CarPlay",
	"CdPlayer" : "CD",
	"ChannelOffAir" : "Canal fora do ar",
	"ChannelUnauth" : "Canal não autorizado",
	"CheckAntenna" : "Verifique a antena",
	"CheckTuner" : "Verifique o sintonizador",
	"Communication" : "Comunicação",
	"Connect" : "Conectar",
	"Contacts" : "Contatos",
	"DVDItem" : "DVD",
	"DabRadio" : "DAB",
	"DialPhone" : "Ligar para telefone",
	"DidYouSay" : "Did you say . . .",
	"DisclaimerText" : "Distrações podem causar acidentes. Não opere enquanto dirige. Concentre-se sempre na direção e obedeça às leis de trânsito. Consulte o manual do proprietário.",
	"DisconnectThenReconnect" : "Desconecte e conecte novamente Apple Device.",
	"DriveRecord" : "Registro de percurso",
	"DriverIDItem" : "Seleção de motorista",
	"EcoenergyApp" : "Monitor de economia",
	"EcoenergyAppHEV" : "Monitor de percurso",
	"Email" : "E-mail",
	"EngineOilLevel" : "Nível de óleo do motor",
	"Entertainment" : "Entretenimento",
	"ErrorWhileStartingSiri" : "Erro ao inicializar Siri",
	"FailedNotificationRetrieval" : "Não é possível recuperar lista de notificações",
	"FavoritesItem" : "Favoritos",
	"FmRadio" : "FM",
	"HDTrafficItem" : "Mapa de tráfego da HD Radio™",
	"InitiateSiri" : "Pressione e mantenha pressionado o botão Falar para iniciar uma sessão Siri",
	"IntelligentDriveMasterItem" : "i-DM",
	"NavigationTitle" : "Navegação",
	"NoConnectionNotifyText" : "Gostaria de conectar um telefone agora?",
	"NoConnectionNotifyTitle" : "Nenhum telefone Conectado",
	"NoDeviceText" : "Gostaria de conectar um dispositivo agora?",
	"NoDeviceTitle" : "Nenhum dispositivo conectado",
	"Notifications" : "Notificações",
	"NotifyIgnore" : "Ignorar",
	"NotifyIncomingMsg" : "Mensagem recebida de:",
	"NotifyOff" : "Notific. desl.",
	"NotifyRead" : "Ler",
	"NotifyReadNow" : "Gostaria de lê-la agora?",
	"Pandora" : "Pandora",
	"ReconnectAhaRadio" : "Reconectando Bluetooth para rádio aha",
	"ReconnectBTAudio" : "Reconectando Bluetooth para continuar",
	"ReconnectCD" : "Verificando CD para continuar reprod.",
	"ReconnectCarPlay" : "Retomando Apple CarPlay.",
	"ReconnectDVD" : "Verificando DVD para continuar reprod",
	"ReconnectEntMenuButton" : "Entretenimento",
	"ReconnectFailedBTAudio" : "Não é possível reconectar áudio Bluetooth",
	"ReconnectFailedCD" : "O CD foi removido. Não é possível continuar a reprodução.",
	"ReconnectFailedCarPlay" : "Não é possível reconectar o Apple CarPlay",
	"ReconnectFailedDVD" : "O DVD foi removido. Não é possível continuar a reprodução.",
	"ReconnectFailedTV" : "TV não disponível. Não é possível continuar reprodução.",
	"ReconnectFailedUSB" : "O dispositivo USB foi alterado. Não é possível continuar a reprodução.",
	"ReconnectPandora" : "Reconectando Bluetooth para Pandora",
	"ReconnectStitcher" : "Reconectando Bluetooth para Stitcher",
	"ReconnectTV" : "Verificando TV para continuar reprodução",
	"ReconnectUSB" : "Reconectando disp.  USB para continuar",
	"RetryLabel" : "Repetir",
	"SchedMaintenanceApp" : "Manutenção",
	"ScreenReplication" : "Replicação da tela",
	"SdarsRadio" : "XM",
	"Settings" : "Configurações",
	"SettingsCommunication" : "Configurações",
	"Siri" : "Siri",
	"SiriDisabled" : "Siri desativada no dispositivo Apple.",
	"Sms" : "Mensagens de texto",
	"StitcherItem" : "Stitcher",
	"TVItem" : "TV",
	"TempWarning" : "Alerta de temperatura",
	"TempWarningText" : "O Display está quente demais. O desempenho da tela pode diminuir até que o display esfrie.",
	"TextDownloaded" : "Msg baixada",
	"TextSent" : "Msg enviada",
	"TrafficAlertsItem" : "Informações de tráfego",
	"USB" : "USB",
	"USB1AndroidAuto" : "USB 1 - Android Auto",
	"USB1CarPlay" : "USB 1 - Apple CarPlay",
	"USB2AndroidAuto" : "USB 2 - Android Auto",
	"UsbAudioA" : "USB 1",
	"UsbAudioAWithDevice" : "USB 1 - {deviceName}",
	"UsbAudioB" : "USB 2",
	"UsbAudioBWithDevice" : "USB 2 - {deviceName}",
	"UseCommander" : "Use o comando enquanto dirige.",
	"VehicleDataTransferItem" : "Transf. dados veíc. ",
	"VehicleStatusMonitor" : "Monitor de status do veículo",
	"VehicleTelemetryTransfer" : "Transferência de Dados",
	"VideoSignalLost" : "Sinal de vídeo perdido",
	"VoiceNotSupported" : "Sem suporte a voz. ",
	"VoiceRecognition" : "Reconhecimento de voz",
	"VrHelp_Applications" : "Aplicações",
	"VrHelp_Communication" : "Comunicação",
	"VrHelp_Entertainment" : "Entretenimento",
	"VrHelp_Favorites" : "Favoritos",
	"VrHelp_Navigation" : "Navegação",
	"VrHelp_Settings" : "Definições",
	"WarnGuidanceApp" : "Alertas de orientação",
	"WarningTitle" : "ATENÇÃO!",
	"XMAudio" : "SXM",
	"XMData" : "SXM Services",
	"agree" : "Concordo",
	"VRD_aharadioSelectCall" : "Telefonar",
	"VRD_aharadioSelectDiscard" : "Descartar",
	"VRD_aharadioSelectEpisodes" : "Episode List",
	"VRD_aharadioSelectLBSTab" : "Nearby",
	"VRD_aharadioSelectMainList" : "Aha Main List",
	"VRD_aharadioSelectMap" : "Mapa",
	"VRD_aharadioSelectPresetsTab" : "Preset",
	"VRD_aharadioSelectSave" : "Salvar",
	"VRD_aharadioSelectSettings" : "Definições de som",
	"VRD_aharadioSelectShout" : "Gritar",
	"VRD_aharadioSelectSource" : "Entertainment / Change Source",
	"VRD_aharadioSelectThumbsDown" : "Desaprovar ",
	"VRD_aharadioSelectThumbsUp" : "Aprovar ",
	"VRD_amradioPlayStationFrequency" : "Tune to {frequency} AM",
	"VRD_amradioSelectAutoMemory" : "Auto Memory",
	"VRD_amradioSelectFavorites" : "Favorites",
	"VRD_amradioSelectHD" : "HD Radio Stations",
	"VRD_amradioSelectHDOff" : "HD Radio Off",
	"VRD_amradioSelectHDOn" : "HD Radio On",
	"VRD_amradioSelectScanOff" : "Scan Off",
	"VRD_amradioSelectScanOn" : "Scan On",
	"VRD_amradioSelectSeekNext" : "Seek Next",
	"VRD_amradioSelectSeekPrevious" : "Seek Previous",
	"VRD_amradioSelectSettings" : "Sound Settings",
	"VRD_amradioSelectSource" : "Go to Entertainment Menu",
	"VRD_amradioSelectStationFrequency" : "{AMFrequency}",
	"VRD_amradioSelectTrafficAlert" : "Traffic Alert",
	"VRD_amradioSelectTrafficAlertOff" : "Traffic Alert Off",
	"VRD_amradioSelectTrafficAlertOn" : "Traffic Alert On",
	"VRD_amradioSelectTune" : "Tune",
	"VRD_amradioSelectUpdateAutoMemory" : "Auto Memory Seek",
	"VRD_amradioSelectiTunesTagging" : "iTunes Tagging",
	"VRD_amradioTuneDown" : "Tune Down",
	"VRD_amradioTuneUp" : "Tune Up",
	"VRD_amradioUpdateAutoMemory" : "Update Station List",
	"VRD_auxinSelectSettings" : "Sound Settings",
	"VRD_auxinSelectSource" : "Entertainment / Change Source",
	"VRD_btaudioScanPlay" : "Procurar reproduzir",
	"VRD_btaudioSelectConnect" : "Ligar",
	"VRD_btaudioSelectRootMenu" : "Menu de raiz ",
	"VRD_btaudioSelectSettings" : "Definições de som",
	"VRD_btaudioSelectSource" : "Ir para menu de entretenimento",
	"VRD_btaudioToggleRepeat" : "Repetir",
	"VRD_btaudioToggleShuffle" : "Aleatório",
	"VRD_carplaySelectApplications" : "Applications",
	"VRD_cdGoSettings" : "Definições de som",
	"VRD_cdHandleStartScan" : "Iniciar procurar",
	"VRD_cdPlayBeginning" : "Recomeçar",
	"VRD_cdRepeatFolder" : "Repetir pasta",
	"VRD_cdRepeatOff" : "Repetir desactivado",
	"VRD_cdRepeatOn" : "Repeat On",
	"VRD_cdRepeatTrack" : "Repeat Track",
	"VRD_cdSelectCurrentFolder" : "Pasta atual",
	"VRD_cdSelectRepeat" : "Repetir",
	"VRD_cdSelectRootFolder" : "Menu de raiz ",
	"VRD_cdSelectShuffle" : "Aleatório",
	"VRD_cdSelectSource" : "Go to Entertainment Menu",
	"VRD_cdSelectTrackList" : "Lista de faixas",
	"VRD_cdSelectTrackNumber" : "Play Track {Number}",
	"VRD_cdShuffleDisk" : "Shuffle Disc",
	"VRD_cdShuffleFolder" : "Shuffle Folder",
	"VRD_cdShuffleOff" : "Shuffle Off",
	"VRD_cdShuffleOn" : "Shuffle On",
	"VRD_commonAddToFavorites" : "Add to Favorites",
	"VRD_commonCancel" : "Cancel",
	"VRD_commonFastForward" : "Fast Forward",
	"VRD_commonGoBack" : "Go Back",
	"VRD_commonIntentParent" : "Parent",
	"VRD_commonIntentParentUSBAudio" : "Parent",
	"VRD_commonIntentUSBAudio" : "Home",
	"VRD_commonIntentUSBAudioBG" : "Home",
	"VRD_commonMenuUp" : "Nenu Up",
	"VRD_commonNext" : "Next",
	"VRD_commonNo" : "No",
	"VRD_commonPageDown" : "Page Down / Scroll Down",
	"VRD_commonPageUp" : "Page Up / Scroll Up",
	"VRD_commonPause" : "Pause",
	"VRD_commonPrevious" : "Previous",
	"VRD_commonResume" : "Play / Resume",
	"VRD_commonRewind" : "Rewind",
	"VRD_commonSelectLineNumber" : "Line {lineNumber}",
	"VRD_commonYes" : "Yes / OK",
	"VRD_contactsChooseContactName" : "{ContactName}",
	"VRD_contactsDisambiguateContactName" : "Show {ContactName}",
	"VRD_contactsImportAll" : "Importar todos os contactos",
	"VRD_contactsImportCancel" : "Cancelar imp.",
	"VRD_contactsImportContacts" : "Editar contatos",
	"VRD_contactsImportSingle" : "Importar contato selecionado",
	"VRD_contactsRemoveContact" : "Remover contacto",
	"VRD_contactsSelectCall" : "Chamar",
	"VRD_contactsSelectContactName" : "{ContactName}",
	"VRD_contactsSelectDownload" : "Transferir",
	"VRD_contactsSelectFavorites" : "Favoritos",
	"VRD_contactsSelectNone" : "None of these",
	"VRD_contactsSelectReadContactName" : "Ler nome do contato",
	"VRD_contactsSelectRemove" : "Remover",
	"VRD_contactsSelectRetry" : "Tentar novamente",
	"VRD_contactsSendPhoneType" : "{phoneType}",
	"VRD_contactsShowAddress" : "Endereço",
	"VRD_dabDisplayDABSettings" : "Configurações DAB",
	"VRD_dabDisplayEnsembleList" : "Selecionar conjunto",
	"VRD_dabDisplayStationList" : "Lista de estações",
	"VRD_dabSelectFavorites" : "Favorites",
	"VRD_dabSelectScan" : "Procurar",
	"VRD_dabSelectSeekNext" : "Seguinte",
	"VRD_dabSelectSeekPrevious" : "Anterior",
	"VRD_dabSelectSettings" : "Definições de som",
	"VRD_dabSelectSource" : "Entretenimento",
	"VRD_dabTAToggleOFF" : "Info. de tráfeg. desativadas",
	"VRD_dabTAToggleON" : "Info. de tráfeg. ativadas",
	"VRD_dabTAToggleVois" : "Anúncio de tráfego (TA)",
	"VRD_dabUpdateStationList" : "Atualizar lista",
	"VRD_dvdClearPin" : "Delete Digits",
	"VRD_dvdSayGRating" : "G",
	"VRD_dvdSayPG12" : "P G Twelve",
	"VRD_dvdSayR15" : "R Fifteen Plus",
	"VRD_dvdSayR18" : "Nenhum",
	"VRD_dvdSelectAspectRatio" : "Proporção",
	"VRD_dvdSelectAudioSettings" : "Video Settings",
	"VRD_dvdSelectCameraAngle" : "Ângulo da câmera",
	"VRD_dvdSelectEditPin" : "Edit PIN Code",
	"VRD_dvdSelectParentLock" : "Bloqueio dos pais",
	"VRD_dvdSelectParentLockOff" : "Parental Lock Off",
	"VRD_dvdSelectParentLockOn" : "Parental Lock On",
	"VRD_dvdSelectParentLockRating" : "Class. bloqueio dos pais",
	"VRD_dvdSelectResetPin" : "Reset PIN Code",
	"VRD_dvdSelectRootMenu" : "Menu de raiz ",
	"VRD_dvdSelectSettings" : "Definições de som",
	"VRD_dvdSelectSource" : "Entretenimento",
	"VRD_dvdSelectSubtitleOff" : "Subtitle Off",
	"VRD_dvdSelectSubtitleOn" : "Subtitle On",
	"VRD_dvdSlowForward" : "Avançar",
	"VRD_dvdSlowRewind" : "Voltar",
	"VRD_dvdVUISendPin" : "{FourDigitPin}",
	"VRD_emailSelectAllAccounts" : "Todas as contas",
	"VRD_emailSelectCall" : "Telefonar",
	"VRD_emailSelectContactName" : "{ContactName}",
	"VRD_emailSelectContinueEmail" : "Continuar e-mail",
	"VRD_emailSelectDelete" : "Excluir",
	"VRD_emailSelectDiscard" : "Descartar",
	"VRD_emailSelectImportEmail" : "Atualizar caixa de entrada",
	"VRD_emailSelectInbox" : "Email Inbox",
	"VRD_emailSelectInboxSelector" : "Caixa de entrada",
	"VRD_emailSelectMessage" : "Adicionar mensagem",
	"VRD_emailSelectNone" : "init",
	"VRD_emailSelectReply" : "Responder",
	"VRD_emailSelectReplyAll" : "Responder a todos",
	"VRD_emailSelectRetry" : "Repetir",
	"VRD_emailSelectReturn" : "Voltar",
	"VRD_emailSelectSend" : "Enviar",
	"VRD_emailSelectSenderName" : "{senderName}",
	"VRD_emnaviAcceptAvoidance" : "Confirm",
	"VRD_emnaviAddCurrentPosToFavourites" : "Add current position to Favorites",
	"VRD_emnaviAddWaypointCityCenter" : "Add Waypoint City Center",
	"VRD_emnaviAddWaypointDistrictCenter" : "Add Waypoint District Center",
	"VRD_emnaviAddWaypointFavorite" : "Add Waypoint Favorite",
	"VRD_emnaviAddWaypointPOI" : "Add Waypoint {poiHypList}",
	"VRD_emnaviAvoidRouteAhead" : "Avoid route ahead",
	"VRD_emnaviCancelRoute" : "Cancel route",
	"VRD_emnaviDecreaseAvoidanceLength" : "Less",
	"VRD_emnaviGoToCockpit" : "Start",
	"VRD_emnaviIncreaseAvoidanceLength" : "More",
	"VRD_emnaviJPJ_VDEHypothesisList" : "A city name",
	"VRD_emnaviNavigateHere" : "Navigate Here",
	"VRD_emnaviNavigateHome" : "Navigate Home",
	"VRD_emnaviNavigateToARecentDestination" : "Navigate to a recent destination",
	"VRD_emnaviNavigateToAddress" : "Navigate to address",
	"VRD_emnaviNavigateToCityCenter" : "Navigate to City Center",
	"VRD_emnaviNavigateToDistrictCenter" : "Navigate to District Center",
	"VRD_emnaviNavigateToFavorite" : "Navigate to Favorite",
	"VRD_emnaviNavigateToPOI" : "Navigate to {poiHypList}",
	"VRD_emnaviNewDestination" : "New destination",
	"VRD_emnaviRepeatInstruction" : "Repeat instruction",
	"VRD_emnaviRouteSummary" : "Route summary",
	"VRD_emnaviSelectCancelRoute" : "Clear route",
	"VRD_emnaviSelectNavigateToAddress" : "Navigate to an address",
	"VRD_emnaviSimpleHypothesisList" : "A state name",
	"VRD_emnaviStepByStep" : "Step by step entry",
	"VRD_emnaviTravelViaARecentDestination" : "Add Waypoint recent destination",
	"VRD_emnaviTravelViaAddress" : "Travel via address",
	"VRD_emnaviTravelViaHome" : "Travel via Home",
	"VRD_emnaviTryAgain" : "Try again",
	"VRD_emnaviUniSimpleHypothesisList" : "An address",
	"VRD_emnaviUniVDEHypothesisList" : "An address",
	"VRD_emnaviVDEHypothesisList" : "An address",
	"VRD_emnaviWhereAmI" : "Where am I",
	"VRD_emnaviZoomIn" : "Zoom In",
	"VRD_emnaviZoomOut" : "Zoom Out",
	"VRD_fmradioPlayStationFrequency" : "Tune to {frequency} FM",
	"VRD_fmradioSelectAutoMemory" : "Auto Memory",
	"VRD_fmradioSelectChangeGenre" : "Change Genre",
	"VRD_fmradioSelectFMSettings" : "FM Settings",
	"VRD_fmradioSelectFavorites" : "Favorites",
	"VRD_fmradioSelectGenreSeek" : "Genre Seek",
	"VRD_fmradioSelectHDChannel" : "{HD Channel}",
	"VRD_fmradioSelectHDChannels" : "HD Radio Stations",
	"VRD_fmradioSelectHDRadio" : "HD Radio",
	"VRD_fmradioSelectHDRadioOff" : "HD Radio Off",
	"VRD_fmradioSelectHDRadioOn" : "HD Radio On",
	"VRD_fmradioSelectScanOff" : "Scan Off",
	"VRD_fmradioSelectScanOn" : "Scan On",
	"VRD_fmradioSelectSeekNext" : "Seek Next",
	"VRD_fmradioSelectSeekPrevious" : "Seek Previous",
	"VRD_fmradioSelectSettings" : "Sound Settings",
	"VRD_fmradioSelectSource" : "Entertainment / Change Source",
	"VRD_fmradioSelectStationAll" : "All Stations",
	"VRD_fmradioSelectStationFrequency" : "{frequency}",
	"VRD_fmradioSelectStationGenre" : "{genreName}",
	"VRD_fmradioSelectStationList" : "Station List",
	"VRD_fmradioSelectStationName" : "{stationName}",
	"VRD_fmradioSelectTrafficAlert" : "Traffic Announcement",
	"VRD_fmradioSelectTrafficAlertOff" : "Traffic Off",
	"VRD_fmradioSelectTrafficAlertOn" : "Traffic On",
	"VRD_fmradioSelectTune" : "Tune",
	"VRD_fmradioSelectUpdateAutoMemory" : "Update Auto Memory",
	"VRD_fmradioSelectiTunesTagging" : "iTunes Tagging",
	"VRD_fmradioTuneDown" : "Tune Down",
	"VRD_fmradioTuneUp" : "Tune Up",
	"VRD_fmradioTurnOffAF" : "Alternate Frequency Off",
	"VRD_fmradioTurnOffREG" : "Region Lock Off",
	"VRD_fmradioTurnOnAF" : "Alternate Frequency On",
	"VRD_fmradioTurnOnREG" : "Region Lock On",
	"VRD_fmradioUpdateAutoMemory" : "Update Station List",
	"VRD_pandoraAddStation" : "Adicionar estação",
	"VRD_pandoraAddStationFromArtist" : "Create Station from Artist",
	"VRD_pandoraAddStationFromSong" : "Create Station from Song",
	"VRD_pandoraAddToFavorites" : "Add to Favorites",
	"VRD_pandoraBookmarkArtist" : "Adicionar artista aos favoritos",
	"VRD_pandoraBookmarkSong" : " Adicionar a canção aos favoritos",
	"VRD_pandoraCreateStation" : "Criar estação",
	"VRD_pandoraSelectAddCurrentStation" : "Adicionar aos Favoritos",
	"VRD_pandoraSelectDelete" : "Excluir",
	"VRD_pandoraSelectEditDelete" : "Excluir",
	"VRD_pandoraSelectEditMove" : "Mover",
	"VRD_pandoraSelectEditReplace" : "Substituir",
	"VRD_pandoraSelectFavorites" : "Favorites",
	"VRD_pandoraSelectMove" : "Mover",
	"VRD_pandoraSelectQuickMix" : "Aleatório",
	"VRD_pandoraSelectSettings" : "Definições de som",
	"VRD_pandoraSelectSortBy" : "Sort",
	"VRD_pandoraSelectSource" : "Entretenimento",
	"VRD_pandoraSelectStationList" : "Lista de estações",
	"VRD_pandoraShowBookmarkOptions" : "Favorito",
	"VRD_pandoraShowByAZ" : "Sort alphabetically",
	"VRD_pandoraShowByDate" : "Sort by date",
	"VRD_pandoraSkip" : "Ignorar",
	"VRD_pandoraThumbsDown" : "Thumbs Down",
	"VRD_pandoraThumbsUp" : "Thumbs Up",
	"VRD_phoneCall" : "Chamar",
	"VRD_phoneCallBack" : "Chamada de retorno",
	"VRD_phoneCallByName" : "Chamar por nome",
	"VRD_phoneCallByNumber" : "Chamar por número",
	"VRD_phoneCallContactType" : "Chamar{contactName}{contactType}",
	"VRD_phoneCallLast" : "Call Last Number",
	"VRD_phoneChooseContactType" : "{contactName} {contactType}",
	"VRD_phoneDialAnyNumber" : "Chamar{number}",
	"VRD_phoneDialpadClearAllDigits" : "Limpar todos os dígitos",
	"VRD_phoneDialpadDeleteDigit" : "Excluir",
	"VRD_phoneDialpadPhoneNumber" : "{phoneNumber}",
	"VRD_phoneReDial" : "Remarcar",
	"VRD_phoneSelectByName" : "Name",
	"VRD_phoneSelectByNumber" : "Number",
	"VRD_phoneSelectContactType" : "{contactType}",
	"VRD_phoneSelectDialPad" : "Teclado de telefone",
	"VRD_phoneSelectFavorites" : "Favoritos",
	"VRD_phoneSelectRecentCalls" : "Chamadas recentes",
	"VRD_phoneSelectRecentCallsAll" : "Todas as chamadas",
	"VRD_phoneSelectRecentCallsMissed" : "Missed Calls",
	"VRD_satradioBackSpaceDelete" : "Delete Digits",
	"VRD_satradioChangeLockCode" : "Change PIN Code",
	"VRD_satradioEnterPIN" : "{4digitPin}",
	"VRD_satradioInitializeLockCode" : "Initialize PIN Code",
	"VRD_satradioPlayChannelName" : "Play {channelName}",
	"VRD_satradioPlayStationNumber" : "Tune to {channelNumber}",
	"VRD_satradioResetLockCode" : "Reset PIN Code",
	"VRD_satradioSeekNext" : "Procurar seguinte",
	"VRD_satradioSeekPrevious" : "Procurar anterior",
	"VRD_satradioSelectChangeCategory" : "Category",
	"VRD_satradioSelectFavorites" : "Favorites",
	"VRD_satradioSelectParentalLock" : "Parental Lock",
	"VRD_satradioSelectScanOff" : "Scan Off",
	"VRD_satradioSelectScanOn" : "Scan On",
	"VRD_satradioSelectSettings" : "Definições de som",
	"VRD_satradioSelectSource" : "Entretenimento",
	"VRD_satradioSelectStation" : "Station {Station number}",
	"VRD_satradioSelectStationAll" : "Todos os canais",
	"VRD_satradioSelectStationCategory" : "{categoryName}",
	"VRD_satradioSelectStationList" : "Channel List",
	"VRD_satradioTurnChannelLockOFF" : "Desbloquear canal atual",
	"VRD_satradioTurnChannelLockON" : "Bloquear canal atual",
	"VRD_satradioTurnParentalLockOFF" : "Bloqueio de sessão desativado",
	"VRD_satradioTurnParentalLockON" : "Bloqueio de sessão ativado",
	"VRD_smsCallPhoneNumber" : "Call",
	"VRD_smsDelete" : "Delete",
	"VRD_smsImportMessages" : "Update Text Inbox",
	"VRD_smsReply" : "Reply",
	"VRD_smsSayAnyConversation" : "{senderName}",
	"VRD_smsSelectBody" : "Add Message",
	"VRD_smsSelectContactName" : "{ContactName}",
	"VRD_smsSelectContinueTextMessage" : "Continue Message",
	"VRD_smsSelectDiscard" : "Discard",
	"VRD_smsSelectInbox" : "SMS Inbox List",
	"VRD_smsSelectNone" : "None of these",
	"VRD_smsSelectRetry" : "Retry",
	"VRD_smsSelectReturn" : "Return",
	"VRD_smsSelectSend" : "Send",
	"VRD_stitcherAddToFavorites" : "Add to Favorites",
	"VRD_stitcherRemoveFromFavorites" : "Remove from Favorites",
	"VRD_stitcherSaveFavorites" : "Salvar alterações",
	"VRD_stitcherSelectSettings" : "Definições de som",
	"VRD_stitcherSelectSource" : "Entretenimento",
	"VRD_stitcherSelectStationList" : "Lista de estações",
	"VRD_stitcherThumbsDown" : "Desaprovar ",
	"VRD_stitcherThumbsUp" : "Aprovar ",
	"VRD_systemSelectAhaRadio" : "Aha Radio",
	"VRD_systemSelectAndroidAuto" : "Android Auto",
	"VRD_systemSelectApplications" : "Aplicações",
	"VRD_systemSelectAuxIn" : "Entrada / AUX",
	"VRD_systemSelectBTAudio" : "Bluetooth",
	"VRD_systemSelectCD" : "CD",
	"VRD_systemSelectCallHistory" : "Histórico de chamadas",
	"VRD_systemSelectCarPlay" : "CarPlay",
	"VRD_systemSelectCommunication" : "Comunicação",
	"VRD_systemSelectConnect" : "Ligar",
	"VRD_systemSelectContacts" : "Contatos",
	"VRD_systemSelectDAB" : "DAB",
	"VRD_systemSelectDVD" : "DVD",
	"VRD_systemSelectDisplayClock" : "Ecrã do relógio",
	"VRD_systemSelectDisplayOff" : "Desligar ecrã",
	"VRD_systemSelectEmail" : "E-mail",
	"VRD_systemSelectEntertainment" : "Entretenimento",
	"VRD_systemSelectEntertainmentMenu" : "Menu de entretenimento",
	"VRD_systemSelectFavorites" : "Favoritos",
	"VRD_systemSelectNavigation" : "Navegação",
	"VRD_systemSelectNotifications" : "Mensagens",
	"VRD_systemSelectNotifyOff" : "Notific. desl.",
	"VRD_systemSelectPandora" : "Pandora",
	"VRD_systemSelectPhone" : "Telefone",
	"VRD_systemSelectRadioAM" : "Rádio AM",
	"VRD_systemSelectRadioFM" : "Rádio FM",
	"VRD_systemSelectRetry" : "Repetir",
	"VRD_systemSelectSatRadio" : "Satellite Radio",
	"VRD_systemSelectSettings" : "Definições",
	"VRD_systemSelectSiri" : "Siri",
	"VRD_systemSelectSms" : "Text / SMS",
	"VRD_systemSelectStitcher" : "Stitcher",
	"VRD_systemSelectTV" : "TV",
	"VRD_systemSelectTrafficAlert" : "Traffic Announcement",
	"VRD_systemSelectTutorial" : "Tutorial",
	"VRD_systemSelectUSB" : "USB",
	"VRD_systemSelectUSBA" : "USB 1",
	"VRD_systemSelectUSBB" : "USB 2",
	"VRD_systemSelectXmAudio" : "SXM Radio",
	"VRD_tvSelectView" : "View",
	"VRD_usbaudioBrowse" : "Browse",
	"VRD_usbaudioBrowseAlbum" : "Browse {albumName}",
	"VRD_usbaudioBrowseAlbums" : "Browse Album",
	"VRD_usbaudioBrowseAll" : "Browse All Songs or Albums or Artists",
	"VRD_usbaudioBrowseAnyAlbum" : "Browse [Album] {albumName}",
	"VRD_usbaudioBrowseAnyArtist" : "Browse [Artist] {artistName}",
	"VRD_usbaudioBrowseAnyFolder" : "Browse Folder {folderName}",
	"VRD_usbaudioBrowseArtist" : "Browse {artistName}",
	"VRD_usbaudioBrowseArtists" : "Browse Artist",
	"VRD_usbaudioBrowseAudiobooks" : "Browse Audiobooks",
	"VRD_usbaudioBrowseFolder" : "Browse {folderName}",
	"VRD_usbaudioBrowseFolders" : "Browse Folder",
	"VRD_usbaudioBrowseGenre" : "Browse [Genre] {genreName}",
	"VRD_usbaudioBrowseGenres" : "Browse Genre",
	"VRD_usbaudioBrowseLineNumber" : "Browse Line {lineNumber}",
	"VRD_usbaudioBrowsePlaylist" : "Browse Playlist {playlistName}",
	"VRD_usbaudioBrowsePlaylists" : "Browse Playlist",
	"VRD_usbaudioBrowsePodcast" : "Browse Podcast {podcastName}",
	"VRD_usbaudioBrowsePodcasts" : "Browse Podcasts",
	"VRD_usbaudioBrowseSongs" : "Browse Song",
	"VRD_usbaudioChooseAlbumArtist" : "{artistName}",
	"VRD_usbaudioGenerateMoreLikeThis" : "Semelhantes",
	"VRD_usbaudioPlayAlbums" : "Reproduzir álbum",
	"VRD_usbaudioPlayAll" : "Reproduzir tudo",
	"VRD_usbaudioPlayAnyAlbum" : "Play [Album] {albumName}",
	"VRD_usbaudioPlayAnyArtist" : "Play [Artist] {artistName}",
	"VRD_usbaudioPlayAnyFolder" : "Play Folder {folderName}",
	"VRD_usbaudioPlayArtistAlbum" : "Play {artistName} {albumName}",
	"VRD_usbaudioPlayArtists" : "Reproduzir artista",
	"VRD_usbaudioPlayAudiobook" : "Play Audiobook {AudiobookName}",
	"VRD_usbaudioPlayAudiobooks" : "Play Audiobooks",
	"VRD_usbaudioPlayChapter" : "{chapterName}",
	"VRD_usbaudioPlayChapterIndex" : "Play Chapter {index} {chapter}",
	"VRD_usbaudioPlayEpisode" : "{episodeName}",
	"VRD_usbaudioPlayFolder" : "Play {folderName}",
	"VRD_usbaudioPlayFolders" : "Play Folder",
	"VRD_usbaudioPlayGenre" : "Play [Genre] {genreName}",
	"VRD_usbaudioPlayGenres" : "Play Genre",
	"VRD_usbaudioPlayLineNumber" : "Play [Line] {lineNumber}",
	"VRD_usbaudioPlayPlaylist" : "Play Playlist {playlistName}",
	"VRD_usbaudioPlayPlaylists" : "Play Playlist",
	"VRD_usbaudioPlayPodcast" : "Play Podcast {PodcastName}",
	"VRD_usbaudioPlayPodcasts" : "Play Podcasts",
	"VRD_usbaudioPlaySongs" : "Play Song",
	"VRD_usbaudioRepeat" : "Repetir",
	"VRD_usbaudioRepeatAll" : "Repetir tudo",
	"VRD_usbaudioRepeatOff" : "Repeat Off",
	"VRD_usbaudioRepeatSong" : "Repeat Song",
	"VRD_usbaudioRewind" : "Voltar",
	"VRD_usbaudioSelectAlbum" : "Album {albumName}",
	"VRD_usbaudioSelectAlbums" : "Álbum",
	"VRD_usbaudioSelectAll" : "All Episodes or Chapters or Songs or Albums or Artists",
	"VRD_usbaudioSelectArtist" : "Artist {artistName}",
	"VRD_usbaudioSelectArtists" : "Artista",
	"VRD_usbaudioSelectAudiobook" : "{audiobookName}",
	"VRD_usbaudioSelectAudiobooks" : "Livros de áudio",
	"VRD_usbaudioSelectFolder" : "Folder {folderName}",
	"VRD_usbaudioSelectFolders" : "Pastas",
	"VRD_usbaudioSelectGenre" : "Genre {genreName}",
	"VRD_usbaudioSelectGenres" : "Gênero",
	"VRD_usbaudioSelectPlaylist" : "Playlist {playlistName}",
	"VRD_usbaudioSelectPlaylists" : "Lista de reprodução",
	"VRD_usbaudioSelectPodcast" : "{podcastName}",
	"VRD_usbaudioSelectPodcasts" : "Podcast",
	"VRD_usbaudioSelectRootFolder" : "Menu de raiz ",
	"VRD_usbaudioSelectSettings" : "Definições de som",
	"VRD_usbaudioSelectSongs" : "Música",
	"VRD_usbaudioSelectSourceMenu" : "Entretenimento",
	"VRD_usbaudioShuffle" : "Aleatório",
	"VRD_usbaudioShuffleOff" : "Shuffle Off",
	"VRD_usbaudioShuffleOn" : "Shuffle On",
	"VRD_usbaudioSongList" : "Lista de músicas",
	"VRD_xmaudioBackSpaceDelete" : "Delete Digits",
	"VRD_xmaudioChangeLockCode" : "Edit PIN Code",
	"VRD_xmaudioConfirmDelete" : "Delete",
	"VRD_xmaudioEnterPIN" : "{fourDigitPIN}",
	"VRD_xmaudioPlayChannelName" : "Play XM Channel {channelName}",
	"VRD_xmaudioPlayStationNumber" : "Tune to {channelNumber}",
	"VRD_xmaudioResetLockCode" : "Reset PIN Code",
	"VRD_xmaudioSelectCallXM" : "Call XM",
	"VRD_xmaudioSelectChangeCategory" : "Change Category",
	"VRD_xmaudioSelectContinueListening" : "Continue Listening",
	"VRD_xmaudioSelectDismiss" : "Dismiss",
	"VRD_xmaudioSelectEveryOccurance" : "Every Occurrence",
	"VRD_xmaudioSelectEveryOtherReport" : "Every Other Report",
	"VRD_xmaudioSelectEveryReport" : "Every Report",
	"VRD_xmaudioSelectExitTuneMix" : "Exit TuneMix",
	"VRD_xmaudioSelectFavorites" : "Favorites",
	"VRD_xmaudioSelectListenNow" : "Listen Now",
	"VRD_xmaudioSelectMove" : "Move",
	"VRD_xmaudioSelectNearestCity" : "Nearest City",
	"VRD_xmaudioSelectOnlyFirstAfterVehicleStart" : "Vehicle Start",
	"VRD_xmaudioSelectOnlyFirstOccuranceInGame" : "First Occurrence",
	"VRD_xmaudioSelectReplayAlert" : "Replay Alert",
	"VRD_xmaudioSelectReturnToPrevious" : "Return to Previous",
	"VRD_xmaudioSelectSFSportBaseball" : "Baseball",
	"VRD_xmaudioSelectSFSportNCAA" : "College Football",
	"VRD_xmaudioSelectSFSportNFL" : "Professional Football",
	"VRD_xmaudioSelectSFSportNHL" : "Hockey",
	"VRD_xmaudioSelectScanOff" : "Scan Off",
	"VRD_xmaudioSelectScanOn" : "Scan On",
	"VRD_xmaudioSelectSettings" : "Settings",
	"VRD_xmaudioSelectSoundSettings" : "Sound Settings",
	"VRD_xmaudioSelectSource" : "Entertainment",
	"VRD_xmaudioSelectStation" : "Station {channelNumber}",
	"VRD_xmaudioSelectStationAll" : "All Channels",
	"VRD_xmaudioSelectStationCategory" : "{categoryName}",
	"VRD_xmaudioSelectStationFeaturedFavorites" : "Featured Favorites",
	"VRD_xmaudioSelectStationList" : "Channels",
	"VRD_xmaudioSelectTuneMix" : "TuneMix",
	"VRD_xmaudioSelectTuneMixChannel" : "TuneMix Channel Options",
	"VRD_xmaudioSelectTuneMixChannelsOptions" : "Channel Options",
	"VRD_xmaudioSelectTuneMixCreation" : "Create New TuneMix Channel",
	"VRD_xmaudioSelectTuneMixEdit" : "Edit TuneMix Channel",
	"VRD_xmaudioSelectTuneMixEditOps" : "TuneMix Edit Options",
	"VRD_xmaudioSelectTuneMixRemove" : "Remove TuneMix Channel",
	"VRD_xmaudioSelectTuneMixRename" : "Rename TuneMix",
	"VRD_xmaudioSelectTurnAlertsOff" : "Turn Alerts Off",
	"VRD_xmaudioSelectiTunesTagging" : "iTunes Tagging",
	"VRD_xmaudioSetChannelLock" : "Lock Channel",
	"VRD_xmaudioSetParentalLock" : "Session Lock",
	"VRD_xmdataSelectFuelPrices" : "Fuel Prices",
	"VRD_xmdataSelectMovies" : "Movies",
	"VRD_xmdataSelectParking" : "Parking",
	"VRD_xmdataSelectSports" : "Esportes",
	"VRD_xmdataSelectStock" : "Stocks",
	"VRD_xmdataSelectTrafficPlus" : "Traffic Plus",
	"VRD_xmdataSelectWeatherForecast" : "Weather Forecast",
	"VRD_xmdataSelectWeatherRadar" : "Weather Radar",
	"VRD_xmdataSelectWeatherSecurityAlerts" : "Weather Security Alerts",
};

framework.registerAppDictLoaded("system", "pt_BR");