var __VrHelpPositionTable__systemAppDict_da_DK = {
	"HomeScreen_Help" : {
		"Right" : ["VrHelp_Favorites"],
		"Left" : ["VrHelp_Entertainment","VrHelp_Communication","VrHelp_Navigation","VrHelp_Settings","VrHelp_Applications"]
	}
};

var Localization_systemAppDict_da_DK = {
	//"stringId" : "localString"
	"ActiveCallItem" : "Aktivt opkald",
	"AhaMaintError" : "aha fejl i vedligeholdelse",
	"AhaRadio" : "aha",
	"AmRadio" : "AM",
	"AndroidAuto" : "Android Auto",
	"Applications" : "Applikationer",
	"AudioSourceNotAvailableBTAudio" : "Bluetooth-audio ikke disponibel",
	"AudioSourceNotAvailableCD" : "CD'en blev fjernet",
	"AudioSourceNotAvailableDVD" : "DVD'en blev fjernet",
	"AudioSourceNotAvailableTV" : "Tv ikke tilgængelig",
	"AudioSourceNotAvailableUSB" : "USB-enhed er skiftet",
	"AuxIn" : "AUX",
	"BT" : "BT",
	"Bluetooth" : "Bluetooth",
	"BluetoothWithDevice" : "Bluetooth - {deviceName}",
	"CallHistory" : "Opkaldshistorik",
	"CarPlay" : "Apple CarPlay",
	"CdPlayer" : "CD",
	"ChannelOffAir" : "Kanal ikke tilgængelig",
	"ChannelUnauth" : "Kanal ikke godkendt",
	"CheckAntenna" : "Kontrollér antennen",
	"CheckTuner" : "Kontrollér radio",
	"Communication" : "Kommunikation",
	"Connect" : "Tilslut",
	"Contacts" : "Kontakter",
	"DVDItem" : "DVD",
	"DabRadio" : "DAB",
	"DialPhone" : "Opkald",
	"DidYouSay" : "Sagde du. . .",
	"DisclaimerText" : "Forstyrrelser kan forårsage ulykker. Betjen ikke under kørsel. Koncentrér dig altid om kørslen og overhold færdselsreglerne. Se instruktionsbogen.",
	"DisconnectThenReconnect" : "Fejl under start af Siri. Frakobl, og tilkobl så Apple Device.",
	"DriveRecord" : "Kørebog",
	"DriverIDItem" : "Identifikation af fører",
	"EcoenergyApp" : "Økonomi",
	"EcoenergyAppHEV" : "Køreskærm",
	"Email" : "Email",
	"EngineOilLevel" : "Motorens oliestand",
	"Entertainment" : "Underholdning",
	"ErrorWhileStartingSiri" : "Fejl under start af Siri.",
	"FailedNotificationRetrieval" : "Kunne ikke hente notifikationsliste",
	"FavoritesItem" : "Favoritter",
	"FmRadio" : "FM",
	"HDTrafficItem" : "HD Radio™ Traffic Map",
	"InitiateSiri" : "Tryk og hold knappen nede for at starte en Siri-session",
	"IntelligentDriveMasterItem" : "i-DM",
	"NavigationTitle" : "Navigering",
	"NoConnectionNotifyText" : "Ønsker du at tilslutte telefonen nu?",
	"NoConnectionNotifyTitle" : "Ingen telefon tilsluttet",
	"NoDeviceText" : "Ønsker du at tilslutte en enhed nu?",
	"NoDeviceTitle" : "Der er ikke tilsluttet nogen enhed",
	"Notifications" : "Meddelelser",
	"NotifyIgnore" : "Ignorér",
	"NotifyIncomingMsg" : "Indgående besked fra:",
	"NotifyOff" : "Medl. Fra",
	"NotifyRead" : "Læs",
	"NotifyReadNow" : "Ønsker du at læse den nu?",
	"Pandora" : "Pandora",
	"ReconnectAhaRadio" : "Genforbinder Bluetooth audio",
	"ReconnectBTAudio" : "Genforbinder Bluetooth audio",
	"ReconnectCD" : "Verificerer CD for at genoptage afspiln.",
	"ReconnectCarPlay" : "Genoptager Apple CarPlay.",
	"ReconnectDVD" : "Verificerer DVD for at genoptage afsp.",
	"ReconnectEntMenuButton" : "Underholdningsmenu",
	"ReconnectFailedBTAudio" : "Kunne ikke genforbinde til Bluetooth-audio.",
	"ReconnectFailedCD" : "CD'en blev fjernet. Kunne ikke genoptage afspilning.",
	"ReconnectFailedCarPlay" : "Kunne ikke tilslutte Apple CarPlay",
	"ReconnectFailedDVD" : "DVD blev fjernet. Kan ikke genoptage afspilningen.",
	"ReconnectFailedTV" : "Tv ikke tilgængelig. Kan ikke genoptage afspilningen.",
	"ReconnectFailedUSB" : "USB-enhed er skiftet. Kunne ikke genoptage afspilning.",
	"ReconnectPandora" : "Genforbinder Bluetooth audio",
	"ReconnectStitcher" : "Genforbinder Bluetooth audio",
	"ReconnectTV" : "Verificerer tv for at genoptage afspilningen",
	"ReconnectUSB" : "Genforbinder USB-enhed",
	"RetryLabel" : "Prøv igen",
	"SchedMaintenanceApp" : "Vedligeholdelse",
	"ScreenReplication" : "Skærmkopiering",
	"SdarsRadio" : "XM",
	"Settings" : "Indstillinger",
	"SettingsCommunication" : "Indstillinger",
	"Siri" : "Siri",
	"SiriDisabled" : "Siri is Disabled on Apple Device.",
	"Sms" : "SMS",
	"StitcherItem" : "Stitcher",
	"TVItem" : "TV",
	"TempWarning" : "Temperaturadvarsel",
	"TempWarningText" : "Displayet er for varmt. Skærmens ydelse kan være nedsat, indtil den køler af.",
	"TextDownloaded" : "SMS hentet",
	"TextSent" : "SMS sendt",
	"TrafficAlertsItem" : "Trafikinformation",
	"USB" : "USB",
	"USB1AndroidAuto" : "USB 1 - Android Auto",
	"USB1CarPlay" : "USB 1 - Apple CarPlay",
	"USB2AndroidAuto" : "USB 2 - Android Auto",
	"UsbAudioA" : "USB 1",
	"UsbAudioAWithDevice" : "USB 1 - {deviceName}",
	"UsbAudioB" : "USB 2",
	"UsbAudioBWithDevice" : "USB 2 - {deviceName}",
	"UseCommander" : "Benyt venligst vognens commander-funktion under kørslen",
	"VehicleDataTransferItem" : "Overførsel af køretøjsdata ",
	"VehicleStatusMonitor" : "Køretøjsstatusmonitor",
	"VehicleTelemetryTransfer" : "OKT",
	"VideoSignalLost" : "Videosignalet mistet",
	"VoiceNotSupported" : "Voice understøttes ikke ",
	"VoiceRecognition" : "Stemmegenkendelse",
	"VrHelp_Applications" : "Applikationer",
	"VrHelp_Communication" : "Kommunikation",
	"VrHelp_Entertainment" : "Underholdning",
	"VrHelp_Favorites" : "Favoritter",
	"VrHelp_Navigation" : "Navigering",
	"VrHelp_Settings" : "Indstillinger",
	"WarnGuidanceApp" : "Advarselsvejledning",
	"WarningTitle" : "ADVARSEL!",
	"XMAudio" : "SXM",
	"XMData" : "XM Data",
	"agree" : "Jeg Accepterer",
	"VRD_aharadioSelectCall" : "Ring op",
	"VRD_aharadioSelectDiscard" : "Kassér",
	"VRD_aharadioSelectEpisodes" : "Episodeliste",
	"VRD_aharadioSelectLBSTab" : "I nærheden",
	"VRD_aharadioSelectMainList" : "Aha-hovedliste",
	"VRD_aharadioSelectMap" : "Kort",
	"VRD_aharadioSelectPresetsTab" : "Forudindstillet",
	"VRD_aharadioSelectSave" : "Gem",
	"VRD_aharadioSelectSettings" : "Lydindstillinger",
	"VRD_aharadioSelectShout" : "Shout",
	"VRD_aharadioSelectSource" : "Underholdning/Skift kilde",
	"VRD_aharadioSelectThumbsDown" : "Tommelfinger Nedad",
	"VRD_aharadioSelectThumbsUp" : "Tommelfinger Opad",
	"VRD_amradioPlayStationFrequency" : "Indstil til {frequency} AM",
	"VRD_amradioSelectAutoMemory" : "Automatisk hukommelse",
	"VRD_amradioSelectFavorites" : "Favoritter",
	"VRD_amradioSelectHD" : "HD-stationer",
	"VRD_amradioSelectHDOff" : "HD Radio fra",
	"VRD_amradioSelectHDOn" : "HD Radio til",
	"VRD_amradioSelectScanOff" : "Scan fra",
	"VRD_amradioSelectScanOn" : "Scan til",
	"VRD_amradioSelectSeekNext" : "Søg næste",
	"VRD_amradioSelectSeekPrevious" : "Søg forrige",
	"VRD_amradioSelectSettings" : "Lydindstillinger",
	"VRD_amradioSelectSource" : "Gå til underholdningsmenu",
	"VRD_amradioSelectStationFrequency" : "{AMFrequency}",
	"VRD_amradioSelectTrafficAlert" : "Trafikvarsel",
	"VRD_amradioSelectTrafficAlertOff" : "Trafikvarsel Fra",
	"VRD_amradioSelectTrafficAlertOn" : "Trafikvarsel Til",
	"VRD_amradioSelectTune" : "Indstil",
	"VRD_amradioSelectUpdateAutoMemory" : "Automatisk hukommelsessøgning",
	"VRD_amradioSelectiTunesTagging" : "iTunes Tagging",
	"VRD_amradioTuneDown" : "Frekvens ned",
	"VRD_amradioTuneUp" : "Frekvens op",
	"VRD_amradioUpdateAutoMemory" : "Opdatér stationsliste",
	"VRD_auxinSelectSettings" : "Lydindstillinger",
	"VRD_auxinSelectSource" : "Underholdning/Skift kilde",
	"VRD_btaudioScanPlay" : "Scan afspil",
	"VRD_btaudioSelectConnect" : "Tilslut",
	"VRD_btaudioSelectRootMenu" : "Hovedmenu",
	"VRD_btaudioSelectSettings" : "Lydindstillinger",
	"VRD_btaudioSelectSource" : "Gå til underholdningsmenu",
	"VRD_btaudioToggleRepeat" : "Gentag",
	"VRD_btaudioToggleShuffle" : "Bland",
	"VRD_carplaySelectApplications" : "Applikationer",
	"VRD_cdGoSettings" : "Lydindstillinger",
	"VRD_cdHandleStartScan" : "Start scanning",
	"VRD_cdPlayBeginning" : "Start forfra",
	"VRD_cdRepeatFolder" : "Gentag Mappe",
	"VRD_cdRepeatOff" : "Gentag Fra",
	"VRD_cdRepeatOn" : "Gentag Til",
	"VRD_cdRepeatTrack" : "Gentag Spor",
	"VRD_cdSelectCurrentFolder" : "Nuværende mappe",
	"VRD_cdSelectRepeat" : "Gentag",
	"VRD_cdSelectRootFolder" : "Hovedmenu",
	"VRD_cdSelectShuffle" : "Bland",
	"VRD_cdSelectSource" : "Gå til underholdningsmenu",
	"VRD_cdSelectTrackList" : "Trackliste",
	"VRD_cdSelectTrackNumber" : "Afspil nummer {Number} ",
	"VRD_cdShuffleDisk" : "Bland cd",
	"VRD_cdShuffleFolder" : "Bland mappe",
	"VRD_cdShuffleOff" : "Blanding Fra",
	"VRD_cdShuffleOn" : "Blanding Til",
	"VRD_commonAddToFavorites" : "Føj til favoritter",
	"VRD_commonCancel" : "Annullér",
	"VRD_commonFastForward" : "Hurtigt frem",
	"VRD_commonGoBack" : "Gå tilbage",
	"VRD_commonIntentParent" : "Forælder",
	"VRD_commonIntentParentUSBAudio" : "Forælder",
	"VRD_commonIntentUSBAudio" : "Hjem",
	"VRD_commonIntentUSBAudioBG" : "Hjem",
	"VRD_commonMenuUp" : "Menu op",
	"VRD_commonNext" : "Næste",
	"VRD_commonNo" : "Nej",
	"VRD_commonPageDown" : "Side ned / Rul ned",
	"VRD_commonPageUp" : "Side op / Rul op",
	"VRD_commonPause" : "Pause",
	"VRD_commonPrevious" : "Foregående",
	"VRD_commonResume" : "Afspil / Genoptag",
	"VRD_commonRewind" : "Spol tilbage",
	"VRD_commonSelectLineNumber" : "Linje {lineNumber}",
	"VRD_commonYes" : "Ja / OK",
	"VRD_contactsChooseContactName" : "{ContactName}",
	"VRD_contactsDisambiguateContactName" : "Vis {ContactName}",
	"VRD_contactsImportAll" : "Importér alle kontakter",
	"VRD_contactsImportCancel" : "Annull. import",
	"VRD_contactsImportContacts" : "Redigér kontakter",
	"VRD_contactsImportSingle" : "Importér valgt kontakt",
	"VRD_contactsRemoveContact" : "Fjern kontakt",
	"VRD_contactsSelectCall" : "Ring op",
	"VRD_contactsSelectContactName" : "{ContactName}",
	"VRD_contactsSelectDownload" : "Download",
	"VRD_contactsSelectFavorites" : "Favoritter",
	"VRD_contactsSelectNone" : "Ingen af disse",
	"VRD_contactsSelectReadContactName" : "Læs kontaktnavn",
	"VRD_contactsSelectRemove" : "Fjern",
	"VRD_contactsSelectRetry" : "Prøv igen",
	"VRD_contactsSendPhoneType" : "{phoneType}",
	"VRD_contactsShowAddress" : "Adresse",
	"VRD_dabDisplayDABSettings" : "DAB-indstillinger",
	"VRD_dabDisplayEnsembleList" : "Vælg Ensemble",
	"VRD_dabDisplayStationList" : "Stationsliste",
	"VRD_dabSelectFavorites" : "Favoritter",
	"VRD_dabSelectScan" : "Scan",
	"VRD_dabSelectSeekNext" : "Næste",
	"VRD_dabSelectSeekPrevious" : "Foregående",
	"VRD_dabSelectSettings" : "Lydindstillinger",
	"VRD_dabSelectSource" : "Underholdning",
	"VRD_dabTAToggleOFF" : "Trafik fra ",
	"VRD_dabTAToggleON" : "Trafik til",
	"VRD_dabTAToggleVois" : "Trafikvarsel (TA)",
	"VRD_dabUpdateStationList" : "Opdatér liste",
	"VRD_dvdClearPin" : "Slet tal",
	"VRD_dvdSayGRating" : "G",
	"VRD_dvdSayPG12" : "P G tolv",
	"VRD_dvdSayR15" : "R femten plus",
	"VRD_dvdSayR18" : "Ingen",
	"VRD_dvdSelectAspectRatio" : "Billedformat",
	"VRD_dvdSelectAudioSettings" : "Videoindstillinger",
	"VRD_dvdSelectCameraAngle" : "Kameravinkel ",
	"VRD_dvdSelectEditPin" : "Redigér PIN-kode",
	"VRD_dvdSelectParentLock" : "Børnesikring",
	"VRD_dvdSelectParentLockOff" : "Forældrelås fra",
	"VRD_dvdSelectParentLockOn" : "Forældrelås til",
	"VRD_dvdSelectParentLockRating" : "Børnesikringsklasse",
	"VRD_dvdSelectResetPin" : "Nulstil PIN-kode",
	"VRD_dvdSelectRootMenu" : "Hovedmenu",
	"VRD_dvdSelectSettings" : "Lydindstillinger",
	"VRD_dvdSelectSource" : "Underholdning",
	"VRD_dvdSelectSubtitleOff" : "Undertekster fra",
	"VRD_dvdSelectSubtitleOn" : "Undertekster til",
	"VRD_dvdSlowForward" : "Hurtigt frem",
	"VRD_dvdSlowRewind" : "Spol tilbage",
	"VRD_dvdVUISendPin" : "{FourDigitPin}",
	"VRD_emailSelectAllAccounts" : "Alle konti",
	"VRD_emailSelectCall" : "Ring op",
	"VRD_emailSelectContactName" : "{ContactName}",
	"VRD_emailSelectContinueEmail" : "Fortsæt Email",
	"VRD_emailSelectDelete" : "Slet",
	"VRD_emailSelectDiscard" : "Kassér",
	"VRD_emailSelectImportEmail" : "Opdatér indbakken",
	"VRD_emailSelectInbox" : "E-mailens indbakke",
	"VRD_emailSelectInboxSelector" : "Indbakke",
	"VRD_emailSelectMessage" : "Tilføj besked",
	"VRD_emailSelectNone" : "Ingen af disse",
	"VRD_emailSelectReply" : "Besvar",
	"VRD_emailSelectReplyAll" : "Svar alle",
	"VRD_emailSelectRetry" : "Prøv igen",
	"VRD_emailSelectReturn" : "Tilbage",
	"VRD_emailSelectSend" : "Send",
	"VRD_emailSelectSenderName" : "{senderName}",
	"VRD_emnaviAcceptAvoidance" : "Bekræft",
	"VRD_emnaviAddCurrentPosToFavourites" : "Tilføj aktuel position i Favoritter",
	"VRD_emnaviAddWaypointCityCenter" : "Tilføj rutepunkt for bycentrum",
	"VRD_emnaviAddWaypointDistrictCenter" : "Tilføj rutepunkt for områdecentrum",
	"VRD_emnaviAddWaypointFavorite" : "Tilføj foretrukket rutepunkt",
	"VRD_emnaviAddWaypointPOI" : "Tilføj rutepunkt {poiHypList}",
	"VRD_emnaviAvoidRouteAhead" : "Undgå kommende rute",
	"VRD_emnaviCancelRoute" : "Annullér rute",
	"VRD_emnaviDecreaseAvoidanceLength" : "Mindre",
	"VRD_emnaviGoToCockpit" : "Start",
	"VRD_emnaviIncreaseAvoidanceLength" : "Flere",
	"VRD_emnaviJPJ_VDEHypothesisList" : "Et bynavn",
	"VRD_emnaviNavigateHere" : "Navigér hertil",
	"VRD_emnaviNavigateHome" : "Navigér til start",
	"VRD_emnaviNavigateToARecentDestination" : "Navigér til en nylig destination",
	"VRD_emnaviNavigateToAddress" : "Navigér til adresse",
	"VRD_emnaviNavigateToCityCenter" : "Navigér til bycentrum",
	"VRD_emnaviNavigateToDistrictCenter" : "Navigér til områdecentrum",
	"VRD_emnaviNavigateToFavorite" : "Navigér til foretrukket",
	"VRD_emnaviNavigateToPOI" : "Navigér til {poiHypList}",
	"VRD_emnaviNewDestination" : "Ny destination",
	"VRD_emnaviRepeatInstruction" : "Gentag vejledning",
	"VRD_emnaviRouteSummary" : "Ruteoversigt",
	"VRD_emnaviSelectCancelRoute" : "Slet rute",
	"VRD_emnaviSelectNavigateToAddress" : "Navigér til en adresse",
	"VRD_emnaviSimpleHypothesisList" : "Et regionsnavn",
	"VRD_emnaviStepByStep" : "Indtast trin for trin",
	"VRD_emnaviTravelViaARecentDestination" : "Tilføj rutepunkt for nylig destination",
	"VRD_emnaviTravelViaAddress" : "Rejs via adresse",
	"VRD_emnaviTravelViaHome" : "Rejs via start",
	"VRD_emnaviTryAgain" : "Prøv igen",
	"VRD_emnaviUniSimpleHypothesisList" : "En adresse",
	"VRD_emnaviUniVDEHypothesisList" : "En adresse",
	"VRD_emnaviVDEHypothesisList" : "En adresse",
	"VRD_emnaviWhereAmI" : "Hvor er jeg",
	"VRD_emnaviZoomIn" : "Zoom ind",
	"VRD_emnaviZoomOut" : "Zoom ud",
	"VRD_fmradioPlayStationFrequency" : "Stil ind på {frequency} FM",
	"VRD_fmradioSelectAutoMemory" : "Automatisk hukommelse",
	"VRD_fmradioSelectChangeGenre" : "Skift genre",
	"VRD_fmradioSelectFMSettings" : "FM-indstillinger",
	"VRD_fmradioSelectFavorites" : "Favoritter",
	"VRD_fmradioSelectGenreSeek" : "Genre søgning",
	"VRD_fmradioSelectHDChannel" : "{HD Channel}",
	"VRD_fmradioSelectHDChannels" : "HD-stationer",
	"VRD_fmradioSelectHDRadio" : "HD Radio",
	"VRD_fmradioSelectHDRadioOff" : "HD Radio fra",
	"VRD_fmradioSelectHDRadioOn" : "HD Radio til",
	"VRD_fmradioSelectScanOff" : "Scan fra",
	"VRD_fmradioSelectScanOn" : "Scan til",
	"VRD_fmradioSelectSeekNext" : "Søg næste",
	"VRD_fmradioSelectSeekPrevious" : "Søg forrige",
	"VRD_fmradioSelectSettings" : "Lydindstillinger",
	"VRD_fmradioSelectSource" : "Underholdning/Skift kilde",
	"VRD_fmradioSelectStationAll" : "Alle stationer",
	"VRD_fmradioSelectStationFrequency" : "{frequency}",
	"VRD_fmradioSelectStationGenre" : "{genreName}",
	"VRD_fmradioSelectStationList" : "Stationsliste",
	"VRD_fmradioSelectStationName" : "{stationName}",
	"VRD_fmradioSelectTrafficAlert" : "Trafikvarsel (TA)",
	"VRD_fmradioSelectTrafficAlertOff" : "Trafik fra ",
	"VRD_fmradioSelectTrafficAlertOn" : "Trafik til",
	"VRD_fmradioSelectTune" : "Indstil",
	"VRD_fmradioSelectUpdateAutoMemory" : "Opdater Auto hukommelse",
	"VRD_fmradioSelectiTunesTagging" : "iTunes Tagging",
	"VRD_fmradioTuneDown" : "Frekvens ned",
	"VRD_fmradioTuneUp" : "Frekvens op",
	"VRD_fmradioTurnOffAF" : "Alternativ frekvens fra",
	"VRD_fmradioTurnOffREG" : "Regional fra",
	"VRD_fmradioTurnOnAF" : "Alternativ frekvens til",
	"VRD_fmradioTurnOnREG" : "Regional til",
	"VRD_fmradioUpdateAutoMemory" : "Opdatér stationsliste",
	"VRD_pandoraAddStation" : "Tilføj station",
	"VRD_pandoraAddStationFromArtist" : "Opret station fra Kunstner",
	"VRD_pandoraAddStationFromSong" : "Opret station fra Sang",
	"VRD_pandoraAddToFavorites" : "Føj til favoritter",
	"VRD_pandoraBookmarkArtist" : "Bogmærk kunstner",
	"VRD_pandoraBookmarkSong" : "Bogmærk sang",
	"VRD_pandoraCreateStation" : "Opret station",
	"VRD_pandoraSelectAddCurrentStation" : "Føj til ",
	"VRD_pandoraSelectDelete" : "Slet",
	"VRD_pandoraSelectEditDelete" : "Slet",
	"VRD_pandoraSelectEditMove" : "Flyt",
	"VRD_pandoraSelectEditReplace" : "Erstat",
	"VRD_pandoraSelectFavorites" : "Favoritter",
	"VRD_pandoraSelectMove" : "Flyt",
	"VRD_pandoraSelectQuickMix" : "Bland",
	"VRD_pandoraSelectSettings" : "Lydindstillinger",
	"VRD_pandoraSelectSortBy" : "Sortér",
	"VRD_pandoraSelectSource" : "Underholdning",
	"VRD_pandoraSelectStationList" : "Stationsliste",
	"VRD_pandoraShowBookmarkOptions" : "Bogmærke",
	"VRD_pandoraShowByAZ" : "Sortér alfabetisk",
	"VRD_pandoraShowByDate" : "Sorter efter dato",
	"VRD_pandoraSkip" : "Spring over",
	"VRD_pandoraThumbsDown" : "Tommelfinger Nedad",
	"VRD_pandoraThumbsUp" : "Tommelfinger Opad",
	"VRD_phoneCall" : "Ring op",
	"VRD_phoneCallBack" : "Ring tilbage",
	"VRD_phoneCallByName" : "Opkald efter navn",
	"VRD_phoneCallByNumber" : "Opkald efter nummer",
	"VRD_phoneCallContactType" : "Ring op{contactName}{contactType}",
	"VRD_phoneCallLast" : "Ring til sidste nummer",
	"VRD_phoneChooseContactType" : "{contactName} {contactType}",
	"VRD_phoneDialAnyNumber" : "Ring op{number}",
	"VRD_phoneDialpadClearAllDigits" : "Ryd alle tal",
	"VRD_phoneDialpadDeleteDigit" : "Slet",
	"VRD_phoneDialpadPhoneNumber" : "{phoneNumber}",
	"VRD_phoneReDial" : "Ring op igen",
	"VRD_phoneSelectByName" : "Navn",
	"VRD_phoneSelectByNumber" : "Nummer",
	"VRD_phoneSelectContactType" : "{contactType}",
	"VRD_phoneSelectDialPad" : "Tastatur",
	"VRD_phoneSelectFavorites" : "Favoritter",
	"VRD_phoneSelectRecentCalls" : "Seneste opkald",
	"VRD_phoneSelectRecentCallsAll" : "Alle opkald",
	"VRD_phoneSelectRecentCallsMissed" : "Ubesvarede opkald",
	"VRD_satradioBackSpaceDelete" : "Slet cifre",
	"VRD_satradioChangeLockCode" : "Skift PIN-kode",
	"VRD_satradioEnterPIN" : "{4digitPin}",
	"VRD_satradioInitializeLockCode" : "Initialisér PIN-kode",
	"VRD_satradioPlayChannelName" : "Afspil {channelName}",
	"VRD_satradioPlayStationNumber" : "Indstil til {channelNumber}",
	"VRD_satradioResetLockCode" : "Nulstil PIN-kode",
	"VRD_satradioSeekNext" : "Søg næste",
	"VRD_satradioSeekPrevious" : "Søg forrige",
	"VRD_satradioSelectChangeCategory" : "Kategori",
	"VRD_satradioSelectFavorites" : "Favoritter",
	"VRD_satradioSelectParentalLock" : "Børnesikring",
	"VRD_satradioSelectScanOff" : "Scan fra",
	"VRD_satradioSelectScanOn" : "Scan til",
	"VRD_satradioSelectSettings" : "Lydindstillinger",
	"VRD_satradioSelectSource" : "Underholdning",
	"VRD_satradioSelectStation" : "Station {Station number}",
	"VRD_satradioSelectStationAll" : "Alle kanaler",
	"VRD_satradioSelectStationCategory" : "{categoryName}",
	"VRD_satradioSelectStationList" : "Kanal liste",
	"VRD_satradioTurnChannelLockOFF" : "Lås nuværende kanal op",
	"VRD_satradioTurnChannelLockON" : "Lås nuværende kanal",
	"VRD_satradioTurnParentalLockOFF" : "Sessionslås fra",
	"VRD_satradioTurnParentalLockON" : "Sessionslås til",
	"VRD_smsCallPhoneNumber" : "Ring op",
	"VRD_smsDelete" : "Slet",
	"VRD_smsImportMessages" : "Opdaterer tekstindbakke",
	"VRD_smsReply" : "Besvar",
	"VRD_smsSayAnyConversation" : "{senderName}",
	"VRD_smsSelectBody" : "Tilføj besked",
	"VRD_smsSelectContactName" : "{ContactName}",
	"VRD_smsSelectContinueTextMessage" : "Fortsæt besked",
	"VRD_smsSelectDiscard" : "Kassér",
	"VRD_smsSelectInbox" : "Liste over SMS-indbakke",
	"VRD_smsSelectNone" : "Ingen af disse",
	"VRD_smsSelectRetry" : "Prøv igen",
	"VRD_smsSelectReturn" : "Tilbage",
	"VRD_smsSelectSend" : "Send",
	"VRD_stitcherAddToFavorites" : "Føj til favoritter",
	"VRD_stitcherRemoveFromFavorites" : "Fjern fra favoritter",
	"VRD_stitcherSaveFavorites" : "Gem ændringer",
	"VRD_stitcherSelectSettings" : "Lydindstillinger",
	"VRD_stitcherSelectSource" : "Underholdning",
	"VRD_stitcherSelectStationList" : "Stationsliste",
	"VRD_stitcherThumbsDown" : "Tommelfinger Nedad",
	"VRD_stitcherThumbsUp" : "Tommelfinger Opad",
	"VRD_systemSelectAhaRadio" : "Aha Radio",
	"VRD_systemSelectAndroidAuto" : "Android Auto",
	"VRD_systemSelectApplications" : "Applikationer",
	"VRD_systemSelectAuxIn" : "Linje In / AUX",
	"VRD_systemSelectBTAudio" : "Bluetooth",
	"VRD_systemSelectCD" : "CD",
	"VRD_systemSelectCallHistory" : "Opkaldshistorik",
	"VRD_systemSelectCarPlay" : "Car Play",
	"VRD_systemSelectCommunication" : "Kommunikation",
	"VRD_systemSelectConnect" : "Tilslut",
	"VRD_systemSelectContacts" : "Kontakter",
	"VRD_systemSelectDAB" : "DAB",
	"VRD_systemSelectDVD" : "DVD",
	"VRD_systemSelectDisplayClock" : "Urdisplay",
	"VRD_systemSelectDisplayOff" : "Sluk skærmen",
	"VRD_systemSelectEmail" : "Email",
	"VRD_systemSelectEntertainment" : "Underholdning",
	"VRD_systemSelectEntertainmentMenu" : "Underholdningsmenu",
	"VRD_systemSelectFavorites" : "Favoritter",
	"VRD_systemSelectNavigation" : "Navigering",
	"VRD_systemSelectNotifications" : "SMS",
	"VRD_systemSelectNotifyOff" : "Medl. Fra",
	"VRD_systemSelectPandora" : "Pandora",
	"VRD_systemSelectPhone" : "In-b.",
	"VRD_systemSelectRadioAM" : "AM radio",
	"VRD_systemSelectRadioFM" : "FM radio",
	"VRD_systemSelectRetry" : "Prøv igen",
	"VRD_systemSelectSatRadio" : "Satellitradio",
	"VRD_systemSelectSettings" : "Indstillinger",
	"VRD_systemSelectSiri" : "Siri",
	"VRD_systemSelectSms" : "Tekst / SMS",
	"VRD_systemSelectStitcher" : "Stitcher",
	"VRD_systemSelectTV" : "TV",
	"VRD_systemSelectTrafficAlert" : "Trafikvarsel (TA)",
	"VRD_systemSelectTutorial" : "Vejledning",
	"VRD_systemSelectUSB" : "USB",
	"VRD_systemSelectUSBA" : "USB 1",
	"VRD_systemSelectUSBB" : "USB 2",
	"VRD_systemSelectXmAudio" : "SXM Radio",
	"VRD_tvSelectView" : "Vis",
	"VRD_usbaudioBrowse" : "Gennemse",
	"VRD_usbaudioBrowseAlbum" : "Gennemse {albumName} ",
	"VRD_usbaudioBrowseAlbums" : "Gennemse album",
	"VRD_usbaudioBrowseAll" : "Gennemse alle sange eller albummer eller kunstnere",
	"VRD_usbaudioBrowseAnyAlbum" : "Gennemse [Mappe]  {albumName} ",
	"VRD_usbaudioBrowseAnyArtist" : "Gennemse [Kunstner] {artistName}",
	"VRD_usbaudioBrowseAnyFolder" : "Gennemse mappe{folderName}",
	"VRD_usbaudioBrowseArtist" : "Gennemse {artistName}",
	"VRD_usbaudioBrowseArtists" : "Gennemse Kunstner",
	"VRD_usbaudioBrowseAudiobooks" : "Gennemse lydbøger",
	"VRD_usbaudioBrowseFolder" : "Gennemse {folderName}",
	"VRD_usbaudioBrowseFolders" : "Gennemse mappe",
	"VRD_usbaudioBrowseGenre" : "Gennemse [Genre] {genreName}",
	"VRD_usbaudioBrowseGenres" : "Gennemse Genre",
	"VRD_usbaudioBrowseLineNumber" : "Gennemse linje {lineNumber}",
	"VRD_usbaudioBrowsePlaylist" : "Gennemse afspilningsliste {playlistName}",
	"VRD_usbaudioBrowsePlaylists" : "Gennemse afspilningsliste",
	"VRD_usbaudioBrowsePodcast" : "Gennemse podcast {podcastName}",
	"VRD_usbaudioBrowsePodcasts" : "Gennemse podcasts",
	"VRD_usbaudioBrowseSongs" : "Gennemse sang",
	"VRD_usbaudioChooseAlbumArtist" : "{artistName}",
	"VRD_usbaudioGenerateMoreLikeThis" : "Mere som dette",
	"VRD_usbaudioPlayAlbums" : "Afspil album",
	"VRD_usbaudioPlayAll" : "Afspil alle",
	"VRD_usbaudioPlayAnyAlbum" : "Afspil [Album] {albumName}",
	"VRD_usbaudioPlayAnyArtist" : "Afspil [Kunstner] {artistName}",
	"VRD_usbaudioPlayAnyFolder" : "Afspil [Mappe] {folderName}",
	"VRD_usbaudioPlayArtistAlbum" : "Afspil {artistName} {albumName}",
	"VRD_usbaudioPlayArtists" : "Afspil kunstner",
	"VRD_usbaudioPlayAudiobook" : "Afspil lydbog {AudiobookName}",
	"VRD_usbaudioPlayAudiobooks" : "Afspil lydbøger",
	"VRD_usbaudioPlayChapter" : "{chapterName}",
	"VRD_usbaudioPlayChapterIndex" : "Afspil kapitel {index} {chapter}",
	"VRD_usbaudioPlayEpisode" : "{episodeName}",
	"VRD_usbaudioPlayFolder" : "Afspil {folderName}",
	"VRD_usbaudioPlayFolders" : "Afspil mappe",
	"VRD_usbaudioPlayGenre" : "Afspil [Genre] {genreName}",
	"VRD_usbaudioPlayGenres" : "Afspil genre",
	"VRD_usbaudioPlayLineNumber" : "Afspil [Linje] {lineNumber}",
	"VRD_usbaudioPlayPlaylist" : "Afspil afspilningsliste {playlistName}",
	"VRD_usbaudioPlayPlaylists" : "Afspil afspilningsliste",
	"VRD_usbaudioPlayPodcast" : "Afspil podcast {PodcastName}",
	"VRD_usbaudioPlayPodcasts" : "Afspil podcast",
	"VRD_usbaudioPlaySongs" : "Afspil sang",
	"VRD_usbaudioRepeat" : "Gentag",
	"VRD_usbaudioRepeatAll" : "Gentag alle",
	"VRD_usbaudioRepeatOff" : "Gentag Fra",
	"VRD_usbaudioRepeatSong" : "Gentag Sang",
	"VRD_usbaudioRewind" : "Spol tilbage",
	"VRD_usbaudioSelectAlbum" : "Album {albumName}",
	"VRD_usbaudioSelectAlbums" : "Album",
	"VRD_usbaudioSelectAll" : "Gennemse alle episoder eller kapitler eller sange eller albummer eller kunstnere",
	"VRD_usbaudioSelectArtist" : "Kunstner {artistName}",
	"VRD_usbaudioSelectArtists" : "Kunstner",
	"VRD_usbaudioSelectAudiobook" : "{audiobookName}",
	"VRD_usbaudioSelectAudiobooks" : "Lydbøger",
	"VRD_usbaudioSelectFolder" : "Mappe {folderName}",
	"VRD_usbaudioSelectFolders" : "Mapper",
	"VRD_usbaudioSelectGenre" : "Genre {genreName}",
	"VRD_usbaudioSelectGenres" : "Genre",
	"VRD_usbaudioSelectPlaylist" : "Afspilningsliste {playlistName}",
	"VRD_usbaudioSelectPlaylists" : "Playliste",
	"VRD_usbaudioSelectPodcast" : "{podcastName}",
	"VRD_usbaudioSelectPodcasts" : "Podcast",
	"VRD_usbaudioSelectRootFolder" : "Hovedmenu",
	"VRD_usbaudioSelectSettings" : "Lydindstillinger",
	"VRD_usbaudioSelectSongs" : "Sang",
	"VRD_usbaudioSelectSourceMenu" : "Underholdning",
	"VRD_usbaudioShuffle" : "Bland",
	"VRD_usbaudioShuffleOff" : "Blanding Fra",
	"VRD_usbaudioShuffleOn" : "Blanding Til",
	"VRD_usbaudioSongList" : "Sangliste",
	"VRD_xmaudioBackSpaceDelete" : "Slet cifre",
	"VRD_xmaudioChangeLockCode" : "Redigér PIN-kode",
	"VRD_xmaudioConfirmDelete" : "Slet",
	"VRD_xmaudioEnterPIN" : "{fourDigitPIN}",
	"VRD_xmaudioPlayChannelName" : "Afspil XM-kanal {channelName}",
	"VRD_xmaudioPlayStationNumber" : "Indstil til {channelNumber}",
	"VRD_xmaudioResetLockCode" : "Nulstil PIN-kode",
	"VRD_xmaudioSelectCallXM" : "Opkald XM",
	"VRD_xmaudioSelectChangeCategory" : "Skift kategori",
	"VRD_xmaudioSelectContinueListening" : "Fortsæt med at lytte",
	"VRD_xmaudioSelectDismiss" : "Afvis",
	"VRD_xmaudioSelectEveryOccurance" : "Hver forekomst",
	"VRD_xmaudioSelectEveryOtherReport" : "Hver anden rapport",
	"VRD_xmaudioSelectEveryReport" : "Hver rapport",
	"VRD_xmaudioSelectExitTuneMix" : "Luk TuneMix",
	"VRD_xmaudioSelectFavorites" : "Favoritter",
	"VRD_xmaudioSelectListenNow" : "Lyt nu",
	"VRD_xmaudioSelectMove" : "Flyt",
	"VRD_xmaudioSelectNearestCity" : "Nærmeste by",
	"VRD_xmaudioSelectOnlyFirstAfterVehicleStart" : "Køretøjets start",
	"VRD_xmaudioSelectOnlyFirstOccuranceInGame" : "Første forekomst",
	"VRD_xmaudioSelectReplayAlert" : "Afspil varsel igen",
	"VRD_xmaudioSelectReturnToPrevious" : "Retur til forrige",
	"VRD_xmaudioSelectSFSportBaseball" : "Baseball",
	"VRD_xmaudioSelectSFSportNCAA" : "College Football",
	"VRD_xmaudioSelectSFSportNFL" : "Professional Football",
	"VRD_xmaudioSelectSFSportNHL" : "Hockey",
	"VRD_xmaudioSelectScanOff" : "Scan fra",
	"VRD_xmaudioSelectScanOn" : "Scan til",
	"VRD_xmaudioSelectSettings" : "Indstillinger",
	"VRD_xmaudioSelectSoundSettings" : "Lydindstillinger",
	"VRD_xmaudioSelectSource" : "Underholdning",
	"VRD_xmaudioSelectStation" : "Station {channelNumber}",
	"VRD_xmaudioSelectStationAll" : "Alle kanaler",
	"VRD_xmaudioSelectStationCategory" : "{categoryName}",
	"VRD_xmaudioSelectStationFeaturedFavorites" : "Foretrukne favoritter",
	"VRD_xmaudioSelectStationList" : "Kanaler",
	"VRD_xmaudioSelectTuneMix" : "TuneMix",
	"VRD_xmaudioSelectTuneMixChannel" : "Kanalindstillinger for TuneMix",
	"VRD_xmaudioSelectTuneMixChannelsOptions" : "Kanalindstillinger",
	"VRD_xmaudioSelectTuneMixCreation" : "Opret ny TuneMix-kanal",
	"VRD_xmaudioSelectTuneMixEdit" : "Redigér TuneMix-kanal",
	"VRD_xmaudioSelectTuneMixEditOps" : "Redigeringsindstillinger for TuneMix",
	"VRD_xmaudioSelectTuneMixRemove" : "Fjern TuneMix-kanal",
	"VRD_xmaudioSelectTuneMixRename" : "Omdøb TuneMix",
	"VRD_xmaudioSelectTurnAlertsOff" : "Slå varsler Fra",
	"VRD_xmaudioSelectiTunesTagging" : "iTunes Tagging",
	"VRD_xmaudioSetChannelLock" : "Lås kanal",
	"VRD_xmaudioSetParentalLock" : "Sessionslås",
	"VRD_xmdataSelectFuelPrices" : "Brændstofpriser",
	"VRD_xmdataSelectMovies" : "Film",
	"VRD_xmdataSelectParking" : "Parkering",
	"VRD_xmdataSelectSports" : "Sports",
	"VRD_xmdataSelectStock" : "Lagerbeholdninger",
	"VRD_xmdataSelectTrafficPlus" : "Trafik plus",
	"VRD_xmdataSelectWeatherForecast" : "Vejrudsigt",
	"VRD_xmdataSelectWeatherRadar" : "Satellitbilleder",
	"VRD_xmdataSelectWeatherSecurityAlerts" : "Vejrmæssige sikkerhedsvarsler",
};

framework.registerAppDictLoaded("system", "da_DK");