var __VrHelpPositionTable__systemAppDict_ja_JP = {
	"HomeScreen_Help" : {
		"Right" : ["VrHelp_Favorites"],
		"Left" : ["VrHelp_Entertainment","VrHelp_Communication","VrHelp_Navigation","VrHelp_Settings","VrHelp_Applications"]
	}
};

var Localization_systemAppDict_ja_JP = {
	//"stringId" : "localString"
	"ActiveCallItem" : "通話中画面",
	"AhaMaintError" : "aha Maintenance Error",
	"AhaRadio" : "aha",
	"AmRadio" : "AM",
	"AndroidAuto" : "Android Auto",
	"Applications" : "Applications",
	"AudioSourceNotAvailableBTAudio" : "Bluetooth Audio Not Available",
	"AudioSourceNotAvailableCD" : "CD was removed",
	"AudioSourceNotAvailableDVD" : "DVD was removed",
	"AudioSourceNotAvailableTV" : "TVは現在利用できません。",
	"AudioSourceNotAvailableUSB" : "USB device has changed",
	"AuxIn" : "AUX",
	"BT" : "BT",
	"Bluetooth" : "Bluetooth",
	"BluetoothWithDevice" : "Bluetooth - {deviceName}",
	"CallHistory" : "履歴",
	"CarPlay" : "Apple CarPlay",
	"CdPlayer" : "CD",
	"ChannelOffAir" : "Channel Off Air",
	"ChannelUnauth" : "Channel Unauthorized",
	"CheckAntenna" : "Check Antenna",
	"CheckTuner" : "Check Tuner",
	"Communication" : "Communication",
	"Connect" : "はい",
	"Contacts" : "連絡先",
	"DVDItem" : "DVD",
	"DabRadio" : "DAB",
	"DialPhone" : "ダイヤル",
	"DidYouSay" : "選択してください。",
	"DisclaimerText" : "運転される方は走行中に\n使用しないでください。\n走行する際は実際の交通規制に\n従ってください。",
	"DisconnectThenReconnect" : "Apple Deviceを切って、また接続してください。",
	"DriveRecord" : "ドライブレコード",
	"DriverIDItem" : "ドライバ選択",
	"EcoenergyApp" : "燃費モニター",
	"EcoenergyAppHEV" : "ドライブモニター",
	"Email" : "メール",
	"EngineOilLevel" : "エンジンオイルレベル",
	"Entertainment" : "Entertainment",
	"ErrorWhileStartingSiri" : "Siriを開始する際エラーが発生。",
	"FailedNotificationRetrieval" : "新着通知を取得できませんでした。",
	"FavoritesItem" : "お気に入り",
	"FmRadio" : "FM",
	"HDTrafficItem" : "HD Radio™ 交通マップ",
	"InitiateSiri" : "Siriセッションを開始する為にTalk Buttonを押し続けてください。",
	"IntelligentDriveMasterItem" : "i-DM",
	"NavigationTitle" : "Navigation",
	"NoConnectionNotifyText" : "接続しますか？",
	"NoConnectionNotifyTitle" : "Bluetooth機器が接続されていません。",
	"NoDeviceText" : "接続しますか？",
	"NoDeviceTitle" : "Bluetooth機器が接続されていません。",
	"Notifications" : "新着通知",
	"NotifyIgnore" : "あとで",
	"NotifyIncomingMsg" : "新着メッセージ",
	"NotifyOff" : "通知しない",
	"NotifyRead" : "読む",
	"NotifyReadNow" : "今すぐ読みますか？",
	"Pandora" : "Pandora",
	"ReconnectAhaRadio" : "ahaに接続中...",
	"ReconnectBTAudio" : "Bluetooth Audioに接続中...",
	"ReconnectCD" : "CD読み込み中...",
	"ReconnectCarPlay" : "Resuming Apple CarPlay.",
	"ReconnectDVD" : "DVD読み込み中...",
	"ReconnectEntMenuButton" : "Entertainment Menu",
	"ReconnectFailedBTAudio" : "Bluetooth接続エラーが発生しました。",
	"ReconnectFailedCD" : "CDを再生できませんでした。",
	"ReconnectFailedCarPlay" : "Unable to Reconnect Apple CarPlay",
	"ReconnectFailedDVD" : "DVDを再生できませんでした。",
	"ReconnectFailedTV" : "TVは現在利用できません。",
	"ReconnectFailedUSB" : "USBを再生できませんでした。",
	"ReconnectPandora" : "Pandoraに接続中...",
	"ReconnectStitcher" : "Stitcherに接続中...",
	"ReconnectTV" : "TV準備中…",
	"ReconnectUSB" : "USB読み込み中...",
	"RetryLabel" : "リトライ",
	"SchedMaintenanceApp" : "メンテナンス",
	"ScreenReplication" : "画面複製",
	"SdarsRadio" : "XM",
	"Settings" : "Settings",
	"SettingsCommunication" : "設定",
	"Siri" : "Siri",
	"SiriDisabled" : "Apple DeviceでSiriが無効にされています。",
	"Sms" : "SMS",
	"StitcherItem" : "Stitcher",
	"TVItem" : "TV",
	"TempWarning" : "温度警告",
	"TempWarningText" : "ディスプレイが高温になっています。\n温度が下がるまで、画面の性能が\n低下するおそれがあります。",
	"TextDownloaded" : "SMS更新完了",
	"TextSent" : "SMS送信完了",
	"TrafficAlertsItem" : "交通情報",
	"USB" : "USB",
	"USB1AndroidAuto" : "USB 1 - Android Auto",
	"USB1CarPlay" : "USB 1 - Apple CarPlay",
	"USB2AndroidAuto" : "USB 2 - Android Auto",
	"UsbAudioA" : "USB 1",
	"UsbAudioAWithDevice" : "USB 1 - {deviceName}",
	"UsbAudioB" : "USB 2",
	"UsbAudioBWithDevice" : "USB 2 - {deviceName}",
	"UseCommander" : "運転中はリモコンを使用してください。",
	"VehicleDataTransferItem" : "車両状態の送信 ",
	"VehicleStatusMonitor" : "車両ステータス",
	"VehicleTelemetryTransfer" : "車両状態の送信",
	"VideoSignalLost" : "Lost Video Signal",
	"VoiceNotSupported" : "音声には対応していません。 ",
	"VoiceRecognition" : "音声認識",
	"VrHelp_Applications" : "Applications",
	"VrHelp_Communication" : "Communication",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_Favorites" : "お気に入り",
	"VrHelp_Navigation" : "Navigation",
	"VrHelp_Settings" : "設定",
	"WarnGuidanceApp" : "ウォーニング",
	"WarningTitle" : "安全のために",
	"XMAudio" : "SXM",
	"XMData" : "SXM Services",
	"agree" : "OK",
	"VRD_aharadioSelectCall" : "電話をかける",
	"VRD_aharadioSelectDiscard" : "削除",
	"VRD_aharadioSelectEpisodes" : "エピソードリスト",
	"VRD_aharadioSelectLBSTab" : "周辺情報",
	"VRD_aharadioSelectMainList" : "Aha のメインリスト",
	"VRD_aharadioSelectMap" : "地図",
	"VRD_aharadioSelectPresetsTab" : "事前設定",
	"VRD_aharadioSelectSave" : "保存",
	"VRD_aharadioSelectSettings" : "サウンド設定",
	"VRD_aharadioSelectShout" : "シャウト",
	"VRD_aharadioSelectSource" : "エンターテインメント／ソース変更",
	"VRD_aharadioSelectThumbsDown" : "不賛成",
	"VRD_aharadioSelectThumbsUp" : "賛成",
	"VRD_amradioPlayStationFrequency" : "{frequency}のAMに合わせてください",
	"VRD_amradioSelectAutoMemory" : "放送局 ",
	"VRD_amradioSelectFavorites" : "お気に入り",
	"VRD_amradioSelectHD" : "HDステーション",
	"VRD_amradioSelectHDOff" : "HD Radio オフ ",
	"VRD_amradioSelectHDOn" : "HD Radio オン",
	"VRD_amradioSelectScanOff" : "スキャンをオフ",
	"VRD_amradioSelectScanOn" : "スキャンをオン",
	"VRD_amradioSelectSeekNext" : "シークアップ",
	"VRD_amradioSelectSeekPrevious" : "シークダウン",
	"VRD_amradioSelectSettings" : "サウンド設定",
	"VRD_amradioSelectSource" : "エンターテインメントメニューを開く",
	"VRD_amradioSelectStationFrequency" : "{AMFrequency}",
	"VRD_amradioSelectTrafficAlert" : "トラフィックの警告",
	"VRD_amradioSelectTrafficAlertOff" : "トラフィックの警告　オフ",
	"VRD_amradioSelectTrafficAlertOn" : "トラフィックの警告　オン",
	"VRD_amradioSelectTune" : "チューニング",
	"VRD_amradioSelectUpdateAutoMemory" : "自動メモリーのシーク",
	"VRD_amradioSelectiTunesTagging" : "iTunes Tagging",
	"VRD_amradioTuneDown" : "周波数を下げる",
	"VRD_amradioTuneUp" : "周波数を上げる",
	"VRD_amradioUpdateAutoMemory" : "リストを更新",
	"VRD_auxinSelectSettings" : "サウンド設定",
	"VRD_auxinSelectSource" : "エンターテインメント／ソース変更",
	"VRD_btaudioScanPlay" : "スキャン 再生",
	"VRD_btaudioSelectConnect" : "接続",
	"VRD_btaudioSelectRootMenu" : "ルートメニュー",
	"VRD_btaudioSelectSettings" : "サウンド設定",
	"VRD_btaudioSelectSource" : "エンターテインメントメニューを開く",
	"VRD_btaudioToggleRepeat" : "リピート",
	"VRD_btaudioToggleShuffle" : "シャッフル",
	"VRD_carplaySelectApplications" : "Applications",
	"VRD_cdGoSettings" : "サウンド設定",
	"VRD_cdHandleStartScan" : "スキャンを開始",
	"VRD_cdPlayBeginning" : "やり直し",
	"VRD_cdRepeatFolder" : "フォルダ ーを リピート",
	"VRD_cdRepeatOff" : "リピートをオフ",
	"VRD_cdRepeatOn" : "リピートをオン",
	"VRD_cdRepeatTrack" : "トラックをリピート",
	"VRD_cdSelectCurrentFolder" : "現在のフォルダー",
	"VRD_cdSelectRepeat" : "リピート",
	"VRD_cdSelectRootFolder" : "ルートメニュー",
	"VRD_cdSelectShuffle" : "シャッフル",
	"VRD_cdSelectSource" : "エンターテインメントメニューを開く",
	"VRD_cdSelectTrackList" : "トラックリスト",
	"VRD_cdSelectTrackNumber" : "トラック{Number}を再生",
	"VRD_cdShuffleDisk" : "ディスク を シャッフル",
	"VRD_cdShuffleFolder" : "フォルダー を シャッフル",
	"VRD_cdShuffleOff" : "シャッフルをオフ",
	"VRD_cdShuffleOn" : "シャッフルをオン",
	"VRD_commonAddToFavorites" : "お気に入りに追加",
	"VRD_commonCancel" : "キャンセル",
	"VRD_commonFastForward" : "早送り",
	"VRD_commonGoBack" : "戻る",
	"VRD_commonIntentParent" : "ペアレント",
	"VRD_commonIntentParentUSBAudio" : "ペアレント",
	"VRD_commonIntentUSBAudio" : "自宅",
	"VRD_commonIntentUSBAudioBG" : "自宅",
	"VRD_commonMenuUp" : "メニュー　アップ",
	"VRD_commonNext" : "次へ",
	"VRD_commonNo" : "いいえ",
	"VRD_commonPageDown" : "ページダウン／スクロールダウン",
	"VRD_commonPageUp" : "ページアップ／スクロールアップ",
	"VRD_commonPause" : "一時停止",
	"VRD_commonPrevious" : "前へ",
	"VRD_commonResume" : "再生／再開",
	"VRD_commonRewind" : "巻き戻し",
	"VRD_commonSelectLineNumber" : "ライン {lineNumber}",
	"VRD_commonYes" : "はい／OK",
	"VRD_contactsChooseContactName" : "{ContactName}",
	"VRD_contactsDisambiguateContactName" : " {ContactName}を表示",
	"VRD_contactsImportAll" : "すべての連絡先を同期",
	"VRD_contactsImportCancel" : "同期中止",
	"VRD_contactsImportContacts" : "連絡先を編集",
	"VRD_contactsImportSingle" : "選択した連絡先を同期",
	"VRD_contactsRemoveContact" : "連絡先を削除",
	"VRD_contactsSelectCall" : "電話をかける",
	"VRD_contactsSelectContactName" : "{ContactName}",
	"VRD_contactsSelectDownload" : "同期開始",
	"VRD_contactsSelectFavorites" : "お気に入り",
	"VRD_contactsSelectNone" : "ガイトウ なし",
	"VRD_contactsSelectReadContactName" : "名前の発音を確認",
	"VRD_contactsSelectRemove" : "削除",
	"VRD_contactsSelectRetry" : "リトライ",
	"VRD_contactsSendPhoneType" : "{phoneType}",
	"VRD_contactsShowAddress" : "住所",
	"VRD_dabDisplayDABSettings" : "DAB 設定",
	"VRD_dabDisplayEnsembleList" : "アンサンブルを選択",
	"VRD_dabDisplayStationList" : "放送局",
	"VRD_dabSelectFavorites" : "お気に入り",
	"VRD_dabSelectScan" : "スキャン",
	"VRD_dabSelectSeekNext" : "次へ",
	"VRD_dabSelectSeekPrevious" : "前へ",
	"VRD_dabSelectSettings" : "サウンド設定",
	"VRD_dabSelectSource" : "エンターテインメント",
	"VRD_dabTAToggleOFF" : "トラフィックオフ",
	"VRD_dabTAToggleON" : "トラフィックオン",
	"VRD_dabTAToggleVois" : "交通情報",
	"VRD_dabUpdateStationList" : "リストを更新",
	"VRD_dvdClearPin" : "番号を削除",
	"VRD_dvdSayGRating" : "G",
	"VRD_dvdSayPG12" : "PG-12",
	"VRD_dvdSayR15" : "R15+",
	"VRD_dvdSayR18" : "なし",
	"VRD_dvdSelectAspectRatio" : "アスペクト比",
	"VRD_dvdSelectAudioSettings" : "ビデオ設定",
	"VRD_dvdSelectCameraAngle" : "カメラアングル",
	"VRD_dvdSelectEditPin" : "PINコードを編集",
	"VRD_dvdSelectParentLock" : "ペアレンタルロック",
	"VRD_dvdSelectParentLockOff" : "ペアレンタル ロック オフ",
	"VRD_dvdSelectParentLockOn" : "ペアレンタル ロック オン",
	"VRD_dvdSelectParentLockRating" : "ペアレンタルロックの等級",
	"VRD_dvdSelectResetPin" : "PINコードをリセット",
	"VRD_dvdSelectRootMenu" : "ルートメニュー",
	"VRD_dvdSelectSettings" : "サウンド設定",
	"VRD_dvdSelectSource" : "エンターテインメント",
	"VRD_dvdSelectSubtitleOff" : "字幕オフ",
	"VRD_dvdSelectSubtitleOn" : "字幕オン",
	"VRD_dvdSlowForward" : "早送り",
	"VRD_dvdSlowRewind" : "巻き戻し",
	"VRD_dvdVUISendPin" : "{FourDigitPin}",
	"VRD_emailSelectAllAccounts" : "全てのアカウント",
	"VRD_emailSelectCall" : "電話をかける",
	"VRD_emailSelectContactName" : "{ContactName}",
	"VRD_emailSelectContinueEmail" : "下書き",
	"VRD_emailSelectDelete" : "削除",
	"VRD_emailSelectDiscard" : "破棄",
	"VRD_emailSelectImportEmail" : "受信トレイを更新",
	"VRD_emailSelectInbox" : "電子メール受信トレイ",
	"VRD_emailSelectInboxSelector" : "受信トレイ",
	"VRD_emailSelectMessage" : "メッセージを追加",
	"VRD_emailSelectNone" : "該当なし",
	"VRD_emailSelectReply" : "返信",
	"VRD_emailSelectReplyAll" : "全員に返信",
	"VRD_emailSelectRetry" : "リトライ",
	"VRD_emailSelectReturn" : "戻る",
	"VRD_emailSelectSend" : "送信",
	"VRD_emailSelectSenderName" : "{senderName}",
	"VRD_emnaviAcceptAvoidance" : "確認",
	"VRD_emnaviAddCurrentPosToFavourites" : "現在の位置をお気に入りに追加",
	"VRD_emnaviAddWaypointCityCenter" : "ウェイポイントにシティセンターを追加",
	"VRD_emnaviAddWaypointDistrictCenter" : "経由地にディストリクトセンターを追加",
	"VRD_emnaviAddWaypointFavorite" : "ウェイポイントにお気に入りを追加",
	"VRD_emnaviAddWaypointPOI" : "ウェイポイントに{poiHypList}を追加",
	"VRD_emnaviAvoidRouteAhead" : "前方のルートを回避",
	"VRD_emnaviCancelRoute" : "ルートをキャンセル",
	"VRD_emnaviDecreaseAvoidanceLength" : "より短く",
	"VRD_emnaviGoToCockpit" : "スタート",
	"VRD_emnaviIncreaseAvoidanceLength" : "より詳しく",
	"VRD_emnaviJPJ_VDEHypothesisList" : "市の名称",
	"VRD_emnaviNavigateHere" : "ここでナビゲート",
	"VRD_emnaviNavigateHome" : "ホームへナビゲート",
	"VRD_emnaviNavigateToARecentDestination" : "最近の目的地へナビゲート",
	"VRD_emnaviNavigateToAddress" : "住所までナビゲート",
	"VRD_emnaviNavigateToCityCenter" : "シティセンターまでナビゲート",
	"VRD_emnaviNavigateToDistrictCenter" : "ディストリクトセンターまでナビゲート",
	"VRD_emnaviNavigateToFavorite" : "お気に入りへナビゲート",
	"VRD_emnaviNavigateToPOI" : "{poiHypList}までナビゲート",
	"VRD_emnaviNewDestination" : "新しい目的地",
	"VRD_emnaviRepeatInstruction" : "道順をリピート",
	"VRD_emnaviRouteSummary" : "ルート情報",
	"VRD_emnaviSelectCancelRoute" : "ルートの削除",
	"VRD_emnaviSelectNavigateToAddress" : "住所までナビゲート",
	"VRD_emnaviSimpleHypothesisList" : "州の名称",
	"VRD_emnaviStepByStep" : "ステップ毎のエントリー",
	"VRD_emnaviTravelViaARecentDestination" : "ウェイポイントに最近の目的地を追加",
	"VRD_emnaviTravelViaAddress" : "住所を使って旅行",
	"VRD_emnaviTravelViaHome" : "自宅を使って旅行",
	"VRD_emnaviTryAgain" : "やり直し",
	"VRD_emnaviUniSimpleHypothesisList" : "住所",
	"VRD_emnaviUniVDEHypothesisList" : "住所",
	"VRD_emnaviVDEHypothesisList" : "住所",
	"VRD_emnaviWhereAmI" : "現在地",
	"VRD_emnaviZoomIn" : "ズームイン",
	"VRD_emnaviZoomOut" : "ズームアウト",
	"VRD_fmradioPlayStationFrequency" : "{frequency}のFMに合わせてください",
	"VRD_fmradioSelectAutoMemory" : "放送局 ",
	"VRD_fmradioSelectChangeGenre" : "ジャンルを変更",
	"VRD_fmradioSelectFMSettings" : "FM設定",
	"VRD_fmradioSelectFavorites" : "お気に入り",
	"VRD_fmradioSelectGenreSeek" : "ジャンルシーク",
	"VRD_fmradioSelectHDChannel" : "{HD Channel}",
	"VRD_fmradioSelectHDChannels" : "HDステーション",
	"VRD_fmradioSelectHDRadio" : "HD Radio",
	"VRD_fmradioSelectHDRadioOff" : "HD Radio オフ ",
	"VRD_fmradioSelectHDRadioOn" : "HD Radio オン",
	"VRD_fmradioSelectScanOff" : "スキャンをオフ",
	"VRD_fmradioSelectScanOn" : "スキャンをオン",
	"VRD_fmradioSelectSeekNext" : "シークアップ",
	"VRD_fmradioSelectSeekPrevious" : "シークダウン",
	"VRD_fmradioSelectSettings" : "サウンド設定",
	"VRD_fmradioSelectSource" : "エンターテインメント／ソース変更",
	"VRD_fmradioSelectStationAll" : "すべての放送局",
	"VRD_fmradioSelectStationFrequency" : "{frequency}",
	"VRD_fmradioSelectStationGenre" : "{genreName}",
	"VRD_fmradioSelectStationList" : "放送局",
	"VRD_fmradioSelectStationName" : "{stationName}",
	"VRD_fmradioSelectTrafficAlert" : "交通情報",
	"VRD_fmradioSelectTrafficAlertOff" : "トラフィックオフ",
	"VRD_fmradioSelectTrafficAlertOn" : "トラフィックオン",
	"VRD_fmradioSelectTune" : "チューニング",
	"VRD_fmradioSelectUpdateAutoMemory" : "自動メモリーを更新",
	"VRD_fmradioSelectiTunesTagging" : "iTunes Tagging",
	"VRD_fmradioTuneDown" : "周波数を下げる",
	"VRD_fmradioTuneUp" : "周波数を上げる",
	"VRD_fmradioTurnOffAF" : "代替周波数オフ",
	"VRD_fmradioTurnOffREG" : "リージョンロックオフ",
	"VRD_fmradioTurnOnAF" : "代替周波数オン",
	"VRD_fmradioTurnOnREG" : "リージョンロックオン",
	"VRD_fmradioUpdateAutoMemory" : "リストを更新",
	"VRD_pandoraAddStation" : "放送局を追加",
	"VRD_pandoraAddStationFromArtist" : "アーチストから放送局を作成",
	"VRD_pandoraAddStationFromSong" : "歌から放送局を作成",
	"VRD_pandoraAddToFavorites" : "お気に入りに追加",
	"VRD_pandoraBookmarkArtist" : "アーティストをブックマーク",
	"VRD_pandoraBookmarkSong" : "曲をブックマーク",
	"VRD_pandoraCreateStation" : "放送局を新規作成",
	"VRD_pandoraSelectAddCurrentStation" : "追加",
	"VRD_pandoraSelectDelete" : "削除",
	"VRD_pandoraSelectEditDelete" : "削除",
	"VRD_pandoraSelectEditMove" : "移動",
	"VRD_pandoraSelectEditReplace" : "置き換え",
	"VRD_pandoraSelectFavorites" : "お気に入り",
	"VRD_pandoraSelectMove" : "移動",
	"VRD_pandoraSelectQuickMix" : "シャッフル",
	"VRD_pandoraSelectSettings" : "サウンド設定",
	"VRD_pandoraSelectSortBy" : "並べ替え",
	"VRD_pandoraSelectSource" : "エンターテインメント",
	"VRD_pandoraSelectStationList" : "放送局",
	"VRD_pandoraShowBookmarkOptions" : "ブックマーク",
	"VRD_pandoraShowByAZ" : "アルファベット順に並べ替え",
	"VRD_pandoraShowByDate" : "日付で並べ替え",
	"VRD_pandoraSkip" : "スキップ",
	"VRD_pandoraThumbsDown" : "逆いいね",
	"VRD_pandoraThumbsUp" : "いいね",
	"VRD_phoneCall" : "電話をかける",
	"VRD_phoneCallBack" : "折り返し電話をかける",
	"VRD_phoneCallByName" : "名前で電話をかける",
	"VRD_phoneCallByNumber" : "番号で電話をかける",
	"VRD_phoneCallContactType" : "{contactName}（{contactType}）に電話をかける",
	"VRD_phoneCallLast" : "最後にかけた番号に電話をかける",
	"VRD_phoneChooseContactType" : "{contactName} （{contactType}）",
	"VRD_phoneDialAnyNumber" : "{number}に電話をかける",
	"VRD_phoneDialpadClearAllDigits" : "番号のすべての数字を消去",
	"VRD_phoneDialpadDeleteDigit" : "削除",
	"VRD_phoneDialpadPhoneNumber" : "{phoneNumber}",
	"VRD_phoneReDial" : "リダイヤル",
	"VRD_phoneSelectByName" : "名前",
	"VRD_phoneSelectByNumber" : "番号",
	"VRD_phoneSelectContactType" : "{contactType}",
	"VRD_phoneSelectDialPad" : "ダイアルパッド",
	"VRD_phoneSelectFavorites" : "お気に入り",
	"VRD_phoneSelectRecentCalls" : "最近の通話履歴",
	"VRD_phoneSelectRecentCallsAll" : "すべての通話",
	"VRD_phoneSelectRecentCallsMissed" : "不在着信",
	"VRD_satradioBackSpaceDelete" : "番号を削除",
	"VRD_satradioChangeLockCode" : "PINコードを変更",
	"VRD_satradioEnterPIN" : "{4digitPin}",
	"VRD_satradioInitializeLockCode" : "初期化PINコード",
	"VRD_satradioPlayChannelName" : "{channelName}を再生",
	"VRD_satradioPlayStationNumber" : "{channelNumber}に合わせてください",
	"VRD_satradioResetLockCode" : "PINコードをリセット",
	"VRD_satradioSeekNext" : "シークアップ",
	"VRD_satradioSeekPrevious" : "シークダウン",
	"VRD_satradioSelectChangeCategory" : "カテゴリー",
	"VRD_satradioSelectFavorites" : "お気に入り",
	"VRD_satradioSelectParentalLock" : "保護者による制限ロック",
	"VRD_satradioSelectScanOff" : "スキャンをオフ",
	"VRD_satradioSelectScanOn" : "スキャンをオン",
	"VRD_satradioSelectSettings" : "サウンド設定",
	"VRD_satradioSelectSource" : "エンターテインメント",
	"VRD_satradioSelectStation" : "放送局{Station number}",
	"VRD_satradioSelectStationAll" : "すべてのチャンネル",
	"VRD_satradioSelectStationCategory" : "{categoryName}",
	"VRD_satradioSelectStationList" : "チャネルリスト",
	"VRD_satradioTurnChannelLockOFF" : "現在のチャンネルのロックを解除",
	"VRD_satradioTurnChannelLockON" : "現在のチャンネルをロック",
	"VRD_satradioTurnParentalLockOFF" : "セッションロックをオフ",
	"VRD_satradioTurnParentalLockON" : "セッションロックをオン",
	"VRD_smsCallPhoneNumber" : "電話をかける",
	"VRD_smsDelete" : "削除",
	"VRD_smsImportMessages" : "テキスト受信トレイを更新",
	"VRD_smsReply" : "返信",
	"VRD_smsSayAnyConversation" : "{senderName}",
	"VRD_smsSelectBody" : "メッセージを追加",
	"VRD_smsSelectContactName" : "{ContactName}",
	"VRD_smsSelectContinueTextMessage" : "メッセージを続ける",
	"VRD_smsSelectDiscard" : "削除",
	"VRD_smsSelectInbox" : "SMS 受信トレイのリスト",
	"VRD_smsSelectNone" : "該当なし",
	"VRD_smsSelectRetry" : "リトライ",
	"VRD_smsSelectReturn" : "戻る",
	"VRD_smsSelectSend" : "送信",
	"VRD_stitcherAddToFavorites" : "お気に入りに追加",
	"VRD_stitcherRemoveFromFavorites" : "お気に入りから削除",
	"VRD_stitcherSaveFavorites" : "変更を保存",
	"VRD_stitcherSelectSettings" : "サウンド設定",
	"VRD_stitcherSelectSource" : "エンターテインメント",
	"VRD_stitcherSelectStationList" : "ステーションのリスト",
	"VRD_stitcherThumbsDown" : "不賛成",
	"VRD_stitcherThumbsUp" : "賛成",
	"VRD_systemSelectAhaRadio" : "Aha ラジオ",
	"VRD_systemSelectAndroidAuto" : "Android Auto",
	"VRD_systemSelectApplications" : "Applications",
	"VRD_systemSelectAuxIn" : "ラインイン／AUX",
	"VRD_systemSelectBTAudio" : "Bluetooth",
	"VRD_systemSelectCD" : "CD",
	"VRD_systemSelectCallHistory" : "通話履歴",
	"VRD_systemSelectCarPlay" : "Apple CarPlay",
	"VRD_systemSelectCommunication" : "Communication",
	"VRD_systemSelectConnect" : "接続",
	"VRD_systemSelectContacts" : "連絡先",
	"VRD_systemSelectDAB" : "DAB ",
	"VRD_systemSelectDVD" : "DVD",
	"VRD_systemSelectDisplayClock" : "時刻表示",
	"VRD_systemSelectDisplayOff" : "ディスプレイオフ",
	"VRD_systemSelectEmail" : "メール",
	"VRD_systemSelectEntertainment" : "エンターテインメント",
	"VRD_systemSelectEntertainmentMenu" : "エンターテイメント メニュー",
	"VRD_systemSelectFavorites" : "お気に入り",
	"VRD_systemSelectNavigation" : "Navigation",
	"VRD_systemSelectNotifications" : "メッセージ",
	"VRD_systemSelectNotifyOff" : "通知しない",
	"VRD_systemSelectPandora" : "Pandora",
	"VRD_systemSelectPhone" : "携帯",
	"VRD_systemSelectRadioAM" : "AM",
	"VRD_systemSelectRadioFM" : "FM",
	"VRD_systemSelectRetry" : "リトライ",
	"VRD_systemSelectSatRadio" : "衛星ラジオ",
	"VRD_systemSelectSettings" : "設定",
	"VRD_systemSelectSiri" : "Siri",
	"VRD_systemSelectSms" : "テキスト／SMS",
	"VRD_systemSelectStitcher" : "Stitcher",
	"VRD_systemSelectTV" : "TV",
	"VRD_systemSelectTrafficAlert" : "交通情報",
	"VRD_systemSelectTutorial" : "チュートリアル",
	"VRD_systemSelectUSB" : "USB",
	"VRD_systemSelectUSBA" : "USB 1",
	"VRD_systemSelectUSBB" : "USB 2",
	"VRD_systemSelectXmAudio" : "SXM ラジオ",
	"VRD_tvSelectView" : "視聴",
	"VRD_usbaudioBrowse" : "ブラウズ",
	"VRD_usbaudioBrowseAlbum" : "{albumName}を表示",
	"VRD_usbaudioBrowseAlbums" : "アルバムを表示",
	"VRD_usbaudioBrowseAll" : "すべての曲、アルバム、または、アーチストを表示",
	"VRD_usbaudioBrowseAnyAlbum" : "[アルバム] {albumName}を表示",
	"VRD_usbaudioBrowseAnyArtist" : "[Artist] {artistName}を表示",
	"VRD_usbaudioBrowseAnyFolder" : "{folderName}のフォルダーを表示",
	"VRD_usbaudioBrowseArtist" : "{artistName}を表示",
	"VRD_usbaudioBrowseArtists" : "アーティストを表示",
	"VRD_usbaudioBrowseAudiobooks" : "オーディオ ブック を 表示",
	"VRD_usbaudioBrowseFolder" : "{folderName}を表示",
	"VRD_usbaudioBrowseFolders" : "フォルダーを表示",
	"VRD_usbaudioBrowseGenre" : " [ジャンル] {genreName}を表示",
	"VRD_usbaudioBrowseGenres" : "ジャンルを表示",
	"VRD_usbaudioBrowseLineNumber" : "ライン {lineNumber}を表示",
	"VRD_usbaudioBrowsePlaylist" : "{playlistName}のプレイリストを表示",
	"VRD_usbaudioBrowsePlaylists" : "プレイリストを表示",
	"VRD_usbaudioBrowsePodcast" : "{podcastName}のポッドキャストを表示",
	"VRD_usbaudioBrowsePodcasts" : "ポッドキャストを表示",
	"VRD_usbaudioBrowseSongs" : "曲を表示",
	"VRD_usbaudioChooseAlbumArtist" : "{artistName}",
	"VRD_usbaudioGenerateMoreLikeThis" : "More Like This",
	"VRD_usbaudioPlayAlbums" : "アルバムを再生",
	"VRD_usbaudioPlayAll" : "すべて再生",
	"VRD_usbaudioPlayAnyAlbum" : "[アルバム] {albumName}を再生",
	"VRD_usbaudioPlayAnyArtist" : " [アーチスト] {artistName}を再生",
	"VRD_usbaudioPlayAnyFolder" : "{folderName}のフォルダー を再生",
	"VRD_usbaudioPlayArtistAlbum" : "{artistName} の{albumName}を再生",
	"VRD_usbaudioPlayArtists" : "アーチストを再生",
	"VRD_usbaudioPlayAudiobook" : "{AudiobookName}のオーディオブックを再生",
	"VRD_usbaudioPlayAudiobooks" : "オーディオブック を再生",
	"VRD_usbaudioPlayChapter" : "{chapterName}",
	"VRD_usbaudioPlayChapterIndex" : " {index} {chapter}のチャプターを再生",
	"VRD_usbaudioPlayEpisode" : "{episodeName}",
	"VRD_usbaudioPlayFolder" : "{folderName}を再生",
	"VRD_usbaudioPlayFolders" : "フォルダーを再生",
	"VRD_usbaudioPlayGenre" : "[ジャンル] {genreName}を再生",
	"VRD_usbaudioPlayGenres" : "ジャンルを再生",
	"VRD_usbaudioPlayLineNumber" : "[ライン] {lineNumber}を再生",
	"VRD_usbaudioPlayPlaylist" : "{playlistName}のプレイリストを再生",
	"VRD_usbaudioPlayPlaylists" : "プレイリストを再生",
	"VRD_usbaudioPlayPodcast" : "{PodcastName}のポッドキャストをブラウズ",
	"VRD_usbaudioPlayPodcasts" : "ポッドキャスト を再生",
	"VRD_usbaudioPlaySongs" : "曲を再生",
	"VRD_usbaudioRepeat" : "リピート",
	"VRD_usbaudioRepeatAll" : "全体リピート",
	"VRD_usbaudioRepeatOff" : "リピートをオフ",
	"VRD_usbaudioRepeatSong" : "曲リピート",
	"VRD_usbaudioRewind" : "巻き戻し",
	"VRD_usbaudioSelectAlbum" : "{albumName}のアルバム",
	"VRD_usbaudioSelectAlbums" : "アルバム",
	"VRD_usbaudioSelectAll" : "すべてのエピソード、チャプター、歌、アルバム、または、アーチスト",
	"VRD_usbaudioSelectArtist" : " {artistName}のアーチスト",
	"VRD_usbaudioSelectArtists" : "アーチスト",
	"VRD_usbaudioSelectAudiobook" : "{audiobookName}",
	"VRD_usbaudioSelectAudiobooks" : "オーディオブック",
	"VRD_usbaudioSelectFolder" : "{folderName}のフォルダー",
	"VRD_usbaudioSelectFolders" : "フォルダー",
	"VRD_usbaudioSelectGenre" : "{genreName}のジャンル",
	"VRD_usbaudioSelectGenres" : "ジャンル",
	"VRD_usbaudioSelectPlaylist" : "{playlistName}のプレイリスト",
	"VRD_usbaudioSelectPlaylists" : "プレイリスト",
	"VRD_usbaudioSelectPodcast" : "{podcastName}",
	"VRD_usbaudioSelectPodcasts" : "ポッドキャスト",
	"VRD_usbaudioSelectRootFolder" : "ルートメニュー",
	"VRD_usbaudioSelectSettings" : "サウンド設定",
	"VRD_usbaudioSelectSongs" : "曲",
	"VRD_usbaudioSelectSourceMenu" : "エンターテインメント",
	"VRD_usbaudioShuffle" : "シャッフル",
	"VRD_usbaudioShuffleOff" : "シャッフルをオフ",
	"VRD_usbaudioShuffleOn" : "シャッフルをオン",
	"VRD_usbaudioSongList" : "現在のフォルダ",
	"VRD_xmaudioBackSpaceDelete" : "番号を削除",
	"VRD_xmaudioChangeLockCode" : "PINコードを編集",
	"VRD_xmaudioConfirmDelete" : "削除",
	"VRD_xmaudioEnterPIN" : "{fourDigitPIN}",
	"VRD_xmaudioPlayChannelName" : "XM チャンネル {channelName}を再生",
	"VRD_xmaudioPlayStationNumber" : "{channelNumber}に合わせてください",
	"VRD_xmaudioResetLockCode" : "PINコードをリセット",
	"VRD_xmaudioSelectCallXM" : "XM に電話をかける",
	"VRD_xmaudioSelectChangeCategory" : "カテゴリーを変更",
	"VRD_xmaudioSelectContinueListening" : "視聴を続ける",
	"VRD_xmaudioSelectDismiss" : "棄却",
	"VRD_xmaudioSelectEveryOccurance" : "各事例",
	"VRD_xmaudioSelectEveryOtherReport" : "他のすべてのレポート",
	"VRD_xmaudioSelectEveryReport" : "すべてのレポート",
	"VRD_xmaudioSelectExitTuneMix" : "TuneMix を閉じる",
	"VRD_xmaudioSelectFavorites" : "お気に入り",
	"VRD_xmaudioSelectListenNow" : "さあ聴きましょう",
	"VRD_xmaudioSelectMove" : "移動",
	"VRD_xmaudioSelectNearestCity" : "最も近い市",
	"VRD_xmaudioSelectOnlyFirstAfterVehicleStart" : "車のスタート",
	"VRD_xmaudioSelectOnlyFirstOccuranceInGame" : "最初の事例",
	"VRD_xmaudioSelectReplayAlert" : "リプレイの警告",
	"VRD_xmaudioSelectReturnToPrevious" : "前に戻る",
	"VRD_xmaudioSelectSFSportBaseball" : "野球",
	"VRD_xmaudioSelectSFSportNCAA" : "大学のフットボール",
	"VRD_xmaudioSelectSFSportNFL" : "プロのフットボール",
	"VRD_xmaudioSelectSFSportNHL" : "ホッケー",
	"VRD_xmaudioSelectScanOff" : "スキャンをオフ",
	"VRD_xmaudioSelectScanOn" : "スキャンをオン",
	"VRD_xmaudioSelectSettings" : "設定",
	"VRD_xmaudioSelectSoundSettings" : "サウンド設定",
	"VRD_xmaudioSelectSource" : "エンターテインメント",
	"VRD_xmaudioSelectStation" : "ステーション{channelNumber}",
	"VRD_xmaudioSelectStationAll" : "すべてのチャンネル",
	"VRD_xmaudioSelectStationCategory" : "{categoryName}",
	"VRD_xmaudioSelectStationFeaturedFavorites" : "注目のお気に入り",
	"VRD_xmaudioSelectStationList" : "チャンネル",
	"VRD_xmaudioSelectTuneMix" : "TuneMix",
	"VRD_xmaudioSelectTuneMixChannel" : "TuneMix チャンネルのオプション",
	"VRD_xmaudioSelectTuneMixChannelsOptions" : "チャネルのオプション",
	"VRD_xmaudioSelectTuneMixCreation" : "新しい TuneMix チャンネルを作成",
	"VRD_xmaudioSelectTuneMixEdit" : "TuneMix チャンネルを編集",
	"VRD_xmaudioSelectTuneMixEditOps" : "TuneMix チャンネルの編集オプション",
	"VRD_xmaudioSelectTuneMixRemove" : "TuneMix チャンネルを削除",
	"VRD_xmaudioSelectTuneMixRename" : "TuneMix の名前を変更",
	"VRD_xmaudioSelectTurnAlertsOff" : "警告をオフにする",
	"VRD_xmaudioSelectiTunesTagging" : "iTunes のタグ付け",
	"VRD_xmaudioSetChannelLock" : "チャンネルをロック",
	"VRD_xmaudioSetParentalLock" : "セッションロック",
	"VRD_xmdataSelectFuelPrices" : "燃料の価格",
	"VRD_xmdataSelectMovies" : "ムービー",
	"VRD_xmdataSelectParking" : "パーキング",
	"VRD_xmdataSelectSports" : "スポーツ",
	"VRD_xmdataSelectStock" : "株価",
	"VRD_xmdataSelectTrafficPlus" : "トラフィック　プラス",
	"VRD_xmdataSelectWeatherForecast" : "天気予報",
	"VRD_xmdataSelectWeatherRadar" : "気象レーダー",
	"VRD_xmdataSelectWeatherSecurityAlerts" : "天候セキュリティ警告",
};

framework.registerAppDictLoaded("system", "ja_JP");