var Localization_vehsettingsAppDict_fr_FR = {
	//"stringId" : "localString"
	"360ViewCamera" : "Assistant d'affichage 360°",
	"AHBC" : "Adaptive LED Headlights",
	"Adaptive" : "Adaptatif",
	"AdaptiveFront-lightingSystem" : "Système d'éclairage avant adaptatif",
	"AdaptiveLaneStreetTurn" : "Voie/Rue/Virage adaptatif(ve)",
	"AlarmTiming" : "Vitesse",
	"AlertTiming" : "Moment de l'alerte",
	"Always" : "Toujours",
	"AtLine" : "ligne",
	"Auto" : "Auto",
	"AutoHeadlightOn" : "Mise en marche auto des phares",
	"AutoWiper" : "Essuie-glace à détecteur de pluie",
	"BSMBuzzerVolume" : "Blind Spot Monitoring Volume",
	"BSMReset" : "Êtes-vous sûr de vouloir rétablir les paramètres du BSM par défaut ?",
	"BSMResetError" : "Erreur de rétablissement des paramètres du BSM par défaut. Souhaitez-vous réessayer ?",
	"BSMResetProgress" : "Rétablis. des param du BSM par défaut",
	"BSMSystem" : "Système Blind Spot Monitoring ",
	"Beep" : "Bip",
	"BeepVolume" : "Volume du bip sonore",
	"Beep_Line" : "Bip",
	"BeforeLine" : "Avant",
	"Brightness" : "Luminosité",
	"BrightnessControl" : "Réglage de la luminosité",
	"CHudNav_Maneuver" : "Manœuvre",
	"CHudNav_Off" : "Arrêt",
	"CHudNav_TBT_Lane" : "Ind voie+vir.",
	"CHudNav_TBT_Street" : "Rue+vir",
	"Calibration" : "Luminosité",
	"CautionSpeed" : "Vitesse d'alerte",
	"CenterDisplay" : "Affichage central",
	"ChangingLASSettings" : "Mod. des par. Lane-keep Assist System",
	"Clock" : "Horloge",
	"Close" : "Ferm",
	"ComingHomeLights" : "Coming Home Light",
	"ComingHomeLightsTimer" : "Coming Home Light",
	"DRSS" : "Distance Recognition Support System",
	"DRSSReset" : "Êtes-vous sûr de vouloir rétablir les paramètres de Distance Recognition Support System (DRSS) par défaut ?",
	"DRSSResetError" : "Erreur de modification de Distance Recognition Support System (DRSS). Souhaitez-vous réessayer ?",
	"DRSSResetProgress" : "En cours de modification des paramètres DRSS",
	"Dark" : "Sombre",
	"DaytimeRunningLights" : "Feux de conduite de jour",
	"Devices" : "Dispositif",
	"Display" : "Afficha.",
	"DisplayInformation" : "Informations d'affichage",
	"DistanceRecognitionSupportSystem" : "Distance Recognition Support System",
	"DoorLock" : "Verrouillage des portes",
	"DoorLockMode" : "Mode verrouillage auto des portes",
	"DoorLockReset" : "Êtes-vous sûr de vouloir rétablir les paramètres de verrouillage des portes par défaut ?",
	"DoorLockResetError" : "Erreur de modification des paramètres de verrouillage des portes. Souhaitez-vous réessayer ?",
	"DoorLockResetProgress" : "En cours de modification des paramètres de verrouillage des portes",
	"DoorRelockTime" : "Délai de reverrouillage automatique",
	"DriverAlert" : "Driver Attention Alert",
	"Early" : "Tôt",
	"ErrorBSMSettings" : "Erreur lors la modification des paramètres du BSM. Souhaitez-vous réessayer ?",
	"ErrorLASSettings" : "Erreur lors la modification du Lane-keep Assist System. Souhaitez-vous réessayer ?",
	"FOWReset" : "Êtes-vous sûr de vouloir rétablir les paramètres par défaut du Forward Obstruction Warning (FOW) ?",
	"FOWResetError" : "Erreur de modification des paramètres du Forward Obstruction Warning (FOW). Souhaitez-vous réessayer ?",
	"FOWResetProgress" : "En cours de modification des paramètres FOW",
	"Far" : "Éloigné",
	"ForwardObstructionWarning" : "Forward Obstruction Warning",
	"FrontCameraView" : "Vue de la caméra avant",
	"GearShiftIndicator" : "Indicateur de changement de vitesse",
	"GuidelineDisplay" : "Lignes itinéraire dyn.",
	"HUD" : "AD-Disp",
	"HUDDisplayInfoError" : "Impossible de réinitialiser les paramètres d'affichage des informations d'AD-Disp par défaut. Voulez-vous réessayer ?",
	"HUDDisplayInfoReset" : "Êtes-vous sûr de vouloir réinitialiser les paramètres d'affichage des informations d'AD-Disp par défaut ?",
	"HUDDisplayInfoResetProgress" : "Rétablismnt param affichage des infos d'AD-Disp en cours",
	"HUDJ78AReset" : "Souhaitez-vous vraiment rétablir les valeurs par défaut des paramètres Active Driving Display ?",
	"HUDJ78AResetError" : "Une erreur est survenue lors de la réinitialisation des paramètres Active Driving Display. Souhaitez-vous réessayer ?",
	"HUDJ78AResetProgress" : "Réinitialisation des paramètres Active Driving Display",
	"HUDJ78ATab" : "Active Driving Display",
	"HUDReset" : "Êtes-vous sûr de vouloir rétablir les paramètres de l'Active Driving Display par défaut ?",
	"HUDResetError" : "Erreur de modification des paramètres de l'Active Driving Display. Souhaitez-vous réessayer ?",
	"HUDResetProgress" : "Modif param Active Driving Display",
	"HUDSettings" : "Paramètres AD-Disp",
	"HUD_HeadUpDisplay" : "Active Driving Display",
	"HeadUpDisplay" : "Active Driving Display",
	"HeadlightOffTimer" : "Délai d’extinction des phares",
	"HeadlightOnWarning" : "Bip phares allumés",
	"HeadsUpDisplay" : "Active Driving Display",
	"Height" : "Hauteur",
	"High" : "Fort",
	"HighBeamControl" : "High Beam Control",
	"High_SensitivityLAS" : "Fort",
	"High_Vibration" : "Fort",
	"ILB_Bright" : "Douce",
	"ILB_Dark" : "Sombre",
	"ILB_Medium" : "Moyenne",
	"ILB_Off" : "Arrêt ",
	"IgONAutoDisplay" : "Affichage automatique 360° View Monitor",
	"InterioLightsTimeOutDoorsClosed" : "Délai extinct plafonnier port ferm",
	"InterioLightsTimeOutDoorsOpen" : "Délai extinct plafonnier port ouv",
	"InteriorLightTimeoutDoorClosedTitle" : "Délai extinct plafonnier port ferm",
	"InteriorLightTimeoutDoorOpenTitle" : "Délai extinct plafonnier port ouv",
	"InteriorLightingBrightness" : "Lumière ambiante",
	"Intervention" : "Intervention",
	"InterventionTiming" : "Moment de l'intervention",
	"KeylessLockBeepVol" : "Volume bip verrouillage sans clé",
	"Kilometers" : "km/h",
	"LASAlert" : "Alerte LAS",
	"LASDefaultValues" : "Êtes-vous sûr de vouloir rétablir les paramètres Lane-keep Assist System par défaut ?",
	"LASEarly" : "Tôt",
	"LASLate" : "Retard",
	"LASSound" : "Type d'alerte",
	"LASTiming" : "Délai LAS",
	"LDWSReset" : "Êtes-vous sûr de vouloir rétablir les paramètres par défaut du Lane Departure Warning System (LDWS) ?",
	"LDWSResetError" : "Erreur de modification des paramètres du Lane Departure Warning System (LDWS). Souhaitez-vous réessayer ?",
	"LDWSResetProgress" : "En cours de modification des paramètres du LDWS",
	"LDWSTiming" : "Délai LDWS",
	"LaneDepartureAlert" : "Alerte de changement de file",
	"LaneDepartureWarningSystem" : "Lane Departure Warning System",
	"LaneKeepAssistSystem" : "Lane-keep Assist System",
	"Late" : "Retard",
	"LeavingHomeLights" : "Leaving Home Light",
	"Light" : "Lumineux",
	"LightOnReminderVolume" : "Alarme oubli feux",
	"Lighting" : "Eclairage",
	"LightingReset" : "Êtes-vous sûr de vouloir rétablir les paramètres de l’éclairage par défaut ?",
	"LightingResetError" : "Erreur de modification des paramètres d’éclairage. Souhaitez-vous réessayer ?",
	"LightingResetProgress" : "En cours de modification des paramètres d’éclairage",
	"LockShiftFromP" : "Verrouiller: quittant Parking ",
	"LockShiftFromPUnlockInPark" : "Verrouill: quitt P, Déverrouill: garé",
	"LockUnlock" : "Verrouill: Conduite Déverr: Statiomnt",
	"LockWhenDriving" : "Verrouiller: Lors de la conduite",
	"LockWhenDrivingUnlockIGNoff" : "Verrouill: Conduite Déverr: IGN Off",
	"Long" : "Éloigné",
	"Low" : "Bas",
	"Low_SensitivityLAS" : "Bas",
	"Low_Vibration" : "Bas",
	"Manual" : "Manuel",
	"Med" : "Moyen",
	"Medium" : "Moyen",
	"MediumDark" : "Med noir",
	"MediumLight" : "Med feu",
	"Medium_Int_OFF" : "Moyen",
	"Medium_SensitivityLAS" : "Moyen",
	"Mid" : "Milieu",
	"Middle" : "Milieu",
	"Miles" : "mph",
	"Mode" : "Mode",
	"Navigation" : "Navigation",
	"NavigationSignal" : "Navigation  ",
	"Near" : "Proche",
	"Off" : "Off",
	"Often" : "Fréquent",
	"Often_Int_OFF" : "Fréquent",
	"OnDemand" : "À la dem",
	"OnceAllDoors" : "1 fois : Toutes les portes",
	"OnceDriversDoorTwiceAllDoors" : "1 fois: porte cond, 2: Toutes portes",
	"Open" : "Ouvrir",
	"ParkingSensorIndication" : "Indication du témoin de parking ",
	"ParkingSensorIndicator" : "Indicateur du témoin de parking",
	"RVMBuzzerVolume" : "Rear Vehicle Monitoring Volume",
	"Rare" : "Rare",
	"Rare_Int_OFF" : "Rare",
	"Reset" : "Réinitialiser",
	"Rotation" : "Rotation",
	"RumbleStrips" : "Band",
	"RumbleStrips_line" : "Band ",
	"RumbleVolume" : "Vol bandes rug",
	"SBSReset" : "Êtes-vous sûr de vouloir rétablir paramètres Smart Brake Support (SBS) par défaut ?",
	"SBSResetError" : "Erreur de modification des paramètres du Smart Brake Support (SBS).Souhaitez-vous réessayer ?",
	"SBSResetProgress" : "En cours de modification des paramètres Smart Brake Support (SBS)",
	"SBSSCBS" : "SBS/SCBS",
	"SBS_SCBSReset" : "Êtes-vous sûr de vouloir rétablir les paramètres des SBS/SCBS par défaut ?",
	"SBS_SCBSResetError" : "Erreur de modification des paramètres des SBS/SCBS. Souhaitez-vous réessayer ?",
	"SBS_SCBSResetProgress" : "En cours de modification des paramètres des SBS/SCBS",
	"SCBS" : "Smart City Brake Support",
	"SCBSReset" : "Êtes-vous sûr de vouloir rétablir les paramètres du SCBS par défaut ?",
	"SCBSResetError" : "Erreur de rétablissement des paramètres du SCBS par défaut. Souhaitez-vous réessayer ?",
	"SCBSResetProgress" : "Rétablis. des param du SCBS par défaut",
	"SLC_Buzzer" : "Alarme sonore uniquement",
	"SLC_Off" : "Arrêt ",
	"SLC_Sign" : "Visuel",
	"SLC_Sign_Buzzer" : "Audio-visuel",
	"SLIReset" : "Êtes-vous sûr de vouloir réinitialiser les paramètres d'avertissement de limitation de vitesse par défaut ?",
	"SLIResetError" : "Impossible de réinitialiser les paramètres d'avertissement de limitation de vitesse par défaut. Souhaitez-vous réessayer ?",
	"SLIResetProgress" : "Réinitialisation des paramètres d'avertissement de limitation de vitesse en cours",
	"SLI_HeadUpDisplay" : "Active Driving Display",
	"Safety" : "Sécurité",
	"Safetysettings" : "Param sécurité",
	"Sensitivity" : "Sensibilité",
	"Sensitivity_Intervention_OFF" : "Avertissement ",
	"Setting" : "Paramètres",
	"Settings" : "Paramètres",
	"Short" : "Proche",
	"SideView" : "Latéral",
	"SideViewFrontView" : "Latéral + avant",
	"SmartBrakeSupport" : "Smart Brake Support",
	"Sound" : "Audio",
	"SpeedAlarm" : "Alarme de vitesse",
	"SpeedLimitCaution" : "Alerte de limitation de vitesse",
	"SpeedLimitInformation" : "Avertissement de limitation de vitesse",
	"SpeedLimitSign" : "Affichage de limitation de vitesse",
	"StepKilometers" : "{value} km/h",
	"StepMiles" : "{value} mph",
	"StreetInformation" : "Informations sur la rue",
	"Streetinfo_off" : "Arrêt",
	"System" : "Système",
	"TSRReset" : "Êtes-vous sûr de vouloir réinitialiser les paramètres du système de reconnaissance des panneaux de signalisation par défaut ?",
	"TSRResetError" : "Erreur de réinitialisation des paramètres du système de reconnaissance des panneaux de signalisation par défaut. Souhaitez-vous réessayer ?",
	"TSRResetProgress" : "Réinitialisation des paramètres du système de reconnaissance des panneaux de signalisation en cours.",
	"TSR_Display" : "Affichage des panneaux de signalisation",
	"TSR_System" : "Système de reconnaissance des panneaux de signalisation",
	"Tachometer" : "Compteur de vitesse",
	"ThreeFlashTurnSignal" : "Signal à 3 clignotements",
	"Timing" : "Délai",
	"Turn" : "Clignotants",
	"TurnProgress" : "En cours de modification des paramètres des clignotants",
	"TurnReset" : "Êtes-vous sûr de vouloir rétablir les paramètres des clignotants par défaut ?",
	"TurnResetError" : "Erreur de modification des paramètres des clignotants. Souhaitez-vous réessayer ?",
	"TurnSettings" : "Tourner",
	"TurnSignalIndicatorVolume" : "Volume signal clignotants",
	"UnlockMode" : "Mode de déverrouillage",
	"Vehicle" : "Véhicule",
	"VehicleSettings" : "Paramètres véhicule",
	"Vibration" : "Vibration",
	"VibrationStrength" : "Intensité vibration",
	"Vibration_Line" : "Vibration",
	"ViewSwitchDisplay" : "Affichage par défaut",
	"ViewSwitchFunction" : "Fonction Changement d'affichage",
	"Volume" : "Volume",
	"WalkAwayLock" : "Verrouillage automatique",
	"Warning" : "Avertissement",
	"WarningDistance" : "Dist avertiss.",
	"_0s" : "0 s",
	"_0seconds" : "0 seconde",
	"_10m" : "10 min",
	"_10minutes" : "10 minutes",
	"_120s" : "120 s",
	"_120seconds" : "120 secondes",
	"_15s" : "15 s",
	"_15seconds" : "15 secondes",
	"_30m" : "30 min",
	"_30minutes" : "30 minutes",
	"_30s" : "30 s",
	"_30seconds" : "30 secondes",
	"_60m" : "60 min",
	"_60minutes" : "60 minutes",
	"_60s" : "60 s",
	"_60seconds" : "60 secondes",
	"_7p5s" : "7,5 s",
	"_7p5seconds" : "7,5 secondes",
	"_90s" : "90 s",
	"_90seconds" : "90 secondes",
	"_AllDoors" : "Toutes",
	"_Driver'sDoor" : "Conduc.",
	"on" : "Activé",
};

framework.registerAppDictLoaded("vehsettings", "fr_FR");