var Localization_vehsettingsAppDict_mn_TW = {
	//"stringId" : "localString"
	"360ViewCamera" : "360° 影像攝影機",
	"AHBC" : "Adaptive LED Headlights",
	"Adaptive" : "自動調整",
	"AdaptiveFront-lightingSystem" : "主動轉向照明系統",
	"AdaptiveLaneStreetTurn" : "自適應車道/街道/轉向",
	"AlarmTiming" : "速度設定",
	"AlertTiming" : "警告定時",
	"Always" : "總是",
	"AtLine" : "位於",
	"Auto" : "自動",
	"AutoHeadlightOn" : "自動頭燈敏感度設定",
	"AutoWiper" : "感應式雨刷",
	"BSMBuzzerVolume" : "Blind Spot Monitoring 音量",
	"BSMReset" : "是否確定要將 BSM 設定還原成原廠預設值?",
	"BSMResetError" : "無法將 BSM 設定還原成原廠預設值。要重試嗎? ",
	"BSMResetProgress" : "正在還原 BSM 設定 ",
	"BSMSystem" : "Blind Spot Monitoring 系統 ",
	"Beep" : "嗶嗶聲",
	"BeepVolume" : "嗶嗶聲音量",
	"Beep_Line" : "嗶嗶聲",
	"BeforeLine" : "之前",
	"Brightness" : "亮度",
	"BrightnessControl" : "亮度控制",
	"CHudNav_Maneuver" : "機動",
	"CHudNav_Off" : "關",
	"CHudNav_TBT_Lane" : "道路指引與逐向",
	"CHudNav_TBT_Street" : "街名與逐向導航",
	"Calibration" : "亮度",
	"CautionSpeed" : "警示閥值",
	"CenterDisplay" : "中央顯示器",
	"ChangingLASSettings" : "變更 Lane-keep Assist System 設定",
	"Clock" : "時鐘",
	"Close" : "關閉",
	"ComingHomeLights" : "Coming Home Light",
	"ComingHomeLightsTimer" : "Coming Home Light",
	"DRSS" : "Distance Recognition Support System",
	"DRSSReset" : "您確定要將 Distance Recognition Support System 設定還原成原廠預設值嗎?",
	"DRSSResetError" : "無法將 Distance Recognition Support System 設定還原成原廠預設值。 要重試嗎?",
	"DRSSResetProgress" : "正在還原 Distance Recognition Support System 設定",
	"Dark" : "低",
	"DaytimeRunningLights" : "日行燈",
	"Devices" : "裝置",
	"Display" : "顯示設定",
	"DisplayInformation" : "顯示資料",
	"DistanceRecognitionSupportSystem" : "Distance Recognition Support System",
	"DoorLock" : "門鎖",
	"DoorLockMode" : "自動門鎖模式",
	"DoorLockReset" : "您確定要將「門鎖」設定還原成原廠預設值嗎?",
	"DoorLockResetError" : "無法將「門鎖」設定還原成原廠預設值。 要重試嗎?",
	"DoorLockResetProgress" : "正在還原「門鎖」設定",
	"DoorRelockTime" : "自動重新鎖定時間",
	"DriverAlert" : "Driver Attention Alert",
	"Early" : "提早",
	"ErrorBSMSettings" : "變更 BSM 設定時出錯。要重試嗎? ",
	"ErrorLASSettings" : "無法變更 Lane-keep Assist System。  要重試嗎?",
	"FOWReset" : "您確定要將 Forward Obstruction Warning 設定還原成原廠預設值嗎?",
	"FOWResetError" : "無法將 Forward Obstruction Warning 設定還原成原廠預設值。 要重試嗎?",
	"FOWResetProgress" : "正在還原 Forward Obstruction Warning 設定",
	"Far" : "較遠",
	"ForwardObstructionWarning" : "Forward Obstruction Warning",
	"FrontCameraView" : "前方攝影機影像",
	"GearShiftIndicator" : "換檔指示燈",
	"GuidelineDisplay" : "動態路線",
	"HUD" : "AD-Disp",
	"HUDDisplayInfoError" : "無法將「AD-Disp 顯示資訊」設定還原為原廠預設值。 是否要重試？",
	"HUDDisplayInfoReset" : "是否確定將「AD-Disp 顯示資訊」設定還原為預設值？",
	"HUDDisplayInfoResetProgress" : "還原「AD-Disp 顯示資訊」設定",
	"HUDJ78AReset" : "是否確定將 Active Driving Display 設定重設為預設值？",
	"HUDJ78AResetError" : "重設 Active Driving Display 設定時發生錯誤。 是否要重試？",
	"HUDJ78AResetProgress" : "重設 Active Driving Display 設定",
	"HUDJ78ATab" : "Active Driving Display",
	"HUDReset" : "您確定要將 Active Driving Display 設定還原成原廠預設值嗎?",
	"HUDResetError" : "無法將 Active Driving Display 設定還原成原廠預設值。 要重試嗎?",
	"HUDResetProgress" : "正在變更 Active Driving Display 設定",
	"HUDSettings" : "AD-Disp 設定",
	"HUD_HeadUpDisplay" : "Active Driving Display",
	"HeadUpDisplay" : "Active Driving Display",
	"HeadlightOffTimer" : "頭燈關閉計時器",
	"HeadlightOnWarning" : "頭燈開啟警告",
	"HeadsUpDisplay" : "Active Driving Display",
	"Height" : "高度",
	"High" : "高",
	"HighBeamControl" : "High Beam Control",
	"High_SensitivityLAS" : "高",
	"High_Vibration" : "高",
	"ILB_Bright" : "亮",
	"ILB_Dark" : "暗",
	"ILB_Medium" : "中",
	"ILB_Off" : "關 ",
	"IgONAutoDisplay" : "自動顯示 360° 影像攝影機",
	"InterioLightsTimeOutDoorsClosed" : "車室燈熄滅-門關閉時",
	"InterioLightsTimeOutDoorsOpen" : "車室燈熄滅-門開啟時",
	"InteriorLightTimeoutDoorClosedTitle" : "內燈逾時未關-車門已關閉",
	"InteriorLightTimeoutDoorOpenTitle" : "內燈逾時未關-車門已開啟",
	"InteriorLightingBrightness" : "環境照明",
	"Intervention" : "干預",
	"InterventionTiming" : "干擾定時",
	"KeylessLockBeepVol" : "免持式鑰匙嗶嗶聲音量",
	"Kilometers" : "km/h",
	"LASAlert" : "LAS 警告",
	"LASDefaultValues" : "您確定要還原 Lane-keep Assist System 設定至預設值嗎?",
	"LASEarly" : "提早",
	"LASLate" : "延後",
	"LASSound" : "警告類型",
	"LASTiming" : "LAS 定時",
	"LDWSReset" : "您確定要將 Lane Departure Warning System 設定還原成原廠預設值嗎?",
	"LDWSResetError" : "無法將 Lane Departure Warning System 設定還原成原廠預設值。 要重試嗎?",
	"LDWSResetProgress" : "正在還原 Lane Departure Warning System 設定",
	"LDWSTiming" : "LDWS 感應時間設定",
	"LaneDepartureAlert" : "Lane Departure 警告",
	"LaneDepartureWarningSystem" : "Lane Departure Warning System",
	"LaneKeepAssistSystem" : "Lane-keep Assist System",
	"Late" : "延後",
	"LeavingHomeLights" : "Leaving Home Light",
	"Light" : "高",
	"LightOnReminderVolume" : "頭燈未關警示音",
	"Lighting" : "照明",
	"LightingReset" : "您確定要將「照明」設定還原成原廠預設值嗎?",
	"LightingResetError" : "無法將「照明」設定還原成原廠預設值。 要重試嗎?",
	"LightingResetProgress" : "正在還原「照明」設定",
	"LockShiftFromP" : "上鎖 : P檔以外檔位 ",
	"LockShiftFromPUnlockInPark" : "上鎖 : P檔外   解鎖 : P檔",
	"LockUnlock" : "上鎖 : 行駛時   解鎖 : P檔",
	"LockWhenDriving" : "上鎖 : 行駛時",
	"LockWhenDrivingUnlockIGNoff" : "上鎖 : 行駛時   解鎖 : 引擎熄火",
	"Long" : "較遠",
	"Low" : "低",
	"Low_SensitivityLAS" : "低",
	"Low_Vibration" : "低",
	"Manual" : "手動",
	"Med" : "中",
	"Medium" : "中",
	"MediumDark" : "中等低",
	"MediumLight" : "中等高",
	"Medium_Int_OFF" : "中",
	"Medium_SensitivityLAS" : "中",
	"Mid" : "中",
	"Middle" : "中等",
	"Miles" : "mph",
	"Mode" : "顯示模式",
	"Navigation" : "導航",
	"NavigationSignal" : "導航  ",
	"Near" : "較近",
	"Off" : "關閉",
	"Often" : "經常",
	"Often_Int_OFF" : "經常",
	"OnDemand" : "隨選",
	"OnceAllDoors" : "所有車門 : 一次",
	"OnceDriversDoorTwiceAllDoors" : "駕駛座車門 : 一次   所有車門 : 兩次",
	"Open" : "開啟",
	"ParkingSensorIndication" : "倒車雷達圖示 ",
	"ParkingSensorIndicator" : "泊車感應器指示燈",
	"RVMBuzzerVolume" : "Rear Vehicle Monitoring 音量",
	"Rare" : "很少",
	"Rare_Int_OFF" : "很少",
	"Reset" : "初始設定",
	"Rotation" : "旋轉",
	"RumbleStrips" : "隆隆聲",
	"RumbleStrips_line" : "隆隆聲 ",
	"RumbleVolume" : "隆隆聲",
	"SBSReset" : "您確定要將 Smart Brake Support 設定還原成原廠預設值嗎?",
	"SBSResetError" : "無法將 Smart Brake Support 設定還原成原廠預設值。 要重試嗎?",
	"SBSResetProgress" : "正在還原 Smart  Brake Support 設定",
	"SBSSCBS" : "SBS/SCBS",
	"SBS_SCBSReset" : "您確定要將 SBS/SCBS 設定還原成原廠預設值嗎?",
	"SBS_SCBSResetError" : "無法將 SBS/SCBS 設定還原成原廠預設值。 要重試嗎?",
	"SBS_SCBSResetProgress" : "正在還原 SBS/SCBS 設定",
	"SCBS" : "Smart City Brake Support",
	"SCBSReset" : "是否確定要將 SCBS 設定還原成原廠預設值? ",
	"SCBSResetError" : "無法將 SCBS 設定還原成原廠預設值。要重試嗎? ",
	"SCBSResetProgress" : "正在還原 SCBS 設定",
	"SLC_Buzzer" : "僅蜂鳴器",
	"SLC_Off" : "關 ",
	"SLC_Sign" : "視覺",
	"SLC_Sign_Buzzer" : "音訊與視覺",
	"SLIReset" : "是否確定要將「速限警告」設定還原成預設值？ ",
	"SLIResetError" : "無法將「速限警告」設定還原成原廠預設值。要重試嗎? ",
	"SLIResetProgress" : "還原「速限警告」設定",
	"SLI_HeadUpDisplay" : "Active Driving Display",
	"Safety" : "安全",
	"Safetysettings" : "安全設定",
	"Sensitivity" : "敏感度",
	"Sensitivity_Intervention_OFF" : "警告 ",
	"Setting" : "設定",
	"Settings" : "設定",
	"Short" : "較近",
	"SideView" : "側方",
	"SideViewFrontView" : "側方+前方",
	"SmartBrakeSupport" : "Smart Brake Support",
	"Sound" : "音效設定",
	"SpeedAlarm" : "車速警報",
	"SpeedLimitCaution" : "速限警示",
	"SpeedLimitInformation" : "速限警告",
	"SpeedLimitSign" : "速限顯示",
	"StepKilometers" : "{value} km/h",
	"StepMiles" : "{value} mph",
	"StreetInformation" : "街道資料",
	"Streetinfo_off" : "關",
	"System" : "系統設定",
	"TSRReset" : "是否確定要將 交通標誌識別系統 設定還原成預設值? ",
	"TSRResetError" : "無法將 交通標誌識別系統設定 還原成原廠預設值。要重試嗎? ",
	"TSRResetProgress" : "還原 交通標誌識別系統 設定",
	"TSR_Display" : "交通標誌顯示",
	"TSR_System" : "交通標誌識別系統",
	"Tachometer" : "轉速計",
	"ThreeFlashTurnSignal" : "輕撥快閃方向燈",
	"Timing" : "計時",
	"Turn" : "方向燈",
	"TurnProgress" : "正在還原「方向燈」設定",
	"TurnReset" : "您確定要將「方向燈」設定還原成原廠預設值嗎?",
	"TurnResetError" : "無法將「方向燈」設定還原成原廠預設值。要重試嗎?",
	"TurnSettings" : "方向燈",
	"TurnSignalIndicatorVolume" : "方向燈作動音量",
	"UnlockMode" : "解除鎖定模式",
	"Vehicle" : "車輛設定",
	"VehicleSettings" : "車輛設定",
	"Vibration" : "震動",
	"VibrationStrength" : "震動強度",
	"Vibration_Line" : "震動",
	"ViewSwitchDisplay" : "預設檢視",
	"ViewSwitchFunction" : "影像切換功能",
	"Volume" : "警告音量",
	"WalkAwayLock" : "遙控鎖",
	"Warning" : "警告",
	"WarningDistance" : "警告距離",
	"_0s" : "0 秒鐘",
	"_0seconds" : "0 秒鐘",
	"_10m" : "10 分鐘",
	"_10minutes" : "10 分鐘",
	"_120s" : "120 秒鐘",
	"_120seconds" : "120 秒鐘",
	"_15s" : "15 秒鐘",
	"_15seconds" : "15 秒鐘",
	"_30m" : "30 分鐘",
	"_30minutes" : "30 分鐘",
	"_30s" : "30 秒鐘",
	"_30seconds" : "30 秒鐘",
	"_60m" : "60 分鐘",
	"_60minutes" : "60 分鐘",
	"_60s" : "60 秒鐘",
	"_60seconds" : "60 秒鐘",
	"_7p5s" : "7.5 秒鐘",
	"_7p5seconds" : "7.5 秒鐘",
	"_90s" : "90 秒鐘",
	"_90seconds" : "90 秒鐘",
	"_AllDoors" : "全部門鎖",
	"_Driver'sDoor" : "駕駛座門鎖",
	"on" : "開啟",
};

framework.registerAppDictLoaded("vehsettings", "mn_TW");