var Localization_vehsettingsAppDict_pl_PL = {
	//"stringId" : "localString"
	"360ViewCamera" : "Widok 360°",
	"AHBC" : "Adaptive LED Headlights",
	"Adaptive" : "Adapt.",
	"AdaptiveFront-lightingSystem" : "System daptacyjnych świateł mijania",
	"AdaptiveLaneStreetTurn" : "Adaptacyjne: pas ruchu/ulica/skręt",
	"AlarmTiming" : "Prędkości",
	"AlertTiming" : "Czas alarmu",
	"Always" : "Zawsze",
	"AtLine" : "Pas",
	"Auto" : "Auto",
	"AutoHeadlightOn" : "Czujn. zmierzchu - poz. światła",
	"AutoWiper" : "Czujnik deszczu",
	"BSMBuzzerVolume" : "Blind Spot Monitoring Głośność",
	"BSMReset" : "Czy na pewno chcesz przywrócić ustawienia fabryczne BSM?",
	"BSMResetError" : "Nie można przywrócić ustawień fabrycznych BSM. Spróbować ponownie?",
	"BSMResetProgress" : "Przywracanie ustawień BSM",
	"BSMSystem" : "System monitorowania martwego pola ",
	"Beep" : "Beep",
	"BeepVolume" : "Głośność sygnału",
	"Beep_Line" : "Beep",
	"BeforeLine" : "p. pas",
	"Brightness" : "Jasność",
	"BrightnessControl" : "Regulacja jasności",
	"CHudNav_Maneuver" : "Manewr",
	"CHudNav_Off" : "Wył.",
	"CHudNav_TBT_Lane" : "Zmiana pasa i wsk. krok po kroku",
	"CHudNav_TBT_Street" : "Nazwa ulicy i wsk. krok po kroku",
	"Calibration" : "Jasność",
	"CautionSpeed" : "Próg alarmowy",
	"CenterDisplay" : "Wyświetlacz środkowy",
	"ChangingLASSettings" : "Zmiana ustawień LAS systemu",
	"Clock" : "Zegar",
	"Close" : "Zam.",
	"ComingHomeLights" : "Coming Home Light",
	"ComingHomeLightsTimer" : "Coming Home Light",
	"DRSS" : "Distance Recognition Support System",
	"DRSSReset" : "Czy na pewno przywrócić wartości domyślne ustawień Distance Recognition Support System (DRSS)?",
	"DRSSResetError" : "Błąd zmiany ustawień Distance Recognition Support System (DRSS). Czy ponowić?",
	"DRSSResetProgress" : "Zmienianie ustawień Distance Recognition Support System (DRSS)",
	"Dark" : "Ciemny",
	"DaytimeRunningLights" : "Światła do jazdy dziennej",
	"Devices" : "Przyrzą.",
	"Display" : "Wyświet",
	"DisplayInformation" : "Wyświetlane informacje",
	"DistanceRecognitionSupportSystem" : "Distance Recognition Support System",
	"DoorLock" : "Zamki drzwi",
	"DoorLockMode" : "Tryb autom. zamków drzwi",
	"DoorLockReset" : "Czy na pewno chcesz przywrócić ustawienia układu blokowania drzwi do wart. fabrycznych?",
	"DoorLockResetError" : "Błąd zmiany ustawień układu blokowania drzwi. Czy ponowić?",
	"DoorLockResetProgress" : "Zmienianie ustawień układu blokowania drzwi",
	"DoorRelockTime" : "Czas autom. ryglowania drzwi",
	"DriverAlert" : "Driver Attention Alert",
	"Early" : "Wczesny",
	"ErrorBSMSettings" : "Błąd podczas zmiany ustawień BSM. Spróbować ponownie?",
	"ErrorLASSettings" : "Błąd przy zmianie Lane-keep Assist System. Czy chcesz spróbować ponownie?",
	"FOWReset" : "Czy na pewno przywrócić ustawienia systemu Forward Obstruction Warning (FOW) do wart. fabrycznych?",
	"FOWResetError" : "Błąd podczas zmiany ustawień Forward Obstruction Warning (FOW). Czy ponowić?",
	"FOWResetProgress" : "Zmienianie ustawień systemu Forward Obstruction Warning (FOW)",
	"Far" : "Daleko",
	"ForwardObstructionWarning" : "Forward Obstruction Warning",
	"FrontCameraView" : "Widok kamery z przodu",
	"GearShiftIndicator" : "Wskaźnik wybranego biegu",
	"GuidelineDisplay" : "Dynam. linie ścieżki",
	"HUD" : "AD-Disp",
	"HUDDisplayInfoError" : "Nie można przywrócić domyślnych ustawień fabrycznych informacji wyświetlacza AD-Disp. Czy chcesz spróbować ponownie?",
	"HUDDisplayInfoReset" : "Czy na pewno chcesz przywrócić domyślne wartości ustawień informacji wyświetlacza AD-Disp?",
	"HUDDisplayInfoResetProgress" : "Trwa przywracanie ustawień informacji wyświetlacza AD-Disp",
	"HUDJ78AReset" : "Czy na pewno chcesz przywrócić ustawienia domyślne Active Driving Display?",
	"HUDJ78AResetError" : "Podczas zerowania ustawień Active Driving Display wystąpił błąd. Chcesz spróbować ponownie?",
	"HUDJ78AResetProgress" : "Zerowanie ustawień Active Driving Display",
	"HUDJ78ATab" : "Active Driving Display",
	"HUDReset" : "Czy na pewno chcesz przywrócić ustawienia systemu Active Driving Display do wart. fabrycznych?",
	"HUDResetError" : "Błąd zmiany ustawień systemu Active Driving Display. Czy ponowić?",
	"HUDResetProgress" : "Zmienianie ustawień systemu AD-Disp",
	"HUDSettings" : "Ustawienia AD-Disp",
	"HUD_HeadUpDisplay" : "Active Driving Display",
	"HeadUpDisplay" : "Active Driving Display",
	"HeadlightOffTimer" : "czasomierz wyłączan. reflektorów",
	"HeadlightOnWarning" : "Ostrzeż. o wył. refl.",
	"HeadsUpDisplay" : "Active Driving Display",
	"Height" : "Wysokość",
	"High" : "Wys.",
	"HighBeamControl" : "High Beam Control",
	"High_SensitivityLAS" : "Wys.",
	"High_Vibration" : "Wysoka",
	"ILB_Bright" : "Jasne",
	"ILB_Dark" : "Przygaszone",
	"ILB_Medium" : "Średni",
	"ILB_Off" : "Wyłączony ",
	"IgONAutoDisplay" : "Automat. wyświetl. 360° View Monitor",
	"InterioLightsTimeOutDoorsClosed" : "Oświetl. wnętrza - drzwi zamkn.",
	"InterioLightsTimeOutDoorsOpen" : "Oświetl. wnętrza - drzwi otw.",
	"InteriorLightTimeoutDoorClosedTitle" : "Wewn. św. wył. - drzwi zamkn.",
	"InteriorLightTimeoutDoorOpenTitle" : "Wewn. św. wył. - drzwi otwarte",
	"InteriorLightingBrightness" : "Oświetlenie otoczenia",
	"Intervention" : "Interwencja",
	"InterventionTiming" : "Czas interwencji",
	"KeylessLockBeepVol" : "Głośność sygn. dostępu bez klucz",
	"Kilometers" : "km/h",
	"LASAlert" : "Ostrzeżenie LAS",
	"LASDefaultValues" : "Czy na pewno chcesz przywrócić domyślne ustawienia Lane-keep Assist System?",
	"LASEarly" : "Wczesny",
	"LASLate" : "Późny",
	"LASSound" : "Rodzaj alarmu",
	"LASTiming" : "Ustawienia czasu LAS",
	"LDWSReset" : "Czy przywrócić ustawienia układu Lane Departure Warning System (LDWS) do wart. fabrycznych.",
	"LDWSResetError" : "Błąd zmiany ustawień układu Lane Departure Warning System (LDWS). Czy ponowić?",
	"LDWSResetProgress" : "Zmienianie ustawień układu Lane Departure Warning System (LDWS)",
	"LDWSTiming" : "Synchronizacja układu LDWS",
	"LaneDepartureAlert" : "Alarm zmiany pasa ruchu",
	"LaneDepartureWarningSystem" : "Lane Departure Warning System",
	"LaneKeepAssistSystem" : "Lane-keep Assist System",
	"Late" : "Późny",
	"LeavingHomeLights" : "Leaving Home Light",
	"Light" : "Jasny",
	"LightOnReminderVolume" : "Sygn. wł. świat.",
	"Lighting" : "Oświetlenie",
	"LightingReset" : "Czy na pewno chcesz przywrócić ustawienia oświetlenia do wart. fabrycznych?",
	"LightingResetError" : "Błąd zmiany ustawień oświetlenia. Czy ponowić?",
	"LightingResetProgress" : "Zmienianie ustawień oświetlenia",
	"LockShiftFromP" : "Zablokuj:  przełączanie z poz. Park ",
	"LockShiftFromPUnlockInPark" : "Zabl: przeł. z Park; odbl: w poz. Park",
	"LockUnlock" : "Zablokuj: jazdy Odblokuj: postoju",
	"LockWhenDriving" : "Zablokuj: podczas jazdy",
	"LockWhenDrivingUnlockIGNoff" : "zablok: w cz. jazdy Odbl.: wył. Zap.",
	"Long" : "Długa",
	"Low" : "Nisk.",
	"Low_SensitivityLAS" : "Nisk.",
	"Low_Vibration" : "Niska",
	"Manual" : "Ręcz.",
	"Med" : "Śred.",
	"Medium" : "Średni",
	"MediumDark" : "Średnio ciemny",
	"MediumLight" : "Średnio jasny",
	"Medium_Int_OFF" : "Śred",
	"Medium_SensitivityLAS" : "Śred",
	"Mid" : "Śred.",
	"Middle" : "Środek",
	"Miles" : "mile/h",
	"Mode" : "Tryb",
	"Navigation" : "Nawigacja",
	"NavigationSignal" : "Nawigacja  ",
	"Near" : "Blisko",
	"Off" : "Wył.",
	"Often" : "Często",
	"Often_Int_OFF" : "Często",
	"OnDemand" : "Na żądanie",
	"OnceAllDoors" : "Jeden raz: wszystkie drzwi",
	"OnceDriversDoorTwiceAllDoors" : "1 raz: drzwi kier. 2 razy: wszystkie",
	"Open" : "Otw.",
	"ParkingSensorIndication" : "Wskaźnik czujnika parkowania ",
	"ParkingSensorIndicator" : "Wskaźnik czujnika parkowania",
	"RVMBuzzerVolume" : "Rear Vehicle Monitoring Głośność",
	"Rare" : "Rzadko",
	"Rare_Int_OFF" : "Rzadko",
	"Reset" : "Resetuj",
	"Rotation" : "Rotacja",
	"RumbleStrips" : "Wibr.",
	"RumbleStrips_line" : "Wibr. ",
	"RumbleVolume" : "Głośność wibracji",
	"SBSReset" : "Czy na pewno przywrócić wartości fabryczne Smart Brake Support (SBS)?",
	"SBSResetError" : "Błąd podczas zmiany ustawień układu Smart Brake Support (SBS). Czy ponowić?",
	"SBSResetProgress" : "Zmienianie ustawień Smart Brake Support (SBS)",
	"SBSSCBS" : "SBS/SCBS",
	"SBS_SCBSReset" : "Czy na pewno przywrócić ustawienia SBS/SCBS do ust. fabrycznych?",
	"SBS_SCBSResetError" : "Błąd podczas zmiany ustawień SBS/SCBS. Czy ponowić?",
	"SBS_SCBSResetProgress" : "Zmienianie ustawień SBS/SCBS",
	"SCBS" : "Smart City Brake Support",
	"SCBSReset" : "Czy na pewno chcesz przywrócić ustawienia fabryczne SCBS?\"",
	"SCBSResetError" : "Nie można przywrócić ustawień fabrycznych SCBS. Spróbować ponownie?\"",
	"SCBSResetProgress" : "Przywracanie ustawień SCBS",
	"SLC_Buzzer" : "Tylko brzęczyk",
	"SLC_Off" : "Wyłączony ",
	"SLC_Sign" : "Wizualnie",
	"SLC_Sign_Buzzer" : "Audiowizualnie",
	"SLIReset" : "Na pewno chcesz przywrócić ustawienia ostrzeżenia o ograniczeniach prędkości do wartości domyślnych?",
	"SLIResetError" : "Nie można przywrócić ustawień ostrzeżenia o ograniczeniach prędkości do wartości domyślnych. Chcesz spróbować ponownie?",
	"SLIResetProgress" : "Przywracanie ustawień ostrzeżenia o ograniczeniach prędkości",
	"SLI_HeadUpDisplay" : "Active Driving Display",
	"Safety" : "Bezp.",
	"Safetysettings" : "Bezpieczne ustawienia",
	"Sensitivity" : "Czułość",
	"Sensitivity_Intervention_OFF" : "Ostrzeżenie ",
	"Setting" : "Powiadomienie wł./wył.",
	"Settings" : "Ustawienia",
	"Short" : "Krótka",
	"SideView" : "Bok",
	"SideViewFrontView" : "Bok+przód",
	"SmartBrakeSupport" : "Smart Brake Support",
	"Sound" : "Dźwięk",
	"SpeedAlarm" : "Alarm prędkości",
	"SpeedLimitCaution" : "Alert o ogr. prędkości",
	"SpeedLimitInformation" : "Ostrz. o ogr. prędkości",
	"SpeedLimitSign" : "Inf. o ogr. prędkości",
	"StepKilometers" : "{value} km/h",
	"StepMiles" : "{value} mile/h",
	"StreetInformation" : "Informacje o ulicy",
	"Streetinfo_off" : "Wyłączony",
	"System" : "System",
	"TSRReset" : "Na pewno chcesz przywrócić ustawienia Systemu rozpoznawania znaków drogowych do wartości domyślnych?",
	"TSRResetError" : "Nie można przywrócić ustawień Systemu rozpoznawania znaków drogowych do wartości domyślnych. Chcesz spróbować ponownie?",
	"TSRResetProgress" : "Przywracanie ustawień Systemu rozpoznawania znaków drogowych",
	"TSR_Display" : "Wyświetlacz znaków drogowych",
	"TSR_System" : "System rozpoznawania znaków drogowych",
	"Tachometer" : "Obrotomierz",
	"ThreeFlashTurnSignal" : "Kierunkowskaz — 3 mignięcia",
	"Timing" : "Synchronizacja",
	"Turn" : "Kierunkowskazy",
	"TurnProgress" : "Zmienianie ustawień skrętu",
	"TurnReset" : "Czy na pewno chcesz przywrócić ustawienia układu ostrzegającego o zmianie pasa.",
	"TurnResetError" : "Błąd zmiany ustawień skrętu. Ponowić?",
	"TurnSettings" : "Kierunkowskazy",
	"TurnSignalIndicatorVolume" : "Głośność dźwięku kier.",
	"UnlockMode" : "Tryb odblokowania",
	"Vehicle" : "Pojazd",
	"VehicleSettings" : "Ustaw. pojazdu",
	"Vibration" : "Wibracje",
	"VibrationStrength" : "Siła wibracji",
	"Vibration_Line" : "Wibracje",
	"ViewSwitchDisplay" : "Widok domyślny",
	"ViewSwitchFunction" : "Funkcja przełączania widoku",
	"Volume" : "Głośność",
	"WalkAwayLock" : "Samoczynne blokowanie",
	"Warning" : "Ostrzeżenie",
	"WarningDistance" : "Dystans ostrzeg",
	"_0s" : "0 s",
	"_0seconds" : "0 s",
	"_10m" : "10 min",
	"_10minutes" : "10 min",
	"_120s" : "120 s",
	"_120seconds" : "120 s",
	"_15s" : "15 s",
	"_15seconds" : "15 s",
	"_30m" : "30 min",
	"_30minutes" : "30 min",
	"_30s" : "30 s",
	"_30seconds" : "30 s",
	"_60m" : "60 min",
	"_60minutes" : "60 min",
	"_60s" : "60 s",
	"_60seconds" : "60 s",
	"_7p5s" : "7,5 s",
	"_7p5seconds" : "7,5 s",
	"_90s" : "90 s",
	"_90seconds" : "90 s",
	"_AllDoors" : "Wszyst.",
	"_Driver'sDoor" : "Kierow.",
	"on" : "Wł.",
};

framework.registerAppDictLoaded("vehsettings", "pl_PL");