var Localization_vehsettingsAppDict_en_US = {
	//"stringId" : "localString"
	"360ViewCamera" : "360° View Monitor",
	"AHBC" : "Adaptive LED Headlights",
	"Adaptive" : "Adaptive",
	"AdaptiveFront-lightingSystem" : "Adaptive Front-lighting System",
	"AdaptiveLaneStreetTurn" : "Adaptive Lane/Street/Turn",
	"AlarmTiming" : "Speed",
	"AlertTiming" : "Alert Timing",
	"Always" : "Always",
	"AtLine" : "At",
	"Auto" : "Auto",
	"AutoHeadlightOn" : "Auto Headlight On",
	"AutoWiper" : "Rain Sensing Wiper",
	"BSMBuzzerVolume" : "Blind Spot Monitoring Volume",
	"BSMReset" : "Are you sure you want to restore BSM settings to the factory defaults?",
	"BSMResetError" : "Unable to restore BSM settings to the factory defaults. Would you like to retry?",
	"BSMResetProgress" : "Restoring BSM Settings",
	"BSMSystem" : "Blind Spot Monitoring System ",
	"Beep" : "Beep",
	"BeepVolume" : "Beep Volume",
	"Beep_Line" : "Beep",
	"BeforeLine" : "Before",
	"Brightness" : "Brightness",
	"BrightnessControl" : "Brightness Control",
	"CHudNav_Maneuver" : "At Maneuver",
	"CHudNav_Off" : "Off",
	"CHudNav_TBT_Lane" : "Lane Guidance & Turn-by-Turn",
	"CHudNav_TBT_Street" : "Street Name & Turn-by-Turn",
	"Calibration" : "Brightness",
	"CautionSpeed" : "Alert Threshold",
	"CenterDisplay" : "Center Display",
	"ChangingLASSettings" : "Changing LAS settings",
	"Clock" : "Clock",
	"Close" : "Close",
	"ComingHomeLights" : "Coming Home Light",
	"ComingHomeLightsTimer" : "Coming Home Light",
	"DRSS" : "Distance Recognition Support System",
	"DRSSReset" : "Are you sure you want to restore Distance Recognition Support System settings to the factory defaults?",
	"DRSSResetError" : "Unable to restore Distance Recognition Support System settings to the factory defaults. Would you like to retry?",
	"DRSSResetProgress" : "Restoring Distance Recognition Support System settings",
	"Dark" : "Low",
	"DaytimeRunningLights" : "Daytime Running Lights",
	"Devices" : "Devices",
	"Display" : "Display",
	"DisplayInformation" : "Display Information",
	"DistanceRecognitionSupportSystem" : "Distance Recognition Support System",
	"DoorLock" : "Door Locks",
	"DoorLockMode" : "Auto Door Lock Mode",
	"DoorLockReset" : "Are you sure you want to restore Door Lock settings to the factory defaults?",
	"DoorLockResetError" : "Unable to restore Door Lock settings to the factory defaults. Would you like to retry?",
	"DoorLockResetProgress" : "Restoring Door Lock settings",
	"DoorRelockTime" : "Auto Relock Time",
	"DriverAlert" : "Driver Attention Alert",
	"Early" : "Early",
	"ErrorBSMSettings" : "Error changing BSM settings. Would you like to retry?",
	"ErrorLASSettings" : "Error changing Lane-keep Assist System. Would you like to retry?",
	"FOWReset" : "Are you sure you want to restore Forward Obstruction Warning settings to the factory defaults?",
	"FOWResetError" : "Unable to restore Forward Obstruction Warning settings to the factory defaults. Would you like to retry?",
	"FOWResetProgress" : "Restoring Forward Obstruction Warning settings",
	"Far" : "Far",
	"ForwardObstructionWarning" : "Forward Obstruction Warning",
	"FrontCameraView" : "Front Camera View",
	"GearShiftIndicator" : "Gear Shift Indicator",
	"GuidelineDisplay" : "Dynamic Path Lines",
	"HUD" : "AD-Disp",
	"HUDDisplayInfoError" : "Unable to restore AD-Disp Display Information settings to the factory defaults. Would you like to retry?",
	"HUDDisplayInfoReset" : "Are you sure you want to restore AD-Disp Display Information settings to their default values?",
	"HUDDisplayInfoResetProgress" : "Restoring AD-Disp Display Information Settings",
	"HUDJ78AReset" : "Are you sure you want to restore Active Driving Display settings to their default values?",
	"HUDJ78AResetError" : "Unable to restore Active Driving Display settings to the factory defaults. Would you like to retry?",
	"HUDJ78AResetProgress" : "Restoring Active Driving Display settings",
	"HUDJ78ATab" : "Active Driving Display",
	"HUDReset" : "Are you sure you want to restore Active Driving Display settings to their default values?",
	"HUDResetError" : "Unable to restore Active Driving Display settings to the factory defaults. Would you like to retry?",
	"HUDResetProgress" : "Restoring Active Driving Display settings",
	"HUDSettings" : "AD-Disp Settings",
	"HUD_HeadUpDisplay" : "Active Driving Display",
	"HeadUpDisplay" : "Active Driving Display",
	"HeadlightOffTimer" : "Headlight Off Timer",
	"HeadlightOnWarning" : "Headlight On Warn",
	"HeadsUpDisplay" : "Active Driving Display",
	"Height" : "Height",
	"High" : "High",
	"HighBeamControl" : "High Beam Control",
	"High_SensitivityLAS" : "High",
	"High_Vibration" : "High",
	"ILB_Bright" : "Bright",
	"ILB_Dark" : "Dim",
	"ILB_Medium" : "Medium",
	"ILB_Off" : "Off ",
	"IgONAutoDisplay" : "Auto Display 360° View Monitor",
	"InterioLightsTimeOutDoorsClosed" : "Interior Light Timeout-Door Close",
	"InterioLightsTimeOutDoorsOpen" : "Interior Light Timeout-Door Open",
	"InteriorLightTimeoutDoorClosedTitle" : "Interior Light Timeout-Doors Closed",
	"InteriorLightTimeoutDoorOpenTitle" : "Interior Light Timeout-Doors Open",
	"InteriorLightingBrightness" : "Ambient Lighting",
	"Intervention" : "Intervention",
	"InterventionTiming" : "Intervention Timing",
	"KeylessLockBeepVol" : "Keyless Lock Beep Volume",
	"Kilometers" : "km/h",
	"LASAlert" : "LAS Alert",
	"LASDefaultValues" : "Are you sure you want to revert Lane-keep Assist System settings to their default values?",
	"LASEarly" : "Early",
	"LASLate" : "Late",
	"LASSound" : "Alert Type",
	"LASTiming" : "LAS Timing",
	"LDWSReset" : "Are you sure you want to restore Lane Departure Warning System settings to the factory defaults?",
	"LDWSResetError" : "Unable to restore Lane Departure Warning System settings to the factory defaults. Would you like to retry?",
	"LDWSResetProgress" : "Restoring Lane Departure Warning System settings",
	"LDWSTiming" : "LDWS Timing",
	"LaneDepartureAlert" : "Lane Departure Alert",
	"LaneDepartureWarningSystem" : "Lane Departure Warning System",
	"LaneKeepAssistSystem" : "Lane-keep Assist System",
	"Late" : "Late",
	"LeavingHomeLights" : "Leaving Home Light",
	"Light" : "High",
	"LightOnReminderVolume" : "Light On Vol",
	"Lighting" : "Lighting",
	"LightingReset" : "Are you sure you want to restore Lighting settings to the factory defaults?",
	"LightingResetError" : "Unable to restore Lighting settings to the factory defaults. Would you like to retry?",
	"LightingResetProgress" : "Restoring Lighting settings",
	"LockShiftFromP" : "Lock: Shifting Out of Park ",
	"LockShiftFromPUnlockInPark" : "Lock: Out of Park Unlock: In Park",
	"LockUnlock" : "Lock: When Driving Unlock: In Park",
	"LockWhenDriving" : "Lock: When Driving",
	"LockWhenDrivingUnlockIGNoff" : "Lock: When Driving Unlock: IGN Off",
	"Long" : "Far",
	"Low" : "Low",
	"Low_SensitivityLAS" : "Low",
	"Low_Vibration" : "Low",
	"Manual" : "Man.",
	"Med" : "Medium",
	"Medium" : "Medium",
	"MediumDark" : "Med. Low",
	"MediumLight" : "Med. High",
	"Medium_Int_OFF" : "Med",
	"Medium_SensitivityLAS" : "Med",
	"Mid" : "Mid",
	"Middle" : "Med.",
	"Miles" : "mph",
	"Mode" : "System",
	"Navigation" : "Navigation",
	"NavigationSignal" : "Navigation  ",
	"Near" : "Near",
	"Off" : "Off",
	"Often" : "Often",
	"Often_Int_OFF" : "Often",
	"OnDemand" : "On-Dem.",
	"OnceAllDoors" : "All Doors: Once",
	"OnceDriversDoorTwiceAllDoors" : "Driver's: Once, All Doors: Twice",
	"Open" : "Open",
	"ParkingSensorIndication" : "Parking Sensor Indication ",
	"ParkingSensorIndicator" : "Parking Sensor Indicator",
	"RVMBuzzerVolume" : "Rear Vehicle Monitoring Volume",
	"Rare" : "Rare",
	"Rare_Int_OFF" : "Rare",
	"Reset" : "Reset",
	"Rotation" : "Rotation",
	"RumbleStrips" : "Rumbl.",
	"RumbleStrips_line" : "Rumble ",
	"RumbleVolume" : "Rumble Volume",
	"SBSReset" : "Are you sure you want to restore Smart Brake Support settings to the factory defaults?",
	"SBSResetError" : "Unable to restore Smart Brake Support settings to the factory defaults. Would you like to retry?",
	"SBSResetProgress" : "Restoring Smart  Brake Support settings",
	"SBSSCBS" : "SBS/SCBS",
	"SBS_SCBSReset" : "Are you sure you want to restore SBS/SCBS settings to the factory defaults?",
	"SBS_SCBSResetError" : "Unable to Restore SBS/SCBS settings to the factory defaults. Would you like to retry?",
	"SBS_SCBSResetProgress" : "Restoring SBS/SCBS settings",
	"SCBS" : "Smart City Brake Support",
	"SCBSReset" : "Are you sure you want to restore SCBS settings to the factory defaults?\"",
	"SCBSResetError" : "Unable to restore SCBS settings to the factory defaults. Would you like to retry?\"",
	"SCBSResetProgress" : "Restoring SCBS settings",
	"SLC_Buzzer" : "Buzzer only",
	"SLC_Off" : "Off ",
	"SLC_Sign" : "Visual",
	"SLC_Sign_Buzzer" : "Audio & Visual",
	"SLIReset" : "Are you sure you want to restore Speed Limit Warning settings to their default values?",
	"SLIResetError" : "Unable to restore Speed Limit Warning settings to the factory defaults. Would you like to retry?",
	"SLIResetProgress" : "Restoring Speed Limit Warning settings",
	"SLI_HeadUpDisplay" : "Active Driving Display",
	"Safety" : "Safety",
	"Safetysettings" : "Safety Settings",
	"Sensitivity" : "Sensitivity",
	"Sensitivity_Intervention_OFF" : "Warning ",
	"Setting" : "Settings",
	"Settings" : "Settings",
	"Short" : "Near",
	"SideView" : "Side",
	"SideViewFrontView" : "Side+Front",
	"SmartBrakeSupport" : "Smart Brake Support",
	"Sound" : "Sound",
	"SpeedAlarm" : "Speed Alarm",
	"SpeedLimitCaution" : "Speed Limit Alert",
	"SpeedLimitInformation" : "Speed Limit Warning",
	"SpeedLimitSign" : "Speed Limit Display",
	"StepKilometers" : "{value} km/h",
	"StepMiles" : "{value} mph",
	"StreetInformation" : "Street Information",
	"Streetinfo_off" : "Off",
	"System" : "System",
	"TSRReset" : "Are you sure you want to restore Traffic Sign Recognition System settings to their default values?",
	"TSRResetError" : "Unable to restore Traffic Sign Recognition System settings to the factory defaults. Would like to retry?",
	"TSRResetProgress" : "Restoring Traffic Sign Recognition System settings",
	"TSR_Display" : "Traffic Sign Display",
	"TSR_System" : "Traffic Sign Recognition System",
	"Tachometer" : "Tachometer",
	"ThreeFlashTurnSignal" : "3-Flash Turn Signal",
	"Timing" : "Timing",
	"Turn" : "Turn Signals",
	"TurnProgress" : "Restoring Turn Signal settings",
	"TurnReset" : "Are you sure you want to restore Turn Signal settings to the factory defaults?",
	"TurnResetError" : "Unable to restore Turn Signal settings to the factory defaults. Would you like to retry?",
	"TurnSettings" : "Turn",
	"TurnSignalIndicatorVolume" : "Turn Signal Volume",
	"UnlockMode" : "Unlock Mode",
	"Vehicle" : "Vehicle",
	"VehicleSettings" : "Vehicle Settings",
	"Vibration" : "Vibration",
	"VibrationStrength" : "Vibration Strength",
	"Vibration_Line" : "Vibration",
	"ViewSwitchDisplay" : "Default View",
	"ViewSwitchFunction" : "View Switch Function",
	"Volume" : "Warning Volume",
	"WalkAwayLock" : "Walk Away Lock",
	"Warning" : "Warning",
	"WarningDistance" : "Warning Distance",
	"_0s" : "0 s",
	"_0seconds" : "0 seconds",
	"_10m" : "10 min",
	"_10minutes" : "10 minutes",
	"_120s" : "120 s",
	"_120seconds" : "120 seconds",
	"_15s" : "15 s",
	"_15seconds" : "15 seconds",
	"_30m" : "30 min",
	"_30minutes" : "30 minutes",
	"_30s" : "30 s",
	"_30seconds" : "30 seconds",
	"_60m" : "60 min",
	"_60minutes" : "60 minutes",
	"_60s" : "60 s",
	"_60seconds" : "60 seconds",
	"_7p5s" : "7.5 s",
	"_7p5seconds" : "7.5 seconds",
	"_90s" : "90 s",
	"_90seconds" : "90 seconds",
	"_AllDoors" : "All",
	"_Driver'sDoor" : "Driver's",
	"on" : "On",
};

framework.registerAppDictLoaded("vehsettings", "en_US");