var Localization_vehsettingsAppDict_sr_RS = {
	//"stringId" : "localString"
	"360ViewCamera" : "Monitor vidljivosti 360°",
	"AHBC" : "Adaptive LED Headlights",
	"Adaptive" : "Prilagodljiv",
	"AdaptiveFront-lightingSystem" : "Prilagodljivi sistem prednjih farova",
	"AdaptiveLaneStreetTurn" : "Prilagođavanje prema traci/ulici/skret.",
	"AlarmTiming" : "Podeš. brzine",
	"AlertTiming" : "Pr. vr. za upoz.",
	"Always" : "Uvek",
	"AtLine" : "Na lin.",
	"Auto" : "Auto",
	"AutoHeadlightOn" : "Autom. uklj. prednjih svetala",
	"AutoWiper" : "Brisač osetljiv na kišu",
	"BSMBuzzerVolume" : "Blind Spot Monitoring Jač. zv.",
	"BSMReset" : "Da li ste sigurni da želite da vratite postavke BSM-a na njihove fabrički podrazumevane vrednosti?",
	"BSMResetError" : "Postavke BSM-a nije moguće vratiti na fabričke vrednosti. Želite li da probate ponovo?",
	"BSMResetProgress" : "Postavke BSM-a se vraćaju",
	"BSMSystem" : "Sistem za nadzor mrtvog ugla ",
	"Beep" : "Zvučni",
	"BeepVolume" : "Jačina zvučnog signala",
	"Beep_Line" : "Zvučni",
	"BeforeLine" : "Pre lin.",
	"Brightness" : "Osvetljenost",
	"BrightnessControl" : "Kontrola osvetljenosti",
	"CHudNav_Maneuver" : "Manevr.",
	"CHudNav_Off" : "Isključ.",
	"CHudNav_TBT_Lane" : "Po trakama",
	"CHudNav_TBT_Street" : "Po ulicama",
	"Calibration" : "Osvetljenost",
	"CautionSpeed" : "Granična vrednost za upozorenje",
	"CenterDisplay" : "Centralni ekran",
	"ChangingLASSettings" : "Promena postavki LAS sistema",
	"Clock" : "Sat",
	"Close" : "Zatv.",
	"ComingHomeLights" : "Coming Home Light",
	"ComingHomeLightsTimer" : "Coming Home Light",
	"DRSS" : "Distance Recognition Support System",
	"DRSSReset" : "Da li ste sigurni da želite da vratite postavke Distance Recognition Support System (DRSS) na fabrički podrazumevane vrednosti?",
	"DRSSResetError" : "Greška pri promeni postavki Distance Recognition Support System (DRSS). Da li želite da pokušate ponovo?",
	"DRSSResetProgress" : "Promena postavki Distance Recognition Support System (DRSS)",
	"Dark" : "Tamno",
	"DaytimeRunningLights" : "Dnevna svetla",
	"Devices" : "Uređaji",
	"Display" : "Ekran",
	"DisplayInformation" : "Prikaz informacija",
	"DistanceRecognitionSupportSystem" : "Distance Recognition Support System",
	"DoorLock" : "Zaključavanje vrata",
	"DoorLockMode" : "Režim autom. zaključ. vrata",
	"DoorLockReset" : "Da li ste sigurni da želite da vratite postavke za zaključavanje vrata na fabrički podrazumevane vrednosti?",
	"DoorLockResetError" : "Greška kod menjanja postavki za zaključavanje vrata. Da li želite da pokušate ponovo?",
	"DoorLockResetProgress" : "Promena postavki za zaključavanje vrata",
	"DoorRelockTime" : "Vreme autom. ponovnog zaključ.",
	"DriverAlert" : "Driver Attention Alert",
	"Early" : "Rano",
	"ErrorBSMSettings" : "Greška pri menjanju postavki BSM-a. Želite li da probate ponovo?",
	"ErrorLASSettings" : "Greška pri promeni postavki Lane-keep Assist System. Da li želite da pokušate ponovo?",
	"FOWReset" : "Da li ste sigurni da želite da vratite postavke Forward Obstruction Warning na fabrički podrazumevane vrednosti?",
	"FOWResetError" : "Greška pri promeni postavki Forward Obstruction Warning. Da li želite da pokušate ponovo?",
	"FOWResetProgress" : "Promena postavki Forward Obstruction Warning",
	"Far" : "Daleko",
	"ForwardObstructionWarning" : "Forward Obstruction Warning",
	"FrontCameraView" : "Slika prednje kamere",
	"GearShiftIndicator" : "Indikator promene stepena prenosa",
	"GuidelineDisplay" : "Linije putanje kret.",
	"HUD" : "AD-Disp",
	"HUDDisplayInfoError" : "Vraćanje podešavanja informacija AD-Disp displeja na fabričke vrednosti nemoguće. Da li želite da pokušate ponovo?",
	"HUDDisplayInfoReset" : "Da li ste sigurni da želite da podešavanja informacija AD-Disp displeja vratite na podrazumevane vrednosti?",
	"HUDDisplayInfoResetProgress" : "Vraćanje podešavanja informacija AD-Disp displeja",
	"HUDJ78AReset" : "Da li ste sigurni da želite da resetujete podešavanja Active Driving Display na fabričke vrednosti?",
	"HUDJ78AResetError" : "Došlo je do greške pri resetovanju podešavanja Active Driving Display. Želite li da probate ponovo?",
	"HUDJ78AResetProgress" : "Podešavanja AD-Disp se resetuju",
	"HUDJ78ATab" : "Active Driving Display",
	"HUDReset" : "Da li ste sigurni da želite da vratite postavke Active Driving Display na fabrički podrazumevane vrednosti?",
	"HUDResetError" : "Greška pri promeni postavki Active Driving Display. Da li želite da pokušate ponovo?",
	"HUDResetProgress" : "Promena postavki Active Driving Display",
	"HUDSettings" : "Podešavanja AD-Disp",
	"HUD_HeadUpDisplay" : "Active Driving Display",
	"HeadUpDisplay" : "Active Driving Display",
	"HeadlightOffTimer" : "Tajmer za isklj. prednjih svetala",
	"HeadlightOnWarning" : "Upoz.uklj.pr.svet.",
	"HeadsUpDisplay" : "Active Driving Display",
	"Height" : "Visina",
	"High" : "Visok",
	"HighBeamControl" : "High Beam Control",
	"High_SensitivityLAS" : "Visok",
	"High_Vibration" : "Visok",
	"ILB_Bright" : "Svetlo",
	"ILB_Dark" : "Prigušeno",
	"ILB_Medium" : "Srednje",
	"ILB_Off" : "Isključeno ",
	"IgONAutoDisplay" : "360° View Monitor Automatski prikaz",
	"InterioLightsTimeOutDoorsClosed" : "Istek.vr.osvet. kabine - Vrata zatv.",
	"InterioLightsTimeOutDoorsOpen" : "Istek.vr.osvetlj. kabine - Vrata otv.",
	"InteriorLightTimeoutDoorClosedTitle" : "Kraj osvetlj.unut.kab.-Vrat.zatv.",
	"InteriorLightTimeoutDoorOpenTitle" : "Kraj osvetlj.unut.kab.-Vrat.otv.",
	"InteriorLightingBrightness" : "Ambijentalno osvetljenje",
	"Intervention" : "Intervencija",
	"InterventionTiming" : "Pr. vr. za inter.",
	"KeylessLockBeepVol" : "Jačina zv. signala dalj. zaklj./otklj.",
	"Kilometers" : "km/h",
	"LASAlert" : "LAS upozorenje",
	"LASDefaultValues" : "Da li ste sigurni da želite da vratite postavke Lane-keep Assist System na fabrički podrazumevane vrednosti?",
	"LASEarly" : "Rano",
	"LASLate" : "Kasno",
	"LASSound" : "Vrsta upozorenja",
	"LASTiming" : "Vremensko podešavanje LAS",
	"LDWSReset" : "Da li ste sigurni da želite da vratite postavke Lane Departure Warning System (LDWS) na fabrički podrazumevane vrednosti?",
	"LDWSResetError" : "Greška pri promeni postavki Lane Departure Warning System (LDWS). Da li želite da pokušate ponovo?",
	"LDWSResetProgress" : "Promena postavki Lane Departure Warning System (LDWS)",
	"LDWSTiming" : "Vremensko podešavanje LDWS",
	"LaneDepartureAlert" : "Upozorenje o napuštanju trake",
	"LaneDepartureWarningSystem" : "Lane Departure Warning System",
	"LaneKeepAssistSystem" : "Lane-keep Assist System",
	"Late" : "Kasno",
	"LeavingHomeLights" : "Leaving Home Light",
	"Light" : "Svetlo",
	"LightOnReminderVolume" : "Jač. zv. uklj. sv.",
	"Lighting" : "Osvetljenje",
	"LightingReset" : "Da li ste sigurni da želite da vratite postavke za osvetljenje na fabrički podrazumevane vrednosti?",
	"LightingResetError" : "Greška kod menjanja postavki za osvetljenje. Da li želite da pokušate ponovo?",
	"LightingResetProgress" : "Promena postavki za osvetljenje",
	"LockShiftFromP" : "Zaklj.: Ubac. u brzinu iz park. položaja ",
	"LockShiftFromPUnlockInPark" : "Zklj:Ubac. u brz. iz p.pol. - otklj:p.pol.",
	"LockUnlock" : "Zaključano: Vožnja otključano: Parki.",
	"LockWhenDriving" : "Zaključaj: Tokom vožnje",
	"LockWhenDrivingUnlockIGNoff" : "Zaklj.:U vožnji otklj.:Auto isklj.",
	"Long" : "Daleko",
	"Low" : "Nizak",
	"Low_SensitivityLAS" : "Nizak",
	"Low_Vibration" : "Nizak",
	"Manual" : "Ručno",
	"Med" : "Sred.",
	"Medium" : "Srednji",
	"MediumDark" : "Sred.Tam.",
	"MediumLight" : "Sred.Svet.",
	"Medium_Int_OFF" : "Sred",
	"Medium_SensitivityLAS" : "Sred",
	"Mid" : "Sred.",
	"Middle" : "Srednji",
	"Miles" : "mph",
	"Mode" : "Režim",
	"Navigation" : "Navigacija",
	"NavigationSignal" : "Navigacija  ",
	"Near" : "Blizu",
	"Off" : "Isključ.",
	"Often" : "Često",
	"Often_Int_OFF" : "Često",
	"OnDemand" : "Na zah.",
	"OnceAllDoors" : "Jednom: Sva vrata",
	"OnceDriversDoorTwiceAllDoors" : "Jedn.:Vozač.dva puta:Sva vrata",
	"Open" : "Otvori",
	"ParkingSensorIndication" : "Indikator parking senzora ",
	"ParkingSensorIndicator" : "Indikator parking senzora",
	"RVMBuzzerVolume" : "Rear Vehicle Monitoring Jač. zv.",
	"Rare" : "Retko",
	"Rare_Int_OFF" : "Retko",
	"Reset" : "Resetuj",
	"Rotation" : "Rotiranje",
	"RumbleStrips" : "Zv.tr.",
	"RumbleStrips_line" : "Zv.tr. ",
	"RumbleVolume" : "Jač. zvuka brujanja",
	"SBSReset" : "Da li ste sigurni da želite da vratite postavke Smart Brake Support (SBS) na fabrički podrazumevane vrednosti?",
	"SBSResetError" : "Greška pri promeni postavki Smart Brake Support (SBS). Da li želite da pokušate ponovo?",
	"SBSResetProgress" : "Promena postavki Smart Brake Support (SBS)",
	"SBSSCBS" : "SBS/SCBS",
	"SBS_SCBSReset" : "Da li ste sigurni da želite da vratite postavke SBS/SCBS na njihove fabrički podrazumevane vrednosti?",
	"SBS_SCBSResetError" : "Greška pri promeni SBS/SCBS postavki. Da li želite da pokušate ponovo?",
	"SBS_SCBSResetProgress" : "Promena SBS/SCBS postavki",
	"SCBS" : "Smart City Brake Support",
	"SCBSReset" : "Da li ste sigurni da želite da vratite postavke SCBS-a na njihove fabričke vrednosti?",
	"SCBSResetError" : "Postavke SCBS-a nije moguće vratiti na fabričke vrednosti. Želite li da probate ponovo?“",
	"SCBSResetProgress" : "Postavke SCBS-a se vraćaju",
	"SLC_Buzzer" : "Samo zvučni signal",
	"SLC_Off" : "Isključeno ",
	"SLC_Sign" : "Vizuelno",
	"SLC_Sign_Buzzer" : "Audio i vizuelni",
	"SLIReset" : "Da li ste sigurni da želite da podešavanja upozorenja na ograničenje brzine vratite na podrazumevane vrednosti?",
	"SLIResetError" : "Vraćanje podešavanja upozorenja na ograničenje brzine na fabričke vrednosti nije moguće. Da li želite da pokušate ponovo?",
	"SLIResetProgress" : "Vraćanje podešavanja upozorenja na ograničenje brzine",
	"SLI_HeadUpDisplay" : "Active Driving Display",
	"Safety" : "Bezbedn.",
	"Safetysettings" : "Bezb. postavke",
	"Sensitivity" : "Osetljivost",
	"Sensitivity_Intervention_OFF" : "Upozorenje ",
	"Setting" : "Podešavanja",
	"Settings" : "Postavke",
	"Short" : "Blizu",
	"SideView" : "Bočno",
	"SideViewFrontView" : "Bočno+napred",
	"SmartBrakeSupport" : "Smart Brake Support",
	"Sound" : "Zvuk",
	"SpeedAlarm" : "Upozorenje za brzinu",
	"SpeedLimitCaution" : "Obavešt. o ogranič. brzine",
	"SpeedLimitInformation" : "Upozorenje na ograničenje brzine",
	"SpeedLimitSign" : "Prikaz ograničenja brzine",
	"StepKilometers" : "{value} km/h",
	"StepMiles" : "{value} mph",
	"StreetInformation" : "Informacije o ulici",
	"Streetinfo_off" : "Isključeno",
	"System" : "Sistem",
	"TSRReset" : "Da li ste sigurni da želite da podešavanja sistema za prepoznavanje saobraćajnih znakova vratite na podrazumevane vrednosti?",
	"TSRResetError" : "Vraćanje podešavanja sistema za prepoznavanje saobraćajnih znakova na fabričke vrednosti nije moguće. Da li želite da pokušate ponovo?",
	"TSRResetProgress" : "Vraćanje podešavanja sistema za prepoznavanje saobraćajnih znakova",
	"TSR_Display" : "Prikaz saobraćajnog znaka",
	"TSR_System" : "Sistem za prepoznavanje saobraćajnih znakova",
	"Tachometer" : "Tahometar",
	"ThreeFlashTurnSignal" : "Signal skretanja sa 3 treptaja",
	"Timing" : "Podešavanje vremena",
	"Turn" : "Skretanje",
	"TurnProgress" : "Promena postavki za skretanje",
	"TurnReset" : "Da li ste sigurni da želite da vratite postavke za skretanje na fabrički podrazumevane vrednosti?",
	"TurnResetError" : "Greška kod menjanja postavki skretanja. Da li želite da pokušate ponovo?",
	"TurnSettings" : "Uključi",
	"TurnSignalIndicatorVolume" : "Jač.zv.sign.skretanja",
	"UnlockMode" : "Režim otključavanja",
	"Vehicle" : "Vozilo",
	"VehicleSettings" : "Postavke vozila",
	"Vibration" : "Vibracija",
	"VibrationStrength" : "Jačina vibracije",
	"Vibration_Line" : "Vibracija",
	"ViewSwitchDisplay" : "Podrazumevani prikaz",
	"ViewSwitchFunction" : "Funkcija promene pogleda",
	"Volume" : "Jačina zvuka",
	"WalkAwayLock" : "Zaključavanje pri udaljavanju od vozila",
	"Warning" : "Upozorenje",
	"WarningDistance" : "Distan.za upozor.",
	"_0s" : "0 s.",
	"_0seconds" : "0 sekundi",
	"_10m" : "10 min.",
	"_10minutes" : "10 minuta",
	"_120s" : "120 s",
	"_120seconds" : "120 sekundi",
	"_15s" : "15 s",
	"_15seconds" : "15 sekundi",
	"_30m" : "30 min.",
	"_30minutes" : "30 minuta",
	"_30s" : "30 s",
	"_30seconds" : "30 sekundi",
	"_60m" : "60 min.",
	"_60minutes" : "60 minuta",
	"_60s" : "60 s",
	"_60seconds" : "60 sekundi",
	"_7p5s" : "7.5 s",
	"_7p5seconds" : "7.5 sekundi",
	"_90s" : "90 s",
	"_90seconds" : "90 sekundi",
	"_AllDoors" : "Sve",
	"_Driver'sDoor" : "Vožač.",
	"on" : "Uklj.",
};

framework.registerAppDictLoaded("vehsettings", "sr_RS");