var Localization_vehsettingsAppDict_id_ID = {
	//"stringId" : "localString"
	"360ViewCamera" : "Monitor Tampilan 360°",
	"AHBC" : "Adaptive LED Headlights",
	"Adaptive" : "Adaptif",
	"AdaptiveFront-lightingSystem" : "Sistem Lampu Depan Adaptif",
	"AdaptiveLaneStreetTurn" : "Sistem Jalur/Jalan/Belokan Adaptif",
	"AlarmTiming" : "Kecepatan",
	"AlertTiming" : "Waktu Peringatan",
	"Always" : "Selalu",
	"AtLine" : "Pada Garis",
	"Auto" : "Otmts",
	"AutoHeadlightOn" : "Lampu Otomatis Hidup",
	"AutoWiper" : "Penyeka kaca dengan sensor hujan",
	"BSMBuzzerVolume" : "Blind Spot Monitoring Volume",
	"BSMReset" : "Anda yakin ingin mengembalikan setelan BSM ke default pabrik?",
	"BSMResetError" : "Tidak dapat mengembalikan setelan BSM ke default pabrik. Mau coba lagi?",
	"BSMResetProgress" : "Mengembalikan Setelan BSM",
	"BSMSystem" : "Sistem Pemantauan Titik Buta ",
	"Beep" : "Bunyi",
	"BeepVolume" : "Volume Bunyi",
	"Beep_Line" : "Bunyi",
	"BeforeLine" : "Sebelum Garis",
	"Brightness" : "Kecerahan",
	"BrightnessControl" : "Kontrol Kecerahan",
	"CHudNav_Maneuver" : "Di Maneuver",
	"CHudNav_Off" : "Mati",
	"CHudNav_TBT_Lane" : "Panduan & Belokan Jalur",
	"CHudNav_TBT_Street" : "Nama Jalan & Belokan",
	"Calibration" : "Kecerahan",
	"CautionSpeed" : "Ambang Batas Tanda",
	"CenterDisplay" : "Layar Tengah",
	"ChangingLASSettings" : "Mengubah pengaturan LAS",
	"Clock" : "Jam",
	"Close" : "Tutup",
	"ComingHomeLights" : "Coming Home Light",
	"ComingHomeLightsTimer" : "Coming Home Light",
	"DRSS" : "Distance Recognition Support System",
	"DRSSReset" : "Apakah Anda yakin ingin mengembalikan setelan Distance Recognition Support System ke setelan standar?",
	"DRSSResetError" : "Gagal mengubah Distance Recognition Support System. Apakah Anda ingin mencoba lagi?",
	"DRSSResetProgress" : "Mengubah Distance Recognition Support System",
	"Dark" : "Gelap",
	"DaytimeRunningLights" : "Lampu Siang",
	"Devices" : "Koneksi",
	"Display" : "Tampilan",
	"DisplayInformation" : "Informasi Tampilan",
	"DistanceRecognitionSupportSystem" : "Distance Recognition Support System",
	"DoorLock" : "Kunci Pintu",
	"DoorLockMode" : "Mode Kunci Pintu Otomatis",
	"DoorLockReset" : "Apakah Anda yakin ingin mengembalikan Setelan Kunci Pintu ke setelan standar?",
	"DoorLockResetError" : "Gagal mengubah Setelan Kunci Pintu. Apakah Anda ingin mencoba lagi?",
	"DoorLockResetProgress" : "Mengubah Setelan Kunci Pintu",
	"DoorRelockTime" : "Waktu Kunci Ulang Otomatis",
	"DriverAlert" : "Driver Attention Alert",
	"Early" : "Awal",
	"ErrorBSMSettings" : "Terjadi kesalahan saat mengganti setelan BSM Mau coba lagi?",
	"ErrorLASSettings" : "Eror saat mengubah Lane-keep Assist System. Ingin mencoba lagi?",
	"FOWReset" : "Apakah Anda yakin ingin mengembalikan Setelan Forward Obstruction Warning (FOW) ke setelan standar?",
	"FOWResetError" : "Gagal mengubah Setelan Forward Obstruction Warning System. Apakah Anda ingin mencoba lagi?",
	"FOWResetProgress" : "Mengubah setelan Forward Obstruction Warning",
	"Far" : "Jauh",
	"ForwardObstructionWarning" : "Forward Obstruction Warning",
	"FrontCameraView" : "Tampilan Kamera Depan",
	"GearShiftIndicator" : "Indikator Pemindahan Gigi",
	"GuidelineDisplay" : "Baris Jalur Dinamis",
	"HUD" : "AD-Disp",
	"HUDDisplayInfoError" : "Tidak dapat mengembalikan pengaturan Informasi Tampilan AD-Disp ke standar pabrik. Apakah Anda ingin mencoba ulang?",
	"HUDDisplayInfoReset" : "Anda yakin ingin mengembalikan pengaturan Informasi Tampilan AD-Disp ke setelan awal?",
	"HUDDisplayInfoResetProgress" : "Mengembalikan Pengaturan Informasi Tampilan AD-Disp",
	"HUDJ78AReset" : "Anda yakin ingin mengatur ulang setelan Active Driving Display ke nilai default?",
	"HUDJ78AResetError" : "Terjadi kesalahan saat mengatur ulang Setelan Active Driving Display. Anda ingin mencoba lagi?",
	"HUDJ78AResetProgress" : "Mengatur ulang Setelan Active Driving Display",
	"HUDJ78ATab" : "Active Driving Display",
	"HUDReset" : "Apakah Anda yakin ingin mengembalikan Active Driving Display ke setelan standar?",
	"HUDResetError" : "Gagal mengubah Setelan Active Driving Display. Apakah Anda ingin mencoba lagi?",
	"HUDResetProgress" : "Mengubah setelan Active Driving Display",
	"HUDSettings" : "Setelan AD-Disp",
	"HUD_HeadUpDisplay" : "Active Driving Display",
	"HeadUpDisplay" : "Active Driving Display",
	"HeadlightOffTimer" : "Pewaktu Lampu Utama Mati",
	"HeadlightOnWarning" : "Peringatan Lampu Utama Nyala",
	"HeadsUpDisplay" : "Active Driving Display",
	"Height" : "Keras",
	"High" : "Keras",
	"HighBeamControl" : "High Beam Control",
	"High_SensitivityLAS" : "Keras",
	"High_Vibration" : "Keras",
	"ILB_Bright" : "Kilau",
	"ILB_Dark" : "Dim",
	"ILB_Medium" : "Menengah",
	"ILB_Off" : "Mati ",
	"IgONAutoDisplay" : "Monitor Tampilan 360° dengan Layar Otomatis",
	"InterioLightsTimeOutDoorsClosed" : "Lampu Dalam Mati-Pintu Ditutup",
	"InterioLightsTimeOutDoorsOpen" : "Lampu Dalam Padam - Pintu Dibuka",
	"InteriorLightTimeoutDoorClosedTitle" : "Lampu Dalam Padam-Pintu Ditutup",
	"InteriorLightTimeoutDoorOpenTitle" : "Lampu Dalam Padam - Pintu Dibuka",
	"InteriorLightingBrightness" : "Lampu Ambien",
	"Intervention" : "Intervensi",
	"InterventionTiming" : "Waktu Intervensi",
	"KeylessLockBeepVol" : "Volume Bip Kunci Keyless",
	"Kilometers" : "km/jam",
	"LASAlert" : "Peringatan LAS",
	"LASDefaultValues" : "Anda yakin ingin mengembalikan pengaturan Lane-keep Assist System ke setelan standar?",
	"LASEarly" : "Awal",
	"LASLate" : "Telat",
	"LASSound" : "Jenis Peringatan",
	"LASTiming" : "Waktu LAS",
	"LDWSReset" : "Apakah Anda yakin ingin mengembalikan setelan Lane Departure Warning System, ke setelan standar?",
	"LDWSResetError" : "gagal mengubah setelan Lane Departure Warning System. Apakah Anda ingin mencoba lagi?",
	"LDWSResetProgress" : "Mengubah setelan Lane Departure Warning System",
	"LDWSTiming" : "Waktu LDWS",
	"LaneDepartureAlert" : "Peringatan Keluar Jalur",
	"LaneDepartureWarningSystem" : "Lane Departure Warning System",
	"LaneKeepAssistSystem" : "Lane-keep Assist System",
	"Late" : "Telat",
	"LeavingHomeLights" : "Leaving Home Light",
	"Light" : "Terang",
	"LightOnReminderVolume" : "Vol. alarm Lampu",
	"Lighting" : "Pencahayaan",
	"LightingReset" : "Apakah Anda ingin mengembalikan Setelan Penerangan ke setelan standar?",
	"LightingResetError" : "Gagal mengubah Setelan Penerangan. Apakah Anda ingin mencoba lagi?",
	"LightingResetProgress" : "Mengubah Setelan Lampu",
	"LockShiftFromP" : "Kunci: Pindah Dari P ",
	"LockShiftFromPUnlockInPark" : "Kunci: Pindah Dari P Buka: Pindah ke P",
	"LockUnlock" : "Kunci: Mengemudi Buka Kunci: Parkir",
	"LockWhenDriving" : "Kunci: Saat Berkendara",
	"LockWhenDrivingUnlockIGNoff" : "Kunci: Saat Berkendara Buka: IGN Mati",
	"Long" : "Jauh",
	"Low" : "Pelan",
	"Low_SensitivityLAS" : "Low",
	"Low_Vibration" : "Pelan",
	"Manual" : "Man.",
	"Med" : "Med",
	"Medium" : "Tengah",
	"MediumDark" : "Med Gel.",
	"MediumLight" : "Med Ter.",
	"Medium_Int_OFF" : "Med",
	"Medium_SensitivityLAS" : "Med",
	"Mid" : "Mid",
	"Middle" : "Sdg",
	"Miles" : "mph",
	"Mode" : "Mode",
	"Navigation" : "Navigasi",
	"NavigationSignal" : "Navigasi  ",
	"Near" : "Dekat",
	"Off" : "Mati",
	"Often" : "Sering",
	"Often_Int_OFF" : "Sering",
	"OnDemand" : "At Per.",
	"OnceAllDoors" : "Sekali: Semua Pintu",
	"OnceDriversDoorTwiceAllDoors" : "1 kali: Pintu Sopir 2 Kali: Semua Pintu",
	"Open" : "Buka",
	"ParkingSensorIndication" : "Indikasi Sensor Parkir ",
	"ParkingSensorIndicator" : "Indikator Sensor Parkir",
	"RVMBuzzerVolume" : "Rear Vehicle Monitoring Volume",
	"Rare" : "Jarang",
	"Rare_Int_OFF" : "Jarang",
	"Reset" : "Setel Ulang",
	"Rotation" : "Rotasi",
	"RumbleStrips" : "Gemetar",
	"RumbleStrips_line" : "Gemetar ",
	"RumbleVolume" : "Vol. Gemetar",
	"SBSReset" : "Apakah Anda yakin ingin mengembalikan Smart Brake Support System (SBS) ke setelan standar?",
	"SBSResetError" : "Gagal mengubah setelan Smart Brake Support System. Apakah Anda ingin mencoba lagi?",
	"SBSResetProgress" : "Mengubah setelan Smart Brake Support System",
	"SBSSCBS" : "SBS/SCBS",
	"SBS_SCBSReset" : "Apakah Anda yakin ingin mengembalikan Setelan SBS/SCBS ke setelan standar?",
	"SBS_SCBSResetError" : "Gagal mengubah Setelan SBS/SCBS. Apakah Anda ingin mencoba lagi?",
	"SBS_SCBSResetProgress" : "Mengubah Setelan SBS/SCBS",
	"SCBS" : "Smart City Brake Support",
	"SCBSReset" : "Anda yakin ingin mengembalikan pengaturan SCBS ke default pabrik?",
	"SCBSResetError" : "Tidak dapat mengembalikan setelan BSM ke default pabrik. Mau coba lagi?",
	"SCBSResetProgress" : "Mengembalikan setelan SCBS",
	"SLC_Buzzer" : "Hanya buzzer",
	"SLC_Off" : "Mati ",
	"SLC_Sign" : "Visual",
	"SLC_Sign_Buzzer" : "Audio & Visual",
	"SLIReset" : "Apakah Anda yakin Anda ingin mengembalikan pengaturan Peringatan Batas Kecepatan ke nilai standarnya?",
	"SLIResetError" : "Tidak dapat mengembalikan pengaturan Peringatan Batas Kecepatan ke standar pabrik. Apakah Anda ingin mencoba ulang?",
	"SLIResetProgress" : "Mengembalikan pengaturan Peringatan Batas Kecepatan",
	"SLI_HeadUpDisplay" : "Active Driving Display",
	"Safety" : "Keaman",
	"Safetysettings" : "Setelan Keselamatan",
	"Sensitivity" : "Sensitivitas",
	"Sensitivity_Intervention_OFF" : "Peringatan ",
	"Setting" : "Setelan",
	"Settings" : "Setelan",
	"Short" : "Dekat",
	"SideView" : "Samping",
	"SideViewFrontView" : "Samping+Depan",
	"SmartBrakeSupport" : "Smart Brake Support",
	"Sound" : "Suara",
	"SpeedAlarm" : "Alarm Kecep.",
	"SpeedLimitCaution" : "Tanda Batas Kecepatan",
	"SpeedLimitInformation" : "Peringatan Batas Kecepatan",
	"SpeedLimitSign" : "Tampilan Batas Kecepatan",
	"StepKilometers" : "{value} km/jam",
	"StepMiles" : "{value} mph",
	"StreetInformation" : "Informasi Jalan",
	"Streetinfo_off" : "Mati",
	"System" : "Sistem",
	"TSRReset" : "Apakah Anda yakin Anda ingin mengembalikan pengaturan  Sistem Pengenalan Rambu Lalu Lintas  ke nilai standarnya?",
	"TSRResetError" : "Tidak dapat mengembalikan pengaturan Sistem  Pengenalan Rambu Lalu Lintas ke standar pabrik. Mau coba lagi?",
	"TSRResetProgress" : "Mengembalikan pengaturan Sistem Pengenalan Rambu Lalu Lintas ",
	"TSR_Display" : "Layar Rambu Lalu Lintas",
	"TSR_System" : "Sistem Pengenalan Rambu Lalu Lintas",
	"Tachometer" : "Tachometer",
	"ThreeFlashTurnSignal" : "Sinyal Belok 3 kali nyala",
	"Timing" : "Pencatatan Waktu",
	"Turn" : "Belok",
	"TurnProgress" : "Mengubah Setelan Belok",
	"TurnReset" : "Apakah Anda yakin ingin mengembalikan Setelan Belok ke setelan standar?",
	"TurnResetError" : "Gagal mengubah Setelan Belok. Apakah Anda ingin mencoba lagi?",
	"TurnSettings" : "Belok",
	"TurnSignalIndicatorVolume" : "Volume Sinyal Belok",
	"UnlockMode" : "Mode Buka Kunci",
	"Vehicle" : "Kndraan",
	"VehicleSettings" : "Setelan Kendaraan",
	"Vibration" : "Vibrasi",
	"VibrationStrength" : "Kekuatan Vibrasi",
	"Vibration_Line" : "Vibrasi",
	"ViewSwitchDisplay" : "Tampilan Default",
	"ViewSwitchFunction" : "Lihat Fungsi Sakelar",
	"Volume" : "Volume",
	"WalkAwayLock" : "Kunci saat Berjalan Menjauh",
	"Warning" : "Peringatan",
	"WarningDistance" : "Panduan Jarak",
	"_0s" : "0 dtk",
	"_0seconds" : "0 detik",
	"_10m" : "10 mnt",
	"_10minutes" : "10 menit",
	"_120s" : "120 dtk",
	"_120seconds" : "120 detik",
	"_15s" : "15 dtk",
	"_15seconds" : "15 detik",
	"_30m" : "30 mnt",
	"_30minutes" : "30 menit",
	"_30s" : "30 dtk",
	"_30seconds" : "30 detik",
	"_60m" : "60 mnt",
	"_60minutes" : "60 menit",
	"_60s" : "60 dtk",
	"_60seconds" : "60 detik",
	"_7p5s" : "7.5 dtk",
	"_7p5seconds" : "7.5 dtk",
	"_90s" : "90 dtk",
	"_90seconds" : "90 detik",
	"_AllDoors" : "Semua",
	"_Driver'sDoor" : "Sopir",
	"on" : "Hidup",
};

framework.registerAppDictLoaded("vehsettings", "id_ID");