var Localization_vehsettingsAppDict_zh_CN = {
	//"stringId" : "localString"
	"360ViewCamera" : "360° 全角度显示",
	"AHBC" : "Adaptive LED Headlights",
	"Adaptive" : "自适应",
	"AdaptiveFront-lightingSystem" : "自适应前照灯系统",
	"AdaptiveLaneStreetTurn" : "自适应巷道/街道/转向",
	"AlarmTiming" : "速度设置",
	"AlertTiming" : "警告定时",
	"Always" : "一直",
	"AtLine" : "在线",
	"Auto" : "自动",
	"AutoHeadlightOn" : "自动大灯开启",
	"AutoWiper" : "感应式雨刷",
	"BSMBuzzerVolume" : "Blind Spot Monitoring 音量",
	"BSMReset" : "确定要将 BSM 设置恢复为出厂默认值？",
	"BSMResetError" : "无法将 BSM 设置恢复为出厂默认值。是否要重试？",
	"BSMResetProgress" : "恢复 BSM 设置",
	"BSMSystem" : "Blind Spot Monitoring 系统 ",
	"Beep" : "提示音",
	"BeepVolume" : "提示音音量",
	"Beep_Line" : "提示音",
	"BeforeLine" : "线前",
	"Brightness" : "亮度",
	"BrightnessControl" : "亮度控制",
	"CHudNav_Maneuver" : "机动",
	"CHudNav_Off" : "关闭",
	"CHudNav_TBT_Lane" : "车道与逐向导航",
	"CHudNav_TBT_Street" : "街名与逐向导航",
	"Calibration" : "亮度",
	"CautionSpeed" : "报警阈值",
	"CenterDisplay" : "中央显示器",
	"ChangingLASSettings" : "正在更改Lane-keep Assist System设置",
	"Clock" : "时钟",
	"Close" : "关闭",
	"ComingHomeLights" : "Coming Home Light",
	"ComingHomeLightsTimer" : "Coming Home Light",
	"DRSS" : "Distance Recognition Support System",
	"DRSSReset" : "您确定要将Distance Recognition Support System恢复为默认值吗？",
	"DRSSResetError" : "更改Distance Recognition Support System时出错。是否要重试？",
	"DRSSResetProgress" : "正在更改Distance Recognition Support System",
	"Dark" : "暗",
	"DaytimeRunningLights" : "日间行驶灯",
	"Devices" : "设备",
	"Display" : "显示",
	"DisplayInformation" : "显示信息",
	"DistanceRecognitionSupportSystem" : "Distance Recognition Support System",
	"DoorLock" : "车门锁",
	"DoorLockMode" : "自动落锁模式",
	"DoorLockReset" : "您确定要将车门锁设置恢复为默认值吗？",
	"DoorLockResetError" : "更改车门锁设置时出错。是否要重试？",
	"DoorLockResetProgress" : "正在更改车门锁设置",
	"DoorRelockTime" : "自动重锁时间",
	"DriverAlert" : "Driver Attention Alert",
	"Early" : "早",
	"ErrorBSMSettings" : "更改 BSM 设置错误。是否要重试？",
	"ErrorLASSettings" : "更改Lane-keep Assist System时出错。是否要重试？",
	"FOWReset" : "您确定要将Forward Obstruction Warning设置恢复为默认值吗？",
	"FOWResetError" : "更改Forward Obstruction Warning设置时出错。是否要重试？",
	"FOWResetProgress" : "正在更改Forward Obstruction Warning设置",
	"Far" : "远",
	"ForwardObstructionWarning" : "Forward Obstruction Warning",
	"FrontCameraView" : "前摄像头视图",
	"GearShiftIndicator" : "换档指示器",
	"GuidelineDisplay" : "动态路线",
	"HUD" : "AD-Disp",
	"HUDDisplayInfoError" : "无法将 AD-Disp 显示信息设置还原为出厂默认值。   是否要重试？",
	"HUDDisplayInfoReset" : "是否确定要将 AD-Disp 显示信息设置还原为其默认值？",
	"HUDDisplayInfoResetProgress" : "正在还原 AD-Disp 显示信息设置",
	"HUDJ78AReset" : "是否确定要将 Active Driving Display设置重置为默认值？",
	"HUDJ78AResetError" : "重置 Active Driving Display 设置时出现错误。 是否要重试？",
	"HUDJ78AResetProgress" : "正在重置 Active Driving Display 设置",
	"HUDJ78ATab" : "Active Driving Display",
	"HUDReset" : "您确定要将Active Driving Display设置恢复为默认值吗？",
	"HUDResetError" : "更改Active Driving Display设置时出错。是否要重试？",
	"HUDResetProgress" : "正在更改Active Driving Display设置",
	"HUDSettings" : "AD-Disp 设置",
	"HUD_HeadUpDisplay" : "Active Driving Display",
	"HeadUpDisplay" : "Active Driving Display",
	"HeadlightOffTimer" : "大灯关闭定时器",
	"HeadlightOnWarning" : "大灯开启警告",
	"HeadsUpDisplay" : "Active Driving Display",
	"Height" : "高度",
	"High" : "高",
	"HighBeamControl" : "High Beam Control",
	"High_SensitivityLAS" : "高",
	"High_Vibration" : "高",
	"ILB_Bright" : "明亮",
	"ILB_Dark" : "昏暗",
	"ILB_Medium" : "中等",
	"ILB_Off" : "关闭 ",
	"IgONAutoDisplay" : "自动显示 360° View Monitor",
	"InterioLightsTimeOutDoorsClosed" : "内饰灯超时 - 关上车门时",
	"InterioLightsTimeOutDoorsOpen" : "内饰灯超时 – 打开车门时",
	"InteriorLightTimeoutDoorClosedTitle" : "内饰灯超时 - 关上车门时",
	"InteriorLightTimeoutDoorOpenTitle" : "内饰灯超时 – 打开车门时",
	"InteriorLightingBrightness" : "环境照明",
	"Intervention" : "干预",
	"InterventionTiming" : "干预定时",
	"KeylessLockBeepVol" : "无钥匙锁车提示音音量",
	"Kilometers" : "km/h",
	"LASAlert" : "LAS 警告",
	"LASDefaultValues" : "您确定要将Lane-keep Assist System设置恢复为默认值吗？",
	"LASEarly" : "早",
	"LASLate" : "晚",
	"LASSound" : "报警类型",
	"LASTiming" : "LAS定时",
	"LDWSReset" : "您确定要将Lane Departure Warning System设置恢复为默认值吗？",
	"LDWSResetError" : "更改Lane Departure Warning System设置时出错。是否要重试？",
	"LDWSResetProgress" : "正在更改Lane Departure Warning System设置",
	"LDWSTiming" : "LDWS定时",
	"LaneDepartureAlert" : "车道偏离警告",
	"LaneDepartureWarningSystem" : "Lane Departure Warning System",
	"LaneKeepAssistSystem" : "Lane-keep Assist System",
	"Late" : "晚",
	"LeavingHomeLights" : "Leaving Home Light",
	"Light" : "亮",
	"LightOnReminderVolume" : "亮灯提醒器音量",
	"Lighting" : "照明",
	"LightingReset" : "您确定要将照明设置恢复为默认值吗？",
	"LightingResetError" : "更改照明设置时出错。是否要重试？",
	"LightingResetProgress" : "正在更改照明设置",
	"LockShiftFromP" : "锁定：换出驻车档 ",
	"LockShiftFromPUnlockInPark" : "锁定：换出驻车档 解锁：驻车状态",
	"LockUnlock" : "锁定：行驶时 解锁：驻车状态",
	"LockWhenDriving" : "锁定：行驶时",
	"LockWhenDrivingUnlockIGNoff" : "锁定：行驶时解锁：IGN关闭",
	"Long" : "远",
	"Low" : "低",
	"Low_SensitivityLAS" : "低",
	"Low_Vibration" : "低",
	"Manual" : "手动",
	"Med" : "中等",
	"Medium" : "中",
	"MediumDark" : "中等暗度",
	"MediumLight" : "中等亮度",
	"Medium_Int_OFF" : "中等",
	"Medium_SensitivityLAS" : "中等",
	"Mid" : "中",
	"Middle" : "中间",
	"Miles" : "mph",
	"Mode" : "模式",
	"Navigation" : "导航",
	"NavigationSignal" : "导航  ",
	"Near" : "近",
	"Off" : "关闭",
	"Often" : "经常",
	"Often_Int_OFF" : "经常",
	"OnDemand" : "按需",
	"OnceAllDoors" : "一次：所有车门",
	"OnceDriversDoorTwiceAllDoors" : "一次：驾驶员侧车门， 两次：所有车门",
	"Open" : "打开",
	"ParkingSensorIndication" : "驻车传感器指示 ",
	"ParkingSensorIndicator" : "驻车传感器指示器",
	"RVMBuzzerVolume" : "Rear Vehicle Monitoring 音量",
	"Rare" : "很少",
	"Rare_Int_OFF" : "很少",
	"Reset" : "复位",
	"Rotation" : "旋转",
	"RumbleStrips" : "振带",
	"RumbleStrips_line" : "振带 ",
	"RumbleVolume" : "振带音量",
	"SBSReset" : "您确定要将Smart Brake Support设置恢复为默认值吗？",
	"SBSResetError" : "更改Smart Brake Support设置时出错。是否要重试？",
	"SBSResetProgress" : "正在更改Smart Brake Support设置",
	"SBSSCBS" : "SBS/SCBS",
	"SBS_SCBSReset" : "您确定要将SBS/SCBS设置恢复为默认值吗？",
	"SBS_SCBSResetError" : "更改SBS/SCBS设置时出错。是否要重试？",
	"SBS_SCBSResetProgress" : "正在更改 SBS/SCBS 设置",
	"SCBS" : "Smart City Brake Support",
	"SCBSReset" : "确定要将 SCBS 设置恢复为出厂默认值？",
	"SCBSResetError" : "无法将 SCBS 设置恢复为出厂默认值。是否要重试？",
	"SCBSResetProgress" : "恢复 SCBS 设置",
	"SLC_Buzzer" : "仅蜂鸣声",
	"SLC_Off" : "关闭 ",
	"SLC_Sign" : "视觉",
	"SLC_Sign_Buzzer" : "音频+视觉",
	"SLIReset" : "确定要将限速警告设置恢复为默认值？",
	"SLIResetError" : "无法将限速警告设置恢复为出厂默认值。是否要重试？",
	"SLIResetProgress" : "恢复限速警告设置",
	"SLI_HeadUpDisplay" : "Active Driving Display",
	"Safety" : "安全",
	"Safetysettings" : "安全设置",
	"Sensitivity" : "敏感度",
	"Sensitivity_Intervention_OFF" : "警告 ",
	"Setting" : "设置",
	"Settings" : "设置",
	"Short" : "近",
	"SideView" : "侧面",
	"SideViewFrontView" : "侧面+正面",
	"SmartBrakeSupport" : "Smart Brake Support",
	"Sound" : "声音",
	"SpeedAlarm" : "超速警报",
	"SpeedLimitCaution" : "限速报警",
	"SpeedLimitInformation" : "限速警告",
	"SpeedLimitSign" : "限速显示",
	"StepKilometers" : "{value} km/h",
	"StepMiles" : "{value} mph",
	"StreetInformation" : "街道信息",
	"Streetinfo_off" : "关闭",
	"System" : "系统",
	"TSRReset" : "确定要将交通信号识别系统设置恢复为默认值？",
	"TSRResetError" : "无法将交通信号识别系统设置恢复为出厂默认值。是否要重试？",
	"TSRResetProgress" : "恢复交通信号识别系统设置",
	"TSR_Display" : "交通信号显示",
	"TSR_System" : "交通信号识别系统",
	"Tachometer" : "转速表",
	"ThreeFlashTurnSignal" : "三次闪灯转向信号",
	"Timing" : "定时",
	"Turn" : "转向",
	"TurnProgress" : "正在更改转向设置",
	"TurnReset" : "您确定要将转向设置恢复为默认值吗？",
	"TurnResetError" : "更改转向设置时出错。是否要重试？",
	"TurnSettings" : "转向",
	"TurnSignalIndicatorVolume" : "转向信号音量",
	"UnlockMode" : "解锁模式",
	"Vehicle" : "车辆",
	"VehicleSettings" : "车辆设置",
	"Vibration" : "振动",
	"VibrationStrength" : "振动强度",
	"Vibration_Line" : "振动",
	"ViewSwitchDisplay" : "默认视图",
	"ViewSwitchFunction" : "视图切换功能",
	"Volume" : "音量",
	"WalkAwayLock" : "离车车锁",
	"Warning" : "警告",
	"WarningDistance" : "警告距离",
	"_0s" : "0 秒",
	"_0seconds" : "0 秒",
	"_10m" : "10 分钟",
	"_10minutes" : "10分钟",
	"_120s" : "120 秒",
	"_120seconds" : "120秒",
	"_15s" : "15 秒",
	"_15seconds" : "15秒",
	"_30m" : "30 分钟",
	"_30minutes" : "30分钟",
	"_30s" : "30 秒",
	"_30seconds" : "30秒",
	"_60m" : "60 分钟",
	"_60minutes" : "60分钟",
	"_60s" : "60 秒",
	"_60seconds" : "60秒",
	"_7p5s" : "7.5 秒",
	"_7p5seconds" : "7.5秒",
	"_90s" : "90 秒",
	"_90seconds" : "90秒",
	"_AllDoors" : "全部",
	"_Driver'sDoor" : "驾驶员",
	"on" : "打开",
};

framework.registerAppDictLoaded("vehsettings", "zh_CN");