var Localization_vehsettingsAppDict_it_IT = {
	//"stringId" : "localString"
	"360ViewCamera" : "Monitor visualiz 360°",
	"AHBC" : "Adaptive LED Headlights",
	"Adaptive" : "Adattivo",
	"AdaptiveFront-lightingSystem" : "Sistema luci anteriori adattive",
	"AdaptiveLaneStreetTurn" : "Corsia/Strada/Direzione adattiva",
	"AlarmTiming" : "Velocità",
	"AlertTiming" : "Momento Avviso",
	"Always" : "Sempre",
	"AtLine" : "InLinea",
	"Auto" : "Auto",
	"AutoHeadlightOn" : "Modalità fari accesi automatica",
	"AutoWiper" : "Tergicristallo con sensore per pioggia",
	"BSMBuzzerVolume" : "Blind Spot Monitoring Volume",
	"BSMReset" : "Ritornare alle impostazioni BSM predefinite di fabbrica?",
	"BSMResetError" : "Errore nel riportare le impostazioni BSM ai valori di fabbrica. Riprovare?",
	"BSMResetProgress" : "Ripristino delle impost. BSM ai valori di fabbrica",
	"BSMSystem" : "Sistema Blind Spot Monitoring ",
	"Beep" : "Beep",
	"BeepVolume" : "Volume Beep",
	"Beep_Line" : "Beep",
	"BeforeLine" : "Prima",
	"Brightness" : "Luminosità",
	"BrightnessControl" : "Controllo luminosità",
	"CHudNav_Maneuver" : "Manovra",
	"CHudNav_Off" : "Spenta",
	"CHudNav_TBT_Lane" : "Corsia ",
	"CHudNav_TBT_Street" : "Nom str.",
	"Calibration" : "Luminosità",
	"CautionSpeed" : "Soglia di avviso",
	"CenterDisplay" : "Display centrale",
	"ChangingLASSettings" : "Modifica impostazioni LAS",
	"Clock" : "Orologio",
	"Close" : "Chiudi",
	"ComingHomeLights" : "Coming Home Light",
	"ComingHomeLightsTimer" : "Coming Home Light",
	"DRSS" : "Distance Recognition Support System",
	"DRSSReset" : "Riportare le impostazioni Distance Recognition Support System (DRSS) ai valori predefiniti?",
	"DRSSResetError" : "Errore nella variazione del Distance Recognition Support System (DRSS). Riprovare?",
	"DRSSResetProgress" : "Variazione  Distance Recognition Support System (DRSS)",
	"Dark" : "Scuro",
	"DaytimeRunningLights" : "Luci diurne",
	"Devices" : "Dispositi.",
	"Display" : "Display",
	"DisplayInformation" : "Informazioni sul display",
	"DistanceRecognitionSupportSystem" : "Distance Recognition Support System",
	"DoorLock" : "Chiusura porte",
	"DoorLockMode" : "Modalità porte chiuse automatica",
	"DoorLockReset" : "Riportare le impostazioni dell'attivazione 3 lampeggi automatici dell'indicatore di direzione ai valori predefiniti?",
	"DoorLockResetError" : "Errore nel cambio delle impostazioni chiusura portiere. Riprovare?",
	"DoorLockResetProgress" : "Cambio impostazioni chiusura portiere",
	"DoorRelockTime" : "Tempo nuova chiusura automatica",
	"DriverAlert" : "Driver Attention Alert",
	"Early" : "Presto",
	"ErrorBSMSettings" : "Errore nella modifica delle impostazioni BSM. Riprovare?",
	"ErrorLASSettings" : "Errore nella modifica di Lane-keep Assist System. Riprovare?",
	"FOWReset" : "Riportare le impostazioni Forward Obstruction Warning (FOW) ai valori predefiniti?",
	"FOWResetError" : "Errore nel cambio delle impostazioni Forward Obstruction Warning (FOW). Riprovare?",
	"FOWResetProgress" : "Cambio impostazioni Forward Obstruction Warning (FOW)",
	"Far" : "Lonta",
	"ForwardObstructionWarning" : "Forward Obstruction Warning",
	"FrontCameraView" : "Visuale telecamera frontale",
	"GearShiftIndicator" : "Indicatore di cambio marcia",
	"GuidelineDisplay" : "Linee percorso dinamiche",
	"HUD" : "AD-Disp",
	"HUDDisplayInfoError" : "Impossibile ripristinare le impostazioni delle informazioni del display AD-Disp ai valori predefiniti di fabbrica. Riprovare?",
	"HUDDisplayInfoReset" : "Ripristinare le impostazioni delle informazioni del display AD-Disp ai valori predefiniti?",
	"HUDDisplayInfoResetProgress" : "Ripristino delle impostazioni delle informazioni del display AD-Disp",
	"HUDJ78AReset" : "Ripristinare le impostazioni Active Driving Display ai valori predefiniti?",
	"HUDJ78AResetError" : "Si è verificato un errore durante il ripristino delle Impostazioni Active Driving Display. Riprovare?",
	"HUDJ78AResetProgress" : "Ripristino delle Impostazioni Active Driving Display",
	"HUDJ78ATab" : "Active Driving Display",
	"HUDReset" : "Riportare le impostazioni Active Driving Display ai valori predefiniti?",
	"HUDResetError" : "Errore nel cambio delle impostazioni Active Driving Display. Riprovare?",
	"HUDResetProgress" : "Cambio impostaz Active Driving Display",
	"HUDSettings" : "Impostazioni AD-Disp",
	"HUD_HeadUpDisplay" : "Active Driving Display",
	"HeadUpDisplay" : "Active Driving Display",
	"HeadlightOffTimer" : "Timer spegnimento fari",
	"HeadlightOnWarning" : "Avviso fari accesi",
	"HeadsUpDisplay" : "Active Driving Display",
	"Height" : "Altezza",
	"High" : "Alto",
	"HighBeamControl" : "High Beam Control",
	"High_SensitivityLAS" : "Alto",
	"High_Vibration" : "Alto",
	"ILB_Bright" : "Luminoso",
	"ILB_Dark" : "Soffusa",
	"ILB_Medium" : "Media",
	"ILB_Off" : "Spenta ",
	"IgONAutoDisplay" : "Vis. Auto. 360° View Monitor",
	"InterioLightsTimeOutDoorsClosed" : "Timeout luci interne:Porte chiuse",
	"InterioLightsTimeOutDoorsOpen" : "Timeout luci interne:Porte aperte",
	"InteriorLightTimeoutDoorClosedTitle" : "Timeout luci interne: Portiere chiuse",
	"InteriorLightTimeoutDoorOpenTitle" : "Timeout luci interne:Porte aperte",
	"InteriorLightingBrightness" : "Illuminazione ambientale",
	"Intervention" : "Intervento",
	"InterventionTiming" : "Momento Intervento",
	"KeylessLockBeepVol" : "Vol segnale chiusura senza chiavi",
	"Kilometers" : "km/h",
	"LASAlert" : "Allerta LAS",
	"LASDefaultValues" : "Riportare le impostazioni di Lane-keep Assist System ai valori predefiniti?",
	"LASEarly" : "Presto",
	"LASLate" : "Tardi",
	"LASSound" : "Tipo di Avviso",
	"LASTiming" : "Tempo LAS",
	"LDWSReset" : "Riportare le impostazioni Lane Departure Warning System (LDWS) ai valori predefiniti?",
	"LDWSResetError" : "Errore nella modifica delle impostazioni Lane Departure Warning System (LDWS). Riprovare?",
	"LDWSResetProgress" : "Modifica impostazioni Lane Departure Warning System (LDWS)",
	"LDWSTiming" : "Tempo LDWS",
	"LaneDepartureAlert" : "Avviso di Abbandono Corsia",
	"LaneDepartureWarningSystem" : "Lane Departure Warning System",
	"LaneKeepAssistSystem" : "Lane-keep Assist System",
	"Late" : "Tardi",
	"LeavingHomeLights" : "Leaving Home Light",
	"Light" : "Luce",
	"LightOnReminderVolume" : "Volume luci accese",
	"Lighting" : "Luci",
	"LightingReset" : "Riportare le impostazioni delle luci ai loro valori predefiniti?",
	"LightingResetError" : "Errore nel cambio impostazioni luci. Riprovare?",
	"LightingResetProgress" : "Cambio impostazioni luci",
	"LockShiftFromP" : "Blocco: spostare non su Park (P) ",
	"LockShiftFromPUnlockInPark" : "Blocco: Non su Park Sblocco: Su Park",
	"LockUnlock" : "Blocco: se alla guida Sblocco: su Park",
	"LockWhenDriving" : "Blocco: Se alla guida",
	"LockWhenDrivingUnlockIGNoff" : "Blocco: se alla guida Sblocco: IGN off",
	"Long" : "Lonta",
	"Low" : "Basso",
	"Low_SensitivityLAS" : "Basso",
	"Low_Vibration" : "Basso",
	"Manual" : "Manu",
	"Med" : "Medio",
	"Medium" : "Medio",
	"MediumDark" : "Buio med",
	"MediumLight" : "Luce med",
	"Medium_Int_OFF" : "Medio",
	"Medium_SensitivityLAS" : "Medio",
	"Mid" : "Medio",
	"Middle" : "Medio",
	"Miles" : "mph",
	"Mode" : "Modalità",
	"Navigation" : "Navigazione",
	"NavigationSignal" : "Navigazione  ",
	"Near" : "Vicino",
	"Off" : "Off",
	"Often" : "Spesso",
	"Often_Int_OFF" : "Spesso",
	"OnDemand" : "Su ric.",
	"OnceAllDoors" : "Una volta: tutte le portiere",
	"OnceDriversDoorTwiceAllDoors" : "1 volta: per conducente 2: Ogni porta",
	"Open" : "Apri",
	"ParkingSensorIndication" : "Indicazione sensore parcheggio ",
	"ParkingSensorIndicator" : "Indicatore sensore parcheggio",
	"RVMBuzzerVolume" : "Rear Vehicle Monitoring Volume",
	"Rare" : "Raro",
	"Rare_Int_OFF" : "Raro",
	"Reset" : "Resetta",
	"Rotation" : "Rotazione",
	"RumbleStrips" : "Rum.",
	"RumbleStrips_line" : "Rum. ",
	"RumbleVolume" : "Vol. banda sonora",
	"SBSReset" : "Riportare le impostazioni Smart Brake Support (SBS) ai valori predefiniti?",
	"SBSResetError" : "Errore nel cambio delle impostazioni Smart Brake Support (SBS). Riprovare?",
	"SBSResetProgress" : "Cambio impostazioni Smart Brake Support (SBS)",
	"SBSSCBS" : "SBS/SCBS",
	"SBS_SCBSReset" : "Riportare le impostazioni SBS/SCBS ai valori predefiniti?",
	"SBS_SCBSResetError" : "Errore nel cambio delle impostazioni SBS/SCBS. Riprovare?",
	"SBS_SCBSResetProgress" : "Cambio impostazioni SBS/SCBS",
	"SCBS" : "Smart City Brake Support",
	"SCBSReset" : "Ritornare alle impostazioni SCBS predefinite di fabbrica?\"",
	"SCBSResetError" : "Errore nel riportare le impostazioni SCBS ai valori di fabbrica. Riprovare?\"",
	"SCBSResetProgress" : "Ripristino impostazioni SCBS",
	"SLC_Buzzer" : "Solo segnale acustico",
	"SLC_Off" : "Spenta ",
	"SLC_Sign" : "Visivo",
	"SLC_Sign_Buzzer" : "Audiovisivo",
	"SLIReset" : "Ripristinare le impostazioni di avvertenza del limite di velocità ai valori predefiniti?",
	"SLIResetError" : "Impossibile ripristinare le impostazioni di avvertenza del limite di velocità ai valori predefiniti di fabbrica. Riprovare?",
	"SLIResetProgress" : "Ripristino delle impostazioni di avvertenza del limite di velocità",
	"SLI_HeadUpDisplay" : "Active Driving Display",
	"Safety" : "Sicurezza",
	"Safetysettings" : "Impostazioni sicurezza",
	"Sensitivity" : "Sensibilità",
	"Sensitivity_Intervention_OFF" : "Attenzione ",
	"Setting" : "Impostazioni",
	"Settings" : "Impostazioni",
	"Short" : "Vicino",
	"SideView" : "Laterale",
	"SideViewFrontView" : "Laterale+Frontale",
	"SmartBrakeSupport" : "Smart Brake Support",
	"Sound" : "Audio",
	"SpeedAlarm" : "Allarme velocità",
	"SpeedLimitCaution" : "Avviso limite di velocità",
	"SpeedLimitInformation" : "Avvertenza limite di velocità",
	"SpeedLimitSign" : "Visualizzazione limite di velocità",
	"StepKilometers" : "{value} km/h",
	"StepMiles" : "{value} mph",
	"StreetInformation" : "Informazioni stradali",
	"Streetinfo_off" : "Spenta",
	"System" : "Sistema",
	"TSRReset" : "Ripristinare le impostazioni del sistema di riconoscimento dei segnali stradali ai valori predefiniti?",
	"TSRResetError" : "Impossibile ripristinare le impostazioni del sistema di riconoscimento dei segnali stradali ai valori predefiniti di fabbrica. Riprovare?",
	"TSRResetProgress" : "Ripristino delle impostazioni del sistema di riconoscimento dei segnali stradali ",
	"TSR_Display" : "Visualizzazione segnali stradali",
	"TSR_System" : "Sistema di riconoscimento dei segnali stradali",
	"Tachometer" : "Tachimetro",
	"ThreeFlashTurnSignal" : "Freccia 3-flash",
	"Timing" : "Timing",
	"Turn" : "Gira",
	"TurnProgress" : "Cambio impostazioni virata",
	"TurnReset" : "Riportare le impostazioni attivazione automatica 3 lampeggi indicatori di direzione ai valori predefiniti?",
	"TurnResetError" : "Errore nel cambio delle impostazioni dell'attivazione 3 lampeggi automatici dell'indicatore di direzione",
	"TurnSettings" : "Gira",
	"TurnSignalIndicatorVolume" : "Volume freccia",
	"UnlockMode" : "Modalità sbloccato",
	"Vehicle" : "Veicolo",
	"VehicleSettings" : "Impostazioni veicolo",
	"Vibration" : "Vibrazione",
	"VibrationStrength" : "Intensità Vibrazione",
	"Vibration_Line" : "Vibrazione",
	"ViewSwitchDisplay" : "Visualizzazione predefinita",
	"ViewSwitchFunction" : "Funzione modifica visualizzazione",
	"Volume" : "Volume",
	"WalkAwayLock" : "Chiusura automatica",
	"Warning" : "Attenzione",
	"WarningDistance" : "Avviso distanza",
	"_0s" : "0 s",
	"_0seconds" : "0 secondi",
	"_10m" : "10 min",
	"_10minutes" : "10 minuti",
	"_120s" : "120 s",
	"_120seconds" : "120 secondi",
	"_15s" : "15 s",
	"_15seconds" : "15 secondi",
	"_30m" : "30 min",
	"_30minutes" : "30 minuti",
	"_30s" : "30 s",
	"_30seconds" : "30 secondi",
	"_60m" : "60 min",
	"_60minutes" : "60 minuti",
	"_60s" : "60 s",
	"_60seconds" : "60 secondi",
	"_7p5s" : "7.5 s",
	"_7p5seconds" : "7.5 secondi",
	"_90s" : "90 s",
	"_90seconds" : "90 secondi",
	"_AllDoors" : "Tutte",
	"_Driver'sDoor" : "Conduc.",
	"on" : "On",
};

framework.registerAppDictLoaded("vehsettings", "it_IT");