var Localization_vehsettingsAppDict_cs_CS = {
	//"stringId" : "localString"
	"360ViewCamera" : "360° monitor",
	"AHBC" : "Adaptive LED Headlights",
	"Adaptive" : "Adaptivní",
	"AdaptiveFront-lightingSystem" : "Adaptivních světlometů",
	"AdaptiveLaneStreetTurn" : "Adaptivní jízdní pruhy / ulice / odbočování",
	"AlarmTiming" : "Rychlosti",
	"AlertTiming" : "Časování upozornění",
	"Always" : "Vždy",
	"AtLine" : "Na ř.",
	"Auto" : "Auto",
	"AutoHeadlightOn" : "Automatické zapínání světlometů",
	"AutoWiper" : "Dešťový snímač stěračů",
	"BSMBuzzerVolume" : "Blind Spot Monitoring Hlasitost",
	"BSMReset" : "Opravdu chcete obnovit výchozí nastavení BSM?",
	"BSMResetError" : "Výchozí nastavení BSM nelze obnovit. Chcete to zkusit znovu?",
	"BSMResetProgress" : "Obnovování nastavení BSM",
	"BSMSystem" : "Systém Blind Spot Monitoring ",
	"Beep" : "Pípnutí",
	"BeepVolume" : "Hlasitost pípnutí",
	"Beep_Line" : "Pípnutí",
	"BeforeLine" : "Př. ř.",
	"Brightness" : "Jas",
	"BrightnessControl" : "Regulace jasu",
	"CHudNav_Maneuver" : "Při man.",
	"CHudNav_Off" : "Vypnuto",
	"CHudNav_TBT_Lane" : "Jízd.pr.",
	"CHudNav_TBT_Street" : "Náz.ul.",
	"Calibration" : "Jas",
	"CautionSpeed" : "Prahová hodnota upozornění",
	"CenterDisplay" : "Prostřední displej",
	"ChangingLASSettings" : "Změna nast. Lane-keep Assist System",
	"Clock" : "Hodiny",
	"Close" : "Zavřít",
	"ComingHomeLights" : "Coming Home Light",
	"ComingHomeLightsTimer" : "Coming Home Light",
	"DRSS" : "Distance Recognition Support System",
	"DRSSReset" : "Opravdu chcete vrátit Distance Recognition Support System (DRSS)? Chcete vše nastavit na původní hodnoty?",
	"DRSSResetError" : "Při změně způsobu Distance Recognition Support System (DRSS). Zkusit znovu?",
	"DRSSResetProgress" : "Změna Distance Recognition Support System (DRSS)",
	"Dark" : "Tma",
	"DaytimeRunningLights" : "Denní světla",
	"Devices" : "Zařízení",
	"Display" : "Displej",
	"DisplayInformation" : "Zobrazit informace",
	"DistanceRecognitionSupportSystem" : "Distance Recognition Support System",
	"DoorLock" : "Zámek dveří",
	"DoorLockMode" : "Automatické zamykání dveří",
	"DoorLockReset" : "Opravdu chcete vrátit výchozí nastavení zámků dveří?",
	"DoorLockResetError" : "Chyba při změně nastavení zámků dveří. Zkusit znovu?",
	"DoorLockResetProgress" : "Změna nastavení zamykání dveří",
	"DoorRelockTime" : "Čas automatiky zamykání",
	"DriverAlert" : "Driver Attention Alert",
	"Early" : "Brzo",
	"ErrorBSMSettings" : "Při změně nastavení BSM došlo k chybě. Chcete to zkusit znovu?",
	"ErrorLASSettings" : "Chyba při změně systému Lane-keep Assist System. Opakovat?",
	"FOWReset" : "Opravdu chcete vrátit výchozí nastavení Forward Obstruction Warning (FOW)?",
	"FOWResetError" : "Při změně nastavení Forward Obstruction Warning (FOW) došlo k chybě. Zkusit znovu?",
	"FOWResetProgress" : "Změna Forward Obstruction Warning překáž.",
	"Far" : "Vzdál.",
	"ForwardObstructionWarning" : "Forward Obstruction Warning",
	"FrontCameraView" : "Pohled z přední kamery",
	"GearShiftIndicator" : "Ukazatel řazení",
	"GuidelineDisplay" : "Dynamické směrové čáry",
	"HUD" : "AD-Disp",
	"HUDDisplayInfoError" : "Nastavení informací o zobrazení AD-Disp na výchozí hodnotu nelze provést. Chcete to zkusit znovu?",
	"HUDDisplayInfoReset" : "Opravdu si přejete obnovit nastavení informací o zobrazení AD-Disp na výchozí hodnotu?",
	"HUDDisplayInfoResetProgress" : "Obnovuji nastavení informací o zobrazení AD-Disp",
	"HUDJ78AReset" : "Opravdu chcete resetovat nastavení displeje Active Driving Display na výchozí hodnoty?",
	"HUDJ78AResetError" : "Při resetování nastavení displeje Active Driving Display došlo k chybě. Chcete to zkusit znovu?",
	"HUDJ78AResetProgress" : "Probíhá resetování nastavení displeje Active Driving Display",
	"HUDJ78ATab" : "Active Driving Display",
	"HUDReset" : "Opravdu chcete vrátit výchozí nastavení  Active Driving Display?",
	"HUDResetError" : "Chyba při změně nastavení Active Driving Display. Zkusit znovu?",
	"HUDResetProgress" : "Změna nastavení Active Driving Display.",
	"HUDSettings" : "Nastavení displeje AD-Disp",
	"HUD_HeadUpDisplay" : "Active Driving Display",
	"HeadUpDisplay" : "Active Driving Display",
	"HeadlightOffTimer" : "Časovač vypnutí světlometů",
	"HeadlightOnWarning" : "Upozor.reflektor",
	"HeadsUpDisplay" : "Active Driving Display",
	"Height" : "Výška",
	"High" : "Vys.",
	"HighBeamControl" : "High Beam Control",
	"High_SensitivityLAS" : "Vys.",
	"High_Vibration" : "Vys.",
	"ILB_Bright" : "Jasné",
	"ILB_Dark" : "Tlumené",
	"ILB_Medium" : "Střední",
	"ILB_Off" : "Vypnuto ",
	"IgONAutoDisplay" : "Autom. zobraz. funkci 360° View Monitor",
	"InterioLightsTimeOutDoorsClosed" : "Čas.lim.vnitř.osvět. - zavř. dveře",
	"InterioLightsTimeOutDoorsOpen" : "Čas.lim.vnitř.osvět. - otevř. dveře",
	"InteriorLightTimeoutDoorClosedTitle" : "Čas.lim.vnitř.osvět. - zavř. dveře",
	"InteriorLightTimeoutDoorOpenTitle" : "Čas.lim.vnitř.osvět. - otevř. dveře",
	"InteriorLightingBrightness" : "Okolní osvětlení",
	"Intervention" : "Zásah",
	"InterventionTiming" : "Časování zásahu",
	"KeylessLockBeepVol" : "Hlasitost signálu zamknutí",
	"Kilometers" : "km/h",
	"LASAlert" : "Upozornění LAS",
	"LASDefaultValues" : "Opravdu chcete vrátit nastavení systému Lane-keep Assist System na výchozí hodnoty?",
	"LASEarly" : "Brzo",
	"LASLate" : "Poslední",
	"LASSound" : "Typ upozornění",
	"LASTiming" : "Časování LAS",
	"LDWSReset" : "Opravdu chcete vrátit výchozí nastavení  Lane Departure Warning System (LDWS)?",
	"LDWSResetError" : "Chyba při změně nastavení Lane Departure Warning System (LDWS). Zkusit znovu?",
	"LDWSResetProgress" : "Změna nastav.  Lane Departure Warning System (LDWS)",
	"LDWSTiming" : "Časování LDWS",
	"LaneDepartureAlert" : "Upoz. před opuštěním pruhu",
	"LaneDepartureWarningSystem" : "Lane Departure Warning System",
	"LaneKeepAssistSystem" : "Lane-keep Assist System",
	"Late" : "Poslední",
	"LeavingHomeLights" : "Leaving Home Light",
	"Light" : "Světlý",
	"LightOnReminderVolume" : "Hlas.roz.světel",
	"Lighting" : "Osvětlení",
	"LightingReset" : "Opravdu chcete vrátit výchozí nastavení osvětlení?",
	"LightingResetError" : "Při změně nastavení osvětlení došlo k chybě. Zkusit znovu?",
	"LightingResetProgress" : "Změna nastavení osvětlení",
	"LockShiftFromP" : "Blokování: vyřazení z polohy Park ",
	"LockShiftFromPUnlockInPark" : "Blok:vyřaz.z polohy park odbl.:při Park",
	"LockUnlock" : "Zamč.: za jízdy; odem.: při parkování",
	"LockWhenDriving" : "Blokování: za jízdy",
	"LockWhenDrivingUnlockIGNoff" : "Blok:za jízdy odbl.: vypnutí zapal.",
	"Long" : "Daleko",
	"Low" : "Nízký",
	"Low_SensitivityLAS" : "Nízký",
	"Low_Vibration" : "Nízká",
	"Manual" : "Ruční",
	"Med" : "Stř.",
	"Medium" : "Střední",
	"MediumDark" : "Stř.Tma",
	"MediumLight" : "Stř.světlý",
	"Medium_Int_OFF" : "Stř.",
	"Medium_SensitivityLAS" : "Stř.",
	"Mid" : "Střed.",
	"Middle" : "Střed.",
	"Miles" : "mi/h",
	"Mode" : "Režim",
	"Navigation" : "Navigace",
	"NavigationSignal" : "Navigace  ",
	"Near" : "Blízký",
	"Off" : "Vyp",
	"Often" : "Často",
	"Often_Int_OFF" : "Často",
	"OnDemand" : "Na vyž.",
	"OnceAllDoors" : "Jednou: všechny dveře",
	"OnceDriversDoorTwiceAllDoors" : "Jednou: řidič. dvakrát: všechny dveře",
	"Open" : "Otevři",
	"ParkingSensorIndication" : "Signál parkovacího snímače ",
	"ParkingSensorIndicator" : "Indikace parkovacího snímače",
	"RVMBuzzerVolume" : "Rear Vehicle Monitoring Hlasitost",
	"Rare" : "Zřídka",
	"Rare_Int_OFF" : "Zřídka",
	"Reset" : "Reset",
	"Rotation" : "Otáčení",
	"RumbleStrips" : "Vibr.č.",
	"RumbleStrips_line" : "Vibr.č. ",
	"RumbleVolume" : "Hlasitost vibrací",
	"SBSReset" : "Opravdu chcete vrátit výchozí nastavení Smart Brake Support (SBS)?",
	"SBSResetError" : "Chyba při změně nastavení Smart Brake Support (SBS). Zkusit znovu?",
	"SBSResetProgress" : "Změna nastavení Smart Brake Support (SBS)",
	"SBSSCBS" : "SBS/SCBS",
	"SBS_SCBSReset" : "Opravdu chcete vrátit výchozí nastavení SBS/SCBS?",
	"SBS_SCBSResetError" : "Chyba při změně nastavení SBS/SCBS. Zkusit znovu?",
	"SBS_SCBSResetProgress" : "Změna nastavení SBS/SCBS",
	"SCBS" : "Smart City Brake Support",
	"SCBSReset" : "„Opravdu chcete obnovit výchozí nastavení SCBS?“",
	"SCBSResetError" : "Výchozí nastavení SCBS nelze obnovit. Chcete to zkusit znovu?",
	"SCBSResetProgress" : "Obnovování nastavení SCBS",
	"SLC_Buzzer" : "Pouze akustické upozornění",
	"SLC_Off" : "Vypnuto ",
	"SLC_Sign" : "Vizuální",
	"SLC_Sign_Buzzer" : "Zvuk a obraz",
	"SLIReset" : "Opravdu chcete obnovit výchozí nastavení varování před rychlostním omezením?",
	"SLIResetError" : "Výchozí nastavení varování před rychlostním omezením nelze obnovit. Chcete to zkusit znovu?",
	"SLIResetProgress" : "Obnovování nastavení varování před rychlostním omezením",
	"SLI_HeadUpDisplay" : "Active Driving Display",
	"Safety" : "Bezp.",
	"Safetysettings" : "Bezp. nastavení",
	"Sensitivity" : "Citlivost",
	"Sensitivity_Intervention_OFF" : "Výstraha ",
	"Setting" : "Nastavení",
	"Settings" : "Nastavení",
	"Short" : "Blízko",
	"SideView" : "Bok",
	"SideViewFrontView" : "Bok+vpředu",
	"SmartBrakeSupport" : "Smart Brake Support",
	"Sound" : "Zvuk",
	"SpeedAlarm" : "Upozornění na rychlost",
	"SpeedLimitCaution" : "Upozor. na rychlostní omezení",
	"SpeedLimitInformation" : "Varování před rychlostním omezením",
	"SpeedLimitSign" : "Zobrazení rychlostního omezení",
	"StepKilometers" : "{value} km/h",
	"StepMiles" : "{value} mi/h",
	"StreetInformation" : "Informace o ulici",
	"Streetinfo_off" : "Vypnuto",
	"System" : "Systém",
	"TSRReset" : "Opravdu chcete obnovit výchozí nastavení systému rozpoznávání dopravních značek?",
	"TSRResetError" : "Výchozí nastavení systému rozpoznávání dopravních značek nelze obnovit. Chcete to zkusit znovu?",
	"TSRResetProgress" : "Obnovování nastavení systému rozpoznávání dopravních značek",
	"TSR_Display" : "Zobrazení dopravních značek",
	"TSR_System" : "Systém rozpoznávání dopravních značek",
	"Tachometer" : "Tachometr",
	"ThreeFlashTurnSignal" : "3 zablikání směrovky",
	"Timing" : "Časové parametry",
	"Turn" : "Směrovka",
	"TurnProgress" : "Změna nastavení odbočování",
	"TurnReset" : "Opravdu chcete vrátit výchozí nastavení signalizace odbočování?",
	"TurnResetError" : "Chyba při změně nastavení signalizace odbočování. Zkusit znovu?",
	"TurnSettings" : "Signalizace odbočování",
	"TurnSignalIndicatorVolume" : "Hlasitost sign. směrovky",
	"UnlockMode" : "Režim odblokování",
	"Vehicle" : "Vozidlo",
	"VehicleSettings" : "Nas.vozidla",
	"Vibration" : "Vibrace",
	"VibrationStrength" : "Intenzita vibrací",
	"Vibration_Line" : "Vibrace",
	"ViewSwitchDisplay" : "Výchozí zobrazení",
	"ViewSwitchFunction" : "Funkce spínače pohledů",
	"Volume" : "Hlasitost",
	"WalkAwayLock" : "Zamykání po vystoupení",
	"Warning" : "Výstraha",
	"WarningDistance" : "Varov. vzdálenost",
	"_0s" : "0 s",
	"_0seconds" : "0 sekund",
	"_10m" : "10 min",
	"_10minutes" : "10 minut",
	"_120s" : "120 s",
	"_120seconds" : "120 sekund",
	"_15s" : "15 s",
	"_15seconds" : "15 sekund",
	"_30m" : "30 min",
	"_30minutes" : "30 minut",
	"_30s" : "30 s",
	"_30seconds" : "30 sekund",
	"_60m" : "60 min",
	"_60minutes" : "60 minut",
	"_60s" : "60 s",
	"_60seconds" : "60 sekund",
	"_7p5s" : "7,5 s",
	"_7p5seconds" : "7,5 sekund",
	"_90s" : "90 s",
	"_90seconds" : "90 sekund",
	"_AllDoors" : "Všechny",
	"_Driver'sDoor" : "Řidiče",
	"on" : "Zap",
};

framework.registerAppDictLoaded("vehsettings", "cs_CS");