var Localization_vehsettingsAppDict_sk_SK = {
	//"stringId" : "localString"
	"360ViewCamera" : "Monitor 360 °",
	"AHBC" : "Adaptive LED Headlights",
	"Adaptive" : "Adaptívny",
	"AdaptiveFront-lightingSystem" : "Adaptive Front-lighting System",
	"AdaptiveLaneStreetTurn" : "Adaptívny pruh/ulica/odbočka",
	"AlarmTiming" : "Rýchlosti",
	"AlertTiming" : "Načas. upoz.",
	"Always" : "Vždy",
	"AtLine" : "Na r.",
	"Auto" : "Auto",
	"AutoHeadlightOn" : "Automat. zapnutie svetlometov",
	"AutoWiper" : "Stierač so senzorom dažďa",
	"BSMBuzzerVolume" : "Blind Spot Monitoring Hlasitosť",
	"BSMReset" : "Naozaj chcete nastavenia BSM vrátiť na ich predvolené hodnoty?",
	"BSMResetError" : "Chyba návratu nastavení BSM na predvolené hodnoty. Chcete to skúsiť znovu?",
	"BSMResetProgress" : "Obnovovanie nastavení BSM",
	"BSMSystem" : "Systém Blind Spot Monitoring ",
	"Beep" : "Pípnutie",
	"BeepVolume" : "Hlasitosť pípnutia",
	"Beep_Line" : "Pípnutie",
	"BeforeLine" : "Pr. r.",
	"Brightness" : "Jas",
	"BrightnessControl" : "Riadenie jasu",
	"CHudNav_Maneuver" : "Manéver",
	"CHudNav_Off" : "Vyp.",
	"CHudNav_TBT_Lane" : "Jazd.pr.",
	"CHudNav_TBT_Street" : "Náz.ul.",
	"Calibration" : "Jas",
	"CautionSpeed" : "Prahová hodnota upozornenia",
	"CenterDisplay" : "Stredný displej",
	"ChangingLASSettings" : "Zmeniť Lane-keep Assist System nast.",
	"Clock" : "Hodiny",
	"Close" : "Zat.",
	"ComingHomeLights" : "Coming Home Light",
	"ComingHomeLightsTimer" : "Coming Home Light",
	"DRSS" : "Distance Recognition Support System",
	"DRSSReset" : "Naozaj chcete nastavenia Distance Recognition Support System (DRSS) vrátiť na ich predvolené hodnoty?",
	"DRSSResetError" : "Chyba pri zmene nastavení Distance Recognition Support System (DRSS). Chcete to skúsiť znovu?",
	"DRSSResetProgress" : "Zmeniť Distance Recognition Support System (DRSS)",
	"Dark" : "Tma",
	"DaytimeRunningLights" : "Svetlá na denné svietenie",
	"Devices" : "Zariade.",
	"Display" : "Displej",
	"DisplayInformation" : "Informácie na displeji",
	"DistanceRecognitionSupportSystem" : "Distance Recognition Support System",
	"DoorLock" : "Zámok dverí",
	"DoorLockMode" : "Režim auto zamykania dverí",
	"DoorLockReset" : "Naozaj chcete nastavenia zámku dverí vrátiť na ich predvolené hodnoty?",
	"DoorLockResetError" : "Chyba pri zmene nastavení zámku dverí. Chcete to skúsiť znovu?",
	"DoorLockResetProgress" : "Zmeniť Door Lock nastavenia",
	"DoorRelockTime" : "Čas auto opät. zamknutia",
	"DriverAlert" : "Driver Attention Alert",
	"Early" : "Včas",
	"ErrorBSMSettings" : "Chyba pri zmene nastavení BSM. Chcete to skúsiť znovu?",
	"ErrorLASSettings" : "Chyba pri zmene nastavení Lane-keep Assist System. Chcete to skúsiť znovu?",
	"FOWReset" : "Naozaj chcete nastavenia Forward Obstruction Warning (FOW) vrátiť na ich predvolené hodnoty?",
	"FOWResetError" : "Chyba pri zmene nastavení Forward Obstruction Warning (FOW). Chcete to skúsiť znovu?",
	"FOWResetProgress" : "Zmeniť Forward Obstruction Warning (FOW) nastavenia",
	"Far" : "Ďaleko",
	"ForwardObstructionWarning" : "Forward Obstruction Warning",
	"FrontCameraView" : "Čelný pohľad kamery",
	"GearShiftIndicator" : "Indikátor prevodového stupňa",
	"GuidelineDisplay" : "Dynamické čiary pohybu",
	"HUD" : "AD-Disp",
	"HUDDisplayInfoError" : "Nemožno obnoviť nastavenia údajov na displeji AD-Disp na výrobné hodnoty. Chcete to skúsiť znovu?",
	"HUDDisplayInfoReset" : "Naozaj chcete obnoviť nastavenia údajov na displeji AD-Disp na predvolené hodnoty?",
	"HUDDisplayInfoResetProgress" : "Obnovujú sa nastavenia údajov na displeji AD-Disp",
	"HUDJ78AReset" : "Naozaj chcete obnoviť nastavenia Active Driving Display na predvolené hodnoty?",
	"HUDJ78AResetError" : "Pri obnovovaní nastavení Active Driving Display došlo k chybe. Chcete to skúsiť znovu?",
	"HUDJ78AResetProgress" : "Obnovujú sa nastavenia Active Driving Display",
	"HUDJ78ATab" : "Active Driving Display",
	"HUDReset" : "Naozaj chcete nastavenia Active Driving Display vrátiť na ich predvolené hodnoty?",
	"HUDResetError" : "Chyba pri zmene nastavení Active Driving Display. Chcete to skúsiť znovu?",
	"HUDResetProgress" : "Zmena Active Driving Display nastavenia",
	"HUDSettings" : "Nastavenia AD-Disp",
	"HUD_HeadUpDisplay" : "Active Driving Display",
	"HeadUpDisplay" : "Active Driving Display",
	"HeadlightOffTimer" : "Časovač vypnutia svetlometov",
	"HeadlightOnWarning" : "Pozor zap. Svetlá",
	"HeadsUpDisplay" : "Active Driving Display",
	"Height" : "Výška",
	"High" : "Vys.",
	"HighBeamControl" : "High Beam Control",
	"High_SensitivityLAS" : "Vys.",
	"High_Vibration" : "Vys.",
	"ILB_Bright" : "Plné",
	"ILB_Dark" : "Stlmené",
	"ILB_Medium" : "Stredné",
	"ILB_Off" : "Vyp. ",
	"IgONAutoDisplay" : "Automaticky zobraziť 360° View Monitor",
	"InterioLightsTimeOutDoorsClosed" : "Doba osvet. inter. po zatv. dvier",
	"InterioLightsTimeOutDoorsOpen" : "Doba osvet. inter.po otv. dvier",
	"InteriorLightTimeoutDoorClosedTitle" : "Doba osv. int.-dvere zat.",
	"InteriorLightTimeoutDoorOpenTitle" : "Doba osv. int.-dvere otv.",
	"InteriorLightingBrightness" : "Náladové osvetlenie",
	"Intervention" : "Zákrok",
	"InterventionTiming" : "Načasovanie zákroku",
	"KeylessLockBeepVol" : "Hlas pípnutia bezkľúčov. Zámku",
	"Kilometers" : "km/h",
	"LASAlert" : "Upozornenie LAS",
	"LASDefaultValues" : "Naozaj chcete nastavenia Lane-keep Assist System vrátiť na ich predvolené hodnoty?",
	"LASEarly" : "Včas",
	"LASLate" : "Neskoro",
	"LASSound" : "Typ upozornenia",
	"LASTiming" : "Načasovanie LAS",
	"LDWSReset" : "Naozaj chcete nastavenia Lane Departure Warning System (LDWS) vrátiť na ich predvolené hodnoty?",
	"LDWSResetError" : "Chyba pri zmene nastavení Lane Departure Warning System (LDWS). Chcete to skúsiť znovu?",
	"LDWSResetProgress" : "Zmeniť Lane Departure Warning System (LDWS) nastavenia",
	"LDWSTiming" : "Načasovanie LDWS",
	"LaneDepartureAlert" : "Upoz. na vyb. z jaz. pr.",
	"LaneDepartureWarningSystem" : "Lane Departure Warning System",
	"LaneKeepAssistSystem" : "Lane-keep Assist System",
	"Late" : "Neskoro",
	"LeavingHomeLights" : "Leaving Home Light",
	"Light" : "Svetlo",
	"LightOnReminderVolume" : "Hlas. up. zap. sv.",
	"Lighting" : "Osvetlenie",
	"LightingReset" : "Naozaj chcete nastavenia osvetlenia vrátiť na ich predvolené hodnoty?",
	"LightingResetError" : "Chyba pri zmene nastavení osvetlenia. Chcete to skúsiť znovu?",
	"LightingResetProgress" : "Zmeniť nastavenie osvetlenia",
	"LockShiftFromP" : "Zam.: Vyr. z parkovacej polohy ",
	"LockShiftFromPUnlockInPark" : "Zamk.: bez park. Odom.: park.",
	"LockUnlock" : "Zamknutie: Počas jazdy  Odom.: park.",
	"LockWhenDriving" : "Zamknutie: Počas jazdy",
	"LockWhenDrivingUnlockIGNoff" : "Zam.: jazda; Odom.: IGN vyp.",
	"Long" : "Ďaleko",
	"Low" : "Nízka",
	"Low_SensitivityLAS" : "Nízka",
	"Low_Vibration" : "Nízka",
	"Manual" : "Man.",
	"Med" : "Stred",
	"Medium" : "Stredné",
	"MediumDark" : "Strd. tma",
	"MediumLight" : "Strd. Sve",
	"Medium_Int_OFF" : "Stred",
	"Medium_SensitivityLAS" : "Stred",
	"Mid" : "Stred",
	"Middle" : "Stred",
	"Miles" : "mph",
	"Mode" : "Režim",
	"Navigation" : "Navigácia",
	"NavigationSignal" : "Navigácia  ",
	"Near" : "Blízko",
	"Off" : "Vyp.",
	"Often" : "Často",
	"Often_Int_OFF" : "Často",
	"OnDemand" : "Na pož.",
	"OnceAllDoors" : "Raz: Všetky dvere",
	"OnceDriversDoorTwiceAllDoors" : "Raz: Vodičove Dvakr.: Všetky dvere",
	"Open" : "Otv.",
	"ParkingSensorIndication" : "Údaj parkovacieho snímača ",
	"ParkingSensorIndicator" : "Indikátor parkovacieho snímača",
	"RVMBuzzerVolume" : "Rear Vehicle Monitoring Hlasitosť",
	"Rare" : "Zadné",
	"Rare_Int_OFF" : "Zadné",
	"Reset" : "Reset",
	"Rotation" : "Otočenie",
	"RumbleStrips" : "RS",
	"RumbleStrips_line" : "RS ",
	"RumbleVolume" : "Hlas akust.",
	"SBSReset" : "Naozaj chcete nastavenia Smart Brake Support (SBS) vrátiť na ich predvolené hodnoty?",
	"SBSResetError" : "Chyba pri zmene nastavení Smart Brake Support (SBS). Chcete to skúsiť znovu?",
	"SBSResetProgress" : "Zmeniť Smart Brake Support (SBS) nastavenia",
	"SBSSCBS" : "SBS/SCBS",
	"SBS_SCBSReset" : "Naozaj chcete nastavenia SBS/SCBS vrátiť na ich predvolené hodnoty?",
	"SBS_SCBSResetError" : "Chyba pri zmene nastavení SBS/SCBS. Chcete to skúsiť znovu?",
	"SBS_SCBSResetProgress" : "Zmeniť SBS/SCBS nastavenia",
	"SCBS" : "Smart City Brake Support",
	"SCBSReset" : "Naozaj chcete nastavenia SCBS obnoviť na ich predvolené hodnoty?\"",
	"SCBSResetError" : "Chyba návratu nastavení SCBS na ich predvolené hodnoty. Chcete to skúsiť znovu?\"",
	"SCBSResetProgress" : "Obnovovanie nastavení SCBS",
	"SLC_Buzzer" : "Len zvuk",
	"SLC_Off" : "Vyp. ",
	"SLC_Sign" : "Vizuálne",
	"SLC_Sign_Buzzer" : "Obraz a zvuk",
	"SLIReset" : "Naozaj chcete obnoviť nastavenia upozornenia na maximálnu rýchlosť na predvolené hodnoty?",
	"SLIResetError" : "Nastavenia upozornenia na maximálnu rýchlosť nemožno obnoviť na predvolené hodnoty. Chcete to skúsiť znovu?",
	"SLIResetProgress" : "Obnovovanie nastavení upozornenia na maximálnu rýchlosť",
	"SLI_HeadUpDisplay" : "Active Driving Display",
	"Safety" : "Bezpečn.",
	"Safetysettings" : "Bezp. nastavenia",
	"Sensitivity" : "Citlivosť",
	"Sensitivity_Intervention_OFF" : "Upozornenie ",
	"Setting" : "Nastavenia",
	"Settings" : "Nastavenia",
	"Short" : "Blízko",
	"SideView" : "Bok",
	"SideViewFrontView" : "Bok+predok",
	"SmartBrakeSupport" : "Smart Brake Support",
	"Sound" : "Zvuk",
	"SpeedAlarm" : "Upozornenie na rýchlosť",
	"SpeedLimitCaution" : "Upoz. na max. rýchlosť",
	"SpeedLimitInformation" : "Varov. o prekroč. max. rýchlosti",
	"SpeedLimitSign" : "Zobraz. max. rýchlosti",
	"StepKilometers" : "{value} km/h",
	"StepMiles" : "{value} mph",
	"StreetInformation" : "Údaje o ulici",
	"Streetinfo_off" : "Vyp.",
	"System" : "Systém",
	"TSRReset" : "Naozaj chcete obnoviť nastavenia systému rozpoznávania dopravného značenia na predvolené hodnoty? ",
	"TSRResetError" : " Nastavenia systém rozpoznávania dopravného značenia nemožno obnoviť na predvolené hodnoty. Chcete to skúsiť znovu?",
	"TSRResetProgress" : "Obnovovanie nastavení systému rozpoznávania dopravného značenia ",
	"TSR_Display" : "Zobrazenie dopravného značenia",
	"TSR_System" : "Systém rozpoznávania dopravného značenia",
	"Tachometer" : "Otáčkomer",
	"ThreeFlashTurnSignal" : "Signál odbočenia 3× blikne",
	"Timing" : "Časovanie",
	"Turn" : "Odbočiť",
	"TurnProgress" : "Zmena nastavenia zabočení",
	"TurnReset" : "Naozaj chcete nastavenia odbočovania vrátiť na ich predvolené hodnoty?",
	"TurnResetError" : "Chyba pri zmene nastavení odbočovania. Chcete to skúsiť znovu?",
	"TurnSettings" : "Odbočiť",
	"TurnSignalIndicatorVolume" : "Hlas. signálu odbočovania",
	"UnlockMode" : "Režim odomykania",
	"Vehicle" : "Vozidlo",
	"VehicleSettings" : "Nastavenia vozidla",
	"Vibration" : "Vibrovanie",
	"VibrationStrength" : "Intenzita vibrovania",
	"Vibration_Line" : "Vibrovanie",
	"ViewSwitchDisplay" : "Predvolené zobrazenie",
	"ViewSwitchFunction" : "Zobraziť spínač funkcie",
	"Volume" : "Hlasitosť",
	"WalkAwayLock" : "Zámok vzdialenia sa od vozidla",
	"Warning" : "Upozornenie",
	"WarningDistance" : "Upoz. – vzdial.",
	"_0s" : "0 s",
	"_0seconds" : "0 sekúnd",
	"_10m" : "10 min",
	"_10minutes" : "10 minút",
	"_120s" : "120 s",
	"_120seconds" : "120 sekúnd",
	"_15s" : "15 s",
	"_15seconds" : "15 sekúnd",
	"_30m" : "30 min",
	"_30minutes" : "30 minút",
	"_30s" : "30 s",
	"_30seconds" : "30 sekúnd",
	"_60m" : "60 min",
	"_60minutes" : "60 minút",
	"_60s" : "60 s",
	"_60seconds" : "60 sekúnd",
	"_7p5s" : "7.5 s",
	"_7p5seconds" : "7,5 sekundy",
	"_90s" : "90 s",
	"_90seconds" : "90 sekúnd",
	"_AllDoors" : "Všetko",
	"_Driver'sDoor" : "Vodiča",
	"on" : "Zap.",
};

framework.registerAppDictLoaded("vehsettings", "sk_SK");