var Localization_vehsettingsAppDict_sv_SE = {
	//"stringId" : "localString"
	"360ViewCamera" : "360° View Monitor",
	"AHBC" : "Adaptive LED Headlights",
	"Adaptive" : "Adaptivt",
	"AdaptiveFront-lightingSystem" : "Adaptivt strålkastarsystem",
	"AdaptiveLaneStreetTurn" : "Adaptiv fil/gata/sväng",
	"AlarmTiming" : "Hastighets",
	"AlertTiming" : "Varningstiming",
	"Always" : "Alltid",
	"AtLine" : "På rad",
	"Auto" : "Auto",
	"AutoHeadlightOn" : "Strålkastare automatiskt på",
	"AutoWiper" : "Regnsensor",
	"BSMBuzzerVolume" : "Blind Spot Monitoring Volym",
	"BSMReset" : "Vill du verkligen återställa BSM-inställningarna till standardvärden?",
	"BSMResetError" : "Det gick inte att återställa BSM-inställningarna till standardvärden. Vill du försöka igen?",
	"BSMResetProgress" : "Återställer BSM-inställningar",
	"BSMSystem" : "Blind Spot Monitoring-system ",
	"Beep" : "Pip",
	"BeepVolume" : "Pipvolym",
	"Beep_Line" : "Pip",
	"BeforeLine" : "F rad",
	"Brightness" : "Ljusstyrka",
	"BrightnessControl" : "Ljusstyrkereglage",
	"CHudNav_Maneuver" : "Vid manöver",
	"CHudNav_Off" : "Av",
	"CHudNav_TBT_Lane" : "Filguidn",
	"CHudNav_TBT_Street" : "Gatunamn",
	"Calibration" : "Ljusstyrka",
	"CautionSpeed" : "Tröskelvärde för varning",
	"CenterDisplay" : "Centerdisplay",
	"ChangingLASSettings" : "Ändra Lane-keep Assist Systeminst.",
	"Clock" : "Klocka",
	"Close" : "Stäng",
	"ComingHomeLights" : "Coming Home Light",
	"ComingHomeLightsTimer" : "Coming Home Light",
	"DRSS" : "Distance Recognition Support System",
	"DRSSReset" : "Är du säker på att du vill återställa inställningarna för Distance Recognition Support System till standardvärden?",
	"DRSSResetError" : "Fel vid ändring av Distance Recognition Support System. Vill du prova igen?",
	"DRSSResetProgress" : "Ändrar Distance Recognition Support System",
	"Dark" : "Mörk",
	"DaytimeRunningLights" : "Belysning dagtid",
	"Devices" : "Enheter",
	"Display" : "Display",
	"DisplayInformation" : "Visa information",
	"DistanceRecognitionSupportSystem" : "Distance Recognition Support System",
	"DoorLock" : "Dörrlås",
	"DoorLockMode" : "Auto låsläge",
	"DoorLockReset" : "Vill du verkligen återställa dörrlåsinställningarna till standardvärden?",
	"DoorLockResetError" : "Fel vid ändring av dörrlåsinställningarna. Vill du prova igen?",
	"DoorLockResetProgress" : "Ändrar dörrlåsinställningarna",
	"DoorRelockTime" : "Tid för automatisk låsning",
	"DriverAlert" : "Driver Attention Alert",
	"Early" : "Tidigt",
	"ErrorBSMSettings" : "Fel vid ändring av BSM-inställningar. Vill du försöka igen?",
	"ErrorLASSettings" : "Fel vid ändring av Lane-keep Assist System. Vill du försöka igen?",
	"FOWReset" : "Vill du verkligen återställa inställningarna för varning för Forward Obstruction Warning till standardvärden?",
	"FOWResetError" : "Fel vid ändring av inställningarna för varning för Forward Obstruction Warning. Vill du prova igen?",
	"FOWResetProgress" : "Ändrar inställningarna för varning för Forward Obstruction Warning",
	"Far" : "Långt",
	"ForwardObstructionWarning" : "Forward Obstruction Warning",
	"FrontCameraView" : "Kameravy fram",
	"GearShiftIndicator" : "Växlingsindikator",
	"GuidelineDisplay" : "Dynamisk körlinje",
	"HUD" : "AD-Disp",
	"HUDDisplayInfoError" : "Det gick inte att återställa inställningarna för AD-Disp displayinformation till fabriksinställningarna. Vill du försöka igen?",
	"HUDDisplayInfoReset" : "Är du säker på att du vill återställa inställningarna för AD-Disp displayinformation till dess standardvärden?",
	"HUDDisplayInfoResetProgress" : "Återställer inställningarna för AD-Disp displayinformation",
	"HUDJ78AReset" : "Är du säker på att du vill återställa inställningarna för Active Driving Display till ursprungsvärdena?",
	"HUDJ78AResetError" : "Ett fel uppstod vid återställning av Active Driving Display-inställningarna. Vill du försöka igen?",
	"HUDJ78AResetProgress" : "Återställning Active Driving Display-inställningar",
	"HUDJ78ATab" : "Active Driving Display",
	"HUDReset" : "Vill du verkligen återställa AD-Disp inställningarna till standardvärden?",
	"HUDResetError" : "Fel vid ändring av AD-Disp inställningarna. Vill du prova igen?",
	"HUDResetProgress" : "Ändrar AD-Disp inställningarna",
	"HUDSettings" : "Inställningar AD-Disp",
	"HUD_HeadUpDisplay" : "Active Driving Display",
	"HeadUpDisplay" : "Active Driving Display",
	"HeadlightOffTimer" : "Strålkastare av, timer",
	"HeadlightOnWarning" : "Varning, strålk",
	"HeadsUpDisplay" : "Active Driving Display",
	"Height" : "Höjd",
	"High" : "Hög",
	"HighBeamControl" : "High Beam Control",
	"High_SensitivityLAS" : "Hög",
	"High_Vibration" : "Hög",
	"ILB_Bright" : "Ljus",
	"ILB_Dark" : "Dämpad",
	"ILB_Medium" : "Medel",
	"ILB_Off" : "Av ",
	"IgONAutoDisplay" : "Visa 360° View Monitor automatiskt",
	"InterioLightsTimeOutDoorsClosed" : "Timeout belysn – Stängda dörrar",
	"InterioLightsTimeOutDoorsOpen" : "Timeout belysn – Öppna dörrar",
	"InteriorLightTimeoutDoorClosedTitle" : "Timeout belysn – Stängda dörrar",
	"InteriorLightTimeoutDoorOpenTitle" : "Timeout belysn – Öppna dörrar",
	"InteriorLightingBrightness" : "Innerbelysning",
	"Intervention" : "Ingripande",
	"InterventionTiming" : "Ingreppstiming",
	"KeylessLockBeepVol" : "Volym på pip för nyckelfri öppning",
	"Kilometers" : "km/h",
	"LASAlert" : "LAS Varning",
	"LASDefaultValues" : "Är du säker på att du vill återgå till Lane-keep Assist Systemets standardinställningar?",
	"LASEarly" : "Tidigt",
	"LASLate" : "Sen",
	"LASSound" : "Varningstyp",
	"LASTiming" : "LAStid",
	"LDWSReset" : "Vill du verkligen återställa inställningarna för Lane Departure Warning System till standardvärden?",
	"LDWSResetError" : "Fel vid ändring av inställningarna för Lane Departure Warning System. Vill du prova igen?",
	"LDWSResetProgress" : "Ändrar inställningarna för Lane Departure Warning System",
	"LDWSTiming" : "LDWS-timing",
	"LaneDepartureAlert" : "Körfältsvarning",
	"LaneDepartureWarningSystem" : "Lane Departure Warning System",
	"LaneKeepAssistSystem" : "Lane-keep Assist System",
	"Late" : "Sen",
	"LeavingHomeLights" : "Leaving Home Light",
	"Light" : "Ljus",
	"LightOnReminderVolume" : "Volym, påm ljus",
	"Lighting" : "Belysning",
	"LightingReset" : "Vill du verkligen återställa ljusinställningarna till standardvärden?",
	"LightingResetError" : "Fel vid ändring av ljusinställningarna. Vill du prova igen?",
	"LightingResetProgress" : "Ändrar ljusinställningarna",
	"LockShiftFromP" : "Lås: Växling från parkeringsläge ",
	"LockShiftFromPUnlockInPark" : "Lås: Lås upp parkeringsläge: I P-läge",
	"LockUnlock" : "Lås: Lås upp för att köra: Parkering",
	"LockWhenDriving" : "Lås: Vid körning",
	"LockWhenDrivingUnlockIGNoff" : "Lås: Lås upp vid körning: IGN av",
	"Long" : "Långt",
	"Low" : "Låg",
	"Low_SensitivityLAS" : "Låg",
	"Low_Vibration" : "Låg",
	"Manual" : "Manu",
	"Med" : "Med",
	"Medium" : "Medel",
	"MediumDark" : "Skymning",
	"MediumLight" : "Medelljus",
	"Medium_Int_OFF" : "Med",
	"Medium_SensitivityLAS" : "Med",
	"Mid" : "Mitt",
	"Middle" : "Mitten",
	"Miles" : "mph",
	"Mode" : "Läge",
	"Navigation" : "Navigation",
	"NavigationSignal" : "Navigering  ",
	"Near" : "Nära",
	"Off" : "Av",
	"Often" : "Ofta",
	"Often_Int_OFF" : "Ofta",
	"OnDemand" : "På beg.",
	"OnceAllDoors" : "En gång: Alla dörrar",
	"OnceDriversDoorTwiceAllDoors" : "En gång: Förarens två ggr: Alla dörrar",
	"Open" : "Öppen",
	"ParkingSensorIndication" : "Parkeringssensorindikation ",
	"ParkingSensorIndicator" : "Parkeringssensorindikator",
	"RVMBuzzerVolume" : "Rear Vehicle Monitoring Volym",
	"Rare" : "Sällsynt",
	"Rare_Int_OFF" : "Sällsynt",
	"Reset" : "Återställ",
	"Rotation" : "Rotation",
	"RumbleStrips" : "Buller",
	"RumbleStrips_line" : "Buller ",
	"RumbleVolume" : "Bullervolym",
	"SBSReset" : "Vill du verkligen återställa inställningarna för Smart Brake Support (SBS) till standardvärden?",
	"SBSResetError" : "Fel vid ändring av inställningarna för Smart Brake Support. Vill du prova igen?",
	"SBSResetProgress" : "Ändrar inställningarna för Smart Brake Support (SBS)",
	"SBSSCBS" : "SBS/SCBS",
	"SBS_SCBSReset" : "Vill du verkligen återställa SBS/SCBS-inställningarna till standardvärden?",
	"SBS_SCBSResetError" : "Fel vid ändring av SBS/SCBS-inställningarna. Vill du prova igen?",
	"SBS_SCBSResetProgress" : "Ändrar SBS/SCBS-inställningarna",
	"SCBS" : "Smart City Brake Support",
	"SCBSReset" : "Vill du verkligen återställa SCBS-inställningarna till standardvärden?\"",
	"SCBSResetError" : "Det gick inte att återställa SCBS-inställningarna till standardvärden. Vill du försöka igen?\"",
	"SCBSResetProgress" : "Återställer SCBS-inställningarna",
	"SLC_Buzzer" : "Enbart ljudsignal",
	"SLC_Off" : "Av ",
	"SLC_Sign" : "Visuell",
	"SLC_Sign_Buzzer" : "Ljud och visuell",
	"SLIReset" : "Är du säker på att du vill återställa inställningarna för hastighetsvarning till standardvärden?",
	"SLIResetError" : "Det gick inte att återställa inställningarna för hastighetsvarning till standardvärden. Vill du försöka igen?",
	"SLIResetProgress" : "Återställer inställningarna för hastighetsvarning",
	"SLI_HeadUpDisplay" : "Active Driving Display",
	"Safety" : "Säkerhet",
	"Safetysettings" : "Säkerhetsinställn",
	"Sensitivity" : "Känslighet",
	"Sensitivity_Intervention_OFF" : "Varning ",
	"Setting" : "Inställningar",
	"Settings" : "Inställningar",
	"Short" : "Nära",
	"SideView" : "Sida",
	"SideViewFrontView" : "Sida+fram",
	"SmartBrakeSupport" : "Smart Brake Support",
	"Sound" : "Ljud",
	"SpeedAlarm" : "Hastighetsvarnare",
	"SpeedLimitCaution" : "Hastighetspåminnelse",
	"SpeedLimitInformation" : "Hastighetsvarning",
	"SpeedLimitSign" : "Visa hastighetsbegränsning",
	"StepKilometers" : "{value} km/h",
	"StepMiles" : "{value} mph",
	"StreetInformation" : "Gatuinformation",
	"Streetinfo_off" : "Av",
	"System" : "System",
	"TSRReset" : "Är du säker på att du vill återställa inställningarna för systemet för igenkänning av trafikmärken till standardvärden?",
	"TSRResetError" : "Det gick inte att återställa inställningarna för systemet för igenkänning av trafikmärken till standardvärden. Vill du försöka igen?",
	"TSRResetProgress" : "Återställer inställningarna för systemet för igenkänning av trafikmärken",
	"TSR_Display" : "Visa trafikmärken",
	"TSR_System" : "System för igenkänning av trafikmärken",
	"Tachometer" : "Varvräknare",
	"ThreeFlashTurnSignal" : "3 blinkersignaler",
	"Timing" : "Timing",
	"Turn" : "Blinkers",
	"TurnProgress" : "Ändrar svänginställningarna",
	"TurnReset" : "Vill du verkligen återställa svänginställningarna till standardvärden?",
	"TurnResetError" : "Fel vid ändring av svänginställningarna. Vill du prova igen?",
	"TurnSettings" : "Blinkers",
	"TurnSignalIndicatorVolume" : "Volym på blinkerssignal",
	"UnlockMode" : "Upplåst läge",
	"Vehicle" : "Fordon",
	"VehicleSettings" : "Fordonsinställn",
	"Vibration" : "Vibration",
	"VibrationStrength" : "Vibrationsstyrka",
	"Vibration_Line" : "Vibration",
	"ViewSwitchDisplay" : "Standardvy",
	"ViewSwitchFunction" : "Växla vy-funktion",
	"Volume" : "Volym",
	"WalkAwayLock" : "Gå iväg-lås",
	"Warning" : "Varning",
	"WarningDistance" : "Avståndsvarning",
	"_0s" : "0 s",
	"_0seconds" : "0 sekunder",
	"_10m" : "10 min",
	"_10minutes" : "10 minuter",
	"_120s" : "120 s",
	"_120seconds" : "120 sekunder",
	"_15s" : "15 s",
	"_15seconds" : "15 sekunder",
	"_30m" : "30 min",
	"_30minutes" : "30 minuter",
	"_30s" : "30 s",
	"_30seconds" : "30 sekunder",
	"_60m" : "60 min",
	"_60minutes" : "60 minuter",
	"_60s" : "60 s",
	"_60seconds" : "60 sekunder",
	"_7p5s" : "7,5 s",
	"_7p5seconds" : "7,5 sekunder",
	"_90s" : "90 s",
	"_90seconds" : "90 sekunder",
	"_AllDoors" : "Alla",
	"_Driver'sDoor" : "Förar.",
	"on" : "På",
};

framework.registerAppDictLoaded("vehsettings", "sv_SE");