var Localization_vehsettingsAppDict_ru_RU = {
	//"stringId" : "localString"
	"360ViewCamera" : "Монитор обзора на 360°",
	"AHBC" : "Adaptive LED Headlights",
	"Adaptive" : "Адаптивн",
	"AdaptiveFront-lightingSystem" : "Aдаптивного головного освещения",
	"AdaptiveLaneStreetTurn" : "Адаптивн. ряд/улица/поворот",
	"AlarmTiming" : "Cкорости",
	"AlertTiming" : "Время предупрежд.",
	"Always" : "Всегда",
	"AtLine" : "В стр.",
	"Auto" : "Авто",
	"AutoHeadlightOn" : "Автоматическое включение фар",
	"AutoWiper" : "авт. Стеклоочиститель",
	"BSMBuzzerVolume" : "Громк. Blind Spot Monitoring",
	"BSMReset" : "Вы действительно хотите восстановить заводские настройки BSM по умолчанию?",
	"BSMResetError" : "Не удалось восстановить заводские настройки BSM по умолчанию. Повторить попытку?",
	"BSMResetProgress" : "Восстановление настроек BSM",
	"BSMSystem" : "Система Blind Spot Monitoring ",
	"Beep" : "Сигнал",
	"BeepVolume" : "Громкость сигнала",
	"Beep_Line" : "Сигнал",
	"BeforeLine" : "Перед",
	"Brightness" : "Яркость",
	"BrightnessControl" : "Управление яркостью",
	"CHudNav_Maneuver" : "Маневр.",
	"CHudNav_Off" : "Выкл.",
	"CHudNav_TBT_Lane" : "Ряд/пов.",
	"CHudNav_TBT_Street" : "Ул/пов.",
	"Calibration" : "Яркость",
	"CautionSpeed" : "Порог сигнала",
	"CenterDisplay" : "Центральный дисплей",
	"ChangingLASSettings" : "Изменение настроек LAS",
	"Clock" : "Часы",
	"Close" : "Закр.",
	"ComingHomeLights" : "Coming Home Light",
	"ComingHomeLightsTimer" : "Coming Home Light",
	"DRSS" : "Distance Recognition Support System",
	"DRSSReset" : "Вы действительно хотите выполнить возврат к настройкам Distance Recognition Support System (DRSS) по умолчанию?",
	"DRSSResetError" : "Ошибка при изменении настроек Distance Recognition Support System (DRSS). Вы хотите повторить?",
	"DRSSResetProgress" : "Изменение настроек Distance Recognition Support System (DRSS)",
	"Dark" : "Темно",
	"DaytimeRunningLights" : "Дневные ходовые огни",
	"Devices" : "Устр-ва",
	"Display" : "Дисплей",
	"DisplayInformation" : "Информация на дисплее",
	"DistanceRecognitionSupportSystem" : "Distance Recognition Support System",
	"DoorLock" : "Дверные замки",
	"DoorLockMode" : "Режим авт. запирания двери",
	"DoorLockReset" : "Вы уверены, что хотите вернуть настройки замков дверей на значения по умолчанию?",
	"DoorLockResetError" : "Ошибка при изменении настроек замков дверей. Вы хотите повторить?",
	"DoorLockResetProgress" : "Изменение настроек замков дверей",
	"DoorRelockTime" : "Время авт. повт. запирания",
	"DriverAlert" : "Driver Attention Alert",
	"Early" : "Раньше",
	"ErrorBSMSettings" : "Ошибка изменения настроек BSM. Повторить попытку?",
	"ErrorLASSettings" : "Ошибка при изменении настроек Lane-keep Assist System. Хотите повторить?",
	"FOWReset" : "Вы уверены, что хотите вернуть настройки Forward Obstruction Warning (FOW) на значения по умолчанию?",
	"FOWResetError" : "Ошибка при изменении настроек Forward Obstruction Warning (FOW). Вы хотите повторить?",
	"FOWResetProgress" : "Изменение настроек Forward Obstruction Warning (FOW)",
	"Far" : "Дал.",
	"ForwardObstructionWarning" : "Forward Obstruction Warning",
	"FrontCameraView" : "Вид передней камеры",
	"GearShiftIndicator" : "Индикатор переключения передач",
	"GuidelineDisplay" : "Динамич. линии пути",
	"HUD" : "AD-Disp",
	"HUDDisplayInfoError" : "Не удалось восстановить заводские значения по умолчанию для настроек отображения информации на дисплее AD-Disp. Повторить попытку?",
	"HUDDisplayInfoReset" : "Действительно восстановить значения по умолчанию для настроек отображения информации на дисплее AD-Disp?",
	"HUDDisplayInfoResetProgress" : "Восст. настроек отображ. инф. на дисп. AD-Disp",
	"HUDJ78AReset" : "Действительно сбросить настройки Active Driving Display и установить значения по умолчанию?",
	"HUDJ78AResetError" : "Возникла ошибка во время сброса настроек Active Driving Display. Повторить попытку?",
	"HUDJ78AResetProgress" : "Сброс настроек Active Driving Display",
	"HUDJ78ATab" : "Active Driving Display",
	"HUDReset" : "Вы уверены, что хотите вернуть настройки Active Driving Display на значения по умолчанию?",
	"HUDResetError" : "Ошибка при изменении настроек Active Driving Display. Вы хотите повторить?",
	"HUDResetProgress" : "Изменение настроек  AD-Disp",
	"HUDSettings" : "Настройки AD-Disp",
	"HUD_HeadUpDisplay" : "Active Driving Display",
	"HeadUpDisplay" : "Active Driving Display",
	"HeadlightOffTimer" : "Таймер отключения фар",
	"HeadlightOnWarning" : "Пред. о вкл. фар",
	"HeadsUpDisplay" : "Active Driving Display",
	"Height" : "Высота",
	"High" : "Выс.",
	"HighBeamControl" : "High Beam Control",
	"High_SensitivityLAS" : "Выс.",
	"High_Vibration" : "Выс.",
	"ILB_Bright" : "Ярко",
	"ILB_Dark" : "Тускло",
	"ILB_Medium" : "Средний",
	"ILB_Off" : "Выкл. ",
	"IgONAutoDisplay" : "Автом. отображ. 360° View Monitor",
	"InterioLightsTimeOutDoorsClosed" : "Откл.освещ.салона при закр.дв.",
	"InterioLightsTimeOutDoorsOpen" : "Откл.освещ.салона при откр.дв.",
	"InteriorLightTimeoutDoorClosedTitle" : "Таймаут подсветки - Двери закр.",
	"InteriorLightTimeoutDoorOpenTitle" : "Таймаут подсветки - Двери откр.",
	"InteriorLightingBrightness" : "Общее освещение",
	"Intervention" : "Вмешательство",
	"InterventionTiming" : "Время вмешательс.",
	"KeylessLockBeepVol" : "Гром.сиг.зап.двр б/з клч",
	"Kilometers" : "км/ч",
	"LASAlert" : "Сообщение LAS",
	"LASDefaultValues" : "Вернуть настройки Lane-keep Assist System на значения по умолчанию?",
	"LASEarly" : "Раньше",
	"LASLate" : "Позже",
	"LASSound" : "Тип предупреждения",
	"LASTiming" : "Расчет времени LAS",
	"LDWSReset" : "Вы уверены, что хотите вернуть настройки Lane Departure Warning System (LDWS) на значения по умолчанию?",
	"LDWSResetError" : "Ошибка при изменении настроек Lane Departure Warning System (LDWS). Вы хотите повторить?",
	"LDWSResetProgress" : "Изменение настроек Lane Departure Warning System (LDWS)",
	"LDWSTiming" : "Расчет времени LDWS",
	"LaneDepartureAlert" : "Предупр. о выезде за пред. пол.",
	"LaneDepartureWarningSystem" : "Lane Departure Warning System",
	"LaneKeepAssistSystem" : "Lane-keep Assist System",
	"Late" : "Позже",
	"LeavingHomeLights" : "Leaving Home Light",
	"Light" : "Светло",
	"LightOnReminderVolume" : "Сигн. о вкл. свете",
	"Lighting" : "Освещение",
	"LightingReset" : "Вы уверены, что хотите вернуть настройки освещения на значения по умолчанию?",
	"LightingResetError" : "Ошибка при изменении настроек освещения. Вы хотите повторить?",
	"LightingResetProgress" : "Изменение настроек освещения",
	"LockShiftFromP" : "Блок: снятие с тормоза ",
	"LockShiftFromPUnlockInPark" : "Блок: снятие с тормоза Разбл: при парк.",
	"LockUnlock" : "Блок: разбл. вожд.  Разбл: парк.",
	"LockWhenDriving" : "Блокировка: во время движения",
	"LockWhenDrivingUnlockIGNoff" : "Блок: разбл. при вожд. Разбл: ЗЖГ выкл.",
	"Long" : "Дал.",
	"Low" : "Низ.",
	"Low_SensitivityLAS" : "Низ.",
	"Low_Vibration" : "Низ.",
	"Manual" : "Ручн.",
	"Med" : "Сред.",
	"Medium" : "Средне",
	"MediumDark" : "Средне темно",
	"MediumLight" : "Средне светло",
	"Medium_Int_OFF" : "Сред",
	"Medium_SensitivityLAS" : "Сред",
	"Mid" : "Сред.",
	"Middle" : "Средн.",
	"Miles" : "мили в час",
	"Mode" : "Режим",
	"Navigation" : "Навигация",
	"NavigationSignal" : "Навигация  ",
	"Near" : "Близ.",
	"Off" : "Выкл",
	"Often" : "Часто",
	"Often_Int_OFF" : "Часто",
	"OnDemand" : "По треб.",
	"OnceAllDoors" : "Один раз: все двери",
	"OnceDriversDoorTwiceAllDoors" : "x1: дверь водителя x2: все двери",
	"Open" : "Откр.",
	"ParkingSensorIndication" : "Ультразвуковой датчик парковки ",
	"ParkingSensorIndicator" : "Индикатор датчика парковки",
	"RVMBuzzerVolume" : "Громк. Rear Vehicle Monitoring",
	"Rare" : "Редко",
	"Rare_Int_OFF" : "Редко",
	"Reset" : "Сбросить",
	"Rotation" : "Поворот",
	"RumbleStrips" : "Рокот",
	"RumbleStrips_line" : "Рокот ",
	"RumbleVolume" : "Громк. рокота",
	"SBSReset" : "Вы уверены, что хотите вернуть настройки Smart Brake Support (SBS) на значения по умолчанию?",
	"SBSResetError" : "Ошибка при изменении настроек Smart Brake Support (SBS). Вы хотите повторить?",
	"SBSResetProgress" : "Изменение настроек Smart Brake Support (SBS)",
	"SBSSCBS" : "SBS/SCBS",
	"SBS_SCBSReset" : "Вы уверены, что хотите вернуть настройки SBS/SCBS на значения по умолчанию?",
	"SBS_SCBSResetError" : "Ошибка при изменении настроек SBS/SCBS. Вы хотите повторить?",
	"SBS_SCBSResetProgress" : "Изменение настроек SBS/SCBS",
	"SCBS" : "Smart City Brake Support",
	"SCBSReset" : "Вы действительно хотите восстановить заводские настройки SCBS по умолчанию?",
	"SCBSResetError" : "Не удалось восстановить заводские настройки SCBS по умолчанию. Повторить попытку?",
	"SCBSResetProgress" : "Восстановление настроек SCBS",
	"SLC_Buzzer" : "Только звуковой сигнализатор",
	"SLC_Off" : "Выкл. ",
	"SLC_Sign" : "Визуальн.",
	"SLC_Sign_Buzzer" : "Аудио и визуальн.",
	"SLIReset" : "Вы действительно хотите восстановить значения по умолчанию для настроек предупреждений об ограничении скорости?",
	"SLIResetError" : "Не удалось восстановить заводские значения по умолчанию для настроек предупреждений об ограничении скорости. Повторить попытку?",
	"SLIResetProgress" : "Восстановление настроек предупреждений об ограничении скорости",
	"SLI_HeadUpDisplay" : "Active Driving Display",
	"Safety" : "Безопас.",
	"Safetysettings" : "Настр. безопас.",
	"Sensitivity" : "Чувствит.",
	"Sensitivity_Intervention_OFF" : "Предупреждение ",
	"Setting" : "Установка",
	"Settings" : "Настройки",
	"Short" : "Близ.",
	"SideView" : "Сбоку",
	"SideViewFrontView" : "Сбоку+спереди",
	"SmartBrakeSupport" : "Smart Brake Support",
	"Sound" : "Звук",
	"SpeedAlarm" : "Аварийный сигнал о скорости",
	"SpeedLimitCaution" : "Сигнал огр. скор.",
	"SpeedLimitInformation" : "Предупр. об огр. скор.",
	"SpeedLimitSign" : "Отобр. огр. скорости",
	"StepKilometers" : "{value} км/ч",
	"StepMiles" : "{value} мили в час",
	"StreetInformation" : "Информация об улице",
	"Streetinfo_off" : "Выкл.",
	"System" : "Система",
	"TSRReset" : "Вы действительно хотите восстановить значения по умолчанию для настроек системы распознавания дорожных знаков?",
	"TSRResetError" : "Не удалось восстановить заводские значения по умолчанию для настроек системы распознавания дорожных знаков. Повторить попытку?",
	"TSRResetProgress" : "Восстановление настроек системы распознавания дорожных знаков",
	"TSR_Display" : "Отображение дорожных знаков",
	"TSR_System" : "Система распознавания дорожных знаков",
	"Tachometer" : "Тахометр",
	"ThreeFlashTurnSignal" : "Тройной сигнал поворота",
	"Timing" : "Расчет времени",
	"Turn" : "Указатель поворота",
	"TurnProgress" : "Изм-ие настр.указ.поворота",
	"TurnReset" : "Вернуть настройки указателей поворота на значения по умолчанию?",
	"TurnResetError" : "Ошибка при изменении настроек указатель поворота. Повторить?",
	"TurnSettings" : "Указатель поворота",
	"TurnSignalIndicatorVolume" : "Громк. сигнала поворота",
	"UnlockMode" : "Режим разблокировки",
	"Vehicle" : "Авто",
	"VehicleSettings" : "Настройки авто",
	"Vibration" : "Вибрация",
	"VibrationStrength" : "Сила вибрации",
	"Vibration_Line" : "Вибрация",
	"ViewSwitchDisplay" : "Обзор по умолчанию",
	"ViewSwitchFunction" : "Функция переключения обзора",
	"Volume" : "Громкость",
	"WalkAwayLock" : "Запирание при покидании автомобиля",
	"Warning" : "Предупреждение",
	"WarningDistance" : "Расст. предупр.",
	"_0s" : "0 с",
	"_0seconds" : "0 секунд",
	"_10m" : "10 мин",
	"_10minutes" : "10 минут",
	"_120s" : "120 с",
	"_120seconds" : "120 секунд",
	"_15s" : "15 с",
	"_15seconds" : "15 секунд",
	"_30m" : "30 мин",
	"_30minutes" : "30 минут",
	"_30s" : "30 с",
	"_30seconds" : "30 секунд",
	"_60m" : "60 мин",
	"_60minutes" : "60 минут",
	"_60s" : "60 с",
	"_60seconds" : "60 секунд",
	"_7p5s" : "7,5 с",
	"_7p5seconds" : "7,5 секунд",
	"_90s" : "90 с",
	"_90seconds" : "90 секунд",
	"_AllDoors" : "Все",
	"_Driver'sDoor" : "Водит.",
	"on" : "Вкл.",
};

framework.registerAppDictLoaded("vehsettings", "ru_RU");