var Localization_vehsettingsAppDict_fi_FI = {
	//"stringId" : "localString"
	"360ViewCamera" : "360° näyttö",
	"AHBC" : "Adaptive LED Headlights",
	"Adaptive" : "Mukautuva",
	"AdaptiveFront-lightingSystem" : "Mukautuvien etuvalojen",
	"AdaptiveLaneStreetTurn" : "Mukautuva kaistan/kadun/vaihto",
	"AlarmTiming" : "Nopeus",
	"AlertTiming" : "Hälytyksen ajoitus",
	"Always" : "Aina",
	"AtLine" : "Viiva",
	"Auto" : "Auto",
	"AutoHeadlightOn" : "Autom. ajovalot",
	"AutoWiper" : "Pyyhinautomatiikka sadetunnistimella",
	"BSMBuzzerVolume" : "Blind Spot Monitoring Äänenv.",
	"BSMReset" : "Oletko varma että haluat palauttaa BSM-asetukset tehdasasetuksiin?",
	"BSMResetError" : "BSM-asetusten palautus tehdasasetuksiin ei onnistu. Haluatko yrittää uudelleen?",
	"BSMResetProgress" : "Palautetaan BSM-asetuksia",
	"BSMSystem" : "Sokean pisteen seurantajärjestelmä ",
	"Beep" : "Ääni",
	"BeepVolume" : "Äänimerkin voimakkuus",
	"Beep_Line" : "Ääni",
	"BeforeLine" : "Ennen",
	"Brightness" : "Kirkkaus",
	"BrightnessControl" : "Kirkkaus",
	"CHudNav_Maneuver" : "Ennen ohjausliikettä",
	"CHudNav_Off" : "Pois",
	"CHudNav_TBT_Lane" : "Ka vaiht",
	"CHudNav_TBT_Street" : "Katunimi",
	"Calibration" : "Kirkkaus",
	"CautionSpeed" : "Hälytyksen alaraja",
	"CenterDisplay" : "Keskusnäyttö",
	"ChangingLASSettings" : "LAS-järjestelmän muokkaaminen",
	"Clock" : "Kello",
	"Close" : "Sulje",
	"ComingHomeLights" : "Coming Home Light",
	"ComingHomeLightsTimer" : "Coming Home Light",
	"DRSS" : "Distance Recognition Support System",
	"DRSSReset" : "Haluatko varmasti palauttaa Distance Recognition Support System asetukset oletusarvoihin?",
	"DRSSResetError" : "Virhe Distance Recognition Support System asetuksia vaihdettaessa. Haluatko yrittää uudelleen?",
	"DRSSResetProgress" : "Vaihdetaan Distance Recognition Support System asetuksia",
	"Dark" : "Tumma",
	"DaytimeRunningLights" : "Ajovalot",
	"Devices" : "Laitteet",
	"Display" : "Näyttö",
	"DisplayInformation" : "Näytön tiedot",
	"DistanceRecognitionSupportSystem" : "Distance Recognition Support System",
	"DoorLock" : "Ovien lukitus",
	"DoorLockMode" : "Autom. ovien lukitus",
	"DoorLockReset" : "Haluatko varmasti palauttaa ovien lukituksen asetukset oletusarvoihin?",
	"DoorLockResetError" : "Virhe ovien lukituksen asetuksia vaihdettaessa. Haluatko yrittää uudelleen?",
	"DoorLockResetProgress" : "Vaihdetaan ovien lukituksen asetuksia",
	"DoorRelockTime" : "Autom. uudelleenlukituksen aika",
	"DriverAlert" : "Driver Attention Alert",
	"Early" : "Aikainen",
	"ErrorBSMSettings" : "Virhe muutettaessa BSM-asetuksia Haluatko yrittää uudelleen?",
	"ErrorLASSettings" : "Virhe muutettaessa Lane-keep Assist System. Haluatko yrittää uudelleen?",
	"FOWReset" : "Haluatko varmasti palauttaa Forward Obstruction Warning asetukset oletusarvoihin?",
	"FOWResetError" : "Virhe Forward Obstruction Warning varoitusasetuksia vaihdettaessa. Haluatko yrittää uudelleen?",
	"FOWResetProgress" : "Vaihdetaan Forward Obstruction Warning varoitusasetuksia",
	"Far" : "Kauk.",
	"ForwardObstructionWarning" : "Forward Obstruction Warning",
	"FrontCameraView" : "Näkymä etukamerasta",
	"GearShiftIndicator" : "Vaihteen vaihto-opastin",
	"GuidelineDisplay" : "Dynaamiset reittilinjat",
	"HUD" : "AD-Disp",
	"HUDDisplayInfoError" : "AD-Disp-näyttötietojen asetusten palautus tehdasarvoiksi epäonnistui. Haluatko yrittää uudelleen?",
	"HUDDisplayInfoReset" : "Haluatko todella palauttaa AD-Disp-näyttötietojen asetukset oletusarvoiksi?",
	"HUDDisplayInfoResetProgress" : "Palauttaa AD-Disp-näyttötietojen asetuksia",
	"HUDJ78AReset" : "Haluatko todella palauttaa Active Driving Display-asetukset oletusarvoiksi?",
	"HUDJ78AResetError" : "Active Driving Display-asetusten palautuksessa tapahtui virhe. Haluatko yrittää uudelleen?",
	"HUDJ78AResetProgress" : "Active Driving Display-asetuksia palautetaan",
	"HUDJ78ATab" : "Active Driving Display",
	"HUDReset" : "Haluatko varmasti palauttaa Active Driving Display asetukset oletusarvoihin?",
	"HUDResetError" : "Virhe Active Driving Display asetuksia vaihdettaessa. Haluatko yrittää uudelleen?",
	"HUDResetProgress" : "Vaihdetaan AD-Disp asetuksia",
	"HUDSettings" : "AD-Disp-asetukset",
	"HUD_HeadUpDisplay" : "Active Driving Display",
	"HeadUpDisplay" : "Active Driving Display",
	"HeadlightOffTimer" : "Ajovalot pois päältä -ajastin",
	"HeadlightOnWarning" : "Ajovalot-varoitus",
	"HeadsUpDisplay" : "Active Driving Display",
	"Height" : "Korkeus",
	"High" : "Suuri",
	"HighBeamControl" : "High Beam Control",
	"High_SensitivityLAS" : "Suuri",
	"High_Vibration" : "Suuri",
	"ILB_Bright" : "Valoisa",
	"ILB_Dark" : "Himmeä",
	"ILB_Medium" : "Kohtalainen",
	"ILB_Off" : "Pois ",
	"IgONAutoDisplay" : "Automaattinen näyttö 360° View Monitor",
	"InterioLightsTimeOutDoorsClosed" : "Sisävalojen aikakatk. - Ovet kiinni",
	"InterioLightsTimeOutDoorsOpen" : "Sisävalojen aikakatk. - Ovet auki",
	"InteriorLightTimeoutDoorClosedTitle" : "Sisävalon aikakatkaisu - Ovet kiinni",
	"InteriorLightTimeoutDoorOpenTitle" : "Sisävalon aikakatkaisu - Ovet auki",
	"InteriorLightingBrightness" : "Valoisuus",
	"Intervention" : "Väliintulo",
	"InterventionTiming" : "Väliintulon ajoitus",
	"KeylessLockBeepVol" : "Avaimettoman luk. äänen voim.",
	"Kilometers" : "km/h",
	"LASAlert" : "LAS-hälytys",
	"LASDefaultValues" : "Oletko varma että haluat asettaa oletusarvot Lane-keep Assist System?",
	"LASEarly" : "Aikainen",
	"LASLate" : "Myöhään",
	"LASSound" : "Hälytystyyppi",
	"LASTiming" : "LAS ajoitus",
	"LDWSReset" : "Haluatko varmasti palauttaa Lane Departure Warning System asetukset oletusarvoihin?",
	"LDWSResetError" : "Virhe Lane Departure Warning System asetuksia vaihdettaessa. Haluatko yrittää uudelleen?",
	"LDWSResetProgress" : "Vaihdetaan Lane Departure Warning System asetuksia",
	"LDWSTiming" : "LDWS ajoitus",
	"LaneDepartureAlert" : "Kaistahälytys",
	"LaneDepartureWarningSystem" : "Lane Departure Warning System",
	"LaneKeepAssistSystem" : "Lane-keep Assist System",
	"Late" : "Myöhään",
	"LeavingHomeLights" : "Leaving Home Light",
	"Light" : "Vaalea",
	"LightOnReminderVolume" : "Valomuistut. voim.",
	"Lighting" : "Valaistus",
	"LightingReset" : "Haluatko varmasti palauttaa valojen asetukset oletusarvoihin?",
	"LightingResetError" : "Virhe valojen asetuksia vaihdettaessa. Haluatko yrittää uudelleen?",
	"LightingResetProgress" : "Vaihdetaan valojen asetuksia",
	"LockShiftFromP" : "Lukitse: P-vaihde pois ",
	"LockShiftFromPUnlockInPark" : "Lukitse: P pois  Avaa: P-vaihteella",
	"LockUnlock" : "Lukko: Ajettaessa Lukko pois: Parkki",
	"LockWhenDriving" : "Lukitse: Ajettaessa",
	"LockWhenDrivingUnlockIGNoff" : "Lukitse: Ajossa Avaa: virta Off",
	"Long" : "Kauk.",
	"Low" : "Pieni",
	"Low_SensitivityLAS" : "Pieni",
	"Low_Vibration" : "Pieni",
	"Manual" : "Man.",
	"Med" : "Keski",
	"Medium" : "Normaali",
	"MediumDark" : "Keskitum.",
	"MediumLight" : "Keskivaal.",
	"Medium_Int_OFF" : "Keski",
	"Medium_SensitivityLAS" : "Keski",
	"Mid" : "Keski",
	"Middle" : "Keski",
	"Miles" : "mph",
	"Mode" : "Tila",
	"Navigation" : "Navigointi",
	"NavigationSignal" : "Navigointi  ",
	"Near" : "Lähellä",
	"Off" : "Pois",
	"Often" : "Usein",
	"Often_Int_OFF" : "Usein",
	"OnDemand" : "Pyyn.",
	"OnceAllDoors" : "Kerran: Kaikki ovet",
	"OnceDriversDoorTwiceAllDoors" : "Kerran: Kuljettajan 2 krt: Kaikki ovet",
	"Open" : "Avaa",
	"ParkingSensorIndication" : "Pysäköintianturin ilmaisin ",
	"ParkingSensorIndicator" : "Pysäköintianturin ilmaisin",
	"RVMBuzzerVolume" : "Rear Vehicle Monitoring Äänenv.",
	"Rare" : "Harvoin",
	"Rare_Int_OFF" : "Harvoin",
	"Reset" : "Palauta",
	"Rotation" : "Kierto",
	"RumbleStrips" : "Vibr",
	"RumbleStrips_line" : "Vibr ",
	"RumbleVolume" : "Heräte vol",
	"SBSReset" : "Haluatko varmasti palauttaa Smart Brake Support (SBS)-asetukset oletusarvoihin?",
	"SBSResetError" : "Virhe Smart Brake Support (SBS)-järjestelmän asetuksia vaihdettaessa. Haluatko yrittää uudelleen?",
	"SBSResetProgress" : "Vaihdetaan Smart Brake Support(SBS)-järjestelmän asetuksia",
	"SBSSCBS" : "SBS/SCBS",
	"SBS_SCBSReset" : "Haluatko varmasti palauttaa SBS/SCBS-asetukset oletusarvoihin?",
	"SBS_SCBSResetError" : "Virhe SBS/SCBS-järjestelmän asetuksia vaihdettaessa. Haluatko yrittää uudelleen?",
	"SBS_SCBSResetProgress" : "Vaihdetaan SBS/SCBS-järjestelmän asetuksia",
	"SCBS" : "Smart City Brake Support",
	"SCBSReset" : "Oletko varma, että haluat palauttaa SCBS-asetukset tehdasasetuksiin?\"",
	"SCBSResetError" : "SCBS-asetusten palautus tehdasasetuksiin ei onnistu. Haluatko yrittää uudelleen?\"",
	"SCBSResetProgress" : "Palautetaan SCBS-asetuksia",
	"SLC_Buzzer" : "Vain summeri",
	"SLC_Off" : "Pois ",
	"SLC_Sign" : "Visuaalinen",
	"SLC_Sign_Buzzer" : "Audiovisuaalinen",
	"SLIReset" : "Haluatko varmasti palauttaa nopeusrajoitusvaroitusten asetukset takaisin oletusasetuksiin?",
	"SLIResetError" : "Nopeusrajoitusvaroitusten asetusten palauttaminen tehdasasetuksiin ei onnistu. Haluatko yrittää uudelleen?",
	"SLIResetProgress" : "Palautetaan nopeusrajoitusvaroitusten asetuksia",
	"SLI_HeadUpDisplay" : "Active Driving Display",
	"Safety" : "Turvall.",
	"Safetysettings" : "Turvallisuusaset.",
	"Sensitivity" : "Herkkyys",
	"Sensitivity_Intervention_OFF" : "Varoitus ",
	"Setting" : "Asetukset",
	"Settings" : "Asetukset",
	"Short" : "Lähellä",
	"SideView" : "Sivu",
	"SideViewFrontView" : "Sivu+keula",
	"SmartBrakeSupport" : "Smart Brake Support",
	"Sound" : "Ääni",
	"SpeedAlarm" : "Nopeushälytys",
	"SpeedLimitCaution" : "Nopeusrajoitushäl.",
	"SpeedLimitInformation" : "Nopeusrajoitusvaroitus",
	"SpeedLimitSign" : "Nopeusrajoitusnäyttö",
	"StepKilometers" : "{value} km/h",
	"StepMiles" : "{value} mph",
	"StreetInformation" : "Katutiedot",
	"Streetinfo_off" : "Pois",
	"System" : "Järjest.",
	"TSRReset" : "Haluatko varmasti palauttaa liikennemerkkien tunnistusjäsjestelmän asetukset takaisin oletusasetuksiin?",
	"TSRResetError" : "Liikenne merkkien tunnistusjärjestelmän asetusten palauttaminen tehdasasetuksiin ei onnistu. Haluatko yrittää uudelleen?",
	"TSRResetProgress" : "Palautetaan liikennemerkkien tunnistusjärjestelmän asetuksia",
	"TSR_Display" : "Liikennemerkkien näyttö",
	"TSR_System" : "Liikennemerkkien huomiojärjestelmä",
	"Tachometer" : "Kierroslukumittari",
	"ThreeFlashTurnSignal" : "Kolme kertaa välähtävä suuntavilkku",
	"Timing" : "Ajoitus",
	"Turn" : "Suuntavilkut",
	"TurnProgress" : "Vaihdetaan käännösasetuksia",
	"TurnReset" : "Haluatko varmasti palauttaa käännösasetukset oletusarvoihin?",
	"TurnResetError" : "Virhe käännösasetuksia vaihdettaessa. Haluatko yrittää uudelleen?",
	"TurnSettings" : "Suuntavilkut",
	"TurnSignalIndicatorVolume" : "Vilkun äänenvoim.",
	"UnlockMode" : "Lukituksenpoistotila",
	"Vehicle" : "Auto",
	"VehicleSettings" : "Auton asetukset",
	"Vibration" : "Värinä",
	"VibrationStrength" : "Värinän voimakkuus",
	"Vibration_Line" : "Värinä",
	"ViewSwitchDisplay" : "Oletusnäkymä",
	"ViewSwitchFunction" : "Näytä vaihtotoiminto",
	"Volume" : "Äänenvoim.",
	"WalkAwayLock" : "Avaimeton lukitusjärjestelmä",
	"Warning" : "Varoitus",
	"WarningDistance" : "Varoitusetäisyys",
	"_0s" : "0 s",
	"_0seconds" : "0 sekuntia",
	"_10m" : "10 min",
	"_10minutes" : "10 minuuttia",
	"_120s" : "120 s",
	"_120seconds" : "120 sekuntia",
	"_15s" : "15 s",
	"_15seconds" : "15 sekuntia",
	"_30m" : "30 min",
	"_30minutes" : "30 minuuttia",
	"_30s" : "30 s",
	"_30seconds" : "30 sekuntia",
	"_60m" : "60 min",
	"_60minutes" : "60 minuuttia",
	"_60s" : "60 s",
	"_60seconds" : "60 sekuntia",
	"_7p5s" : "7.5 s",
	"_7p5seconds" : "7.5 sekuntia",
	"_90s" : "90 s",
	"_90seconds" : "90 sekuntia",
	"_AllDoors" : "Kaikki",
	"_Driver'sDoor" : "Kuljett.",
	"on" : "Päällä",
};

framework.registerAppDictLoaded("vehsettings", "fi_FI");