var Localization_vehsettingsAppDict_pt_BR = {
	//"stringId" : "localString"
	"360ViewCamera" : "360° View Monitor",
	"AHBC" : "Adaptive LED Headlights",
	"Adaptive" : "Adaptável",
	"AdaptiveFront-lightingSystem" : "Sistema adaptável de luzes dianteiras",
	"AdaptiveLaneStreetTurn" : "Adaptive Lane/Street/Turn",
	"AlarmTiming" : "Velocid.",
	"AlertTiming" : "Temporizador de alerta",
	"Always" : "Sempre",
	"AtLine" : "Em",
	"Auto" : "Auto",
	"AutoHeadlightOn" : "Faróis automáticos ligados",
	"AutoWiper" : "Limpador com sensor de chuva",
	"BSMBuzzerVolume" : "Volume do Blind Spot Monitoring",
	"BSMReset" : "Are you sure you want to restore BSM settings to the factory defaults?",
	"BSMResetError" : "Unable to restore BSM settings to the factory defaults. Would you like to retry?",
	"BSMResetProgress" : "Restoring BSM Settings",
	"BSMSystem" : "Blind Spot Monitoring System ",
	"Beep" : "Bipe",
	"BeepVolume" : "Volume bipe",
	"Beep_Line" : "Bipe",
	"BeforeLine" : "Antes",
	"Brightness" : "Brilho",
	"BrightnessControl" : "Controle de brilho",
	"CHudNav_Maneuver" : "At Maneuver",
	"CHudNav_Off" : "Off",
	"CHudNav_TBT_Lane" : "Lane Guidance & Turn-by-Turn",
	"CHudNav_TBT_Street" : "Street Name & Turn-by-Turn",
	"Calibration" : "Brightness",
	"CautionSpeed" : "Alert Threshold",
	"CenterDisplay" : "Display central",
	"ChangingLASSettings" : "Alter. config. Lane-keep Assist System",
	"Clock" : "Relógio",
	"Close" : "Fechar",
	"ComingHomeLights" : "Coming Home Light",
	"ComingHomeLightsTimer" : "Coming Home Light",
	"DRSS" : "Distance Recognition Support System",
	"DRSSReset" : "Tem certeza de que deseja restaurar as configurações do Distance Recognition Support System com os valores padrão de fábrica?",
	"DRSSResetError" : "Não é possível restaurar configurações do Distance Recognition Support System para os valores padrão de fábrica. Deseja tentar novamente?",
	"DRSSResetProgress" : "Restaurando as configurações do Distance Recognition Support System",
	"Dark" : "Baixo",
	"DaytimeRunningLights" : "Faróis diurnos",
	"Devices" : "disp.",
	"Display" : "Exibição",
	"DisplayInformation" : "Exibir informações",
	"DistanceRecognitionSupportSystem" : "Distance Recognition Support System",
	"DoorLock" : "Travamento de portas",
	"DoorLockMode" : "Travamento autom. portas",
	"DoorLockReset" : "Você tem certeza de que deseja restaurar as configurações de travamento de portas com os valores padrão de fábrica?",
	"DoorLockResetError" : "Não é possível restaurar configurações de travamento de portas para os valores padrão de fábrica. Deseja tentar novamente?",
	"DoorLockResetProgress" : "Restaurando configurações de travamento de portas",
	"DoorRelockTime" : "Tempo de retrav. autom.",
	"DriverAlert" : "Driver Attention Alert",
	"Early" : "Precoce",
	"ErrorBSMSettings" : "Error changing BSM settings. Would you like to retry?",
	"ErrorLASSettings" : "Erro ao alterar o Lane-keep Assist System. Deseja tentar novamente?",
	"FOWReset" : "Tem certeza de que deseja restaurar as configurações do Forward Obstruction Warning com os valores padrão de fábrica?",
	"FOWResetError" : "Não é possível restaurar configurações do Forward Obstruction Warning com os valores padrão de fábrica. Deseja tentar novamente?",
	"FOWResetProgress" : "Restaurando configurações do Forward Obstruction Warning",
	"Far" : "Longe",
	"ForwardObstructionWarning" : "Forward Obstruction Warning",
	"FrontCameraView" : "Front Camera View",
	"GearShiftIndicator" : "Indicador de mudança de marcha",
	"GuidelineDisplay" : "Dynamic Path Lines",
	"HUD" : "AD-Disp",
	"HUDDisplayInfoError" : "Não é possível restaurar as configurações de informações de tela AD-Disp para os padrões de fábrica. Deseja tentar novamente?",
	"HUDDisplayInfoReset" : "Tem certeza que deseja restaurar as configurações de informações de tela AD-Disp para os valores padrão?",
	"HUDDisplayInfoResetProgress" : "Restaurando as configurações de informações de tela AD-Disp",
	"HUDJ78AReset" : "Tem certeza que deseja redefinir as configurações de Active Driving Display para os valores padrão?",
	"HUDJ78AResetError" : "Ocorreu um erro ao restaurar as configurações de Active Driving Display. Deseja tentar novamente?",
	"HUDJ78AResetProgress" : "Redefinindo configurações de Active Driving Display",
	"HUDJ78ATab" : "Active Driving Display",
	"HUDReset" : "Tem certeza de que deseja restaurar as configurações do Active Driving Display com os valores padrão de fábrica?",
	"HUDResetError" : "Não é possível restaurar as configurações do Active Driving Display com os valores padrão de fábrica. Deseja tentar novamente?",
	"HUDResetProgress" : "Alt. Config. Active Driving Display",
	"HUDSettings" : "Configurações de AD-Disp",
	"HUD_HeadUpDisplay" : "Active Driving Display",
	"HeadUpDisplay" : "Active Driving Display",
	"HeadlightOffTimer" : "Tempor. deslig. faróis",
	"HeadlightOnWarning" : "Alerta de faróis ligados",
	"HeadsUpDisplay" : "Active Driving Display",
	"Height" : "Altura",
	"High" : "Alto",
	"HighBeamControl" : "High Beam Control",
	"High_SensitivityLAS" : "Alto",
	"High_Vibration" : "Alto",
	"ILB_Bright" : "Claro",
	"ILB_Dark" : "Escuro",
	"ILB_Medium" : "Médio",
	"ILB_Off" : "Desligado ",
	"IgONAutoDisplay" : "Auto Display 360° View Monitor",
	"InterioLightsTimeOutDoorsClosed" : "Limite luz interna - portas fechadas",
	"InterioLightsTimeOutDoorsOpen" : "Limite luz interna - portas abertas",
	"InteriorLightTimeoutDoorClosedTitle" : "Limite luz interna - portas fechadas",
	"InteriorLightTimeoutDoorOpenTitle" : "Limite luz interna - portas abertas",
	"InteriorLightingBrightness" : "Iluminação ambiente",
	"Intervention" : "Intervenção",
	"InterventionTiming" : "Temporizador de intervenção",
	"KeylessLockBeepVol" : "Volume bipe trav. sem chave",
	"Kilometers" : "km/h",
	"LASAlert" : "Alerta LAS",
	"LASDefaultValues" : "Tem certeza de que deseja reverter as configurações do Lane-keep Assist System para os valores padrão de fábrica?",
	"LASEarly" : "Precoce",
	"LASLate" : "Tardio",
	"LASSound" : "Tipo de alerta",
	"LASTiming" : "Tempo LAS",
	"LDWSReset" : "Tem certeza de que deseja restaurar as configurações do Lane Departure Warning System com os valores padrão de fábrica?",
	"LDWSResetError" : "Não é possível restaurar configurações do Lane Departure Warning System com os valores padrão de fábrica. Deseja tentar novamente?",
	"LDWSResetProgress" : "Restaurando as configurações do Lane Departure Warning System",
	"LDWSTiming" : "Temporização LDWS",
	"LaneDepartureAlert" : "Alerta de saída de faixa",
	"LaneDepartureWarningSystem" : "Lane Departure Warning System",
	"LaneKeepAssistSystem" : "Lane-keep Assist System",
	"Late" : "Tardio",
	"LeavingHomeLights" : "Leaving Home Light",
	"Light" : "Alto",
	"LightOnReminderVolume" : "Vol. bipe luz",
	"Lighting" : "Iluminação",
	"LightingReset" : "Você tem certeza de que deseja restaurar as configurações de iluminação com os valores padrão de fábrica?",
	"LightingResetError" : "Não é possível restaurar configurações de iluminação com os valores padrão de fábrica. Deseja tentar novamente?",
	"LightingResetProgress" : "Restaurando configurações de iluminação",
	"LockShiftFromP" : "Travar: saindo de P ",
	"LockShiftFromPUnlockInPark" : "Travar: saindo de P Destr.: em P",
	"LockUnlock" : "Travar: ao dirigir Destr.: em P",
	"LockWhenDriving" : "Travar: ao dirigir",
	"LockWhenDrivingUnlockIGNoff" : "Travar: ao dirigir Destr.: IGN desl.",
	"Long" : "Longe",
	"Low" : "Baixo",
	"Low_SensitivityLAS" : "Baixo",
	"Low_Vibration" : "Baixo",
	"Manual" : "Man.",
	"Med" : "Médio",
	"Medium" : "Médio",
	"MediumDark" : "M. Baxio",
	"MediumLight" : "M. Alto",
	"Medium_Int_OFF" : "Médio",
	"Medium_SensitivityLAS" : "Médio",
	"Mid" : "Mid",
	"Middle" : "Média",
	"Miles" : "mph",
	"Mode" : "Modo",
	"Navigation" : "Navegação",
	"NavigationSignal" : "Navegação  ",
	"Near" : "Próx.",
	"Off" : "Deslig.",
	"Often" : "Freq.",
	"Often_Int_OFF" : "Freq.",
	"OnDemand" : "Sob dem",
	"OnceAllDoors" : "Todas as portas: Uma vez",
	"OnceDriversDoorTwiceAllDoors" : "Do motorista: uma, Todas port.: duas",
	"Open" : "abert.",
	"ParkingSensorIndication" : "Indicação de sensor de estacionamento ",
	"ParkingSensorIndicator" : "Parking Sensor Indicator",
	"RVMBuzzerVolume" : "Volume do Rear Vehicle Monitoring",
	"Rare" : "Raro",
	"Rare_Int_OFF" : "Raro",
	"Reset" : "Reiniciar",
	"Rotation" : "Rotação",
	"RumbleStrips" : "Sonor.",
	"RumbleStrips_line" : "Rumble ",
	"RumbleVolume" : "Rumble Volume",
	"SBSReset" : "Tem certeza de que deseja restaurar as configurações do Smart Brake Support com os valores padrão de fábrica?",
	"SBSResetError" : "Não é possível restaurar configurações do Smart Brake Support com os valores padrão de fábrica. Deseja tentar novamente?",
	"SBSResetProgress" : "Restaurando as configurações do Smart  Brake Support",
	"SBSSCBS" : "SBS/SCBS",
	"SBS_SCBSReset" : "Você tem certeza de que deseja restaurar as configurações do SBS/SCBS com os valores padrão de fábrica?",
	"SBS_SCBSResetError" : "Não é possível restaurar configurações do SBS/SCBS com os valores padrão de fábrica. Deseja tentar novamente?",
	"SBS_SCBSResetProgress" : "Restaurando configurações do SBS/SCBS",
	"SCBS" : "Smart City Brake Support",
	"SCBSReset" : "Are you sure you want to restore SCBS settings to the factory defaults?\"",
	"SCBSResetError" : "Unable to restore SCBS settings to the factory defaults. Would you like to retry?\"",
	"SCBSResetProgress" : "Restoring SCBS settings",
	"SLC_Buzzer" : "Somente vibração",
	"SLC_Off" : "Desligado ",
	"SLC_Sign" : "Visual",
	"SLC_Sign_Buzzer" : "Audio & Visual",
	"SLIReset" : "Are you sure you want to restore Speed Limit Warning settings to their default values?",
	"SLIResetError" : "Unable to restore Speed Limit Warning settings to the factory defaults. Would you like to retry?",
	"SLIResetProgress" : "Restoring Speed Limit Warning settings",
	"SLI_HeadUpDisplay" : "Active Driving Display",
	"Safety" : "Seg.",
	"Safetysettings" : "Config. segurança",
	"Sensitivity" : "Sensibilidade",
	"Sensitivity_Intervention_OFF" : "Alerta ",
	"Setting" : "Configurações",
	"Settings" : "Configurações",
	"Short" : "Próxima",
	"SideView" : "Side",
	"SideViewFrontView" : "Side+Front",
	"SmartBrakeSupport" : "Smart Brake Support",
	"Sound" : "Som",
	"SpeedAlarm" : "Alarme de velocidade",
	"SpeedLimitCaution" : "Speed Limit Alert",
	"SpeedLimitInformation" : "Speed Limit Warning",
	"SpeedLimitSign" : "Speed Limit Display",
	"StepKilometers" : "{value} km/h",
	"StepMiles" : "{value} mph",
	"StreetInformation" : "Informações de rua",
	"Streetinfo_off" : "Desligado",
	"System" : "Sistema",
	"TSRReset" : "Are you sure you want to restore Traffic Sign Recognition System settings to their default values?",
	"TSRResetError" : "Unable to restore Traffic Sign Recognition System settings to the factory defaults. Would like to retry?",
	"TSRResetProgress" : "Restoring Traffic Sign Recognition System settings",
	"TSR_Display" : "Traffic Sign Display",
	"TSR_System" : "Traffic Sign Recognition System",
	"Tachometer" : "Tacômetro",
	"ThreeFlashTurnSignal" : "Seta de 3 piscadas",
	"Timing" : "Tempo",
	"Turn" : "Seta",
	"TurnProgress" : "Restaurando configurações de seta",
	"TurnReset" : "Você tem certeza de que deseja restaurar as configurações de seta para os valores padrão de fábrica?",
	"TurnResetError" : "Não é possível restaurar configurações de seta para os valores padrão de fábrica. Deseja tentar novamente?",
	"TurnSettings" : "Seta",
	"TurnSignalIndicatorVolume" : "Volume do sinal de seta",
	"UnlockMode" : "Modo de destravamento",
	"Vehicle" : "Veículo",
	"VehicleSettings" : "Config do veículo",
	"Vibration" : "Vibração",
	"VibrationStrength" : "Força de vibração",
	"Vibration_Line" : "Vibração",
	"ViewSwitchDisplay" : "Default View",
	"ViewSwitchFunction" : "View Switch Function",
	"Volume" : "Volume do alerta",
	"WalkAwayLock" : "Travar ao se afastar",
	"Warning" : "Alerta",
	"WarningDistance" : "Distância do alerta",
	"_0s" : "0s",
	"_0seconds" : "0 segundos",
	"_10m" : "10 min",
	"_10minutes" : "10 minutos",
	"_120s" : "120s",
	"_120seconds" : "120 segundos",
	"_15s" : "15s",
	"_15seconds" : "15 segundos",
	"_30m" : "30 min",
	"_30minutes" : "30 minutos",
	"_30s" : "30s",
	"_30seconds" : "30 segundos",
	"_60m" : "60 min",
	"_60minutes" : "60 minutos",
	"_60s" : "60s",
	"_60seconds" : "60 segundos",
	"_7p5s" : "7,5s",
	"_7p5seconds" : "7,5 segundos",
	"_90s" : "90s",
	"_90seconds" : "90 segundos",
	"_AllDoors" : "Tudo",
	"_Driver'sDoor" : "Motor.",
	"on" : "Ligado",
};

framework.registerAppDictLoaded("vehsettings", "pt_BR");