var Localization_vehsettingsAppDict_he_IL = {
	//"stringId" : "localString"
	"360ViewCamera" : "מוניטור צפייה 360 °",
	"AHBC" : "Adaptive LED Headlights",
	"Adaptive" : "מותאם",
	"AdaptiveFront-lightingSystem" : "מערכת פנסים קדמית מסתגלת",
	"AdaptiveLaneStreetTurn" : "נתיב/רחוב/סיבוב ניתנים להתאמה",
	"AlarmTiming" : "הגדרת מהירות",
	"AlertTiming" : "תזמון התרעה",
	"Always" : "תמיד",
	"AtLine" : "בקו",
	"Auto" : "אוט'",
	"AutoHeadlightOn" : "פנס קידמי דולק אוטומטי",
	"AutoWiper" : "מגב- חיישן גשם",
	"BSMBuzzerVolume" : "Blind Spot Monitoring עוצמה",
	"BSMReset" : "האם אתה בטוח שברצונך לשחזר את הגדרות BSM לברירת המחדל של המפעל?",
	"BSMResetError" : " לא ניתן לשחזר את הגדרות BSM לברירת המחדל של המפעל. האם ברצונך לנסות שוב?",
	"BSMResetProgress" : "משחזר את הגדרות BSM",
	"BSMSystem" : "מערכת ניטור שטחים מתים ",
	"Beep" : "צפצוף",
	"BeepVolume" : "עוצמת צפצוף",
	"Beep_Line" : "צפצוף",
	"BeforeLine" : "לפ' קו",
	"Brightness" : "בהירות",
	"BrightnessControl" : "בקרת בהירות",
	"CHudNav_Maneuver" : "מתמרן",
	"CHudNav_Off" : "כבוי",
	"CHudNav_TBT_Lane" : "הכוונת נתיב וסיבוב אחר סיבוב",
	"CHudNav_TBT_Street" : "שם רחוב וסיבוב אחר סיבוב",
	"Calibration" : "בהירות",
	"CautionSpeed" : "סף התראה",
	"CenterDisplay" : "תצוגה מרכזית",
	"ChangingLASSettings" : "משנה הגדרות Lane-keep Assist System",
	"Clock" : "שעון",
	"Close" : "סגור",
	"ComingHomeLights" : "Coming Home Light",
	"ComingHomeLightsTimer" : "Coming Home Light",
	"DRSS" : "Distance Recognition Support System",
	"DRSSReset" : "האם אתה בטוח שברצונך להחזיר את הגדרות DRSS לערכי ברירת המחדל שלהן?",
	"DRSSResetError" : "שגיאת החלפת DRSS. האם ברצונך לנסות שנית?",
	"DRSSResetProgress" : "משנה הגדרות שלDistance Recognition  Support  System",
	"Dark" : "כהה",
	"DaytimeRunningLights" : "אורות בשעות היום",
	"Devices" : "מכשירים",
	"Display" : "הצג",
	"DisplayInformation" : "הצג מידע",
	"DistanceRecognitionSupportSystem" : "Distance Recognition Support System",
	"DoorLock" : "נעילת דלתות",
	"DoorLockMode" : "מצב נעילת דלת אוטומטית",
	"DoorLockReset" : "האם אתה בטוח שברצונך להחזיר את הגדרות \"נעילת דלת\" לערכי ברירת המחדל שלהן?",
	"DoorLockResetError" : "שגיאת החלפת הגדרות נעילת הדלת. האם ברצונך לנסות שנית?",
	"DoorLockResetProgress" : "משנה הגדרות נעילת דלת",
	"DoorRelockTime" : "זמן נעילה אוטומטי",
	"DriverAlert" : "Driver Attention Alert",
	"Early" : "מוקדם",
	"ErrorBSMSettings" : "שגיאה בשינוי הגדרות BSM. האם ברצונך לנסות שוב?",
	"ErrorLASSettings" : "שגיאה בעת שינוי Lane-keep Assist System. האם ברצונך לנסות שנית?",
	"FOWReset" : "האם אתה בטוח שברצונך להחזיר הגדרות של Forward Obstruction Warning לערכי ברירת המחדל שלהם?",
	"FOWResetError" : "שגיאת החלפה של הגדרות Forward Obstruction Warning. האם ברצונך לנסות שנית?",
	"FOWResetProgress" : "משנה הגדרות של Forward Obstruction Warning",
	"Far" : "רחוק",
	"ForwardObstructionWarning" : "Forward Obstruction Warning",
	"FrontCameraView" : "תצוגת מצלמה קדמית ",
	"GearShiftIndicator" : "מחוון החלפת הילוכים",
	"GuidelineDisplay" : "קווי מסלול דינמיים",
	"HUD" : "AD-Disp",
	"HUDDisplayInfoError" : "לא ניתן להחזיר את הגדרות המידע של תצוגת AD-Disp לערכי ברירת המחדל של היצרן. האם ברצונך לנסות שוב?",
	"HUDDisplayInfoReset" : "האם אתה בטוח שברצונך להחזיר את הגדרות המידע של תצוגת AD-Disp לערכי ברירת המחדל?",
	"HUDDisplayInfoResetProgress" : "החזרת הגדרות המידע של תצוגת AD-Disp",
	"HUDJ78AReset" : "האם אתה בטוח שברצונך לאפס את הגדרות ה-Active Driving Display לערכי ברירת המחדל?",
	"HUDJ78AResetError" : "אירעה שגיאה במהלך האיפוס של הגדרות Active Driving Display. האם ברצונך לנסות שוב?",
	"HUDJ78AResetProgress" : "מאפס הגדרות Active Driving Display",
	"HUDJ78ATab" : "Active Driving Display",
	"HUDReset" : "האם אתה בטוח שברצונך להחזיר את הגדרות Active Driving Display לערכי ברירת המחדל שלהם?",
	"HUDResetError" : "שגיאת החלפת הגדרות של Active Driving Display. האם ברצונך לנסות שנית?",
	"HUDResetProgress" : "משנה הגדרות של Active Driving Display",
	"HUDSettings" : "הגדרות AD-Disp",
	"HUD_HeadUpDisplay" : "Active Driving Display",
	"HeadUpDisplay" : "Active Driving Display",
	"HeadlightOffTimer" : "טיימר כיבוי פנס קידמי",
	"HeadlightOnWarning" : "התראת פנס קדמי",
	"HeadsUpDisplay" : "Active Driving Display",
	"Height" : "גובה",
	"High" : "גבוה",
	"HighBeamControl" : "High Beam Control",
	"High_SensitivityLAS" : "גבוה",
	"High_Vibration" : "גבוה",
	"ILB_Bright" : "בהיר",
	"ILB_Dark" : "כהה",
	"ILB_Medium" : "בינוני",
	"ILB_Off" : "כבוי ",
	"IgONAutoDisplay" : "תצוגה אוטומטית 360° View Monitor",
	"InterioLightsTimeOutDoorsClosed" : "כיבוי תאורה פנימית – דלת נעולה",
	"InterioLightsTimeOutDoorsOpen" : "כיבוי תאורה פנימית – דלת פתוחה",
	"InteriorLightTimeoutDoorClosedTitle" : "אור פנימי הופסק – דלתות נעולות",
	"InteriorLightTimeoutDoorOpenTitle" : "אור פנימי הופסק – דלתות פתוחות",
	"InteriorLightingBrightness" : "תאורת אווירה",
	"Intervention" : "התערבות",
	"InterventionTiming" : "תזמון התערבות",
	"KeylessLockBeepVol" : "עוצמת צפצוף נעילה ללא מפתח",
	"Kilometers" : "קמ\"ש",
	"LASAlert" : "התראת LAS",
	"LASDefaultValues" : "האם אתה בטוח שברצונך להחזיר את הגדרות Lane-keep Assist System להגדרות המקוריות?",
	"LASEarly" : "מוקדם",
	"LASLate" : "מאוחר",
	"LASSound" : "סוג התרעה",
	"LASTiming" : "תזמון LAS",
	"LDWSReset" : "האם אתה בטוח שברצונך להחזיר את הגדרות Lane Departure Warning System לערכי ברירת המחדל שלהן?",
	"LDWSResetError" : "שגיאת החלפת הגדרות Lane Departure Warning System. האם ברצונך לנסות שנית?",
	"LDWSResetProgress" : "משנה הגדרות Lane Departure Warning System",
	"LDWSTiming" : "תזמון במערכת על LDWS",
	"LaneDepartureAlert" : "התרעה על יציאה מנתיב",
	"LaneDepartureWarningSystem" : "Lane Departure Warning System",
	"LaneKeepAssistSystem" : "Lane-keep Assist System",
	"Late" : "מאוחר",
	"LeavingHomeLights" : "Leaving Home Light",
	"Light" : "בהיר",
	"LightOnReminderVolume" : "תזכורת אורות",
	"Lighting" : "תאורה",
	"LightingReset" : "האם אתה בטוח שברצונך להחזיר את הגדרות \"תאורה\" לברירת המחדל שלהן?",
	"LightingResetError" : "שגיאת החלפת הגדרות התאורה. האם ברצונך לנסות שנית?",
	"LightingResetProgress" : "משנה הגדרות תאורה",
	"LockShiftFromP" : "נעל: הזזת הרכב ממצב חניה ",
	"LockShiftFromPUnlockInPark" : "נעילה: העברה מחניה פתיחה: בחניה",
	"LockUnlock" : "נעילה: במהלך הנסיעה פתיחה: חונה",
	"LockWhenDriving" : "נעל: בזמן נהיגה",
	"LockWhenDrivingUnlockIGNoff" : "נעל: בזמן נהיגה, פתח: כשהמנוע כבוי",
	"Long" : "רחוק",
	"Low" : "נמוך",
	"Low_SensitivityLAS" : "נמוך",
	"Low_Vibration" : "נמוך",
	"Manual" : "ידני",
	"Med" : "בינוני",
	"Medium" : "בינוני",
	"MediumDark" : "בינונ.כהה",
	"MediumLight" : "אור.בינוני",
	"Medium_Int_OFF" : "בינוני",
	"Medium_SensitivityLAS" : "בינוני",
	"Mid" : "מיד",
	"Middle" : "אמצעי",
	"Miles" : "מייל לשעה",
	"Mode" : "מצב",
	"Navigation" : "ניווט",
	"NavigationSignal" : "ניווט  ",
	"Near" : "קרוב",
	"Off" : "כבוי",
	"Often" : "תְכּוּפוֹת",
	"Often_Int_OFF" : "תְכּוּפוֹת",
	"OnDemand" : " לפי דרישה",
	"OnceAllDoors" : "פעם אחת: כל הדלתות",
	"OnceDriversDoorTwiceAllDoors" : "פעם 1: של נהג, פעמיים: כל הדלתות",
	"Open" : "פתוח",
	"ParkingSensorIndication" : "חיווי לחיישן חניה ",
	"ParkingSensorIndicator" : "נורית חיישן חניה",
	"RVMBuzzerVolume" : "Rear Vehicle Monitoring עוצמה",
	"Rare" : "נדיר",
	"Rare_Int_OFF" : "נדיר",
	"Reset" : "איפוס",
	"Rotation" : "סיבוב",
	"RumbleStrips" : "רצועה",
	"RumbleStrips_line" : "רצועה ",
	"RumbleVolume" : "עוצמת הטרטור",
	"SBSReset" : "האם אתה בטוח שברצונך להחזיר הגדרות Smart Brake Support לערך ברירת המחדל שלהם",
	"SBSResetError" : "שגיאה בהחלפת הגדרות  של Smart Brake Support.  האם ברצונך לנסות שוב?",
	"SBSResetProgress" : "משנה הגדרות של Smart Brake Support",
	"SBSSCBS" : "SBS/SCBS",
	"SBS_SCBSReset" : "האם אתה בטוח שברצונך להחזיר את הגדרות SBS/SCBS לערכי ברירת המחדל שלהן?",
	"SBS_SCBSResetError" : "שגיאת החלפת הגדרות SBS/SCBS. האם ברצונך לנסות שנית?",
	"SBS_SCBSResetProgress" : "משנה הגדרות SBS/SCBS",
	"SCBS" : "Smart City Brake Support",
	"SCBSReset" : "האם אתה בטוח שברצונך לשחזר את הגדרות SCBS לברירת המחדל של המפעל?",
	"SCBSResetError" : "לא ניתן לשחזר את הגדרות ה-SCBS לברירת המחדל של המפעל. האם ברצונך לנסות שוב?",
	"SCBSResetProgress" : "משחזר את הגדרות SCBS",
	"SLC_Buzzer" : "זמזום בלבד",
	"SLC_Off" : "כבוי ",
	"SLC_Sign" : "חזותי",
	"SLC_Sign_Buzzer" : "קולי וחזותי",
	"SLIReset" : "האם אתה בטוח שברצונך לשחזר את הגדרות אזהרת הגבלת המהירות לערכי ברירת המחדל?",
	"SLIResetError" : "לא ניתן לשחזר את הגדרות אזהרת הגבלת המהירות לברירת המחדל של המפעל. האם ברצונך לנסות שוב?",
	"SLIResetProgress" : "משחזר את הגדרות אזהרת הגבלת המהירות ",
	"SLI_HeadUpDisplay" : "Active Driving Display",
	"Safety" : "בטיחות",
	"Safetysettings" : "הגדרות בטיחות",
	"Sensitivity" : "רגישות",
	"Sensitivity_Intervention_OFF" : "אזהרה ",
	"Setting" : "הגדרות",
	"Settings" : "הגדרות",
	"Short" : "קרוב",
	"SideView" : "צד",
	"SideViewFrontView" : "צד+חזית",
	"SmartBrakeSupport" : "Smart Brake Support",
	"Sound" : "צליל",
	"SpeedAlarm" : "התראת מהירות",
	"SpeedLimitCaution" : "התראת הגבלת מהירות",
	"SpeedLimitInformation" : "אזהרת הגבלת מהירות",
	"SpeedLimitSign" : "הצגת הגבלת מהירות",
	"StepKilometers" : "{value}קמ\"ש",
	"StepMiles" : "{value} מייל לשעה",
	"StreetInformation" : "מידע על הרחוב",
	"Streetinfo_off" : "כבוי",
	"System" : "מערכת",
	"TSRReset" : "האם אתה בטוח שברצונך לשחזר את הגדרות מערכת זיהוי התמרורים לערכי ברירת המחדל?",
	"TSRResetError" : "לא ניתן לשחזר את הגדרות מערכת זיהוי התמרורים לברירת המחדל של המפעל. האם ברצונך לנסות שוב?",
	"TSRResetProgress" : "משחזר את הגדרות מערכת זיהוי התמרורים ",
	"TSR_Display" : "תצוגת תמרורים",
	"TSR_System" : "מערכת זיהוי תמרורים",
	"Tachometer" : "טכומטר",
	"ThreeFlashTurnSignal" : "שלושה איתותי פניה",
	"Timing" : "מדד זמן",
	"Turn" : "פניה",
	"TurnProgress" : "משנה הגדרות פניה",
	"TurnReset" : "האם אתה בטוח שברצונך להחזיר את הגדרות פניה לערכי ברירת המחדל שלהם?",
	"TurnResetError" : "שגיאת החלפה של הגדרות פניה. האם ברצונך לנסות שנית?",
	"TurnSettings" : "פנה",
	"TurnSignalIndicatorVolume" : "עוצמת איתות",
	"UnlockMode" : "נעילה מחדש אוטומטית",
	"Vehicle" : "רכב",
	"VehicleSettings" : "הגדרות רכב",
	"Vibration" : "רטט",
	"VibrationStrength" : "עוצמת רטט",
	"Vibration_Line" : "רטט",
	"ViewSwitchDisplay" : "הצגת ברירת מחדל",
	"ViewSwitchFunction" : "הצג תפקוד מפסק",
	"Volume" : "עוצמה",
	"WalkAwayLock" : "נעילת עזיבה",
	"Warning" : "אזהרה",
	"WarningDistance" : "אזהרת מרחק",
	"_0s" : "0 שניות",
	"_0seconds" : "0 שניות",
	"_10m" : "10 דקות",
	"_10minutes" : "10 דקות",
	"_120s" : "120 שניות",
	"_120seconds" : "120 שניות",
	"_15s" : "15 שניות",
	"_15seconds" : "15 שניות",
	"_30m" : "30 דקות",
	"_30minutes" : "30 דקות",
	"_30s" : "30 שניות",
	"_30seconds" : "30 שניות",
	"_60m" : "60 דקות",
	"_60minutes" : "60 דקות",
	"_60s" : "60 שניות",
	"_60seconds" : "60 שניות",
	"_7p5s" : "7.5 שניות",
	"_7p5seconds" : "7.5 שניות",
	"_90s" : "90 שניות",
	"_90seconds" : "90 שניות",
	"_AllDoors" : "הכל",
	"_Driver'sDoor" : "הנהג",
	"on" : "דולק",
};

framework.registerAppDictLoaded("vehsettings", "he_IL");