var Localization_vehsettingsAppDict_bg_BG = {
	//"stringId" : "localString"
	"360ViewCamera" : "Монитор за изглед на 360°",
	"AHBC" : "Adaptive LED Headlights",
	"Adaptive" : "Адаптив.",
	"AdaptiveFront-lightingSystem" : "Адапт. система за предно осветление",
	"AdaptiveLaneStreetTurn" : "Адаптивно – платно/улица/завой",
	"AlarmTiming" : "Cкорост",
	"AlertTiming" : "Време за сигнал",
	"Always" : "Винаги",
	"AtLine" : "В ред",
	"Auto" : "Авт.",
	"AutoHeadlightOn" : "Авт. вкл. фар-те",
	"AutoWiper" : "Чистачка със сензор за дъжд",
	"BSMBuzzerVolume" : "Blind Spot Monitoring обем",
	"BSMReset" : "Наистина ли искате да възстановите фабричните настройки по подразбиране за BSM?",
	"BSMResetError" : "Фабричните настройки по подразбиране за BSM не могат да бъдат възстановени. Искате ли да опитате отново?",
	"BSMResetProgress" : "Възстановяване на настройките за BSM",
	"BSMSystem" : "Система Blind Spot Monitoring ",
	"Beep" : "Сигнал",
	"BeepVolume" : "Сила на сигнала",
	"Beep_Line" : "Сигнал",
	"BeforeLine" : "П. ред",
	"Brightness" : "Яркост",
	"BrightnessControl" : "Регулиране на яркостта",
	"CHudNav_Maneuver" : "При маневр.",
	"CHudNav_Off" : "Изкл.",
	"CHudNav_TBT_Lane" : "Пътна лента и завои",
	"CHudNav_TBT_Street" : "Ул.&зав.",
	"Calibration" : "Яркост",
	"CautionSpeed" : "Праг за предупредителен сигнал",
	"CenterDisplay" : "Централен дисплей",
	"ChangingLASSettings" : "Промяна на настройки на LAS",
	"Clock" : "Часовни.",
	"Close" : "Затв.",
	"ComingHomeLights" : "Coming Home Light",
	"ComingHomeLightsTimer" : "Coming Home Light",
	"DRSS" : "Distance Recognition Support System",
	"DRSSReset" : "Наистина ли искате да върнете настройките за Distance Recognition Support System (DRSS) до техните стойности по подразбиране?",
	"DRSSResetError" : "Грешка при промяната на Distance Recognition Support System (DRSS). Искате ли да опитате отново?",
	"DRSSResetProgress" : "Промяна на Distance Recognition Support System (DRSS)",
	"Dark" : "Тъмно",
	"DaytimeRunningLights" : "Дневни светлини за движение",
	"Devices" : "Устр-ва",
	"Display" : "Дисплей",
	"DisplayInformation" : "Информация за показване",
	"DistanceRecognitionSupportSystem" : "Distance Recognition Support System",
	"DoorLock" : "Заключване на вратите",
	"DoorLockMode" : "Авт. закл. врати",
	"DoorLockReset" : "Наистина ли искате да върнете настройките за заключване на вратите на техните стойности по подразбиране?",
	"DoorLockResetError" : "Грешка при промяната на настройките за заключване на вратите. Искате ли да опитате отново?",
	"DoorLockResetProgress" : "Промяна на настройките за заключване на вратите",
	"DoorRelockTime" : "Време за авт. заключване",
	"DriverAlert" : "Driver Attention Alert",
	"Early" : "Рано",
	"ErrorBSMSettings" : "Грешка при промяна на настройките за BSM. Искате ли да опитате отново?",
	"ErrorLASSettings" : "Грешка при промяната на Lane-keep Assist System. Искате ли да опитате отново?",
	"FOWReset" : "Наистина ли искате да върнете настройките за Forward Obstruction Warning (FOW) на техните стойности по подразбиране?",
	"FOWResetError" : "Грешка при промяната на настройките за Forward Obstruction Warning (FOW). Искате ли да опитате отново?",
	"FOWResetProgress" : "Настройки за Forward Obstruction Warning (FOW)",
	"Far" : "Дал.",
	"ForwardObstructionWarning" : "Forward Obstruction Warning",
	"FrontCameraView" : "Изглед камера отпред",
	"GearShiftIndicator" : "Индикатор за смяна на предавка",
	"GuidelineDisplay" : "Динам. линии траектор.",
	"HUD" : "AD-Disp",
	"HUDDisplayInfoError" : "Настройките на информационния дисплей AD-Disp не могат да бъдат възстановени до стойностите си по подразбиране. Искате ли да пробвате отново?",
	"HUDDisplayInfoReset" : "Наистина ли искате да възстановите настройките на информационния дисплей AD-Disp до стойностите им по подразбиране?",
	"HUDDisplayInfoResetProgress" : "Възст. на настройките за информация на AD-Disp",
	"HUDJ78AReset" : "Сигурни ли сте, че желаете да върнете настройките по подразбиране на Active Driving Display дисплея?",
	"HUDJ78AResetError" : "Възникна грешка при нулиране на настройките на Active Driving Display дисплея. Желаете ли да опитате отново?",
	"HUDJ78AResetProgress" : "Нулиране на настройките на Active Driving Display дисплея",
	"HUDJ78ATab" : "Active Driving Display",
	"HUDReset" : "Наистина ли искате да върнете настройките за Active Driving Display на техните стойности по подразбиране?",
	"HUDResetError" : "Грешка при промяната на настройките за Active Driving Display. Искате ли да опитате отново?",
	"HUDResetProgress" : "Настройки за Active Driving Display",
	"HUDSettings" : "Настройки AD-Disp",
	"HUD_HeadUpDisplay" : "Active Driving Display",
	"HeadUpDisplay" : "Active Driving Display",
	"HeadlightOffTimer" : "Таймер изключване фарове",
	"HeadlightOnWarning" : "Втр. осв. предуп.",
	"HeadsUpDisplay" : "Active Driving Display",
	"Height" : "Височина",
	"High" : "Вис.",
	"HighBeamControl" : "High Beam Control",
	"High_SensitivityLAS" : "Вис.",
	"High_Vibration" : "Вис.",
	"ILB_Bright" : "Ярка",
	"ILB_Dark" : "Слаба",
	"ILB_Medium" : "Умерена",
	"ILB_Off" : "Изкл. ",
	"IgONAutoDisplay" : "Авт. показване на 360° View Monitor",
	"InterioLightsTimeOutDoorsClosed" : "Вътр. освет. – вр. е затв.",
	"InterioLightsTimeOutDoorsOpen" : "Вътр. освет. – вр. е отвор.",
	"InteriorLightTimeoutDoorClosedTitle" : "Вътр. освет. – вр. са затв.",
	"InteriorLightTimeoutDoorOpenTitle" : "Вътр. освет. – вр. са отв.",
	"InteriorLightingBrightness" : "Вътрешно осветление",
	"Intervention" : "Интервенция",
	"InterventionTiming" : "Време за интер.",
	"KeylessLockBeepVol" : "Сила сигн. закл. без ключ",
	"Kilometers" : "км/ч",
	"LASAlert" : "Предупр. LAS",
	"LASDefaultValues" : "Наистина ли искате да върнете настройките на Lane-keep Assist System към фабричните?",
	"LASEarly" : "Рано",
	"LASLate" : "Късно",
	"LASSound" : "Вид предупреждение",
	"LASTiming" : "LAS Времена",
	"LDWSReset" : "Наистина ли искате да върнете настройките за Lane Departure Warning System (LDWS) на техните стойности по подразбиране?",
	"LDWSResetError" : "Грешка при промяната на настройките за  Lane Departure Warning System (LDWS) Settings. Искате ли да опитате отново?",
	"LDWSResetProgress" : "Настройки за Lane Departure Warning System (LDWS) Settings",
	"LDWSTiming" : "Времена за LDWS",
	"LaneDepartureAlert" : "Аларма за напускане на алеята",
	"LaneDepartureWarningSystem" : "Lane Departure Warning System",
	"LaneKeepAssistSystem" : "Lane-keep Assist System",
	"Late" : "Късно",
	"LeavingHomeLights" : "Leaving Home Light",
	"Light" : "Светло",
	"LightOnReminderVolume" : "Напм. вкл. свтл.",
	"Lighting" : "Осветление",
	"LightingReset" : "Наистина ли искате да върнете настройките за осветлението на техните стойности по подразбиране?",
	"LightingResetError" : "Грешка при промяната на настройките за осветлението. Искате ли да опитате отново?",
	"LightingResetProgress" : "Промяна на настройките за осветлението",
	"LockShiftFromP" : "Закл.: превкл. скор., разл. от „парк.“ ",
	"LockShiftFromPUnlockInPark" : "Закл.: не парк. – откл.: при парк.",
	"LockUnlock" : "Закл.: при шоф. откл.: при парк.",
	"LockWhenDriving" : "Заключване: при шофиране",
	"LockWhenDrivingUnlockIGNoff" : "Закл.: при шоф. откл: изкл. зплв.",
	"Long" : "Далеч",
	"Low" : "Ниско",
	"Low_SensitivityLAS" : "Ниско",
	"Low_Vibration" : "Ниско",
	"Manual" : "Ръчно",
	"Med" : "Средно",
	"Medium" : "Средно",
	"MediumDark" : "здрач",
	"MediumLight" : "не тъмно",
	"Medium_Int_OFF" : "Средно",
	"Medium_SensitivityLAS" : "Средно",
	"Mid" : "Средно",
	"Middle" : "Сред.",
	"Miles" : "mph",
	"Mode" : "Режим",
	"Navigation" : "Навигация",
	"NavigationSignal" : "Навигация  ",
	"Near" : "Близо",
	"Off" : "Изкл.",
	"Often" : "Често",
	"Often_Int_OFF" : "Често",
	"OnDemand" : "При пои.",
	"OnceAllDoors" : "Веднъж: всички врати",
	"OnceDriversDoorTwiceAllDoors" : "1 път: на вод., 2 пъти: вс. вр.",
	"Open" : "Отв.",
	"ParkingSensorIndication" : "Индикатор на сензор за паркинг ",
	"ParkingSensorIndicator" : "Индикатор на сензор за паркиране",
	"RVMBuzzerVolume" : "Rear Vehicle Monitoring обем",
	"Rare" : "Рядко",
	"Rare_Int_OFF" : "Рядко",
	"Reset" : "Нулиране",
	"Rotation" : "Въртене",
	"RumbleStrips" : "ПЛ",
	"RumbleStrips_line" : "ПЛ ",
	"RumbleVolume" : "Сила звук гуми",
	"SBSReset" : "Наистина ли искате да върнете настройките за Smart Brake Support (SBS) на техните стойности по подразбиране?",
	"SBSResetError" : "Грешка при промяната на настройките за Smart Brake Support (SBS). Искате ли да опитате отново?",
	"SBSResetProgress" : "Промяна на настройките за Smart Brake Support (SBS)",
	"SBSSCBS" : "SBS/SCBS",
	"SBS_SCBSReset" : "Наистина ли искате да върнете настройките за SBS/SCBS на техните стойности по подразбиране?",
	"SBS_SCBSResetError" : "Грешка при промяната на настройките за SBS/SCBS. Искате ли да опитате отново?",
	"SBS_SCBSResetProgress" : "Промяна на настройките за SBS/SCBS",
	"SCBS" : "Smart City Brake Support",
	"SCBSReset" : "Наистина ли искате да възстановите фабричните настройки по подразбиране за SCBS?",
	"SCBSResetError" : "Фабричните настройки по подразбиране за SCBS не могат да бъдат възстановени. Искате ли да опитате отново?",
	"SCBSResetProgress" : "Възстановяване на настройките за SCBS",
	"SLC_Buzzer" : "Само звук",
	"SLC_Off" : "Изкл. ",
	"SLC_Sign" : "Визуален",
	"SLC_Sign_Buzzer" : "Звук и картина",
	"SLIReset" : "Наистина ли искате да възстановите настройките за предупреждение за ограничение на скоростта до стойностите им по подразбиране?",
	"SLIResetError" : "Настройките за предупреждение за ограничение на скоростта не могат да се възстановят до фабричните стойности по подразбиране. Искате ли да опитате отново?",
	"SLIResetProgress" : "Възстановяване на настройките за предупреждение за ограничение на скоростта",
	"SLI_HeadUpDisplay" : "Active Driving Display",
	"Safety" : "Безоп.",
	"Safetysettings" : "Прдп. вкл. фар.",
	"Sensitivity" : "Чувствителност",
	"Sensitivity_Intervention_OFF" : "Предупреждение ",
	"Setting" : "Настройка",
	"Settings" : "Настройки",
	"Short" : "Близо",
	"SideView" : "Отстрани",
	"SideViewFrontView" : "Отстрани+отпред",
	"SmartBrakeSupport" : "Smart Brake Support",
	"Sound" : "Звук",
	"SpeedAlarm" : "Сигнал за скорост",
	"SpeedLimitCaution" : "Предупр. огранич. скорост",
	"SpeedLimitInformation" : "Предупр. огранич. скорост",
	"SpeedLimitSign" : "Показв. огранич. скорост",
	"StepKilometers" : "{value} км/ч",
	"StepMiles" : "{value} mph",
	"StreetInformation" : "Информация за улица",
	"Streetinfo_off" : "Изкл.",
	"System" : "Система",
	"TSRReset" : "Наистина ли искате да възстановите настройките на системата за разпознаване на пътните знаци до стойностите им по подразбиране?",
	"TSRResetError" : "Настройките на системата за разпознаване на пътните знаци не могат да се възстановят до фабричните стойности по подразбиране. Искате ли да опитате отново?",
	"TSRResetProgress" : "Възстановяване на настройките на системата за разпознаване на пътните знаци ",
	"TSR_Display" : "Показване на пътните знаци",
	"TSR_System" : "Система за разпознаване на пътните знаци",
	"Tachometer" : "Тахометър",
	"ThreeFlashTurnSignal" : "Мигач с 3 примигвания",
	"Timing" : "Времена",
	"Turn" : "Завиване",
	"TurnProgress" : "Промяна на настройките за завиването",
	"TurnReset" : "Наистина ли искате да върнете настройките за завиването на техните стойности по подразбиране?",
	"TurnResetError" : "Грешка при промяната на настройките за завиването. Искате ли да опитате отново?",
	"TurnSettings" : "Завиване",
	"TurnSignalIndicatorVolume" : "Сила на сигнала мигач",
	"UnlockMode" : "Режим на отключване",
	"Vehicle" : "Автмоб.",
	"VehicleSettings" : "Настр. автом.",
	"Vibration" : "Вибрация",
	"VibrationStrength" : "Сила на вибр.",
	"Vibration_Line" : "Вибрация",
	"ViewSwitchDisplay" : "Изглед по подразбиране",
	"ViewSwitchFunction" : "Функция за превкл. м/у изгледите",
	"Volume" : "Сила на звука",
	"WalkAwayLock" : "Заключване при отдалечаване",
	"Warning" : "Предупреждение",
	"WarningDistance" : "Разст. предупр.",
	"_0s" : "0 с",
	"_0seconds" : "0 секунди",
	"_10m" : "10 мин",
	"_10minutes" : "10 минути",
	"_120s" : "120 с",
	"_120seconds" : "120 секунди",
	"_15s" : "15 с",
	"_15seconds" : "15 секунди",
	"_30m" : "30 мин",
	"_30minutes" : "30 минути",
	"_30s" : "30 с",
	"_30seconds" : "30 секунди",
	"_60m" : "60 мин",
	"_60minutes" : "60 минути",
	"_60s" : "60 с",
	"_60seconds" : "60 секунди",
	"_7p5s" : "7,5 с",
	"_7p5seconds" : "7,5 секунди",
	"_90s" : "90 с",
	"_90seconds" : "90 секунди",
	"_AllDoors" : "Всички",
	"_Driver'sDoor" : "На вод.",
	"on" : "Вкл.",
};

framework.registerAppDictLoaded("vehsettings", "bg_BG");