var Localization_vehsettingsAppDict_hr_HR = {
	//"stringId" : "localString"
	"360ViewCamera" : "Monitor s kutom prikaza od 360°",
	"AHBC" : "Adaptive LED Headlights",
	"Adaptive" : "Prilagodljivo",
	"AdaptiveFront-lightingSystem" : "Sistem adaptivnog prednjeg osvjetljenja",
	"AdaptiveLaneStreetTurn" : "Prilagod. sust. vozni trak/ulicu/skret.",
	"AlarmTiming" : "Postavke brzine",
	"AlertTiming" : "Vrijed. do alarma",
	"Always" : "Uvijek",
	"AtLine" : "U tr.",
	"Auto" : "Auto",
	"AutoHeadlightOn" : "Auto. uklj. pred. svjetla",
	"AutoWiper" : "Senzorski brisač za kišu",
	"BSMBuzzerVolume" : "Blind Spot Monitoring Glasnoća",
	"BSMReset" : "Jeste li sigurni da želite vratiti postavke BSM na tvornički zadane postavke?",
	"BSMResetError" : "Nije moguće vratiti postavke BSM na tvornički zadane vrijednosti. Želite li ponovno pokušati?",
	"BSMResetProgress" : "Vraćanje postavki BSM",
	"BSMSystem" : "Sustav Blind Spot Monitoring ",
	"Beep" : "Bip",
	"BeepVolume" : "Glasnoća bipa",
	"Beep_Line" : "Bip",
	"BeforeLine" : "Pr. lin.",
	"Brightness" : "Svjetlina",
	"BrightnessControl" : "Regulacija svjetline",
	"CHudNav_Maneuver" : "Pri manevr.",
	"CHudNav_Off" : "Isključi",
	"CHudNav_TBT_Lane" : "Vođenje trakom i po skretanjima",
	"CHudNav_TBT_Street" : "Naziv ulice i po skretanjima",
	"Calibration" : "Svjetlina",
	"CautionSpeed" : "Prag za alarmiranje",
	"CenterDisplay" : "Središnji zaslon",
	"ChangingLASSettings" : "Promjena postavki LAS  sustava",
	"Clock" : "Sat",
	"Close" : "Zatv.",
	"ComingHomeLights" : "Coming Home Light",
	"ComingHomeLightsTimer" : "Coming Home Light",
	"DRSS" : "Distance Recognition Support System",
	"DRSSReset" : "Jeste li sigurni da postavke Distance Recognition Support System (DRSS) želite vratiti na zadane vrijednosti?",
	"DRSSResetError" : "Pogreška promjene Distance Recognition Support System (DRSS) Želite li ponovno pokušati?",
	"DRSSResetProgress" : "Promjena postavki Distance Recognition Support System (DRSS)",
	"Dark" : "Tamno",
	"DaytimeRunningLights" : "Dnevna svjetla",
	"Devices" : "Uređaji",
	"Display" : "Prikaz",
	"DisplayInformation" : "Zaslonske informacije",
	"DistanceRecognitionSupportSystem" : "Distance Recognition Support System",
	"DoorLock" : "Blokada vrata",
	"DoorLockMode" : "Način automatske blokade vrata",
	"DoorLockReset" : "Jeste li sigurni da postavke blokade vrata želite vratiti na zadane vrijednosti?",
	"DoorLockResetError" : "Pogreška promjene postavki blokade vrata. Želite li ponovno pokušati?",
	"DoorLockResetProgress" : "Promjena postavki blokade vrata",
	"DoorRelockTime" : "Vrij. ponovnog auto. zaklj.",
	"DriverAlert" : "Driver Attention Alert",
	"Early" : "Rano",
	"ErrorBSMSettings" : "Pogreška u promjeni postavki BSM. Želite li ponovno pokušati?",
	"ErrorLASSettings" : "Pogreška promjene Lane-keep Assist System. Želite li ponovno pokušati?",
	"FOWReset" : "Jeste li sigurni da postavke Forward Obstruction Warning želite vratiti na zadane vrijednosti?",
	"FOWResetError" : "Pogreška promjene Forward Obstruction Warning postavki. Želite li ponovno pokušati?",
	"FOWResetProgress" : "Promjena postavki Forward Obstruction Warning",
	"Far" : "Daleko",
	"ForwardObstructionWarning" : "Forward Obstruction Warning",
	"FrontCameraView" : "Prikaz prednje kamere",
	"GearShiftIndicator" : "Indikator promjene brzine",
	"GuidelineDisplay" : "Dinamične linije puta",
	"HUD" : "AD-Disp",
	"HUDDisplayInfoError" : "Vraćanje postavki podataka zaslona AD-Disp na tvorničke postavke nije uspjelo. Želite li pokušati ponovno?",
	"HUDDisplayInfoReset" : "Jeste li sigurni da želite vratiti postavke podataka zaslona AD-Disp na njihove zadane vrijednosti?",
	"HUDDisplayInfoResetProgress" : "Vraćanje postavki podataka zaslona AD-Disp.",
	"HUDJ78AReset" : "Jeste li sigurni da želite vratiti postavke za Active Driving Display na zadane vrijednosti?",
	"HUDJ78AResetError" : "Došlo je do pogreške prilikom ponovnog postavljanja postavki za Active Driving Display. Želite li pokušati ponovno?",
	"HUDJ78AResetProgress" : "Ponovno postavljanje postavki za Active Driving Display",
	"HUDJ78ATab" : "Active Driving Display",
	"HUDReset" : "Jeste li sigurni da postavke Active Driving Display želite vratiti na zadane vrijednosti?",
	"HUDResetError" : "Pogreška promjene Active Driving Display postavki. Želite li ponovno pokušati?",
	"HUDResetProgress" : "Promjena postavki AD-Disp",
	"HUDSettings" : "Postavke za AD-Disp",
	"HUD_HeadUpDisplay" : "Sustav prikaza informacija AD-Disp",
	"HeadUpDisplay" : "Active Driving Display",
	"HeadlightOffTimer" : "Mjer.vrem. isklj. pred. svjetla",
	"HeadlightOnWarning" : "Upoz. za uklj. pred. svj.",
	"HeadsUpDisplay" : "Active Driving Display",
	"Height" : "Visina",
	"High" : "Visoko",
	"HighBeamControl" : "High Beam Control",
	"High_SensitivityLAS" : "Visoko",
	"High_Vibration" : "Visoko",
	"ILB_Bright" : "Jako",
	"ILB_Dark" : "Zatamnjeno",
	"ILB_Medium" : "Srednje",
	"ILB_Off" : "Isključeno ",
	"IgONAutoDisplay" : "Automatski prikaz sustava 360° View Monitor",
	"InterioLightsTimeOutDoorsClosed" : "Istek vr. unut. svj. - vrata zatv.",
	"InterioLightsTimeOutDoorsOpen" : "Istek vr. unut. svjetla - vrata otv.",
	"InteriorLightTimeoutDoorClosedTitle" : "Istek vre. unut. svj. - vrata zatv.",
	"InteriorLightTimeoutDoorOpenTitle" : "Istek vre. unut. svj. - vrata otv.",
	"InteriorLightingBrightness" : "Ambijent. osvjetljenje",
	"Intervention" : "Korekcija upravljanja",
	"InterventionTiming" : "Vr. do kor. upr.",
	"KeylessLockBeepVol" : "Glasnoća brave dalj. otklj.",
	"Kilometers" : "km/h",
	"LASAlert" : "Upozorenje LAS",
	"LASDefaultValues" : "Želite li zaista postavke Lane-keep Assist System vratiti na zadane vrijednosti?",
	"LASEarly" : "Rano",
	"LASLate" : "Kasno",
	"LASSound" : "Vrsta upozorenja",
	"LASTiming" : "Mjerenje vremena LAS-a",
	"LDWSReset" : "Jeste li sigurni da postavke Lane Departure Warning System želite vratiti na zadane vrijednosti?",
	"LDWSResetError" : "Pogreška promjene Lane Departure Warning System postavki. Želite li ponovno pokušati?",
	"LDWSResetProgress" : "Promjena postavki Lane Departure Warning System",
	"LDWSTiming" : "Mjerenje vremena LDWS-a",
	"LaneDepartureAlert" : "Upozorenje o skretanju iz traka",
	"LaneDepartureWarningSystem" : "Lane Departure Warning System",
	"LaneKeepAssistSystem" : "Lane-keep Assist System",
	"Late" : "Kasno",
	"LeavingHomeLights" : "Leaving Home Light",
	"Light" : "Svjetlo",
	"LightOnReminderVolume" : "Gl. pods. uklj. svj.",
	"Lighting" : "Svjetla",
	"LightingReset" : "Jeste li sigurni da postavke svjetla želite vratiti na zadane vrijednosti?",
	"LightingResetError" : "Pogreška promjene postavki svjetla. Želite li ponovno pokušati?",
	"LightingResetProgress" : "Promjena postavki svjetla",
	"LockShiftFromP" : "Zaklj.: prom. iz st. prij. za parkiranje ",
	"LockShiftFromPUnlockInPark" : "Zklj:Ubac. u brz. iz p.pol. - otklj:p.pol.",
	"LockUnlock" : "Blokada: u vožnji Deblokada: parkirano",
	"LockWhenDriving" : "Zaključaj: prilikom vožnje",
	"LockWhenDrivingUnlockIGNoff" : "Zaklj.: pri vož. Otklj.: palj. isklj.",
	"Long" : "Daleko",
	"Low" : "Nisko",
	"Low_SensitivityLAS" : "Nisko",
	"Low_Vibration" : "Nisko",
	"Manual" : "Ručno",
	"Med" : "Sred",
	"Medium" : "Srednje",
	"MediumDark" : "Sred tam.",
	"MediumLight" : "Sred svij.",
	"Medium_Int_OFF" : "Sred",
	"Medium_SensitivityLAS" : "Sred",
	"Mid" : "Sred",
	"Middle" : "Sred.",
	"Miles" : "mph",
	"Mode" : "Način rada",
	"Navigation" : "Navigacija",
	"NavigationSignal" : "Navigacija  ",
	"Near" : "U bliz.",
	"Off" : "Isključi",
	"Often" : "Često",
	"Often_Int_OFF" : "Često",
	"OnDemand" : "Na zah.",
	"OnceAllDoors" : "Jednom: sva vrata",
	"OnceDriversDoorTwiceAllDoors" : "Jednom: vozačeva Dvaput: sva vrata",
	"Open" : "Otvori",
	"ParkingSensorIndication" : "Upozorenje senzora za parkiranje. ",
	"ParkingSensorIndicator" : "Pokazivač senzora za parkiranje",
	"RVMBuzzerVolume" : "Rear Vehicle Monitoring Glasnoća",
	"Rare" : "Rijetko",
	"Rare_Int_OFF" : "Rijetko",
	"Reset" : "Poništi",
	"Rotation" : "Rotacija",
	"RumbleStrips" : "Sig. b.",
	"RumbleStrips_line" : "Sig. b. ",
	"RumbleVolume" : "Glasnoća tutn.",
	"SBSReset" : "Jeste li sigurni da postavke Smart Brake Support (SBS) želite vratiti na zadane vrijednosti?",
	"SBSResetError" : "Pogreška promjene Smart Brake Support (SBS) Želite li ponovno pokušati?",
	"SBSResetProgress" : "Promjena postavki Smart Brake Support (SBS)",
	"SBSSCBS" : "SBS/SCBS",
	"SBS_SCBSReset" : "Jeste li sigurni da postavke SBS/SCBS želite vratiti na zadane vrijednosti?",
	"SBS_SCBSResetError" : "Pogreška promjene SBS/SCBS postavki. Želite li ponovno pokušati?",
	"SBS_SCBSResetProgress" : "Promjena postavki SBS/SCBS",
	"SCBS" : "Smart City Brake Support",
	"SCBSReset" : "Jeste li sigurni da želite vratiti postavke SCBS na tvornički zadane postavke?\"",
	"SCBSResetError" : "Nije moguće vratiti postavke SCBS na tvornički zadane vrijednosti. Želite li ponovno pokušati?\"",
	"SCBSResetProgress" : "Vraćanje postavki SCBS",
	"SLC_Buzzer" : "Samo zvučno",
	"SLC_Off" : "Isključeno ",
	"SLC_Sign" : "Vizualno",
	"SLC_Sign_Buzzer" : "Zvučno i vizualno",
	"SLIReset" : "Jeste li sigurni da postavke upozorenja za ograničenje brzine želite vratiti na zadane vrijednosti?",
	"SLIResetError" : "Postavke upozorenja za ograničenje brzine ne mogu se vratiti na tvornički zadane vrijednosti. Želite li ponovno pokušati?",
	"SLIResetProgress" : "Vraćanje postavki upozorenja za ograničenje brzine",
	"SLI_HeadUpDisplay" : "Sustav prikaza informacija AD-Disp",
	"Safety" : "Sigurnost",
	"Safetysettings" : "Postavke sig.",
	"Sensitivity" : "Osjetljivost",
	"Sensitivity_Intervention_OFF" : "Upozorenje ",
	"Setting" : "Postavke",
	"Settings" : "Postavke",
	"Short" : "Blizu",
	"SideView" : "Strana",
	"SideViewFrontView" : "Bočno + Sprijeda",
	"SmartBrakeSupport" : "Smart Brake Support",
	"Sound" : "Zvuk",
	"SpeedAlarm" : "Alarm za brzinu",
	"SpeedLimitCaution" : "Alarm. za ograničenje brzine",
	"SpeedLimitInformation" : "Upozorenje za ograničenje brzine",
	"SpeedLimitSign" : "Prikaz ograničenja brzine",
	"StepKilometers" : "{value} km/h",
	"StepMiles" : "{value} mph",
	"StreetInformation" : "Informacije o ulici",
	"Streetinfo_off" : "Isključeno",
	"System" : "Sustav",
	"TSRReset" : "Jeste li sigurni da želite postavke sustava za prepoznavanje prometnih znakova vratiti na zadane vrijednosti?",
	"TSRResetError" : "Nije moguće vraćanje postavki  sustava za prepoznavanje prometnih znakova na tvornički zadane vrijednosti. Želite li ponovno pokušati?",
	"TSRResetProgress" : "Vraćanje postavki sustava za prepoznavanje prometnih znakova ",
	"TSR_Display" : "Prikaz prometnih znakova",
	"TSR_System" : "Sustav za prepoznavanje prometnih znakova",
	"Tachometer" : "Tahometar",
	"ThreeFlashTurnSignal" : "Signal skretanja s tri treptaja",
	"Timing" : "Mjerač vremena",
	"Turn" : "Pokazivači smjera",
	"TurnProgress" : "Promjena postavki pokazivača smjera",
	"TurnReset" : "Jeste li sigurni da postavke pokazivača smjera želite vratiti na zadane vrijednosti?",
	"TurnResetError" : "Pogreška promjene postavki pokazivača smjera. Želite li ponovno pokušati?",
	"TurnSettings" : "Pokazivači smjera",
	"TurnSignalIndicatorVolume" : "Glasnoća pokaziv. smjera",
	"UnlockMode" : "Način otključavanja",
	"Vehicle" : "Vozilo",
	"VehicleSettings" : "Postavke vozila",
	"Vibration" : "Vibracija",
	"VibrationStrength" : "Jačina vibracije",
	"Vibration_Line" : "Vibracija",
	"ViewSwitchDisplay" : "Zadani prikaz",
	"ViewSwitchFunction" : "Pogledaj funkciju izmjenjivača",
	"Volume" : "Glasnoća",
	"WalkAwayLock" : "Blokada kod napuštanja",
	"Warning" : "Upozorenje",
	"WarningDistance" : "Udalj. upozorenja",
	"_0s" : "0 s",
	"_0seconds" : "0 sekundi",
	"_10m" : "10 min",
	"_10minutes" : "10 minuta",
	"_120s" : "120 s",
	"_120seconds" : "120 sekundi",
	"_15s" : "15 s",
	"_15seconds" : "15 sekundi",
	"_30m" : "30 min",
	"_30minutes" : "30 minuta",
	"_30s" : "30 s",
	"_30seconds" : "30 sekundi",
	"_60m" : "60 min",
	"_60minutes" : "60 minuta",
	"_60s" : "60 s",
	"_60seconds" : "60 sekundi",
	"_7p5s" : "7,5 s",
	"_7p5seconds" : "7,5 sekundi",
	"_90s" : "90 s",
	"_90seconds" : "90 sekundi",
	"_AllDoors" : "Sve",
	"_Driver'sDoor" : "Voz.",
	"on" : "Uključi",
};

framework.registerAppDictLoaded("vehsettings", "hr_HR");