var Localization_vehsettingsAppDict_lv_LV = {
	//"stringId" : "localString"
	"360ViewCamera" : "360° skata monitors",
	"AHBC" : "Adaptive LED Headlights",
	"Adaptive" : "Adaptīva",
	"AdaptiveFront-lightingSystem" : "Adaptīvā priekšējās apgaismes sistēma",
	"AdaptiveLaneStreetTurn" : "Pielāgošanās joslai/ielai/pagriez.",
	"AlarmTiming" : "Ātruma",
	"AlertTiming" : "Brīdin. ierosme",
	"Always" : "Vienmēr",
	"AtLine" : "Pie līn.",
	"Auto" : "Aut.",
	"AutoHeadlightOn" : "Autom. priekš. lukt. iesl.",
	"AutoWiper" : "Logu tīrītāji ar lietus sensoru",
	"BSMBuzzerVolume" : "Blind Spot Monitoring Skaļums",
	"BSMReset" : "Vai tiešām vēlaties atjaunot BSM iestatījumus uz rūpnīcas noklusējuma iestatījumiem?",
	"BSMResetError" : "Nevar atjaunot BSM iestatījumus uz rūpnīcas noklusējuma iestatījumiem. Vai mēģināt vēlreiz?",
	"BSMResetProgress" : "Notiek BSM iestatījumu atjaunošana",
	"BSMSystem" : "BSM sistēma ",
	"Beep" : "Signāls",
	"BeepVolume" : "Signāla skaļums",
	"Beep_Line" : "Signāls",
	"BeforeLine" : "Pirms",
	"Brightness" : "Spilgtums",
	"BrightnessControl" : "Spilgtuma vadība",
	"CHudNav_Maneuver" : "Manevra laikā",
	"CHudNav_Off" : "Izslēgts",
	"CHudNav_TBT_Lane" : "Josl.vad",
	"CHudNav_TBT_Street" : "Ielu nos",
	"Calibration" : "Spilgtums",
	"CautionSpeed" : "Brīdinājuma slieksnis",
	"CenterDisplay" : "Centrālais displejs",
	"ChangingLASSettings" : "LAS sistēmas iestatījumu mainīšana",
	"Clock" : "Pulkst.",
	"Close" : "Aizv.",
	"ComingHomeLights" : "Coming Home Light",
	"ComingHomeLightsTimer" : "Coming Home Light",
	"DRSS" : "Distance Recognition Support System",
	"DRSSReset" : "Vai tiešām atjaunot Distance Recognition Support System (DRSS) uz to noklusējuma vērtībām?",
	"DRSSResetError" : "Kļūda, mainot Distance Recognition Support System (DRSS).  Vai mēģināt vēlreiz?",
	"DRSSResetProgress" : "Maina Distance Recognition Support System (DRSS)",
	"Dark" : "Tumšs",
	"DaytimeRunningLights" : "Dienas gaitas gaismas",
	"Devices" : "Ierīces",
	"Display" : "Displejs",
	"DisplayInformation" : "Displeja informācija",
	"DistanceRecognitionSupportSystem" : "Distance Recognition Support System",
	"DoorLock" : "Durvju slēdzene",
	"DoorLockMode" : "Autom. durvju bloķēš. rež.",
	"DoorLockReset" : "Vai tiešām atjaunot durvju slēdzenes iestatījumus uz to noklusējuma vērtībām?",
	"DoorLockResetError" : "Kļūda, mainot durvju slēdzenes iestatījumus. Vai mēģināt vēlreiz?",
	"DoorLockResetProgress" : "Maina durvju slēdzenes iestatījumus",
	"DoorRelockTime" : "Autom. atbloķ. laiks",
	"DriverAlert" : "Driver Attention Alert",
	"Early" : "Agrīna",
	"ErrorBSMSettings" : "Mainot BSM iestatījumus, radusies kļūda. Vai mēģināt vēlreiz?",
	"ErrorLASSettings" : "Kļūda, mainot Lane-keep Assist System. Vai vēlaties mēģināt vēlreiz?",
	"FOWReset" : "Vai tiešām atjaunot  Forward Obstruction Warning (FOW) uz to noklusējuma vērtībām?",
	"FOWResetError" : "Kļūda, mainot Forward Obstruction Warning (FOW). Vai mēģināt vēlreiz?",
	"FOWResetProgress" : "Maina Forward Obstruction Warning (FOW)",
	"Far" : "Tālu",
	"ForwardObstructionWarning" : "Forward Obstruction Warning",
	"FrontCameraView" : "Priekš. kameras skats",
	"GearShiftIndicator" : "Ātrumpārslēga indikators",
	"GuidelineDisplay" : "Aktīvās joslu līnijas",
	"HUD" : "AD-Disp",
	"HUDDisplayInfoError" : "Nav iespējams atiestatīt AD-Disp displeja informācijas iestatījumus uz rūpnīcas noklusējuma vērtībām. Vai vēlaties atkārtot?",
	"HUDDisplayInfoReset" : "Vai tiešām vēlaties atiestatīt AD-Disp displeja informācijas iestatījumus uz to noklusējuma vērtībām?",
	"HUDDisplayInfoResetProgress" : "AD-Disp displeja informācijas iestatījumu atiestatīšana",
	"HUDJ78AReset" : "Vai tiešām vēlaties atiestatīt brīdinājuma Active Driving Display iestatījumus uz to noklusējuma vērtībām?",
	"HUDJ78AResetError" : "Brīdinājuma Active Driving Display iestatījumu atiestatīšanas laikā radās kļūda. Vai vēlaties atkārtot?",
	"HUDJ78AResetProgress" : "Brīdinājuma Active Driving Display iestatījumu atiestatīšana",
	"HUDJ78ATab" : "Active Driving Display",
	"HUDReset" : "Vai tiešām atjaunot Active Driving Display uz to noklusējuma vērtībām?",
	"HUDResetError" : "Kļūda, mainot Active Driving Display. Vai mēģināt vēlreiz?",
	"HUDResetProgress" : "Maina Active Driving Display",
	"HUDSettings" : "Brīdinājuma AD-Disp iestatījumi",
	"HUD_HeadUpDisplay" : "Active Driving Display",
	"HeadUpDisplay" : "Active Driving Display",
	"HeadlightOffTimer" : "Priekš. lukturu izsl. taimeris",
	"HeadlightOnWarning" : "Priekš. lukt. iesl. brīdin.",
	"HeadsUpDisplay" : "Active Driving Display",
	"Height" : "Augstums",
	"High" : "Aug.",
	"HighBeamControl" : "High Beam Control",
	"High_SensitivityLAS" : "Aug.",
	"High_Vibration" : "Aug.",
	"ILB_Bright" : "Gaišs",
	"ILB_Dark" : "Blāvs",
	"ILB_Medium" : "Vidējs",
	"ILB_Off" : "Izslēgts ",
	"IgONAutoDisplay" : "Automātiskais „360° View Monitor” skats",
	"InterioLightsTimeOutDoorsClosed" : "Iekš.apgaism. noildze-durvis aizv.",
	"InterioLightsTimeOutDoorsOpen" : "Iekš.apgaism. noildze-durvis atv.",
	"InteriorLightTimeoutDoorClosedTitle" : "Iekš. apg. noil. — durvis aizv.",
	"InteriorLightTimeoutDoorOpenTitle" : "Iekš. apg. noil. — durvis atv.",
	"InteriorLightingBrightness" : "Salona apgaismojums",
	"Intervention" : "Iejaukšanās",
	"InterventionTiming" : "Iejaukšanās laiks",
	"KeylessLockBeepVol" : "Bezatslēgas slēdz. sign. skaļums",
	"Kilometers" : "km/h",
	"LASAlert" : "LAS trauksme",
	"LASDefaultValues" : "Vai tiešām vēlaties atjaunot Lane-keep Assist System iestatījumus uz to noklusējuma vērtībām?",
	"LASEarly" : "Agrīna",
	"LASLate" : "Vēla",
	"LASSound" : "Brīdinājuma veids",
	"LASTiming" : "LAS laika koordinācija",
	"LDWSReset" : "Vai tiešām atjaunot Lane Departure Warning System (LDWS) uz to noklusējuma vērtībām?",
	"LDWSResetError" : "Kļūda, mainot Lane Departure Warning System (LDWS). Vai mēģināt vēlreiz?",
	"LDWSResetProgress" : "Maina Lane Departure Warning System (LDWS)",
	"LDWSTiming" : "LDWS laika koord.",
	"LaneDepartureAlert" : "Brīdin. par novirz.no joslas",
	"LaneDepartureWarningSystem" : "Lane Departure Warning System",
	"LaneKeepAssistSystem" : "Lane-keep Assist System",
	"Late" : "Vēla",
	"LeavingHomeLights" : "Leaving Home Light",
	"Light" : "Gaišs",
	"LightOnReminderVolume" : "Iesl.gaism atg.skaļ.",
	"Lighting" : "Apgaismojums",
	"LightingReset" : "Vai tiešām atjaunot apgaismojuma iestatījumus uz to noklusējuma vērtībām?",
	"LightingResetError" : "Kļūda, mainot apgaismojuma iestatījumus. Vai mēģināt vēlreiz?",
	"LightingResetProgress" : "Maina apgaismojuma iestatījumus",
	"LockShiftFromP" : "Bloķ.: no stāv. pārnes. ",
	"LockShiftFromPUnlockInPark" : "Bloķ: no stāv.pārn. Atbloķ: stāv.pārn.",
	"LockUnlock" : "Bloķēt: braucot. Atbloķēt: parkošanās",
	"LockWhenDriving" : "Bloķēt: braukšanas laikā",
	"LockWhenDrivingUnlockIGNoff" : "Bloķ.: braucot Atbloķ.: aizd. izsl.",
	"Long" : "Tālu",
	"Low" : "Zems",
	"Low_SensitivityLAS" : "Zems",
	"Low_Vibration" : "Zems",
	"Manual" : "Rok.gr.",
	"Med" : "Vid.",
	"Medium" : "Vidēja",
	"MediumDark" : "Vid. Tumš",
	"MediumLight" : "Vid. gaišs",
	"Medium_Int_OFF" : "Vid.",
	"Medium_SensitivityLAS" : "Vid.",
	"Mid" : "Vid.",
	"Middle" : "Vidū",
	"Miles" : "jūdzes/h",
	"Mode" : "Režīms",
	"Navigation" : "Navigācija",
	"NavigationSignal" : "Navigācija  ",
	"Near" : "Tuvu",
	"Off" : "Izslēgt",
	"Often" : "Bieži",
	"Often_Int_OFF" : "Bieži",
	"OnDemand" : "Pēc piep.",
	"OnceAllDoors" : "Vienreiz: visas durvis",
	"OnceDriversDoorTwiceAllDoors" : "Vienreiz: vadītāja Divreiz: visas durvis",
	"Open" : "Atv.",
	"ParkingSensorIndication" : "Parkošanās sensora indikācija ",
	"ParkingSensorIndicator" : "Automobiļa novietošanas sensora indikators",
	"RVMBuzzerVolume" : "Rear Vehicle Monitoring Skaļums",
	"Rare" : "Reti",
	"Rare_Int_OFF" : "Reti",
	"Reset" : "Atiestatīt",
	"Rotation" : "Rotācija",
	"RumbleStrips" : "Vibr.j.",
	"RumbleStrips_line" : "Vibr.j. ",
	"RumbleVolume" : "Rūkoņas skaļ.",
	"SBSReset" : "Vai tiešām atjaunot Smart Brake Support (SBS) uz to noklusējuma vērtībām?",
	"SBSResetError" : "Kļūda, mainot Smart Brake Support (SBS). Vai mēģināt vēlreiz?",
	"SBSResetProgress" : "Maina Smart Brake Support (SBS)",
	"SBSSCBS" : "SBS/SCBS",
	"SBS_SCBSReset" : "Vai tiešām atjaunot SBS/SCBS uz to noklusējuma vērtībām?",
	"SBS_SCBSResetError" : "Kļūda, mainot SBS/SCBS. Vai mēģināt vēlreiz?",
	"SBS_SCBSResetProgress" : "Maina SBS/SCBS",
	"SCBS" : "Smart City Brake Support",
	"SCBSReset" : "Vai tiešām vēlaties atjaunot SCBS iestatījumus uz rūpnīcas noklusējuma iestatījumiem? ",
	"SCBSResetError" : "Nevar atjaunot SCBS iestatījumus uz rūpnīcas noklusējuma iestatījumiem. Vai mēģināt vēlreiz?\"",
	"SCBSResetProgress" : "Notiek SCBS iestatījumu atjaunošana",
	"SLC_Buzzer" : "Tikai skaņa",
	"SLC_Off" : "Izslēgts ",
	"SLC_Sign" : "Vizuāli",
	"SLC_Sign_Buzzer" : "Ar skaņu un vizuāli",
	"SLIReset" : "Vai tiešām vēlaties atjaunot ātruma ierobežojuma brīdinājuma iestatījumus uz to noklusējuma vērtībām?",
	"SLIResetError" : "Neizdevās atjaunot ātruma ierobežojuma brīdinājuma iestatījumus uz to rūpnīcas iestatījumiem. Vai mēģināt vēlreiz?",
	"SLIResetProgress" : "Notiek ātruma ierobežojuma brīdinājuma iestatījumu atjaunošana",
	"SLI_HeadUpDisplay" : "Active Driving Display",
	"Safety" : "Drošība",
	"Safetysettings" : "Droš. iestat.",
	"Sensitivity" : "Jutīgums",
	"Sensitivity_Intervention_OFF" : "Brīdinājums ",
	"Setting" : "Iestatījums",
	"Settings" : "Iestatījumi",
	"Short" : "Tuvu",
	"SideView" : "Sāns",
	"SideViewFrontView" : "Sāni un priekšpuse",
	"SmartBrakeSupport" : "Smart Brake Support",
	"Sound" : "Skaņa",
	"SpeedAlarm" : "Ātruma brīdinājums",
	"SpeedLimitCaution" : "Ātruma ierobežoj. brīdināj.",
	"SpeedLimitInformation" : "Ātruma ierobežojuma brīdinājums",
	"SpeedLimitSign" : "Ātruma ierobežojuma rādījums",
	"StepKilometers" : "{value} km/h",
	"StepMiles" : "{value} jūdzes/h",
	"StreetInformation" : "Ielas informācija",
	"Streetinfo_off" : "Izslēgts",
	"System" : "Sistēma",
	"TSRReset" : "Vai tiešām vēlaties atjaunot ceļazīmju atpazīšanas sistēmas iestatījumus uz to noklusējuma vērtībām?",
	"TSRResetError" : "Neizdevās atjaunot ceļazīmju atpazīšanas sistēmas iestatījumus uz to rūpnīcas iestatījumiem. Vai mēģināt vēlreiz?",
	"TSRResetProgress" : "Notiek ceļazīmju atpazīšanas sistēmas iestatījumu atjaunošana",
	"TSR_Display" : "Ceļazīmju attēlošana",
	"TSR_System" : "Ceļazīmju atpazīšanas sistēma",
	"Tachometer" : "Tahometrs",
	"ThreeFlashTurnSignal" : "3 gaismu virzienrādītājs",
	"Timing" : "Laika koordinācija",
	"Turn" : "Virzienrādītājs",
	"TurnProgress" : "Maina virzienrādītāju iestatījumus",
	"TurnReset" : "Vai tiešām atjaunot virzienrādītāju iestatījumus uz to noklusējuma vērtībām?",
	"TurnResetError" : "Kļūda, mainot virzienrādītāju iestatījumus. Vai mēģināt vēlreiz?",
	"TurnSettings" : "Virzienrādītājs",
	"TurnSignalIndicatorVolume" : "Virzienr. signāla skaļums",
	"UnlockMode" : "Atbloķēšanas režīms",
	"Vehicle" : "Transp.",
	"VehicleSettings" : "Transportl. iestat.",
	"Vibration" : "Vibrācija",
	"VibrationStrength" : "Vibrācijas stiprums",
	"Vibration_Line" : "Vibrācija",
	"ViewSwitchDisplay" : "Noklusējuma skats",
	"ViewSwitchFunction" : "Skata pārslēgšanas funkcija",
	"Volume" : "Skaļums",
	"WalkAwayLock" : "Aiziešanas slēdzene",
	"Warning" : "Brīdinājums",
	"WarningDistance" : "Brīdin. attāl.",
	"_0s" : "0 s",
	"_0seconds" : "0 sekundes",
	"_10m" : "10 min",
	"_10minutes" : "10 minūtes",
	"_120s" : "120 s",
	"_120seconds" : "120 sekundes",
	"_15s" : "15 s",
	"_15seconds" : "15 sekundes",
	"_30m" : "30 min",
	"_30minutes" : "30 minūtes",
	"_30s" : "30 s",
	"_30seconds" : "30 sekundes",
	"_60m" : "60 min",
	"_60minutes" : "60 minūtes",
	"_60s" : "60 s",
	"_60seconds" : "60 sekundes",
	"_7p5s" : "7,5 s",
	"_7p5seconds" : "7,5 sekundes",
	"_90s" : "90 s",
	"_90seconds" : "90 sekundes",
	"_AllDoors" : "Visas",
	"_Driver'sDoor" : "Vadīt.",
	"on" : "Ieslēgt",
};

framework.registerAppDictLoaded("vehsettings", "lv_LV");