var Localization_vehsettingsAppDict_nl_NL = {
	//"stringId" : "localString"
	"360ViewCamera" : "360°-weergavemonitor",
	"AHBC" : "Adaptive LED Headlights",
	"Adaptive" : "Adaptief",
	"AdaptiveFront-lightingSystem" : "Adaptief bochtenverlichtingssysteem",
	"AdaptiveLaneStreetTurn" : "Adaptive Lane/Street/Turn-systeem",
	"AlarmTiming" : "Snelheids",
	"AlertTiming" : "Timing wrsch.",
	"Always" : "Altijd",
	"AtLine" : "Op lijn",
	"Auto" : "Auto",
	"AutoHeadlightOn" : "Autom. koplamp AAN",
	"AutoWiper" : "Regensensor ruitenwisser",
	"BSMBuzzerVolume" : "Blind Spot Monitoring Volume",
	"BSMReset" : "Weet u zeker dat u de BSM-instellingen wilt terugzetten naar de standaardwaarden?",
	"BSMResetError" : "Kan de BSM-instellingen niet terugzetten naar de standaardwaarden. Wilt u het opnieuw proberen?",
	"BSMResetProgress" : "BSM-instellingen terugzetten",
	"BSMSystem" : "Blind Spot Monitoring-systeem ",
	"Beep" : "Pieptoon",
	"BeepVolume" : "Volume pieptoon",
	"Beep_Line" : "Pieptoon",
	"BeforeLine" : "Vr. lijn",
	"Brightness" : "Helderheid",
	"BrightnessControl" : "Helderheidscontrole",
	"CHudNav_Maneuver" : "Aan of uit",
	"CHudNav_Off" : "Uit",
	"CHudNav_TBT_Lane" : "LG & T-b-T",
	"CHudNav_TBT_Street" : "Str & T-b-T",
	"Calibration" : "Helderheid",
	"CautionSpeed" : "Waarschuwingsdrempel",
	"CenterDisplay" : "Centrale display",
	"ChangingLASSettings" : "Bezig met wijzigen LAS instellingen",
	"Clock" : "Klok",
	"Close" : "Sluiten",
	"ComingHomeLights" : "Coming Home Light",
	"ComingHomeLightsTimer" : "Coming Home Light",
	"DRSS" : "Distance Recognition Support System",
	"DRSSReset" : "Weet u zeker dat u de instellingen van de Distance Recognition Support System wilt terugzetten naar  standaardwaarden?",
	"DRSSResetError" : "Fout wijziging Distance Recognition Support System. Wilt u het opnieuw proberen?",
	"DRSSResetProgress" : "Distance Recognition Support System wijzigen",
	"Dark" : "Donker",
	"DaytimeRunningLights" : "Dagrijverlichting",
	"Devices" : "Apparat.",
	"Display" : "Display",
	"DisplayInformation" : "Informatie display",
	"DistanceRecognitionSupportSystem" : "Distance Recognition Support System",
	"DoorLock" : "Deurvergrendeling",
	"DoorLockMode" : "Autom. Deurvergrendelingsmodule",
	"DoorLockReset" : "Weet u zeker dat u de instellingen Deurvergrendeling naar standaard waarden wilt terugzetten?",
	"DoorLockResetError" : "Fout bij het wijzigen deurslot Instellingen. Wilt u het opnieuw proberen?",
	"DoorLockResetProgress" : "Instellingen “deurvergrendeling” wijzigen",
	"DoorRelockTime" : "Tijd Autom. Hervergrendelen",
	"DriverAlert" : "Driver Attention Alert",
	"Early" : "Vroeg",
	"ErrorBSMSettings" : "Fout bij wijzigen BSM-instellingen. Wilt u het opnieuw proberen?",
	"ErrorLASSettings" : "Fout bij wijzigen Lane-keep Assist System.  Wilt u het opnieuw proberen?",
	"FOWReset" : "Weet u zeker dat u de instellingen van de Forward Obstruction Warning (FOW) wilt terugzetten naar hun standaardwaarden?",
	"FOWResetError" : "Fout wijziging instellingen Forward Obstruction Warning (FOW). Wilt u het opnieuw proberen?",
	"FOWResetProgress" : "Instellingen Forward Obstruction Warning (FOW) wijzigen",
	"Far" : "Ver",
	"ForwardObstructionWarning" : "Forward Obstruction Warning",
	"FrontCameraView" : "Weergave camera voorzijde",
	"GearShiftIndicator" : "Schakelindicator",
	"GuidelineDisplay" : "Dynamische padlijnen",
	"HUD" : "AD-Disp",
	"HUDDisplayInfoError" : "De fabrieksinstellingen voor AD-Disp displayinfo kunnen niet hersteld worden. Wil je het opnieuw proberen?",
	"HUDDisplayInfoReset" : "Weet je zeker dat je de standaardinstellingen voor AD-Disp displayinfo wil herstellen?",
	"HUDDisplayInfoResetProgress" : "De instellingen voor AD-Disp displayinfo worden hersteld",
	"HUDJ78AReset" : "Weet u zeker dat u de Active Driving Display-instellingen wilt terugzetten naar de standaardwaarden?",
	"HUDJ78AResetError" : "Er is fout opgetreden tijdens het terugzetten van de Active Driving Display-instellingen. Wilt u het opnieuw proberen?",
	"HUDJ78AResetProgress" : "Bezig met terugzetten Active Driving Display-instellingen",
	"HUDJ78ATab" : "Active Driving Display",
	"HUDReset" : "Weet u zeker dat u de instellingen van de Active Driving Display wilt terugzetten naar hun standaardwaarden?",
	"HUDResetError" : "Fout bij het wijzigen van Active Driving Display Instellingen. Wilt u het opnieuw proberen?",
	"HUDResetProgress" : "Instel. Active Driving Display wijz.",
	"HUDSettings" : "AD-Disp-instellingen",
	"HUD_HeadUpDisplay" : "Active Driving Display",
	"HeadUpDisplay" : "Active Driving Display",
	"HeadlightOffTimer" : "Timer koplamp UIT",
	"HeadlightOnWarning" : "Waarsch. licht AAN",
	"HeadsUpDisplay" : "Active Driving Display",
	"Height" : "Hoogte",
	"High" : "Hoog",
	"HighBeamControl" : "High Beam Control",
	"High_SensitivityLAS" : "Hoog",
	"High_Vibration" : "Hoog",
	"ILB_Bright" : "Helder",
	"ILB_Dark" : "Gedempt",
	"ILB_Medium" : "Medium",
	"ILB_Off" : "Uit ",
	"IgONAutoDisplay" : "Auto-Display 360° View Monitor",
	"InterioLightsTimeOutDoorsClosed" : "Time-out binnenverl. – Deur gesl.",
	"InterioLightsTimeOutDoorsOpen" : "Time-out binnenverl, – Deuren open",
	"InteriorLightTimeoutDoorClosedTitle" : "Time-out Binnenverl. – Deur dicht",
	"InteriorLightTimeoutDoorOpenTitle" : "Time-out Binnenverl. – Deur open",
	"InteriorLightingBrightness" : "Omgevingslicht",
	"Intervention" : "Interventie",
	"InterventionTiming" : "Interventietiming",
	"KeylessLockBeepVol" : "Volume pieptoon Keyless",
	"Kilometers" : "km/u",
	"LASAlert" : "LAS Alarm",
	"LASDefaultValues" : "Weet u zeker dat u de Lane-keep Assist System instellingen naar standaardwaarden wilt terugstellen?",
	"LASEarly" : "Vroeg",
	"LASLate" : "Laat",
	"LASSound" : "Type waarschuwing",
	"LASTiming" : "LAS-timing",
	"LDWSReset" : "Weet u zeker dat u de Lane Departure Warning System Instellingen wilt terugzetten naar hun standaardwaarden?",
	"LDWSResetError" : "Fout bij het wijzigen van het Lane Departure Warning System Instellingen. Wilt u het opnieuw proberen?",
	"LDWSResetProgress" : "Instellingen Lane Departure Warning System wijzigen",
	"LDWSTiming" : "LDWS-timing",
	"LaneDepartureAlert" : "Waarsch. bij verlaten rijstr.",
	"LaneDepartureWarningSystem" : "Lane Departure Warning System",
	"LaneKeepAssistSystem" : "Lane-keep Assist System",
	"Late" : "Laat",
	"LeavingHomeLights" : "Leaving Home Light",
	"Light" : "Licht",
	"LightOnReminderVolume" : "Vol. Licht aan",
	"Lighting" : "Verlichting",
	"LightingReset" : "Weet u zeker dat u de instellingen Verlichting naar standaard waarden wilt terugzetten?",
	"LightingResetError" : "Fout bij het wijzigen van Verlichting instellingen. Wilt u het opnieuw proberen?",
	"LightingResetProgress" : "Instellingen verlichting wijzigen",
	"LockShiftFromP" : "Slot: Van de parkeerstand zetten ",
	"LockShiftFromPUnlockInPark" : "Dicht: uit P-stand.  Open: In P-stand",
	"LockUnlock" : "Vergr: rijden. Ontgr: geparkeerd",
	"LockWhenDriving" : "Vergrendelen: Tijdens het rijden",
	"LockWhenDrivingUnlockIGNoff" : "Dicht: Rijden Open: Contact aan",
	"Long" : "Veraf",
	"Low" : "Laag",
	"Low_SensitivityLAS" : "Laag",
	"Low_Vibration" : "Laag",
	"Manual" : "Hand.",
	"Med" : "Med",
	"Medium" : "Medium",
	"MediumDark" : "Half don.",
	"MediumLight" : "Half licht",
	"Medium_Int_OFF" : "Med",
	"Medium_SensitivityLAS" : "Med",
	"Mid" : "Midden",
	"Middle" : "Mid.",
	"Miles" : "mph",
	"Mode" : "Modus",
	"Navigation" : "Navigatie",
	"NavigationSignal" : "Navigatie  ",
	"Near" : "Vlakbij",
	"Off" : "Uit",
	"Often" : "Vaak",
	"Often_Int_OFF" : "Vaak",
	"OnDemand" : "Op ver.",
	"OnceAllDoors" : "1x: Alle portieren",
	"OnceDriversDoorTwiceAllDoors" : "1x: Best. Kant 2x: Alle deuren",
	"Open" : "Open",
	"ParkingSensorIndication" : "Parkeersensorindicatie ",
	"ParkingSensorIndicator" : "Indicator parkeersensor",
	"RVMBuzzerVolume" : "Rear Vehicle Monitoring Volume",
	"Rare" : "Zeldzam",
	"Rare_Int_OFF" : "Zeldzam",
	"Reset" : "Reset",
	"Rotation" : "Draaien",
	"RumbleStrips" : "Ribbel",
	"RumbleStrips_line" : "Ribbel ",
	"RumbleVolume" : "Vol. bandengel.",
	"SBSReset" : "Weet u zeker dat u de instellingen van de Smart Brake Support (SBS) wilt terugzetten naar hun standaardwaarden?",
	"SBSResetError" : "Fout wijziging instellingen Smart Brake Support (SBS). Wilt u het opnieuw proberen?",
	"SBSResetProgress" : "Instellingen Smart Brake Support (SBS) wijzigen",
	"SBSSCBS" : "SBS/SCBS",
	"SBS_SCBSReset" : "Weet u zeker dat u de instellingen van de “SBS/SCBS” wilt terugzetten naar hun standaardwaarden?",
	"SBS_SCBSResetError" : "Fout wijziging instellingen “SBS/SCBS”. Wilt u het opnieuw proberen?",
	"SBS_SCBSResetProgress" : "Instellingen “SBS/SCBS” wijzigen",
	"SCBS" : "Smart City Brake Support",
	"SCBSReset" : "Weet u zeker dat u de SCBS-instellingen wilt terugzetten naar de standaardwaarden?",
	"SCBSResetError" : "Kan de SCBS-instellingen niet terugzetten naar de standaardwaarden. Wilt u het opnieuw proberen?",
	"SCBSResetProgress" : "SCBS-instellingen terugzetten",
	"SLC_Buzzer" : "Alleen zoemer",
	"SLC_Off" : "Uit ",
	"SLC_Sign" : "Visueel",
	"SLC_Sign_Buzzer" : "Audio en visueel",
	"SLIReset" : "Weet u zeker dat u de instellingen voor de snelheidslimietwaarschuwingen wilt terugzetten naar de standaardwaarden?",
	"SLIResetError" : "Kan de instellingen voor de snelheidslimietwaarschuwingen niet terugzetten naar de standaardwaarden. Wilt u het opnieuw proberen?",
	"SLIResetProgress" : "Instellingen voor snelheidslimietwaarschuwingen terugzetten",
	"SLI_HeadUpDisplay" : "Active Driving Display",
	"Safety" : "Veiligheid",
	"Safetysettings" : "Veiligheidsinstellingen",
	"Sensitivity" : "Gevoeligheid",
	"Sensitivity_Intervention_OFF" : "Waarschuwing ",
	"Setting" : "Instellingen",
	"Settings" : "Instellingen",
	"Short" : "Dicht",
	"SideView" : "Zijkant",
	"SideViewFrontView" : "Zij- & voorkant",
	"SmartBrakeSupport" : "Smart Brake Support",
	"Sound" : "Geluid",
	"SpeedAlarm" : "Snelheidsalarm",
	"SpeedLimitCaution" : "Waarschuwing snelheidslimiet",
	"SpeedLimitInformation" : "Waarschuwing snelheidslimiet",
	"SpeedLimitSign" : "Display snelheidslimiet",
	"StepKilometers" : "{value} km/u",
	"StepMiles" : "{value} mph",
	"StreetInformation" : "Straatinformatie",
	"Streetinfo_off" : "Uit",
	"System" : "Systeem",
	"TSRReset" : "Weet u zeker dat u de instellingen voor het  Verkeersbordherkenningssysteem  wilt terugzetten naar de standaardwaarden?",
	"TSRResetError" : "Kan de instellingen voor het  Verkeersbordherkenningssysteem  niet terugzetten naar de standaardwaarden. Wilt u het opnieuw proberen?",
	"TSRResetProgress" : "Instellingen voor het  Verkeersbordherkenningssysteem  terugzetten",
	"TSR_Display" : "Verkeersbordweergave",
	"TSR_System" : "Verkeersbordherkenningssysteem",
	"Tachometer" : "Toerenteller",
	"ThreeFlashTurnSignal" : "3x knipperende richtingaanwijzer signaal",
	"Timing" : "Timing",
	"Turn" : "Richtingaanwijzer",
	"TurnProgress" : "Instellingen “Turn” wijzigen",
	"TurnReset" : "Weet u zeker dat u de Turn instellingen wilt terugzetten naar standaardwaarden?",
	"TurnResetError" : "Fout bij het wijzigen van RAW-instellingen. Wilt u het opnieuw proberen?",
	"TurnSettings" : "Draaien",
	"TurnSignalIndicatorVolume" : "Volume turnsignaal",
	"UnlockMode" : "Modus ontgrendelen",
	"Vehicle" : "Voertuig",
	"VehicleSettings" : "Instel. voertuig",
	"Vibration" : "Trillen",
	"VibrationStrength" : "Trilkracht",
	"Vibration_Line" : "Trillen",
	"ViewSwitchDisplay" : "Standaard weergave",
	"ViewSwitchFunction" : "Functie aanzicht wisselen",
	"Volume" : "Volume",
	"WalkAwayLock" : "Walk Away vergrendeling",
	"Warning" : "Waarschuwing",
	"WarningDistance" : "Afstandswaars.",
	"_0s" : "0 s",
	"_0seconds" : "0 seconden",
	"_10m" : "10 min",
	"_10minutes" : "10 minuten",
	"_120s" : "120 s",
	"_120seconds" : "120 seconden",
	"_15s" : "15 s",
	"_15seconds" : "15 seconden",
	"_30m" : "30 min",
	"_30minutes" : "30 minuten",
	"_30s" : "30 s",
	"_30seconds" : "30 seconden",
	"_60m" : "60 min",
	"_60minutes" : "60 minuten",
	"_60s" : "60 s",
	"_60seconds" : "60 seconden",
	"_7p5s" : "7,5 s",
	"_7p5seconds" : "7,5 seconden",
	"_90s" : "90 s",
	"_90seconds" : "90 seconden",
	"_AllDoors" : "Alle",
	"_Driver'sDoor" : "Bestu",
	"on" : "Aan",
};

framework.registerAppDictLoaded("vehsettings", "nl_NL");