var Localization_vehsettingsAppDict_tr_TR = {
	//"stringId" : "localString"
	"360ViewCamera" : "360° Görünüm Ekranı",
	"AHBC" : "Adaptive LED Headlights",
	"Adaptive" : "Adaptif",
	"AdaptiveFront-lightingSystem" : "Direksiyona Duyarlı Far Sistemi",
	"AdaptiveLaneStreetTurn" : "Adaptif Şerit/Sokak/Dönüş",
	"AlarmTiming" : "Hız Ayarı",
	"AlertTiming" : "Uyarı Zamanı",
	"Always" : "Daima",
	"AtLine" : "Şeritte",
	"Auto" : "Oto.",
	"AutoHeadlightOn" : "Otomatik Far Açık",
	"AutoWiper" : "Yağmur Sezicili Silecek",
	"BSMBuzzerVolume" : "Blind Spot Monitoring S.Seviye",
	"BSMReset" : "BSM ayarlarını fabrika ayarlarına döndürmek istediğinizden emin misiniz?",
	"BSMResetError" : "BSM ayarları fabrika ayarlarına geri döndürülemedi. Tekrar denemek ister misiniz?",
	"BSMResetProgress" : "BSM Ayarlarını Geri Yükleme",
	"BSMSystem" : "BSM Sistemi ",
	"Beep" : "Bip Sesi",
	"BeepVolume" : "Bip Sesi Seviyesi",
	"Beep_Line" : "Bip Sesi",
	"BeforeLine" : "Ş.Önce",
	"Brightness" : "Parlaklık",
	"BrightnessControl" : "Parlaklık Kontrolü",
	"CHudNav_Maneuver" : "Manevra",
	"CHudNav_Off" : "Kapalı",
	"CHudNav_TBT_Lane" : "Şrt v Sk",
	"CHudNav_TBT_Street" : "Sk. Adı",
	"Calibration" : "Parlaklık",
	"CautionSpeed" : "Alarm Eşiği",
	"CenterDisplay" : "Merkez Gösterge",
	"ChangingLASSettings" : "LAS Sistemi ayarları değiştiriliyor",
	"Clock" : "Saat",
	"Close" : "Kapat",
	"ComingHomeLights" : "Coming Home Light",
	"ComingHomeLightsTimer" : "Coming Home Light",
	"DRSS" : "Distance Recognition Support System",
	"DRSSReset" : "Distance Recognition Support System (DRSS) ayarlarını varsayılan değerlerine geri almak istediğinizden emin misiniz?",
	"DRSSResetError" : "Distance Recognition Support System (DRSS) değiştirilirken hata oluştu. Yeniden denemek ister misiniz?",
	"DRSSResetProgress" : "Distance Recognition Support System (DRSS) Değiştiriliyor",
	"Dark" : "Koyu",
	"DaytimeRunningLights" : "Gündüz Çalışan Işıklar",
	"Devices" : "Aygıtlar",
	"Display" : "Ekran",
	"DisplayInformation" : "Gösterge Bilgileri",
	"DistanceRecognitionSupportSystem" : "Distance Recognition Support System",
	"DoorLock" : "Kapı Kilidi",
	"DoorLockMode" : "Otomatik Kapı Kilidi Modu",
	"DoorLockReset" : "Kapı Kilidi Ayarlarını varsayılan değerlerine getirmek istediğinizden emin misiniz?",
	"DoorLockResetError" : "Kapı Kilidi Ayarları değiştirilirken hata meydana geldi. Yeniden denemek ister misiniz?",
	"DoorLockResetProgress" : "Kapı Kilidi Ayarları Değiştiriliyor",
	"DoorRelockTime" : "Otomatik Geri Kilitleme Süresi",
	"DriverAlert" : "Driver Attention Alert",
	"Early" : "Erken",
	"ErrorBSMSettings" : "BSM ayarlarını değiştirirken bir hata oluştu. Tekrar denemek ister misiniz?",
	"ErrorLASSettings" : "Lane-keep Assist System değiştirilirken hata oluştu. Tekrar denemek ister misiniz?",
	"FOWReset" : "Forward Obstruction Warning (FOW) Ayarlarını varsayılan değerlerine geri getirmek istediğinizden emin misiniz?",
	"FOWResetError" : "Forward Obstruction Warning (FOW) Ayarları Değiştirilirken Hata Meydana Geldi. Tekrar denemek ister misiniz?",
	"FOWResetProgress" : "Forward Obstruction Warning (FOW) Ayarları Değiştiriliyor",
	"Far" : "Uzak",
	"ForwardObstructionWarning" : "Forward Obstruction Warning",
	"FrontCameraView" : "Ön Kamera Görünümü",
	"GearShiftIndicator" : "Vites Değiştirme Göstergesi",
	"GuidelineDisplay" : "Dinamik Yol Çizgileri",
	"HUD" : "AD-Disp",
	"HUDDisplayInfoError" : "AD-Disp Ekran Bilgileri ayarları fabrika ayarlarına geri yüklenemez. Yeniden denemek ister misiniz?",
	"HUDDisplayInfoReset" : "AD-Disp Ekran Bilgileri ayarlarını varsayılan değerlerine geri yüklemek istediğinizden emin misiniz?",
	"HUDDisplayInfoResetProgress" : "AD-Disp Ekran Bilgileri  ayarları geri yükleniyor",
	"HUDJ78AReset" : "Active Driving Display ayarlarını varsayılan değerlerine sıfırlamak istediğinizden emin misiniz?",
	"HUDJ78AResetError" : "Active Driving Display ayarları sıfırlanırken bir hata oluştu. Yeniden denemek istiyor musunuz?",
	"HUDJ78AResetProgress" : "Active Driving Display Ayarları Sıfırlanıyor",
	"HUDJ78ATab" : "Active Driving Display",
	"HUDReset" : "Active Driving Display Ayarlarını varsayılan değerlerine getirmek istediğinizden emin misiniz?",
	"HUDResetError" : "Active Driving Display Ayarları değiştirilirken hata meydana geldi. Yeniden denemek ister misiniz?",
	"HUDResetProgress" : "AD-Disp Ayarları Değiştiriliyor",
	"HUDSettings" : "AD-Disp Ayarları",
	"HUD_HeadUpDisplay" : "Active Driving Display",
	"HeadUpDisplay" : "Active Driving Display",
	"HeadlightOffTimer" : "Far Kapatma Zamanlayıcısı",
	"HeadlightOnWarning" : "Far Açık Uyarısı",
	"HeadsUpDisplay" : "Active Driving Display",
	"Height" : "Yükseklik",
	"High" : "Yük.",
	"HighBeamControl" : "High Beam Control",
	"High_SensitivityLAS" : "Yük.",
	"High_Vibration" : "Yük.",
	"ILB_Bright" : "Parlak",
	"ILB_Dark" : "Loş",
	"ILB_Medium" : "Orta",
	"ILB_Off" : "Kapalı ",
	"IgONAutoDisplay" : "360° View Monitor Oto-Görünüm",
	"InterioLightsTimeOutDoorsClosed" : "İç Aydınlatma Süresi - Kapı Kapalı",
	"InterioLightsTimeOutDoorsOpen" : "İç Aydınlatma Süresi - Kapı Açık",
	"InteriorLightTimeoutDoorClosedTitle" : "İç Aydınlatma Süresi - Kapı Kapalı",
	"InteriorLightTimeoutDoorOpenTitle" : "İç Aydınlatma Süresi - Kapılar Açık",
	"InteriorLightingBrightness" : "Ortam Işığı",
	"Intervention" : "Müdahale",
	"InterventionTiming" : "Müdahale Zamanı",
	"KeylessLockBeepVol" : "Anahtarsız Kilit Bip Sesi Seviyesi",
	"Kilometers" : "km/sa",
	"LASAlert" : "LAS Uyarısı",
	"LASDefaultValues" : "Lane-keep Assist System ayarlarını varsayılan değerlere döndürmek istiyor musunuz?",
	"LASEarly" : "Erken",
	"LASLate" : "Geç",
	"LASSound" : "Uyarı Türü",
	"LASTiming" : "LAS Zamanlaması",
	"LDWSReset" : "Lane Departure Warning System (LDWS) Ayarlarını varsayılan değerlerine getirmek istediğinizden emin misiniz?",
	"LDWSResetError" : "Lane Departure Warning System (LDWS) Ayarları değiştirilirken hata meydana geldi. Yeniden denemek ister misiniz?",
	"LDWSResetProgress" : "Lane Departure Warning System (LDWS) Ayarları Değiştiriliyor",
	"LDWSTiming" : "LDWS Zamanlama",
	"LaneDepartureAlert" : "Şerit Değiştirme Uyarısı",
	"LaneDepartureWarningSystem" : "Lane Departure Warning System",
	"LaneKeepAssistSystem" : "Lane-keep Assist System",
	"Late" : "Geç",
	"LeavingHomeLights" : "Leaving Home Light",
	"Light" : "Işık",
	"LightOnReminderVolume" : "Aydnltm Açık Ses",
	"Lighting" : "Aydınlatma",
	"LightingReset" : "Aydınlatma Ayarlarını varsayılan değerlerine getirmek istediğinizden emin misiniz?",
	"LightingResetError" : "Aydınlatma Ayarları değiştirilirken hata meydana geldi. Yeniden denemek ister misiniz?",
	"LightingResetProgress" : "Aydınlatma Ayarları Değiştiriliyor",
	"LockShiftFromP" : "Kilitli: Vites Park Konumu Dışında ",
	"LockShiftFromPUnlockInPark" : "Kilit: Vites Park Dışı Açık: Park",
	"LockUnlock" : "Kilitle: Sürüşte Kilidi Aç: Park Halinde",
	"LockWhenDriving" : "Kilitli: Sürüş Sırasında",
	"LockWhenDrivingUnlockIGNoff" : "Kilitli: Sürüş Sırasında Açık: IGN Kapalı",
	"Long" : "Yakın",
	"Low" : "Düşük",
	"Low_SensitivityLAS" : "Düşük",
	"Low_Vibration" : "Düşük",
	"Manual" : "Kılavuz",
	"Med" : "Orta",
	"Medium" : "Orta",
	"MediumDark" : "Yari Koyu",
	"MediumLight" : "Yari ışık",
	"Medium_Int_OFF" : "Orta",
	"Medium_SensitivityLAS" : "Orta",
	"Mid" : "Orta",
	"Middle" : "Orta",
	"Miles" : "mph",
	"Mode" : "Mod",
	"Navigation" : "Navigasyon",
	"NavigationSignal" : "Navigasyon  ",
	"Near" : "Yakın",
	"Off" : "Kapalı",
	"Often" : "Sık",
	"Often_Int_OFF" : "Sık",
	"OnDemand" : "İst. Üz.",
	"OnceAllDoors" : "Bir Defa: Tüm Kapılar",
	"OnceDriversDoorTwiceAllDoors" : "Bir Defa: Sürücü İki Defa: Tüm Kapılar",
	"Open" : "Açık",
	"ParkingSensorIndication" : "Park Sensörü Göstergesi ",
	"ParkingSensorIndicator" : "Park Sensörü Göstergesi",
	"RVMBuzzerVolume" : "Rear Vehicle Monitoring S.Seviye",
	"Rare" : "Seyrek",
	"Rare_Int_OFF" : "Seyrek",
	"Reset" : "Sıfırla",
	"Rotation" : "Döndürme",
	"RumbleStrips" : "Hız B.",
	"RumbleStrips_line" : "Hız B. ",
	"RumbleVolume" : "Gürültü Ses Düzeyi",
	"SBSReset" : "Smart Brake Support (SBS) Ayarlarını varsayılan değerlerine geri getirmek istediğinizden emin misiniz?",
	"SBSResetError" : "Smart Brake Support (SBS) Ayarları değiştirilirken hata oluştu. Yeniden denemek ister misiniz?",
	"SBSResetProgress" : "Smart Brake Support (SBS) Ayarları Değiştiriliyor",
	"SBSSCBS" : "SBS/SCBS",
	"SBS_SCBSReset" : "SBS/SCBS Ayarlarını varsayılan değerlerine geri getirmek istediğinizden emin misiniz?",
	"SBS_SCBSResetError" : "SBS/SCBS Ayarları değiştirilirken hata meydana geldi. Tekrar denemek ister misiniz?",
	"SBS_SCBSResetProgress" : "SBS/SCBS Ayarları Değiştiriliyor",
	"SCBS" : "Smart City Brake Support",
	"SCBSReset" : "SCBS ayarlarını fabrika ayarlarına döndürmek istediğinizden emin misiniz?",
	"SCBSResetError" : "SCBS ayarları fabrika ayarlarına geri döndürülemedi. Tekrar denemek ister misiniz?",
	"SCBSResetProgress" : "SCBS ayarlarını geri yükleme",
	"SLC_Buzzer" : "Sadece sesli ikaz",
	"SLC_Off" : "Kapalı ",
	"SLC_Sign" : "Görsel",
	"SLC_Sign_Buzzer" : "Ses ve Görsel",
	"SLIReset" : "Hız Limiti Uyarı ayarlarını varsayılan değerlerine geri döndürmek istediğinizden emin misiniz?",
	"SLIResetError" : "Hız Limiti Uyarı ayarları fabrika ayarlarına geri döndürülemedi. Tekrar denemek ister misiniz?",
	"SLIResetProgress" : "Hız Limiti Uyarı ayarları geri yükleniyor",
	"SLI_HeadUpDisplay" : "Active Driving Display",
	"Safety" : "Güvenlik",
	"Safetysettings" : "Güvenlik Ayarları",
	"Sensitivity" : "Hassasiyet",
	"Sensitivity_Intervention_OFF" : "Uyarı ",
	"Setting" : "Ayarlar",
	"Settings" : "Ayarlar",
	"Short" : "Uzak",
	"SideView" : "Yan",
	"SideViewFrontView" : "Yan+Ön",
	"SmartBrakeSupport" : "Smart Brake Support",
	"Sound" : "Ses",
	"SpeedAlarm" : "Hız Alarmı",
	"SpeedLimitCaution" : "Hız Sınırı Alarmı",
	"SpeedLimitInformation" : "Hız Sınırı Uyarısı",
	"SpeedLimitSign" : "Hız Sınırı Ekranı",
	"StepKilometers" : "{value} km/sa",
	"StepMiles" : "{value} mph",
	"StreetInformation" : "Cadde Bilgileri",
	"Streetinfo_off" : "Kapalı",
	"System" : "Sistem",
	"TSRReset" : "Trafik İşareti Tanıma Sistemi ayarlarını varsayılan değerlerine geri döndürmek istediğinizden emin misiniz?",
	"TSRResetError" : "Trafik İşareti Tanıma Sistem ayarları fabrika ayarlarına geri döndürülemedi. Tekrar denemek ister misiniz?",
	"TSRResetProgress" : "Trafik İşareti Tanıma Sistemi ayarları geri yükleniyor",
	"TSR_Display" : "Trafik İşareti Ekranı",
	"TSR_System" : "Trafik İşareti Tanıma Sistemi",
	"Tachometer" : "Takometre",
	"ThreeFlashTurnSignal" : "3 Flaşlı Dönüş Sinyali",
	"Timing" : "Zamanlama",
	"Turn" : "Dönüş",
	"TurnProgress" : "Dönüş Ayarları Değiştiriliyor",
	"TurnReset" : "Dönüş Ayarlarını varsayılan değerlerine getirmek istediğinizden emin misiniz?",
	"TurnResetError" : "Dönüş Ayarları Değiştirilirken Hata Meydana Geldi. Yeniden denemek ister misiniz?",
	"TurnSettings" : "Dönüş",
	"TurnSignalIndicatorVolume" : "Dönüş Sinyali Ses Seviy.",
	"UnlockMode" : "Kilit Açma Modu",
	"Vehicle" : "Araç",
	"VehicleSettings" : "Araç Ayarları",
	"Vibration" : "Titreşim",
	"VibrationStrength" : "Titreşim Gücü",
	"Vibration_Line" : "Titreşim",
	"ViewSwitchDisplay" : "Varsayılan Görünüm",
	"ViewSwitchFunction" : "Görünüm Düğmesi İşlevi",
	"Volume" : "Ses Seviyesi",
	"WalkAwayLock" : "Uzaklaşma Kilidi",
	"Warning" : "Uyarı",
	"WarningDistance" : "Uyarı Mesafesi",
	"_0s" : "0 sn",
	"_0seconds" : "0 saniye",
	"_10m" : "10 dak",
	"_10minutes" : "10 dakika",
	"_120s" : "120 sn",
	"_120seconds" : "120 saniye",
	"_15s" : "15 sn",
	"_15seconds" : "15 saniye",
	"_30m" : "30 dak",
	"_30minutes" : "30 dakika",
	"_30s" : "30 sn",
	"_30seconds" : "30 saniye",
	"_60m" : "60 dak",
	"_60minutes" : "60 dakika",
	"_60s" : "60 sn",
	"_60seconds" : "60 saniye",
	"_7p5s" : "7.5 sn",
	"_7p5seconds" : "7.5 saniye",
	"_90s" : "90 sn",
	"_90seconds" : "90 saniye",
	"_AllDoors" : "Tümü",
	"_Driver'sDoor" : "Sürücü",
	"on" : "Açık",
};

framework.registerAppDictLoaded("vehsettings", "tr_TR");