var Localization_vehsettingsAppDict_no_NO = {
	//"stringId" : "localString"
	"360ViewCamera" : "Monitor med 360°-visning",
	"AHBC" : "Adaptive LED Headlights",
	"Adaptive" : "Tilpasningsbar",
	"AdaptiveFront-lightingSystem" : "Adaptive frontlys",
	"AdaptiveLaneStreetTurn" : "Adaptiv kjørefelt/gate/sving",
	"AlarmTiming" : "Hastighets",
	"AlertTiming" : "Varslingsinnstilling",
	"Always" : "Alltid",
	"AtLine" : "V/linje",
	"Auto" : "Auto",
	"AutoHeadlightOn" : "Frontlys automatisk på",
	"AutoWiper" : "Automatiske vindusviskere",
	"BSMBuzzerVolume" : "Blind Spot Monitoring Volum",
	"BSMReset" : "Er du sikker på at du vil tilbakestille BSM til fabrikkinnstillinger?",
	"BSMResetError" : "Kunne ikke tilbakestille BSM til fabrikkinnstillinger. Vil du prøve på nytt?",
	"BSMResetProgress" : "Tilbakestiller BSM-innstillinger",
	"BSMSystem" : "Blind Spot Monitoring-system ",
	"Beep" : "Pipelyd",
	"BeepVolume" : "Lydsignalvolum",
	"Beep_Line" : "Pipelyd",
	"BeforeLine" : "F/linje",
	"Brightness" : "Lysstyrke",
	"BrightnessControl" : "Luminanskontroll",
	"CHudNav_Maneuver" : "Ved manøver",
	"CHudNav_Off" : "Av",
	"CHudNav_TBT_Lane" : "Felt-guide + sving-for-sving",
	"CHudNav_TBT_Street" : "Gatenavn + sving-for-sving",
	"Calibration" : "Lysstyrke",
	"CautionSpeed" : "Alarmterskel",
	"CenterDisplay" : "Midtdisplay",
	"ChangingLASSettings" : "Endrer innstillinger for LAS",
	"Clock" : "Klokke",
	"Close" : "Lukke",
	"ComingHomeLights" : "Coming Home Light",
	"ComingHomeLightsTimer" : "Coming Home Light",
	"DRSS" : "Distance Recognition Support System",
	"DRSSReset" : "Er du sikker på at du vil tilbakestille Distance Recognition Support System (DRSS) til standardverdier?",
	"DRSSResetError" : "Feil ved endring av Distance Recognition Support System (DRSS). Vil du prøve på nytt?",
	"DRSSResetProgress" : "Endrer Distance Recognition Support System (DRSS)",
	"Dark" : "Mørk",
	"DaytimeRunningLights" : "Kjørelys",
	"Devices" : "Enheter",
	"Display" : "Skjerm",
	"DisplayInformation" : "Displayinformasjon",
	"DistanceRecognitionSupportSystem" : "Distance Recognition Support System",
	"DoorLock" : "Dørlås",
	"DoorLockMode" : "Modus for automatisk dørlås",
	"DoorLockReset" : "Er du sikker på at du vil tilbakestille dørlåsinnstillingene til standardverdiene?",
	"DoorLockResetError" : "Feil ved endring av dørlåsinnstillinger. Vil du prøve på nytt?",
	"DoorLockResetProgress" : "Endrer dørlåsinnstillinger",
	"DoorRelockTime" : "Tid for autolås",
	"DriverAlert" : "Driver Attention Alert",
	"Early" : "Tidlig",
	"ErrorBSMSettings" : "Feil ved endring av BSM-innstillinger. Vil du prøve på nytt?",
	"ErrorLASSettings" : "Feil ved endring av innstillingene for Lane  Lane-keep Assist System. Vil du prøve på nytt?",
	"FOWReset" : "Er du sikker på at du vil tilbakestille innstillingene for Forward Obstruction Warning (FOW) til standardverdiene?",
	"FOWResetError" : "Feil ved endring av innstillinger for Forward Obstruction Warning (FOW). Vil du prøve på nytt?",
	"FOWResetProgress" : "Endrer innstillinger for Forward Obstruction Warning (FOW)",
	"Far" : "Fjernt",
	"ForwardObstructionWarning" : "Forward Obstruction Warning",
	"FrontCameraView" : "Visning av kamera foran",
	"GearShiftIndicator" : "Girskiftindikator",
	"GuidelineDisplay" : "Dynamiske kjørelinjer",
	"HUD" : "AD-Disp",
	"HUDDisplayInfoError" : "Kan ikke gjenopprette innstillinger for visning av AD-Disp informasjon til fabrikkinnstillinger. Vil du prøve på nytt?",
	"HUDDisplayInfoReset" : "Er du sikker på at du vil gjenopprette innstillinger for visning av AD-Disp informasjon til standardverdier?",
	"HUDDisplayInfoResetProgress" : " Gjenoppretter innstill. for å vise AD-Disp info",
	"HUDJ78AReset" : "Er du sikker på at du vil tilbakestille Active Driving Display-innstillingene til standardverdiene?",
	"HUDJ78AResetError" : "En feil oppsto ved tilbakestilling av Active Driving Display-innstillingene. Vil du forsøke på nytt?",
	"HUDJ78AResetProgress" : "Tilbakestiller Active Driving Display-innstillingene",
	"HUDJ78ATab" : "Active Driving Display",
	"HUDReset" : "Er du sikker på at du vil tilbakestille  Active Driving Display til standardverdiene?",
	"HUDResetError" : "Feil ved endring av innstillingene for Active Driving Display. Vil du prøve på nytt?",
	"HUDResetProgress" : "Endrer Active Driving Display Settings",
	"HUDSettings" : "AD-Disp-innstillinger",
	"HUD_HeadUpDisplay" : "Active Driving Display",
	"HeadUpDisplay" : "Active Driving Display",
	"HeadlightOffTimer" : "Timer for frontlys",
	"HeadlightOnWarning" : "Frontlysvarsel",
	"HeadsUpDisplay" : "Active Driving Display",
	"Height" : "Høyde",
	"High" : "Høy",
	"HighBeamControl" : "High Beam Control",
	"High_SensitivityLAS" : "Høy",
	"High_Vibration" : "Høy",
	"ILB_Bright" : "Lyst",
	"ILB_Dark" : "Mørkt",
	"ILB_Medium" : "Middels",
	"ILB_Off" : "Av ",
	"IgONAutoDisplay" : "Vis 360° View Monitor automatisk",
	"InterioLightsTimeOutDoorsClosed" : "Timer for interiørlys, dør lukket",
	"InterioLightsTimeOutDoorsOpen" : "Timer for interiørlys, dør åpen",
	"InteriorLightTimeoutDoorClosedTitle" : "Timer for interiørlys, dør åpen",
	"InteriorLightTimeoutDoorOpenTitle" : "Timer for interiørlys, dør lukket",
	"InteriorLightingBrightness" : "Omgivelsestilpasset lys",
	"Intervention" : "Intervensjon",
	"InterventionTiming" : "Intervensjonstidspunkt",
	"KeylessLockBeepVol" : "Volum, varseltone for nøkkelfri lås",
	"Kilometers" : "km/t",
	"LASAlert" : "LAS-varsel",
	"LASDefaultValues" : "Er du sikker på at du vil tilbakestille innstillinger for Lane-keep Assist System til standardverdier?",
	"LASEarly" : "Tidlig",
	"LASLate" : "Sent",
	"LASSound" : "Varslingstype",
	"LASTiming" : "LAS Timing",
	"LDWSReset" : "Er du sikker på at du vil tilbakestille innstillinger for Lane Departure Warning System (LDWS) til standardverdier?",
	"LDWSResetError" : "Feil ved endring av innstillingene for Lane Departure Warning System (LDWS). Vil du prøve på nytt?",
	"LDWSResetProgress" : "Endrer innstillingene for Lane Departure Warning System (LDWS)",
	"LDWSTiming" : "LDWS-timing",
	"LaneDepartureAlert" : "Banefravikningsvarsel",
	"LaneDepartureWarningSystem" : "Lane Departure Warning System",
	"LaneKeepAssistSystem" : "Lane-keep Assist System",
	"Late" : "Sent",
	"LeavingHomeLights" : "Leaving Home Light",
	"Light" : "Lett",
	"LightOnReminderVolume" : "Volum lysvarsler",
	"Lighting" : "Belysning",
	"LightingReset" : "Er du sikker på at du vil tilbakestille lysinnstillingene til standardverdiene?",
	"LightingResetError" : "Feil ved endring av lysinnstillinger. Vil du prøve på nytt?",
	"LightingResetProgress" : "Endrer lysinnstillingene",
	"LockShiftFromP" : "Lås: Girer ut av Park ",
	"LockShiftFromPUnlockInPark" : "Lås: Girer ut av Park Lås opp: I Park",
	"LockUnlock" : "Lås: Ved kjøring Lås opp: I Park",
	"LockWhenDriving" : "Lås: Ved kjøring",
	"LockWhenDrivingUnlockIGNoff" : "Lås: Ved kjøring Lås opp: Tenning av",
	"Long" : "Fjernt",
	"Low" : "Lav",
	"Low_SensitivityLAS" : "Lav",
	"Low_Vibration" : "Lav",
	"Manual" : "Man.",
	"Med" : "Med",
	"Medium" : "Middels",
	"MediumDark" : "Mid mørk",
	"MediumLight" : "Mid lys",
	"Medium_Int_OFF" : "Med",
	"Medium_SensitivityLAS" : "Med",
	"Mid" : "Mid",
	"Middle" : "Midte",
	"Miles" : "mph",
	"Mode" : "Modus",
	"Navigation" : "Navigering",
	"NavigationSignal" : "Navigering  ",
	"Near" : "Nær",
	"Off" : "Av",
	"Often" : "Ofte",
	"Often_Int_OFF" : "Ofte",
	"OnDemand" : "Ved for.",
	"OnceAllDoors" : "Én gang: Alle dører",
	"OnceDriversDoorTwiceAllDoors" : "Én gang: Fører to ganger: Alle dører",
	"Open" : "Åpne",
	"ParkingSensorIndication" : "Indikasjon for parkeringssensor ",
	"ParkingSensorIndicator" : "Indikator for parkeringssensor",
	"RVMBuzzerVolume" : "Rear Vehicle Monitoring Volum",
	"Rare" : "Sjelden",
	"Rare_Int_OFF" : "Sjelden",
	"Reset" : "Tilbakestill",
	"Rotation" : "Rotering",
	"RumbleStrips" : "Roml.",
	"RumbleStrips_line" : "Roml. ",
	"RumbleVolume" : "Ristelydvolum",
	"SBSReset" : "Er du sikker på at du vil tilbakestille innstillingene for Smart Brake Support (SBS) til standardverdier?",
	"SBSResetError" : "Feil ved endring av Smart Brake Support (SBS)-innstillingene. Vil du prøve på nytt?",
	"SBSResetProgress" : "Endrer Smart Brake Support (SBS)-innstillinger",
	"SBSSCBS" : "SBS/SCBS",
	"SBS_SCBSReset" : "Er du sikker på at du vil tilbakestille innstillingene for SBS/SCBS til standardverdiene?",
	"SBS_SCBSResetError" : "Feil ved endring av SBS/SCBS innstillingene. Vil du prøve på nytt?",
	"SBS_SCBSResetProgress" : "Endrer SBS/SCBS innstillingene",
	"SCBS" : "Smart City Brake Support",
	"SCBSReset" : "Er du sikker på at du vil tilbakestille SCBS til fabrikkinnstillinger?",
	"SCBSResetError" : "Kunne ikke tilbakestille SCBS til fabrikkinnstillinger. Vil du prøve på nytt?\"",
	"SCBSResetProgress" : "Tilbakestiller SCBS-innstillinger",
	"SLC_Buzzer" : "Kun signallyd",
	"SLC_Off" : "Av ",
	"SLC_Sign" : "Visuelt",
	"SLC_Sign_Buzzer" : "Lyd og grafikk",
	"SLIReset" : "Er du sikker på at du vil tilbakestille fartsgrenseadvarsler til standardverdiene?",
	"SLIResetError" : "Kunne ikke tilbakestille fartsgrenseadvarsler til fabrikkinnstillinger. Vil du prøve på nytt?",
	"SLIResetProgress" : "Gjenoppretter innstillinger for fartsgrenseadvarsler",
	"SLI_HeadUpDisplay" : "Active Driving Display",
	"Safety" : "Sikkerhet",
	"Safetysettings" : "Sikkerhetsinnstillinger",
	"Sensitivity" : "Følsomhet",
	"Sensitivity_Intervention_OFF" : "Advarsel ",
	"Setting" : "Innstillinger",
	"Settings" : "Innstillinger",
	"Short" : "Nær",
	"SideView" : "Side",
	"SideViewFrontView" : "Side+foran",
	"SmartBrakeSupport" : "Smart Brake Support",
	"Sound" : "Lyd",
	"SpeedAlarm" : "Fartsalarm",
	"SpeedLimitCaution" : "Fartsgrensevarsel",
	"SpeedLimitInformation" : "Fartsgrenseadvarsel",
	"SpeedLimitSign" : "Fartsgrense-visning",
	"StepKilometers" : "{value} km/t",
	"StepMiles" : "{value} mph",
	"StreetInformation" : "Gateinformasjon",
	"Streetinfo_off" : "Av",
	"System" : "System",
	"TSRReset" : "Er du sikker på at du vil gjenopprette innstillinger for automatisk skiltgjenkjenning til standardverdier?",
	"TSRResetError" : "Kunne ikke tilbakestille innstillinger for automatisk skiltgjenkjenning til fabrikkinnstillinger. Vil du prøve på nytt?",
	"TSRResetProgress" : "Gjenoppretter innstillinger for automatisk skiltgjenkjenning",
	"TSR_Display" : "Trafikkskiltvisning",
	"TSR_System" : "Skiltgjenkjenningssystem",
	"Tachometer" : "Turteller",
	"ThreeFlashTurnSignal" : "Blinklys, 3-blink",
	"Timing" : "Tidsplanlegging",
	"Turn" : "Slå over",
	"TurnProgress" : "Endrer svinginnstillingene",
	"TurnReset" : "Er du sikker på at du vil tilbakestille svinginnstillingene til standardverdiene?",
	"TurnResetError" : "Feil ved endring av svinginnstillinger. Vil du prøve på nytt?",
	"TurnSettings" : "Blinklys",
	"TurnSignalIndicatorVolume" : "Blinklys signalvolum",
	"UnlockMode" : "Opplåst modus",
	"Vehicle" : "Kjøretøy",
	"VehicleSettings" : "Kjøretøyinnstillinger",
	"Vibration" : "Vibrasjon",
	"VibrationStrength" : "Vibrasjonsstyrke",
	"Vibration_Line" : "Vibrasjon",
	"ViewSwitchDisplay" : "Standardvisning",
	"ViewSwitchFunction" : "Funksjon for visningsbytte",
	"Volume" : "Volum",
	"WalkAwayLock" : "Walk Away-lås",
	"Warning" : "Advarsel",
	"WarningDistance" : "Advarselsavstand",
	"_0s" : "0 s",
	"_0seconds" : "0 sekunder",
	"_10m" : "10 min",
	"_10minutes" : "10 minutter",
	"_120s" : "120 s",
	"_120seconds" : "120 sekunder",
	"_15s" : "15 s",
	"_15seconds" : "15 sekunder",
	"_30m" : "30 min",
	"_30minutes" : "30 minutter",
	"_30s" : "30 s",
	"_30seconds" : "30 sekunder",
	"_60m" : "60 min",
	"_60minutes" : "60 minutter",
	"_60s" : "60 s",
	"_60seconds" : "60 sekunder",
	"_7p5s" : "7,5 s",
	"_7p5seconds" : "7,5 sekunder",
	"_90s" : "90 s",
	"_90seconds" : "90 sekunder",
	"_AllDoors" : "Alle",
	"_Driver'sDoor" : "Sjåfør.",
	"on" : "På",
};

framework.registerAppDictLoaded("vehsettings", "no_NO");