var Localization_vehsettingsAppDict_ms_MY = {
	//"stringId" : "localString"
	"360ViewCamera" : "Monitor Penglihatan 360 °",
	"AHBC" : "Adaptive LED Headlights",
	"Adaptive" : "Mudah S.",
	"AdaptiveFront-lightingSystem" : "Sistem Lampu Hadapan Mudah Suai",
	"AdaptiveLaneStreetTurn" : "Penyesuaian Lorong/Jalan/Selekoh",
	"AlarmTiming" : "Kelajuan",
	"AlertTiming" : "Pemasaan Amaran",
	"Always" : "Selalu",
	"AtLine" : "Pd Brs",
	"Auto" : "Auto",
	"AutoHeadlightOn" : "Lampu Tinggi Auto dihidupkan",
	"AutoWiper" : "Pengesan Wiper",
	"BSMBuzzerVolume" : "Blind Spot Monitoring Lantang",
	"BSMReset" : "Adakah anda pasti untuk memulihkan tetapan BSM ke lalai kilang?",
	"BSMResetError" : " Tidak dapat untuk memulihkan tetapan BSM ke lalai kilang. Adakah anda ingin mencuba semula?",
	"BSMResetProgress" : "Memulihkan Tetapan BSM",
	"BSMSystem" : "Sistem Pemantauan Tompok Buta ",
	"Beep" : "Beep",
	"BeepVolume" : "Kelantangan Beep",
	"Beep_Line" : "Beep",
	"BeforeLine" : "Sbl Gr",
	"Brightness" : "Kecerahan",
	"BrightnessControl" : "Kawalan Kecerahan",
	"CHudNav_Maneuver" : "Digerakkan",
	"CHudNav_Off" : "Mati",
	"CHudNav_TBT_Lane" : "Panduan Lorong & Selok Belok",
	"CHudNav_TBT_Street" : "Nama Jalan & Selok Belok",
	"Calibration" : "Kecerahan",
	"CautionSpeed" : "Amaran Ambang",
	"CenterDisplay" : "Paparan Tengah",
	"ChangingLASSettings" : "Menukar tetapan Sistem LAS",
	"Clock" : "Jam",
	"Close" : "Tutup",
	"ComingHomeLights" : "Coming Home Light",
	"ComingHomeLightsTimer" : "Coming Home Light",
	"DRSS" : "Distance Recognition Support System",
	"DRSSReset" : "Adakah anda pasti mahu mengembalikan tetapan Distance Recognition Support System kepada nilai lalai?",
	"DRSSResetError" : "Ralat berlaku semasa menukar Distance Recognition Support System (DRSS). Anda mahu cuba semula?",
	"DRSSResetProgress" : "Menukar Distance Recognition Support System",
	"Dark" : "Gelap",
	"DaytimeRunningLights" : "Lampu Dipasang Pada Siang Hari",
	"Devices" : "Peranti",
	"Display" : "Paparan",
	"DisplayInformation" : "Maklumat Paparan",
	"DistanceRecognitionSupportSystem" : "Distance Recognition Support System",
	"DoorLock" : "Kunci Pintu",
	"DoorLockMode" : "Mod Kunci Pintu Auto",
	"DoorLockReset" : "Adakah anda pasti mahu mengembalikan Tetapan Kunci Pintu kepada nilai asalnya?",
	"DoorLockResetError" : "Ralat semasa menukar Tetapan Kunci Pintu. Anda ingin cuba semula?",
	"DoorLockResetProgress" : "Menukar tetapan Kunci Pintu",
	"DoorRelockTime" : "Masa Kunci Semula Auto",
	"DriverAlert" : "Driver Attention Alert",
	"Early" : "Awal",
	"ErrorBSMSettings" : " Ralat menukar tetapan BSM. Adakah anda ingin mencuba semula?",
	"ErrorLASSettings" : "Ralat menukar Lane-keep Assist System. Adakah anda mahu cuba semula?",
	"FOWReset" : "Adakah anda pasti mahu mengembalikan Tetapan Forward Obstruction Warning (FOW) kepada nilai asalnya?",
	"FOWResetError" : "Ralat semasa menukar Tetapan Forward Obstruction Warning (FOW). Anda ingin cuba semula?",
	"FOWResetProgress" : "Menukar Tetapan Forward Obstruction Warning (FOW)",
	"Far" : "Jauh",
	"ForwardObstructionWarning" : "Forward Obstruction Warning",
	"FrontCameraView" : "Pandangan Kamera Hadapan",
	"GearShiftIndicator" : "Penunjuk Anjak Gear",
	"GuidelineDisplay" : "Talian Laluan Dinamik",
	"HUD" : "AD-Disp",
	"HUDDisplayInfoError" : "Suatu ralat berlaku semasa mensetkan semula Tetapan Maklumat AD-Disp. Adakah anda ingin cuba semula?",
	"HUDDisplayInfoReset" : "Adakah anda pasti anda ingin setkan semula tetapan Maklumat AD-Disp kepada nilai lalailnya?",
	"HUDDisplayInfoResetProgress" : "Mensetkan Semula Tetapan Maklumat AD-Disp",
	"HUDJ78AReset" : "Adakah anda pasti anda ingin menetapkan semula tetapan Active Driving Display kepada nilai asalnya?",
	"HUDJ78AResetError" : "Suatu ralat berlaku semasa menetapkan semula Tetapan Active Driving Display. Adakah anda ingin cuba semula?",
	"HUDJ78AResetProgress" : "Menetapkan Semula Tetapan Maklumat Active Driving Display.",
	"HUDJ78ATab" : "Active Driving Display",
	"HUDReset" : "Adakah anda pasti anda mahu mengembalikan Tetapan Active Driving Display (AD-Disp) kepada nilaiasalnya?",
	"HUDResetError" : "Ralat semasa menukar Tetapan Active Driving Display (AD-Disp). Anda ingin cuba semula?",
	"HUDResetProgress" : "Menukar Tetapan Active Driving Display",
	"HUDSettings" : "Tetapan AD-Disp",
	"HUD_HeadUpDisplay" : "Active Driving Display",
	"HeadUpDisplay" : "Active Driving Display",
	"HeadlightOffTimer" : "Pemasa Lampu Puncak Dimatikan",
	"HeadlightOnWarning" : "Amrn Hdp Lmp",
	"HeadsUpDisplay" : "Active Driving Display",
	"Height" : "Ketinggian",
	"High" : "Tinggi",
	"HighBeamControl" : "High Beam Control",
	"High_SensitivityLAS" : "Tinggi",
	"High_Vibration" : "Tinggi",
	"ILB_Bright" : "Terang",
	"ILB_Dark" : "Malap",
	"ILB_Medium" : "Medium",
	"ILB_Off" : "Matikan ",
	"IgONAutoDisplay" : "Monitor Pandangan 360 ° Paparan Auto ",
	"InterioLightsTimeOutDoorsClosed" : "Masa Rehat Cah. Dlm-Pintu Tutup",
	"InterioLightsTimeOutDoorsOpen" : "Masa Rehat Cah. Dlm-Pintu Buka",
	"InteriorLightTimeoutDoorClosedTitle" : "Masa Rht Lmp Dlm-Pintu Tutup",
	"InteriorLightTimeoutDoorOpenTitle" : "Masa Rht Lmp Dlm-Pintu Buka",
	"InteriorLightingBrightness" : "Cahaya Sekeliling",
	"Intervention" : "Intervensi",
	"InterventionTiming" : "Pemasaan Intervensi",
	"KeylessLockBeepVol" : "Kelantangan Beep Kunci Keyless",
	"Kilometers" : "km/j",
	"LASAlert" : "Makluman LAS",
	"LASDefaultValues" : "Adakah anda pasti anda mahu mengembalikan tetapan Lane-keep Assist System  kepada nilai asal?",
	"LASEarly" : "Awal",
	"LASLate" : "Lewat",
	"LASSound" : "Jenis Amaran",
	"LASTiming" : "Pemasa LAS",
	"LDWSReset" : "Adakah anda pasti anda mahu mengembalikan Tetapan Lane Departure Warning System (LDWS) kepada nilai asalnya?",
	"LDWSResetError" : "Ralat semasa menukar Tetapan Lane Departure Warning System (LDWS). Anda ingin cuba semula?",
	"LDWSResetProgress" : "Menukar Tetapan Lane Departure Warning System (LDWS)",
	"LDWSTiming" : "Pemasaan LDWS",
	"LaneDepartureAlert" : "Amaran Keluar Lorong",
	"LaneDepartureWarningSystem" : "Lane Departure Warning System",
	"LaneKeepAssistSystem" : "Lane-keep Assist System",
	"Late" : "Lewat",
	"LeavingHomeLights" : "Leaving Home Light",
	"Light" : "Ringan",
	"LightOnReminderVolume" : "Lampu-on Amaran",
	"Lighting" : "Pencahayaan",
	"LightingReset" : "Adakah anda pasti mahu mengembalikan Tetapan Pencahayaan kepada nilai asalnya?",
	"LightingResetError" : "Ralat semasa menukar Tetapan Pencahayaan. Anda ingin cuba semula?",
	"LightingResetProgress" : "Menukar Tetapan Lampu",
	"LockShiftFromP" : "Kunci: Beralih Dari Parkir ",
	"LockShiftFromPUnlockInPark" : "Kunci: Alih Dr Letak Buka: Di Letak",
	"LockUnlock" : "Kunci: Ketika Pandu Buka: Parkir",
	"LockWhenDriving" : "Kunci: Apabila Memandu",
	"LockWhenDrivingUnlockIGNoff" : "Kunci: memandu, Bukakunci: IGN tutup",
	"Long" : "Jauh",
	"Low" : "Rendah",
	"Low_SensitivityLAS" : "Rendah",
	"Low_Vibration" : "Rendah",
	"Manual" : "Man.",
	"Med" : "Tengah",
	"Medium" : "Tengah",
	"MediumDark" : "Sdrhn Glp",
	"MediumLight" : "Sdrhn Trg",
	"Medium_Int_OFF" : "Tengah",
	"Medium_SensitivityLAS" : "Tengah",
	"Mid" : "Seder.",
	"Middle" : "Tngah",
	"Miles" : "bsj",
	"Mode" : "Mod",
	"Navigation" : "Navigasi",
	"NavigationSignal" : "Navigasi  ",
	"Near" : "Dekat",
	"Off" : "Tutup",
	"Often" : "Kerap",
	"Often_Int_OFF" : "Kerap",
	"OnDemand" : "Dal-Per",
	"OnceAllDoors" : "Sekali: Semua Pintu",
	"OnceDriversDoorTwiceAllDoors" : "Sekali: Pemandu Dua Kali: Semua Pintu",
	"Open" : "Buka",
	"ParkingSensorIndication" : "Indikasi Parking Sensor ",
	"ParkingSensorIndicator" : "Penunjuk Sensor Parkir",
	"RVMBuzzerVolume" : "Rear Vehicle Monitoring Lantang",
	"Rare" : "Jarang",
	"Rare_Int_OFF" : "Jarang",
	"Reset" : "Tetapkan semula",
	"Rotation" : "Putaran",
	"RumbleStrips" : "Derum",
	"RumbleStrips_line" : "Derum ",
	"RumbleVolume" : "Bunyi Degam",
	"SBSReset" : "Adakah anda pasti mahu mengembalikan Smart Brake Supprt (SBS) kepada nilai asalnya?",
	"SBSResetError" : "Ralat berlaku semasa menukar Smart Brake Supprt (SBS). Anda ingin cuba semula?",
	"SBSResetProgress" : "Menukar Smart Brake Supprt (SBS)",
	"SBSSCBS" : "SBS/SCBS",
	"SBS_SCBSReset" : "Adakah anda pasti mahu mengembalikan Tetapan SBS/SCBS kepada nilai asalnya?",
	"SBS_SCBSResetError" : "Ralat semasa menukar Tetapan SBS/SCBS. Anda ingin cuba semula?",
	"SBS_SCBSResetProgress" : "Menukar Tetapan SBS/SCBS",
	"SCBS" : "Smart City Brake Support",
	"SCBSReset" : "Adakah anda pasti untuk memulihkan tetapan SCBS ke lalai kilang?",
	"SCBSResetError" : " Tidak dapat untuk memulihkan tetapan SCBS ke lalai kilang. Adakah anda ingin mencuba semula?",
	"SCBSResetProgress" : "Memulihkan tetapan SCBS",
	"SLC_Buzzer" : "Pembaz sahaja",
	"SLC_Off" : "Matikan ",
	"SLC_Sign" : "Visual",
	"SLC_Sign_Buzzer" : "Audio & Visual",
	"SLIReset" : "Adakah anda pasti untuk memulihkan tetapan Amaran Had Laju kepada nilai lalainya?",
	"SLIResetError" : "Tidak boleh untuk memulihkan tetapan Amaran Had Laju kepada lalai kilang. Adakah anda ingin mencuba semula?",
	"SLIResetProgress" : "Memulihkan tetapan Amaran Had Laju",
	"SLI_HeadUpDisplay" : "Active Driving Display",
	"Safety" : "Keselam",
	"Safetysettings" : "Ttpn Keselamatn",
	"Sensitivity" : "Sensitiviti",
	"Sensitivity_Intervention_OFF" : "Amaran ",
	"Setting" : "Tetapan",
	"Settings" : "Tetapan",
	"Short" : "Dekat",
	"SideView" : "Sisi",
	"SideViewFrontView" : "Sisi+Hadapan",
	"SmartBrakeSupport" : "Smart Brake Support",
	"Sound" : "Bunyi",
	"SpeedAlarm" : "Penggera Kelajuan",
	"SpeedLimitCaution" : "Amaran Had Kelajuan",
	"SpeedLimitInformation" : "Amaran Had Kelajuan",
	"SpeedLimitSign" : "Paparan Had Kelajuan",
	"StepKilometers" : "{value} km/h",
	"StepMiles" : "{value} bsj",
	"StreetInformation" : "Maklumat Jalan",
	"Streetinfo_off" : "Matikan",
	"System" : "Sistem",
	"TSRReset" : "Adakah anda pasti untuk menyimpan tetapan nbsp Sistem Pengecaman Tanda Trafik nbsp kepada nilai lalainya?",
	"TSRResetError" : "Tidak boleh untuk memulihkan nbsp tetapan Sistem Pengecaman Tanda nbsp Trafik kepada lalai kilang. Adakah anda ingin mencuba semula?",
	"TSRResetProgress" : "Memulihkan tetapan nbsp Sistem Pengecaman Tanda Trafik nbsp",
	"TSR_Display" : "Paparan Tanda Trafik",
	"TSR_System" : "Sistem Pengecaman Tanda Trafik",
	"Tachometer" : "Takometer",
	"ThreeFlashTurnSignal" : "Isyarat Membelok 3 denyar",
	"Timing" : "Pemasa",
	"Turn" : "Belok",
	"TurnProgress" : "Menukar Tetapan Belokan",
	"TurnReset" : "Adakah anda pasti anda mahu mengembalikan Tetapan Membelok kepada nilai asalnya?",
	"TurnResetError" : "Ralat semasa menukar Tetapan Membelok. Anda ingin cuba semula?",
	"TurnSettings" : "Belok",
	"TurnSignalIndicatorVolume" : "Volum Isyarat Membelok",
	"UnlockMode" : "Mod Buka",
	"Vehicle" : "Kereta",
	"VehicleSettings" : "Tetapan Kenderaan",
	"Vibration" : "Getaran",
	"VibrationStrength" : "Kekuatan Getaran",
	"Vibration_Line" : "Getaran",
	"ViewSwitchDisplay" : "Paparan Lalai",
	"ViewSwitchFunction" : "Fungsi Tukar Pandangan",
	"Volume" : "Kelantangan",
	"WalkAwayLock" : "Kunci Semasa Pergi",
	"Warning" : "Amaran",
	"WarningDistance" : "Jarak Amaran",
	"_0s" : "0 s",
	"_0seconds" : "0 saat",
	"_10m" : "10 min",
	"_10minutes" : "10 minit",
	"_120s" : "120 s",
	"_120seconds" : "120 saat",
	"_15s" : "15 s",
	"_15seconds" : "15 saat",
	"_30m" : "30 min",
	"_30minutes" : "30 minit",
	"_30s" : "30 s",
	"_30seconds" : "30 saat",
	"_60m" : "60 min",
	"_60minutes" : "60 minit",
	"_60s" : "60 s",
	"_60seconds" : "60 saat",
	"_7p5s" : "7.5 s",
	"_7p5seconds" : "7.5 saat",
	"_90s" : "90 s",
	"_90seconds" : "90 saat",
	"_AllDoors" : "Semua",
	"_Driver'sDoor" : "Pmndu",
	"on" : "Hidup",
};

framework.registerAppDictLoaded("vehsettings", "ms_MY");