var Localization_vehsettingsAppDict_et_EE = {
	//"stringId" : "localString"
	"360ViewCamera" : "360° vaate ekraan",
	"AHBC" : "Adaptive LED Headlights",
	"Adaptive" : "Kohanduv",
	"AdaptiveFront-lightingSystem" : "Kohanduva esitulede süsteemi",
	"AdaptiveLaneStreetTurn" : "Kohanduv rada/tänav/pööre",
	"AlarmTiming" : "Kiiruse",
	"AlertTiming" : "Hoiatuse ajastus",
	"Always" : "Alati",
	"AtLine" : "Joonel",
	"Auto" : "Aut.",
	"AutoHeadlightOn" : "Autom. esitulede sisselülitamine",
	"AutoWiper" : "Vihmaanduriga klaasipuhasti",
	"BSMBuzzerVolume" : "Blind Spot Monitoring Helitug.",
	"BSMReset" : "Kas olete kindel, et tahate BSM-sätete tehase vaikeväärtused taastada?",
	"BSMResetError" : "BSM-sätete tehase vaikeväärtuste taastamine ei õnnestu. Kas soovite uuesti proovida?",
	"BSMResetProgress" : "BSM-sätete taastamine",
	"BSMSystem" : "BSM-süsteem ",
	"Beep" : "Heli",
	"BeepVolume" : "Signaali helitugevus",
	"Beep_Line" : "Heli",
	"BeforeLine" : "Enne j.",
	"Brightness" : "Heledus",
	"BrightnessControl" : "Heleduse reguleerimine",
	"CHudNav_Maneuver" : "Manööver",
	"CHudNav_Off" : "Väljas",
	"CHudNav_TBT_Lane" : "Snd/Pöör",
	"CHudNav_TBT_Street" : "Tn/Pöör",
	"Calibration" : "Heledus",
	"CautionSpeed" : "Häiresignaali lävi",
	"CenterDisplay" : "Keskmine näidik",
	"ChangingLASSettings" : "Muuda Lane-keep Assist System seaded",
	"Clock" : "Kell",
	"Close" : "Sulge",
	"ComingHomeLights" : "Coming Home Light",
	"ComingHomeLightsTimer" : "Coming Home Light",
	"DRSS" : "Distance Recognition Support System",
	"DRSSReset" : "Kas soovite Distance Recognition Support System (DRSS) vaikeväärtused taastada?",
	"DRSSResetError" : "Viga Distance Recognition Support System (DRSS) muutmisel. Kas soovite uuesti proovida?",
	"DRSSResetProgress" : "Distance Recognition Support System (DRSS) muutmine",
	"Dark" : "Tume",
	"DaytimeRunningLights" : "Päevatuled",
	"Devices" : "Seadmed",
	"Display" : "Ekraan",
	"DisplayInformation" : "Näidikuteave",
	"DistanceRecognitionSupportSystem" : "Distance Recognition Support System",
	"DoorLock" : "Kesklukk",
	"DoorLockMode" : "Autom. uste lukustamise režiim",
	"DoorLockReset" : "Kas soovite keskluku sätete vaikeväärtused taastada?",
	"DoorLockResetError" : "Keskluku sätete muutmine ebaõnnestus. Kas proovida uuesti?",
	"DoorLockResetProgress" : "Keskluku sätete muutmine",
	"DoorRelockTime" : "Automaatne taaslukustusaeg",
	"DriverAlert" : "Driver Attention Alert",
	"Early" : "Vara",
	"ErrorBSMSettings" : "Tõrge BSM-sätete muutmisel. Kas soovite uuesti proovida?",
	"ErrorLASSettings" : "Lane-keep Assist System-i sätete muutmisel tekkis viga. Kas soovite uuesti proovida?",
	"FOWReset" : "Kas soovite Forward Obstruction Warning (FOW) vaikeväärtused taastada?",
	"FOWResetError" : "Forward Obstruction Warning (FOW) muutmine ebaõnnestus. Kas proovida uuesti?",
	"FOWResetProgress" : "Forward Obstruction Warning (FOW) muutmine",
	"Far" : "Kauge",
	"ForwardObstructionWarning" : "Forward Obstruction Warning",
	"FrontCameraView" : "Esikaamera vaade",
	"GearShiftIndicator" : "Käiguvahetuse näidik",
	"GuidelineDisplay" : "Dünaamilised teekonnad",
	"HUD" : "AD-Disp",
	"HUDDisplayInfoError" : "AD-Disp-ekraaniteabe seadete vaikeväärtustele lähtestamine ebaõnnestus. Kas soovite uuesti proovida?",
	"HUDDisplayInfoReset" : "Kas olete kindel, et soovite lähtestada AD-Disp-ekraaniteabe seaded nende vaikeväärtustele?",
	"HUDDisplayInfoResetProgress" : "Lähtestan AD-Disp-ekraaniteabe seadeid",
	"HUDJ78AReset" : "Kas olete kindel, et soovite lähtestada Active Driving Display-i seaded nende vaikeväärtustele?",
	"HUDJ78AResetError" : "Active Driving Display-i seadete lähtestamisel tekkis tõrge. Kas soovite uuesti proovida?",
	"HUDJ78AResetProgress" : "Active Driving Display-i seadete lähtestamine",
	"HUDJ78ATab" : "Active Driving Display",
	"HUDReset" : "Kas soovite Active Driving Display vaikeväärtused taastada?",
	"HUDResetError" : "Active Driving Display  muutmine ebaõnnestus. Kas proovida uuesti?",
	"HUDResetProgress" : "AD-Disp sätete muutmine",
	"HUDSettings" : "AD-Disp-i seaded",
	"HUD_HeadUpDisplay" : "Active Driving Display",
	"HeadUpDisplay" : "Active Driving Display",
	"HeadlightOffTimer" : "Esitulede väljalülitamise taimer",
	"HeadlightOnWarning" : "Esitulede hoiatus",
	"HeadsUpDisplay" : "Active Driving Display",
	"Height" : "Kõrgus",
	"High" : "Kõrge",
	"HighBeamControl" : "High Beam Control",
	"High_SensitivityLAS" : "Kõrge",
	"High_Vibration" : "Kõrge",
	"ILB_Bright" : "Hele",
	"ILB_Dark" : "Sume",
	"ILB_Medium" : "Keskmine",
	"ILB_Off" : "Väljas ",
	"IgONAutoDisplay" : "Autom. kuvaga 360° View Monitor",
	"InterioLightsTimeOutDoorsClosed" : "Salongivalg. ajalõpp – uks suletud",
	"InterioLightsTimeOutDoorsOpen" : "Salongivalg. ajalõpp – uks avatud",
	"InteriorLightTimeoutDoorClosedTitle" : "Salongivalg. ajalõpp – uksed sulet.",
	"InteriorLightTimeoutDoorOpenTitle" : "Salongivalg. ajalõpp – uksed avat.",
	"InteriorLightingBrightness" : "Ümbritsev valgustus",
	"Intervention" : "Sekkumine",
	"InterventionTiming" : "Sekkumise ajastus",
	"KeylessLockBeepVol" : "Võtmeta luku signaali helitugevus",
	"Kilometers" : "km/h",
	"LASAlert" : "LAS- hoiatus",
	"LASDefaultValues" : "Kas soovite kindlasti Lane-keep Assist System-i sätete vaikeväärtused taastada?",
	"LASEarly" : "Vara",
	"LASLate" : "Hilja",
	"LASSound" : "Hoiatuse tüüp",
	"LASTiming" : "LAS-i ajastus",
	"LDWSReset" : "Kas soovite Lane Departure Warning System (LDWS) vaikeväärtused taastada?",
	"LDWSResetError" : "Lane Departure Warning System (LDWS) muutmine ebaõnnestus. Kas proovida uuesti?",
	"LDWSResetProgress" : "Lane Departure Warning System (LDWS) muutmine",
	"LDWSTiming" : "LDWS-i ajastus",
	"LaneDepartureAlert" : "Sõidureast lahkumise hoiatus",
	"LaneDepartureWarningSystem" : "Lane Departure Warning System",
	"LaneKeepAssistSystem" : "Lane-keep Assist System",
	"Late" : "Hilja",
	"LeavingHomeLights" : "Leaving Home Light",
	"Light" : "Tuli",
	"LightOnReminderVolume" : "Tul. meeldet. hel.",
	"Lighting" : "Tuled",
	"LightingReset" : "Kas soovite tulede sätete vaikeväärtused taastada?",
	"LightingResetError" : "Tulede sätete muutmine ebaõnnestus. Kas proovida uuesti?",
	"LightingResetProgress" : "Tulede sätete muutmine",
	"LockShiftFromP" : "Lukusta:  käiguvah. parkimisasendist ",
	"LockShiftFromPUnlockInPark" : "Lukusta:  käiguvahetus P-st Ava: P",
	"LockUnlock" : "Lukusta: Sõidu  ava: Parkimisasendis",
	"LockWhenDriving" : "Lukusta:  Sõidu ajal",
	"LockWhenDrivingUnlockIGNoff" : "Lukusta: sõidu ajal Ava: süüde väljas",
	"Long" : "Kaugel",
	"Low" : "Madal",
	"Low_SensitivityLAS" : "Madal",
	"Low_Vibration" : "Madal",
	"Manual" : "Käsitsi",
	"Med" : "Keskm.",
	"Medium" : "Keskmine",
	"MediumDark" : "Ksk.tume",
	"MediumLight" : "Ksk.hele",
	"Medium_Int_OFF" : "Keskm.",
	"Medium_SensitivityLAS" : "Keskm.",
	"Mid" : "Keskm.",
	"Middle" : "Keskm",
	"Miles" : "mph",
	"Mode" : "Režiim",
	"Navigation" : "Navigatsioon",
	"NavigationSignal" : "Navigatsioon  ",
	"Near" : "Lähed.",
	"Off" : "Väljas",
	"Often" : "Sageli",
	"Often_Int_OFF" : "Sageli",
	"OnDemand" : "Nõud.",
	"OnceAllDoors" : "Üks kord: kõik uksed",
	"OnceDriversDoorTwiceAllDoors" : "Korra: juhiuks; kaks korda: kõik uksed",
	"Open" : "Ava",
	"ParkingSensorIndication" : "Parkimisanduri signaal ",
	"ParkingSensorIndicator" : "Parkimisanduri näidik",
	"RVMBuzzerVolume" : "Rear Vehicle Monitoring Helitug.",
	"Rare" : "Harulda.",
	"Rare_Int_OFF" : "Harulda.",
	"Reset" : "Lähtesta",
	"Rotation" : "Pööramine",
	"RumbleStrips" : "Relj.",
	"RumbleStrips_line" : "Relj. ",
	"RumbleVolume" : "Müra helitugevus",
	"SBSReset" : "Kas soovite Smart Brake Support (SBS) vaikeväärtused taastada.",
	"SBSResetError" : "Viga Smart Brake Support (SBS) muutmisel. Kas soovite uuesti proovida?",
	"SBSResetProgress" : "Smart Brake Support (SBS) muutmine",
	"SBSSCBS" : "SBS/SCBS",
	"SBS_SCBSReset" : "Kas soovite SBS/SCBS-sätete vaikeväärtused taastada?",
	"SBS_SCBSResetError" : "SBS/SCBS-sätete muutmine ebaõnnestus. Kas proovida uuesti?",
	"SBS_SCBSResetProgress" : "SBS/SCBS sätete muutmine",
	"SCBS" : "Smart City Brake Support",
	"SCBSReset" : "Kas olete kindel, et tahate SCBS-sätted tehase vaikeväärtustele taastada?",
	"SCBSResetError" : "SCBS-sätete tehase vaikeväärtustele taastamine ei õnnestu. Kas soovite uuesti proovida?",
	"SCBSResetProgress" : "SCBS-sätete taastamine",
	"SLC_Buzzer" : "Ainult sumisti",
	"SLC_Off" : "Väljas ",
	"SLC_Sign" : "Visuaalne",
	"SLC_Sign_Buzzer" : "Heli ja visuaal",
	"SLIReset" : "Kas olete kindel, et tahate taastada kiiruspiirangu hoiatuse seadete vaikeväärtused?",
	"SLIResetError" : "Kiiruspiirangu hoiatuse seadete tehase vaikeväärtuste taastamine ebaõnnestus. Kas soovite uuesti proovida?",
	"SLIResetProgress" : "Kiiruspiirangu hoiatuse seadete taastamine",
	"SLI_HeadUpDisplay" : "Active Driving Display",
	"Safety" : "Ohutus",
	"Safetysettings" : "Ohutussätted",
	"Sensitivity" : "Tundlikkus",
	"Sensitivity_Intervention_OFF" : "Hoiatus ",
	"Setting" : "Seaded",
	"Settings" : "Sätted",
	"Short" : "Lähed",
	"SideView" : "Külg",
	"SideViewFrontView" : "Külg+Esiosa",
	"SmartBrakeSupport" : "Smart Brake Support",
	"Sound" : "Heli",
	"SpeedAlarm" : "Kiiruse alarm",
	"SpeedLimitCaution" : "Kiiruspiirangu häiresignaal",
	"SpeedLimitInformation" : "Kiiruspiirangu hoiatus",
	"SpeedLimitSign" : "Kiiruspiirangu kuvamine",
	"StepKilometers" : "{value} km/h",
	"StepMiles" : "{value} mph",
	"StreetInformation" : "Tänavateave",
	"Streetinfo_off" : "Väljas",
	"System" : "Süsteem",
	"TSRReset" : "Kas olete kindel, et tahate taastada liiklusmärgi tuvastussüsteemi seadete vaikeväärtused?",
	"TSRResetError" : " Liiklusmärgi tuvastussüseemi seadete tehase vaikeväärtuste taastamine ebaõnnestus. Kas soovite uuesti proovida?",
	"TSRResetProgress" : " Liiklusmärgi tuvastussüsteemi seadete taastamine",
	"TSR_Display" : "Liiklusmärgi kuva",
	"TSR_System" : "Liiklusmärgi tuvastussüsteem",
	"Tachometer" : "Tahhomeeter",
	"ThreeFlashTurnSignal" : "3 vilkumist, suunatuli",
	"Timing" : "Ajastus",
	"Turn" : "Suunatuled",
	"TurnProgress" : "Pööramissätete muutmine",
	"TurnReset" : "Kas soovite pööramise sätete vaikeväärtused taastada?",
	"TurnResetError" : "Pööramise sätete muutmine ebaõnnestus. Kas proovida uuesti?",
	"TurnSettings" : "Pööramine",
	"TurnSignalIndicatorVolume" : "Suunatule helitugevus",
	"UnlockMode" : "Lukust vabastatud režiim",
	"Vehicle" : "Sõiduk",
	"VehicleSettings" : "Sõiduki sätted",
	"Vibration" : "Vibratsioon",
	"VibrationStrength" : "Vibratsiooni tugevus",
	"Vibration_Line" : "Vibratsioon",
	"ViewSwitchDisplay" : "Vaikimisi vaade",
	"ViewSwitchFunction" : "Vaate lüliti funktsioon",
	"Volume" : "Helitugevus",
	"WalkAwayLock" : "Eemaldumislukustus",
	"Warning" : "Hoiatus",
	"WarningDistance" : "Hoiatuse kaugus",
	"_0s" : "0 s",
	"_0seconds" : "0 sekundit",
	"_10m" : "10 min",
	"_10minutes" : "10 minutit",
	"_120s" : "120 s",
	"_120seconds" : "120 sekundit",
	"_15s" : "15 s",
	"_15seconds" : "15 sekundit",
	"_30m" : "30 min",
	"_30minutes" : "30 minutit",
	"_30s" : "30 s",
	"_30seconds" : "30 sekundit",
	"_60m" : "60 min",
	"_60minutes" : "60 minutit",
	"_60s" : "60 s",
	"_60seconds" : "60 sekundit",
	"_7p5s" : "7.5 s",
	"_7p5seconds" : "7.5 sekundit",
	"_90s" : "90 s",
	"_90seconds" : "90 sekundit",
	"_AllDoors" : "Kõik",
	"_Driver'sDoor" : "Juhi",
	"on" : "Sees",
};

framework.registerAppDictLoaded("vehsettings", "et_EE");