var Localization_vehsettingsAppDict_pt_PT = {
	//"stringId" : "localString"
	"360ViewCamera" : "Monitor de visualização 360 °",
	"AHBC" : "Adaptive LED Headlights",
	"Adaptive" : "Adaptável",
	"AdaptiveFront-lightingSystem" : "Sistema de Iluminação Frontal Adaptável",
	"AdaptiveLaneStreetTurn" : "Faixa/Rua/Mudança de Direção Adaptável",
	"AlarmTiming" : "Velocid.",
	"AlertTiming" : "Tempo do alerta",
	"Always" : "Sempre",
	"AtLine" : "Linha",
	"Auto" : "Auto",
	"AutoHeadlightOn" : "Farol Dianteiro Automático Ligado",
	"AutoWiper" : "Limpa-pára-brisas com Sens. de Chuva",
	"BSMBuzzerVolume" : "Blind Spot Monitoring Volume",
	"BSMReset" : "Tem a certeza de que pretende reverter as definições de BSM para os valores predefinidos?",
	"BSMResetError" : "Erro ao reverter as definições de BSM para os valores predefinidos.  Pretende tentar novamente?",
	"BSMResetProgress" : "A reverter as definições de BSM",
	"BSMSystem" : "Sistema Blind Spot Monitoring ",
	"Beep" : "Sinal",
	"BeepVolume" : "Volume do Sinal",
	"Beep_Line" : "Sinal",
	"BeforeLine" : "Antes",
	"Brightness" : "Luminosidade",
	"BrightnessControl" : "Controlo de Luminosidade",
	"CHudNav_Maneuver" : "Em manobra",
	"CHudNav_Off" : "Desligado",
	"CHudNav_TBT_Lane" : "Orient. de Faixa e de Naveg.",
	"CHudNav_TBT_Street" : "Orient. Naveg./Nome de rua",
	"Calibration" : "Luminosidade",
	"CautionSpeed" : "Limiar do alerta",
	"CenterDisplay" : "Ecrã central",
	"ChangingLASSettings" : "A alterar definições do LAS",
	"Clock" : "Relógio",
	"Close" : "Fechar",
	"ComingHomeLights" : "Coming Home Light",
	"ComingHomeLightsTimer" : "Coming Home Light",
	"DRSS" : "Distance Recognition Support System",
	"DRSSReset" : "Tem a certeza de que pretende reverter as definições de Distance Recognition Support System (DRSS) para os valores predefinidos?",
	"DRSSResetError" : "Erro ao alterar as definições de Distance Recognition Support System (DRSS). Pretende tentar novamente?",
	"DRSSResetProgress" : "A Alterar Distance Recognition Support System (DRSS)",
	"Dark" : "Escuro",
	"DaytimeRunningLights" : "Luzes Diurnas Permanentes",
	"Devices" : "Disps.",
	"Display" : "Ecrã",
	"DisplayInformation" : "Informações do ecrã",
	"DistanceRecognitionSupportSystem" : "Distance Recognition Support System",
	"DoorLock" : "Bloqueio de Portas",
	"DoorLockMode" : "Modo Bloqueio de Portas Autom.",
	"DoorLockReset" : "Tem a certeza de que pretende reverter as definições de Bloqueio de Portas para os valores predefinidos?",
	"DoorLockResetError" : "Erro ao alterar definições de Bloqueio de Portas. Pretende tentar novamente?",
	"DoorLockResetProgress" : "A Alterar Definições de Bloqueio de Portas",
	"DoorRelockTime" : "Tempo de Novo Bloqueio Autom.",
	"DriverAlert" : "Driver Attention Alert",
	"Early" : "Cedo",
	"ErrorBSMSettings" : "Erro ao alterar as definições de BSM. Pretende tentar novamente?",
	"ErrorLASSettings" : "Erro ao alterar Lane-keep Assist System. Pretende tentar novamente?",
	"FOWReset" : "Tem a certeza de que pretende reverter as definições de Forward Obstruction Warning (FOW) para os valores predefinidos?",
	"FOWResetError" : "Erro ao alterar as definições de Forward Obstruction Warning (FOW). Pretende tentar novamente?",
	"FOWResetProgress" : "A Alterar Forward Obstruction Warning (FOW)",
	"Far" : "Longe",
	"ForwardObstructionWarning" : "Forward Obstruction Warning",
	"FrontCameraView" : "Vista câmara dianteira",
	"GearShiftIndicator" : "Indicador de mudança de velocidade",
	"GuidelineDisplay" : "Linhas tajet. dinâm.",
	"HUD" : "AD-Disp",
	"HUDDisplayInfoError" : "Não foi possível repor as definições das Informações de Visualização do Disp. AD para as predefinições de fábrica. Pretende repetir?",
	"HUDDisplayInfoReset" : "Pretende repor as definições das Informações de Visualização do Disp. AD para os valores predefinidos?",
	"HUDDisplayInfoResetProgress" : "A repor Def. das Inf. de Visualiz. do AD-Disp",
	"HUDJ78AReset" : "Pretende redefinir as Definições Active Driving Display para os valores predefinidos?",
	"HUDJ78AResetError" : "Ocorreu um erro ao redefinir as Definições Active Driving Display. Tentar novamente?",
	"HUDJ78AResetProgress" : "A redefinir Definições Active Driving Display",
	"HUDJ78ATab" : "Active Driving Display",
	"HUDReset" : "Tem a certeza de que pretende reverter as definições de Active Driving Display para os valores predefinidos?",
	"HUDResetError" : "Erro ao alterar as definições de Active Driving Display. Pretende tentar novamente?",
	"HUDResetProgress" : "A Alterar Active Driving Display",
	"HUDSettings" : "Definições AD-Disp",
	"HUD_HeadUpDisplay" : "Active Driving Display",
	"HeadUpDisplay" : "Active Driving Display",
	"HeadlightOffTimer" : "Temporizador para Desligar Faróis",
	"HeadlightOnWarning" : "Aviso Faróis Ligs.",
	"HeadsUpDisplay" : "Active Driving Display",
	"Height" : "Altura",
	"High" : "Alto",
	"HighBeamControl" : "High Beam Control",
	"High_SensitivityLAS" : "Alto",
	"High_Vibration" : "Alto",
	"ILB_Bright" : "Suave",
	"ILB_Dark" : "Escuro",
	"ILB_Medium" : "Médio",
	"ILB_Off" : "Desligado ",
	"IgONAutoDisplay" : "Visualização auto do 360 ° View Monitor",
	"InterioLightsTimeOutDoorsClosed" : "Tempo Ilum. Interior - Porta Fech.",
	"InterioLightsTimeOutDoorsOpen" : "Tempo Ilum. Interior - Porta Aber.",
	"InteriorLightTimeoutDoorClosedTitle" : "Tempo Luz Interior - Portas Fech.",
	"InteriorLightTimeoutDoorOpenTitle" : "Tempo Luz Interior - Portas Aber.",
	"InteriorLightingBrightness" : "Iluminação ambiente",
	"Intervention" : "Intervenção",
	"InterventionTiming" : "Tempo interven.",
	"KeylessLockBeepVol" : "Vol. Sinal Bloqueio por Comando",
	"Kilometers" : "Km/h",
	"LASAlert" : "Alerta LAS",
	"LASDefaultValues" : "Tem a certeza de que pretende reverter as definições do Lane-keep Assist System para os respectivos valores predefinidos?",
	"LASEarly" : "Cedo",
	"LASLate" : "Atrasado",
	"LASSound" : "Tipo de alerta",
	"LASTiming" : "Tempo LAS",
	"LDWSReset" : "Tem a certeza de que pretende reverter as definições de Lane Departure Warning System (LDWS) para os valores predefinidos?",
	"LDWSResetError" : "Erro ao alterar as definições de Lane Departure Warning System (LDWS). Pretende tentar novamente?",
	"LDWSResetProgress" : "A Alterar Lane Departure Warning System (LDWS)",
	"LDWSTiming" : "Tempo de LDWS",
	"LaneDepartureAlert" : "Alerta de saída de faixa",
	"LaneDepartureWarningSystem" : "Lane Departure Warning System",
	"LaneKeepAssistSystem" : "Lane-keep Assist System",
	"Late" : "Atrasado",
	"LeavingHomeLights" : "Leaving Home Light",
	"Light" : "Luz",
	"LightOnReminderVolume" : "Vol Lemb Luz",
	"Lighting" : "Iluminação",
	"LightingReset" : "Tem a certeza de que pretende reverter as definições de Iluminação para os valores predefinidos?",
	"LightingResetError" : "Erro ao alterar definições de Iluminação. Pretende tentar novamente?",
	"LightingResetProgress" : "A Alterar Definições de Iluminação",
	"LockShiftFromP" : "Bloquear: Sair do Estacionamento ",
	"LockShiftFromPUnlockInPark" : "Bloq: Fora estac Desbloq: Estac",
	"LockUnlock" : "Bloq:Condução Desb:Estacionar",
	"LockWhenDriving" : "Bloquear: Na Condução",
	"LockWhenDrivingUnlockIGNoff" : "Bloq: Na Condução Desb:IGN Deslig.",
	"Long" : "Longe",
	"Low" : "Baixo",
	"Low_SensitivityLAS" : "Baixo",
	"Low_Vibration" : "Baixo",
	"Manual" : "Man.",
	"Med" : "Médio",
	"Medium" : "Médio",
	"MediumDark" : "Escuro Médio",
	"MediumLight" : "Luz Média",
	"Medium_Int_OFF" : "Médio",
	"Medium_SensitivityLAS" : "Médio",
	"Mid" : "Meio",
	"Middle" : "Meio",
	"Miles" : "Mph",
	"Mode" : "Modo",
	"Navigation" : "Navegação",
	"NavigationSignal" : "Navegação  ",
	"Near" : "Próx.",
	"Off" : "Deslig.",
	"Often" : "Freq.",
	"Often_Int_OFF" : "Freq.",
	"OnDemand" : "A ped.",
	"OnceAllDoors" : "Uma Vez: Todas as Portas",
	"OnceDriversDoorTwiceAllDoors" : "1 Vez: Condut. 2 Vezes: Tod. Portas",
	"Open" : "Abrir",
	"ParkingSensorIndication" : "Indicação dos Sensor de Estacionamento ",
	"ParkingSensorIndicator" : "Indicador do sensor de estacionamento",
	"RVMBuzzerVolume" : "Rear Vehicle Monitoring Volume",
	"Rare" : "Raro",
	"Rare_Int_OFF" : "Raro",
	"Reset" : "Repor",
	"Rotation" : "Rotação",
	"RumbleStrips" : "Banda",
	"RumbleStrips_line" : "Banda ",
	"RumbleVolume" : "Vol. Banda",
	"SBSReset" : "Tem a certeza de que pretende reverter as definições de Smart Brake Support (SBS) para os valores predefinidos?",
	"SBSResetError" : "Erro ao alterar as definições de Smart Brake Support (SBS). Pretende tentar novamente?",
	"SBSResetProgress" : "A Alterar Smart Brake Support (SBS)",
	"SBSSCBS" : "SBS/SCBS",
	"SBS_SCBSReset" : "Tem a certeza de que pretende reverter as definições de SBS/SCBS para os valores predefinidos?",
	"SBS_SCBSResetError" : "Erro ao alterar as definições de SBS/SCBS. Pretende tentar novamente?",
	"SBS_SCBSResetProgress" : "A Alterar SBS/SCBS",
	"SCBS" : "Smart City Brake Support",
	"SCBSReset" : "Tem a certeza de que pretende reverter as definições de SCBS para os valores predefinidos?\"",
	"SCBSResetError" : "Erro ao reverter as definições de SCBS para os valores predefinidos. Pretende tentar novamente?\"",
	"SCBSResetProgress" : "A reverter as definições de SCBS",
	"SLC_Buzzer" : "Só buzina",
	"SLC_Off" : "Desligado ",
	"SLC_Sign" : "Visual",
	"SLC_Sign_Buzzer" : "Audiovisual",
	"SLIReset" : "Tem a certeza de que pretende repor as definições do Aviso de Limite de Velocidade para os valores predefinidos?",
	"SLIResetError" : "Não foi possível repor as definições do Aviso de Limite de Velocidade para os valores predefinidos. Pretende tentar novamente?",
	"SLIResetProgress" : "A repor as definições do Aviso de Limite de Velocidade",
	"SLI_HeadUpDisplay" : "Active Driving Display",
	"Safety" : "Seguran.",
	"Safetysettings" : "Def. de Segur.",
	"Sensitivity" : "Sensibilidade",
	"Sensitivity_Intervention_OFF" : "Aviso ",
	"Setting" : "Definições",
	"Settings" : "Definições",
	"Short" : "Próx.",
	"SideView" : "Lateral",
	"SideViewFrontView" : "Lateral+Dianteira",
	"SmartBrakeSupport" : "Smart Brake Support",
	"Sound" : "Som",
	"SpeedAlarm" : "Alarme de velocidade",
	"SpeedLimitCaution" : "Alerta de limite de velocidade",
	"SpeedLimitInformation" : "Aviso de limite de velocidade",
	"SpeedLimitSign" : "Apresentação do limite de velocidade",
	"StepKilometers" : "{value} km/h",
	"StepMiles" : "{value} Mph",
	"StreetInformation" : "Informações sobre a via",
	"Streetinfo_off" : "Desligado",
	"System" : "Sistema",
	"TSRReset" : "Tem a certeza de que pretende repor as definições do Sistema de Reconhecimento de Sinais de Trânsito para os valores predefinidos?",
	"TSRResetError" : "Não foi possível repor as definições do Sistema de Reconhecimento de Sinais para os valores predefinidos. Pretende tentar novamente?",
	"TSRResetProgress" : "A repor as definições do Sistema de Reconhecimento de Sinais de Trânsito ",
	"TSR_Display" : "Ecrã de Sinais de Trânsito",
	"TSR_System" : "Sistema de Reconhecimento de Sinais de Trânsito",
	"Tachometer" : "Taquímetro",
	"ThreeFlashTurnSignal" : "Sinal Mudança de Direcção de 3 piscas",
	"Timing" : "Tempo",
	"Turn" : "Mudança de Direcção",
	"TurnProgress" : "A Alterar Definições de Mudança de Direcção",
	"TurnReset" : "Tem a certeza de que pretende reverter as definições de Mudança de Direcção para os valores predefinidos?",
	"TurnResetError" : "Erro ao alterar definições de Mudança de Direcção. Pretende tentar novamente?",
	"TurnSettings" : "Mudança de Direcção",
	"TurnSignalIndicatorVolume" : "Vol. da Mudança Direcção",
	"UnlockMode" : "Modo de Desbloqueio",
	"Vehicle" : "Veículo",
	"VehicleSettings" : "Def. do Veículo",
	"Vibration" : "Vibração",
	"VibrationStrength" : "Intensidade vibração",
	"Vibration_Line" : "Vibração",
	"ViewSwitchDisplay" : "Visualização predefinida",
	"ViewSwitchFunction" : "Função Mudar de Vista",
	"Volume" : "Volume",
	"WalkAwayLock" : "Bloqueio Automático (deixar)",
	"Warning" : "Aviso",
	"WarningDistance" : "Distân. de Aviso",
	"_0s" : "0 s",
	"_0seconds" : "0 segundos",
	"_10m" : "10 min",
	"_10minutes" : "10 minutos",
	"_120s" : "120 s",
	"_120seconds" : "120 segundos",
	"_15s" : "15 s",
	"_15seconds" : "15 segundos",
	"_30m" : "30 min",
	"_30minutes" : "30 minutos",
	"_30s" : "30 s",
	"_30seconds" : "30 segundos",
	"_60m" : "60 min",
	"_60minutes" : "60 minutos",
	"_60s" : "60 s",
	"_60seconds" : "60 segundos",
	"_7p5s" : "7,5 s",
	"_7p5seconds" : "7,5 segundos",
	"_90s" : "90 s",
	"_90seconds" : "90 segundos",
	"_AllDoors" : "Todas",
	"_Driver'sDoor" : "Conduc.",
	"on" : "Em",
};

framework.registerAppDictLoaded("vehsettings", "pt_PT");