var Localization_vehsettingsAppDict_es_MX = {
	//"stringId" : "localString"
	"360ViewCamera" : "Monitor con vista de 360°",
	"AHBC" : "Adaptive LED Headlights",
	"Adaptive" : "Adaptable",
	"AdaptiveFront-lightingSystem" : "Sistema de luces adaptativas",
	"AdaptiveLaneStreetTurn" : "Adaptable a Carril/Calle/Giro",
	"AlarmTiming" : "Velocidad",
	"AlertTiming" : "Momento alerta",
	"Always" : "Siempre",
	"AtLine" : "Línea",
	"Auto" : "Auto",
	"AutoHeadlightOn" : "Activación de luz automática",
	"AutoWiper" : "Sistema de detección de lluvia",
	"BSMBuzzerVolume" : "Blind Spot Monitoring Volumen",
	"BSMReset" : "¿Estás seguro de que deseas restablecer todos los ajustes de BSM a los valores de fábrica?",
	"BSMResetError" : "Error al restablecer los ajustes de BSM a los valores de de fábrica. ¿Deseas reintentarlo?",
	"BSMResetProgress" : "Restablecer los ajustes de BSM",
	"BSMSystem" : "Sistema de Blind Spot Monitoring ",
	"Beep" : "Pitido",
	"BeepVolume" : "Volumen del Pitido",
	"Beep_Line" : "Pitido",
	"BeforeLine" : "Antes",
	"Brightness" : "Brillo",
	"BrightnessControl" : "Ajustes de brillo",
	"CHudNav_Maneuver" : "Al maniobrar",
	"CHudNav_Off" : "Off",
	"CHudNav_TBT_Lane" : "Guía de carril y Giro a giro",
	"CHudNav_TBT_Street" : "Nombre de la calle y Giro a giro",
	"Calibration" : "Brillo",
	"CautionSpeed" : "Umbral de alerta",
	"CenterDisplay" : "Pantalla central",
	"ChangingLASSettings" : "Camb. Aj. de Lane-keep Assist System",
	"Clock" : "Reloj",
	"Close" : "Cerrar",
	"ComingHomeLights" : "Coming Home Light",
	"ComingHomeLightsTimer" : "Coming Home Light",
	"DRSS" : "Distance Recognition Support System",
	"DRSSReset" : "¿Desea revertir las configuraciones de DRSS a sus valores predeterminados?",
	"DRSSResetError" : "Error cambiando el Distance Recognition Support System (DRSS). ¿Desea reintentarlo?",
	"DRSSResetProgress" : "Cambiando Distance Recognition Support System (DRSS)",
	"Dark" : "Oscuro",
	"DaytimeRunningLights" : "Luces de posición de día",
	"Devices" : "Aparatos",
	"Display" : "Pantalla",
	"DisplayInformation" : "Información de pantalla",
	"DistanceRecognitionSupportSystem" : "Distance Recognition Support System",
	"DoorLock" : "Bloqueo de Puerta",
	"DoorLockMode" : "Modo Bloq Puerta Autom",
	"DoorLockReset" : "Desea reiniciar los ajustes de bloqueo de puerta a valores de fábrica?",
	"DoorLockResetError" : "Error al cambiar la Configuración de Bloqueo de Puerta. ¿Desea reintentar?",
	"DoorLockResetProgress" : "Cambiando Config. De Bloqueo de Puerta",
	"DoorRelockTime" : "Tiempo de bloqueo automático",
	"DriverAlert" : "Driver Attention Alert",
	"Early" : "Temprano",
	"ErrorBSMSettings" : "Error al cambiar los ajustes de BSM ¿Deseas reintentarlo?",
	"ErrorLASSettings" : "Error al hacer cambios en Lane-keep Assist System. ¿Desea volver a intentarlo?",
	"FOWReset" : "¿Está Desea revertir las configuraciones Forward Obstruction Warning (FOW) a sus valores predeterminados?",
	"FOWResetError" : "Error cambiando el Forward Obstruction Warning (FOW) ¿Desea reintentarlo?",
	"FOWResetProgress" : "Cambiando Forward Obstruction Warning (FOW)",
	"Far" : "Lejos",
	"ForwardObstructionWarning" : "Forward Obstruction Warning",
	"FrontCameraView" : "Vista cámara delantera",
	"GearShiftIndicator" : "Indicador de cambio de velocidad",
	"GuidelineDisplay" : "Lín. camino vehículo",
	"HUD" : "AD-Disp",
	"HUDDisplayInfoError" : "No se puede restablecer la configuración información de la pantalla de conducción activa a los valores predeterminados de fábrica. ¿Desea volver a intentarlo?",
	"HUDDisplayInfoReset" : "¿Está seguro de que desea restablecer la configuración de información de la pantalla de conducción activa a los valores predeterminados?",
	"HUDDisplayInfoResetProgress" : "Restablec. config. de info en pant. cond. activa",
	"HUDJ78AReset" : "¿Está seguro de que desea restablecer la configuración de Active Driving Display a los valores predeterminados?",
	"HUDJ78AResetError" : "Se produjo un error al restablecer la configuración de Active Driving Display. ¿Desea volver a intentarlo?",
	"HUDJ78AResetProgress" : "Restablecimiento de la configuración de Active Driving Display",
	"HUDJ78ATab" : "Active Driving Display",
	"HUDReset" : "¿Desea reiniciar los ajsutes de Active Driving Display a los valores de fábrica?",
	"HUDResetError" : "Error al configurar los ajustes de Active Driving Display. ¿Desea reintentar?",
	"HUDResetProgress" : "Cambiando Config. Active Driving Display",
	"HUDSettings" : "Config. de AD-Disp",
	"HUD_HeadUpDisplay" : "Active Driving Display",
	"HeadUpDisplay" : "Pantalla de visualización frontal",
	"HeadlightOffTimer" : "Temporizador de Luz Apagado",
	"HeadlightOnWarning" : "Luz de alerta encendida",
	"HeadsUpDisplay" : "Active Driving Display",
	"Height" : "Altura",
	"High" : "Alto",
	"HighBeamControl" : "High Beam Control",
	"High_SensitivityLAS" : "Alto",
	"High_Vibration" : "Alto",
	"ILB_Bright" : "Brillante",
	"ILB_Dark" : "Tenue",
	"ILB_Medium" : "Medio",
	"ILB_Off" : "Off ",
	"IgONAutoDisplay" : "Pantalla automática 360° View Monitor",
	"InterioLightsTimeOutDoorsClosed" : "Lím tpo Luz Int – Puerta Cerrada",
	"InterioLightsTimeOutDoorsOpen" : "Lím tpo Luz Int – Puerta Abierta",
	"InteriorLightTimeoutDoorClosedTitle" : "Lím tpo Luz Int – Puerta Cerrada",
	"InteriorLightTimeoutDoorOpenTitle" : "Lím tpo Luz Int – Puerta Abierta",
	"InteriorLightingBrightness" : "Iluminación del interior",
	"Intervention" : "Intervención",
	"InterventionTiming" : "Momento interven.",
	"KeylessLockBeepVol" : "Pitido de bloqueo sin llave",
	"Kilometers" : "km/h",
	"LASAlert" : "Alerta LAS",
	"LASDefaultValues" : "¿Desea realmente restaurar los ajustes predeterminados de Lane-keep Assist System?",
	"LASEarly" : "Temprano",
	"LASLate" : "Tarde",
	"LASSound" : "Tipo de alerta",
	"LASTiming" : "Tiempo LAS",
	"LDWSReset" : "¿Está Desea revertir las configuraciones Lane Departure Warning System (LDWS) a sus valores predeterminados?",
	"LDWSResetError" : "Error cambiando el Lane Departure Warning System (LDWS) ¿Desea reintentarlo?",
	"LDWSResetProgress" : "Cambiando Lane Departure Warning System (LDWS)",
	"LDWSTiming" : "Tiempo LDWS",
	"LaneDepartureAlert" : "Alerta de salida de carril",
	"LaneDepartureWarningSystem" : "Lane Departure Warning System",
	"LaneKeepAssistSystem" : "Lane-keep Assist System",
	"Late" : "Tarde",
	"LeavingHomeLights" : "Leaving Home Light",
	"Light" : "Brillante",
	"LightOnReminderVolume" : "Vol. Aviso Luz",
	"Lighting" : "Iluminación",
	"LightingReset" : "¿Desea reiniciar los ajustes de luz a valores de fábrica?",
	"LightingResetError" : "Error al cambiar la Configuración de Luz. ¿Desea Reintentar?",
	"LightingResetProgress" : "Cambiando los ajustes de iluminación",
	"LockShiftFromP" : "Bloqueo: Salir Modo aparcamiento ",
	"LockShiftFromPUnlockInPark" : "Bloq: No Aparcar Desbloq: Aparcar",
	"LockUnlock" : "Bloq: Al conducir Desbloq: Aparcar",
	"LockWhenDriving" : "Bloqueo: Cuando Maneja",
	"LockWhenDrivingUnlockIGNoff" : "Bloq: Al Manejar Desbloq: IGN Off",
	"Long" : "Lejos",
	"Low" : "Bajo",
	"Low_SensitivityLAS" : "Bajo",
	"Low_Vibration" : "Bajo",
	"Manual" : "Man",
	"Med" : "Medio",
	"Medium" : "Medio",
	"MediumDark" : "Tenue",
	"MediumLight" : "Brillo med",
	"Medium_Int_OFF" : "Medio",
	"Medium_SensitivityLAS" : "Medio",
	"Mid" : "Medio",
	"Middle" : "Medio",
	"Miles" : "mph",
	"Mode" : "Modo",
	"Navigation" : "Navegación",
	"NavigationSignal" : "Navegación  ",
	"Near" : "Cerca",
	"Off" : "Off",
	"Often" : "A veces",
	"Often_Int_OFF" : "A veces",
	"OnDemand" : "A ped.",
	"OnceAllDoors" : "Una vez: Todas las Puertas",
	"OnceDriversDoorTwiceAllDoors" : "Una vez: Cond. Dos: todas puertas",
	"Open" : "Abrir",
	"ParkingSensorIndication" : "Indicación de sensor de aparcamiento\n ",
	"ParkingSensorIndicator" : "Indicación de sensor de aparcamiento",
	"RVMBuzzerVolume" : "Rear Vehicle Monitoring Volumen",
	"Rare" : "Raro",
	"Rare_Int_OFF" : "Raro",
	"Reset" : "Reiniciar",
	"Rotation" : "Rotación",
	"RumbleStrips" : "B. Son",
	"RumbleStrips_line" : "B. Son ",
	"RumbleVolume" : "Vol. B. Sonora",
	"SBSReset" : "¿Está Desea revertir las configuraciones Smart Brake Support (SBS) a sus valores predeterminados?",
	"SBSResetError" : "Error cambiando el Smart Brake Support (SBS) ¿Desea reintentarlo?",
	"SBSResetProgress" : "Cambiando Smart Brake Support (SBS)",
	"SBSSCBS" : "SBS/SCBS",
	"SBS_SCBSReset" : "¿Desea reiniciar los ajustes de SBS/SCBS a valores de fábrica?",
	"SBS_SCBSResetError" : "Error al cambiar la Configuración SBS/SCBS. ¿Desea reintentar?",
	"SBS_SCBSResetProgress" : "Cambiando Config. SBS/SCBS",
	"SCBS" : "Smart City Brake Support",
	"SCBSReset" : "¿Estás seguro de que deseas restaurar los ajustes de SCBS a los valores de fábrica?",
	"SCBSResetError" : "Error al restablecer los ajustes de SBSM a los valores de de fábrica. ¿Deseas reintentarlo?\"",
	"SCBSResetProgress" : "Restableciendo ajustes de SCBS",
	"SLC_Buzzer" : "Solo zumbador",
	"SLC_Off" : "Off ",
	"SLC_Sign" : "Visual",
	"SLC_Sign_Buzzer" : "Auditiva y visual",
	"SLIReset" : "¿Está seguro de que desea restablecer la configuración de advertencia de límite de velocidad a los valores predeterminados?",
	"SLIResetError" : "No se puede restablecer la configuración de advertencia de límite de velocidad a los valores predeterminados de fábrica. ¿Desea volver a intentarlo?",
	"SLIResetProgress" : "Restableciendo la configuración de advertencia de límite de velocidad",
	"SLI_HeadUpDisplay" : "Active Driving Display",
	"Safety" : "Seguri.",
	"Safetysettings" : "Ajuste de seguridad",
	"Sensitivity" : "Sensibilidad",
	"Sensitivity_Intervention_OFF" : "Advertencia ",
	"Setting" : "Configuración",
	"Settings" : "Configuraciones",
	"Short" : "Cerca",
	"SideView" : "Lateral",
	"SideViewFrontView" : "Lateral+Frente",
	"SmartBrakeSupport" : "Smart Brake Support",
	"Sound" : "Sonido",
	"SpeedAlarm" : "Alarma de velocidad",
	"SpeedLimitCaution" : "Alerta de límite de velocidad",
	"SpeedLimitInformation" : "Adv. de lím. vel.",
	"SpeedLimitSign" : "Mostrar límite de velocidad",
	"StepKilometers" : "{value} km/h",
	"StepMiles" : "{value} mph",
	"StreetInformation" : "Información de la calle",
	"Streetinfo_off" : "Off",
	"System" : "Sistema",
	"TSRReset" : "¿Está seguro de que desea restablecer la configuración del Sistema de reconocimiento de señales de tránsito a los valores predeterminados?",
	"TSRResetError" : "Error al restablecer la configuración del Sistema de reconocimiento de señales de tránsito a los valores de fábrica. ¿Desea reintentarlo?",
	"TSRResetProgress" : "Restableciendo la configuración del Sistema de reconocimiento de señales de tránsito ",
	"TSR_Display" : "Mostrar señales de tránsito",
	"TSR_System" : "Sistema de reconocimiento de señales de tránsito",
	"Tachometer" : "Tacómetro",
	"ThreeFlashTurnSignal" : "Tres destellos como señal intermitente",
	"Timing" : "Tiempo",
	"Turn" : "Girar",
	"TurnProgress" : "Cambiando Config. De giro",
	"TurnReset" : "Desea reiniciar los ajustes de Giro a valores de fábrica?",
	"TurnResetError" : "Error al cambiar la Configuración de Giro. ¿Desea reintentar?",
	"TurnSettings" : "Girar",
	"TurnSignalIndicatorVolume" : "Vol Señal Intermit",
	"UnlockMode" : "Modo Desbloquear",
	"Vehicle" : "Vehículo",
	"VehicleSettings" : "Config vehículo",
	"Vibration" : "Vibración",
	"VibrationStrength" : "Potencia vibración",
	"Vibration_Line" : "Vibración",
	"ViewSwitchDisplay" : "Vista predeterminada",
	"ViewSwitchFunction" : "Función cambio de vista",
	"Volume" : "Volumen",
	"WalkAwayLock" : "Bloqueo al Alejarse",
	"Warning" : "Advertencia",
	"WarningDistance" : "Dist de Alerta",
	"_0s" : "0 s",
	"_0seconds" : "0 segundos",
	"_10m" : "10 min",
	"_10minutes" : "10 minutos",
	"_120s" : "120 s",
	"_120seconds" : "120 segundos",
	"_15s" : "15 s",
	"_15seconds" : "15 segundos",
	"_30m" : "30 min",
	"_30minutes" : "30 minutos",
	"_30s" : "30 s",
	"_30seconds" : "30 segundos",
	"_60m" : "60 min",
	"_60minutes" : "60 minutos",
	"_60s" : "60 s",
	"_60seconds" : "60 segundos",
	"_7p5s" : "7.5 s",
	"_7p5seconds" : "7.5 segundos",
	"_90s" : "90 s",
	"_90seconds" : "90 segundos",
	"_AllDoors" : "Todas",
	"_Driver'sDoor" : "Cond.",
	"on" : "On",
};

framework.registerAppDictLoaded("vehsettings", "es_MX");