var Localization_vehsettingsAppDict_cn_HK = {
	//"stringId" : "localString"
	"360ViewCamera" : "360° 影像攝像頭",
	"AHBC" : "Adaptive LED Headlights",
	"Adaptive" : "適應",
	"AdaptiveFront-lightingSystem" : "自動轉向頭燈系統",
	"AdaptiveLaneStreetTurn" : "自適應車道/街道/轉向",
	"AlarmTiming" : "速度設定",
	"AlertTiming" : "警示定時",
	"Always" : "總是",
	"AtLine" : "在",
	"Auto" : "自動",
	"AutoHeadlightOn" : "自動大燈感光度",
	"AutoWiper" : "雨點感應水撥",
	"BSMBuzzerVolume" : "Blind Spot Monitoring 音量",
	"BSMReset" : "是否確定要將 BSM 設定還原為出廠預設？ ",
	"BSMResetError" : "無法將 BSM 設定還原為出廠預設？ 是否要重試？ ",
	"BSMResetProgress" : "正在還原 BSM 設定 ",
	"BSMSystem" : "Blind Spot Monitoring 系統 ",
	"Beep" : "蜂鳴聲",
	"BeepVolume" : "提示音音量",
	"Beep_Line" : "蜂鳴聲",
	"BeforeLine" : "之前",
	"Brightness" : "亮度",
	"BrightnessControl" : "亮度控制",
	"CHudNav_Maneuver" : "調遣中",
	"CHudNav_Off" : "關",
	"CHudNav_TBT_Lane" : "道路與逐向指引",
	"CHudNav_TBT_Street" : "街道名與逐向導航",
	"Calibration" : "亮度",
	"CautionSpeed" : "警示閾值",
	"CenterDisplay" : "中央顯示器",
	"ChangingLASSettings" : "正在更改 Lane-keep Assist System 設定",
	"Clock" : "時鐘",
	"Close" : "關閉",
	"ComingHomeLights" : "Coming Home Light",
	"ComingHomeLightsTimer" : "Coming Home Light",
	"DRSS" : "Distance Recognition Support System",
	"DRSSReset" : "確定要將 Distance Recognition Support System 設定還原為其預設值？",
	"DRSSResetError" : "無法將 Distance Recognition Support System 設定還原為出廠預設。 是否要重試？",
	"DRSSResetProgress" : "Distance Recognition Support System",
	"Dark" : "低",
	"DaytimeRunningLights" : "白天行車照明",
	"Devices" : "裝置",
	"Display" : "顯示",
	"DisplayInformation" : "顯示資料",
	"DistanceRecognitionSupportSystem" : "Distance Recognition Support System",
	"DoorLock" : "門鎖",
	"DoorLockMode" : "自動車門鎖定模式",
	"DoorLockReset" : "確定要將車門鎖定設定還原為出廠預設？",
	"DoorLockResetError" : "無法將車門鎖定設定還原為出廠預設。 是否要重試？",
	"DoorLockResetProgress" : "正在還原車門鎖定設定",
	"DoorRelockTime" : "自動重鎖時間",
	"DriverAlert" : "Driver Attention Alert",
	"Early" : "較早",
	"ErrorBSMSettings" : "更改 BSM 設定時出錯。是否要重試？ ",
	"ErrorLASSettings" : "更改 Lane-keep Assist System 時出錯 是否要重試？",
	"FOWReset" : "確定要將 Forward Obstruction Warning  設定還原為其預設值？",
	"FOWResetError" : "無法將 Forward Obstruction Warning 設定還原為出廠預設。 是否要重試？",
	"FOWResetProgress" : "正在還原 Forward Obstruction Warning 設定",
	"Far" : "遠",
	"ForwardObstructionWarning" : "Forward Obstruction Warning",
	"FrontCameraView" : "前方攝像頭影像",
	"GearShiftIndicator" : "換檔指示燈",
	"GuidelineDisplay" : "動態路線",
	"HUD" : "AD-Disp",
	"HUDDisplayInfoError" : "無法將「AD-Disp 顯示資訊」設定還原為出廠預設。 是否要重試？",
	"HUDDisplayInfoReset" : "是否確定要將「AD-Disp 顯示資訊」的設定還原為其預設值？",
	"HUDDisplayInfoResetProgress" : "還原「AD-Disp 顯示資訊」設定",
	"HUDJ78AReset" : "是否確定將 Active Driving Display 設定重設為預設值？",
	"HUDJ78AResetError" : "重設Active Driving Display 設定時發生錯誤。 是否要重試？",
	"HUDJ78AResetProgress" : "重設 Active Driving Display 設定",
	"HUDJ78ATab" : "Active Driving Display",
	"HUDReset" : "確定要將 Active Driving Display 設定還原為其預設值？",
	"HUDResetError" : "無法將 Active Driving Display 還原為出廠預設。 是否要重試？",
	"HUDResetProgress" : "正在更改 Active Driving Display 設定",
	"HUDSettings" : "AD-Disp 設定",
	"HUD_HeadUpDisplay" : "Active Driving Display",
	"HeadUpDisplay" : "Active Driving Display",
	"HeadlightOffTimer" : "大燈關閉計時器",
	"HeadlightOnWarning" : "大燈打開警告",
	"HeadsUpDisplay" : "Active Driving Display",
	"Height" : "高度",
	"High" : "高",
	"HighBeamControl" : "High Beam Control",
	"High_SensitivityLAS" : "高",
	"High_Vibration" : "強",
	"ILB_Bright" : "亮",
	"ILB_Dark" : "暗",
	"ILB_Medium" : "中",
	"ILB_Off" : "關 ",
	"IgONAutoDisplay" : "自動顯示 360° 影像攝像頭 ",
	"InterioLightsTimeOutDoorsClosed" : "關閉車內照明-當車門關閉",
	"InterioLightsTimeOutDoorsOpen" : "關閉車內照明-當車門打開",
	"InteriorLightTimeoutDoorClosedTitle" : "關閉車內照明-當車門關閉",
	"InteriorLightTimeoutDoorOpenTitle" : "關閉車內照明-當車門打開",
	"InteriorLightingBrightness" : "環境照明",
	"Intervention" : "間隔",
	"InterventionTiming" : "間隔定時",
	"KeylessLockBeepVol" : "無鑰匙鎖定提示音音量",
	"Kilometers" : "km/h",
	"LASAlert" : "LAS 警示",
	"LASDefaultValues" : "確定要將 Lane-keep Assist System 設定還原為其預設值？",
	"LASEarly" : "較早",
	"LASLate" : "較晚",
	"LASSound" : "警示類型",
	"LASTiming" : "LAS 定時",
	"LDWSReset" : "確定要將 Lane Departure Warning System 設定還原為其預設值？",
	"LDWSResetError" : "無法將 Lane Departure Warning System 設定還原為出廠預設。 是否要重試？",
	"LDWSResetProgress" : "正在還原 Lane Departure Warning System 設定",
	"LDWSTiming" : "LDWS 定時",
	"LaneDepartureAlert" : "Lane Departure 警示",
	"LaneDepartureWarningSystem" : "Lane Departure Warning System",
	"LaneKeepAssistSystem" : "Lane-keep Assist System",
	"Late" : "較晚",
	"LeavingHomeLights" : "Leaving Home Light",
	"Light" : "高",
	"LightOnReminderVolume" : "開啟燈光音量",
	"Lighting" : "照明",
	"LightingReset" : "確定要將照明設定還原為出廠預設？",
	"LightingResetError" : "無法將照明設定還原為出廠預設。 是否要重試？",
	"LightingResetProgress" : "正在還原照明設定",
	"LockShiftFromP" : "鎖門： 停車模式切換 ",
	"LockShiftFromPUnlockInPark" : "鎖門：離開停車 解鎖：停車",
	"LockUnlock" : "鎖門： 駕駛時 解鎖： 處於停車模式",
	"LockWhenDriving" : "鎖門： 駕駛時",
	"LockWhenDrivingUnlockIGNoff" : "鎖門： 駕駛時 解鎖： IGN 關閉",
	"Long" : "遠",
	"Low" : "低",
	"Low_SensitivityLAS" : "低",
	"Low_Vibration" : "弱",
	"Manual" : "手動",
	"Med" : "適中",
	"Medium" : "適中",
	"MediumDark" : "中低",
	"MediumLight" : "中高",
	"Medium_Int_OFF" : "適中",
	"Medium_SensitivityLAS" : "中",
	"Mid" : "中",
	"Middle" : "中",
	"Miles" : "mph",
	"Mode" : "啟動",
	"Navigation" : "導航",
	"NavigationSignal" : "導航  ",
	"Near" : "近",
	"Off" : "關閉",
	"Often" : "頻密",
	"Often_Int_OFF" : "頻密",
	"OnDemand" : "隨選",
	"OnceAllDoors" : "全部車門： 一次",
	"OnceDriversDoorTwiceAllDoors" : "駕駛者門：一次，全部車門： 兩次",
	"Open" : "打開",
	"ParkingSensorIndication" : "停車感應指示 ",
	"ParkingSensorIndicator" : "停車感應指示燈",
	"RVMBuzzerVolume" : "Rear Vehicle Monitoring 音量",
	"Rare" : "較少",
	"Rare_Int_OFF" : "較少",
	"Reset" : "重設",
	"Rotation" : "旋轉",
	"RumbleStrips" : "低音",
	"RumbleStrips_line" : "低音 ",
	"RumbleVolume" : "停車震動",
	"SBSReset" : "確定要將 Smart Brake Support System 設定還原為其預設值？",
	"SBSResetError" : "無法將 Smart Brake Support 設定還原為出廠預設。 是否要重試？",
	"SBSResetProgress" : "正在還原 Smart Brake Support 設定",
	"SBSSCBS" : "SBS/SCBS",
	"SBS_SCBSReset" : "確定要將 SBS/SCBS 設定還原為其預設值？",
	"SBS_SCBSResetError" : "無法將 SBS/SCBS 設定還原為出廠預設。 是否要重試？",
	"SBS_SCBSResetProgress" : "正在還原 SBS/SCBS 設定",
	"SCBS" : "Smart City Brake Support",
	"SCBSReset" : "是否確定要將 SCBS 設定還原為出廠預設？ ",
	"SCBSResetError" : "無法將 SCBS 設定還原為出廠預設？ 是否要重試？",
	"SCBSResetProgress" : "正在還原 SCBS 設定 ",
	"SLC_Buzzer" : "僅蜂鳴器",
	"SLC_Off" : "關 ",
	"SLC_Sign" : "視覺",
	"SLC_Sign_Buzzer" : "音訊+視覺",
	"SLIReset" : "是否確定要將「速限警告」設定還原為預設值？ ",
	"SLIResetError" : "無法將「速限警告」設定還原為出廠預設。是否要重試？ ",
	"SLIResetProgress" : "還原「限速警告」設定",
	"SLI_HeadUpDisplay" : "Active Driving Display",
	"Safety" : "安全",
	"Safetysettings" : "安全設定",
	"Sensitivity" : "敏感度",
	"Sensitivity_Intervention_OFF" : "警告 ",
	"Setting" : "設定",
	"Settings" : "設定",
	"Short" : "近",
	"SideView" : "側方",
	"SideViewFrontView" : "側方+前方",
	"SmartBrakeSupport" : "Smart Brake Support",
	"Sound" : "聲音",
	"SpeedAlarm" : "車速警報",
	"SpeedLimitCaution" : "限速警示",
	"SpeedLimitInformation" : "限速警告",
	"SpeedLimitSign" : "限速顯示",
	"StepKilometers" : "{value} km/h",
	"StepMiles" : "{value} mph",
	"StreetInformation" : "街道資料",
	"Streetinfo_off" : "關",
	"System" : "系統",
	"TSRReset" : "是否確定要將 交通標誌識別系統 設定還原為預設值？",
	"TSRResetError" : "無法將 交通標誌識別系統設定 還原為出廠預設。是否要重試？",
	"TSRResetProgress" : "還原 交通標誌識別系統 設定",
	"TSR_Display" : "交通標誌顯示",
	"TSR_System" : "交通標誌識別系統",
	"Tachometer" : "轉速計",
	"ThreeFlashTurnSignal" : "三閃轉向訊號",
	"Timing" : "定時",
	"Turn" : "轉向訊號",
	"TurnProgress" : "正在還原轉向訊號設定",
	"TurnReset" : "確定要將轉向訊號設定還原為出廠預設？",
	"TurnResetError" : "無法將轉向訊號設定還原為出廠預設。 是否要重試？",
	"TurnSettings" : "轉向",
	"TurnSignalIndicatorVolume" : "轉向訊號音量",
	"UnlockMode" : "解鎖模式",
	"Vehicle" : "車輛",
	"VehicleSettings" : "車輛設定",
	"Vibration" : "震動",
	"VibrationStrength" : "震動強度",
	"Vibration_Line" : "震動",
	"ViewSwitchDisplay" : "預設檢視",
	"ViewSwitchFunction" : "影像切換功能",
	"Volume" : "警告音量",
	"WalkAwayLock" : "離開鎖定",
	"Warning" : "警告",
	"WarningDistance" : "警告距離",
	"_0s" : "0 秒",
	"_0seconds" : "0 秒",
	"_10m" : "10 分鐘",
	"_10minutes" : "10 分鐘",
	"_120s" : "120 秒",
	"_120seconds" : "120 秒",
	"_15s" : "15 秒",
	"_15seconds" : "15 秒",
	"_30m" : "30 分鐘",
	"_30minutes" : "30 分鐘",
	"_30s" : "30 秒",
	"_30seconds" : "30 秒",
	"_60m" : "60分鐘",
	"_60minutes" : "60 分鐘",
	"_60s" : "60 秒",
	"_60seconds" : "60 秒",
	"_7p5s" : "7.5 秒",
	"_7p5seconds" : "7.5 秒",
	"_90s" : "90 秒",
	"_90seconds" : "90 秒",
	"_AllDoors" : "全部車門",
	"_Driver'sDoor" : "駕駛者門",
	"on" : "打開",
};

framework.registerAppDictLoaded("vehsettings", "cn_HK");