var Localization_vehsettingsAppDict_ro_RO = {
	//"stringId" : "localString"
	"360ViewCamera" : "Monitor cu vedere la 360°",
	"AHBC" : "Adaptive LED Headlights",
	"Adaptive" : "Adaptiv",
	"AdaptiveFront-lightingSystem" : "Sistem de faruri adaptive",
	"AdaptiveLaneStreetTurn" : "Bandă/stradă/viraj adaptive",
	"AlarmTiming" : "Viteză",
	"AlertTiming" : "Interval alertă",
	"Always" : "Întotdeauna",
	"AtLine" : "Linie",
	"Auto" : "Auto",
	"AutoHeadlightOn" : "Aprindere automată faruri",
	"AutoWiper" : "Ştergător cu detector de ploaie",
	"BSMBuzzerVolume" : "Blind Spot Monitoring Volum",
	"BSMReset" : "Confirmaţi aducerea setărilor BSM la valorile iniţiale din fabrică?",
	"BSMResetError" : "Eroare la aducerea setărilor BSM la valorile din fabrică. Reîncercaţi?",
	"BSMResetProgress" : "Se restabilesc setările BSM",
	"BSMSystem" : "Sistem BSM (monitorizare a unghiului mort) ",
	"Beep" : "Bip",
	"BeepVolume" : "Volum semnal sonor",
	"Beep_Line" : "Bip",
	"BeforeLine" : "În.lin.",
	"Brightness" : "Luminozitate",
	"BrightnessControl" : "Controlul luminozităţii",
	"CHudNav_Maneuver" : "La manevră",
	"CHudNav_Off" : "Oprit",
	"CHudNav_TBT_Lane" : "Încadrare bandă & Pas cu pas",
	"CHudNav_TBT_Street" : "Nume stradă & Pas cu pas",
	"Calibration" : "Luminozitate",
	"CautionSpeed" : "Prag alertă",
	"CenterDisplay" : "Afişare pe centru",
	"ChangingLASSettings" : "Schim. setări Lane-keep Assist System",
	"Clock" : "Ceas",
	"Close" : "Închis",
	"ComingHomeLights" : "Coming Home Light",
	"ComingHomeLightsTimer" : "Coming Home Light",
	"DRSS" : "Distance Recognition Support System",
	"DRSSReset" : "Confirmaţi revenirea Distance Recognition Support System (DRSS) la valorile iniţiale?",
	"DRSSResetError" : "Eroare la modificarea Distance Recognition Support System (DRSS). Reîncercaţi?",
	"DRSSResetProgress" : "Schimbare Distance Recognition Support System (DRSS)",
	"Dark" : "Întunecat",
	"DaytimeRunningLights" : "Faruri de zi",
	"Devices" : "Dispoziti.",
	"Display" : "Afişaj",
	"DisplayInformation" : "Informaţii afişare",
	"DistanceRecognitionSupportSystem" : "Distance Recognition Support System",
	"DoorLock" : "Închidere portiere",
	"DoorLockMode" : "Mod închidere automată portiere",
	"DoorLockReset" : "Sigur doriţi să readuceţi Setările de închidere a uşilor la valorile iniţiale?",
	"DoorLockResetError" : "Eroare la modificarea Setărilor de închidere a uşilor. Doriţi să reîncercaţi?",
	"DoorLockResetProgress" : "Schimbare setări închidere uşi",
	"DoorRelockTime" : "Interval de reînchidere automată",
	"DriverAlert" : "Driver Attention Alert",
	"Early" : "Devreme",
	"ErrorBSMSettings" : "Eroare la modificarea setărilor BSM. Reîncercaţi?",
	"ErrorLASSettings" : "Eroare la modificarea Lane-keep Assist System. Reîncercaţi?",
	"FOWReset" : "Sigur doriţi să readuceţi Setările de Forward Obstruction Warning (FOW) la valorile iniţiale?",
	"FOWResetError" : "Eroare la modificarea Setărilor de Forward Obstruction Warning (FOW). Doriţi să reîncercaţi?",
	"FOWResetProgress" : "Schimbare setări Forward Obstruction Warning (FOW)",
	"Far" : "Dprte",
	"ForwardObstructionWarning" : "Forward Obstruction Warning",
	"FrontCameraView" : "Vedere frontală cameră",
	"GearShiftIndicator" : "Indicator de schimbare a vitezei",
	"GuidelineDisplay" : "Linii dinamice cale",
	"HUD" : "AD-Disp",
	"HUDDisplayInfoError" : "Imposibil de readus setările de afişare AD-Disp la valorile implicite. Doriţi să reîncercaţi?",
	"HUDDisplayInfoReset" : "Doriţi să readuceţi setările de afişare AD-Disp la valorile implicite?",
	"HUDDisplayInfoResetProgress" : "Se restabilesc setările de afişare AD-Disp",
	"HUDJ78AReset" : "Doriţi să readuceţi setările Active Driving Display la valorile implicite?",
	"HUDJ78AResetError" : "Eroare la resetarea Active Driving Display. Doriţi să reîncercaţi?",
	"HUDJ78AResetProgress" : "Se resetează Active Driving Display",
	"HUDJ78ATab" : "Active Driving Display",
	"HUDReset" : "Sigur doriţi să readuceţi Setările Active Driving Display la valorile iniţiale?",
	"HUDResetError" : "Eroare la modificarea Setărilor Active Driving Display. Doriţi să reîncercaţi?",
	"HUDResetProgress" : "Schimb. setări Active Driving Display",
	"HUDSettings" : "Setări AD-Disp",
	"HUD_HeadUpDisplay" : "Active Driving Display",
	"HeadUpDisplay" : "Active Driving Display",
	"HeadlightOffTimer" : "Temporizator stingere faruri",
	"HeadlightOnWarning" : "At. faruri aprinse",
	"HeadsUpDisplay" : "Active Driving Display",
	"Height" : "Înălţime",
	"High" : "Înalt",
	"HighBeamControl" : "High Beam Control",
	"High_SensitivityLAS" : "Înalt",
	"High_Vibration" : "Înalt",
	"ILB_Bright" : "Luminoasă",
	"ILB_Dark" : "Scăzută",
	"ILB_Medium" : "Medie",
	"ILB_Off" : "Oprit ",
	"IgONAutoDisplay" : "Afişare automată 360° View Monitor",
	"InterioLightsTimeOutDoorsClosed" : "Expirare lum. interioară – uşă înch.",
	"InterioLightsTimeOutDoorsOpen" : "Expirare lum. habitaclu – uşă desch.",
	"InteriorLightTimeoutDoorClosedTitle" : "Expirare lum. interioară – usi înch.",
	"InteriorLightTimeoutDoorOpenTitle" : "Expirare lum. interioară – usi desch.",
	"InteriorLightingBrightness" : "Lumină ambientală",
	"Intervention" : "Intervenţie",
	"InterventionTiming" : "Interval intervenţie",
	"KeylessLockBeepVol" : "Vol. bip sonor închid. fără cheie",
	"Kilometers" : "km/h",
	"LASAlert" : "Alertă LAS",
	"LASDefaultValues" : "Confirmaţi revenirea setărilor Lane-keep Assist System la valorile iniţiale?",
	"LASEarly" : "Devreme",
	"LASLate" : "Târziu",
	"LASSound" : "Tip alertă",
	"LASTiming" : "Temporizare LAS",
	"LDWSReset" : "Sigur doriţi să readuceţi Setările Lane Departure Warning System (LDWS) la valorile iniţiale?",
	"LDWSResetError" : "Eroare la modificarea Setărilor Sistemului de Lane Departure Warning System (LDWS). Doriţi să reîncercaţi?",
	"LDWSResetProgress" : "Schimbare setări Lane Departure Warning System (LDWS)",
	"LDWSTiming" : "Temporizare LDWS",
	"LaneDepartureAlert" : "Alertă părăsire bandă",
	"LaneDepartureWarningSystem" : "Lane Departure Warning System",
	"LaneKeepAssistSystem" : "Lane-keep Assist System",
	"Late" : "Târziu",
	"LeavingHomeLights" : "Leaving Home Light",
	"Light" : "Lumină",
	"LightOnReminderVolume" : "Lumină aprinsă vol.",
	"Lighting" : "Iluminare",
	"LightingReset" : "Sigur doriţi să readuceţi Setările de Iluminare la valorile iniţiale?",
	"LightingResetError" : "Eroare la modificarea Setărilor de Iluminare. Doriţi să reîncercaţi?",
	"LightingResetProgress" : "Schimbare setări iluminare",
	"LockShiftFromP" : "Blocare: decupl. poz. parcare ",
	"LockShiftFromPUnlockInPark" : "Blc.: decupl. poz. parc. Deblc: poz. parc.",
	"LockUnlock" : "Bloc.: în mers Debloc.: parc.",
	"LockWhenDriving" : "Blocare: în timpul conducerii",
	"LockWhenDrivingUnlockIGNoff" : "Blc. când conduc. Deblc.: IGN oprit",
	"Long" : "Dep.",
	"Low" : "Scăzut",
	"Low_SensitivityLAS" : "Scăzut",
	"Low_Vibration" : "Scăzut",
	"Manual" : "Man.",
	"Med" : "Mediu",
	"Medium" : "Mediu",
	"MediumDark" : "Întunecat mediu",
	"MediumLight" : "Deschis mediu",
	"Medium_Int_OFF" : "Mediu",
	"Medium_SensitivityLAS" : "Mediu",
	"Mid" : "Mediu",
	"Middle" : "Mediu",
	"Miles" : "mph",
	"Mode" : "Mod",
	"Navigation" : "Navigaţie",
	"NavigationSignal" : "Navigaţie  ",
	"Near" : "Aprpe",
	"Off" : "Oprit",
	"Often" : "Adesea",
	"Often_Int_OFF" : "Adesea",
	"OnDemand" : "La cer.",
	"OnceAllDoors" : "O dată: Toate portierele",
	"OnceDriversDoorTwiceAllDoors" : "O dată: a sof. De 2 ori: Toate usile",
	"Open" : "Desch.",
	"ParkingSensorIndication" : "Indicare senzor de parcare ",
	"ParkingSensorIndicator" : "Indicare senzor de parcare",
	"RVMBuzzerVolume" : "Rear Vehicle Monitoring Volum",
	"Rare" : "Rar",
	"Rare_Int_OFF" : "Rar",
	"Reset" : "Resetare",
	"Rotation" : "Rotire",
	"RumbleStrips" : "Ban.",
	"RumbleStrips_line" : "Ban. ",
	"RumbleVolume" : "Vol. rezon.",
	"SBSReset" : "Sigur doriţi să readuceţi Setările de Smart Brake Support (SBS) la valorile iniţiale?",
	"SBSResetError" : "Eroare la modificarea setărilor frânei Smart Brake Support (SBS). Reîncercaţi?",
	"SBSResetProgress" : "Schimbare setări Smart Brake Support (SBS)",
	"SBSSCBS" : "SBS/SCBS",
	"SBS_SCBSReset" : "Sigur doriţi să readuceţi Setările SBS/SCBS la valorile iniţiale?",
	"SBS_SCBSResetError" : "Eroare la modificarea Setărilor SBS/SCBS. Doriţi să reîncercaţi?",
	"SBS_SCBSResetProgress" : "Schimbare setări SBS/SCBS",
	"SCBS" : "Smart City Brake Support",
	"SCBSReset" : "Confirmaţi aducerea setărilor SCBS la valorile iniţiale din fabrică?",
	"SCBSResetError" : "Eroare la aducerea setărilor SCBS la valorile din fabrică. Reîncercaţi?",
	"SCBSResetProgress" : "Se restabilesc setările SCBS",
	"SLC_Buzzer" : "Doar semnal sonor",
	"SLC_Off" : "Oprit ",
	"SLC_Sign" : "Vizual",
	"SLC_Sign_Buzzer" : "Audio și vizual",
	"SLIReset" : "Doriţi să readuceţi setările atenţionării pentru limita de viteză la valorile implicite?",
	"SLIResetError" : "Imposibil de readus setările atenţionării pentru limita de viteză la valorile implicite. Doriţi să reîncercaţi?",
	"SLIResetProgress" : "Se restabilesc setările atenţionării pentru limita de viteză",
	"SLI_HeadUpDisplay" : "Active Driving Display",
	"Safety" : "Siguranţă",
	"Safetysettings" : "Setări siguranţă",
	"Sensitivity" : "Sensibilitate",
	"Sensitivity_Intervention_OFF" : "Avertisment ",
	"Setting" : "Setări",
	"Settings" : "Setări",
	"Short" : "Apr.",
	"SideView" : "Lateral",
	"SideViewFrontView" : "Lateral+frontal",
	"SmartBrakeSupport" : "Smart Brake Support",
	"Sound" : "Sunet",
	"SpeedAlarm" : "Viteză de alarmă",
	"SpeedLimitCaution" : "Alertă limită de viteză",
	"SpeedLimitInformation" : "Atenţionare limită de viteză",
	"SpeedLimitSign" : "Afişaj limită de viteză",
	"StepKilometers" : "{value} km/h",
	"StepMiles" : "{value} mph",
	"StreetInformation" : "Informaţii stradale",
	"Streetinfo_off" : "Oprit",
	"System" : "Sistem",
	"TSRReset" : "Doriţi să readuceţi setările sistemului de recunoaştere a indicatoarelor rutiere la valorile implicite?",
	"TSRResetError" : "Imposibil de readus setările sistemului de recunoaştere a indicatoarelor rutiere la valorile implicite. Doriţi să reîncercaţi?",
	"TSRResetProgress" : "Se restabilesc setările sistemului de recunoaştere a indicatoarelor rutiere",
	"TSR_Display" : "Afişare indicator rutier",
	"TSR_System" : "Sistem de recunoaştere a indicatoarelor rutiere",
	"Tachometer" : "Tahometru",
	"ThreeFlashTurnSignal" : "Semnalizare cu 3 flash-uri",
	"Timing" : "Temporizare",
	"Turn" : "Viraj",
	"TurnProgress" : "Schimbare setări virare",
	"TurnReset" : "Sigur doriţi să readuceţi Setările de virare la valorile iniţiale?",
	"TurnResetError" : "Eroare la modificarea Setărilor de Virare. Doriţi să reîncercaţi?",
	"TurnSettings" : "Viraj",
	"TurnSignalIndicatorVolume" : "Volum semnalizare",
	"UnlockMode" : "Mod deblocare",
	"Vehicle" : "Vehicul",
	"VehicleSettings" : "Setări vehicul",
	"Vibration" : "Vibraţie",
	"VibrationStrength" : "Intensitate vibraţie",
	"Vibration_Line" : "Vibraţie",
	"ViewSwitchDisplay" : "Vedere implicită",
	"ViewSwitchFunction" : "Vizualizare funcţie comutator",
	"Volume" : "Volum",
	"WalkAwayLock" : "Închidere prin distanţare",
	"Warning" : "Avertisment",
	"WarningDistance" : "Atentie distanta",
	"_0s" : "0 s",
	"_0seconds" : "0 secunde",
	"_10m" : "10 min",
	"_10minutes" : "10 minute",
	"_120s" : "120 s",
	"_120seconds" : "120 de secunde",
	"_15s" : "15 s",
	"_15seconds" : "15 secunde",
	"_30m" : "30 min",
	"_30minutes" : "30 de minute",
	"_30s" : "30 s",
	"_30seconds" : "30 de secunde",
	"_60m" : "60 min",
	"_60minutes" : "60 de minute",
	"_60s" : "60 s",
	"_60seconds" : "60 de secunde",
	"_7p5s" : "7.5 s",
	"_7p5seconds" : "7.5 secunde",
	"_90s" : "90 s",
	"_90seconds" : "90 de secunde",
	"_AllDoors" : "Toate",
	"_Driver'sDoor" : "Şofer",
	"on" : "Pornit",
};

framework.registerAppDictLoaded("vehsettings", "ro_RO");