var Localization_vehsettingsAppDict_ja_JP = {
	//"stringId" : "localString"
	"360ViewCamera" : "360°ビュー・モニター",
	"AHBC" : "アダプティブLEDヘッドライト",
	"Adaptive" : "自動",
	"AdaptiveFront-lightingSystem" : "AFS",
	"AdaptiveLaneStreetTurn" : "安全指示",
	"AlarmTiming" : "設定車速",
	"AlertTiming" : "警報タイミング",
	"Always" : "常時",
	"AtLine" : "行",
	"Auto" : "自動",
	"AutoHeadlightOn" : "オートライト点灯タイミング",
	"AutoWiper" : "オートワイパー",
	"BSMBuzzerVolume" : "BSM音量",
	"BSMReset" : "BSMの設定値をリセットしてもよろしいですか?",
	"BSMResetError" : "リセットできませんでした。リトライしますか?",
	"BSMResetProgress" : "処理中...",
	"BSMSystem" : "BSMシステム ",
	"Beep" : "ﾋﾞｰﾌﾟ",
	"BeepVolume" : "ビープ音量",
	"Beep_Line" : "ビープ音",
	"BeforeLine" : "ﾗｲﾝ前",
	"Brightness" : "明るさ",
	"BrightnessControl" : "明るさ調節",
	"CHudNav_Maneuver" : "安全指示",
	"CHudNav_Off" : "OFF",
	"CHudNav_TBT_Lane" : "レーン&ターンモード",
	"CHudNav_TBT_Street" : "道路名&ターンモード",
	"Calibration" : "明るさ",
	"CautionSpeed" : "警報しきい値",
	"CenterDisplay" : "センターディスプレイ",
	"ChangingLASSettings" : "処理中…",
	"Clock" : "時計",
	"Close" : "閉じる",
	"ComingHomeLights" : "カミングホームライト",
	"ComingHomeLightsTimer" : "カミングホームライト",
	"DRSS" : "車間認知支援システム",
	"DRSSReset" : "設定値をリセットしても\nよろしいですか？",
	"DRSSResetError" : "設定を変更できませんでした。\nリトライしますか？",
	"DRSSResetProgress" : "処理中…",
	"Dark" : "遅く",
	"DaytimeRunningLights" : "デイタイムランニングライト",
	"Devices" : "通信",
	"Display" : "画面",
	"DisplayInformation" : "表示情報",
	"DistanceRecognitionSupportSystem" : "車間認知支援システム",
	"DoorLock" : "ドアロック",
	"DoorLockMode" : "自動ドアロックモード",
	"DoorLockReset" : "設定値をリセットしても\nよろしいですか？",
	"DoorLockResetError" : "リセットできませんでした。\nリトライしますか？",
	"DoorLockResetProgress" : "処理中…",
	"DoorRelockTime" : "キーレス自動再ロック時間",
	"DriverAlert" : "ドライバーアテンションアラート",
	"Early" : "近い",
	"ErrorBSMSettings" : "設定変更中にエラーが発生しました。リトライしますか?",
	"ErrorLASSettings" : "リセットできませんでした。\nリトライしますか？",
	"FOWReset" : "設定値をリセットしても\nよろしいですか？",
	"FOWResetError" : "リセットできませんでした。\nリトライしますか？",
	"FOWResetProgress" : "処理中…",
	"Far" : "遠い",
	"ForwardObstructionWarning" : "Forward Obstruction Warning",
	"FrontCameraView" : "フロントビュー表示",
	"GearShiftIndicator" : "ギアシフトインジケータ",
	"GuidelineDisplay" : "予想進路線表示",
	"HUD" : "AD-Disp",
	"HUDDisplayInfoError" : "設定を変更できませんでした。\nリトライしますか？",
	"HUDDisplayInfoReset" : "設定値をリセットしてもよろしいですか？",
	"HUDDisplayInfoResetProgress" : "処理中…",
	"HUDJ78AReset" : "設定値をリセットしてもよろしいですか？",
	"HUDJ78AResetError" : "設定を変更できませんでした。\nリトライしますか？",
	"HUDJ78AResetProgress" : "処理中…",
	"HUDJ78ATab" : "表示",
	"HUDReset" : "設定値をリセットしても\nよろしいですか？",
	"HUDResetError" : "リセットできませんでした。\nリトライしますか？",
	"HUDResetProgress" : "処理中…",
	"HUDSettings" : "AD-Disp Setting",
	"HUD_HeadUpDisplay" : "表示",
	"HeadUpDisplay" : "表示",
	"HeadlightOffTimer" : "ヘッドライト自動消灯時間",
	"HeadlightOnWarning" : "ﾍｯﾄﾞﾗｲﾄON警告",
	"HeadsUpDisplay" : "表示",
	"Height" : "高さ",
	"High" : "大",
	"HighBeamControl" : "ハイビームコントロールシステム",
	"High_SensitivityLAS" : "低い",
	"High_Vibration" : "強",
	"ILB_Bright" : "明るい",
	"ILB_Dark" : "暗い",
	"ILB_Medium" : "中間",
	"ILB_Off" : "OFF ",
	"ILB_OffShrt" : "OFF",
	"IgONAutoDisplay" : "エンジン始動後の自動表示",
	"InterioLightsTimeOutDoorsClosed" : "ドアクローズ照明点灯時間",
	"InterioLightsTimeOutDoorsOpen" : "ドアオープン照明点灯時間",
	"InteriorLightTimeoutDoorClosedTitle" : "ドア開連動照明点灯時間",
	"InteriorLightTimeoutDoorOpenTitle" : "ドア閉連動照明点灯時間",
	"InteriorLightingBrightness" : "間接照明",
	"Intervention" : "ハンドルアシスト",
	"InterventionTiming" : "アシストタイミング",
	"KeylessLockBeepVol" : "キーレスアンサーバック音量",
	"Kilometers" : "km/h",
	"LASAlert" : "LAS 警告",
	"LASDefaultValues" : "設定値をリセットしても\nよろしいですか？",
	"LASEarly" : "早い",
	"LASLate" : "遅い",
	"LASSound" : "警報種類",
	"LASTiming" : "LAS距離",
	"LDWSReset" : "設定値をリセットしても\nよろしいですか？",
	"LDWSResetError" : "リセットできませんでした。\nリトライしますか？",
	"LDWSResetProgress" : "処理中…",
	"LDWSTiming" : "警報距離",
	"LaneDepartureAlert" : "警報(音/振動)",
	"LaneDepartureWarningSystem" : "車線逸脱警報システム",
	"LaneKeepAssistSystem" : "レーンキープ・アシスト・システム",
	"Late" : "遠い",
	"LeavingHomeLights" : "リービングホームライト",
	"Light" : "早く",
	"LightOnReminderVolume" : "ライトON警報",
	"Lighting" : "照明",
	"LightingReset" : "設定値をリセットしても\nよろしいですか？",
	"LightingResetError" : "リセットできませんでした。\nリトライしますか？",
	"LightingResetProgress" : "処理中…",
	"LockShiftFromP" : "ﾛｯｸ : ｼﾌﾄ連動 ",
	"LockShiftFromPUnlockInPark" : "ﾛｯｸ / ｱﾝﾛｯｸ : ｼﾌﾄ連動",
	"LockUnlock" : "ﾛｯｸ : 車速、ｱﾝﾛｯｸ : ｼﾌﾄ連動",
	"LockWhenDriving" : "ﾛｯｸ : 車速連動",
	"LockWhenDrivingUnlockIGNoff" : "ﾛｯｸ : 車速、ｱﾝﾛｯｸ : 電源",
	"Long" : "遠い",
	"Low" : "小",
	"Low_SensitivityLAS" : "高い",
	"Low_Vibration" : "弱",
	"Manual" : "手動",
	"Med" : "標準",
	"Medium" : "標準",
	"MediumDark" : "少し遅く",
	"MediumLight" : "少し早く",
	"Medium_Int_OFF" : "標準",
	"Medium_SensitivityLAS" : "標準",
	"Mid" : "中",
	"Middle" : "中間",
	"Miles" : "mph",
	"Mode" : "設定",
	"Navigation" : "ナビガイダンス",
	"NavigationSignal" : "ナビガイダンス  ",
	"Near" : "近い",
	"Off" : "OFF",
	"Often" : "高い",
	"Often_Int_OFF" : "高い",
	"OnDemand" : " ストリート変更時",
	"OnceAllDoors" : "1回 : すべてのドア",
	"OnceDriversDoorTwiceAllDoors" : "1回 : 運転席、2回 : すべて",
	"Open" : "開く",
	"ParkingSensorIndication" : "パーキングセンサー表示 ",
	"ParkingSensorIndicator" : "パーキングセンサーインジケーター",
	"RVMBuzzerVolume" : "リアビークルモニタリング音量",
	"Rare" : "低い",
	"Rare_Int_OFF" : "低い",
	"Reset" : "リセット",
	"Rotation" : "傾き調整",
	"RumbleStrips" : "ﾗﾝﾌﾞﾙ",
	"RumbleStrips_line" : "ランブル音 ",
	"RumbleVolume" : "ランブル音量",
	"SBSReset" : "設定値をリセットしても\nよろしいですか？",
	"SBSResetError" : "リセットできませんでした。\nリトライしますか？",
	"SBSResetProgress" : "処理中…",
	"SBSSCBS" : "SBS/SCBS",
	"SBS_SCBSReset" : "設定値をリセットしても\nよろしいですか？",
	"SBS_SCBSResetError" : "リセットできませんでした。\nリトライしますか？",
	"SBS_SCBSResetProgress" : "処理中…",
	"SCBS" : "スマートシティーブレーキサポート",
	"SCBSReset" : "SCBSの設定値をリセットしてもよろしいですか?",
	"SCBSResetError" : "リセットできませんでした。\nリトライしますか?",
	"SCBSResetProgress" : "処理中…",
	"SLC_Buzzer" : "ブザーのみ",
	"SLC_Off" : "OFF ",
	"SLC_OffShrt" : "OFF",
	"SLC_Sign" : "表示のみ",
	"SLC_Sign_Buzzer" : "表示+ブザー",
	"SLIReset" : "設定値をリセットしてもよろしいですか？",
	"SLIResetError" : "リセットできませんでした。リトライしますか?",
	"SLIResetProgress" : "処理中…",
	"SLI_HeadUpDisplay" : "表示",
	"Safety" : "安全装備",
	"Safetysettings" : "Settings",
	"Sensitivity" : "アシスト感度",
	"Sensitivity_Intervention_OFF" : "警報感度 ",
	"Setting" : "設定",
	"Settings" : "Settings",
	"Short" : "近い",
	"SideView" : "サイドビュー",
	"SideViewFrontView" : "サイドビュー + フロントビュー",
	"SmartBrakeSupport" : "スマートブレーキサポート",
	"Sound" : "サウンド",
	"SpeedAlarm" : "スピードアラーム",
	"SpeedLimitCaution" : "スピードリミッター警報",
	"SpeedLimitInformation" : "スピードリミッター警報感度",
	"SpeedLimitSign" : "スピードリミッター表示",
	"StepKilometers" : "{value} km/h",
	"StepMiles" : "{value} mph",
	"StreetInformation" : "道路/交差点名称",
	"Streetinfo_off" : "OFF",
	"System" : "システム",
	"TSRReset" : "設定値をリセットしてもよろしいですか？",
	"TSRResetError" : "リセットできませんでした。リトライしますか?",
	"TSRResetProgress" : "処理中…",
	"TSR_Display" : "交通標識表示",
	"TSR_System" : "交通標識認識システム",
	"Tachometer" : "タコメータ",
	"ThreeFlashTurnSignal" : "スリーフラッシュターンシグナル",
	"Timing" : "警報距離",
	"Turn" : "ターン",
	"TurnProgress" : "処理中…",
	"TurnReset" : "設定値をリセットしても\nよろしいですか？",
	"TurnResetError" : "変更できませんでした。\nリトライしますか？",
	"TurnSettings" : "ターン",
	"TurnSignalIndicatorVolume" : "ウィンカー音量",
	"UnlockMode" : "キーレスアンロックモード",
	"Vehicle" : "車両装備",
	"VehicleSettings" : "Settings",
	"Vibration" : "ﾊﾝﾄﾞﾙ",
	"VibrationStrength" : "ハンドル振動",
	"Vibration_Line" : "ハンドル振動",
	"ViewSwitchDisplay" : "Viewスイッチ機能",
	"ViewSwitchFunction" : "ビュースイッチ機能",
	"Volume" : "音量",
	"WalkAwayLock" : "キーレスオートロック",
	"Warning" : "警報感度",
	"WarningDistance" : "警告距離",
	"_0s" : "0 秒",
	"_0seconds" : "0 秒",
	"_10m" : "10分",
	"_10minutes" : "10 分",
	"_120s" : "120秒",
	"_120seconds" : "120 秒",
	"_15s" : "15秒",
	"_15seconds" : "15 秒",
	"_30m" : "30分",
	"_30minutes" : "30 分",
	"_30s" : "30秒",
	"_30seconds" : "30 秒",
	"_60m" : "60分",
	"_60minutes" : "60 分",
	"_60s" : "60秒",
	"_60seconds" : "60 秒",
	"_7p5s" : "7.5秒",
	"_7p5seconds" : "7.5 秒",
	"_90s" : "90秒",
	"_90seconds" : "90 秒",
	"_AllDoors" : "全席",
	"_Driver'sDoor" : "運転席",
	"on" : "On",
};

framework.registerAppDictLoaded("vehsettings", "ja_JP");