var Localization_vehsettingsAppDict_ar_SA = {
	//"stringId" : "localString"
	"360ViewCamera" : "شاشة عرض 360 درجة",
	"AHBC" : "Adaptive LED Headlights",
	"Adaptive" : "مهايئ",
	"AdaptiveFront-lightingSystem" : "نظام الإضاءة الأمامية المهايئ",
	"AdaptiveLaneStreetTurn" : "الحارة/الشارع/الدوران التكيفي",
	"AlarmTiming" : "السرعة",
	"AlertTiming" : "توقيت التنبيه",
	"Always" : "دائمًا",
	"AtLine" : "بالخط",
	"Auto" : "آلي",
	"AutoHeadlightOn" : "التشغيل الآلي للمصباح الأمامي",
	"AutoWiper" : "ماسحة استشعار المطر",
	"BSMBuzzerVolume" : "الصوت Blind Spot Monitoring",
	"BSMReset" : "هل تريد حقًا إعادة إعدادات BSM إلى إعدادات المصنع الافتراضية؟",
	"BSMResetError" : "يتعذر إعادة إعدادات BSM إلى إعدادات المصنع الافتراضية. هل ترغب في إعادة المحاولة؟",
	"BSMResetProgress" : "تتم الآن إعادة إعدادات BSM",
	"BSMSystem" : "نظام Blind Spot Monitoring ",
	"Beep" : "منبه",
	"BeepVolume" : "مستوى صوت الصافرة",
	"Beep_Line" : "منبه",
	"BeforeLine" : "ق.خط",
	"Brightness" : "السطوع",
	"BrightnessControl" : "تحكم في درجة السطوع",
	"CHudNav_Maneuver" : "المناورة",
	"CHudNav_Off" : "إيقاف تشغيل",
	"CHudNav_TBT_Lane" : "حارة لفة",
	"CHudNav_TBT_Street" : "شارع لفة",
	"Calibration" : "السطوع",
	"CautionSpeed" : "حد التنبيه",
	"CenterDisplay" : "شاشة عرض مركزية",
	"ChangingLASSettings" : "تغيير إعدادات نظام  LAS",
	"Clock" : "الساعة",
	"Close" : "إغلاق",
	"ComingHomeLights" : "Coming Home Light",
	"ComingHomeLightsTimer" : "Coming Home Light",
	"DRSS" : "Distance Recognition Support System",
	"DRSSReset" : "هل أنت متأكد من رغبتك في إعادة إعدادات Distance Recognition Support System إلى قيمها الافتراضية؟",
	"DRSSResetError" : "حدث خطأ في تغيير  Distance Recognition Support System. هل ترغب في إعادة المحاولة؟",
	"DRSSResetProgress" : "تغيير Distance Recognition Support System",
	"Dark" : "إعتام",
	"DaytimeRunningLights" : "تشغيل أضواء النهار",
	"Devices" : "الأجهزة",
	"Display" : "عرض",
	"DisplayInformation" : "عرض المعلومات",
	"DistanceRecognitionSupportSystem" : "Distance Recognition Support System",
	"DoorLock" : "قفل الباب",
	"DoorLockMode" : "وضع قفل الباب تلقائيًا",
	"DoorLockReset" : "هل أنت متأكد من رغبتك في إعادة إعدادات قفل الباب إلى القيم الافتراضية؟",
	"DoorLockResetError" : "حدث خطأ أثناء تغيير إعدادات قفل الباب. هل ترغب في إعادة المحاولة؟",
	"DoorLockResetProgress" : "تغيير إعدادات قفل الباب",
	"DoorRelockTime" : "زمن إعادة الإقفال تلقائيًا",
	"DriverAlert" : "Driver Attention Alert",
	"Early" : "مبكر",
	"ErrorBSMSettings" : "خطأ في تغيير إعدادات BSM؟ هل ترغب في إعادة المحاولة؟",
	"ErrorLASSettings" : "حدث خطأ أثناء تغيير نظام  Lane-keep Assist System. هل ترغب في إعادة المحاولة؟",
	"FOWReset" : "هل أنت متأكد من رغبتك في إعادة إعدادات Forward Obstruction Warning إلى القيم الافتراضية؟",
	"FOWResetError" : "حدث خطأ أثناء تغيير إعدادات Forward Obstruction Warning. هل ترغب في إعادة المحاولة؟",
	"FOWResetProgress" : "تغيير إعدادات Forward Obstruction Warning",
	"Far" : "بعيد",
	"ForwardObstructionWarning" : "Forward Obstruction Warning",
	"FrontCameraView" : "عرض الكاميرا الأمامية",
	"GearShiftIndicator" : "مؤشر نقل الحركة",
	"GuidelineDisplay" : "خطوط مسار ديناميكية",
	"HUD" : "AD-Disp",
	"HUDDisplayInfoError" : "لا يمكن استعادة إعدادات معلومات شاشة AD-Disp إلى القيم الافتراضية للمصنع. هل ترغب في إعادة المحاولة؟",
	"HUDDisplayInfoReset" : "هل أنت متأكد من رغبتك في استعادة إعدادات معلومات شاشة AD-Disp إلى قيمها الافتراضية؟",
	"HUDDisplayInfoResetProgress" : "استعادة إعدادات معلومات شاشة AD-Disp",
	"HUDJ78AReset" : "هل أنت متأكد أنك ترغب في استعادة إعدادات شاشة العرض الرأسية الشفافة (Active Driving Display) إلى قيمها الافتراضية؟",
	"HUDJ78AResetError" : "حدث خطأ أثناء إعادة تعيين إعدادات شاشة العرض الرأسية الشفافة (Active Driving Display). هل ترغب في إعادة المحاولة؟",
	"HUDJ78AResetProgress" : "إعادة تعيين إعدادات شاشة العرض الرأسية الشفافة (Active Driving Display)",
	"HUDJ78ATab" : "Active Driving Display",
	"HUDReset" : "هل أنت متأكد من رغبتك في إعادة إعدادات Active Driving Display إلى قيمها الافتراضية؟",
	"HUDResetError" : "حدث خطأ أثناء تغيير إعدادات Active Driving Display. هل ترغب في إعادة المحاولة؟",
	"HUDResetProgress" : "تغيير إعداد Active Driving Display",
	"HUDSettings" : "إعدادات شاشة العرض الرأسية الشفافة (AD-Disp)",
	"HUD_HeadUpDisplay" : "Active Driving Display",
	"HeadUpDisplay" : "Active Driving Display",
	"HeadlightOffTimer" : "موقت إيقاف المصباح الأمامي",
	"HeadlightOnWarning" : "تنبيه تفعيل الإضاءة الأمامية",
	"HeadsUpDisplay" : "Active Driving Display",
	"Height" : "الارتفاع",
	"High" : "مرتفع",
	"HighBeamControl" : "High Beam Control",
	"High_SensitivityLAS" : "مرتفع",
	"High_Vibration" : "مرتفع",
	"ILB_Bright" : "لامع",
	"ILB_Dark" : "معتم",
	"ILB_Medium" : "متوسط",
	"ILB_Off" : "إيقاف تشغيل ",
	"IgONAutoDisplay" : "شاشة العرض التلقائي بزاوية 360 درجة",
	"InterioLightsTimeOutDoorsClosed" : "مدة إضاءة الداخل - الباب مغلق",
	"InterioLightsTimeOutDoorsOpen" : "مدة إضاءة الداخل - الباب مفتوح",
	"InteriorLightTimeoutDoorClosedTitle" : "مدة إضاءة الداخل - الباب مغلق",
	"InteriorLightTimeoutDoorOpenTitle" : "مدة إضاءة الداخل - الباب مفتوح",
	"InteriorLightingBrightness" : "الإضاءة المحيطة",
	"Intervention" : "التدخل",
	"InterventionTiming" : "توقيت التدخل",
	"KeylessLockBeepVol" : "جهارة صافرة الإغلاق دون مفتاح",
	"Kilometers" : "كم/س",
	"LASAlert" : "تنبيه LAS",
	"LASDefaultValues" : "هل أنت متأكد من رغبتك في إعادة إعدادات نظام Lane-keep Assist System إلى قيمها الافتراضية؟",
	"LASEarly" : "مبكر",
	"LASLate" : "متأخر",
	"LASSound" : "نوع التنبيه",
	"LASTiming" : "توقيت LAS",
	"LDWSReset" : "هل أنت متأكد من رغبتك في إعادة إعدادات Lane Departure Warning System إلى القيم الافتراضية؟",
	"LDWSResetError" : "حدث خطأ أثناء تغيير إعدادات Lane Departure Warning System. هل ترغب في إعادة المحاولة؟",
	"LDWSResetProgress" : "تغيير إعدادات Lane Departure Warning System",
	"LDWSTiming" : "توقيت نظام LDWS",
	"LaneDepartureAlert" : "التنبيه عند الخروج من المسار",
	"LaneDepartureWarningSystem" : "Lane Departure Warning System",
	"LaneKeepAssistSystem" : "Lane-keep Assist System",
	"Late" : "متأخر",
	"LeavingHomeLights" : "Leaving Home Light",
	"Light" : "إضاءة",
	"LightOnReminderVolume" : "جهارة منبه الإضاءة",
	"Lighting" : "الإضاءة",
	"LightingReset" : "هل أنت متأكد من رغبتك في إعادة إعدادات الإضاءة إلى القيم الافتراضية؟",
	"LightingResetError" : "حدث خطأ أثناء تغيير إعدادات الإضاءة. هل ترغب في إعادة المحاولة؟",
	"LightingResetProgress" : "تغيير إعدادات الإضاءة",
	"LockShiftFromP" : "قفل: انتقال من وضع الوقوف التام ",
	"LockShiftFromPUnlockInPark" : "قفل:انتقال من وقوف إلغاء ق.:وقوف",
	"LockUnlock" : "القفل: القيادة الفتح: عند الوقوف",
	"LockWhenDriving" : "قفل: عند القيادة",
	"LockWhenDrivingUnlockIGNoff" : "قفل:قيادة إلغاء قفل:إيقاف تشغيل",
	"Long" : "بعيد",
	"Low" : "منخفض",
	"Low_SensitivityLAS" : "منخفض",
	"Low_Vibration" : "منخفض",
	"Manual" : "يدوي",
	"Med" : "متوسط",
	"Medium" : "متوسط",
	"MediumDark" : "إعتام م.",
	"MediumLight" : "إضاءة م.",
	"Medium_Int_OFF" : "متوسط",
	"Medium_SensitivityLAS" : "متوسط",
	"Mid" : "منتصف",
	"Middle" : "وسط",
	"Miles" : "ميل/ساعة",
	"Mode" : "الوضع",
	"Navigation" : "التنقل",
	"NavigationSignal" : "الملاحة  ",
	"Near" : "قريب",
	"Off" : "إيقاف",
	"Often" : "غالبًا",
	"Often_Int_OFF" : "غالبًا",
	"OnDemand" : "عند الطلب",
	"OnceAllDoors" : "مرة: جميع الأبواب",
	"OnceDriversDoorTwiceAllDoors" : "مرة: للسائق مرتين: جميع الأبواب",
	"Open" : "فتح",
	"ParkingSensorIndication" : "مؤشر مستشعر الوقوف ",
	"ParkingSensorIndicator" : "مؤشر مستشعر الركن",
	"RVMBuzzerVolume" : "الصوت Rear Vehicle Monitoring",
	"Rare" : "نادرًا",
	"Rare_Int_OFF" : "نادرًا",
	"Reset" : "إعادة ضبط",
	"Rotation" : "تدوير",
	"RumbleStrips" : "خ.إ",
	"RumbleStrips_line" : "خ.إ ",
	"RumbleVolume" : "مستوى صوت الدوي",
	"SBSReset" : "هل أنت متأكد من رغبتك في إعادة إعدادات Smart Brake Support إلى إعدادات المصنع الافتراضية؟",
	"SBSResetError" : "حدث خطأ أثناء تغيير إعدادات Smart Brake Support. هل ترغب في إعادة المحاولة؟",
	"SBSResetProgress" : "تغيير إعدادات Smart Brake Support",
	"SBSSCBS" : "SBS/SCBS",
	"SBS_SCBSReset" : "هل أنت متأكد من رغبتك في إعادة إعدادات SBS/SCBS إلى القيم الافتراضية؟",
	"SBS_SCBSResetError" : "حدث خطأ أثناء تغيير إعدادات SBS/SCBS. هل ترغب في إعادة المحاولة؟",
	"SBS_SCBSResetProgress" : "تغيير إعدادات نظام SBS/SCBS",
	"SCBS" : "Smart City Brake Support",
	"SCBSReset" : "هل تريد حقًا إعادة إعدادات SCBS إلى إعدادات المصنع الافتراضية؟\"",
	"SCBSResetError" : "يتعذر إعادة إعدادات SCBS إلى إعدادات المصنع الافتراضية. هل ترغب في إعادة المحاولة؟\"",
	"SCBSResetProgress" : "تتم الآن إعادة إعدادات SCBS",
	"SLC_Buzzer" : "جرس طنان فقط",
	"SLC_Off" : "إيقاف تشغيل ",
	"SLC_Sign" : "مرئي",
	"SLC_Sign_Buzzer" : "الصوت والصورة",
	"SLIReset" : "هل تريد حقًا إعادة إعدادات تحذير حد السرعة إلى قيمها الافتراضية؟",
	"SLIResetError" : "تتعذر إعادة إعدادات تحذير حد السرعة إلى قيم المصنع الافتراضية. هل ترغب في إعادة المحاولة؟",
	"SLIResetProgress" : "تتم الآن إعادة إعدادات تحذير حد السرعة",
	"SLI_HeadUpDisplay" : "Active Driving Display",
	"Safety" : "السلامة",
	"Safetysettings" : "إعدادات السلامة",
	"Sensitivity" : "الحساسية",
	"Sensitivity_Intervention_OFF" : "تحذير ",
	"Setting" : "إعدادات",
	"Settings" : "الإعدادات",
	"Short" : "قريب",
	"SideView" : "جانبي",
	"SideViewFrontView" : "جانبي + أمامي",
	"SmartBrakeSupport" : "Smart Brake Support",
	"Sound" : "الصوت",
	"SpeedAlarm" : "تنبيه السرعة",
	"SpeedLimitCaution" : "تنبيه حد السرعة",
	"SpeedLimitInformation" : "تحذير حد السرعة",
	"SpeedLimitSign" : "عرض حد السرعة",
	"StepKilometers" : "{value} كم/س",
	"StepMiles" : "{value} ميل/ساعة",
	"StreetInformation" : "معلومات الشارع",
	"Streetinfo_off" : "إيقاف تشغيل",
	"System" : "النظام",
	"TSRReset" : "هل تريد حقًا إعادة إعدادات  نظام التعرف على إشارات المرور  إلى قيمها الافتراضية؟",
	"TSRResetError" : "تتعذر إعادة إعدادات  نظام التعرف على إشارات المرور  إلى قيم المصنع الافتراضية. هل ترغب في إعادة المحاولة؟",
	"TSRResetProgress" : "تتم الآن إعادة إعدادات  نظام التعرف على إشارات المرور  ",
	"TSR_Display" : "عرض إشارات المرور",
	"TSR_System" : "نظام التعرف على إشارات المرور",
	"Tachometer" : "جهاز قياس السرعة",
	"ThreeFlashTurnSignal" : "إشارة التبادل الضوئية الثلاثية",
	"Timing" : "التوقيت",
	"Turn" : "تـحـويل الإشارة",
	"TurnProgress" : "تغيير إعدادات التحويل",
	"TurnReset" : "هل أنت متأكد من رغبتك في إعادة إعدادات التحويل إلى القيم الافتراضية؟",
	"TurnResetError" : "حدث خطأ أثناء تغيير إعدادات التحويل. هل ترغب في إعادة المحاولة؟",
	"TurnSettings" : "تـحـويل الإشارة",
	"TurnSignalIndicatorVolume" : "تبديل جهارة الإشارة",
	"UnlockMode" : "وضع إلغاء القفل",
	"Vehicle" : "المركبة",
	"VehicleSettings" : "إعدادات المركبة",
	"Vibration" : "اهتزاز",
	"VibrationStrength" : "قوة الاهتزاز",
	"Vibration_Line" : "اهتزاز",
	"ViewSwitchDisplay" : "العرض الافتراضي",
	"ViewSwitchFunction" : "عرض وظيفة التبديل",
	"Volume" : "مستوى الصوت",
	"WalkAwayLock" : "القفل عن بعد",
	"Warning" : "تحذير",
	"WarningDistance" : "مسافة التحذير",
	"_0s" : "0 ثانية",
	"_0seconds" : "0 ثانية",
	"_10m" : "10 دقائق",
	"_10minutes" : "10 دقائق",
	"_120s" : "120 ثانية",
	"_120seconds" : "120 ثانية",
	"_15s" : "15 ثانية",
	"_15seconds" : "15 ثانية",
	"_30m" : "30 دقيقة",
	"_30minutes" : "30 دقيقة",
	"_30s" : "30 ثانية",
	"_30seconds" : "30 ثانية",
	"_60m" : "60 دقيقة",
	"_60minutes" : "60 دقيقة",
	"_60s" : "60 ثانية",
	"_60seconds" : "60 ثانية",
	"_7p5s" : "7.5 ثانية",
	"_7p5seconds" : "7.5 ثانية",
	"_90s" : "90 ثانية",
	"_90seconds" : "90 ثانية",
	"_AllDoors" : "الكل",
	"_Driver'sDoor" : "السائق",
	"on" : "مفعل",
};

framework.registerAppDictLoaded("vehsettings", "ar_SA");