var Localization_vehsettingsAppDict_el_GR = {
	//"stringId" : "localString"
	"360ViewCamera" : "Κάμερα 360°",
	"AHBC" : "Adaptive LED Headlights",
	"Adaptive" : "Προσαρ.",
	"AdaptiveFront-lightingSystem" : "Προσαρμ.μπροστ.συστήμ.φωτισμού",
	"AdaptiveLaneStreetTurn" : "Προσαρμογή Λωρίδας/Οδού/Στροφής",
	"AlarmTiming" : "Ταχύτητας",
	"AlertTiming" : "Χρόνος ειδοποίησης",
	"Always" : "Πάντα",
	"AtLine" : "Γραμ.",
	"Auto" : "Αυτόμ.",
	"AutoHeadlightOn" : "Αυτ. ενεργ. κεντρικού προβολέα",
	"AutoWiper" : "Υαλοκαθαριστήρες με αισθητήρα βροχής",
	"BSMBuzzerVolume" : "Blind Spot Monitoring Ένταση",
	"BSMReset" : "Θέλετε σίγουρα να επαναφέρετε τις ρυθμίσεις του BSM στις εργοστασιακές τιμές;",
	"BSMResetError" : "Σφάλμα επαναφοράς ρυθμίσεων BSM στις εργοστασιακές τιμές. Θέλετε να προσπαθήσετε ξανά;",
	"BSMResetProgress" : "Γίνεται επαναφορά των ρυθμίσεων του BSM",
	"BSMSystem" : "Σύστημα παρακολούθησης νεκρού σημείου (BSM) ",
	"Beep" : "Μπιπ",
	"BeepVolume" : "Ένταση μπιπ",
	"Beep_Line" : "Μπιπ",
	"BeforeLine" : "Πρ. Γ",
	"Brightness" : "Φωτεινότητα",
	"BrightnessControl" : "Έλεγχος φωτεινότητας",
	"CHudNav_Maneuver" : "Σε ελιγμό",
	"CHudNav_Off" : "Απενερ.",
	"CHudNav_TBT_Lane" : "ΛωρίδΣτρ",
	"CHudNav_TBT_Street" : "ΟδόςΣτρφ",
	"Calibration" : "Φωτεινότητα",
	"CautionSpeed" : "Όριο ειδοποίησης",
	"CenterDisplay" : "Κεντρική οθόνη",
	"ChangingLASSettings" : "Αλλαγή ρυθμίσεων του LAS",
	"Clock" : "Ρολόι",
	"Close" : "Κλείσ.",
	"ComingHomeLights" : "Coming Home Light",
	"ComingHomeLightsTimer" : "Coming Home Light",
	"DRSS" : "Distance Recognition Support System",
	"DRSSReset" : "Θέλετε σίγουρα να επαναφέρετε τις ρυθμίσεις Distance Recognition Support System στις προεπιλεγμένες τιμές τους;",
	"DRSSResetError" : "Σφάλμα αλλαγής Distance Recognition Support System. Θέλετε να ξαναδοκιμάσετε;",
	"DRSSResetProgress" : "Αλλαγή Distance Recognition Support System",
	"Dark" : "Σκούρο",
	"DaytimeRunningLights" : "Φώτα λειτουργίας ημέρας",
	"Devices" : "Συσκευέ",
	"Display" : "Οθόνη",
	"DisplayInformation" : "Προβολή πληροφοριών",
	"DistanceRecognitionSupportSystem" : "Distance Recognition Support System",
	"DoorLock" : "Ασφάλεια πόρτας",
	"DoorLockMode" : "Τρόπος αυτ. ασφάλισης πόρτας",
	"DoorLockReset" : "Θέλετε σίγουρα να επαναφέρετε τις ρυθμίσεις ασφάλισης πόρτας στις προεπιλεγμένες τιμές τους;",
	"DoorLockResetError" : "Σφάλμα αλλαγής ρυθμίσεων ασφάλισης πόρτας. Θέλετε να ξαναδοκιμάσετε;",
	"DoorLockResetProgress" : "Αλλαγή ρυθμίσεων ασφάλισης πόρτας",
	"DoorRelockTime" : "Χρόνος αυτ. επανασφάλισης",
	"DriverAlert" : "Driver Attention Alert",
	"Early" : "Νωρίς",
	"ErrorBSMSettings" : "Σφάλμα στην αλλαγή των ρυθμίσεων του BSM. Θέλετε να προσπαθήσετε ξανά;",
	"ErrorLASSettings" : "Σφάλμα αλλαγής Lane-keep Assist System. Θέλετε να ξαναπροσπαθήσετε;",
	"FOWReset" : "Θέλετε σίγουρα να επαναφέρετε τις ρυθμίσεις Forward Obstruction Warning στις προεπιλεγμένες τιμές τους;",
	"FOWResetError" : "Σφάλμα αλλαγής ρυθμίσεων Forward Obstruction Warning. Θέλετε να ξαναδοκιμάσετε;",
	"FOWResetProgress" : "Αλλαγή ρυθμίσεων Forward Obstruction Warning",
	"Far" : "Μακρ",
	"ForwardObstructionWarning" : "Forward Obstruction Warning",
	"FrontCameraView" : "Εικόν. μπροστ. κάμερας",
	"GearShiftIndicator" : "Ένδειξη αλλαγής ταχύτητας",
	"GuidelineDisplay" : "Πρόβλ. διαδρομής οχήμ.",
	"HUD" : "AD-Disp",
	"HUDDisplayInfoError" : "Προέκυψε σφάλμα κατά την επαναφορά των Ρυθμίσεων των πληροφοριών της AD-Disp. Θέλετε να ξαναδοκιμάσετε;",
	"HUDDisplayInfoReset" : "Είστε βέβαιος ότι θέλετε να επαναφέρετε τις ρυθμίσεις των πληροφοριών της AD-Disp στις προεπιλεγμένες τιμές;",
	"HUDDisplayInfoResetProgress" : "Επαναφορά ρυθμίσεων πληροφ. της AD-Disp",
	"HUDJ78AReset" : "Είστε βέβαιος ότι θέλετε να επαναφέρετε τις ρυθμίσεις της Active Driving Display στις προεπιλεγμένες τιμές;",
	"HUDJ78AResetError" : "Προέκυψε σφάλμα κατά την επαναφορά των Ρυθμίσεων της Active Driving Display. Θέλετε να ξαναδοκιμάσετε;",
	"HUDJ78AResetProgress" : "Επαναφορά ρυθμίσεων της Active Driving Display",
	"HUDJ78ATab" : "Active Driving Display",
	"HUDReset" : "Θέλετε σίγουρα να επαναφέρετε τις ρυθμίσεις Active Driving Display στις προεπιλεγμένες τιμές τους;",
	"HUDResetError" : "Σφάλμα αλλαγής ρυθμίσεων Active Driving Display. Θέλετε να ξαναδοκιμάσετε;",
	"HUDResetProgress" : "AD-Disp Einstellungen Ändern",
	"HUDSettings" : "Ρυθμίσεις AD-Disp",
	"HUD_HeadUpDisplay" : "Active Driving Display",
	"HeadUpDisplay" : "Active Driving Display",
	"HeadlightOffTimer" : "Χρονόμετρο σβησίματος προβολέα",
	"HeadlightOnWarning" : "Προειδ. ενεργ. Προβολέα",
	"HeadsUpDisplay" : "Active Driving Display",
	"Height" : "Ύψος",
	"High" : "Υψ.",
	"HighBeamControl" : "High Beam Control",
	"High_SensitivityLAS" : "Υψ.",
	"High_Vibration" : "Υψ.",
	"ILB_Bright" : "Έντονος",
	"ILB_Dark" : "Χαμηλός",
	"ILB_Medium" : "Μεσαίο",
	"ILB_Off" : "Απενεργοποίηση ",
	"IgONAutoDisplay" : "Αυτόματη προβολή 360° View Monitor",
	"InterioLightsTimeOutDoorsClosed" : "Λήξη χρ. εσωτ. φωτ. - Κλ. πόρτα",
	"InterioLightsTimeOutDoorsOpen" : "Λήξη χρ. εσωτ. φωτ. - Αν. πόρτα",
	"InteriorLightTimeoutDoorClosedTitle" : "Λήξη χρ. εσωτ. φωτ. - Κλ. πόρτες",
	"InteriorLightTimeoutDoorOpenTitle" : "Λήξη χρ. εσωτ. φωτ. - Αν. πόρτες",
	"InteriorLightingBrightness" : "Φωτισμός εσωτερ. χώρου",
	"Intervention" : "Παρέμβαση",
	"InterventionTiming" : "Χρόνος παρέμβασης",
	"KeylessLockBeepVol" : "Ένταση μπιπ ασφ. χωρίς κλειδί",
	"Kilometers" : "km/h",
	"LASAlert" : "Ειδοποίηση LAS",
	"LASDefaultValues" : "Είστε βέβαιοι ότι θέλετε να επαναφέρετε τις ρυθμίσεις του Lane-keep Assist System στις προκαθορισμένες τιμές;",
	"LASEarly" : "Νωρίς",
	"LASLate" : "Καθυστέρηση",
	"LASSound" : "Τύπος ειδοποίησης",
	"LASTiming" : "Χρονισμός LAS",
	"LDWSReset" : "Θέλετε σίγουρα να επαναφέρετε τις ρυθμίσεις Lane Departure Warning System στις προεπιλεγμένες τιμές τους;",
	"LDWSResetError" : "Σφάλμα αλλαγής ρυθμίσεων Lane Departure Warning System. Θέλετε να ξαναδοκιμάσετε;",
	"LDWSResetProgress" : "Αλλαγή ρυθμίσεων Lane Departure Warning System",
	"LDWSTiming" : "Χρονισμός LDWS",
	"LaneDepartureAlert" : "Ειδοποίηση αποχώρησης λωρίδα",
	"LaneDepartureWarningSystem" : "Lane Departure Warning System",
	"LaneKeepAssistSystem" : "Lane-keep Assist System",
	"Late" : "Καθυστέρηση",
	"LeavingHomeLights" : "Leaving Home Light",
	"Light" : "Ανοιχτό",
	"LightOnReminderVolume" : "Έντ. υπενθ. Ενερ",
	"Lighting" : "Φωτισμός",
	"LightingReset" : "Θέλετε σίγουρα να επαναφέρετε τις ρυθμίσεις φωτισμού στις προεπιλεγμένες τιμές τους;",
	"LightingResetError" : "Σφάλμα αλλαγής ρυθμίσεων φωτισμού. Θέλετε να ξαναδοκιμάσετε;",
	"LightingResetProgress" : "Αλλαγή ρυθμίσεων φωτισμού",
	"LockShiftFromP" : "Κλείδ: Αλλαγή ταχ. από στάθμευση ",
	"LockShiftFromPUnlockInPark" : "Κλείδ:Αλλαγή ταχ Ξεκλείδ: Σε στάθμ.",
	"LockUnlock" : "Κλείδ:Οδήγηση Ξεκλείδ:Στάθμ.",
	"LockWhenDriving" : "Κλείδωμα: Κατά την οδήγηση",
	"LockWhenDrivingUnlockIGNoff" : "Κλείδ: Οδήγ Ξεκλείδ: Ανεν κλειδί εκ.",
	"Long" : "Μακρ",
	"Low" : "Χαμ.",
	"Low_SensitivityLAS" : "Χαμ.",
	"Low_Vibration" : "Χαμ.",
	"Manual" : "Χειρ.",
	"Med" : "Μέσ",
	"Medium" : "Μέσο",
	"MediumDark" : "δεν φως",
	"MediumLight" : "Ημι φως",
	"Medium_Int_OFF" : "Μέσ",
	"Medium_SensitivityLAS" : "Μέσ",
	"Mid" : "Μέση:",
	"Middle" : "Μέση",
	"Miles" : "mph",
	"Mode" : "Λειτουργία",
	"Navigation" : "Πλοήγηση",
	"NavigationSignal" : "Πλοήγηση  ",
	"Near" : "Κοντά",
	"Off" : "Ανεν.",
	"Often" : "Συχνά",
	"Often_Int_OFF" : "Συχνά",
	"OnDemand" : "Κατ. ζήτ.",
	"OnceAllDoors" : "Μία φορά: Όλες οι πόρτες",
	"OnceDriversDoorTwiceAllDoors" : "1 φορά: Οδηγού 2 φορές: Όλες",
	"Open" : "Ανοιγ.",
	"ParkingSensorIndication" : "Ένδειξη αισθητήρα στάθμευσης ",
	"ParkingSensorIndicator" : "Ένδειξη αισθητήρα στάθμευσης",
	"RVMBuzzerVolume" : "Rear Vehicle Monitoring Ένταση",
	"Rare" : "Σπάνιο",
	"Rare_Int_OFF" : "Σπάνιο",
	"Reset" : "Επαναφορά",
	"Rotation" : "Περιστροφή",
	"RumbleStrips" : "Σαμαρ.",
	"RumbleStrips_line" : "Σαμαρ. ",
	"RumbleVolume" : "Έντ. βόμβου",
	"SBSReset" : "Θέλετε σίγουρα να επαναφέρετε τις ρυθμίσεις Smart Brake Support στις προεπιλεγμένες τιμές τους;",
	"SBSResetError" : "Σφάλμα αλλαγής ρυθμίσεων Smart Brake Support. Θέλετε να ξαναδοκιμάσετε;",
	"SBSResetProgress" : "Αλλαγή Smart Brake Support ρυθμίσεων",
	"SBSSCBS" : "SBS/SCBS",
	"SBS_SCBSReset" : "Θέλετε σίγουρα να επαναφέρετε τις ρυθμίσεις SBS/SCBS στις προεπιλεγμένες τιμές τους;",
	"SBS_SCBSResetError" : "Σφάλμα αλλαγής ρυθμίσεων SBS/SCBS. Θέλετε να ξαναδοκιμάσετε;",
	"SBS_SCBSResetProgress" : "Αλλαγή ρυθμίσεων SBS/SCBS",
	"SCBS" : "Smart City Brake Support",
	"SCBSReset" : "Θέλετε σίγουρα να επαναφέρετε τις ρυθμίσεις του SCBS στις εργοστασιακές τιμές;",
	"SCBSResetError" : "Σφάλμα επαναφοράς ρυθμίσεων SCBS στις εργοστασιακές τιμές. Θέλετε να προσπαθήσετε ξανά;",
	"SCBSResetProgress" : "Γίνεται επαναφορά των ρυθμίσεων του SCBS",
	"SLC_Buzzer" : "Βομβητής μόνο",
	"SLC_Off" : "Απενεργοποίηση ",
	"SLC_Sign" : "Οπτ. ένδ",
	"SLC_Sign_Buzzer" : "Ηχητ. & Οπτ. ένδ.",
	"SLIReset" : "Είστε βέβαιοι ότι θέλετε να επαναφέρετε τις ρυθμίσεις Προειδοποίησης Ορίου Ταχύτητας στις προεπιλεγμένες τιμές;",
	"SLIResetError" : "Αδύνατη η επαναφορά των ρυθμίσεων Προειδοποίησης Ορίου Ταχύτητας στις προεπιλεγμένες τιμές. Θέλετε να προσπαθήσετε ξανά;",
	"SLIResetProgress" : "Γίνεται επαναφορά των ρυθμίσεων Προειδοποίησης Ορίου Ταχύτητας",
	"SLI_HeadUpDisplay" : "Active Driving Display",
	"Safety" : "ασφαλής",
	"Safetysettings" : "Ρυθμ. ασφάλειας",
	"Sensitivity" : "Ευαισθησία",
	"Sensitivity_Intervention_OFF" : "Προειδοποίηση ",
	"Setting" : "Ρυθμίσεις",
	"Settings" : "Ρυθμίσεις",
	"Short" : "Κοντά",
	"SideView" : "Πλάι",
	"SideViewFrontView" : "Πλάι+Εμπρός",
	"SmartBrakeSupport" : "Smart Brake Support",
	"Sound" : "Ήχος",
	"SpeedAlarm" : "Συναγερμός ταχύτητας",
	"SpeedLimitCaution" : "Ειδοποίηση ορίου ταχύτητας",
	"SpeedLimitInformation" : "Προειδ. ορίου ταχ.",
	"SpeedLimitSign" : "Ένδειξη ορίου ταχύτητας",
	"StepKilometers" : "{value} km/h",
	"StepMiles" : "{value} mph",
	"StreetInformation" : "Πληροφορίες οδών",
	"Streetinfo_off" : "Απενεργοποίηση",
	"System" : "Σύστημα",
	"TSRReset" : "Είστε βέβαιοι ότι θέλετε να επαναφέρετε τις ρυθμίσεις του Συστήματος Αναγνώρισης Οδικής Σήμανσης στις προεπιλεγμένες τιμές;",
	"TSRResetError" : "Αδύνατη η επαναφορά των ρυθμίσεων του Συστήματος Αναγνώρισης Οδικής Σήμανσης στις προεπιλεγμένες τιμές. Θέλετε να προσπαθήσετε ξανά;",
	"TSRResetProgress" : "Γίνεται επαναφορά των ρυθμίσεων του Συστήματος Αναγνώρισης Οδικής Σήμανσης",
	"TSR_Display" : "Προβολή οδικής σήμανσης",
	"TSR_System" : "Σύστημα αναγνώρισης οδικής σήμανσης",
	"Tachometer" : "Ταχύμετρο",
	"ThreeFlashTurnSignal" : "Σήμα στροφής 3 φλας",
	"Timing" : "Χρονισμός",
	"Turn" : "Στροφή",
	"TurnProgress" : "Αλλαγή ρυθμίσεων στροφής",
	"TurnReset" : "Θέλετε σίγουρα να επαναφέρετε τις ρυθμίσεις στροφής στις προεπιλεγμένες τιμές τους;",
	"TurnResetError" : "Σφάλμα αλλαγής ρυθμίσεων στροφής. Θέλετε να ξαναδοκιμάσετε;",
	"TurnSettings" : "Στροφή",
	"TurnSignalIndicatorVolume" : "Ένταση σήματος στροφ",
	"UnlockMode" : "Ξεκλείδωμα λειτουργίας",
	"Vehicle" : "Όχημα",
	"VehicleSettings" : "Ρυθμ. οχήματος",
	"Vibration" : "Δόνηση",
	"VibrationStrength" : "Ένταση δόνησης",
	"Vibration_Line" : "Δόνηση",
	"ViewSwitchDisplay" : "Προεπιλεγμένη προβολή",
	"ViewSwitchFunction" : "Λειτουργία εναλλαγής προβολής",
	"Volume" : "Ένταση ήχου",
	"WalkAwayLock" : "Κλείδωμα απομάκρυνσης",
	"Warning" : "Προειδοποίηση",
	"WarningDistance" : "Απόσταση προειδ.",
	"_0s" : "0 δευτ.",
	"_0seconds" : "0 δευτερόλεπτα",
	"_10m" : "10 λεπτά",
	"_10minutes" : "10 λεπτά",
	"_120s" : "120 δευτ.",
	"_120seconds" : "120 δευτερόλεπτα",
	"_15s" : "15 δευτ.",
	"_15seconds" : "15 δευτερόλεπτα",
	"_30m" : "30 λεπτά",
	"_30minutes" : "30 λεπτά",
	"_30s" : "30 δευτ.",
	"_30seconds" : "30 δευτερόλεπτα",
	"_60m" : "60 λεπτά",
	"_60minutes" : "60 λεπτά",
	"_60s" : "60 δευτ.",
	"_60seconds" : "60 δευτερόλεπτα",
	"_7p5s" : "7,5 δευτ.",
	"_7p5seconds" : "7,5 δευτερόλεπτα",
	"_90s" : "90 δευτ.",
	"_90seconds" : "90 δευτερόλεπτα",
	"_AllDoors" : "Όλες",
	"_Driver'sDoor" : "Οδηγού",
	"on" : "Ενερ.",
};

framework.registerAppDictLoaded("vehsettings", "el_GR");