var Localization_vehsettingsAppDict_hu_HU = {
	//"stringId" : "localString"
	"360ViewCamera" : "360°-os látószögű kamera",
	"AHBC" : "Adaptive LED Headlights",
	"Adaptive" : "Adaptív",
	"AdaptiveFront-lightingSystem" : "Adaptív elsőfényszóró-rendszer",
	"AdaptiveLaneStreetTurn" : "Alkalmazkodó köz/utca/sarok",
	"AlarmTiming" : "Sebesség",
	"AlertTiming" : "Riasztás időzítése",
	"Always" : "Mindig",
	"AtLine" : "Sornál:",
	"Auto" : "Auto",
	"AutoHeadlightOn" : "Fényszóró aut. bekapcsolása",
	"AutoWiper" : "Esőérzékelős ablaktörlő",
	"BSMBuzzerVolume" : "Blind Spot Monitoring Hangerő",
	"BSMReset" : "Biztosan visszaállítja a BSM-beállításokat gyári alapértékekre?",
	"BSMResetError" : "Hiba a BSM-beállítások gyári alapértékeinek visszaállításakor. Megpróbálja újra?",
	"BSMResetProgress" : "BSM beállítások visszaállítása folyamatban",
	"BSMSystem" : "Blind Spot Monitoring-rendszer ",
	"Beep" : "Csipogás",
	"BeepVolume" : "Hangjelzés hangereje",
	"Beep_Line" : "Csipogás",
	"BeforeLine" : "Sor el:",
	"Brightness" : "Fényerő",
	"BrightnessControl" : "Fényerőszabályzás",
	"CHudNav_Maneuver" : "Manőver",
	"CHudNav_Off" : "Ki",
	"CHudNav_TBT_Lane" : "Sávvez. és T-b-T",
	"CHudNav_TBT_Street" : "Utcanév és T-b-T",
	"Calibration" : "Fényerő",
	"CautionSpeed" : "Riasztási határérték",
	"CenterDisplay" : "Középső kijelző",
	"ChangingLASSettings" : "Lane-keep Assist System beáll. módos.",
	"Clock" : "Óra",
	"Close" : "Bezár",
	"ComingHomeLights" : "Coming Home Light",
	"ComingHomeLightsTimer" : "Coming Home Light",
	"DRSS" : "Distance Recognition Support System",
	"DRSSReset" : "Biztosan visszaállítja az Distance Recognition Support System (DRSS) beállításait gyári alapértékekre?",
	"DRSSResetError" : "Hiba az Distance Recognition Support System (DRSS) beállításainak módosításakor. Megpróbálja újra?",
	"DRSSResetProgress" : "Distance Recognition Support System (DRSS) beállításainak módosítása",
	"Dark" : "Sötét",
	"DaytimeRunningLights" : "Nappali világítás (DRL)",
	"Devices" : "Eszközök",
	"Display" : "Képer.",
	"DisplayInformation" : "Megjelenített adatok",
	"DistanceRecognitionSupportSystem" : "Distance Recognition Support System",
	"DoorLock" : "Ajtózár",
	"DoorLockMode" : "Automatikus ajtózár üzemmód",
	"DoorLockReset" : "Biztosan visszaállítja az ajtózár-beállításokat gyári alapértékekre?",
	"DoorLockResetError" : "Hiba az ajtózár-beállítások módosításakor... Megpróbálja újra?",
	"DoorLockResetProgress" : "Ajtózár-beállítások módosítása",
	"DoorRelockTime" : "Automatikus visszazárási idő",
	"DriverAlert" : "Driver Attention Alert",
	"Early" : "Korai",
	"ErrorBSMSettings" : "Hiba a BSM-beállítások megváltoztatása közben. Megpróbálja újra?",
	"ErrorLASSettings" : "Hiba a Lane-keep Assist System beállításainak módosításakor. Megpróbálja újra?",
	"FOWReset" : "Biztosan visszaállítja az Forward Obstruction Warning (FOW) beállításait gyári alapértékekre?",
	"FOWResetError" : "Hiba az Forward Obstruction Warning (FOW) beállításainak módosításakor. Megpróbálja újra?",
	"FOWResetProgress" : "Forward Obstruction Warning (FOW) beállításainak módosítása",
	"Far" : "Távol",
	"ForwardObstructionWarning" : "Forward Obstruction Warning",
	"FrontCameraView" : "Elülső kamerás nézet",
	"GearShiftIndicator" : "Sebességfokozat jelzése",
	"GuidelineDisplay" : "Dinamikus útvonalak",
	"HUD" : "AD-Disp",
	"HUDDisplayInfoError" : "Nem lehet visszaállítani a hirdetések megjelenítésére vonatkozó beállításokat a gyári értékekre. Szeretné újra megpróbálni?",
	"HUDDisplayInfoReset" : "Biztosan visszaállítja a hirdetések megjelenítésére vonatkozó beállításokat az alapbeállított értékekre?",
	"HUDDisplayInfoResetProgress" : " Visszaállítja a hirdetések megjelenítési beállításait",
	"HUDJ78AReset" : "Biztosan alapértelmezett értékre szeretné visszaállítani a Active Driving Display-beállításokat?",
	"HUDJ78AResetError" : "Hiba történt a Active Driving Display-beállítások visszaállításakor. Szeretné újból megpróbálni?",
	"HUDJ78AResetProgress" : "Active Driving Display-beállítások visszaállítása",
	"HUDJ78ATab" : "Active Driving Display",
	"HUDReset" : "Biztosan visszaállítja az Active Driving Display beállításait gyári alapértékekre?",
	"HUDResetError" : "Hiba az Active Driving Display beállításainak módosításakor. Megpróbálja újra?",
	"HUDResetProgress" : "AD-Disp beállításainak módosítása",
	"HUDSettings" : "AD-Disp-beállítások",
	"HUD_HeadUpDisplay" : "Active Driving Display",
	"HeadUpDisplay" : "Active Driving Display",
	"HeadlightOffTimer" : "Fényszóró-kikapcsolási időzítő",
	"HeadlightOnWarning" : "Bekapcsolt fényszóróra figyelmeztetés",
	"HeadsUpDisplay" : "Active Driving Display",
	"Height" : "Magasság",
	"High" : "Magas",
	"HighBeamControl" : "High Beam Control",
	"High_SensitivityLAS" : "Magas",
	"High_Vibration" : "Magas",
	"ILB_Bright" : "Halvány",
	"ILB_Dark" : "Halvány",
	"ILB_Medium" : "Közepes",
	"ILB_Off" : "Ki ",
	"IgONAutoDisplay" : "360° View Monitor automat. kijelzője",
	"InterioLightsTimeOutDoorsClosed" : "Belső világít. időzítése - zárt ajtók",
	"InterioLightsTimeOutDoorsOpen" : "Belső vil. leidőzítése - nyitott ajtók",
	"InteriorLightTimeoutDoorClosedTitle" : "Belső világítás időzít. - zárt ajtók",
	"InteriorLightTimeoutDoorOpenTitle" : "Belső vil. leidőzítése - nyitott ajtók",
	"InteriorLightingBrightness" : "Környezeti világítás",
	"Intervention" : "Közbelépés",
	"InterventionTiming" : "Közbelépés időzítése",
	"KeylessLockBeepVol" : "Kulcs nélküli zár hangjelz hangereje",
	"Kilometers" : "km/h",
	"LASAlert" : "Figyelmeztetés LAS",
	"LASDefaultValues" : "Biztosan visszaállítja a gyári alapbeállításokra a Lane-keep Assist System értékeit?",
	"LASEarly" : "Korai",
	"LASLate" : "Késő",
	"LASSound" : "Riasztás típusa",
	"LASTiming" : "LAS időzítés",
	"LDWSReset" : "Biztosan visszaállítja az Lane Departure Warning System (LDWS) beállításait gyári alapértékekre?",
	"LDWSResetError" : "Hiba az Lane Departure Warning System (LDWS) beállításainak módosításakor. Megpróbálja újra?",
	"LDWSResetProgress" : "Lane Departure Warning System (LDWS) beállításainak módosítása",
	"LDWSTiming" : "LDWS időzítése",
	"LaneDepartureAlert" : "Sávelhagyási riasztás",
	"LaneDepartureWarningSystem" : "Lane Departure Warning System",
	"LaneKeepAssistSystem" : "Lane-keep Assist System",
	"Late" : "Késő",
	"LeavingHomeLights" : "Leaving Home Light",
	"Light" : "Világos",
	"LightOnReminderVolume" : "Vil.figy. Hangereje",
	"Lighting" : "Világítás",
	"LightingReset" : "Biztosan visszaállítja a világítási beállításokat a gyári alaphelyzetre?",
	"LightingResetError" : "Hiba a világítási beállítások módosításakor. Megpróbálja újra?",
	"LightingResetProgress" : "Világítási beállítások módosítása",
	"LockShiftFromP" : "Zár: Fokozat kapcsolásakor ",
	"LockShiftFromPUnlockInPark" : "Zár: p.seb.f. elhagy. Nyit: p.seb.fok.ban",
	"LockUnlock" : "Zár: Vez. Nyit: Park.",
	"LockWhenDriving" : "Zár: Vezetés közben",
	"LockWhenDrivingUnlockIGNoff" : "Zár: Zár feloldása vezetéskor: IGN ki",
	"Long" : "Távol",
	"Low" : "Alacs",
	"Low_SensitivityLAS" : "Alacs",
	"Low_Vibration" : "Alacs",
	"Manual" : "Kézi",
	"Med" : "Közepes",
	"Medium" : "Közepes",
	"MediumDark" : "Közep sötét",
	"MediumLight" : "Közep világos",
	"Medium_Int_OFF" : "Közepes",
	"Medium_SensitivityLAS" : "Közepes",
	"Mid" : "Közepes",
	"Middle" : "Közép",
	"Miles" : "mph",
	"Mode" : "Üzemmód",
	"Navigation" : "Navigáció",
	"NavigationSignal" : "Navigáció  ",
	"Near" : "Közel",
	"Off" : "Ki",
	"Often" : "Gyakran",
	"Often_Int_OFF" : "Gyakran",
	"OnDemand" : "Ig. Sz.",
	"OnceAllDoors" : "Egyszer: összes ajtó",
	"OnceDriversDoorTwiceAllDoors" : "Egyszer: vezetőo. Kétszer: össz. ajtó",
	"Open" : "Nyitás",
	"ParkingSensorIndication" : "Parkolóradar jelzése ",
	"ParkingSensorIndicator" : "Parkolóradar-jelzőfény",
	"RVMBuzzerVolume" : "Rear Vehicle Monitoring Hangerő",
	"Rare" : "Ritka",
	"Rare_Int_OFF" : "Ritka",
	"Reset" : "Visszaállítás",
	"Rotation" : "Elforgatás",
	"RumbleStrips" : "Rázókő",
	"RumbleStrips_line" : "Rázókő ",
	"RumbleVolume" : "Rázókő hangereje",
	"SBSReset" : "Biztosan visszaállítja az Smart Brake Support (SBS) beállításait gyári alapértékekre?",
	"SBSResetError" : "Hiba az Smart Brake Support (SBS) beállításainak módosításakor. Megpróbálja újra?",
	"SBSResetProgress" : "Smart Brake Support (SBS) beállításainak módosítása",
	"SBSSCBS" : "SBS/SCBS",
	"SBS_SCBSReset" : "Biztosan visszaállítja az SBS/SCBS beállításait gyári alapértékekre?",
	"SBS_SCBSResetError" : "Hiba az SBS/SCBS beállításainak módosításakor. Megpróbálja újra?",
	"SBS_SCBSResetProgress" : "SBS/SCBS beállításainak módosítása",
	"SCBS" : "Smart City Brake Support",
	"SCBSReset" : "Biztosan visszaállítja az SCBS-beállításokat gyári alapértékekre?",
	"SCBSResetError" : "Nem lehet visszaállítani az SCBS-beállításokat gyári alapértékekre. Megpróbálja újra?",
	"SCBSResetProgress" : "SCBS beállítások visszaállítása folyamatban",
	"SLC_Buzzer" : "Csak hangjelzés",
	"SLC_Off" : "Ki ",
	"SLC_Sign" : "Vizuális",
	"SLC_Sign_Buzzer" : "Audiovizuális",
	"SLIReset" : "Biztosan visszaállítja a sebességhatár-figyelmeztetési értékeket az alapbeállítás értékeire?",
	"SLIResetError" : "Nem lehet visszaállítani a sebességhatár-figyelmeztetési értékeket a gyári értékekre. Megpróbálja újra?",
	"SLIResetProgress" : "Sebességhatár-figyelmeztetési értékek visszaállítása",
	"SLI_HeadUpDisplay" : "Active Driving Display",
	"Safety" : "Bizton.",
	"Safetysettings" : "Biztonsági beállítások",
	"Sensitivity" : "Érzékenység",
	"Sensitivity_Intervention_OFF" : "Figyelmeztetés ",
	"Setting" : "Beállítások",
	"Settings" : "Beállítások",
	"Short" : "Közel",
	"SideView" : "Oldalsó",
	"SideViewFrontView" : "Oldalsó+Elülső",
	"SmartBrakeSupport" : "Smart Brake Support",
	"Sound" : "Hang",
	"SpeedAlarm" : "Sebességriasztás",
	"SpeedLimitCaution" : "Sebességkorlátozási riasztás",
	"SpeedLimitInformation" : "Sebességkorlátozási figyelmeztetés",
	"SpeedLimitSign" : "Sebességkorlátozás megjelenítése",
	"StepKilometers" : "{value} km/h",
	"StepMiles" : "{value} mph",
	"StreetInformation" : "Utcainformációk",
	"Streetinfo_off" : "Ki",
	"System" : "Rendszer",
	"TSRReset" : "Biztosan visszaállítja a közúti jelzést felismerő rendszer értékeket az alapbeállítás értékeire?",
	"TSRResetError" : "Nem lehet visszaállítani a közlekedésijelzés-felismerő rendszer értékeket a gyári értékekre. Megpróbálja újra?",
	"TSRResetProgress" : "Közúti jelzést felismerő rendszer értékeinek visszaállítása",
	"TSR_Display" : "Közúti jelzés kijelzője",
	"TSR_System" : "Közúti jelzést felismerő rendszer",
	"Tachometer" : "Fordulatszámmérő",
	"ThreeFlashTurnSignal" : "3 villanásos irányjelző",
	"Timing" : "Időzítés",
	"Turn" : "Kanyarodás",
	"TurnProgress" : "Kanyarodási beállítások módosítása",
	"TurnReset" : "Biztosan visszaállítja a kanyarodási beállításokat a gyári alaphelyzetre?",
	"TurnResetError" : "Hiba a kanyarodási beállítások módosításakor. Megpróbálja újra?",
	"TurnSettings" : "Kanyarodás",
	"TurnSignalIndicatorVolume" : "Irányjelző hangereje",
	"UnlockMode" : "Feloldás üzemmód",
	"Vehicle" : "Jármű",
	"VehicleSettings" : "Járműbeállítások",
	"Vibration" : "Rezgés",
	"VibrationStrength" : "Rezgés erőssége",
	"Vibration_Line" : "Rezgés",
	"ViewSwitchDisplay" : "Alapértelmezett nézet",
	"ViewSwitchFunction" : "Nézetváltás funkció",
	"Volume" : "Hangerő",
	"WalkAwayLock" : "Nyitva hagyott jármű aut. lezárása",
	"Warning" : "Figyelmeztetés",
	"WarningDistance" : "Figyelmeztet. táv.",
	"_0s" : "0 s",
	"_0seconds" : "0 másodperc",
	"_10m" : "10 perc",
	"_10minutes" : "10 perc",
	"_120s" : "120 s",
	"_120seconds" : "120 másodperc",
	"_15s" : "15 s",
	"_15seconds" : "15 másodperc",
	"_30m" : "30 perc",
	"_30minutes" : "30 perc",
	"_30s" : "30 s",
	"_30seconds" : "30 másodperc",
	"_60m" : "60 perc",
	"_60minutes" : "60 perc",
	"_60s" : "60 s",
	"_60seconds" : "60 másodperc",
	"_7p5s" : "7,5 s",
	"_7p5seconds" : "7,5 másodperc",
	"_90s" : "90 s",
	"_90seconds" : "90 másodperc",
	"_AllDoors" : "Összes",
	"_Driver'sDoor" : "Vezetői",
	"on" : "Be",
};

framework.registerAppDictLoaded("vehsettings", "hu_HU");