var Localization_aharadioAppDict_fr_FR = {
	//"stringId" : "localString"
	"ActionNotAvailable" : "Action indisponible",
	"AhaMaintenance" : "Désolé, les serveurs aha sont momentanément indisponibles.",
	"AhaNotFound" : "aha non trouvée",
	"Back" : "Retour",
	"CheckConnection" : "Assurez-vous que la connexion de données sur votre dispositif mobile fonctionne correctement.",
	"Connect" : "Connecter",
	"ConnectionLost" : "Communication Bluetooth perdue",
	"Discard" : "Ne pas enregistrer",
	"Dislike" : "N’aime pas",
	"DislikeTooltip" : "N’aime pas",
	"EmptyList" : "Liste vide. Ajouter dispositif mobile.",
	"Episodes_Tooltip" : "Épisodes",
	"FunctioningProperly" : "Lorsque cela ne présente pas de risque, assurez-vous que votre appareil mobile fonctionne correctement.",
	"GUI_ShoutPosted_Alert" : "Shout envoyé",
	"InsufficientConnectivity_Alert" : "Connectivité insuffisante",
	"LBS" : "A proximité",
	"Like" : "Aime",
	"LikeTooltip" : "Aime",
	"MainList_Tooltip" : "Liste principale",
	"MakeSureAhaIsInstalled" : "Assurez-vous que l'application aha est bien installée sur votre appareil mobile.",
	"MobileDeviceError" : "Erreur du dispositif mobile",
	"NoDeviceConnected" : "Aucun dispositif connecté",
	"NoNetworkAvailable" : "Aucune connexion au réseau",
	"Nostationsadded" : "Aucune station ajoutée.",
	"Preset" : "Préréglages",
	"RecordingLimit" : "La limite d’enregistrement a été atteinte. Voulez-vous poster ce shout ?",
	"Save" : "Enregistrer",
	"SetupBluetooth" : "Configurer le dispositif Bluetooth maintenant ?",
	"ShoutReady" : "Shout prêt",
	"ShoutRecording" : "Enregistrement d’un Shout",
	"VrHelp_LBSDetail_Help_Left1" : "Divertissements",
	"VrHelp_LBSDetail_Help_Left2" : "Liste principale",
	"VrHelp_LBSDetail_Help_Left3" : "Épisodes",
	"VrHelp_LBSDetail_Help_Left4" : "Shoute",
	"VrHelp_LBSDetail_Help_Left5" : "Carte",
	"VrHelp_LBSDetail_Help_Right1" : "Appeler",
	"VrHelp_LBSDetail_Help_Right2" : "Lire/Pause",
	"VrHelp_LBSDetail_Help_Right3" : "Précédent / Suivant",
	"VrHelp_LBSDetail_Help_Right4" : "Paramètres audio",
	"VrHelp_NowPlaying_Help_Left1" : "Divertissements",
	"VrHelp_NowPlaying_Help_Left2" : "Liste principale",
	"VrHelp_NowPlaying_Help_Left3" : "Épisodes",
	"VrHelp_NowPlaying_Help_Left4" : "Shoute",
	"VrHelp_NowPlaying_Help_Left5" : " Aime / N'aime pas",
	"VrHelp_NowPlaying_Help_Right1" : "Retour de 15 secondes",
	"VrHelp_NowPlaying_Help_Right2" : "Lire/Pause",
	"VrHelp_NowPlaying_Help_Right3" : "Précédent / Suivant",
	"VrHelp_NowPlaying_Help_Right4" : "Avance de 30 secondes",
	"VrHelp_NowPlaying_Help_Right5" : "Paramètres audio",
	"buffering" : "Mise en mémoire",
	"entMenu" : "Menu des divertissements",
	"sbNameId" : "aha",
};

framework.registerAppDictLoaded("aharadio", "fr_FR");