var Localization_aharadioAppDict_th_TH = {
	//"stringId" : "localString"
	"ActionNotAvailable" : "ไม่สามารถดำเนินการได้",
	"AhaMaintenance" : "ขออภัย เซอร์ฟเวอร์ของ aha ยังไม่พร้อมใช้งานในขณะนี้",
	"AhaNotFound" : "ไม่พบ aha",
	"Back" : "ย้อนกลับ",
	"CheckConnection" : "ตรวจสอบให้แน่ใจว่าการเชื่อมต่อข้อมูลบนอุปกรณ์เคลื่อนที่ของคุณทำงานอย่างถูกต้อง",
	"Connect" : "เชื่อมต่อ",
	"ConnectionLost" : "ขาดการติดต่อกับบลูทูธ",
	"Discard" : "ยกเลิก",
	"Dislike" : "ไม่ชอบ",
	"DislikeTooltip" : "ไม่ชอบ",
	"EmptyList" : "ไม่มีรายการ กรุณาเพิ่มจากมือถือ",
	"Episodes_Tooltip" : "ตอน",
	"FunctioningProperly" : "หากดำเนินการได้โดยปลอดภัย โปรดตรวจสอบว่าอุปกรณ์เคลื่อนที่ของคุณทำงานได้อย่างถูกต้อง",
	"GUI_ShoutPosted_Alert" : "โพสต์การบอกเล่าเรื่องราว",
	"InsufficientConnectivity_Alert" : "การเชื่อมต่อไม่เพียงพอ",
	"LBS" : "บริเวณใกล้เคียง",
	"Like" : "ชอบ",
	"LikeTooltip" : "ชอบ",
	"MainList_Tooltip" : "รายชื่อหลัก",
	"MakeSureAhaIsInstalled" : "ตรวจสอบให้แน่ใจว่าแอปพลิเคชัน aha ติดตั้งในอุปกรณ์เคลื่อนที่ของคุณแล้ว",
	"MobileDeviceError" : "อุปกรณ์เคลื่อนที่ทำงานขัดข้อง",
	"NoDeviceConnected" : "ไม่ได้เชื่อมต่ออุปกรณ์",
	"NoNetworkAvailable" : "ไม่มีการเชื่อมต่อเครือข่าย",
	"Nostationsadded" : "ไม่มีการเพิ่มสถานี",
	"Preset" : "กำหนดไว้ล่วงหน้า",
	"RecordingLimit" : "หมดเวลาในการบันทึก คุณต้องการโพสต์การบอกเล่าเรื่องราวนี้หรือไม่",
	"Save" : "บันทึก",
	"SetupBluetooth" : "ติดตั้งอุปกรณ์ Bluetooth เดี๋ยวนี้หรือไม่",
	"ShoutReady" : "การบอกเล่าเรื่องราวพร้อมทำงาน",
	"ShoutRecording" : "กำลังบันทึกการบอกเล่าเรื่องราว",
	"VrHelp_LBSDetail_Help_Left1" : "Entertainment",
	"VrHelp_LBSDetail_Help_Left2" : "Main List",
	"VrHelp_LBSDetail_Help_Left3" : "Episodes",
	"VrHelp_LBSDetail_Help_Left4" : "Shout",
	"VrHelp_LBSDetail_Help_Left5" : "Map",
	"VrHelp_LBSDetail_Help_Right1" : "Call",
	"VrHelp_LBSDetail_Help_Right2" : "Play / Pause",
	"VrHelp_LBSDetail_Help_Right3" : "Previous / Next",
	"VrHelp_LBSDetail_Help_Right4" : "Sound Settings",
	"VrHelp_NowPlaying_Help_Left1" : "Entertainment",
	"VrHelp_NowPlaying_Help_Left2" : "Main List",
	"VrHelp_NowPlaying_Help_Left3" : "Episodes",
	"VrHelp_NowPlaying_Help_Left4" : "Shout",
	"VrHelp_NowPlaying_Help_Left5" : "Like / Dislike",
	"VrHelp_NowPlaying_Help_Right1" : "Back 15 Seconds",
	"VrHelp_NowPlaying_Help_Right2" : "Play / Pause",
	"VrHelp_NowPlaying_Help_Right3" : "Previous / Next",
	"VrHelp_NowPlaying_Help_Right4" : "Forward 30 Seconds",
	"VrHelp_NowPlaying_Help_Right5" : "Sound Settings",
	"buffering" : "กำลังบัฟเฟอร์",
	"entMenu" : "เมนูความบันเทิง",
	"sbNameId" : "aha",
};

framework.registerAppDictLoaded("aharadio", "th_TH");