var Localization_dabAppDict_sk_SK = {
	//"stringId" : "localString"
	"DABAnalog" : "Analógové",
	"DABBandIII" : "Pásmo III",
	"DABBandSettingsList" : "Nastenia vysiel. pásma",
	"DABBandSettingsTitle" : "Nastenia vysiel. pásma",
	"DABBoth" : "Obidve",
	"DABChangeEnsemble" : "Zmeňte, prosím, skupinu",
	"DABDABLink" : "Prepojenie DAB-DAB",
	"DABDigital" : "Digitálne",
	"DABEnsembleList" : "Zoznam skupín",
	"DABEnsembleListTitle" : "Vyberte skupín",
	"DABEnsembleListTitle2" : "Zoznam skupín",
	"DABEnsembleListUpdateComplete" : "Zoznam skupín sa aktualizoval",
	"DABFMLink" : "Prepojenie DAB-FM",
	"DABLBand" : "Pásmo L",
	"DABListNotAvailable" : "Zoznam staníc nie je dostupný",
	"DABNoResultsFound" : "Nenašli sa žiadne výsledky",
	"DABNoSignal" : "Žiadny signál",
	"DABPleaseUpdateList" : "Aktualizujte, prosím, zoznam",
	"DABRadio" : "Rádio DAB",
	"DABRadioText" : "Rozhlasový text",
	"DABSelectEnsemble" : "Vyberte skupín",
	"DABSettings" : "Nastavenia DAB",
	"DABSettingsListTitle" : "Nastavenia",
	"DABSettingsNowPlaying" : "Nastavenia DAB",
	"DABSignalLost" : "{ChNum} Video signál sa stratil",
	"DABSignalSearch" : "Vyhľadáva sa…",
	"DABStationListUpdateFailedSelect" : "Zoznam staníc nemožno aktualiz.",
	"DABStationListUpdated" : "Aktualizuje sa zoznam staníc",
	"DABStatusBarTitle" : "DAB",
	"DABTrafficAlertOff" : "Premávka (TA) vyp",
	"DABTrafficAlertOn" : "Premávka (TA) zap",
	"DABUnableToUpdateStationList" : "Nemožno aktualizovať",
	"DABUpdate" : "Aktualizovať",
	"DABUpdateEnsemble" : "Chcete ho aktualizovať?",
	"DABUpdateEnsembleList" : "Aktualizovať zoznam skupín",
	"DABUpdateList" : "Aktualizujte zoznam",
	"DABUpdateStation" : "Aktualizovať zoznam staníc?",
	"DABUpdatingEnsembleList" : "Aktualizuje sa zoznam skupín",
	"DABUpdatingList" : "Zoznam sa aktualizuje…",
	"DABUpdatingListNowPlaying" : "Zoznam sa aktualizuje…",
	"StationListTab" : "Zoznam staníc",
	"VrHelp_DABSettings" : "DAB Settings",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_Favorites" : "Favourites",
	"VrHelp_Next" : "Next",
	"VrHelp_Previous" : "Previous",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement  (TA)",
};

framework.registerAppDictLoaded("dab", "sk_SK");