var Localization_dabAppDict_ms_MY = {
	//"stringId" : "localString"
	"DABAnalog" : "Analog",
	"DABBandIII" : "Jalur III",
	"DABBandSettingsList" : "Tetapan Jalur",
	"DABBandSettingsTitle" : "Tetapan Jalur",
	"DABBoth" : "Kedua-dua",
	"DABChangeEnsemble" : "Sila ubah Ensembel",
	"DABDABLink" : "Pautan DAB-DAB",
	"DABDigital" : "Digital",
	"DABEnsembleList" : "Senarai Ensembel",
	"DABEnsembleListTitle" : "Pilih Ensembel",
	"DABEnsembleListTitle2" : "Senarai Ensembel",
	"DABEnsembleListUpdateComplete" : "Senarai Ensembel Dikemas Kini",
	"DABFMLink" : "Pautan DAB-FM",
	"DABLBand" : "Jalur L",
	"DABListNotAvailable" : "Senarai Stesen Tidak Tersedia",
	"DABNoResultsFound" : "Tiada keputusan ditemui",
	"DABNoSignal" : "Tiada Isyarat",
	"DABPleaseUpdateList" : "Sila kemas kini senarai",
	"DABRadio" : "Radio DAB",
	"DABRadioText" : "Teks Radio",
	"DABSelectEnsemble" : "Pilih Ensembel",
	"DABSettings" : "Tetapan DAB",
	"DABSettingsListTitle" : "Tetapan",
	"DABSettingsNowPlaying" : "Tetapan",
	"DABSignalLost" : "Isyarat Hilang{ChNum}",
	"DABSignalSearch" : "Mencari. . .",
	"DABStationListUpdateFailedSelect" : "Tidak Dapat Mengemas Kini Senarai Stesen",
	"DABStationListUpdated" : "Senarai Stesen Dikemas Kini",
	"DABStatusBarTitle" : "DAB",
	"DABTrafficAlertOff" : "Pengumuman Lalu Lintas Mati",
	"DABTrafficAlertOn" : "Pengumuman Lalu Lintas Hidup",
	"DABUnableToUpdateStationList" : "Tidak Dapat Mengemas Kini Senarai",
	"DABUpdate" : "Kemas Kini",
	"DABUpdateEnsemble" : "Kemas Kini Senarai Ensembel?",
	"DABUpdateEnsembleList" : "Kemas Kini Senarai Ensembel",
	"DABUpdateList" : "Mengemas Kini Senarai",
	"DABUpdateStation" : "Kemas Kini Senarai Stesen?",
	"DABUpdatingEnsembleList" : "Mengemas Kini senarai Ensembel",
	"DABUpdatingList" : "Mengemas Kini Senarai. . .",
	"DABUpdatingListNowPlaying" : "Mengemas Kini Senarai…",
	"StationListTab" : "Senarai Stesen",
	"VrHelp_DABSettings" : "DAB Settings",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_Favorites" : "Favourites",
	"VrHelp_Next" : "Next",
	"VrHelp_Previous" : "Previous",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement",
};

framework.registerAppDictLoaded("dab", "ms_MY");