var Localization_dabAppDict_fr_CN = {
	//"stringId" : "localString"
	"DABAnalog" : "Analogique",
	"DABBandIII" : "Bande III",
	"DABBandSettingsList" : "Paramètres de bande",
	"DABBandSettingsTitle" : "Paramètres de bande",
	"DABBoth" : "Les deux",
	"DABChangeEnsemble" : "Veuillez modifier l'ensemble",
	"DABDABLink" : "Lien DAB-DAB",
	"DABDigital" : "Digital",
	"DABEnsembleList" : "Liste de l'ensemble",
	"DABEnsembleListTitle" : "Sélectionner Ensemble",
	"DABEnsembleListTitle2" : "Liste de l'ensemble",
	"DABEnsembleListUpdateComplete" : "Liste d'ensemble mise à jour",
	"DABFMLink" : "Lien DAB-FM",
	"DABLBand" : "Bande L ",
	"DABListNotAvailable" : "Liste des stations non disponible",
	"DABNoResultsFound" : "Aucun résultat trouvé",
	"DABNoSignal" : "Pas de signal",
	"DABPleaseUpdateList" : "Veuillez mettre à jour la liste",
	"DABRadio" : "Radio DAB",
	"DABRadioText" : "Radio information",
	"DABSelectEnsemble" : "Sélectionner Ensemble",
	"DABSettings" : "Paramètres DAB",
	"DABSettingsListTitle" : "Paramètres",
	"DABSettingsNowPlaying" : "Paramètres DAB",
	"DABSignalLost" : "{ChNum} Signal perdu",
	"DABSignalSearch" : "Recherche en cours…",
	"DABStationListUpdateFailedSelect" : "Imp. de mettre la liste de st. à jour",
	"DABStationListUpdated" : "Liste des stations mise à jour",
	"DABStatusBarTitle" : "DAB",
	"DABTrafficAlertOff" : "Annonce de circulation désactivée",
	"DABTrafficAlertOn" : "Annonce de circulation activée",
	"DABUnableToUpdateStationList" : "Impossible de mettre jour",
	"DABUpdate" : "Mise à jour",
	"DABUpdateEnsemble" : "Mettre à jour la liste d'ensemble ?",
	"DABUpdateEnsembleList" : "Mise à jour de la liste d'ensemble",
	"DABUpdateList" : "Mettre liste à jour",
	"DABUpdateStation" : "Mettre à jour liste des stations?",
	"DABUpdatingEnsembleList" : "Mise à jour de la liste d'ensemble",
	"DABUpdatingList" : "Mise à jour de la liste…",
	"DABUpdatingListNowPlaying" : "Mise à jour de la liste…",
	"StationListTab" : "Liste des stations",
	"VrHelp_DABSettings" : "DAB Settings",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_Favorites" : "Favorites",
	"VrHelp_Next" : "Next",
	"VrHelp_Previous" : "Previous",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement",
};

framework.registerAppDictLoaded("dab", "fr_CN");