var Localization_dabAppDict_es_MX = {
	//"stringId" : "localString"
	"DABAnalog" : "Analógico",
	"DABBandIII" : "Banda III",
	"DABBandSettingsList" : "Configuración de banda",
	"DABBandSettingsTitle" : "Configuración de banda",
	"DABBoth" : "Ambos",
	"DABChangeEnsemble" : "Por favor, cambie el grupo",
	"DABDABLink" : "Enlace de DAB-DAB",
	"DABDigital" : "Digital",
	"DABEnsembleList" : "Lista de grupos",
	"DABEnsembleListTitle" : "Seleccione un grupo",
	"DABEnsembleListTitle2" : "Lista de grupos\n",
	"DABEnsembleListUpdateComplete" : "Se ha actualizado Lista de grupos",
	"DABFMLink" : "Enlace de DAB-FM",
	"DABLBand" : "Banda L",
	"DABListNotAvailable" : "Lista de emisoras no disponible",
	"DABNoResultsFound" : "No se encontraron resultados",
	"DABNoSignal" : "No hay señal",
	"DABPleaseUpdateList" : "Por favor, actualice la lista",
	"DABRadio" : "Radio DAB",
	"DABRadioText" : "Texto de radio",
	"DABSelectEnsemble" : "Seleccione un grupo",
	"DABSettings" : "Configuración de DAB",
	"DABSettingsListTitle" : "Configuraciones",
	"DABSettingsNowPlaying" : "Configuración de DAB",
	"DABSignalLost" : "{ChNum} Señal perdida",
	"DABSignalSearch" : "Buscando…",
	"DABStationListUpdateFailedSelect" : "Imposible actualizar lista emisoras",
	"DABStationListUpdated" : "Lista de emisoras actualizada",
	"DABStatusBarTitle" : "DAB",
	"DABTrafficAlertOff" : "Anuncio de Tráfico (TA) apagado",
	"DABTrafficAlertOn" : "Anuncio de Tráfico (TA) encendido",
	"DABUnableToUpdateStationList" : "No se puede actualizar",
	"DABUpdate" : "Actualizar",
	"DABUpdateEnsemble" : "¿Desea actualizar la Lista de grupos?",
	"DABUpdateEnsembleList" : "Actualizar la Lista de grupos",
	"DABUpdateList" : "Actualizar Lista",
	"DABUpdateStation" : "¿Actualizar lista de emisoras?",
	"DABUpdatingEnsembleList" : "Actualizando la Lista de grupos",
	"DABUpdatingList" : "Actualizando lista…",
	"DABUpdatingListNowPlaying" : "Actualizando lista…",
	"StationListTab" : "Lista de Emisoras",
	"VrHelp_DABSettings" : "Configuración de DAB",
	"VrHelp_Entertainment" : "Entretenimiento",
	"VrHelp_Favorites" : "Favoritos",
	"VrHelp_Next" : "Siguiente",
	"VrHelp_Previous" : "Anterior",
	"VrHelp_Scan" : "Explorar",
	"VrHelp_SoundSettings" : "Ajustes de Sonido",
	"VrHelp_StationList" : "Lista de Emisoras",
	"VrHelp_TrafficAnnouncement" : "Anuncio de Tráfico (TA)",
};

framework.registerAppDictLoaded("dab", "es_MX");