var Localization_dabAppDict_lt_LT = {
	//"stringId" : "localString"
	"DABAnalog" : "Analoginis",
	"DABBandIII" : "III dažnių juosta",
	"DABBandSettingsList" : "Dažnių juostos nustatymai",
	"DABBandSettingsTitle" : "Dažnių juostos nustatymai",
	"DABBoth" : "Abi",
	"DABChangeEnsemble" : "Pakeiskite stočių grupę",
	"DABDABLink" : "DAB-DAB sąsaja",
	"DABDigital" : "Skaitmeninis",
	"DABEnsembleList" : "Stočių grupių sąrašas",
	"DABEnsembleListTitle" : "Pasirinkite stočių grupę",
	"DABEnsembleListTitle2" : "Stočių grupių sąrašas",
	"DABEnsembleListUpdateComplete" : "Stočių grupių sąrašas atnaujintas",
	"DABFMLink" : "DAB-FM sąsaja",
	"DABLBand" : "L dažnių juosta",
	"DABListNotAvailable" : "Stočių sąrašas nepasiekiamas",
	"DABNoResultsFound" : "Rezultatų nerasta",
	"DABNoSignal" : "Nėra signalo",
	"DABPleaseUpdateList" : "Atnaujinkite sąrašą",
	"DABRadio" : "DAB radijas",
	"DABRadioText" : "Radijo tekstas",
	"DABSelectEnsemble" : "Pasirinkite stočių grupę",
	"DABSettings" : "DAB nustatymai",
	"DABSettingsListTitle" : "Nustatymai",
	"DABSettingsNowPlaying" : "DAB nustatymai",
	"DABSignalLost" : "{ChNum} Prarastas signalas",
	"DABSignalSearch" : "Ieškoma…",
	"DABStationListUpdateFailedSelect" : "Nepavyksta naujinti stočių sąrašo",
	"DABStationListUpdated" : "Stočių sąrašas atnaujintas",
	"DABStatusBarTitle" : "DAB",
	"DABTrafficAlertOff" : "Pranešimas apie eismą išjungtas",
	"DABTrafficAlertOn" : "Pranešimas apie eismą įjungtas",
	"DABUnableToUpdateStationList" : "Nepavyksta naujinti",
	"DABUpdate" : "Naujinti",
	"DABUpdateEnsemble" : "Naujinti stočių grupių sąrašą?",
	"DABUpdateEnsembleList" : "Naujinti stočių grupių sąrašą",
	"DABUpdateList" : "Atnaujinkite sąrašą",
	"DABUpdateStation" : "Naujinti stočių sąrašą?",
	"DABUpdatingEnsembleList" : "Naujinamas stočių grupių sąrašas",
	"DABUpdatingList" : "Naujinamas sąrašas…",
	"DABUpdatingListNowPlaying" : "Naujinamas sąrašas…",
	"StationListTab" : "Stočių sąrašas",
	"VrHelp_DABSettings" : "DAB Settings",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_Favorites" : "Favourites",
	"VrHelp_Next" : "Next",
	"VrHelp_Previous" : "Previous",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement  (TA)",
};

framework.registerAppDictLoaded("dab", "lt_LT");