var Localization_dabAppDict_ru_RU = {
	//"stringId" : "localString"
	"DABAnalog" : "Аналоговое",
	"DABBandIII" : "Полоса Ⅲ",
	"DABBandSettingsList" : "Настройки ПОЛОС",
	"DABBandSettingsTitle" : "Настройки ПОЛОС",
	"DABBoth" : "Обе",
	"DABChangeEnsemble" : "Пожалуйста измените ансамбль",
	"DABDABLink" : "Цифр.-Цифр. соед.",
	"DABDigital" : "Цифровое",
	"DABEnsembleList" : "Список ансамблей",
	"DABEnsembleListTitle" : "Выбрать ансамбль",
	"DABEnsembleListTitle2" : "Список ансамблей",
	"DABEnsembleListUpdateComplete" : "Список ансамблей был обновлен",
	"DABFMLink" : "Цифр.-FM соединен.",
	"DABLBand" : "Полоса L",
	"DABListNotAvailable" : "Список радиостанций недоступен",
	"DABNoResultsFound" : "Результаты не найдены",
	"DABNoSignal" : "Нет сигнала",
	"DABPleaseUpdateList" : "Пожалуйста, обновите список",
	"DABRadio" : "Радио DAB",
	"DABRadioText" : "Радиотекст",
	"DABSelectEnsemble" : "Выбрать ансамбль",
	"DABSettings" : "Настройки DAB",
	"DABSettingsListTitle" : "Настройки",
	"DABSettingsNowPlaying" : "Настройки DAB",
	"DABSignalLost" : "{ChNum} Сигнал потерян",
	"DABSignalSearch" : "Идет поиск…",
	"DABStationListUpdateFailedSelect" : "Невозможно обновить список",
	"DABStationListUpdated" : "Список станций обновлен.",
	"DABStatusBarTitle" : "DAB",
	"DABTrafficAlertOff" : "Выключить контроль трафика",
	"DABTrafficAlertOn" : "Включить контроль трафика",
	"DABUnableToUpdateStationList" : "Невозможно обновить",
	"DABUpdate" : "Обновить",
	"DABUpdateEnsemble" : "Обновить список ансамблей?",
	"DABUpdateEnsembleList" : "Обновить список ансамблей",
	"DABUpdateList" : "Обновить список",
	"DABUpdateStation" : "Обновить список станций?",
	"DABUpdatingEnsembleList" : "Обновление списка ансамблей",
	"DABUpdatingList" : "Обновление списка…",
	"DABUpdatingListNowPlaying" : "Обновление списка…",
	"StationListTab" : "Список радиостанции",
	"VrHelp_DABSettings" : "Настройки DAB",
	"VrHelp_Entertainment" : "Развлечения",
	"VrHelp_Favorites" : "Избранное",
	"VrHelp_Next" : "Следующий ",
	"VrHelp_Previous" : "Предыдущий ",
	"VrHelp_Scan" : "Сканировать",
	"VrHelp_SoundSettings" : "Настройки звука",
	"VrHelp_StationList" : "Cписок станций",
	"VrHelp_TrafficAnnouncement" : "Контроль трафика",
};

framework.registerAppDictLoaded("dab", "ru_RU");