var Localization_dabAppDict_ja_JP = {
	//"stringId" : "localString"
	"DABAnalog" : "アナログ",
	"DABBandIII" : "バンドIII",
	"DABBandSettingsList" : "バンド設定",
	"DABBandSettingsTitle" : "バンド設定",
	"DABBoth" : "両方",
	"DABChangeEnsemble" : "アンサンブルを変更してください",
	"DABDABLink" : "DAB-DABリンク",
	"DABDigital" : "デジタル",
	"DABEnsembleList" : "アンサンブルを選択",
	"DABEnsembleListTitle" : "アンサンブルを選択",
	"DABEnsembleListTitle2" : "アンサンブルを選択",
	"DABEnsembleListUpdateComplete" : "アンサンブルリストを更新しました",
	"DABFMLink" : "DAB-FMリンク",
	"DABLBand" : "Lバンド",
	"DABListNotAvailable" : "放送局は使用できません",
	"DABNoResultsFound" : "放送局が見つかりませんでした",
	"DABNoSignal" : "信号がありません",
	"DABPleaseUpdateList" : "リストを更新してください",
	"DABRadio" : "DAB ラジオ",
	"DABRadioText" : "文字放送",
	"DABSelectEnsemble" : "アンサンブルを選択",
	"DABSettings" : "DAB 設定",
	"DABSettingsListTitle" : "設定",
	"DABSettingsNowPlaying" : "DAB 設定",
	"DABSignalLost" : "{ChNum} 信号エラー",
	"DABSignalSearch" : "検索中...",
	"DABStationListUpdateFailedSelect" : "放送局の更新に失敗しました",
	"DABStationListUpdated" : "放送局を更新しました",
	"DABStatusBarTitle" : "DAB",
	"DABTrafficAlertOff" : "交通情報オフ",
	"DABTrafficAlertOn" : "交通情報オン",
	"DABUnableToUpdateStationList" : "放送局の更新に失敗しました。",
	"DABUpdate" : "更新",
	"DABUpdateEnsemble" : "リストを更新しますか？",
	"DABUpdateEnsembleList" : "アンサンブルリストを更新",
	"DABUpdateList" : "リストを更新",
	"DABUpdateStation" : "放送局を更新しますか？",
	"DABUpdatingEnsembleList" : "アンサンブルリストを更新中です",
	"DABUpdatingList" : "リスト更新中…",
	"DABUpdatingListNowPlaying" : "リスト更新中…",
	"StationListTab" : "放送局",
	"VrHelp_DABSettings" : "DAB Settings",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_Favorites" : "Favorites",
	"VrHelp_Next" : "Next",
	"VrHelp_Previous" : "Previous",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement",
};

framework.registerAppDictLoaded("dab", "ja_JP");