var Localization_dabAppDict_pl_PL = {
	//"stringId" : "localString"
	"DABAnalog" : "Analogowe",
	"DABBandIII" : "Pasmo Ⅲ",
	"DABBandSettingsList" : "Ustawienia PASMA",
	"DABBandSettingsTitle" : "Ustawienia PASMA",
	"DABBoth" : "Obydwa",
	"DABChangeEnsemble" : "Proszę zmienić zespół",
	"DABDABLink" : "Łącze DAB-DAB",
	"DABDigital" : "Cyfrowe",
	"DABEnsembleList" : "Grupa stacji",
	"DABEnsembleListTitle" : "Wybierz zestaw",
	"DABEnsembleListTitle2" : "Grupa stacji",
	"DABEnsembleListUpdateComplete" : "Lista zespołów zaktualizowana",
	"DABFMLink" : "Łącze DAB-FM",
	"DABLBand" : "Pasmo L",
	"DABListNotAvailable" : "Lista stacji niedostępna",
	"DABNoResultsFound" : "Nie znaleziono wyników.",
	"DABNoSignal" : "Brak sygnału",
	"DABPleaseUpdateList" : "Proszę zaktualizować listę",
	"DABRadio" : "Radio DAB",
	"DABRadioText" : "Funkcja Radio Text",
	"DABSelectEnsemble" : "Wybierz zestaw",
	"DABSettings" : "Ustawienia DAB",
	"DABSettingsListTitle" : "Ustawienia",
	"DABSettingsNowPlaying" : "Ustawienia DAB",
	"DABSignalLost" : "Utrata sygnału {ChNum}",
	"DABSignalSearch" : "Wyszukiwanie…",
	"DABStationListUpdateFailedSelect" : "Nie udało się zaktualiz. listy stacji",
	"DABStationListUpdated" : "Zaktualizowano listę stacji",
	"DABStatusBarTitle" : "DAB",
	"DABTrafficAlertOff" : "Wyłącz komunikat drogowy",
	"DABTrafficAlertOn" : "Włącz komunikat drogowy",
	"DABUnableToUpdateStationList" : "Nie udało zaktualizować.",
	"DABUpdate" : "Akutalizuj",
	"DABUpdateEnsemble" : "Zaktualizować listę zespołów?",
	"DABUpdateEnsembleList" : "Zaktualizuj listę zespołów",
	"DABUpdateList" : "Zaktualizować listę",
	"DABUpdateStation" : "Zaktualizować listę stacji?",
	"DABUpdatingEnsembleList" : "Aktualizacja listy zespołów",
	"DABUpdatingList" : "Aktualizacja listy…",
	"DABUpdatingListNowPlaying" : "Aktualizacja listy…",
	"StationListTab" : "Lista stacji",
	"VrHelp_DABSettings" : "DAB Settings",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_Favorites" : "Favourites",
	"VrHelp_Next" : "Next",
	"VrHelp_Previous" : "Previous",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement  (TA)",
};

framework.registerAppDictLoaded("dab", "pl_PL");