var Localization_dabAppDict_no_NO = {
	//"stringId" : "localString"
	"DABAnalog" : "Analog",
	"DABBandIII" : "Bånd III",
	"DABBandSettingsList" : "BÅND-innstillinger",
	"DABBandSettingsTitle" : "BÅND-innstillinger",
	"DABBoth" : "Begge",
	"DABChangeEnsemble" : "Vennligst velg annet ensemble",
	"DABDABLink" : "DAB-DAB-link",
	"DABDigital" : "Digital",
	"DABEnsembleList" : "Ensemble-oversikt",
	"DABEnsembleListTitle" : "Velg Ensemble",
	"DABEnsembleListTitle2" : "Ensemble-oversikt",
	"DABEnsembleListUpdateComplete" : "Ensemble-listen er oppdatert",
	"DABFMLink" : "DAB-FM-link",
	"DABLBand" : "L-bånd",
	"DABListNotAvailable" : "Stasjonsliste ikke tilgjengelig",
	"DABNoResultsFound" : "Fant ingen resultater",
	"DABNoSignal" : "Ingen signal",
	"DABPleaseUpdateList" : "Vennligst oppdater liste",
	"DABRadio" : "DAB radio",
	"DABRadioText" : "Radiotekst",
	"DABSelectEnsemble" : "Velg Ensemble",
	"DABSettings" : "DAB-innstillinger",
	"DABSettingsListTitle" : "Innstillinger",
	"DABSettingsNowPlaying" : "DAB Innstillinger",
	"DABSignalLost" : "Tapt {ChNum}signal",
	"DABSignalSearch" : "Søker…",
	"DABStationListUpdateFailedSelect" : "Kan ikke oppdatere stasjonsliste",
	"DABStationListUpdated" : "Stasjonsliste oppdatert",
	"DABStatusBarTitle" : "DAB",
	"DABTrafficAlertOff" : "Trafikkmelding (TA) av",
	"DABTrafficAlertOn" : "Trafikkmelding (TA) på",
	"DABUnableToUpdateStationList" : "Kan ikke oppdatere",
	"DABUpdate" : "Oppdater",
	"DABUpdateEnsemble" : "Ønsker du å oppdatere ensemble-liste?",
	"DABUpdateEnsembleList" : "Velg Ensemble",
	"DABUpdateList" : "Oppdater liste",
	"DABUpdateStation" : "Oppdatere stasjonsliste?",
	"DABUpdatingEnsembleList" : "Oppdaterer ensemble-liste",
	"DABUpdatingList" : "Oppdaterer liste…",
	"DABUpdatingListNowPlaying" : "Oppdaterer liste…",
	"StationListTab" : "Stasjonsliste",
	"VrHelp_DABSettings" : "DAB Settings",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_Favorites" : "Favourites",
	"VrHelp_Next" : "Next",
	"VrHelp_Previous" : "Previous",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement  (TA)",
};

framework.registerAppDictLoaded("dab", "no_NO");