var Localization_dabAppDict_sv_SE = {
	//"stringId" : "localString"
	"DABAnalog" : "Analog",
	"DABBandIII" : "Band Ⅲ",
	"DABBandSettingsList" : "BAND-inställningar",
	"DABBandSettingsTitle" : "BAND-inställningar",
	"DABBoth" : "Båda",
	"DABChangeEnsemble" : "Ändra ensemblelista",
	"DABDABLink" : "DAB-DAB-länk",
	"DABDigital" : "Digital",
	"DABEnsembleList" : "Ensemblelista",
	"DABEnsembleListTitle" : "Välj Ensemble",
	"DABEnsembleListTitle2" : "Ensemblelista",
	"DABEnsembleListUpdateComplete" : "Ensemblelista uppdaterad",
	"DABFMLink" : "DAB-FM-länk",
	"DABLBand" : "L-band",
	"DABListNotAvailable" : "Stationslista inte tillgänglig",
	"DABNoResultsFound" : "Hittade inga resultat",
	"DABNoSignal" : "Ingen signal",
	"DABPleaseUpdateList" : "Uppdatera lista",
	"DABRadio" : "DAB Radio",
	"DABRadioText" : "Radiotext",
	"DABSelectEnsemble" : "Välj Ensemble",
	"DABSettings" : "DAB Inställningar",
	"DABSettingsListTitle" : "Inställningar",
	"DABSettingsNowPlaying" : "DAB Inställningar",
	"DABSignalLost" : "{ChNum} Ingen signal",
	"DABSignalSearch" : "Sök…",
	"DABStationListUpdateFailedSelect" : "Går inte att uppdatera listan",
	"DABStationListUpdated" : "Kanallista uppdaterad",
	"DABStatusBarTitle" : "DAB",
	"DABTrafficAlertOff" : "Trafikvarning (TA) av",
	"DABTrafficAlertOn" : "Trafikvarning (TA) på",
	"DABUnableToUpdateStationList" : "Går inte att uppdatera",
	"DABUpdate" : "Uppdatera",
	"DABUpdateEnsemble" : "Uppdatera ensemblelista?",
	"DABUpdateEnsembleList" : "Uppdatera ensemblelista",
	"DABUpdateList" : "Uppdatera lista",
	"DABUpdateStation" : "Uppdatera kanallista?",
	"DABUpdatingEnsembleList" : "Uppdaterar ensemblelista",
	"DABUpdatingList" : "Uppdaterar lista…",
	"DABUpdatingListNowPlaying" : "Uppdaterar lista…",
	"StationListTab" : "Stationslista",
	"VrHelp_DABSettings" : "DAB Inställningar",
	"VrHelp_Entertainment" : "Underhållning",
	"VrHelp_Favorites" : "Favoriter",
	"VrHelp_Next" : "Nästa",
	"VrHelp_Previous" : "Föregående",
	"VrHelp_Scan" : "Sök",
	"VrHelp_SoundSettings" : "Ljudinställningar",
	"VrHelp_StationList" : "Stationslista",
	"VrHelp_TrafficAnnouncement" : "Trafikvarning (TA)",
};

framework.registerAppDictLoaded("dab", "sv_SE");