var Localization_dabAppDict_ar_SA = {
	//"stringId" : "localString"
	"DABAnalog" : "تناظرية",
	"DABBandIII" : "النطاق III",
	"DABBandSettingsList" : "إعدادات النطاق",
	"DABBandSettingsTitle" : "إعدادات النطاق",
	"DABBoth" : "الاثنان معًا",
	"DABChangeEnsemble" : "الرجاء تغيير المجموعة",
	"DABDABLink" : "رابط DAB-DAB",
	"DABDigital" : "رقمية",
	"DABEnsembleList" : "اختر المجموعة",
	"DABEnsembleListTitle" : "اختر مجموعة",
	"DABEnsembleListTitle2" : "قائمة المجموعات",
	"DABEnsembleListUpdateComplete" : "تم تحديث المجموعة",
	"DABFMLink" : "رابط DAB-FM",
	"DABLBand" : "النطاق L",
	"DABListNotAvailable" : "قائمة المحطات غير متوفرة",
	"DABNoResultsFound" : "لم يتم العثور على نتائج",
	"DABNoSignal" : "لا توجد إشارة",
	"DABPleaseUpdateList" : "الرجاء تحديث القائمة",
	"DABRadio" : "راديو DAB\n",
	"DABRadioText" : "النصوص الإذاعية",
	"DABSelectEnsemble" : "اختر مجموعة",
	"DABSettings" : "إعدادات DAB",
	"DABSettingsListTitle" : "إعدادات",
	"DABSettingsNowPlaying" : "إعدادات",
	"DABSignalLost" : "{ChNum}  الإشارة المفقودة",
	"DABSignalSearch" : "جارٍ البحث عن إشارة…",
	"DABStationListUpdateFailedSelect" : "فشل تحديث قائمة المحطات",
	"DABStationListUpdated" : "تحديث قائمة المحطات",
	"DABStatusBarTitle" : "DAB",
	"DABTrafficAlertOff" : "إيقاف تنبيه التنقل",
	"DABTrafficAlertOn" : "تشغيل تنبيه التنقل",
	"DABUnableToUpdateStationList" : "فشل تحديث قائمة المحطات",
	"DABUpdate" : "تحديث",
	"DABUpdateEnsemble" : "الإذاعية غير متاحة. هل تريد تحديثها؟",
	"DABUpdateEnsembleList" : "تحديث قائمة المجموعة",
	"DABUpdateList" : "تحديث القائمة",
	"DABUpdateStation" : "تحديث قائمة المحطات؟",
	"DABUpdatingEnsembleList" : "جارٍ تحديث قائمة المجموعة",
	"DABUpdatingList" : "تحديث القائمة…",
	"DABUpdatingListNowPlaying" : "تحديث القائمة…",
	"StationListTab" : "قائمة المحطات",
	"VrHelp_DABSettings" : "إعدادات DAB",
	"VrHelp_Entertainment" : "ترفيه",
	"VrHelp_Favorites" : "المفضلات",
	"VrHelp_Next" : "التالي",
	"VrHelp_Previous" : "السابق",
	"VrHelp_Scan" : "المسح الضوئي",
	"VrHelp_SoundSettings" : "إعدادات الصوت",
	"VrHelp_StationList" : "قائمة المحطة",
	"VrHelp_TrafficAnnouncement" : "تنبيه التنقل",
};

framework.registerAppDictLoaded("dab", "ar_SA");