var Localization_dabAppDict_fi_FI = {
	//"stringId" : "localString"
	"DABAnalog" : "Analoginen",
	"DABBandIII" : "Kaista Ⅲ",
	"DABBandSettingsList" : "KAISTA-asetukset",
	"DABBandSettingsTitle" : "KAISTA-asetukset",
	"DABBoth" : "Molemmat",
	"DABChangeEnsemble" : "Vaihda yhdistelmä",
	"DABDABLink" : "DAB-DAB-yhteys",
	"DABDigital" : "Digitaalinen",
	"DABEnsembleList" : "Valitse esittäjä",
	"DABEnsembleListTitle" : "Valitse yhdistelmä",
	"DABEnsembleListTitle2" : "Yhdistelmäluettelo",
	"DABEnsembleListUpdateComplete" : "Esittäjäluettelo päivitetty",
	"DABFMLink" : "DAB-FM-yhteys",
	"DABLBand" : "L-kaista",
	"DABListNotAvailable" : "Asemaluettelo ei saatavilla",
	"DABNoResultsFound" : "Ei tuloksia",
	"DABNoSignal" : "Ei signaalia",
	"DABPleaseUpdateList" : "Päivitä luettelo",
	"DABRadio" : "DAB radio",
	"DABRadioText" : "Radioteksti",
	"DABSelectEnsemble" : "Valitse yhdistelmä",
	"DABSettings" : "DAB-asetukset",
	"DABSettingsListTitle" : "Asetukset",
	"DABSettingsNowPlaying" : "DAB-asetukset",
	"DABSignalLost" : "{ChNum} Signaali katkesi",
	"DABSignalSearch" : "Etsii…",
	"DABStationListUpdateFailedSelect" : "Asemaluettelo päivitys epäonnistui",
	"DABStationListUpdated" : "Kanavaluettelo päivitetty",
	"DABStatusBarTitle" : "DAB",
	"DABTrafficAlertOff" : "Liikennetiedote (TA) pois päältä",
	"DABTrafficAlertOn" : "Liikennetiedote (TA) päälle",
	"DABUnableToUpdateStationList" : "Luettelo ei päivity",
	"DABUpdate" : "Päivitä",
	"DABUpdateEnsemble" : "Päivitetäänkö yhdistelmä?",
	"DABUpdateEnsembleList" : "Päivitä esittäjäluettelo",
	"DABUpdateList" : "Päivitä luettelo",
	"DABUpdateStation" : "Päivitä kanavaluettelo?",
	"DABUpdatingEnsembleList" : "Päivittää esittäjäluetteloa",
	"DABUpdatingList" : "Päivityslista…",
	"DABUpdatingListNowPlaying" : "Päivityslista…",
	"StationListTab" : "Kanavaluettelo",
	"VrHelp_DABSettings" : "DAB-asetukset",
	"VrHelp_Entertainment" : "Viihde",
	"VrHelp_Favorites" : "Suosikit",
	"VrHelp_Next" : "Seuraava",
	"VrHelp_Previous" : "Edellinen",
	"VrHelp_Scan" : "Haku",
	"VrHelp_SoundSettings" : "Ääniasetukset",
	"VrHelp_StationList" : "Kanavaluettelo",
	"VrHelp_TrafficAnnouncement" : "Liikennetiedote (TA)",
};

framework.registerAppDictLoaded("dab", "fi_FI");