var Localization_dabAppDict_pt_BR = {
	//"stringId" : "localString"
	"DABAnalog" : "Analógico",
	"DABBandIII" : "Banda III",
	"DABBandSettingsList" : "Configurações de banda",
	"DABBandSettingsTitle" : "Configurações de banda",
	"DABBoth" : "Ambos",
	"DABChangeEnsemble" : "Por favor, mude o conjunto",
	"DABDABLink" : "Link DAB-DAB",
	"DABDigital" : "Digital",
	"DABEnsembleList" : "Lista de conjuntos",
	"DABEnsembleListTitle" : "Selecionar conjunto",
	"DABEnsembleListTitle2" : "Lista de conjuntos",
	"DABEnsembleListUpdateComplete" : "Lista de conjuntos atualizada",
	"DABFMLink" : "Link DAB-FM",
	"DABLBand" : "Banda L",
	"DABListNotAvailable" : "Lista de estações não disponível",
	"DABNoResultsFound" : "Nenhum resultado encontrado",
	"DABNoSignal" : "Sem sinal",
	"DABPleaseUpdateList" : "Por favor, atualize a lista",
	"DABRadio" : "Rádio DAB",
	"DABRadioText" : "Texto da rádio",
	"DABSelectEnsemble" : "Selecionar conjunto",
	"DABSettings" : "Configurações DAB",
	"DABSettingsListTitle" : "Configurações",
	"DABSettingsNowPlaying" : "Configurações",
	"DABSignalLost" : "Sinal {ChNum} perdido",
	"DABSignalSearch" : "Pesquisando. . .",
	"DABStationListUpdateFailedSelect" : "Não é possível atualizar lista est.",
	"DABStationListUpdated" : "Lista de estações atualizada",
	"DABStatusBarTitle" : "DAB",
	"DABTrafficAlertOff" : "Anúncio de Tráfego (TA) desligado",
	"DABTrafficAlertOn" : "Anúncio de Tráfego (TA) ligado",
	"DABUnableToUpdateStationList" : "Não é possível atual. lista",
	"DABUpdate" : "Atualizar",
	"DABUpdateEnsemble" : "Atualizar lista de conjuntos?",
	"DABUpdateEnsembleList" : "Atualizar lista de conjuntos",
	"DABUpdateList" : "Atualizar lista",
	"DABUpdateStation" : "Atualizar lista de estações?",
	"DABUpdatingEnsembleList" : "Atualizando lista de conjuntos",
	"DABUpdatingList" : "Atualizando lista...",
	"DABUpdatingListNowPlaying" : "Atualizando lista...",
	"StationListTab" : "Lista de estações",
	"VrHelp_DABSettings" : "DAB Settings",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_Favorites" : "Favorites",
	"VrHelp_Next" : "Next",
	"VrHelp_Previous" : "Previous",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement",
};

framework.registerAppDictLoaded("dab", "pt_BR");