var Localization_dabAppDict_en_UK = {
	//"stringId" : "localString"
	"DABAnalog" : "Analog",
	"DABBandIII" : "Band III",
	"DABBandSettingsList" : "BAND Settings",
	"DABBandSettingsTitle" : "BAND Settings",
	"DABBoth" : "Both",
	"DABChangeEnsemble" : "Please change the Ensemble",
	"DABDABLink" : "DAB-DAB Link",
	"DABDigital" : "Digital",
	"DABEnsembleList" : "Ensemble List",
	"DABEnsembleListTitle" : "Select Ensemble",
	"DABEnsembleListTitle2" : "Ensemble List",
	"DABEnsembleListUpdateComplete" : "Ensemble List Updated",
	"DABFMLink" : "DAB-FM Link",
	"DABLBand" : "L Band",
	"DABListNotAvailable" : "Station List Not Available",
	"DABNoResultsFound" : "No results found",
	"DABNoSignal" : "No Signal",
	"DABPleaseUpdateList" : "Please update list",
	"DABRadio" : "DAB Radio",
	"DABRadioText" : "Radio Text",
	"DABSelectEnsemble" : "Select Ensemble",
	"DABSettings" : "DAB Settings",
	"DABSettingsListTitle" : "Settings",
	"DABSettingsNowPlaying" : "DAB Settings",
	"DABSignalLost" : "{ChNum} Signal Lost",
	"DABSignalSearch" : "Searching…",
	"DABStationListUpdateFailedSelect" : "Unable To Update Station List",
	"DABStationListUpdated" : "Station List Updated",
	"DABStatusBarTitle" : "DAB",
	"DABTrafficAlertOff" : "Traffic Announcement  (TA) Off",
	"DABTrafficAlertOn" : "Traffic Announcement  (TA) On",
	"DABUnableToUpdateStationList" : "Unable To Update List",
	"DABUpdate" : "Update",
	"DABUpdateEnsemble" : "Update Ensemble List?",
	"DABUpdateEnsembleList" : "Update Ensemble List",
	"DABUpdateList" : "Update List",
	"DABUpdateStation" : "Update Station List?",
	"DABUpdatingEnsembleList" : "Updating Ensemble list",
	"DABUpdatingList" : "Updating List...",
	"DABUpdatingListNowPlaying" : "Updating List...",
	"StationListTab" : "Station List",
	"VrHelp_DABSettings" : "DAB Settings",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_Favorites" : "Favourites",
	"VrHelp_Next" : "Next",
	"VrHelp_Previous" : "Previous",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement  (TA)",
};

framework.registerAppDictLoaded("dab", "en_UK");