var Localization_dabAppDict_ro_RO = {
	//"stringId" : "localString"
	"DABAnalog" : "Analog",
	"DABBandIII" : "Banda Ⅲ",
	"DABBandSettingsList" : "Setări BANDĂ",
	"DABBandSettingsTitle" : "Setări BANDĂ",
	"DABBoth" : "Ambele",
	"DABChangeEnsemble" : "Vă rugăm schimbaţi ansamblul",
	"DABDABLink" : "Legătură DAB-DAB",
	"DABDigital" : "Digital",
	"DABEnsembleList" : "Listă ansamblu",
	"DABEnsembleListTitle" : "Selectaţi ansamblul",
	"DABEnsembleListTitle2" : "Listă ansamblu",
	"DABEnsembleListUpdateComplete" : "Lista anslamblu actualilzată",
	"DABFMLink" : "Legătură DAB-FM",
	"DABLBand" : "Banda L",
	"DABListNotAvailable" : "Listă de posturi indisponibilă",
	"DABNoResultsFound" : "Nu s-au găsit rezultate",
	"DABNoSignal" : "Fără semnal",
	"DABPleaseUpdateList" : "Vă rugăm actualizaţi lista",
	"DABRadio" : "Radio DAB",
	"DABRadioText" : "Text radio",
	"DABSelectEnsemble" : "Selectaţi ansamblul",
	"DABSettings" : "Setări DAB",
	"DABSettingsListTitle" : "Setări",
	"DABSettingsNowPlaying" : "Setări DAB",
	"DABSignalLost" : "Semnal {ChNum} întrerupt",
	"DABSignalSearch" : "Căutare…",
	"DABStationListUpdateFailedSelect" : "Actualizare listă posturi nereușită",
	"DABStationListUpdated" : "Listă de posturi actualizată",
	"DABStatusBarTitle" : "DAB",
	"DABTrafficAlertOff" : "Informaţii trafic oprite",
	"DABTrafficAlertOn" : "Informaţii trafic pornite",
	"DABUnableToUpdateStationList" : "Actualizare listă nereușită",
	"DABUpdate" : "Actualizare",
	"DABUpdateEnsemble" : "Actualizare listă ansamblu?",
	"DABUpdateEnsembleList" : "Actualizare listă ansamblu",
	"DABUpdateList" : "Actualizaţi lista",
	"DABUpdateStation" : "Actualizați lista de posturi?",
	"DABUpdatingEnsembleList" : "Se actualizează lista ansamblu",
	"DABUpdatingList" : "Actualizare listă...",
	"DABUpdatingListNowPlaying" : "Actualizare listă...",
	"StationListTab" : "Listă de posturi",
	"VrHelp_DABSettings" : "DAB Settings",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_Favorites" : "Favourites",
	"VrHelp_Next" : "Next",
	"VrHelp_Previous" : "Previous",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement  (TA)",
};

framework.registerAppDictLoaded("dab", "ro_RO");