var Localization_dabAppDict_lv_LV = {
	//"stringId" : "localString"
	"DABAnalog" : "Analogs",
	"DABBandIII" : "Frekvenču josla III",
	"DABBandSettingsList" : "FREKV. JOSLAS iest.",
	"DABBandSettingsTitle" : "FREKV. JOSLAS iest.",
	"DABBoth" : "Abas",
	"DABChangeEnsemble" : "Lūdzu, nomainiet ansambli",
	"DABDABLink" : "DAB-DAB saite",
	"DABDigital" : "Digitāls",
	"DABEnsembleList" : "Ansambļu saraksts",
	"DABEnsembleListTitle" : "Atlasīt ansambli",
	"DABEnsembleListTitle2" : "Ansambļu saraksts",
	"DABEnsembleListUpdateComplete" : "Ansambļu saraksts ir atjaunots",
	"DABFMLink" : "DAB-FM saite",
	"DABLBand" : "L frekvenču josla",
	"DABListNotAvailable" : "Staciju saraksts nav pieejams",
	"DABNoResultsFound" : "Nav atrasts neviens rezultāts",
	"DABNoSignal" : "Nav signāla",
	"DABPleaseUpdateList" : "Lūdzu, atjaunojiet sarakstu",
	"DABRadio" : "DAB Radio",
	"DABRadioText" : "Radio teksts",
	"DABSelectEnsemble" : "Atlasīt ansambli",
	"DABSettings" : "DAB iestatījumi",
	"DABSettingsListTitle" : "Iestatījumi",
	"DABSettingsNowPlaying" : "DAB iestatījumi",
	"DABSignalLost" : "{ChNum} signāls zaudēts",
	"DABSignalSearch" : "Meklē…",
	"DABStationListUpdateFailedSelect" : "Nevar atjaunināt staciju sarakstu",
	"DABStationListUpdated" : "Staciju saraksts atjaunināts",
	"DABStatusBarTitle" : "DAB",
	"DABTrafficAlertOff" : "Satiksmes paziņojums (TA) izslēgts",
	"DABTrafficAlertOn" : "Satiksmes paziņojums (TA) ieslēgts",
	"DABUnableToUpdateStationList" : "Nevar atjaunināt sarakstu",
	"DABUpdate" : "Atjaunot",
	"DABUpdateEnsemble" : "Atjaunot ansambļu sarakstu?",
	"DABUpdateEnsembleList" : "Atjaunojiet ansambļu sarakstu",
	"DABUpdateList" : "Atjaunojiet sarakstu",
	"DABUpdateStation" : "Vai atjaunināt staciju sarakstu?",
	"DABUpdatingEnsembleList" : "Atjauno ansambļu sarakstu",
	"DABUpdatingList" : "Saraksta atjaunināšana…",
	"DABUpdatingListNowPlaying" : "Saraksta atjaunināšana…",
	"StationListTab" : "Staciju saraksts",
	"VrHelp_DABSettings" : "DAB Settings",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_Favorites" : "Favorites",
	"VrHelp_Next" : "Next",
	"VrHelp_Previous" : "Previous",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement  (TA)",
};

framework.registerAppDictLoaded("dab", "lv_LV");