var Localization_dabAppDict_et_EE = {
	//"stringId" : "localString"
	"DABAnalog" : "Analoog",
	"DABBandIII" : "Laineala Ⅲ",
	"DABBandSettingsList" : "Laineala seaded",
	"DABBandSettingsTitle" : "Laineala seaded",
	"DABBoth" : "Mõlemad",
	"DABChangeEnsemble" : "Palun muuda ansamblit",
	"DABDABLink" : "DAB-DAB-link",
	"DABDigital" : "Digitaalne",
	"DABEnsembleList" : "Ansamblite loend",
	"DABEnsembleListTitle" : "Vali ansambel",
	"DABEnsembleListTitle2" : "Ansambliloend",
	"DABEnsembleListUpdateComplete" : "Ansamblite loetelu on uuendatud",
	"DABFMLink" : "DAB-FM-link",
	"DABLBand" : "L-laineala",
	"DABListNotAvailable" : "Jaamaloend pole saadaval",
	"DABNoResultsFound" : "Tulemusi ei leitud",
	"DABNoSignal" : "Signaal puudub",
	"DABPleaseUpdateList" : "Palun uuenda loetelu",
	"DABRadio" : "DAB raadio",
	"DABRadioText" : "Raadio tekst",
	"DABSelectEnsemble" : "Vali ansambel",
	"DABSettings" : "DAB sätted",
	"DABSettingsListTitle" : "Sätted",
	"DABSettingsNowPlaying" : "DAB sätted",
	"DABSignalLost" : "{ChNum} Signaal kadus",
	"DABSignalSearch" : "Otsib…",
	"DABStationListUpdateFailedSelect" : "Jaamaloendi uuend. nurjus",
	"DABStationListUpdated" : "Jaamade loend uuendatud",
	"DABStatusBarTitle" : "DAB",
	"DABTrafficAlertOff" : "Liiklusteade  (TA)  väljas",
	"DABTrafficAlertOn" : "Liiklusteade  (TA)  sees",
	"DABUnableToUpdateStationList" : "Jaamaloendi uuend. nurjus",
	"DABUpdate" : "Uuenda",
	"DABUpdateEnsemble" : "Kas tahad ansamblite loetelu uuendada?",
	"DABUpdateEnsembleList" : "Uuenda ansamblite loetelu",
	"DABUpdateList" : "Uuenda loetelu",
	"DABUpdateStation" : "Uuendada jaamade loend?",
	"DABUpdatingEnsembleList" : "Ansamblite loetelu uuendamine",
	"DABUpdatingList" : "Loendi uuendamine…",
	"DABUpdatingListNowPlaying" : "Loendi uuendamine…",
	"StationListTab" : "Jaamade loend",
	"VrHelp_DABSettings" : "DAB Settings",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_Favorites" : "Favourites",
	"VrHelp_Next" : "Next",
	"VrHelp_Previous" : "Previous",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement  (TA)",
};

framework.registerAppDictLoaded("dab", "et_EE");