var Localization_dabAppDict_da_DK = {
	//"stringId" : "localString"
	"DABAnalog" : "Analog",
	"DABBandIII" : "Band III",
	"DABBandSettingsList" : "BAND-indstillinger",
	"DABBandSettingsTitle" : "BAND-indstillinger",
	"DABBoth" : "Begge",
	"DABChangeEnsemble" : "Skift til Ensemble",
	"DABDABLink" : "DAB-DAB-link",
	"DABDigital" : "Digital",
	"DABEnsembleList" : "Ensemble-liste",
	"DABEnsembleListTitle" : "Vælg Ensemble",
	"DABEnsembleListTitle2" : "Ensemble liste",
	"DABEnsembleListUpdateComplete" : "Listen Ensemble opdateret",
	"DABFMLink" : "DAB-FM-link",
	"DABLBand" : "L-band",
	"DABListNotAvailable" : "Stationsliste er ikke tilgængelig",
	"DABNoResultsFound" : "Ingen resultater fundet",
	"DABNoSignal" : "Intet signal",
	"DABPleaseUpdateList" : "Opdater liste",
	"DABRadio" : "DAB radio",
	"DABRadioText" : "Radiotekst",
	"DABSelectEnsemble" : "Vælg Ensemble",
	"DABSettings" : "DAB-Indstillinger",
	"DABSettingsListTitle" : "DAB-Indstillinger",
	"DABSettingsNowPlaying" : "DAB-indstillinger",
	"DABSignalLost" : "{ChNum} Signal er tabt",
	"DABSignalSearch" : "Søger…",
	"DABStationListUpdateFailedSelect" : "Kunne ikke opdatere stationslisten",
	"DABStationListUpdated" : "Stationsliste blev opdateret",
	"DABStatusBarTitle" : "DAB",
	"DABTrafficAlertOff" : "Trafikvarsel (TA) fra",
	"DABTrafficAlertOn" : "Trafikvarsel (TA) til",
	"DABUnableToUpdateStationList" : "Opdatering af liste mislykk",
	"DABUpdate" : "Opdater",
	"DABUpdateEnsemble" : "Opdater listen Ensemble?",
	"DABUpdateEnsembleList" : "Opdater listen Ensemble",
	"DABUpdateList" : "Opdatér liste",
	"DABUpdateStation" : "Vil du opdatere stationsliste?",
	"DABUpdatingEnsembleList" : "Opdaterer listen Ensemble",
	"DABUpdatingList" : "Opdaterer liste…",
	"DABUpdatingListNowPlaying" : "Opdaterer liste…",
	"StationListTab" : "Stationsliste",
	"VrHelp_DABSettings" : "DAB-Indstillinger",
	"VrHelp_Entertainment" : "Underholdning",
	"VrHelp_Favorites" : "Favoritter",
	"VrHelp_Next" : "Næste",
	"VrHelp_Previous" : "Forrige ",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SoundSettings" : "LydIndstillinger",
	"VrHelp_StationList" : "Stationsliste",
	"VrHelp_TrafficAnnouncement" : "Trafikvarsel (TA)",
};

framework.registerAppDictLoaded("dab", "da_DK");