var Localization_dabAppDict_nl_NL = {
	//"stringId" : "localString"
	"DABAnalog" : "Analoog",
	"DABBandIII" : "Band Ⅲ",
	"DABBandSettingsList" : "BAND-instellingen",
	"DABBandSettingsTitle" : "BAND-instellingen",
	"DABBoth" : "Beide",
	"DABChangeEnsemble" : "Wijzig het Ensemble.",
	"DABDABLink" : "DAB-DAB-koppeling",
	"DABDigital" : "Digitaal",
	"DABEnsembleList" : "Ensemblelijst",
	"DABEnsembleListTitle" : "Selecteer Ensemble",
	"DABEnsembleListTitle2" : "Ensemblelijst",
	"DABEnsembleListUpdateComplete" : "Bijwerken Ensemblelijst gereed",
	"DABFMLink" : "DAB-FM-koppeling",
	"DABLBand" : "L-band",
	"DABListNotAvailable" : "Zenderlijst niet beschikbaar",
	"DABNoResultsFound" : "Geen resultaten gevonden",
	"DABNoSignal" : "Geen signaal",
	"DABPleaseUpdateList" : "Werk lijst bij.",
	"DABRadio" : "DAB radio",
	"DABRadioText" : "Radiotekst",
	"DABSelectEnsemble" : "Selecteer Ensemble",
	"DABSettings" : "DAB-instellingen",
	"DABSettingsListTitle" : "DAB-Instellingen",
	"DABSettingsNowPlaying" : "DAB-instellingen",
	"DABSignalLost" : "{ChNum} Signaal verbroken",
	"DABSignalSearch" : "Bezig met zoeken…",
	"DABStationListUpdateFailedSelect" : "Niet in staat zenderlijst te updaten",
	"DABStationListUpdated" : "Updaten zenderlijst gereed",
	"DABStatusBarTitle" : "DAB",
	"DABTrafficAlertOff" : "Verkeerswaarschuwing (TA) Uit",
	"DABTrafficAlertOn" : "Verkeerswaarschuwing (TA) Aan",
	"DABUnableToUpdateStationList" : "Niet in staat te updaten",
	"DABUpdate" : "Bijwerken",
	"DABUpdateEnsemble" : "Ensemblelijst bijwerken?",
	"DABUpdateEnsembleList" : "Werk Ensemblelijst bij.",
	"DABUpdateList" : "Updatelijst",
	"DABUpdateStation" : "Zenderlijst updaten?",
	"DABUpdatingEnsembleList" : "Bezig met bijwerken Ensemblelijst",
	"DABUpdatingList" : "Bezig met updaten lijst…",
	"DABUpdatingListNowPlaying" : "Bezig met updaten lijst…",
	"StationListTab" : "Zenderlijst",
	"VrHelp_DABSettings" : "DAB-instellingen",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_Favorites" : "Favorieten",
	"VrHelp_Next" : "Volgende",
	"VrHelp_Previous" : "Vorige",
	"VrHelp_Scan" : "Scannen",
	"VrHelp_SoundSettings" : "Geluidsinstellingen",
	"VrHelp_StationList" : "Zenderlijst",
	"VrHelp_TrafficAnnouncement" : "Verkeerswaarschuwing (TA)",
};

framework.registerAppDictLoaded("dab", "nl_NL");