var Localization_dabAppDict_th_TH = {
	//"stringId" : "localString"
	"DABAnalog" : "อนาล็อก",
	"DABBandIII" : "ความถี่ III",
	"DABBandSettingsList" : "การตั้งค่าความถี่",
	"DABBandSettingsTitle" : "การตั้งค่าความถี่",
	"DABBoth" : "ทั้งสอง",
	"DABChangeEnsemble" : "โปรดเปลี่ยนวงดนตรี",
	"DABDABLink" : "ลิงก์ DAB-DAB",
	"DABDigital" : "ดิจิตอล",
	"DABEnsembleList" : "รายชื่อวงดนตรี",
	"DABEnsembleListTitle" : "เลือกวงดนตรี",
	"DABEnsembleListTitle2" : "รายชื่อวงดนตรี",
	"DABEnsembleListUpdateComplete" : "อัพเดตรายชื่อวงดนตรี",
	"DABFMLink" : "ลิงก์ DAB-FM",
	"DABLBand" : "ความถี่ L",
	"DABListNotAvailable" : "ไม่มีรายชื่อสถานี",
	"DABNoResultsFound" : "ไม่พบผลลัพธ์ที่ค้นหา",
	"DABNoSignal" : "ไม่มีสัญญาณ",
	"DABPleaseUpdateList" : "โปรดอัพเดตรายชื่อ",
	"DABRadio" : "วิทยุ DAB",
	"DABRadioText" : "ข้อความวิทยุ",
	"DABSelectEnsemble" : "เลือกวงดนตรี",
	"DABSettings" : "การตั้งค่า DAB",
	"DABSettingsListTitle" : "การตั้งค่า",
	"DABSettingsNowPlaying" : "การตั้งค่า",
	"DABSignalLost" : "{ChNum} สัญญาณขาดหาย",
	"DABSignalSearch" : "กำลังค้นหา...",
	"DABStationListUpdateFailedSelect" : "ไม่สามารถอัพเดตรายชื่อสถานี",
	"DABStationListUpdated" : "อัพเดตรายชื่อสถานีแล้ว",
	"DABStatusBarTitle" : "DAB",
	"DABTrafficAlertOff" : "ปิดการประกาศการจราจร (TA)",
	"DABTrafficAlertOn" : "เปิดการประกาศการจราจร (TA)",
	"DABUnableToUpdateStationList" : "ไม่สามารถอัพเดตรายชื่อได้",
	"DABUpdate" : "อัพเดต",
	"DABUpdateEnsemble" : "อัพเดตรายชื่อวงดนตรี?",
	"DABUpdateEnsembleList" : "อัพเดตรายชื่อวงดนตรี",
	"DABUpdateList" : "ปรับปรุงรายการ",
	"DABUpdateStation" : "อัพเดตรายชื่อสถานี?",
	"DABUpdatingEnsembleList" : "กำลังอัพเดตรายชื่อวงดนตรี",
	"DABUpdatingList" : "กำลังอัพเดตรายชื่อ...",
	"DABUpdatingListNowPlaying" : "กำลังอัพเดตรายชื่อ...",
	"StationListTab" : "รายการสถานี",
	"VrHelp_DABSettings" : "DAB Settings",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_Favorites" : "Favourites",
	"VrHelp_Next" : "Next",
	"VrHelp_Previous" : "Previous",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement (TA)",
};

framework.registerAppDictLoaded("dab", "th_TH");