var Localization_dabAppDict_it_IT = {
	//"stringId" : "localString"
	"DABAnalog" : "Analogico",
	"DABBandIII" : "Banda Ⅲ",
	"DABBandSettingsList" : "Impostazioni BANDA",
	"DABBandSettingsTitle" : "Impostazioni BANDA",
	"DABBoth" : "Entrambe",
	"DABChangeEnsemble" : "Si pr. di mod. l'elenco d'esecuzione",
	"DABDABLink" : "Colleg. DAB-DAB",
	"DABDigital" : "Digitale",
	"DABEnsembleList" : "Elenco d'esecuzione",
	"DABEnsembleListTitle" : "Seleziona esecuzione",
	"DABEnsembleListTitle2" : "Elenco d'esecuzione",
	"DABEnsembleListUpdateComplete" : "Elenco d'esecuzione aggiornato",
	"DABFMLink" : "Colleg. DAB-FM",
	"DABLBand" : "Banda L",
	"DABListNotAvailable" : "Elenco stazioni non disponibile",
	"DABNoResultsFound" : "Nessun risultato trovato.",
	"DABNoSignal" : "Nessun segnale",
	"DABPleaseUpdateList" : "Si prega di aggiornare l'elenco",
	"DABRadio" : "Radio DAB",
	"DABRadioText" : "Radiotesto",
	"DABSelectEnsemble" : "Seleziona esecuzione",
	"DABSettings" : "Impostazioni DAB",
	"DABSettingsListTitle" : "Impostazioni",
	"DABSettingsNowPlaying" : "Impostazioni DAB",
	"DABSignalLost" : "{ChNum} Segnale perso",
	"DABSignalSearch" : "Ricerca…",
	"DABStationListUpdateFailedSelect" : "Impossibile aggiornare elenco",
	"DABStationListUpdated" : "Elenco stazioni aggiornato",
	"DABStatusBarTitle" : "DAB",
	"DABTrafficAlertOff" : "Annuncio sul traffico (TA) spento",
	"DABTrafficAlertOn" : "Annuncio sul traffico (TA) acceso",
	"DABUnableToUpdateStationList" : "Impossibile aggiornare",
	"DABUpdate" : "Aggiorna",
	"DABUpdateEnsemble" : "Aggiornare elenco d'esecuzione?",
	"DABUpdateEnsembleList" : "Aggiorna elenco d'esecuzione",
	"DABUpdateList" : "Aggiorna elenco",
	"DABUpdateStation" : "Aggiornare elenco stazioni?",
	"DABUpdatingEnsembleList" : "Agg. elenco d'esecuzione in corso",
	"DABUpdatingList" : "Aggiornamento elenco in corso…",
	"DABUpdatingListNowPlaying" : "Aggiornamento elenco in corso…",
	"StationListTab" : "Elenco stazioni",
	"VrHelp_DABSettings" : "Impostazioni DAB",
	"VrHelp_Entertainment" : "Intrattenimento",
	"VrHelp_Favorites" : "Preferiti",
	"VrHelp_Next" : "Successivo",
	"VrHelp_Previous" : "Precedente",
	"VrHelp_Scan" : "Scansione",
	"VrHelp_SoundSettings" : "Impostazioni audio",
	"VrHelp_StationList" : "Elenco stazioni",
	"VrHelp_TrafficAnnouncement" : "Annuncio sul traffico (TA)",
};

framework.registerAppDictLoaded("dab", "it_IT");