var Localization_dabAppDict_tr_TR = {
	//"stringId" : "localString"
	"DABAnalog" : "Analog",
	"DABBandIII" : "Bant Ⅲ",
	"DABBandSettingsList" : "BANT Ayarları",
	"DABBandSettingsTitle" : "BANT Ayarları",
	"DABBoth" : "Her İkisi",
	"DABChangeEnsemble" : "Lütfen Grubu değiştirin",
	"DABDABLink" : "DAB-DAB Bağlantısı",
	"DABDigital" : "Dijital",
	"DABEnsembleList" : "Grup Listesi",
	"DABEnsembleListTitle" : "Grup Seç",
	"DABEnsembleListTitle2" : "Grup Listesi",
	"DABEnsembleListUpdateComplete" : "Grup Listesi Güncellendi",
	"DABFMLink" : "DAB-FM Bağlantısı",
	"DABLBand" : "L Bandı",
	"DABListNotAvailable" : "İstasyon Listesi Kullanılamıyor",
	"DABNoResultsFound" : "Sonuç bulunamadı",
	"DABNoSignal" : "Sinyal Yok",
	"DABPleaseUpdateList" : "Lütfen listeyi güncelleyin",
	"DABRadio" : "DAB Radyo",
	"DABRadioText" : "Radyo Metni",
	"DABSelectEnsemble" : "Grup Seç",
	"DABSettings" : "DAB Ayarları",
	"DABSettingsListTitle" : "Ayarlar",
	"DABSettingsNowPlaying" : "DAB Ayarları",
	"DABSignalLost" : "{ChNum} Sinyal Kaybedildi",
	"DABSignalSearch" : "Arıyor…",
	"DABStationListUpdateFailedSelect" : "İstasyon Listesi Güncellenemiyor",
	"DABStationListUpdated" : "İstasyon Listesi Güncellendi",
	"DABStatusBarTitle" : "DAB",
	"DABTrafficAlertOff" : "Trafik uyarısı (TA) Kapalı",
	"DABTrafficAlertOn" : "Trafik uyarısı (TA) Açık",
	"DABUnableToUpdateStationList" : "Listesi Güncellenemiyor",
	"DABUpdate" : "Güncelle",
	"DABUpdateEnsemble" : "Grup Listesi güncellensin mi?",
	"DABUpdateEnsembleList" : "Grup Listesini Güncelle",
	"DABUpdateList" : "Listeyi güncelleyin",
	"DABUpdateStation" : "İstasyon Listesi Güncellensin mi?",
	"DABUpdatingEnsembleList" : "Grup listesi güncelleniyor",
	"DABUpdatingList" : "Liste Güncelleniyor…",
	"DABUpdatingListNowPlaying" : "Liste Güncelleniyor…",
	"StationListTab" : "İstasyon Listesi",
	"VrHelp_DABSettings" : "DAB Settings",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_Favorites" : "Favourites",
	"VrHelp_Next" : "Next",
	"VrHelp_Previous" : "Previous",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement",
};

framework.registerAppDictLoaded("dab", "tr_TR");