var Localization_dabAppDict_he_IL = {
	//"stringId" : "localString"
	"DABAnalog" : "אנלוגי",
	"DABBandIII" : "רצועה Ⅲ",
	"DABBandSettingsList" : "הגדרות רצועה",
	"DABBandSettingsTitle" : "הגדרות רצועה",
	"DABBoth" : "שתיהן",
	"DABChangeEnsemble" : "אנא שנה את האנסמבל",
	"DABDABLink" : "קישור DAB-DAB",
	"DABDigital" : "דיגיטלי",
	"DABEnsembleList" : "רשימת אנסמבל",
	"DABEnsembleListTitle" : "רשימת אנסמבל",
	"DABEnsembleListTitle2" : "רשימת אנסמבל",
	"DABEnsembleListUpdateComplete" : "רשימת אנסמבל עודכנה",
	"DABFMLink" : "קישור DAB-FM",
	"DABLBand" : "רצועה L",
	"DABListNotAvailable" : "רשימת תחנות אינה זמינה",
	"DABNoResultsFound" : "לא נמצאו תוצאות",
	"DABNoSignal" : "אין אות",
	"DABPleaseUpdateList" : "אנא עדכן רשימה",
	"DABRadio" : "רדיו DAB",
	"DABRadioText" : "טקסט רדיו",
	"DABSelectEnsemble" : "בחירת אנסמבל",
	"DABSettings" : "הגדרות DAB",
	"DABSettingsListTitle" : "הגדרות",
	"DABSettingsNowPlaying" : "הגדרות DAB",
	"DABSignalLost" : "{ChNum} האות אבד",
	"DABSignalSearch" : "מחפש…",
	"DABStationListUpdateFailedSelect" : "אין אפשרות לעדכן רשימת תחנות",
	"DABStationListUpdated" : "רשימת תחנות עודכנה",
	"DABStatusBarTitle" : "DAB",
	"DABTrafficAlertOff" : "הודעת תנועה כבוי",
	"DABTrafficAlertOn" : "הודעת תנועה מופעל",
	"DABUnableToUpdateStationList" : "אין אפשרות לעדכ",
	"DABUpdate" : "עדכן",
	"DABUpdateEnsemble" : "האם לעדכן רשימת אנסמבל?",
	"DABUpdateEnsembleList" : "עדכן רשימת אנסמבל",
	"DABUpdateList" : "עדכן רשימה",
	"DABUpdateStation" : "האם לעדכן רשימת תחנות?",
	"DABUpdatingEnsembleList" : "מעדכן רשימת אנסמבל",
	"DABUpdatingList" : "מעדכן רשימה…",
	"DABUpdatingListNowPlaying" : "מעדכן רשימה…",
	"StationListTab" : "רשימת תחנות",
	"VrHelp_DABSettings" : "DAB Settings",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_Favorites" : "Favourites",
	"VrHelp_Next" : "Next",
	"VrHelp_Previous" : "Previous",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement  (TA)\u200e",
};

framework.registerAppDictLoaded("dab", "he_IL");