var Localization_dabAppDict_hu_HU = {
	//"stringId" : "localString"
	"DABAnalog" : "Analóg",
	"DABBandIII" : "III sáv",
	"DABBandSettingsList" : "Sávbeállítások",
	"DABBandSettingsTitle" : "Sávbeállítások",
	"DABBoth" : "Mindkettő",
	"DABChangeEnsemble" : "Változtassa meg az Áll. csoportot",
	"DABDABLink" : "DAB-DAB kapcsolat",
	"DABDigital" : "Digitális",
	"DABEnsembleList" : "Állomáscsoport-lista",
	"DABEnsembleListTitle" : "Válasszon Állomáscsoportot",
	"DABEnsembleListTitle2" : "Állomáscsoport-lista",
	"DABEnsembleListUpdateComplete" : "Az állomáscsoport-lista frissítve",
	"DABFMLink" : "DAB-FM kapcsolat",
	"DABLBand" : "L sáv",
	"DABListNotAvailable" : "Állomáslista frissítése nem áll rendelkezésre",
	"DABNoResultsFound" : "Nincs találat",
	"DABNoSignal" : "Nincs jel",
	"DABPleaseUpdateList" : "Frissítse a listát",
	"DABRadio" : "DAB rádió",
	"DABRadioText" : "Rádiószöveg",
	"DABSelectEnsemble" : "Válasszon Állomáscsoportot",
	"DABSettings" : "DAB beállítások",
	"DABSettingsListTitle" : "Beállítások",
	"DABSettingsNowPlaying" : "DAB beállítások",
	"DABSignalLost" : "{ChNum} Jel elveszett",
	"DABSignalSearch" : "Keresés folyamatban…",
	"DABStationListUpdateFailedSelect" : "Nem sikerült az lista eltávolítása",
	"DABStationListUpdated" : "Állomáslista frissítve",
	"DABStatusBarTitle" : "DAB",
	"DABTrafficAlertOff" : "Útinform (TA) ki",
	"DABTrafficAlertOn" : "Útinform (TA) be",
	"DABUnableToUpdateStationList" : "Nem sikerült az frissítése",
	"DABUpdate" : "Frissítés",
	"DABUpdateEnsemble" : "Frissíti?",
	"DABUpdateEnsembleList" : "Állomáscsoport-lista frissítése",
	"DABUpdateList" : "Frissítse a listát",
	"DABUpdateStation" : "Frissíti az állomáslistát?",
	"DABUpdatingEnsembleList" : "A lista frissítése folyamatban",
	"DABUpdatingList" : "Lista frissítése…",
	"DABUpdatingListNowPlaying" : "Lista frissítése…",
	"StationListTab" : "Állomáslista",
	"VrHelp_DABSettings" : "DAB Settings",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_Favorites" : "Favourites",
	"VrHelp_Next" : "Next",
	"VrHelp_Previous" : "Previous",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement  (TA)",
};

framework.registerAppDictLoaded("dab", "hu_HU");