var Localization_dabAppDict_hr_HR = {
	//"stringId" : "localString"
	"DABAnalog" : "Analogno",
	"DABBandIII" : "Band III",
	"DABBandSettingsList" : "BAND postavke",
	"DABBandSettingsTitle" : "BAND postavke",
	"DABBoth" : "Oba",
	"DABChangeEnsemble" : "Molimo promijenite ansambl",
	"DABDABLink" : "Veza DAB-DAB",
	"DABDigital" : "Digitalno",
	"DABEnsembleList" : "Popis stavki",
	"DABEnsembleListTitle" : "Odaberite ansambl",
	"DABEnsembleListTitle2" : "Popis stavki",
	"DABEnsembleListUpdateComplete" : "Ažuriran Popis ansambla",
	"DABFMLink" : "Veza DAB-FM",
	"DABLBand" : "L Band",
	"DABListNotAvailable" : "Nedostupan popis postaja",
	"DABNoResultsFound" : "Nisu pronađeni rezultati",
	"DABNoSignal" : "Nema signala",
	"DABPleaseUpdateList" : "Molimo ažurirajte popis",
	"DABRadio" : "DAB radio",
	"DABRadioText" : "Radiotekst",
	"DABSelectEnsemble" : "Odaberite ansambl",
	"DABSettings" : "Postavke DAB-a",
	"DABSettingsListTitle" : "Postavke",
	"DABSettingsNowPlaying" : "Postavke DAB-a",
	"DABSignalLost" : "{ChNum} Izgubljen signal",
	"DABSignalSearch" : "Traženje…",
	"DABStationListUpdateFailedSelect" : "Neuspjelo ažur. popisa postaja",
	"DABStationListUpdated" : "Ažuriran popis postaja",
	"DABStatusBarTitle" : "DAB",
	"DABTrafficAlertOff" : "Prometna objava (TA) isklj",
	"DABTrafficAlertOn" : "Prometna objava (TA) uklj",
	"DABUnableToUpdateStationList" : "Neuspjelo ažur.",
	"DABUpdate" : "Ažuriraj",
	"DABUpdateEnsemble" : "Ažurirati Popis ansambla?",
	"DABUpdateEnsembleList" : "Ažuriraj Popis ansambla",
	"DABUpdateList" : "Ažurirajte popis",
	"DABUpdateStation" : "Ažurirati popis postaja?",
	"DABUpdatingEnsembleList" : "Ažuriranje Popisa ansambla",
	"DABUpdatingList" : "Ažuriranje popisa…",
	"DABUpdatingListNowPlaying" : "Ažuriranje popisa…",
	"StationListTab" : "Popis postaja",
	"VrHelp_DABSettings" : "DAB Settings",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_Favorites" : "Favourites",
	"VrHelp_Next" : "Next",
	"VrHelp_Previous" : "Previous",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement  (TA)",
};

framework.registerAppDictLoaded("dab", "hr_HR");