var Localization_dabAppDict_de_DE = {
	//"stringId" : "localString"
	"DABAnalog" : "Analog",
	"DABBandIII" : "Band Ⅲ",
	"DABBandSettingsList" : "BAND-Einstellungen",
	"DABBandSettingsTitle" : "BAND-Einstellungen",
	"DABBoth" : "Beide",
	"DABChangeEnsemble" : "Bitte das Ensemble austauschen",
	"DABDABLink" : "DAB-DAB Link",
	"DABDigital" : "Digital",
	"DABEnsembleList" : "Ensembleliste",
	"DABEnsembleListTitle" : "Ensemble wählen",
	"DABEnsembleListTitle2" : "Ensembleliste",
	"DABEnsembleListUpdateComplete" : "Ensembleliste aktualisiert",
	"DABFMLink" : "DAB-FM Link",
	"DABLBand" : "L-Band",
	"DABListNotAvailable" : "Senderliste nicht verfügbar",
	"DABNoResultsFound" : "Nicht gefunden",
	"DABNoSignal" : "Kein Signal",
	"DABPleaseUpdateList" : "Bitte Liste aktualisieren",
	"DABRadio" : "DAB Radio",
	"DABRadioText" : "Radiotext",
	"DABSelectEnsemble" : "Ensemble wählen",
	"DABSettings" : "DAB-Einstellungen",
	"DABSettingsListTitle" : "DAB-Einstellungen",
	"DABSettingsNowPlaying" : "DAB-Einstellungen",
	"DABSignalLost" : "{ChNum} Signal verloren",
	"DABSignalSearch" : "Auf der Suche…",
	"DABStationListUpdateFailedSelect" : "Kann Senderliste nicht aktualisieren",
	"DABStationListUpdated" : "Senderliste aktualisiert",
	"DABStatusBarTitle" : "DAB",
	"DABTrafficAlertOff" : "Verkehrsmeldung (TA)  aus",
	"DABTrafficAlertOn" : "Verkehrsmeldung  (TA) an",
	"DABUnableToUpdateStationList" : "Kann nicht aktualisieren",
	"DABUpdate" : "Aktualisieren",
	"DABUpdateEnsemble" : "Ensembleliste aktualisieren?",
	"DABUpdateEnsembleList" : "Ensembleliste aktualisieren",
	"DABUpdateList" : "Liste aktualisieren",
	"DABUpdateStation" : "Senderliste aktualisieren?",
	"DABUpdatingEnsembleList" : "Aktualisierung der Ensembleliste",
	"DABUpdatingList" : "Liste wird aktualisiert…",
	"DABUpdatingListNowPlaying" : "Liste wird aktualisiert…",
	"StationListTab" : "Senderliste",
	"VrHelp_DABSettings" : "DAB-Einstellungen",
	"VrHelp_Entertainment" : "Unterhaltung",
	"VrHelp_Favorites" : "Favoriten",
	"VrHelp_Next" : "Nächster",
	"VrHelp_Previous" : "Vorheriger",
	"VrHelp_Scan" : "Abstimmen",
	"VrHelp_SoundSettings" : "Toneinstellungen",
	"VrHelp_StationList" : "Senderliste",
	"VrHelp_TrafficAnnouncement" : "Verkehrsmeldung (TA)",
};

framework.registerAppDictLoaded("dab", "de_DE");