var Localization_dabAppDict_cs_CS = {
	//"stringId" : "localString"
	"DABAnalog" : "Analogový",
	"DABBandIII" : "Pásmo Ⅲ",
	"DABBandSettingsList" : "Nastavení PÁSMA",
	"DABBandSettingsTitle" : "Nastavení PÁSMA",
	"DABBoth" : "Obě",
	"DABChangeEnsemble" : "Změňte repertoár",
	"DABDABLink" : "Propojení DAB_DAB",
	"DABDigital" : "Digitální",
	"DABEnsembleList" : "Seznam repertoáru",
	"DABEnsembleListTitle" : "Vybrat repertoár",
	"DABEnsembleListTitle2" : "Seznam repertoáru",
	"DABEnsembleListUpdateComplete" : "Seznam repertoáru aktualizován",
	"DABFMLink" : "Propojení DAB-FM",
	"DABLBand" : "Pásmo L",
	"DABListNotAvailable" : "Seznam stanic není k dispozici.",
	"DABNoResultsFound" : "Nebyl nalezen žádný výsledek",
	"DABNoSignal" : "Žádný signál",
	"DABPleaseUpdateList" : "Aktualizujte seznam, prosím",
	"DABRadio" : "Radio DAB",
	"DABRadioText" : "Rádiotext",
	"DABSelectEnsemble" : "Vybrat repertoár",
	"DABSettings" : "Nastavení DAB",
	"DABSettingsListTitle" : "Nastavení",
	"DABSettingsNowPlaying" : "Nastavení DAB",
	"DABSignalLost" : "Ztráta signálu kanálu č. {ChNum}",
	"DABSignalSearch" : "Vyhledávání…",
	"DABStationListUpdateFailedSelect" : "Nelze aktualizovat seznam stanic.",
	"DABStationListUpdated" : "Seznam stanic byl aktualizován",
	"DABStatusBarTitle" : "DAB",
	"DABTrafficAlertOff" : "Dopravní oznámení (TA) vypn.",
	"DABTrafficAlertOn" : "Dopravní oznámení (TA) zapn.",
	"DABUnableToUpdateStationList" : "Nelze aktualizovat seznam.",
	"DABUpdate" : "Aktualizovat",
	"DABUpdateEnsemble" : "Aktualizovat seznam?",
	"DABUpdateEnsembleList" : "Aktualizovat seznam",
	"DABUpdateList" : "Aktualizujte seznam",
	"DABUpdateStation" : "Aktualizovat seznam stanic?",
	"DABUpdatingEnsembleList" : "Aktualizace seznamu repertoáru",
	"DABUpdatingList" : "Aktualizace seznamu…",
	"DABUpdatingListNowPlaying" : "Aktualizace seznamu…",
	"StationListTab" : "Seznam stanic",
	"VrHelp_DABSettings" : "DAB Settings",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_Favorites" : "Favourites",
	"VrHelp_Next" : "Next",
	"VrHelp_Previous" : "Previous",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement  (TA)",
};

framework.registerAppDictLoaded("dab", "cs_CS");