var Localization_dabAppDict_sr_RS = {
	//"stringId" : "localString"
	"DABAnalog" : "Analogno",
	"DABBandIII" : "Band Ⅲ",
	"DABBandSettingsList" : "BAND postavke",
	"DABBandSettingsTitle" : "BAND postavke",
	"DABBoth" : "Oba",
	"DABChangeEnsemble" : "Promenite ansambl",
	"DABDABLink" : "DAB-DAB veza",
	"DABDigital" : "Digitalno",
	"DABEnsembleList" : "Lista ansambla",
	"DABEnsembleListTitle" : "Izaberi ansambl",
	"DABEnsembleListTitle2" : "Lista ansambla",
	"DABEnsembleListUpdateComplete" : "Lista ansambla je ažurirana",
	"DABFMLink" : "DAB-FM veza",
	"DABLBand" : "L Band",
	"DABListNotAvailable" : "Lista stanica nije dostupna",
	"DABNoResultsFound" : "Nema pronađenih rezultata",
	"DABNoSignal" : "Nema signala",
	"DABPleaseUpdateList" : "Molimo, ažurirajte listu",
	"DABRadio" : "DAB radio",
	"DABRadioText" : "Radio tekst",
	"DABSelectEnsemble" : "Izaberi ansambl",
	"DABSettings" : "DAB postavke",
	"DABSettingsListTitle" : "Postavke",
	"DABSettingsNowPlaying" : "DAB postavke",
	"DABSignalLost" : "Signal {ChNum} je izgubljen",
	"DABSignalSearch" : "Tražim …",
	"DABStationListUpdateFailedSelect" : "Ažuriranje liste stanica nije uspelo",
	"DABStationListUpdated" : "Lista stanica je ažurirana",
	"DABStatusBarTitle" : "DAB",
	"DABTrafficAlertOff" : "Obav. o stanju saobraćaja isklj.",
	"DABTrafficAlertOn" : "Obav. o stanju saobraćaja uklj.",
	"DABUnableToUpdateStationList" : "Ažuriranje nije uspelo",
	"DABUpdate" : "Ažuriraj",
	"DABUpdateEnsemble" : "Želite li ažurirati listu ansambla?",
	"DABUpdateEnsembleList" : "Ažuriraj listu ansambla",
	"DABUpdateList" : "Ažurirajte listu",
	"DABUpdateStation" : "Želite da ažurirate listu stanica?",
	"DABUpdatingEnsembleList" : "Ažuriranje liste ansambla",
	"DABUpdatingList" : "Ažuriranje liste…",
	"DABUpdatingListNowPlaying" : "Ažuriranje liste…",
	"StationListTab" : "Lista stanica",
	"VrHelp_DABSettings" : "DAB Settings",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_Favorites" : "Favourites",
	"VrHelp_Next" : "Next",
	"VrHelp_Previous" : "Previous",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement  (TA)",
};

framework.registerAppDictLoaded("dab", "sr_RS");