var Localization_dabAppDict_id_ID = {
	//"stringId" : "localString"
	"DABAnalog" : "Analog",
	"DABBandIII" : "Pita III",
	"DABBandSettingsList" : "Pengaturan Pita",
	"DABBandSettingsTitle" : "Pengaturan Pita",
	"DABBoth" : "Keduanya",
	"DABChangeEnsemble" : "Ubah Ansambel",
	"DABDABLink" : "Tautan DAB-DAB",
	"DABDigital" : "Digital",
	"DABEnsembleList" : "Daftar Ansambel",
	"DABEnsembleListTitle" : "Pilih Ansambel",
	"DABEnsembleListTitle2" : "Daftar Ansambel",
	"DABEnsembleListUpdateComplete" : "Daftar Ansambel Diperbarui",
	"DABFMLink" : "Tautan DAB-FM",
	"DABLBand" : "Pita L",
	"DABListNotAvailable" : "Daftar Stasiun Tidak Tersedia",
	"DABNoResultsFound" : "Tidak ada hasil yang ditemukan",
	"DABNoSignal" : "Tidak Ada Sinyal",
	"DABPleaseUpdateList" : "Perbarui daftar",
	"DABRadio" : "Radio DAB",
	"DABRadioText" : "Teks Radio",
	"DABSelectEnsemble" : "Pilih Ansambel",
	"DABSettings" : "Pengaturan DAB",
	"DABSettingsListTitle" : "Setelan",
	"DABSettingsNowPlaying" : "Setelan",
	"DABSignalLost" : "{ChNum} Sinyal Terputus",
	"DABSignalSearch" : "Mencari. . .",
	"DABStationListUpdateFailedSelect" : "Tidak Dapat Memperbarui Daftar Stasiun",
	"DABStationListUpdated" : "Daftar Stasiun Diperbarui",
	"DABStatusBarTitle" : "DAB",
	"DABTrafficAlertOff" : "Pemberitahuan Lalu-Lintas (TA) non aktif",
	"DABTrafficAlertOn" : "Pemberitahuan Lalu-Lintas (TA) aktif",
	"DABUnableToUpdateStationList" : "Tidak Dapat Memperbarui Daftar",
	"DABUpdate" : "Perbarui",
	"DABUpdateEnsemble" : "Perbarui Daftar Ansambel?",
	"DABUpdateEnsembleList" : "Perbarui Daftar Ansambel",
	"DABUpdateList" : "Update List",
	"DABUpdateStation" : "Perbarui Daftar Stasiun?",
	"DABUpdatingEnsembleList" : "Memperbarui daftar Ansambel",
	"DABUpdatingList" : "Memperbarui Daftar. . .",
	"DABUpdatingListNowPlaying" : "Memperbarui Daftar...",
	"StationListTab" : "Station List",
	"VrHelp_DABSettings" : "DAB Settings",
	"VrHelp_Entertainment" : "Entertainment",
	"VrHelp_Favorites" : "Favourites",
	"VrHelp_Next" : "Next",
	"VrHelp_Previous" : "Previous",
	"VrHelp_Scan" : "Scan",
	"VrHelp_SoundSettings" : "Sound Settings",
	"VrHelp_StationList" : "Station List",
	"VrHelp_TrafficAnnouncement" : "Traffic Announcement",
};

framework.registerAppDictLoaded("dab", "id_ID");